### ISSUE TITLE
Hero's shadow shouldn't lay on mountains, while hero moving behind mountains

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1004]
While moving behind mountains we can still watch shadow covering this mountains.
![shadow](https://user-images.githubusercontent.com/55348946/87133438-fd17b780-c29f-11ea-8684-b81ed55a1b7c.jpg)
[Shadow over mountains.zip](https://github.com/ihhub/fheroes2/files/6246015/Shadow.over.mountains.zip)
[Shadow over mountains 2.zip](https://github.com/ihhub/fheroes2/files/6246018/Shadow.over.mountains.2.zip)

**Comment by ihhub** [comment]
This issue relates to #772

**Comment by Branikolog** [comment]
Not sure this is the same issue. Shadow from hero is drawn good. But it shouldn't be, because hero is behind mountains. When hero is in front of mountains - everything is ok.

**Comment by ihhub** [comment]
It's the same in terms on source code :)

**Comment by ihhub** [comment]
Hi @idshibanov , did we fix this with map changes?

**Comment by idshibanov** [comment]
@ihhub Not the hero redraw, probably not.
