### ISSUE TITLE
Unit with "haste" and "slow" spells should change its moving speed  over battlefield

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1011]
Unit moves faster, when we cast "haste" and slower, when we cast "slow"  in the OG. We need to adjust moving speeds to the unit having spell effect.

**Comment by ihhub** [comment]
We need to know how fast or slow the unit should move in this case. 25% faster/slower?

**Comment by Branikolog** [comment]
@ihhub 
Unfortunately, I don't know exactly... I even cannot say if both of this animations should change speed in the same grade...
To me it seemes like 20%...
