### ISSUE TITLE
Neutral creatures remain alive after hero lost or run away from a battle

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1012]
Hero disappears after using "Storm" spell and dying. Quantity of creatures he fought remains the same.

**Comment by ihhub** [comment]
Hi @Branikolog , could you please attach a save file for this situation and give clear explanation of the issue? I don't really understand what you mean.

**Comment by Branikolog** [comment]
If we use mass spell "Elemental Storm" (or Armageddon, i suppose) in a battle against neutral creatures, till hero army dies, neutral creatures remain at the same place with full quantity (like no battle happened). But hero disappears.
[Last.zip](https://github.com/ihhub/fheroes2/files/4906670/Last.zip)

**Comment by Branikolog** [comment]
Well, actually neutral creature quantity doesn't change after battle at all, if hero hadn't managed to win the battle.

**Comment by Branikolog** [comment]
Also I should mention here, that hero can be hired in a tavern later with the army, he had before casting "Elemental Storm" spell, (Or any other mass spell that killed all hero army)
