### ISSUE TITLE
2-hex flying creatures under Berserk spell don't do anything

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#1017]
Apply Berserk spell over 2-hex flying creature like Phoenix or Roc and observe that it doesn't move:
![image](https://user-images.githubusercontent.com/19829520/87241359-f7af9e00-c454-11ea-8e18-bdb4d2b8adeb.png)

The bug is only for such type of creatures.

**Comment by Branikolog** [comment]
Currently, berserk doesn't work as it supposed to. Enemy creatures don't want to attack allies and AI continues to attack player's creatures.
