### ISSUE TITLE
Write a script to automatically delete old releases from Github releases

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#102]
We have deployment of releases on [Travis-CI](https://travis-ci.org/ihhub/fheroes2) platform for Linux and OSX. We deploy a new package for every commit into **master** branch. We face a problem that we have many releases in [Github releases](https://github.com/ihhub/fheroes2/releases). For each commit we create 4 tags (they are done in parallel):
```
fheroes2-linux-sdl1-<build id>
fheroes2-linux-sdl2-<build id>
fheroes2-osx-sdl1-<build id>
fheroes2-osx-sdl2-<build id>
```

The potential script which accepts as an input parameter a name (prefix) will list all tags with this prefix and remove all releases and tags **except last 5** (before deploying a new). API token for Github releases is stored in `$GITHUB_OAUTH_TOKEN` environment variable. This script could be a part of `.travis.yaml` file as well.

This is [description](https://developer.github.com/v3/repos/releases/#delete-a-release) of how to delete GitHub release via GitHub API.

**Comment by mahasak** [comment]
Can i take this one ? I want to try working with Travis (I'm usually use TeamCity/Jenkins). This sounds to be a good start for this year hactober :D

**Comment by ihhub** [comment]
Hi @mahasak sure! Please ask any questions if you need any help.

**Comment by ihhub** [comment]
By the way, you could try #37 as well for AppVeyor.

**Comment by ihhub** [comment]
Hi @mahasak , have you started working on this issue? It seems like it's very important to create some script now as we have a lot of commits. Removing files manually is a frustration :(

**Comment by ihhub** [comment]
This is command to remove release `DELETE https://api.github.com//repos/:owner/:repo/releases/:release_id`.

**Comment by ihhub** [comment]
@mahasak I tested to use GitHub Authorization token and Travis-CI doesn't allow to do such. So what we need is to create a script which would accept 2 parameters: `token` and `tag_prefix`. The script will list all releases by `curl -H "Authorization: token TOKEN" https://api.github.com/repos/ihhub/fheroes2/releases` in JSON format. We need to find all releases whose tag starts from `tag_prefix`, delete them by `curl -X DELETE -H "Authorization: token TOKEN" "https://api.github.com/repos/ihhub/fheroes2/releases/RELEASE_ID"` and delete it's tag as well.

**Comment by bjauny** [comment]
Would it be OK to keep tagging each complete master job but only have one release (overwriting the archives each time)?
This way we're able to reach each integration step if need be (via the tags) and we only keep the latest stable state archives.

**Comment by ihhub** [comment]
I'm thinking to keep using just on release (from master branch as development release). In such case we would always have only 6 releases unless we add some releases later, for example, as monthly release.

**Comment by ihhub** [comment]
It's done. Now we need to do for AppVeyor.
