### ISSUE TITLE
Add proper credits in the Main Menu

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#1021]
Right now we have very silly credits which don't include all contributors and needed information about the project:
![image](https://user-images.githubusercontent.com/19829520/87268927-5846e580-c4fe-11ea-9711-1c0cd7ca9644.png)

For comparison these are credits from the original game:
![image](https://user-images.githubusercontent.com/19829520/87268957-74e31d80-c4fe-11ea-9cbe-fbbe4876cfae.png)

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

Currently, the expansion credits are missing.

In Heroes 2 Gold:

Actual credits:

![Expansion credits 003](https://user-images.githubusercontent.com/43583994/142189079-3543e5e7-e891-4dc3-9e57-ec15487d8330.png)

Missing credits:

![Expansion credits 001](https://user-images.githubusercontent.com/43583994/142189122-27187ad2-e8fa-4a13-bfae-f6df45e0390e.png)

![Expansion credits 002](https://user-images.githubusercontent.com/43583994/142189132-a44967b7-8d14-414d-92ad-f498b38fd6c0.png)
