### ISSUE TITLE
Number in creature counter during battle is shifted to right

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1023]
All two-digit numbers in creature counter are not centered.
![Counter](https://user-images.githubusercontent.com/55348946/87292713-e4aad580-c509-11ea-8d96-a8f70dfc948d.jpg)

**Comment by idshibanov** [comment]
@Branikolog It is quite unfortunate but unit counter bar is only 20 pixels wide when text inside is 9 pixels wide (4 for each digit, 1 for spacing). That leaves you with uneven number of pixels on each side, you can't center it. It will be either leaning to the right or left depending on how you round it.

Black dots to visualize the pixels:
![image](https://user-images.githubusercontent.com/1373638/87327446-115aef00-c502-11ea-8506-0d2f96c694ee.png)

This is how it looks rounded down (resulting in shift 1 pixel to the left):
![image](https://user-images.githubusercontent.com/1373638/87327269-da84d900-c501-11ea-81c0-ea05afadfbd1.png)

I prefer how it is right now.

**Comment by Branikolog** [comment]
It is terrible news, @idshibanov! I haven't thought it would be such an unsolvable problem...
We should think about this problem in future... For now I leave "beyond 1.0" state for it...

**Comment by ihhub** [comment]
This problem is unsolvable since it requires different sizes of "counter" image. I'm closing this issue as invalid.
