### ISSUE TITLE
Updating project labels

### ISSUE THREAD

**Issue by idshibanov** [ihhub/fheroes2#1024]
- **GUI**: I think it's a catch-all right now that has too many issues tagged. I think we should split this in two: actual UI issues and graphical ones (can't think of better name).
- **Regression**: tagging sub-type of the bug that was caused by recent code change. It is useful for the future tracking.
- **Audio** and **sound**: I think we should combine the two.
- **Deployment**, AppVeyor and Travis-CI: can we combine those as well? I don't think there will be many issues/PRs related.

Anything else?

**Comment by ihhub** [comment]
Hi @idshibanov , I updated some labels based on your input. Something I didn't touch for now.
