### ISSUE TITLE
Update MP2, tile and map code to use extra data available

### ISSUE THREAD

**Issue by idshibanov** [ihhub/fheroes2#1026]
While working on #1025 I found out that map object IDs is a huge mess right now. There's a big confusion between MP2 objects (with unnecessary distinction of OBJ and OBJN), ICN files and indexes, map objects and addon objects stacked together.

We're losing significant information contained in bitfields (interactivity, animation, frames, shadows, roads) with the current MP2 parser and map initialization. A lot of hacks exist in the code right now like `ICN::AnimationFrame()` with long switch cases where I find errors and omissions. `Tiles/TilesAddon` classes need some work as well.

This is relatively big 0.9 task on it's own however I see few things to discuss here:
1. Updating map structures is important, but that will kill compatibility with 0.7 and 0.8 save format. Repeating my question again: is it worth fixing the saves after refactor or no?
2. If we ditch the compatibility then I would be glad to refactor Point and Size classes here to move on from 16bit variables. There's too many warnings related to this in the code.
3. What's the best strategy handling bitfields? Is it worth moving them into dedicated booleans or we'll use bitwise logic? Do you care about memory costs (each map tile + addons can add up in the end). Memory costs of bigger Point class also can be discussed here.

**Comment by ihhub** [comment]
Hi @idshibanov ,

1. It's not worth fixing old saves. Our user base is insignificant for now.
2. I'm fine to change these classes. I can create template based version of it and concrete implementations to ease work.
3. We could use bit field class from STL. Most of memory is eaten by graphics so no need to worry much about boolean variables for now.

Also we need to get some place for discussions like Discord or Slack.

**Comment by ihhub** [comment]
I checked random castle related pull request: we can use boolean variables and convert 13 bits into `uint16_t` value with bit shift by 3.

**Comment by idshibanov** [comment]
> Also we need to get some place for discussions like Discord or Slack.

@ihhub I fully agree, it will be much easier to coordinate and ask one-off questions there :) I used Slack in the past but for me Discord will be preferable, straightforward to manage. We could easily add github webhook there.

I created new Discord server https://discord.gg/BreEUrh if that's okay.
