### ISSUE TITLE
Question about path penalty

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1028]
Playing current version of our game i have a few questions regarding paths and penalty behavior.
Does current indication of terrain penalty, which we can see by right click over land near hero, correct?
If so, what is the difference between straight and diagonal hero movement?
![roadss](https://user-images.githubusercontent.com/55348946/87425089-bbf80e00-c5e5-11ea-90ca-e8782d34d987.jpg)
![roadss2](https://user-images.githubusercontent.com/55348946/87425095-bdc1d180-c5e5-11ea-9173-3dbfab1ec9ab.jpg)
Why does game shows different penalty when hero stands close to the road turning ?
![Roads](https://user-images.githubusercontent.com/55348946/87425282-0a0d1180-c5e6-11ea-9502-a5aef3cafdb2.jpg)
![Roads1](https://user-images.githubusercontent.com/55348946/87425285-0bd6d500-c5e6-11ea-9980-36cf247af197.jpg)

**Comment by idshibanov** [comment]
Diagonal move costs 1.5 times as much, this is how it was supposed to be. Road movement is 75 always (112 diagonal). If you see 150 there it's either not detecting road or the info dialog (which is more likely) is wrong.

**Comment by Branikolog** [comment]
If info is wrong it should be corrected or simply turned off. To stop confusing players. )
In the OG there's no such feature at all.
