### ISSUE TITLE
All animations stop while casting "Dimension Door" spell

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1039]
All animations on a world map shouldn't stop while using "Dimension Door" spell. 
![DD range3](https://user-images.githubusercontent.com/55348946/87544462-27f27900-c6af-11ea-810e-e90bbde5a617.jpg)

**Comment by ihhub** [comment]
Setting this issue to 1.0 as we are not going to add such feature for 0.8 release.
