### ISSUE TITLE
Music stops playing during the AI turn, after enemy has made any battle

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1051]
When AI hero fights anyone music stops.
Also, I'm curious, if we have any music theme for AI turn. As during AI turn always plays last theme, we can hear during player turn.

**Comment by idshibanov** [comment]
There's 42 full tracks on CD and only 17 MIDI versions exist in data files, AI theme is missing too. We need CD support for that or external music file. In original it usually stays silent during the turn.

**Comment by Branikolog** [comment]
I think silence - is not a choice. Better continue current soundtrack till the end of AI turn.
Or at least silence shouldn't happen after a certain condition.

**Comment by ihhub** [comment]
What will happen if player's hero for which the soundtrack is being played was defeated by AI? Which soundtrack do we need to choose?

**Comment by Branikolog** [comment]
I think, no matter, what happened during AI turn, soundrtack shouldn't change till the end of AI turn. We should simply play single composition...

**Comment by Branikolog** [comment]
With the original CD soundtrack, music still stops, after AI hero attacks anyone. Until the moment another hero starts moving.

**Comment by Branikolog** [comment]
Hi, @idshibanov. Here's the savegame for this issue. Yellow AI attacks my hero, and after battle we we cannot hear any music, until my turn starts.
[Music issue.zip](https://github.com/ihhub/fheroes2/files/4970556/Music.issue.zip)

**Comment by idshibanov** [comment]
> 
> Hi, @idshibanov. Here's the savegame for this issue. Yellow AI attacks my hero, and after battle we we cannot hear any music, until my turn starts.

Ahhh, got you. In this case music stops to play the battle track and then does not resume after. Not really related to AI, rather than general issue of not restarting music.

Thanks for the save, will correct.

**Comment by Branikolog** [comment]
You are welcome. Hope, you'll get over this issue easily.
