### ISSUE TITLE
Sea sound is missing

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1052]
When hero sails far from coast, we cannot hear any sound, even seawaves. It is quite weird, to ride boat in silence.
![Sail music](https://user-images.githubusercontent.com/55348946/87644656-11066200-c755-11ea-975b-7c003fc7511d.jpg)

Also, when we switch between any hero and hero, that sails deep in sea - we continue listening soundtrack of a terrain, switched hero stands on.
Also, I'm curious, if we have any special music theme for sea, besides seawaves' sound, we can hear close to coast.

**Comment by idshibanov** [comment]
Same thing as in previous ticket. Music for Ocean, Wasteland and Beach terrain is missing in MIDI files (as well as Sorceress castle and 20 other things).

**Comment by Branikolog** [comment]
Sad news... 
Can we at least make sewaves' sounds playing during any sailing activity? That silence makes me feel uncomfortable.) 
Or your suggestion is to forget about this issue till we implement CD music in our game?

**Comment by idshibanov** [comment]
I can fix up the .ogg music support from GOG version of the game (I have the copy) to make sure it runs smooth in our version. Full CD support is already a part of another ticket but I wasn't planning to do it now.

**Comment by ihhub** [comment]
Let's add a support of ogg music for 0.9.

**Comment by idshibanov** [comment]
> 
> 
> Let's add a support of ogg music for 0.9.

I did it anyway since it was a quick one :) let's plan CD support for 0.9 instead.

**Comment by Branikolog** [comment]
I'm waiting with anticipation the moment I can enjoy original non-midi music in the game....
