### ISSUE TITLE
Hero rises scepter too slowly, while casting a spell

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1057]
Comparing to the OG hero rises his hand too slowly, while spell cast.
![Cast](https://user-images.githubusercontent.com/55348946/87796238-c1f22700-c851-11ea-87c7-997f423faa22.jpg)

**Comment by idshibanov** [comment]
Wizard and Necromancer heroes have more animation frames than others. As a fun fact everything related to Wizard or Necromancer looks different in the game files and probably was drawn much later in the game development, because they ported first 4 castles straight from Heroes 1 :)

To solve this we might take advantage of `TimedSequence` class instead of `AnimationSequence` to make sure total animation time is the same regardless of the frame count.

**Comment by Branikolog** [comment]
> Wizard and Necromancer heroes have more animation frames than others. As a fun fact everything related to Wizard or Necromancer castles looks different in the game files and probably was drawn much later in the game development, because they ported first 4 castles straight from Heroes 1 :)

Curious fact.)

> 
> To solve this we might take advantage of `TimedSequence` class instead of `AnimationSequence` to make sure total animation time is the same regardless of the frame count.

I'm not sure, that all hero animations should last the same time, but rising scepter (during "Holy Shout" spell for example) is way too slow. :)

**Comment by ihhub** [comment]
Hi @Branikolog , is this issue still reproducible?

**Comment by Branikolog** [comment]
@ihhub 
In the OG Sorceress animation of spellcasting is much more smooth. It seems to have even more frames, than currently we can watch in fheroes2.
There's certainly an issue with hero animation in fheroes2.

**Comment by ihhub** [comment]
Hi @Branikolog , is it still the case? @Districh-ru  fixed hero's animation in the past.

**Comment by Branikolog** [comment]
Hello, @ihhub !
I'm sorry for such a late response.

I still see issues with hero animation while casting:
OG (minimum battle speed (normal)):

https://github.com/ihhub/fheroes2/assets/55348946/0d9c9a72-5334-4f57-91ca-ce73c3004d58

fheroes2 (5 battle speed):

https://github.com/ihhub/fheroes2/assets/55348946/04e447e2-229f-4023-b707-d29c06f3d949

As you can see, first half of hero animation in fheroes2 looks slower, while the second part looks quite close to the OG.

For sorceress heroes :
OG:

https://github.com/ihhub/fheroes2/assets/55348946/51e5b24c-be45-4e8b-90e7-77ac55fa9060

fheroes2:


https://github.com/ihhub/fheroes2/assets/55348946/c4f98d48-cd4d-47da-8a22-ded77fb2ca3e
