### ISSUE TITLE
World map scroll doesn't work correctly

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#106]
If user moves mouse out of window logically we should not scroll world map in game but we do which seems like incorrect behavior.

On this screenshot I actually moved mouse out of window but game still keeps scrolling (right center side of screenshot contains arrow):
![image](https://user-images.githubusercontent.com/19829520/66051612-bf903c00-e561-11e9-99de-2287fa3d348c.png)

**Comment by kgorecki** [comment]
I’m on it!

**Comment by andrey-starodubtsev** [comment]
Also scroll interrupts hero's movement.

**Comment by kgorecki** [comment]
@ihhub shall we handle scroll interruption? I can't check original version. How does it work there?
btw. I fixed it, but it needs some refactoring still. I'll push it as soon as it's refactored.

**Comment by ihhub** [comment]
The root of the problem is in `int Interface::Basic::HumanTurn( bool isload )` function:
```cpp
        // fast scroll
        if ( gameArea.NeedScroll() && Game::AnimateInfrequentDelay( Game::SCROLL_DELAY ) ) {
            cursor.Hide();

            if ( le.MouseCursor( GetScrollLeft() ) || le.MouseCursor( GetScrollRight() ) || le.MouseCursor( GetScrollTop() ) || le.MouseCursor( GetScrollBottom() ) )
                cursor.SetThemes( gameArea.GetScrollCursor() );

            gameArea.Scroll();

            // need stop hero
            if ( GetFocusHeroes() && GetFocusHeroes()->isEnableMove() )
                GetFocusHeroes()->SetMove( false );

            gameArea.SetRedraw();
            radar.SetRedraw();
            Redraw();
            cursor.Show();
            display.Flip();

            // enable right click emulation
            if ( conf.ExtPocketTapMode() )
                le.SetTapMode( true );

            continue;
        }
```

He have an explicit code to stop hero's movement. This we can remove. We need to delay moving map window for some time before actually doing this.
