### ISSUE TITLE
Disable Continue Movement button for a hero which doesn't have chosen path

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#107]
We must disable **Continue Movement** button if chosen hero doesn't have path to move. Here is a screenshot of current application:
![image](https://user-images.githubusercontent.com/19829520/66051834-21e93c80-e562-11e9-8a56-59898f224ce7.png)

and here is a screenshot of correct behavior:
![image](https://user-images.githubusercontent.com/19829520/66051862-2f062b80-e562-11e9-8ab9-fee65d4276a3.png)

**Comment by kgorecki** [comment]
I'll take this one if it's free

**Comment by ihhub** [comment]
Sure!
