### ISSUE TITLE
"Resurrect" spell animation is missing

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1073]
There are spinning waves inside dark circle in the OG.
![Ressurect](https://user-images.githubusercontent.com/55348946/87870957-5923bf80-c9b5-11ea-8e13-7e5e88c25468.jpg)
Our version has none.
![Ressurect2](https://user-images.githubusercontent.com/55348946/87870981-7d7f9c00-c9b5-11ea-9559-3d97a36c5da2.jpg)

**Comment by ihhub** [comment]
We can't do this with current implementation of drawings.

**Comment by idshibanov** [comment]
> 
> We can't do this with current implementation of drawings.

Okay, I looked at the ICN graphics for this spell and fully agree. Let's move this to 0.9, I think it's doable after we implement new rendering logic.

**Comment by Branikolog** [comment]
Okay. Let's hold off this issue for a while.
