### ISSUE TITLE
Mud pool on a lava battlefield

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1075]
Fighting on lava battlefield I've noticed a mud pool witch doesn't suit this terrain. Also it is lacking animation of bubbles on it...
In the OG i couldn't met such object on this type of battlefield.
Is everything okay with this object? Shall we continue using it on this type of terrain? Can we make any animation to it?
![dust](https://user-images.githubusercontent.com/55348946/87871630-642d1e80-c9ba-11ea-873d-3a64188f9970.jpg)

**Comment by idshibanov** [comment]
This is a one of the few unused objects that were added back in fheroes2 a long time ago. There's no animation or cycling for it. We can just remove it from the list if it doesn't fit at all.
