### ISSUE TITLE
Only half of a farm is drawn in Knight city without castle 

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1080]
We should draw missing part of field, that is located behind the castle.
![Farm](https://user-images.githubusercontent.com/55348946/87874624-f42b9200-c9d3-11ea-9f62-78b0adb006b4.jpg)

**Comment by idshibanov** [comment]
Reminder: there's no sprite or graphics for it. Here you would need an artist to draw a new pixel art.
