### ISSUE TITLE
"EXIT" button in a city should have "inactive" status

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1085]
"EXIT" button in a city window should change to "unactive" status while entering recruit window; build window while choosing any building; hero hiring window; market window.
![Exit button](https://user-images.githubusercontent.com/55348946/87928432-7cba3900-ca8d-11ea-842b-9db9d8727339.jpg)

**Comment by ihhub** [comment]
This is how it look in the original game:
![image](https://user-images.githubusercontent.com/19829520/87933329-a12f0900-cabf-11ea-874f-b6df7324c851.png)
![image](https://user-images.githubusercontent.com/19829520/87933408-c3c12200-cabf-11ea-8dcf-5dc57d82710a.png)

The only time when the button becomes disabled when we select a building to build:
![image](https://user-images.githubusercontent.com/19829520/87933447-d9364c00-cabf-11ea-867c-26aa46b13369.png)

**Comment by Branikolog** [comment]
![Recruit2](https://user-images.githubusercontent.com/55348946/87933718-73819a00-ca96-11ea-8b2a-e40d57fed9a7.jpg)
I think it should be done for all cases, where exit button couldn't be pressed... As it was done for more, than one....
