### ISSUE TITLE
Captains Quarters to build image is incorrect 

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#109]
If a town has not built captains quarters you could go to town building and see the icon for it. This is how it looks like with current version of game (and with right clicked button):
![image](https://user-images.githubusercontent.com/19829520/66053146-5b22ac00-e564-11e9-8e5f-eff6793e24b3.png)

and this is how it should be:
![image](https://user-images.githubusercontent.com/19829520/66053169-683f9b00-e564-11e9-8467-595464fef461.png)

We have to display building, not captain itself.

**Comment by euronay** [comment]
Hi, I think I have fixed this - see PR - It's my first time writing C++ so I'm figuring out a bunch of things! I hope it's OK. Happy Hacktoberfest 🎃!

**Comment by ihhub** [comment]
Hi @euronay , I'll check this how it works. I think I was having another solution :)
