### ISSUE TITLE
Pressed MAX/MIN button in troop separation window has wrong background

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1090]
![Sepa](https://user-images.githubusercontent.com/55348946/87933467-fa824280-ca95-11ea-9eb1-ace9f75614ba.jpg)

**Comment by Branikolog** [comment]
Also, it is brown in "evil" interface:
![Separate troop MAX](https://user-images.githubusercontent.com/55348946/88709765-48deb380-d11e-11ea-8331-a7bb2a0416ce.jpg)

**Comment by LeHerosInconnu** [comment]
Even when the "MAX" button is not pressed, there is a graphic defect around the button.
Same for the "MIN" button.

In fheroes2:

![Max min default fh2 01](https://user-images.githubusercontent.com/43583994/101723080-dd352b80-3aab-11eb-8554-97718e26b240.png)

![Max min default fh2 02](https://user-images.githubusercontent.com/43583994/101723086-df978580-3aab-11eb-843b-a639c73d39bd.png)

![Max min default fh2 03](https://user-images.githubusercontent.com/43583994/101723090-e0c8b280-3aab-11eb-975c-04ed2fde0e3c.png)

**Comment by ihhub** [comment]
Closing this issue as it was fixed some time ago.
