### ISSUE TITLE
Sensitive area does not stretching on SDL2 build after switching to fullscreen

### ISSUE THREAD

**Issue by shprotru** [ihhub/fheroes2#1091]
Sensitive area does not stretching on `SDL2` build after switching to fullscreen:
https://vimeo.com/439800009
changing `SDL_WINDOW_FULLSCREEN_DESKTOP` to `SDL_WINDOW_FULLSCREEN` will bring this:
https://vimeo.com/439891880

**Comment by ihhub** [comment]
Hi @shprotru , could you please take a look into [this code](https://github.com/vcmi/vcmi/blob/12a4cee09207508cec15e9527e334eb15f38a68c/client/CMT.cpp). Maybe we can solve the issue.
