### ISSUE TITLE
Barbarian castle well animation problems

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1094]
I've noticed a bunch of problem with animations in barbarian well:
Goblins shift back a little after moving animation stops;
The same seemed to do Orc Chiefs.
Ogres have little shifting to left, right before walking animation starts.
This also happens, while walking animation stops.
Walking animation seem to be shifted for lots of creatures in well.

**Comment by Branikolog** [comment]
Hi, @ihhub. Could you please look into code, relating this? I believe, this is not only for this castle. I'm still investigating the problem in others... Unicorns seemed to have similar problem... I'm talking about shifting while movement...

**Comment by Branikolog** [comment]
Also look at swordsmen animation. Seemed to have the same problem as goblins.

**Comment by ihhub** [comment]
Wolves are fixed in #1111
