### ISSUE TITLE
Animation goes out of city well window

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1095]
Cyclops' low-hex double-creature attack goes out of window.
![cyclops](https://user-images.githubusercontent.com/55348946/88031340-227caf00-cb45-11ea-86e9-8b32ff13f219.jpg)

**Comment by Branikolog** [comment]
@idshibanov, hello. Could you look at this problem, please? I believe it is related to #815, you've recently worked on.

**Comment by Branikolog** [comment]
The same with Phoenixes:
![phoenix](https://user-images.githubusercontent.com/55348946/88031980-00cff780-cb46-11ea-9337-2a8aad23754d.jpg)

**Comment by idshibanov** [comment]
Yes, this is not castle or creature related. Monster were not supposed to be animated there and would never fit in the window. We need to add a new surface to draw on to make sure sprites don't go over window limits.

**Comment by ihhub** [comment]
To simplify work we need to use an extra Sprite only for well animation. The rest of the city's graphics is okay.
