### ISSUE TITLE
Some parts of ship can be seen through terrain objects

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1103]
![Boat ass](https://user-images.githubusercontent.com/55348946/88177099-fb031080-cc30-11ea-9dc5-84f61737c1a7.jpg)

**Comment by ihhub** [comment]
relates to #1038

**Comment by LeHerosInconnu** [comment]
Another save for this.

In fheroes2:

![Boat in mountains fh2 01](https://user-images.githubusercontent.com/43583994/116011738-cb9d8c00-a626-11eb-9099-6872e01cd212.png)

Here is the save file:
[Boat mountains 01.zip](https://github.com/ihhub/fheroes2/files/6373324/Boat.mountains.01.zip)

**Comment by LeHerosInconnu** [comment]
Another save for the same problem.

In fheroes2:

![Boat sprite through mountains 01](https://user-images.githubusercontent.com/43583994/136039651-15847bf9-cb84-4c37-95e4-28cd1bdd327a.png)

Here is the save file (0.9.7 4306):
[Boat mountains 01.zip](https://github.com/ihhub/fheroes2/files/7286515/Boat.mountains.01.zip)
