### ISSUE TITLE
Horse of Necromant hero is missing glowing eyes and nostrils effect

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1114]
In the OG the eyes and nostrils of a horse on a battlefield are glowing with evil red color.
![Devil Eyes](https://user-images.githubusercontent.com/55348946/88369372-86e37c80-cd98-11ea-8e6f-4f300aaf4eef.jpg)

**Comment by idshibanov** [comment]
Will be done together with #724.
