### ISSUE TITLE
In-game resolution change issues #2

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1131]
When I set ex:1280x1024 resolution, and try to change it to another 1280x** - nothing happens. Only when I choose resolution with not 1280, i can change then to any 1280x* resolution. So when we change between two resolutions, where one of values is the same - nothing happens.

Also... I'm just curious... Can screen resolution value be saved? Currently, when we start client, each time we have default 640x480...

And... Are we seriously going to support low resolutions?)
![Resolution](https://user-images.githubusercontent.com/55348946/88466062-505d4d00-ced1-11ea-9550-b93b3ed4deeb.jpg)

**Comment by Branikolog** [comment]
Also, when we set any resolution **x1050 game runs in a fulscreen mode like this:
![Resolution2](https://user-images.githubusercontent.com/55348946/88466363-41c46500-ced4-11ea-9311-14c99a0764cd.jpg)

**Comment by Branikolog** [comment]
Do we really need resolutions with difference in 6 pixels?
![Resolution3](https://user-images.githubusercontent.com/55348946/88466403-936cef80-ced4-11ea-89ab-6871b989b2cd.jpg)

**Comment by idshibanov** [comment]
> Do we really need resolutions with difference in 6 pixels?

Resolutions list is auto-generated depending on screen of your computer. I think it is the same one as in your OS settings (at least on Windows). I only got 9 options for example.

> Also... I'm just curious... Can screen resolution value be saved? Currently, when we start client, each time we have default 640x480...
Already reported as #723 . Before that feature is done you have to update fheroes2.cfg file. I agree that it should be higher priority than 1.0.

**Comment by idshibanov** [comment]
> Also, when we set any resolution **x1050 game runs in a fullscreen mode like this:

Are you talking about image stretching in the main menu? Can't do much about the image itself. We might have to add black borders on both sides to correct.

**Comment by ihhub** [comment]
Here I see multiple problems. Let's separate them:
- don't show lover than 640 x 480 if the current screen supports higher or equal than 640 x 480
- figure out what's why we receive resolutions with only few pixels difference
- some resolutions have incorrect image stretching

@Branikolog I like your screen resolution in first comment! It's like a game for Smart Watches.

**Comment by Branikolog** [comment]
> Here I see multiple problems. Let's separate them:
> 
> * don't show lover than 640 x 480 if the current screen supports higher or equal than 640 x 480 **fixed**
> * figure out what's why we receive resolutions with only few pixels difference
> * some resolutions have incorrect image stretching
> * save configuration file
> 
> @Branikolog I like your screen resolution in first comment! It's like a game for Smart Watches.

Yep. Looks so funny... To play game in such low resolution.)

**Comment by ihhub** [comment]
The original inability to change resolution is fixed.

**Comment by Branikolog** [comment]
The issue regarding not correct stretching in a fullscreen mode works only on SDL2 version for me. SDL1 works well.

**Comment by ihhub** [comment]
Hi @Branikolog could you please retest this issue? I think it should be fixed by now.

**Comment by Branikolog** [comment]
@ihhub 
Yes. Resolution switch works well a couple of weeks already!
