### ISSUE TITLE
Creature quantity in hero trade window should be under creature icon

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1140]
The numbers on units are drawn over black square:
![Trade window](https://user-images.githubusercontent.com/55348946/88479984-ca3a1880-cf5b-11ea-8f16-537d06cc6d1f.jpg)

**Comment by Branikolog** [comment]
Actually, in the OG creature quantity is written under the creature in this window:
![Pathfinding](https://user-images.githubusercontent.com/55348946/88803018-8beb6600-d1b4-11ea-9fb9-18fdf7122517.jpg)

**Comment by ihhub** [comment]
Hi @Branikolog , please update this issue or create a new one.

**Comment by Branikolog** [comment]
Hello, @ihhub.
Done.

**Comment by ihhub** [comment]
This issue was fixed recently.
