### ISSUE TITLE
Use locale to display numerals

### ISSUE THREAD

**Issue by bjauny** [ihhub/fheroes2#115]
Related to #56 
From the FIXME in `src/fheroes2/castle/castle_town.cpp`.

Numerals are displayed differently depending on the locale. `6000`, `6,000`, `6 000` represent the same number 0x1770. When displaying troups count we have to be aware of this.

**Comment by bjauny** [comment]
Known variations:
- US: `6,000` (comma)
- France: `6 000` (space)
- Spain: `6.000` (period)

**Comment by ihhub** [comment]
Hmm... Maybe we stick to one variation only? If we want to deal with this we need to create a new from `StringReplace` function to deal only with such cases.

**Comment by bjauny** [comment]
Well, the current behavior is like this. The issue can stay for someone to pick it up but it's not critical.

**Comment by ihhub** [comment]
Closing this issue as invalid. At the highlighted area the number of artifacts can't exceed even 50 so there's no point to support locales. I'll remove the comment in one of pull requests.
