### ISSUE TITLE
"Good" scrollbars for heroes and castles are shown in "evil" interface

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1154]
Brown scrollbars are placed in a gray interface.
![Evil bars](https://user-images.githubusercontent.com/55348946/88637034-536b5f80-d0c2-11ea-95ce-43fff36d7fe3.jpg)

**Comment by Branikolog** [comment]
The problem seems a bit deeper, than simply  wrong scrollbars for "evil" interface.
When we change interface to "evil" and save the game, the next time we load this savefile, interface would be "evil". After we close game and start it again, load game, we'd see "evil" interface with "evil" scrollbars. But when we change it to "good", scrollbars remain gray:
![Evil bars2](https://user-images.githubusercontent.com/55348946/88931986-2cf62180-d286-11ea-99d4-a291e81c6031.jpg)

**Comment by ihhub** [comment]
Hi @Branikolog could you please verify this issue again?

**Comment by Branikolog** [comment]
Hi, @ihhub !
I still can reproduce this issue. While loading game after I've set other interface or switching good/evil interface via config button in "Adventure options" menu.

**Comment by Branikolog** [comment]
I think, we should delete switching good/evil code in CONFIG menu. It is really not necessary to have this option in two places in GUI.
Currently, switching good/evil interfaces is working correctly via "System Options" menu.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> I think, we should delete switching good/evil code in CONFIG menu. It is really not necessary to have this option in two places in GUI.

Yes, I will even say these three options can be removed from the "Experimental Game Settings" window (https://github.com/ihhub/fheroes2/issues/1272) as they are redundant in the GUI:
- "game: use evil interface"
- "game: also use dynamic interface for castles"
- "game: hide interface"

**Comment by ihhub** [comment]
Hi @Branikolog , could you please test this issue again?

**Comment by Branikolog** [comment]
@ihhub 
The issue is no more reproducible.
