### ISSUE TITLE
Change LastLoseHero structure to have readable format

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#116]
We have a structure in `src/fheroes2/kingdom/kingdom.h` file:
```cpp
struct LastLoseHero : std::pair<int, u32> /* Heroes, date */
{
    LastLoseHero() : std::pair<int, u32>(Heroes::UNKNOWN, 0) {}
};
```
The structure looks weird to use `first` and `second` structure members instead. We must have something like this:
```cpp
struct LastLoseHero
{
    LastLoseHero()
     : heroes(Heroes::UNKNOWN)
     , date(0)
    {}
    int heroes;
    u32 date;
};
```

And change the usage of this structure everywhere in the code.

**Comment by mgroovyank** [comment]
Can I take up this issue?

**Comment by ihhub** [comment]
Hi @mgroovyank , sure!

**Comment by mgroovyank** [comment]
Thanks! I will do it.
