### ISSUE TITLE
Status window info should extend according to resolution

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1164]
Currently, on a resolutions lower, than ***x768, on Y- axis , we can see only one info block, that can be "hero's army", "Month/week/day" or "resources".
ex: 1280x720
![Status window 1280x720](https://user-images.githubusercontent.com/55348946/88806477-25b51200-d1b9-11ea-8cb9-eeffe4cc25f5.jpg)
While on a higher resolutions we can see all these three blocks together.
ex: 1280x800
![Status window 1280x800](https://user-images.githubusercontent.com/55348946/88806553-42514a00-d1b9-11ea-978d-a92462b52386.jpg)
It would be nice, if we could show at least two block for resolutions from the first case to fill the empty space in status window, up to the resolution, where only one block could fit the status window.
ex: 800x600
![Status window 800x600](https://user-images.githubusercontent.com/55348946/88806768-82b0c800-d1b9-11ea-85ce-519a1786adf0.jpg)

**Comment by ihhub** [comment]
I think we can similar issue...

**Comment by Branikolog** [comment]
Well, i'll look through all our issues tomorrow and try to find duplicated.
