### ISSUE TITLE
Switching arrows in scenario options window

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1167]
![New scenario arrows](https://user-images.githubusercontent.com/55348946/88839418-b6084c80-d1e3-11ea-8bef-3a20eaaaa4ff.jpg)
These arrows change only player's order in this window... Does it effect the order of players in game? I mean, choose player who will get turn first?
If the colors always act in a fixed sequence in game, what do we need these arrows for?

**Comment by Branikolog** [comment]
Currently this option doesn't work. No matter, how colors are placed in this window, AI players make their turn in a default sequence.

**Comment by LeHerosInconnu** [comment]
@Branikolog,

Yes, this option does not work.

However, the idea is good, changing the order of action of the players can be interesting, in particular to increase the difficulty by making the human player play after all the other AI players.
