### ISSUE TITLE
A hero attacking a couple of creatures on a world map can have two dialog windows in a row

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1185]
When creatures are standing too close to each other, approaching hero would have two dialog windows in a row (ex: that creatures are scattering).
In the OG hero has to make any move to make second neutral creature scatter, when standing close to it.

**Comment by idshibanov** [comment]
I believe this was one of the "fixes" in fheroes2 custom options enabled by default.

**Comment by Branikolog** [comment]
It happens, when "only the first monster will attack(H2 bug)" option is switched off

**Comment by oleg-derevenetz** [comment]
Fixed by #3574
