### ISSUE TITLE
While switching between heroes in a sea and on any terrain MIDI music starts from the beginning

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1188]
As we don't have special MIDI theme for sea, currently the previous theme continues playing, while switching to the hero in the sea, But when we switch back to the hero standing the terrain with the same theme, or simply unboard hero - same theme starts from the beginning.
I think, if the theme is going to be played the same to current - we don't need to start it from the beginning.

**Comment by oleg-derevenetz** [comment]
As far as I can see, this is no longer the case and has already been fixed (presumably by #3231). Hi @Branikolog could you please check this on your side too (and close this issue if it is not observed anymore)?

**Comment by Branikolog** [comment]
@oleg-derevenetz 
The problem is gone! Your fix works perfect! Thank you so much for helping with this!
