### ISSUE TITLE
Well "Max" hiring button logic

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1195]
![Well hiring](https://user-images.githubusercontent.com/55348946/89119334-69a85f80-d4b6-11ea-9e8f-d51b6a3a3a89.jpg)
This option should hire the strongest creatures available.
If there're already some creatures - they should be hired as well. 
Let's say, we have 2 free slots on army. 3 other are occupied by dwarves and two some other creatures. So by pressing "MAX" button we should by all available Phoenixes, Unicorns and Dwarves. Priority on stronger creatures.
Only that creatures, that are going to be hired should be in a list.
Also we should create another message logic for this function. (All text message are just my thoughts and can be changed)
If we don't have enough money to purchase any creature - we should see a message: "There's not enough resources to purchase any creature."
If there're no creatures to hire, we should see next message: "There's no one to hire in this city."
If there're no free space in city garrison we should see message: "There's no free space in garrison to hire new creatures."

**Comment by ihhub** [comment]
Hi @Branikolog please verify this issue. I think we did some changes for this in the past.

**Comment by Branikolog** [comment]
Hello, @ihhub!
You're right, logic has changed and now button works much better.
The only thing left, is when we have empty slot in city garrison, it still shows the price for buying all creatures:
![image](https://user-images.githubusercontent.com/55348946/101901337-f3351000-3bc1-11eb-9c8d-b1ad503b1ac6.png)
![image](https://user-images.githubusercontent.com/55348946/101901576-4c9d3f00-3bc2-11eb-89d4-db968123bbc5.png)
While there's no empty places in garrison, MAX button shows only creatures are already in garrison.
![image](https://user-images.githubusercontent.com/55348946/101901824-b3225d00-3bc2-11eb-98a2-ffc4dc6e9b84.png)
![image](https://user-images.githubusercontent.com/55348946/101901833-b74e7a80-3bc2-11eb-92db-5cda4b8ae706.png)
