### ISSUE TITLE
AI end turn crash

### ISSUE THREAD

**Issue by shprotru** [ihhub/fheroes2#1198]
The game is crashes of freezes on AI end of turn, was reported in a discourse chat:
[autosave.zip](https://github.com/ihhub/fheroes2/files/5016071/autosave.zip)

**Comment by mturubanov** [comment]
I guess i've encountered similar problem. In debug i always get
`[DBG_BATTLE]	GetAStarPath:  path not found: Unit: [ 7 Magi, Red, pos: 88, -1 ], dst: (head: 22, tail: -1)`

There is some problem with AI turns in battle (AI::Get().BattleTurn, line 358 in battle_arena.cpp), for unknown reason it gets called infinitely with same action. As a workaround added ai turn counter and in case it goes over some value (1000 in my case) army1 is defeated. Something like that:
`                if ( ( current_troop->GetCurrentControl() & CONTROL_AI ) || ( current_color & auto_battle )) {
                    AI::Get().BattleTurn( *this, *current_troop, actions );
                    if (!interface)
                    {
                        if (ai_turns++ > 1000)
                        {
                            VERBOSE("Too many AI turns!");
                            result_game.army1 = 1;
                        }
                    }
                }
`
Not the best solution, guess someone will find something better.
[bug.sav.tar.gz](https://github.com/ihhub/fheroes2/files/5018057/bug.sav.tar.gz)
