### ISSUE TITLE
Upgrade creature button cannot be seen, if player has not enough gold

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1199]
"Disabled" status button "Upgrade" should be added, if there's not enough money to upgrade unit.
Currently this button disappears:
![Upgrade creature](https://user-images.githubusercontent.com/55348946/89220170-c7819800-d5d9-11ea-9f2b-c578dc634bf6.jpg)

**Comment by idshibanov** [comment]
That's a great moment you caught on the screenshot. I was even confused for a second which unit was displayed :)

**Comment by Branikolog** [comment]
> That's a great moment you caught on the screenshot. I was even confused for a second which unit was displayed :)

Creatures in HoMM2 often have unusual and amusing animations. That's one of the reasons I love this game so much.)
