### ISSUE TITLE
Incorrect message for Shipyard by right click

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#122]
We have repeated message about Shipyard when we right click on it:
![image](https://user-images.githubusercontent.com/19829520/66131659-69d19780-e626-11e9-8d76-36ea066f1595.png)

Notice how it should be:
![image](https://user-images.githubusercontent.com/19829520/66131691-77871d00-e626-11e9-9a9c-138c86fc358f.png)

This means that first message in popup window must be `The Shipyard allows ships to be built.`

**Comment by kgorecki** [comment]
![fheroes2-shipyard](https://user-images.githubusercontent.com/1744776/66145698-0b9bb900-e614-11e9-9b92-4428001a65f4.png)
It looks like it is fine in a castle close to water. Just error message is doubled.
