### ISSUE TITLE
Cost of spell book in shrines (and values in configuration files)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1220]
In fheroes2, there is an option that allows the hero to buy a spell book in the shrines when he does not have one:

"heroes: allow buy a spellbook from Shrines"

I love this option.
However, I think there is no need to swindle the heroes with the price of the spell book in the shrines, 500 gold for all the shrines is enough for an empty book.

In the previous fheroes2 project, it was possible to change the cost of the spell book independently for each shrine in an .xml file.
It would be nice to also be able to set the values ​​used by the game in different .xml files as it was possible with the previous fheroes2 project.

**Comment by ihhub** [comment]
I'm closing this issue as this option was removed from the game. We can reopen it once the option is put back.
