### ISSUE TITLE
"Pursue and engage" window buttons' position

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1226]
Buttons "YES" and "NO" in "pursue and engage" window are placed with unequal spaces to the borders of the window from right and left.
![Scatter buttons](https://user-images.githubusercontent.com/55348946/90290932-726e3d80-de87-11ea-839e-082c2d744caf.jpg)

**Comment by ihhub** [comment]
Closing this issue as it was fixed in #1805 .
