### ISSUE TITLE
Add missing text in battle options dialog

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#123]
During battle go to battle options dialog (left bottom button with computer icon) and notice this:
![image](https://user-images.githubusercontent.com/19829520/66132236-4fe48480-e627-11e9-8849-3b4daadcb879.png)

There is no any information regarding which option is for. Here is a screenshot from the original game:
![image](https://user-images.githubusercontent.com/19829520/66132300-68ed3580-e627-11e9-8ded-f99e8ecb04bb.png)

As you could see here is some text. We don't have all options implemented but at least we must give some text for options we have like in original game.

**Comment by MariaSopkova** [comment]
I'll fix it

**Comment by ihhub** [comment]
Sure!

**Comment by MariaSopkova** [comment]
done
