### ISSUE TITLE
"Hypnotize" retaliation 

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1230]
Currently "hypnotized" creature being attacked and retaliated loses the effect of this spell.
In the OG player can attack "hypnotized" creature without retaliation.

**Comment by LeHerosInconnu** [comment]
Yes, in fheroes2, the Hypnotize spell doesn't work like in the original game.

The Hypnotize spell should work this way:
- the duration of the spell is egal to the hero's Spell Power (hero's Spell Power 3, spell duration 3 turns),
- the spell can be canceled by the Dispel Magic spells, the Cure spells and the Anti-Magic spell,
- the spell is canceled if the hypnotized stack performs an attack,
- the spell is not canceled when the hypnotized stack is physically attacked (melee attack, ranged attack), and the hypnotized stack doesn't retaliate,
- the spell is not canceled when the hypnotized stack takes damage from damage spells.

I also have a suggestion to make it possible to finally use this spell. :)

**Comment by Branikolog** [comment]
Great precision, @LeHerosInconnu ! )
Thanks!
