### ISSUE TITLE
Scenario selection window, elements position

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1235]
In fheroes2:
- [ ] The position of the icons "Players Icon", "Size Icon", "Victory Condition Icon" and "Loss Condition Icon" is not the same as in the original game.
- [ ] The names of the scenarios in the scenarios list are not centered, the names of the scenarios are centered in the original game.
- [ ] The vertical spacing between the names of scenarios in the scenarios list is not regular, this spacing is regular in the original game.
- [ ] The text line of the scenario name "Broken Alliance" is not located at the same vertical position as in the original game.
- [ ] The scenario name "Broken Alliance" is not centered horizontally, the scenario name is not centered horizontally in the original game either, but it is less visible.
- [ ] The difficulty text line of the "Map difficulty: Normal" scenario is not located at the same vertical position as in the original game (the word "Normal" should be centered vertically in the frame and the text "Map difficulty:" should be aligned vertically to the word "Normal").
- [ ] The word used for the difficulty of the scenario "Normal" is not centered horizontally, the word used for the difficulty of the scenario is not centered horizontally either in the original game but it is less visible.
- [ ] The first line of the scenario description text is not located at the same vertical position as in the original game.

In the original game:

![Scenario selection 01](https://user-images.githubusercontent.com/43583994/90317136-941f0180-df27-11ea-91ef-c9512be6614d.png)

In fheroes2:

![Scenario selection 02](https://user-images.githubusercontent.com/43583994/90317151-abf68580-df27-11ea-9277-ee9027b55b33.png)

**Edit 2022/10/10.**

Positions with the number of pixels from the original game screen, with the corrections to be applied.

In original game:

![Scenario selection window pixels 001](https://user-images.githubusercontent.com/43583994/194859225-997f651f-4811-4f1b-96c2-05e9f9cb6b91.png)

Since a supplementary icon for "The Succession Wars" and "The Price of Loyalty" versions has been added for the scenarios in fheroes2, the scenario name must be centered horizontally in the space between the icons on the left and the icons on the right in the list of scenarios.

In fheroes2:

![Scenario selection window 002](https://user-images.githubusercontent.com/43583994/194860940-186d8d4b-9b20-4621-bca3-f5b6af6d546e.png)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , please update the description in the first message. I remember that we agreed to keep the location of these winows in the middle of the screen.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , please update the description in the first message. I remember that we agreed to keep the location of these winows in the middle of the screen. Is it correct?

All remarks are still valid, and yes, the window has to remain centered in the screen.

**Comment by kant2002** [comment]
@LeHerosInconnu can you remove first item in the original issue description? Also if you can convert issue in the list of actionable work items. For example like below. 

- [ ] The position of the icons "Players Icon", "Size Icon", "Victory Condition Icon" and "Loss Condition Icon" is not the same as in the original game.
- [ ] The names of the scenarios in the scenarios list are not centered, the names of the scenarios are centered in the original game.
- [ ] The vertical spacing between the names of scenarios in the scenarios list is not regular, this spacing is regular in the original game.
- [ ] The text line of the scenario name "Broken Alliance" is not located at the same vertical position as in the original game.
- [ ] The scenario name "Broken Alliance" is not centered horizontally, the scenario name is not centered horizontally in the original game either, but it is less visible.
- [ ] The difficulty text line of the "Map difficulty: Normal" scenario is not located at the same vertical position as in the original game (the word "Normal" should be centered vertically in the frame and the text "Map difficulty:" should be aligned vertically to the word "Normal").
- [ ] The word used for the difficulty of the scenario "Normal" is not centered horizontally, the word used for the difficulty of the scenario is not centered horizontally either in the original game but it is less visible.
- [ ] The first line of the scenario description text is not located at the same vertical position as in the original game.

I some items no longer applicable then better completely remove from issue description, to not confuse what have to be done.

**Comment by LeHerosInconnu** [comment]
Hello @kant2002,

I removed the first item in the list "The position of the buttons for selecting the size of the scenarios is not the same as in the original game." and changed the style of the list.

**Comment by kant2002** [comment]
Thanks. I will take a look what can I do

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , could you please update the description of this issue based on the latest UI? We added an extra icon to show map type so some things might not be implemented in the same way to keep text size the same.

**Comment by ihhub** [comment]
@LeHerosInconnu , it would be a real help if we have numbers (pixels) in positions so a developer can easily adjust them based on these numbers.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> @LeHerosInconnu , it would be a real help if we have numbers (pixels) in positions so a developer can easily adjust them based on these numbers.

Original post updated.

**Comment by HaveFun91** [comment]
Here's the screenshot with applied changes.
![image](https://user-images.githubusercontent.com/627531/196045717-d5e4aa34-bbd2-44bb-8732-eb11a64bfbc2.png)

**Comment by LeHerosInconnu** [comment]
Hello @HaveFun91,

> Here's the screenshot with applied changes.
![image](https://user-images.githubusercontent.com/627531/196045717-d5e4aa34-bbd2-44bb-8732-eb11a64bfbc2.png)

After the last changes applied, I made some remarks here: https://github.com/ihhub/fheroes2/pull/5961#issuecomment-1282386799.
