### ISSUE TITLE
Scenario selection window, text "Maps Difficulty"

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1236]
Scenario selection window, text "Maps Difficulty"
In fheroes2, the scenario difficulty text is written this way: "Maps Difficulty:"
The word "Maps" is written in the plural, however this is the difficulty of the selected scenario, so the word should be written in the singular: "Map"
The first letter of the word "Difficulty" is written with a capital letter, in the original game the first letter of this word is written with a lowercase "difficulty".

In the original game:

![Scenario selection 01](https://user-images.githubusercontent.com/43583994/90317136-941f0180-df27-11ea-91ef-c9512be6614d.png)

In fheroes2:

![Scenario selection 02](https://user-images.githubusercontent.com/43583994/90317151-abf68580-df27-11ea-9277-ee9027b55b33.png)

**Comment by Branikolog** [comment]
Good catch, @LeHerosInconnu !

**Comment by LeHerosInconnu** [comment]
It was an easy catch.
