### ISSUE TITLE
Scenario selection window position

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1237]
In fheroes2, the scenarios selection window is not centered horizontally in its parent window (the original window where an action triggered the display of this window, in this case the "Scenario" window, the one where the user regulates the difficulty of the scenario among other things).
In fheroes2, the scenarios selection window is centered vertically in relation to the home screen.
This window is not vertically centered in the original game.
For my part, I prefer it to be centered vertically in relation to the home screen, as is currently the case in fheroes2. :)

In the original game:

![Scenario selection 01](https://user-images.githubusercontent.com/43583994/90317136-941f0180-df27-11ea-91ef-c9512be6614d.png)

In fheroes2:

![Scenario selection 02](https://user-images.githubusercontent.com/43583994/90317151-abf68580-df27-11ea-9277-ee9027b55b33.png)

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu!
I agree with you. I also want all these windows be centered.

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,
Not necessarily in all cases, but in these screens yes.

**Comment by ihhub** [comment]
Left offset from parent window is 21 pixels, right offset - 22 pixels. Closing this issue as we can't shift a window with subpixel accuracy.

**Comment by ihhub** [comment]
This issue was fixed some time ago by another commit.
