### ISSUE TITLE
Scenario selection window shadow

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1238]
In fheroes2, the scenarios selection window has no shadow.
In the original game, this window has a shadow.

In the original game:

![Scenario selection 01](https://user-images.githubusercontent.com/43583994/90317136-941f0180-df27-11ea-91ef-c9512be6614d.png)

In fheroes2:

![Scenario selection 02](https://user-images.githubusercontent.com/43583994/90317151-abf68580-df27-11ea-9277-ee9027b55b33.png)

**Comment by idshibanov** [comment]
This is already addressed and fixed in #1232 .

@LeHerosInconnu it's unfortunate that you spent so much time filing shadow tickets. All shadows issues were linked to the same limitation of our old drawing engine. I'll close other tickets and leave this one open to track progress.

**Comment by LeHerosInconnu** [comment]
Hello @idshibanov,
It's good that it's already fixed.
Too bad that I was too fast, I knew about the new engine and the shadow issues on the adventure map but I didn't think it was related to window shadows too.
I will no longer be reporting on issues related to shadows now, thanks for the info.

For your information, you also closed the ticket "Scenario selection window, scenario information windows https://github.com/ihhub/fheroes2/issues/1245" which is not really related to shadows, I don't know if you did it on purpose.
