### ISSUE TITLE
Battle hexagonal net doesn't appear if enabled until next battle

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#124]
Start any battle with disabled option to display hexagonal (green) net. Enable this option. You could notice that nothing happen. Finish the battle and enter a new battle. Notice that there is the net:
![image](https://user-images.githubusercontent.com/19829520/66134670-40673a80-e62b-11e9-9be5-434a1fe5722a.png)

**Comment by kgorecki** [comment]
Taking! All in all there are plenty of "good first issues" ;}
