### ISSUE TITLE
Scenario selection window, memorized selection

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1240]
In the original game, when the user selects a scenario from a list according to the size of the scenarios and then the user selects the scenarios of all sizes with the "ALL" selection button, the scenario remains selected in the list displayed (in the example the user selects the small scenarios using the "S" selection button and then selects the "0 Test 06" scenario from the list).

In fheroes2, the scenario does not stay selected.

In the original game:

![Scenario selection 07](https://user-images.githubusercontent.com/43583994/90317561-be25f300-df2a-11ea-8367-1371e135db70.png)

![Scenario selection 08](https://user-images.githubusercontent.com/43583994/90317579-d990fe00-df2a-11ea-9b49-282aadd5f2ba.png)

In fheroes2:

![Scenario selection 09](https://user-images.githubusercontent.com/43583994/90317588-e6155680-df2a-11ea-9940-6dfbf30e1c1e.png)

![Scenario selection 10](https://user-images.githubusercontent.com/43583994/90317598-ef062800-df2a-11ea-9258-d2e12cdf3d95.png)

**Comment by felix642** [comment]
Hi @ihhub @LeHerosInconnu this issue seems to be fixed in the latest version of fheroes 2.

**Comment by felix642** [comment]
Hi @zenseii, you are right... For some reason, I thought that the issue described was when leaving the menu and reentering it after. My bad
