### ISSUE TITLE
Scenario selection window, maps size information windows

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1241]
- In fheroes2, the vertical position of the displayed window is not the same as in the original game.
- In fheroes2, the window is not centered horizontally with respect to the home screen.
In the original game, this window is centered horizontally with respect to the home screen.
- In fheroes2, the vertical position of the text in the info window is not the same as in the original game.
- In fheroes2, the text shadow is lighter than the text shadow in the original game.

In the original game:

![Scenario selection 11](https://user-images.githubusercontent.com/43583994/90317669-5623dc80-df2b-11ea-81e1-6fd3fc41190c.png)

In fheroes2:

![Scenario selection 12](https://user-images.githubusercontent.com/43583994/90317677-5c19bd80-df2b-11ea-98e3-fa132222d2f5.png)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu could you please update this issue?

**Comment by LeHerosInconnu** [comment]
@ihhub.

> Hi @LeHerosInconnu could you please update this issue?

It's done.

**Comment by kant2002** [comment]
@LeHerosInconnu and @ihhub  seems to be this issue can be closed. Am I miss something?

**Comment by LeHerosInconnu** [comment]
Hello @kant2002,

> @LeHerosInconnu and @ihhub seems to be this issue can be closed. Am I miss something?

Yes, everything is correct (or modified according to the new fheroes2 rules) except the vertical position of the text in the info window that is not the same as in the original game, but this will be adjusted generally for all windows in another issue: https://github.com/ihhub/fheroes2/issues/1260.
