### ISSUE TITLE
Scenario selection window, maps size information windows shadows

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1242]
In fheroes2, the maps size information windows have no shadow.
In the original game, these windows have a shadow.

In the original game:

![Scenario selection 11](https://user-images.githubusercontent.com/43583994/90317669-5623dc80-df2b-11ea-81e1-6fd3fc41190c.png)

In fheroes2:

![Scenario selection 12](https://user-images.githubusercontent.com/43583994/90317677-5c19bd80-df2b-11ea-98e3-fa132222d2f5.png)

**Comment by idshibanov** [comment]
Closing as duplicate.
