### ISSUE TITLE
Scenario selection window, icons information windows shadows

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1244]
In fheroes2, the icons information windows have no shadow.
In the original game, these windows have a shadow.

In the original game:

![Scenario selection 13](https://user-images.githubusercontent.com/43583994/90317821-4fe23000-df2c-11ea-9abf-e6b3e4425ca9.png)

In fheroes2:

![Scenario selection 14](https://user-images.githubusercontent.com/43583994/90317823-596b9800-df2c-11ea-81f5-35a3a6724281.png)

In the original game:

![Scenario selection 15](https://user-images.githubusercontent.com/43583994/90317825-61c3d300-df2c-11ea-90d1-44af5e97d010.png)

In fheroes2:

![Scenario selection 16](https://user-images.githubusercontent.com/43583994/90317829-68eae100-df2c-11ea-8aeb-581fb8cee6f4.png)

In the original game:

![Scenario selection 17](https://user-images.githubusercontent.com/43583994/90317835-71431c00-df2c-11ea-8ab5-9790adadc711.png)

In fheroes2:

![Scenario selection 18](https://user-images.githubusercontent.com/43583994/90317839-7902c080-df2c-11ea-8a67-191f2d8d6425.png)

In the original game:

![Scenario selection 19](https://user-images.githubusercontent.com/43583994/90317849-81f39200-df2c-11ea-9820-3220c479b089.png)

In fheroes2:

![Scenario selection 20](https://user-images.githubusercontent.com/43583994/90317856-89b33680-df2c-11ea-8e24-c6ee9762c187.png)

**Comment by idshibanov** [comment]
Closing as duplicate.
