### ISSUE TITLE
Scenario selection window, scenario information windows shadows

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1246]
In fheroes2, the scenario information windows have no shadow.
In the original game, these windows have a shadow.

In the original game:

![Scenario selection 21](https://user-images.githubusercontent.com/43583994/90318008-a56b0c80-df2d-11ea-96d4-9ba557e0f0f1.png)

In fheroes2:

![Scenario selection 22](https://user-images.githubusercontent.com/43583994/90318015-ad2ab100-df2d-11ea-9866-b20db22a1375.png)

In the original game:

![Scenario selection 23](https://user-images.githubusercontent.com/43583994/90318016-b4ea5580-df2d-11ea-8b73-0315686d6b20.png)

In fheroes2:

![Scenario selection 24](https://user-images.githubusercontent.com/43583994/90318024-bb78cd00-df2d-11ea-8d56-135709dc8aee.png)

In the original game:

![Scenario selection 25](https://user-images.githubusercontent.com/43583994/90318030-c2074480-df2d-11ea-883a-feb00d5540e0.png)

In fheroes2:

![Scenario selection 26](https://user-images.githubusercontent.com/43583994/90318035-c9c6e900-df2d-11ea-9325-30429d63c5ee.png)

**Comment by idshibanov** [comment]
Closing as duplicate.
