### ISSUE TITLE
Scenario window, elements position

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1250]
- In fheroes2, the text "Rating 100%" is not centered horizontally in the window.
This text is not centered horizontally in the original game either.
For my part, I would prefer that it be centered horizontally in the window.
- In fheroes 2, the edge of the "OKAY" and "CANCEL" buttons are not the same distance from the edge of the window.
These buttons are not the same distance from the edge of the window in the original game either.
For my part, I would prefer that they be at the same distance from the edge of the window.
- The shadows of the difficulty level buttons and the scenario name bar do not have the same offset as in the original game.
4 pixels to the left, 3 pixels to the bottom in the original game.
4 pixels to the left, 4 pixels to the bottom in fheroes2.
For my part, I prefer the evenly distributed shadow of fheroes2.
So for me, no need to change that. :)

- The words "Hard", "Expert" and "Impossible" are not centered in relation to the difficulty level buttons, 1 pixel offset to the left of the word.

- Opponent buttons, hero class buttons and double arrow graphics for changing player order have no shadows.

**Some adjustments to make to improve the visual appearance of this window:**

By taking the title of the window "Scenario:" as a reference and which must remain in its current position.

- Move the position of the difficulty level selection buttons 2 pixels down to prevent the red frame indicating the selected difficulty from covering the text shadow of the letter "y" of the word "Difficulty".

- Put the same vertical space between the median of the line of the text and the element just above (11 pixels).
Example, the bottom of the scenario name graphic and the median of the line of the text "Game Difficulty:".

- Put the same vertical space between the baseline of the line of the text and the element just below (8 pixels).
Example, the baseline of the text "Game Difficulty:" and the top of the graphic of the difficulty level selection button.

- Adjust the vertical spacing between the median of the line of the text "Random" and the bottom of the hero class button graphic (5 pixels).

- The vertical spacing between the bottom of the scenario difficulty level graphic and the median of the line of the text of the difficulty level must remain at 7 pixels.

![Scenario window, improve the visual appearance 01](https://user-images.githubusercontent.com/43583994/92324670-48eaa100-f044-11ea-9251-4dd7bc82dc94.png)

In the original game:

![Scenario window 03](https://user-images.githubusercontent.com/43583994/90333832-4955c600-dfc9-11ea-856d-dfd9cc2e3c48.png)

In fheroes2:

![Scenario window 05](https://user-images.githubusercontent.com/43583994/92324838-a3383180-f045-11ea-935a-ab1505587cf2.png)

**Edit 2022/05/23.**

Related discussion: https://github.com/ihhub/fheroes2/discussions/5444.

**Edit 2022/10/22.**

Vertical spacing adjusted with the addition of the new handicap buttons.

![Vertical spacing 02](https://user-images.githubusercontent.com/43583994/197357834-14fd8aed-e2ec-4f67-966c-df67d8d32838.png)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu please update this issue, downloading the latest version after an hour (it should be compiled in an hour). I fixed few things here.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu please update this issue, downloading the latest version after an hour (it should be compiled in an hour). I fixed few things here.

I updated the first post.
And I also added some suggestions to improve the visual appearance of this window.

**Comment by ihhub** [comment]
Hmm... it's hard to do for now as we don't have a proper UI framework :) I'll check something. Also I forgot to update the position of player count window with buttons...

**Comment by LeHerosInconnu** [comment]
@ihhub.

> Hmm... it's hard to do for now as we don't have a proper UI framework :) I'll check something.

Okay I understand.

> Also I forgot to update the position of player count window with buttons...

Yes, that window.
Heroes 2 left, fheroes2 right:

![Multiplayer, number of players window H2 01](https://user-images.githubusercontent.com/43583994/92330964-3fc4f880-f073-11ea-9b61-1749039a538e.png) ![Multiplayer, number of players window fh2 01](https://user-images.githubusercontent.com/43583994/92330970-4489ac80-f073-11ea-87a9-4aec9cd568d5.png)

**Comment by ihhub** [comment]
It's updated few hours ago :)

**Comment by LeHerosInconnu** [comment]
@ihhub.

> It's updated few hours ago :)

Nice. :)

**Comment by kant2002** [comment]
@ihhub and @LeHerosInconnu is this fixed?

**Comment by LeHerosInconnu** [comment]
@kant2002.

> @ihhub and @LeHerosInconnu is this fixed?

No, all remarks are still valid.

**Comment by HaveFun91** [comment]
As mentioned on discord when i did this:
![image](https://user-images.githubusercontent.com/627531/195859195-fa9d4335-fb9b-441d-8cb9-2c2530f3d53e.png)
in `game_scenarioinfo.cpp` i got this
![image](https://user-images.githubusercontent.com/627531/195859141-b04d03df-708f-42df-8cbe-79510262d0b7.png)

This means that difficulty level buttons are part of panel background and cannot be moved like we'd like to.

**Comment by HaveFun91** [comment]
Ok,
I made some changes. @LeHerosInconnu please verify if it fits you.
Scenario window:
![image](https://user-images.githubusercontent.com/627531/196002233-42451323-4c08-4d8d-a51f-66f6183ff4f7.png)
Game info Dialog:
![image](https://user-images.githubusercontent.com/627531/196002242-61737877-b704-4163-acb3-bfb63354b5ce.png)

**Comment by HaveFun91** [comment]
Ok, so this is a question whether we want to create separate task for it or it should be covered within this one. @ihhub ?

**Comment by HaveFun91** [comment]
Ok,
I applied changes both in Dialog Game Info.
To sum up:
- Scenario Window
![image](https://user-images.githubusercontent.com/627531/197152622-47d89693-0c7f-4aff-9711-e48da91ebf50.png)
- Game Info Dialog
![image](https://user-images.githubusercontent.com/627531/197152705-2b212fc8-576b-4d3f-8531-963fc0e61ebb.png)

**Comment by LeHerosInconnu** [comment]
@HaveFun91.

I will take a look at it tomorow. :)

**Comment by LeHerosInconnu** [comment]
Hello @HaveFun91,

> @HaveFun91.
> 
> I will take a look at it tomorow. :)

- **Scenario Window.**

The word "Normal" is not centered horizontally in relation to the Cavalier frame, 9 pixels on the left and 11 pixels on the right.
You can also notice that the spacing between the Cavalier and the Tower graphics is only 11 pixels instead of 12 pixels for the other graphics (it is the same in the original game).

I have updated the original post for vertical spacing adjusted with the addition of the new handicap buttons.

- **Game Info Dialog.**

"Grad", "100 %", "Gegner" and "Klasse" are correctly centered respectively.

**Comment by zenseii** [comment]
Thanks as always for taking a look at this, @LeHerosInconnu.

> The word "Normal" is not centered horizontally in relation to the Cavalier frame, 9 pixels on the left and 11 pixels on the right. 

This is due to the issue with original assets as you mentioned about the cavalier and the tower. However, this "Normal" can still be adjusted. We basically need to account for the spacing not being equal between all the difficulty buttons.

> You can also notice that the spacing between the Cavalier and the Tower graphics is only 11 pixels instead of 12 pixels for the other graphics (it is the same in the original game).

The take away message here is that there is a problem with the original asset and this can only be dealt with by producing
