### ISSUE TITLE
Scenario window position

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1252]
In fheroes2, the scenario window is not at same position as in the original game.
In fheroes2, this window is not vertically centered.
This window is not vertically centered in the original game either.
For my part, I prefer this window to be centered both vertically and horizontally in fheroes2.

In the original game:

![Scenario window 03](https://user-images.githubusercontent.com/43583994/90333832-4955c600-dfc9-11ea-856d-dfd9cc2e3c48.png)

In fheroes2:

![Scenario window 04](https://user-images.githubusercontent.com/43583994/90333834-507cd400-dfc9-11ea-9b0a-c36a3a725d1e.png)

**Comment by Branikolog** [comment]
Closing as it relates to an existing issue (#1247)
