### ISSUE TITLE
Multiplayer mode, enter the players' handicap

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1255]
In the original game, in the multiplayer mode, it is possible to enter a personalized name for each player.
In fheroes2 this is not possible.

![Multiplayer mode 01](https://user-images.githubusercontent.com/43583994/90338037-0f93b800-dfe7-11ea-804d-2ae705a0acf3.png)

![Multiplayer mode 02](https://user-images.githubusercontent.com/43583994/90338040-17535c80-dfe7-11ea-80ab-dd7ea6dc809e.png)

In the original game, it is also possible to apply a handicap for each player.

![Multiplayer mode 06](https://user-images.githubusercontent.com/43583994/90338045-22a68800-dfe7-11ea-9140-609e96c0a845.png)

**Edit 2022/04/19.**

The operation for the names should remain the same as now (see post below).
Only the handicap choice for the players is missing.

**Comment by zenseii** [comment]
Looking at some of these old issues. I think name entry is better in fheroes2 since you don't get annoyed by pop-ups for name entry, like if you want to play 5 players.

If this is agreed on, then the only thing missing in this issue should be handicap?

Should the title of the issue be changed, @LeHerosInconnu ?

**Comment by LeHerosInconnu** [comment]
@zenseii,

> Looking at some of these old issues. I think name entry is better in fheroes2 since you don't get annoyed by pop-ups for name entry, like if you want to play 5 players.
> 
> If this is agreed on, then the only thing missing in this issue should be handicap?
> 
> Should the title of the issue be changed, @LeHerosInconnu ?

Yes, the current way of doing for player names in fheroes2 is better. :)
I changed the title of the issue and edited the message, thanks.
