### ISSUE TITLE
Multiplayer mode, text of the "NEW GAME" request window

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1257]
I think a dot "." is missing at the end of the second sentence in parentheses.
"Are you sure you want to restart? (Your current game will be lost.)"
This sentence has the same problem in the original game.

![Multiplayer mode 09](https://user-images.githubusercontent.com/43583994/90338124-a52f4780-dfe7-11ea-9a0f-20ecf0783068.png)

**Edit 2020/10/07.**

Another window with the same problem.

![File options Evil fh2 08](https://user-images.githubusercontent.com/43583994/95351735-d6c6df80-08c1-11eb-8fb4-2a395d8c4f68.png)

**Comment by ihhub** [comment]
I disagree with this. The text between () never ends with a dot. It looks very weird to have a dot before ).

**Comment by LeHerosInconnu** [comment]
@ihhub.

> I disagree with this. The text between () never ends with a dot. It looks very weird to have a dot before ).

This is also a typographical rule.
The ending period is placed inside the parentheses when the comment forms a complete sentence.

(It is also possible to put the second sentence on another line, remove the parentheses and add the period.) :D

There are several phrases in this case in the original game.
In original game, for example:

![Period parenthese H2 01](https://user-images.githubusercontent.com/43583994/94178950-15a96e00-fe9c-11ea-9c6c-edf6ab212fea.png)
