### ISSUE TITLE
Multiplayer mode, position of the "NEW GAME" request window

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1258]
This window is not centered with respect to its parent window.

![Multiplayer mode 09](https://user-images.githubusercontent.com/43583994/90338124-a52f4780-dfe7-11ea-9a0f-20ecf0783068.png)

I suggest all these windows to be centered both vertically and horizontally in fheroes2.
This taking into account only the rectangular part of the window graphic, in my opinion the upper and lower "decorations" of the window graphic should not be taken into account for the window centering.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , could you please retest this issue. I've fixed the position of all such windows (they are generated). The window was shifted 8 pixel to right.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , could you please retest this issue. I've fixed the position of all such windows (they are generated). The window was shifted 8 pixel to right.

This is how this window is displayed in version 0.8.1 1552.

![Multiplayer mode 09 081 1552](https://user-images.githubusercontent.com/43583994/92325693-e8139680-f04c-11ea-91a7-e3b49fe64d87.png)

It was well centered horizontally in version 0.8.0. :)
It was the vertical position (without the top and bottom decorations) that was a problem for this window in version 0.8.0. :)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , this window now is centered against the whole display like any other generic window. What I can do is to center "parent" window as it's shifted due to shadow presence.

**Comment by LeHerosInconnu** [comment]
@ihhub.

> Hi @LeHerosInconnu , this window now is centered against the whole display like any other generic window. What I can do is to center "parent" window as it's shifted due to shadow presence.

Yes, the "parent" window must also be centered in relation to the whole screen without its shadow being taken into account. :)
