### ISSUE TITLE
Game settings window

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1261]
When the user right-clicks or left-clicks in the text area, or checks/unchecks an option, or uses the scroll bar, or uses the mouse wheel, part of the top of the graphic of the two buttons " OKAY "and" CANCEL" is cut off.

![Game settings window 01](https://user-images.githubusercontent.com/43583994/90392049-78823b00-e08e-11ea-90fa-e8eb98b94626.png)

**Comment by ihhub** [comment]
This issue is not valid anymore.
