### ISSUE TITLE
Game settings window, "game: show SDL logo"

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1262]
This option is activated by default.
SDL logo is not displayed during launch.
This error is reported in the message window.

![Game settings window 02](https://user-images.githubusercontent.com/43583994/90393961-09a6e100-e092-11ea-8bfd-819bb16bb4da.png)

Anyway, is this a really essential option?

**Comment by Branikolog** [comment]
Currently we are discussing "Config" options menu:
The nearest time developers are going to remove this menu, as the options included there in the majority are useless, not in alignment with the project view and not properly working.
Some of them would be set to default. Some of them could be applied in future.

**Comment by LeHerosInconnu** [comment]
@Branikolog,

Is there any trace of what has already been discussed about this?

And how is it planned to activate certain options then if this menu disappears?
Imposing options is not my view of how a good user friendly game should work.

If you want, I can do a study of the different options and suggest which ones are useful, which are redundant or will bring more disadvantages than advantages, and which are useless or not too much in relation to the gameplay of the game?

**Comment by Branikolog** [comment]
@LeHerosInconnu, hi.
As we currently working on a remake of original HoMM2, we are going to remove all options, that effect gameplay experience. So we leave only a few, that make playing experience more comfortable.
In future, for game version beyond 1.0 we'd probably return some of them and even add new.
So welcome to our forum thread for discussing beyond 1.0 features. ;) You can also discuss there tweaks from current list, you think, would be nice to have in game.

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

I opened a thread on this subject here: https://github.com/ihhub/fheroes2/issues/1272

**Comment by ihhub** [comment]
Closing the issue as this option not longer exists.
