### ISSUE TITLE
Game settings window, "world: Outer creature dwellings should accumulate units"

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1263]
This option is not enabled by default.
In the original game, creatures accumulate in creature generators on the adventure map.
This option should be enabled by default.

![Game settings window 03](https://user-images.githubusercontent.com/43583994/90395385-c306b600-e094-11ea-94bc-0df1c248e617.png)

**Comment by Branikolog** [comment]
Is this the only option should be set to default from this list?
Regarding this list I've already written in #1262.

**Comment by LeHerosInconnu** [comment]
@Branikolog,

I haven't looked at everything yet, and I made an answer here: https://github.com/ihhub/fheroes2/issues/1262

**Comment by ihhub** [comment]
Closing this issue as we removed this option making it by default.
