### ISSUE TITLE
Titans surrender cost is not like the original

### ISSUE THREAD

**Issue by bjauny** [ihhub/fheroes2#127]
Related to #56
From the FIXME in `src/fheroes2/battle/battle_army.cpp`.

Since I can't easily start the original Windows demo I'll guess that the original cost for the surrender of 3 Titans is 7500 golds. In the current version it's 5000 gold per Titan (plus 2 gems).

**Comment by alx168** [comment]
I will take this on. I don't notice anything relating to cost in the battle_army.cpp. Could you tell me about where I should look around to change this?

**Comment by ihhub** [comment]
Hi @alx168 , you have to take a look into `u32 Battle::Force::GetSurrenderCost(void) const` function in this file.
