### ISSUE TITLE
Game settings window, opinion and suggestions regarding the options

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1272]
I did a little study of the different options available in the "Game Settings" window.
Here is my opinion and suggestions regarding these options.

**Mandatory by default:**

- game: autosave on
Currently this option is enabled by default.

- world: use unique artifacts for secondary skills
Currently this option is not enabled by default.
This option affects artifacts related to the secondary skills Scouting, Mysticism and Necromancy.
In the original game, if the hero has multiple copies of one of these artifacts, the bonus is only counted once (hero's vision area, etc.).
**Scouting**
--Telescope: +1 square to hero's viewing range.
**Mysticism**
--Power Ring: +2 additional spell points restored to the hero (a total of 3 spell points restored with the spell point restored by the hero at the start of each turn).
**Necromancy**
--Spade of Necromancy: +10% of Skeletons generated at the end of a combat.
When this option is not activated, all the bonuses of artifacts related to these three secondary skills are counted multiple times.
This is a very interesting option but it should be possible to set it separately for each secondary skill to allow precise tuning according to the user's wishes (separate settings for Scouting, Mysticism and Necromancy). (https://github.com/ihhub/fheroes2/issues/2336)

- heroes: remember move points for retreat/surrender result
Currently this option is not enabled by default.
In the original game, the hero recovers all of his movement points when the hero is recruited.
I consider this to be a bug.
In fheroes2, it is possible to use this option to remedie this.

**Must have:**

- game: remember last focus
This option makes the last hero/castle selected when the player ends his turn automatically be selected in the next turn.

- battle: show damage info
This option can be improved, I already have some ideas. (https://github.com/ihhub/fheroes2/issues/1624)
Edit: Should be integrated into the program with the possibility to be activated/deactivated with the keyboard key "F5".

- world: show visited content from objects
Currently this option is enabled by default.
It may be desirable to leave this option enabled by default, even if it does not match how the original game works, as it is a very nice game improvement.
This option also acts, in a hidden way, on the display of the terrain penalty in the information window in the squares adjacent to the hero.
This feature should have a separate setting (https://github.com/ihhub/fheroes2/issues/2575).

- world: Wind/Water Mills and Magic Garden can be captured
I really like this option, because it removes unnecessary and tedious micromanagement from the game.

- world: scouting skill show extended content info
This option needs to be improved, and I already have a more complete idea for it. (https://github.com/ihhub/fheroes2/issues/1506)

- world: Eagle Eye also works like Scholar in H3.
Related to Heroes 3.
This option needs to be improved and there are some bugs.
I planned a tweak for the Eagle Eye skill and I have a skill suggestion (Learning) that does much the same thing. (https://github.com/ihhub/fheroes2/discussions/2990)

- world: ban plagues months
This option can prevent "unintentional" reloads of the game.

- heroes: allow buy a spellbook from Shrines
This option is very nice, but the price of the book in the shrines is too high for my liking.
Edit: A cost of 500 Gold in all Shrines as in a Mage Guild is high enough (instead of a different price in each type of Shrine). (https://github.com/ihhub/fheroes2/discussions/3384)

- heroes: in Arena can choose any of primary skills
This option is very interesting, I wonder why it is not automatically integrated into the original game.
The power of knowledge should not be underestimated, and in addition the graphic is already present in the game files.
This option is related to "The Price of Loyalty" expansion.
Folders and files from the expansion are necessary.

**Useful:**

- game: always confirm for rewrite savefile

- game: show info system
Displays the time and the number of frames per second.
Edit: Could be integrated into the program with the possibility of being activated/deactivated with a keyboard key.

- game: autosave will be made at the beginning of the day
This option can be useful to avoid having to wait for AI players turn.

- game: offer to continue the game afer victory condition
I know someone interested in this option.

- world: allow set guardian to objects
Related to Heroes 3.
This option can be improved.

- world: ban for WeekOf/MonthOf Monsters

- world: Months Of Monsters do not place creatures on map

- battle: show army order
This option can be interesting, especially for new players.
Edit: Should be integrated into the program with the possibility to be activated/deactivated with the keyboard key "F6".

- world: Neutral armies scale with game difficulty (https://github.com/ihhub/fheroes2/pull/1872)
If you enable the option army counts are simply multiplied by:
Normal - 100%
Hard - 130%
Expert - 160%
Impossible - 190%

- world: show terrain penalty
This option displays the terrain penalty according to the selected hero taking into account the hero's secondary skill Pathfinding.

- castle: allow gardians
This option can be interesting.
I haven't tested it extensively.
This option needs to be improved.

**Bugged:**

- game: use fade
This option is bugged.
The effects should be integrated the same as in the original game and this option should be removed.

**Related to Heroes 3:**

- unions: allow meeting heroes
This option can be interesting.
Edit: This option is bugged, see post below.

- unions: allow castle visiting
This option can be interesting.
This option crashes the game when a hero visits an ally's castle in two-human multiplayer mode.
Edit: This option is bugged, see post below.

- battle: soft wait troop

- battle: reverse wait order (fast, average, slow)
This option can only work if the "battle: soft wait troop" option is activated, however activating the "battle: reverse wait order (fast, average, slow)" option does not automatically activate the "battle: soft wait troop" option.
Edit: Could be integrated into the program with the possibility of being activated/deactivated with a keyboard key.

**These options will not be necessary in the future:**
These options are intended to bring difficulty to the player.
I doubt they will be used by the majority of players.
Also, since the AI will be improved and there will be a very difficult mode, they are not really necessary anymore.

- world: Starting heroes as Loss Conditions for Human Players
This option can be frustrating, but useful for players who want a challenge.

- world: Only 1 hero can be hired by the one player every week
This option can be frustrating, but useful for players who want a challenge.

- world: each castle allows one hero to be recruited every week
This option can be frustrating, but useful for players who want a challenge.

- world: use unique artifacts for resource affecting
This option does not currently work. (https://github.com/ihhub/fheroes2/issues/2337)
This option can be frustrating, but useful for players who want a challenge.

- heroes: recruit cost to be dependent on hero level
This option can be frustrating, but useful for players who want a challenge.

- castle: higher mage guilds regenerate more spell points/turn (20/40/60/80/100%)
This option can be frustrating, but useful for players who want a challenge.

**These options should be adapted:**

- world: use unique artifacts for primary skills
This option can be frustrating, but useful for players who want a challenge.
Currently, this option also affects artifacts related to movement on land and ocean and it is not possible to make fheroes2 work the same as the original game because of this.
This option affects artifacts related to the primary skills Attack, Defense, Spell Power and Knowledge.
When this option is activated, all the bonuses of artifacts related to these four primary skills are counted only once.
This is not the way the original game works where all bonuses from artifacts are counted.
This option also affects artifacts related to the secondary skills "Logistics" (movement on land) and Navigation.
**"Logistics"** (movement on land)
-- Nomad Boots of Mobility: +6 Moves (600 points).
-- True Compass of Mobility: +5 Moves (500 points) on land and ocean.
-- Traveller's Boots of Mobility: +3 Moves (300 points).
**Navigation**
-- Sailor's Astrolabe of Mobility: +10 Moves (1000 points) on ocean.
-- True Compass of Mobility: +5 Moves (500 points) on land and ocean.
When this option is not activated, the bonuses of artifacts related to these two secondary skills are counted several times.
This is not the way the original game works where bonuses from these artifacts are counted only once.
As you can see, currently it is not possible to make fheroes2 work the same as the original game.
If the option is not enabled, the bonuses of movement artifacts on the land and on the ocean are counted multiple times, which is not the case in the original game.
And if the option is enabled to remedy this problem, the bonuses of artifacts related to the four primary skills are only taken into account once, which is not the case in the original game.
I suggest moving the setting for the secondary skills "Logistics" and Navigation in the option "world: use unique artifacts for secondary skills" (with separate setting for Logistics/Navigation as proposed). (https://github.com/ihhub/fheroes2/issues/2335)

- world: use unique artifacts for moral/luck (currently not available)
Currently this option is not enabled by default.
In the original game, if the hero has multiple copies of the same artifact, the bonus is counted only once.
And in fheroes2, when this option is not activated, the info window does not give correct information when the hero has several copies of the same artifact, examples "Medals of Valor +2", "Fizbins of Misfortune -4". (https://github.com/ihhub/fheroes2/issues/1300)
The possibility to cumulate the effects of multiple copies of the same Morale and Luck artifact is a good option in my opinion because it reduces micromanagement between heroes and reduces the frustration of having artifacts taking up space for nothing.

**Related to "The Price of Loyalty" expansion.**
Folders and files from the expansion are necessary.

- world: Crystal Ball also added Identify Hero and Visions spells
Edit: With this option enabled, the "Identify Hero" and "Visions" spells are available in the hero's Magic Book as long as the Crystal Ball artifact is present in the hero's inventory.
The description of this option can be confusing and should be replaced:
"world: Crystal Ball temporarily inscribes the "Identify Hero" and "Visions" spells in the hero's magic book"
It can be an interesting option for the game.

- world: disable Barrow Mounds
I have a very interesting idea for ghosts.

- heroes: allow transcribing scrolls (needs: Eye Eagle skill)
This option has the effect of permanently inscribing the temporary spell of a spell scroll in the hero's magic book.
This is a very nice option.
Edit: Adjustment for the option: https://github.com/ihhub/fheroes2/issues/2466.

There are spelling mistakes and presentation irregularities in this window, it would be nice that a native english speaker checks this window.

I will report the bugs mentioned in this post later.

I will suggest other options to improve the gameplay and make the game more user friendly.

**Edit 2020/12/25.**

Managing options and user preferences with a better GUI: https://github.com/ihhub/fheroes2/discussions/2472.

**Comment by idshibanov** [comment]
Hi @LeHerosInconnu 

Original developer of the project added a lot arbitrary changes to game logic that we're still cleaning up. This setting window is one of those things that we do not support. Main focus right now is to re-create the original game rather than spend time on enhancements.

With that context I think for 0.9 we should either remove this window altogether or remove a lot of options there. It's amazing that you tested and reviewed them since it saves us time.

In the future, around 1.0 we can go back and work on meaningful enhancements. I also think that we will need a better GUI than simple checkbox list.

If you have ideas you can add them here so they won't get lost.

**Comment by LeHerosInconnu** [comment]
Hello @idshibanov,

You do well to tell me that this window may be temporarily removed.
I intended to report a few bugs related to the options in this window, but as the main focus for now is to re-create the original game, I will only focus on the bugs related to the differences compared to the original version of the game for now.

Count on me to add new options for "Beyond 1.0" version.

**Comment by LeHerosInconnu** [comment]
Correction for the options concerning the add-on "The Price of Loyalty":

- world: Crystal Ball also added Identify Hero and Visions spells
- world: disable Barrow Mounds
- heroes: allow transcribing scrolls (needs: Eye Eagle skill)

It is possible to test these options provided you add all the folders and files necessary for the add-on to work.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , please update your first message in this topic based on changes I made in [this pull request](https://github.com/ihhub/fheroes2/pull/1446).

**Comment by LeHerosInconnu** [comment]
@ihhub.

> Hi @LeHerosInconnu , please update your first message in this topic based on changes I made in [this pull request](https://github.com/ihhub/fheroes2/pull/1446).

It's done.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , I made an extra change for these options [here](https://github.com/ihhub/fheroes2/pull/1448). You can remove both options from the list in your first message.

**Comment by LeHerosInconnu** [comment]
@ihhub.

> Hi @LeHerosInconnu , I made an extra change for these options [here](https://github.com/ihhub/fheroes2/pull/1448). You can remove both options from the list in your first message.

It's also done.

**Comment by ihhub** [comment]
Good job!

**Comment by LeHerosInconnu** [comment]
This option does not work:

- "world: Crystal Ball also added Identify Hero and Visions spells"

This option is supposed to give directly the information provided by these two spells, without needing to cast the spells, but it does not work.
It can be a very interesting option for the game.

Visions:
Gives relative strength of an army camp, and whether that camp will offer to join the hero.

![Identify Hero and Visions spells 01](https://user-images.githubusercontent.com/43583994/91717825-878ae200-eb92-11ea-9abd-73bc6ac601ab.png)

Identify Hero:
Allows you to see the stats of all enemy heroes and the size of their armies.

![Identify Hero and Visions spells 02](https://user-images.githubusercontent.com/43583994/91717841-8fe31d00-eb92-11ea-9bea-e7abe834ec53.png)

![Identify Hero and Visions spells 03](https://user-images.githubusercontent.com/43583994/91717838-8eb1f000-eb92-11ea-9acb-d791c2594ed2.png)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , I removed few other options as well [here](https://github.com/ihhub/fheroes2/pull/1461). Two of them didn't work properly and third one was impacting balance.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , I removed few other options as well [here](https://github.com/ihhub/fheroes2/pull/1461). Two of them didn't work properly and third one was impacting balance.

I removed these options from the first post.

**Comment by LeHerosInconnu** [comment]
Option "heroes: allow transcribing scrolls (needs: Eye Eagle skill)".

This option has the effect of permanently inscribing the temporary spell of a spell scroll in the hero's magic book.
The spell scroll is consumed during transcription.

The hero must have a certain level of the Eagle Eye skill to be able to transcribe the spell depending on the level of the spell.

Eagle Eye Basic: Spells level 1 to level 2
Eagle Eye Advanced: Spells level 1 to level 3
Eagle Eye Expert: Spells level 1 to level 5

The hero must also have the level of Wisdom skill sufficient to be able to transcribe the spell in the magic book.

No Wisdom: Spells level 1 to level 2
Wisdom Basic: Spells level 1 to level 3
Wisdom Advanced: Spells level 1 to level 4
Wisdom Expert: Spells level 1 to level 5

The transcription of the spell in the magic book also has a cost in spell points corresponding to the cost of casting the spell.

![Transcribing scrolls 01](https://user-images.githubusercontent.com/43583994/91744872-6c33cd00-ebba-11ea-87b3-b260d68050fd.png)

This is a very nice option.

For my part, I would adapt the level of spells authorized by the level of the Eagle Eye skill a little so that it is more in relation to the levels of the Wisdom skill:

Eagle Eye Basic: Spells level 1 to level 3
Eagle Eye Advanced: Spells level 1 to level 4
Eagle Eye Expert: Spells level 1 to level 5

There is also a small bug that I will report (https://github.com/ihhub/fheroes2/issues/1467).

**Comment by Branikolog** [comment]
> Eagle Eye Basic: Spells level 1 to level 3
> Eagle Eye Advanced: Spells level 1 to level 4
> Eagle Eye Expert: Spells level 1 to level 5

In my opinion, levels of the spells that hero can learn in battle and from scrolls, should be the same for each level of secondary skill.
It looks bad, when hero can learn in battle 1-2lvl spells, but can learn from scroll 1-3 having basic "Eagle Eye" skill. Also, we should add this additional info in the description of the secondary skill.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

That's a good point.

The problem is that the Eagle Eye skill is limited to level 4 spells at most during combat.

Eagle Eye Basic: Spells level 1 to level 2
Eagle Eye Advanced: Spells level 1 to level 3
Eagle Eye Expert: Spells level 1 to level 4

When the ability to transcribe a spell was designed, the creator simply increased the level of the Eagle Eye Expert skill from level 4 spells during combat to level 5 spells for transcription so that the level 5 spells could be transcribed.

This is what makes the option a bit "wobbly" in its use.

Based on this principle, if the Expert level of the Eagle Eye skill has been increased by 1 level for the level of spells (it has gone from the value 4 to the value 5), the other mastery levels of the Eagle Eye skill must be increased of the same value.

We can also consider that it is more difficult to use the Eagle Eye skill during combat because the learned spells come from the opponent.
While the transcription of the spells comes from the hero himself, hence the possibility of using the Eagle Eye skill with 1 higher level for spells for each level of expertise of the Eagle Eye skill.

> >  Also, we should add this additional info in the description of the secondary skill.

Yes, absolutely. :)

**Comment by Branikolog** [comment]
> Yes, absolutely. :)

So, if we have to describe different spell levels for transcribing scrolls, the whole skill description will become too large. I don't like, when there's lots of text in description. Looks bad. Hard to read and recognize information.
 

> The problem is that the Eagle Eye skill is limited to level 4 spells at most during combat.

Why can't we limit scroll transcribing on the same level too?

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> > Yes, absolutely. :)
> 
> So, if we have to describe different spell levels for transcribing scrolls, the whole skill description will become too large. I don't like, when there's lots of text in description. Looks bad. Hard to read and recognize information.

No need to write a novel, the simple sentence "Allows you to transcribe 1st to 3rd level spells from spell scrolls into your magic book." should be sufficient. :)

> > The problem is that the Eagle Eye skill is limited to level 4 spells at most during combat.
> 
> Why can't we limit scroll transcribing on the same level too?

Because it will bring frustration to the player.
The main appeal of playing a video game is to have fun playing the game, not to have frustration.

For the limitation of spell level during combat, that's understandable.
The player must deploy time and skill to obtain level 5 spells and sometimes even build several mage guilds to obtain the desired spell.
If it was easy to learn level 5 spells during a combat, the human player would just wait for AI players to build mage guilds to get the spells, which would break the design of the game a bit.
Not to mention that when the player plays the scenarios in "Impossible" difficulty mode, it is even more difficult to build level 5 mage guilds.

For the spell scrolls, the hero can already use the spells, the transcription just registers the spell permanently in the hero's magic book and frees a slot in the hero's inventory.
It doesn't break the design of the game in any way and I would even say that it fixes the flaw of being encumbered by multiple spell scrolls after defeating an opposing hero.

Now all that remains is to teach the AI ​​to use this possibility intelligently. No need to "grill" a level 5 spell scroll if the hero already has the spell, the AI ​​must give the spell scroll to a another of his heroes who can use the spell with all its effectiveness. :D

**Comment by Branikolog** [comment]
Well, I want to see this option with some limitations: not all scrolls can be learned. Let's leave the most valuable 5th level scrolls as they are. Let players exchange them. Win in a battle. Let this scroll fill a space in inventory, if you still want to use 5th level spell.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> Well, I want to see this option with some limitations: not all scrolls can be learned. Let's leave the most valuable 5th level scrolls as they are. Let players exchange them. Win in a battle. Let this scroll fill a space in inventory, if you still want to use 5th level spell.

Why activate a fun option and then want to restrict it? :)

Or a settings file for the option to allow/prohibit certain spell scrolls should also be available to provide maximum flexibility to users.

**Comment by Branikolog** [comment]
> Why activate a fun option and then want to restrict it? :)

We are not talking about deliberate restrictions, but about in-game balance.
If authors decided to make a hero with "eagle eye" skill not recognize 5th level spells (admitting it in such way especially rare and valuable) they probably assume player should learn them only in Guild or having special artifact, but not somewhere during other activities. They even haven't made a special 5 tier shrine for 5th level spells. (If i'm not mistaken)
So let's leave 5th level spells like something ultra valuable and unattainable for the most of cases.
Also. i don't like "eagle eye" skill having different values for studying spells. Players always be in a mess. "What level can they learn by advanced skill? 3? And what scrolls? 4?" 
It should be simple: the same level of the skill for the same level of spells, no matter, how player would try to learn it: in battle, or by scroll. 
That's my opinion for this nice skill improvement. We also should ask other members of the project.)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> We are not talking about deliberate restrictions, but about in-game balance.

The balance of the game is absolutely not changed since in any way the hero can already use the spell contained in the spell scroll.

> They even haven't made a special 5 tier shrine for 5th level spells. (If i'm not mistaken)

The pyramid can be thought of as a kind of a shrine with single use. :)

> So let's leave 5th level spells like something ultra valuable and unattainable for the most of cases.

Spell scrolls containing a level 5 spell will not appear miraculously on the adventure map, it is the scenario creator who will place them on the adventure map.
The fact that the hero can transcribe in his magic book a level 5 spell, which he already has, will not change the fact that he must first obtain the famous spell scroll containing the spell.

> Also, I don't like "eagle eye" skill having different values for studying spells. Players always be in a mess. "What level can they learn by advanced skill? 3? And what scrolls? 4?"
It should be simple: the same level of the skill for the same level of spells, no matter, how player would try to learn it: in a battle or by scroll.

It seems simple to me.

During combat:
Basic: spells level 1 to 2
Advanced: spells level 1 to 3
Expert: spells level 1 to 4

Transcribe the spell, with the required level of Wisdom:
Basic: spells level 1 to 3
Advanced: spells level 1 to 4
Expert: spells 1 to 5
The same level ​​for spells with the same expertise as for the Wisdom skill.

Very easy to understand.

> Also we can try to improve "Eagle Eye" skill in other way.

I also have some tweaks and enhancements that are already planned to improve the Eagle Eye skill. ;)

> we even have such option in CONFIG menu: add scrolar effect for this skill. Originally, this skill was intended to expand the cases for a hero to learn new spells.

I also have a secondary skill suggestion that does the same thing, among other things.

> So my proposal is to make it work only in one way manner. If hero has this skill - only HE can learn spells from other alied heroes' books, that he met on his way, using his sharp eagle eye.

There may also be a settings file for the option that allows the user to choose how the Eagle Eye skill works.
- Only the hero who knows the Eagle Eye skill can learn the spells of the allied heroes he meets.
- The hero who knows the Eagle Eye skill can also teach the spells he knows to other heroes he meets.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , I removed `game: show SDL logo` option.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , I removed game: show SDL logo option.

I removed this option from the first post.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu, I've removed "castle: allow recruits special/expansion heroes" option as it was really imbalanced. Imagine having a Level 1 hero with Spell Power 4 and Knowledge 5 at a normal multiplayer map.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu, I've removed "castle: allow recruits special/expansion heroes" option as it was really imbalanced. Imagine having a Level 1 hero with Spell Power 4 and Knowledge 5 at a normal multiplayer map.

I removed this option from the first post.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , we've removed "world: save count monster after battle" option.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , we've removed "world: save count monster after battle" option.

I removed this option from the first post.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , could you please remove `"heroes: allow pickup objects for patrol"` option as it's not used anywhere anymore after AI changes?

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , could you please remove `"heroes: allow pickup objects for patrol"` option as it's not used anywhere anymore after AI changes?

I removed this option from the first post.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , we recently updated `game: show info system` option to show current time and FPS value. Now this option is more valuable.

**Comment by LeHerosInconnu** [comment]
@ihhub.

> Hi @LeHerosInconnu , we recently updated `game: show info system` option to show current time and FPS value. Now this option is more valuable.

I modified the first post accordingly.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , I removed these options since they don't work:
- hero: allow banned sec. skills upgrade
- battle: high objects are an obstacle for archers

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , I removed these options since they don't work:
> 
> * hero: allow banned sec. skills upgrade
> * battle: high objects are an obstacle for archers

First post updated.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , few buggy options were removed from the code:
- "heroes: surrendering gives some experience"
- "heroes: recalculate movement points after creatures movement"

Could you please update the original post in this issue?

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , few buggy options were removed from the code:
> 
> * "heroes: surrendering gives some experience"
> * "heroes: recalculate movement points after creatures movement"
> 
> Could you please update the original post in this issue?

First post updated.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu  and @Branikolog , I'm thinking that we should make `heroes: in Arena can choose any of primary skills` option by default and remove it completely since the original game might just contain the bug. What do you think?

**Comment by Branikolog** [comment]
Hi, @ihhub 
Well... On one hand, developers of the OG could consider knowledge as ultimate primary attribute and they didn't want players to excessively rise this important skill.
On the other hand, I'm 101% sure no one would even notice that, as receiving each type of primary skill is quite expectable from this type of object.
So, my word:
This will have an influence on original gameplay. But I don't mind if it really appears there.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

I've edited the original post and added some remarks for the options that could be removed and those possibly integrated with a direct access with a keyboard key.

Regarding the Morale and Luck artifacts option, it has been completely removed.
Is this temporary?
I think the ability to cumulate the effects of multiple copies of the same Morale and Luck artifact is a good option in my opinion because it reduces micromanagement between heroes and reduces the frustration of having artifacts taking up space for nothing.
Personally, I was using this option. :)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , to keep AI development going on we have to limit the number of these options as every such option adds more complexity for AI logic. For now this option is removed completely. We'll review all these options once we have a standle logic and AI.

**Comment by BlkSwnNoir** [comment]
Not sure that this is the proper place still

Similar to HOMM3, optional setting to auto bypass "One or more hero may still move..."

![image](https://user-images.githubusercontent.com/103940477/163848468-f7b4446b-bf19-4e66-9c80-c828070a3218.png)

**Comment by zenseii** [comment]
> Not sure that this is the proper place still
> 
> Similar to HOMM3, optional setting to auto bypass "One or more hero may still move..."
> 
> ![image](https://user-images.githubusercontent.com/103940477/163848468-f7b4446b-bf19-4e66-9c80-c828070a3218.png)

Personally I would prefer a key to make a hero "sleep" so that you wouldn't get reminded of that specific hero. Also until 1.0 as a rule there won't be added any more experimental options, and beyond that I believe the plan is to keep options as few as possible.

**Comment by LeHerosInconnu** [comment]
Hello @BlkSwnNoir and @zenseii,

> > Not sure that this is the proper place still
> > Similar to HOMM3, optional setting to auto bypass "One or more hero may still move..."
> 
> Personally I would prefer a key to make a hero "sleep" so that you wouldn't get reminded of that specific hero. Also until 1.0 as a rule there won't be added any more experimental options, and beyond that I believe the plan is to keep options as few as possible.

In fheroes2, it is already possible to change the state of the hero to "sleeping" with the "z" key on the keyboard.
In this state the hero is ignored when the user uses the buttons "Next Hero" and "End turn".

Related discussion: https://github.com/ihhub/fheroes2/discussions/4763.

**Comment by zenseii** [comment]
> Hello @BlkSwnNoir and @zenseii,
> 
> > > Not sure that this is the proper place still
> > > Similar to HOMM3, optional setting to auto bypass "One or more hero may still move..."
> > 
> > 
> > Personally I would prefer a key to make a hero "sleep" so that you wouldn't get reminded of that specific hero. Also until 1.0 as a rule there won't be added any more experimental options, and beyond that I believe the plan is to keep options as few as possible.
> 
> In fheroes2, it is already possible to change the state of the hero to "sleeping" with the "z" key on the keyboard. In this state the hero is ignored when the user uses the buttons "Next Hero" and "End turn".
> 
> Related discussion: #4763.

Thanks! Every day I learn something new! In that case I don't think an option to disable this reminder all together is necessary. If someone cares that much it shouldn't be hard to disable in the source code, in my opinion. Most HOMM games don't let you disable it anyway, but they do have that sleep function.
