### ISSUE TITLE
Abandoned Mine, info window

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1274]
In fheroes2, when the hero is positioned on the entrance to the abandoned mine, after the combat with the ghosts, and the player right-clicks on part of the mine, the information window does not indicate the type of the mine.

Also, in the original game, the window is displayed over the mouse cursor, the cursor is no longer visible.
In fheroes2, the window is displayed next to the cursor.

In the original game:

![Abandoned mine info 01](https://user-images.githubusercontent.com/43583994/90628218-87e3be80-e21d-11ea-88dc-e1f6694dd93a.png)

![Abandoned mine info 02](https://user-images.githubusercontent.com/43583994/90628235-8d410900-e21d-11ea-9022-ba1a8b222ae0.png)

In fheroes2:

![Abandoned mine info 03](https://user-images.githubusercontent.com/43583994/90628248-93cf8080-e21d-11ea-8d5f-030f272156e8.png)

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu !
A window appearing after right click over an object, was made in a bit different way in fheroes2 . It appears next to cursor, so that player could definitely know, what object on a world map he had checked. It can help, when there're several same looking objects (ex: neutral creatures) placed too close to each other.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

I really prefer the way it works in the original game.
The object is located just below the position where the user clicks, the user does not need to change the direction of his gaze to see the information in the window.
This is much more functional from an ergonomic point of view.
I highly recommend making it work the same as in the original game for this reason.
