### ISSUE TITLE
Mine, info window, moving the mouse cursor

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1278]
In fheroes2, when the player right clicks to display the mine information window, the mouse cursor is displayed when the player moves the mouse cursor around the screen.
In the original game, the mouse cursor is no longer displayed on the screen, the mouse cursor is hidden by the information window, and it is not displayed when the player moves the mouse cursor around the screen.

In fheroes2:

![Mine, info window, moving the mouse cursor 01](https://user-images.githubusercontent.com/43583994/90633757-e5303d80-e226-11ea-9a86-23851a8f8ae3.png)

**Comment by ihhub** [comment]
Closing this issue as it was fixed some time ago.
