### ISSUE TITLE
Graveyard, alternative background

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1279]
In fheroes2, the background of the graveyard is not the same as in the original game.
Also, in the original game, the battlefield is adapted to the terrain where the graveyard is located, and this is not the case in fheroes2.

Since this is not the same as in the original game, I suggest that an option be added for this:
"Game: Use an alternative background for the Graveyard."
And backgrounds adapted to each type of terrain where the graveyard is located must therefore be created.

In the original game:

![Graveyard, alternative background 01](https://user-images.githubusercontent.com/43583994/90647812-0863e880-e239-11ea-86d7-0cc39347a5b2.png)

![Graveyard, alternative background 03](https://user-images.githubusercontent.com/43583994/90647838-0f8af680-e239-11ea-80af-bababa8e7f72.png)

In fheroes2:

![Graveyard, alternative background 02](https://user-images.githubusercontent.com/43583994/90647857-174a9b00-e239-11ea-8a2f-14a2238952b4.png)

**Comment by Branikolog** [comment]
@LeHerosInconnu 
I really like this type of battlefield. 
I think minor enhancements such as separate graveyard battlefield or abandoned mine animation should take place in fheroes2 project. As they were taken from the original free demo version.

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

I find that this graveyard screen is not at the same level of visual quality as the rest of the game, which is certainly why it was not integrated in the final version.
Also, the scenery encroaches on the battlefield when the grid is displayed, which is not the most beautiful effect.

![Crappy graveyard background with grid](https://user-images.githubusercontent.com/43583994/90675622-027eff00-e25b-11ea-812c-bbe85f14edab.png)

If this screen were to be integrated into fheroes2, it would have to be reworked.
And it would also need versions for all types of terrain.
For my part, I prefer a visual related to the type of terrain on which the graveyard is located.

I don't like this animation with the ghosts above the abandoned mines either.
In addition it can mislead the player with the animation of mines guarded by ghosts using the Haunt spell.
To respect the original game, I would remove the animation above the abandoned mines from fheroes2.
