### ISSUE TITLE
Compare dialogs when an army is not joinable

### ISSUE THREAD

**Issue by bjauny** [ihhub/fheroes2#128]
Related to #56
From the FIXMEs in `src/fheroes2/battle/battle_dialog.cpp` and `src/fheroes2/pocketpc/pocketpc_castle.cpp`

This one is a bit obscure. We need to compare the original message when troops can't join an army.

Is it possible that `CanJoinTroops` returns false for something else than a full army?
Is the original message completely different?

**Comment by ihhub** [comment]
This issues is not valid anymore.
