### ISSUE TITLE
Sawmill, info window, mouse cursor position on the sawmill and right click, and Dragon City

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1281]
In fheroes2, depending on the position of the mouse cursor when the player clicks on a sawmill, there is not the same information available in the displayed information window.
In the original game, there is always the same information available in the displayed information window.

Also, when the sawmill is located near a dragon city, the information window of the dragon city is displayed instead of that of the sawmill.
This bug is also present in the original game.

In fheroes2:

![Sawmill, info window, mouse cursor position on the sawmill and right click, and Dragon City 01](https://user-images.githubusercontent.com/43583994/90653308-4e23af80-e23f-11ea-89d3-6dcb14ea42ed.png)

![Sawmill, info window, mouse cursor position on the sawmill and right click, and Dragon City 02](https://user-images.githubusercontent.com/43583994/90653327-5380fa00-e23f-11ea-86b2-c080f0d31b8b.png)

![Sawmill, info window, mouse cursor position on the sawmill and right click, and Dragon City 03](https://user-images.githubusercontent.com/43583994/90653350-5976db00-e23f-11ea-96ae-74678cf2853a.png)

**Edit 2021/04/28.**

Similar behavior for information related to a hero ("(not visited)", "(already visited)") when another hero is positioned on a large object (an object that occupies several squares and part of which is directly accessible with the mouse cursor).

In fheroes2:

![Large objet info window for hero fh2 01](https://user-images.githubusercontent.com/43583994/116282933-a2e2d700-a78b-11eb-894d-187a2043406e.png)

**Comment by idshibanov** [comment]
Hi @LeHerosInconnu,

Please take a look at comments in existing ticket #660. It covers all cases like this, no need for a separate issue for each map object. This is a limitation of map data structure in original game that I'm not sure how we should get around it. 

Hopefully by the time we reach 1.0 we'll find a way.

**Comment by LeHerosInconnu** [comment]
Hello @idshibanov,

Yes ok, thanks for the explanation.
I also hope you find the solution.
