### ISSUE TITLE
Magic book, display of the information text when the magic book is open and when the mouse cursor is not positioned over the bookmarks

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1283]
In fheroes2, it is not the same text that is displayed in the info bar at the bottom of the screen when the magic book is open.
The text displayed in the original game is: "View Spells".
The text displayed in fheroes2 is: "Open Book".

In the original game:

![Magic book, spells position 01](https://user-images.githubusercontent.com/43583994/90655368-c7240680-e241-11ea-98fc-57d449c2e7dd.png)

In fheroes2:

![Magic book, spells position 02](https://user-images.githubusercontent.com/43583994/90655397-cdb27e00-e241-11ea-8d33-6dd3b82dc0d6.png)

There is also a bug when the mouse cursor is positioned over bookmarks when the magic book is open.
This bug is already reported here: https://github.com/ihhub/fheroes2/issues/51

**Comment by ihhub** [comment]
This issue was fixed some time ago.
