### ISSUE TITLE
Redundant embranchments of frames around status window

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1286]
When game is running on any higher that 640x480 resolution, we can see two embranchments of the status window frame. 
![UI frame](https://user-images.githubusercontent.com/55348946/90677637-504d3480-e266-11ea-8146-1a064477a345.jpg)

**Comment by a1exsh** [comment]
The parts are coming from the original border image (`advbord`) apparently:

![image](https://user-images.githubusercontent.com/489601/130409866-a4afe991-1711-4f1e-bca8-1f87c1d1f339.png)
![image](https://user-images.githubusercontent.com/489601/130409838-9601d054-79e4-448e-b0ec-cfc1d7a53429.png)

Not sure how to fix that yet.

**Comment by Branikolog** [comment]
@a1exsh 
True.
This issue is more about drawing job for artists... Or we can try to catch other part of the frame (without that joints) and draw it over a problematic place...

**Comment by a1exsh** [comment]
Working on a fix.

**Comment by a1exsh** [comment]
While investigating, I've noticed a related problem at the junctions of middle/right and bottom borders, that is specific to some resolutions (800x600, 1920x1080), but not others (1024x768, 1280x960).

800x600 :stop_sign: :
![image](https://user-images.githubusercontent.com/489601/132939718-7af5aba5-c12c-4df0-ad68-02dbfc37f921.png)

1024x768 :heavy_check_mark: :
![image](https://user-images.githubusercontent.com/489601/132939765-c406119b-4c25-4912-bafa-3afc683b1809.png)
