### ISSUE TITLE
Village's shadow doesn't change after a castle was built

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1288]
After player builds a castle the shadow near city remains the same, as it was near village.
![City shadow](https://user-images.githubusercontent.com/55348946/90760140-1c1b5780-e2ea-11ea-8714-bde284a04a6a.jpg)
![City shadow2](https://user-images.githubusercontent.com/55348946/90760075-0017b600-e2ea-11ea-9212-8a5b0994b57c.jpg)
A shadow near city with castle looks like that:
![City shadow3](https://user-images.githubusercontent.com/55348946/90759966-dced0680-e2e9-11ea-8449-659b7bb9744f.jpg)

**Comment by idshibanov** [comment]
Small note: new fix won't salvage the savegames made before 0.8.2 because data is corrupted there already (wrong map tiles saved).
