### ISSUE TITLE
Credits info is incorrect

### ISSUE THREAD

**Issue by bjauny** [ihhub/fheroes2#129]
Accessing the credits from the main menu, the displayed info needs updating.

**Comment by ihhub** [comment]
@bjauny could you please elaborate what's exactly wrong with credits and how should we change to?

**Comment by bjauny** [comment]
Yes, will do when back home.

**Comment by bjauny** [comment]
Faulty credits lines are:
`AI engine: empty, license: GPL` (is it GPL or GPL v2? What is empty?)
`Site project:` is the sourceforge URL
Not sure about `Authors`. It says `Andrey Afletdinov, maintainer` and `fheroes2@gmail.com`.

**Comment by ihhub** [comment]
Fixed in [71c2a8c38cb985e8a9d9166bcc58a508d3582edd](https://github.com/ihhub/fheroes2/commit/71c2a8c38cb985e8a9d9166bcc58a508d3582edd)
