### ISSUE TITLE
Wrong mouse cursor over allied hero when not reachable due to fog of war

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1292]
In fheroes2, the helmet mouse cursor is displayed when the selected hero cannot reach a friendly hero due to fog of war.
In the original game, the helmet mouse cursor appears only when the mouse cursor is positioned over the selected hero.

In the original game:

![Wrong mouse cursor over allied hero when not reachable due to fog of war 01](https://user-images.githubusercontent.com/43583994/90789596-5e9f5d00-e307-11ea-8c1a-398068bbc2b5.png)

In fheroes2:

![Wrong mouse cursor over allied hero when not reachable due to fog of war 02](https://user-images.githubusercontent.com/43583994/90789631-6959f200-e307-11ea-92d9-9ce545a0c85d.png)

Here is the test scenario file:
[Abandoned mine no victory window.zip](https://github.com/ihhub/fheroes2/files/5098267/Abandoned.mine.no.victory.window.zip)

Select the second hero from the list and position the mouse cursor over a friendly hero.

**Comment by Branikolog** [comment]
If this feature can refine playing experience, i'd like to leave it...
@LeHerosInconnu, can you investigate, if this feature can break playing process in any cases?

**Comment by ihhub** [comment]
This issue is no longer reproducible. I'm closing it.
