### ISSUE TITLE
Priority of display during the animation of sprites of creatures in relation to creatures during combat

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1296]
In fheroes2, during combat, the priority of displaying creatures sprites over enemy creatures when attacking is not visually coherent.
The animation sprites of the creature attacking another creature on the same visual plane should be displayed in the foreground.
It works fine in the original game.

In fheroes2, example with black dragons attacking ghosts:

![Priority of display during the animation of sprites of creatures in relation to creatures during combat 01](https://user-images.githubusercontent.com/43583994/90792178-74fae800-e30a-11ea-9cc2-90c1a6aeb7d6.png)

Here is the test scenario file:
[Abandoned mine no victory window.zip](https://github.com/ihhub/fheroes2/files/5098267/Abandoned.mine.no.victory.window.zip)

**Comment by Branikolog** [comment]
Here I should mention, that when Dragon makes his breath attacking creature from behind, animation works fine. Issue is only for cases, when attack goes from left side from ghosts.
