### ISSUE TITLE
Creature generators on the adventure map should accumulate creatures over the weeks

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1299]
In the original game, creature generators on the adventure map accumulate creatures over the weeks.
In fheroes2, this is not the case.
In fheroes2, there is an option that allows this, but it is not enabled by default: "world: Outer creature dwellings should accumulate units".

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu!
You've done an enormous work in #1272, describing all the features.
You don't need to create new issues, regarding turning on the features, that are currently available, but not in a default state, as you've already talked about it in #1272.

**Comment by idshibanov** [comment]
Also creature growth amount is wrong. I think we should return to default behavior here and remove this option.

**Comment by LeHerosInconnu** [comment]
@idshibanov.

> Also creature growth amount is wrong. I think we should return to default behavior here and remove this option.

Indeed, this option should be enabled by default.

So why not make it work like in the original game and just remove that option.
I doubt anyone who play Heroes 2 will play the game with this option off if he find out about it.
