### ISSUE TITLE
QVGA mode not supported

### ISSUE THREAD

**Issue by bjauny** [ihhub/fheroes2#130]
Related to #56
From the FIXME in `src/fheroes2/dialog/dialog_gameinfo.cpp`.

QVGA mode (resolution < 640x480) is not supported for the game info window.

From what I saw, QVGA is really badly supported, period. I propose we should not support it completely by checking the videomode at startup.

**Comment by ihhub** [comment]
QVGA has no reason nowadays so we could support of it.

**Comment by ihhub** [comment]
Closing this issue as we aren't going to support such low resolution.
