### ISSUE TITLE
Change the name of the "world: use unique artifacts for moral/luck" option and the default state of the option, and adjust the text

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1300]
In the original game, if the hero has several times the same artifact concerning morale and luck, the bonus is only taken into account once.
In fheroes2, if the hero has several times the same artifact concerning morale and luck, he gets the bonus for each artifact.
In fheroes2, there is an option that allows this, but it is not enabled by default: "world: use unique artifacts for moral/luck".
And in fheroes2, when this option is not activated, the info window does not give correct information when the hero has several copies of the same artifact, examples "Medals of Valor +2", "Fizbins of Misfortune -4".

**Edit 2021/01/21.**

For operation comparable to the original game, this option should be renamed "world: several copies of the same artifact are taken into account for Morale and Luck" and disabled by default.

Bug incorrect moral text information:

![Bug incorrect moral text information 01](https://user-images.githubusercontent.com/43583994/90800765-6239e080-e315-11ea-9579-2ccae70772f4.png)

**Comment by vincent-grosbois** [comment]
Just to understand, what is the normal behavior? it is supposed to be cumulated?

**Comment by LeHerosInconnu** [comment]
Hello @vincent-grosbois,

> Just to understand, what is the normal behavior? it is supposed to be cumulated?

In the original game, for Moral and Luck, the same artifact is taken into account only once.

In fheroes2, there is an option that allows to have the same functioning back, but the option is not activated by default.

In fheroes2, when this option is not activated, the text has to be changed to correspond to the accumulation of the same artifact.
For example, if the hero has two copies of the artifact "Medal of Valor", the text should indicate: "Medals of Valor +2" with an "s" for Medals because there are several medals, and the bonus should be adjusted to indicate the correct value for the accumulation of the two artifacts: "+2".

**Comment by vincent-grosbois** [comment]
I see, but is it a bug that it's not activated by default?
Another possibility would be that the option is "allow duplicate effect for artifacts" and it's disabled by default

**Comment by vincent-grosbois** [comment]
Also, for putting the plural in the text box, I really think it's not possible unless there is a huge refacto etc.
It's possible to do something like "Medal of Valor (x2) +4" though

**Comment by LeHerosInconnu** [comment]
@vincent-grosbois.

> I see, but is it a bug that it's not activated by default?

Yes, kind of. :)

> Another possibility would be that the option is "allow duplicate effect for artifacts" and it's disabled by default

Yes, that would be better. :)
It's also on my list of things to change in the "Experimental Game Settings" window.
There are also many other things to change in that window.
But this window is "temporary", and should be improved later.

For operation comparable to the original game, this option should be renamed "world: several copies of the same artifact are taken into account for Moral and Luck" and disabled by default.

**Comment by LeHerosInconnu** [comment]
@vincent-grosbois.

> Also, for putting the plural in the text box, I really think it's not possible unless there is a huge refacto etc.
> It's possible to do something like "Medal of Valor (x2) +4" though

If it takes too much time, your solution may be suitable for now, but with "+2" in the case of the two "Medal of Valor" artifacts. :)

So "Medal of Valor (x2) +2" or "Medal of Valor (2) +2" (without "x").

**Comment by LeHerosInconnu** [comment]
I've changed the title of the issue and the first post for a better concordance.
