### ISSUE TITLE
The hero's magic points should be remembered when the hero retreats or surrenders

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1301]
In the original game, the hero's magic points are memorized when the hero retreats or surrenders.
In fheroes2, the hero recovers all of his magic points when he is recruited.
In fheroes2, there is an option that allows this, but it is not enabled by default: "heroes: remember MP/SP for retreat/surrender result".
In fheroes2, when this option is activated, the hero movement points is also memorized.
However, it is not possible to set the memorization separately for magic points and movement and therefore it is not possible to adjust these parameters to achieve the same setting as in the original game.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , please update #1272 . The option was renamed and effects only move points while spell points work like in the original game (don't restore till next week for an unhired hero).

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , please update #1272 . The option was renamed and effects only move points while spell points work like in the original game (don't restore till next week for an unhired hero).

It's done.
