### ISSUE TITLE
Mage guild building picture is shifted in different way in all cities in a spell window

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1306]
The picture of Mage guild is shifted.
![Mage guild 4](https://user-images.githubusercontent.com/55348946/90890588-f615b600-e3c2-11ea-88ba-1e818b907f78.png)
Especially noticeable for Knight city:
![Mage guild 3](https://user-images.githubusercontent.com/55348946/90890385-8acbe400-e3c2-11ea-9f2e-f0624d808d32.png)
In my opinion, the image is centered considering the building and its shadow. I think each mage guild picture should be drawn in the center part of free space to the left from spells, disregarding shadow.

**Comment by ihhub** [comment]
It is due to a fact that shadow is a part of the image.

**Comment by Branikolog** [comment]
Yes. Exactly.
I think we have to shift image for each case manually...
