### ISSUE TITLE
Enhancement for fonctioning when the castle troops join the defending hero when there is room

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1313]
One enhancement that I've always wanted to have in Heroes 2 is that troops maintain their locations relative to hexes during combat during a siege.

In the original game, if there are no similar troops to the garrisoned ones in the hero's army and there is enough room in the hero's army, the number of creatures in each troop will be kept and troops of the same type will not be reunited.
If there are similar troops to the garrisoned ones in the hero's army, the troops of the same type will be reunited.

However, the position of the troops in the slots in relation to the position of the troops in the hexagons during the combat is not respected.

Two options are added to make this possible:

"Battle: Position of the troops in garrison in relation to the hexagons during the combat is preserved when the garrison troops join the hero who defends the castle when there is room in the hero's army."

"Battle: Troops of the same type in garrison are reunited with the hero's troop of the same type when the garrison troops join the hero who defends the castle even if there is room in the hero's army."

First example:
Hero's army.
First slot: 20 black dragons.

Army in garrison.
Second slot: 5 grand elves.
Fourth slot: 5 grand elves.
Fifth slot: 10 greater druids.

Position of the troops before the combat:

![Options castle troops join the defending hero 01](https://user-images.githubusercontent.com/43583994/90955482-06d73200-e47e-11ea-9545-b8549fe67029.png)

With "Battle: Position of the troops in garrison in relation to the hexagons during the combat is preserved..." option enabled:
The troops maintain their position in relation to the hexagons during combat.

![Options castle troops join the defending hero 02](https://user-images.githubusercontent.com/43583994/90955486-18b8d500-e47e-11ea-8f51-20f7e64db09c.png)

Second example:
Hero's army.
First slot: 20 black dragons.
Second slot: 5 grand elves.
Fifth slot: 5 greater druids.

Army in garrison.
Third slot: 5 grand elves.
Fourth slot: 5 greater druids.

Position of the troops before the combat:

![Options castle troops join the defending hero 03](https://user-images.githubusercontent.com/43583994/90955495-29694b00-e47e-11ea-8860-0227fce53f38.png)

With "Battle: Position of the troops in garrison in relation to the hexagons during the combat is preserved..." and "Battle: Troops of the same type in garrison are reunited with the hero's troop..." options enabled:
The troops maintain their position in relation to the hexagons during combat.
The troops of the same type are reunited only if the "Battle: Troops of the same types in garrison are reunited with the hero's troop..." option is enabled.

![Options castle troops join the defending hero 04](https://user-images.githubusercontent.com/43583994/90955500-2f5f2c00-e47e-11ea-9085-c13cbe1ed722.png)

**Comment by idshibanov** [comment]
I think this should be always enabled rather than option.

**Comment by LeHerosInconnu** [comment]
Hi @idshibanov,

> I think this should be always enabled rather than option. "battle: merge armies for hero from castle" should be removed too as it's useless without an ability to put hero in a guardian slot.

I proposed this as an option because it's different from the original game.
But, yes, it could be integrated directly because it improves the operation without really changing it.

For the option "battle: merge armies for hero from castle", yes, it could be removed because that's the way the original game works.
