### ISSUE TITLE
Number of experience points for early game heroes

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1316]
In fheoes2, all starting heroes have zero experience points.
In the original game, the starting heroes can have some experience points.

**Comment by eos428** [comment]
Is there some sort of algorithm to decide how many exp the starting hero gets and what are the exact numbers?

**Comment by LeHerosInconnu** [comment]
Hi @eos428,

> Is there some sort of algorithm to decide how many exp the starting hero gets and what are the exact numbers?

For my part, I can only give an approximate answer.
Between 40 and 100 experience points.
Maybe @idshibanov could give a more specific answer.

**Comment by LeHerosInconnu** [comment]
Hello @idshibanov,

> Hi @eos428 and @LeHerosInconnu,
> 
> Your estimate is almost on point, the value is random between 40 to 90 experience in the original game.

Thanks for the precision. :)
