### ISSUE TITLE
Check Lighthouse fog clearance

### ISSUE THREAD

**Issue by bjauny** [ihhub/fheroes2#132]
Related to #56
From the FIXME in src/fheroes2/kingdom/world.cpp.

I can only guess that the fog clearance of the lighthouse is different from the original.

**Comment by LeHerosInconnu** [comment]
In the original game, the lighthouse does not reveal additional squares.

In original game:

![Lighthouse fog clearance 01](https://user-images.githubusercontent.com/43583994/91041116-bdb6e780-e60f-11ea-8d57-f149718a36fc.png)

In fheroes2:

![Lighthouse fog clearance 02](https://user-images.githubusercontent.com/43583994/91041290-0f5f7200-e610-11ea-9b2c-767a867e178c.png)
