### ISSUE TITLE
Creature upgrade cost

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1322]
In fheroes2, the cost to upgrade a creature is once the price difference between the two creatures.

I love this change from the original version of the game that sometimes makes the upgrade cost incoherent.
The best example is the cost of upgrading the giant to titan which is higher than the cost of purchasing the titan, a game design mistake for me.
Also this is necessary in fheroes2, as it is possible to buy unimproved creatures when the upgraded creature building is built, which is a very good addition to the original game and allows for new strategies.

However, in the original game, the cost to upgrade a creature is twice the price difference between the two creatures.
To enable the original game's operating mode, it is therefore necessary to add an option to the game:
"Game: The cost to upgrade a creature is only once the price difference between the two creatures."
And this option should be unchecked by default.

**Comment by idshibanov** [comment]
In my opinion some improvements should be enabled by default and this is one of them.

I don't think most players will want full original experience with all bugs and mistakes of the past. Not everybody will look for settings and will find the option to enable it. Also we should avoid adding to much options because it will clutter the GUI.

It is bad design if you have 100 small things to enable to enjoy the game.

**Comment by LeHerosInconnu** [comment]
@idshibanov.

Personally, I'm happy with the way this works in fheroes2 currently.
My goal here was to carry over the difference with the original version. :)

And I already have some ideas to improve the handling of options in the graphical user interface.
But it will be for the Beyond 1.0 version.

**Comment by bleakley** [comment]
Another possibility is to make the cost equal to twice the difference, but not to exceed the cost of the more expensive creature.

**Comment by LeHerosInconnu** [comment]
Hello @bleakley,

> Another possibility is to make the cost equal to twice the difference, but not to exceed the cost of the more expensive creature.

I consider the double difference in the cost of upgrading the creatures a flaw in the original game.

And as @idshibanov mentioned, I doubt that even the most purist Heroes 2 players would want to enable this option if it were available in the game.
I don't think there's any need to add this option to fheroes2.
And if there's a very high demand for it, it will always be possible to add it later, but I doubt it. :)
Anyway, thanks for your suggestion. :)

**Comment by Branikolog** [comment]
@LeHerosInconnu 

> I consider the double difference in the cost of 
upgrading the creatures a flaw in the original game.

I suppose, original dev team implemented such price for upgrading to nerf diplomacy skill in a such strange way. So player, that accidentally was joined by non-upgraded creatures, will have to pay even  more gold, to make them join his upgraded army...

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> @LeHerosInconnu
> 
> > I consider the double difference in the cost of
> > upgrading the creatures a flaw in the original game.
> 
> I suppose, original dev team implemented such price for upgrading to nerf diplomacy skill in a such strange way. So player, that accidentally was joined by non-upgraded creatures, will have to pay even more gold, to make them join his upgraded army...

I rather think it's a way to "force" the player to build the upgraded buildings in all his castles.

Otherwise, the player could have built for example a single Upg. Cloud Castle and upgrade the Giants recruited in his other Wizard castles in the castle where the Upg. Cloud Castle is built.
And that could have resulted in boring micromanagement; not very good for the game, nor for the players. :)

In my mod, I plan to make the construction of upgraded buildings interesting to counter this possible boring micromanagement, and the player won't need to work on it. :)

Diplomacy is not so powerful, it's just that it allows to recruit troops "on the way" instead of "waiting" for the troops recruited in the castle (the hero has to travel more distance for the troops recruited in the castle).

By the way, gold is limited in Heroes 2 and the player has to make a choice, buy troops from the castle or recruit troops with Diplomacy, it's hard to do both.

The benefit of the Diplomacy skill is, in a way, to bring a gain in time.

Also in its current state, its use is complicated to manage and practice because only the Expert level is really interesting.
And the cost of troops to recruit quickly becomes very important, because the number of creatures in the wandering troops is increasing rapidly; the player must plan a solid economy to use the Diplomacy skill.

In my mod, I plan to modify the Diplomacy skill to make it interesting from the Basic level on. :)

**Comment by Branikolog** [comment]
I think, up to upcoming 1.0 release we should make creature upgrade cost completely the same to the OG (2x).

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

> I think, up to upcoming 1.0 release we should make creature upgrade cost completely the same to the OG (2x).

If this is to happen, it is imperative to offer only the difference in upgrade cost as an option.
And this is also beneficial for AI.

**Comment by ihhub** [comment]
AI does not benefit from any options. Each added option actually increases the complexity of AI code which would be really hard to maintain.
