### ISSUE TITLE
Name of the shipyard in the castle screen

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1324]
Just to point out that the name given to the shipyard is not the same as in the original game when the mouse cursor is positioned over the building built in the castle.
Personally, I always found this odd in the original game, but some purists might point out. :)

In the original game:

![Name of the shipyard in the castle screen 01](https://user-images.githubusercontent.com/43583994/90975640-56793480-e536-11ea-962a-eb0837eb3fe5.png)

In fheroes2:

![Name of the shipyard in the castle screen 02](https://user-images.githubusercontent.com/43583994/90975650-6c86f500-e536-11ea-853c-97af7c143cbe.png)

**Comment by ihhub** [comment]
I'm closing this issue as @LeHerosInconnu prefers what is in the game as well.
