### ISSUE TITLE
Dimension Door spell, cost in movement points

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1325]
In fheroes2, the cost in movement points for casting the dimension door spell is one movement point on grass (100 points).

In the original game, the cost in movement points is higher.
For example, with a creature of speed 6, the hero can move horizontally 14 movements on grass (14 x 100 points).
By casting the dimension door spell several times in a row, the number of hero movement points available after each spell is cast for horizontal movement is as follows:
14/11/9/7/5/2/0.

**Comment by idshibanov** [comment]
Dimension door and town portal movement cost is 125, both in original game and in fheroes2 master branch. Was fixed in #1208. I'll close after validation.

**Comment by LeHerosInconnu** [comment]
Hello @idshibanov,

Are you sure of the value for the original game?
It seems to be more like 225 points in the original game.

14/11/9/7/5/2/0:
1400 - 225 = 1175 --> 11 moves on grass
1175 - 225 = 950 --> 9 moves on grass
950 - 225 = 725 --> 7 moves on grass
725 - 225 = 500 --> 5 moves on grass
500 - 225 = 275 --> 2 moves on grass
275 - 225 = 50 --> 0 move

**Comment by idshibanov** [comment]
Correct, 225, made a typo. That's the new value in heroes_spell.cpp.

**Comment by LeHerosInconnu** [comment]
Okay, thanks for the clarification.
