### ISSUE TITLE
Dimension Door spell, objects passability

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1327]
In fheroes2, the dimension door spell travel distance bug present in the original game has been fixed.
In the original game, the hero can teleport seven squares away to the west and north but only six squares to the east and south.

But in the original game, the hero can position himself on certain objects when moving while walking.
And in the original game, the hero can also position himself on these emplacements when he uses the dimension door spell to move.

In fheroes2, this is not respected.

In the original game:

![Dimension Door spell, objects passability 01](https://user-images.githubusercontent.com/43583994/90981818-6e1ae200-e563-11ea-8a1f-3dffc8c2d49d.png)

![Dimension Door spell, objects passability 02](https://user-images.githubusercontent.com/43583994/90981820-73782c80-e563-11ea-9c58-61c0367872f6.png)

![Dimension Door spell, objects passability 03](https://user-images.githubusercontent.com/43583994/90981825-77a44a00-e563-11ea-89a9-701de56c7c38.png)

![Dimension Door spell, objects passability 04](https://user-images.githubusercontent.com/43583994/90981828-7d9a2b00-e563-11ea-9d8e-ce69002f8ddd.png)

In fheroes2:

![Dimension Door spell, objects passability 05](https://user-images.githubusercontent.com/43583994/90981833-82f77580-e563-11ea-9391-f0224f6e4194.png)

![Dimension Door spell, objects passability 06](https://user-images.githubusercontent.com/43583994/90981836-868afc80-e563-11ea-9098-2559aba68b2b.png)

![Dimension Door spell, objects passability 07](https://user-images.githubusercontent.com/43583994/90981839-8b4fb080-e563-11ea-9e57-f93aa6c54f4f.png)

Here is the test scenario file:
[Dimension Door spell, objects passability.zip](https://github.com/ihhub/fheroes2/files/5114152/Dimension.Door.spell.objects.passability.zip)

**Comment by Branikolog** [comment]
I believe, that this issue is similar to #496.

**Comment by LeHerosInconnu** [comment]
Hi @Branikolog,

Yes, it is certainly the same bug.
I saw this issue, but I did not make the connection. :)
