### ISSUE TITLE
"City of the Dead" recruit issue

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1331]
While buying troops in the City of the Dead we can see wrong info:
![Liches](https://user-images.githubusercontent.com/55348946/91036405-f5259400-e60f-11ea-8cec-36ea861a0761.png)
Also, the ammount of available Liches is 3. While in the OG you can recruit 5.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu, do you know the exact amount of Liches in the original game?

**Comment by LeHerosInconnu** [comment]
@ihhub.

> Hi @LeHerosInconnu, do you know the exact amount of Liches in the original game?

I did three tests for this.
Here are the results:

Heroes 2.
City of the Dead.

Test 01:

5 Power Liches Month 1 Week 1,

2 Power Liches available Month 1 Week 2,
1 Power Liche available Month 1 Week 3,
3 Power Liches available Month 1 Week 4,

0 Power Liche available Month 2 Week 1 (month of the plague),
3 Power Liches available Month 2 Week 2,
1 Power Liche available Month 2 Week 3,
1 Power Liche available Month 2 Week 4,

3 Power Liches available Month 3 Week 1,
3 Power Liches available Month 3 Week 2,
2 Power Liches available Month 3 Week 3,
3 Power Liches available Month 3 Week 4,

3 Power Liches available Month 4 Week 1,
2 Power Liches available Month 4 Week 2,
2 Power Liches available Month 4 Week 3,
3 Power Liches available Month 4 Week 4,

3 Power Liches available Month 5 Week 1,
1 Power Liche available Month 5 Week 2,
1 Power Liche available Month 5 Week 3,
2 Power Liches available Month 5 Week 4.

Test 02:

6 Power Liches Month 1 Week 1,

3 Power Liches available Month 1 Week 2,
3 Power Liches available Month 1 Week 3,
1 Power Liche available Month 1 Week 4,

1 Power Liche available Month 2 Week 1 (month of the plague),
2 Power Liches available Month 2 Week 2,
1 Power Liche available Month 2 Week 3,
3 Power Liches available Month 2 Week 4,

2 Power Liches available Month 3 Week 1,
3 Power Liches available Month 3 Week 2,
3 Power Liches available Month 3 Week 3,
1 Power Liche available Month 3 Week 4,

3 Power Liches available Month 4 Week 1 (Lich population doubles, normally not affected by this),
2 Power Liches available Month 4 Week 2,
2 Power Liches available Month 4 Week 3,
1 Power Liche available Month 4 Week 4,

2 Power Liches available Month 5 Week 1,
2 Power Liches available Month 5 Week 2,
3 Power Liches available Month 5 Week 3,
1 Power Liche available Month 5 Week 4.

Test 03:

4 Power Liches Month 1 Week 1,

2 Power Liches available Month 1 Week 2,
1 Power Liche available Month 1 Week 3,
1 Power Liche available Month 1 Week 4,

2 Power Liches available Month 2 Week 1,
3 Power Liches available Month 2 Week 2,
2 Power Liches available Month 2 Week 3,
1 Power Liche available Month 2 Week 4,

2 Power Liches available Month 3 Week 1,
3 Power Liches available Month 3 Week 2,
1 Power Liche available Month 3 Week 3,
1 Power Liche available Month 3 Week 4,

3 Power Liches available Month 4 Week 1,
2 Power Liches available Month 4 Week 2,
2 Power Liches available Month 4 Week 3,
2 Power Liches available Month 4 Week 4,

3 Power Liches available Month 5 Week 1,
3 Power Liches available Month 5 Week 2,
3 Power Liches available Month 5 Week 3,
1 Power Liche available Month 5 Week 4.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , thanks a lot! Looks like it's random as in our project.

@Branikolog please test the changes and close the issue if no other changes required.

**Comment by LeHerosInconnu** [comment]
@ihhub.

> Hi @LeHerosInconnu , thanks a lot! Looks like it's random as in our project.

In fheroes2, this appears to be always 3 Power Liches.

3 Power Liches Month 1 Week 1,

3 Power Liches available Month 1 Week 2,
3 Power Liches available Month 1 Week 3,
3 Power Liches available Month 1 Week 4.

**Comment by Branikolog** [comment]
> In fheroes2, this appears to be always 3 Power Liches.

For me seemes to be too...

**Comment by LeHerosInconnu** [comment]
In Heroes 2, there always seems to be 4, 5, or 6 Power Liches on the first visit.
Then 1, 2 or 3 Power Liches are added at the beginning of each week after the first visit (I did a test over twelve months of play for this).

For the month of the plague, I'm not sure.

Apparently there may be Power Liches added even when the month of the plague occurs.
"0 Power Lich" and "1 Power Lich" in the tests performed.

It seems that the City of the Dead gets the growth of the week but then undergoes the halving of the population already present.
This would explain "0 Power Lich", growth of 1 Power Lich reduced by half, so 0.5 Power Lich rounded down to 0 Power Lich.
And "1 Power Lich", growth of 2 Power Liches reduced by half, so 1 Power Lich, or growth of 3 Power Liches reduced by half, so 1.5 Power Lich rounded down to 1 Power Lich.

The events "Power Lich population doubles!" and "Power Lich growth +5." must affect the City of the Dead.

**Comment by ihhub** [comment]
Hi @Branikolog , please the issue as the original bug is fixed.

**Comment by Branikolog** [comment]
@ihhub, great job!
