### ISSUE TITLE
Navigation skill

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1332]
In the original game, there is a bug with the hero's movement on the ocean and the navigation skill.

Without the navigation skill, the hero has the maximum displacement of 15 moves (1500 points), and the speed of creatures in his army is never taken into account.

The basic level navigation skill gives 1/3 additional movements.
This means that the hero should be able to move 15 moves + (1/3 of 15 moves) = 20 moves.
However, in the original game, the hero can only move 19 moves.

The same bug appears with the advanced level navigation skill which gives 2/3 additional movements.
The hero should be able to move 15 moves + (2/3 of 15 moves) = 25 moves.
But the hero can only move 24 moves.

For the expert level navigation skill, it works correctly and the hero can move 30 moves.

In fheroes2, the bug has not been fixed and it works the same as in the original game.
The hero have 19 moves (1995 points) instead of 20 moves (2000 points).

![Heroes, navigation skill and lighthouse 01](https://user-images.githubusercontent.com/43583994/91038919-e937d300-e60b-11ea-9406-e59e761529e1.png)

**Comment by Branikolog** [comment]
Hello, @LeHerosInconnu.
Could you make separate topics for such issues in future, please?
Here you've found four different substantive bugs:
Name mistake (text bug)
Movement points over the sea(logic bug)
Increasing of movement points(Lighthouse bug)
Displaying the number of Lighthouses under control(UI bug)
A separate person would work on each of these issues, so it would be a mess in this topic.

**Comment by LeHerosInconnu** [comment]
Hi @Branikolog,

Yes, okay.
And if necessary, I can separate this topic into four issues.
It shouldn't take me too long to do this.

**Comment by Branikolog** [comment]
@LeHerosInconnu 

> And if necessary, I can separate this topic into four issues.

That's would be nice!

**Comment by LeHerosInconnu** [comment]
> @LeHerosInconnu
> 
> > And if necessary, I can separate this topic into four issues.
> 
> That's would be nice!

@Branikolog.

It's done.

**Comment by Branikolog** [comment]
Thank you, @LeHerosInconnu!
Your contribution to our project makes us closer to a success!
