### ISSUE TITLE
Display of the attack cursor sprite during combat

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1336]
In fheroes2, when a troop is blocked by opposing troops and wants to attack one of these troops in melee, the attack cursor sprite is displayed only when the mouse cursor is positioned in the adjacent part closest to the hexagon where the troop to attack is located.

In the original game, it is possible to position the mouse cursor over the entire hexagon so that the attack cursor sprite is displayed.

In original game:

![Display of the attack sprite during combat 01](https://user-images.githubusercontent.com/43583994/91158023-5dcf4800-e6c6-11ea-9b8a-51a255cabe97.png)

In fheroes2:

![Display of the attack sprite during combat 02](https://user-images.githubusercontent.com/43583994/91158046-645dbf80-e6c6-11ea-9581-d1635097a1a7.png)

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu 
I think, this issue is a particular case of #2497 issue.
Can we close this issue, as we have more detailed one?

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> Hi, @LeHerosInconnu
> I think, this issue is a particular case of #2497 issue.
> Can we close this issue, as we have more detailed one?

Yes, it's done.
