### ISSUE TITLE
Hill Fort message window, upgrade text

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1339]
In fheroes2, the names of the creatures are not written in the text in the same order as in the original game.
In addition, the word "and" is missing twice in the text of fheroes2.

In the original game:

"...Ogres, Orcs, and Dwarves..."
"...Ogre Lords, Orc Chiefs, and Battle Dwarves."

![Additional message window with greater width 05](https://user-images.githubusercontent.com/43583994/91166874-53677b00-e6d3-11ea-8103-ba8c195b56e6.png)

In fheroes2:

"...Dwarves, Orcs, Ogres..."
"...Battle Dwarves, Orc Chiefs, Ogre Lords."

![Additional message window with greater width 03](https://user-images.githubusercontent.com/43583994/91166886-58c4c580-e6d3-11ea-9c17-e675c483ee83.png)

**Edit 2020/11/21.**

The text must be:

"...Ogres, Orcs and Dwarves..."
"...Ogre Lords, Orc Chiefs and Battle Dwarves."

Instead of:

"...Dwarves, Orcs, Ogres..."
"...Battle Dwarves, Orc Chiefs, Ogre Lords."

**Comment by github-contributor-1** [comment]
Can I work on the text part ?
