### ISSUE TITLE
Simplify MP2::isXXXLife functions

### ISSUE THREAD

**Issue by bjauny** [ihhub/fheroes2#134]
Related to #56
From the FIXMEs in `src/fheroes2/maps/mp2.cpp`.

Make const maps in unnamed namespace with the lifecycle of the impacted objects to simplify the functions.

**Comment by Tetrergeru** [comment]
I want to try it, if you don't mind

**Comment by ihhub** [comment]
@Tetrergeru sure!

**Comment by Tetrergeru** [comment]
#171 Sorry that it took so long. Should I fix incompatibility with c++98, that makes travis to fail the build?

**Comment by bjauny** [comment]
If I remember correctly (@ihhub will confirm) C++11 compatibility is not on the menu right now so: yes, make it C++98 compliant.

**Comment by andrey-starodubtsev** [comment]
@bjauny, that's correct - code is C++98 compliant at the moment.

@ihhub, I don't quite understand what has to be done here. Alas, project was imported without history to github, but original repository is still available at https://sourceforge.net/p/fheroes2/code/HEAD/tree/; these `FIXME` comments were added in

```
------------------------------------------------------------------------
r710 | afletdinov | 2008-12-11 08:58:57 +0300 (Чт, 11 дек 2008) | 1 line

new version AI engine, add options for current player color, update radar, more files update...
------------------------------------------------------------------------
```

and no reference to what was planned to be added/fixed.

Judging by the final code `switch` with several cases will be faster than filling `std:map`. One can easily check this statement using https://godbolt.org/ - `switch` statement wit `-O3` boils down to 3 assembler commands + table of 256 values for byte selector.

256 bytes is too much? Okay, using `-Os` gets you dozen of commands, which a still much faster than using `std::map`.

So what is planning to be done in this issue?

**Comment by ihhub** [comment]
Hi @andrey-starodubtsev , the project was under **SVN** while GitHub uses **git** so I made easy way to just start from scratch. You are right, I could have migrated history.

Switch optimization is disputable. Replacing it by map makes code looks easy to read only but not always to run it faster. Using map only to replace switch with few cases makes not sense but I saw switch with a lot of cases (look at `bool MP2::isGroundObject(int obj)` function).

I think we could shift this issue into **WishList** category.

**Comment by qarkai** [comment]
Is this issue still relevant (for switches with a lot of cases at least)? I consider simplifying `MP2::GetICNObject`, `MP2::StringObject`, `MP2::isWeekLife` and probably `MP2::GetObjectDirect`.

**Comment by ihhub** [comment]
Hi @qarkai , please hold any changes for this issue. We're changing a lot of stuff in MP2 namespace.

**Comment by qarkai** [comment]
Hi @ihhub, you didn't answer my question. Is this issue still be relevant after "changing a lot of stuff"?

**Comment by ihhub** [comment]
Hi @qarkai , I don't think that this issue is really relevant. Having many cases is not a big problem after all. We also have places with many switch cases as well.

**Comment by qarkai** [comment]
Hi @ihhub, close it then.
