### ISSUE TITLE
Hill Fort message window, creature display order

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1340]
In fheroes2, the creatures are not displayed in the same order as in the original game.

In the original game:

Ogre Lords first, then Orc Chiefs, then Battle Dwarves.

![Additional message window with greater width 05](https://user-images.githubusercontent.com/43583994/91166874-53677b00-e6d3-11ea-8103-ba8c195b56e6.png)

In fheroes2:

The order is reversed, Battle Dwarves first, then Orc Chiefs, then Ogre Lords.

![Additional message window with greater width 03](https://user-images.githubusercontent.com/43583994/91166886-58c4c580-e6d3-11ea-9c17-e675c483ee83.png)

**Comment by Branikolog** [comment]
I'm not sure, that this makes an essential  difference.
Probably, in the OG developers couldn't fit three troops into this window, that's why they've decided to show two more useful (Ogres and Orcs) troops first.
If we'd make three troops' icons fit the window, the order they will be placed - doesn't matter.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> I'm not sure, that this makes an essential difference.
> If we'd make three troops' icons fit the window, the order they will be placed - doesn't matter.

It's a matter of consistency, and convenience in the game.

First the barbarian troops from the highest level to the lowest level, then the sorceress' troop.

This corresponds to the order of the castles in the game:
Knight, barbarian, sorceress, warlock, wizard and necromancer.

> Probably, in the OG developers couldn't fit three troops into this window, that's why they've decided to show two more useful (Ogres and Orcs) troops first.

Dwarves are not to be underestimated compared to ogres and orcs, for example they can resist magic. :)
