### ISSUE TITLE
Hill Fort message window, no troop text

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1341]
In fheroes2 the text is the same as in the original game.
However in the original game, the names of the creatures are not written in the text in the same order as in the text of the creature upgrade window.

In fheroes2, no troop text:
"...Orcs, Ogres, and Dwarves..."

![Additional message window with greater width 07](https://user-images.githubusercontent.com/43583994/91171240-7184a980-e6da-11ea-8bea-3f33a4a7eb41.png)

In the original game, no troop text:
"...Orcs, Ogres, and Dwarves..."

![Additional message window with greater width 06](https://user-images.githubusercontent.com/43583994/91171217-6893d800-e6da-11ea-9d0e-754afb591022.png)

In the original game, upgrade text:
"...Ogres, Orcs, and Dwarves..."

![Additional message window with greater width 05](https://user-images.githubusercontent.com/43583994/91166874-53677b00-e6d3-11ea-8103-ba8c195b56e6.png)

The text of the message that is displayed when there are no troops to upgrade should be changed accordingly.

**Edit 2020/11/21.**

The comma "," with the word "and" is superfluous.
When the word "and" is used, it is not necessary to put a comma ",".

In the example:

"...Ogres, Orcs and Dwarves..."
"...Ogre Lords, Orc Chiefs and Battle Dwarves."

Instead of:

"...Ogres, Orcs, and Dwarves..."
"...Ogre Lords, Orc Chiefs, and Battle Dwarves."

**Comment by Branikolog** [comment]
To my mind the order of the creatures had been shown in the window should be the same, as order written in all text windows above. No matter order it would be.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

Yes that's the goal, display the order of creature names in the text of all windows the same as in the original game's upgrade window:
"... Ogres, Orcs, and Dwarves ...". :)
