### ISSUE TITLE
Lighthouse bonus not applied

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1342]
In fheroes2, there is a bug with the lighthouses.
Controlled lighthouses do not grant movement bonuses on the ocean.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , is the bonus accumulative? I see that in the code we grant 500 extra movement points. Do we need to grant such for each Lighthouse?

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , is the bonus accumulative? I see that in the code we grant 500 extra movement points. Do we need to grant such for each Lighthouse?

Yes, in the original game, the Lighthouse bonuses are added, 500 extra movement points for each Lighthouse.
