### ISSUE TITLE
Sphinx riddle, question window, text layout

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1345]
In fheroes2, the presentation of the text is not the same as in the original game.
In the original game, the layout of the text is much more pleasant to read.

In the original game:

![Sphinx riddle 01](https://user-images.githubusercontent.com/43583994/91208077-efac7480-e709-11ea-962f-68bfbbe6a73f.png)

In fheroes2:

![Sphinx riddle 02](https://user-images.githubusercontent.com/43583994/91208106-fa670980-e709-11ea-9b44-1e9447c3c578.png)

**Comment by ihhub** [comment]
Fixed some times ago.
