### ISSUE TITLE
Sphinx riddle, question window, vertical position of the text in the answer field

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1347]
In fheroes2, the text is not correctly positioned vertically in the answer field.

In the original game:

![Sphinx riddle 01](https://user-images.githubusercontent.com/43583994/91208077-efac7480-e709-11ea-962f-68bfbbe6a73f.png)

In fheroes2:

![Sphinx riddle 02](https://user-images.githubusercontent.com/43583994/91208106-fa670980-e709-11ea-9b44-1e9447c3c578.png)

**Comment by undef21** [comment]
Hello, @LeHerosInconnu. Is it actual bug?
![Снимок экрана_2021-04-15_23-26-21](https://user-images.githubusercontent.com/71143197/114939863-b156f780-9e49-11eb-8acb-b5a46d1d81b7.png)

**Comment by LeHerosInconnu** [comment]
Hi @undef21,

> Hello, @LeHerosInconnu. Is it actual bug?

It seems that this has been corrected.
Thanks. :)
