### ISSUE TITLE
Sphinx riddle, reward window, elements layout

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1348]
In fheroes2, the layout of the elements is not the same as in the original game.

In the original game:

![Sphinx riddle 03](https://user-images.githubusercontent.com/43583994/91208730-eec81280-e70a-11ea-8ec5-ac97deb94246.png)

In fheroes2:

![Sphinx riddle 04](https://user-images.githubusercontent.com/43583994/91208766-fd162e80-e70a-11ea-82f2-d288e13c8345.png)

**Comment by Branikolog** [comment]
So, is the issue in just an adding more space between rewards and the text?

**Comment by LeHerosInconnu** [comment]
@Branikolog.

The framing graphic of the artifact graphic is not at the same horizontal position as in the original game.
The graphic of the artifact is not positioned correctly inside the frame.

The "OKAY" button is not centered horizontally.
The "OKAY" button is not at the same distance vertically from the bottom of the window.
The text does not appear to be centered horizontally either.

I like that the gold coin graphic is vertically centered relative to the artifact framing graphic.
But I wonder if it is really voluntary in view of the disposition of the other elements. ;)
In any case, it would be nice if it stayed centered that way. :)

And yes, a little more space between the text and the graphics would air the window a bit.
In fheroes2, everything seems compressed in this window.

And I think a title should be added to this window. :)
And also for the other windows of the sphinx. :)

**Comment by ihhub** [comment]
Fixed in #1805
