### ISSUE TITLE
Vertical position of the hero in the square on the adventure map

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1349]
In fheroes2, the vertical position of the hero's sprite is shifted by one pixel vertically.

In the original game:

![Vertical position of the hero 01](https://user-images.githubusercontent.com/43583994/91208976-53836d00-e70b-11ea-9a92-ab7a73aa309c.png)

In fheroes2:

![Vertical position of the hero 02](https://user-images.githubusercontent.com/43583994/91209012-5f6f2f00-e70b-11ea-9573-cd583f2e043f.png)

Open the two images in different tabs in your browser, enlarge the images and switch between the two tabs alternately.

![Vertical position of the hero 01 coupé](https://user-images.githubusercontent.com/43583994/91208908-3cdd1600-e70b-11ea-80a6-d14f64979218.png) ![Vertical position of the hero 02 coupé](https://user-images.githubusercontent.com/43583994/91208939-49616e80-e70b-11ea-8657-f390dee41409.png)

**Comment by Branikolog** [comment]
I believe, it's the similar problem to #1311. 
Nevertheless, I leave it as separate issue, as boat is shifted on more than 1 pixel.
