### ISSUE TITLE
Graveyard window, information displayed when the user right clicks on the different elements of the reward 

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1356]
In fheroes2, the player cannot obtain information on the different parts of the reward by right-clicking on them unlike the original game.

In the original game:

![Graveyard window, reward info 01](https://user-images.githubusercontent.com/43583994/91293172-e79b1600-e797-11ea-8fae-2b3ccc8e9810.png)

![Graveyard window, reward info 02](https://user-images.githubusercontent.com/43583994/91293185-ecf86080-e797-11ea-8117-5e096964b757.png)

![Graveyard window, reward info 03](https://user-images.githubusercontent.com/43583994/91293197-f1bd1480-e797-11ea-8913-13d3a6e1c5f3.png)

The bug concerning the information for the artifact is already reported here: https://github.com/ihhub/fheroes2/issues/468

**Comment by Mandras** [comment]
It is fixed right ?

![fheroes1](https://user-images.githubusercontent.com/5680511/156679406-9c1bb7b4-2c2d-4f20-aeec-9533b1d2f052.png)
![fheroes2](https://user-images.githubusercontent.com/5680511/156679408-fb32b5f3-ae8d-4a65-9fa7-024401ec7b2b.png)
![fheroes3](https://user-images.githubusercontent.com/5680511/156679418-841b16ef-56ae-4920-a905-5c2ada273b2c.png)

**Comment by ihhub** [comment]
@Mandras , yes it is :)
