### ISSUE TITLE
Graveyard window, reward text, word "zomies" instead of "zombies"

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1357]
In fheroes2, in the text of the graveyard reward window, there is a misspelling in the word "zombies", the "b" is missing.
In the original game, this fault is also present.

In the original game:

![Graveyard window, reward info 01](https://user-images.githubusercontent.com/43583994/91293172-e79b1600-e797-11ea-8fae-2b3ccc8e9810.png)

In fheroes2:

![Graveyard window, reward info 04](https://user-images.githubusercontent.com/43583994/91295260-1666bb80-e79b-11ea-8ef3-494151c770a6.png)

It might be also better to write "mutant zombies" instead of "zombies" since it is mutant zombies that defend the graveyard.

Also, for the way to write the name of the creatures in the game, with a capital letter at the beginning of the name or not, example "Mutant Zombies" or "mutant zombies", it would be necessary to define a rule and stick to it for all the displayed texts.
I will add an issue for this suggestion.
It's done here: https://github.com/ihhub/fheroes2/issues/1358

**Comment by ihhub** [comment]
Let's stick to Zombies for now. I'll fix it.
