### ISSUE TITLE
Sphinx riddle, challenge window, add "Sphinx" as the title of the window

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1363]
I suggest adding the title "Sphinx" to this window.

In the original game, this window also has no title.

![Sphinx riddle, challenge 01](https://user-images.githubusercontent.com/43583994/91300117-0652da00-e7a3-11ea-9388-fd395fa73abf.png)

**Comment by Branikolog** [comment]
Well, #1362 and #1361 are all about the same issue.)
You shouldn't have done three separate issues, and simply make one thread with three screened windows there.
For the future. ;)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

I will see for the next time. :)
