### ISSUE TITLE
Graveyard window, reward window, elements layout

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1366]
In fheroes2, the framing graphic of the artifact graphic is not at the same horizontal distance related to the nearest edge of the window as in the original game.
The graphic of the artifact is not positioned correctly inside the frame.
The horizontal spacing is not the same for the two graphics related to the edges of the window.

The "OKAY" button is not centered horizontally.
The "OKAY" button is not at the same distance vertically from the bottom of the window.

A little more space between the text and the graphics would air the window a bit.

I like the fact that the artifact graphic is positioned on the left side of the window unlike the original game where it is located on the right side of this window.
The title added to this window is also welcome.

In the original game:

![Graveyard window, reward info 01](https://user-images.githubusercontent.com/43583994/91293172-e79b1600-e797-11ea-8fae-2b3ccc8e9810.png)

In fheroes2:

![Graveyard window, reward info 04](https://user-images.githubusercontent.com/43583994/91295260-1666bb80-e79b-11ea-8ef3-494151c770a6.png)

**Comment by ihhub** [comment]
Fixed in #1805
