### ISSUE TITLE
Combat screen, logs list, quantity text "one" instead of "1"

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1369]
In the logs list, the word "one" is used instead of the number "1", "...one Boar..." instead of "...1 Boar...".

![Text one boar instead 1 boar 01](https://user-images.githubusercontent.com/43583994/91483674-5a93b200-e8a8-11ea-8c3a-e6a4d8d55f4f.png)

**Comment by Lumary2** [comment]
Im on it
