### ISSUE TITLE
Combat screen, logs list, the yellow border of the frame is not the same width everywhere

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1370]
The yellow border of the frame is not the same width on the right (3 pixels) compared to the width on the left, top and bottom (5 pixels).

![Combat screen, logs list, yellow border 01](https://user-images.githubusercontent.com/43583994/91483931-b827fe80-e8a8-11ea-9298-0de6f322094c.png)

**Comment by Branikolog** [comment]
The problem occurs only on 640x480 resolution.
As this window is wider, than it is supposed to be.
On a higher resolutions we can see the right frame overlapping the border of battle screen.
![image](https://user-images.githubusercontent.com/55348946/91539898-b6028600-e922-11ea-881f-d8754961006f.png)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

Okay, I see .
It is the width of the window that must be reduced in this case.

For now, my focus is more on finding bugs in the native resolution of the original game (640 x 480).
There are already so many differences to carry over from the original game in this resolution. :)
It is the starting point which must be perfect for the realization of the project, and which must serve as a reference for the other resolutions.

**Comment by Branikolog** [comment]
Go on, dear @LeHerosInconnu! ;)
I've written here to clarify the reason of issue behaviour for the developer, that would work on this problem.)

**Comment by ihhub** [comment]
The issue is no longer valid.
