### ISSUE TITLE
Shadow of creature info window is shifted up

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1386]
We can notice, that spaces in the shadow, close to the left edge, don't match the decoration.
![Frame](https://user-images.githubusercontent.com/55348946/91562491-f3c4d600-e945-11ea-8196-60fa4a10439c.png)

**Comment by ihhub** [comment]
Hi @Branikolog , how does it look like in the original game? Isn't it the same? The shift of the shadow is 16 pixel left and 16 pixels bottom.

**Comment by Branikolog** [comment]
Hello, @ihhub.
Look at left side of the window: spaces in shadow can be seen near the decoration.
![Window shadow](https://user-images.githubusercontent.com/55348946/91631613-9aab7f80-e9e3-11ea-8397-4958f3bd494e.png)
