### ISSUE TITLE
Elementals guarding mine have wrong sprites

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1387]
Air Elemental guarding mine should have other sprite, without blue filling, and faced to left.
Current:
![Air Guard](https://user-images.githubusercontent.com/55348946/91563082-ef4ced00-e946-11ea-83a1-36b2a9d630c8.png)
Original game:
![Air Guard OG](https://user-images.githubusercontent.com/55348946/91563093-f542ce00-e946-11ea-8fda-463f32040ec3.png)
Water Elemental in OG:
![Water Guard OG](https://user-images.githubusercontent.com/55348946/91564064-adbd4180-e948-11ea-9c45-699c1a9e925a.png)
In current version:
![Water Guard](https://user-images.githubusercontent.com/55348946/91564079-b877d680-e948-11ea-88eb-14c41513c0ef.png)

**Comment by ihhub** [comment]
Hi @idshibanov , I think it's a part of your map related pull request, isn't it?
