### ISSUE TITLE
Daemon Cave, reward windows, reward window not displayed and bugged reward window

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1388]
In fheroes2, if the player chooses not to fight the demon servants at the Daemon Cave and slay the demon and earn the reward of 1000 experience points, the reward window is not displayed and the choice for a secondary skill is displayed directly.

In the original game:

![Daemon Cave No 01](https://user-images.githubusercontent.com/43583994/91580856-fc210f00-e94d-11ea-97fe-d62539046c50.png)

![Daemon Cave No 02](https://user-images.githubusercontent.com/43583994/91580879-02af8680-e94e-11ea-9fbc-a1f3e3c29318.png)

In fheroes2:

![Daemon Cave No fh2 02](https://user-images.githubusercontent.com/43583994/91580920-1529c000-e94e-11ea-979b-90c40e271991.png)

In fheroes2, if the player chooses not to fight the demon servants at the Daemon Cave and slay the demon and earn the reward of 1000 experience points and 2500 gold, the reward window is bugged.

In the original game:

![Daemon Cave No 03](https://user-images.githubusercontent.com/43583994/91580939-1e1a9180-e94e-11ea-8d35-ea7cad313d06.png)

![Daemon Cave No 04](https://user-images.githubusercontent.com/43583994/91580961-24a90900-e94e-11ea-857b-8f607f5ff17f.png)

In fheroes2:

![Daemon Cave No fh2 bug 03](https://user-images.githubusercontent.com/43583994/91581001-31c5f800-e94e-11ea-8290-c62c5b7cd651.png)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , could you please check this issue tomorrow (the compilation is too long as we're compiling many changes)? I made few updates on this issue but not everything is fixed. The rest should be fixed once we solved the problem with map information reading which is now incorrect.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , could you please check this issue tomorrow (the compilation is too long as we're compiling many changes)? I made few updates on this issue but not everything is fixed. The rest should be fixed once we solved the problem with map information reading which is now incorrect.

Okay, I'll look at this tomorrow. :)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , it's already merged. You're free to do it from now :)

**Comment by LeHerosInconnu** [comment]
@ihhub.

> Hi @LeHerosInconnu , it's already merged. You're free to do it from now :)

There is still the case of the window alone:

![Daemon Cave fh2 10](https://user-images.githubusercontent.com/43583994/93024017-5202e180-f5f3-11ea-86ea-d32ac3ec3afe.png)

There are these windows:

![Daemon Cave fh2 11](https://user-images.githubusercontent.com/43583994/93024022-57602c00-f5f3-11ea-8c6d-9d55ff7d8962.png)

![Daemon Cave fh2 12](https://user-images.githubusercontent.com/43583994/93024024-59c28600-f5f3-11ea-99ff-170592451770.png)

There are also these windows:

![Daemon Cave fh2 13](https://user-images.githubusercontent.com/43583994/93024025-5f1fd080-f5f3-11ea-9b42-14920a3caafa.png)

![Daemon Cave fh2 14](https://user-images.githubusercontent.com/43583994/93024026-60e99400-f5f3-11ea-801e-bc0c4a4e2fdf.png)
