### ISSUE TITLE
"Disabled" MAX button in creature hire window has too bold shadow

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1410]
Comparing to "Okay" button the shadow is too dark.
![image](https://user-images.githubusercontent.com/55348946/91634991-66dd5380-e9fd-11ea-826b-e943fb17eddb.png)

**Comment by ihhub** [comment]
Hi @Branikolog , how does it look in the original game?

**Comment by Branikolog** [comment]
In the original game this button is always active.
