### ISSUE TITLE
"View Intro" button has too bold shadow

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1412]
OG:
![image](https://user-images.githubusercontent.com/55348946/91637539-e83ee100-ea11-11ea-8980-e1e8c4deb39c.png)
Our version:
![image](https://user-images.githubusercontent.com/55348946/91637534-d8bf9800-ea11-11ea-9c86-cb695689d7ff.png)
It can be related to #1410.

**Comment by ihhub** [comment]
Hi @Branikolog could you please check this issue? I think we fixed it some time ago.

**Comment by Branikolog** [comment]
Hello, @ihhub!
Shadows for "Okay" and "Cancel" buttons are ok now.
But what about excessively dark shadow for disabled  "View intro" button? I understand, that we currently cannot make anything with it, but can we at least make it active and allow players to repeat intro?

**Comment by ihhub** [comment]
Hi @Branikolog please update this issue based on latest state of this dialog.

**Comment by a1exsh** [comment]
Already fixed in `HEAD`:
![image](https://user-images.githubusercontent.com/489601/134630236-e2c75d94-d9d1-4364-b387-618b0fc3f70f.png)
