### ISSUE TITLE
Primary Skills names are shifted up in hero info window

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1419]
In our version:
![image](https://user-images.githubusercontent.com/55348946/91638966-e712b180-ea1b-11ea-8ea0-18a4fb06485c.png)
In OG:
![image](https://user-images.githubusercontent.com/55348946/91638972-f3970a00-ea1b-11ea-809e-7f39abd5fb29.png)

**Comment by ihhub** [comment]
This issue was fixed some time ago.
