### ISSUE TITLE
Game Settings window, scroll bar graphic border

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1420]
The border of the buttons and the scroll bar does not have a yellow border on the left (1 pixel wide).

![Game settings window 05](https://user-images.githubusercontent.com/43583994/91638909-1113a600-ea13-11ea-9017-d684b3bc5ab9.png)

**Comment by Branikolog** [comment]
I suppose, this issue is similar to #1371.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

Yes, this is a similar issue.
These graphics are half done.

Where are stored the graphics files used in fheroes2 that are not present in the original game?
Directly in the executable?
It would be nice to make these files accessible, as is the case for the original game (and with a setup.ini file for each graphic), in a fheroes2 specific .AGG file to allow the user to modify/rectify them.

**Comment by a1exsh** [comment]
Looks like these graphics do come from the AGG.  Check `DROPLISL.ICN`.

**Comment by a1exsh** [comment]
I have a PR that fixes this, but I'm asking myself, if it wouldn't look nicer if we used the same scrollbar as we have in the "Select Resolution" dialog?
![image](https://user-images.githubusercontent.com/489601/134629791-a0f6049a-95d3-4254-a3dd-942041e0abd7.png)

**Comment by LeHerosInconnu** [comment]
@a1exsh.

> I have a PR that fixes this, but I'm asking myself, if it wouldn't look nicer if we used the same scrollbar as we have in the "Select Resolution" dialog?
> ![image](https://user-images.githubusercontent.com/489601/134629791-a0f6049a-95d3-4254-a3dd-942041e0abd7.png)

For my part, I am okay with replacing the scrollbar. :)
