### ISSUE TITLE
Experimental game Settings window, window background

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1423]
There is a highly visible graphic pattern that repeats for each option near the scroll bar.

![Game settings window 05 ellipse](https://user-images.githubusercontent.com/43583994/91639001-b6c71500-ea13-11ea-8e78-1dc879c3c9fe.png)

**Comment by ihhub** [comment]
This is due to frame dialog generation as we create a new dialog with custom dimensions.

**Comment by a1exsh** [comment]
I think this could be improved by using pattern mirroring instead of wrapping in the stretch algorithm.

**Comment by LeHerosInconnu** [comment]
Hello everyone,

Why not use a one-part background instead of repeating a smaller part?

A part of the file contained in STONEBAK.ICN could be cut out for the background of the window and the edges and other elements added "on top".

**Comment by a1exsh** [comment]
> `STONEBAK.ICN`

Hm, interesting.  This one is probably big enough to accommodate any window: 640x480.  What is missing is the same for Evil interface, but we could try to overcome it by applying a gray palette.

I'll give it a try.

**Comment by ihhub** [comment]
This window is deprecated and will be removed by 1.0.
