### ISSUE TITLE
Adventure map, locations too close inaccessible

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1425]
In fheroes2, if some locations are too close, it is not possible to access them.
Example with Stables.

In original game:

![Adventure map, locations too close 01](https://user-images.githubusercontent.com/43583994/91640983-c4839700-ea21-11ea-84cc-f18814ff59fd.png)

In fheroes2:

![Adventure map, locations too close 02](https://user-images.githubusercontent.com/43583994/91640991-cbaaa500-ea21-11ea-9812-58d9f9b7d10b.png)

And also the location info window does not match.

![Adventure map, locations too close 03](https://user-images.githubusercontent.com/43583994/91640997-d402e000-ea21-11ea-8b83-78682635b30a.png)

**Comment by Branikolog** [comment]
So, is this issue happens only if two buildings are close to each other?

Off-topic:
I've noticed, that you often insert cursor into the screenshots... Where you want to make an accent on a position or type of cursor.
Unfortunately, SDL2 version doesn't screen mouse cursor...
For this cases I use SDL1 version of game (for making screenshots with cursor)... But I recommend you to prioritise working on SDL2.
Hope, this can be useful for you...

**Comment by LeHerosInconnu** [comment]
@Branikolog.

>So, is this issue happens only if two buildings are close to each other?

I did not do more in-depth testing on the subject.
I reported the bug just as it appeared to me.

> Off-topic:
> I've noticed, that you often insert cursor into the screenshots... Where you want to make an accent on a position or type of cursor.
> Unfortunately, SDL2 version doesn't screen mouse cursor...
> For this cases I use SDL1 version of game (for making screenshots with cursor)... But I recommend you to prioritise working on SDL2.
> Hope, this can be useful for you...

Yes, thanks for the advice.
For making screenshots, I use a small utility "PicPick Portable" from PortableApps.com, no need to install it and it allows, among other things, to capture or not the mouse cursor.
The problem I am having with fheroes2 is that the mouse cursor is distorted.

And @ihhub also advised me to use SDL2 version of the game. :)

**Comment by idshibanov** [comment]
Fixed as of 0.8.2 (after the map updates).
