### ISSUE TITLE
Hero screen, Magic Book, defect in the shadow of info windows

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1430]
There is a defect in the shadow of info windows.

In fheroes2:

![Shadow info windows 01](https://user-images.githubusercontent.com/43583994/91642854-0535dd00-ea2f-11ea-95cb-384bc456483c.png)

![Shadow info windows 02](https://user-images.githubusercontent.com/43583994/91642857-0a932780-ea2f-11ea-878c-fb566a7d620a.png)

![Shadow info windows 03](https://user-images.githubusercontent.com/43583994/91642859-0e26ae80-ea2f-11ea-80d5-bd8c4e52bd11.png)

**Comment by LeHerosInconnu** [comment]
Other window shadow defects.

At the bottom of the window in the center.

In fheroes2:

![Shadow info windows 04 cercle](https://user-images.githubusercontent.com/43583994/91655827-1c6ade00-eab4-11ea-9b4f-182af634fd69.png)

![Shadow info windows 05](https://user-images.githubusercontent.com/43583994/91655836-22f95580-eab4-11ea-897e-1f50fcd2cb7d.png)

**Comment by ihhub** [comment]
Fixed in #1805
