### ISSUE TITLE
Adventure map, shadow of objects becomes darker when the hero moves or is positioned on the shadow of the object

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1433]
In fheroes2, the shadow of objects becomes darker when the hero moves or is positioned on the shadow of the object.

In fheroes2:

![Adventure map, darker shadow 01](https://user-images.githubusercontent.com/43583994/91644153-b477b180-ea39-11ea-9542-ff3063ab79f1.png)

**Comment by Branikolog** [comment]
Oh, that's well known old bug.
One of the most complex current bugs in game...

**Comment by LeHerosInconnu** [comment]
@Branikolog.

I have not seen it reported in the issues, and as it's the new rendering engine. :)

**Comment by Branikolog** [comment]
> I have not seen it reported in the issues

That's true. We've discussed it so many times, so I even didn't make an issue for this problem.)

Master Developer told me, that this issue is not about rendering engine, but the code itself.
I hope, the nearest future we'd find the solution...

**Comment by LeHerosInconnu** [comment]
@Branikolog.

I hope so too, and since this is a matter of code, the solution has to exist. :)
Thanks for the precision.
