### ISSUE TITLE
Hero screen, info window, display problems with long info window

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1443]
Display issues appear when a long information window is displayed with right click or left click.
First, by clicking the "OKAY" button for the first time and moving the mouse.
And then, by clicking a second time on the "OKAY" button.

By moving the mouse cursor without clicking:

![Hero screen, info window, display problems 01](https://user-images.githubusercontent.com/43583994/91656682-f8f76180-eaba-11ea-84f7-469400ce4966.png)
![Hero screen, info window, display problems 02](https://user-images.githubusercontent.com/43583994/91656684-fac12500-eaba-11ea-8e89-c8c8e66b27e9.png)
![Hero screen, info window, display problems 03](https://user-images.githubusercontent.com/43583994/91656685-fb59bb80-eaba-11ea-8895-163f840d586a.png)
![Hero screen, info window, display problems 04](https://user-images.githubusercontent.com/43583994/91656687-fc8ae880-eaba-11ea-8610-6c8b049c6311.png)
![Hero screen, info window, display problems 05](https://user-images.githubusercontent.com/43583994/91656688-fdbc1580-eaba-11ea-8fd7-e27a8906e8b0.png)
![Hero screen, info window, display problems 06](https://user-images.githubusercontent.com/43583994/91656689-feed4280-eaba-11ea-8e4b-4bca607fce63.png)
![Hero screen, info window, display problems 07](https://user-images.githubusercontent.com/43583994/91656690-001e6f80-eabb-11ea-8f31-23151b75bb70.png)
![Hero screen, info window, display problems 08](https://user-images.githubusercontent.com/43583994/91656680-f7c63480-eaba-11ea-95de-d43be13c3c3a.png)
![Hero screen, info window, display problems 12](https://user-images.githubusercontent.com/43583994/91656713-2a702d00-eabb-11ea-8c37-c806025e4e7a.png)

By clicking:

![Hero screen, info window, display problems 09](https://user-images.githubusercontent.com/43583994/91656728-4247b100-eabb-11ea-99d8-a6a33f338535.png)
![Hero screen, info window, display problems 10](https://user-images.githubusercontent.com/43583994/91656732-4378de00-eabb-11ea-932e-6020b70d3320.png)
![Hero screen, info window, display problems 11](https://user-images.githubusercontent.com/43583994/91656726-407ded80-eabb-11ea-9e5c-0f1c5404a223.png)
![Hero screen, info window, display problems 13](https://user-images.githubusercontent.com/43583994/91656744-5095cd00-eabb-11ea-92bb-74bb31635a4c.png)
![Hero screen, info window, display problems 14](https://user-images.githubusercontent.com/43583994/91656741-4ecc0980-eabb-11ea-8bbe-6e8f9cd271bb.png)

Here is the save file:
[Bug big info window 01.zip](https://github.com/ihhub/fheroes2/files/5146632/Bug.big.info.window.01.zip)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , I tested these scenarios on the latest version and none of them are reproducible anymore. I'm attaching your save file which could be played on the latest version.
[Bug big info window 01.zip](https://github.com/ihhub/fheroes2/files/7022174/Bug.big.info.window.01.zip)

If you see no issues with these windows please close this topic.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub, 

Everything seems to be working correctly.
