### ISSUE TITLE
Adventure map screen, info windows, defect in the shadow of info windows

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1444]
There is a defect in the shadow of lots of info windows.
I didn't test everything, but it must be a widespread problem.
Only the darker rectangular shadows in the shadow area are to be taken into account. There may also be the shadow of the objects (artifacts, etc.) which is darker, which is normal.

In fheroes2:

![Map screen, shadow info windows 01](https://user-images.githubusercontent.com/43583994/91658048-593fd080-eac6-11ea-8cf4-ec1437ca06f7.png)
![Map screen, shadow info windows 02](https://user-images.githubusercontent.com/43583994/91658050-5b099400-eac6-11ea-8e48-60dfc49f1516.png)
![Map screen, shadow info windows 03](https://user-images.githubusercontent.com/43583994/91658052-5c3ac100-eac6-11ea-92ec-eac84a131685.png)
![Map screen, shadow info windows 04](https://user-images.githubusercontent.com/43583994/91658054-5d6bee00-eac6-11ea-8f35-90da127c1f25.png)
![Map screen, shadow info windows 05](https://user-images.githubusercontent.com/43583994/91658056-5e9d1b00-eac6-11ea-8721-c5394fe103a0.png)
![Map screen, shadow info windows 06](https://user-images.githubusercontent.com/43583994/91658060-5fce4800-eac6-11ea-813f-4e5005c58078.png)
![Map screen, shadow info windows 07](https://user-images.githubusercontent.com/43583994/91658061-60ff7500-eac6-11ea-9858-f0e85e8d3653.png)
![Map screen, shadow info windows 08](https://user-images.githubusercontent.com/43583994/91658062-6230a200-eac6-11ea-8b4e-af13ea8efd90.png)
![Map screen, shadow info windows 09](https://user-images.githubusercontent.com/43583994/91658063-6361cf00-eac6-11ea-9d26-27ec01a14351.png)
![Map screen, shadow info windows 10](https://user-images.githubusercontent.com/43583994/91658064-6492fc00-eac6-11ea-9c0b-ab75591ed306.png)
![Map screen, shadow info windows 11](https://user-images.githubusercontent.com/43583994/91658066-665cbf80-eac6-11ea-9e59-ec4f9fe077ac.png)
![Map screen, shadow info windows 12](https://user-images.githubusercontent.com/43583994/91658068-678dec80-eac6-11ea-8b2a-8fdad4c3af19.png)
![Map screen, shadow info windows 13](https://user-images.githubusercontent.com/43583994/91658069-68bf1980-eac6-11ea-8810-628b856630d7.png)
![Map screen, shadow info windows 14](https://user-images.githubusercontent.com/43583994/91658073-69f04680-eac6-11ea-8195-b0d6559a1ead.png)
![Map screen, shadow info windows 15](https://user-images.githubusercontent.com/43583994/91658074-6bba0a00-eac6-11ea-9d96-b02adc5fbad6.png)
![Map screen, shadow info windows 16](https://user-images.githubusercontent.com/43583994/91658075-6ceb3700-eac6-11ea-9eb1-42c9818587ae.png)
![Map screen, shadow info windows 17](https://user-images.githubusercontent.com/43583994/91658077-6e1c6400-eac6-11ea-8d6b-c6628f492738.png)
![Map screen, shadow info windows 18](https://user-images.githubusercontent.com/43583994/91658078-6fe62780-eac6-11ea-8b2e-1c3f0d4695f3.png)
![Map screen, shadow info windows 19](https://user-images.githubusercontent.com/43583994/91658079-71175480-eac6-11ea-8038-073839ef18d6.png)
![Map screen, shadow info windows 20](https://user-images.githubusercontent.com/43583994/91658080-72488180-eac6-11ea-8510-881817bcf350.png)
![Map screen, shadow info windows 21](https://user-images.githubusercontent.com/43583994/91658082-7379ae80-eac6-11ea-9bc8-c7ed2ab254b5.png)
![Map screen, shadow info windows 22](https://user-images.githubusercontent.com/43583994/91658083-75437200-eac6-11ea-8d94-b9a42c998a16.png)
![Map screen, shadow info windows 23](https://user-images.githubusercontent.com/43583994/91658084-76749f00-eac6-11ea-91f2-62a9d18b344c.png)
![Map screen, shadow info windows 24](https://user-images.githubusercontent.com/43583994/91658085-77a5cc00-eac6-11ea-9eca-8fb36ffa1bee.png)

Here is the test scenario file:
[0 9996.zip](https://github.com/ihhub/fheroes2/files/5146721/0.9996.zip)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , I know this problem. I'll try to fix it soon.

350+ issues, we won't finish in time if only me is fixing all of them. Eh...

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , I know this problem. I'll try to fix it soon.

Ok, thank you.

> 350+ issues, we won't finish in time if only me is fixing all of them. Eh...

There is a lot more to come. :)
Still counting.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , it's fixed :)

**Comment by LeHerosInconnu** [comment]
@ihhub.

Nice, it was a quick fix. :)
Do the same for all other issues and the delivery date will be respected. :D
I will download the new version of the program in two hours to avoid all these window shadow issues. :)
