### ISSUE TITLE
Treasure location map doesn't update after visiting obelisk

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#145]
Visit any obelisk by any hero and observe that treasure (puzzle) location map doesn't update:
<img width="639" alt="treasure_map" src="https://user-images.githubusercontent.com/19829520/66294531-c8935b80-e91b-11e9-82fe-b0d6d9e557fd.png">

**Comment by Branikolog** [comment]
I suppose this happens only if map doesn't have defined ultimate artifact location.
