### ISSUE TITLE
Adventure map, Jail, the sprite of the hero who opens the jail is no longer displayed

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1451]
In fheroes2, if a hero opens the jail when arriving from the north, the sprite of the hero who opens the jail is no longer displayed.

In fheroes2:

![Jail hero sprite  01](https://user-images.githubusercontent.com/43583994/91664534-2a3e5480-eaf0-11ea-9189-b2aa08a464e8.png)
![Jail hero sprite  02](https://user-images.githubusercontent.com/43583994/91664535-2ca0ae80-eaf0-11ea-8a12-20e75f8e3d14.png)
![Jail hero sprite  03](https://user-images.githubusercontent.com/43583994/91664536-2dd1db80-eaf0-11ea-8db9-2c83143deffe.png)
![Jail hero sprite  04](https://user-images.githubusercontent.com/43583994/91664537-2f030880-eaf0-11ea-888b-e293398347b2.png)
![Jail hero sprite  05](https://user-images.githubusercontent.com/43583994/91664538-30cccc00-eaf0-11ea-82ac-a0359a237794.png)

Here is the save file:
[Bug jail north 01.zip](https://github.com/ihhub/fheroes2/files/5147123/Bug.jail.north.01.zip)

**Comment by ihhub** [comment]
Tested on latest version. Everything works fine.
