### ISSUE TITLE
Combat screen, positioning of obstacles on the battlefield

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1454]
In fheroes2, tree obstacles can be positioned in two adjacent hexagons.
In the original game, I don't remember seeing a setup where two trees were located side by side on the battlefield.
Some obstacles can also be side by side in the original game.

In original game:

![Combat screen, obstacles battlefield 01](https://user-images.githubusercontent.com/43583994/91695104-edb13e00-eb6d-11ea-9580-fd61437f8d5c.png)

![Combat screen, obstacles battlefield 02](https://user-images.githubusercontent.com/43583994/91695111-f0139800-eb6d-11ea-8ac4-b004244adfbc.png)

![Combat screen, obstacles battlefield 03](https://user-images.githubusercontent.com/43583994/91695115-f1dd5b80-eb6d-11ea-872c-abefc5801582.png)

![Combat screen, obstacles battlefield 05](https://user-images.githubusercontent.com/43583994/91696539-002c7700-eb70-11ea-9aaf-34887eaca609.png)

![Combat screen, obstacles battlefield 06](https://user-images.githubusercontent.com/43583994/91696529-fdca1d00-eb6f-11ea-8f2d-9818d90ad18c.png)

In fheroes2:

![Combat screen, obstacles battlefield 04](https://user-images.githubusercontent.com/43583994/91695135-fa359680-eb6d-11ea-8654-9c72c521e43b.png)

**Comment by LeHerosInconnu** [comment]
More screenshots for this, as well as saves and a test scenario.

Here are the screenshots:
[Obstacles position 01.zip](https://github.com/ihhub/fheroes2/files/7612112/Obstacles.position.01.zip)

Here are the save files:
[Obstacles position saves 01.zip](https://github.com/ihhub/fheroes2/files/7612113/Obstacles.position.saves.01.zip)

Here is the scenario test:
[0 9947.zip](https://github.com/ihhub/fheroes2/files/7612114/0.9947.zip)

**Comment by LeHerosInconnu** [comment]
Another save for this (0.9.14 5285).

In fheroes2:

![Tree near tree 01](https://user-images.githubusercontent.com/43583994/164061681-cc341f55-e74e-466b-826b-9f8b9a721fe5.png)

Here is the save file:
[Before two trees near 01.zip](https://github.com/ihhub/fheroes2/files/8515175/Before.two.trees.near.01.zip)

**Comment by LeHerosInconnu** [comment]
I recently had two trees in two adjacent hexagons in the original game (a first time I remember seeing this).
It seems that this is possible after all. :)

In original game:

![Before two trees near in combat 01](https://user-images.githubusercontent.com/43583994/169324754-c878e21f-8689-4cbe-9115-7766dee835aa.png)

Here is the save file:
[Before two trees near in combat 01.zip](https://github.com/ihhub/fheroes2/files/8730374/Before.two.trees.near.in.combat.01.zip)

**Comment by slawomir-witkowski** [comment]
Do we want to prevent 2 obstacles next to each other or should this issue be closed?

**Comment by LeHerosInconnu** [comment]
Hello @slawomir-witkowski,

> Do we want to prevent 2 obstacles next to each other or should this issue be closed?

As it is possible in the original game, I close the issue.
Thank you.
