### ISSUE TITLE
Artifact, Crystal Ball, Crystal Ball window display fault

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1457]
In fheroes2, when the hero picks up the Crytal Ball artifact and the player exits the Crytal Ball artifact window, parts of the closed window remain displayed at the top and bottom of the screen.

In fheroes2:

![Crystal Ball window display fault 01](https://user-images.githubusercontent.com/43583994/91704472-f1e45800-eb7b-11ea-8ee8-6b5f6783a2e0.png)

![Crystal Ball window display fault 02](https://user-images.githubusercontent.com/43583994/91704459-f01a9480-eb7b-11ea-93aa-fa7bd19a1b1d.png)

**Comment by ihhub** [comment]
Closing this issue as it's not reproducible anymore.
