### ISSUE TITLE
Artifact, Crystal Ball, Crystal Ball functioning without selecting the hero who owns the Crystal Ball artifact

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1460]
In the original game, when the hero owning the Crystall Ball artifact is not selected, and when another hero of the player is selected or when a player's city is selected, information on wandering creatures, enemy heroes, and enemy cities within the area of effect of the Crystall Ball artifact are displayed.

In fheroes2, this is not the case.

In the example, the first hero owns the Crystal Ball artifact.

In original game:

![Artifact, Crystal Ball functioning without hero selected 01](https://user-images.githubusercontent.com/43583994/91715268-9e7b0580-eb8d-11ea-8a60-601794a20604.png)

![Artifact, Crystal Ball functioning without hero selected 02](https://user-images.githubusercontent.com/43583994/91715276-a0dd5f80-eb8d-11ea-97c3-37608a7425ae.png)

![Artifact, Crystal Ball functioning without hero selected 03](https://user-images.githubusercontent.com/43583994/91715280-a20e8c80-eb8d-11ea-8b45-9a6c818db752.png)

![Artifact, Crystal Ball functioning without hero selected 05](https://user-images.githubusercontent.com/43583994/91715284-a3d85000-eb8d-11ea-9dc3-bb7db6342e47.png)

![Artifact, Crystal Ball functioning without hero selected 06](https://user-images.githubusercontent.com/43583994/91715290-a5097d00-eb8d-11ea-9f03-ec9781641c68.png)

![Artifact, Crystal Ball functioning without hero selected 07](https://user-images.githubusercontent.com/43583994/91715298-a63aaa00-eb8d-11ea-855d-eb407ee7cb26.png)

In fheroes2:

![Artifact, Crystal Ball functioning without hero selected 04](https://user-images.githubusercontent.com/43583994/91715321-b0f53f00-eb8d-11ea-9c6e-9931257b0254.png)

![Artifact, Crystal Ball functioning without hero selected 08](https://user-images.githubusercontent.com/43583994/91715317-af2b7b80-eb8d-11ea-9f8b-6a88ceab65a0.png)

**Comment by vincent-grosbois** [comment]
Wait, so Crystal Ball is supposed to work for the whole map once you have it ?

**Comment by LeHerosInconnu** [comment]
Hello @vincent-grosbois,

> Wait, so Crystal Ball is supposed to work for the whole map once you have it ?

No, the Crystal Ball works with a radius, but the information about the objects located in this radius is always displayed even when the hero who owns the Crystal Ball is not selected.
