### ISSUE TITLE
Hero screen, Necromancy skill, Shrine building bonus not displayed

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1470]
In fheroes2, the bonus of the Shrine building "+1" from "Basic+1" is not displayed on the Necromancy skill sprite and is not displayed in the Necromancy skill info windows.
The title of the info windows must also be modified "Basic Necromancy (+1)" as well as the text.

Note that there is also a bug in the info windows of the original game, the graphic used in the info windows does not show "Basic+1" but "Basic" only.

In original game:

![Necromancy bonus 03](https://user-images.githubusercontent.com/43583994/91828920-0cccd000-ec41-11ea-8568-3ce470aeb96f.png)

![Necromancy bonus 04](https://user-images.githubusercontent.com/43583994/91828932-0e969380-ec41-11ea-92db-3aef135172ea.png)

![Necromancy bonus 09](https://user-images.githubusercontent.com/43583994/91829005-279f4480-ec41-11ea-871c-01ad815dddc4.png)

In fheroes2:

![Necromancy bonus 05](https://user-images.githubusercontent.com/43583994/91829084-47cf0380-ec41-11ea-83ae-c4f833195b05.png)

![Necromancy bonus 06](https://user-images.githubusercontent.com/43583994/91828937-0fc7c080-ec41-11ea-95ac-388496d3b6e3.png)

![Necromancy bonus 10](https://user-images.githubusercontent.com/43583994/91829114-50273e80-ec41-11ea-853a-39498ac94a50.png)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , could you please retest this issue? I remember we fixed Necromancy related window information recently.

**Comment by vincent-grosbois** [comment]
Isn't this the same as #1469 ? What's the difference?

**Comment by LeHerosInconnu** [comment]
Hello @ihhub and @vincent-grosbois,

> Hi @LeHerosInconnu , could you please retest this issue? I remember we fixed Necromancy related window information recently.

Everything seems to work as in the original game.
But I just realized that there is a bug in the original game. :)
The maximum percentage of resurrected Skeletons is only 90% when it should be 100%.

30% for the secondary skill Necromancy expert level.
60% maximum for Shrines built in the Necromancer's castles (maximum of 6 Shrines taken into account).
10% for the Spade of Necromancy artifact.

Should I open a new issue for this?

> Isn't this the same as #1469 ? What's the difference?

Yes, both issues concern the bonus for the Necromancy skill.
The first one for the Spade of Necromancy and the second one for the Shrines.

**Comment by vincent-grosbois** [comment]
> Should I open a new issue for this?

I'm not even sure it's a bug, it's could be just a cap for the maximum

**Comment by LeHerosInconnu** [comment]
@vincent-grosbois.

> > Should I open a new issue for this?
> 
> I'm not even sure it's a bug, it's could be just a cap for the maximum

Clearly, with the limitation of the 6 Shrines (60%) and the possibility of the 10% from the Spade of Necromancy, their intention was to allow the 100% resurrection, which is logical.
But something went wrong.

**Comment by vincent-grosbois** [comment]
I can cap it at 100%, it's literally a change of 2 characters
But I'm not sure it was really intended.
Anyway it doesn't change much, I'll change it

**Comment by LeHerosInconnu** [comment]
Hello @vincent-grosbois,

> I can cap it at 100%, it's literally a change of 2 characters
> But I'm not sure it was really intended.
> Anyway it doesn't change much, I'll change it

I think it's okay.

I can understand the limitation to 100% because it allows for no more skeletons to be raised than decimated creatures.
But I can't find a reason for the 90% limit. :)

**Comment by Branikolog** [comment]
@LeHerosInconnu 
It can be a minor limitation to prevent necromancers be overpowered. ;)
