### ISSUE TITLE
Scenario window, multiplayer games, human players

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1472]
In the original game, when the program is started in "MULTI-PLAYER GAME", "HOT SEAT", "2 PLAYERS", the second human player is already activated in the "Scenario" window.

In fheroes2 this is not the case and sometimes the user may forget to do it and have to start all over.

In original game:

![Scenario window, multiplayer games, human players 01](https://user-images.githubusercontent.com/43583994/91839083-c2525000-ec4e-11ea-9f3a-d5c59bd110a5.png)

In fheroes2:

![Scenario window, multiplayer games, human players 02](https://user-images.githubusercontent.com/43583994/91839101-caaa8b00-ec4e-11ea-8e47-c86613956323.png)

**Comment by Branikolog** [comment]
I think this issue already was in #448.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

Yes it seems.
