### ISSUE TITLE
Scenario window, scenario launched in single player mode after being launched in multiplayer mode

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1473]
In the original game, when the user exits a scenario launched in multiplayer mode and relaunches the same scenario without going through multiplayer mode, the second player is adjusted as an AI player.

In fheroes2, the second player remains validated as a human player when this should not be the case.

In original game:

![Scenario window, single player after multiplayer 01](https://user-images.githubusercontent.com/43583994/91840007-46590780-ec50-11ea-856e-74a1a7fef540.png)

In fheroes2:

![Scenario window, single player after multiplayer 02](https://user-images.githubusercontent.com/43583994/91840015-49ec8e80-ec50-11ea-9664-5f592742433b.png)

**Comment by Branikolog** [comment]
This issue is already was described in #643.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

Yes it also seems.
