### ISSUE TITLE
"Full screen mode" interface option implementation

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1474]
We should add an user friendly full screen switching in game.

**Comment by ihhub** [comment]
Hi @Branikolog and @LeHerosInconnu this is a good topic for discussion :)

**Comment by Branikolog** [comment]
It's time to test new section for discussions! :D

**Comment by LeHerosInconnu** [comment]
@ihhub and @Branikolog.

> Hi @Branikolog and @LeHerosInconnu this is a good topic for discussion :)

> It's time to test new section for discussions! :D

I have to leave now.
Maybe later or tomorrow. :)

**Comment by ihhub** [comment]
Good. We need a solution by tomorrow as it should be included into upcoming release.

**Comment by LeHerosInconnu** [comment]
@ihhub.

> Good. We need a solution by tomorrow as it should be included into upcoming release.

Maybe this will do the job: https://github.com/ihhub/fheroes2/discussions/2433#discussioncomment-224172. :)

**Comment by ihhub** [comment]
This option was added in the game some time ago.
