### ISSUE TITLE
Game Settings window, enabling/disabling options while playing a scenario

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1484]
While playing a scenario, by accessing the "Game Settings" window, it is not possible to activate or deactivate certain options.
It should be ensured that enabling and disabling all displayed options is possible.
If it is not possible to do it for some options, it is not necessary to display them in the options list during the game.

![Info window, size CONFIG OKAY 01](https://user-images.githubusercontent.com/43583994/91872686-68668000-ec78-11ea-93d8-aba47104547e.png)

![Options while playing a scenario 02](https://user-images.githubusercontent.com/43583994/91873700-a3b57e80-ec79-11ea-95c9-0f9e76e6a039.png)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu I made elements which a user can't modify with gray color. We should display all settings to get people to know what settings the current map has. If you don't have any objections about this approach.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu I made elements which a user can't modify with gray color. We should display all settings to get people to know what settings the current map has. If you don't have any objections about this approach.

It's okay for me.
Except that the gray color is maybe a little too close to the white color, especially for such a small text?
And how does that look with the Evil interface?
