### ISSUE TITLE
Combat screen, creature sprite border

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1495]
In fheroes2, the creature sprite border is thicker than in the original game.

In original game:

![Battlefield H2 01](https://user-images.githubusercontent.com/43583994/91971642-d44cf500-ed19-11ea-8656-cadc51ab1b24.png)

In fheroes2:

![Battlefield fh2 02](https://user-images.githubusercontent.com/43583994/91971621-cb5c2380-ed19-11ea-9091-5c9a70dbac9f.png)

Open the two images in different tabs in your browser, enlarge the images and switch between the two tabs alternately.

![Battlefield H2 01 sprite border 01](https://user-images.githubusercontent.com/43583994/91972970-bf716100-ed1b-11ea-82b1-5c1afa156942.png) ![Battlefield fh2 02 sprite border 01](https://user-images.githubusercontent.com/43583994/91972986-c304e800-ed1b-11ea-99a6-d3590daeabb5.png)

**Comment by Branikolog** [comment]
Our Dev team is already working on this issue.
The same behaviour you can notice through all the game: in well, in creature info and in hero info windows.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

Yes, I saw that there was already a postponed issue for the creature info window.
Thanks for warning me, this will avoid me from reporting similar bugs if this occurs.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

Maybe one day the developers will say:
"Stop him from reporting bugs. It's enough." :)

**Comment by Branikolog** [comment]
I hope ,one day you won't find any. ;)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

I hope that one day I will enjoy the game without thinking about potential bugs. :)

**Comment by ihhub** [comment]
This issue is fixed in #1651
