### ISSUE TITLE
Hero, combat, necromancy skill, number of skeletons raised

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1496]
In the original game, when a hero has the Necromancy skill, at the end of a combat there is always at least 1 skeleton raised.
In fheroes2, this is not the case.

In original game:

![Minimum 1 skeleton 01](https://user-images.githubusercontent.com/43583994/91979178-a79eda80-ed25-11ea-8385-d25d62e2550c.png)

![Minimum 1 skeleton 02](https://user-images.githubusercontent.com/43583994/91979183-a9689e00-ed25-11ea-91f2-c8197158ab02.png)

In fheroes2:

![Minimum 1 skeleton 03](https://user-images.githubusercontent.com/43583994/91979195-b08fac00-ed25-11ea-9d62-4b1eee6ed37f.png)

**Comment by eos428** [comment]
Hi there, can I get a save file for easy testing?

**Comment by Branikolog** [comment]
[Necromancy.zip](https://github.com/ihhub/fheroes2/files/5422156/Necromancy.zip)

**Comment by LeHerosInconnu** [comment]
Hello @eos428 and @Branikolog, and thank you @Branikolog.

> Hi there, can I get a save file for easy testing?

I know it's too late, but you never know. :)

Here is the test scenario file:
[Necromancy skill test 01.zip](https://github.com/ihhub/fheroes2/files/5422281/Necromancy.skill.test.01.zip)

**Comment by Branikolog** [comment]
No problem, @LeHerosInconnu! We're all working here on the same goal: to make HoMM2 shine again. :)

**Comment by eos428** [comment]
Many thanks, both of you!
