### ISSUE TITLE
The size of hexagonal battle net is incorrect

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#150]
Here is hexagonal net in current application:
![image](https://user-images.githubusercontent.com/19829520/66306791-2bddb780-e935-11e9-8340-9105a26b8b99.png)

and this how it looks like in original game:
![image](https://user-images.githubusercontent.com/19829520/66306901-795a2480-e935-11e9-9e74-21970bd7520a.png)

**Comment by MariaSopkova** [comment]
I'll fix it
