### ISSUE TITLE
Hero, combat, "A glorious victory!" window, add a line of space between the title and the text

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1501]
In the original game, there is a space line between the title "A glorious victory!" and the text.
In fheroes2, this is not the case.

In original game:

![Minimum 1 skeleton 01](https://user-images.githubusercontent.com/43583994/91979178-a79eda80-ed25-11ea-8385-d25d62e2550c.png)

In fheroes2:

![Wrong window combat skeleton raised 01](https://user-images.githubusercontent.com/43583994/91979381-f9dffb80-ed25-11ea-839d-853129de6f6c.png)

**Comment by Branikolog** [comment]
I think this issue is the same to the #1031...

**Comment by LeHerosInconnu** [comment]
@Branikolog.

There's some of that.
Although the other issue is less precise. :)

There is a lot of tuning work for the various windows in the game.

**Comment by Branikolog** [comment]
Ok, let's leave yours.) I like a precision.)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

The power of precision is huge. :)
