### ISSUE TITLE
Font color for creature name is incorrect

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#152]
In original version of the game all creatures have gold color font while in current game it's standard white color:
![image](https://user-images.githubusercontent.com/19829520/66314019-f2fa0e80-e945-11e9-9bed-86c7a6c95647.png)

Original game:
![image](https://user-images.githubusercontent.com/19829520/66314010-ed9cc400-e945-11e9-89a7-3cb96caab639.png)

**Comment by dev-SB** [comment]
I would like to work on this issue.

**Comment by ihhub** [comment]
hi @dev-SB  sure!

**Comment by dev-SB** [comment]
I am having difficulties in debugging the project on my machine.

**Comment by ihhub** [comment]
Which difficulties?

**Comment by dev-SB** [comment]
I am trying to debug in CLion but since it doesn't support makefile, I am following this: https://www.jetbrains.com/help/clion/managing-makefile-projects.html . When I run compiledb make it causes "SDLl.h" not found error in /src/engine/types.h file
Can you please help?

**Comment by dev-SB** [comment]
*It is "SDL.h".

**Comment by ihhub** [comment]
Did you follow an instructions written in readme file in **compilation** section?

**Comment by dev-SB** [comment]
I did, now the issue is resolved
Thank you.

**Comment by dev-SB** [comment]
Yes, I did.

**Comment by dev-SB** [comment]
Can you please guide me on how can I debug it after compiling the project?

**Comment by ihhub** [comment]
There are multiple tools for debugging. For example you could use `gbd`. I think CLion has it's own debugger. Alternatively you could use **VERBOSE**() call to output any information from any place of the code during runtime

**Comment by dev-SB** [comment]
I have compiled the project following the compilation guide, after which how should I proceed?

**Comment by ihhub** [comment]
There is no direct guide to software development and debugging. What I could suggest is to find a file/place where such text is created and displayed (this part is made by engine so you don't need care about it). All files locate in `src/fheroes2`. To prove your idea use `VERBOSE()` function in source code that it's exactly an information representing creature count. After this check the font and color of text to be passed to engine to draw (most likely it's `Text` object). Then try to change it to validate the assumption and after this change the color to correct one :)

**Comment by dev-SB** [comment]
I will do it. Thanks a lot :)
