### ISSUE TITLE
Adventure map, mine sprite over hero sprite near the mine

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1522]
The hero sprite near the entrance to the mine is covered by the mine sprite after another hero visits the mine.

Certainly related to this: https://github.com/ihhub/fheroes2/issues/1480

In fheroes2:

![Mine sprite over hero sprite near the mine 01](https://user-images.githubusercontent.com/43583994/92145343-5de2ec80-ee18-11ea-83e1-91f5586a2307.png)

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu!

> Certainly related to this: #1480

I think it's the same bug. 
You should simply add the type of buildings to the #1480 issue, rather, than creating new. (In a case, not all large objects have the same behaviour. If they are, simply leave that issue as it is. We'd fix them all)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

Okay, I'll see for the next time.
