### ISSUE TITLE
Adventure map, Ultimate Artifact, View Puzzle screen, Ultimate Artifact location sprite

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1524]
In fheroes2, the sprite used for the location of the Ultimate Artifact is suitable for the scenario editor but does not have the graphic style to appear during the game.
The sprite of the cross from the original game fits perfectly.

In original game:

![Ultime Artifact view puzzle 01](https://user-images.githubusercontent.com/43583994/92147349-55d87c00-ee1b-11ea-8055-6e61ac4c7c4a.png)

In fheroes2:

![Ultime Artifact view puzzle 02](https://user-images.githubusercontent.com/43583994/92147352-57a23f80-ee1b-11ea-8542-6c1fb43f7441.png)

**Comment by Branikolog** [comment]
Humm...
The map, I'm currently playing, everything seemes to be ok...
![image](https://user-images.githubusercontent.com/55348946/92150286-dac99280-ee27-11ea-9aea-03fcc75500cf.png)
Have you tried to dig it out?

**Comment by LeHerosInconnu** [comment]
@Branikolog.

Digging for the Ultimate Artifact works fine.
I tried with the resolution 1024 x 768 and I have the same behavior for the displayed crappy sprite.

**Comment by Branikolog** [comment]
@LeHerosInconnu 
I mean, that on my current map I've dig the artifact out ong time ago, and I don't remeber wether i had a cross or round sprite...
Could you check puzzle map after you've dig artifact out? (I suppose, it can have wrong sprite till the moment player digs artifact out)
Could the issue also happen on a certain maps only? Let's say on expansion ones? (As I'm always playing PoL maps)
Could you check, please?

**Comment by LeHerosInconnu** [comment]
@Branikolog.

The sprite remains the same in the View Puzzle screen after digging.
This happens for the "Succession Wars" and "Price of Loyalty" scenarios.

**Comment by Branikolog** [comment]
@LeHerosInconnu 
Can you attach savefile or map you're experiencing this issue, please?

**Comment by LeHerosInconnu** [comment]
@Branikolog.

Here are the test scenario files:
[Ultimate Artifact location sprite.zip](https://github.com/ihhub/fheroes2/files/5173225/Ultimate.Artifact.location.sprite.zip)

**Comment by LeHerosInconnu** [comment]
The sprite of the scenario editor used for the Ultimate Artifact only appears when the scenario creator has positioned the Ultimate Artifact in the scenario editor.

In fheroes2, Ultimate Artifact no personalized localization:
Here, there is another bug for the display of the crosshair graphic used for the location of the Ultimate Artifact. https://github.com/ihhub/fheroes2/issues/1537
But the sprite of the scenario editor is not displayed.

![Ultime Artifact without personalized position 01](https://user-images.githubusercontent.com/43583994/92247912-32b7d600-eec8-11ea-94bb-70554fdf2ec5.png)

![View Puzzle no obelisk bug 01](https://user-images.githubusercontent.com/43583994/92248102-74e11780-eec8-11ea-9ef1-42480bb05529.png)
