### ISSUE TITLE
Empty puzzle window

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1526]
If there's no ultimate artifact hidden in a map. (Let's say, for example default Broken Alliance...)
We can see empty puzzle window, even on start.

Edit:
This issue happens after we look at complete puzzle map before, in other game.
Actually game remembers once opened parts of puzzle map and later shows opened puzzle map at all games\saves.

![image](https://user-images.githubusercontent.com/55348946/92150605-50356300-ee28-11ea-95a0-e6986cd3d126.png)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

I would like to point out that there is always an Ultimate Artifact on the map even if the scenario creator does not place it on the adventure map in the scenario editor.

**Comment by Branikolog** [comment]
@LeHerosInconnu 
How can you chack this, if there would be no obelisks on a map?

**Comment by LeHerosInconnu** [comment]
@Branikolog.

If there are no obelisks, the player can still try to dig at random.
With patience and time, the Ultimate Artifact will be in his possession. :)

**Comment by Branikolog** [comment]
Sounds like a challenge!)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

Here is a scenario without obelisk.
Launch the scenario in two human players multiplayer mode and dig.
This scenario crashes the original game, but works fine in fheroes2.

"You see, in this world there's two kinds of people, my friend: those with loaded guns, and those who dig. You dig."
Clint Eastwood as "Blondie", "The Good, the Bad and the Ugly" (1966).

[Ultimate Artifact no obelisk.zip](https://github.com/ihhub/fheroes2/files/5173233/Ultimate.Artifact.no.obelisk.zip)

**Comment by Branikolog** [comment]
:)
Yes. it works.
Talking about the subject, i found out the the bahaviour of this bug..

**Comment by LeHerosInconnu** [comment]
@Branikolog.

And what is this behavior?

**Comment by Branikolog** [comment]
@LeHerosInconnu 
I've edited the first message:
Once you've seen any element opened in puzzle map, you'd seen such opened elements other games.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

This makes a bug with the scenario "Ultimate Artifact with no obelisk".

In fheroes2:

![View Puzzle no obelisk bug 01](https://user-images.githubusercontent.com/43583994/92234980-39881e00-eeb3-11ea-93d4-ba03a93b81d9.png)

And your bug is only for the first player.

In fheroes2:

![View Puzzle no obelisk bug 02](https://user-images.githubusercontent.com/43583994/92235466-0003e280-eeb4-11ea-8346-8c5776eec180.png)

**Comment by Branikolog** [comment]
Good clarification, @LeHerosInconnu!

> This makes a bug with the scenario "Ultimate Artifact with no obelisk".

What happens if there will be no place at all for UA?

**Comment by LeHerosInconnu** [comment]
@Branikolog.

I'm testing, I'll report the bug later and I also know why the scenario "Ultimate Artifact with no obelisk" crashes the original game. :)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> This scenario crashes the original game, but works fine in fheroes2.

This scenario crashes the original game, because "The ultimate artifact must be placed at least 9 squares in from map edge."

![9 squares rule 01](https://user-images.githubusercontent.com/43583994/92248543-26804880-eec9-11ea-87e2-c0315daa39ee.png)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> What happens if there will be no place at all for UA?

In the original game, this crashes the program.
It's normal, there is no place to place the Ultimate Artifact.

In fheroes2, the View Puzzle screen is displayed, but no part of the puzzle is revealed, even with the bug related to a previous scenario where the whole puzzle is revealed.

In fheroes2:

![Ultimate Artifact no place 01](https://user-images.githubusercontent.com/43583994/92271451-1c217700-eee8-11ea-9d5e-ab14c0e1a37e.png)

**Comment by Branikolog** [comment]
Hmm. I think, that we should make a message, while visiting obelisks on a maps with no UA, that there's no hidden artifact on this lands...
And I think we should leave "view obelisk puzzle" button working... Just simply show default hidden puzzle...

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> Hmm. I think, that we should make a message, while visiting obelisks on a maps with no UA, that there's no hidden artifact on this lands...

A scenario without the ability to position an Ultimate Artifact by the program would be unplayable anyway, as there would be no place to move a hero (except if the scenario victory condition is to find the Ultimate Artifact, but it would be a very quick and boring scenario).

Remember there is no map without Ultimate Artifact (if it is possible to place one).
If there is a possibility to place the Ultimate Artifact, the program will do so and even if it's under a hero's location.

It's why the hero can still dig in the "Digging Ultimate Artifact no obelisk, 9 squares rule." scenario (0 9990a.MP2).

> And I think we should leave "view obelisk puzzle" button working... Just simply show default hidden puzzle...

Yes, to show that all possibilities have been considered by the game designer/program developer. :)

Here is the test scenario file:
[Ultimate Artifact no place.zip](https://github.com/ihhub/fheroes2/files/5179709/Ultimate.Artifact.no.place.zip)

**Comment by Branikolog** [comment]
> A scenario without the ability to position an Ultimate Artifact by the program would be unplayable anyway, as there would be no place to move a hero

Don't forget that player can move over some objects. And also some terrain objects prevent UA be placed at, but a hero can pass over it. Like flowers or hole in a ground...

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> > A scenario without the ability to position an Ultimate Artifact by the program would be unplayable anyway, as there would be no place to move a hero
> 
> Don't forget that player can move over some objects. And also some terrain objects prevent UA be placed at, but a hero can pass over it. Like flowers or hole in a ground...

A map full of flowers. :)

The smallest scenario ever made.
Just dig to win. What else to do anyway. :)

Here is the test scenario file:
[Smallest scenario ever.zip](https://github.com/ihhub/fheroes2/files/5186712/Smallest.scenario.ever.zip)
