### ISSUE TITLE
Frequency of spell occurrence in Mage Guilds

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1531]
In the original game, there is a subtle balance about the occurrence of spells in mage guilds, third circle shrines and pyramids and also in mage guilds relative to each other.
For example, when a spell is available in a mage guild, it also appears more regularly in other mage guilds and different spells are available in third circle shrines and in pyramids, to a certain extent of course.
This has for effect of making shrines and pyramids always interesting to visit.

At least that's how I felt after practicing the original game a lot.

In fheroes2, Summon Elementals spells appear more often in mage guilds than in the original game.
In the original game, Summon Elementals spells are more likely to be available in pyramids.
And the Town Portal spell also appears much less often in the mage guild in the original game and a little more in the pyramids.
The Town Portal spell is very rare in mage guilds in the original game.
Set Guardian, Visions, Haunt spells are also very rare in mage guilds in the original game.

In original game:

![Mage Guild H2 01](https://user-images.githubusercontent.com/43583994/92223016-2586f100-eea0-11ea-8068-23bd3750eb7f.png)

![Mage Guild H2 02](https://user-images.githubusercontent.com/43583994/92223019-2750b480-eea0-11ea-88cf-6f1239e5fcea.png)

![Mage Guild H2 03](https://user-images.githubusercontent.com/43583994/92223021-2881e180-eea0-11ea-8da9-844a93fcd734.png)

![Mage Guild H2 04](https://user-images.githubusercontent.com/43583994/92223023-29b30e80-eea0-11ea-9636-8165930b4dde.png)

![Mage Guild H2 05](https://user-images.githubusercontent.com/43583994/92223027-2ae43b80-eea0-11ea-9488-683aa96f0ae0.png)

In fheroes2:

![Mage Guild fh2 01](https://user-images.githubusercontent.com/43583994/92223075-39caee00-eea0-11ea-94ed-ede840a87e4b.png)

![Mage Guild fh2 02](https://user-images.githubusercontent.com/43583994/92223085-3b94b180-eea0-11ea-8e01-ffed41efc3fa.png)

![Mage Guild fh2 03](https://user-images.githubusercontent.com/43583994/92223092-3d5e7500-eea0-11ea-9fe4-f900d51af20b.png)

![Mage Guild fh2 04](https://user-images.githubusercontent.com/43583994/92223097-3e8fa200-eea0-11ea-8841-e966a7f6a8ae.png)

![Mage Guild fh2 05](https://user-images.githubusercontent.com/43583994/92223099-3fc0cf00-eea0-11ea-949e-36cf57cbf1d7.png)

Here is the test scenario file:
[Frequency of spell occurrence in Mage Guilds.zip](https://github.com/ihhub/fheroes2/files/5173852/Frequency.of.spell.occurrence.in.Mage.Guilds.zip)

**Comment by Branikolog** [comment]
@LeHerosInconnu 
So, you want to say, that in the original game we have a higher chance to get the same spells in all mage guilds?

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> So, you want to say, that in the original game we have a higher chance to get the same spells in all mage guilds?

Only an examination of the source code could tell for sure.

But what is certain is that some spells have a very small percentage of appearance in the mage guilds, 1% or 2%.

**Comment by idshibanov** [comment]
> For example, when a spell is available in a mage guild, it also appears more regularly in other mage guilds and different spells are available in third circle shrines and in pyramids, to a certain extent of course.

Wrong, there's nothing like that in the original code. All spells are pre-determined when you start the game. For pyramids and shrines game simply rolls a number between 0 and 64. If spell with that ID is right level then it's added to the object otherwise it keeps rolling. Technically chance is even for every spell.

For castles there's multiple things happening, but they don't affect each other at all. I suspect that behavior that you learned to love and expect is there due to a weird logic in the original code.

First game makes sure that there's always one of damage spells (Arrow/Cold ray/Lightning/Cold ring/Fireball, 20% chance each) and dispels (Cure/Dispel/Mass/Antimagic, 25% chance each). Then it keeps rolling random spells based on the chance, but for human player castles (at the start of the game!) the chance for each spell is equal. If you create map with 10 castles and fully built mage guilds, you will see your "rare 1-2% spells" there.

For AI necromancer castles it also forces either Death Wave/Ripple to be there. For AI castles game actually uses internal "spell power" AI variable as chance to roll spells that computer thinks are more powerful. Armageddon for example is 2000 and summon elemental spell is only a 1000. All adventure spells (except Dimension Portal) priority for AI is 30, so it never appears there.

This is a fault (or a bug) of original code that we shouldn't reproduce.

**Comment by LeHerosInconnu** [comment]
Thank you for your explanation @idshibanov. :)

I made several tests with the original game.
Here are the observations for test 03 (the only complete one).

24 guilds, 28 spells (level 5).
24 pyramids, 24 spells (level 5).

Guilds human player:

- Mirror Image: 4
- Armageddon: 3
- Hypnotize: 3
- Resurrect True: 2
- Dimension Door: 1
- Summon Water Elemental: 1

Guilds AI player:

- Dimension Door: 3
- Hypnotize: 3
- Resurrect True: 3
- Armageddon: 2
- Mirror Image: 1
- Summon Earth Elemental: 1
- Summon Fire Elemental: 1

Guilds human and AI players:

- Summon Elemental spells : 3/28
- Town Portal: 0/28

Pyramids:

- Dimension Door: 6
- Summon Air Elemental: 5
- Hypnotise: 3
- Summon Earth Elemental: 3
- Summon Fire Elemental: 3
- Town Portal: 2
- Resurrect True: 1
- Summon Water Elemental: 1

Pyramids:

- Summon Elemental spells : 13/24
- Town Portal: 2/24

Set Guardian, Visions, Haunt spells are also very rare in mage guilds in the tests.

Here is the save file, the test scenario file and screenshots:

[Test guilds pyramids.zip](https://github.com/ihhub/fheroes2/files/5177134/Test.guilds.pyramids.zip)

**Comment by LeHerosInconnu** [comment]
@idshibanov.

> Then it keeps rolling random spells based on the chance, but for human player castles (at the start of the game!) the chance for each spell is equal. If you create map with 10 castles and fully built mage guilds, you will see your "rare 1-2% spells" there.

Does this mean that there is no set value for each spell as to how often spells appear in mage guilds?

> For AI necromancer castles it also forces either Death Wave/Ripple to be there.

This is indeed the case in all the tests carried out.

> For AI castles game actually uses internal "spell power" AI variable as chance to roll spells that computer thinks are more powerful. Armageddon for example is 2000 and summon elemental spell is only a 1000. All adventure spells (except Dimension Portal) priority for AI is 30, so those rarely appear there.

So the Armageddon spell will be available more often in AI mage guilds than the Summon Elemental spells and the Dimension Door spell will also be available more often in AI mage guilds.
As for adventure spells below level five, indeed AI has almost none in its mage guilds in the different tests.
The spells available in the AI's mage guilds will therefore, to some extent, be quite different from the spells available in the human player's mage guilds.

And how does it work for neutral cities at the beginning of the scenario? Is there a special rule for them?
