### ISSUE TITLE
Resurrected unit has wrong sprite

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1534]
After resurrecting a completely defeated stack of goblins, we can see animation of resurrection first:
![Ress](https://user-images.githubusercontent.com/55348946/92241907-a86f7200-eec7-11ea-9812-b738465c8b1c.png)
And after that we can see sleeping goblin on that place:
![Ress bug](https://user-images.githubusercontent.com/55348946/92241974-c50baa00-eec7-11ea-935d-95be851a2df9.png)

**Comment by Branikolog** [comment]
Even yellow edge on Goblins' turn appears around them. :D
![Sleeping Goblin](https://user-images.githubusercontent.com/55348946/92242179-161b9e00-eec8-11ea-9713-d65b7f6326d9.png)

**Comment by ihhub** [comment]
I have even better one:
![image](https://user-images.githubusercontent.com/19829520/92295910-ca1d3780-ef61-11ea-9d20-90f483491f34.png)
