### ISSUE TITLE
View Puzzle screen, wrong position for the location of the Ultimate Artifact

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1536]
The crosshair graphic used for the location of the Ultimate Artifact is displayed at the top of the screen.

In fheroes2:

![View Puzzle no obelisk bug 01](https://user-images.githubusercontent.com/43583994/92248102-74e11780-eec8-11ea-9ef1-42480bb05529.png)

In this scenario, the 9 squares from map edge rule for the position of the Ultimate Artifact cannot be respected.

![9 squares rule 01](https://user-images.githubusercontent.com/43583994/92248543-26804880-eec9-11ea-87e2-c0315daa39ee.png)

In this scenario, the 9 squares from map edge rule for the position of the Ultimate Artifact can be respected.

![Ultime Artifact without personalized position 02](https://user-images.githubusercontent.com/43583994/92247916-34819980-eec8-11ea-8f4b-ed2ae5dc89e7.png)

Here are the test scenario files:
[Ultimate Artifact no obelisk.zip](https://github.com/ihhub/fheroes2/files/5173233/Ultimate.Artifact.no.obelisk.zip)
[Ultimate Artifact graphic location.zip](https://github.com/ihhub/fheroes2/files/5175243/Ultimate.Artifact.graphic.location.zip)

**Comment by Branikolog** [comment]
Well done! The cross is no more drawn out of puzzle map range.
But, " the 9 squares from map edge rule" is not working properly still.
![image](https://user-images.githubusercontent.com/55348946/94422296-8d72e380-018f-11eb-9d17-fa2404975eb0.png)
On the screenshot we can see the upper edge of a world map. When game have the only space to put artifact on the square to the left of current, we can see no puzzle map at all, even if we have an obelisk. I suppose the same should happen to current situation on a screenshot, as we're too close to the edge.
The only question I have is do we need to prevent UA from appearing at such places at all? Or do we should allow game to place artifacts close to edge (in a cases we don't have any free squares on the whole map)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

In the original game, the rule of 9 squares is there to avoid problems with the edges of the map (say the Ultimate Artifact is positioned right in the place of the hero in the example).
First an aesthetic problem and the recognition of the map around the position of the Ultimate Artifact.
It is not very nice to display the edge of the map in the puzzle screen.
It is difficult to recognize the position on the map if only the revealed puzzle parts are located in the edge space.
Then a problem of "cheating".
It is easier to locate the position of the Ultimate Artifact if part of the frame is displayed in the puzzle screen.

In original game:

![Ultime Artifact view puzzle H2 10](https://user-images.githubusercontent.com/43583994/94431938-45a38a80-0196-11eb-80be-879173fd785a.png)

Now the scenario creator really has to intentionally create a scenario without the ability to place the Utimate Artifact with the 9 squares rule.
A scenario with only land located around the map within the limit of 9 squares.
I have never seen such a map.
To avoid this, a message should appear in the scenario editor when this happens.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu and @Branikolog , could you please verify this issue again as I remember we fixed it some time ago?

**Comment by LeHerosInconnu** [comment]
> Hi @LeHerosInconnu and @Branikolog , could you please verify this issue again as I remember we fixed it some time ago?

I will do some more tests later.

**Comment by LeHerosInconnu** [comment]
@ihhub.

> > Hi @LeHerosInconnu and @Branikolog , could you please verify this issue again as I remember we fixed it some time ago?
> 
> I will do some more tests later.

I did some tests, everything seems to work fine.

**Comment by ihhub** [comment]
Excellent! Thank you very much!
