### ISSUE TITLE
View Puzzle screen, no crosshair graphic displayed for the location of the Ultimate Artifact

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1537]
The crosshair graphic used for the location of the Ultimate Artifact is not displayed when the creator of the scenario has not positioned it in the scenario editor.

In fheroes2, Ultime Artifact without personalized position:

![Ultime Artifact without personalized position 01](https://user-images.githubusercontent.com/43583994/92247912-32b7d600-eec8-11ea-94bb-70554fdf2ec5.png)

In fheroes2, Ultime Artifact with personalized position:

![Ultime Artifact with personalized position 01](https://user-images.githubusercontent.com/43583994/92253018-54688b80-eecf-11ea-929b-6af9e3e02452.png)

Here are the test scenario files:
[Ultimate Artifact graphic location.zip](https://github.com/ihhub/fheroes2/files/5175243/Ultimate.Artifact.graphic.location.zip)

**Comment by Branikolog** [comment]
If I'm not mistaken, the crosshair is placed in the top of the map, out of range of puzzle screen.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> If I'm not mistaken, the crosshair is placed in the top of the map, out of range of puzzle screen.

I don't know where it is, but it's not where it should be.

Part of the cross may also be visible at the top of the screen. (https://github.com/ihhub/fheroes2/issues/1536)
I don't know if these two bugs are related.
