### ISSUE TITLE
Observation tower doesn't uncover correct area

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#154]
This is the size of area which is uncovered by visiting observation tower:
![image](https://user-images.githubusercontent.com/19829520/66314826-30ab6700-e947-11e9-80ff-5c380beb5872.png)
![image](https://user-images.githubusercontent.com/19829520/66314851-3dc85600-e947-11e9-8015-3561c92cf617.png)

and this is how it should be:
![image](https://user-images.githubusercontent.com/19829520/66314836-3608b180-e947-11e9-937c-340b63e92250.png)
![image](https://user-images.githubusercontent.com/19829520/66314882-50db2600-e947-11e9-89e4-3b616b0fd77a.png)

**Comment by mast4461** [comment]
The view distance values, and the constant term in the distance calculation, might need to be adjusted, but apart from that I think #163 and #164 close this issue. :)
