### ISSUE TITLE
Combat screen, wrong creature speed information

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1544]
In fheroes2, when a troop has passed its turn or made its move, the information about the creature's speed is changed to "Speed: Standing (0)".
This is not very useful to know the creature's speed the next turn, in the example with the Haste spell cast on the troop.

In the original game, this information remains consistent.

In original game:

![Wrong creature speed information 01](https://user-images.githubusercontent.com/43583994/92304269-ba5f1c80-ef7c-11ea-99da-e4353a9b2f82.png)

![Wrong creature speed information 02](https://user-images.githubusercontent.com/43583994/92304270-bcc17680-ef7c-11ea-8ebe-2123d064588b.png)

In fheroes2:

![Wrong creature speed information 03](https://user-images.githubusercontent.com/43583994/92304272-be8b3a00-ef7c-11ea-9c52-9c17fc5944b8.png)

![Wrong creature speed information 04](https://user-images.githubusercontent.com/43583994/92304273-c054fd80-ef7c-11ea-9be7-6c95bb6600c5.png)

![Wrong creature speed information 05](https://user-images.githubusercontent.com/43583994/92304274-c21ec100-ef7c-11ea-9d3c-7d3c6618a3b3.png)

![Wrong creature speed information 06](https://user-images.githubusercontent.com/43583994/92304276-c3e88480-ef7c-11ea-84dd-08fa1aab7d48.png)

**Comment by Branikolog** [comment]
On the other hand, here we can know the useful information, if a certain unit made any action during this round.
Surely, we should go for original implementation first, but I would like to have both of these info blocks...

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> On the other hand, here we can know the useful information, if a certain unit made any action during this round.
> Surely, we should go for original implementation first, but I would like to have both of these info blocks...

Yes, this information can be added in another way without displaying erroneous information about the creature's speed.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu and @Branikolog , I can change it with ease but we haven't decided how we're going to separate creatures which moved and didn't?
Solution 1: display creature's speed string and value if it hasn't been moved otherwise creature's speed string and (0)
Solution 2: always display creature's speed string and value independent from creature's movement
Solution 3: display a separate indicator that the creature has moved.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu and @Branikolog , I can change it with ease but we haven't decided how we're going to separate creatures which moved and didn't?
> Solution 1: display creature's speed string and value if it hasn't been moved otherwise creature's speed string and (0)
> Solution 2: always display creature's speed string and value independent from creature's movement
> Solution 3: display a separate indicator that the creature has moved.

I will go for solution 3. :)

**Comment by Branikolog** [comment]
I think we should go for original implementation for now. 
And make separate enhancement issue to display the case, when troop has already performed an action.

**Comment by ihhub** [comment]
@LeHerosInconnu and @Branikolog please create a separate topic in `Discussions` how we could indicate moved creature. Once we come up with the idea we can create needed issue.
