### ISSUE TITLE
Adventure map, Ultimate Artifact, "Congratulations!" window, add a dot "." at the end of the text sentence

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1560]
In the original game, a dot "." is missing at the end of the text sentence.
It is the same in fheroes2.

In original game:

![Ultimate Artifact minimalist map H2 01](https://user-images.githubusercontent.com/43583994/92376431-dd1b3d80-f102-11ea-976c-db710f63a645.png)

In fheroes2:

![Ultimate Artifact minimalist map fh2 02](https://user-images.githubusercontent.com/43583994/92376454-e5737880-f102-11ea-8b1f-e04e6558d636.png)

**Comment by ihhub** [comment]
Hi @Aditya-Srivastav , please go ahead and do. You can ignore .po files for now.
