### ISSUE TITLE
Adventure map, scenario, "...7 days left to capture a town..." window, add "Beware!" as the title of the window

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1561]
I suggest adding the title "Beware!" to this window.

In the original game, this window also has no title.

![Ultimate Artifact minimalist map fh2 01](https://user-images.githubusercontent.com/43583994/92376633-2a97aa80-f103-11ea-8068-187c6e19b1e6.png)

**Comment by Kazhuu** [comment]
@LeHerosInconnu I'm trying to implement this. I noticed the same code is used for this window as well. Do you want to add title to this one as well?
![image](https://user-images.githubusercontent.com/11016113/232307479-be5b8d49-22e0-48db-a42c-898d4ad0db79.png)

**Comment by Kazhuu** [comment]
I also added same title to the dialog which informs you about the last day you are in play
![image](https://user-images.githubusercontent.com/11016113/232307613-c7dd6deb-c80f-430b-b479-54ad45b99073.png)

**Comment by LeHerosInconnu** [comment]
Hello @Kazhuu,

> @LeHerosInconnu I'm trying to implement this. I noticed the same code is used for this window as well. Do you want to add title to this one as well?
> ![image](https://user-images.githubusercontent.com/11016113/232307479-be5b8d49-22e0-48db-a42c-898d4ad0db79.png)

For this window you can display the yellow title "Major Event!".
I have made a request for a choice or another proposal here: https://github.com/ihhub/fheroes2/issues/1649.

> I also added same title to the dialog which informs you about the last day you are in play
> ![image](https://user-images.githubusercontent.com/11016113/232307613-c7dd6deb-c80f-430b-b479-54ad45b99073.png)

Yes, "Beware!" should be the yellow title of all windows from "...7 days left..." to "...last day...".
 
> When it is your last day and you press end turn this dialog is shown. What tittle we should use for this?
> ![image](https://user-images.githubusercontent.com/11016113/232307803-a3805aca-de57-4ec6-a37b-e4aca770d7bd.png)

The yellow title of this window should be "Defeat!".

**Comment by Kazhuu** [comment]
Okay thanks @LeHerosInconnu. How about this dialog?

![image](https://user-images.githubusercontent.com/11016113/232310122-65ada3ae-20e2-45a9-8de0-88adb7aaf49b.png)

**Comment by LeHerosInconnu** [comment]
@Kazhuu.

> Okay thanks @LeHerosInconnu. How about this dialog?
> 
> ![image](https://user-images.githubusercontent.com/11016113/232310122-65ada3ae-20e2-45a9-8de0-88adb7aaf49b.png)

Here too, "Beware!" is the correct yellow title.

**Comment by Kazhuu** [comment]
Okay these are now done @LeHerosInconnu.
