### ISSUE TITLE
Magic book, spells order

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1564]
In the original game, spells are placed in a certain order in the magic book.
For example, simple spells and mass spells of the same spell are placed next to each other.
For adventure spells, too, there is a specific placement.
For example, "View" and "Hero" spells are placed first, "Summon Boat", "Dimension Door" and "Towns" spells are grouped together, "Set Guardian" spells are grouped together, and so on.

In fheroes2, it's a big mess, difficult to find your way around quickly.

It is necessary to put some consistency in all this.

In original game:

![Spells order H2 01](https://user-images.githubusercontent.com/43583994/92383959-8e27d500-f10f-11ea-96e5-2edc0e424170.png)

![Spells order H2 02](https://user-images.githubusercontent.com/43583994/92383963-8f590200-f10f-11ea-9651-8e5a2231bc22.png)

![Spells order H2 03](https://user-images.githubusercontent.com/43583994/92383969-908a2f00-f10f-11ea-9a1c-38932072ac0f.png)

![Spells order H2 04](https://user-images.githubusercontent.com/43583994/92383973-91bb5c00-f10f-11ea-9bb9-66c7feeeb4f7.png)

![Spells order H2 05](https://user-images.githubusercontent.com/43583994/92383976-92ec8900-f10f-11ea-96c8-3e7a0f528585.png)

![Spells order H2 06](https://user-images.githubusercontent.com/43583994/92383979-941db600-f10f-11ea-9a63-3e8a276bf9b0.png)

In fheroes2:

![Spells order fh2 01](https://user-images.githubusercontent.com/43583994/92384001-9a139700-f10f-11ea-9815-20fecf012823.png)

![Spells order fh2 02](https://user-images.githubusercontent.com/43583994/92384006-9bdd5a80-f10f-11ea-89a0-f2cd43a091d3.png)

![Spells order fh2 03](https://user-images.githubusercontent.com/43583994/92384009-9d0e8780-f10f-11ea-98ee-f0e0b7e7025c.png)

![Spells order fh2 04](https://user-images.githubusercontent.com/43583994/92384012-9e3fb480-f10f-11ea-8742-8e8420bb9b05.png)

![Spells order fh2 05](https://user-images.githubusercontent.com/43583994/92384018-9f70e180-f10f-11ea-8953-bf241c854c46.png)

![Spells order fh2 06](https://user-images.githubusercontent.com/43583994/92384025-a0a20e80-f10f-11ea-890b-4dec82ce98af.png)

**Comment by Branikolog** [comment]
> In fheroes2, it's a big mess, difficult to find your way around quickly.

Currently spells are placed in alphabetic order... 
Agreed, not the best decision.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> > In fheroes2, it's a big mess, difficult to find your way around quickly.
> 
> Currently spells are placed in alphabetic order...
> Agreed, not the best decision.

In fheroes2, the spells don't seem to be sorted alphabetically, or else there is a big bug. :)

**Comment by Branikolog** [comment]
> In fheroes2, the spells don't seem to be sorted alphabetically, or else there is a big bug.

My fault. I check my spells in battle more often...
![image](https://user-images.githubusercontent.com/55348946/92517992-5492bf00-f220-11ea-9db7-bd9457c63991.png)
Here's alphabetical order.
In all other info windows is not. You're completely right!

**Comment by LeHerosInconnu** [comment]
@Branikolog.

I compared in the fastest way, just after visiting a group of mage guilds. :)
But you're right, it's even different between the adventure map and during combat.
A vertical alphabetical order during combat. :)
