### ISSUE TITLE
Hero, combat, allow to view the magic book when a spell has already been cast for the current turn

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1566]
One enhancement I'd like to see in fheroes2 is to allow viewing the magic book when a spell has already been cast for the current turn.

When the player has several heroes, it is sometimes difficult to remember which hero has which spells.
And before performing an action with a troop during a combat, it is sometimes necessary to consult the magic book to know if the hero has a certain spell.
Unfortunately this is not possible if a spell has already been cast for the current turn.

It would be nice to add this possibility to fheroes2.
The graphic of the button is changed to indicate to the player that he can consult the magic book without being able to cast a spell.

In fheroes2:

![View magic book spell already been cast 01](https://user-images.githubusercontent.com/43583994/92402338-b0314f80-f12f-11ea-8ef3-9b7a8fae5534.png)

**Comment by Branikolog** [comment]
I'd like to suggest to combine this issue with #1566.
We should add an option to click over hero's portrait to enter hero menu, where we can check all hero info and even enter a spellbook and look through it.
