### ISSUE TITLE
Hero, combat, allow to consult the hero screen during combat

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1567]
One enhancement I'd like to see in fheroes2 is to allow consulting the hero's screen to see the artifacts he owns.

When the player has several heroes, it is sometimes difficult to remember which hero has which artifacts.
For example, before using a spell or before performing an action with a troop during a combat, it would sometimes be convenient to know which artifacts the hero has.
And to know also the level of the hero, etc. when a surrender or a retreat is envisaged.
Unfortunately, this is not possible.

It would be nice to add this possibility to fheroes2.
For example by clicking on the portrait of the hero to access the hero's screen or a window is displayed containing the artifacts owned by the hero and it is possible to have information about the artifacts, and information about the hero.

In fheroes2:

![View magic book spell already been cast 01](https://user-images.githubusercontent.com/43583994/92402338-b0314f80-f12f-11ea-8ef3-9b7a8fae5534.png)

![Consult hero screen during combat 01](https://user-images.githubusercontent.com/43583994/92403014-eb804e00-f130-11ea-8644-8256d530df0a.png)

**Comment by Branikolog** [comment]
I'd like to suggest to combine this issue with #1566.
We should add an option to click over hero's portrait to enter hero menu, where we can check all hero info and even enter a spellbook and look through it.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> I'd like to suggest to combine this issue with #1566.
> We should add an option to click over hero's portrait to enter hero menu, where we can check all hero info and even enter a spellbook and look through it.

Yes, the two options can be combined into one and viewing the hero's screen would be the most convenient I think.
