### ISSUE TITLE
Game shouldn't create a new savefile for each day

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1571]
Currently, each day game always offers to create a new savefile with a day number in it.
This leads to annoying appearing lots of unnecessary savefiles while saving on a default.
Surely, it can be an option that saves the game each day. It can be useful for tournaments, probably... Game: Creating a save each day...  So player can load game at any day he wants... We even can place them in a special folder,  like we've discussed in #1221.

But on default, a previous saved file should be selected, so player shouldn't choose each time needed file.

**Comment by Branikolog** [comment]
If I'm not mistaken, in the OG it works like this. There's always the last saved file selected on a default.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> Currently, each day game always offers to create a new savefile with a day number in it.

I will go even further.
When I'm testing or even playing, sometimes I save the game even several times per turn.
For me an option that allows me to do this automatically would be welcome: "Game: Create a different save file for each save".

> This leads to annoying appearing lots of unnecessary savefiles while saving on a default.

This option may address this problem for some types of players: https://github.com/ihhub/fheroes2/issues/1529

> Surely, it can be an option that saves the game each day. It can be useful for tournaments, probably... Game: Creating a save each day... So player can load game at any day he wants... We even can place them in a special folder, like we've discussed in #1221.

Yes, different options should be offered.
All users can have a different way of doing things.
They must be given the possibility to do so.

> But on default, a previous saved file should be selected, so player shouldn't choose each time needed file.
> If I'm not mistaken, in the OG it works like this. There's always the last saved file selected on a default.

Yes, in the original game, the last save is selected by default.

**Comment by ihhub** [comment]
Hi @Branikolog and @LeHerosInconnu , please provide a proper solution for this issue without an introduction of an option or with a mockup of the UI look for this feature.

If you think that this idea needs some time and it is not ready we can move it to discussions.

**Comment by ihhub** [comment]
Let's close it for now. If you find a better solution please reopen this issue.
