### ISSUE TITLE
Adventure map, End Turn window, add the yellow title "Beware!" to this window

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1576]
I suggest to add the yellow title "Beware!" to this window.

In fheroes2:

![End turn window fh2 01](https://user-images.githubusercontent.com/43583994/92459950-9cd1c300-f1c7-11ea-9044-302525e14f63.png)

**Comment by Branikolog** [comment]
"Beware" is too scary. :)
We can simply name this window "End Turn".

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> "Beware" is too scary. :)
> We can simply name this window "End Turn".

I had thought of "End Turn" but I think it's a bit too much of a "computer" term.
The term must remain in the feeling of playing a game.
And on top of that, the words "end... turn" are already in the sentence and I found that repetitive.

We need a native English speaker to find the right term. :)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

What do you think of "Be Careful!" or "Pay Attention!".

**Comment by Branikolog** [comment]
Hummm... 
"Pay Attention" looks better but...
"End Turn" is still my #1.))
Between, we're already have this implementation:
![image](https://user-images.githubusercontent.com/55348946/92737765-157d7e80-f384-11ea-8ec0-56006532ca8d.png)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

Let's go for "End Turn" then. :)
