### ISSUE TITLE
Adventure map, Water Wheel, wrong passability/pathfinding for the water wheel

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1577]
The lower center square of the water wheel should be passable.

In original game:

![Path near water wheel H2 01](https://user-images.githubusercontent.com/43583994/92460097-d6a2c980-f1c7-11ea-86c4-54aae6ec9030.png)

![Path near water wheel H2 02](https://user-images.githubusercontent.com/43583994/92460103-d86c8d00-f1c7-11ea-972b-b1f0909d68d2.png)

![Path near water wheel H2 03](https://user-images.githubusercontent.com/43583994/92460106-d99dba00-f1c7-11ea-9627-c495dd9530c8.png)

In fheroes2:

![Path near water wheel fh2 01](https://user-images.githubusercontent.com/43583994/92460128-e15d5e80-f1c7-11ea-81bb-79d735e9ba90.png)

![Path near water wheel fh2 02](https://user-images.githubusercontent.com/43583994/92460133-e3272200-f1c7-11ea-8242-3bec67630702.png)

![Path near water wheel fh2 03](https://user-images.githubusercontent.com/43583994/92460138-e4584f00-f1c7-11ea-944d-c2cab774891b.png)

**Comment by ihhub** [comment]
Closing this issue as it was fixed in #3522.
