### ISSUE TITLE
Adventure map, New Week window, add the yellow title "New Week!" to this window

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1582]
I suggest to add the yellow title "New Week!" to this window.

In fheroes2:

![New week window fh2 01](https://user-images.githubusercontent.com/43583994/92460938-e4a51a00-f1c8-11ea-981e-cca5b5f397b0.png)

**Comment by ihhub** [comment]
This proposed feature needs some feedback.

@zenseii , @Branikolog  what do you think?
