### ISSUE TITLE
Adventure map, Magic Garden, New Week window, wrong title color

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1583]
The title of this window should be yellow.
This window is displayed at the beginning of each new week when the option "world: Wind/Water Mills and Magic Garden can be captured" is enabled.

In fheroes2:

![Magic garden new week fh2 01](https://user-images.githubusercontent.com/43583994/92461049-08686000-f1c9-11ea-8021-05e786eee92b.png)

**Comment by ihhub** [comment]
Closing as duplicate of #2154.
