### ISSUE TITLE
Adventure map, Windmill, New Week window, wrong title color

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1584]
The title of this window should be yellow.
This window is displayed at the beginning of each new week when the option "world: Wind/Water Mills and Magic Garden can be captured" is enabled.

In fheroes2:

![Windmill new week fh2 01](https://user-images.githubusercontent.com/43583994/92461151-3057c380-f1c9-11ea-90e3-9a58c9a706f6.png)

**Comment by ihhub** [comment]
Closing as duplicate of #2154.
