### ISSUE TITLE
Adventure Map, Oracle screen, wrong position of the columns

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1593]
In fheroes2, the horizontal position of the columns "1st", "2nd", etc. is not the same as in the original game.

In original game:

![Oracle 03](https://user-images.githubusercontent.com/43583994/92477560-1924d000-f1e1-11ea-982e-702f5da12638.png)

In fheroes2:

![Oracle 04](https://user-images.githubusercontent.com/43583994/92477396-d19e4400-f1e0-11ea-86b4-bc8533d0d088.png)

**Comment by Aditya-Srivastav** [comment]
Hey ,
I've figured out the issue.
In [File](https://github.com/ihhub/fheroes2/blob/9ae6662d85e4214a571ab99789b6d4bd8852b9c2/src/fheroes2/dialog/dialog_thievesguild.cpp)
Seems like in `void DrawHeroIcons( )` https://github.com/ihhub/fheroes2/blob/9ae6662d85e4214a571ab99789b6d4bd8852b9c2/src/fheroes2/dialog/dialog_thievesguild.cpp#L208  
,  `void DrawFlags( )` https://github.com/ihhub/fheroes2/blob/9ae6662d85e4214a571ab99789b6d4bd8852b9c2/src/fheroes2/dialog/dialog_thievesguild.cpp#L189 
and in `void Dialog::ThievesGuild( )` https://github.com/ihhub/fheroes2/blob/9ae6662d85e4214a571ab99789b6d4bd8852b9c2/src/fheroes2/dialog/dialog_thievesguild.cpp#L275 

The total width is divided by the number of columns required. ( ie `count` , `v.size()` and `colors.size()`)
which makes it look like equally seperated.

IMO best way to fix would be to limit the width of column which would not depend on the number of columns .
Idk what exact width they have used in original one.

Let me know the exact width to be used or any other way to fix it.

**Comment by LeHerosInconnu** [comment]
Hi @Aditya-Srivastav,

Personally, I don't mind if the columns are distributed in the available space, as long as this is done correctly.
If you look at the current screen, it is immediately obvious that this is not the case.
The spaces on either side of the columns are not uniform, they are of different widths.
This makes the screen uggly.

In the original game, the spacing between the two points of the text ":" and the frame of the first portrait is 39 pixels and the spacing between the frames of the portraits is 30 pixels.
The width of each column is 68 pixels, 38 pixels for the portrait frame plus 30 pixels spacing.

In original game:

![Oracle screen espacement modifié 01](https://user-images.githubusercontent.com/43583994/92580153-57c49400-f28e-11ea-9408-0edbfd431b3d.png)

**Comment by Aditya-Srivastav** [comment]
I've fixed this one,
Can u tell me how to reproduce this screen so that i can test it .
Thx.

**Comment by LeHerosInconnu** [comment]
@Aditya-Srivastav.

Load the scenario and visit the Oracle with the hero.

![Move Oracle 01](https://user-images.githubusercontent.com/43583994/92594406-ff4bc180-f2a2-11ea-9fe1-889909adf83c.png)

![Move Oracle 02](https://user-images.githubusercontent.com/43583994/92594411-01158500-f2a3-11ea-9a64-0e7a80fd5014.png)

Here are the test scenario files:
[Test Oracle.zip](https://github.com/ihhub/fheroes2/files/5194884/Test.Oracle.zip)
