### ISSUE TITLE
Combat, Ghosts, number of Ghosts not taken into account at the end of the combat

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1600]
The Ghosts who joined the hero's army are not taken into account at the end of the combat.

In fheroes2:

![Number of Ghosts 01](https://user-images.githubusercontent.com/43583994/92509021-dd523080-f209-11ea-9245-c797f44bc921.png)

![Number of Ghosts 02](https://user-images.githubusercontent.com/43583994/92509025-dfb48a80-f209-11ea-91a0-8572b6655007.png)

![Number of Ghosts 03](https://user-images.githubusercontent.com/43583994/92509030-e17e4e00-f209-11ea-9d71-2649c383d8da.png)

![Number of Ghosts 04](https://user-images.githubusercontent.com/43583994/92509031-e2af7b00-f209-11ea-96f2-183f56606ed7.png)

![Number of Ghosts 05](https://user-images.githubusercontent.com/43583994/92509037-e4793e80-f209-11ea-91ac-c9cdfc32cbbf.png)

![Number of Ghosts 06](https://user-images.githubusercontent.com/43583994/92509040-e5aa6b80-f209-11ea-8479-e9eff9ef92b8.png)

Here is the test scenario file:
[Number of Ghosts.zip](https://github.com/ihhub/fheroes2/files/5189996/Number.of.Ghosts.zip)

**Comment by ihhub** [comment]
This issue has been fixed some time ago.
