### ISSUE TITLE
Music from the city continues playing, after player exits

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1604]
City soundtrack stops playing, when we exit, in the OG.
Currently we can hear city music, until we choose a hero.

**Comment by 1GodRage** [comment]
**How to reproduce this bug:**
Music is MIDI or MIDI extended.
Starting location is Wasteland terrain type. _(there is no music in Wasteland, so this bug could happens in Water also)_
Wait before opening castle: there is no music...
Open castle: music of the castle.
Exit castle: music of the castle remains.

But in a previous game (map was official map "Bien contre Mal" (english name is probably somethign like "Good vs Evil")), the game even started to play random musics; I heard battle music starting to play while I was pathing in Wasteland terrain.
But couldn't reproduce it.
