### ISSUE TITLE
Combat, order of play of the creatures with many troops of summoned elementals on the battlefield

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1609]
When there are a certain number of summoned elemental troops (I don't know exactly how many), the program does not give the correct order of play to the creatures.
For example, the champions at the top of the screen (in the first row) play first, then the champions at the bottom of the screen (in the last row) instead of those in second position (in the third row), then the champions in the seventh row, etc.
Same for boars, they don't play in the correct order, or the summoned elementals play before the boars, etc.

Summon elementals continuously with the two heroes in multiplayer mode.
Here is the save file:
[Full elementals.zip](https://github.com/ihhub/fheroes2/files/5195265/Full.elementals.zip)

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu I decided to deal with this bug but could not reproduce it, or may be I summoned not enough elementals. Summoned 15 groups of water elementals, but this still not caused reordering of unit's turns. Could you please check again whether this issue is still being observed or it has been already fixed, and if it still observed, then how many groups of elementals should be summoned?

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> Hi @LeHerosInconnu I decided to deal with this bug but could not reproduce it, or may be I summoned not enough elementals. Summoned 15 groups of water elementals, but this still not caused reordering of unit's turns. 
Could you please check again whether this issue is still being observed or it has been already fixed, and if it still observed, then how many groups of elementals should be summoned?

Many more elemental groups need to be summoned for this to happen.
It happens when the battlefield is almost full of elementals.

![Full elementals 09](https://user-images.githubusercontent.com/43583994/92601422-1099cb80-f2ad-11ea-8a45-f14190d3568a.png)

I'll do another test.

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu 

> It happens when the battlefield is almost full of elementals.

OMG :)

> I'll do another test.

I will be very grateful for that. I'll try to reproduce this once again too...

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> I'll do another test.

Everything works properly until turn 28.
The troop of Champions in fifth position plays before the troop of Champions in second position.
There are 28 Fire Elemental troops on one side and 27 Air Elemental troops on the other.

Later it's the same for the troops of Boars, they don't play in the correct order, or the summoned Elementals play before the troops of Boars, etc.
Also Fire Elementals and Air Elementals do not play in the right order (order of summoning).

Here is a video of the full combat:
I will delete the file in 30 days (file about 257MB).
The link will be available after the video has been uploaded (about 1 hour).

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu Thank you very much, I was able to reproduce this issue and found the root cause.
