### ISSUE TITLE
Combat, add the "Game: Display spell effect area" option

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1626]
In fheroes2, it would be nice to add an option that display the spell effect area for damage spells during combat.

The hexagons where the spell will take effect are grayed out in a darker way and the outline of the hexagons becomes red.

The creatures hit with the Chain Lightning spell are also clearly indicated, the background color of the hexagons becomes darker and the outline of the hexagons where the troops are located becomes red.
Both hexagons are indicated if the troop occupies two hexagons.

For damage spells without an area of effect (Lightning, etc.), the outline of the hexagon where the targeted troop is located must also becomes red to maintain consistency of indication in the game.
Both hexagons are indicated if the troop occupies two hexagons.

Here is a screen I used for the previous fheroes2 project to explain how it works.
This screen is for explanatory purposes only.

![Heroes 2 Screen 76](https://user-images.githubusercontent.com/43583994/92746655-bddf1300-f383-11ea-92e5-58513ea3fbf6.png)

**Comment by Branikolog** [comment]
> The creatures hit with the Chain Lightning spell are also clearly indicated, the background color of the hexagons becomes darker

Correct me if I'm wrong, but "Chain Lightning" spell works like a random, so we cannot know, in most cases, where'd it shoot, if there're more than one close targets.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> > The creatures hit with the Chain Lightning spell are also clearly indicated, the background color of the hexagons becomes darker
> 
> Correct me if I'm wrong, but "Chain Lightning" spell works like a random, so we cannot know, in most cases, where'd it shoot, if there're more than one close targets.

No, the Chain Lightning spell is not random.
After hitting the first troop, the spell hits the nearest troop.
The distance is calculated according to the center of each creature's sprite graphic.

If two troops are at the same distance, it is the troop which is the closest according to the position of the troop in the hero's army at the beginning of the combat and also according to the attacking and defending hero who is hit.

Examples:
If both troops are in the same army, for example the one that was in the first slot of the attacking hero's army at the beginning of the combat and the one that was in the third slot, it is the one that was in the first slot at the beginning of the combat who is hit.

If the two troops are in different armies, for example the third slot of the attacking army and the fifth slot of the defending army, the troop in third slot of the attacking army is hit.

If the two troops are in different armies and in the same slot at the beginning of the combat, for example in the second slot of each army, the troop in the army of the first hero, the attacking hero, is hit.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu and @Branikolog I took steps forward and implemented this for 4 spells except chain lighting as this spell is still buggy.

**Comment by ihhub** [comment]
Also there is not option for toggle on/off. I don't think we damage any user experience by having such interface. If you have concerns please let me know.

**Comment by Branikolog** [comment]
Good. 
We have a lot of time to test, as it works now. We always can make changes if required.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

Ah, nice. :)
It's okay for it to be integrated directly (without being an option) because it improves the game without changing the way it works.

I will do some testing. :)
