### ISSUE TITLE
Hero, Magic Book, spell info window, add the "Game: Display additional spell info in Magic Book" option

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1632]
In fheroes2, it would be nice to add an option that display some additional information about the spell in the spell info windows.

A sentence is added in the spell's information window to indicate additional information about the effect of the spell depending on the hero who uses it.
An additional sentence is added when the hero has an artifact that modifies the effect of the spell.

For the damage spells "Magic Arrow", "Death Ripple", etc.:
Example with the "Lightning Bolt" spell:
Without artifact that modifies the effect of the spell:
"This spell does 50 points of damage when Natasha casts it."

With the artifact "Lighting Rod":
"Natasha has the Lighting Rod artifact which increases the damage of this spell by 50%.
This spell does 75 damage when Natasha casts it."

For the "Cure" and "Mass Cure" spells:
Example with the "Cure" spell:
"This spell restores 10 HP when Natasha casts it."

For the resurrection spells "Animate Dead", "Resurrect", etc.:
Example with the "Resurrect True" spell:
With no artifact that modifies the effect of the spell:
"This spell restores 100 HP when Natasha casts it."

With the artifact "Ankh":
"Natasha has the Ankh artifact which doubles the effectiveness of this spell.
This spell restores 200 HP when Natasha casts it."

For "Set Guardian" spells:
Example with the spell "Set Earth Guardian":
"This spell summons 8 Earth Elementals to guard the mine when Natasha casts it."

For the "Town Gate" spell:
The name of the nearest village/castle and the possibility to welcome the hero are indicated.

Example with a castle occupied by another hero:
“The nearest castle is Algary.
This castle is occupied by your hero Halon."

Example with a town which is not occupied:
"The nearest town is Sorpigal.
This town can welcome you."

For "Summon Elemental" spells:
Example with the spell "Summon Air Elemental":
Without artifact which modifies the effect of the spell:
"This spell summons 6 Air Elementals when Natasha casts it."

With the "Book of Elements" artifact:
"Natasha has the Book of Elements artifact which doubles the effectiveness of this spell.
This spell summons 12 Air Elementals when Natasha casts it."

With the "Book of Elements" and "Elemental Ring" artifacts:
"Natasha has the Book of Elements artifact which doubles the effectiveness of this spell and the Elemental Ring which halves the cost of this spell.
This spell summons 12 Air Elementals when Natasha casts it for only half the cost of the spell."

For "Earthquake" spell:
"This spell will inflict 1 damage to all walls during siege combat when Natasha casts it."

In fheroes2:

![Additional spell info Magic Book 01](https://user-images.githubusercontent.com/43583994/92919824-7911b580-f431-11ea-865d-e21d00ed23ce.png)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , we added additional information for many existing spells. Should we close it or at least update the issue?

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , we added additional information for many existing spells. Should we close it or at least update the issue?

I close the issue and will open a discussion to add a small "+" graphic (or other) next to the spell icon in the magic book to visually and directly indicate when an artifact modifies the spell or the effects of the spell compared to the original spell.
