### ISSUE TITLE
Shadows are drawn under a road

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1635]
Roads a drawn over some shadows in game:
![image](https://user-images.githubusercontent.com/55348946/92937962-a885e980-f454-11ea-8097-b10628067eff.png)

**Comment by idshibanov** [comment]
This is actually not a "graphics" drawing bug, but more of a map data issue. Every map tile can have multiple "addons", sub-objects. In this case they are just ordered wrong.
