### ISSUE TITLE
Adventure map, resource generators, there should not be a gray flag on the resource generators when a player loses the game

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1640]
In fheroes2, when a player loses the game, the resource generators that were under his control have the flag color changed to gray.
In the original game the flags are removed, there is no gray flag.

In original game:

![Resource generator flag H2 01](https://user-images.githubusercontent.com/43583994/92989521-31dd0080-f4d5-11ea-80ba-63a4f9e4e726.png)

![Resource generator flag H2 02](https://user-images.githubusercontent.com/43583994/92989524-33a6c400-f4d5-11ea-92da-47193c55d0a7.png)

![Resource generator flag H2 03](https://user-images.githubusercontent.com/43583994/92989525-34d7f100-f4d5-11ea-87bf-d754df0c93ba.png)

In fheroes2:

![Resource generator flag fh2 01](https://user-images.githubusercontent.com/43583994/92989535-3d302c00-f4d5-11ea-97d4-b15050270f2f.png)

![Resource generator flag fh2 02](https://user-images.githubusercontent.com/43583994/92989537-3ef9ef80-f4d5-11ea-91b6-ef3c0d3036d9.png)

![Resource generator flag fh2 03](https://user-images.githubusercontent.com/43583994/92989538-402b1c80-f4d5-11ea-831c-d069aee163bc.png)

**Comment by a1exsh** [comment]
I'm having a look at this one.
