### ISSUE TITLE
Hero screen, automatically move the Magic Book into the first slot of the hero's inventory

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1644]
In the original game, when a hero of might who already has artifacts buys a Magic Book, the Magic Book ends up in a different slot than for heroes of magic (the first slot).
This is annoying because you have to look for the Magic Book in the hero's inventory to be able to view the spells it contains.

In fheroes2, it would be nice to remove this flaw.

I suggest that the Magic Book be automatically moved to the first slot of the hero's inventory when it is purchased.
If there is already an artifact in the first slort of the hero's inventory, this artifact is moved one slot to the right.
It may be necessary to move several artifacts one slot to the right to do this.
The positioning of artifacts in the hero inventory should be changed as little as possible.

This proposal must be taken into account with this proposal: https://github.com/ihhub/fheroes2/issues/1643.

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu !
What do you think of a reserved place in hero's inventory for magic book? We can even try to change chess icon for a special book icon in similar style.
![Chess](https://user-images.githubusercontent.com/55348946/92997486-53ada600-f51c-11ea-8716-e95a17e14e22.png)

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

> Hi, @LeHerosInconnu !
> What do you think of a reserved place in hero's inventory for magic book? We can even try to change chess icon for a special book icon in similar style.
> ![Chess](https://user-images.githubusercontent.com/55348946/92997486-53ada600-f51c-11ea-8716-e95a17e14e22.png)

It almost could have worked, provided the hero could still receive an artifact in the first slot when all other slots are already occupied.
Because there is no question of preventing a hero from having 14 artifacts without Magic Book.

And we end up with the same problem if the hero meets another hero and exchanges artifacts leaving the first slot occupied and other slots free. :)

**Comment by Branikolog** [comment]
Actually, I haven't seen people playing without magic book at all...
Making a first slot with special book icon can help people not to forget to buy book, when they see empty slot in the beginning with a book picture on it.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> Actually, I haven't seen people playing without magic book at all...
> Making a first slot with special book icon can help people not to forget to buy book, when they see empty slot in the beginning with a book picture on it.

This can happen quite frequently for me in the game.
For example, by sending a Barbarian hero to gather resources and the like in the ocean when there is no Sorceress hero available and it is now that the resources in the ocean need to be harvested not the following week or the one after.
This Barbarian hero can quickly find himself with the inventory full of 14 artifacts.

**Comment by Branikolog** [comment]
So, as fheroes2 provides player with the possibility to move any artifact or book in inventory, do we realy need automatic book moving then? Player can always move it, if he wants...

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> So, as fheroes2 provides player with the possibility to move any artifact or book in inventory, do we realy need automatic book moving then? Player can always move it, if he wants...

This is to have the same operation as in the original game: https://github.com/ihhub/fheroes2/issues/761. :)

**Comment by Branikolog** [comment]
What if we make it possible to move book to any slot till player puts it in a special reserved slot, where book will be stuck forever?

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> What if we make it possible to move book to any slot till player puts it in a special reserved slot, where book will be stuck forever?

What will it be used for?
Why complicate things?
- As in the original game, the player cannot move the Magic Book in the hero's inventory.
- The Magic Book is automatically placed in the first slot as soon as the hero purchases the Magic Book.
- If there is already an artifact in the first slot, this artifact is moved.

It 's done. :)

**Comment by Branikolog** [comment]
So your proposal is to always place book at the first slot and cancel the ability to move it at all. Am I right?

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> So your proposal is to always place book at the first slot and cancel the ability to move it at all. Am I right?

Yes, there is no need to move the Magic Book once it is in the first slot. :)

**Comment by ihhub** [comment]
This logic was implemented in #5172.
