### ISSUE TITLE
Adventure map, losing player information window, add the yellow title "Maybe Victory is at hand!" to this window

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1649]
I suggest to add the yellow title "Maybe Victory is at hand!" to this window.

In fheroes2:

![Resource generator flag fh2 02](https://user-images.githubusercontent.com/43583994/92989537-3ef9ef80-f4d5-11ea-91b6-ef3c0d3036d9.png)

**Comment by Branikolog** [comment]
As not native English speaker I cannot understand clearly the meaning of this phrase.) Too complex to my mind.))
On subject: Agreed, some yellow nice-looking title would be nice.)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> As not native English speaker I cannot understand clearly the meaning of this phrase.) Too complex to my mind.))
> On subject: Agreed, some yellow nice-looking title would be nice.)

"Victory is in reach!"
"Victory is near!"
"Victory is attainable!"
"Victory is close!"

**Comment by Branikolog** [comment]
Actually, this phrase is confusing me... Imagine, that we are playing the map, where the victory condition is not to defeat all players... Victory not always come closer with the defeating of any player...

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> Actually, this phrase is confusing me... Imagine, that we are playing the map, where the victory condition is not to defeat all players... Victory not always come closer with the defeating of any player...

This is why "may be" must be included in the title. :)

**Comment by Branikolog** [comment]
@LeHerosInconnu 
Humm. To my mind here should be some "notification-looking" phrase... Something like "Global Announcement"... "May be" sounds so indefinitely and ominous... 
Actually, I'm not that person, that should make consulting here, as my english is below average... :)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> @LeHerosInconnu
> Humm. To my mind here should be some "notification-looking" phrase... Something like "Global Announcement"... "May be" sounds so indefinitely and ominous...
> Actually, I'm not that person, that should make consulting here, as my english is below average... :)

Each window deserves its title.
The solution will come one day. :)

Maybe "Breaking News!" or just "Event!". ;)

**Comment by LeHerosInconnu** [comment]
Hello everyone,

So we have to make a choice for the yellow title of this window.
The candidates are:
- "Breaking News!"
- "Event!" This one can be confusing because it could be used for the "global event" or "map event" windows.
- "Major Event!" This is the one I would choose for now.

You can also make a "more appropriate" proposal if you have one. :)
