### ISSUE TITLE
Hero screen, title text, there must be no space between the parentheses and the text between the parentheses "(Level 1)"

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1673]
In the typographical rules, there are no spaces between the parentheses and the text within the parentheses.
The title should be written this way: "Lord Kilburn the Knight (Level 1)".

In fheroes2:

![Hero screen fh2 01](https://user-images.githubusercontent.com/43583994/93108423-0fa0d980-f6b3-11ea-9a76-be4475a3c4ab.png)

**Comment by Branikolog** [comment]
At first we need to look, on a "(Level 1)" without spaces... 
To mind, spaces would make easier to read the text...

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> At first we need to look, on a "(Level 1)" without spaces...
> To mind, spaces would make easier to read the text...

I have never found that a text between parentheses with respect for typographic rules is more difficult to read.
It looks so ugly the way it is now.

It can also be done this way:

"Lord Kilburn the Knight ~ Level 1"

**Comment by Branikolog** [comment]
> 
> I have never found that a text between parentheses with respect for typographic rules is more difficult to read.
> It looks so ugly the way it is now.
> 
> It can also be done this way:
> 
> "Lord Kilburn the Knight ~ Level 1"

Sounds like good topic for discussion. ;)
What if we add some preposition between "Knight" and "Level"?

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> Sounds like good topic for discussion. ;)
> What if we add some preposition between "Knight" and "Level"?

Something like that ?
"Lord Kilburn the Knight of Level 1"

Frankly I prefer with the tilde: :)
"Lord Kilburn the Knight ~ Level 1"

**Comment by Branikolog** [comment]
Let's leave it now as it is. Up to 1.0 release we'd have more suggestions on this thread. ;)
