### ISSUE TITLE
Hero screen, number of spell points, the vertical position of the slash "/" of the number of spell points is shifted

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1684]
In fheroes2, the vertical position of the slash "/" of the number of spell points is shifted compared to the original game.

In original game:

![Hero screen H2 10](https://user-images.githubusercontent.com/43583994/93109464-60650200-f6b4-11ea-8072-01075ade6bdf.png)

In fheroes2:

![Hero screen fh2 10](https://user-images.githubusercontent.com/43583994/93109527-78d51c80-f6b4-11ea-8ecf-6332a9444669.png)

Open the two images in different tabs in your browser, enlarge the images and switch between the two tabs alternately.
Heroes 2 first, fheroes2 second.

![Primary skills position H2 01](https://user-images.githubusercontent.com/43583994/93110720-fd746a80-f6b5-11ea-8f1c-1eb9194d644e.png) ![Primary skills position fh2 01](https://user-images.githubusercontent.com/43583994/93110841-2563ce00-f6b6-11ea-8ff6-ff8d8c432cd6.png)

**Comment by ihhub** [comment]
Closing this issue as it was fixed with font related changes.
