### ISSUE TITLE
Hero, number of creatures present in the hero's army when the hero is recruited

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1693]
In fheroes2, there are more creatures in the hero's army when the hero is recruited than in the original game.
Except for the Peasants. :)

In original game:

![Hero screen H2 10](https://user-images.githubusercontent.com/43583994/93120171-4252ce00-f6c3-11ea-9b75-ca9649f17e11.png)

In fheroes2:

![Hero screen fh2 10](https://user-images.githubusercontent.com/43583994/93120186-47178200-f6c3-11ea-8bae-1eb5f2b2f9d1.png)

In original game:

![Hero screen H2 11](https://user-images.githubusercontent.com/43583994/93120202-4c74cc80-f6c3-11ea-9b96-300d0bc0f42b.png)

In fheroes2:

![Hero screen fh2 11](https://user-images.githubusercontent.com/43583994/93120216-50085380-f6c3-11ea-878f-783602c1f95e.png)

In original game:

![Hero screen H2 12](https://user-images.githubusercontent.com/43583994/93120223-53034400-f6c3-11ea-972b-9a5cff1b198f.png)

In fheroes2:

![Hero screen fh2 12](https://user-images.githubusercontent.com/43583994/93120235-572f6180-f6c3-11ea-83d8-1e7c7901cfc7.png)

In original game:

![Hero screen H2 13](https://user-images.githubusercontent.com/43583994/93120244-5ac2e880-f6c3-11ea-8ed5-63887445ae9d.png)

In fheroes2:

![Hero screen fh2 13](https://user-images.githubusercontent.com/43583994/93120256-5dbdd900-f6c3-11ea-9167-df65f3c106fa.png)

In original game:

![Hero screen H2 14](https://user-images.githubusercontent.com/43583994/93120268-62828d00-f6c3-11ea-9059-5d43534108c4.png)

In fheroes2:

![Hero screen fh2 14](https://user-images.githubusercontent.com/43583994/93120277-66161400-f6c3-11ea-9580-4eacf26dd116.png)

In original game:

![Hero screen H2 15](https://user-images.githubusercontent.com/43583994/93120280-69a99b00-f6c3-11ea-9d17-547235d0b701.png)

In fheroes2:

![Hero screen fh2 15](https://user-images.githubusercontent.com/43583994/93120293-6dd5b880-f6c3-11ea-8340-3bdfc5153b39.png)

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu !
Can you write the approximate quantity of creatures?

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> Hi, @LeHerosInconnu !
> Can you write the approximate quantity of creatures?

I will look at this later. :)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> @Branikolog.
> 
> > Hi, @LeHerosInconnu !
> > Can you write the approximate quantity of creatures?
> 
> I will look at this later. :)

For the original game, this information is already known.
Look here: https://github.com/ihhub/fheroes2/issues/1265.

**Comment by bleakley** [comment]
I generated a lot of starting heroes in the original game and I think I've determined the formula.

You get 0.8 to 1.2 times the growth rate for tier one units, and 0.4 to 0.6 times the growth rate for tier two units. 10% of the time you get no tier two units. Peasants are an exception, you get an additional +30 modifier to the starting number of peasants.

I can open a PR to fix this.
