### ISSUE TITLE
Hero screen, info bar text at the bottom of the screen, no text displayed for the number of spell points

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1695]
In fheroes2, there is no text displayed in the info bar at the bottom of the screen when the player hovers the mouse cursor over the spell points bookmark.

In original game:

![Info bar no text number spell points H2 01](https://user-images.githubusercontent.com/43583994/93125091-ebe98d80-f6ca-11ea-9bb3-af8fa6fb1b70.png)

In fheroes2:

![Info bar no text number spell points fh2 01](https://user-images.githubusercontent.com/43583994/93125107-f1df6e80-f6ca-11ea-90e0-bc3ece655b79.png)

**Comment by ihhub** [comment]
This issue was fixed some time ago.
