### ISSUE TITLE
Combat, Resurrect spells, it should not be possible to cast the Resurrect spell when it cannot affect any creature

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1697]
In fheroes2, it is possible to cast the Resurrect spell when it cannot affect any creature.

In the example, the corpse of the attacking hero's Champion is positioned over the corpse of the defending hero's Peasant.
The Defending Hero's Ranger is positioned over the corpse of the attacking Hero's Champion.
In the original game, in this case, if the attacking hero tries to cast the Resurrect spell with the intention of resurrecting his Champion, a message window is displayed telling him that the spell cannot affect any creature.
The hero cannot cast the Resurrect spell.
This is normal, the Ranger of the defending hero prevents this from being possible.

In fheroes2, the message window is not displayed.
The hero can cast the Resurrect spell.
But the hero cannot use it, which is also normal.
The message window must be displayed and the hero must not be able to cast the Resurrect spell.

In original game:

![Resurrect spell H2 01](https://user-images.githubusercontent.com/43583994/93194829-cef39f80-f748-11ea-8d5a-324ba3db3b45.png)

In fheroes2:

![Resurrect spell fh2 01](https://user-images.githubusercontent.com/43583994/93194862-d87d0780-f748-11ea-81e2-978f67a7470b.png)

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu.
How do you think, can we make two separate messages for the both cases?
If there's no one to resurrect.
And if we cannot apply the spell because of some reasons.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> Hi, @LeHerosInconnu.
> How do you think, can we make two separate messages for the both cases?
> If there's no one to resurrect.
> And if we cannot apply the spell because of some reasons.

Yes, that would be even better. :)

The standard message, when there is no troop to resurrect.

And a more informative message when it is possible to cast the spell because there is at least one troop to resurrect, but at least an allied or enemy troop is preventing it.

"It is not possible to resurrect one of your troops because an allied troop is preventing it.
Move your troop before you can cast the spell."

"It is not possible to resurrect one of your troops because an enemy troop is preventing it.
Eliminate the enemy troop before you can cast the spell."

"It is not possible to resurrect one of your troops because several allied troops are preventing it.
Move your troops before you can cast the spell."

"It is not possible to resurrect one of your troops because several enemy troops are preventing it.
Eliminate the enemy troops before you can cast the spell."

"It is not possible to resurrect one of your troops because an allied troop and an enemy troop are preventing it.
Move your troop and eliminate the enemy troop before you can cast the spell."

Also, all these message windows which inform the player of the non possibility of casting the different spells, are displayed on the battlefield, after the Magic Book is closed.
I also have a proposal, which I will add later, that these message windows are displayed directly in the Magic Book when the player left clicks on the spell and also this will be indicated in the information window displayed when the player right clicks on the spell.

The information bar at the bottom of the screen also displays a message to indicate whether the spell can be cast when the player hovers the mouse cursor over the graphics of different spells.

This will prevent the player from having to reopen the Magic Book if the spell cannot be cast.

**Comment by Branikolog** [comment]
> And a more informative message when it is not possible to cast the spell because there is at least one troop to resurrect, but at least an allied or enemy troop is preventing it.

I don't think we should make separate messages in a case if allied or enemy troops are preventing it... Just a message that there's something preventing resurrection of troops.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> > And a more informative message when it is not possible to cast the spell because there is at least one troop to resurrect, but at least an allied or enemy troop is preventing it.
> 
> I don't think we should make separate messages in a case if allied or enemy troops are preventing it... Just a message that there's something preventing resurrection of troops.

You asked, I put a message for almost all cases. :)

Here is a "lazy" sentence: :D
“It is not possible to resurrect one of your troops because another troop is preventing it."

**Comment by Branikolog** [comment]
> “It is not possible to resurrect one of your troops because another troop is preventing it."

I think somwthing like that... 

> You asked, I put a message for almost all cases. :)

Sorry, that made you doing more work. I just think it would be enough to have 2 messages for a cases:
There's no one to resurrect.
And there's some targets, but you cannot at the moment.)

Don't want to complicate this situation. :)
