### ISSUE TITLE
Combat screen, log list, the information displayed in the log list should be written in a more understandable and correct way

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1701]
The information displayed in the log list should be written in a more understandable and correct way, and with a period at the end of each sentence.

A complet and enhanced remake of Heroes of Might and Magic 2 does not deserve lazy programming.
Does fheroes2 have to?

In fheroes2:

![Log list understandable and correct 01](https://user-images.githubusercontent.com/43583994/93224568-87cdd480-f771-11ea-9ca8-2a915e22d142.png)

- "1 Champion rise(s) from the dead!"

The sentence must be adapted directly to the number of creatures:
"1 Champion rises from the dead!"
"10 Champions rise from the dead!"

- "Gargoyle skipping turn"

Correct and understandable sentences should be used:
"The Gargoyle skips her turn."
"Gargoyles skip their turn."

- "Green cast spell: Fireball"
"Wrathmont casts Fireball on the Veteran Pikeman."

Is the first sentence really necessary?
"Wrathmont casts Fireball on the Veteran Pikeman."

- "The Fireball does 30 damage."
"one creature perishes."

These sentences should be combined in one sentence on the same line, and the name of the creature clearly indicated.
And the word "one" should be replaced by the number "1":
"The Fireball does 30 damage, 1 Ranger perishes."

In fheroes2:

![Log list understandable and correct 02](https://user-images.githubusercontent.com/43583994/93224592-8e5c4c00-f771-11ea-8b4e-142845801aa7.png)

- "Moved Champion: 27, 9"

Correct and understandable sentences should be used, and with more understandable hexagon positions (https://github.com/ihhub/fheroes2/issues/1372):
"The Champion moves from C6-7 to A10-11."
"Champions move from C6-7 to A10-11."

- "Champion do 13 damage. one Peasant perishes."

These sentences should be combined in one sentence on the same line, and the word "one" should be replaced by the number "1":
"The Champion does 13 damage, 1 Peasant perishes."
"Champions do 13 damage, 1 Peasant perishes."

- "Champion do 9 damage."
"Champion do 5 damage."

These sentences describe an attack and a retaliation from the attacked troop.
This should be specified:
"The Champion does 9 damage."
"The Champion retaliates and does 5 damage."
"Champions do 9 damage."
"Champions retaliate and do 5 damage."

**Comment by ihhub** [comment]
Hi @LeHerosInconnu just off-topic: check Credits on latest build :)

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu just off-topic: check Credits on latest build :)

Great!
So we are famous. :)
There is a bug in this window... no, just kidding. :)
Poor Goblin. :)

**Comment by zenseii** [comment]
Did we fix all of these mentioned issues, @LeHerosInconnu ?

**Comment by LeHerosInconnu** [comment]
Hello @zenseii,

> Did we fix all of these mentioned issues, @LeHerosInconnu ?

No, not everything is fixed.
For example, "Moved Champion..." is still there.
There are also problems with upper and lower case for the names of the creatures.
Retaliation is not indicated.
I didn't test everything.

In fheroes2:

https://user-images.githubusercontent.com/43583994/200586299-285e1080-7271-4e33-83cc-56105e5310d6.mp4
