### ISSUE TITLE
Adventure map, single and multiplayer mode, wrong text displayed in the information window when the player loses the game

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1705]
In fheroes2, the text displayed in the information window when the player loses the game is not the same as in the original game.

In original game:

![Multiplayer mode player loses game H2 01](https://user-images.githubusercontent.com/43583994/93313330-a16e2b00-f808-11ea-8661-4ecc5099bac5.png)

In fheroes2:

![Multiplayer mode player loses game fh2 01](https://user-images.githubusercontent.com/43583994/93313299-95826900-f808-11ea-98cf-04fb71c3d805.png)

**Edit 2020/10/24.**

This is also valid for the single player mode.

Here is the test scenario file:
[Player loses game 01.zip](https://github.com/ihhub/fheroes2/files/5433356/Player.loses.game.01.zip)

**Comment by Lumary2** [comment]
did it :)
