### ISSUE TITLE
Meeting screen, wrong yellow color of frames

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1711]
In fheroes2, the yellow color of frames used for primary skills, secondary skills, creatures and artifacts is not the same as in the original game.

In original game:

RGB (228, 200, 20)
C++ 0x14C8E4

![Meeting screen H2 01](https://user-images.githubusercontent.com/43583994/93360938-8a4d2e80-f844-11ea-9eff-2e4ab3183b9a.png)

In fheroes2:

RGB (232,172,80)
C++ 0x50ACE8

![Meeting screen fh2 01](https://user-images.githubusercontent.com/43583994/93360963-90dba600-f844-11ea-8b0b-9be363d28bfb.png)

Open the two images in different tabs in your browser, enlarge the images and switch between the two tabs alternately.
Heroes 2 first, fheroes2 second.

![Meeting screen H2 secondary skills coupé 01](https://user-images.githubusercontent.com/43583994/93362120-e82e4600-f845-11ea-9fb6-935cd0420ab3.png) ![Meeting screen fh2 secondary skills coupé 01](https://user-images.githubusercontent.com/43583994/93362143-ec5a6380-f845-11ea-9111-f1774c311a8e.png)

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

It seems that you forgot to change the yellow color of the primary skills frames. :)

In fheroes2:

![Primary skill frame color fh2 01](https://user-images.githubusercontent.com/43583994/98956581-7f3f1380-2500-11eb-8758-5e4fbf7e4b77.png)

**Comment by ihhub** [comment]
I didn't touch primary skills so yeah, my bad for missing it. Also could you please answer [here](https://github.com/ihhub/fheroes2/pull/2208)?

**Comment by ihhub** [comment]
@LeHerosInconnu could you please just update the original message in this issue, I will fix it later.

**Comment by ihhub** [comment]
Actually forget about change the first message. I'll fix it right away. Don't waste you time.
