### ISSUE TITLE
Meeting screen, wrong color of creature selection frame

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1718]
In fheroes2, the color of creature selection frame is not the same as in the original game.
White in the original game, red in fheroes2.

In original game:

![Meeting screen H2 02](https://user-images.githubusercontent.com/43583994/93363857-1d3b9800-f848-11ea-8df1-cf82a491776c.png)

In fheroes2:

![Meeting screen fh2 02](https://user-images.githubusercontent.com/43583994/93363870-22004c00-f848-11ea-9c5e-47fc05f78119.png)

Open the two images in different tabs in your browser, enlarge the images and switch between the two tabs alternately.
Heroes 2 first, fheroes2 second.

![Meeting screen H2 cadre creatures 02](https://user-images.githubusercontent.com/43583994/93363998-4eb46380-f848-11ea-91be-34bbae8cebd3.png) ![Meeting screen fh2 cadre creatures 02](https://user-images.githubusercontent.com/43583994/93364011-5247ea80-f848-11ea-8a29-451238d2c80b.png)

**Comment by ihhub** [comment]
We aren't going to use white color but cycling color instead for creatures and monsters making the selection more intuitively for players.
