### ISSUE TITLE
Meeting screen, wrong color of artifact selection frame

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1719]
In fheroes2, the color of artifact selection frame is not the same as in the original game.
White in the original game, red in fheroes2.

In original game:

![Meeting screen H2 03](https://user-images.githubusercontent.com/43583994/93364224-96d38600-f848-11ea-8f1d-81e1958ce6c2.png)

In fheroes2:

![Meeting screen fh2 03](https://user-images.githubusercontent.com/43583994/93364249-9b983a00-f848-11ea-9d8d-10d29c437cf2.png)

Open the two images in different tabs in your browser, enlarge the images and switch between the two tabs alternately.
Heroes 2 first, fheroes2 second.

![Meeting screen H2 cadre artifacts 03](https://user-images.githubusercontent.com/43583994/93364265-a226b180-f848-11ea-87da-b72f63c3c941.png) ![Meeting screen fh2 cadre artifacts 03](https://user-images.githubusercontent.com/43583994/93364283-a783fc00-f848-11ea-85b3-2bb22a830754.png)

**Comment by Branikolog** [comment]
Hello, @LeHerosInconnu !
I can't say that both of this frame implementations are eye-freindly. Sometimes it's rather hard to find a selected box in this window.
How do you think, could we change the color or the the type of this frame, to make it more visible? I hope, that you remember, that one of out goals is to make UI more user-friendly.
One of our main developers showed me a concept of glowing frame, and it looked not bad....

**Comment by LeHerosInconnu** [comment]
Hi @Branikolog,

> Hello, @LeHerosInconnu !
> I can't say that both of this frame implementations are eye-freindly. Sometimes it's rather hard to find a selected box in this window.
> How do you think, could we change the color or the the type of this frame, to make it more visible? I hope, that you remember, that one of out goals is to make UI more user-friendly.
> One of our main developers showed me a concept of glowing frame, and it looked not bad....

I have nothing against.
It should be seen in use. :)

**Comment by ihhub** [comment]
I can implement glowing frame :) It looks pretty good.

**Comment by LeHerosInconnu** [comment]
@ihhub.

> I can implement glowing frame :) It looks pretty good.

Nice work on the selection frame. :)
Can I suggest some adjustments? :)

Would it be possible to make the color cycle go back and forth rather than jumping from one color to another at the end of the cycle.
A "bounce" rather than a "jump".
Cycle from red to yellow, then continue cycle from yellow to red instead of cycle from red to yellow and then jump directly from yellow to red.
Maybe a little slower color cycle speed too (maybe not needed with color cycle bounce).
I also find the color of red a bit too dark.

Would it be possible to try with these colors:
Red:
RGB (255, 0, 0)
C++ 0x0000FF

Yellow (original game color):
RGB (228, 200, 20)
C++ 0x14C8E4

Yellow (fheroes2 actual color):
RGB (232,172,80)
C++ 0x50ACE8

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , all cycling colors are predetermined and we use color palette which cannot be extended. This is done in order to keep the game visually same as the original game. In other words, color representation is limited by the original game.

@idshibanov am I correct on this?

The color cycling is a global function and we cannot change the speed of it. However, we can do all these change but they are not really worth to spend hours of time to do this :)

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , all cycling colors are predetermined and we use color palette which cannot be extended. This is done in order to keep the game visually same as the original game. In other words, color representation is limited by the original game.
> 
> @idshibanov am I correct on this?
> 
> The color cycling is a global function and we cannot change the speed of it. However, we can do all these change but they are not really worth to spend hours of time to do this :)

Okay I see.
You use the color of the phoenix then.
Too bad it takes too long to make the changes.
Thanks for the explanation.

**Comment by ihhub** [comment]
No problem at all. Yes, it's a color from Phoenix :) I think this solution is better than just a single color. We could come back to this improvement in the future but definitely it's not a priority.
