### ISSUE TITLE
Meeting screen, morale and luck sprites, sprites are not correctly centered horizontally with respect to each other

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1721]
In fheroes2, morale and luck sprites are not correctly centered horizontally with respect to each other.
The luck sprite should be shifted 1 pixel to the left.
The corrected position of the luck sprite will still be good even when the neutral morale sprite will be 1 pixel larger in width with the border of black pixels surrounding the sprite (https://github.com/ihhub/fheroes2/issues/1720).

In fheroes2:

![Meeting screen fh2 01](https://user-images.githubusercontent.com/43583994/93360963-90dba600-f844-11ea-8b0b-9be363d28bfb.png)

Enlarge the image.

![Meeting screen fh2 morale luck sprites coupé 01](https://user-images.githubusercontent.com/43583994/93364677-20835380-f849-11ea-9c75-cf1e31e5af26.png)

**Comment by roman-yagodin** [comment]
It probably will need more than just moving luck indicator 1px to the left.

I've experimented with this and after moving luck indicator 1px to the left the neutral morale icon is too much out of center line visually:

![neutral_and_good_morale_1](https://user-images.githubusercontent.com/5691178/229530268-656e896a-1d24-4204-b210-59b39eebc91a.png)

Compare with 1.0.2:

![neutral_and_good_morale_2](https://user-images.githubusercontent.com/5691178/229530261-0c9d357c-d435-471b-a176-7118171831f1.png)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , the icon was modified so the shift came out of the box. Therefore, I am closing this issue.
