### ISSUE TITLE
Adventure map, empty pyramid info window, wrong horizontal position of bad luck sprites in window

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1726]
In fheroes2, the horizontal position of bad luck sprites is not the same as in the original game.

In original game:

![Pyramid luck empty sprite position H2 01](https://user-images.githubusercontent.com/43583994/93371284-62fd5e00-f852-11ea-9b13-441be52862c5.png)

In fheroes2:

![Pyramid luck empty sprite position fh2 01](https://user-images.githubusercontent.com/43583994/93371296-67c21200-f852-11ea-8732-cbaf7bd76a0b.png)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu I've updated the code to address it. If the do pixel to pixel then we have to change a big chunk of code. What I did is to put one sprite width offset between them instead of 1/3 like it was before.

**Comment by LeHerosInconnu** [comment]
@ihhub.

> Hi @LeHerosInconnu I've updated the code to address it. If the do pixel to pixel then we have to change a big chunk of code. What I did is to put one sprite width offset between them instead of 1/3 like it was before.

Okay, thanks for the clarification.
We'll see how it works. :)
