### ISSUE TITLE
Castle screen, creature recruit window, the text "MIN" is not centered horizontally inside the "MIN" button

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1736]
In fheroes2, the text "MIN" is not centered horizontally inside the "MIN" button.

In fheroes2:

![Recruit creature fh2 01](https://user-images.githubusercontent.com/43583994/93664461-83eeca80-fa6f-11ea-9d29-ec640dc9c22c.png)

![Recruit creature fh2 coupé 01](https://user-images.githubusercontent.com/43583994/93664223-7d5f5380-fa6d-11ea-9dda-1492c1d574ea.png)

**Comment by ihhub** [comment]
This issue was fixed some time ago.
