### ISSUE TITLE
Castle screen, creature recruit window, creature information window with left click

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1743]
In the original game, it is possible to display an information window with an "EXIT" button by left clicking on the creature's sprite.
In fheroes2 this is not possible.

In original game:

![Recruit creature info creature left H2 01](https://user-images.githubusercontent.com/43583994/93664839-2019d100-fa72-11ea-8eb4-e5cd0f269075.png)

**Comment by Branikolog** [comment]
This happens due to the <change> option we have over sprite.
When we implement a new way to change upgraded and non-upgraded creature we'd add this window. (#1744)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> This happens due to the option we have over sprite.
> When we implement a new way to change upgraded and non-upgraded creature we'd add this window. (#1744)

Okay, I see.
