### ISSUE TITLE
Castle construction screen, change the sentence in the info bar at the bottom of the screen when it is not possible to build the shipyard

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1746]
I suggest replacing this sentence with this one:

"Cannot build Shipyard because castle does not have access to ocean."

In fheroes2:

![Shipyard text ocean fh2 01](https://user-images.githubusercontent.com/43583994/93666313-80fad680-fa7d-11ea-94a0-27c0b4bd016b.png)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , what's wrong with the current sentence present in the game: `Cannot build Shipyard because castle is too far from water.`?

FIY, @zenseii and @Branikolog .

**Comment by Branikolog** [comment]
I'm OK with both sentences. The only thing bothers me is the consistency of wording: all places mentioning water (like summon boat spell etc) should refer to the same word - either water or ocean.

**Comment by ihhub** [comment]
> I'm OK with both sentences. The only thing bothers me is the consistency of wording: all places mentioning water (like summon boat spell etc) should refer to the same word - either water or ocean.

Hi @Branikolog , this is the only sentence in relation to water terrain which uses the word **water**.

I will simply change the sentence to be consistent.

**Comment by LeHerosInconnu** [comment]
Hello everyone,

> My guess is that @LeHerosInconnu wants it to specifically refer to "Ocean" because that is what the game calls any body of water when you right click them.

Yes, exactly. :)

For me, this part of the sentence...:

"...does not have access to ocean."

...is clearer and more informative than that one:

"...is too far away from an ocean."

Also, I think the word "an" can be removed from the sentence:

"Cannot build Shipyard because castle does not have access to ocean."

Also, if "the" is used for "castle", it should also be used for "shipyard".
I don't think it's necessary to use the two "the"'s in this sentence.

**Comment by LeHerosInconnu** [comment]
Hello @zenseii,

> Hi, @LeHerosInconnu. If space permits it then to me the sentence reads much better with two "the"s and the "an". While "we don't have access to water" works, "we don't have access to ocean" sounds very weird. Dropping the indefinite noun works for things that don't usually take a quantity or number like food, water etc. E.G. We don't talk about "one water" but we can talk about "one ocean". Likewise "one food" is weird.
> 
> On a slightly unreleated note, we would not be able to use "the" for ocean and write "we don't have access to the ocean" because then we're talking about the main body of water of the planet Enroth, but I feel like we've discussed this to death at this point xD

In my mind, the use of "ocean" is more related to the "ocean" terrain than to a body of water, which could be indicated by "an ocean".

For example, by replacing the terrain "Ocean" with the terrain "Dirt" (supposedly the type of terrain, not a "surface"):

"...does not have access to dirt."

It seems more appropriate than:

"...does not have access to a dirt."

Anyway, as I'm not a native English speaker, if you think one is more appropriate than the other, do what you think is best. :)

> So yes, we can use "access" instead.

Yes, "access" seems clearer to me.
Here's why:
In the example, the two cities are both not too far away from ocean, but only the one on the left has access to ocean:

In fheroes2:

![Shipyard with ocean access 01](https://github.com/ihhub/fheroes2/assets/43583994/8c8d89ab-9743-4dc5-af85-08a805e62585)
