### ISSUE TITLE
Castle construction screen, Recruit Hero window, the portrait frame is not centered horizontally

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1748]
In fheroes2, the portrait frame is not centered horizontally.

In fheroes2:

![Recruit hero window fh2 01](https://user-images.githubusercontent.com/43583994/93666330-a687e000-fa7d-11ea-8edb-89c9177c1399.png)

**Comment by ihhub** [comment]
Fixed in #1805 .
