### ISSUE TITLE
Remove speed 0 for battle and world map

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#175]
We noticed that speed ranges from **0** to **10**. Logically, speed 0 _makes no sense_ in the game. We should set minimum value to all speeds to **1**. Please be aware that there is a code which includes `% 11` which we need to change too.

The start point is `src/fheroes2/system/settings.cpp` file.

**Comment by dariodsa** [comment]
I will look into this.

**Comment by ihhub** [comment]
@dariodsa sure!
