### ISSUE TITLE
Castle construction screen, Recruit Hero window, "OKAY" and "CANCEL" buttons are not at the same horizontal distance from the edge of the window

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1753]
In fheroes2, the "OKAY" and "CANCEL" buttons are not at the same horizontal distance from the edge of the window.

In fheroes2:

![Recruit hero window fh2 01](https://user-images.githubusercontent.com/43583994/93666330-a687e000-fa7d-11ea-8edb-89c9177c1399.png)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , please check the position of buttons because we fixed this dialog type rendering some time ago. If the issue is fixed please close it.

**Comment by LeHerosInconnu** [comment]
@ihhub.

> Hi @LeHerosInconnu , could you please re-check the position of buttons because we fixed this dialog type rendering some time ago? If the issue is fixed please close it.

It's done, the buttons are at the same distance from the edge of the window.
