### ISSUE TITLE
Castle construction screen, remove the Shrine building in the Necromancer's castle for the scenarios from "The Succession Wars"

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1759]
In the original game, with the "The Price of Loyalty" add-on installed, when the player is playing a scenario from "The Succession Wars", the Shrine building is not available in the Necromancer's castle.

In fheroes2, the Shrine building should not be available in the Necromancer's castle for the scenarios from "The Succession Wars".

In original game:

![Building sign position H2 01](https://user-images.githubusercontent.com/43583994/93666264-177ac800-fa7d-11ea-8962-05cebe0a0628.png)

In fheroes2:

![Building sign position fh2 01](https://user-images.githubusercontent.com/43583994/93666266-1e093f80-fa7d-11ea-8037-1336d691db65.png)

**Comment by idshibanov** [comment]
I disagree - this shouldn't be an option. Building is not there by default and only present if you have data files from Price of Loyalty. Works as intended.

**Comment by LeHerosInconnu** [comment]
@idshibanov.

> I disagree - this shouldn't be an option. Building is not there by default and only present if you have data files from Price of Loyalty. Works as intended.

This means that if the "The Price of Loyalty" data files are present, it is not possible to play a "The Succession Wars" scenario the way it is played in the original game.

So the user must remove the "The Price of Loyalty" data files to be able to play the scenario as in "The Succession Wars".

Not very user friendly.

**Comment by idshibanov** [comment]
Then this ticket has to be renamed into "Add in-game option to disable Price of Loyalty features" that would also disable new artifacts, hero and music altogether. We shouldn't pollute our settings windows.

I doubt this option is really needed/would be popular. For example in Heroes 3 if I have Shadow of Death add-on I would never go back to vanilla Restoration of Eurathia, it's such a step backwards. I also don't think it's possible right now to get a copy of original release (not Gold) without the add-on.

**Comment by LeHerosInconnu** [comment]
@idshibanov.

> Then this ticket has to be renamed into "Add in-game option to disable Price of Loyalty features" that would also disable new artifacts, hero and music altogether. We shouldn't pollute our settings windows.
> 
> I doubt this option is really needed/would be popular. For example in Heroes 3 if I have Shadow of Death add-on I would never go back to vanilla Restoration of Erathia, it's such a step backwards. I also don't think it's possible right now to get a copy of original release (not Gold) without the add-on.

In Heroes of Might and Magic 2 Gold, or any version with the "The Price of Loyalty" add-on installed, when the player is playing a "The Succession Wars" scenario, there are no features of “The Price of Loyalty”, it's not going a step backwards, it's just the way the game works.

I will change the title of the issue later.

**Comment by LeHerosInconnu** [comment]
> I will change the title of the issue later.

I modified the title and the text of the issue to be more in line with how the original game works.

**Comment by ihhub** [comment]
This is a bug: original maps (without the add-on) should not have such building.
