### ISSUE TITLE
Shadows on world map for SDL 2 aren't displayed properly

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#176]
While application is built with **SDL 2** (on MacOS) shadows aren't displayed properly on World Map. Most likely we don't use alpha channel for drawings.

<img width="639" alt="Screenshot 2019-10-18 at 3 31 51 PM" src="https://user-images.githubusercontent.com/19829520/67074846-85a77280-f1bc-11e9-87f5-b418b63f2181.png">

**Comment by ihhub** [comment]
Hi @andrey-starodubtsev , I think you might have an idea about this :)

**Comment by andrey-starodubtsev** [comment]
Yes, please assigned it to me.

All alpha-channel related issues with SDL2 have common ground - we use 16-bit color depth by default, SDL2 has no alpha mask for this graphics mode (but SDL1 has!) and using alpha channel for surface relies on alpha-mask of used color depth which is incorrect behavior.
