### ISSUE TITLE
Magic book, spell cost position

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1768]
In the original game, when possible, for example for all spells with a small name, the cost of the spell is displayed alone on the second line of text of the spell.

In the example, Fireball, Fireblast, Teleport, Cure, Mass Cure, Resurrect, Haste, Mass Haste, Slow.

In fheroes2 this is not the case and because of it the spell texts are too close making everything a bit "messy".

In the example, Fireball and Hypnotise, Blood Lust and Earthquake.

In original game:

![Spells order H2 01](https://user-images.githubusercontent.com/43583994/92383959-8e27d500-f10f-11ea-96e5-2edc0e424170.png)

In fheroes2:

![Spells order fh2 01](https://user-images.githubusercontent.com/43583994/92384001-9a139700-f10f-11ea-9815-20fecf012823.png)

**Comment by Branikolog** [comment]
It would be nice, if we can make a separate [mana cost quantity] for all spells in the lowest string.
Unfortunately, there're some spells with too long names (Summon elementals for example), so [mana cost quantity] would be at 4th string, which looks quite bad...
I've already made a proposal to shorten the name of summon spells here #556. This can be made for spell book list only, so player won't confuse it with "Set Elemental" spell in a mage guild. 
In that case we would see all spells' [mana cost quantity] in the lowest string, which would make spell book look better.
@LeHerosInconnu, can you remind me, if we have some other long named spells, except summoning?

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> It would be nice, if we can make a separate [mana cost quantity] for all spells in the lowest string.
> Unfortunately, there're some spells with too long names (Summon elementals for example), so [mana cost quantity] would be at 4th string, which looks quite bad...
> I've already made a proposal to shorten the name of summon spells here #556. This can be made for spell book list only, so player won't confuse it with "Set Elemental" spell in a mage guild.
> In that case we would see all spells' [mana cost quantity] in the lowest string, which would make spell book look better.
> @LeHerosInconnu, can you remind me, if we have some other long named spells, except summoning?

The "Summon Elemental" spells are the most problematic.
The name chosen for the spells must also be the same in the mage guild and in the magic book.

I had thought about "Call Water Elemental", etc.
But I find the word "Summon" more appropriate and evocative.

So I thought of "Summon Water Unit", etc.
But I'm not decided.

In the simplest case, I thought of "Summon Water", etc.
I prefer to keep the word "Summon" rather than "Elemental".

**Comment by Branikolog** [comment]
In HoMM3, for example, this spell is called "Water Elemental". So, players are rather used to this name... Better than "Unit", or "Call"....

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> In HoMM3, for example, this spell is called "Water Elemental". So, players are rather used to this name... Better than "Unit", or "Call"....

Heroes 3 is Heroes 3.
For a Heroes 2 remake, I would prefer "Summon Water", etc. if the name needs to be really shorter.
