### ISSUE TITLE
Change missing file message

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#177]
We have this message when `DATA` directory is not present:

<img width="636" alt="Screenshot 2019-10-18 at 3 42 01 PM" src="https://user-images.githubusercontent.com/19829520/67075524-e8e5d480-f1bd-11e9-9d1f-dac5eb7cade4.png">

We should change it to inform user to download demo version of the game via script.

**Comment by pathway27** [comment]
Would you suggest changing the `agg_error.png` binary picture structure in `/src/fheroes2/image/images_pack.h` ?

**Comment by ihhub** [comment]
Wow. I didn't know that we have prewritten png file in source. Ideally, we have to change this image into image without any text and then render text on it.

**Comment by pathway27** [comment]
Yeah, it's a little weird.

So, even the 'Error' and 'OKAY' text should be removed ?
Would it make more sense to make this into a normal `.png` then ? Under `/images` or `/files/images` ?

Also any idea on how I can render text [here](https://github.com/ihhub/fheroes2/blob/master/src/fheroes2/agg/agg.cpp#L1863) before loading  our font files ?

**Comment by ihhub** [comment]
The idea is simple: create the same window with new info during application execution and dump it into local file. Then copy content of the file into source.

**Comment by ihhub** [comment]
We need to save png file as **_ptr_080721d0** is png file data.
