### ISSUE TITLE
Creature information window with left click, wrong horizontal and vertical position of the "DISMISS" button

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1773]
In fheroes2, the horizontal and vertical position of the "DISMISS" button is not the same as in the original game.

In original game:

![Creature info left H2 01](https://user-images.githubusercontent.com/43583994/93760876-20020880-fc0d-11ea-9fad-1e184d9b1312.png)

In fheroes2:

![Creature info left fh2 01](https://user-images.githubusercontent.com/43583994/93760899-27c1ad00-fc0d-11ea-8842-7beb1a8b831e.png)

**Comment by Branikolog** [comment]
Actually, it's the problem with "EXIT" button...
The issue is already exists.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> Actually, it's the problem with "EXIT" button...
> The issue is already exists.

No, the issue with the "EXIT" button is another problem.
It seems so visible to me that I didn't even add any image parts to compare. :)

Open the two images in different tabs in your browser, enlarge the images and switch between the two tabs alternately.
Heroes 2 first, fheroes2 second.

![Creature info left H2 coupé 01](https://user-images.githubusercontent.com/43583994/93867393-471e1000-fcc9-11ea-9ead-569aea85c3aa.png) ![Creature info left fh2 coupé 01](https://user-images.githubusercontent.com/43583994/93867409-4f764b00-fcc9-11ea-9e12-636cef607573.png)

**Comment by Branikolog** [comment]
Oh, you're right, @LeHerosInconnu! My failure.
So we also need to mention this thread in that topic, so developers wouldn't make "EXIT" button the same level as current "DISMISS", but higher.
