### ISSUE TITLE
Creature information window with left click, there should be no spaces between the damage numbers and the dash

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1774]
In the original game, there is no space before and after the dash between the damage numbers:
"Damage: 1-3"

Here again, in that case in fheroes2, it is a typographical rule which is not respected.

In original game:

![Creature info left H2 01](https://user-images.githubusercontent.com/43583994/93760876-20020880-fc0d-11ea-9fad-1e184d9b1312.png)

In fheroes2:

![Creature info left fh2 01](https://user-images.githubusercontent.com/43583994/93760899-27c1ad00-fc0d-11ea-8842-7beb1a8b831e.png)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , thanks a lot for work!

Let's group these tiny corrections under the same issue. For example, extra spaces in place A, B, C and D. This will ease the work and the development team can easily fix all places in a batch.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , thanks a lot for work!
> 
> Let's group these tiny corrections under the same issue. For example, extra spaces in place A, B, C and D. This will ease the work and the development team can easily fix all places in a batch.

Okay, I will bundle similar issues into one thread in the future.
