### ISSUE TITLE
Font, vertical position of punctuation marks in the font

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1775]
In fheroes2, the vertical position of the punctuation marks in the font is not the same as in the original game.
In the examples, with colon ":", comma "," and dash "-", and also for the "+" sign.

In original game:

![Creature info left H2 01](https://user-images.githubusercontent.com/43583994/93760876-20020880-fc0d-11ea-9fad-1e184d9b1312.png)

![Police punctuation H2 02](https://user-images.githubusercontent.com/43583994/93763776-4f674400-fc12-11ea-8068-11553978947c.png)

![Police punctuation H2 03](https://user-images.githubusercontent.com/43583994/93765995-0fa25b80-fc16-11ea-86b7-7a163b2a3863.png)

In fheroes2:

![Creature info left fh2 01](https://user-images.githubusercontent.com/43583994/93760899-27c1ad00-fc0d-11ea-8842-7beb1a8b831e.png)

![Police punctuation fh2 02](https://user-images.githubusercontent.com/43583994/93763789-568e5200-fc12-11ea-95c2-41d9ef0dd73b.png)

![Police punctuation fh2 03](https://user-images.githubusercontent.com/43583994/93766031-18932d00-fc16-11ea-8554-f5073722fcbd.png)

Open the two images in different tabs in your browser, enlarge the images and switch between the two tabs alternately.
Heroes 2 first, fheroes2 second.

![Police punctuation H2 coupé 02](https://user-images.githubusercontent.com/43583994/93763649-1a5af180-fc12-11ea-8ea9-8cef0f094be6.png) ![Police punctuation fh2 coupé 02](https://user-images.githubusercontent.com/43583994/93763673-2181ff80-fc12-11ea-9c76-946d77c82f86.png)

![Police punctuation H2 coupé 01](https://user-images.githubusercontent.com/43583994/93763716-38285680-fc12-11ea-9811-76c6a33a2f39.png) ![Police punctuation fh2 coupé 01](https://user-images.githubusercontent.com/43583994/93763731-3eb6ce00-fc12-11ea-8a3f-7b7c946096a4.png)

![Police punctuation H2 coupé 03](https://user-images.githubusercontent.com/43583994/93766066-247eef00-fc16-11ea-852d-f18120d2e2ba.png) ![Police punctuation fh2 coupé 03](https://user-images.githubusercontent.com/43583994/93766081-2ba5fd00-fc16-11ea-9c3f-8ff9e94c10e8.png)

**Comment by Branikolog** [comment]
@LeHerosInconnu, wow, thanks for your help. You're doing a great work cutting this small pieces of UI!
That "+" and "~" signs both seem for me placed in a wrong places.) Is it possibe to place them somewhere in the middle, comparing your two screenshots?

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> @LeHerosInconnu, wow, thanks for your help. You're doing a great work cutting this small pieces of UI!
> That "+" and "~" signs both seem for me placed in a wrong places.) Is it possibe to place them somewhere in the middle, comparing your two screenshots?

Yes, I also find that the "+" and "~" signs should be lowered a bit compared to their position in the original game.
One way to do this would be to edit the font with a font editor.
The font files are no longer accessible in the new fheroes2 project.

**Comment by Branikolog** [comment]
Well, i think a new "Enhancement" thread could be created, regarding "+" and "~" symbols then.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> Well, i think a new "Enhancement" thread could be created, regarding "+" and "~" symbols then.

It's done here: https://github.com/ihhub/fheroes2/issues/1782.

**Comment by Branikolog** [comment]
Great job, @LeHerosInconnu!
Thanks for your vast contribution to the project.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> Great job, @LeHerosInconnu!
> Thanks for your vast contribution to the project.

Thank you for your kind words.
I will continue to add issues, be warned. :)
