### ISSUE TITLE
2hex unit's path failure over battlefield

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1778]
Currently, 2hex unit cannot move to the spot, it is supposed to reach:
![Unicorn movement0](https://user-images.githubusercontent.com/55348946/93885180-8a3daa80-fcec-11ea-85d6-df20c29e03c2.png)

Also, if we have an object or other creature in a certain spot, unicorns on a screenshot can reach the most distant line. But with animation failure:
![Unicorn movement](https://user-images.githubusercontent.com/55348946/93885690-1e0f7680-fced-11ea-843b-28d28271e910.png)
![Unicorn movement1](https://user-images.githubusercontent.com/55348946/93885696-2071d080-fced-11ea-8fc6-2a43586ba005.png)
![Unicorn movement2](https://user-images.githubusercontent.com/55348946/93885701-236cc100-fced-11ea-98ca-d95847097894.png)
Sprite shifts with excessive speed to that place.

**Comment by idshibanov** [comment]
Same as #719 .
