### ISSUE TITLE
Remove top icon bar in no frame mode

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#179]
In no frame mode we noticed that there is an additional icon bar at the top-right corner which repeats the same bar at the bottom. We have to remove it. 

<img width="636" alt="Screenshot 2019-10-19 at 12 58 21 PM" src="https://user-images.githubusercontent.com/19829520/67142849-952ec600-f265-11e9-9a10-afafde136ff3.png">

**Comment by pathway27** [comment]
These buttons actually toggle the other dialogs invisible and not.

Do we really want to remove them?

**Comment by ihhub** [comment]
Hmm... Let me check this.

**Comment by ihhub** [comment]
Hi @pathway27 , you are right. We can't remove them. Closing this issue as invalid.
