### ISSUE TITLE
Town Population screen (with the well), wrong vertical position of the text in the information bar at the bottom of the screen

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1793]
In fheroes2, the vertical position of the text in the information bar at the bottom of the screen is not the same as in the original game.

In original game:

![Town well pop H2 01](https://user-images.githubusercontent.com/43583994/94143063-9736d700-fe6f-11ea-9014-d1df54df2ad8.png)

In fheroes2:

![Town well pop fh2 01](https://user-images.githubusercontent.com/43583994/94143086-9d2cb800-fe6f-11ea-8f20-b06258fa3990.png)

Open the two images in different tabs in your browser, enlarge the images and switch between the two tabs alternately.
Heroes 2 first, fheroes2 second.

![Town well pop H2 bar info 01](https://user-images.githubusercontent.com/43583994/94173139-be9f9b00-fe93-11ea-8c7d-1315055105be.png) ![Town well pop fh2 bar info 01](https://user-images.githubusercontent.com/43583994/94173147-c3fce580-fe93-11ea-8ce3-cfa8b028e113.png)

Similar issue: https://github.com/ihhub/fheroes2/issues/1687.

**Comment by Branikolog** [comment]
I believe this issue is connected with #1687. I hope our dev team would fix this issues together.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> I believe this issue is connected with #1687. I hope our dev team would fix this issues together.

I should have grouped this issue with another of the same kind.
I wanted to add links in other similar issues but I haven't done so yet.
