### ISSUE TITLE
Town Population screen (with the well), "Buy Monsters:" window, the elements are not centered horizontally

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1797]
In fheroes2, in the "Buy Monsters:" window, the elements are not centered horizontally.
This includes the title "Buy Monsters:", the different creatures and their quantity, the gold sprite and the gold number.
The buttons are not at the same horizontal distance from the edge of the window.

In fheroes2:

![Buy monsters fh2 01](https://user-images.githubusercontent.com/43583994/94174009-f9560300-fe94-11ea-96c0-ec91ab3215cc.png)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , do we have any other issues with horizontal shift of elements in a dialog? I fixed whole dialog generation so it applies for every window similar to this.

**Comment by LeHerosInconnu** [comment]
@ihhub.

> Hi @LeHerosInconnu , do we have any other issues with horizontal shift of elements in a dialog? I fixed whole dialog generation so it applies for every window similar to this.

Have you looked at these issues: https://github.com/ihhub/fheroes2/issues/1366, https://github.com/ihhub/fheroes2/issues/1359, https://github.com/ihhub/fheroes2/issues/1348, https://github.com/ihhub/fheroes2/issues/1611.
