### ISSUE TITLE
Remove final coin result for creature purchase window

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#180]
In creature purchase window (in any town) we display overall amount of coins for purchase as well as result after deduction this amount. This confuses users. We have to remove it.

On screenshot below we have 1200 coins and 6300 coins after purchase. We need to remove 6300:
<img width="635" alt="Screenshot 2019-10-19 at 12 56 07 PM" src="https://user-images.githubusercontent.com/19829520/67142874-e5a62380-f265-11e9-87eb-3fe5634a75b2.png">

**Comment by brunonucleu** [comment]
loser

**Comment by brunonucleu** [comment]
good job

**Comment by andrey-starodubtsev** [comment]
this issue was addressed in #181
