### ISSUE TITLE
Make with external libs

### ISSUE THREAD

**Issue by undef21** [ihhub/fheroes2#1801]
There is policy to build packages with system libraries in mainstream linux distributions. May be add option WITH_SYSTEM_LIBS in makefiles to use gzstream, tinyxml and, probably, libsmacker for use with distrib libraries?

**Comment by ihhub** [comment]
Are we sure that these libraries are present in MacOS as well?

**Comment by undef21** [comment]
There is tinyxml in brew repository for MacOS. Gzstream probably unused and it's should be deleted.
WITH_EXTERNAL_LIBS is better name and it's may be optional flag for those cases, when user link fheroes2 with manually compiled libs in /usr/local or /home places.

**Comment by geekless** [comment]
> Are we sure that these libraries are present in MacOS as well?

I guess, the purpose of that flag is mainly to make maintainers of some Linux distributions happy, so it actually makes little or no sense in MacOS.

**Comment by ihhub** [comment]
I'm okay with such option if it doesn't break any existing compilation.
