### ISSUE TITLE
Puzzle map is too bright

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1824]
After recent updates puzzle map became too bright, so we cannot see the details on it:
![image](https://user-images.githubusercontent.com/55348946/94408571-9eb2f480-017d-11eb-84e9-8e2431fa4ad2.png)

**Comment by Branikolog** [comment]
I know, that it's close to original, but previous implementation seemed more informative to me... 
At screenshot i can hardly recognize mountains and sands.

**Comment by idshibanov** [comment]
Both previous and current implementations are based on the palettes from original game. There's no "brightness" adjustment or something like that, just decide and pick one of them. @LeHerosInconnu

**Comment by idshibanov** [comment]
#1523 for reference.

**Comment by Branikolog** [comment]
@idshibanov 
Yeah, I know that different palettes were used for both implementations... 
It's just my point of view, that previous implementation was more comfortable. 
I open discussion here, so everyone can tell his thoughts here. 
I want to hear more opinions, especially from @LeHerosInconnu and our dev team...

**Comment by LeHerosInconnu** [comment]
@idshibanov.

> Both previous and current implementations are based on the palettes from original game. There's no "brightness" adjustment or something like that, just decide and pick one of them. @LeHerosInconnu

The color palette used seems to be this one:

![Puzzle palette H2 01](https://user-images.githubusercontent.com/43583994/94429751-1b040280-0193-11eb-9b16-cfbc068f8d88.png)

Now, the colors of the puzzle screen match the original game.

In original game:

![Ultime Artifact view puzzle 01](https://user-images.githubusercontent.com/43583994/92147349-55d87c00-ee1b-11ea-8055-6e61ac4c7c4a.png)

In fheroes2:

![Ultime Artifact view puzzle fh2 04](https://user-images.githubusercontent.com/43583994/94429787-2b1be200-0193-11eb-9c1f-37d6d69db076.png)

@Branikolog.

> @idshibanov
> Yeah, I know that different palettes were used for both implementations...
> It's just my point of view, that previous implementation was more comfortable.
> I open discussion here, so everyone can tell his thoughts here.
> I want to hear more opinions, especially from @LeHerosInconnu and our dev team...

It is true that with snow, beach and desert terrain, it is not really possible to discern them.
And I would also prefer these terrains to be recognizable.
The player have to rely on the surrounding objects to get an idea of ​​the location of the Ultimate Artifact.

The Ultimate Artifact is less frequently positioned on these three types of terrain than other types.
And I prefer the other types of terrain to be "brighter" compared to the previous too dark version of fheroes2.

I think that this is a technical aspect to be improved in the future for fheroes2.

In original game:

![Ultime Artifact view puzzle H2 05](https://user-images.githubusercontent.com/43583994/94429861-48e94700-0193-11eb-86af-458bc64df580.png)

![Ultime Artifact view puzzle H2 03](https://user-images.githubusercontent.com/43583994/94429884-53a3dc00-0193-11eb-8c50-153dd9b3a3dd.png)

In fheroes2:

![Ultime Artifact view puzzle fh2 03](https://user-images.githubusercontent.com/43583994/94429908-5e5e7100-0193-11eb-95de-c8cebda822bd.png)

**Comment by Branikolog** [comment]
So, lets wait with this improvement till we finish 1.0 version, then.....
