### ISSUE TITLE
Neutral creatures are willing to join hero's army way too often

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1828]
8 of 10 creatures want to join hero's army. This kills playing pleasure at all.
![image](https://user-images.githubusercontent.com/55348946/94435750-3a575b80-01a4-11eb-92d9-28ebcf2b1ff6.png)

**Comment by idshibanov** [comment]
Right now it is 20% chance when your army at least twice as stronger. Judging by the code I see original game also should have 20% chance.

1. We can force check if unit can fit in your army when they are willing to join for free (matching OG logic).
2. Change randomizer class to use C++11 library, it might improve it?
3. Knowingly reduce the default chance.

**Comment by ihhub** [comment]
Hi @Branikolog , could you please retest this issue on a new game? Just start the same map and check the ratio.

**Comment by idshibanov** [comment]
I believe the condition is set when you start a game, so to test this you'll have to restart scenario...

**Comment by Branikolog** [comment]
Okay. I'll do my best. )

**Comment by ihhub** [comment]
@Branikolog what's your conclusion? :)

**Comment by Branikolog** [comment]
@ihhub 
Well, it seems to me okay now. Nearly 1 out of 8 neutral creatures now want to join. Acceptable.

**Comment by ihhub** [comment]
Nice. Please close the issue if you think it's fixed.
