### ISSUE TITLE
Hero doesn't have custom start army

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1829]
When placed in front of city a hero starts with basic army, no matter what troops were set in editor.

**Comment by jacobggman** [comment]
can I try to do that?

**Comment by Branikolog** [comment]
Sure! You're free to make a PR to any issue you like. :)

**Comment by jacobggman** [comment]
Can you tell me which files I need to edit to make this?

**Comment by ihhub** [comment]
Hi @jacobggman , it's hard to say, otherwise we'd have fixed it. Please start with heroes.cpp where we read data from a stream.
