### ISSUE TITLE
Kingdom Overview screen, Towns/Castles Overview screen, graphical flaws in the display of town sprites

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1845]
In fheroes2, there are sometimes graphical flaws in the display of town sprites.
There is no black border inside the yellow frame to the right of the town sprite.
In the examples, for the second town sprite.

Edit: This is for the Knight town sprite and for the Warlock castle sprite that this happens.

In fheroes2:

![Kingdom Towns fh2 01](https://user-images.githubusercontent.com/43583994/94677754-ba550100-031d-11eb-979a-3a7a0414c384.png)

![Kingdom Towns fh2 02](https://user-images.githubusercontent.com/43583994/94681455-c348d100-0323-11eb-8955-7f53bd63db72.png)

![Kingdom Towns fh2 coupé 01](https://user-images.githubusercontent.com/43583994/94681468-cb087580-0323-11eb-9a0e-0cec0f4435a9.png)

![Kingdom Towns fh2 coupé 02](https://user-images.githubusercontent.com/43583994/94681478-cf349300-0323-11eb-9774-67d8de740a30.png)

**Edit 2020/10/01.**

Same problem in the adventure map screen in the towns list and in the towns information window (the town sprite is too large).

In fheroes2:

![Adventure screen fh2 01](https://user-images.githubusercontent.com/43583994/94796576-4418d300-03df-11eb-806e-9f6ecb5e0ea3.png)

![Adventure screen fh2 coupé 01](https://user-images.githubusercontent.com/43583994/94796603-4b3fe100-03df-11eb-8163-4ce2a7b6ba49.png)

![Adventure screen fh2 02](https://user-images.githubusercontent.com/43583994/94797943-2fd5d580-03e1-11eb-825e-c574ec2d59b0.png)

![Adventure screen fh2 03](https://user-images.githubusercontent.com/43583994/94797979-39f7d400-03e1-11eb-9fd6-24425885cc62.png)

**Comment by ihhub** [comment]
Is it correct that it happens only for the second from the top castle/town?

**Comment by LeHerosInconnu** [comment]
@ihhub.

> Is it correct that it happens only for the second from the top castle/town?

This could have been the cause of the bug. :)
If you look at the position of the scroll bar in the first screenshot, the sprite is not second in the towns/castles list.

I did some tests.
This is for the Knight town sprite and for the Warlock castle sprite that this happens.
I edited the first post.

**Comment by ihhub** [comment]
Fixed in #2142 .
