### ISSUE TITLE
Kingdom Overview screen, Heroes Overview and Towns/Castles Overview screens, left click on hero's portrait and on castle sprite

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1847]
In the original game, when the player left click on a hero's portrait, the hero screen is displayed.
And when the player exits the hero screen, he end up in the adventure map screen.

In fheroes2, it would be nice if the player could left click on a hero's portrait to display the hero screen.
An improvement can be made to the original game by having that when the player exits the hero screen, he returns to where he was on the Kingdom Overview screen and not on the adventure map screen.

In the original game, when the player left click on a castle sprite, the castle screen is displayed.
And when the player exits the castle screen, he end up in the adventure map screen.

In fheroes2, it would be nice if the player could left click on a castle sprite to display the castle screen.
The same improvement can be made to the original game by having that when the player exits the castle screen, he returns to where he was in the Kingdom Overview screen and not on the adventure map screen.

In fheroes2 it would also be nice to make sure that when the player left click on the captain portrait/empty captain slot (so when there is no hero portrait in that slot), the castle screen is also displayed.

In original game:

![Kingdom Heroes H2 01](https://user-images.githubusercontent.com/43583994/94677515-4fa3c580-031d-11eb-8f28-d67bf9c19e00.png)

![Kingdom Towns H2 01](https://user-images.githubusercontent.com/43583994/94677740-b5904d00-031d-11eb-83ee-575e4e32a4f1.png)

**Comment by ihhub** [comment]
The start point would be to check `OpenDialog` method of hero and castle classes.
