### ISSUE TITLE
Game considers hero has movement points, when he boards a ship

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1858]
When hero boards, game asks on ending turn. Also we have "Next Hero" button in non-disabled mode.
![image](https://user-images.githubusercontent.com/55348946/94816549-a7692c00-0404-11eb-8fc9-1ff3c7469768.png)

**Comment by ihhub** [comment]
Hi @Branikolog could you please provide a save file for this issue? I cannot reproduce it.

**Comment by Branikolog** [comment]
@ihhub
Here you are.
[1The_Legends_0007.zip](https://github.com/ihhub/fheroes2/files/5316592/1The_Legends_0007.zip)
