### ISSUE TITLE
Castle construction screen, Wizard castle, Library information window display fault

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1861]
Start (for example) the "Broken Aliance" scenario by choosing the Wizard's castle.
Open the castle construction screen and right click on the Library.
A display bug occurs.

In fheroes2:

![Library info bug fh2 01](https://user-images.githubusercontent.com/43583994/94838378-c6bc8500-0415-11eb-9b83-97bfd38ffcd0.png)

**Comment by idshibanov** [comment]
Happens on 640x480 resolution only. I think that popup doesn't fit and one of the variables overflows.
