### ISSUE TITLE
Captain displayed in wrong row of Castle Overview screen

### ISSUE THREAD

**Issue by taeber** [ihhub/fheroes2#1877]
In the original game, the Captain is displayed on the bottom row of the Castle Overview screen. In fheroes2, however, the Captain is being displayed in the top row.

### HOMM2
![Captain on bottom row when no hero is present](https://user-images.githubusercontent.com/1855194/94995814-c7b4fa00-056e-11eb-95fc-52fc9a116aba.png)
_Captain on bottom row when no hero is present in HOMM2_

![No captain seen when Hero present](https://user-images.githubusercontent.com/1855194/94995815-c84d9080-056e-11eb-97ea-d85e121188ac.png)
_No captain seen when hero is present in HOMM2_

### FHeroes2
![Captain on top row in fheroes2](https://user-images.githubusercontent.com/43583994/94686651-69e4a000-032b-11eb-8734-f520b660e97c.png)
_Captain on top row in fheroes2_

**Comment by Branikolog** [comment]
Hello, @taeber!
Thanks, for your contribution to our project! 
Actually, we've placed captain on top, so player would know, if it was built, when a hero is in castle... 
How do you think, is it essential to have captain in the same place, as in the original game? 
Also, I would like to hear the opinion of @LeHerosInconnu about this issue too.

**Comment by taeber** [comment]
@Branikolog, I agree that it makes more sense to have it on the top row so you can more easily see if there is a captain present.

I had assumed, however, that the initial 1.0 release of fheroes2 was trying to be as close to the original as possible while offering optional enhancements to the game play and user interface.

I totally understand if you want to close this bug as *wont-fix*. No hard feelings. It'll be good to document that this decision was made either way. (For what it's worth, I did search for an existing issue before opening this one.)

Thank you!

**Comment by Branikolog** [comment]
I won't close it for now, as I have the same thoughts. 
I'd like to hear the opinion of our developer team, as well as our main OG tester @LeHerosInconnu, about this enhancement. :)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

Personally, I prefer the way the captain's portrait is currently positioned in fheroes2 because it gives information to the user.
Also, in the future, I have planned various things for the captain and a right click on his portrait (among other possibilities) when a hero is also present in the castle would allow the player to take into account the information on the captain to make decisions.

**Comment by ihhub** [comment]
@Branikolog and @LeHerosInconnu am I correct to say that we are going to keep the current logic and won't change it back to the logic in the original game? If yes we will close this issue and related pull request.

**Comment by Branikolog** [comment]
I vote for captain in the upper row.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

I am for the captain to stay in the top box as is currently the case in fheroes2.

**Comment by ihhub** [comment]
In this case I'm closing this issue and the pull request as everyone agreed on the same.
