### ISSUE TITLE
Tavern information should show correct info about project

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#188]
Open a castle with built tavern. Right now it show old information about the project:
<img width="666" alt="Screenshot 2019-10-22 at 2 28 20 PM" src="https://user-images.githubusercontent.com/19829520/67285402-24471280-f4e0-11e9-8675-9e5c817a2450.png">
We should display information about current project, not about the old one.

**Comment by swarupe** [comment]
Can you explain, what information should be shown in the tavern screen?

**Comment by ihhub** [comment]
Hi @swarupe , let's change this message into `You could download latest version of the game from https://github.com/ihhub/fheroes2/releases`. At least it makes more sense for us.

**Comment by swarupe** [comment]
Ok I ll check into it

**Comment by swarupe** [comment]
How can I reach tavern screen?

**Comment by swarupe** [comment]
![Screenshot (38)](https://user-images.githubusercontent.com/32168917/67514606-a12de400-f6ba-11e9-96d4-004b3ebc312e.png)
I am getting this screen instead
