### ISSUE TITLE
Game screens, all "EVIL" windows are not centered vertically in the screen

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1882]
In fheroes2, with the "EVIL" interface, all windows of this type are not centered vertically in the screen.

In fheroes2:

![Quit confirmation window evil fh2 01](https://user-images.githubusercontent.com/43583994/94999522-323f5780-05ba-11eb-90f8-c5c69b765b71.png)

![Adventure Evil fh2 01](https://user-images.githubusercontent.com/43583994/94999527-39666580-05ba-11eb-8322-8e2ffd04a35f.png)

![Hero Evil fh2 03](https://user-images.githubusercontent.com/43583994/94999528-3f5c4680-05ba-11eb-8dc8-95c0dda64920.png)

![Hero meeting Evil fh2 02](https://user-images.githubusercontent.com/43583994/94999534-46835480-05ba-11eb-9b8b-aa907e70b050.png)

![Castle Evil fh2 02](https://user-images.githubusercontent.com/43583994/94999544-4b480880-05ba-11eb-8379-8d881d90ec6f.png)

![Castle construction Evil fh2 02](https://user-images.githubusercontent.com/43583994/94999550-51d68000-05ba-11eb-9e49-7c44fbca187c.png)

![Castle mage guild Evil fh2 02](https://user-images.githubusercontent.com/43583994/94999554-5864f780-05ba-11eb-84d2-50bf062d1192.png)

![Castle pop well Evil fh2 03](https://user-images.githubusercontent.com/43583994/94999560-5ef36f00-05ba-11eb-8a2a-733cb36f50e7.png)

![Kingdom Hero Evil fh2 02](https://user-images.githubusercontent.com/43583994/94999566-6581e680-05ba-11eb-9cec-82debed56859.png)

![Kingdom Town Evil fh2 04](https://user-images.githubusercontent.com/43583994/94999571-6c105e00-05ba-11eb-95dc-b7d5bcf510ca.png)

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu!
Can you clarify, if we should center these windows vertically considering skulls on top and bottom? Or the same distance should be between edges of the screen and frames of the window?

**Comment by emotionalamoeba** [comment]
![image](https://user-images.githubusercontent.com/19264468/97116560-eb92d800-16f5-11eb-9a84-5ffd1deaea0c.png)

Looks like a difference of about 5 pixels vertically in this example. This is the issue, right?

**Comment by Branikolog** [comment]
@LeHerosInconnu 
Sure!
I'm just sitting with a ruler in front of my screen trying to find out the way it centers on a screen. The distance from the edges of the screen are both not same for both this windows.)

**Comment by emotionalamoeba** [comment]
So both types need equal distancing between screen border and straight edges on borders vertically then? :)

**Comment by Branikolog** [comment]
@emotionalamoeba 
I think both of text boxes of this window should be at the same place, at least.)

**Comment by LeHerosInconnu** [comment]
@Branikolog and @emotionalamoeba.

It would be best to center these windows vertically, taking into account the frame without the protruding decorations ("Good" and "Evil" interface).

This way if the window becomes too large in height relative to the screen the decorations are cut first rather than the window content.
Also visually it looks more "balanced " this way.

**Comment by Branikolog** [comment]
@LeHerosInconnu 

> It would be best to center these windows vertically, taking into account the frame without the protruding decorations ("Good" and "Evil" interface).

It seems to me that the majority of"good" interface windows are not centered in this manner currently... Do we have a thread for "good" interface windows' vertical position?

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> @LeHerosInconnu
> 
> > It would be best to center these windows vertically, taking into account the frame without the protruding decorations ("Good" and "Evil" interface).
> 
> It seems to me that the majority of"good" interface windows are not centered in this manner currently... Do we have a thread for "good" interface windows' vertical position?

There does not seem to be an open issue for this type of window.
I have made some suggestions about this, but the issues are closed: https://github.com/ihhub/fheroes2/issues/1251, https://github.com/ihhub/fheroes2/issues/1258.

**Comment by ihhub** [comment]
Hi @emotionalamoeba ,

you should take a look into dialog_box.cpp file. All the code locates there. The solution should be trivial about the shift of the window by Y axis in both interfaces. `startYPos` input argument is responsible for the position in case of specific cases. If it's -1 then we have to center the window. So what we need is to modify `posy = ( display.height() - height_top_bottom - height_middle ) / 2;` line.

**Comment by emotionalamoeba** [comment]
Thanks ihhub :slightly_smiling_face:
