### ISSUE TITLE
Hero screen, creature separation window, info bar text at the bottom of the screen, add the word "to" and put "r" in lowercase

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1887]
Add the word "to" and put the first letter "r" of the word "redistribute" in lowercase:

"Move or right click to redistribute Black Dragons"

Instead of:

"Move or right click Redistribute Black Dragons"

I also suggest to change the sentence in the creature separation window:

"How many troops to move?"

Instead of:

"Move how many troops?"

In fheroes2:

![Hero Evil fh2 20a](https://user-images.githubusercontent.com/43583994/94999843-92cf9400-05bc-11eb-94ec-99303e0580da.png)

**Comment by Lumary2** [comment]
did that one. :)
