### ISSUE TITLE
Battle animation goes out of battle window

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#191]
Run the game in resolution more than 640 x 480 pixels and run any battle. Move unit close to upper side of battle window and notice that images stay on world map until the end of the battle which looks very weird:

<img width="836" alt="Screenshot 2019-10-22 at 5 47 23 PM" src="https://user-images.githubusercontent.com/19829520/67398276-12826f80-f5b3-11e9-9832-507faf9bb60c.png">

**Comment by ihhub** [comment]
One solution for this problem is to redraw whole game instead of battle area like it is done right now.

**Comment by idshibanov** [comment]
@ihhub can we treat battle area as a separate surface and draw on that? Would have to update all offsets though..
