### ISSUE TITLE
Don't enter in main menu into 'new game' - all freezed

### ISSUE THREAD

**Issue by efureev** [ihhub/fheroes2#1911]
1. After run:

user@MacBook-Pro ~ % /Users/fureev/Downloads/fheroes2_osx_sdl2/fheroes2 ; exit;
libsmacker::smk_open_file(H2XINTRO.SMK,1) - ERROR: could not open file (errno: 2)
	Error reported was: No such file or directory

MacBook Pro (15-inch, 2018), 32Gb
Catalina (10.15.6)

2.  Don't enter in main menu into 'new game' - all freezed.

**Comment by ihhub** [comment]
Hi @efureev , the error mentioned by you is just a warning. It doesn't affect anything. Could you please help us with more details: are you clicking on New Game button and everything freezes?

**Comment by efureev** [comment]
> Hi @efureev , the error mentioned by you is just a warning. It doesn't affect anything. Could you please help us with more details: are you clicking on New Game button and everything freezes?

yes. When I clicked on the 'New Game' button - everything freezes. none of the buttons respond

**Comment by ihhub** [comment]
Ah, okay. Thank you for the info. We'll try to reproduce it and fix it.

**Comment by ihhub** [comment]
@efureev please try to press Esc button when yousee this issue. If it's the case then you're right about resolution.

**Comment by ihhub** [comment]
Hi @efureev , could you please verify this issue on the latest commit? it should be fixed by now.

**Comment by efureev** [comment]
> @efureev please try to press Esc button when yousee this issue. If it's the case then you're right about resolution.
Yes, so works.

I've download v0.8.4 and tried this issue - the issue is stay )
When you choose a resolution from list greater then yours - all modal window are hidden. For example: after choosing resolution, click on button "new game". You'll see nothing. 'Esc' is the only solution.

**Comment by ihhub** [comment]
Hi @efureev could you please attach a screenshot of your game with when you notice this?

**Comment by ihhub** [comment]
Closing this issue as a solution for it is to use a smaller resolution and just rescale the window, which is supported right now.
