### ISSUE TITLE
"Blind" spell has wrong spell cost

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1912]
When we look at "Blind" spell in magic book, it costs 3SP.
When we look at the same spell in mage guild, it costs 6 SP.
![image](https://user-images.githubusercontent.com/55348946/95217915-673aec80-07fc-11eb-9219-b106af9c6659.png)
![image](https://user-images.githubusercontent.com/55348946/95217950-6e61fa80-07fc-11eb-8d3c-9f661340a664.png)
In the OG it costs 6 SP.

**Comment by a-mere-peasant** [comment]
https://github.com/ihhub/fheroes2/blob/6bcdda1ad1e91b3abb79b39f96ed872a7cf93ce0/src/fheroes2/spell/spell.cpp#L73
Is there any change made to this cost anywhere ?

**Comment by ihhub** [comment]
Hi @a-mere-peasant , this place contains the correct value: 6 SP.

**Comment by ihhub** [comment]
Hi @Branikolog , I tested it right now and I see no such issue:
![image](https://user-images.githubusercontent.com/19829520/95222251-e3e4bf80-082a-11eb-9ce1-2ff4d52b913b.png)
![image](https://user-images.githubusercontent.com/19829520/95222272-e9420a00-082a-11eb-87f8-7b1281abc225.png)

**Comment by ihhub** [comment]
Hi @Branikolog , could you please check that your hero doesn't have **Evil Eye** artifact in his inventory.

**Comment by Branikolog** [comment]
@ihhub 
Okay. Probably you're right. 
I could have it. I'll check this issue again in a hour, or so...

**Comment by LeHerosInconnu** [comment]
@Branikolog.

It certainly comes from the Skullcap artifact.

In fheroes2:

![Skullcap fh2 01](https://user-images.githubusercontent.com/43583994/95227021-e54bc300-07fd-11eb-97e9-ee96cc09a44f.png)

**Comment by Branikolog** [comment]
@LeHerosInconnu, exactly! 
I definitely own that hat!) 
Thanks for your high precision skill! :)
Sorry for wrong issue.
