### ISSUE TITLE
Game windows, changes to title, yellow color and colon ":"

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1919]
I suggest to make some changes to these windows.

Change the title color to yellow and remove the colon ":" in the title "Income".
![Castle Evil fh2 08](https://user-images.githubusercontent.com/43583994/95341020-21425f00-08b6-11eb-9d26-5b279435be5d.png)

Change the title color to yellow and remove the colon ":" in the title "Income".
![Castle Evil fh2 09](https://user-images.githubusercontent.com/43583994/95341025-23a4b900-08b6-11eb-8c61-faac91213243.png)

Remove the colon ":" in the title "Buy Monsters".
![Castle pop well Evil fh2 03](https://user-images.githubusercontent.com/43583994/94999560-5ef36f00-05ba-11eb-8a2a-733cb36f50e7.png)

Change the title "Recruit Hero" color to yellow.
![Castle construction Evil fh2 04](https://user-images.githubusercontent.com/43583994/95341094-34edc580-08b6-11eb-9e5c-3af63e1fa2e7.png)

Change the title "Recruit Titans" color to yellow.
![Kingdom Town Evil fh2 06](https://user-images.githubusercontent.com/43583994/95341114-3a4b1000-08b6-11eb-9e97-4f403687ca87.png)

Change the title "A glorious victory!" color to yellow.
![Combat Evil fh2 04](https://user-images.githubusercontent.com/43583994/95341143-40d98780-08b6-11eb-8e6e-5a9eef4ff425.png)

**Comment by shprotru** [comment]
Question: at screen `A glorious victory!` small header `Battlefield Casualties` should be yellow color?

**Comment by LeHerosInconnu** [comment]
Hi @shprotru,

> Question: at screen `A glorious victory!` small header `Battlefield Casualties` should be yellow color?

No, this is not necessary, only the title of the window should be in yellow.

**Comment by Branikolog** [comment]
Well, I cannot say, that changing colors for all of this windows will look better. Especially without screenshots. 
On my subjective point of view "income", "recruit hero" and could win, if we make yellow titles...
And "victory" and "recruit creatures"  windows would probably not...
Also I'm not sure that "buy monsters" window should be leaved as it is... Yellow title was made there to divide a title from a text written in the same fonts... And it is, surely, a required step. But I think, for creatures selection we should add some kind of buttons, or small icons... And after that I'm not sure about adding yellow title here at all.
Let's say that I don't want to change color to yellow, while looking at the messages while recruiting creatures and winning a battle... For example, for a bottle message I definitely want a yellow title, but for this two... Not sure is it necessary at all..
We might ask more people to share their thoughts on this issue...
