### ISSUE TITLE
Put VS 2015 redistributable files into deployment package for Windows

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#192]
If user doesn't have installed **Visual Studio 2015** redistributable then the game won't start and shows error message with missing **MSVCP140.dll** library. We have to include this file into deployment package for x32 and x64 versions.

Alternatively, we could try to compile the application with `/MTd` flag for debug mode and `/MT` for release mode.

**Comment by andrey-starodubtsev** [comment]
my VS2015 setup says this during the build, BTW:

```
1>LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library
```

seems like `SDL.dll` and `SDL_Mixer.dll` both linked with another version of MSVCRT.dll:

![depends_sdl](https://user-images.githubusercontent.com/7666511/67486800-5c338e80-f675-11e9-8fd4-7812b767299a.png)
![depends_sdl_mixer](https://user-images.githubusercontent.com/7666511/67486842-6fdef500-f675-11e9-9ae3-f0c67e291d4a.png)

May be these dlls should be rebuilt statically or with the same version of MSVCRT on their own.

**Comment by andrey-starodubtsev** [comment]
Also, relies on #198 PR.
