### ISSUE TITLE
File Options window, "CANCEL" button information window missing

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1925]
In fheroes2, the "CANCEL" button information window is missing.

I also suggest to add the yellow title "Cancel" to this window.

In original game:

![File Options Cancel info Evil H2 01](https://user-images.githubusercontent.com/43583994/95355843-4c34af00-08c6-11eb-9d6b-e63e8a7ac68c.png)

In fheroes2:

![File Options Cancel info Evil fh2 01](https://user-images.githubusercontent.com/43583994/95355896-5bb3f800-08c6-11eb-9ab2-ab1dda7f7f95.png)

![File Options Cancel info Good fh2 01](https://user-images.githubusercontent.com/43583994/95355915-61a9d900-08c6-11eb-82b1-e69441947ac4.png)

**Comment by Branikolog** [comment]
In my opinion yellow titles should be added only for those windows (the most of them) which you've clicked with the left mouse button. As yellow titles for me - is an important window performing action. Also it reminds me, what window had I chosen, so I wouldn't be confused. 
For the description widows appeared on a right click I'd like not  to have yellow titles... As I simply want to check the purpose of the button I've pressed with right click. 
The same idea is for #1918 description windows...

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> In my opinion yellow titles should be added only for those windows (the most of them) which you've clicked with the left mouse button. As yellow titles for me - is an important window performing action. Also it reminds me, what window had I chosen, so I wouldn't be confused.
> For the description widows appeared on a right click I'd like not to have yellow titles... As I simply want to check the purpose of the button I've pressed with right click.
> The same idea is for #1918 description windows...

This aims to standardize the interface.
There are already a lot of windows that are opened with the right click that have a yellow title.
Some examples:

In fheroes2:

![Adventure Evil fh2 01](https://user-images.githubusercontent.com/43583994/94999527-39666580-05ba-11eb-8322-8e2ffd04a35f.png)

![Castle Evil fh2 02](https://user-images.githubusercontent.com/43583994/94999544-4b480880-05ba-11eb-8379-8d881d90ec6f.png)

![Castle mage guild Evil fh2 02](https://user-images.githubusercontent.com/43583994/94999554-5864f780-05ba-11eb-84d2-50bf062d1192.png)

![File options Evil new game fh2 06](https://user-images.githubusercontent.com/43583994/95561221-b3fc0e80-0a1a-11eb-93da-edf1fbaa006d.png)

![Hero Evil fh2 03](https://user-images.githubusercontent.com/43583994/94999528-3f5c4680-05ba-11eb-8dc8-95c0dda64920.png)

![Hero meeting Evil fh2 02](https://user-images.githubusercontent.com/43583994/94999534-46835480-05ba-11eb-9b8b-aa907e70b050.png)

![Info quit evil fh2 01](https://user-images.githubusercontent.com/43583994/95561197-a9da1000-0a1a-11eb-83de-53ce3b74571c.png)

![Kingdom Hero Evil fh2 02](https://user-images.githubusercontent.com/43583994/94999566-6581e680-05ba-11eb-9cec-82debed56859.png)

![Scenario multiplayer Evil fh2 03](https://user-images.githubusercontent.com/43583994/95561255-beb6a380-0a1a-11eb-938d-e3f5e9211c34.png)

![Scenario selection Evil fh2 14](https://user-images.githubusercontent.com/43583994/94999793-150b8880-05bc-11eb-9dd3-d304e7cfcec0.png)

**Comment by Branikolog** [comment]
@LeHerosInconnu 
Well, your conviction skills as well as precision power reassures me again.)
