### ISSUE TITLE
Adventure map, wasteland terrain sprite displayed over hero's sprite

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1933]
The wasteland terrain sprite is displayed over the hero's sprite.

In fheroes2:

![Wasteland over hero fh2 01](https://user-images.githubusercontent.com/43583994/95486165-f7ab3580-0992-11eb-9224-3148fa088556.png)

![Wasteland over hero fh2 coupé 01](https://user-images.githubusercontent.com/43583994/95486172-f974f900-0992-11eb-8222-ad23e69067c6.png)

**Comment by idshibanov** [comment]
Same cause and resolution as described in #772 . Have to refactor Hero redraw logic.

**Comment by LeHerosInconnu** [comment]
@idshibanov.

> Same cause and resolution as described in #772 . Have to refactor Hero redraw logic.

Okay, I will suspend bug reports related to the hero sprite for now.
Thank you.

**Comment by vasilenkoalexey** [comment]
> Okay, I will suspend bug reports related to the hero sprite for now.

Could you provide sav file for this issue?

**Comment by LeHerosInconnu** [comment]
Hello @vasilenkoalexey,

> > Okay, I will suspend bug reports related to the hero sprite for now.
> 
> Could you provide sav file for this issue?

Here are the save files (before and after) and the scenario test:
[Crater 01.zip](https://github.com/ihhub/fheroes2/files/6644135/Crater.01.zip)

**Comment by LeHerosInconnu** [comment]
The Watering Hole sprite is displayed over the hero's sprite.

In fheroes2:

![vlcsnap-2021-09-12-11h10m17s775](https://user-images.githubusercontent.com/43583994/132982154-0800182b-041e-44e2-8ceb-e2a2d346e541.png)

https://user-images.githubusercontent.com/43583994/132982166-b2ace6f0-dde1-475b-93d7-14203e214206.mp4

Here is the save file (0.9.7 4180):
[Hero move under Watering ho.zip](https://github.com/ihhub/fheroes2/files/7149329/Hero.move.under.Watering.ho.zip)

**Comment by LeHerosInconnu** [comment]
Another save for this (0.9.9 4628).

In fheroes2, the Windmill sprite and animation is displayed over the hero's flag.

In fheroes2:

![Windmill over hero flag 01](https://user-images.githubusercontent.com/43583994/143442299-cf5b26e7-6618-4256-b409-a54a5cac83e1.png)

Here is the save file:
[Windmill over hero flag 01.zip](https://github.com/ihhub/fheroes2/files/7602946/Windmill.over.hero.flag.01.zip)
