### ISSUE TITLE
Adventure map, mine flag no longer displayed when hero next to the mine

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1940]
In fheroes2, the mine flag is no longer displayed when the hero is next to the mine.

In fheroes2:

![Flag not displayed 01](https://user-images.githubusercontent.com/43583994/95651606-d4e06480-0aeb-11eb-803c-de76c221646d.png)

![Flag not displayed 02](https://user-images.githubusercontent.com/43583994/95651608-d742be80-0aeb-11eb-9631-49eb757c8b4d.png)

Here is the save file:
[Bug mine no flag 01.zip](https://github.com/ihhub/fheroes2/files/5358735/Bug.mine.no.flag.01.zip)

**Comment by idshibanov** [comment]
Same as #1933 .

**Comment by LeHerosInconnu** [comment]
Another save for this bug.

In fheroes2, the top of the sawmill flag is cut.

In fheroes2:

![Flag sawmill cut fh2 01](https://user-images.githubusercontent.com/43583994/101158633-522bdf80-362c-11eb-93cc-34b0d457dcd6.png)

Here is the save file:
[Flag sawmill cut fh2 01.zip](https://github.com/ihhub/fheroes2/files/5642409/Flag.sawmill.cut.fh2.01.zip)
