### ISSUE TITLE
Adventure map, hero sprite, castle flag displayed over hero sprite flag

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1941]
In fheroes2, the castle flag is displayed over the hero sprite flag.

In fheroes2:

![Castle flag over hero flag 01](https://user-images.githubusercontent.com/43583994/95651912-b1b6b480-0aed-11eb-9dc1-2b1873e0953c.png)

Here is the save file:
[Bug hero flag castle flag 01.zip](https://github.com/ihhub/fheroes2/files/5358751/Bug.hero.flag.castle.flag.01.zip)

Similar issue: https://github.com/ihhub/fheroes2/issues/1516.

**Comment by idshibanov** [comment]
Same as #1933 .

**Comment by ihhub** [comment]
Closing this issue as it was fixed few days ago.
