### ISSUE TITLE
View Puzzle screen, Ultimate Artifact, the rule of 9 squares of the original game should be respected

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1944]
In fheroes2, maps without a predetermined position of the Ultimate Artifact by the author of the scenario (automatic random placement of the position of the Ultimate Artifact), must follow the rules of the 9 squares of the original game (the Ultimate Artifact is positioned at a distance at least 9 squares from the edges of the map) to avoid problems with the edges of the map described in this thread: https://github.com/ihhub/fheroes2/issues/1536.

Here is a screenshot of the puzzle with the position of the Ultimate Artifact too close to the edge of the map.
Part of the bottom edge of the map is visible.
In this scenario the location of the Ultimate Artifact is randomly placed automatically.

In fheroes2:

![Puzzle 9 squares rule 01](https://user-images.githubusercontent.com/43583994/95652896-b03cba80-0af4-11eb-9b67-9f05f7386bb7.png)

Here is the save file:
[Puzzle near edge 01.zip](https://github.com/ihhub/fheroes2/files/5358810/Puzzle.near.edge.01.zip)

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu 
I also find a weird UA location case on a map, I've created.
The only free space is placed too close to world map edge. And the game decided to place UA over the existing hole on a distant island.
![image](https://user-images.githubusercontent.com/55348946/105479339-65b30880-5cb5-11eb-80ab-a593d24e535c.png)
![image](https://user-images.githubusercontent.com/55348946/105479368-6cda1680-5cb5-11eb-9656-3437f7f32b43.png)
The strange thing is that this place is always the same on this map...
[Map_0368.zip](https://github.com/ihhub/fheroes2/files/5855138/Map_0368.zip)
I also have a question for you.
Here, we have both cases, where "9 square rule" and "auto-placing of UA avoid certain areas" (#2317) are broken.
How should be artifact be placed here? On the only free space, but close to an edge? Or on any place, distant from the edges enough, but taken with object, like hole, river etc?

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

> Hi, @LeHerosInconnu
> I also find a weird UA location case on a map, I've created.
> The only free space is placed too close to world map edge. And the game decided to place UA over the existing hole on a distant island.
> The strange thing is that this place is always the same on this map...

Apparently, fheroes2 always chooses the first available spot relative to the map coordinates (0,0 in the upper left corner).
It should not be the case.

> I also have a question for you.
> Here, we have both cases, where "9 square rule" and "auto-placing of UA avoid certain areas" (#2317) are broken.
> How should be artifact be placed here? On the only free space, but close to an edge? Or on any place, distant from the edges enough, but taken with object, like hole, river etc?

On any place, distant from the edges enough.
River first (or other objects of the same category (decorations but accessible)), digging hole next (to avoid misleading the player as much as possible), free space behind object last (behind a mountain, etc.).
