### ISSUE TITLE
Adventure map, behavior of AI heroes in relation to their movement and resource generators

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1946]
The hero Darlana of the purple AI player does not take control of the Alchemist Lab during his movement although it would have been possible to do so without reducing his possible movement and even on the contrary because the hero makes a detour to pass by.

In fheroes2:

![Darlana lab 01](https://user-images.githubusercontent.com/43583994/95653208-3ce87800-0af7-11eb-8c6e-a5c1ff8ae2fb.png)

Pass the turn to observe the movement of the hero Darlana.

Here is the save file:
[AI hero do not flag lab 01.zip](https://github.com/ihhub/fheroes2/files/5358837/AI.hero.do.not.flag.lab.01.zip)

**Comment by idshibanov** [comment]
Known issue, already in the pipeline. This will be corrected in next round of AI changes for 0.8.3 release.

**Comment by LeHerosInconnu** [comment]
@idshibanov.

> Known issue, already in the pipeline. This will be corrected in next round of AI changes for 0.8.3 release.

Good to know.
I will suspend bug reports related to AI behavior until the next release.
Thank you.

**Comment by idshibanov** [comment]
It is still useful to have this control save to test while preparing the release.

AI is such a big change that we have to split it into smaller modules. This is the main reason why we started doing monthly releases. AI in 0.8.2 had a very minimal feature set (although arguably still better than what was there before) just to replace the old code for license reasons. Every subsequent release will add to it.

**Comment by LeHerosInconnu** [comment]
@idshibanov.

> It is still useful to have this control save to test while preparing the release.
> 
> AI is such a big change that we have to split it into smaller modules. This is the main reason why we started doing monthly releases. AI in 0.8.2 had a very minimal feature set (although arguably still better than what was there before) just to replace the old code for license reasons. Every subsequent release will add to it.

Okay, I understand.
I will continue to look at this. :)
