### ISSUE TITLE
Adventure map, wrong passability of objects

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1951]
In fheroes2, some objects do not have the same passability as in the original game.

In original game:

![Passability objets H2 01](https://user-images.githubusercontent.com/43583994/95658627-26084c80-0b1c-11eb-9971-aa03735bdfc3.png)

In fheroes2:

![Passability objets fh2 01](https://user-images.githubusercontent.com/43583994/95658643-489a6580-0b1c-11eb-9f09-d222dbcbf16e.png)

In original game:

![Passability objets H2 02](https://user-images.githubusercontent.com/43583994/95658629-2e608780-0b1c-11eb-9b39-7e7d4dd85f37.png)

In fheroes2:

![Passability objets fh2 02](https://user-images.githubusercontent.com/43583994/95658645-4df7b000-0b1c-11eb-8100-539d0878affe.png)

![Passability objets fh2 02a](https://user-images.githubusercontent.com/43583994/95658646-5223cd80-0b1c-11eb-9121-c4682faa7fa1.png)

In original game:

![Passability objets H2 03](https://user-images.githubusercontent.com/43583994/95658632-36b8c280-0b1c-11eb-8fd9-fd634bee741a.png)

In fheroes2:

![Passability objets fh2 03](https://user-images.githubusercontent.com/43583994/95658648-58b24500-0b1c-11eb-8eb9-42bcff92d25a.png)

In original game:

![Passability objets H2 04](https://user-images.githubusercontent.com/43583994/95658635-3c160d00-0b1c-11eb-89d7-280f5c2861fa.png)

![Passability objets H2 04a](https://user-images.githubusercontent.com/43583994/95658639-40422a80-0b1c-11eb-9eea-7fc0afb4eec9.png)

In fheroes2:

![Passability objets fh2 04](https://user-images.githubusercontent.com/43583994/95658657-6798f780-0b1c-11eb-8df5-2910e3b446da.png)

![Passability objets fh2 04a](https://user-images.githubusercontent.com/43583994/95658659-6a93e800-0b1c-11eb-94a9-e57417d988c5.png)

Here are the save files:
[Wrong objets passability 01.zip](https://github.com/ihhub/fheroes2/files/5359235/Wrong.objets.passability.01.zip)

Similar issues: https://github.com/ihhub/fheroes2/issues/1577, https://github.com/ihhub/fheroes2/issues/1521.

**Edit 2020/11/01.**

In original game:

![Passability objets fh2 10](https://user-images.githubusercontent.com/43583994/97812639-e815c880-1c82-11eb-8ce8-45c3cda0d114.png)

In fheroes2:

![Passability objets fh2 11](https://user-images.githubusercontent.com/43583994/97812630-d0d6db00-1c82-11eb-8b30-c12a3aa6f3cf.png)

Here is the save file:
[Hero path 01.zip](https://github.com/ihhub/fheroes2/files/5471617/Hero.path.01.zip)

**Edit 2020/11/08.**

In original game:

![Hero path passability H2 05](https://user-images.githubusercontent.com/43583994/98465361-ed19d100-21c8-11eb-9791-975500f6dac4.png)

In fheroes2:

![Hero path passability 05](https://user-images.githubusercontent.com/43583994/98465372-f3a84880-21c8-11eb-9f13-5dfb136991b3.png)

**Edit 2021/05/01.**

In original game:

![Before attack boat castle H2 01](https://user-images.githubusercontent.com/43583994/116791428-9a0b4180-aaba-11eb-8018-bb044e85e53f.png)

In fheroes2:

![Before attack boat castle fh2 01](https://user-images.githubusercontent.com/43583994/116791436-a2637c80-aaba-11eb-9c98-444c589bd69a.png)

**Edit 2021/05/30.**

In original game:

![Path shipwreck 02](https://user-images.githubusercontent.com/43583994/120113389-9848a280-c17a-11eb-9503-ea64bf149c62.png)

In fheroes2:

![Path shipwreck 01](https://user-images.githubusercontent.com/43583994/120113394-9da5ed00-c17a-11eb-9e1e-8c6daa0600ab.png)

I think all objects should be checked in comparison to the original game.

**Comment by Branikolog** [comment]
Also some rocks are passable, while in the OG they are not:
![image](https://user-images.githubusercontent.com/55348946/102221765-986a2400-3ef3-11eb-8fd8-9fe2910efca9.png)
![image](https://user-images.githubusercontent.com/55348946/102221809-a750d680-3ef3-11eb-8dc5-584564043ad5.png)

**Comment by Branikolog** [comment]
Wrong passability has Lean-to:
fheroes2
![image](https://user-images.githubusercontent.com/55348946/103151756-06370b00-4792-11eb-8ddd-a9b33acd45e0.png)
original game
![image](https://user-images.githubusercontent.com/55348946/103151778-2ff03200-4792-11eb-92a9-1a51f174c07f.png)

**Comment by qarkai** [comment]
Some looks like bugs in OG. E.g. ![HoMM2](https://user-images.githubusercontent.com/43583994/95658635-3c160d00-0b1c-11eb-89d7-280f5c2861fa.png)
and
![fheroes2](https://user-images.githubusercontent.com/43583994/95658657-6798f780-0b1c-11eb-8df5-2910e3b446da.png)
