### ISSUE TITLE
Combat, faded color background not very pretty

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1956]
In fheroes2, the faded color background is not very pretty compared to the original game.

In original game:

![Faded color background H2 01](https://user-images.githubusercontent.com/43583994/95661011-27417580-0b2c-11eb-9348-89eddd5d3e34.png)

In fheroes2:

![Faded color background fh2 01](https://user-images.githubusercontent.com/43583994/95661015-2dcfed00-0b2c-11eb-8682-9ae0ca757e25.png)

Here is the save file:
[Faded color background.zip](https://github.com/ihhub/fheroes2/files/5359455/Faded.color.background.zip)

**Comment by ihhub** [comment]
I think in our version fading is not that dark.
