### ISSUE TITLE
Adventure map, graphic glitch with boat near the coast

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1964]
In fheroes2, there is a graphical fault when the boat is positioned near the coast.

In fheroes2:

![Graphic glitch boat fh2 01](https://user-images.githubusercontent.com/43583994/95677428-c4042180-0bc5-11eb-9897-402133960731.png)

![Graphic glitch boat fh2 02](https://user-images.githubusercontent.com/43583994/95677430-c5cde500-0bc5-11eb-99fa-8e5facc7df57.png)

Here is the save file:
[Graphic glitch boat 01.zip](https://github.com/ihhub/fheroes2/files/5360988/Graphic.glitch.boat.01.zip)

**Comment by ihhub** [comment]
Closing this issue as #772 duplicate.
