### ISSUE TITLE
Adventure map, hero and castle, wrong selection after exiting the castle screen

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1965]
In fheroes2, there is a wrong selection after exiting the castle screen.

Attack Whiteshield castle with hero Celia.
After the combat, move Celia to the castle.
Then exit the castle screen.

The first hero Roxanna is selected.
But it is the hero Celia who must be selected.
In the original game, that's what happens.

In original game:

![Wrong selection H2 01](https://user-images.githubusercontent.com/43583994/95678893-beabd480-0bcf-11eb-859f-f5e3a0448241.png)

![Wrong selection H2 02](https://user-images.githubusercontent.com/43583994/95678896-c0759800-0bcf-11eb-937b-a7ee7a06720b.png)

![Wrong selection H2 03](https://user-images.githubusercontent.com/43583994/95678898-c23f5b80-0bcf-11eb-825a-8633013304d4.png)

In fheroes2:

![Wrong selection fh2 01](https://user-images.githubusercontent.com/43583994/95678904-ce2b1d80-0bcf-11eb-828b-876bec23dd56.png)

![Wrong selection fh2 02](https://user-images.githubusercontent.com/43583994/95678905-cff4e100-0bcf-11eb-9fc0-b01ec3bead90.png)

![Wrong selection fh2 03](https://user-images.githubusercontent.com/43583994/95678906-d1bea480-0bcf-11eb-9117-a1283216c95d.png)

Also, in the original game, when a castle screen is displayed and there is a visiting hero in that castle, that visiting hero is selected when the player exits the castle screen.
In fheroes2, the castle remains selected.

In original game:

![Wrong selection H2 04](https://user-images.githubusercontent.com/43583994/95678944-0d596e80-0bd0-11eb-8ddb-430c53b9dd0d.png)

![Wrong selection H2 02](https://user-images.githubusercontent.com/43583994/95678896-c0759800-0bcf-11eb-937b-a7ee7a06720b.png)

![Wrong selection H2 03](https://user-images.githubusercontent.com/43583994/95678898-c23f5b80-0bcf-11eb-825a-8633013304d4.png)

In fheroes2:

![Wrong selection fh2 04](https://user-images.githubusercontent.com/43583994/95678975-3da10d00-0bd0-11eb-8e17-14486a5a5d9c.png)

![Wrong selection fh2 02](https://user-images.githubusercontent.com/43583994/95678905-cff4e100-0bcf-11eb-9fc0-b01ec3bead90.png)

![Wrong selection fh2 05](https://user-images.githubusercontent.com/43583994/95678973-3bd74980-0bd0-11eb-98d5-e5e7ba38272e.png)

Here is the save file:
[Wrong selection fh2.zip](https://github.com/ihhub/fheroes2/files/5361084/Wrong.selection.fh2.zip)

**Comment by ihhub** [comment]
The problem lies in hero's movement, the same logic which triggers the screen move a bit after the completion of movement.

**Comment by LeHerosInconnu** [comment]
@ihhub.

This problem is still present. 

In original game:

https://user-images.githubusercontent.com/43583994/108639043-b5dae180-7492-11eb-83ed-14bc643b5533.mp4

In fheroes2 (0.9.0 2841):

https://user-images.githubusercontent.com/43583994/108639063-d145ec80-7492-11eb-9279-cb67a9908a50.mp4
