### ISSUE TITLE
Sea event operation

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1969]
In the OG we don't hear any sounds, while event appears. Also we can see a message in the appearing window together with artifact.
![image](https://user-images.githubusercontent.com/55348946/95733499-e8760180-0c8a-11eb-8d06-0c860deed688.png)
In fheroes2 we first see a separate window with message.
![image](https://user-images.githubusercontent.com/55348946/95733569-00e61c00-0c8b-11eb-802e-8e6243923ee1.png)
And then we see the ordinary window while finding artifact. Also, we can hear "collecting" sound, while this window appears. In the OG we don't hear any sounds.
![image](https://user-images.githubusercontent.com/55348946/95733708-2ecb6080-0c8b-11eb-8945-61a5a33bf005.png)

**Comment by Branikolog** [comment]
I'm not sure, if we shouldn't play here sound. It seems to me quite okay, to hear it during this event...

**Comment by a1exsh** [comment]
The original game also has a bug, in that it does not display all the resources collected in a sea event (here, 5 wood is not shown, but collected):
![Screenshot from 2021-09-04 09-16-43](https://user-images.githubusercontent.com/489601/132086301-e1ce4b61-0e55-4fa8-a148-22ab291c55c3.png)

Our version shows the resources correctly (followed by the Artifact dialog with the sound, as explained in the issue description):
![image](https://user-images.githubusercontent.com/489601/132086363-01e2c7a4-da8f-4913-8f23-bb17f60ff67e.png)

I think our version is better than OG and requires no changes.

**Comment by a1exsh** [comment]
Map used for the test: [ALLTEST.MP2.zip](https://github.com/ihhub/fheroes2/files/7109380/ALLTEST.MP2.zip)

**Comment by LeHerosInconnu** [comment]
Hello everyone.

> I'm not sure, if we shouldn't play here sound. It seems to me quite okay, to hear it during this event...

It would be nice if a sound is played when an event is triggered in fheroes2, at least when the player receives a reward.
Maybe with another sound when the event is rather negative?
Or a specific sound is played when an event is triggered, whether it is positive or negative?
It would be nice to have different sounds if the "reward" is negative or positive (if it is both at the same time, only the positive sound is played?, or both sounds are played in succession eventually?).

> The original game also has a bug, in that it does not display all the resources collected in a sea event (here, 5 wood is not shown, but collected):
> Our version shows the resources correctly (followed by the Artifact dialog with the sound, as explained in the issue description):
> I think our version is better than OG and requires no changes.

Would it be possible to display everything concerning the "reward" (positive or/and negative) in the same window?
This would be much better than requiring the player to close several windows.

**Comment by Branikolog** [comment]
Well, Original game has some other flaws here, in a case there's too much text and rewards here:
![image](https://user-images.githubusercontent.com/55348946/132091926-5dec7846-7436-43cc-b844-a2a01031a5fb.png)
In fheroes2, actually this case is handled better...
![image](https://user-images.githubusercontent.com/55348946/132091952-511df920-9135-42c8-9c6d-201e707ce37b.png)
(but the pop up window doesn't fit the screen on 640x480 res)
So I'm in a doubt now, whether we should make the same to the OG...
Probably, it would be better to show text first, and then window with rewards...

**Comment by LeHerosInconnu** [comment]
And why not add a scroll bar for the text when the window has reached the maximum size depending on the resolution?
The window could also be automatically expanded horizontally. :D
In all cases a unique window would be better in my opinion.

**Comment by a1exsh** [comment]
> And why not add a scroll bar for the text when the window has reached the maximum size depending on the resolution?

That's a good idea, probably worth of a separate issue (unless there is one already — at least I haven't found one).

> In all cases a unique window would be better in my opinion.

I second that: one window would be ideal, but we have to solve the issue of the long text in some way for that to work.
