### ISSUE TITLE
Wrong sounds are playing while visiting some objects on a world map

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1976]
"Wagon" and "Lean-to" play wrong sound. There should be sound the same to halfling hole, for example.
"Skeleton" object, also has wrong sound. It should play the current sound of "Lean-to".
![image](https://user-images.githubusercontent.com/55348946/95741710-6b04be00-0c97-11eb-95aa-ad22805172e4.png)

**Comment by Branikolog** [comment]
Also, don't forget, that sound should be played only of hero receives any resource or artifact.

**Comment by ihhub** [comment]
We need a proper list what should be changed in this issue description.
