### ISSUE TITLE
Adventure map, change of terrain type by the hero, there is a delay for the music when the hero changes terrain (in MIDI)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1979]
**Edit 2021/02/21.**
**Edit 2022/06/07.**

In the original game, there is no delay for the music when the hero changes terrain and the music resumes where it left off (in MIDI):

https://user-images.githubusercontent.com/43583994/108638297-cc7f3980-748e-11eb-852c-01e49283dfd6.mp4

In fheroes2, there is a delay for the music when the hero changes terrain (in MIDI)(and the music starts over from the beginning (will be corrected with another issue)):

https://user-images.githubusercontent.com/43583994/108638312-e587ea80-748e-11eb-8e48-7e2121ebb528.mp4

In fheroes2:

![Hero change terrain fh2 01](https://user-images.githubusercontent.com/43583994/95748306-157de080-0c9a-11eb-8c7d-587dec0e90d7.png)

Move the hero Roxana between the two types of terrain.

Here is the save file:
[Hero change terrain 01.zip](https://github.com/ihhub/fheroes2/files/5365185/Hero.change.terrain.01.zip)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , could you please update this issue or close it as we fixed #1008 recently?

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , could you please update this issue or close it as we fixed #1008 recently?

The issue has been updated.

**Comment by LeHerosInconnu** [comment]
Hello @zenseii,

I have edited the title and the original post.
