### ISSUE TITLE
Adventure map, hero with 0 movement points selected with the "Next Hero" button, also the hero should be able to make his last move over all types of terrain

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1986]
The hero Roxana has 0 movement points.
However the hero Roxanna is selected when the "Next Hero" button is pressed several times.

**Edit 2020/10/14.**
The hero should be able to make his last move over all types of terrain and in all directions from the road penalty.
And this should also be indicated in the hero's movement bar (a portion of the bar should be yellow) and the movement information should indicate "Move points: 1/85/1560".

![Roxana move left fh2 coupé 01](https://user-images.githubusercontent.com/43583994/95980297-3de21800-0e1d-11eb-8999-2ab1d45f7bfb.png)

In fheroes2:

![Hero 0 move next hero fh2 01](https://user-images.githubusercontent.com/43583994/95886729-3cfaa900-0d7f-11eb-809f-9b9cb317dc5f.png)

Here is the save file:
[Hero 0 move next hero fh2 01.zip](https://github.com/ihhub/fheroes2/files/5372627/Hero.0.move.next.hero.fh2.01.zip)

**Edit 2020/10/18.**
Another save for this bug.

The hero Troyan is located on the Swamp terrain which has a 175% movement penalty.
Troyan has 138 movement points left.
For her last move, Troyan should not be able to move because it is the penalty for the terrain where she is located that is taken into account.
However, Troyan can make a move on the Lava terrain which has a 100% movement penalty when she shouldn't be able to.

In fheroes2:

![Troyan move fh2 01](https://user-images.githubusercontent.com/43583994/96374338-72820680-1172-11eb-8c76-43fe3b90db5f.png)

![Troyan move fh2 02](https://user-images.githubusercontent.com/43583994/96374339-744bca00-1172-11eb-8af3-2d723e0667bf.png)

Here is the save file:
[Troyan move fh2 01.zip](https://github.com/ihhub/fheroes2/files/5397833/Troyan.move.fh2.01.zip)

**Comment by Branikolog** [comment]
The thing is that Roxana has movement points.
![image](https://user-images.githubusercontent.com/55348946/95977578-b5b24180-0e21-11eb-8b1a-08208d940264.png)
She has 85 out of 1560. Which is enough to make one more movement over a road.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> The thing is that Roxana has movement points.
> She has 85 out of 1560. Which is enough to make one more movement over a road.

Indeed, Roxana can move on the road.
But in this case, since Roxana is located on a road, she must be able to make her last move in all directions and over all types of terrain (from the road penalty).

And this should also be indicated in the hero's movement bar (a portion of the bar should be yellow) and the movement information should indicate "Move points: 1/85/1560".

![Roxana move left fh2 coupé 01](https://user-images.githubusercontent.com/43583994/95980297-3de21800-0e1d-11eb-8999-2ab1d45f7bfb.png)

**Comment by Branikolog** [comment]
@LeHerosInconnu 
I've just remembered the same case in Heroes3.
A hero with such small amount of points can move over a road/ (And he has a tiny yellow bar in movement meter left). But when he tries to step to a swamp, which penalty is huge, all movement points disappear, but hero doesn't move. What is original behaviour of heroes2 in this case?

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> @LeHerosInconnu
> I've just remembered the same case in Heroes3.
> A hero with such small amount of points can move over a road/ (And he has a tiny yellow bar in movement meter left). But when he tries to step to a swamp, which penalty is huge, all movement points disappear, but hero doesn't move. What is original behaviour of heroes2 in this case?

In the original game, if the hero can make a last horizontal or vertical move from the type of terrain or the road, then he can make a last move diagonally.
In the original game, it is the type of terrain or the road from which the hero initiates his last move that determines the possibility of the last move.

If the hero can move horizontally or vertically from the "grass" terrain, so he has at least 100 movement points left, then he will be able to move to a "desert" terrain type square diagonally.

If the hero can move horizontally or vertically from the "road" terrain, so he has at least 75 movement points left, then he will be able to move to a "desert" terrain type square diagonally.

It is always the penalty of the type of terrain or the road where the hero is located before making his last move that is used as a reference for the last move and not the penalty of the type of terrain of the destination square.

_Originally posted by @LeHerosInconnu in https://github.com/ihhub/fheroes2/issues/1145#issuecomment-690588986_

**Comment by ihhub** [comment]
Rleates to #3431

**Comment by LeHerosInconnu** [comment]
Another save for this.

The hero should not be able to enter the town because he has 75 movement points left and the move costs 100 movement points from the Dirt terrain.

In fheroes2:

![Hero wrong possible move 01](https://user-images.githubusercontent.com/43583994/132982952-ee4a743c-388a-4abd-8747-59a916a0a25d.png)

![Hero wrong possible move 02](https://user-images.githubusercontent.com/43583994/132982956-128756a6-d5ab-46eb-8f44-1a33bc5bb34b.png)

![Hero wrong possible move 03](https://user-images.githubusercontent.com/43583994/132982949-7e9d5c02-facb-49d5-9ea5-4cc9e3df8868.png)

Here is the save file (0.9.7 4180):
[Hero wrong possible move 01.zip](https://github.com/ihhub/fheroes2/files/7149366/Hero.wrong.possible.move.01.zip)

**Comment by LeHerosInconnu** [comment]
Another save for this.

The hero should be able to move all directions on all terrain types because he has 151 movement points left and the move costs 75 movement points from the road.

In fheroes2:

![Hero wrong possible move 02 001](https://user-images.githubusercontent.com/43583994/132983502-debc52ad-0ce5-4e69-9426-47bac8d43a6b.png)

![Hero wrong possible move 02 002](https://user-images.githubusercontent.com/43583994/132983505-b663ba12-acb0-40e1-8761-68e81d70ae0d.png)

![Hero wrong possible move 02 003](https://user-images.githubusercontent.com/43583994/132983508-b672c1fa-6690-484e-9c76-031c59fe62ce.png)

![Hero wrong possible move 02 004](https://user-images.githubusercontent.com/43583994/132983514-16c02525-5e12-4ea0-8443-45a70082e6ec.png)

Here is the save file (0.9.7 4180):
[Hero movement left should m.zip](https://github.com/ihhub/fheroes2/files/7149390/Hero.movement.left.should.m.zip)

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu

> The hero should not be able to enter the town because he has 75 movement points left and the move costs 100 movement points from the Dirt terrain.

In fact, this hero stands not on the Dirt terrain, but on the road with penalty 75 (I suppose it's due to the paved town exit). So with #4626 he is not only able to enter the town, but also to take a step aside:

<img width="639" alt="Road to town" src="https://user-images.githubusercontent.com/32623900/141594862-fba47282-071e-49a4-9695-4e580aa89b3d.png">

> The hero should be able to move all directions on all terrain types because he has 151 movement points left and the move costs 75 movement points from the road.

It looks like this is fixed too with #4626:

<img width="639" alt="Road in snow 1" src="https://user-images.githubusercontent.com/32623900/141595005-9400bc24-55d1-42fc-b6b3-89c2ec319fdc.png">
<img width="642" alt="Road in snow 2" src="https://user-images.githubusercontent.com/32623900/141595010-d422ba5d-86b6-462c-8b08-b9aa8c2af117.png">

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> Hi @LeHerosInconnu
> 
> > The hero should not be able to enter the town because he has 75 movement points left and the move costs 100 movement points from the Dirt terrain.
> 
> In fact, this hero stands not on the Dirt terrain, but on the road with penalty 75 (I suppose it's due to the paved town exit).

In fheroes2, this is not correct compared to the original game.
The square just south of the city entrance should not be a road and should not have the road penalty.
Tell me if it is preferable to open another issue for this.

In original game:

![City south of entrance 001](https://user-images.githubusercontent.com/43583994/141642491-ed47f11a-d12a-4bfe-9333-e746666a4e1d.png)

![City south of entrance 002](https://user-images.githubusercontent.com/43583994/141642495-56f9dcdc-d03b-4d7f-a359-7ef54ddd3ea9.png)

In fheroes2:

![City south of entrance 003](https://user-images.githubusercontent.com/43583994/141642510-038c0870-9ff2-4fdd-be3c-6f9c13c47175.png)

![City south of entrance 004](https://user-images.githubusercontent.com/43583994/141642516-71a4e757-850f-4de5-bba8-7755da152465.png)

> > The hero should be able to move all directions on all terrain types because he has 151 movement points left and the move costs 75 movement points from the road.
> 
> It looks like this is fixed too with #4626:
> <img alt="Road in snow 2" width="642" src="https://user-images.githubusercontent.com/32623900/141595010-d422ba5d-86b6-462c-8b08-b9aa8c2af117.png">

I can't test with the PR changes right now, but shouldn't the path be more like this:

![Path on road 01](https://user-images.githubusercontent.com/43583994/141642773-65b6c0a7-f43b-48e6-a5d9-6d4b82bc63fb.png)

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu 

> I can't test with the PR changes right now, but shouldn't the path be more like this:

Currently hero has 151 MP, so after two movements to the right he well have 1 MP, which is not enough to make a last move, so rather not :)

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> @LeHerosInconnu
> 
> > I can't test with the PR changes right now, but shouldn't the path be more like this:
> 
> Currently hero has 151 MP, so after two movements to the right along the road he well have 1 MP, which is not enough to make a last move, so rather not :)

Yes, I just noticed this (with few movement points left). :)

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu

> In fheroes2, this is not correct compared to the original game.
> The square just south of the city entrance should not be a road and should not have the road penalty.
> Tell me if it is preferable to open another issue for this.

It seemed to me that I already saw an issue about this (or at least a mention that town/castle exits are roads), but I wasn't able to find it so far. If this is wrong, then maybe it will be better to open a separate issue for this.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> @LeHerosInconnu
> 
> > In fheroes2, this is not correct compared to the original game.
> > The square just south of the city entrance should not be a road and should not have the road penalty.
> > Tell me if it is preferable to open another issue for this.
> 
> It seemed to me that I already saw an issue about this (or at least a mention that town/castle exits are roads), but I wasn't able to find it so far. If this is wrong, then maybe it will be better to open a separate issue for this.

The square where the entrance to the city is located (the active square of the city) should not be confused with the square just south of the city entrance.
Yes, I will open another issue for that.

This is what you are looking for:
Related issue: https://github.com/ihhub/fheroes2/issues/2602.
Related discussion: https://github.com/ihhub/fheroes2/discussions/2606.
