### ISSUE TITLE
Adventure map, suppression of the hero's path from the adventure map when the hero visits a location

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1988]
In the original game, the hero's path when the hero visits a location is quickly deleted from the adventure map.
In the example, in the original game, when the hero visits the Shipwreck, the hero's path is already cleared from the adventure map when the player clicks the "YES" button in the displayed window.

In fheroes2, the hero's path on the adventure map is still briefly visible when the player clicks the "OKAY" button on the Shipwreck's reward window.

In original game:

![Hero path shipwreck H2 01](https://user-images.githubusercontent.com/43583994/95895887-ae405900-0d8b-11eb-8418-acbebe1191bb.png)

In fheroes2:

![Hero path shipwreck fh2 01](https://user-images.githubusercontent.com/43583994/95895915-b5676700-0d8b-11eb-9ca5-d80fa94218d3.png)

Here are the save files:
[Hero path shipwreck fh2 01.zip](https://github.com/ihhub/fheroes2/files/5373111/Hero.path.shipwreck.fh2.01.zip)

**Edit 2020/10/14.**
Same problem when a hero attacks another hero.
In the original game, the hero's path cross disappears as soon as the hero attacks the other hero.

In fheroes2:

![Hero path hero fh2 01](https://user-images.githubusercontent.com/43583994/95983961-c0b9a180-0e22-11eb-9151-4cc8381b9a0d.png)

Attack Mandigal with Roxana.

Here is the save file:
[Hero path hero fh2 01.zip](https://github.com/ihhub/fheroes2/files/5377902/Hero.path.hero.fh2.01.zip)

**Edit 2020/10/17.**
Same problem when a hero attacks a castle.
In the original game, the hero's path cross disappears as soon as the hero attacks the castle.

In fheroes2:

![Hero path castle fh2 01](https://user-images.githubusercontent.com/43583994/96337809-fdd39d00-1089-11eb-8b10-9233fe12bc46.png)

Attack Hillstone castle with Roxana.

Here is the save file:
[Hero path castle fh2 01.zip](https://github.com/ihhub/fheroes2/files/5395706/Hero.path.castle.fh2.01.zip)

**Comment by felix642** [comment]
@LeHerosInconnu I think this issue has been fixed can you confirm ? 
[Screencast from 2022-10-16 02:02:55 PM.webm](https://user-images.githubusercontent.com/60141446/196050859-3ebe9724-b423-466f-bb85-c296e135cb83.webm)

**Comment by LeHerosInconnu** [comment]
Hello @felix642,

> @LeHerosInconnu I think this issue has been fixed can you confirm ?
[Screencast from 2022-10-16 02:02:55 PM.webm](https://user-images.githubusercontent.com/60141446/196050859-3ebe9724-b423-466f-bb85-c296e135cb83.webm)

Indeed it seems to have been corrected, and I don't know when.
Tested with version 0.9.20 5949.
Thanks for finding it. :)
I close the issue.
