### ISSUE TITLE
Hero's shadow is drawn incorrectly, while diagonal moving

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1995]
When hero moves to the left-bottom direction, we can notice, that shadow changes its shape and looks inappropriate.
![image](https://user-images.githubusercontent.com/55348946/95991148-18610880-0e35-11eb-8ee9-513c825fb31e.png)
![image](https://user-images.githubusercontent.com/55348946/95991172-20b94380-0e35-11eb-9607-081104ecf2cd.png)
![image](https://user-images.githubusercontent.com/55348946/95991192-26168e00-0e35-11eb-819b-9e473124de64.png)

**Comment by ihhub** [comment]
The amount of sprites for hero's shadow is bigger than sprites for hero. We might need to change our rendering logic for it.

**Comment by vasilenkoalexey** [comment]
Does anyone have SHADOW32 icn decoded as png or bmp? We can manually choose correct shadow index for each direction and animate index of hero.

**Comment by vasilenkoalexey** [comment]
There are hero shadow images  from 45 to 51 index
![045](https://user-images.githubusercontent.com/24250224/100518376-3f378c00-31a2-11eb-826a-405c57b03d72.png)
![046](https://user-images.githubusercontent.com/24250224/100518378-4068b900-31a2-11eb-9ddd-9c8fe8957be0.png)
![047](https://user-images.githubusercontent.com/24250224/100518379-4068b900-31a2-11eb-9cad-4674542bca98.png)
![048](https://user-images.githubusercontent.com/24250224/100518381-41014f80-31a2-11eb-99a5-711c8ea6b62a.png)
![049](https://user-images.githubusercontent.com/24250224/100518382-41014f80-31a2-11eb-8fa4-74147b28f416.png)
![050](https://user-images.githubusercontent.com/24250224/100518383-4199e600-31a2-11eb-99b9-309712c320f1.png)
![051](https://user-images.githubusercontent.com/24250224/100518403-56767980-31a2-11eb-9a3d-258d4c504214.png)

52 index
![052](https://user-images.githubusercontent.com/24250224/100518496-ec120900-31a2-11eb-8885-9bd1efeecb10.png)

So, shadows 45-51 refer to movement to the right but not to the left, and at the shadow 52 flag pointing the other way. Method `SpriteShad` should definitely have different logic

**Comment by ihhub** [comment]
Hi @vasilenkoalexey you're correct. The amount of sprites for shadows is different so the method should be changed.
