### ISSUE TITLE
The growth of ghosts after battle

### ISSUE THREAD

**Issue by shprotru** [ihhub/fheroes2#1997]
Whenever in battle amount of ghosts grows, after battle this amount is reduced to before-battle amount.

Save file: [4_mal_Blutzeit_0002.zip](https://github.com/ihhub/fheroes2/files/5378359/4_mal_Blutzeit_0002.zip)

**Comment by LeHerosInconnu** [comment]
Just for information, there is the same issue here:: https://github.com/ihhub/fheroes2/issues/1600.
