### ISSUE TITLE
Hero screen, impossible to move artifacts in hero inventory when hero screen is opened from level up window

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2004]
In fheroes2, when the hero screen is opened from the level up window with the hero button, it is not possible to move artifacts in the hero's inventory.

In fheroes2:

![Hero move artifact fh2 01](https://user-images.githubusercontent.com/43583994/96122250-81a65180-0ef1-11eb-937a-af4a7aa0f85c.png)

![Hero move artifact fh2 02](https://user-images.githubusercontent.com/43583994/96122260-83701500-0ef1-11eb-853a-67231a17bd51.png)

**Comment by Branikolog** [comment]
Also troops cannot be dismissed.

**Comment by tau3** [comment]
high-level assessment: 
`dialog_levelup.cpp#DialogSelectSecondary, line 199: ` hero dialog is intentionally opened read-only; it makes army bar and artifacts bar read only, dismiss button is hidden, also disables army spread format changing and quick info displaying.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu and @Branikolog why do even need this? Is there any logical situation when a player needs to move artifacts or monsters while leveling up?

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu and @Branikolog why do even need this? Is there any logical situation when a player needs to move artifacts or monsters while leveling up?

You have to ask yourself the question in a different way. ;)

Why prevent the user from performing these actions while in this screen?

If the user wants to perform these actions, it's because he has the opportunity to do it now.

(I discovered this flaw precisely because I wanted to take the opportunity to change the location of the artifacts without having to reopen the screen later.)

If the user can't do it, for no good reason in this case, he's going to protest against the GUI because it doesn't work as usual in this screen; and it forces him to reopen the hero's screen to perform the actions he wanted to do.

Therefore, it is preferable to let the user change the position of the artifacts, dismiss his creatures, change the formation of his troops, and so on. :)

**Comment by Branikolog** [comment]
> If the user can't do it, for no good reason in this case, he's going to protest against the GUI because it doesn't work as usual in this screen;

Completely agreed.
