### ISSUE TITLE
Combat screen, sometimes sound level of intro music of the combat is lower than sound level of music of the combat

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2009]
In fheroes2, sometimes the sound level of the intro music of the combat is lower than the sound level of the music of the combat.
This is valid for Grass, Lava, Dirt, Desert, and Snow terrain types and sometimes also for Swamp terrain.

Here are the save and test scenario files:
[Test music start combat 01.zip](https://github.com/ihhub/fheroes2/files/5386889/Test.music.start.combat.01.zip)

**Comment by Branikolog** [comment]
Actually I couldn't reproduce your bug from your savefile.
I've noticed, sometimes the sounds become lower, if there's some other application in my PC makes sounds: like browser music or other game is running. Can you check, please, again this issue?

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> Actually I couldn't reproduce your bug from your savefile.
> I've noticed, sometimes the sounds become lower, if there's some other application in my PC makes sounds: like browser music or other game is running. Can you check, please, again this issue?

I did some tests without there being any other program that uses audio.

The bug is easily reproducible.
Here are some videos that show the bug encountered:
[Test music start combat 02.zip](https://github.com/ihhub/fheroes2/files/5391931/Test.music.start.combat.02.zip)

**Comment by LeHerosInconnu** [comment]
I did some tests.
Here is the procedure to reproduce the bug.

The bug occurs when the "Music Type" is set to "External" and the "MUSIC" folder of the Gog version is not present (if the player is using the Windows English version 2.1 of Heroes 2 Gold or other version) or when the "Music Type" is set to "MIDI" or "MIDI Expansion" whether the "MUSIC" folder is present or not.

The bug occurs when the hero changes terrain type and directly attacks the enemy hero.

If the hero first moves on the same terrain where the opposing hero is positioned and the player waits for the terrain music to be played before attacking the opposing hero, then the sound level of intro music of the combat is played at its correct level.

The Wasteland and Beach/Ocean type terrains are not affected because there is no Midi music for these terrains.

In fheroes2:

Set the "Music Type" to "External" without the "MUSIC" folder, or set the "Music Type" to "MIDI" or "MIDI Expansion" with or without the "MUSIC" folder:

![Combat intro music fh2 01](https://user-images.githubusercontent.com/43583994/96371871-42cc0200-1164-11eb-9727-69d49741299e.png)

Directly attack the enemy hero:

![Combat intro music fh2 02](https://user-images.githubusercontent.com/43583994/96371880-4a8ba680-1164-11eb-9c7e-336cdb323d4d.png)

Move the hero to the same type of terrain as the opposing hero, wait for the terrain music to be played and then attack the opposing hero:

![Combat intro music fh2 03](https://user-images.githubusercontent.com/43583994/96371885-50818780-1164-11eb-9f8d-2a15f0dd8f79.png)
