### ISSUE TITLE
Combat screen, strange obstacle on the battlefield with lava type terrain

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2012]
What is this "obstacle"?
I don't remember ever seeing this type of obstacle in Heroes 2.

In fheroes2:

![Obstacle lava fh2 cercle 01](https://user-images.githubusercontent.com/43583994/96171512-5178a600-0f25-11eb-8b1e-41b17ab0418a.png)

**Comment by idshibanov** [comment]
This is one of the obstacles in the game files. They probably planned to use it in the game but never included.

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu!
Nice, that you've also noticed that strange obstacle. :)
#1075

**Comment by LeHerosInconnu** [comment]
Hello @idshibanov and @Branikolog,

Yes, I find that it is absolutely not suitable for the terrain, it seems out of place.

At the limit, if the colors were in the red tones of the lava terrain this could have been tolerable.
If they did not use this obstacle, it is certainly because it was not suitable.
I think the best is to simply remove it. :)

**Comment by Branikolog** [comment]
In future, probably, we could turn it into lava poll... But for now - I don't like it either...
