### ISSUE TITLE
Combat screen, grid, part of the hexagon in front of the entrance of the castle is not displayed

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2023]
In fheroes2, during a siege, part of the hexagon in front of the entrance to the castle is not displayed.

This part of the hexagon is briefly displayed when there is animation near the hexagon, for example when the AI captain casts the Magic Arrow spell, and during the AI's turn, and this part of the hexagon is displayed when there is a creature near this hexagon.

In fheroes2:

![Part hexagon entrance fh2 01](https://user-images.githubusercontent.com/43583994/96348102-8102ec00-10a6-11eb-9af8-c5ccb36c72ef.png)

![Part hexagon entrance fh2 02](https://user-images.githubusercontent.com/43583994/96348105-83654600-10a6-11eb-8ec7-b93b723b7798.png)

Attack Hillstone castle with Roxana.

Here is the save file:
[Hero path castle fh2 01.zip](https://github.com/ihhub/fheroes2/files/5395706/Hero.path.castle.fh2.01.zip)

**Comment by ihhub** [comment]
Fixed in #2562 .
