### ISSUE TITLE
Combat screen, Unicorn troop sprite turns around before being attacked

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2027]
In fheroes2, during combat, the Unicorn troop sprite turns around before being attacked by the Dragon troop and stays in that position while making its retaliation and performing its attack.
In the original game, in this case, the Unicorn troop does not turn around.

In fheroes2:

![vlcsnap-2020-10-17-18h08m29s356](https://user-images.githubusercontent.com/43583994/96350221-07bec580-10b5-11eb-974c-66fbc725242d.png)

![vlcsnap-2020-10-17-18h09m17s556](https://user-images.githubusercontent.com/43583994/96350223-0c837980-10b5-11eb-9b61-2600869ca891.png)

![Unicorn turns around fh2 01](https://user-images.githubusercontent.com/43583994/96350229-10af9700-10b5-11eb-8142-c8d9e3b4f6c8.png)

Attack Hillstone castle with Roxana.

Here is the save file:
[Hero path castle fh2 01.zip](https://github.com/ihhub/fheroes2/files/5395706/Hero.path.castle.fh2.01.zip)

Here is a video that show the bug encountered:
[Unicorn turns around fh2 01.zip](https://github.com/ihhub/fheroes2/files/5396233/Unicorn.turns.around.fh2.01.zip)

**Comment by idshibanov** [comment]
Root cause: In original game main hex of the large unit is its "back", in fheroes2 it is the "head".

This is how it was designed way back and to flip them around might create new bugs. Might not be trivial to fix.
