### ISSUE TITLE
Combat screen, sprite animations "jump" to a distant location on the battlefield unrelated to the troop movement

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2029]
In fheroes2, sometimes the sprite animations "jump" to a distant location on the battlefield unrelated to the troop movement.

In fheroes2:

![vlcsnap-2020-10-17-18h02m16s626](https://user-images.githubusercontent.com/43583994/96351555-63408180-10bc-11eb-830f-c0dcfc9a34ef.png)

![vlcsnap-2020-10-17-18h01m31s957](https://user-images.githubusercontent.com/43583994/96351553-5de33700-10bc-11eb-9094-579684675826.png)

Attack Hillstone castle with Roxana.

Here is the save file:
[Hero path castle fh2 01.zip](https://github.com/ihhub/fheroes2/files/5395706/Hero.path.castle.fh2.01.zip)

Here is a video that show the bug encountered:
[Sprite animations jump fh2 01.zip](https://github.com/ihhub/fheroes2/files/5396361/Sprite.animations.jump.fh2.01.zip)

**Comment by idshibanov** [comment]
This is a known issue. Combat engine is deeply flawed in fheroes2 (since sourceforge days) and has to be rewritten when it's time. Will be addressed closer to 0.9.

**Comment by LeHerosInconnu** [comment]
@idshibanov.

> This is a known issue. Combat engine is deeply flawed in fheroes2 (since sourceforge days) and has to be rewritten when it's time. Will be addressed closer to 0.9.

Okay.
Is it useful to keep save files when this happens or is it unnecessary?

**Comment by idshibanov** [comment]
> Is it useful to keep save files when this happens or is it unnecessary?

Useful. This is one of the cases where it's hard to reproduce it reliably.

**Comment by LeHerosInconnu** [comment]
@idshibanov.

> > Is it useful to keep save files when this happens or is it unnecessary?
> 
> Useful. This is one of the issues which hard to reproduce reliably.

Okay, thanks.
