### ISSUE TITLE
Combat screen, siege, position of elements

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2046]
In fheroes2, the castle entrance wall sprite is not removed when the castle entrance is destroyed.

I also suggest leaving part of the broken wall for the entrance to the castle when it's destroyed, like the other walls (https://github.com/ihhub/fheroes2/issues/2047).
And also give a "straight" perspective to the wall of the entrance to the castle (currently this wall has an "oblique" perspective).

In original game:

![Siege H2 01](https://user-images.githubusercontent.com/43583994/96596581-28716000-12ed-11eb-865a-947849725dc6.png)

![Siege H2 03](https://user-images.githubusercontent.com/43583994/96596588-2ad3ba00-12ed-11eb-8163-ffb1c37db420.png)

In fheroes2:

![Siege fh2 01](https://user-images.githubusercontent.com/43583994/96596616-33c48b80-12ed-11eb-94fc-2deb6b566d0a.png)

![Siege fh2 03](https://user-images.githubusercontent.com/43583994/96596625-3626e580-12ed-11eb-9d98-9737133cd636.png)

Open the two images in different tabs in your browser, enlarge the images and switch between the two tabs alternately.
Heroes 2 first, fheroes2 second.

![Siege H2 catapult coupé 01](https://user-images.githubusercontent.com/43583994/96596865-76866380-12ed-11eb-8e70-be8f148d8c19.png) ![Siege fh2 catapult coupé 01](https://user-images.githubusercontent.com/43583994/96596873-7be3ae00-12ed-11eb-9110-c1553905b95a.png)

![Siege H2 captain coupé 01](https://user-images.githubusercontent.com/43583994/96596889-8140f880-12ed-11eb-949e-37dab176848b.png) ![Siege fh2 captain coupé 01](https://user-images.githubusercontent.com/43583994/96596909-843be900-12ed-11eb-96f5-8ec3ef4c081e.png)

![Siege H2 turrets coupé 01](https://user-images.githubusercontent.com/43583994/96596929-89993380-12ed-11eb-9e97-6179bab584ee.png) ![Siege fh2 turrets coupé 01](https://user-images.githubusercontent.com/43583994/96596952-8e5de780-12ed-11eb-9c82-217214cafdba.png)

Here are other screenshots during siege:
[Siege screens H2 fh2 01.zip](https://github.com/ihhub/fheroes2/files/5409196/Siege.screens.H2.fh2.01.zip)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , could you please update this issue? I think I fixed everything except captain's position.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , could you please update this issue? I think I fixed everything except captain's position.

Okay, I'll look at this in the course of next week.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hello @ihhub,
> 
> > Hi @LeHerosInconnu , could you please update this issue? I think I fixed everything except captain's position.
> 
> Okay, I'll look at this in the course of next week.

fheroes2_windows_x64_SDL2 0.8.4 2626

All the elements seem to be in their correct position.
The Captain's position is also right in all the castles.

I updated the first post.

**Comment by ihhub** [comment]
Thanks @LeHerosInconnu ! Looks like only the entrance is incorrect. I'll fix that.
