### ISSUE TITLE
Can't change language

### ISSUE THREAD

**Issue by antikruk** [ihhub/fheroes2#2056]
I can not change the language on android. In the config file the language changes, but the game itself does not.

**Comment by ihhub** [comment]
Hi @antikruk we do not build or support anything on Android. What type of project are you asking about?

**Comment by antikruk** [comment]
Free heroes 2 on android from Play Market. This not a port of your project?

**Comment by ihhub** [comment]
No, it is not. We are not responsible for that port.

**Comment by antikruk** [comment]
OK, sorry. You are not planning builds for android?

**Comment by ihhub** [comment]
We're planning a release for Android but first we need to make the full game on PC first as we don't see a reason to release a half-backed product to masses :)

**Comment by antikruk** [comment]
Thanks
