### ISSUE TITLE
Scenario selection is stuck on one, started once before

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2070]
When we start game or start any scenario and return back to new game scenario list - there's always one scenario chosen as default.
On screenshots I've started new game on the map "Dead dragons".
Then I started new game and try to choose other scenario:
![image](https://user-images.githubusercontent.com/55348946/96993004-5a740380-1533-11eb-96db-8400dc9150d6.png)
![image](https://user-images.githubusercontent.com/55348946/96993105-80010d00-1533-11eb-9a31-4654bb79dd0b.png)
![image](https://user-images.githubusercontent.com/55348946/96993075-75df0e80-1533-11eb-870b-2208451350b7.png)
![image](https://user-images.githubusercontent.com/55348946/96993137-8c856580-1533-11eb-820b-dec4f9c23d29.png)
![image](https://user-images.githubusercontent.com/55348946/96993166-97d89100-1533-11eb-94d8-4afbf0e15891.png)
When I press selection button a previous scenario is chosen:
![image](https://user-images.githubusercontent.com/55348946/96993281-c0608b00-1533-11eb-9f0a-5e0ae207aed6.png)

**Comment by emotionalamoeba** [comment]
Could I take this one please?

**Comment by ihhub** [comment]
Hi @emotionalamoeba sure!

**Comment by emotionalamoeba** [comment]
![2070](https://user-images.githubusercontent.com/19264468/98464840-74f9de00-21bd-11eb-82de-e017af30e84f.gif)

This is the current state of the feature branch. The only thing is that the scenario selection is not saved to disk.

**Comment by emotionalamoeba** [comment]
![2027-2](https://user-images.githubusercontent.com/19264468/98465238-cb681c00-21bf-11eb-8f40-2d45466ab427.gif)

This is selection without entering the scenarios

**Comment by emotionalamoeba** [comment]
![2027-3](https://user-images.githubusercontent.com/19264468/98465533-73cab000-21c1-11eb-9e31-5e366669b137.gif)
