### ISSUE TITLE
Unknown monsters on a world map

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2072]
There's still can be found some Unknown "peasants" on a world map. At least they simply disappear, while being attacked by player.
![image](https://user-images.githubusercontent.com/55348946/96998088-9317db00-153b-11eb-83f5-34b76f6d9b9f.png)

[Unknown monsters.zip](https://github.com/ihhub/fheroes2/files/5429130/Unknown.monsters.zip)

**Comment by idshibanov** [comment]
Yes I fixed the battles in #2019.
Is this a new game on a map or old save?

**Comment by Branikolog** [comment]
I've started it just today.

**Comment by idshibanov** [comment]
Finally reproduced it! Bug happens when there's adjacent monsters to each other.
