### ISSUE TITLE
Meeting screen, transfer of the creatures of the hero's last troop

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2100]
In fheroes2, during the meeting of two heroes, when there is only one troop left in the army of one hero and the player selects this last troop and then clicks on the troop of the same type of creatures in the army of the other hero, the two troops are swapped in the armies of the two heroes.

In fheroes2:

![Transfert last troop fh2 01](https://user-images.githubusercontent.com/43583994/97210879-822acc00-17be-11eb-8ebc-dfeacb5a497d.png)

![Transfert last troop fh2 02](https://user-images.githubusercontent.com/43583994/97210884-83f48f80-17be-11eb-8e21-d0663cb00ec8.png)

It would be nice if in this case, all but one of the creatures in the first troop would be transferred to the army of the other hero.

In fheroes2:

![Transfert last troop fh2 01](https://user-images.githubusercontent.com/43583994/97210879-822acc00-17be-11eb-8ebc-dfeacb5a497d.png)

![Transfert last troop fh2 03](https://user-images.githubusercontent.com/43583994/97210973-a4244e80-17be-11eb-8717-0109dab0be15.png)

It should be the same when there is only one troop left from the hero's army and the player tries to transfer it to a free slot in the other hero's army.

In fheroes2:

![Transfert last troop fh2 04](https://user-images.githubusercontent.com/43583994/97211093-d170fc80-17be-11eb-95ad-534da7623421.png)

![Transfert last troop fh2 03](https://user-images.githubusercontent.com/43583994/97210973-a4244e80-17be-11eb-8717-0109dab0be15.png)

**Comment by emotionalamoeba** [comment]
Could I be assigned this please?

**Comment by emotionalamoeba** [comment]
Hi @LeHerosInconnu do you have a savegame which represents this scenario please?

**Comment by LeHerosInconnu** [comment]
Hello @emotionalamoeba,

> Hi @LeHerosInconnu do you have a savegame which represents this scenario please?

Of course, here it is. :)

Here is the test scenario file:
[Transfert last troop fh2 01.zip](https://github.com/ihhub/fheroes2/files/5440871/Transfert.last.troop.fh2.01.zip)

**Comment by emotionalamoeba** [comment]
Wow, that is a lot of heroes! Thanks :slightly_smiling_face:
