### ISSUE TITLE
UI bug while upgrading troops in a Freeman Foundry

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2101]
Missing sprite of Pikeman and background picture are missing while visiting Freeman Foundry with both Pikemen and Swordsmen in hero's army.
![image](https://user-images.githubusercontent.com/55348946/97212765-e1dea280-17d1-11eb-8bed-e922e33c2955.png)
![image](https://user-images.githubusercontent.com/55348946/97212817-f0c55500-17d1-11eb-9a15-0b9670b92e7d.png)

**Comment by emotionalamoeba** [comment]
Hi, do you have a savegame for this one?

**Comment by Branikolog** [comment]
Hi, @emotionalamoeba.
Here it is:
[Freeman Foundry.zip](https://github.com/ihhub/fheroes2/files/5451630/Freeman.Foundry.zip)

**Comment by emotionalamoeba** [comment]
Could I be assigned this one please?
