### ISSUE TITLE
Wrong arrow appears while player creates path near waterwheel

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2119]
After visiting waterwheel i tried to create path to the area near hero:
![image](https://user-images.githubusercontent.com/55348946/97432890-bc66ab80-192d-11eb-9b2c-08cbefa1f8bb.png)
[Wrong path arrow.zip](https://github.com/ihhub/fheroes2/files/5451650/Wrong.path.arrow.zip)

**Comment by Branikolog** [comment]
Path near waterwheel is also being created in different way, comparing to OG.
fheroes2:
![image](https://user-images.githubusercontent.com/55348946/97434799-9989c680-1930-11eb-8c83-e9761346c8b6.png)
OG:
![image](https://user-images.githubusercontent.com/55348946/97434767-8bd44100-1930-11eb-9306-1eb74079facf.png)

**Comment by ihhub** [comment]
Hi @idshibanov isn't it related to path finding?

**Comment by LeHerosInconnu** [comment]
Just for information, there is the same issue here: https://github.com/ihhub/fheroes2/issues/1577.
And similar issues here: https://github.com/ihhub/fheroes2/issues/1521, https://github.com/ihhub/fheroes2/issues/1951.

**Comment by idshibanov** [comment]
> 
> 
> Hi @idshibanov isn't it related to path finding?

Not necessarily to pathfinding, we just have to refactor passability rules. Example is `Tiles::UpdatePassable()` mess.

**Comment by Branikolog** [comment]
> Just for information, there is the same issue here: #1577.
> And similar issues here: #1521, #1951.

Yes, you're right! 
We have so much issues now, that I start forgetting the existing...
