### ISSUE TITLE
Boarding/unboarding animation

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2129]
When hero boards or unboards screen smoothly moves to the position centered on a hero, currently.
In the original game screen changes its focus only after/before hero appearing animation.

**Comment by ihhub** [comment]
Hi @Branikolog , how is it a bug? :)

**Comment by Branikolog** [comment]
Both variants work good, but I used to original behaviour. 
In our version disappearing of a hero and smooth changing of screen focus happen simultaneously. 
While in the original game smooth refocus occurs only after hero disappearing animation finishes while boarding.

**Comment by ihhub** [comment]
@Branikolog , this issue is an opposite of #1186 . I remember fixing that issue and explicitly adding such animation.

**Comment by ihhub** [comment]
Closing this issue as it contradicts what was requested before.

**Comment by Branikolog** [comment]
In the OG it works like:
1) Hero comes close to boat. 
2) We watch hero fading. 
3) Screen focus smoothly changes to a boat. 
In fheroes2 it works in a different manner:
1) Hero comes close to boat. 
2) We watch hero fading animation AND smooth screen focus on boat simultaneously. 

Cannot tell it's an essential difference, but I used to OG behaviour. Watching these two actions separated (note, that screen refocus happens much faster in the OG) makes a feeling of complex action being proceeded.
