### ISSUE TITLE
Boat shouldn't change its position while hero boards on it

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2130]
In the OG boat doesn't change its postition if hero boards.
In fheroes2 boat turns to the direction, hero was moving before boarding.
![image](https://user-images.githubusercontent.com/55348946/97563070-9c012480-19f3-11eb-9554-a94e7005f85a.png)
![image](https://user-images.githubusercontent.com/55348946/97563095-a28f9c00-19f3-11eb-88ab-b393bcc5eaf2.png)

**Comment by Mr1BitL8r** [comment]
Hello,

Please assign this issue to me. :)
