### ISSUE TITLE
File to Save window, use of the "Delete" key on the keyboard

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2137]
In fheroes2, when the user selects a save file from the list and move the text cursor to the left in the file name with the left arrow key and then tries to use the "Delete" key on the keyboard to delete a character to the left of the text cursor, a file deletion confirmation window is displayed instead of deleting the character.
If the user does not select a save file from the list first, the "Delete" key has no effect.

In fheroes2:

![Delete key fh2 01](https://user-images.githubusercontent.com/43583994/97726092-2d919480-1acf-11eb-9c58-7e41e4e1ad97.png)

![Delete key fh2 02](https://user-images.githubusercontent.com/43583994/97726108-2ff3ee80-1acf-11eb-8738-81c51610b2d5.png)

**Comment by Mr1BitL8r** [comment]
Hi!

Can you please assign the issue to me?

**Comment by Branikolog** [comment]
Hello, @Mr1BitL8r !
Sure! :)
