### ISSUE TITLE
Knight town and Warlock Castle icons are by 1 pixel wider than others

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#2141]
Find a Knight town in the list of castles and check its width. You can see that this icon is by 1 pixel wider than others:
![image](https://user-images.githubusercontent.com/19829520/97773164-8113e900-1b88-11eb-8faf-c04edc2facce.png)

The same applies to Warlock Castle:
![image](https://user-images.githubusercontent.com/19829520/97773208-dd770880-1b88-11eb-8090-6b83809e8738.png)

**Comment by LeHerosInconnu** [comment]
Hi @ihhub,

For your information, there is a similar issue here: https://github.com/ihhub/fheroes2/issues/1845.
