### ISSUE TITLE
Recruit windows should have evil version

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2144]
Currently we have recruit window only in "good" colors. It would be nice, if we add gray window for "evil" interface.
![image](https://user-images.githubusercontent.com/55348946/97778617-6e4de400-1b89-11eb-8aa6-2ecf0bb266d8.png)
![image](https://user-images.githubusercontent.com/55348946/97778626-7f96f080-1b89-11eb-8aec-d9a31e1513f0.png)

**Comment by Branikolog** [comment]
I'm not sure, if an info window should be done in gray colors.
![image](https://user-images.githubusercontent.com/55348946/97779207-a6efbc80-1b8d-11eb-932f-f03d060da8da.png)

**Comment by LeHerosInconnu** [comment]
Hi @Branikolog,

Just so you don't waste your time, there is a thread related to the Evil interface here: https://github.com/ihhub/fheroes2/issues/1893.

I didn't put all the screenshots in the post, and there's a downloadable file at the end of the post with other screens that should be adjusted for the Evil interface.
More screens need to be adjusted, I'll add them later. :)

**Comment by Branikolog** [comment]
@LeHerosInconnu 
Good. We should put all them together in one thread.
