### ISSUE TITLE
Animation of lighting spell in battle is incorrect

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#215]
This how it looks currently:
![viber_image_2019-10-30_04-17-54](https://user-images.githubusercontent.com/19829520/67923769-c6a27c80-fbe9-11e9-9d9a-f59d49778214.jpg)

In original game the animation is different.

**Comment by shprotru** [comment]
Is it possible catch visual frames with this animation? Would be enough catch on screenshot's, as more different - as better. If yes then would be cool to extract the chain lightning spell animation frames.
Is Lighting zigzags looks every time different?

**Comment by shprotru** [comment]
Hi @ihhub, I make a detailed [video](https://vimeo.com/431572444) of lightning bolt effect. I have a few questions about it:
1. Have we ID of lightning bolt image in AGG? I have noticed ID only from m82, that is sound of this effect.
2. Do you see how fast lightning drawing from left to right, this tells us that framerate of the game is very high. Could our engine framerate, in current state, draw with such speed?

**Comment by ihhub** [comment]
No, we don't have any special image for lighting.

The math behind lighting simulation can be found [here](https://gamedev.stackexchange.com/questions/71397/how-can-i-generate-a-lightning-bolt-effect). I might try to write a simple code for this.

**Comment by ihhub** [comment]
![image](https://user-images.githubusercontent.com/19829520/85502680-6c43a980-b61a-11ea-9236-ebe2894f0d70.png)

**Comment by shprotru** [comment]
Hi, @ihhub! Very nice! Missed this small details:
1. In OG on a half of the lightning ray you could notice that core is done with red shade.
2. The hero raises his hand before casting this spell.

**Comment by ihhub** [comment]
We will do such in other commits plus we have different lightning animation :)
