### ISSUE TITLE
Adventure map, castle info window, the castle information window should be displayed if a part of the castle is visible

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2156]
In the original game, it is possible to display the castle information window if a part of the castle has been revealed.
In fheroes2, this does not work the same way.

In original game:

![Castle info window H2 01](https://user-images.githubusercontent.com/43583994/97812864-c289be80-1c84-11eb-9ea5-53ed8b80bf4e.png)

![Castle info window H2 02](https://user-images.githubusercontent.com/43583994/97812869-c4ec1880-1c84-11eb-9cb6-4ddfad384845.png)

In fheroes2:

![Castle info window fh2 01](https://user-images.githubusercontent.com/43583994/97812881-ccabbd00-1c84-11eb-86ef-43b3868e2c1d.png)

![Castle info window fh2 02](https://user-images.githubusercontent.com/43583994/97812885-cf0e1700-1c84-11eb-8042-3c0155ce8447.png)

**Comment by Branikolog** [comment]
Hello, @LeHerosInconnu !
On the screenshots revealed parts of castle are different.
Are you sure, that issue is actual within the same conditions?

**Comment by LeHerosInconnu** [comment]
Hi @Branikolog,

> Hello, @LeHerosInconnu !
> On the screenshots revealed parts of castle are different.
> Are you sure, that issue is actual within the same conditions?

Even if a larger part of the castle is revealed, it doesn't work like in the original game either.

In fheroes2:

![Castle info window fh2 03](https://user-images.githubusercontent.com/43583994/97814796-282c7980-1c8a-11eb-8fb8-e01156699f98.png)

Here is the save file:
[Castle info 01.zip](https://github.com/ihhub/fheroes2/files/5471697/Castle.info.01.zip)

**Comment by Branikolog** [comment]
Yes, original behaviour is not obvious:
While right click on a squares behind a castle we can see a castle info. While in fheroes2 we can see castle's statistics only over the cells, where a castle is located.

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

> Yes, original behaviour is not obvious:
> While right click on a squares behind a castle we can see a castle info. While in fheroes2 we can see castle's statistics only over the cells, where a castle is located.

In the original game, all the squares where part of the castle/town sprite is located (except the squares of the castle shadow) allow the player to display the castle/town information window with a right click.

In the editor, these squares are brown for the bottom of the castle/town sprite, the square at the entrance of the castle/town is orange, and the squares at the top of the castle/town sprite are green.
During the game, all these squares (brown, orange and green) can be used to display the information window of the castle/town with a right click.

In the editor, the black squares represent the shadow of the castle/town.
During the game, these squares (black) cannot be used to display the castle/town information window with a right click.

In original game:

![Castle info right 01](https://user-images.githubusercontent.com/43583994/98443246-6e5e5e80-210a-11eb-8885-1cd148bda9f5.png)

![Castle info right 02](https://user-images.githubusercontent.com/43583994/98443249-70282200-210a-11eb-9d2c-ba566cbd086c.png)

![Castle info right 03](https://user-images.githubusercontent.com/43583994/98443250-71594f00-210a-11eb-8502-2a552f55aca4.png)

**Comment by ihhub** [comment]
The issue was fixed some time ago.
