### ISSUE TITLE
Building animation of tavern in Barbarian Town is not solid

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2157]
While appearing, part of a roof is more transparent, than the wole building.
![image](https://user-images.githubusercontent.com/55348946/97813204-93c91380-1c97-11eb-9fa9-bc5fd6222f4d.png)

**Comment by ihhub** [comment]
It's a limitation of alpha blitting algorithm. Most likely we won't fix it.

**Comment by ihhub** [comment]
This issue is not reproducible anymore:
![image](https://user-images.githubusercontent.com/19829520/112864749-b3e7ec00-90ea-11eb-914f-6daa5ef3d305.png)
