### ISSUE TITLE
Adventure map, Hero, revealed area

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2159]
In fheroes2, the area revealed by the hero is reduced compared to the original game.

In original game:

![Hero revealed area H2 01](https://user-images.githubusercontent.com/43583994/97813418-6c1e7f00-1c88-11eb-8cf5-13d4c41985ae.png)

In fheroes2:

![Magic Garden not captured 01](https://user-images.githubusercontent.com/43583994/97812963-552a5d80-1c85-11eb-8f98-e2ccf7601a16.png)

Similar issue: https://github.com/ihhub/fheroes2/issues/1434.

**Comment by vincent-grosbois** [comment]
If I understand, it's said in #1434 that it is intentional ?

**Comment by LeHerosInconnu** [comment]
Hello @vincent-grosbois,

> If I understand, it's said in #1434 that it is intentional ?

Yes, this was done intentionally in fheroes2.
Here is another case to show that this different mode of operation from the original game causes annoying problems for the player by diminishing the visibility of the original game. :)

**Comment by vincent-grosbois** [comment]
Ok I see
In that case, what do we do with this ? this is marked as 0.9 , but I'm not sure I can do anything for this issue

**Comment by LeHerosInconnu** [comment]
@vincent-grosbois.

> Ok I see
> In that case, what do we do with this ? this is marked as 0.9 , but I'm not sure I can do anything for this issue

A discussion would be planned for this.
For the time being, it would be necessary to know if this is considered urgent.
So, @ihhub and @Branikolog is this urgent?

For my part, I vote for an operation as in the original game.
Every square that is uncovered counts and this may change the strategy to be adopted. :)

**Comment by Branikolog** [comment]
Hello, @vincent-grosbois  and @LeHerosInconnu !
The nearest release is AI/logic oriented. I believe, we can postpone this issue a little bit, so we can more deeply discuss here the problem and the solition.)
But the last word is for @ihhub, surely. :)

On subject:
I really don't understand, why do we have such hexagon-like shape of area. Why couldn't we make it more round-shaped? Can we make a compromise solution between these two variants? Just by adding a small revealed area in this places....
![97812963-552a5d80-1c85-11eb-8f98-e2ccf7601a16](https://user-images.githubusercontent.com/55348946/105886541-94194680-601b-11eb-9119-717ea55e2e35.png)

**Comment by LeHerosInconnu** [comment]
Heroes 2 players are used to it working this way:

![Hero revealed area H2 01](https://user-images.githubusercontent.com/43583994/97813418-6c1e7f00-1c88-11eb-8cf5-13d4c41985ae.png)

Why change that?
Not to mention all the scenarios created with the game's original mode of operation.

**Comment by ihhub** [comment]
Reveal area should be the same as in the original game as it's closer to circle shape and old maps depend on this shape. This is the method `void Maps::ClearFog( s32 index, int scoute, int color )` which should be modified.

**Comment by a1exsh** [comment]
Seems like this is already fixed in the latest `HEAD`:

OG:
![image](https://user-images.githubusercontent.com/489601/135761163-48029014-22ef-484e-9557-4a3b2142033b.png)

fheroes2:
![image](https://user-images.githubusercontent.com/489601/135761164-e041c27b-f13b-427b-ad8d-80695c84cc46.png)

**Comment by felix642** [comment]
@ihhub, as mentioned by @a1exsh, I think we can close this issue.

Unless there is something else to do?

**Comment by ihhub** [comment]
Closing this issue as being fixed.

@felix642 , thank you so spotting this!
