### ISSUE TITLE
Phoenix movement animation is shifted during battle

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#216]
Start a battle with Phoenix and notice that animation of the creature is shifted:
![viber_image_2019-10-29_22-20-45](https://user-images.githubusercontent.com/19829520/67928602-5e0dcc80-fbf6-11e9-95b4-13324c6d96c6.jpg)
![viber_image_2019-10-29_22-20-48](https://user-images.githubusercontent.com/19829520/67928610-649c4400-fbf6-11e9-93a2-16065e2f60d0.jpg)
![viber_image_2019-10-29_22-20-51](https://user-images.githubusercontent.com/19829520/67928623-6b2abb80-fbf6-11e9-9967-70b2e41ec6bd.jpg)

**Comment by idshibanov** [comment]
@ihhub I might take a look at this one as a part of #440. I think I know the line.
