### ISSUE TITLE
Adventure map, rounded Stone Liths don't work

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2168]
Use the rounded Stone Liths several times with Sir Gallant.

In fheroes2:

![Rounded stone liths fh2 01](https://user-images.githubusercontent.com/43583994/98260669-e1899880-1f83-11eb-8d94-c2f507280fcf.png)

Here is the save file:
[Stone liths dont work 01.zip](https://github.com/ihhub/fheroes2/files/5495299/Stone.liths.dont.work.01.zip)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu I tested it on latest build with a new game. It works totally find. Could you please check it again with 0.8.3 release?

**Comment by LeHerosInconnu** [comment]
@ihhub.

> Hi @LeHerosInconnu I tested it on latest build with a new game. It works totally find. Could you please check it again with 0.8.3 release?

I did some tests with fheroes2 0.8.3 2176 and a new game, and it seems to be working fine.

**Comment by LeHerosInconnu** [comment]
I had this bug again with two types of Stone Liths (rounded shape and shape with the two triangles) with fheroes2 0.8.3 2268 and a new game.

I don't have a save file from fheroes2 0.8.3 2268 with the reproducible bug yet.

But the bug is reproducible with the save file of the first post.

Here is a video that show the bug encountered:
[Stone Liths don't work.zip](https://github.com/ihhub/fheroes2/files/5642799/Stone.Liths.don.t.work.zip)
