### ISSUE TITLE
Mage guild shows incorrect level by mouse clicking on the building

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#217]
Right mouse click on mage build to bring information window and check level of the guild:
![viber_image_2019-10-29_22-22-28](https://user-images.githubusercontent.com/19829520/67928701-a200d180-fbf6-11e9-89ff-f94436f7118e.jpg)

Please notice that correct level is shown at the bottom bar of castle options.

**Comment by andrey-starodubtsev** [comment]
1. Not actually a bug, this message is shown if you click on the first floor of the building. If you click on the second floor, message with correct level is shown:

![Screenshot from 2019-11-21 12-14-04](https://user-images.githubusercontent.com/7666511/69323941-a69a3200-0c58-11ea-947c-d3853e85b006.png)

2. Original game doesn't show guild level at all:

![Screenshot from 2019-11-21 12-17-14](https://user-images.githubusercontent.com/7666511/69324120-ef51eb00-0c58-11ea-872d-ee0d68c7ec59.png)

**Comment by ihhub** [comment]
Initially I though the same way but later I realized that we somehow confuse player. We show highest Mage Guild level at the bottom bar of screen but in window we display different information. Moreover for all dwelling buildings we display information without segregation between upgraded and not upgraded.
