### ISSUE TITLE
Adventure map, unable to disembark on Coast

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2171]
In fheroes2, the hero cannot disembark at places considered "Coast".

In fheroes2:

![unable to disembark 02](https://user-images.githubusercontent.com/43583994/98273732-de49d900-1f92-11eb-9873-ea29763b566f.png)

![unable to disembark 03](https://user-images.githubusercontent.com/43583994/98273746-e0139c80-1f92-11eb-9816-1e8e4f9fd160.png)

![unable to disembark 04](https://user-images.githubusercontent.com/43583994/98273748-e144c980-1f92-11eb-88f9-05e09b08166a.png)

![unable to disembark 05](https://user-images.githubusercontent.com/43583994/98273754-e30e8d00-1f92-11eb-9727-b71bd93f72f9.png)

![unable to disembark 06](https://user-images.githubusercontent.com/43583994/98274242-7647c280-1f93-11eb-8caa-d718bd3a2e22.png)

![unable to disembark 07](https://user-images.githubusercontent.com/43583994/98274248-78aa1c80-1f93-11eb-86f3-464ac952121e.png)

Here is the save file:
[Unable to disembark 01.zip](https://github.com/ihhub/fheroes2/files/5495901/Unable.to.disembark.01.zip)

**Comment by Branikolog** [comment]
Hello, @LeHerosInconnu !
Could you check once again or explain me, if I'm wrong.
It seems to me, that hero cannot disembark only on a cells on a beach, that suppose diagonal movement.
For example:
![image](https://user-images.githubusercontent.com/55348946/98441578-52f65200-2110-11eb-92d6-2e1af83395e6.png)
On this screenshot hero can disembark on a target cell, but on the right to it he cannot.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> It seems to me, that hero cannot disembark only on a cells on a beach, that suppose diagonal movement.

Yes, that's correct, that's what we can notice.
