### ISSUE TITLE
Adventure map, problem with the Summon Boat spell

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2172]
When the hero casts the "Summon Boat" spell, the brought boat is not always positioned at a location accessible by the hero despite the fact that there are other accessible squares where to position the boat.
This flaw is also present in the original game.

In fheroes2, it would be nice to make sure that when the spell is used, the boat is always positioned in a square directly accessible to the hero whatever the position of the hero.

In fheroes2:

![Problem embark summon boat 02](https://user-images.githubusercontent.com/43583994/98276798-ca07db00-1f96-11eb-90f9-a49086e0074b.png)

![Problem embark summon boat 03](https://user-images.githubusercontent.com/43583994/98276804-cc6a3500-1f96-11eb-8d05-8ea8ecff24c3.png)

Make the hero Ector cast the Summon Boat spell.
Here is the save file:
[Problem embark summon boat 01.zip](https://github.com/ihhub/fheroes2/files/5496045/Problem.embark.summon.boat.01.zip)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu could you please test all Summon Boat related issue on a new game without using the old save because as I remember our changes only are applicable for new save file format.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu could you please test all Summon Boat related issue on a new game without using the old save because as I remember our changes only are applicable for new save file format.

Okay, I'll look at that later this week.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu thank you for your testing! Could you please provide a map, not a save for these issues? I'll take a look at all of them.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu thank you for your testing! Could you please provide a map, not a save for these issues? I'll take a look at all of them.

Sure.

Here is the test scenario file:
[Summon boat test 0 9974a.zip](https://github.com/ihhub/fheroes2/files/5719253/Summon.boat.test.0.9974a.zip)

**Comment by ihhub** [comment]
Thank you very much!
