### ISSUE TITLE
Adventure map, boat's sprite changes its orientation when a hero gets on board

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2173]
In fheroes2, the boat's sprite changes its orientation when a hero gets on board.

In fheroes2:

![Boat orientation fh2 01](https://user-images.githubusercontent.com/43583994/98278151-7b5b4080-1f98-11eb-9d9f-259f84bac6de.png)

![Boat orientation fh2 02](https://user-images.githubusercontent.com/43583994/98278156-7d250400-1f98-11eb-8934-06e87f64c82b.png)

End the turn.
The AI hero gets on board.
Here is the save file:
[Boat orientation 01.zip](https://github.com/ihhub/fheroes2/files/5496101/Boat.orientation.01.zip)

Related issue: https://github.com/ihhub/fheroes2/issues/2130.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , did you create this save before or after 0.8.3? If before then it's an expected behavior as boat doesn't change its direction only for new saves.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , did you create this save before or after 0.8.3? If before then it's an expected behavior as boat doesn't change its direction only for new saves.

The save file comes from a game started with the latest version of the moment fheroes2 0.8.2 2108 and which had be continued with the version fheroes2 0.8.2 2165.

With version fheroes2 0.8.3 2163 and a new game, the bug still occurs with an AI hero, but apparently this has been fixed now with the last changes made.

**Comment by LeHerosInconnu** [comment]
This problem is still present (fheroes2.exe 0.8.3 2430).

In fheroes2:

![Boat changed after hero embarks fh2 01](https://user-images.githubusercontent.com/43583994/102687485-aec3f880-41ef-11eb-84b1-98dbbee21166.png)
