### ISSUE TITLE
Adventure map, boat's sprite disappears from the adventure map after using the Summon Boat spell

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2174]
In fheroes2, the boat's sprite disappears from the adventure map after using the Summon Boat spell.

In fheroes2:

![Boat disappears fh2 01](https://user-images.githubusercontent.com/43583994/98280743-215c7a00-1f9c-11eb-8be7-9f5afe95104b.png)

Here is the save file and a video of the bug:
[Boat disappears fh2 01.zip](https://github.com/ihhub/fheroes2/files/5496199/Boat.disappears.fh2.01.zip)

Related issue: https://github.com/ihhub/fheroes2/issues/2126.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu could you please verify all boat related issues for a new save after 0.8.3 release? If these issues can't be replicated then please close them as the can't fix old saves due to a wrong save format.

**Comment by LeHerosInconnu** [comment]
@ihhub.

> Hi @LeHerosInconnu could you please verify all boat related issues for a new save after 0.8.3 release? If these issues can't be replicated then please close them as the can't fix old saves due to a wrong save format.

This bug is still present when the hero is positioned at the location in the example and the boat is summoned near the windmill.

In fheroes2:

![Boat disappears fh2 10](https://user-images.githubusercontent.com/43583994/98407871-ab761280-2070-11eb-9d16-39889a70dcdc.png)

Here is the test scenario file:
[Boat disappears fh2 10.zip](https://github.com/ihhub/fheroes2/files/5503152/Boat.disappears.fh2.10.zip)

**Comment by Branikolog** [comment]
Could reproduce it exactly near windmill... Boat should appear over the shadow of Windmill.
Interesting.... While appearing over other shadows boat disappears too.
Nevertheless, hero can board on it and then boat appears.
