### ISSUE TITLE
Adventure map, hero's shadow is displayed over the boat's sprite

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2179]
In fheroes2, the hero's shadow is displayed over the boat's sprite.

In fheroes2:

![Summon Boat orientation fh2 02](https://user-images.githubusercontent.com/43583994/98405815-38b76800-206d-11eb-992b-9d04a75463c4.png)

**Comment by Branikolog** [comment]
I'm 100% sure, this issue is the same to #1004. Current hero shadow is displayed wrong over ton of objects.
