### ISSUE TITLE
Stables: wrong passability of an object

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2188]
There's only one cell for visiting stables in the original game. Also hero cannot move through it.
OG:
![image](https://user-images.githubusercontent.com/55348946/98461168-09af0c80-21bb-11eb-924c-cd0d2f83334d.png)
![image](https://user-images.githubusercontent.com/55348946/98461216-6e6a6700-21bb-11eb-83c3-247a8871c128.png)
![image](https://user-images.githubusercontent.com/55348946/98461220-79bd9280-21bb-11eb-8756-52a92a958242.png)
fheroes2:
![image](https://user-images.githubusercontent.com/55348946/98461221-8510be00-21bb-11eb-8fd6-ac3033e12dc1.png)
![image](https://user-images.githubusercontent.com/55348946/98461231-935eda00-21bb-11eb-8d8e-a9738ba156e5.png)
![image](https://user-images.githubusercontent.com/55348946/98461236-a1145f80-21bb-11eb-80b4-cc3adb59060e.png)
![image](https://user-images.githubusercontent.com/55348946/98461244-ad002180-21bb-11eb-968e-c920d04cc6d3.png)

**Comment by Mr1BitL8r** [comment]
Hi and thanks once more for the finding! :)

Please assign the issue to me.

**Comment by Mr1BitL8r** [comment]
Wow, thanks! 
I spend a lot of time searching for the right place to set the passability but you found it and solved the mystery. :)

**Comment by Eldorias-Piano-Covers** [comment]
I juste saw this bug on 0.9.15, IA just move through the stables, from left top to left bottom. And my hero can pass too.
![image](https://user-images.githubusercontent.com/104630245/169837135-0c03604e-4f0b-475c-8345-21cfec548601.png)

**Comment by ihhub** [comment]
Hi @Eldorias-Piano-Covers , are you using a save created by 0.9.15 engine version or older?

**Comment by Eldorias-Piano-Covers** [comment]
Hi, Its on the POL main campaign, which I started on may the 18th, so 95% sure it is 0.9.15, 5% chance started with 0.9.14. Any way to check initial version on savegame file ?

**Comment by Eldorias-Piano-Covers** [comment]
Yes, here it is (left bottom size, with 1st hero Sarakin)
[stablesbug.zip](https://github.com/ihhub/fheroes2/files/8773051/stablesbug.zip)
:
