### ISSUE TITLE
While AI using whirlpool screen shouldn't be focused on a destination point, hidden in a fog

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2189]
After AI enters whirlpool we can see the place, hidden in a fog, where he came out.
![image](https://user-images.githubusercontent.com/55348946/98461686-54cb1e80-21bf-11eb-8d02-e90f6fb0de12.png)
![image](https://user-images.githubusercontent.com/55348946/98461712-8a700780-21bf-11eb-82f9-98126a32e370.png)

**Comment by ihhub** [comment]
Hi @idshibanov , would you mind to take a look here? I think the issue is with not checking destination point for human player visibility.
