### ISSUE TITLE
Combat screen, siege, the surrender button of the defending hero must always be accessible

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2191]
During a siege, the surrender button of the defending hero must always be accessible.
In fheroes2 this is not the case.

In original game:

![Retreat siege H2 01](https://user-images.githubusercontent.com/43583994/98466030-3bc96a00-21cd-11eb-8118-98a32b01d354.png)

![Retreat siege H2 02](https://user-images.githubusercontent.com/43583994/98466032-3e2bc400-21cd-11eb-8a41-bf46e0ba82ea.png)

![Retreat siege H2 03](https://user-images.githubusercontent.com/43583994/98466034-3ff58780-21cd-11eb-9d10-0c964d270025.png)

In fheroes2:

![Retreat siege fh2 01](https://user-images.githubusercontent.com/43583994/98466040-48e65900-21cd-11eb-9921-4de6f0a43ca4.png)

**Edit 2020/12/23.**

Related issue: https://github.com/ihhub/fheroes2/issues/2460.

**Comment by grasshopper-newt** [comment]
I am unable to replicate this issue. The surrender button always seems to be accessible during siege. Can you confirm this bug still exists?

**Comment by LeHerosInconnu** [comment]
Hello @grasshopper-newt,

> I am unable to replicate this issue. The surrender button always seems to be accessible during siege. Can you confirm this bug still exists?

The surrender button is accessible, but the intermediate window showing the amount of gold to be paid is not displayed when the player does not have enough gold to pay the requested amount of gold.

In original game:

![Retreat siege H2 02](https://user-images.githubusercontent.com/43583994/98466032-3e2bc400-21cd-11eb-8a41-bf46e0ba82ea.png)

In fheroes2:

![Surrender siege fh2 10](https://user-images.githubusercontent.com/43583994/102976591-15078e80-4502-11eb-820b-27d3462cc644.png)

![Surrender siege fh2 11](https://user-images.githubusercontent.com/43583994/102976601-189b1580-4502-11eb-8f14-d12bcb6e3b3a.png)

**Comment by grasshopper-newt** [comment]
Ah yes, thanks for the clarification. I will try tackling this bug.

**Comment by LeHerosInconnu** [comment]
@grasshopper-newt.

There is also another issue related to this window https://github.com/ihhub/fheroes2/issues/2460.
