### ISSUE TITLE
Combat screen, siege, the troop of Cavalries cannot enter in the castle

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2192]
In fheroes2, during a siege, the troop of Cavalries cannot enter in the castle.

By selecting the hexagon just in front of the entrance of the castle inside the castle walls as destination, the troop of Cavalries does not enter in the castle and positions itself in the moat next to the entrance of the castle.

In fheroes2:

![Cavalries no enter castle fh2 01](https://user-images.githubusercontent.com/43583994/98467869-0aa26700-21d8-11eb-8a4a-028d11a7ffac.png)

![Cavalries no enter castle fh2 02](https://user-images.githubusercontent.com/43583994/98467871-0d04c100-21d8-11eb-864f-94790b3b9d4d.png)

End the turn.
Here is the save file and a video that show the bug encountered:
[Cavalries no enter castle fh2 01.zip](https://github.com/ihhub/fheroes2/files/5506511/Cavalries.no.enter.castle.fh2.01.zip)

**Edit 2021/02/05.**

The troop of Cavalries cannot enter the castle at all (fheroes2.exe 0.9.0 2693).

In fheroes2:

![Castle outside no go inside fh2 01](https://user-images.githubusercontent.com/43583994/107067648-df7fe180-67df-11eb-8c53-5115b7409401.png)

**Comment by Branikolog** [comment]
@LeHerosInconnu 
Dev team knows this issue.
I hope, they can fix it as soon as possible.;)

**Comment by Branikolog** [comment]
The issue was fixed some time ago.
