### ISSUE TITLE
Combat screen, siege, the troop of Cavalries teleports itself into the castle

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2193]
In fheroes2, during a siege, the troop of Cavalries teleports itself into the castle.

In fheroes2:

![Cavalries teleport castle fh2 01](https://user-images.githubusercontent.com/43583994/98468306-3292ca00-21da-11eb-91cd-d88d049f53b4.png)

![Cavalries teleport castle fh2 02](https://user-images.githubusercontent.com/43583994/98468310-358dba80-21da-11eb-9462-0d0146041381.png)

End the turn.
Here is the save file and a video that show the bug encountered:
[Cavalries teleport castle fh2 01.zip](https://github.com/ihhub/fheroes2/files/5506532/Cavalries.teleport.castle.fh2.01.zip)

**Comment by Branikolog** [comment]
Him @LeHerosInconnu 
Recently, @ihhub made a huge improvement for pathfinding during battle.
I think this issue is not actual anymore.
Could you, please, check it once again?

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

> Him @LeHerosInconnu
> Recently, @ihhub made a huge improvement for pathfinding during battle.
> I think this issue is not actual anymore.
> Could you, please, check it once again?

This bug seems to have been fixed, but another one has appeared: https://github.com/ihhub/fheroes2/issues/2192.

> **Edit 2021/02/05.**
> 
> The troop of Cavalries cannot enter the castle at all (fheroes2.exe 0.9.0 2693).
> 
> In fheroes2:
> 
> ![Castle outside no go inside fh2 01](https://user-images.githubusercontent.com/43583994/107067648-df7fe180-67df-11eb-8c53-5115b7409401.png)

**Comment by Branikolog** [comment]
Closing the issue as it cannot be reproduced anymore.
