### ISSUE TITLE
Adventure map, penalty information window of the terrain adjacent to the hero, wrong information for the road

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2197]
In fheroes2, information about penalties of the terrain adjacent to the hero has been added.

When the adjacent square contains a road (penalty 75%), the penalty is taken into account and displayed, but it is not indicated that it is a road, and it is the name of the terrain where the road is located that is displayed.

In the example:
"Snow
penalty: 75".

Instead of:
"Road
penalty: 75".

In fheroes2:

![Snow penalty 75 01](https://user-images.githubusercontent.com/43583994/98551166-4b17e880-229d-11eb-836b-20137b1bb50f.png)

Also this feature should be extended to all the squares of the adventure map and not only to the squares adjacent to the heroes.
And the Pathfinding skill of the hero should be taken into account to indicate the terrain penalty according to the selected hero.
When there is no hero selected, the standard terrain penalty is displayed.
This feature can also be an option.

I will add an issue for this proposal. (https://github.com/ihhub/fheroes2/issues/2198)

**Comment by Branikolog** [comment]
Also, I've noticed, that penalty for diagonal movement and straight up and down are the same.

**Comment by LeHerosInconnu** [comment]
Hi @Branikolog,

> Also, I've noticed, that penalty for diagonal movement and straight up and down are the same.

This is normal. It's the penalty of the **terrain** that is displayed; this penalty will be taken into account when the hero will be positioned on this square.

The current movement penalty of the hero is located in the square where the hero is currently positioned (it is not currently displayed in the hero information window with a right click).

In the example, the hero is located on the Snow terrain.
The Snow square therefore gives a penalty of 175% (175 movement points) and the hero will therefore lose 175 movement points to leave the square with a vertical and horizontal movement and 262 movement points (+50% rounded) to leave the square moving diagonally, unless it is the last movement, in which case he will be able to move in all directions if he has at least 175 movement points left (penalty of the square where the hero is located taken into account).

**Comment by Branikolog** [comment]
@LeHerosInconnu 
It is a bit confusing, when I see penalty on horizontal/vertical movement the same as diagonal. But when I make horizontal/vertical movements and and then diagonal, my hero wastes different amount of movement points... I mean, +50% for diagonal movement is not so obvious...
How do you think, can we change that "penalty description" to "movement meter"? So player would see, how many movement points he would spend to reach the destination point.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> @LeHerosInconnu
> It is a bit confusing, when I see penalty on horizontal/vertical movement the same as diagonal. But when I make horizontal/vertical movements and and then diagonal, my hero wastes different amount of movement points... I mean, +50% for diagonal movement is not so obvious...
> How do you think, can we change that "penalty description" to "movement meter"? So player would see, how many movement points he would spend to reach the destination point.

Currently, for moving the hero on a square, the length of the arrows of the hero's path gives an indication of the cost of moving (very short arrows on a Road, very long arrows on Desert terrain).

To indicate the cost of movement on a square far from the hero with a right click would be complicated because it is the square where the hero is located that is taken into account for the cost of movement (with the predefined path this initial square is known so the length of the arrow can be adapted accordingly).

To know the current cost of the hero's movement from the square where he is located, it would be necessary to indicate this in the hero information window displayed with a right click.
It can also be indicated with a right click on an adjacent square (but only for those squares) with additional information:

For an horizontal and vertical movement:

"Road

terrain penalty: 75
hero's movement penalty (Snow): 175"


For a diagonal movement (except if it's the last move of the hero, in this case only 175 movement points):

"Road

terrain penalty: 75
hero's movement penalty (Snow): 262"
