### ISSUE TITLE
Expert scouting reveals number of creatures

### ISSUE THREAD

**Issue by Killbrum** [ihhub/fheroes2#2205]
Expert scouting reveals a number of creatures. Basically, I cannot recall that OG returns the exact amount of creatures if you have expert scouting. Is it correct behavior? See Game::CountScoute(...)

**Comment by LeHerosInconnu** [comment]
Hello @Killbrum,

> Expert scouting reveals a number of creatures. Basically, I cannot recall that OG returns the exact amount of creatures if you have expert scouting. Is it correct behavior? See Game::CountScoute(...)

In fheroes2, there is an option "world: scouting skill show extended content info" which gives additional information.
Is this option enabled in the Experimental Game Settings window?

In fheroes2:

![Scouting setting fh2 01](https://user-images.githubusercontent.com/43583994/98676839-6c8bd980-235c-11eb-8468-ee1e33fa6ba6.png)

**Comment by Killbrum** [comment]
I see, thank you for explanation
