### ISSUE TITLE
A creature blinded by Unicorn, with triggered moral is still able to attack

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#221]
Start a battle with Unicorns and make sure that you attack one of them. Wait for a situation when your attacking unit would be blinded by Unicorn and your turn receives another movement by triggering moral. The creature should not receive any extra turn after Blind spell:
![unicorn_1](https://user-images.githubusercontent.com/19829520/68067795-6b0df580-fd87-11e9-8722-e574e92a0efa.jpg)
![unicorn_2](https://user-images.githubusercontent.com/19829520/68067798-706b4000-fd87-11e9-966b-9c9d212f0e3e.jpg)

**Comment by idshibanov** [comment]
This was present because morale was computed at the start of the round. Fixed in #465
