### ISSUE TITLE
Scenario, scenario settings are not respected for troops at the beginning of the scenario compared to the scenario editor

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2212]
In fheroes2, the troops indicated in the scenario editor are not respected for the second player in single and multiplayer mode.

In original game:

![Troop setting fh2 01](https://user-images.githubusercontent.com/43583994/98947101-14d4a600-24f5-11eb-8cf4-25363c45c54d.png)

![Troop setting fh2 02](https://user-images.githubusercontent.com/43583994/98947122-1b631d80-24f5-11eb-894b-099ee683a428.png)

In fheroes2:

![Troop setting fh2 03](https://user-images.githubusercontent.com/43583994/98947140-20c06800-24f5-11eb-95bb-ac4d3f076a33.png)

Here are the test scenario file and the save file:
[Troop setting fh2 01.zip](https://github.com/ihhub/fheroes2/files/5530916/Troop.setting.fh2.01.zip)

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu !
What is the difference of your issue with #1829?

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

> Hi, @LeHerosInconnu !
> What is the difference of your issue with #1829?

Effectively, it's the same problem. Thanks.
