### ISSUE TITLE
Combat screen, hexagons where the Unicorn troop should be able to move are not grayed out (and the Unicorn troop cannot move 5 hexagons as it should)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2235]
The hexagons where the Unicorn troop should be able to move are not grayed out and the Unicorn troop cannot move 5 hexagons as it should.
In the example, the Unicorn troop should be able to attack the Veteran Pikemen and the Master Swordsmen.

In fheroes2:

![Unicorns should attack](https://user-images.githubusercontent.com/43583994/99401804-e554dd80-28e8-11eb-984a-cbf891cff53a.png)

Related issues: https://github.com/ihhub/fheroes2/issues/1778, https://github.com/ihhub/fheroes2/issues/719.

**Comment by Branikolog** [comment]
Hello, @LeHerosInconnu !
This issue seems to be completely the same to the both, you've mentioned before. 
Are you sure, we need one more thread for this issue?
P.S. This problem seems to occur, when 2-hex creature start moving and it turns around while movement: in this case game counts, that creature walks one more hex (the back one) that's why unicorn , while moving backwards, cannot reach necessary hex.

**Comment by LeHerosInconnu** [comment]
Hi @Branikolog,

> Hello, @LeHerosInconnu !
> This issue seems to be completely the same to the both, you've mentioned before.
> Are you sure, we need one more thread for this issue?
> P.S. This problem seems to occur, when 2-hex creature start moving and it turns around while movement: in this case game counts, that creature walks one more hex (the back one) that's why unicorn , while moving backwards, cannot reach necessary hex.

The difference comes from the ungrayed movement hexagons, clearly only 4 moves in this issue.
If you think that this is the same problem, you can close this issue.

**Comment by Branikolog** [comment]
> The difference comes from the ungrayed movement hexagons, clearly only 4 moves in this issue.

The same is for the mentioned issues: creature spends one movement hex while turning... I can be wrong about the reasons, but all this issues are 100% in the same code.
