### ISSUE TITLE
Combat screen, dragon fire behind enemy

### ISSUE THREAD

**Issue by vasilenkoalexey** [ihhub/fheroes2#2236]
Dragon fire painted behind enemy while attack directly from left

In fheroes2:

![1](https://user-images.githubusercontent.com/24250224/99406042-800be700-28fe-11eb-886d-974113cfb544.png)

**Comment by Branikolog** [comment]
Hi, @vasilenkoalexey !
This issue is already exists. :) #1296

**Comment by vasilenkoalexey** [comment]
> This issue is already exists. :) #1296

Hi! Looks like you're right, i think issue can be closed as duplicate.

**Comment by Branikolog** [comment]
Okay! 
Anyway, this issue is not so obvious. Nice, that you've noticed it!
