### ISSUE TITLE
"Town portal" spell window should have evil UI elements

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2240]
Buttons, scroll bar and list background in evil interface are the same as for good interface.
![image](https://user-images.githubusercontent.com/55348946/99527222-82794a00-29ad-11eb-9384-f685ebabdcd6.png)

**Comment by ihhub** [comment]
I'm not sure about the background but buttons are definitely doable.

**Comment by Branikolog** [comment]
@ihhub 
Can we make background in grayscale?
