### ISSUE TITLE
Wrong numbers' font for campaign selection window

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2241]
In the campaign selection window the numbers near missions have wrong font:
OG:
![image](https://user-images.githubusercontent.com/55348946/99533341-c3299100-29b6-11eb-8fbc-cf2e787cf2f5.png)
fheroes2:
![image](https://user-images.githubusercontent.com/55348946/99533358-cd4b8f80-29b6-11eb-98de-2a0de523ef0e.png)

**Comment by LeHerosInconnu** [comment]
Just by looking at the screen, and without taking into account the position of the elements, neither the quotation marks added to the name of the scenario, nor the word "None" added for the Awards, the graphics of the buttons other than for the first scenario are not the right ones, the arrows between the buttons are missing, and the tree structure of the campaign is not the same from the sixth scenario on.

**Comment by ihhub** [comment]
Yes, you're both right :)

This window has a lot of missing and incorrect elements. Also I couldn't find some assets like arrows in demo version of the game.

**Comment by Branikolog** [comment]
> Just by looking at the screen, and without taking into account the position of the elements, neither the quotation marks added to the name of the scenario, nor the word "None" added for the Awards, the graphics of the buttons other than for the first scenario are not the right ones, the arrows between the buttons are missing, and the tree structure of the campaign is not the same from the sixth scenario on.

Yes, @LeHerosInconnu . )
I've wanted to make a separate thread for the elements' layout.
But the wrong font and missing arrows seemed more substantial fore me, so I've decided to make a separate thread for it. Unfortunately, I haven't enough time at my workplace to make all, I've wanted....


> Yes, you're both right :)
> 
> This window has a lot of missing and incorrect elements. Also I couldn't find some assets like arrows in demo version of the game.

Aha! That's why these elements are missing... =/
