### ISSUE TITLE
Adventure map, Freeman's Foundry window, wrong title and wrong text

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2245]
In fheroes2, the title of the Freeman's Foundry window is not correct, the " 's " are missing.

It should be:

"Freeman's Foundry"

Instead of:

"Freeman Foundry"

In fheroes2, the text of the Freeman's Foundry window is not correct, the word "and" should replace the ",".

It should be:

"...Pikemen and Swordsmen..."
"...Veteran Pikemen and Master Swordsmen."

Instead of:

"...Pikemen, Swordsmen..."
"...Veteran Pikemen, Master Swordsmen."

In original game:

![Text title upgrade foundry H2 01](https://user-images.githubusercontent.com/43583994/99686335-ca6aa080-2a83-11eb-948f-90cfe2bb087a.png)

In fheroes2:

![Text title upgrade foundry fh2 01](https://user-images.githubusercontent.com/43583994/99686371-d22a4500-2a83-11eb-8139-351ee701e23d.png)

**Comment by shprotru** [comment]
Hi @LeHerosInconnu! On this screenshot's I see in OG `[p]ikemen` vs FH `[P]ikemen`, notice the difference in first letter register(lowercase vs uppercase). Which variant is acceptable?

**Comment by LeHerosInconnu** [comment]
Hello @shprotru,

> Hi @LeHerosInconnu! On this screenshot's I see in OG `[p]ikemen` vs FH `[P]ikemen`, notice the difference in first letter register(lowercase vs uppercase). Which variant is acceptable?

In fheroes2, the names of the creatures are all written with the first letter in uppercase, and I think it's nicer that way.
So, it's better to continue this way.

**Comment by shprotru** [comment]
Hi @LeHerosInconnu!
1. Text part with comma related to `HILLFORT` object, there name of units should be enumerated with `and` instead of `,` too or stay untouched?
2. The `FREEMANFOUNDRY` can upgrade 3 types of units: `PIKEMAN`, `SWORDSMAN` and `IRON_GOLEM`(and `HILLFORT` 3 too: `DWARF`, `ORC` and `OGRE`), how text should look if hero comes with all 3, non-graded, types of units?

**Comment by LeHerosInconnu** [comment]
Hello @shprotru,

> Hi @LeHerosInconnu!
> 
> 1. Text part with comma related to `HILLFORT` object, there name of units should be enumerated with `and` instead of `,` too or stay untouched?

Yes, it should also be corrected for the Hill Fort.

> 2. The `FREEMANFOUNDRY` can upgrade 3 types of units: `PIKEMAN`, `SWORDSMAN` and `IRON_GOLEM`(and `HILLFORT` 3 too: `DWARF`, `ORC` and `OGRE`), how text should look if hero comes with all 3, non-graded, types of units?

You do well to tell me about the Hill Fort, I didn't pay attention to the order of the creatures for the Freeman's Foundry.

- For the Freeman's Foundry, the order of the creatures, in the text and for the display of the creature graphics, should be as follows:
Master Swordsmen, Veteran Pikemen and Steel Golems.

So, for the text it should be:

"...Swordsmen, Pikemen and Iron Golems..."
"...Master Swordsmen, Veteran Pikemen and Steel Golems."

- For the Hill Fort, the order of the creatures, in the text and for the display of the creature graphics, should be as follows:
Ogre Lords, Orc Chiefs and Battle Dwarves.

So, for the text it should be:

"...Ogres, Orcs and Dwarves..."
"...Ogre Lords, Orc Chiefs and Battle Dwarves."

Of course, if there are only two creatures to be upgraded, the text must be adapted without the comma ",".

Examples:

"...Swordsmen and Iron Golems..."
"...Master Swordsmen and Steel Golems.

"...Orcs and Dwarves..."
"...Orc Chiefs and Battle Dwarves."

Related issues: https://github.com/ihhub/fheroes2/issues/1341, https://github.com/ihhub/fheroes2/issues/1340, https://github.com/ihhub/fheroes2/issues/1339.
