### ISSUE TITLE
Adventure map, Freeman's Foundry info window, wrong name

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2246]
In fheroes2, the name of the Freeman's Foundry info window is not correct, the " 's " are missing.

It should be:

"Freeman's Foundry"

Instead of:

"Freeman Foundry"

In original game:

![Name info foundry H2 01](https://user-images.githubusercontent.com/43583994/99686935-5da3d600-2a84-11eb-9833-22219d7ef9ae.png)

In fheroes2:

![Name info foundry fh2 01](https://user-images.githubusercontent.com/43583994/99686909-567cc800-2a84-11eb-80c2-46e568a0146e.png)

**Comment by Mr1BitL8r** [comment]
Hi and thanks for the finding,

Please assign the issue to me.

**Comment by shprotru** [comment]
Hi, @Mr1BitL8r! This issue is related to: `pull/2253` and already resolved.
