### ISSUE TITLE
Castle screen, the music of the Sorceress' castle does not start instantly in "MIDI" mode, and delay in "MIDI Expansion" and "External" modes

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2251]
In fheroes2, when the "Music Type" is set to "MIDI" and the "MUSIC" folder is present or not, when the player changes castles in the castle screen, all musics are played instantly except the music from the Sorceress' castle.

Here are the save file and a video that show the bug encountered:
[Castle music midi.zip](https://github.com/ihhub/fheroes2/files/5569442/Castle.music.midi.zip)

In fheroes2, when the "Music Type" is set to "MIDI Expansion" and the "MUSIC" folder is present, when the player changes castles in the castle screen, there is a significant delay before the music is played.
And when the "Music Type" is set to "External" and the "MUSIC" folder is present, when the player changes castles in the castle screen, there is a small delay before the music is played and this delay is more important for some castles.

Here is a video that show the bug encountered:
[Castle music midi expansion external.zip](https://github.com/ihhub/fheroes2/files/5569448/Castle.music.midi.expansion.external.zip)

**Edit 2021/05/09.**

In fheroes2:
Activate the sound of the video.

https://user-images.githubusercontent.com/43583994/117577025-63e84600-b0e8-11eb-9dc4-ad57922c4337.mp4

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , it is not a bug but the theme of the song, it is the song itself and we can do nothing about it.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , it is not a bug but the theme of the song, it is the song itself and we can do nothing about it.

Okay, I see.
Just out of curiosity, isn't there a way to ignore or skip the silence part at the beginning of the theme?

**Comment by ihhub** [comment]
Nope, un

**Comment by ihhub** [comment]
Nope, unless we modify MIDI file which is not easy.

**Comment by LeHerosInconnu** [comment]
@ihhub.

> Nope, unless we modify MIDI file which is not easy.

Okay, I understand, it's not impossible but it would be too complicated. :)
