### ISSUE TITLE
Mouse speed issue on larger & native resolutions Linux

### ISSUE THREAD

**Issue by hutber** [ihhub/fheroes2#2254]
On higher than native resolution it is impossible to move the mouse, however on the default size, as you can see in the video, its slightly less difficult to move. But still very much difficult to use.

https://www.youtube.com/watch?v=Qrt22GHMic4

I love the project btw :D LOVE IT!!

**Comment by ihhub** [comment]
Hi @hutber , do you use SDL1 or SDL2. Seems like the first option. If yes please try the second one.
If no what's the specifications of your PC?

**Comment by hutber** [comment]
I was using SDL1 yes, to use SDL2 I just ran the script and then started again with `fheroes2`. Still having the same issue, I assume I cannot uninstall?

Otherwise its 
LInux Mint, fact here :)
![image](https://user-images.githubusercontent.com/1344898/99908130-b5d31600-2cd8-11eb-8452-1cdf4de4d893.png)

**Comment by undef21** [comment]
Hello, @hutber. Have you ran fheroes2 from  fheroes2_linux_sdl2.zip? If you built from sources, have you ran 'make clean' before?

What is your display resolution and DPI?

**Comment by hutber** [comment]
You were right, thank you. Cleaning before then running fixed it for me.
