### ISSUE TITLE
Combat screen, Surrender window, wrong cost for the hero's surrender, and also when the hero owns the Statesman's Quill artifact

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2260]
In fheroes2, there is a wrong cost for the hero's surrender.

In the original game, the cost is 50 percent of the total gold price of the creatures.
In the example, with 1 Peasant (cost 20 gold) the price of surrender is 10 gold.

In original game:

![Surrender H2 01](https://user-images.githubusercontent.com/43583994/100388692-9ebf5b80-302b-11eb-8c3e-189e90c2f9c9.png)

In fheroes2:

![Surrender fh2 01](https://user-images.githubusercontent.com/43583994/100388704-a8e15a00-302b-11eb-900e-4a1a3f7fb214.png)

In the original game, the cost is 10 percent of the total gold price of the creatures if the hero owns the Statesman's Quill artifact.
In the example, with the Statesman's Quill artifact, with 1 Peasant (cost 20 gold) the price of surrender is 2 gold.

In original game:

![Surrender H2 02](https://user-images.githubusercontent.com/43583994/100390322-3a52cb00-3030-11eb-9504-c4e16ce70253.png)

In fheroes2:

![Surrender fh2 03](https://user-images.githubusercontent.com/43583994/100390338-48a0e700-3030-11eb-9ba1-4adcfc7fcecc.png)

![Surrender fh2 02](https://user-images.githubusercontent.com/43583994/100390339-4a6aaa80-3030-11eb-8b12-40893f9a6ce0.png)

Here is the test scenario file:
[Surrender fh2 01.zip](https://github.com/ihhub/fheroes2/files/5604907/Surrender.fh2.01.zip)

**Comment by undef21** [comment]
@LeHerosInconnu , is cost depends on Diplomacy skill in original game?

**Comment by LeHerosInconnu** [comment]
@undef21.

> @LeHerosInconnu , is cost depends on Diplomacy skill in original game? If yes, is Diplomacy effect summed up with Statesman's Quill effect?
> There is minimal cost 100 gold in fheroes2. Please, check surrending with army's cost > 200 gold

In the original game the cost is reduced with the Diplomacy skill and the effect of the Statesman's Quill further reduces the cost.

Surrender with 1000 Peasants (cost 20,000 gold).

In original game:

No Diplomacy, without Statesman's Quill.
![Surrender H2 no Diplomacy 01](https://user-images.githubusercontent.com/43583994/100524347-b4618c00-31b7-11eb-8edc-5027a868c0b4.png)

No Diplomacy, with Statesman's Quill.
![Surrender H2 no Diplomacy quill 01](https://user-images.githubusercontent.com/43583994/100524354-c4796b80-31b7-11eb-8ebb-2ca56335ac7f.png)

Diplomacy Basic, without Statesman's Quill.
![Surrender H2 Diplomacy basic 01](https://user-images.githubusercontent.com/43583994/100524356-d2c78780-31b7-11eb-9daf-7cf795864ab3.png)

Diplomacy Basic, with Statesman's Quill.
![Surrender H2 Diplomacy basic quill 01](https://user-images.githubusercontent.com/43583994/100524370-de1ab300-31b7-11eb-8943-b897dd059ea2.png)

Diplomacy Advanced, without Statesman's Quill.
![Surrender H2 Diplomacy advanced 01](https://user-images.githubusercontent.com/43583994/100524372-e7a41b00-31b7-11eb-9f4a-8de33870e245.png)

Diplomacy Advanced, with Statesman's Quill.
![Surrender H2 Diplomacy advanced quill 01](https://user-images.githubusercontent.com/43583994/100524376-f12d8300-31b7-11eb-9790-f9f6e1eba224.png)

Diplomacy Expert, without Statesman's Quill. Should be 4000 gold instead of 3999 gold.
![Surrender H2 Diplomacy expert 01](https://user-images.githubusercontent.com/43583994/100524380-fa1e5480-31b7-11eb-9eab-584be6ab5437.png)

Diplomacy Expert, with Statesman's Quill. Should be 800 gold instead of 799 gold.
![Surrender H2 Diplomacy expert quill 01](https://user-images.githubusercontent.com/43583994/100524384-02768f80-31b8-11eb-96c4-df4fbd44e479.png)

In fheroes2:

No Diplomacy, without Statesman's Quill.
![Surrender fh2 no Diplomacy 01](https://user-images.githubusercontent.com/43583994/100524440-89c40300-31b8-11eb-9505-e24747cbc8c7.png)

No Diplomacy, with Statesman's Quill.
![Surrender fh2 no Diplomacy quill 01](https://user-images.githubusercontent.com/43583994/100524446-934d6b00-31b8-11eb-8251-416589c60d50.png)

Diplomacy Basic, without Statesman's Quill.
![Surrender fh2 Diplomacy basic 01](https://user-images.githubusercontent.com/43583994/100524451-9d6f6980-31b8-11eb-8ea3-194370a08665.png)

Diplomacy Basic, with Statesman's Quill.
![Surrender fh2 Diplomacy basic quill 01](https://user-images.githubusercontent.com/43583994/100524456-a6f8d180-31b8-11eb-9538-1c90fcc094b3.png)

Diplomacy Advanced, without Statesman's Quill.
![Surrender fh2 Diplomacy advanced 01](https://user-images.githubusercontent.com/43583994/100524459-ae1fdf80-31b8-11eb-867a-520b28ab693b.png)

Diplomacy Advanced, with Statesman's Quill.
![Surrender fh2 Diplomacy advanced quill 01](https://user-images.githubusercontent.com/43583994/100524465-b37d2a00-31b8-11eb-8246-46e56b663ac0.png)

Diplomacy Expert, without Statesman's Quill.
![Surrender fh2 Diplomacy expert 01](https://user-images.githubusercontent.com/43583994/100524471-bbd56500-31b8-11eb-9556-63ef6bc55dfa.png)

Diplomacy Expert, with Statesman's Quill.
![Surrender fh2 Diplomacy expert quill 01](https://user-images.githubusercontent.com/43583994/100524480-c7289080-31b8-11eb-845e-2e2b2c5d3a5c.png)
