### ISSUE TITLE
Combat screen, Surrender window, "ACCEPT" and "DECLINE" buttons have no shadow

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2261]
In fheroes2, the "ACCEPT" and "DECLINE" buttons have no shadow.
The same flaw is present in the original game.

In fheroes2:

![Surrender fh2 02](https://user-images.githubusercontent.com/43583994/100390339-4a6aaa80-3030-11eb-8b12-40893f9a6ce0.png)

For fheroes2, I suggest vertically moving these buttons the same distance from the bottom edge of the window and adding a shadow in the same way as in this window:

![Surrendered fh2 01](https://user-images.githubusercontent.com/43583994/100391218-0cbb5100-3033-11eb-8fa6-0d059aa3fba8.png)

**Comment by ihhub** [comment]
Hmmm... we then have to change the sprites... I'll take a look.

**Comment by ihhub** [comment]
This issue was fixed in #4350.
