### ISSUE TITLE
Combat screen, Surrender and Fled windows, graphic default of 1 pixel over the entire width of the bottom of the window

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2263]
In fheroes2, there is a graphic default of 1 pixel over the entire width of the bottom of the window, the shading does not seem applied.

In fheroes2:

![Surrendered fh2 01](https://user-images.githubusercontent.com/43583994/100391218-0cbb5100-3033-11eb-8fa6-0d059aa3fba8.png)

![Fled fh2 01](https://user-images.githubusercontent.com/43583994/100391969-658be900-3035-11eb-8072-ccc34967c5ac.png)

**Comment by undef21** [comment]
@LeHerosInconnu, could you post same dialog screenshot from original game?

**Comment by LeHerosInconnu** [comment]
@undef21.

> @LeHerosInconnu, could you post same dialog screenshot from original game?

Yes, of course.

Note that in the original game there is a flaw with the shadow of the window and the bottom of the yellow frame of the information bar at the bottom of the screen which has been fixed in fheroes2 and which should not be reproduced.

In original game:

![Surrendered H2 01](https://user-images.githubusercontent.com/43583994/100523098-fa195700-31ad-11eb-83f7-9f8dd3341cc2.png)

![Fled H2 01](https://user-images.githubusercontent.com/43583994/100523096-f7b6fd00-31ad-11eb-86aa-b31eb242fe62.png)
