### ISSUE TITLE
No sound of vanishing AI hero, after losing a battle

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2271]
When AI attacks human player's castle and loses a battle, there's no sound, when it disappears from a world map.
![image](https://user-images.githubusercontent.com/55348946/100518373-3941ab00-31a2-11eb-8181-818141e0a3e9.png)

**Comment by shprotru** [comment]
[cases for checks(RUS)](https://github.com/ihhub/fheroes2/files/5610873/cases.txt)

**Comment by LeHerosInconnu** [comment]
Same if it is the human defensive hero who loses the siege or surrenders during the AI's turn.
Same if the AI hero attacking the castle flees during the combat during the AI's turn.
