### ISSUE TITLE
Implement hotkeys for splitting stacks

### ISSUE THREAD

**Issue by eos428** [ihhub/fheroes2#2280]
![Screenshot 2020-11-29 084005](https://user-images.githubusercontent.com/38433056/100530148-d93e1980-3220-11eb-8ae8-7bae50941fc2.jpg)

Currently, we have to right-click on an empty unit slot to split a stack, I propose the usage of these hotkeys to make splitting easier:
- `Shift` key. This should closely follow the logic in the original game.
- `CTRL` key. This is an enhancement and should work like how CTRL key works in HOTA (or simply H3 HD mod? I forgot). Basically if you use CTRL key + left mouse click on a stack, it will split 1 unit to a new stack on the next empty slot. The stack does not have to be selected to use this feature.

We can also enhance the `shift` key functionality by making it usable when clicking on the selected stack too. This should split the troops evenly without opening a new dialog. Consecutive clicks will split it to 3 stacks, and so on. However, we already have the fast separation into slots thing, so this might not be necessary. Essentially something we see in modded H3 again, but I believe if it's good we should look to it for inspiration.

Also, this text below should be updated to reflect the changes made against this issue. Probably just need to give info that we can use the hotkeys to split the stack
![Screenshot 2020-11-29 090521](https://user-images.githubusercontent.com/38433056/100530247-24a4f780-3222-11eb-89d6-ce74c1c4ab59.jpg)

Since some of the proposed changes are subjective, let me know what you think.

**Comment by Branikolog** [comment]
Hello, @eos428!
I think, we should implement all this button+click combinations, as lots of players are get used to them (H2 and H3 players). Button support doesn't affect UI, so we can add any. Those, who use button will be glad. Those, who don't use buttons - won't feel the difference.
According to text in the bottom - I'm not sure we should update it. I think there's not enough space to type all possible interactions. So I prefer leave it as it is. Anyone knows, how to use Shift to split troops. But not everyone knows, how to split troops using mouse.
