### ISSUE TITLE
Make Troops and Army classes contain value and not pointers

### ISSUE THREAD

**Issue by vincent-grosbois** [ihhub/fheroes2#2301]
Currently, we have a class Troop and a class ArmyTroop inheriting from Troop.
We have a class Troops containing Troop* values.
We have a class Army inheriting from Troops, so it contains also Troop* values.

Some things I have noted browsing the repo:
- Troops instances only ever contain Troop* values, and not pointers to derived class. In it also possible that this vector contains > 5 troops
- Army instances apparently only ever contain ArmyTroop* values, and always exactly 5 (with maybe some empty Troop)
- Due to inheritance, it's possible to call either Insert() or PushBack() on an army instance, which will add new Troop objects (not ArmyTroop objects)

So, this makes the code quite complex to understand, and also requires lots of dynamic allocations

I propose to do the following:
- change Troops class so it inherits from std::vector<Troop> instead of std::vector<Troop*> (actually it's maybe even best to not use inheritance but just add a vector member)
- change Army class so it contains an array ArmyTroop[5]

What do you think ?
The complex part would be to keep a single version of methods that works on sequences of troops (like MergeTroop()), but that can be achieved by refactoring + templates

**Comment by ihhub** [comment]
I am closing this issue as it brings no real value except code beautification.
