### ISSUE TITLE
Flags overlapping while castle appears

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2304]
When we build a castle we can see that different animation sprites are drawn over each other multiple times.
The issue is noticeable on a resolutions 1024x and higher. On a 640x480 and 800x600 i could notice only 1 wrong sprite, while on higher resolutions flags are moving faster, that causes its sprites overlap.
![image](https://user-images.githubusercontent.com/55348946/100811809-88126d80-344c-11eb-9eed-259cdc4f4902.png)

**Comment by ihhub** [comment]
Hi @Branikolog , could you please retest this issue as we fixed building animation recently.

**Comment by Branikolog** [comment]
@ihhub 
Well done. The problem is gone!
