### ISSUE TITLE
Hero's sprite is cut while standing on a road with a crack under it

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2305]
This issue is probably connected with #2201, where some parts of roads close to terrain objects are not drawn.
When a hero comes close to the road, this part of road even disappears.
![image](https://user-images.githubusercontent.com/55348946/100812227-93b26400-344d-11eb-946e-692ca60aae79.png)
![image](https://user-images.githubusercontent.com/55348946/100812257-a331ad00-344d-11eb-940e-2e91977d99c9.png)
And while standing on this part of road we can notice, that horse hoofs are being cut off.
![image](https://user-images.githubusercontent.com/55348946/100812287-b5abe680-344d-11eb-826d-829292b3b09b.png)

**Comment by ihhub** [comment]
Hi @vasilenkoalexey , could you please take a look at this issue?

**Comment by vasilenkoalexey** [comment]
> Hi @vasilenkoalexey , could you please take a look at this issue?
Shure!
