### ISSUE TITLE
Game is not fully drawn while switching into window mode

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2308]
Press f4 in fullscreen mode while moving screen. (Holding cursor close to the edge of the screen on a world map)
Right and bottom edges of game are not drawn. They even blinking with black color/background picture of OS.
![image](https://user-images.githubusercontent.com/55348946/100816117-759d3180-3456-11eb-8de5-77a633afcd5d.png)

**Comment by Branikolog** [comment]
The issue can be reproduced in the exact moment of reaching the edge of the screen by the cursor:
we move cursor to the edge and simultaneously press F4 button.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog Is this issue still observed? I can't reproduce this, so I believe this has already been fixed as a side effect of some another fix.

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz.
Great news! I cannot reproduce the issue anymore! Thanks for tracking the problem!
