### ISSUE TITLE
Castle screen, Tavern window, wrong title color

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2310]
The title "Tavern" of this window should be yellow.

In fheroes2:

![Tavern fh2 01](https://user-images.githubusercontent.com/43583994/100824935-4d620280-3457-11eb-842f-743a52287767.png)

**Comment by ihhub** [comment]
In the original game it's the same color.

**Comment by LeHerosInconnu** [comment]
Hi @ihhub,

> In the original game it's the same color.

Here again, the goal is to standardize the interface. :)

In fheroes2:

![Yellow title fh2 01](https://user-images.githubusercontent.com/43583994/100909686-542b5c80-34cd-11eb-8717-541869bc6607.png)

![Yellow title fh2 02](https://user-images.githubusercontent.com/43583994/100909700-57264d00-34cd-11eb-9537-b0f50dbcb538.png)

![Yellow title fh2 03](https://user-images.githubusercontent.com/43583994/100909709-5988a700-34cd-11eb-96e9-1f980e2146da.png)

![Yellow title fh2 04](https://user-images.githubusercontent.com/43583994/100909726-5beb0100-34cd-11eb-9810-a16c170ac805.png)

![Yellow title fh2 05](https://user-images.githubusercontent.com/43583994/100909736-5e4d5b00-34cd-11eb-8952-81686efec2f7.png)

![Yellow title fh2 06](https://user-images.githubusercontent.com/43583994/100909747-60afb500-34cd-11eb-8fe8-09ba1692b079.png)
