### ISSUE TITLE
Slowed flying creature animation bug

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2314]
Vampires don't move smoothly over battlefield. They turn into bat, bat starts waving with its wings, then bat appears the next hex. Then jumps the last one (Vampires have speed 2) and there we can see transformation.
[Vampires issue.zip](https://github.com/ihhub/fheroes2/files/5635963/Vampires.issue.zip)

**Comment by ihhub** [comment]
This is the problem for any flying creature.

**Comment by ihhub** [comment]
@Branikolog , could you please check if in the original game slowed creatures can fly through a castle's wall?

**Comment by Branikolog** [comment]
@ihhub 
In the original game slowed flying creature acts the same to walking creatures:
It cannot fly over any obstacles or other troops.
It also can be stopped by a moat.

**Comment by Branikolog** [comment]
I think, slowed flying animation should be fixed up to upcoming 1.0 release, as it looks quite bad, actually.

**Comment by Districh-ru** [comment]
Hello, @Branikolog.
In the original game the slowed creatures also have bad animation:

https://user-images.githubusercontent.com/113276641/206899380-adbcfa89-4c82-4428-96a3-6d091241db26.mp4

fheroes2 for the comparison:

https://user-images.githubusercontent.com/113276641/206899463-7753d88e-6232-483a-9234-c3f3a84f67ac.mp4

The most notable difference is the lack of a vampire-to-bat animation.

Do we plan not to replicate the original game, but to make the smooth slow animation for the flying creatures?

**Comment by Branikolog** [comment]
Hi, @Districh-ru !
We should improve the animation. Original game looks as bad, as the current implementation.
I think, there're two problems here:
1) No take off and landing animation frames.
2) Not smooth enough flying animation.

**Comment by Districh-ru** [comment]
> Hi, @Districh-ru ! We should improve the animation. Original game looks as bad, as the current implementation. I think, there're two problems here:
> 
>     1. No take off and landing animation frames.
> 
>     2. Not smooth enough flying animation.

Ok, I'll try to fix this issue bout I don't know how fast I could do this.

**Comment by Branikolog** [comment]
@Districh-ru 
You've done well before! I really appreciate your help fixing all those game issues!

**Comment by Districh-ru** [comment]
Thank you, @Branikolog!
I'm glad that I was able to help with the project development. :)

**Comment by Districh-ru** [comment]
The start is made, they learned how to take off and land. :)

https://user-images.githubusercontent.com/113276641/206919038-31a95196-1329-4f98-a3b8-b3a55e64932c.mp4

But I will be busy at work in the next days. Therefore, I will focus on opened PRs.
