### ISSUE TITLE
Adventure map, graphic glitch in trees near Water Wheel

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2320]
In fheroes2, there is a graphic glitch in the trees near the Water Wheel.

In fheroes2:

![Black part cercle 01](https://user-images.githubusercontent.com/43583994/101159765-2f022f80-362e-11eb-9535-6ffaaf820490.png)

Here is the save file:
[Graphic glitch in trees fh2 01.zip](https://github.com/ihhub/fheroes2/files/5642474/Graphic.glitch.in.trees.fh2.01.zip)

**Comment by Branikolog** [comment]
Well, the shadow of watermill looks strange even without trees.
![image](https://user-images.githubusercontent.com/55348946/101164409-0be37a00-3646-11eb-98d3-f96675ec0ab8.png)
It seems to me, its edges are too sharp.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu and @Branikolog , this is a screenshot from the original game:
![image](https://user-images.githubusercontent.com/19829520/109019094-a3131780-76f3-11eb-9136-e9c26ebc9f2f.png)

As you can see the object has the exact shadow as in our version. Could you please explain what's wrong with this shadow?

**Comment by LeHerosInconnu** [comment]
@ihhub.

> Hi @LeHerosInconnu and @Branikolog , this is a screenshot from the original game:
> As you can see the object has the exact shadow as in our version. Could you please explain what's wrong with this shadow?

Indeed, it is the same in the original game.
Looking for flaws, you end up finding them everywhere. :)

It's just that the shadow looks more like a part of the fog of war that wouldn't have been removed properly.
A bit like a round for the war fog in this example with the ocean:

![Détail fog of war round 01](https://user-images.githubusercontent.com/43583994/109024128-b73c2200-76bd-11eb-966e-136b8d941e27.png)

I think this is due to the way the shadows are handled.
So, it seems to be normal.

**Comment by ihhub** [comment]
Closing this issue as no action is required here.
