### ISSUE TITLE
Adventure map, Boat's sprite cut near Magellan Maps

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2321]
In fheroes2, the Boat's sprite is cut near Magellan Maps.

In fheroes2:

![Boat cut Magellan fh2 01](https://user-images.githubusercontent.com/43583994/101160607-9c629000-362f-11eb-87fc-a756482eae44.png)

Here is the save file:
[Boat cut Magellan fh2 01.zip](https://github.com/ihhub/fheroes2/files/5642522/Boat.cut.Magellan.fh2.01.zip)

**Comment by ihhub** [comment]
Hi @Branikolog , could you please verify this issue on the latest build?

**Comment by Branikolog** [comment]
Hi, @ihhub !
The issue is gone.
But I found another issue connected with Magellan maps:
![image](https://user-images.githubusercontent.com/55348946/114701253-3eeff580-9d2b-11eb-8be5-38f4d1b7bfc3.png)
Should I create another issue for it or can I modify this one?

**Comment by a1exsh** [comment]
> I found another issue connected with Magellan maps:

@Branikolog what is the issue this time?  From the screenshot it's not obvious to me.

**Comment by Branikolog** [comment]
Hi, @a1exsh 
At the screenshot there's a line of water texture could be seen through a boat's nose.
