### ISSUE TITLE
Combat, Chain Lightning spell doesn't work as it should

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2327]
In fheroes2, the Chain Lightning spell doesn't work as it should.

In the video examples, there is a troop closer than the Titans or Archmagi of the hero Kastore who should be hit by the spell (Archmagi or Steel Golems of the hero Myra).

In fheroes2:

![vlcsnap-2020-12-04-16h00m09s704](https://user-images.githubusercontent.com/43583994/101184131-a2b53400-3650-11eb-8ab5-412be95faa79.png)

![vlcsnap-2020-12-04-16h01m32s870](https://user-images.githubusercontent.com/43583994/101184116-9df08000-3650-11eb-8c0e-6a22366f598c.png)

Attack Myra with Kastore.
Reproduce the combat as shown in the larger video.
Here are the save file and videos that show the bug encountered:
[Bug chain lightning fh2 01.zip](https://github.com/ihhub/fheroes2/files/5643747/Bug.chain.lightning.fh2.01.zip)

**Comment by Branikolog** [comment]
One more strange case of "Chain Lightning" spell operation...
Here we have similar issues with incorrect behaviour of this spell too: #840, #537.
