### ISSUE TITLE
Adventure screen, make a left click and hold it on the adventure map (or on the graphic of a castle, or on the portrait of a hero, or anywhere in the adventure screen) and moving the cursor over the minimap area should not change the position of the crosshairs of the minimap

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2332]
In fheroes2, make a left click and hold it on the adventure map (or on the graphic of a castle, or on the portrait of a hero, or anywhere in the adventure screen) and moving the cursor over the minimap area should not change the position of the crosshairs of the minimap.

The view of the minimap should change only when the left click is performed in the minimap area.

This flaw is not present in the original game.

In fheroes2:

![Move minimap 01](https://user-images.githubusercontent.com/43583994/101290599-a5a45600-3803-11eb-8df2-0db180a5b754.gif)

![Move minimap 02](https://user-images.githubusercontent.com/43583994/101290610-b5239f00-3803-11eb-9930-a1c7f51f2542.gif)

![Move minimap 03](https://user-images.githubusercontent.com/43583994/101290612-bce34380-3803-11eb-8a86-3d90453bb843.gif)

Also, make a left click and hold it on the minimap and exiting the minimap area and then returning to the minimap area should not change the position of the minimap crosshairs.

The view of the minimap should only change when the left click is performed in the minimap area.

This flaw is also present in the original game.

In fheroes2:

![Move minimap 04](https://user-images.githubusercontent.com/43583994/101290626-ce2c5000-3803-11eb-99f1-522c59954625.gif)

**Comment by Laserlicht** [comment]
@ihhub I think this is solved now with https://github.com/ihhub/fheroes2/pull/5878 😊
