### ISSUE TITLE
Adventure map, hero info window, wrong number displayed for movement points on land and water with artifacts related to movement

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2338]
In fheroes2, there is a wrong number displayed for movement points on land and water with artifacts related to movement.

The possible movement of the hero on the adventure map is correct.

In fheroes2:
Ruby has a movement on land of 25 with the Phoenixes and two copies of the artifact "True Compass of Mobility" (+5 Moves (500 points) on land and ocean), it's okay.
![Artifacts movement fh2 01](https://user-images.githubusercontent.com/43583994/101422282-94884180-38f6-11eb-924b-96825d66b96b.png)

Ruby still has a movement on land of 25 with the addition of the artifact "Nomad Boots of Mobility" (+6 Moves (600 points) on land), the movement should be 31.
![Artifacts movement fh2 02](https://user-images.githubusercontent.com/43583994/101422293-9ce07c80-38f6-11eb-919e-b357a4877c2b.png)

Ruby still has a movement on land of 25 with the addition of the artifact "Traveller's Boots of Mobility" (+3 Moves (300 points) on land), the movement should be 34.
![Artifacts movement fh2 03](https://user-images.githubusercontent.com/43583994/101422305-a4078a80-38f6-11eb-8b08-1a0e48385b12.png)

Ruby has a movement on ocean of 25 with the Phoenixes and two copies of the artifact "True Compass of Mobility" (+5 Moves (500 points) on land and ocean), it's okay.
![Artifacts movement fh2 04](https://user-images.githubusercontent.com/43583994/101422314-a9fd6b80-38f6-11eb-94a9-826efc5d55d8.png)

Ruby still has a movement on ocean of 25 with the addition of the artifact "Sailor's Astrolabe of Mobility" (+10 Moves (1000 points) on ocean), the movement should be 35.
![Artifacts movement fh2 05](https://user-images.githubusercontent.com/43583994/101422321-aec21f80-38f6-11eb-87cc-ae259ac02142.png)

Ruby has a movement on ocean of 25 with the Phoenixes and the artifact "Sailor's Astrolabe of Mobility" (+10 Moves (1000 points) on ocean), it's okay.
![Artifacts movement fh2 06](https://user-images.githubusercontent.com/43583994/101422331-b5509700-38f6-11eb-9816-383d276d9bf3.png)

Ruby still has a movement on ocean of 25 with the addition of the artifact "True Compass of Mobility" (+5 Moves (500 points) on land and ocean), the movement should be 30.
![Artifacts movement fh2 07](https://user-images.githubusercontent.com/43583994/101422336-b97cb480-38f6-11eb-88c6-fece9a4a57e9.png)

Here are the save files:
[Artifacts movement fh2 01.zip](https://github.com/ihhub/fheroes2/files/5656057/Artifacts.movement.fh2.01.zip)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , I have a non-related to this issue question: would you like to be a **Collaborator** for this project? In this case you can be able to assign needed labels, assignee as well as milestone for the issues; modify issues or reopen them as well as create/edit wikis. The full list of rights you can read [here](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/permission-levels-for-a-user-account-repository). The quick brief guide I can do later.

An answer **NO** is totally fine, I'm not insisting on anything. Just I would like to appreciate your work and make your impact on the project more valuable. Take your time if needed, it's not an instant yes/no question.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , I have a non-related to this issue question: would you like to be a **Collaborator** for this project? In this case you can be able to assign needed labels, assignee as well as milestone for the issues; modify issues or reopen them as well as create/edit wikis. The full list of rights you can read [here](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/permission-levels-for-a-user-account-repository). The quick brief guide I can do later.
> 
> An answer **NO** is totally fine, I'm not insisting on anything. Just I would like to appreciate your work and make your impact on the project more valuable. Take your time if needed, it's not an instant yes/no question.

I appreciate the offer, but there is already so much to do to report bugs and for future suggestions; a collaborator position would only decrease the time spent on these tasks and I prefer to focus on these tasks, even if it might relieve you a little bit, to have less bug reports. :)
So I have to say no. :)

**Comment by ihhub** [comment]
@LeHerosInconnu got it! Thank you very much for your answer!

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu It seems that this mobility info is absent in OG in the hero's "quick info" window, so I wander, what should the first number really mean? Now it means the "mobility index" of this hero, which corresponds to the internal index of the hero movement sprite (that yellow bar on the left of hero's avatar) and it cannot exceed 25. May be we should remove it entirely and leave only the current and max hero's movement points (the next two numbers after this one)?

**Comment by Branikolog** [comment]
Hi.
My 5 cent...
I think we should remove this useless and confusing number. :)
"2500/3000" is quite enough for player to understand and use movement rules of the game.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog I think that initially this number was displayed for debug purposes, now it is useless and misleading.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Totally agreed.

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz and @Branikolog,

This number is not useless.
It gives an idea of the number of potential movements.
For "15/1500/1500":
- "15": the hero has a potential of 15 moves (with a 100% penalty terrain).
- First "1500": the "real" number of movement points left.
- Second "1500": the number of movement points of the hero for the next turn according to the slowest creature in the hero's army and movement artifacts (if the composition of the hero's army is changed and/or if he gives a movement artifact to another hero).

For example, if the hero is on the Desert terrain and has 150 movement points left, the player may believe that the hero can still move (150/1500) when this is not the case (0/150/1500).

> Hi @LeHerosInconnu It seems that this mobility info is absent in OG in the hero's "quick info" window, so I wander, what should the first number really mean? Now it means the "mobility index" of this hero, which corresponds to the internal index of the hero movement sprite (that yellow bar on the left of hero's avatar) and it cannot exceed 25, because 25 is the index of that "plenty of move points" sprite with three plus signs. May be we should remove it entirely and leave only the current and max hero's movement points (the next two numbers after this one)?

There are at least two ways to solve the problem without removing the first number.

- Add extra sprites when the hero has even more movement (for example):
![Hero move full fh2 02](https://user-images.githubusercontent.com/43583994/113145939-5ad5a080-922f-11eb-95e4-fc007ef29946.png) ![Hero move full fh2 03](https://user-images.githubusercontent.com/43583994/113145941-5b6e3700-922f-11eb-9b58-4e8ddec1ce4f.png) ![Hero move full fh2 04](https://user-images.githubusercontent.com/43583994/113145944-5c06cd80-922f-11eb-873f-392715755253.png)

- Specify the corresponding potential movement number without adding extra sprites (for example):
"34/3400/3400"
And use the last sprite when the number is equal or greater than 25.

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu Currently this number is basically just the following: `min(25, hero_can_move ? hero_move_points / 100 : 0)`, that's all. It can't properly represent count of remaining moves, because this count depends on particular path (there are terrain penalties, there can be multiple different terrains, there may be roads, there may be diagonal moves and so on). I can remove the `min(25)` part, but I still think that this number seems useless in real life.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub @idshibanov What do you think regarding this issue?

**Comment by idshibanov** [comment]
I'm voting to remove it. I never look at this number myself since it can't be precise (for all reasons stated already). Also first time I opened fheroes2 I was very confused by the three numbers for movement since humans are used to X out of Y.

**Comment by ihhub** [comment]
I think having these 3 numbers is indeed confusing for players. First number works only for the case of terrains with 100% penalty and it could mislead a player who for example moves a hero over swamp.
I recommend to remove the first number.
