### ISSUE TITLE
Game freezes during animation of resources collection in world map menu so user cannot access menu options

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#234]
Pressing "End Turn", "Cast Spell", "Adventure", "File & System" options buttons, while world map menu window shows info regarding collected resources, causes game completely freeze in a couple of seconds.
![Безымянный11](https://user-images.githubusercontent.com/55348946/69224180-c3fdcc00-0b84-11ea-8f0c-660bd4191f72.jpg)

**Comment by ihhub** [comment]
This is known issue: the game doesn't accept any user input until animation of certain event is finished.

**Comment by ihhub** [comment]
Most likely we need to create a queue for animation to avoid such situations. The same problem appears in castle during construction of new building: no user input is accepted for few seconds.
