### ISSUE TITLE
Adventure screen, making a left click not held on an area under the lists of heroes and castles and moving the mouse cursor over a hero or castle should not select the hero or castle

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2357]
In fheroes2, when the user left-clicks (without holding it down) on the area indicated in red below the lists of heroes and castles and then moves the mouse cursor over the portrait of a hero or the graphic of a castle, it selects the hero or the castle.
If the hero or castle is already selected, the same operation opens the screen of the hero or castle.

In fheroes2:

![Left clic not hold fh2 rectangle 01](https://user-images.githubusercontent.com/43583994/101981199-621a7380-3c6b-11eb-81e0-53df1e963f68.png)

![Left clic not hold fh2 02](https://user-images.githubusercontent.com/43583994/101981197-5d55bf80-3c6b-11eb-91e1-9f04c8479805.png)

![Left clic not hold fh2 03](https://user-images.githubusercontent.com/43583994/101981198-5fb81980-3c6b-11eb-9713-1ae8f43ddba0.png)

**Comment by oleg-derevenetz** [comment]
Should have been fixed by #2485.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Issue is gone!
Thanks for your contribution!
