### ISSUE TITLE
Hero screen, Morale info window, missing text when the army consists only of undead troops

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2358]
In fheroes2, there is a missing text when the army consists only of undead troops:

"Entire unit is undead, so morale does not apply."

I also suggest replacing the word "unit" with the word "army":

"Entire army is undead, so morale does not apply."

Instead of:

"Entire unit is undead, so morale does not apply."

In original game:

![Morale info H2 01](https://user-images.githubusercontent.com/43583994/101981710-1e296d80-3c6f-11eb-8554-cb3f4f4b3f7c.png)

In fheroes2:

![Morale info fh2 01](https://user-images.githubusercontent.com/43583994/101981715-297c9900-3c6f-11eb-87b6-854b63aafbc4.png)

In the original game, the negative current modifiers are not displayed when the army consists only of undead troops.
An improvement could be made for this in fheroes2, by displaying the current morale modifiers (without them being applied) even when the army contains only undead troops.
This would allow the player to be informed of the morale modifiers before including alive troops in his army if he is considering doing so.
In the previous screenshot, the word "None" would therefore be kept and displayed (and also for cases with other current morale modifiers). (https://github.com/ihhub/fheroes2/issues/2359)

**Comment by Branikolog** [comment]
> An improvement could be made for this in fheroes2, by displaying the current morale modifiers (without them being applied) even when the army contains only undead troops.

I like this idea. I think we should always show hero's morale modifier. No matter what army he has.
