### ISSUE TITLE
Good Morale and Luck rates are incorrect

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#236]
Good morale and Luck effects appear way too often. Especially having +2 an +3 index.
![Безымянный111](https://user-images.githubusercontent.com/55348946/69235817-ebf82a00-0b9a-11ea-9773-2c1bb5b85983.jpg)

**Comment by temyurchenko** [comment]
Why is it a bug? What are the correct rates? Do we have information on what they are in the original?

Right now, the rate of an event is 12.5% at the highest. While 50% before was probably, indeed, too high, is 12.5% too low?

cc @ihhub

**Comment by ihhub** [comment]
Hi @temyurchenko , the rates are set to be the same as in the original game.

**Comment by temyurchenko** [comment]
> Hi [@temyurchenko](https://github.com/temyurchenko) , the rates are set to be the same as in the original game.

Got it, thank you! I was trying to find what the rates were in the original, but failed. Could you please give me a hint where the documentation on that is?

**Comment by temyurchenko** [comment]
However, based on the manual, it seems that the bad luck chance is not implemented according to the original. It should be twice as likely.
