### ISSUE TITLE
Adventure map, Graveyard, Shipwreck and Derelict Ship, the penalty for visiting these places should only be applied if the hero visits the place without having fought and defeated the creatures

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2362]
In the original game, the penalty for visiting these places is applied only if the hero visits the place without having fought and defeated the creatures.
If the hero starts fighting the creatures and runs away during the combat, the penalty is not applied.
If the hero fights and defeats the creatures, the penalty is not applied.

In fheroes2, the penalty is applied even when the hero fights and defeats the creatures; this must not happen.

In fheroes2:

![Derelict ship robber fh2 01](https://user-images.githubusercontent.com/43583994/101982819-dad2fd00-3c76-11eb-9e2b-8b482818e482.png)

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog 

Are you sure about that? I decided to deal with this bug and found that morale penalty will be applied if you defeated the creatures, but find nothing. The game even has a corresponding message:

> Upon defeating the Zombies you spend several hours searching the graves and find nothing. Such a despicable act reduces your army's morale.

And there are similar messages for other objects with morale penalty.

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz !
I've just tried this bug: I won a battle and still have a negative morale modifier:
![image](https://user-images.githubusercontent.com/55348946/112622987-d48b1a00-8e3c-11eb-8b50-cb4d4dea038c.png)

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog Yes, you are able to get a negative morale modifier if you won the battle, but got no reward. That's why message about morale reduction tells this. Are you sure that's not the case in OG?

**Comment by Branikolog** [comment]
@oleg-derevenetz 
I've just checked the OG. When we fight ghosts and receive xxx gold we don't get morale penalty.
In fheroes2 after winning a battle hero gets -1 to morale.

**Comment by oleg-derevenetz** [comment]
@Branikolog Hmm, it's strange then, it shouldn't happen according to the code - you can get a morale penalty if you won the battle but ONLY if you doesn't get a reward. OK, I'll look into this...

**Comment by Branikolog** [comment]
@oleg-derevenetz 
I thought player will always get a reward after he won a battle...
But yes: on victory my hero gains -1 to morale. 100% sure.

**Comment by oleg-derevenetz** [comment]
@Branikolog Yes, it looks like it gets no reward only if object was already visited by someone else, in this case there is no battle and morale penalty. But it shouldn't get a morale penalty if it won the battle and get a reward, that's right.

**Comment by Branikolog** [comment]
So we simply should apply penalty for any hero pressed "OKAY" on searching this kind of object was already visited by someone. But not for that hero, who won the battle.
