### ISSUE TITLE
Adventure map, month of the creature, hero's path must be actualized when a wandering troop is positioned on the path determined the previous turn when the month of the creature occurs

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2365]
In fheroes2, the hero's path must be actualized when a wandering troop is positioned on the path determined the previous turn when the month of the creature occurs.

In fheroes2:

![Month Vampire hero path fh2 01](https://user-images.githubusercontent.com/43583994/101984390-7d907900-3c81-11eb-9a6f-8c453f6e0233.png)

Here are the save files:
[Month of creature fh2 01.zip](https://github.com/ihhub/fheroes2/files/5683088/Month.of.creature.fh2.01.zip)

**Comment by ihhub** [comment]
This issue is not valid anymore on the latest build.
