### ISSUE TITLE
Adventure map, month of the creature, the positioning of the wandering troops during the month of the creature does not seem to be the same as in the original game

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2366]
In fheroes2, the positioning of the wandering troops during the month of the creature does not seem to be the same as in the original game.

Here are the save files:
[Month of creature fh2 01.zip](https://github.com/ihhub/fheroes2/files/5683088/Month.of.creature.fh2.01.zip)

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu!
Could you, please, clarify, what is going wrong?

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

> Hi, @LeHerosInconnu!
> Could you, please, clarify, what is going wrong?

I have already planned to test this with the original game.
This may take some time. :)
And I won't test it before several days.

But maybe it would be easier to see how this function works in the original game code?
It would save me a lot of time for something else. :)

**Comment by Branikolog** [comment]
@LeHerosInconnu 
Sorry for bothering you. 
I've just wanted you to write here, what exactly do you think is wrong. Is this density of the creatures? Quantity of appeared stacks? Or probably the places they're appearing? So our dev team would better know, where to watch in the code. 
Could you make your little precision here? ;)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> @LeHerosInconnu
> Sorry for bothering you.
> I've just wanted you to write here, what exactly do you think is wrong. Is this density of the creatures? Quantity of appeared stacks? Or probably the places they're appearing? So our dev team would better know, where to watch in the code.
> Could you make your little precision here, please? ;)

No problem. :)

Already for the positioning of groups, this does not seem correct.

Then for the quantity of groups generated and the quantity of creatures in the groups, I'm not sure, and it should also be seen for the quantity generated according to the number of turns in the game and according to the size of the map.

As a matter of checking the code of the function why not do it in its entirety, to be sure of the result in one go?

**Comment by Branikolog** [comment]
I've experienced a problem, regarding this issue.
In a month of minotaur some of minotaurs appeared close to some of my heroes and couple of battles occurred with the beginning of a day.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> I've experienced a problem, regarding this issue.
> In a month of minotaur some of minotaurs appeared close to some of my heroes and couple of battles occurred with the beginning of a day.

In the original game, this does not happen because for the duration of the first day of the week, heroes can even move into the adjacent squares of the generated creatures without triggering a combat.

But I find this operation of the original game a bit annoying because it doesn't respect the rules concerning wandering creatures.

In fheroes2, the heroes cannot move to one of the adjacent squares of the generated creatures without triggering a combat.
And the predefined path of the heroes must also be recalculated (https://github.com/ihhub/fheroes2/issues/2365).

The case you encountered with Minotaur can be avoided by stipulating in the code not to generate a troop of creatures in a square adjacent to a hero. :)

**Comment by Branikolog** [comment]
@LeHerosInconnu 
And not only hero!
![image](https://user-images.githubusercontent.com/55348946/102999633-721f3680-453a-11eb-8b37-99ca1a2c1b62.png)
:D

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , could you please give more clarification in terms on logic and formulas how the correct behavior should be? I think we fixed something before for wandering creatures but if it's not enough we could make adjustments.

**Comment by LeHerosInconnu** [comment]
@ihhub.

> Hi @LeHerosInconnu , could you please give more clarification in terms on logic and formulas how the correct behavior should be? I think we fixed something before for wandering creatures but if it's not enough we could make adjustments.

Okay, I'll do a test on this.

**Comment by LeHerosInconnu** [comment]
@ihhub.

> @ihhub.
> 
> > Hi @LeHerosInconnu , could you please give more clarification in terms on logic and formulas how the correct behavior should be? I think we fixed something before for wandering creatures but if it's not enough we could make adjustments.
> 
> Okay, I'll do a test on this.

For the original game, this is the number of Vampire groups generated on the Broken Alliance map on Impossible difficulty mode after the AI clears the map of all other wandering creatures.
Three groups of 10-19 Vampires (Pack) for this test, if I haven't missed any.
(Impossible Week 20 Day 7.GM1 and Impossible Week 21 Day 1 Vampire.GM1 in the Creature Month Heroes 2.zip file below)

In original game:

![Vampire Month Impossible 001](https://user-images.githubusercontent.com/43583994/115785485-cf7ba500-a3bf-11eb-903f-23d577b31050.png)
![Vampire Month Impossible 002](https://user-images.githubusercontent.com/43583994/115785496-d30f2c00-a3bf-11eb-9002-3412f11c28f1.png)
![Vampire Month Impossible 003](https://user-images.githubusercontent.com/43583994/115785459-c7236a00-a3bf-11eb-9e62-ffe2f7c25746.png)
![Vampire Month Impossible 004](https://user-images.githubusercontent.com/43583994/115785473-cb4f8780-a3bf-11eb-8713-046015910252.png)

In the original game, there doesn't seem to be any difference between the difficulty modes for the number of creature groups generated or for the amount of creatures in each group.

I don't know how it works in Heroes 2.
Sometimes there are more groups and the amount of creatures can be more or less important.
The groups are generally positioned on points of passage and/or on points of interest.
I think the best thing to do is to look at how it works in the source code of the original game, because to do it with tests would not necessarily be reliable and it would take a lot of time.

Here are save files from Heroes 2 before and after the Month of Creature on different difficuties:
[Creature Month Heroes 2.zip](https://github.com/ihhub/fheroes2/files/6361307/Creature.Month.Heroes.2.zip)

Also, the predetermined path of the hero remains problematic with the latest version of fheroes2 (fheroes2 0.9.2 3254 with save from fheroes2 0.9.2 3231).
Related to this closed issue: https://github.com/ihhub/fheroes2/issues/2365.

In fheroes2:

![Hero path creature month fh2 01](https://user-images.githubusercontent.com/43583994/115786459-203fcd80-a3c1-11eb-99b1-10af8adb8fdb.png)

Here are the save files (before and after):
[Hero path creature month fh2 01.zip](https://github.com/ihhub/fheroes2/files/6361330/Hero.path.creature.month.fh2.01.zip)

As you can see also with these save files (Hero path creature month fh2 01.zip), there are more creature groups generated in fheroes2.
