### ISSUE TITLE
Hero meeting screen, merging and moving creatures dialog issue

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2368]
While trying to merge two same type creatures, there appears dialog, which is supposed to work for the action with pressed "Shift" button.
Here we're trying to merge hobbits:
![image](https://user-images.githubusercontent.com/55348946/101985421-f8b15980-3c98-11eb-8207-36d28f668f76.png)
![image](https://user-images.githubusercontent.com/55348946/101985426-ff3fd100-3c98-11eb-8366-44733653aa6f.png)
Also, while moving any creature over any empty place of the same hero we can accidentally watch the same dialog.

**Comment by ihhub** [comment]
Hi @eos428 could you please take a look? I think the issue is that we use the same logic for mouse right and mouse left clicks but should be only for right click.

**Comment by Branikolog** [comment]
The issue is actual for not only meeting heroes, but for hero info and castle windows.
