### ISSUE TITLE
Save/load list, scroll bar is shifted in its bottom position

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2373]
When we reach the end of a list, we can notice a small gap between scroll bar and frame.
![image](https://user-images.githubusercontent.com/55348946/102006551-14693e00-3d33-11eb-8e25-9c6c5d35adc5.png)

**Comment by ihhub** [comment]
#2374 is the same as this issue. The problem lies in `Splitter` class where we calculate fixed step and use it for position of the scrollbar which is not accurate leading to situations above.

**Comment by Branikolog** [comment]
The thing is that not all vertical scroll bars have this issue.
