### ISSUE TITLE
Hero near the enemy group gets in the fight immediately

### ISSUE THREAD

**Issue by andrey-starodubtsev** [ihhub/fheroes2#238]
If one loads `Alteris` scenario from the original game, after couple of introduction dialogs Ariel the Sorceress is engaged in the battle.

If we start original game (I use HoMM II Gold from GoG, if it's important), hero stays right after the group of zombies but fight doesn't starts automatically.

**Comment by ihhub** [comment]
Could you please attach the screenshot of this case?

**Comment by andrey-starodubtsev** [comment]
Here how it looks in original game:
![Screenshot from 2019-11-21 12-23-51](https://user-images.githubusercontent.com/7666511/69377102-a5025580-0cbc-11ea-8509-742dca62f139.png)

**Comment by ihhub** [comment]
The starting point for this issue is `int Interface::Basic::HumanTurn(bool isload)` function.

**Comment by ihhub** [comment]
As well it's worth to try to have a look into `if(!conf.ExtWorldOnlyFirstMonsterAttack()) myKingdom.HeroesActionNewPosition();`

**Comment by Branikolog** [comment]
Issue came back to life..
While playing Hot Seat we can watch creature attacking hero, before it starts it's turn.
![Attacking creature 2 0](https://user-images.githubusercontent.com/55348946/88560336-ad264800-d036-11ea-97c4-8451b1740648.jpg)

**Comment by ihhub** [comment]
Closing this issue as we removed the option causing the problem.
