### ISSUE TITLE
Adjust fast split logic when targeting another troop of the same type

### ISSUE THREAD

**Issue by eos428** [ihhub/fheroes2#2386]
Recently we have implemented splitting to another troop of the same type. I believe we should look into adjusting the fast splitting logic in this new situation. 

![Screenshot 2020-12-14 201644](https://user-images.githubusercontent.com/38433056/102085657-8469e800-3e49-11eb-8636-255133df89ad.jpg)

In this picture, I would like to split from one power lich troop to the other one. So far so good.

![Screenshot 2020-12-14 201709](https://user-images.githubusercontent.com/38433056/102085663-86cc4200-3e49-11eb-9a99-aee9e9e7fe22.jpg)

From here, notice that we can only fast split to 3-4 slots. I believe the 5th slot should also be available, considering that the 2nd slot is also of the same type (power lich).

![Screenshot 2020-12-14 201722](https://user-images.githubusercontent.com/38433056/102085670-892e9c00-3e49-11eb-8da8-4e9012a18d99.jpg)

The result is that the fast split only takes into account one of the power lich troops. Or more specifically, the split source. The split target is not affected at all despite being the split target.

Here are the changes I propose:
- Accumulate the troops from both the source and target and then split them evenly based on the amount of slots we allocate
- Open up both the source and target slots when fast splitting.

The logic of fast splitting against an empty troop slot should be unaffected.

**Comment by LeHerosInconnu** [comment]
Hello @eos428,

For me, it works fine this way.

The user wanted to adjust the amount of creatures in both troops, but he changed his mind and used the fast separation in the free slots.

If the user wants to adjust the amount of creatures in both troops, he has to go all the way to the end and indicate the number of creatures to move in the other troop (without using the fast separation buttons).
If the user wants to separate all the creatures of the two troops in the five slots, he must first reunite the two troops and only then use the fast separation in the other four slots.

The result in the last screen is okay for me. :)

On the other hand, it would be necessary to add a fast separation button "2" in the second screen, to be able to separate only the first troop in two slots, thus obtaining 25 creatures in the first slot (the initial slot), 50 creatures in the second slot (the second slot is not modified), and 25 creatures in the third slot.

**Comment by eos428** [comment]
Hi @LeHerosInconnu,

What you are saying makes sense. so unless someone else comes in with a differing opinion, I'll implement the logic you proposed instead 👍 

So what I'm thinking would be:
- If splitting to an empty slot, button `2` won't appear since a normal split would create the new troop at the 2nd slot
- If splitting to another troop of the same type (like above), `2` will appear and the split would happen as you suggest

**Comment by Branikolog** [comment]
> On the other hand, it would be necessary to add a fast separation button "2" in the second screen, to be able to separate only the first troop in two slots, thus obtaining 25 creatures in the first slot (the initial slot), 50 creatures in the second slot (the second slot is not modified), and 25 creatures in the third slot.

Why can't we add not only "2" button, but also "3", "4", "5"? So player, that has chosen two stacks of that Liches on the screenshot, can split them into 3, 4 or 5 stacks without cancelling dialog to reuniting all the troops in one stack?

**Comment by LeHerosInconnu** [comment]
Hello @eos428 and @Branikolog,
 
> * If splitting to an empty slot, button `2` won't appear since a normal split would create the new troop at the 2nd slot

After a few thoughts, I think it would be nice to display the "2" button but in its already selected state; this would visually inform the user that if he presses the "OKAY" button the troop will be separated into two troops, which is not the case at the moment (and at the same time it gives a visual indication to the new users that the small buttons with the numbers are clickable).

Also, if the user first clicks the "3" button and then changes his mind, he can select the "2" button instead, which is not possible to do at the moment either.
(Then the "2" button should be displayed in its selected state in the separation window for all cases where it is the default operation when the user clicks the "OKAY" button. If the user changes the amount of creatures to transfer, the "2" button is automatically deselected as usual.)

> * If splitting to another troop of the same type (like above), `2` will appear and the split would happen as you suggest

So yes, and in this case the "2" button is displayed in its non selected state.

Also I suggest in this case to change the number of creatures to be transferred by default to "0" (instead of the number corresponding to half the number of creatures in the starting troop).
This allows to indicate to the user that he is indeed in an action to transfer the number of creatures of his choice from one troop to another troop, and not in an action to separate a troop into two similar troops (its starting action, if the user clicks on one of the buttons of the number of groups of the separation, the number of creatures is adjusted automatically as it should be done (I will report the bug) :) ).

> Why can't we add not only "2" button, but also "3", "4", "5"? So player, that has chosen two stacks of that Liches on the screenshot, can split them into 3, 4 or 5 stacks without cancelling dialog to reunite all the troops in one stack?

With the "5" button added, when the "5" button is selected and the user presses the "OKAY" button the two troops are joined in the background and distributed in the five slots.

This is a good idea in case of two troops of the same type.

But how is it supposed to work when there are three (or four) troops of the same type to start with and the player wants to transfer creatures from the first troop to the second troop?
Should the "5" button also be added to bring the three troops together and distribute them in the five slots? Or should the third troop be ignored and only display the "2", "3" and "4" buttons?

This may become complicated for the user to understand and memorize.

In another issue, I will propose an easier and quicker way to reunite all the troops of the same type in one troop. :)

**Comment by Branikolog** [comment]
> But how is it supposed to work when there are three (or four) troops of the same type to start with and the player wants to transfer creatures from the first troop to the second troop?

In this case we can leave current logic as it is: we split one troop stack over the same type other troop stack, watch normal splitting window, where we can choose the exact number of transferring creatures. Also, here we can add "2" button, so we divide the quantity of creatures in both stacks together into 2 same parts.
For fast uniting multiple(>2) troops into one we are going (or even already) implement Alt button...
And after that we can split the united stack into the needed number of stacks.
Heroes2 has just 5 slots for army, and I believe, there would be not so much cases, where we work with more than two stacks...
Anyway, here I want to note, that it is not possible to implement all split logic via mouse only. We've already made it better, than it was implemented in ex: HoTa, as there we're always need a keyboard and in fheroes2 we can do certain split activities with the help of mouse only.
I think, we need to implement the most useful split logics via mouse, and the rest (Like uniting all stacks in army into one with ALT) implement using buttons on keyboard. I'm not bother clicking a few times more to unite units manually (Or for some other uncommon cases), while playing with mouse only.
If I'm speedrunning the game, I'll definitely have a keyboard and have all the fast splitting/uniting capabilities. 

> With the "5" button added, when the "5" button is selected and the user presses the "OKAY" button the two troops are joined in the background and distributed in the five slots.

We can also implement another logic, if we have a few stacks of the same time and a few spare slots in army:
When fast splitting of two stacks (one stack over another) exceeds the number of free slots, we can take into consideration other stacks of the same time in hero's army and create the needed number of stacks according to fast split button we press.
Here's the example:
Imagine, that we have 3 stacks of troops of the same time and two free slots in hero's army. We're splitting one stack over another and watch common splitting dialog with fast split buttons:
"2" : make two stacks of two selected troops with the same quantity of creatures.
"3" : Divide the sum of these two stacks into three. (And then we have 3 same stacks, one untouched and one free slot)
"4" : Divide the sum of these two stacks into four. (And then we have 4 same stacks and one untouched and 0 free slots)
"5" : In this case we sum all creatures and divide them into 5 stacks.
Also, if at the beginning we have only one free slot, pressing "4" button will sum three stacks together and divide them into 4. (4 exceeds the number of splitting two stacks with + one free slot => we consider all the same type troops in army then.)

> This may become complicated for the user to understand and memorize.

I don't think so. I've been used to current split logic within a few minutes. I believe players would love to use any split logics we'd introduce. Or they always can use simple mouse clicking, if it's too complicated.  :)

> Also I suggest in this case to change the number of creatures to be transferred by default to "0" (instead of the number corresponding to half the number of creatures in the starting troop).

Is a good proposal, but I personally prefer 50/50 to be the default value, as I use this in almost 80% of cases. (While splitting over an empty slot

> This allows to indicate to the user that he is indeed in an action to transfer the number of creatures of his choice from one troop to another troop, and not in an action to separate a troop into two similar troops (its starting action, if the user clicks on one of the buttons of the number of groups of the separation, the number of creatures is adjusted automatically as it should be done (I will report the bug) :) (#2406)).

While splitting over an other stack of the same type I hardly ever decide to add 1/2/3/etc troops. Here I believe is the best solution to make one of your proposals, when we show "2" button already selected (So players would know, that in this default case they are going to equalize this two stacks) and show the number of transferred creatures in a upper box.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

It has to be simple and easy.

Reorganize a troop into several troops:
- Select the starting troop.
- Select an empty destination slot.
- Select the desired number of groups.
- The number of creatures in the starting group is distributed evenly in the number of groups indicated.

Reorganize the creatures of two troops:
- Select the starting troop.
- Select another troop of the same type.
- The indicator for the number of troops indicates "0" to make it clear to the player that the creatures in the starting group will be transferred to the ending group and that the goal is not to equalize the two troops into two equal troops.
- Indicate the number of creatures to be transferred.

If the player wants to equalize two (or more than two) troops into equal troops, he must first join the two troops into one troop.

If there is another troop, or more, of the same type when the player wants to reorganize a troop into several troops or reorganize the creatures of two troops, they are ignored.
If the player wants these troops to be taken into account, he must first bring them together before proceeding to reorganize the troops.

**Comment by Branikolog** [comment]
> * The indicator for the number of creatures indicates "0" to make it clear to the player that the creatures in the starting group will be transferred to the ending group and that the goal is not to equalize the two troops into two equal troops.
> * Indicate the number of creatures to be transferred.

In my personal opinion, the case, when we have two stacks of creatures of the same type and want them be equalized happens more frequently. That's why I want the default state of splitting one stack over another be equalizing.

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

> > * The indicator for the number of creatures indicates "0" to make it clear to the player that the creatures in the starting group will be transferred to the ending group and that the goal is not to equalize the two troops into two equal troops.
> > * Indicate the number of creatures to be transferred.

In the original game, when the player performs this action, the indicator for the number of creatures indicates "0".
Heroes 2 players are used to this mode of operation.

In original game:

![Reorganize troops H2 01](https://user-images.githubusercontent.com/43583994/106034477-406a3400-60d3-11eb-92da-3b4c36e421c6.png)

> In my personal opinion, the case, when we have two stacks of creatures of the same type and want them be equalized happens more frequently. That's why I want the default state of splitting one stack over another be equalizing.

In this case, I think it would be better to add a small button to the left of the indicator for the number of creatures or/and allow a third state of the MAX/MIN button, e.g. "HALF", "1/2", or "50%" to perform this action.
Note: When the user uses this button, the indicator for the number of creatures is updated.

This would allow identical operation in all cases with an additional possibility but "separate" from the standard action.
This screen is for explanatory purposes only.

![Reorganize troops fh2 signe egal button 01](https://user-images.githubusercontent.com/43583994/106035728-ba4eed00-60d4-11eb-9089-4c43d5382c57.png)

**Comment by ihhub** [comment]
Hi @eos428 , haven't we impleneted all the logic in the project?
