### ISSUE TITLE
Splitting troops in a castle and meeting heroes windows doesn't work well

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2389]
We cannot use shift to split one troop from hero to castle garrison. Selected troop with Shift button moves to garrison. Separating troops from hero to empty slot of garrison works only with right click currently. 
![image](https://user-images.githubusercontent.com/55348946/102191723-d868e100-3eca-11eb-9aec-a2bfd9a5847e.png)
![image](https://user-images.githubusercontent.com/55348946/102191747-e159b280-3eca-11eb-90cc-3b789957c8a6.png)
Also, if we hold left mouse button over a troop and move it over empty slot - a common separation dialog appears after releasing mouse button. But when we are trying to drag troop to castle garrison - nothing happens.
All the same is actual for meeting heroes window.

**Comment by Branikolog** [comment]
Also, we cannot split stack of hero army over the stack of the same type in castle garrison using shift button or right click. And reversed action doesn't work too.

**Comment by eos428** [comment]
Assign this one to me too :) So far I managed to get the shift logic working, but not too sure with the dragging one.

Is it okay if we have to select the troop first before dragging it to the other army bar?

**Comment by Branikolog** [comment]
Sure!
I'm also not sure about dragging technique in heroes, as I so got used to use mouse clicking after a years of playing this game. :) Probably, dragging will be useful for newcomers in HoMM series..

**Comment by eos428** [comment]
From a technical POV, trying to get the drag logic working seems to be significantly more work compared to the shift-based one. So I'm not too sure I can get it done quickly. However, my latest PR did give me some inspiration, but we'll see how it's reviewed to see how I'd approach this issue.

As a personal anecdote, I almost always split with hotkeys with HOTA, hence all the recent split-related PRs coming from me :P

**Comment by Branikolog** [comment]
So, you know, what to do. And how should it work. :)
Regarding dragging:
we should make it work everywhere, or just delete. Now, working only in 30% cases it frustrates me. :)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> Regarding dragging:
> we should make it work everywhere, or just delete. Now, working only in 30% cases it frustrates me. :)

Yes, it works well in the hero's screen, it should be possible to make it work in all screens. :)
