### ISSUE TITLE
Troop separation right click shouldn't work over the selected creature

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2390]
If we select any troop and then press right mouse button over the selected troop, we can see a common separation dialog window.
![image](https://user-images.githubusercontent.com/55348946/102192612-0f8bc200-3ecc-11eb-8bbc-e9a4fcac0d05.png)

**Comment by eos428** [comment]
Assign this one to me please, will be making a PR soon along with some other fixes :)

**Comment by Branikolog** [comment]
Sure!
