### ISSUE TITLE
Splitting 1 troop over stack of the same type

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2392]
If we choose a stack with 1 troop and then use right click over second stack with x troops of the same type, these both stacks are swapping:
![image](https://user-images.githubusercontent.com/55348946/102203623-dce8c600-3ed9-11eb-89e8-6e8ffe8100c1.png)
![image](https://user-images.githubusercontent.com/55348946/102203639-e2dea700-3ed9-11eb-8c19-c159335abab5.png)
Actually, this case can be useful, if we want to move a stack with >1 troops among stacks with 1 troop. But this logic doesn't seem to be self-consistent, comparing to other cases of splitting troops.

**Comment by eos428** [comment]
Hi @Branikolog can you check if this is still the case as of the latest commit?

I think one of my previous PRs changed this logic too, albeit accidentally.
Also, just to confirm again in case there's also a regression - are we supposed to initiate splitting on right click in this case, or just open the troop info?

**Comment by Branikolog** [comment]
Hello, @eos428!
Currently, this issue doesn't happen: when we initiate splitting of one troop with right click over other stack of the same type nothing happens. (That's ok, we cannot split 1 single troop.)
But unfortunately, right click splitting over a troop of the same type doesn't work at all. We cannot split any amount of troops over other stack of troops of the same type.
I think, for now we shouldn't perform any action, while trying to split 1 troop over other stack of the same time.  We shouldn't show troop info as well. Just cancel the selection and that's it.

**Comment by eos428** [comment]
I see... we have a regression here then. Although I think the current implementation makes it similar to the original game's logic, where right click will just show the troop info :P

But anyways, can you assign this issue to me? I'll work on it once my latest PR is merged.
