### ISSUE TITLE
Using scrollwheel for changing the quantity of splitting troops

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2393]
Currently, we can use scrollwheel to change the number of troops you're going to split. And this feature is so comfy!
![image](https://user-images.githubusercontent.com/55348946/102206400-95fccf80-3edd-11eb-9607-c08caba9f556.png)
But to be able to use this feature we have to point the box with quantity of troops.
I suggest to expand the area, where we can use scrollwheel to change the quantity. At least over the whole dialog window, as we cannot perform any other action in this window with scrollwheel.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> I suggest to expand the area, where we can use scrollwheel to change the quantity. At least over the whole dialog window, as we cannot perform any other action in this window with scrollwheel.

Yes, I even think it would be nice to extend the area to the whole game screen. :)
