### ISSUE TITLE
Income info window appears while clicking over a small area surrounding "EXIT" button

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2394]
When we use right button over a small black area surrounding "EXIT" button in "Castle View" window, we can still watch an income info window:
![image](https://user-images.githubusercontent.com/55348946/102207656-6f3f9880-3edf-11eb-9eca-f3a5ed2a5eac.png)
![image](https://user-images.githubusercontent.com/55348946/102207701-7ebee180-3edf-11eb-9e82-1bdaddd81431.png)
![image](https://user-images.githubusercontent.com/55348946/102207719-87171c80-3edf-11eb-9cca-a6d3e50a9f61.png)

**Comment by undef21** [comment]
Assign me, please

**Comment by Branikolog** [comment]
Sure!

**Comment by LeHerosInconnu** [comment]
This bug is still present in the castle construction screen.

In fheroes2:

![Income exit construction fh2 01](https://user-images.githubusercontent.com/43583994/103166827-2912ff00-4826-11eb-9d9f-a4a135086dc4.png)

Related to https://github.com/ihhub/fheroes2/pull/2404.

**Comment by ihhub** [comment]
Hi @undef21 could you please make the same changes for the construction screenb as well?

**Comment by ihhub** [comment]
Hi @undef21 could you please make the same changes for the construction screenb as well?
