### ISSUE TITLE
Meeting screen, hero's army doesn't update, if it was adjusted in personal hero info window

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2395]
When we enter hero's info window and change army arrangement there...
![image](https://user-images.githubusercontent.com/55348946/102210921-df501d80-3ee3-11eb-97d7-7a83c4bc611e.png)
![image](https://user-images.githubusercontent.com/55348946/102210696-9009ed00-3ee3-11eb-9419-aaae031a665d.png)
And the exit back to meeting heroes screen army doesn't update, until we make any click over any slot.
![image](https://user-images.githubusercontent.com/55348946/102210765-ad3ebb80-3ee3-11eb-9454-3977311048fa.png)
![image](https://user-images.githubusercontent.com/55348946/102210788-b3349c80-3ee3-11eb-9515-46e04e0119fa.png)

**Comment by ihhub** [comment]
It's easy to fix: call uodate of armybar after closing the window.
