### ISSUE TITLE
Meeting heroes window, swapping armies

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2396]
I suggest using arrows between heroes for fast swapping of armies or artifacts.
![image](https://user-images.githubusercontent.com/55348946/102211275-72895300-3ee4-11eb-8850-63c84c624752.png)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> I suggest using arrows between heroes for fast swapping of armies or artifacts.

Ah yes, it was also on my list, I tried to click on those arrows the first time I played the demo of the game. :D

Maybe in the future it would be nice to make these arrows into buttons to let the user know that the arrows are active and have a function, and also add a right-click information window.

**Comment by Branikolog** [comment]
> Ah yes, it was also on my list, I tried to click on those arrows the first time I played the demo of the game. :D

I've noticed that, while watching of gameplay videos: some people tried that too. 

Creating a button is a tough work... Let's do this area at least clickable for start.)

**Comment by LeHerosInconnu** [comment]
@Branikolog.
 
> I've noticed that, while watching of gameplay videos: some people tried that too.

Yes, I've seen that in videos as well.
These arrows are very tempting. :D

> Creating a button is a tough work... Let's do this area at least clickable for start.)

Without completely redoing a button, using the current arrow graphic and slightly changing the position of the arrow graphic while playing with the shadow to simulate a button being pressed, this should do the trick.
