### ISSUE TITLE
Click over empty slot in hero/town list automatically selects hero or town after pointing it

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2397]
If we make a left mouse click over an empty slot in a hero list and then point any hero - it will be automatically selected. The same works for towns.
Making left click:
![image](https://user-images.githubusercontent.com/55348946/102212804-d3198f80-3ee6-11eb-903e-b3c6459c27a3.png)
Moving mouse over a town:
![image](https://user-images.githubusercontent.com/55348946/102212836-e0cf1500-3ee6-11eb-8c71-0d561a046032.png)
At the time cursor reaches town icon it becomes selected.
Similar problem we had in #2357

**Comment by LeHerosInconnu** [comment]
@Branikolog.

Good catch. :)

**Comment by Branikolog** [comment]
@LeHerosInconnu, thanks! 
But I'm pretty sure, this issue is the same to yours. If you remember recent issue regarding exit button in a castle, there was a small area surrounding button, that belonged to income frame... I think here you found that area under list of heroes and castles, that interactes the same to empty castle/hero list.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Indeed ! Everything works now!
Thanks for your help!
