### ISSUE TITLE
Question/answer doesn't work for barriers and tents

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2400]
Player doesn't receive answer in travelers tent. However, for opening barrier it is not required, To open barrier, player needs only a visited status for a tent. 
![image](https://user-images.githubusercontent.com/55348946/102220104-6ce63a00-3ef1-11eb-940c-88ae297c25b1.png)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

It was really annoying to have to remember the password for the barriers in Heroes 2.

It's a good improvement in fheroes2 that only the condition of having visited the Traveller's Tent can open the Barrier.

Maybe it would be nice to add the "password" in the message window text of the Traveller's Tent and Barrier, but that would just be for fun, without going back to the boring operation of the original game. :)

**Comment by Branikolog** [comment]
I've read somewhere a discussion regarding this topic... Probably here, but couldn't find it with search tool... 


> It was really annoying to have to remember the password for the barriers in Heroes 2.

At the same time, I like the feeling, that I'm doing something special, while entering a password. Something, that depends on my personal skills. So, if I make a mistake - nothing will happen...  How often do we type text in heroes? This is so unusual, and I like it. :)

Also, password can be transferred via not only tent, by event messages, signs, or ally player...  So this expands playing experience. 
So I vote for passwords. )

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> At the same time, I like the feeling, that I'm doing something special, while entering a password. Something, that depends on my personal skills. So, if I make a mistake - nothing will happen... How often do we type text in heroes? This is so unusual, and I like it. :)
> 
> Also, password can be transferred via not only tent, by event messages, signs, or ally player... So this expands playing experience.
> So I vote for passwords. )

Play a XL map over several real days with all the tents and barriers present.

Maybe as an option, let's call it the "masochist" option. :)
But not for me in anyway. :D

**Comment by ihhub** [comment]
A downside of using passwords is inability to enter it if you play a map made in different language which expects answers in that language.

**Comment by ihhub** [comment]
I'm making this topic as a discussion as both solutions have right to exist.
