### ISSUE TITLE
Game freezes while AI captures empty town

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2402]
Blue player enters town, and game doesn't respond after.
![image](https://user-images.githubusercontent.com/55348946/102223843-44ad0a00-3ef6-11eb-93e4-b2b59a85968a.png)
Here's a savefile:
[Game freeze.zip](https://github.com/ihhub/fheroes2/files/5696319/Game.freeze.zip)

**Comment by grasshopper-newt** [comment]
If town/castle has no defenders, this occurs regardless of map.

**Comment by Branikolog** [comment]
@grasshopper-newt, thanks for the precision!  👍

**Comment by ihhub** [comment]
I'll create a pull request today.
