### ISSUE TITLE
Regroup all troops of the same type into one troop, simply and quickly

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2408]
In the hero screen, when the user makes a left click held from a troop, then moves the mouse cursor inside the troop frame without leaving it and releases the left mouse button, all troops of the same type present in the hero's army are regrouped in the initial troop.

While hero is in a meeting with another hero or is inside a city, when the user makes a left click by pressing the "Alt" key on keyboard at the same time, all troops of the same type located in both armies during a meeting and all troops of the same type located in hero's army and garrison when hero is inside a city are regrouped in the initial troop.

The same action as the previous one (grouping all troops of the same type when meeting another hero or inside a city) can also be performed only with the mouse by clicking the initial troop with the mouse wheel button (or the central mouse button).

This should also work in the Kingdom Overview screen.

**Comment by Branikolog** [comment]
@LeHerosInconnu 
> In the hero screen, when the user makes a left click held from a troop, then moves the mouse cursor inside the troop frame without leaving it and releases the left mouse button, all troops of the same type present in the hero's army are regrouped in the initial troop.

I'm not sure, that dragging the same troop within one frame is a good idea, as this can cause a simple click to work as regrouping. 
Adding any key or mouse wheel button seems more accurate for me.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> @LeHerosInconnu
> 
> > In the hero screen, when the user makes a left click held from a troop, then moves the mouse cursor inside the troop frame without leaving it and releases the left mouse button, all troops of the same type present in the hero's army are regrouped in the initial troop.
> 
> I'm not sure, that dragging the same troop within one frame is a good idea, as this can cause a simple click to work as regrouping.
> Adding any key or mouse wheel button seems more accurate for me.

The goal is to use only the mouse to perform the action.

Mouse wheel and mouse button are already used elsewhere.

For the action to be enabled there may be a condition that the mouse cursor should have moved x pixels (say at least 10 pixels) between pressing and releasing the left mouse button, this would prevent a "messed up" left click.

**Comment by Branikolog** [comment]
If player would try to drag troop somewhere and suddenly change his mind, he would return cursor back and release button, what will cause a mess with uniting all troops. 
Well, actually, I don't feel, that fast uniting is so useful to have it among mouse interaction list. Don't forget, that we have just 5 slots, not 7, like in H3. And also uniting manually is not such a hard task, comparing to splitting...

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> If player would try to drag troop somewhere and suddenly change his mind, he would return cursor back and release button, what will cause a mess with uniting all troops.

Yes, I see what you mean. :)

With a left click held and a right click then.

> Well, actually, I don't feel, that fast uniting is so useful to have it among mouse interaction list. Don't forget, that we have just 5 slots, not 7, like in H3. And also uniting manually is not such a hard task, comparing to splitting...

Anyway, this can be put on hold for now. :)
