### ISSUE TITLE
Small adjustment needed for current fonctioning when the castle troops join the defending hero when there is room

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2418]
In fheroes2, the troops are not positioned correctly at the beginning of the combat.

Related to: https://github.com/ihhub/fheroes2/pull/2092.

Position of the troops before the combat:
![Troops position fh2 01](https://user-images.githubusercontent.com/43583994/102479360-172fa000-405f-11eb-9c4d-295f6f1800a3.png)

Incorrect position of the troops during the combat:
![Troops position fh2 02](https://user-images.githubusercontent.com/43583994/102479391-21ea3500-405f-11eb-80e7-7c6cd2758f8c.png)

Position of troops that should have been applied during the combat:
![Troops position fh2 03](https://user-images.githubusercontent.com/43583994/102479417-29a9d980-405f-11eb-8517-5a51c5938ae1.png)

End the turn.

Here is the save file:
[Troops position auto fh2 01.zip](https://github.com/ihhub/fheroes2/files/5708830/Troops.position.auto.fh2.01.zip)

**Comment by ihhub** [comment]
Hi @idshibanov , didn't you fix this issue some time ago?

**Comment by LeHerosInconnu** [comment]
@ihhub.

This adjustment has not yet been made.
This remark is still valid.
