### ISSUE TITLE
Adventure map, level of the music decreases when there are "effects" of sound played at the same time

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2423]
When the "MUSIC" folder is not present, or when the "MUSIC" folder is present and the "Music Type" is set to "MIDI" or "MIDI Expansion", the level of the music decreases when there are "effects" of sound played at the same time.

Here are the save file and a video that show the bug encountered:
[Bug music level near stone fh2 01.zip](https://github.com/ihhub/fheroes2/files/5710799/Bug.music.level.near.stone.fh2.01.zip)

**Edit 2020/12/19.**

The difference in the level of the music is easily heard in the video:

https://user-images.githubusercontent.com/43583994/102690215-2d2a9580-4204-11eb-9d4f-814ee08c6876.mp4

**Comment by Branikolog** [comment]
Actually, a cannot hear the difference.)

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

> Actually, a cannot hear the difference.)

With which software did you test?

With VLC Media Player, the sound level seems to be correct.
It is easier to hear the level difference with OpenShot or Shotcut.

**Comment by Branikolog** [comment]
@LeHerosInconnu 
I've played your video in a common WP for Win8.1.
I can say even more, in game I can hear music OK. 
I only noticed, that sounds sometimes too quiet, when there's any other sound playing in OS or I'm running a couple of games at the same time...

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> @LeHerosInconnu
> I've played your video in a common WP for Win8.1.
> I can say even more, in game I can hear music OK.
> I only noticed, that sounds sometimes too quiet, when there's any other sound playing in OS or I'm running a couple of games at the same time...

I can only suggest that you try it with Shotcut.
It's open source and portable (no installation).
https://shotcut.org/blog/portable-app/

**Comment by Branikolog** [comment]
We need someone more to confirm this issue. As I hear music ok in game..

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> We need someone more to confirm this issue. As I hear music ok in game..

Okay.

**Comment by ihhub** [comment]
All music during the video stays at the same level.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> All music during the video stays at the same level.

On the video, we can see that the sound of the effects completely "crushes" the sound of the music.
This gives the impression that the music level is dropping.
For my part, I perceive the level of the music which lowers when the sound of ambience of the Stone Lith is played.

You can also notice that there is not really a difference between the "5" and "10" level settings for the effects sound.

In fheroes2:
Activate the sound of the video.

https://user-images.githubusercontent.com/43583994/115969943-c6b1dd00-a53f-11eb-850c-6fb37c722979.mp4

It's pretty much the same in the original game.

In original game:
Activate the sound of the video.

https://user-images.githubusercontent.com/43583994/115969971-f4972180-a53f-11eb-9739-868f0e9e2e53.mp4

https://user-images.githubusercontent.com/43583994/115970009-1d1f1b80-a540-11eb-81f3-469ffd497eb5.mp4

**Comment by LeHerosInconnu** [comment]
Another save for this.
Switch between the first two heroes in the list.

Here is the save file:
[Sound volume different 01.zip](https://github.com/ihhub/fheroes2/files/7594472/Sound.volume.different.01.zip)

**Comment by ihhub** [comment]
We fixed this issue some time ago while rewritting the code for MIDI music handling.
