### ISSUE TITLE
Combat, Dwarves and Battle Dwarves must not resist the creatures' ability during combat

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2425]
In fheroes2, Dwarves and Battle Dwarves must not resist the creatures' ability during combat:
- "Curse" ability from Mummy and Royal Mummy
- "Paralyze" ability from Cyclops
- "Blind" ability from Unicorn
- "Stone" ability from Medusa

In the original game, this does not happen.

Dwarves and Battle Dwarves should resist only when a **spell** is cast by the hero, not at an **ability** of creature, even if this ability has the same effect as a spell.

In fheroes2, Dwarves resist the Curse ability from Mummy:

![Dwarves resist mummies spell fh2 01](https://user-images.githubusercontent.com/43583994/102604224-2593bf80-4124-11eb-83c2-3a8de750256f.png)

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu!
Are you sure, that in the OG the don't resist abelites? Could it be just an absence of displaying of this process in the OG in a journal?

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> Hi, @LeHerosInconnu!
> Are you sure, that in the OG the don't resist abelites? Could it be just an absence of displaying of this process in the OG in a journal?

No, because there is a sound that is played when the Dwarves resist a spell. :)

**Comment by Branikolog** [comment]
Can the OG not play the sound as well, while resisting the spell? Like nothing happens in UI at all, but the % of resisting works, and the chance of applying the ability still was lowered by dwarves.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> Can the OG not play the sound as well, while resisting the spell? Like nothing happens in UI at all, but the % of resisting works, and the chance of applying the ability still was lowered by dwarves.

Why would it be done this way?
By changing the operation for Dwarves who resist.
Also, the creature's abilities already work with a percentage of chance, it would be a double penalty.

I think the best would be to check the source code if it's possible.

**Comment by Branikolog** [comment]
> Why would it be done this way?

You know, the original game has lots of flaws.

> I think the best would be to check the source code if it's possible.

Let's wait for a feedback of our team then. :)
