### ISSUE TITLE
Adventure map, there is a shadow area (darker pixels) in the trees to the north of the treasure chest

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2426]
In fheroes2, there is a shadow area (darker pixels) in the trees to the north of the treasure chest.
These darker pixels do not disappear when the treasure chest has been picked up.

In fheroes2:

![Shadow tree chest fh2 cercle 01](https://user-images.githubusercontent.com/43583994/102610378-617f5280-412d-11eb-927a-0b567293739a.png)

![Shadow tree chest fh2 cercle 02](https://user-images.githubusercontent.com/43583994/102610385-6512d980-412d-11eb-836f-3796b087328b.png)

Compare the area of the same trees in the area surrounded by a red circle and the area surrounded by an orange circle.

Here are the save files (before and after):
[Shadow tree chest before after fh2 01.zip](https://github.com/ihhub/fheroes2/files/5715376/Shadow.tree.chest.before.after.fh2.01.zip)

**Comment by Branikolog** [comment]
Hello, @LeHerosInconnu.
Are You sure, that OG doesn't have same issue?
After deleting the chest there's still dark part in the forest.
It seems to me, there's another tree in the dark area in this circle.
I opened Editor and tried to make the same forest with myself. The original part is in green circle.
![Trees](https://user-images.githubusercontent.com/55348946/102617039-9ac5bb80-4149-11eb-819f-c446b933cf9d.png)
I found out, that dark place doesn't appear while connecting two different objects. (Red circle)
But, when I added one more object with some trees there, the forest became almost the same as original. (Yellow circle)
While in the top of your screenshot we have a single object.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> Hello, @LeHerosInconnu.
> Are You sure, that OG doesn't have same issue?

Effectively, it is also the same in the original game during the game.

> After deleting the chest in editor there's still dark part in the forest.
> It seems to me, there's another tree in the dark area in this circle.
> I opened Editor and tried to make the same forest with myself. The original part is in green circle.
> I found out, that dark place doesn't appear while connecting two different objects. (Red circle)
> But, when I added one more object with some trees there, the forest became almost the same as original. (Yellow circle)
> While in the top of your screenshot we have a single object.

You are right, it comes from the positioning of the objects in the editor.

**Comment by Branikolog** [comment]
This issue relates only the mapmaker, who placed objects on a certain manner. 
Surely, in future, map editor also would be modified to get rid of such textures, while objects being overlapped, but this is another story. ;) 
So, can we close this issue for now?

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> This issue relates only the mapmaker, who placed objects on a certain manner.
> Surely, in future, map editor also would be modified to get rid of such textures, while objects being overlapped, but this is another story. ;)
> So, can we close this issue for now?

Yes.
It's done. :)

**Comment by Branikolog** [comment]
@LeHerosInconnu 
Great work! We together managed to reduce our issue number by one. :)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> @LeHerosInconnu
> Great work! We together managed to reduce our issue number by one. :)

Yes, and without a single line of code. :D
If everything could be that simple. :)

**Comment by Branikolog** [comment]
I'm pretty sure, our main part of team does things in the same manner. They at just telling is, how hard was work, but actually they make it done in a few words typed with keyboard. ;)
