### ISSUE TITLE
Scrolling lists behaviour with arrow keys

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2427]
Currently, while reaching the edge of the list, we can see next page with all new names.
![image](https://user-images.githubusercontent.com/55348946/102618623-2e988700-414c-11eb-9262-3a5eea5763ae.png)
![image](https://user-images.githubusercontent.com/55348946/102618653-39ebb280-414c-11eb-9dbd-3a5e509da1d1.png)
When we come to the end, list shifts partially, as there's only a small part of names left.
![image](https://user-images.githubusercontent.com/55348946/102619000-d2823280-414c-11eb-8912-1c30539d03bc.png)
![image](https://user-images.githubusercontent.com/55348946/102619026-dca43100-414c-11eb-9366-a22755dbbb08.png)
When we decide to scroll back, the next updated list appears shifted  for the amount of names, it was shifted previously, while scrolling down,
![image](https://user-images.githubusercontent.com/55348946/102619327-563c1f00-414d-11eb-90f4-2f1117361e33.png)
![image](https://user-images.githubusercontent.com/55348946/102619345-5b996980-414d-11eb-884a-c97776563af9.png)
The next step goes as usual.
I suggest the list always jump the maximum possible number of names it includes, no matter where it is located at the moment. And small step with remaining names should be the last one,

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

You have not created an issue to make the lists scroll smoothly in all cases (with mouse wheel and with up and down keys), as we have discussed here: https://github.com/ihhub/fheroes2/issues/2420#issuecomment-748095409 - https://github.com/ihhub/fheroes2/issues/2420#issuecomment-748105407 - https://github.com/ihhub/fheroes2/issues/2420#issuecomment-748120154 - https://github.com/ihhub/fheroes2/issues/2420#issuecomment-748175158, and this new issue is the opposite of a smooth operation when using lists with arrow keys. :)

> @Branikolog.
> If it's the list that "jumps" the problem, it is to be done in such a way that the list does not jump, neither with the mouse wheel, nor with the up and down keys. :)

> We have to decide whether list should jump or not. Currently, scrolling with mouse works smoothly, and with keyboard it jumps.

> @Branikolog.
> 
> > We have to decide whether list should jump or not. Currently, scrolling with mouse works smoothly, and with keyboard it jumps.
> 
> I've always found these lists that "jump" a bit awkward.
> For me, it would be preferable that the lists scroll smoothly in all cases, rather than jumping as it does now with the up and down keys.
> 
> > Anyway, I think two current issues should be separate, as we're talking about different problems.
> > This issue is about inability to use mouse scroll, and yours is about the logic of scrolling (moving the "yellow" selection down or not).
> 
> Yes, you can create a new issue to make the lists scroll smoothly in all cases (with mouse wheel and with up and down keys).

> @LeHerosInconnu
> Between, I like your idea of smooth continuous scrolling. ;)
> I hope, in future our team will implement it.)

So what should we do?

**Comment by Branikolog** [comment]
Hello, @LeHerosInconnu!
I'm sorry, I forgot about that discussion!
Definitely, you're right, all scrolling should be the same type.
Here, I couldn't stop myself, while watching incorrect operation, no matter if this operation should be changed. :) 
In the OG, while using a keyboard, we can smoothly move the whole list for one name per each button pressing. So we need to make the same in fheroes2.
