### ISSUE TITLE
Screen focuses on AI hero, while he is hidden under a fog

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2432]
I'm not sure, that AI hero standing in a fog close to the palm tree should initiate focus, while moving...
![image](https://user-images.githubusercontent.com/55348946/102642857-5c42f780-416f-11eb-84af-50709399933c.png)
Here's a savefile.
[01 test.zip](https://github.com/ihhub/fheroes2/files/5717137/01.test.zip)
Simply end turn. Screen focuses on a hero moving in a fog.

**Comment by ihhub** [comment]
I'm closing this issue as nobody is able to reproduce it anymore.
@Branikolog , please reopen the issue with a new save attached if you find this behavior.
