### ISSUE TITLE
Adventure map, the second summoned boat is displayed under the first summoned boat

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2434]
In fheroes2, the second summoned boat is displayed under the first summoned boat.

In fheroes2:

![Boat under boat after second summon fh2 01](https://user-images.githubusercontent.com/43583994/102687618-999b9980-41f0-11eb-8e37-f9133e67f516.png)

**Comment by vincent-grosbois** [comment]
What's the issue here?

**Comment by LeHerosInconnu** [comment]
@vincent-grosbois.

> What's the issue here?

The sail of the most southern boat is under the hull of the most northern boat. :D
