### ISSUE TITLE
Adventure screen, make a left click not maintained on certain zones of the screen and move the mouse cursor over the minimap should not change the view of the minimap

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2445]
In fheroes2, make a left click not maintained on certain zones of the screen and move the mouse cursor over the minimap should not change the view of the minimap.

The view of the minimap should change only when the left click is performed in the minimap area.

This flaw is not present in the original game.

In fheroes2:

https://user-images.githubusercontent.com/43583994/102707188-1bdf9880-4299-11eb-8a5f-bb7fa0ce3712.mp4

Similar issue: https://github.com/ihhub/fheroes2/issues/2332.

**Comment by vincent-grosbois** [comment]
Same thing happens also for the heroes / castle list

**Comment by vincent-grosbois** [comment]
I'll do this one if it's ok

**Comment by ihhub** [comment]
@vincent-grosbois sure. I assigned this issue to you.

**Comment by Branikolog** [comment]
This bug is also gone.
Thanks, @oleg-derevenetz, for fixing it!
