### ISSUE TITLE
Adventure screen, clickable area of the buttons for heroes in the hero list is shifted right and down from the button position with the hero's portrait and frame, same for castles

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2446]
In fheroes2, the clickable area of the buttons for heroes in the hero list is shifted right and down from the button position with the hero's portrait and frame, same for castles.

In fheroes2:

https://user-images.githubusercontent.com/43583994/102707616-e8067200-429c-11eb-8393-8fb61489c225.mp4

**Comment by Branikolog** [comment]
@LeHerosInconnu, Good catch!
I've done similar thread, regarding clickable area of wells...
I expect a lot of GUI elements have same problem. I think, we can find more stuff like this...

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

> @LeHerosInconnu, Good catch!

Yes, thank you. :)

> I've done similar thread, regarding clickable area of wells...
> I expect a lot of GUI elements have same problem. I think, we can find more stuff like this...

There are also many similar cases with the creatures' dwellings in the screens of the different castles, same for the moat, etc., etc., etc. etc.
There will be dozens and dozens of issues just for that.
The issue counter is not close to being at "zero issue". :-1: 

I don't know if this is really the right way to deal with all these problems.
Have you seen this: https://github.com/ihhub/fheroes2/discussions/2448?

**Comment by vincent-grosbois** [comment]
Hello
I'll take that one if it's ok, I've seen where it is in the code that needs fixing
