### ISSUE TITLE
Interface setting in "Evil" or "Good" mode is not retained when the user goes to the Home screen and returns to the game

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2450]
In fheroes2, the interface setting in "Evil" mode or "Good" mode is not retained when the user goes to the Home screen and returns to the game.
In the example, when the user returns from the Home screen, the interface should be "Good".

In fheroes2:

https://user-images.githubusercontent.com/43583994/102710767-daf57d00-42b4-11eb-801d-31b317641d33.mp4

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu 
Couldn't reproduce your issue in such way. I found out that the game always starts with good interface mode until you've set in CONFIG menu the "Evil" interface. And no matter, what kind of interface you've chosen in game System Options, It will always run according to setting in CONFIG menu. 
Are you sure, you haven't set "Evil" in config in this example?

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> Hi, @LeHerosInconnu
> Couldn't reproduce your issue in such way. I found out that the game always starts with good interface mode until you've set in CONFIG menu the "Evil" interface. And no matter, what kind of interface you've chosen in game System Options, It will always run according to setting in CONFIG menu.
> Are you sure, you haven't set "Evil" in config in this example?

Not sure about that.
I'll do some tests later.

But in any case, if the user makes changes anywhere in the interface, they must be taken into account.

Also I think that the option "game: use evil interface" should be removed from the options in the "Experimental Game Settings" window.

**Comment by Branikolog** [comment]
@LeHerosInconnu.
For the case, when player makes changes and saves the game - changes in a savegame should be applied after loading. I'm agreed.
But what about the case in your video? You've started a new game. Should we save interface type? New Game always starts on "good" interface... Is it ok for the case, when player start new game, he start with some non-default options applied... New game = default options?

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> @LeHerosInconnu.
> For the case, when player makes changes and saves the game - changes in a savegame should be applied after loading. I'm agreed.
> But what about the case in your video? You've started a new game. Should we save interface type? New Game always starts on "good" interface... Is it ok for the case, when player start new game, he start with some non-default options applied... New game = default options?

Changes made by the player should always be saved, even the next time the program is started.
It works this way in the original game.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

It's heavily broken. :-1: 

In fheroes2:

https://user-images.githubusercontent.com/43583994/102716213-a694b780-42da-11eb-8f5c-8d30e82e9b7f.mp4

**Comment by Branikolog** [comment]
@LeHerosInconnu.
Yes, @ihhub already knows about this issue with CONFIG.
Cannot say, it's sooo "heavily". ))

**Comment by Branikolog** [comment]
I've checked the OG. It works simply there: once you've changed GUI "Evilness", it will be evil everywhere. Each time you load, or start new game. That's true.
In my personal point, I'd prefer to save a type of GUI into a savefile, so if I play one scenario in evil form, it should be loaded with evil GUI. But when I load another scenario, for which I had chosen a "Good" GUI, the game should remember that and show "Good" GUI...
But currently, interface works incorrectly, comparing to OG.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> ...so if I play one scenario in evil form, it should be loaded with evil GUI. But when I load another scenario, for which I had chosen a "Good" GUI, the game should remember that and show "Good" GUI...

In fheroes2, the "Interface Dynamic" setting of the original game is missing: https://github.com/ihhub/fheroes2/issues/1329. :)

**Comment by Branikolog** [comment]
@LeHerosInconnu 
Isn't the dynamic interface just chooses the default type for playing game, according to the race selected?

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> @LeHerosInconnu
> Isn't the dynamic interface just chooses the default type for playing game, according to the starting race selected?

If you start a scenario with the dynamic interface, the game will select the interface accordingly.
If you change the interface during the scenario, the program will remember it the next time the game loads.

**Comment by LeHerosInconnu** [comment]
Hello @zenseii,

The problem described in the original post seems to be solved.
I will do a test of functioning in the original game later and open another issue if necessary.
Thanks for your comment.
I close this issue.
