### ISSUE TITLE
Mouse cursor doesn't move in mouse emulation mode

### ISSUE THREAD

**Issue by dimag0g** [ihhub/fheroes2#2455]
Steps to reproduce:
- Build with SDL2 and define `WITHOUT_MOUSE`
- start mouse emulation using config file or by forcing `emulate_mouse = true`

Expected behavior: 
- the cursor position moves with arrow keys 
- the cursor tile (arrow) position is updated

Actual behavior: 
- the cursor position moves with arrow keys
- on platforms with mouse support (I used Debian Buster) the cursor tile stays at the mouse position.
- on platforms with no mouse (I used Nintendo Switch, where `SDL_ShowCursor` is a no-op), no cursor tile is displayed.

I think `emulate_mouse` should switch the game to software cursor rendering for mouse emulation to work correctly.

**Comment by Northfear** [comment]
emulate_mouse may be broken since last release. And SDL2 code is using hardware cursor by default, so it's probably a better idea to use the fallback code for Switch.
You can use PS Vita port as a base for Switch BTW. It already has all of the input stuff in it.
https://github.com/Northfear/fheroes2-vita

**Comment by ihhub** [comment]
I think it's time to add some code for mobile platforms into main code base.
@dimag0g could you please create a fork of this project and add needed changes with making a pull request here? Then we can detect needed changes for both platforms.

**Comment by dimag0g** [comment]
@Northfear thanks, I'll look into your repo (I took some code from fheroes2enh for now, which may have borrowed it from you). However, I'd like to make platform-independent changes where possible, and mouse emulation is one of such things. I plan to fix the problem on Debian first, and perhaps submit a PR, then add more plaftorm-specific code specifically for Switch if necessary.

**Comment by dimag0g** [comment]
@ihhub, I managed to get the cursor working by essentially falling back to SDL1 cursor handling code if WITHOUT_MOUSE is defined. The modification is literally two lines,

    #if SDL_VERSION_ATLEAST( 2, 0, 0 ) && !defined(WITHOUT_MOUSE)

one in `screen.cpp:117` and one in `cursor.cpp:29`. Let me know if you want a PR for this trivial fix, as well as for the other one: https://github.com/ihhub/fheroes2/issues/2380

A bigger change I'm working on (adapting what appears to be Northfear's VITA code) is joystick/touchscreen support via `SDL_JOYAXISMOTION` / `SDL_JOYBUTTONDOWN` / `SDL_FINGERDOWN`  etc. In the end I expect this code to be cross-platform. Shall I open a new issue to make my intent known?

**Comment by ihhub** [comment]
Hi @dimag0g does it mean that you still use SDL 2 compilation? If yes you could create a PR and we check it. I think it's a valid change.

Please go ahead and make the fix for #2380 as well if it's a trivial one.

Also you could create a new issue for extra support then we can combine Vita and Switch code and put it into main code base.

**Comment by Northfear** [comment]
I can make a separate PR with gamepad support tomorrow. It's platform independend. Probably just needs a little testing with new fullscreen support.

Touchpad needs a bit more work tho to make it functional everywhere.

**Comment by ihhub** [comment]
Hi @dimag0g does this issue still present?

**Comment by Northfear** [comment]
@ihhub it probably is, since emulate_mouse was removed altogether in https://github.com/ihhub/fheroes2/pull/2424 (it was mostly a part of WinCE)

**Comment by dimag0g** [comment]
I think the issue is gone now since the `Cursor` constructor in `screen.h` activates SW rendering:

        Cursor()
            : _emulation( true )

**Comment by dimag0g** [comment]
The issue is gone now. Actually, the `Cursor` constructor in `screen.h` activates SW rendering, so if I understand this correctly, everyone is using emulated cursor now:

    Cursor()
        : _emulation( true )

You might want to default to non-emulated cursor though, cursor emulation is only really needed on specific platforms such as Nintendo Switch which don't have any system cursor.

**Comment by ihhub** [comment]
Hi @dimag0g ,

`Cursor` is a base class for SDL 1 and SDL 2 implementations. If you check the implementation of `RenderCursor` class for SDL2 you could notice that we set this member into false state:
```
        RenderCursor()
            : _cursor( NULL )
        {
            // SDL 2 handles mouse properly without any emulation.
            _emulation = false;
        }
```

**Comment by dimag0g** [comment]
@ihhub, you're right. The emulation seems to be enabled when a new game controller is connected or open.
