### ISSUE TITLE
Adjustment for option "heroes: allow transcribing scrolls (needs: Eye Eagle skill)"

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2466]
Option "heroes: allow transcribing scrolls (needs: Eye Eagle skill)".

This option has the effect of permanently inscribing the temporary spell of a spell scroll in the hero's magic book.
The spell scroll is consumed during transcription.
The transcription of the spell in the magic book also has a cost in spell points corresponding to the cost of casting the spell.

The hero must have a certain level of the Eagle Eye skill to be able to transcribe the spell depending on the level of the spell.

Eagle Eye Basic: Spells level 1 to level 2
Eagle Eye Advanced: Spells level 1 to level 3
Eagle Eye Expert: Spells level 1 to level 5

The hero must also have the level of Wisdom skill sufficient to be able to transcribe the spell in the magic book.

No Wisdom: Spells level 1 to level 2
Wisdom Basic: Spells level 1 to level 3
Wisdom Advanced: Spells level 1 to level 4
Wisdom Expert: Spells level 1 to level 5

I suggest to adapt the level of spells authorized by the level of the Eagle Eye skill a little (in relation to the required level of the Wisdom skill for learning spells) and to remove the need of the Wisdom skill to transcribe a spell scroll:

Eagle Eye Basic: Spells level 1 to level 3
Eagle Eye Advanced,: Spells level 1 to level 4
Eagle Eye Expert: Spells level 1 to level 5

A sentence must be added after the text already present, separated by a space line, in the information window of the secondary skill Eagle Eye to inform the player of this possibility:

Eagle Eye Basic:

"Allows to transcribe 1st to 3rd level spells from spell scrolls into your Magic Book."

Eagle Eye Advanced:

"Allows to transcribe 1st to 4th level spells from spell scrolls into your Magic Book."

Eagle Eye Expert:

"Allows to transcribe 1st to 5th level spells from spell scrolls into your Magic Book."

In fheroes2:

![Transcribe basic eagle eye fh2 01](https://user-images.githubusercontent.com/43583994/102994648-c0730c00-451f-11eb-9d76-992c228c8f0d.png)

**Edit 2021/01/11.**

After some thought, I think the requirement to have the secondary skill Wisdom should simply be removed.
The hero can use spells of any level contained in a spell scroll, even if he doesn't have the secondary skill Wisdom, so why force him to have Wisdom in order to be able to transcribe the spell.

I edited the first post accordingly.

**Comment by ihhub** [comment]
This feature was removed from the list of options. Closing this issue for now.
