### ISSUE TITLE
AI?

### ISSUE THREAD

**Issue by TIle7** [ihhub/fheroes2#2475]
Hi guys. 
What you are doing is unbeliveable. 
One of the things I do daily is checking if you released a new version.
However, last version, anything seriously done with the AI?
Ai is original game was awful, but here... unplayable. Everything is unbeliveably easy.
I'm still finding AI castles full of armies and AI heroes with almost no armies at all. 
There is zero chalenge, no matter what the dificulty setting is (I use only impossible. But impossible should be renamed to guaranteed... ).
So, if you can work on that a bit more... In any case, great work, thanks a lot and Merry Christmas.

**Comment by ihhub** [comment]
Hi @TIle7 AI is not an easy task to do so it takes time to shape all things up our AI is written from a scratch.

**Comment by ihhub** [comment]
Closing this issue as no work is required for it.
