### ISSUE TITLE
Missing FMVs in "my exotic" version

### ISSUE THREAD

**Issue by J013k** [ihhub/fheroes2#2487]
Hi.

I have a problem with [FMV](https://en.wikipedia.org/wiki/Full_motion_video)s  in "my exotic" PL version of a game.
I additionally copied all the SMK files including `H2XINTRO.SMK` into `Anim` folder.
![https://i.postimg.cc/cHqVsLPw/f-anim.png](https://i.postimg.cc/cHqVsLPw/f-anim.png)

Instead of having any [FMV](https://en.wikipedia.org/wiki/Full_motion_video), I'm getting "kicked" straight into Main Menu.
I tried version 0.8.4 (23 December 2020):
`fheroes2_windows_x64_SDL1`
`fheroes2_windows_x64_SDL2`
None of these versions launch FMVs...

Only when I insert an org CD and launch an org launcher `Heroes2w.exe` everything is fine:
![https://i.postimg.cc/Gh63BrkY/FMV1.png](https://i.postimg.cc/Gh63BrkY/FMV1.png)
![https://i.postimg.cc/yNy7rZ2X/FMV2.png](https://i.postimg.cc/yNy7rZ2X/FMV2.png)

**Comment by ihhub** [comment]
Hi @J013k , video support is done in relation to GOG version of the game. In your case you should copy these files from `anim` folder into `heroes2\anim` folder like one nested folder. However, we will add more code to check both paths.

**Comment by ihhub** [comment]
Hi @J013k , did it help you?

**Comment by J013k** [comment]
I am not sure what do you mean...
Should I change name of my folder from `Heroes of Might and Magic II` to `heroes2`?
Because currently I have all the animations in `...\Heroes of Might and Magic II\Anim` on a HDD
and in `E:\Heroes2\Anim`* on a CD.

[*] - E.g. "E" it is a letter for my optical drive

Additionally these fixes were tagged with 0.9 milestone...
The latest version seems to be 0.8.4.
Or am I missing something?

**Comment by ihhub** [comment]
Hi @J013k ,
- if you unpacked fheroes2 into `E:\Heroes of Might and Magic II` and video files are located at `E:\Heroes of Might and Magic II\Anim` then you need to move Anim folder to `E:\Heroes of Might and Magic II\Heroes2` directory so your animation/video files will be located at `E:\Heroes of Might and Magic II\Heroes2\Anim`.
- tags are for the versions where a bug or feature will be implemented. 0.9 is a future release version.

**Comment by ihhub** [comment]
However, I'll make some changes to detect videos even for your version.

**Comment by J013k** [comment]
*Facepalm*

Sorry about that...
When I copy all the animation into `...\Heroes of Might and Magic II\Heroes2\Anim` I have Intro:
![https://i.postimg.cc/vZ7cHVch/Intro.png](https://i.postimg.cc/vZ7cHVch/Intro.png)
At least `H2XINTRO.SMK` probably because only this intro is supported.

However there is something wrong with "cutscenes" after starting a campaign...
At first I have a corrupted image:
![https://i.postimg.cc/sxSZY0gd/FMV-1.png](https://i.postimg.cc/sxSZY0gd/FMV-1.png)
After one\two second(s) everything seems to fine:
![https://i.postimg.cc/j2XRYz8n/FMV-1a.png](https://i.postimg.cc/j2XRYz8n/FMV-1a.png)

Tested on Win 7 x64.
Tested x64_SDL1 and x64_SDL2 (0.8.4).

**Comment by ihhub** [comment]
Hi @J013k , that's great! I pushed changes to support **Anim** path as well for your Gold version so in the future you won't need to manipulate directories.

**Comment by J013k** [comment]
Thank you.

I am not sure if I am getting retarded or somethings else... 

But do you also have the same problems with cutscenes?

**Comment by ihhub** [comment]
No, we haven't experienced such issues with video playback. It might be that your version of the game has different video file standard or there's something wrong with palette switching in our game.

**Comment by J013k** [comment]
Thanks once again.
Theoretically "my" version has got PL dubbing in FMVs\Cutscenes,
but I'm not sure if there is an another video standard\codec involve in this.

Should I make an another "Issue" or for now leave it as it is?

**Comment by ihhub** [comment]
Hi @J013k please make another issue for video problem so we could track it in the future.
