### ISSUE TITLE
Combat screen, hero's sprite is displayed over the Ballista

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2490]
In fheroes2, the hero's sprite on the right is displayed over the Ballista.

In fheroes2:

![Hero over ballista fh2 01](https://user-images.githubusercontent.com/43583994/103167079-582a7000-4828-11eb-8969-d190803caa3f.png)

**Comment by ihhub** [comment]
Fix issue was fixed some time ago.
