### ISSUE TITLE
Add clang compilation for GitHub Actions

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#2493]
We would like to expand the range of compilers used in our CI/CD pipeline and to add OSX compilation with `clang`. What we need to do is to modify `.github/workflows/osx_pull_request.yml` file to add another entry there just for SDL 2 build. Most likely you have to take a look into `src/Makefile.all` file how we declare the compiler (and linker).
This will help us to add more compilation flags in order to avoid coding mistakes.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub!

In xCode, g++ is the same as c++ and they are both clang:

```
oleg@MacBook-Pro ~ % g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin20.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Are you sure it makes sense to add a separate entry for clang on OS X?

**Comment by ihhub** [comment]
Hi @oleg-derevenetz ,
you might be correct about this. Let me run some tests on our CI pipeline to see how it looks like.

**Comment by ihhub** [comment]
Yes, you're totally right. In this case we could easily add more compilation flags in our pipeline!

**Comment by ihhub** [comment]
From another side, developers stil can't use clang on non-macOS machines :(

**Comment by oleg-derevenetz** [comment]
@ihhub Why? They can install it and then update Makefile to use clang.

**Comment by ihhub** [comment]
That's the problem. Simple change in makefile from g++ to clang doesn't work.

**Comment by qarkai** [comment]
@ihhub, what's the issue with clang compilation? I successfully compiled project with clang using both cmake and make.

**Comment by ihhub** [comment]
Previously we couldn't do that. The idea is to use additional compilation flags present in clang to make the compilation even more stricter but better code.

**Comment by ihhub** [comment]
Closing this issue as irrelevant to focus more on real problems.
