### ISSUE TITLE
Loading a save file, Heroes paths, when the program has just been launched and the user loads a save file (with heroes paths predefined by the player), the heroes paths are not displayed on the adventure map

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2496]
In fheroes2, when the program has just been started and the user loads a save file (with heroes paths predefined by the player), the heroes paths are not displayed on the adventure map.
If the same save file is reloaded (or another save file), then the heroes paths are correctly displayed.

In fheroes2:

![Hero path start load fh2 01](https://user-images.githubusercontent.com/43583994/103177655-a9fce580-487c-11eb-9872-7d1a0aacd27f.png)

![Hero path start load fh2 02](https://user-images.githubusercontent.com/43583994/103177657-acf7d600-487c-11eb-8922-0664bafc9100.png)

![Hero path start load fh2 03](https://user-images.githubusercontent.com/43583994/103177661-af5a3000-487c-11eb-9afb-4fc66c9d7c74.png)

![Hero path start load fh2 04](https://user-images.githubusercontent.com/43583994/103177663-b1bc8a00-487c-11eb-8dd7-221ce1c1cf4a.png)

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu!
Nice precision of my old #731 issue!

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

> Hi, @LeHerosInconnu!
> Nice precision of my old #731 issue!

Oh yes, there are too many issues. :)

**Comment by Branikolog** [comment]
I've just found out, that issue happens also at the case of starting new game and then loading savefile and at the case of loading single player savefile and then multiplayer file.
I believe that would happen, when we load campaign savefiles as well.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog I hope I found the cause of this bug, please update this issue (and reopen, if necessary) if the problem persists after merging of #3088.

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz 
I've tried your fix. Everything seems to work fine!
