### ISSUE TITLE
Combat, attack cursor should adapt its direction according to the possible direction of the attack and in the largest possible area of the hexagon

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2497]
In fheroes2, the attack cursor should adapt its direction according to the possible direction of the attack and in the largest possible area of the hexagon.

In fheroes2, the cursor must not display an attack direction that cannot be performed.
The cursor should automatically display the only possible attack direction and this in the maximum area of the hexagon where the attacked creature is located. (https://github.com/ihhub/fheroes2/issues/501)
In the example, the attack of the Dragons troop will not reach the Gargoyles troop contrary to what the direction of the attack cursor suggests.

In fheroes2:

![Dragon attack direction fh2 01](https://user-images.githubusercontent.com/43583994/103178012-825b4c80-487f-11eb-87f3-5490a7e1882c.png)

![Dragon attack direction fh2 02](https://user-images.githubusercontent.com/43583994/103178010-7f605c00-487f-11eb-89ff-2f303e34c896.png)

In the original game, the cursor adapts its direction according to the possible direction of the attack and in the largest possible area of the hexagon.

In original game:

![Dragon attack direction H2 01](https://user-images.githubusercontent.com/43583994/103178015-8dae7800-487f-11eb-8be6-c14815a6cd64.png)

![Dragon attack direction H2 02](https://user-images.githubusercontent.com/43583994/103178018-9010d200-487f-11eb-9ebe-f73693fcecfc.png)

![Dragon attack direction H2 03](https://user-images.githubusercontent.com/43583994/103178019-92732c00-487f-11eb-8751-e85fbeab573e.png)

![Dragon attack direction H2 04](https://user-images.githubusercontent.com/43583994/103178021-94d58600-487f-11eb-9ff5-981caa645047.png)

![Dragon attack direction H2 05](https://user-images.githubusercontent.com/43583994/103178023-9737e000-487f-11eb-9310-f103ef2afc06.png)

![Dragon attack direction H2 06](https://user-images.githubusercontent.com/43583994/103178025-9901a380-487f-11eb-9fb2-cd29d46deb66.png)

Rialdo attacks Dragontooth.

Here is the save file:
[Flying Hydras fh2 01.zip](https://github.com/ihhub/fheroes2/files/5745048/Flying.Hydras.fh2.01.zip)

**Edit 2020/12/29.**

Related issues: https://github.com/ihhub/fheroes2/issues/1628, https://github.com/ihhub/fheroes2/issues/1629.

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu.
I think this issue happens to the missing direct attacks of 2-hex creatures. We have an #501 issue regarding this.
But I like your comment regarding adaptation of cursor attacking area for the cases, some of directions are impassible.
Can you, please, transform your issue (or create new) so we can investigate and fix the cursor pointing areas?

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> Hi, @LeHerosInconnu.
> I think this issue happens to the missing direct attacks of 2-hex creatures. We have an #501 issue regarding this.
> But I like your comment regarding adaptation of cursor attacking area for the cases, some of directions are impassible.
> Can you, please, transform your issue (or create new) so we can investigate and fix the cursor pointing areas?

I changed the title and modified the first post.

**Comment by Branikolog** [comment]
Well done, @LeHerosInconnu!
Thanks a lot, for finding such issue!
