### ISSUE TITLE
"File to Save:" and "File to Load:" windows, depending on the file name, the date and time on the right side of the list is not vertically aligned

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2501]
In fheroes2, depending on the file name, the date and time on the right side of the list of files to load/save is not vertically aligned.

In fheroes2:

![Alignement date heure fh2 ligne 01](https://user-images.githubusercontent.com/43583994/103178729-cfdab800-4885-11eb-8a8b-65da71ed6346.png)

![Alignement date heure fh2 ligne 02](https://user-images.githubusercontent.com/43583994/103178733-d2d5a880-4885-11eb-83ca-27e831901365.png)

Related issue: https://github.com/ihhub/fheroes2/issues/1892.

**Comment by vincent-grosbois** [comment]
I checked and this is because it's aligned to the right
Is that different in the gog version?

**Comment by LeHerosInconnu** [comment]
@vincent-grosbois.

> I checked and this is because it's aligned to the right
> Is that different in the gog version?

In the original version of the game and in the GoG version, the date and time are not indicated in the file name list.
The file names are centered horizontally in the filename list.

**Comment by vincent-grosbois** [comment]
@LeHerosInconnu 
ok
I'm not sure it's a bug then (?), I mean, it is intended to be aligned on the right for the dates

**Comment by LeHerosInconnu** [comment]
@vincent-grosbois.

> @LeHerosInconnu
> ok
> I'm not sure it's a bug then (?), I mean, it is intended to be aligned on the right for the dates

Not much of a bug, but from an aesthetic point of view, it would be better to align the date and time on the left as is the case with file names when their names are short. :)

**Comment by kant2002** [comment]
![image](https://user-images.githubusercontent.com/4257079/105625322-8fedfd00-5e52-11eb-96ba-5a5566a9d9ef.png)

If implement with alignment of dates on left side, then one character is eats up. Look at the "May 24, 22:29" this looks like longest date which can be here.

**Comment by Branikolog** [comment]
Hummm.
I personally don't like both variants. :(
In the first case we have months that are not vertically aligned from the left side.
In the second case, made by @kant2002, we have time, that is not aligned vertically from the right side...
I propose to separate the days from the time. And then align time to the right edge and days+month to the line, where the widest month+day starts...

**Comment by kant2002** [comment]
1. Align day/month left. Align time left. Original file name length ![image](https://user-images.githubusercontent.com/4257079/105626158-55875e80-5e58-11eb-9012-48f5a9ae3e10.png)
2. Align day/month left. Align time left. Filename length -1 character 
![image](https://user-images.githubusercontent.com/4257079/105626214-88315700-5e58-11eb-9561-7fc440027ae1.png)
3. Align day/month left. Align time right. Filename length -1 character 
![image](https://user-images.githubusercontent.com/4257079/105626269-c890d500-5e58-11eb-8c39-df63befe551b.png)
4. Align day/month right. Align time left. File name length - 1 character 
![image](https://user-images.githubusercontent.com/4257079/105626394-7ef4ba00-5e59-11eb-9c76-c6c8ff904703.png)
5. Align day/month right. Align time right. File name length - 1 character. 
![image](https://user-images.githubusercontent.com/4257079/105626451-d4c96200-5e59-11eb-94f4-a7976e1f7754.png)

Additional variants. Select one which you find better fit. Also I believe that here 2 separate small issues. Alignment and length of the displayed file name. I don't like to cut that portion, but seems do not have an option, if play with alignment..

**Comment by Branikolog** [comment]
@kant2002 

Thanks for introducing so many possible variations! :)

> I don't like to cut that portion, but seems do not have an option, if play with alignment..

Agree with you.
Originally heroes 2 don't have date/time in this list. It was an enhancement of fheroes2 project. Which I really like. Even sacrificing the length of file name...
But now it becomes even shorter... I'm afraid not everyone in our team would like and accept to cut it more....
At the same time, I believe lots of players create their custom names. Shorter, than automatically generated, and aligning of date/time looks preferable in this case...
(Also, in future we can rework automatic name generation and try to make a default names shorter. But that's not priority for now)

Partition of date and time and aligning them separately looks quite good. I like all the variations you've made above! 
I think, I like 1st(or 2nd) the best... We also can try to align time column regarding " : " symbol between hours and minutes...
But anyway, I suggest to wait a bit to listen to opinions of other dev team. )

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog and @kant2002,

For me, the date and time are not necessary.
The file name alone and a sorting according to the last saved file would be sufficient (the last saved file is always at the top of the list). (https://github.com/ihhub/fheroes2/issues/1211)

The month can also be displayed numerically: "05 24, 22:29" instead of "May 24, 22:29".

So this one, with month displayed numerically:

> ![image](https://user-images.githubusercontent.com/4257079/105625322-8fedfd00-5e52-11eb-96ba-5a5566a9d9ef.png)

The display of the month, day and time could possibly be an option, in order not to visually "pollute" the filename list and to allow the display of a longer filename.

And why not also add the year if the player takes his time, more than a year, to play a scenario. Joke Inside® :rofl:

**Comment by ihhub** [comment]
Hi, everyone.

Using digits for months might be a bad idea as we need to keep in mind that 02/03 date could be interpret by european standards as 02 March while in USA it is 3rd of February.

I personally prefer version 4 as it's visually more pleasant. I recommend every one, including @kant2002 vote for one of proposed solutions or keep it as it is.

**Comment by Branikolog** [comment]
@ihhub 
I agree with you, as aligning date to the right reduces the gap between date and time, which can be significant, if we have short month name and 1 day...
But also I like aligning time to the right or to the left not very much... I think , aligning time regarding to the " : " will make that column more or less eye-friendly.
So I vote for 4 variant, but with time centered in a column, where center coincides with " : "

**Comment by kant2002** [comment]
I would vote for Variant 7 where 
6. Align day/month right. Align hours right (end with colon). Align minutes right. File name length - 1 character.
![image](https://user-images.githubusercontent.com/4257079/105721284-995c8f80-5f4e-11eb-90d0-52958446c24a.png)
7. Align day/month right. Align hours right (end with colon). Align minutes left. File name length - 1 character.
![image](https://user-images.githubusercontent.com/4257079/105721528-e0e31b80-5f4e-11eb-9c02-ebe937ae66dc.png)

@Branikolog you can clarify now which option do you like here.

**Comment by Branikolog** [comment]
@kant2002 
7 option is what I was talking about. :) 
In my opinion 7 is the most compacted and at the same time we have two separate information columns (With date and time) which are easily distinguished.

**Comment by ihhub** [comment]
Option **7** is definitely the best one.

**Comment by LeHerosInconnu** [comment]
Thank you @kant2002 for all the visuals of these variants. :)

I also vote for version 7 which seems clearer and more pleasing to the eyes. :)
