### ISSUE TITLE
Adventure map, hero's path shouldn't include a cell close to both creatures

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2504]
While attacking one creature, game creates a path, that causes hero attack both creatures standing close to each other.
![image](https://user-images.githubusercontent.com/55348946/103214580-db7bbc80-4921-11eb-8371-de2a56245106.png)

**Comment by vincent-grosbois** [comment]
Hello,
I can have a look, but do you have a save file for this ?
Also, what is the behavior in the OG ? Should the path to the zombies specifically avoid the tile under the sprites?

**Comment by Branikolog** [comment]
Hello, @vincent-grosbois.
Unfortunately, I cannot provide a savefile right now. Can you wait till tomorrow, please?
Actually, I haven't reproduced this issue in the OG, but I'm pretty sure, the path should include the bottom cell in this area (As I've drawn on a screenshot)
![path2](https://user-images.githubusercontent.com/55348946/103307475-2d573c00-4a21-11eb-9e72-078818d7ebe4.png)

**Comment by vincent-grosbois** [comment]
As you are the person who did the pathfinding, I think you are better suited than me for this issue ;)

**Comment by Branikolog** [comment]
I've checked this issue in original game and there path is completely the same.
My fault. I was confused here because of the issue, where all creatures attack hero, if he stands in a cell close to them. (#1185) That's why I've decided, this path wasn't optimal.

**Comment by LeHerosInconnu** [comment]
Hi @Branikolog,

What is the name of the scenario corresponding to this screenshot?

**Comment by Branikolog** [comment]
@LeHerosInconnu, hi. 
I can't tell right now, as I've left from work. 
I'll write tomorrow.

**Comment by Branikolog** [comment]
> As you are the person who did the pathfinding, I think you are better suited than me for this issue ;)

It was the @idshibanov ,who did this enormous work of creating pathfinding. :)

**Comment by Branikolog** [comment]
@LeHerosInconnu 
Here it is.
[RiddleMe.zip](https://github.com/ihhub/fheroes2/files/5769770/RiddleMe.zip)

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

> I've checked this issue in original game and there path is completely the same.

Although the path is like in the original game, I think the path you proposed (with the arrow with only a green outline) would be more appropriate.

Why don't you open a new issue in that direction?
This would be an improvement over the original game where the hero ends up in a square adjacent to a wandering troop after attacking another wandering troop.

**Comment by Branikolog** [comment]
I thought, it was my excessive hypercriticism.
But if you do agree with me, I'll do an enhancement issue then. :)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> I thought, it was my excessive hypercriticism.
> But if you do agree with me, I'll do an enhancement issue then. :)

Sometimes criticism is good. :)
And the path seems more logical this way. :)
