### ISSUE TITLE
Adventure map, re-centering of the screen should not happen after an AI hero attacks a hero and loses the combat

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2507]
In the original game, during the AI turn, when an opposing hero attacks the hero led by the human player located in a castle, and the AI hero loses the combat, and the human player's turn begins, the screen is already centered on the hero (the one who was defending the castle), so there is no re-centering of the screen.

In fheroes2, in the same case, the screen is not centered on the hero (the one who was defending the castle), so there is a re-centering of the screen that should not happen.

In original game:

https://user-images.githubusercontent.com/43583994/103281810-2eae4780-49d4-11eb-9092-81f3b5c1731d.mp4

In fheroes2:

https://user-images.githubusercontent.com/43583994/103282127-05da8200-49d5-11eb-955c-f624e9f0b49b.mp4

Same for a hero located on the adventure map.

In original game:

https://user-images.githubusercontent.com/43583994/103282597-95ccfb80-49d6-11eb-9f2d-2950ce5e97f7.mp4

In fheroes2:

https://user-images.githubusercontent.com/43583994/103282549-703ff200-49d6-11eb-9799-63052cd96bcf.mp4

Here is the test scenario file:
[AI attacks hero castle.zip](https://github.com/ihhub/fheroes2/files/5750585/AI.attacks.hero.castle.zip)

**Comment by Branikolog** [comment]
Hello, @LeHerosInconnu!
Can you explain a little bit more of this issue, please?
Does screen needed to be focused on a winner of the battle, after the battle is over, right? 
Will this re-focus happen before vanishing animation of attacking hero or after it? 
Will a battle between two AI have the same behaviour of screen focusing?

**Comment by vincent-grosbois** [comment]
@Branikolog 
I didn't see your message before
I've made a tentative PR to fix this. It fixes the problem but indeed it's not very clear what is the regular behavior

**Comment by LeHerosInconnu** [comment]
@Branikolog and @vincent-grosbois.

> Hello, @LeHerosInconnu!
> Can you explain a little bit more of this issue, please?
> Does screen needed to be focused on a winner of the battle, after the battle is over, right?
> Will this re-focus happen before vanishing animation of attacking hero or after it?

In the original game, after the combat, the defending hero is centered (in the background) before the attacking hero disappears.

In original game:
Open the two images in different tabs in your browser and switch between the two tabs alternately.

![vlcsnap-2020-12-29-22h03m53s468](https://user-images.githubusercontent.com/43583994/103314704-1534ec00-4a24-11eb-8884-eae042c0dabb.png)

![vlcsnap-2020-12-29-22h04m39s735](https://user-images.githubusercontent.com/43583994/103314708-19f9a000-4a24-11eb-9d63-5eb343929f1d.png)

> Will a battle between two AI have the same behaviour of screen focusing?

I didn't do a test, but I think that since the human player is an outside observer (he doesn't see the combat), the screen should be centered on the attacking AI hero and see him disappear without the adventure map screen being changed.
I'll have a look at that later. :)
