### ISSUE TITLE
Hero, Magic Book, spells are not written in the hero's Magic Book at the beginning of the scenario

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2508]
In fheroes2, the spells are not written in the hero's Magic Book at the beginning of the scenario.
It is necessary to end the turn for the spells to be written in the hero's Magic Book.

In fheroes2:

https://user-images.githubusercontent.com/43583994/103283552-286e9a00-49d9-11eb-9f23-9007d3f4b351.mp4

Here is the test scenario file:
[AI attacks hero castle.zip](https://github.com/ihhub/fheroes2/files/5750585/AI.attacks.hero.castle.zip)

**Comment by vincent-grosbois** [comment]
I'm wondering if this is the same for hero bonuses that you get when visiting a castle
But I don't think it existed yet in Heroes 2

**Comment by LeHerosInconnu** [comment]
Hello @vincent-grosbois,

> I'm wondering if this is the same for hero bonuses that you get when visiting a castle
> But I don't think it existed yet in Heroes 2

In Heroes 2, there are only temporary bonuses for Morale (Tavern, Barbarian's Castle), Luck (Sorceress' Castle) and Spell Power (Necromancer's Castle) when the hero (or Captain) defends the castle.
