### ISSUE TITLE
Replace every occurrence of std::mem_fun_ref by normal function call 

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#254]
We have many place in code where we use `std::mem_fun_ref` function which is deprecated in **C++11**. We would like to remove the usage of this function to be able to add C++11 in future.

**Comment by idshibanov** [comment]
What do we replace them with? Plain for loops and function calls? I think that both lambas (ideal choice imo) and std::mem_fn are C++11 features, so we'll have to update compiler config first. It should compile even now.

**Comment by ihhub** [comment]
Hi @idshibanov , it's better to replace them by normal loops.
