### ISSUE TITLE
Suggestion for "View World" windows

### ISSUE THREAD

**Issue by vincent-grosbois** [ihhub/fheroes2#2542]
Here are some proposals for an improvement of the view world windows (and "view all", "view artifacts" etc windows)

- once one of these spell is cast, casting it again on the same turn is free
- once "view all" spell is cast, going on the "view world" window opens the window for "view all" spell
- binding the "view world" window to the scroll wheel from the world map, ie it dezooms the world map when you scroll. Normally in the "view world" window the different zoom levels can be switched with the scroll wheel as well

what do you think?

**Comment by LeHerosInconnu** [comment]
Hello @vincent-grosbois,

> Here are some proposals for an improvement of the view world windows (and "view all", "view artifacts" etc windows)
> 
> * once one of these spell is cast, casting it again on the same turn is free
> * once "view all" spell is cast, going on the "view world" window opens the window for "view all" spell
> * binding the "view world" window to the scroll wheel from the world map, ie it dezooms the world map when you scroll. Normally in the "view world" window the different zoom levels can be switched with the scroll wheel as well
> 
> what do you think?

I'm currently working on a suggestion for the "View" spells.
I would normally post it tomorrow.
I think you'll be happy. :)
Stay tuned. :)

**Comment by LeHerosInconnu** [comment]
@vincent-grosbois.

> I'm currently working on a suggestion for the "View" spells.
> I would normally post it tomorrow.
> I think you'll be happy. :)
> Stay tuned. :)

Here is the suggestion: https://github.com/ihhub/fheroes2/discussions/2544.

**Comment by vincent-grosbois** [comment]
I close this because it's duplicated idea with the link
