### ISSUE TITLE
Game should ask if player wants to retreat during auto battle

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2554]
Currently, AI retreats on its own will, when we use auto battle and AI feels, the battle is going to be lost. Without asking a permission from a player.
I think, there should appear a dialog, where player can choose an action. 
This was implemented in Heroes3, where we could see something like: " [Name of hero] feels, he can lose this battle and suggests you to run away." [Yes]/[No]

**Comment by ihhub** [comment]
As a temporary solution we disable retreat ability for auto battle.

**Comment by ihhub** [comment]
Closing this issue as a duplicate of #1832.
