### ISSUE TITLE
Optimize include files (include what you use)

### ISSUE THREAD

**Issue by dimag0g** [ihhub/fheroes2#2559]
I wonder is such kind of optimization would be welcome:

https://github.com/dimag0g/fheroes2/commit/53a3569e144152064d84947abb5aacb0871c4074

The current principle I apply is:

- if a unit includes a header directly without using any definitions from it, remove the include line
- if a lot of units include a header indirectly (via intermediate headers) and only a few units actually use it, remove the indirect inclusion and include the header only in units using it
- if a lot of units include a header file indirectly and many of them use it, leave that header alone

In the current code, virtually every engine header file is included in `engine.h`, which in turn gets into `gamedefs.h` and makes its way to almost every compilation unit. Some of those header files are actually used very sparingly, like `audio_cdrom.h`. This IMO obfuscates the dependencies between the units which are more obvious with "include what you use" rule.

A more drastic change would be to e.g. stop including `serialize.h` globally and only include it in headers which define classes with `StreamBase` dependencies. Similar changes could be done for `translations.h`, `rand.h`, `system.h` etc. I don't want to do this work unless it's actually needed of course.

**Comment by ihhub** [comment]
Hi @dimag0g , it is a well-known issues with current project. The structure was made before us and we have already done many changes to decouple the code.
Decouping always reduces compilation time and of course such work is needed in order to speed up our CI/CD servers.

**Comment by ihhub** [comment]
@dimag0g , you should go ahead and do decoupling as you've done some background work.

**Comment by dimag0g** [comment]
@ihhub Thanks. Let me know if you want me to make a PR with the current changes, or make more changes (perhaps decouple serialize.h) before I come up with a PR. Or maybe you have something else in mind.

**Comment by ihhub** [comment]
@dimag0g the rest of changes seems not that trivial and require more code refactor. You can create a PR just for these changes and later decouple more dependencies in a separate PR.

**Comment by dimag0g** [comment]
@ihhub,

I have made another PR (#2611), let me know if you don't like something about it so I can fix it if necessary.

I expect to create a final PR in about 1 week, this time optimizing `system.h` and `settings.h`. I understand that a lot of units include those just to use the `DEBUG` macro.  My plan is to create a separate header (`logging.h`?) with just the logging functionality and include it as appropriate, so that `system.h` and `settings.h` are only included in parts of the code which actually deals with system and settings. Additionally, I want to introduce a new compile-time switch, `WITH_LOGFILE`, which will be automatically set on platforms with no console (such as Android/Nintendo Switch), but could be set manually via the Makefile in order to use the logfile on Linux/Windows as well. How does that sound?

**Comment by ihhub** [comment]
Hi @dimag0g ,

My apoligies for a late response. Putting the code into logging.h is a great idea for decoupling the code. However, let's proceed with no `WITH_LOGFILE` flag for now. Having already many flags is troublesome for maintainance. We could always identify the platform and set just empty macros for it. Also since we're change it please rename `ERROR` macro to something similar as such macro is defined in Windows headers and we have compilation warnings for this.

XML support is partially dead and most likely we're going to drop it in the future in favor for JSON. One of our compilation servers (**scan-build**) use a build with no XML. Without this flag we have unwanted compilation warnings coming from tinyxml library which is not a part of our project.
