### ISSUE TITLE
Movement penalty operation and switching

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2575]
Currently, movement penalty turns on, when we select "Show visited content from objects" option in CONFIG menu. Which is not obvious.
I suggest adding a separate option in CONFIG menu for switching on penalty description.

**Comment by LeHerosInconnu** [comment]
Oh, nice catch. :)
Yes, this option should be independent.

In fheroes2:

![Terrain penalty near hero display 01](https://user-images.githubusercontent.com/43583994/104229755-f46d8d00-544c-11eb-9d93-aaf702557aa4.png)

![Terrain penalty near hero display 03](https://user-images.githubusercontent.com/43583994/104230064-59c17e00-544d-11eb-8dfc-21e4ed896798.png)

![Terrain penalty near hero display 02](https://user-images.githubusercontent.com/43583994/104229764-f6cfe700-544c-11eb-9f3e-40ba0154b768.png)

**Comment by Branikolog** [comment]
@LeHerosInconnu, thanks!
I was just looking for the way to turn it on for about 15 minutes. :)
Somehow the option regarding object info was turned off and I was confused by the missing penalty description, which I've noticed.)

**Comment by vincent-grosbois** [comment]
I don't even get what's the point of this movement penalty box...
Is it normal that it shows only for nearest tile, or is it a bug?

**Comment by Branikolog** [comment]
@vincent-grosbois 
I can say for now it's something like a hint for a player. He can find out, what is the penalty at different terrains.
In future, we're planning to evolve this feature, so we can find out how many movement points player would waste, while traveling over the path created.

**Comment by LeHerosInconnu** [comment]
@vincent-grosbois and @Branikolog.

Yes, in its current operation, I also find this feature to be almost useless. :)
I made a related proposal here: https://github.com/ihhub/fheroes2/issues/2198.
