### ISSUE TITLE
Main menu, game allows to choose the color, which is not supposed to be human player

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2578]
fheroes2:
![image](https://user-images.githubusercontent.com/55348946/104198820-bfa30b00-5437-11eb-856f-ee1f2af91732.png)
The same map in OG:
![image](https://user-images.githubusercontent.com/55348946/104198894-d9445280-5437-11eb-9651-6cf5dae45d76.png)

**Comment by ihhub** [comment]
This is a special map case: the map has loss condition of specific hero which is under Green hero possession while in multiplayer this map allows to particiate 2 human players. We need to add logic to handle this special case.
