### ISSUE TITLE
Summon Boat spell, selection of the boat summoned when casting the "Summon Boat" spell

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2580]
For the selection of the boat summoned when casting the "Summon Boat" spell, I suggest that it works this way:
- the free neutral boats (empty boats at the beginning of the scenario) must be summoned first according to their distance, the closest one first,

- a boat that has just been summoned is ignored for subsequent summonings as long as the hero is located in the same square where it was during the previous summonings,

- then are summoned the empty boats built in the player's castles in the reverse order of construction in time (the one built most recently first, then the one built just before, or the new one built just after the first summoned boat was built, etc.), 

- then if the hero casting the spell occupied a boat, that boat is summoned first, unless that boat is already located in a square adjacent to the hero casting the spell,

- then are summoned the empty boats belonging to the player which have been summoned but have not been embarked by a player's hero,

- then are summoned the empty boats freed by the player's other heroes in relation to time, the one freed longest ago first.

Note:
- When a hero summons a free boat (neutral at the beginning of the scenario), this boat is now considered as belonging to the player who leads the hero, and it cannot be summoned by a hero of another player.

- When a player builds a boat in one of his castles, this boat is considered as belonging to the player and cannot be summoned by a hero of another player.

- Similarly, when a hero boards a boat built by another player, or invoked or previously occupied by a hero of another player, that boat is now considered as belonging to the player and cannot be summoned by a hero of another player.

Precisions:
In Heroes 2, the Summon Boat spell does not create a boat.
In order to summon a boat, there must be a neutral boat on the map (empty boat at the beginning of the scenario), or the player must build a shipyard and then build a boat, or use another player's boat (the boat is then marked as his own, because the hero was the last occupant) and disembark from that boat.

**Edit.**

Related issue: https://github.com/ihhub/fheroes2/issues/2175.

**Comment by Branikolog** [comment]
Hello, @LeHerosInconnu 

> * When a hero summons a free boat (neutral at the beginning of the scenario), this boat is now considered as belonging to the player who leads the hero, and it cannot be summoned by a hero of another player.

Are you sure, it's the original behaviour? I supposed, that boats only marked as belonging to a certain player only after boarding on any or being built in a shipyard by this player.

> * then if the hero casting the spell occupied a boat, that boat is summoned first, unless that boat is already located in a square adjacent to the hero casting the spell,

So, you're suggesting, that hero will always summon the same boat, he boarded the last time. No matter how far is it and even if there're lots of "summonable" boats nearby?

Actually, I thought that this spell summons always the nearest (except the case, we've summoned some without moving), no matter if it's neutral or belonging to the current player. I think those rules above are too complex to implement. And not so necessary... 

So, If you think, I'm wrong, could you, please, create a discussion, so we could find the best solution together? :) 


P.s.

> * a boat that has just been summoned is ignored for subsequent summonings as long as the hero is located in the same square where it was during the previous summonings

> The solution you propose can be a problem for some scenarios where boats are given to the AI player on the other side of the adventure map.

It sounds, like I can cheat and try deprive some AI of neutral boats, designed to certain areas by summoning 3-4 neutral boats at the beginning of the map. :-P

**Comment by LeHerosInconnu** [comment]
Hi @Branikolog,

The operation and use of the "Summon Boat" spell is a real mess in the original game. :D

Here I'm trying to do something consistent and better than in the original game, also with future possibilities in mind added to the scenario editor:
- In the scenario editor, it should be possible to set each free empty boat to a specific player (or neutral), so the boat is considered one of his own.
- Also, it should be possible to set a hero directly in a boat, just like the hero in the Jail (POL).

> It sounds, like I can cheat and try deprive some AI of neutral boats, designed to certain areas by summoning 3-4 neutral boats at the beginning of the map. :-P

Someway... :)

In original game:

https://user-images.githubusercontent.com/43583994/102687808-1da25100-41f2-11eb-8a56-f887ec66aa28.mp4

Also, you can see that it is not the closest boat that is summoned. :)

I don't know what the original game rules are for the "Summon Boat" spell, all I do know is that it needs to be improved. :)

For the scenarios already created, it cannot be worse than in the original game. :rofl: 
These scenarios can be slightly adapted (with the new possibilities of the scenario editor) for a better game experience (with the possibility of setting an empty boat to a player).

**Comment by LeHerosInconnu** [comment]
Closed to propose another suggestion.
