### ISSUE TITLE
Pathfinding issue, not optimal path

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2583]
Hero has enough movement points to reach the needed cell, but when there's other hero there, hero lacks movement points.
![image](https://user-images.githubusercontent.com/55348946/104313379-fdac3780-54e8-11eb-82d0-03bbb4a6ecdc.png)
![image](https://user-images.githubusercontent.com/55348946/104313611-4ebc2b80-54e9-11eb-89bb-d494c77035df.png)

**Comment by Branikolog** [comment]
Here's a savefile for this issue.
[pathfinding.zip](https://github.com/ihhub/fheroes2/files/5801990/pathfinding.zip)
Also, I've noticed, that in the original game path is created in different way according to the amount of points left:
![image](https://user-images.githubusercontent.com/55348946/104314520-a018ea80-54ea-11eb-90db-3eaa54552666.png)
![image](https://user-images.githubusercontent.com/55348946/104314562-a9a25280-54ea-11eb-9c7b-d31881cd5bbb.png)
![Uploading image.png…]()

**Comment by LeHerosInconnu** [comment]
Just for information, there is a similar issue here: https://github.com/ihhub/fheroes2/issues/2200.
And, there is a related issue here: https://github.com/ihhub/fheroes2/issues/1986.

**Comment by Branikolog** [comment]
Indeed. Thanks, @LeHerosInconnu. Issue list is soo huge now, hard to remember all the issues.)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> Indeed. Thanks, @LeHerosInconnu. Issue list is soo huge now, hard to remember all the issues.)

Yes, it becomes tedious to check if an issue is already reported. :)

**Comment by idshibanov** [comment]
All of issues mentioned here are caused by the same thing: last diagonal move which bypasses regular rules of the game. Technically heroes don't have enough movement points to get there if it's not a "last tile", so this will be a workaround. We're discussing a solution with @shprotru .
