### ISSUE TITLE
Combat, troops can be attacked, while standing right behind the moat

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2589]
Troops, that enter moat shouldn't be able to attack enemy behind the moat. This can happen only if attacking troop spends one turn standing in a moat. 
![image](https://user-images.githubusercontent.com/55348946/104459342-aa57e900-55bd-11eb-830e-a4c2c92ba598.png)

**Comment by ihhub** [comment]
The problem is not being attacked but being set to the position of the wall.

**Comment by ihhub** [comment]
Hold on. The wall is broken so my initial assumption is incorrect.
