### ISSUE TITLE
0.8.4 window does not expand to full screen, ALT+Enter doesn't work

### ISSUE THREAD

**Issue by KloinTiinn** [ihhub/fheroes2#2590]
Operating System: Debian GNU/Linux 10 (buster)
Kernel: Linux 4.19.0-13-amd64
Architecture: x86-64

fheroes2 SDL2
![Screenshot_20210113_221100](https://user-images.githubusercontent.com/77409701/104498366-a42d3100-55ec-11eb-8a0b-f543e0976772.png)
 version

**Comment by Branikolog** [comment]
Hi, @KloinTiinn.
Fullscreen is switching by "F4" button. (On some notebooks it's also required to press "Fn")
Can you confirm this issue?

**Comment by KloinTiinn** [comment]
Thanks, F4 works

**Comment by Branikolog** [comment]
@KloinTiinn 
You're welcome! :) 
If you have any questions, you can always discuss them in our discord chanel.
