### ISSUE TITLE
Kingdom summary window, list of heroes doesn't refresh after dissmissing or hiring a hero

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2594]
When we dismiss any hero from "Kingdom Summary" window, hero list doesn't update. 
Also, UI of this window corrupts after the action.
Edit: Same thing happens after we hire a new hero through "Kingdom Summary" window.
![image](https://user-images.githubusercontent.com/55348946/104636451-701d4300-56b4-11eb-9e4a-02c15ff4a653.png)
![image](https://user-images.githubusercontent.com/55348946/104636523-89be8a80-56b4-11eb-873b-3c2b944e0201.png)
![image](https://user-images.githubusercontent.com/55348946/104636554-94791f80-56b4-11eb-8e18-59a4799f1b60.png)

**Comment by LeHerosInconnu** [comment]
There are also graphic problems.

In fheroes2:

![Dissmiss hero kingdom overview fh2 01](https://user-images.githubusercontent.com/43583994/104639643-f0897700-56a7-11eb-8685-252568169387.png)

https://user-images.githubusercontent.com/43583994/104639648-f2533a80-56a7-11eb-82c2-842bd68479d8.mp4

Related issue: https://github.com/ihhub/fheroes2/issues/2302.

**Comment by Branikolog** [comment]
> Also, UI of this window corrupts after the action.

Yes. Saw this bug, but couldn't reproduce for screenshot. :)

**Comment by vincent-grosbois** [comment]
The whole game is in undefined behavior anyway after this point, so graphic bugs are expected

**Comment by vincent-grosbois** [comment]
I think there are also different issues depending on if you dismiss hero that had focus, and if you dismiss the last hero
