### ISSUE TITLE
Ubuntu packages should be packed with non-dev SDL scripts

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#2599]
We ship Ubuntu packages with installation of development version of SDL (`script/linux/install_sdl_1.sh` and `script/linux/install_sdl_2.sh` files). We should provide scripts for **normal** version of SDL instead.

**Comment by qarkai** [comment]
Said scripts are used for development too. I'd suggest moving them to `script/linux/dev` or rename to something like `install_sdl_1_dev.sh` or even add optional parameter.
