### ISSUE TITLE
Set correct paths to headers for all files without inclusion of directories for project

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#26]
Right now we use project settings (make or VS project) to set include directories which are presented. This make source code browsing messy as we don't have proper file structure connection within project.
For example:
File `game.cpp` has an inclusion `#include "ground.h"`. ground.h file doesn't exist within the same directory as game.cpp which leads to confusion. Instead we need to have `#include "../maps/ground.h"`

**Comment by gbolli** [comment]
Hi, I'd like to help but I'm very new to this.    Would this task just be checking all .cpp files for headers in quotation marks, and correcting the paths?    I'm not sure how many files need correcting or how long it would take.   Would it be acceptable to do a few at a time or do you need the whole thing done at once?    Thanks

**Comment by ihhub** [comment]
Hi @gbolli thanks for interest in this task but unfortunately I made pull request long time ago. I'm not sure that this change is really needed for the project right now so I didn't merge.

Don't worry, I'll create many issue in upcoming days once I have free time :)

**Comment by gbolli** [comment]
Ok thanks, Cheers!
