### ISSUE TITLE
Combat screen, cannot cancel spell with esc button

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2600]
We should be able to cancel any spell after pressing esc button.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

This is also on my list. :)

In the original game, this operating mode with the "ESC" key is already available; and it is also used to close windows with an "OKAY" button (when this button is the only one) and windows with a "CANCEL" button (as if the user pressed the "CANCEL" button). 

I made a proposal to do it also with the mouse right click anywhere on the screen when a window is open. (https://github.com/ihhub/fheroes2/discussions/2607)
