### ISSUE TITLE
AI is stuck at coast and doesn't move

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2601]
AI is standing for a long period of time at once cell with one of his leading heroes.
![image](https://user-images.githubusercontent.com/55348946/104706212-ddb88600-572b-11eb-986f-be5d09d178e6.png)
[AI chilling on a beach.zip](https://github.com/ihhub/fheroes2/files/5819542/AI.chilling.on.a.beach.zip)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

Yes, I also noticed that the AI often landed at places where they had no choice but to re-embark. :D

> The AI hero Wrathmont disembarks at a place where he has no choice but to re-embark the next turn: "Before Ai disembark no way.sav" and "Ai disembark no way 01.sav".

_Originally posted by @LeHerosInconnu in https://github.com/ihhub/fheroes2/issues/2158#issuecomment-721964233_

**Comment by Branikolog** [comment]
But in my case he doesn't re-embark. :)

**Comment by idshibanov** [comment]
Tile passability rules issue. That boat is actually getting blocked by the mountain and Ruby can't embark/use that boat.

Fix will be probably in `Maps::Tiles::UpdatePassable` method, rule #8.

![image](https://user-images.githubusercontent.com/1373638/104805749-53f6d000-57a0-11eb-818c-ad9f2f33cbf6.png)

**Comment by Branikolog** [comment]
What about this case? There's no rock close to the boat.
![image](https://user-images.githubusercontent.com/55348946/104812373-c30d0c80-5812-11eb-88de-fd7d7b41bbe3.png)

**Comment by idshibanov** [comment]
Same issue here, boat is actually blocked to use because it's near the bottom edge. Rule 7 of the same function. Our issue is that boat isn't considered an "action" object here because it's on water and can't be used from water. Edge case obviously that wasn't accounted for.

We have to review passability rules at some point, as this is something I did not touch yet. Original game logic is quite difficult to understand as well.

**Comment by Branikolog** [comment]
I also noticed, that about a half of my saves has this flaw.
But in other part, when hero walks out of city we have penalty 75... Can't find out the root of this behaviour.
