### ISSUE TITLE
Warlock castle screen, centaur cave is drawn, while only waterfall was set in editor

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2614]
When we have a city, where waterfall was built, but Cave was not, we can see the image of Cave on a rocks, which is unclickable.
![image](https://user-images.githubusercontent.com/55348946/104811314-9c97a300-580b-11eb-8c8b-36a43dd813a0.png)
![image](https://user-images.githubusercontent.com/55348946/104811316-a4574780-580b-11eb-8d6f-ad170f517d12.png)
This flaw is present in the OG.

**Comment by ihhub** [comment]
This is true for Magic Garden in Sorceress castle. It's a problem of original resources.
