### ISSUE TITLE
"Summon boat" spell operation

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2621]
Currently, "Summon boat" spell doesn't work the same, in most cases, to the original game.
I propose to make it working more predictable and understandable for users.
Here's a set of rules for this spell:
- Summon boat should always bring either the nearest neutral boat or boat was owned before by a current player, or built by a current player in shipyard.
- Any neutral boat, that was summoned by a player once is not considered as neutral anymore and cannot be summoned by other players.
- If there're any neutral or belonging to a current player boats located in the cells close to the hero (in the summoning area), "summon boat" spell should bring another boat (if there're free somewhere). So, in this case player can summon multiple boats one by one, until he have free space around him. This prevents from summoning the same boat to the current hero over and over again.

P.S. Special thanks to @LeHerosInconnu and his substantial remarks about this spell operation in the original game.

P.P,S. If I've made some mistakes or forgotten something, I hope @LeHerosInconnu and our other members can add something to this issue. :)

**Comment by LeHerosInconnu** [comment]
Related issues: https://github.com/ihhub/fheroes2/issues/2175, https://github.com/ihhub/fheroes2/issues/2435.

**Comment by vincent-grosbois** [comment]
Why do we need to introduce this notion of "boat owned by player X" ? Sounds weird
What's wrong with having the logic purely based on player position + boats positions ?

**Comment by Branikolog** [comment]
@vincent-grosbois 
It's the original mechanics. 
Imagine, that you've just built a boat in a castle. But you don't have enough movement points to reach it current turn.
Are you sure, that you want to allow other players summon your boat, while you've waiting your next turn? :D

**Comment by vasilenkoalexey** [comment]
> If there're any neutral or belonging to a current player boats located in the cells close to the hero (in the summoning area), "summon boat" spell should bring another boat (if there're free somewhere). So, in this case player can summon multiple boats one by one, until he have free space around him. This prevents from summoning the same boat to the current hero over and over again.

Looks like i have implemented this in [2641](https://github.com/ihhub/fheroes2/pull/2641). Could you check?

**Comment by ihhub** [comment]
Closing this issue as we fixed all cases related to SUmmon Boat spell.
