### ISSUE TITLE
The program should remember whether it was in full-screen or windowed mode the last time the user exited the program

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2622]
When the user exits the program, the program should remember whether the game was in full-screen or windowed mode so that when the user restarts the program it is automatically in the same mode as when the user left it.
Basically, this should be updated in the game config file "fheroes2.cfg".

_Originally posted by @LeHerosInconnu in https://github.com/ihhub/fheroes2/discussions/2609_

**Comment by ihhub** [comment]
Closing this issue as we fixed it some time ago.
