### ISSUE TITLE
Kingdom Overview, strange behavior in the Kingdom Overview by left clicking on the castle graphic

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2627]
In fheroes2, there is a strange behavior in the Kingdom Overview by left clicking on the castle graphic.
Unrelated windows are displayed.

In fheroes2:

![Strange behavior castle graphic 01](https://user-images.githubusercontent.com/43583994/105070499-b04d3e80-5a83-11eb-9a98-446e357de85d.png)

![Strange behavior castle graphic 02](https://user-images.githubusercontent.com/43583994/105070508-b2af9880-5a83-11eb-925a-3961c574ce9f.png)

https://user-images.githubusercontent.com/43583994/105070582-cce97680-5a83-11eb-93ff-bbbe2d24e98f.mp4

**Comment by oleg-derevenetz** [comment]
Should have been fixed by #2597.

**Comment by Branikolog** [comment]
Agreed. Cannot reproduce it anymore.
