### ISSUE TITLE
When last hero gets attacked and killed by AI, game doesn't abort but shows enemy movements endlessly instead

### ISSUE THREAD

**Issue by manyilov** [ihhub/fheroes2#2645]
http://s000.tinyupload.com/?file_id=54072317713347754541

1. Open linked save file.
2. End turn.
3. Last hero gets attacked. Let the hero lose the battle.

Result: Game shows enemies' movements endlessly.
Expected: Game aborts since player has no castles or heroes left.

Tested on MacOS

--
GREAT project otherwise, thank you for your work!

**Comment by ihhub** [comment]
Hi @manyilov , could you please specify a version which you use? Is it a latest builf from master branch or one of builds from releases?

**Comment by manyilov** [comment]
According to changelog.txt, I am using version 0.8.4 (23 December 2020) on MacOS High Sierra. Didn't compile or build anything myself, just downloaded fheroes2_osx_sdl2.zip and ran the scripts.

**Comment by ihhub** [comment]
We fixed this issue recently so the upcoming release will include it.

@Branikolog could you please verify it on the latest build?

**Comment by Branikolog** [comment]
@ihhub .
OK. Give me 30 minutes, I'll check, if this issue is valid.

**Comment by Branikolog** [comment]
Bug confirmed.
But it looks kind of a cool feature. We can watch an ultimate AI battle without playing by ourselves. :D
