### ISSUE TITLE
The scrollbar of marketplace should be divided into segments according to the quantity of maximum resources

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2652]
The bar after dragging and releasing it should be sticked to the certain areas, where integer number of resources is shown.
Currently, if we drag the bar and stop it right before the place, where the resource number is raised, it doesn't add the resource till we reach the exact area.
In the example below, we're trading 5000k for one resource. But we should place the bar at the exact position in order to trade resource, (On a screenshots I'm releasing the mouse button, but still cannot trade any resource)
![image](https://user-images.githubusercontent.com/55348946/105578261-e34b4700-5d8f-11eb-99e4-8a3c9734bc8b.png)
![image](https://user-images.githubusercontent.com/55348946/105578265-e8a89180-5d8f-11eb-9682-4563bec59a8f.png)
![image](https://user-images.githubusercontent.com/55348946/105578268-ef370900-5d8f-11eb-8e98-b0a84372d629.png)
![image](https://user-images.githubusercontent.com/55348946/105578272-f9590780-5d8f-11eb-95a6-df1b7754edc4.png)
![image](https://user-images.githubusercontent.com/55348946/105578274-fd852500-5d8f-11eb-8853-3e22b0690b69.png)
I suggest to divide the scrollbar area into segments according to maximum resource number able to trade. When we click right before the middle of this segment, bar should jump to the previous quantity area. If we click after the middle of the segment, bar should be sticked to the next resource quantity area.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

Yes, that would be nice.
