### ISSUE TITLE
Adventure map, joining creature window with no marketplace built

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2654]
If we don't have any marketplace we can still press the place, where the button is supposed to be and enter exchange window.
But we still cannot trade resources.
![image](https://user-images.githubusercontent.com/55348946/105595205-6d050f80-5da4-11eb-8e18-16b15f8f98ff.png)
![image](https://user-images.githubusercontent.com/55348946/105595561-8443fd00-5da4-11eb-8df9-31f17b5d4081.png)
![image](https://user-images.githubusercontent.com/55348946/105595658-8ad27480-5da4-11eb-8c2c-6ef9806e1b4f.png)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

Good catch. :)

**Comment by vincent-grosbois** [comment]
it's a regression from what I changed recently in this window I think

**Comment by Branikolog** [comment]
@LeHerosInconnu 
> @Branikolog.
> 
> Good catch. :)

Actually, I didn't know, how could I find this bug.)
