### ISSUE TITLE
Main menu should remember difficulty while restarting

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2656]
If we choose scenario options when starting new game, we have the same ones, while restarting. Except difficulty. It is always set "Normal"
Game should remember difficulty,
![image](https://user-images.githubusercontent.com/55348946/105605963-b145df00-5da7-11eb-9052-10cc6d6d5a8d.png)

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

Ah, that was on my list, thank you. :)

**Comment by Branikolog** [comment]
@LeHerosInconnu 
Welcome!
Now you have more time to post the rest of your list. ;)
