### ISSUE TITLE
Campaign Awards

### ISSUE THREAD

**Issue by eos428** [ihhub/fheroes2#2670]
Another feature related to campaign that we haven't implemented yet in campaign awards.

So far I have identified these types:
- Creature Bane: Causes all neutral stacks of the troop type to run away from you
- Creature alliance: Causes all neutral stacks of the troop type to join you
- Get artifact: Artifact will be present on strongest hero's inventory
- Carryover troops: Strongest hero with all the troops will be carried over to final scenario I think
- Hero defeated: X hero will never show up again in later scenarios. I assume this needs the enemy hero in the map itself and then you'd remove it manually.

The one award in SW which I'm not sure of the is sorceress guild. Also if there's anything I missed feel free to let me know. Feel free to assign this issue to me too, but I'm open in case someone else wants to do it.

**Comment by vincent-grosbois** [comment]
https://gamefaqs.gamespot.com/pc/932491-heroes-of-might-and-magic-ii-gold/faqs/77670/campaign-awards-guide

**Comment by vincent-grosbois** [comment]
It seems you got all of them, except "+2 wood / day". BTW this isn't even something that is implemented in the game anyway

**Comment by ihhub** [comment]
Hi @eos428 , I think we have similar topic for this #2382.

**Comment by eos428** [comment]
@vincent-grosbois Wow some of these bonuses are a bit weird... Wayward son is going to be a headache to implement :D

@ihhub #2382 seems to be closer to #2668 now that I think about it since it's about the bonus choices. We can probably consider the former as a sub-issue of the latter. #2668 is about the implementation, #2382 is more or less the about applying them in each individual scenarios.

**Comment by vincent-grosbois** [comment]
@eos428 
The bonus about new heroes appearing is a totally new thing to implement IMO
Some remarks / question about this:
- I don't even know how we support "custom" heroes like this, for now all I see in the code are hardcoded heroes in the c++ code
- we have to make sure these heroes you get awarded are not available in all other map types, and that they can't be hired by the enemy if we don't hire them (I guess)
