### ISSUE TITLE
Split logic, ability to transfer the whole stack divided into two

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2671]
Currently, Thanks to @eos428, we have a nice and comfortable splitting of creatures.
I've noticed, that there was implemented a useful splitting of one stack into 3/4/5 and transferring them all to an other hero while meeting or while transferring to/from city garrison: 
![image](https://user-images.githubusercontent.com/55348946/105719587-812b4700-5f33-11eb-97e8-f6adca3045d1.png)
![image](https://user-images.githubusercontent.com/55348946/105720300-555c9100-5f34-11eb-8eea-dab5c1801f48.png)
![image](https://user-images.githubusercontent.com/55348946/105719616-8be5dc00-5f33-11eb-9ce2-436a876257be.png)
It would be nice if we can split one stack into two and transfer them to garrison (or to other hero) in one action, by adding a "2" button to split dialog.
Currently, we have an ability to transfer a half of stack (or, actually, any amount of troops) to garrison leaving the rest in hero army:
![image](https://user-images.githubusercontent.com/55348946/105719945-e848fb80-5f33-11eb-80cf-1d22cd32e0d6.png)
![image](https://user-images.githubusercontent.com/55348946/105719981-f1d26380-5f33-11eb-8eb0-ba53876892f2.png)
![image](https://user-images.githubusercontent.com/55348946/105719997-f7c84480-5f33-11eb-8f4e-18b42752f4d3.png)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

Would your proposal not fit into this issue? (https://github.com/ihhub/fheroes2/issues/2386)

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu !
Actually, I forgot, about that discussion. :)
I've made current improvement-issue just because recent PR made splitting a little bit confusing, as we can split to garrison current troops from hero's army (through a normal splitting dialog), but at the same time, fast split buttons work in different manner: they transfer the whole splitted stack and divide it into 3/4/5 stacks. So, I've thought: "Why can't we also transfer current stack to garrison divided in two stack as well?" It's an addition to current implementation of splitting in hero-garrison and hero-hero scenarios.
In #2386 we mostly discussed splitting logic within hero's army.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

The problem with the way it works now is that it works differently if the separation is in the hero's army, or from the hero's army to the garrison or army of another hero.
This is not good.
It must always work the same way.

In the case presented, the player should first transfer the troop from the hero's army to the garrison and only then separate the troop in the garrison.

Also a left click held and move to another slot only works in the hero's army and don't works from the hero's army to the garrison or the army of another hero.
It must also work in the same way for all cases.

**Comment by Branikolog** [comment]
> Also a left click held and move to another slot only works in the hero's army and don't works from the hero's army to the garrison or the army of another hero.
> It must also work in the same way for all cases

This should be definitely be an issue! 

Regarding current split logic:
Actually, I like this implementation as well as the default one. 
One I tried to split troops into garrison or second hero army I noticed, that it works in a different manner, but I understand the rules and accept them. Remember, that here we're creating a new content, so prayers would have to get acquainted. ;)


> The problem with the way it works now is that it works differently if the separation is in the hero's army, or from the hero's army to the garrison or army of another hero.
> This is not good.
> It must always work the same way.
> 
> In the case presented, the player should first transfer the troop from the hero's army to the garrison and only then separate the troop in the garrison.

Splitting between armies can be considered as different case, comparing to splitting within single hero. 
I believe, that the case, when we need to transfer the whole stack and split it into 2/3/4 will happen more often, comparing to the case we need split stack into several same but leave one in native hero army.
Remember, I don't say, any of this implementations is worse or better. I just note, that one of them will be used a little more frequently.

**Comment by eos428** [comment]
Hi @Branikolog @LeHerosInconnu, it's true that cross-army drag split isn't working at the moment. It was one of the pending split issues that I haven't gotten to yet because of the scale of the work. I think we already had an issue for it?

Regarding the "2" slot in fast split, I'd be fine whether it's implemented or not but if we do, I think it should be usable for both cross-army split and otherwise.

**Comment by Branikolog** [comment]
Hi, @eos428 
Yes, we have an issue: #2389.
Regarding "2" we're both agreed on implementing it.
Currently we're debating, should it always work the same, or the way it is implemented currently, with a slight different logic in cross-army cases.

**Comment by LeHerosInconnu** [comment]
@Branikolog and @eos428.

> Currently we're debating, should it always work the same, or the way it is implemented currently, with a slight different logic in cross-army cases.

It is important that it always works the same way.

I have a suggestion to allow the other way of working.

To allow the troop to be transferred completely and distributed to several troops at the same time, a button "A" (meaning "All") is added.
By default this button is not activated, which allows standard operation.
This button has two states, activated and non-activated and is independent from the buttons with the numbers "2", "3", "4" and "5".
This means that this button can be activated at the same time as one of the buttons with numbers.

When this button is activated all the creatures of the starting troop will be transferred to the destination and the troop will be separated into as many troops as indicated by the button with numbers.
If the troop is the only troop in the hero's army, all but one of the creatures will be transferred.

This button is displayed only when the destination is not in the same army, so only from the hero's army to the garrison or to the army of another hero.
This screen is for explanatory purposes only.

![Separation slots fh2 avec bouton A et  jusqu'à 5 01](https://user-images.githubusercontent.com/43583994/106044495-18350200-60e0-11eb-97f2-a05f9c83634a.png)
