### ISSUE TITLE
Split logic, cancel highlighted troop while using Alt/Ctrl

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2679]
![image](https://user-images.githubusercontent.com/55348946/105990751-fe7dc580-60b3-11eb-85c1-15fc439b4bcb.png)
I think, we need to cancel highlighting of the troop, if we previously selected it, and then start splitting/uniting activity.

**Comment by eos428** [comment]
Hi, assign this one to me too :)

**Comment by Branikolog** [comment]
Sure, @eos428 !
