### ISSUE TITLE
Reorganization of troops using "CTRL" and "ALT" keys does not work when the hero screen is open from the meeting screen

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2681]
In fheroes2, the reorganization of troops using "CTRL" and "ALT" keys does not work when the hero screen is open from the meeting screen.

In fheroes2:

https://user-images.githubusercontent.com/43583994/106049873-ee330e00-60e6-11eb-8071-e01d9a5d65c2.mp4

**Comment by oleg-derevenetz** [comment]
Actually, according to current logic in the code, hero screen opens in the read-only mode in this case. So it's the same bug as in #2628.
