### ISSUE TITLE
In the hero screen and in the meeting screen the use of the "ALT" key for troop reorganization does not always work correctly

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2682]
In fheroes2, in the hero screen and in the meeting screen the use of the "ALT" key for troop reorganization does not always work correctly.

Select the troop to be reorganized.
Press and hold the "CTRL" key.
Click several times on the starting troop.
Release the "CTRL" key.
Move the mouse cursor over one of the troops of 1 creature.
Press and hold the "ALT" key.
Click on the 1 creature troop without releasing the "ALT" key.
Not all similar troops are joined together.

This seems to work correctly when the troop is not selected first.

In fheroes2:

https://user-images.githubusercontent.com/43583994/106053573-423ff180-60eb-11eb-976e-dde805bed99c.mp4

**Comment by Branikolog** [comment]
I believe, this issue will be gone, when we fix another issue: #2679.

**Comment by eos428** [comment]
Hi @LeHerosInconnu , does this issue still persist as of the latest commit?

**Comment by LeHerosInconnu** [comment]
Hello @eos428,

> Hi @LeHerosInconnu , does this issue still persist as of the latest commit?

It still doesn't work in all cases:

https://user-images.githubusercontent.com/43583994/109853585-5466ff80-7c56-11eb-97d7-5a95048fabe4.mp4

**Comment by eos428** [comment]
Alright, let me take a look at it again. Assign this issue to me please :)
