### ISSUE TITLE
Creature separation window, spacing between the buttons of the number of troops to be separated is not identical

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2683]
In fheroes 2, the spacing between the buttons of the number of troops to be separated is not identical.

There is a spacing of 10 pixels between button "3" and button "4", and the spacing is only 9 pixels between button "4" and button "5".
The spacing between the buttons should always be 10 pixels.

In fheroes2:

![Separation slots fh2 avec boutons 3 4 5 01](https://user-images.githubusercontent.com/43583994/106055462-b24f7700-60ed-11eb-85b7-9d6b6ae775f7.png)

**Comment by eos428** [comment]
Hi @LeHerosInconnu, does this issue still persist as of the latest commit?

**Comment by LeHerosInconnu** [comment]
@eos428.

> Hi @LeHerosInconnu, does this issue still persist as of the latest commit?

That's corrected, thanks. :)
