### ISSUE TITLE
Replace (void) by empty () statement

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#27]
Not sure what was an intention behind but original code is filled with functions containing `void` as input parameter. This brings no value to code and just complicates reading. We want to remove replace by empty parameter function code as `()`.

**Comment by kgorecki** [comment]
As a specialist for that kind of tasks, I'll take it if no one else dares ;}

**Comment by ihhub** [comment]
@kgorecki we already such pull request :)

**Comment by kgorecki** [comment]
Oh boy, I was sleepy when I did that... :}
