### ISSUE TITLE
Incorrect movement counter.

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#271]
The less movement points left, the less third day movement prediction shows on a map. When a hero has full movement points, third day movement prediction shows correctly.
![Безымянный](https://user-images.githubusercontent.com/55348946/71442215-aa185180-270d-11ea-8e85-cff09cd4f434.jpg)
![Безымянный1](https://user-images.githubusercontent.com/55348946/71442216-aa185180-270d-11ea-8d6a-527e79c1671c.jpg)
![Безымянный2](https://user-images.githubusercontent.com/55348946/71442217-aa185180-270d-11ea-8613-dbd0fc64de69.jpg)

**Comment by ihhub** [comment]
The problem lies in `int Heroes::GetRangeRouteDays(s32 dst) const` function.
