### ISSUE TITLE
Kingdom Overview screen, Towns/Castles screen, it is not possible to reorganize the troops in the hero's army or in the garrison or between the hero's army and the garrison

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2715]
In fheroes2, it is not possible to reorganize the troops in the hero's army or in the garrison or between the hero's army and the garrison.

In fheroes2:

![Not possible move troops](https://user-images.githubusercontent.com/43583994/106653161-b91b3580-6596-11eb-87dd-16db1a97a1c3.png)

**Comment by Branikolog** [comment]
It's definitely a bug. Only dragging within one army works here. And still it works as splitting only.

**Comment by LeHerosInconnu** [comment]
This bug is quite recent, it worked fine in version 0.8.4 2644.
And this bug is already present in version 0.8.4 2663.
