### ISSUE TITLE
Summon Boat spell, boat summoned under the hero's sprite

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2720]
In fheroes2, the boat is summoned under the hero's sprite.

In fheroes2:

![Boat summon under hero fh2 01](https://user-images.githubusercontent.com/43583994/106661358-64c98300-65a1-11eb-9fe7-e73e55506f0c.png)

https://user-images.githubusercontent.com/43583994/106661417-77dc5300-65a1-11eb-9d0b-ec98fc4bf98a.mp4

**Comment by vasilenkoalexey** [comment]
Duplicate #2179
