### ISSUE TITLE
Combat, Phoenixes fly in the reverse direction

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2724]
In fheroes2, the Phoenixes fly in the reverse direction.

In fheroes2:

https://user-images.githubusercontent.com/43583994/106666334-c12fa100-65a7-11eb-9644-7f1172029a3c.mp4

End the turn.
Here is the save file:
[Before attack castle cyclops 2.zip](https://github.com/ihhub/fheroes2/files/5914596/Before.attack.castle.cyclops.2.zip)

**Comment by oleg-derevenetz** [comment]
This related not only to phoenixes, pixies will do the same when moving in strictly vertical direction. Are you sure it's really a bug? When moving vertically, both directions are legitimate.

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> This related not only to phoenixes, pixies will do the same when moving in strictly vertical direction. Are you sure it's really a bug? When moving vertically, both directions are legitimate.

In the original game, when a creature moves to an hexagon located in front of or on the same plane (vertically) as their current position, it never turns around as it moves.
This is true for all flying and other creatures.

In original game:

https://user-images.githubusercontent.com/43583994/110201693-da589580-7e64-11eb-887c-12bfc816fb25.mp4
