### ISSUE TITLE
Experimental Game Settings window, the option "world: new version WeekOf (+ growth)" automatically activates/deactivates the option "world: ban for WeekOf/MonthOf Monsters"

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2725]
In fheroes2, the option "world: new version WeekOf (+ growth)" automatically activates/deactivates the option "world: ban for WeekOf/MonthOf Monsters"

In fheroes2:

https://user-images.githubusercontent.com/43583994/106667844-c261cd80-65a9-11eb-91f3-79da40a43e39.mp4

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu 
I don't even know, what the option "New version" is doing currently. ;)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> Hi, @LeHerosInconnu
> I don't even know, what the option "New version" is doing currently. ;)

I haven't tested this option yet either. :)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu and @Branikolog , I removed this option as the only thing it was doing is setting different imbalanced number of growth.
