### ISSUE TITLE
Adventure map, AI's behavior in attacking opposing heroes and defending its castles

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2731]
AI is sometimes too confident. :)
The AI recruits a hero and gives him a proper army to attack a human hero who is a bit too adventurous (it's really well thought out at first), but for that it uses all the troops defending its castle.
The hero of the AI is defeated, to the great astonishment of the AI. :D
And the AI castle is completely defenseless the next turn, while there are still many creatures to recruit in the castle.
By simply leaving just a few Ogre Lords (even only the 2 Ogre Lords of the AI hero's army who attacked) and a few Goblins troops for example in defense, it would have been more complicated (if not impossible) for the human hero to capture the AI castle the next turn.

In fheroes2:

![AI attack but no defense fh2 01](https://user-images.githubusercontent.com/43583994/106786589-0064fd00-664f-11eb-8282-904add60b0e0.png)

![AI attack but no defense fh2 02](https://user-images.githubusercontent.com/43583994/106786597-03f88400-664f-11eb-8544-fc85c3b727f1.png)

![AI attack but no defense fh2 03](https://user-images.githubusercontent.com/43583994/106786608-06f37480-664f-11eb-8c95-eaadfd4d7241.png)

![AI attack but no defense fh2 04](https://user-images.githubusercontent.com/43583994/106786618-09ee6500-664f-11eb-96b0-20f381e49625.png)

Here are the save files (before and after):
[AI's behavior defending castles.zip](https://github.com/ihhub/fheroes2/files/5920403/AI.s.behavior.defending.castles.zip)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , could you please check if this bug is still present? We recently fixed the logic of army estimation for AI so it shouldn't recklessly attack a powerful human hero.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , could you please check if this bug is still present? We recently fixed the logic of army estimation for AI so it shouldn't recklessly attack a powerful human hero.

I did some tests to check the AI behavior and I didn't see any particular problem, but it doesn't mean anything because it's not a bug that can be checked easily (and the save file of the original post can't be loaded anymore in the current version of the program 0.9.4 3771), it should be kept in mind and checked in the long run.

**Comment by ihhub** [comment]
Closing this issue for now.

@LeHerosInconnu feel free to reopen it if you find the same behavior of AI again.
