### ISSUE TITLE
Castle screen, Hero can learn spells from non-opened scrolls in mage guild

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2743]
Hero managed to learn "magic arrow" spell, while there's none in town's mage guild.
![image](https://user-images.githubusercontent.com/55348946/107117711-460f0900-688d-11eb-9340-cacba99c34c8.png)
Also, if we make a right click over a closed scroll in 1st row of magic guild we can know, what the spell it is.
![image](https://user-images.githubusercontent.com/55348946/107117753-7fe00f80-688d-11eb-902e-b627a631ef67.png)

**Comment by vincent-grosbois** [comment]
Are you sure that Magic Arrow is not a spell that was granted for free when you buy the hero ? I think this exists

**Comment by Branikolog** [comment]
@vincent-grosbois 
Absolutely! :)
Wizard heroes start with stone skill spell in their books.
Once I've built the guild, I was disappointed, that I haven't received attacking spell.
But I was quite surprised, when I opened spell book and found there new spell.
Also, clicking on the right  closed scroll and watching the info window pop up there is not normal.
