### ISSUE TITLE
Combat, AI should move its ranged troops if those troops are in melee with opposing troops instead of passing their turn without taking action

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2747]
In fheroes2, AI should move its ranged troops if those troops are in melee with opposing troops instead of passing their turn without taking action.

In the example, Grand Elves and War Trolls pass their turn without attacking.
This is a good thing at first because by attacking the Phoenixes in close combat these troops would suffer damage (at least one of the two troops).

In fheroes2:

https://user-images.githubusercontent.com/43583994/106665989-48304980-65a7-11eb-8292-9511fbf6f611.mp4

![Ranged troops should move fh2 01](https://user-images.githubusercontent.com/43583994/107127930-f4c93e80-68b9-11eb-8ac0-b74af65ac847.png)

However, a better action would be to move the Grand Elves away from the Phoenixes for two reasons (same for the War Trolls).
First, if the Grand Elves have good Morale and this allows them to attack a second time, they would be able to fire freely because they would no longer be in contact with the Phoenixes.
And second, it would allow them to be out of close combat the next turn.

For their movement, the Grand Elves should move to a position that does not allow the Phoenixes to block two ranged troops the next turn, while also trying not to get too close to the other opposing troops that are not flying (there are none in the example), and trying to limit the attack possibilities of the other opposing troops by positioning in hexagons close to the edge of the battlefield.
Grand Elves should also avoid positioning in hexagons where the two-square attack of the allied Cyclopes could hit them (by a retaliation of the Cyclops when they would be attacked).

For example, Grand Elves could position in a hexagon where the yellow movement cursor of these screens is positioned:

Just in front of the entrance of the castle, which would prevent the defensive troops that do not fly (there are none in the example) from leaving the castle at the same time.
![Ranged troops should move fh2 05](https://user-images.githubusercontent.com/43583994/107127946-09a5d200-68ba-11eb-8a63-8601c3987cc6.png)

In a hexagon that does not allow the Phoenixes to block two ranged troops.
![Ranged troops should move fh2 02](https://user-images.githubusercontent.com/43583994/107127956-1f1afc00-68ba-11eb-815f-189bfd4a5d6a.png)

In a hexagon close to the edge of the battlefield in order to limit the possibilities of attack by other opposing troops and at the same time the Goblins can defend them.
![Ranged troops should move fh2 06](https://user-images.githubusercontent.com/43583994/107127978-52f62180-68ba-11eb-9c47-7a97d65730ca.png)

In a hexagon close to the edge of the battlefield in order to limit the possibilities of attack by other opposing troops and at the same time not to suffer the two-square attack of the allied Cyclopes (by a retaliation of the Cyclops when they would be attacked).
![Ranged troops should move fh2 04](https://user-images.githubusercontent.com/43583994/107127991-6f925980-68ba-11eb-9d36-01f61f49db7d.png)

For War Trolls, in the hexagon at the bottom left of the battlefield in order to limit the possibilities of attack by other opposing troops (in case the Cyclopes would have attacked the Phoenixes in the hexagon just behind the Phoenixes, as they should have done).
![Ranged troops should move fh2 03](https://user-images.githubusercontent.com/43583994/107128000-8173fc80-68ba-11eb-897e-4844a6caed56.png)

In a hexagon close to the edge of the battlefield in order to limit the possibilities of attack of the other opposing troops and at the same time not to suffer the two-square attack of the allied Cyclopes (in the case where the Grand Elves would have been positioned just in front of the entrance of the castle for example).
![Ranged troops should move fh2 04](https://user-images.githubusercontent.com/43583994/107127991-6f925980-68ba-11eb-9d36-01f61f49db7d.png)

**Comment by idshibanov** [comment]
We have a logical branch for this in AI's decision tree. Unit knows that attacking back in this case isn't ideal but "kiting" code for moving away isn't implemented yet. Let's hope we can finish it by the 0.9.1 release.

I appreciate the examples and suggestions, will come back to this ticket later.
