### ISSUE TITLE
Make visible MIN and MAX buttons for troop separation dialog

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#275]
A button must be made while splitting units. The same as we have in a unit purchase window in a city.
![Безымянный](https://user-images.githubusercontent.com/55348946/71466292-d0022c80-27c7-11ea-8661-bd270a228774.jpg)
![Безымянный1](https://user-images.githubusercontent.com/55348946/71466291-cf699600-27c7-11ea-9912-cc4ab88aec59.jpg)

**Comment by ihhub** [comment]
On top of this:
- rename `Move how many troops?` into `How many troops to move?`
- use buttons for 3, 4 and 5 as well
