### ISSUE TITLE
Combat, AI doesn't move his troop of Cyclopes when they could move closer to the moat

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2754]
In fheroes2, the AI doesn't move his troop of Cyclopes when they could move closer to the moat.

In the example, the Cyclopes do not move from their starting position for the entire time they are in the combat.
They could move closer to the moat (without necessarily entering it, depending on the case), especially since in this example the army's Morale is good, and they could possibly attack with good Morale if they entered the moat.
For example, they could position in the moat near the Wolves (or in the moat near the bottom wall, or in the moat between the Goblins and the Ogre Lords), a position that would allow them to enter the castle if the wall were to be destroyed.

![vlcsnap-2021-02-07-00h14m41s404](https://user-images.githubusercontent.com/43583994/107132280-e5f48300-68dd-11eb-8090-c2eec32fbc1d.png)

https://user-images.githubusercontent.com/43583994/107131947-649bf100-68db-11eb-9b38-9339baa8d9c4.mp4

**Comment by idshibanov** [comment]
Can you share a savegame before this battle start? I would like to check debug logs to see what Cyclops are thinking.

**Comment by LeHerosInconnu** [comment]
Hello @idshibanov,

> Can you share a savegame before this battle start? I would like to check debug logs to see what Cyclops are thinking.

Sure.

End the turn.
Reproduce the first combat.
Here is the save file (Broken_Alliance_0033aaa.sav):
[AI's behavior defending castles.zip](https://github.com/ihhub/fheroes2/files/5920403/AI.s.behavior.defending.castles.zip)
