### ISSUE TITLE
Change castle navigation button status from pressed to disabled while only one castle is present

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#276]
Change castle navigation button status from pressed to disabled while only one castle is present:
![1](https://user-images.githubusercontent.com/55348946/71467946-0f7f4780-27cd-11ea-966d-315cfcb86056.jpg)

**Comment by Igonorant** [comment]
Is this issue already solved by the code below?

    if ( 2 > world.GetKingdom( GetColor() ).GetCastles().size() || readonly ) {
        buttonPrevCastle.Press();
        buttonPrevCastle.SetDisable( true );

        buttonNextCastle.Press();
        buttonNextCastle.SetDisable( true );
    }

**Comment by ihhub** [comment]
Hi @Igonorant I think the problem is exactly in this code: we make a state of button to be pressed which causes these button shifts. We need to just set the button to disabled state.

**Comment by idshibanov** [comment]
Regarding button shifts: that's how the sprite is in SMALLBAR.ICN file. There's no 'disabled' sprite. I can only adjust the placement.
