### ISSUE TITLE
Could Dews add support of gog's .exe's jh HoMMii?

### ISSUE THREAD

**Issue by DragonSerW** [ihhub/fheroes2#2767]
There are 2 exe's of the game awailable to download nowadays:
setup_heroes_of_might_and_magic_2_gold_1.01_(2.1)_(33438).exe
setup_homm2_gold_win_2.0.0.7.exe

I wish I could put one oh them to the folder of The Script, and the script should uncompress them on his own -- is it possible?
How coul I decompress gog's exe @ macOS / Fedora?

**Comment by undef21** [comment]
Gog's installers  could be extracted with innoextract. This program is available from fedora and brew (macos) repositories. While gog update game archives with new versions of inno installer, some stable distributions (debian, ubuntu  lts) may contain outdated versions.

**Comment by ihhub** [comment]
Hi @DragonSerW , this is out of scope of this project. The original game is developed only for Windows. You could try the above solution by @undef21 or through Wine. Alternatively, you could still download the demo version of the game which will interpret by our engine as a full game.

**Comment by ihhub** [comment]
Closing this issue as it is irrelevant to the project.
