### ISSUE TITLE
Troop separation dialog's place

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#278]
Troop separation dialog should be placed higher. Now it covers the most part of granison.
![Безымянный](https://user-images.githubusercontent.com/55348946/71471271-a8b35b80-27d7-11ea-8f01-0a7acf469026.jpg)

**Comment by ihhub** [comment]
`class FrameBox` is responsible for the position of the window.

**Comment by Branikolog** [comment]
I think we should add a picture of separated unit to this window. So we don't have to move it after that.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> I think we should add a picture of separated unit to this window. So we don't have to move it after that.

Yes, it's a good idea to add the creature's graphic in the separation window. :)

It would also be good to add the creature name as a yellow title for the separation window, so with the creature graphic below it and the rest of the current window content after it.
