### ISSUE TITLE
Combat screen, logs list, indicate "Ballista" instead of "Turret" when referring to the Ballista

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2784]
In the logs list, use the word "Ballista" instead of the word "Turret" when referring to the Ballista.

In the example, replace the word "Tower" by "Ballista":

"Ballista does 37 damage, 3 Archers perish."

Instead of:

"Tower does 37 damage, 3 Archers perish."

In fheroes2:

![Ballista fh2 03](https://user-images.githubusercontent.com/43583994/107702698-e95f8400-6cba-11eb-938e-11235633e399.png)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu and @shprotru , this is actually incorrect. In th original game we have two cases:
- Garrison (for main tower)
- Tower

there is no Ballista or Turret. Please correct me if I am wrong here.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu and @shprotru , this is actually incorrect. In the original game we have two cases:
> 
> * Garrison (for main tower)
> * Tower
> 
> there is no Ballista or Turret. Please correct me if I am wrong here.

Well noticed. :)
Indeed, in the original game, there is mention of "Garrison" in the logs when the "Ballista" shoots and "Tower" for the Turrets:

![Ballista Towers H2 002](https://user-images.githubusercontent.com/43583994/109015586-91128400-76b5-11eb-9bfc-34340f1ae42a.png)

But in the info window, "Ballista" is used:

![Ballista Towers H2 001](https://user-images.githubusercontent.com/43583994/109015620-9bcd1900-76b5-11eb-9146-1f972ba0d3d5.png)

And in the construction screen, it is "Turret" (Left and Right) which is used:

![Ballista Towers H2 003](https://user-images.githubusercontent.com/43583994/109015669-adaebc00-76b5-11eb-8491-6a574d2f8cc2.png)

I suggest to use "Ballista" and "Turret" (Left and Right) also in the logs.

In fheroes2:

![Ballista Towers fh2 001](https://user-images.githubusercontent.com/43583994/109015700-b7382400-76b5-11eb-8068-1f0f190e8a07.png)

So:

"Ballista does 37 damage, 3 Archers perish."
"Left Turret does 24 damage, 3 Archers perish." (Turret at the top of the screen during combat.)
"Right Turret does 16 damage, 1 Archers perishes." (Turret at the bottom of the screen during combat.)
