### ISSUE TITLE
Resources in recruit window are shifted lower their original position

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#279]
The picture of required resourse is too huge, so it covers a part of number nearby.
![Безымянный4](https://user-images.githubusercontent.com/55348946/71472121-853de000-27da-11ea-8fb4-6dc7ddc5d3de.jpg)

**Comment by ihhub** [comment]
This is how it should be:
![image](https://user-images.githubusercontent.com/19829520/71475318-9c9cbd80-281a-11ea-817d-9eab0275e935.png)
