### ISSUE TITLE
All scrollbars and buttons in game, add the ability to left-click and hold to continuously scroll the scrollbar or increase/decrease the quantity value

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2809]
In fheroes2, it would be nice to add the ability to left-click and hold to continuously scroll the scrollbar or increase/decrease the number of creatures in addition to operating multiple clicks in a row.
This for all scrollbars and buttons in game.
"File to Load:" window, Adventure map screen, Kingdom Overview screens, Castle screen, "Experimental Game Settings" window, etc.

In fheroes2:

![Mouse left button maintained fh2 01](https://user-images.githubusercontent.com/43583994/106063022-dfa12280-60f7-11eb-9ec0-05361e387a75.png)

![Separation slots fh2 avec boutons 3 4 5 01](https://user-images.githubusercontent.com/43583994/106055462-b24f7700-60ed-11eb-85b7-9d6b6ae775f7.png)

![Recruit window mouse wheel fh2 01](https://user-images.githubusercontent.com/43583994/106059263-c0ec5d00-60f2-11eb-9e34-053de557108b.png)

![Marketplace window mouse wheel fh2 01](https://user-images.githubusercontent.com/43583994/106059284-c9dd2e80-60f2-11eb-8a43-7ea8f6599f64.png)

_Originally posted by @LeHerosInconnu in https://github.com/ihhub/fheroes2/discussions/2687_

![Scrollbars buttons all 001](https://user-images.githubusercontent.com/43583994/108062144-a9512600-7059-11eb-8e1d-229f6a226774.png)

![Scrollbars buttons all 002](https://user-images.githubusercontent.com/43583994/108062156-ad7d4380-7059-11eb-901a-120c9fd72d44.png)

![Scrollbars buttons all 003](https://user-images.githubusercontent.com/43583994/108062168-b110ca80-7059-11eb-9750-7e236b51bf9f.png)

![Scrollbars buttons all 004](https://user-images.githubusercontent.com/43583994/108062174-b3732480-7059-11eb-99cc-167f8c9b7e05.png)

![Scrollbars buttons all 005](https://user-images.githubusercontent.com/43583994/108062185-b79f4200-7059-11eb-8be8-9d11e5cefbfb.png)

**Comment by ihhub** [comment]
Hi @eos428 , could you please take a look? I think it's similar to what you've done with split window.
