### ISSUE TITLE
Mouse cursor, small arrow cursor with a yellow border has no shadow

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2810]
In the original game, for the adventure map and screens, the small arrow cursor with a yellow border has a shadow.
This is not the case in fheroes2.

In original game:
![Cursor type and shadow 001](https://user-images.githubusercontent.com/43583994/107424269-c0ee5300-6b1d-11eb-86b6-1cc88b8dd2d0.png)
![Cursor type and shadow 002](https://user-images.githubusercontent.com/43583994/107424287-c481da00-6b1d-11eb-936b-233cc0526c32.png)
![Cursor type and shadow 003](https://user-images.githubusercontent.com/43583994/107424298-c8156100-6b1d-11eb-8377-6484f343c499.png)

In fheroes2:
![Cursor type and shadow 008](https://user-images.githubusercontent.com/43583994/107424399-dfece500-6b1d-11eb-8190-572c6018859d.png)
![Cursor type and shadow 009](https://user-images.githubusercontent.com/43583994/107424408-e4190280-6b1d-11eb-8bb9-b4f9a77afd6a.png)
![Cursor type and shadow 010](https://user-images.githubusercontent.com/43583994/107424415-e7ac8980-6b1d-11eb-9be3-91869f708bc6.png)

_Originally posted by @LeHerosInconnu in https://github.com/ihhub/fheroes2/discussions/2772_

**Comment by ihhub** [comment]
It is not possible to do exactly like in the original game because SDL 2 uses OS level cursor drawings. What I can do is to add as close as possible alpha channel value for pixels which were shadow in the original game.
