### ISSUE TITLE
Mouse pointer slowness or smoothing?

### ISSUE THREAD

**Issue by tremby** [ihhub/fheroes2#2814]
It seems like the mouse cursor is less responsive than I'm used to on my desktop. I wondered if there's some kind of smoothing happening which I could disable, but I think it's probably something else since it seems to get worse and better over time.

I'm playing under Linux; the latest build for SDL1.

**Comment by ihhub** [comment]
Hi @tremby , please use SDL2 version. SDL1 version has internal software mouse rendering.

**Comment by tremby** [comment]
Makes sense.

I've got some dependency hell there which I'm not prepared to bother dealing with, so I'm stuck at least for now with SDL1.

**Comment by ihhub** [comment]
Nothing we can do in this case as it's a limitation of SDL 1.
