### ISSUE TITLE
Pixel scaling/zoom without fullscreen

### ISSUE THREAD

**Issue by tremby** [ihhub/fheroes2#2815]
I have a high resolution screen and would like to play with a bigger window but without everything being invisibly tiny. I'd like to be able to scale up the window and have the game pixels scale.

I found that fullscreen mode does this, but that switches off my second display and I also don't want to be full screen at all.

I suppose as a stretch goal it'd be nice to support [pixel upscaling algorithms](https://en.wikipedia.org/wiki/Pixel-art_scaling_algorithms) like ScummVM and Dosbox do.

**Comment by ihhub** [comment]
This issue is fixed in #2829 .

**Comment by tremby** [comment]
Ouch, this means I need to resolve my dependency hell to get SDL2 installed! Thank you.
