### ISSUE TITLE
Splitting troops, highlighting of selected stack doesn't work within single army

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2823]
When we're trying to split stack of creatures within single army the highlighting cancels on dialog appearing:
![image](https://user-images.githubusercontent.com/55348946/108503668-d6097580-72c5-11eb-9805-abeda9946970.png)
![image](https://user-images.githubusercontent.com/55348946/108503688-dbff5680-72c5-11eb-9f9b-00adbe10e488.png)
But when we do separation between hero and garrison (or between heroes in a meeting heroes screen) the highlighting of selected stack works well:
![image](https://user-images.githubusercontent.com/55348946/108503847-179a2080-72c6-11eb-9921-74ffd943c84b.png)
![image](https://user-images.githubusercontent.com/55348946/108503868-1cf76b00-72c6-11eb-95d4-6ba46fd15184.png)

**Comment by eos428** [comment]
Hi, assign this issue to me too :)

**Comment by Branikolog** [comment]
👍
