### ISSUE TITLE
Splitting troops, Shift button operation for fast splitting

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2824]
To finish the fast split keyboard combinations (after "ALT" and "Ctrl" was implemented by our dear contributors) we should add "Shift" button common usability, which players are so used to.
When we hold "Shift" button and press any creature stack it should be divided into two equal. In a case we have any free slot within target garrison.
![image](https://user-images.githubusercontent.com/55348946/108504400-dce4b800-72c6-11eb-8d0d-d7641b21ee81.png)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

Yes, this can work too.
You're quite inspired at this time. :D

So, if there is room in the hero's army, the created group goes to the first free slot in the hero's army (even when visiting a castle or meeting with another hero).

For the hero alone, if there is no free slot, nothing happens.

When the hero is visiting a castle or meeting with another hero and there is no place in his army, the created group goes to the first free slot of the garrison army or to the army of the other hero.

If there is no place in the garrison or in the army of the other hero, nothing happens.

**Comment by Branikolog** [comment]
> You're quite inspired at this time. :D

I had all this threads opened in my browser tabs for so long time...
It's time to discuss all this issues, find the solution and take away that unsolved questions. And free my browser. :)


> When the hero is visiting a castle or meeting with another hero and there is no place in his army, the created group goes to the first free slot of the garrison army or to the army of the other hero.

I'm not sure, that split logic, that sends troops to other army (meeting hero or city garrison) without pointing that "other" army is intuitive and easy-to-get-accustomed... I mean if we do some actions within one army - we change things inside this army. If we press, point, or pull between the first and the second army (of meeting hero or town garrison) - we transfer creatures from one to another.

On the other hand your addition broadens the usability...

From my point, I would perform no action in a case above: "No free space in one army - nothing happens. If you want to transfer creatures - you should transfer them by pointing another army."
Also, your proposal makes "Shift" button the only occasion, when we can transfer troops using keyboard buttons... And only in one special case, when army is full...

**Comment by LeHerosInconnu** [comment]
@Branikolog.

I agree that the action should only concern the hero's army.

I was trying to understand how it works as you were talking about a garrison and the hero is visiting a castle: :D

> When we hold "Shift" button and press any creature stack it should be divided into two equal. In a case we have any free slot within target garrison.
> ![image](https://user-images.githubusercontent.com/55348946/108504400-dce4b800-72c6-11eb-8d0d-d7641b21ee81.png)

**Comment by Branikolog** [comment]
I mean withing single army: 
If we press hobbits in hero army (Using "Shift" button) - they are divided within hero army (if hero army has no free slots - nothing happens.)
If we press hobbitts in town garrison army (Using "Shift" button) - they also divided withing town garrison army. (If garrison is full - nothing happens)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> I mean withing single army:
> If we press hobbits in hero army (Using "Shift" button) - they are divided within hero army (if hero army has no free slots - nothing happens.)
> If we press hobbitts in town garrison army (Using "Shift" button) - they also divided withing town garrison army. (If garrison is full - nothing happens)

Yes, I understand.
Within the same army, led by a hero or in the garrison of a castle.
But no interaction between two different armies.
It's okay. :)

**Comment by Branikolog** [comment]
So let's for start add such simple but obvious behviour: Split stack into two with "Shift" button pressed within same army.
In future we can upgrade this mechanics for sure.

**Comment by eos428** [comment]
Hi @Branikolog, can you assign this issue to me?

**Comment by Branikolog** [comment]
@eos428 
Done!
