### ISSUE TITLE
Town screen, reduce the clickable area for income window

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2825]
In the OG we haven't an option of kingdom income on clicking of resource box in town screen.
The option is useful, but we sometimes need to close income window due to accidental triggering of the window while trying to close town screen.
![image](https://user-images.githubusercontent.com/55348946/108507889-09e79980-72cc-11eb-894d-fccd75e90325.png)
Suggest reduce a little bit of clickable area of income box close to "EXIT" button. (A small row in a few pixel height above "EXIT" button shouldn't trigger anything)
![Area Income](https://user-images.githubusercontent.com/55348946/108508402-cf323100-72cc-11eb-8943-0b3a7c1bfac7.png)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> Suggest reduce a little bit of clickable area of income box close to "EXIT" button. (A small row in a few pixel height above "EXIT" button shouldn't trigger anything)

Good idea. :)
