### ISSUE TITLE
Unhireable hero in tavern with strong army at the first day of the map

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2843]
On a new map I recently started, I noticed, that there was a hero in tavern, with strong army. But I can't hire him.
![image](https://user-images.githubusercontent.com/55348946/108702607-8d96c580-751a-11eb-86c1-d586451ff624.png)
The next turn it disappears.
Also, while restarting the map the next time, the same hero can also appears at the same place in tavern either with normal army or with another not starting army:
![image](https://user-images.githubusercontent.com/55348946/108702791-cafb5300-751a-11eb-942b-9d1bf6e59f54.png)
![image](https://user-images.githubusercontent.com/55348946/108702825-d5b5e800-751a-11eb-8f46-6efe3ff25ae5.png)
(Two above screenshots are made in the first day of a new game of the same map)
Also, after creating new game on the other map I could sometimes catch other unhireable heroes:
![image](https://user-images.githubusercontent.com/55348946/108703039-23325500-751b-11eb-8053-bb566722175d.png)
Here's a savefile of the first case:
[O__O.zip](https://github.com/ihhub/fheroes2/files/6021634/O__O.zip)
Map:
[map003.zip](https://github.com/ihhub/fheroes2/files/6021658/map003.zip)

**Comment by Branikolog** [comment]
@idshibanov, hello!
I remember, you've recently made some changes regarding heroes...
Could you, please, check if something went wrong?

**Comment by Branikolog** [comment]
To reproduce bug:
Load savefile - check hero in tavern - start new game without any changes.  (Even some other maps can have same bug)

**Comment by Branikolog** [comment]
Had caught a hero in tavern, that I already had!
![image](https://user-images.githubusercontent.com/55348946/108704527-334b3400-751d-11eb-8e8d-7758b40ce6df.png)
![image](https://user-images.githubusercontent.com/55348946/108704549-39d9ab80-751d-11eb-8410-50d283f82265.png)

**Comment by ihhub** [comment]
The same hero exists at the map:
![image](https://user-images.githubusercontent.com/19829520/108713383-1b8ea280-7553-11eb-989a-cfb2f7c526b9.png)
