### ISSUE TITLE
Won't run on macOS High Sierra 10.13.6

### ISSUE THREAD

**Issue by elias137** [ihhub/fheroes2#2851]
Won't run on macOS High Sierra 10.13.6, getting an error:

/Users/elias137/Downloads/\!GAMES/fheroes2/fheroes2_osx_sdl2/fheroes2 ; exit;
dyld: Library not loaded: /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib
  Referenced from: /Users/elias137/Downloads/!GAMES/fheroes2/fheroes2_osx_sdl2/fheroes2
  Reason: Incompatible library version: fheroes2 requires version 15.0.0 or later, but libSDL2-2.0.0.dylib provides version 13.0.0
Abort trap: 6
logout

**Comment by ihhub** [comment]
Hi @elias137 , sadly bu our compilation server is macOS 10.15 that's why you receive such error. Could you please compile the project on your PC by executing these commands in terminal (just create any folder for this):
```
git clone https://github.com/ihhub/fheroes2
cd fheroes2
make -j4
```
In this case fheroes2 will be built according to your OS needs.

**Comment by ihhub** [comment]
@elias137 , we'll try to compile older versions since one of our servers has macOS 10.11+ virtual machines.

**Comment by elias137** [comment]
> @elias137 , we'll try to compile older versions since one of our servers has macOS 10.11+ virtual machines.
That would be super cool! As I'm getting errors while compiling on my Mac:

In file included from audio_music.cpp:26:
./audio_mixer.h:31:10: fatal error: 'SDL_mixer.h' file not found
#include <SDL_mixer.h>
         ^~~~~~~~~~~~~
c++ -c -MD dir.cpp -I/usr/local/include/SDL2 -D_THREAD_SAFE -std=c++11 -O3  -fsigned-char -Wall -Wextra -Wpedantic -Wfloat-conversion -Wshadow -Wfloat-equal -Wredundant-decls -Wdouble-promotion -Wunused -Wuninitialized -DWITH_MIXER -DWITH_TTF -DWITH_XML -DWITH_ZLIB -DWITH_ICONV -I../thirdparty/libsmacker
In file included from audio_mixer.cpp:27:
./audio_mixer.h:31:10: fatal error: 'SDL_mixer.h' file not found
#include <SDL_mixer.h>
         ^~~~~~~~~~~~~
1 error generated.
make[2]: *** [audio_mixer.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 error generated.
make[2]: *** [audio_music.o] Error 1
make[1]: *** [all] Error 2
make: *** [all] Error 2

**Comment by ihhub** [comment]
Could you please run `script/macos/install_sdl_2.sh` script? Your machine is missing needed packages.

**Comment by elias137** [comment]
> Could you please run `script/macos/install_sdl_2.sh` script? Your machine is missing needed packages.

Yes, it's worked for me! Thanks!
