### ISSUE TITLE
Summon boat spell should have 100% success rate

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2858]
In the OG "Summon Boat" spell can always summon a boat (In a case there's any available)
Currently, the spell can sometimes fail in no reason.
![image](https://user-images.githubusercontent.com/55348946/109049243-17948900-76e9-11eb-9908-705bc83f4b2f.png)

**Comment by vasilenkoalexey** [comment]
I will make a push request soon for this one

**Comment by Branikolog** [comment]
Okay! :)

**Comment by LeHerosInconnu** [comment]
For information, there is a similar issue here: https://github.com/ihhub/fheroes2/issues/2175. :)

**Comment by Branikolog** [comment]
@LeHerosInconnu 
Oh! True!
I hope contributor would fix it in a few days, so we can close both at once.)
