### ISSUE TITLE
Hero's disappearance after move through enemy

### ISSUE THREAD

**Issue by undef21** [ihhub/fheroes2#2888]
![Снимок экрана_2021-03-01_09-13-09](https://user-images.githubusercontent.com/71143197/109458992-f4facb00-7a6e-11eb-8d8a-58ac23e1b269.png)
Attack vampires by Crodo. After 2 battles hero will disappear.
![Снимок экрана_2021-03-01_09-15-01](https://user-images.githubusercontent.com/71143197/109459135-40ad7480-7a6f-11eb-8022-f44cc8757fa2.png)

Save: 
[bug.zip](https://github.com/ihhub/fheroes2/files/6059498/bug.zip)

~Also, sometimes in this position I have game crash with message:
`fheroes2: ../fheroes2/battle/battle_board.cpp:824: void Battle::Board::SetCobjObject(int, s32): Assertion 'at( dst + 1 ).GetObject() == 0' failed.`~

**Comment by ihhub** [comment]
The assertion is fixed.

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu @Branikolog Hi, can you help me a little here? I would like to understand how the pathfinding algorithm works in original Heroes II in such situations. Where exactly will it allow you to go from this cell and how? The fact that the hero passes through monsters is clearly abnormal, and I think I can fix this, but but I need to understand which algorithm will be correct here. Is it allowed to pass by the monsters on the clean cells directly adjacent to them? Screenshots with allowed paths from original Heroes II are welcome.

**Comment by Branikolog** [comment]
Hi @oleg-derevenetz!
In the OG it's quite simple: Hero can move only close to monsters, but cannot step over them:
![image](https://user-images.githubusercontent.com/55348946/110234022-34c32600-7f39-11eb-99da-61854be82d7c.png)
Once hero approaches, the interaction occurs:
![image](https://user-images.githubusercontent.com/55348946/110234038-53c1b800-7f39-11eb-8224-6dba7c373dae.png)
(actually, I don't know the algorithm, what creature should be triggered in this situation)
So, after interaction with monsters hero shouldn't trigger other, until he makes any move:
![image](https://user-images.githubusercontent.com/55348946/110234115-d2b6f080-7f39-11eb-96fe-e8bcb535d39d.png)
![image](https://user-images.githubusercontent.com/55348946/110234124-d8acd180-7f39-11eb-8d47-e136963800e9.png)
![image](https://user-images.githubusercontent.com/55348946/110234137-e3676680-7f39-11eb-9cd2-9d83278648a0.png)
If hero has any free cell close to him he should be able to stand it and trigger another interaction with one of the adjacent monsters.
![image](https://user-images.githubusercontent.com/55348946/110234180-17428c00-7f3a-11eb-8d4d-8c5f92045542.png)
![image](https://user-images.githubusercontent.com/55348946/110234184-20335d80-7f3a-11eb-9fc7-cfa7ce886cf4.png)
So it could happen such thing: hero can pass through monsters, but can't return back without triggering any battle once again...
![image](https://user-images.githubusercontent.com/55348946/110234230-52dd5600-7f3a-11eb-9c41-473ee672845c.png)
![image](https://user-images.githubusercontent.com/55348946/110234239-58d33700-7f3a-11eb-9b43-fede35d41183.png)
