### ISSUE TITLE
No animation of water surface

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#289]
Currently we have a static water surface:
![image](https://user-images.githubusercontent.com/19829520/71585408-5fee0080-2b51-11ea-9bea-d8d60f7fe111.png)

While original game has a good water surface animation. We should have it too.

**Comment by idshibanov** [comment]
This is done by the same color cycling (as in lava and unit static animation) which can very tricky to implement correctly. Basically this requires us to swap (cycle) colors on the active palette using predefined pattern.
