### ISSUE TITLE
"MAX" should have "grayish" style for evil interface in troop splitting dialog

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2899]
![image](https://user-images.githubusercontent.com/55348946/110123123-8f417280-7dd1-11eb-9c62-3d756e6da1ab.png)
Creature splitting dialog should have "evil"-style MAX button.

**Comment by LeHerosInconnu** [comment]
Hi @Branikolog,

Just so you don't waste your time (again https://github.com/ihhub/fheroes2/issues/2144) :D, there is a thread related to the Evil interface here: https://github.com/ihhub/fheroes2/issues/1893. :)

**Comment by Branikolog** [comment]
Hello, @LeHerosInconnu!
Thanks! I remember some sort of such topic, but couldn't find it with the help of search tool. :)
I think, I leave this thread opened for now, as this button is currently doesn't suit actual split dialog and looks quite bad. And it should be fixed with higher priority.


(psst...  Don't tell enyone... I heard, Master Developer saw this issue in some video-review of our project and was quite annoyed by the fact, everyone would notice that... So, I think the issue can be fixed in really short terms...)

**Comment by ihhub** [comment]
"Hold my beer" (c)
