### ISSUE TITLE
Scroll bar is shifted in its bottom position

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2900]
In a battle log:
![image](https://user-images.githubusercontent.com/55348946/110124868-b0a35e00-7dd3-11eb-8fce-9467712e25c0.png)
In a scenario list:
![image](https://user-images.githubusercontent.com/55348946/110124902-bdc04d00-7dd3-11eb-8deb-0fa6b1f60865.png)
In Experimental Game Settings:
![image](https://user-images.githubusercontent.com/55348946/110125048-eea08200-7dd3-11eb-80e2-476263feb2d1.png)

**Comment by ihhub** [comment]
Hi @Branikolog , could you please be more specific about this bug? How exactly the bar should look like and what's exactly wrong with it?

**Comment by Branikolog** [comment]
In its bottom position this bar overlaps the bottom frame (1-2 px)

**Comment by Branikolog** [comment]
Also in battle journal:
![image](https://user-images.githubusercontent.com/55348946/110684141-d70b3400-81ed-11eb-8e73-626903fd5aa1.png)
Bar should stop here:
![image](https://user-images.githubusercontent.com/55348946/110684305-091c9600-81ee-11eb-9d3c-f0d828b4c19c.png)
