### ISSUE TITLE
Horse's steps are fading while crossing terrain border using MIDI sound

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2901]
When hero moves from one terrain type to another and the music is changing, horse's steps disappear for a while and then fade up in a few seconds.

**Comment by oleg-derevenetz** [comment]
It seems to be a Windows-specific issue. On Windows SDL mixer uses music volume as a master volume, and game sets a fade-in on music, so when music is changed, fade-in seems to be applied to all sounds (including horse steps, ambient sounds, etc).

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Absolutely correct.
I'm so annoyed by this "feature", I have with windows SDL. :-/
