### ISSUE TITLE
"Town Portal" spell window has texture defect close to buttons

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2907]
In "evil"-type window we have texture defects appearing upon pressing both buttons:
![image](https://user-images.githubusercontent.com/55348946/110210932-36430e80-7ea5-11eb-8c8a-204825ac2b40.png)
![image](https://user-images.githubusercontent.com/55348946/110210939-3fcc7680-7ea5-11eb-89fa-3909179155ed.png)
![image](https://user-images.githubusercontent.com/55348946/110210940-43f89400-7ea5-11eb-86d9-bf6990c140e9.png)

**Comment by idshibanov** [comment]
Unfortunately it's an original resource issue for both Good and Evil interface. Pressed button sprite contains "corners". I used the same buttons for auto combat dialog.

**Comment by Branikolog** [comment]
We've recently fixed same issue for good interface #1066
So here we have a problem only for "evil" interface window.

**Comment by ihhub** [comment]
I'll take a look at all these button issues soon.
