### ISSUE TITLE
End of scenario/campaign animation, show score text after dragon's fire breath and fade to black after input

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2918]
In the original game, after the dragon animation, the screen stays on the last frame of the animation and the player must click to exit the animation screen:
**Edit 2021/03/25.**
**This step is working correctly now.**
![vlcsnap-2021-03-08-12h20m31s420](https://user-images.githubusercontent.com/43583994/110317352-54774e80-800c-11eb-971f-4fb00dfda498.png)
![vlcsnap-2021-03-08-12h20m42s716](https://user-images.githubusercontent.com/43583994/110317359-593c0280-800c-11eb-853c-b921e62c618c.png)

When the player makes a click, there is a fade effect to switch to a black and white image:
![vlcsnap-2021-03-08-12h21m27s173](https://user-images.githubusercontent.com/43583994/110317387-61943d80-800c-11eb-8e7d-5de1ab793fc5.png)

Then a window is displayed to enter the desired name:
![vlcsnap-2021-03-08-12h21m36s492](https://user-images.githubusercontent.com/43583994/110317402-678a1e80-800c-11eb-8a20-1e8700b62804.png)

After validating the name, there is a fade effect and the score screen is displayed:
The mouse cursor is then displayed back on the screen.
![vlcsnap-2021-03-08-12h21m53s286](https://user-images.githubusercontent.com/43583994/110317427-6e189600-800c-11eb-8ad0-2d27595f76c2.png)

In original game:

https://user-images.githubusercontent.com/43583994/110316655-512f9300-800b-11eb-8eee-8d50e40438fc.mp4

In fheroes2:

https://user-images.githubusercontent.com/43583994/110316760-73291580-800b-11eb-874e-ae41aa066279.mp4

Here is the save file:
[Anim Score End mouse curso.zip](https://github.com/ihhub/fheroes2/files/6101097/Anim.Score.End.mouse.curso.zip)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , could you please update this issue as we added waiting user input code.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , could you please update this issue as we added waiting user input code.

First post updated.

**Comment by ihhub** [comment]
I'm marking this issue as high priority because this is an essential missing feature for many players.
