### ISSUE TITLE
Adventure map, Summon Boat spell, the boat is summoned at a location not accessible by the hero while another location is available that would allow him to board immediately

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2919]
In fheroes2, the boat is summoned at a location not accessible by the hero while another location is available that would allow him to board immediately.

In fheroes2:
The boat can be summoned at three locations.
This is fine and normal.
![Summon Boat locations fh2 01](https://user-images.githubusercontent.com/43583994/110320018-f9dff180-800f-11eb-9811-2942fd138cbb.png)

The boat could have been summoned at the bottom location, rather than at the top location and be directly accessible.
![Summon Boat locations fh2 02](https://user-images.githubusercontent.com/43583994/110320040-049a8680-8010-11eb-984b-da65e232da4a.png)

https://user-images.githubusercontent.com/43583994/110320064-0b28fe00-8010-11eb-99cb-564333780dde.mp4

Here is the save file:
End the turn.
[Before summon boat 1000.zip](https://github.com/ihhub/fheroes2/files/6101242/Before.summon.boat.1000.zip)

Related closed issue: https://github.com/ihhub/fheroes2/issues/2172.

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu.
Can you help me, please, with one issue?
Recently I've noticed a strange bahaviour of summoning in OG and fheroes2:
![image](https://user-images.githubusercontent.com/55348946/110632397-a230ba00-81b8-11eb-8f9d-fd41e4d269ab.png)
On a screenshot above (OG) we cannot summon more boats here, Only the upper one was summoned,
The same behaviour is in fheroes2.
BUT when we place any boat in editor here. and start new game a hero can summon another boat at this place, after another hero boards the boat and goes away...

**Comment by LeHerosInconnu** [comment]
Another case for this.

In fheroes2:

![Summon Boat 1000](https://user-images.githubusercontent.com/43583994/132981819-c130d295-f8d9-4f30-9de3-eaa80d459432.png)

Here are the save files (0.9.7 4180):
[Summon Boat wrong location 10.zip](https://github.com/ihhub/fheroes2/files/7149304/Summon.Boat.wrong.location.10.zip)
