### ISSUE TITLE
Cannot summon boats close to some objects on a world map

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2935]
![110632397-a230ba00-81b8-11eb-8f9d-fd41e4d269ab](https://user-images.githubusercontent.com/55348946/110683159-ca3a1080-81ec-11eb-8a40-86dfba8c659e.png)
Hero can summon only one boat (the upper cell) and cannot do it for other free cells on a beach.
Interesting thing: if at the beginning of a game these both cells contain boats, hero can summon boats here  later.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog could you please provide a save file for this issue? I'll try ro take a look at it.

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz 

[Summon Boat.zip](https://github.com/ihhub/fheroes2/files/6336298/Summon.Boat.zip)

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog Thanks! It's because of lighthouse that occupies two cells. I'm not sure is there anything possible to do about it... I'll think about it however.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog I just tried this in OG and it looks like OG have the same behavior?

**Comment by Branikolog** [comment]
@oleg-derevenetz 
True.
But this is not ok, when we cannot summon boat in these cells. While we can, if boats were placed there in the beginning of a game.

**Comment by felix642** [comment]
Hi @Branikolog , @oleg-derevenetz
What should we do with this issue? 
Should we allow players to summon boats near the lighthouse or should we remove the possibility for players to summon boats if they were placed there in the beginning of a game ?

**Comment by oleg-derevenetz** [comment]
Hi @felix642 Well, opinions are varying: I think that it's OG behavior, @Branikolog think that it is a bug in OG and should be fixed. If you agree that this is a bug, you are free to fix it, I suppose that this shouldn't break anything.

**Comment by Branikolog** [comment]
Hi, @felix642 and @oleg-derevenetz!
I'm really can't understand, why do we can summon boat in some cases, while cannot in others... It's definitely broken logic. 
If we want to prevent player from summoning in certain areas, we should create a special event for this. In all other cases player should be able to summon boat at any place he physically can embark.
