### ISSUE TITLE
Screen dimming

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#295]
In original game, when you switch between map and city windows, or between city and hero windows there's black dimming, that last's about half of second.
![Безымянный4](https://user-images.githubusercontent.com/55348946/71620770-6a051300-2bd4-11ea-8ebd-9cf4f00bf883.jpg)

**Comment by idshibanov** [comment]
I think this doesn't make sense for resolutions higher than 640x480 because windows doesn't take up the whole screen. Is it worth doing just for the smallest resolution?

**Comment by ihhub** [comment]
We already have an implementation of this in our source code. We could do this for native (640x480) resolution for now.
