### ISSUE TITLE
Combat screen, 2-hex troops cannot reach moat hex and skip turn or start moving the wrong direction

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2951]
When we place 2-hex troop (here Medusas) in a certain place inside castle:
![Medusa problem](https://user-images.githubusercontent.com/55348946/111041972-f56e6b00-844b-11eb-867b-1538ea745c0f.png)
![Medusa problem 2](https://user-images.githubusercontent.com/55348946/111041996-20f15580-844c-11eb-9014-86950f9624e2.png)
And then we select a place to enter the moat - Medusas skip its turn and don't perform any action.

Edit:
The same happens here:
![Medusa problem 5](https://user-images.githubusercontent.com/55348946/111042403-43846e00-844e-11eb-8ccd-2a9b0cd0a025.png)

Alos, if we place Medusas other place and try to reach the same cell - they move into wrong direction and stuck in a moat:
![Medusa problem 3](https://user-images.githubusercontent.com/55348946/111042107-b391f480-844c-11eb-9931-e32b4878c324.png)
![Medusa problem 4](https://user-images.githubusercontent.com/55348946/111042119-c86e8800-844c-11eb-8525-2d099a4464ef.png)

**Comment by Branikolog** [comment]
Also,  defending creatures seem to lose some movement points while moving from the issue cell:
![image](https://user-images.githubusercontent.com/55348946/111042230-66625280-844d-11eb-8440-ac4a7ffbca38.png)

**Comment by Branikolog** [comment]
One more problem place.
Medusas (both stacks at the mirrored sides of castle walls) while rushing the selected cell choose the wrong path and stuck in a moat:
![Medusa problem 6](https://user-images.githubusercontent.com/55348946/111042746-f1444c80-844f-11eb-9f15-d248e8e13dc4.png)

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog

> When we place 2-hex troop (here Medusas) in a certain place inside castle:
> And then we select a place to enter the moat - Medusas skip its turn and don't perform any action.

Seems not observed with #2932:

<img width="639" alt="Centaurs OK 1" src="https://user-images.githubusercontent.com/32623900/111051777-ab46b300-8466-11eb-88a2-36cbbcda7eb6.png">
<img width="639" alt="Centaurs OK 2" src="https://user-images.githubusercontent.com/32623900/111051786-bdc0ec80-8466-11eb-8024-f51eb2ae00bf.png">

> The same happens here:

This is still observed with #2932.

> Alos, if we place Medusas other place and try to reach the same cell - they move into wrong direction and stuck in a moat:

Not observed with #2932:

<img width="639" alt="Centaurs OK 3" src="https://user-images.githubusercontent.com/32623900/111051894-830b8400-8467-11eb-8ca2-dfba0a515cda.png">
<img width="638" alt="Centaurs OK 4" src="https://user-images.githubusercontent.com/32623900/111051896-8e5eaf80-8467-11eb-9f6b-b5bc371169fb.png">

> One more problem place.
> Medusas (both stacks at the mirrored sides of castle walls) while rushing the selected cell choose the wrong path and stuck in a moat:

Not observed with #2932:

<img width="638" alt="Centaurs OK 5" src="https://user-images.githubusercontent.com/32623900/111051977-193faa00-8468-11eb-9ab0-0c5db19016a4.png">
<img width="639" alt="Centaurs OK 6" src="https://user-images.githubusercontent.com/32623900/111051982-2a88b680-8468-11eb-8ba2-cda6c65400f2.png">

> Also, defending creatures seem to lose some movement points while moving from the issue cell:

Seems not to be the case with #2932 too (if I understand the issue correctly):

<img width="639" alt="Unicorn OK" src="https://user-images.githubusercontent.com/32623900/111052064-cfa38f00-8468-11eb-8ecf-3cf8603538a0.png">
