### ISSUE TITLE
World map, allied AI hero(s) standing without any actions

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2959]
One of the main starting allied heroes is standing for more than a month in a starting location.
Also there's some other heroes with similar problem...
![image](https://user-images.githubusercontent.com/55348946/111125873-21403c80-8583-11eb-9d4a-1dfd81c4a4a9.png)
[01 bug.zip](https://github.com/ihhub/fheroes2/files/6139888/01.bug.zip)

**Comment by ihhub** [comment]
Verified on the latest build: AI hero don't stand anymore at one place.
