### ISSUE TITLE
Retreat window animation

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#296]
Retreat window animation is playing way too slow and laggy.
![Безымянный4](https://user-images.githubusercontent.com/55348946/71621068-f6fc9c00-2bd5-11ea-81bf-6f480c0646ca.jpg)

**Comment by ihhub** [comment]
Hi @Branikolog , could you please verify this issue again? I think we've fixed it.

**Comment by Branikolog** [comment]
> Hi @Branikolog , could you please verify this issue again? I think we've fixed it.

Animation became faster, is looped. It should be played once.

**Comment by Branikolog** [comment]
Also, i've noticed, that animation is not full. In the original game in the window we can see fighting troops at first, and few seconds later they start fleeding. 
But in 0.7 version animation starts from the moment troops running.
