### ISSUE TITLE
Inactive OKAY button in some (all?) enemy artifact capture windows

### ISSUE THREAD

**Issue by hgdagon** [ihhub/fheroes2#3003]
Was playtesting the demo and came across these 2 windows one after the other on 2 different enemies. The OKAY button was inactive, but pressing `Enter` exited the window just fine. Haven't tested this with the full version yet.

![](https://user-images.githubusercontent.com/15173076/112103010-5c83d200-8b66-11eb-9c2b-bbc449ed779a.png)

![](https://user-images.githubusercontent.com/15173076/112103009-5c83d200-8b66-11eb-9731-3e49138dd652.png)

**Comment by Branikolog** [comment]
This happens only after instant battle.
