### ISSUE TITLE
[Possibly not a bug] Warlock town: Cave visible before it's built

### ISSUE THREAD

**Issue by hgdagon** [ihhub/fheroes2#3007]
On the "Dungeon Below" mission, you start off as a warlock with no cave built in town. Yet, it's visible, but you cannot click on it. After building it, the sprite barely changes (there's a minor change at the top, I guess). Not sure if it's a bug, since it's the same with the og engine.

**Comment by Branikolog** [comment]
I think the issue already exists as #2614.
