### ISSUE TITLE
Creature recruit window, "MIN" button, the spacing between letters is too large

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3019]
In fheroes2, for the "MIN" button, the spacing between the letters is too large.

Button currently with letters overspaced:
![Recruit creature wrong MIN fh2 coupé 01](https://user-images.githubusercontent.com/43583994/112640020-3baacd80-8e41-11eb-93e4-0498ae80b5af.png)

What the button should look like:
![Recruit creature correct MIN fh2 coupé 01](https://user-images.githubusercontent.com/43583994/112640057-436a7200-8e41-11eb-973d-ec489be853a1.png)

Related closed issue: https://github.com/ihhub/fheroes2/issues/1736.

**Comment by Branikolog** [comment]
Such wide spacing between letters was made to match the design of MAX button.
![image](https://user-images.githubusercontent.com/55348946/112641335-571ed400-8e53-11eb-928f-2ec1cbe6d01b.png)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> Such wide spacing between letters was made to match the design of MAX button.

The difference in spacing between the letters is very noticeable.
Look at the "OKAY" and "CANCEL" buttons and look at the "MIN" button, it doesn't work.
It hurt my eyes.
The spacing rule for letters in the text should be the same in all buttons.

**Comment by Branikolog** [comment]
@LeHerosInconnu 
> It hurt my eyes.

I can tell the same thing, while looking on the spaces between letters and right and left borders of the button... :D

Actually, here we should choose between these two implementations (As they're both not ideal).... And for me personally, it looks better, in a case we switch MIN/MAX buttons, when the first and the last letters of both buttons keep the same place...

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> @LeHerosInconnu
> 
> > It hurt my eyes.
> 
> I can tell the same thing, while looking on the spaces between letters and right and left borders of the button... :D

![Texte 02 01](https://user-images.githubusercontent.com/43583994/112651730-f7bdc580-8e4c-11eb-901a-2e13bf44d82a.png)
![Texte 02 02](https://user-images.githubusercontent.com/43583994/112651768-01472d80-8e4d-11eb-8990-f43acabdb41f.png)

> Actually, here we should choose between these two implementations (As they're both not ideal).... And for me personally, it looks better, in a case we switch MIN/MAX buttons, when the first and the last letters of both buttons keep the same place...

![Texte 02](https://user-images.githubusercontent.com/43583994/112651214-79612380-8e4c-11eb-9bf6-08f28d5aae9d.png)

**Comment by Branikolog** [comment]
They're a little bit different spaces between words on your text. :D

On topic:
No, only in this particular case. ;)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

I think it's better to have all the buttons in the interface with the same rules:
- Same font with the same spacing for the letters in the font.
- All letters of the button text in capital letters.
- Text centered horizontally and vertically in the button.

It's more harmonious.
