### ISSUE TITLE
A hypronize creature can't attack another hypnotuzed creature

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#3031]
Start a battle and hypnotize a creature on each side. Try to attack one another:
![image](https://user-images.githubusercontent.com/19829520/112744458-da1a6880-8fd2-11eb-95e6-ea6ac28a9fcd.png)

**Comment by oleg-derevenetz** [comment]
Hi @ihhub It seems that the alternative will be that hypnotized creatures from the SAME ARMY will not be able to attack each other (in case if we verify the target using current color instead of army color) :) What is the behavior in OG in this case?

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , as far as I understand, logically these 2 monsters are in opposite armies.
@Branikolog , could you please OG behavior?

**Comment by oleg-derevenetz** [comment]
@ihhub Yes, now unit have an "army color" (the original affiliation to a particular army) and "current color" (after hypnotize or berserk). If we choose to select a target using "current color" instead of "army color", then it solves this issue, but the new one arrives - two hypnotized units from the same army will have the same "current color" so they will not be able to attack each other.

**Comment by Branikolog** [comment]
@ihhub, @oleg-derevenetz 
In the OG Hypnotized creature cannot attack another hypnotized creature...
But when we hypnotize both creatures in the same army - they can attack each other...

**Comment by oleg-derevenetz** [comment]
@Branikolog Thank you! It's so hard to get this spell to work without patching sources (in fheroes2) and (maybe) cheats in OG :) Well, then in OG behavior is the same as current behavior in fheroes2.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Welcome!
![image](https://user-images.githubusercontent.com/55348946/112747215-81d86c00-8fbc-11eb-84ee-b45aac4bb258.png)
Look, here all creatures are hypnotized.
Cavalry cannot attack boars. So in a case players don't have mana for spells, they have to wait until spell's duration will over. :)

**Comment by oleg-derevenetz** [comment]
@ihhub @Branikolog I think this is the logic here: each commander is trying to save his own troops (even temporary hypnotized), but he tries to destroy the enemy troops (including hypnotized), so everything is consistent. The developers of the OG thought the same way.

**Comment by oleg-derevenetz** [comment]
@ihhub @Branikolog I think there is a logic here: each commander tries to save his own troops (even temporary hypnotized) but attacks enemy troops (including hypnotized ones). It seems that developers of OG reasoned the same way :)

**Comment by ihhub** [comment]
In this case we can close this issue🙂
