### ISSUE TITLE
Hero shouldn't gain any experience when enemy flees without any loss

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#3034]
In the OG hero gains 0 exp when enemy flees.
In fheroes hero receives 500 exp.
![image](https://user-images.githubusercontent.com/55348946/112750521-bb67a200-8fd1-11eb-8d31-0996f7fc5811.png)

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog It seems that now the winning hero always get additional 500 experience points if the opposing army was led by a hero. I don't know where did this come from. Maybe there are some reasons for this additional experience?

**Comment by Branikolog** [comment]
@oleg-derevenetz if I'm not mistaken, we previously had an "experimental" option of this kind...
Currently it seems to be out of game... But effect is on on some reason...

**Comment by undef21** [comment]
@oleg-derevenetz, src/fheroes2/battle/battle_arena.cpp:502

**Comment by oleg-derevenetz** [comment]
Hi @undef21 Yes, thank you, I already found this place... But I wasn't sure is this for a reason (for example, there are some game mechanics, just incorrectly implemented) or what :) @Branikolog tells (if I understand correctly) that this was related to some experimental feature which was then removed.

**Comment by oleg-derevenetz** [comment]
According to git blame, this code was here since the first import 2 years ago... So the reason is lost in the darkness of the ages :)

**Comment by oleg-derevenetz** [comment]
@Branikolog It seems that in OG hero actually gains additional 500 experience if if he defeats the opposing hero, but not if opposing hero surrenders or flees.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Seems to be true:
![image](https://user-images.githubusercontent.com/55348946/112752230-a3485080-8fda-11eb-98f9-21461b3b2bbd.png)
