### ISSUE TITLE
Arm of the Martyr has incorrect rendering

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#3043]
This is how it looks in the original game:
![image](https://user-images.githubusercontent.com/19829520/112757233-6ea8b900-901b-11eb-81e9-a5b278093a81.png)
and this is how it looks in our project:
![image](https://user-images.githubusercontent.com/19829520/112757159-2093b580-901b-11eb-9778-4d64e6276a1b.png)

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

The bug is also present in the original game.
It comes from a wrong color (tranparency) in the sprite of the original game.

In original game:

![0088](https://user-images.githubusercontent.com/43583994/112758338-27580380-8fee-11eb-9b30-a52128303bab.png)
