### ISSUE TITLE
Digging problem

### ISSUE THREAD

**Issue by undef21** [ihhub/fheroes2#3058]
Map is Alteris2.
Artifact is placed here by scenario:
![Снимок экрана_2021-03-30_12-24-41](https://user-images.githubusercontent.com/71143197/112967445-f2fe5780-9153-11eb-8223-fb85a3648de0.png)
![Снимок экрана_2021-03-30_12-09-51](https://user-images.githubusercontent.com/71143197/112967009-74091f00-9153-11eb-8132-916d0df7b82c.png)

Try to dig Ultimate artifact by Crodo
![Снимок экрана_2021-03-30_12-24-10](https://user-images.githubusercontent.com/71143197/112967096-8d11d000-9153-11eb-89cf-ff1735e8de1c.png)

Also, last obelisk is not avaibled for Ariel.
![Снимок экрана_2021-03-30_12-30-10](https://user-images.githubusercontent.com/71143197/112967352-dd892d80-9153-11eb-8597-f06677978804.png)

Save: 
[artifact.zip](https://github.com/ihhub/fheroes2/files/6227980/artifact.zip)

**Comment by ihhub** [comment]
Ultimate Artifact digging issue is fixed by @oleg-derevenetz .

**Comment by undef21** [comment]
Confirm. Issue with obelisk is needed with additional checks and should be separate. In the original game I can't move Ariel to those obelisk so close with Dimensional Door.
