### ISSUE TITLE
Adventure map, defeated creature should be vanished before hero disappears in "Stone Liths"

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#3074]
Hero attacks peasants.
![image](https://user-images.githubusercontent.com/55348946/113305077-57174c00-930b-11eb-89f3-c85abf2ccd00.png)
After victory hero changes his location. But peasants vanish only after hero appears in the exit "Stone Liths"
![image](https://user-images.githubusercontent.com/55348946/113305281-88901780-930b-11eb-919b-ccd1219e5faf.png)
![image](https://user-images.githubusercontent.com/55348946/113305341-980f6080-930b-11eb-9631-b4df77c2cca5.png)

**Comment by oleg-derevenetz** [comment]
I think that's the same bug as #1151. May I ask you to attach the savefile?

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz !
Yes. This issues seem to be similar. 
Unfortunately, I'm out of my PC now. 
Can you wait a few hours for me attaching savefile here, please?

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog Of course, thank you!

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Here's a save file.
[Stone Liths.zip](https://github.com/ihhub/fheroes2/files/6245355/Stone.Liths.zip)

**Comment by oleg-derevenetz** [comment]
@Branikolog Thank you!
