### ISSUE TITLE
Hero's path through sphinx

### ISSUE THREAD

**Issue by undef21** [ihhub/fheroes2#3094]
![Снимок экрана_2021-04-04_01-22-12](https://user-images.githubusercontent.com/71143197/113493019-9a78e280-94e4-11eb-806e-2ef6fdaff016.png)
Hero attacks medusas. Sphinx triggers after fight.

~Also, after answering sphing question hero doesn't get 15 mercury.~
![Снимок экрана_2021-04-04_01-23-32](https://user-images.githubusercontent.com/71143197/113493074-0d825900-94e5-11eb-89ef-86e625384a61.png)

[sphix_bug.zip](https://github.com/ihhub/fheroes2/files/6253597/sphix_bug.zip)

**Comment by ihhub** [comment]
Missing mercury issue is fixed.

**Comment by undef21** [comment]
Possibly closed by #3756. I can't check it because sav file is old format.
