### ISSUE TITLE
Cannot confirm end turn while cursor is over options buttons

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#3104]
Dialog disappears without any action proceeded when we press Enter while pointing one of the buttons.
![image](https://user-images.githubusercontent.com/55348946/113504159-fff9bd00-953e-11eb-9390-34a8be55e851.png)

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog I can't reproduce this. Here's what I did:

1. Run fheroes2, New Game->Standard Game->choose the Alteris map->skip all introduction dialogs;
2. Press End Turn button, dialog "One or more heroes may still move" arrives;
3. Move mouse pointer to disabled "Continue move" button;
4. Press Enter;
5. A new day begins, as it should be.

**Comment by Branikolog** [comment]
Hello, @oleg-derevenetz !
Try to initiate end turn by pressing "E" button.
It seems that while using mouse to push the button everything works fine. o_O
