### ISSUE TITLE
What are minimal platform-independent system requirements of this?

### ISSUE THREAD

**Issue by KOLANICH** [ihhub/fheroes2#3112]
I mean size of RAM.

**Comment by ihhub** [comment]
Hi @KOLANICH , it really depends on a resolution. What's your resolution?

**Comment by KOLANICH** [comment]
480x272

**Comment by ihhub** [comment]
The minimal resolution for the game is 640 x 480. Right now it requires around 60 MB RAM.

**Comment by KOLANICH** [comment]
>The minimal resolution for the game is 640 x 480. Right now it requires around 60 MB RAM.

So it won't fit PSP-1xxx ("Thick") in its current state neither by memory nor by screen.

I wonder if there is any model allowing one to predict memory consumption based on screen size. I guess it may be something like `const not dependent on resolution + video buffer + f(sprites fitting the screen)`. Can it be built by compiling the game with dufferent resolutions, running against a benchmark file and fitting the coefficients?

**Comment by ihhub** [comment]
Hi @KOLANICH , we do not have any formula for this as we don't have need to do it.

**Comment by ihhub** [comment]
I'm closing this issue as the primary question was answered.
