### ISSUE TITLE
Mine guardian icon does not disappear after defeat

### ISSUE THREAD

**Issue by senneschall** [ihhub/fheroes2#3114]
When you set any guardian on a mine and the AI defeats the guardian, the monster icon is still on the mine, even though there's no guardian there any more.

**Comment by oleg-derevenetz** [comment]
Hi @senneschall @Branikolog Where is exactly this monster icon is shown? When I assign a guardian on a mine, I only see "Guarded by XXX" in quick info. Should I additionally enable something in settings or somewhere?

**Comment by Branikolog** [comment]
![image](https://user-images.githubusercontent.com/55348946/114231858-a8ff4800-9983-11eb-8833-23002c273722.png)

**Comment by oleg-derevenetz** [comment]
@Branikolog Ah, that's some another guardian, not related to "world: allow set guardian to objects". Is this a spell?

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Yes. It's 4-th level spell "Set Air/Water/Earth/Fire Guardian". :)

**Comment by oleg-derevenetz** [comment]
@Branikolog Thank you!
