### ISSUE TITLE
highscore points can be messed up

### ISSUE THREAD

**Issue by senneschall** [ihhub/fheroes2#3121]
![fheroes2092highscorebug](https://user-images.githubusercontent.com/14364389/113864054-bb725980-97aa-11eb-999c-bf36ca33f91b.jpg)
To my eyes this looks like there is some sort of negative int -> uint conversion error where the last three digits are just cut out. I can reproduce this when I play a very long game. I'll attach a savegame for a game when this happenes:
[savegame.zip](https://github.com/ihhub/fheroes2/files/6271416/savegame.zip)

**Comment by oleg-derevenetz** [comment]
That's because here:

https://github.com/ihhub/fheroes2/blob/849fcf7b9e295f176a3f567e968f7712125f2ca7/src/fheroes2/game/game.cpp#L472

is assumed that `nk` never exceed 200, but in your case it is 264, so we get a negative number which then turns into unsigned. @Branikolog @LeHerosInconnu does anyone know the correct formula?

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> That's because here:
> 
> https://github.com/ihhub/fheroes2/blob/849fcf7b9e295f176a3f567e968f7712125f2ca7/src/fheroes2/game/game.cpp#L472
> 
> is assumed that `nk` never exceed 200, but in your case it is 264, so we get a negative number which then turns into unsigned. @Branikolog @LeHerosInconnu does anyone know the correct formula?

Maybe this can help you:

Hello @ihhub,

> Hi @LeHerosInconnu , do you know the formula for displaying creatures in this window?

**dahbk** did it!

It's not really a "formula", but the list of creature correspondence according to the "Rating" for "Scenario", and to the number of "Days" for "Campaign".

https://www.gog.com/forum/heroes_of_might_and_magic_series/homm2_rating_corresponding_creatures

I didn't check for all the scores, but it matches the scores I did.
I think that should be correct. :)

**Scenario.**

"Rating", Monster:
0 Peasant
1 Peasant
2 Peasant
3 Peasant
4 Goblin
5 Goblin
6 Goblin
7 Goblin
8 Sprite
9 Sprite
10 Sprite
11 Sprite
12 Halfling
13 Halfling
14 Halfling
15 Halfling
16 Centaur
17 Centaur
18 Centaur
19 Centaur
20 Rogue
21 Rogue
22 Rogue
23 Rogue
24 Skeleton
25 Skeleton
26 Skeleton
27 Skeleton
28 Orc
29 Orc
30 Orc
31 Orc
32 Zombie
33 Zombie
34 Zombie
35 Zombie
36 Archer
37 Archer
38 Archer
39 Archer
40 Ranger
41 Ranger
42 Ranger
43 Ranger
44 Boar
45 Boar
46 Boar
47 Boar
48 Dwarf
49 Dwarf
50 Dwarf
51 Dwarf
52 Mutant zombie
53 Mutant zombie
54 Mutant zombie
55 Mutant zombie
56 Orc Chieftain
57 Orc Chieftain
58 Orc Chieftain
59 Orc Chieftain
60 Elf
61 Elf
62 Elf
63 Elf
64 Gargoyle
65 Gargoyle
66 Gargoyle
67 Gargoyle
68 Pikeman
69 Pikeman
70 Pikeman
71 Pikeman
72 Grand Elf
73 Grand Elf
74 Grand Elf
75 Grand Elf
76 Battle Dwarf
77 Battle Dwarf
78 Battle Dwarf
79 Battle Dwarf
80 Nomad
81 Nomad
82 Nomad
83 Nomad
84 Veteran Pikeman
85 Veteran Pikeman
86 Veteran Pikeman
87 Veteran Pikeman
88 Wolf
89 Wolf
90 Wolf
91 Wolf
92 Mummy
93 Mummy
94 Mummy
95 Mummy
96 Iron Golem
97 Iron Golem
98 Iron Golem
99 Iron Golem
100 Royal Mummy
101 Royal Mummy
102 Royal Mummy
103 Royal Mummy
104 Ogre
105 Ogre
106 Ogre
107 Ogre
108 Griffin
109 Griffin
110 Griffin
111 Griffin
112 Swordsman
113 Swordsman
114 Swordsman
115 Swordsman
116 Druid
117 Druid
118 Druid
119 Druid
120 Steel Golem
121 Steel Golem
122 Steel Golem
123 Steel Golem
124 Master Swordsman
125 Master Swordsman
126 Master Swordsman
127 Master Swordsman
128 Air Elemental
129 Air Elemental
130 Air Elemental
131 Air Elemental
132 Greater Druid
133 Greater Druid
134 Greater Druid
135 Fire Elemental
136 Fire Elemental
137 Fire Elemental
138 Ghost
139 Ghost
140 Ghost
141 Vampire
142 Vampire
143 Vampire
144 Water Elemental
145 Water Elemental
146 Water Elemental
147 Earth Elemental
148 Earth Elemental
149 Earth Elemental
150 Roc
151 Roc
152 Roc
153 Minotaur
154 Minotaur
155 Minotaur
156 Cavalry
157 Cavalry
158 Cavalry
159 Troll
160 Troll
161 Troll
162 Mage
163 Mage
164 Mage
165 Medusa
166 Medusa
167 Medusa
168 Lich
169 Lich
170 Lich
171 Ogre Lord
172 Ogre Lord
173 Ogre Lord
174 Minotaur King
175 Minotaur King
176 Minotaur King
177 Champion
178 Champion
179 Champion
180 War Troll
181 War Troll
182 War Troll
183 Vampire Lord
184 Vampire Lord
185 Vampire Lord
186 Archmage
187 Archmage
188 Archmage
189 Power Lich
190 Power Lich
191 Power Lich
192 Unicorn
193 Unicorn
194 Unicorn
195 Hydra
196 Hydra
197 Hydra
198 Paladin
199 Paladin
200 Paladin
201 Genie
202 Genie
203 Genie
204 Crusader
205 Crusader
206 Crusader
207 Cyclops
208 Cyclops
209 Cyclops
210 Giant
211 Giant
212 Giant
213 Phoenix
214 Phoenix
215 Phoenix
216 Bone Dragon
217 Bone Dragon
218 Bone Dragon
219 Green Dragon
220 Green Dragon
221 Green Dragon
222 Red Dragon
223 Red Dragon
224 Red Dragon
225 Titan
226 Titan
227 Titan
228 Black Dragon 

**Campaign.**

"Days", Monster:
0-300 Black Dragon
301-320 Titan
321-340 Red Dragon
341-360 Green Dragon
361-380 Bone Dragon
381-400 Phoenix
401-420 Giant
421-440 Cyclopse
441-460 Crusader
461-480 Genie
481-500 Paladin
501-520 Hydra
521-540 Unicorn
541-560 Power Lich
561-580 Archmage
581-600 Vampire Lord
601-620 War Troll
621-640 Champion
641-660 Minotaur King
661-680 Ogre Lord
681-700 Lich
701-720 Medusa
721-740 Mage
741-760 Troll
761-780 Cavalry
781-800 Minotaur
801-820 Roc
821-840 Earth Elemental
841-860 Water elemental
861-880 Vampire
881-900 Ghost
901-920 Fire Elemental
921-940 Greater druid
941-960 Air Elemental
961-980 Master Swordsman
981-1000 Steel Golem
1001-1100 Druid
1101-1200 Swordsman
1201-1300 Griffin
1301-1400 Ogre
1401-1500 Royal Mummy
1501-1600 Iron Golem
1601-1700 Mummy
1701-1800 Wolf
1801-1900 Veteran Pikeman
1901-2000 Nomad
2001-2200 Battle Dwarf
2201-2400 Grand Elf
2401-2600 Pikeman
2601-2800 Gargoyle
2801-3000 Elf
3001-3200 Orc Chieftain
3201-3400 Mutant Zombie
3401-3600 Dwarf
3601-3800 Boar
3801-4000 Ranger
4001-4200 Archer
4201-4400 Zombie
4401-4600 Orc
4601-4800 Skeleton
4801-5000 Rogue
5001-5200 Centaur
5201-5400 Halfling
5401-5600 Sprite
5601-5800 Goblin
5801-∞ Peasant

_Originally posted by @LeHerosInconnu in https://github.com/ihhub/fheroes2/issues/954#issuecomment-742099166_

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu Thank you! However that's just a match table between points and monsters, but there is nothing here about how exactly points are counted :( So far all I've found is the similar formula, but from H3:

http://heroescommunity.com/viewthread.php3?TID=14020&PID=279535#focus

Don't know is this applicable to H2 as well though... It looks like current implementation uses different formula that takes map size into account and with some intricate dependency on mission time.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> Hi @LeHerosInconnu Thank you! However that's just a match table between points and monsters, but there is nothing here about how exactly points are counted :( So far all I've found is the similar formula, but from H3:
> 
> http://heroescommunity.com/viewthread.php3?TID=14020&PID=279535#focus
> 
> Don't know is this applicable to H2 as well though... It looks like current implementation uses different formula that takes map size into account and with some intricate dependency on mission time.

**dahbk** made a little tool to calculate the score.
Try to contact him on the Gog forum, maybe he knows the exact formula?

https://www.gog.com/forum/heroes_of_might_and_magic_series/homm2_rating_corresponding_creatures/post9

![91699aabb7c025e696478c365995948adc16b13b](https://user-images.githubusercontent.com/43583994/114029388-bd571e00-9879-11eb-9d0b-4e8bc80ef29b.png)

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu Thanks! I'll try to contact this person.

**Comment by undef21** [comment]
@oleg-derevenetz, from those tool:
`score = (200 - daysScore) * (50 + gameDifficulty + mapDifficulty) / 100;`
`days = days * mapSize / 100; mapSize = { 140, 100, 80, 60 };`
`daysScore = days <= 60 ? days : days <= 120 ? (days / 2 + 30) : days <= 360 ? (days / 4 + 60) : ( days / 8 + 105); if(dayScore > 200) days = 200;`
`gameDifficulty = { 0, 30, 50, 70, 90 };`
`mapDifficulty = { 0, 20, 40, 80 };`

**Comment by oleg-derevenetz** [comment]
Hi @undef21 O, thanks! :)

> `if(dayScore > 200) days = 200;`

`days = 200` or `dayScore = 200`? If the latter, then we can't have "lowest possible score 10", because `(200 - 200) * (50 + gameDifficulty + mapDifficulty) / 100` will be zero anyway. Or we should additionally check that the result is not less than 10?

**Comment by undef21** [comment]
> `days = 200` or `dayScore = 200`?
`dayScore = 200`

This case when "Remove lower limit" checked. If this checkbox is not checked then:
`if(days > 600) dayScore = 180`.

`daysScore = days <= 60 ? days : days <= 120 ? (days / 2 + 30) : days <= 360 ? (days / 4 + 60) : days <= 600 ? ( days / 8 + 105) : 180;`

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> Hi @undef21 O, thanks! :)
> 
> > `if(dayScore > 200) days = 200;`
> 
> `days = 200` or `dayScore = 200`? If the latter, then we can't have "lowest possible score 10", because `(200 - 200) * (50 + gameDifficulty + mapDifficulty) / 100` will be zero anyway. Or we should additionally check that the result is not less than 10?
> 
> P.S. Hmm, according to the match table given above, we still can have scores less than 10 - peasant, goblin and sprite correspond to values 0-9.

By activating the "Remove lower limit" option, a window with an explanatory message is displayed:

![Remove limit 01](https://user-images.githubusercontent.com/43583994/114169167-7e849f00-9931-11eb-9279-fe04154eef84.png)

**Comment by oleg-derevenetz** [comment]
@undef21 @LeHerosInconnu Thanks! :)
