### ISSUE TITLE
treasure chest icon sometimes does not disappear after being opened

### ISSUE THREAD

**Issue by senneschall** [ihhub/fheroes2#3122]
Description: the treasure chest is opened and disappears from the game logic. But the icon very rarely remains visible. As the screenshot shows, you walk over it, it's not really there anymore.
![fheroes2092chestnotdisapeear](https://user-images.githubusercontent.com/14364389/113864571-553a0680-97ab-11eb-95f0-cf34da24cb18.jpg)

I could reproduce this bug, but this happens so rarely I can't definately tell the exact circumstances when this happens. But it always happened later in the games when I don't get any more secondary skills but primary skills. Another theory I have is that this happens when I click away the chest very quickly while the music is still running.

**Comment by Branikolog** [comment]
Hi,  @senneschall !
Could you, please, create save file with this issue, if you manage to catch it again?

**Comment by oleg-derevenetz** [comment]
I really think that's the same bug as #3074 and #1151 and should be resolved by #3081 that was merged recently. @senneschall if you have a desire to build this game from sources, you can build the latest snapshot from master branch and check is this issue still observed.

**Comment by ihhub** [comment]
Correction: you don't need to build to get the latest build. Just search for the build within our releases, mostly second page :)

**Comment by oleg-derevenetz** [comment]
@ihhub May be I am wrong, but it looks like Linux snapshots are outdated in Releases section... Windows and MacOS are fine BTW.

**Comment by senneschall** [comment]
@Branikolog 
There's a savegame attached to #3121. The screenshot comes from that game, the lost treasure chest is to the southwest of the hero, in the snow directly above of the sulfure mine.
When I find the time, I'll try to compile it by myself. But I don't have a working C++ environement running, so this may take some time.

**Comment by oleg-derevenetz** [comment]
Hi @senneschall Is this problem still being observed in latest builds?

**Comment by senneschall** [comment]
Hi @oleg-derevenetz 
it did not occur any other time, but I only had time for some limited testing. Still, it looks like it's gone.

**Comment by oleg-derevenetz** [comment]
Hi @senneschall If this issue is not observed anymore, can I ask you to close it, please? :)

**Comment by senneschall** [comment]
Issue seems to be resolved by now
