### ISSUE TITLE
Castle Siege, all missed shots of catapult are drawn beside balista.

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#3127]
During one siege my Catapult shot the main tower of castle (balista) for more than 10 times and it still was alive!

Edit:
every time catapult misses - we can watch an animation of stone beside the central tower (ballista)

**Comment by oleg-derevenetz** [comment]
Yes, you should destroy the walls first, then two towers on walls, then bridge, and only then you will be able to destroy the main tower. As far as I remember, it's the same in the original game - you can't destroy main tower until all other defenses are destroyed. Also there is always a 25% chance to miss if your hero have no Ballistics skill.

**Comment by Branikolog** [comment]
I'm not sure about the original behaviour, but my catapult shot like 4 times in a row on a central tower with 0 efficiency...
Should we reduce the chance of hitting balista then? :) It's not okay that catapult managed to broke a single wall in ~10 turns because of being constantly shooting an indestructible tower.

**Comment by oleg-derevenetz** [comment]
> Should we reduce the chance of hitting balista then?

I don't think so. With random numbers there is no guarantee that if chance to miss is 1/4 it always will be one miss out of every four shots. It's random, so this ratio will only be observed on a really large number of shots (and even in this case, only approximately).

**Comment by Branikolog** [comment]
I've checked the OG.
There catapult never hits main tower before other castle parts were destroyed.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog is this issue still considered as a bug and, if yes, in what way?

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz !
In the OG catapult never hits the ballista until all other castle parts are destroyed.
In fheroes2 currently it hits the ballista, wasting its shots for nothing, as the ballista can't be destroyed. 
We shouldn't allow catapult to hit ballista, until other castle parts were destroyed.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog

> In fheroes2 currently it hits the ballista, wasting its shots for nothing,

Why do you think that it hits the ballista? It's just an animation of missing shot. Catapult can miss when shooting on any part of the castle - wall, bridge, etc, it always have 25% chance to miss (if attacking hero doesn't have Ballistics).

**Comment by oleg-derevenetz** [comment]
@Branikolog Are you sure that catapult really hits the Ballista a few times in a row (and before other parts of castle defense are still untouched) and Ballista remains alive? In #3159 catapult may shoot the Ballista before other parts of the castle just because they were in fact already destroyed, it was just a bug in animation (because it was performed in reverse order), not in logic.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
I've just tested it in a latest build:
Catapult hit central tower like 4 times in a row, while there were both other towers and gates untouched...(And like 3-4 times before it in the beginning of the battle)
I agree, that 50% of these shots could be unsuccessful, but why do we need to shot the ballista at all here? When our goal is to destroy walls. (As the ballista couldn't be destroyed, no matter how many shots we made at it.)
In the OG catapult NEVER shoots at ballista. So in the OG we can destroy walls much faster, than in fheroes2, where catapult can waste 2-5 shoots at the ballista, which cannot be destroyed at all.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog I don't really see how it is possible (and I never seen this behavior myself yet). According to `Battle::Catapult::GetTarget()` logic, Ballista can't even be selected as a target until other parts of the castle are destroyed. Could you please attach a video of such case? I can't reproduce this yet.

**Comment by Branikolog** [comment]
> P.S. In case of a catapult miss, the stone falls into the courtyard of the castle, may be you take it as a shot at Ballista? But it's not, it's just an animation of a miss.

![image](https://user-images.githubusercontent.com/55348946/116778622-b045dd00-aa7b-11eb-8242-7d6e4d9121d4.png)

So, if it's just an animation of a miss, we should fix it, as this is not the OG behaviour. In the OG we have like two separate sprites of explosion (successful shot and failed shot) and both of these sprites are drawn over a certain wall (or tower) the ballista made a shot at. Not in the courtyard.

**Comment by Branikolog** [comment]
Successful shot in the OG:
![image](https://user-images.githubusercontent.com/55348946/116778842-2ac32c80-aa7d-11eb-8d27-8713c9e4c167.png)
Failed shot in the OG:
![image](https://user-images.githubusercontent.com/55348946/116779174-50503600-aa7d-11eb-8d07-136765d409f3.png)

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog

> So, if it's just an animation of a miss

Yes. Currently, if missed, stone always falls at the same position (with coordinates 610x320 according to `Battle::Catapult::GetTargetPosition()`).

> we should fix it, as this is not the OG behaviour. In the OG we have like two separate sprites of explosion (successful shot and failed shot) and both of these sprites are drawn over a certain wall (or tower) the ballista made a shot at. Not in the courtyard.

Yes, it seems that catapult miss animation doesn't match miss animation in OG. It's cosmetic issue, not an issue with logic. I think it would be nice to rename this issue somehow to reflect results of our investigation :)

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Done. :)
Thank you for revealing the root of the problem.
