### ISSUE TITLE
Adventure map, vanishing creatures sound is not fully played

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#3129]
While using MIDI music the sound of vanishing creatures after battle is cut from its end...

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz 
Could you, please look at this issue?
Something went wrong after one of latest fixes...

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog

On MacOS there is a slight pause near the end of that sound, and then sound continues to play. I suppose that it's because animation ends slightly earlier than the sound finishes playing, and after that there is a slight pause in event processing somewhere, so new sound frames are not pushed to the sound engine, or something like this. If I make this animation slower, there is no intermittent sound. I can make it slower.

**Comment by Branikolog** [comment]
Hello, @oleg-derevenetz 
I think, all fading animations need to be the same.  Not sure that long fading will look well... 
I know about the fact, we experience a bunch of problems with sound... I hope you and the rest of our team invent the solution. ;)

**Comment by oleg-derevenetz** [comment]
Well, it's up to @ihhub now. If he thinks that there is no need in this workaround, he will not merge my PR :)

**Comment by ihhub** [comment]
Now things become weird: I can't reproduce anymore on the latest version. @oleg-derevenetz do you still have the issue?

**Comment by oleg-derevenetz** [comment]
Hi @ihhub No, I have not. But as soon as I rollback commit 69acb064, it appears again. So that commit somehow fixed this issue as well :)

**Comment by oleg-derevenetz** [comment]
I closed #3133 and #3213 for now. As far as I understand, this issue is no longer reproducible?

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , that's right. Do you still have the issue on the latest version?

**Comment by oleg-derevenetz** [comment]
Hi @ihhub No. @Branikolog, do you still have this issue?

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Everything sounds correct now.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog Thank you! It's a miracle! :)

**Comment by ihhub** [comment]
I'm closing this issue as it's magically fixed!

**Comment by Branikolog** [comment]
I wish all other issues would fix themselves in this manner too. ^_^
