### ISSUE TITLE
Combat screen, during a siege, the Drawbridge must always be destroyed before the Ballista

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3159]
In fheroes2, during a siege, the Drawbridge must always be destroyed before the Ballista.

In the original game, it is always this sequence:
- the four Walls first
- the two Turrets next
- then the Drawbridge
- and finally the Ballista

In fheroes2:

https://user-images.githubusercontent.com/43583994/114319601-6b7cf500-9b12-11eb-9889-1d615b4fd701.mp4

Here is the save file:
[Drawbridge before Ballista.zip](https://github.com/ihhub/fheroes2/files/6292679/Drawbridge.before.Ballista.zip)

**Comment by Branikolog** [comment]
Related to #3127.

**Comment by oleg-derevenetz** [comment]
That's because if catapult have a multiple shots in a row, it shoots in "reverse order" (in comparison to planning those shots), so when it shoots at Ballista, it "already knows" that the Drawbridge will be 100% destroyed. This issue is rather cosmetic, but I agree that it should be fixed.
