### ISSUE TITLE
End of scenario animation, clicking during the victory animation must stop the animation and go to the next step

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3160]
Clicking during the victory animation must stop the animation and go to the next step described here (fade effect to switch to a black and white image): https://github.com/ihhub/fheroes2/issues/2918.

In fheroes2, currently when the user clicks the animation is stopped, but nothing happens.
The user has to make a second click to activate the next step.

In original game:

https://user-images.githubusercontent.com/43583994/114320165-e8a96980-9b14-11eb-963b-85ea8eb464a7.mp4

In fheroes2:

https://user-images.githubusercontent.com/43583994/114320174-feb72a00-9b14-11eb-86bb-4e016b36e504.mp4

Here are the save files:
[Drawbridge before Ballista.zip](https://github.com/ihhub/fheroes2/files/6292679/Drawbridge.before.Ballista.zip)
[end 0940.zip](https://github.com/ihhub/fheroes2/files/6292714/end.0940.zip)

**Comment by felix642** [comment]
Hi @LeHerosInconnu can you please confirm if this bug still exists? I've been trying to reproduce it on my side and everything seems fine now. 

https://user-images.githubusercontent.com/60141446/123885197-f05dfa80-d91a-11eb-916d-227ec1361174.mp4

Of course we don't have the fading animation but this is related to another issue #2918

**Comment by LeHerosInconnu** [comment]
Hello @felix642,

> Hi @LeHerosInconnu can you please confirm if this bug still exists? I've been trying to reproduce it on my side and everything seems fine now.
> Of course we don't have the fading animation but this is related to another issue #2918

Effectively, it seems to work correctly.
I close the issue. Thank you.
