### ISSUE TITLE
Autosave file, the name of the AUTOSAVE file is no longer written in capital letters

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3178]
In fheroes2, the name of the AUTOSAVE file is no longer written in capital letters.

In fheroes2:

![Autosave not upper case fh2 10](https://user-images.githubusercontent.com/43583994/114726460-b3339480-9d3d-11eb-99d6-ba21b942fa47.png)

Related closed issue: https://github.com/ihhub/fheroes2/issues/1999.

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu is this observed on Windows? On macOS it still named in capital letters.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> Hi @LeHerosInconnu is this observed on Windows? On macOS it still named in capital letters.

Yes.
My OS: Windows 7 64 bits Edition Familiale Premium Service Pack 1, with fheroes2 - 0.9.2 3170 - Windows x64 build with SDL2 support.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , could you please delete existing autosave file and check again? I remember that if you have an existing file it won't become all capital letters till you delete it. From then on you'll have a correct name.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , could you please delete existing autosave file and check again? I remember that if you have an existing file it won't become all capital letters till you delete it. From then on you'll have a correct name.

It worked. :)
Thanks.
