### ISSUE TITLE
Screen doesn't move to selected hero

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#318]
Screen doesn't move while switching between two heroes. One of them stands close to the edge of map. The second hero is in the distance, that the first hero is not on the screen. While switching from the second hero to the first, screen stays the same place.
![Безымянный6](https://user-images.githubusercontent.com/55348946/73055728-1bc2f700-3e96-11ea-914c-19fc2ccc8419.jpg)
![Безымянный7](https://user-images.githubusercontent.com/55348946/73055729-1bc2f700-3e96-11ea-96df-8af76dde361a.jpg)
![Безымянный8](https://user-images.githubusercontent.com/55348946/73055731-1bc2f700-3e96-11ea-879d-9867f3c60aac.jpg)

**Comment by werfu** [comment]
@Branikolog I cannot reproduce it with the lastest master. Can you validate?

**Comment by Branikolog** [comment]
> @Branikolog I cannot reproduce it with the lastest master. Can you validate?

Both heroes must be on the same horizontal line (or close to it). One hero - stands close to the edge of the map, second one - on a distance a little more 1\2 of world window. When you switch between them - window's behavior is not correct.
The problem is still actual.

**Comment by ihhub** [comment]
Hi @Branikolog , could you please check the status of this bug? I think we fixed it by adding the edge of the map.

**Comment by Branikolog** [comment]
> Hi @Branikolog , could you please check the status of this bug? I think we fixed it by adding the edge of the map.

The problem merged into another one.
While switching between heroes, screen slips with its border to the edge of a world map, so, when you switch between heroes, hero appears not centered in the screen.
Also, I noticed problems with centering screen over a hero in #443.
