### ISSUE TITLE
Tavern, Falagar surrender previous turn but is not available in tavern

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3191]
In fheroes2, Falagar surrender previous turn but is not available in tavern.

In the original game, if one or more heroes surrender, they can all be recruited at the tavern, even if it's a new week that begins.

In fheroes2:

![Surrender but not in tavern fh2 01](https://user-images.githubusercontent.com/43583994/114786039-cbc39f00-9d7d-11eb-9da6-93c0f49ef48e.png)
![Surrender but not in tavern fh2 02](https://user-images.githubusercontent.com/43583994/114786055-d0885300-9d7d-11eb-9a7a-b57fc0fe6ed3.png)
![Surrender but not in tavern fh2 03](https://user-images.githubusercontent.com/43583994/114786069-d41bda00-9d7d-11eb-9a7b-9133fe284410.png)

End the turn.
Surrender with Falagar.
Gem cannot surrender, the button is grayed. (https://github.com/ihhub/fheroes2/issues/3190)
Gem flees.

The next turn a new week begins.
Gem can be recruited at the tavern.
In the original game this is possible, but the likelihood of it happening is quite low. (Not correct, it was a confusion with a defeated hero.)

Falagar surrenders the previous turn, but he cannot be recruited at the tavern.
In the original game, if a hero surrenders, he is always recruitable (at least for one full week, and this even if it is a new week that begins).

Here is the save file:
[No surrender with enough gold.zip](https://github.com/ihhub/fheroes2/files/6313940/No.surrender.with.enough.gold.zip)

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu

> Gem flees.
> Gem can be recruited at the tavern. In the original game this is possible, but the likelihood of it happening is quite low.

In H3 the fled hero will immediately reappear in Tavern ready for recruiting. The only difference with a surrender is the loss of an army. Isn't it the same in H2?

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu I made some tests using original H2 game, both fled and surrendered heroes become available in the tavern immediately. The sole difference between OG and fheroes is the number of "remembered" fled/surrendered heroes. OG "remembers" two heroes (fled or surrendered - doesn't matter), while fheroes "remembers" just one of them, the last one.

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> Hi @LeHerosInconnu
> 
> > Gem flees.
> > Gem can be recruited at the tavern. In the original game this is possible, but the likelihood of it happening is quite low.
> 
> In H3 the fled hero will immediately reappear in Tavern ready for recruiting. The only difference with a surrender is the loss of an army. Isn't it the same in H2?

You are right, my bad, I confused it with a defeated hero. :)

> Hi @LeHerosInconnu I made some tests using original H2 game, both fled and surrendered heroes become available in the tavern immediately. The sole difference between OG and fheroes is the number of "remembered" fled/surrendered heroes. OG "remembers" two heroes (fled or surrendered - doesn't matter), while fheroes "remembers" just one of them, the last one.

I think there should be "no limit" to the number of heroes that flee or surrender and that can be recruited.

Why limit the player with this action.
It can be frustrating, especially if the player pays a large amount of gold to get his heroes and armies back and he can't recruit them.

To the team, I have opened a discussion thread, if you think it is necessary to discuss this subject: https://github.com/ihhub/fheroes2/discussions/3199.
