### ISSUE TITLE
Good campaign: Dwarves not joining hero after completing optional scenario

### ISSUE THREAD

**Issue by aslak01** [ihhub/fheroes2#3192]
So I'm just playing through the campaign, and I've noticed that the Dwarves on the map seem to all want to fight, although I've completed the optional map between scenario 2 and 3, where you "save the dwarven villages". I'm pretty sure the dwarves on the map are supposed to join instead of fight you when that was the case.

**Comment by oleg-derevenetz** [comment]
It looks like it related to campaign awards (#2670). They are not yet implemented, WIP (#2926).

**Comment by aslak01** [comment]
Nice, I just wanted to point it out in case it wasn't on the radar.

**Comment by oleg-derevenetz** [comment]
@aslak01 That's fine, no problem :)
