### ISSUE TITLE
Adventure map, flotsam's shadow not removed

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3207]
In fheroes2, the flotsam's shadow is not removed.

In fheroes2:

![Flotsam shadow not removed 01](https://user-images.githubusercontent.com/43583994/115069825-71008380-9ef4-11eb-854e-d1d097d1ee87.png)

![Flotsam shadow not removed 02](https://user-images.githubusercontent.com/43583994/115069838-75c53780-9ef4-11eb-81ad-67f01fc0fbbc.png)

Take the flotsam with Zom.

Here is the save file:
[Flotsam shadow not removed.zip](https://github.com/ihhub/fheroes2/files/6327307/Flotsam.shadow.not.removed.zip)

**Comment by tau3** [comment]
probable cause: 
`void Maps::Tiles::Remove( u32 uniqID )` - looks like flotsam's shadow addon (the only item of `addons_level1`) has id that differs from flotsam's `uniqID`, and so it's not removed  from the list.

**Comment by ihhub** [comment]
We meed to investigate why it's hapenning. Is it because of incorrect map reading or incorrect object processing?

**Comment by oleg-derevenetz** [comment]
Interesting. In both cases (this one and #3620) shadow addon is removed immediately after starting a new map in `Maps::Tiles::AddonsSort()`, but in both save files shadow addons are somehow here again, but with zero `uniq` field. I was not able to reproduce this issue so far on a new map. The only possible explanation I have so far - it's an old games (not started from scratch after addon management-related changes in `Maps::Tiles::AddonsSort()` were introduced).

**Comment by oleg-derevenetz** [comment]
Ah, I was able to reproduce it. This "addon" arrives when I cast "Summon Boat" spell on this tile.
