### ISSUE TITLE
Cache PSV build steps

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#3214]
PSV build step on GitHub Actions takes a lot of time in comparison with other builds. The build contains 2 steps for SDK download and installation. We would like to cache if possible such steps to improve build times.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub Vita SDK download & installation takes just ~45s for psv-sdl2 job, while compilation step takes about 7-7:30 minutes (in comparison with ~2-2:30 min for any linux sdl2 job). It doesn't look like caching of SDK will help much here.

**Comment by ihhub** [comment]
At least we could fix failed builds with this approach.
