### ISSUE TITLE
Combat, sometimes the combat music is not played (fheroes2 0.9.2 3231)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3240]
In fheroes2, sometimes the combat music is not played.

In fheroes2:
Activate the sound of the video.

https://user-images.githubusercontent.com/43583994/115619742-91657f00-a2f4-11eb-8070-b816d642ce93.mp4

Wrathmont attacks Dragontooth.

Here is the save file:
[Before attack defense freeze.zip](https://github.com/ihhub/fheroes2/files/6353760/Before.attack.defense.freeze.zip)

**Edit.**

This issue may be related: https://github.com/ihhub/fheroes2/issues/3244.

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu Does this happen after you send the game to the background when battle begins?

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> Hi @LeHerosInconnu Does this happen after you send the game to the background when battle begins?

I sent the program to the background, then to the foreground before entering the combat.
I was able to do the same operation a second time with the same effect after launching OBS Studio to record the video.
But this is not always the case.
