### ISSUE TITLE
Adventure map, boat changes position when the hero embarks

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3243]
In fheroes2, the boat changes position when the hero embarks.

In fheroes2:

https://user-images.githubusercontent.com/43583994/115624005-46e70100-a2fa-11eb-8314-d75ce932a282.mp4

Here is the save file:
[Before boat direction 01.zip](https://github.com/ihhub/fheroes2/files/6354062/Before.boat.direction.01.zip)

**Comment by felix642** [comment]
I think this issues duplicates #2173
