### ISSUE TITLE
Adventure map, ambient sounds are not played when the game window returns to "foreground" after the window has been "in background" (sound and music cut off)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3244]
In fheroes2, ambient sounds are not played when the game window returns to "foreground" after the window has been "in background" (sound and music cut off).
It is necessary to select another hero (or perform another action) and reselect the hero for the ambient sounds to be played again.

In fheroes2:
Activate the sound of the video.

https://user-images.githubusercontent.com/43583994/115625825-ead1ac00-a2fc-11eb-9df6-95aa91d8de73.mp4

Here is the save file:
[Before Troll Bridge without troll.zip](https://github.com/ihhub/fheroes2/files/6354152/Before.Troll.Bridge.without.troll.zip)

**Comment by LeHerosInconnu** [comment]
Something is definitely wrong with the sound management.

Here, the hero Ranloo was located next to the easternmost Stone Lith on the small island west of Ranloo's current position.
He then boarded a boat and sailed away from the island.
The sound of the Stone Lith can be heard at all times, even when changing heroes or selecting a castle.
The sound of the Stone Lith is no longer played as soon as Ranloo moves on the ocean after selecting another hero or a castle.

I did not find the exact procedure to reproduce the bug.
Try to put the program in the background and then in the foreground.
And at the same time change the sound level of "Effects" in the "System Options" window.

In fheroes2:
Activate the sound of the video.

https://user-images.githubusercontent.com/43583994/115969397-ff9c8280-a53c-11eb-8445-d96e718c9322.mp4

**Comment by LeHerosInconnu** [comment]
Another example of a problem with sound management.
Sometimes, on the adventure map, unrelated music is played.
I did not find the exact procedure to reproduce the bug.

In fheroes2:
Activate the sound of the video.

https://user-images.githubusercontent.com/43583994/116486595-4f0ce680-a88e-11eb-80c2-c8855aca4de3.mp4

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu

> Incorrect remark. It happens in other cases too.
> End the turn.
> Flee with Vatawna.

This particular case should be fixed by #3362. This may happen in certain cases in the beginning of a new turn when hero or castle is on a tile for which no music track is found. In this case, the unrelated track from the previous turn (or even from the battle) could be used.
