### ISSUE TITLE
Adventure map, after defeating the Trolls guarding the Troll Bridge, the hero is not offered to recruit Trolls

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3245]
In fheroes2, after defeating the Trolls guarding the Troll Bridge, the hero is not offered to recruit Trolls.

In original game:

https://user-images.githubusercontent.com/43583994/115627585-9419a180-a2ff-11eb-9623-d566fb0b21d5.mp4

In fheroes2:

https://user-images.githubusercontent.com/43583994/115627802-e955b300-a2ff-11eb-956f-7dd93014294d.mp4

Here is the save file:
[Before Troll Bridge without troll.zip](https://github.com/ihhub/fheroes2/files/6354152/Before.Troll.Bridge.without.troll.zip)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , I tested on latest version of the application with a new game created and it works.

I debugged the save and there were no Trolls in the bridge. Did you defeat AI just a day before? Or maybe the bridge don't renew Troll each week after all?

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , I tested on latest version of the application with a new game created and it works.
> 
> I debugged the save and there were no Trolls in the bridge. Did you defeat AI just a day before? Or maybe the bridge don't renew Troll each week after all?

No, I didn't defeat an AI player just a day before.

In the original game, there are always Trolls to be recruited when the guardians have been defeated.
Then there are new Trolls to recruit every week and they accumulate over the weeks once the guardians have been defeated.

Here is the save file at start of the game:
[Broken_Alliance_0001.zip](https://github.com/ihhub/fheroes2/files/6360024/Broken_Alliance_0001.zip)

**Comment by oleg-derevenetz** [comment]
Hi @ihhub @LeHerosInconnu It seems that AI is a cheater - it could hire units from guarded objects (like troll bridge) without the need to fight the guards. It [calls](https://github.com/ihhub/fheroes2/blob/a41fae15113e3e02eeb836449992fc488c3812d8/src/fheroes2/ai/ai_hero_action.cpp#L408) `AIToDwellingRecruitMonster()` from `HeroesAction()` during the visit of such objects:

```
        // recruit army (battle)
        case MP2::OBJ_DRAGONCITY:
        case MP2::OBJ_CITYDEAD:
        case MP2::OBJ_TROLLBRIDGE:
            AIToDwellingRecruitMonster( hero, object, dst_index );
            break;
```

and `AIToDwellingRecruitMonster()` just [pays](https://github.com/ihhub/fheroes2/blob/a41fae15113e3e02eeb836449992fc488c3812d8/src/fheroes2/ai/ai_hero_action.cpp#L1297) them without fighting the guards :) It would be nice if @idshibanov took a look at it.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz, @ihhub and @idshibanov.

I saw an AI hero moving on the Troll Bridge a few turns earlier, but his army was full and he had no Trolls in his army after the visit.

In fheroes2:

![AI hero visits Troll Bridge fh2 01](https://user-images.githubusercontent.com/43583994/115791792-5bde9580-a3c9-11eb-814d-06423668ceec.png)

![AI hero visits Troll Bridge fh2 02](https://user-images.githubusercontent.com/43583994/115791800-5f721c80-a3c9-11eb-8a18-a983f76c8360.png)

Here is the save file:
[AI hero visits Troll Bridge.zip](https://github.com/ihhub/fheroes2/files/6361553/AI.hero.visits.Troll.Bridge.zip)

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu AI didn't hire trolls on that turn, there were 5 trolls on that tile before the visit and there 5 trolls left after the visit. Apparently this happened later.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz, @ihhub and @idshibanov.

> @LeHerosInconnu AI didn't hire trolls on that turn, there were 5 trolls on that tile before the visit and there 5 trolls left after the visit. Apparently this happened later.

Here are the save files before the AI hero visits the Troll Bridge (several times in several turns):
The hero has the Trolls in his army with the file Broken_Alliance_0060 c.sav (after ending the turn).
[AI hero visits Troll Bridge 02.zip](https://github.com/ihhub/fheroes2/files/6365617/AI.hero.visits.Troll.Bridge.02.zip)

In fheroes2:

![AI recruit Trolls fh2 002](https://user-images.githubusercontent.com/43583994/115878265-a4896380-a448-11eb-82e7-33fef48dba88.png)

![AI recruit Trolls fh2 001](https://user-images.githubusercontent.com/43583994/115878250-a0f5dc80-a448-11eb-849e-2d25ee34afda.png)
