### ISSUE TITLE
Adventure map, heroes' path in relation to the objects

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3246]
In fheroes2, the heroes take paths that give the impression that they are "penetrating" the objects.
This should be avoided.

In original game:

https://user-images.githubusercontent.com/43583994/115630134-c9c08980-a303-11eb-8b27-228ffc23c9bc.mp4

In fheroes2:

https://user-images.githubusercontent.com/43583994/115630240-f7a5ce00-a303-11eb-909b-b985eca6e0a4.mp4

Here is the save file:
[Hero path and castle.zip](https://github.com/ihhub/fheroes2/files/6354317/Hero.path.and.castle.zip)

**Comment by undef21** [comment]
Same issue #3094
