### ISSUE TITLE
Adventure map, hero info window shadow over wasteland mountains

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3257]
The shadow of the hero information window is not very dark at the area of the wasteland mountains.
Is this normal?

In fheroes2:

![AI hero visits Troll Bridge fh2 01](https://user-images.githubusercontent.com/43583994/115791792-5bde9580-a3c9-11eb-814d-06423668ceec.png)

![AI hero visits Troll Bridge fh2 02](https://user-images.githubusercontent.com/43583994/115791800-5f721c80-a3c9-11eb-8a18-a983f76c8360.png)

**Comment by Branikolog** [comment]
Hello, @LeHerosInconnu 
I think it's the same to OG:
![image](https://user-images.githubusercontent.com/55348946/115840245-231fda00-a424-11eb-829c-3252aff97c95.png)

**Comment by LeHerosInconnu** [comment]
Hi @Branikolog,

> Hello, @LeHerosInconnu
> I think it's the same to OG:

Yes, but should it be improved or left as is?

**Comment by ihhub** [comment]
We aren't going to change the shadow of the window based on the complexity of the task. The same shadow present in many other windows as well. I'm closing this issue.

However, what we could do with shadows is to add one to Magic Book. Our algorithms can add left-bottom shadows to any images. Feel free to create a new issue just for this if you feel that it's worth to be done.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> We aren't going to change the shadow of the window based on the complexity of the task. The same shadow present in many other windows as well. I'm closing this issue.

It's okay, thanks.

> However, what we could do with shadows is to add one to Magic Book. Our algorithms can add left-bottom shadows to any images. Feel free to create a new issue just for this if you feel that it's worth to be done.

Adding a shadow to the Magic Book is on my wish list, but I wonder how the shadow should be handled for bookmarks.
Not sure if it can be rendered in a good way.
What do you think about it?
