### ISSUE TITLE
Adventure map, AI hero visits the Troll Bridge several times in several turns before recruiting Trolls (fheroes2 0.9.2 3254)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3261]
In fheroes2, the AI hero visits the Troll Bridge several times in several turns before recruiting Trolls.
The hero loses a lot of movement points by making these successive moves.

Here are the save files:
End the turn.
[AI hero visits Troll Bridge 02.zip](https://github.com/ihhub/fheroes2/files/6365617/AI.hero.visits.Troll.Bridge.02.zip)

**Comment by ihhub** [comment]
Closing this issue as it's no longer reproducible.
