### ISSUE TITLE
No support of diagonal scrolling on world map

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#327]
Original game supports diagonal scrolling while our implementation doesn't. We would like to add such ability.

Base point to check the code is `int Interface::Basic::HumanTurn( bool isload )` function.

**Comment by werfu** [comment]
Did you add the support for it? It seems to be working with an SDL2 build.

**Comment by ihhub** [comment]
Yes, I added in [this](https://github.com/ihhub/fheroes2/commit/3fa2291a6e9457316474f16e8b0232c4afcf0e22) commit. Thanks for pointing!
