### ISSUE TITLE
Hero screen, Leadership description has not optimized layout

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#3273]
![image](https://user-images.githubusercontent.com/55348946/115993327-f3670280-a5da-11eb-85f0-714d2d576708.png)
For each level we have "1", "2" and "3" morale indicator on a separate line, which looks bad.
While in original game all text is placed evenly in three lines.
![image](https://user-images.githubusercontent.com/55348946/115993662-73419c80-a5dc-11eb-897e-ed9c976e6c9e.png)

**Comment by ihhub** [comment]
This is a common issue with text layout in all windows. I'm putting this issue to 1.0 milestone.
