### ISSUE TITLE
Combat, hero in visit in a castle cannot retreat when he attacks an opposite hero

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3276]
In fheroes2, the hero in visit in a castle cannot retreat when he attacks an opposite hero.

In fheroes2:

![No retreat fh2 10](https://user-images.githubusercontent.com/43583994/116006782-0e526a80-a60d-11eb-8ad7-44e5969a77d4.png)

Gem attacks Ergon.

Here is the save file:
[No retreat fh2 10.zip](https://github.com/ihhub/fheroes2/files/6372799/No.retreat.fh2.10.zip)

**Comment by Branikolog** [comment]
Good catch, @LeHerosInconnu ! :)
