### ISSUE TITLE
Adventure map, moving boat is displayed under another boat

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3277]
In fheroes2, the moving boat is displayed under another boat.

In fheroes2:

![vlcsnap-2021-04-26-00h23m18s045](https://user-images.githubusercontent.com/43583994/116011520-becc6880-a625-11eb-90de-ded165b8a65a.png)

https://user-images.githubusercontent.com/43583994/116011528-ca1f9400-a625-11eb-94f7-89c4bcf81897.mp4

Here is the save file:
[Boat under boat fh2 01.zip](https://github.com/ihhub/fheroes2/files/6373308/Boat.under.boat.fh2.01.zip)

**Comment by vasilenkoalexey** [comment]
Duplicate #1293
