### ISSUE TITLE
Castle, the Castle Archer is added only when the Mage Guild is built

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3294]
In fheroes2, when it is a scenario with the buildings in "Standard" mode (the creator of the scenario did not put the buildings in "Custom" mode), the Archer who defends the castle (1 Archer per building built, including the Castle (Town upgrade)) is added only when the Mage Guild is built.

In fheroes2:

The Castle information window indicates 16 Archers.
![Number Archers fh2 01](https://user-images.githubusercontent.com/43583994/116292857-7bddd280-a796-11eb-9f85-f73814fb5adf.png)

There are 17 buildings built (including the Castle upgrade from the Town).
So the Ballista should fire with the strength of 17 Archers.
![Number Archers fh2 02](https://user-images.githubusercontent.com/43583994/116292896-8bf5b200-a796-11eb-81f4-85aa432af97a.png)

After the construction of the Mage Guild, it is indicated that the Ballista fires with the strength of 18 Archers.
![Number Archers fh2 03](https://user-images.githubusercontent.com/43583994/116292942-957f1a00-a796-11eb-9818-237db5b34f4f.png)
![Number Archers fh2 04](https://user-images.githubusercontent.com/43583994/116292950-9912a100-a796-11eb-8647-946a9e09dbf9.png)

This applies to all castles.
Here the Treehouse is built in the castle.
So the Ballista should fire with the strength of 2 Archers.
![Number Archers fh2 05](https://user-images.githubusercontent.com/43583994/116293002-a760bd00-a796-11eb-800f-26e4e1ac04db.png)

The Castle information window indicates only 1 Archer.
![Number Archers fh2 06](https://user-images.githubusercontent.com/43583994/116293050-b5164280-a796-11eb-8571-5571eccef2e7.png)
![Number Archers fh2 07](https://user-images.githubusercontent.com/43583994/116293031-b0518e80-a796-11eb-89c7-ba726d053205.png)

Here is the save file (before the Mage Guild is built):
[Before Mage Guild 01.zip](https://github.com/ihhub/fheroes2/files/6386747/Before.Mage.Guild.01.zip)

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu How does the level of mage guild affect the number of archers in OG? Will mage guild level 2 add one more archer, mage guild level 3 add two more archers, etc, etc?

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> Hi @LeHerosInconnu How does the level of mage guild affect the number of archers in OG? Will mage guild level 2 add one more archer, mage guild level 3 add two more archers, etc, etc?

In the original game, only the "base" building adds 1 Archer for the defense of the Castle.

The Town adds 1 Archer (the Castle, as an upgrade to the Town, only adds the Town Archer).
So Town or Castle adds only 1 Archer.

A base creature building adds 1 Archer.
An upgraded creature building does not add an additional Archer.
Same for Mage Guild Mage, only 1 Archer for level 1.
In addition, each level of the Mage Guild gives +1 Attack for the Ballista and each of the Turrets.

In my mod, there will be an option to add 1 Archer for each upgrade of the base buildings: https://github.com/ihhub/fheroes2/discussions/2981.

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu Thank you!
