### ISSUE TITLE
Hero screen, do not display the artifact exchange message in the info bar at the bottom of the screen when an artifact is selected and the mouse cursor is positioned over the Magic Book

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3351]
In fheroes2, do not display the artifact exchange message in the info bar at the bottom of the screen when an artifact is selected and the mouse cursor is positioned over the Magic Book, it should be indicated "View Spells".

**Edit 2021/05/06.**

The displayed sentence should be:

"Magic Book cannot be moved"

In fheroes2:

![Do not display exchange message fh2 01](https://user-images.githubusercontent.com/43583994/117185723-6db53500-adda-11eb-972e-a3f3961b7758.png)

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu In a similar case, the neighboring function has the wording "Cannot move artifact", so I'm using it for now.
