### ISSUE TITLE
Hero screen, when an artifact is selected and the user left-clicks on the Magic Book, the artifact should be deselected and the Magic Book should be opened directly

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3352]
In fheroes2, when an artifact is selected and the user left-clicks on the Magic Book, the artifact should be deselected and the Magic Book should be opened directly.

In fheroes2:

![Do not display exchange message fh2 01](https://user-images.githubusercontent.com/43583994/117185723-6db53500-adda-11eb-972e-a3f3961b7758.png)

Related issue: https://github.com/ihhub/fheroes2/issues/3351.

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu !
This was intended to happen here:
When a player selects an artifact and tries to exchange it with book - the selection cancels. (As the book shouldn't be selected and moved or exchanged everywhere in the game). So this just supports overall game style.
If a player accidentally pressed the book (while exchanging artifacts in his inventory)- single deselection (without opening of the book) is more more predictable. Player shouldn't close unexpected book then and simply select previous artifact for exchanging it again.
In a case he selected an artifact, while he was trying to open the book - making one more mouse click to open the book is much faster, than closing book in my previous example.

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

> Hi, @LeHerosInconnu !
> This was intended to happen here:
> When a player selects an artifact and tries to exchange it with book - the selection cancels. (As the book shouldn't be selected and moved or exchanged everywhere in the game). So this just supports overall game style.
> If a player accidentally pressed the book (while exchanging artifacts in his inventory)- single deselection (without opening of the book) is more more predictable. Player shouldn't close unexpected book then and simply select previous artifact for exchanging it again.
> In a case he selected an artifact, while he was trying to open the book - making one more mouse click to open the book is much faster, than closing book in my previous example.

I don't know.
I'm so used to the way the original game works with a simple left click on the Magic Book to open it, that it seems strange to have to click a second time when an artifact is selected, I always feel that something is wrong. :)
We can leave it this way for now and see how it goes, but in this case the sentence in the info bar at the bottom of the screen should be changed to something like:

"Magic Book cannot be moved"

**Comment by Branikolog** [comment]
> We can leave it this way for now and see how it goes, but in this case the sentence in the info bar at the bottom of the screen should be changed to something like:
> 
> "Magic Book cannot be moved"

I'm pretty sure we should add it in your #3351 issue.

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

> > We can leave it this way for now and see how it goes, but in this case the sentence in the info bar at the bottom of the screen should be changed to something like:
> > "Magic Book cannot be moved"
> 
> I'm pretty sure we should add it in your #3351 issue.

Yes, it's done.
