### ISSUE TITLE
Adventure map, part of the bottom of the Hero sprite is visible through the mountain

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3363]
In fheroes2, part of the bottom of the Hero sprite is visible through the mountain.

In fheroes2:

![Hero mountain 01](https://user-images.githubusercontent.com/43583994/117498887-b1df3b80-af7a-11eb-9332-3ce29c24b224.png)

![Hero dimension door mountain 01](https://user-images.githubusercontent.com/43583994/117498877-adb31e00-af7a-11eb-91e5-e2f1704013e8.png)

Move Zam near the boat to the west (movement on horseback or with the Dimension Door spell).

Here is the save file:
[Hero before dimension door 0.zip](https://github.com/ihhub/fheroes2/files/6443880/Hero.before.dimension.door.0.zip)

Similar issue: https://github.com/ihhub/fheroes2/issues/3344.

**Comment by Branikolog** [comment]
Similar issue #3210.

**Comment by LeHerosInconnu** [comment]
In fheroes2, part of the right part of the Hero sprite is visible through the mountain.

In fheroes2:
![Hero sprite mountain 02](https://user-images.githubusercontent.com/43583994/132980114-d4ff0814-786c-4892-a19f-fe9d6bab8d04.png)

Here is the save file (0.9.7 4180):
[Hero sprite mountain 02.zip](https://github.com/ihhub/fheroes2/files/7149274/Hero.sprite.mountain.02.zip)
