### ISSUE TITLE
Adventure map, AI behavior, yellow player's hero Ruby embarks without recruiting the Genies even though she just landed the previous turn

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3365]
In fheroes2, the yellow player's hero Ruby embarks without recruiting the Genies even though she just landed the previous turn.

In fheroes2:

![Hero yellow not recruit genies 01](https://user-images.githubusercontent.com/43583994/117502020-35029080-af7f-11eb-91f1-f55de7d54b6c.png)

Here are the save files (before disembarking and after boarding):
[AI not recruit genies 01.zip](https://github.com/ihhub/fheroes2/files/6444018/AI.not.recruit.genies.01.zip)

**Comment by ihhub** [comment]
Closing this issue as it must be fixed by recent changes in AI pathfinding algorithm. Please feel free to reopen it if it's not the case.
