### ISSUE TITLE
Adventure map, all neutral monsters are shown in plural form while using crystal ball

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#3366]
If there's only 1 peasant on a world map we should type "1 peasant", not "peasants'.
![image](https://user-images.githubusercontent.com/55348946/117531205-18e80900-afea-11eb-8693-b0d7af7f98cc.png)

**Comment by ihhub** [comment]
The problem lies in `ShowGuardiansInfo` and `ShowMonsterInfo` functions.

**Comment by ihhub** [comment]
Hi @gentooza , Scouting works only as Crystal Ball does when extended option is enabled in Experimental settings. Please try this.
