### ISSUE TITLE
Program screen goes completely black after the program switches from background to foreground (0.9.3 3373)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3392]
Sometimes it happens that the program screen goes completely black after the program switches from background to foreground.
In this case there is no other possibility than to terminate the program and restart it.

I haven't found the procedure to reproduce this bug.

In fheroes2:

![Black screen after backgroung foreground 01](https://user-images.githubusercontent.com/43583994/117693851-b8f68b80-b1be-11eb-9ae1-054c2880eb62.png)

**Comment by oleg-derevenetz** [comment]
This may be fixed by #3428 as well. Hi @LeHerosInconnu is this issue still observed in recent times?

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> This may be fixed by #3428 as well. Hi @LeHerosInconnu is this issue still observed in recent times?

I have not observed this problem recently.
I will close the issue after a few quick tests if it doesn't happen any more.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> I will close the issue after a few quick tests if it doesn't happen any more.

This problem is still present (test with 0.9.3 3442).

Here is how to reproduce it:
- Open the View World screen.
- Minimize the window.
- Bring the window to the foreground (the screen is now black).
- Left click and hold, and move the mouse to make the window refresh.

In fheroes2:

![Black screen 001](https://user-images.githubusercontent.com/43583994/119364021-c3c91a00-bcae-11eb-99c6-ef816a20e881.png)

![Black screen 002](https://user-images.githubusercontent.com/43583994/119364038-c7f53780-bcae-11eb-9dff-d83e34deafdd.png)

![Black screen 003](https://user-images.githubusercontent.com/43583994/119364051-cc215500-bcae-11eb-95b4-12233ba2f534.png)

![Black screen 004](https://user-images.githubusercontent.com/43583994/119364058-cdeb1880-bcae-11eb-8853-04f127f38826.png)
