### ISSUE TITLE
XML status?

### ISSUE THREAD

**Issue by lyssdod** [ihhub/fheroes2#3396]
Hello,

Thanks for this awesome project! Question... there is a bunch of XML files from previous development, but they're not used currently? From the code view it seems that all information is hardcoded in `cpp` files. Is this final or are there any plans to migrate "back" to XML for data storage?

**Comment by ihhub** [comment]
Hi @lyssdod , we dropped all XML support support in favor to focus on the main game development rather than addressing modding issues.
Most likely XML related code will be removed and JSON based future mod support will be added.

**Comment by lyssdod** [comment]
got it, thanks!
