### ISSUE TITLE
Hero screen, long artifact names overlap GUI while exchanging

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#3407]
The text is too long while exchanging.
![image](https://user-images.githubusercontent.com/55348946/118140949-88f2f680-b411-11eb-9e03-861882215591.png)
We either should cut it or hide under the buttons.

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog.

I think there are still too many issues currently: https://github.com/ihhub/fheroes2/issues/1689. :D

**Comment by Branikolog** [comment]
> Hello @Branikolog.
> 
> I think there are still too many issues currently: #1689. :D

Huh-uh. )
Hi, @LeHerosInconnu !
From now I won't create any new issue at all until I look through all current opened issues! :D 
P.S. At least I've found a longer combination of artifacts here. :P
