### ISSUE TITLE
View World screen, the map is not centered in the frame (0.9.3 3373)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3410]
In fheroes2, the map is not centered in the frame.

In original game:

![H2 centered map 01](https://user-images.githubusercontent.com/43583994/118303402-b1e4bb80-b4e5-11eb-808f-d905d5b3b5ca.png)

![H2 centered map 02](https://user-images.githubusercontent.com/43583994/118303418-b7da9c80-b4e5-11eb-8874-4757af51823a.png)

![H2 centered map 03](https://user-images.githubusercontent.com/43583994/118303428-bd37e700-b4e5-11eb-9293-552deab2a8fe.png)

In fheroes2:

![Not centered 03](https://user-images.githubusercontent.com/43583994/118303502-d0e34d80-b4e5-11eb-8221-bffae4a3d28e.png)

![Not centered 01](https://user-images.githubusercontent.com/43583994/118303468-c628b880-b4e5-11eb-80e3-685b5fd0a303.png)

![Not centered 02](https://user-images.githubusercontent.com/43583994/118303488-ccb73000-b4e5-11eb-9b57-af33337fe0fa.png)

https://user-images.githubusercontent.com/43583994/118303539-db9de280-b4e5-11eb-9c67-239cf1c7696b.mp4

Here is the save file:
[Broken_Alliance_0058 k.zip](https://github.com/ihhub/fheroes2/files/6480137/Broken_Alliance_0058.k.zip)

**Comment by a1exsh** [comment]
Potentially fixed by #4156

**Comment by ihhub** [comment]
It's fixed by #4156.
