### ISSUE TITLE
Program freezes after switching from background to foreground after a combat is initiated (0.9.3 3370)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3415]
Sometimes it happens that the program freezes after switching from background to foreground after a combat is initiated.
In this case there is no other possibility than to terminate the program and restart it.

I haven't found the procedure to reproduce this bug.

In fheroes2:

![Program freeze 01](https://user-images.githubusercontent.com/43583994/118377930-9d312200-b5d0-11eb-972c-61327a58b9f5.png)

**Comment by oleg-derevenetz** [comment]
Related bug: #3113. I've tried to catch it too, but I haven't been able to do it yet.

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu Do you use version built with SDL2 or SDL1?

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> Hi @LeHerosInconnu Do you use version built with SDL2 or SDL1?

I use Windows x64 build with SDL2 support.

**Comment by oleg-derevenetz** [comment]
I have an impression that waiting cycles like this:

```
while ( LocalEvent::Get().HandleEvents() && Mixer::isPlaying( -1 ) )
     ;
```

may not work as expected if app is in background and block app indefinitely. But I'm not sure why yet. These cycles are used both at the beginning of the battle and when playing sound effects like the "luck" sound effect mentioned [here](https://github.com/ihhub/fheroes2/issues/3113#issuecomment-832092513).

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , I'm able to reproduce the problem by switching to another app at the start of the battle (somethimes it works). The problem is that in LocalEvent to mute sounds and music while switching off the game. The fast solution would be to remove/comment this code for a while until we find a proper solution.
The best approach would be to check the type of sound playing. For example, `Mixer::isPlaying( -1. MIDI::SOMETHING )`. In this case we are checking if the certain audio is playing.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub I still don't understand why exactly it doesn't work. Mixer::isPlaying() checks the output volume of all channels first and, if zero, it should return zero as well. Doesn't this work in case of muted sound?

**Comment by ihhub** [comment]
Honestly, SDL works terribly with sounds so I might not be surprised if it doesn't work with muted sound. A small note: all this behavior usually happens on Windows.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub I was able to reproduce this on my MacOS by calling `LocalEvent::StopSounds()` within a loop by hand and yes, it looks like it causes immediate freeze, because `Mix_Volume()` and `Mix_Playing()` both returns that everything is going on with paused sound. However it's still not clear for me why `ResumeSounds()` isn't called when game window is activated back, because it should be called inside `HandleEvents()` loop...

**Comment by oleg-derevenetz** [comment]
Hi @ihhub Unfortunately I don't have a Windows machine, but that's what makes me suspicious:

```
void LocalEvent::OnSdl2WindowEvent( const SDL_Event & event )
{
    if ( !Mixer::isValid() ) {
        return;
    }
    if ( event.window.event == SDL_WINDOWEVENT_FOCUS_LOST ) {
        StopSounds();
    }
    else if ( event.window.event == SDL_WINDOWEVENT_FOCUS_GAINED ) {
        ResumeSounds();
    }
}

```

`SDL_WINDOWEVENT_FOCUS_GAINED` will work only when window gets a KEYBOARD focus, and this may not always be the case, and therefore `ResumeSounds()` is never called. And it's interesting that [here](https://github.com/ihhub/fheroes2/blob/94ceef01ddb7cace7e11873e412e9ad9990ccf7b/src/engine/localevent.cpp#L1151) (with SDL1) `StopSounds()` appears to never been called if app is iconified. Unfortunately, I have no Windows machine here :( Would you be so kind to make tests regarding those event types? Will game always get keyboard focus when its window is activated?

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , this method is being called multiple times on SDL 2 when I switch between applications on Windows and the events are `SDL_WINDOWEVENT_FOCUS_GAINED` and `SDL_WINDOWEVENT_EXPOSED` or `SDL_WINDOWEVENT_RESTORED`, `SDL_WINDOWEVENT_FOCUS_GAINED` and `SDL_WINDOWEVENT_EXPOSED` for restoring from an icon application.

SDL1 version enters`if ( event.active.state & SDL_APPACTIVE ) {` code for me.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub I have a theory that sometimes, when app is in waiting cycle, `SDL_WINDOWEVENT_FOCUS_GAINED` doesn't arrive and therefore `ResumeSounds()` is not called. I tried to call `StopSounds()` in a waiting cycle by hand and then, after a few thousands cycles, call `ResumeSounds()`, and everything works fine in this case - music effect continues, wait cycle exits when sound effect ends, and everything is going like it should. So it looks like `ResumeSounds()` just not called sometimes.

**Comment by oleg-derevenetz** [comment]
I think that #3240 is also related.
