### ISSUE TITLE
Adventure map, AI behavior, red AI player's Vatawna hero does not move while a hero is a threat (0.9.3 3370)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3417]
In fheroes2, the red AI player's Vatawna hero does not move while a hero is a threat.
Vatawna could have moved away, even just by using the Stone Liths without leaving the Stones Lith location.

In fheroes2:

![AI Vatawna no move 001](https://user-images.githubusercontent.com/43583994/118378127-ca320480-b5d1-11eb-9dbc-e4f2f160bfd7.png)

![AI Vatawna no move 002](https://user-images.githubusercontent.com/43583994/118378130-d027e580-b5d1-11eb-862a-b26b0e432dcb.png)

End the turn.

Here are the save files (before and after):
[Vatawna no move 01.zip](https://github.com/ihhub/fheroes2/files/6488209/Vatawna.no.move.01.zip)

**Comment by ihhub** [comment]
The problem here Vatawna has no espace route. Each portal leads to strong monsters.

**Comment by LeHerosInconnu** [comment]
Some possibilities in this case:
- Vatawna can protect herself simply by using the Stones Lith and without moving from it (like a space bar press for the human player).
- Vatawna can try to lure the human player's hero so that he wastes his time in pursuit by using the Stones Lith and moving as far away from the Stones Lith as possible, favoring terrain that has a large movement penalty or conversely a terrain where she could keep him as far away as possible for as long as possible.
- Vatawna can also separate her troops (in five troops in this case) so that even if the human hero attacks her, she will have  (maybe) the option to flee.
- If Vatawna is an important hero and/or has valuable artifacts, she can also escape by attacking the nearby village and running away during the combat.
- Vatawna can also move as far away from the hero as possible so that he wastes his time in pursuit, and escape the next turn by attacking a strong wandering troop and running away during the combat.
