### ISSUE TITLE
Combat, AI behavior, defending Goblin leaves the castle grounds resulting in the loss of the combat (0.9.3 3370)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3418]
In fheroes2, the defending Goblin leaves the castle grounds, while the combat would have been won by the shots of the Ballista and the Turrets if the Goblin had stayed inside.

In fheroes2:

![Dumb Goblin 01](https://user-images.githubusercontent.com/43583994/118378197-4f1d1e00-b5d2-11eb-95ee-e326b31d8a27.png)

https://user-images.githubusercontent.com/43583994/118378203-593f1c80-b5d2-11eb-8cb8-c0f2504f180e.mp4

Kastore attacks Whiteshield.

Here is the save file:
[Dumb goblin 01.zip](https://github.com/ihhub/fheroes2/files/6488221/Dumb.goblin.01.zip)

**Comment by ihhub** [comment]
The problem lies in this particular code:
```
        // TODO: replace this hacky code for archers
        // Calculate each hero spell strength and add it to shooter values after castle modifiers were applied
        if ( _commander && _myShooterStr > 1 ) {
            _myShooterStr += _commander->GetSpellcastStrength();
        }
        const HeroBase * enemyCommander = arena.GetCommander( _myColor, true );
        if ( enemyCommander ) {
            _enemySpellStrength = enemyCommander->GetSpellcastStrength();
            _enemyShooterStr += _enemySpellStrength;
        }
```

**Comment by ihhub** [comment]
This issue is fixed recently.
