### ISSUE TITLE
Adventure map, Fog of War is not removed when a hero uses a Stones Lith (0.9.3 3446)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3448]
In fheroes2, the Fog of War is not removed when a hero uses a Stones Lith.
And it is not possible to move the hero located under the Fog of War even if the destinaton is visible.

In fheroes2:

![Fog of war not removed 01](https://user-images.githubusercontent.com/43583994/118706686-f50e9980-b819-11eb-993c-10fba67dc3a4.png)

![Fog of war not removed 02](https://user-images.githubusercontent.com/43583994/118706707-fb047a80-b819-11eb-8f01-ab1fad591e9f.png)

Here is the save file:
[Fog of war stones lith 01.zip](https://github.com/ihhub/fheroes2/files/6503566/Fog.of.war.stones.lith.01.zip)

**Comment by oleg-derevenetz** [comment]
Looks like a regression after #3445.
