### ISSUE TITLE
Adventure map, defect with the shadow of the pile of gems (0.9.3 3446)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3450]
In fheroes2, there is a defect with the shadow of the pile of gems near the Water Wheel.

In fheroes2:

![Gems shadow 10](https://user-images.githubusercontent.com/43583994/118718918-1b3b3600-b828-11eb-9ab5-6e2486f66fca.png)

Here is the save file:
[Gems shadow 01.zip](https://github.com/ihhub/fheroes2/files/6504260/Gems.shadow.01.zip)

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu 
Isn't it the same issue to #2152?

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

> Hi, @LeHerosInconnu
> Isn't it the same issue to #2152?

Oh yes, I knew I had something close but I couldn't find it when I was searching for it. :D
We make a good complementary team to find the bugs already mentioned. :)

So it seems that the problem is more related to the proximity of the Water Wheel than the resource itself.

**Comment by Branikolog** [comment]
@LeHerosInconnu 
:)
Just curious... How does look the OG in this place?

**Comment by ihhub** [comment]
Fixed recently.
