### ISSUE TITLE
Game, all heroes who are in the "hero pool" (heroes available at the tavern and all heroes who are not recruited) should recover spell points at the beginning of each turn

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3464]
All heroes who are in the "hero pool" (heroes available at the tavern and all heroes who are not recruited) should recover spell points at the beginning of each turn, at least one point per turn and more if they have the Mysticism skill and/or artifact(s) that act on the spell points recovered each turn (Power Ring).
It works this way in the original game.

In the example, Arie still has 7 out of 40 spell points at the beginning of the next turn.

In fheroes2:

![Hero spell points 004](https://user-images.githubusercontent.com/43583994/118857973-eb983680-b8d8-11eb-8225-7c33715ebc33.png)

![Hero spell points 005](https://user-images.githubusercontent.com/43583994/118858002-f226ae00-b8d8-11eb-810e-f6a17e0f55d6.png)

![Hero spell points 006](https://user-images.githubusercontent.com/43583994/118858008-f5219e80-b8d8-11eb-937a-a0f5b1fb2f66.png)

![Hero spell points 007](https://user-images.githubusercontent.com/43583994/118858031-fbb01600-b8d8-11eb-876e-734448395351.png)

Here is the save file:
[Broken_Alliance_0043 m.zip](https://github.com/ihhub/fheroes2/files/6510682/Broken_Alliance_0043.m.zip)

Related issue: https://github.com/ihhub/fheroes2/issues/3463.

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu 
What if new week has started? Should heroes appeared in tavern have 100% mana or continue recovering it till full each turn?

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

> Hi, @LeHerosInconnu
> What if new week has started? Should heroes appeared in tavern have 100% mana or continue recovering it till full each turn?

In the original game, all heroes follow the same rule regarding the recovery of spell points, heroes in the ranks of a human or AI player, heroes available for recruitment in the tavern of a human or AI player, and all other heroes that are not recruited.

By default, each hero gets one spell point back per day wherever he is located.
If the hero has the Mysticism skill and/or artifact(s) that act on the spell points recovered each turn (Power Ring), he gets additional spell points.
If a new week starts, this rule continues to be applied until the hero has recovered his maximum spell points; the hero does not recover all his spell points at the beginning of a new week.
The only rule that takes precedence over this one is the one that when a hero is visiting a castle and ends the turn in a castle with a built Mage Guild the hero gets all his spell points back.

**Comment by Branikolog** [comment]
@LeHerosInconnu 
So, if a hero has 5/10 of mana points in the end of the week, and it happens, that the next week the same hero appears in tavern, he'd have 6/10 (with the default recovery), right? So any hero, that had 0/300 mana points he will still have not full mana, if he appears in tavern within a few months, right?

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> @LeHerosInconnu
> So, if a hero has 5/10 of mana points in the end of the week, and it happens, that the next week the same hero appears in tavern, he'd have 6/10 (with the default recovery), right?

Yes.

> So any hero, that had 0/300 mana points he will still have not full mana, if he appears in tavern within a few months, right?

Yes, he will only get one spell point back per day.

**Comment by Branikolog** [comment]
Thanks for clarification, @LeHerosInconnu!
In later series heroes recover their points in a bit other manner.
