### ISSUE TITLE
Adventure map, animation of the AI hero boarding during the AI turn is too fast

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3474]
In fheroes2, the animation of the AI hero boarding during the AI turn is too fast.
Also, I think the boarding sound should also be played when an AI hero boards during the AI turn.

In fheroes2:
Activate the sound of the video.

https://user-images.githubusercontent.com/43583994/119199409-46718f80-ba8b-11eb-8dec-a4b0402600e6.mp4

End the turn and win the combat against Flint (with Summon Earth Elemental spell).

Here is the save file:
[Before AI hero embark.zip](https://github.com/ihhub/fheroes2/files/6525114/Before.AI.hero.embark.zip)

Related issue for sound: https://github.com/ihhub/fheroes2/issues/2271.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , which value did you set for AI speed? It looks like 9 or 10. I have the same animation timing for human and AI heroes if I set the same animation speed.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , which value did you set for AI speed? It looks like 9 or 10. I have the same animation timing for human and AI heroes if I set the same animation speed.

The "Hero Speed" setting was on "6" and the "Enemy Speed" setting was on "8".

Compare the duration of the animation of the disappearance of the AI Wizard hero from the adventure map after the combat (about one second) and the duration of the animation of the AI hero boarding (less than a quarter of a second).

Compare also with the duration of the animation of a hero's boarding in the original game.

Here in fheroes2 with both settings set to "8":

https://user-images.githubusercontent.com/43583994/119268843-09291100-bbf5-11eb-867a-21c9235fe357.mp4

And here in the original game with both settings set to "Canter":

https://user-images.githubusercontent.com/43583994/119268932-6755f400-bbf5-11eb-9f25-04da23c0255b.mp4

The speed of the boarding animation seems to be related to the setting of "Hero Speed" and "Enemy Speed" while the speed of the disappearing hero animation is always the same regardless of the setting of "Hero Speed" and "Enemy Speed".

End the turn.

Here is the save file:
[Before ai embark 02.zip](https://github.com/ihhub/fheroes2/files/6528490/Before.ai.embark.02.zip)
