### ISSUE TITLE
Scenario info window, incorrect graphics and information displayed for the scenario information window during the game compared to before the game

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3475]
In fheroes2, there are incorrect graphics and information displayed for the scenario information window during the game compared to before the game.

In original game:

![Wrong players' graphics 003](https://user-images.githubusercontent.com/43583994/119203115-9bfd6a80-ba92-11eb-8345-f0079c4dfc1c.png)

![Wrong players' graphics 004](https://user-images.githubusercontent.com/43583994/119203128-a3247880-ba92-11eb-86b9-f599e4d51410.png)

In fheroes2:

![Wrong players' graphics 001](https://user-images.githubusercontent.com/43583994/119203158-afa8d100-ba92-11eb-8b16-3c907021bb0e.png)

![Wrong players' graphics 002](https://user-images.githubusercontent.com/43583994/119203167-b59eb200-ba92-11eb-8a08-93ae85a7b9e2.png)

**Comment by Arthusppp** [comment]
I fixed a bug in the game info window that incorrectly displayed the player icon for computer-only players. See: bofore.png and after.png.

However, I am not sure if we should reimplement the whole original game logic. For example, the race picture is always grayed when a player is a computer-only player. I like more what is now in fheroes2: the picture is grayed only when a player cannot change its race.

What is more, I have found a few useful resources in the AGG. For example, an index from 21 to 26 (fheroes2::AGG::GetICN( ICN::NGEXTRA, index )) represents "dead human player". I have checked the game info window in the original game, and the original game does not use it. However, in my opinion, we can use it ("dead human player" may occur in the hot seat mode). The same for "computer only dead player" - index from 15 to 20.



![after](https://user-images.githubusercontent.com/85434237/127057242-9dee0428-7a47-4a18-863a-148d1fe1ef53.png)
![before](https://user-images.githubusercontent.com/85434237/127057243-999dc674-5410-46ba-b795-4349a8c71c4f.png)

**Comment by Arthusppp** [comment]
Update: As per fheroes2::AGG::GetICN( ICN::NGEXTRA, index), we have the following:

- index from 3 to 8 - represents a computer or human player (ie. blue, green or orange player on Brooken Alliance)
- index from 9 to 14 - represents a real human player; human selected player (ie. blue player on Brooken Alliance is a default player, the human icon)
- index from 15 to 20 - represents a computer only player (ie. red, yellow or purple on Brooken Alliance)
- index from 21 to 26 - represents a real human player, but "inactive/vanquished" (ie. a map with only one human only player)
And all above +24 gives an icon with name.
