### ISSUE TITLE
Add flavor text for Campaign Creature Alliance/Bane

### ISSUE THREAD

**Issue by eos428** [ihhub/fheroes2#3480]
In the original game, there are some flavor text for creature alliance/bane bonuses such as these:
![ogre-dwarfbane](https://user-images.githubusercontent.com/38433056/119231092-459f3300-bb49-11eb-9b12-1e941634bf38.png)
![dwarf-dwarfbane](https://user-images.githubusercontent.com/38433056/119231093-46d06000-bb49-11eb-98f9-dbbe58a9e98e.png)

So far in the original game's campaign, including PoL, we have these creature alliance/bane bonuses:
- Dwarf alliance
- Dwarf bane
- Ogre alliance
- Dragon alliance
- Elven alliance (in PoL campaign)

We should look into implementing the flavor text in these bonuses once PoL campaign support is up.
Let's assign this issue to me, but I'm open for an assignee change if anyone wants to try.

**Comment by Branikolog** [comment]
As in fheroes2 there's an option to enter heroes info and rearrange space for joining army, I think we should initiate a standard joining dialog after we watch a campaign specified message, that creatures are willing to join.
Also, in a case player has no free space in the OG we watch a message, that the creatures are going to give hero a pass.
![image](https://user-images.githubusercontent.com/55348946/119261143-b6445f00-bbde-11eb-9806-75735d1e7ab3.png)
I suggest this message appear, in a case player canceled joining dialog.

**Comment by eos428** [comment]
Hi @Branikolog, can you compile all the flavor text messages from the base game for this and post them in this issue?

Also, I'd like to know if the flavor text for Elven alliance is different depending on the campaign. They are available in both PoL campaign (scenario 3) and Descendants campaign (scenario 7).

**Comment by Branikolog** [comment]
Hi, @eos428 !
I'll try to check everything tomorrow (in ~12hrs). Don't have a machine with installed OG currently. )

**Comment by eos428** [comment]
Great, thanks for the help in advance!
