### ISSUE TITLE
Combat, when a troop of Dwarves resists a spell, the message should be displayed only after the animation of the spell

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3481]
When a troop of Dwarves resists a spell, the message should be displayed only after the animation of the spell.

In the example, Rialdo casts the spell Death Wave, the message that the Dwarves are resisting the spell is displayed before the animation of the spell is finished, breaking the suspense of the result.

In fheroes2:

![vlcsnap-2021-05-22-17h49m33s301](https://user-images.githubusercontent.com/43583994/119233163-e7158d00-bb27-11eb-8688-17f6f2aa71e9.png)

https://user-images.githubusercontent.com/43583994/119233173-f8f73000-bb27-11eb-999c-3424c5e84575.mp4

Rialdo attacks Rebecca.

Here is the save file:
[Before dwarves resist spellm.zip](https://github.com/ihhub/fheroes2/files/6526757/Before.dwarves.resist.spellm.zip)

**Comment by oleg-derevenetz** [comment]
> breaking the suspense of the result

:)
