### ISSUE TITLE
Campaign, wrong hero receives bonus spell

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#3492]
Scenario 6, "Defender".
![image](https://user-images.githubusercontent.com/55348946/119267626-1f849c00-bbf8-11eb-9421-04d9f38ada9d.png)
In the OG another hero gets a bonus and Lord Halton has empty spellbook,
[Good_5_Complete.zip](https://github.com/ihhub/fheroes2/files/6528435/Good_5_Complete.zip)

**Comment by ihhub** [comment]
I think we have correct implementation in comparison with the original game. Lord Halton should receive this spell, not a random hero in the castle.

**Comment by Branikolog** [comment]
Hi, @ihhub 
I believe, that applying bonus to the second hero makes both of starting heroes valuable and expands the gameplay of the scenario. Player is given a choice which of both heroes to use as primary. (or even both at once) While your proposal makes player always choose Halton.
