### ISSUE TITLE
Main menu, highlight key controls in introducing message

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#3505]
I suggest make "F4" and "Door" with other color, so players won't skip this message so fast and notice window adjustment controls.
![image](https://user-images.githubusercontent.com/55348946/119331193-c23c2980-bc8f-11eb-8a76-4c9f7ef429ab.png)

**Comment by ihhub** [comment]
This needs a proper implementation of Text class to support multi-color letters.
