### ISSUE TITLE
Campaign, some names of bonuses don't fit the box and should be shortened

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#3509]
The names of bonuses in "Choice" box are sometimes too long:
![image](https://user-images.githubusercontent.com/55348946/119353626-ca09c700-bcab-11eb-85a4-c4241ff4c2cd.png)
![image](https://user-images.githubusercontent.com/55348946/119332345-20b5d780-bc91-11eb-8540-c40a29c29199.png)
![image](https://user-images.githubusercontent.com/55348946/119332252-01b74580-bc91-11eb-8078-c5c4255a00f4.png)
![image](https://user-images.githubusercontent.com/55348946/119336045-c408eb80-bc95-11eb-9c42-0b7e2c82b43a.png)
![image](https://user-images.githubusercontent.com/55348946/119338603-e05a5780-bc98-11eb-95ad-deb447291f39.png)
![image](https://user-images.githubusercontent.com/55348946/119339384-c10ffa00-bc99-11eb-943a-2f2ff8d66969.png)
![image](https://user-images.githubusercontent.com/55348946/119341902-01bd4280-bc9d-11eb-80f2-9654bf5dd749.png)
![image](https://user-images.githubusercontent.com/55348946/119351874-a9d90880-bca9-11eb-8964-59cb8f7dd816.png)
![image](https://user-images.githubusercontent.com/55348946/119351987-cbd28b00-bca9-11eb-8099-407a114e3502.png)

**Comment by Branikolog** [comment]
In the original "Choice" looks like:
![image](https://user-images.githubusercontent.com/55348946/119353344-70090180-bcab-11eb-99a5-45178fb1ab2c.png)
![image](https://user-images.githubusercontent.com/55348946/119353397-80b97780-bcab-11eb-95bf-e68bb94198c5.png)
![image](https://user-images.githubusercontent.com/55348946/119353448-93cc4780-bcab-11eb-823c-be8876ea8395.png)

![image](https://user-images.githubusercontent.com/55348946/119352463-659a3800-bcaa-11eb-9d59-2b64a9cc539e.png)
![image](https://user-images.githubusercontent.com/55348946/119352533-78ad0800-bcaa-11eb-8e7c-939c14f5d366.png)
![image](https://user-images.githubusercontent.com/55348946/119352575-8793ba80-bcaa-11eb-8b35-81b83961c43b.png)
![image](https://user-images.githubusercontent.com/55348946/119352725-b3af3b80-bcaa-11eb-880a-38f460a1d0e5.png)
![image](https://user-images.githubusercontent.com/55348946/119352669-a3975c00-bcaa-11eb-8bc9-985111a66a7e.png)

**Comment by felix642** [comment]
Is there a reason why the rewards are different from the original ? 
For example:
In Roland's campaign scenario 1 one of the reward is a scroll instead of a gauntlet..?
