### ISSUE TITLE
View Puzzle screen, the outline of the pieces of the puzzle can be seen

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3516]
In fheroes2, the outline of the pieces of the puzzle can be seen.

In original game:

![Full puzzle H2 01](https://user-images.githubusercontent.com/43583994/119368488-5d92c600-bcb3-11eb-90be-03891d88c104.png)

In fheroes2:

![Full puzzle fh2 01](https://user-images.githubusercontent.com/43583994/119368531-684d5b00-bcb3-11eb-99a7-e2ce0c8fa215.png)

Here are the save files:
[Full puzzle 01.zip](https://github.com/ihhub/fheroes2/files/6533340/Full.puzzle.01.zip)

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

You should do this as quickly for all issues.
We would be close to zero issues now. :D

**Comment by ihhub** [comment]
Haha. I just knew how to fix it.
