### ISSUE TITLE
Intro videos and cutscenes don't play

### ISSUE THREAD

**Issue by mepm1234** [ihhub/fheroes2#3525]
Using the GOG gold version the startup video, intro and cutscenes do not play. Intro button greyed out.

**Comment by Branikolog** [comment]
Hi, @mepm1234 
Could you specify, what version of fheroes2 engine have you installed?
So, you're not even able to choose the lord and default start campaign for Roland, right?

**Comment by ihhub** [comment]
Hi @mepm1234 , video supported will be added in the upcoming 0.9.4 release.

**Comment by mepm1234** [comment]
> 
> 
> Hi, @mepm1234
> Could you specify, what version of fheroes2 engine have you installed?
> So, you're not even able to choose the lord and default start campaign for Roland, right?

Hello, I am using the one installed from GOG, which i believe is 2.1 Gold.
The game starts fine, I can choose lord and start campaign no problem, i just do not see any of the opening splash videos, intro videos, or any of the other videos in the game.
This seems to stem from the GOG gold version locating the video and cd audio files on a virtual cd instead of in a video folder in the game directory.
I managed to find a regular copy of heroes 2 and copied the video folder across and now the cutscenes play fine.

**Comment by ihhub** [comment]
Hi @mepm1234 , DOS version of the game from GOG has CD music wrapped into virtual player. Windows version from GOG which you can download on the right side of the the game description contains proper video files which are payed by fheroes2. Also, as I mentioned earlier the upcoming 0.9.4 version will have proper intro videos for every scenario in the campaign. If you use the latest version (not release) of the project then you can enjoy it even right now🙂
