### ISSUE TITLE
Combat screen, display the greyed out hex(es) for troop positioning when attacking

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3575]
~In fheroes2, the 2-hex units' shadow is not displayed when the unit attacks a troop.~
In fheroes2, it would be nice to display the greyed out hex(es) for troop positioning when attacking.

In fheroes2:

![2 hex creature shadow 001](https://user-images.githubusercontent.com/43583994/120108630-531a7580-c166-11eb-8dda-b1f5df5e014e.png)

![2 hex creature shadow 002](https://user-images.githubusercontent.com/43583994/120108632-5877c000-c166-11eb-8aeb-5b85b66e2b84.png)

**Comment by ihhub** [comment]
None of movement shadow is displayed while attacking.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> None of movement shadow is displayed while attacking.

Oh, you're right.
Do you think it would be nice to display the greyed out hex(es) for troop positioning when attacking?
Personally, I'm for it. :)
