### ISSUE TITLE
Segfault OS X Map 10 Price of Loyalty 

### ISSUE THREAD

**Issue by mgtremaine** [ihhub/fheroes2#3581]
I have Seg Fault on OS X in the Price of Loyalty Map 10... In the start of the game if Kalindra attacks Corlagon and lightning bolts the Champions the same segfault after the victory screen.

Attached is part of the backtrace. I'll try to see if other combos work around or also crash but I tried it 3 times to make sure.

[sig_fault_osx-05312021.txt](https://github.com/ihhub/fheroes2/files/6571010/sig_fault_osx-05312021.txt)

-Mike

**Comment by ihhub** [comment]
Hi @mgtremaine , could you please provide a save file for this?

**Comment by mgtremaine** [comment]
In zip file.. 
[homm2_crash_save.zip](https://github.com/ihhub/fheroes2/files/6571122/homm2_crash_save.zip)

**Comment by oleg-derevenetz** [comment]
A quick glance reveals that `std::find()` returns `heroes.end()` here:

https://github.com/ihhub/fheroes2/blob/426d8cf9e7d78fe114f1eb34b7e880dab040f808/src/fheroes2/kingdom/kingdom.cpp#L274

so `heroes.erase()` crashes, because its argument isn't dereferenceable.

**Comment by oleg-derevenetz** [comment]
hi @ihhub I have some suspicions regarding `applyObtainedCampaignAwards()` in `game/game_campaign.cpp`. In this function hero may be removed from kingdom if `TYPE_DEFEAT_ENEMY_HERO` award was received, but this hero may still be present on map itself. Is this possible?

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , I have a fix for this. I'll create a pull request in the next 1-2 hours.
