### ISSUE TITLE
Adventure map, AI behavior, hero Luna of the yellow AI player does not capture mines located near his movement path (0.9.3 3574)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3589]
The hero Luna of the yellow AI player does not capture mines located near his movement path.
Later Luna attacks a green AI hero but does not capture the mine and moves away, to capture the mine the next turn.

In fheroes2:

https://user-images.githubusercontent.com/43583994/120367568-53a33f80-c311-11eb-91a6-c9c217a4cf6d.mp4

End the turn several times.

Here is the save file:
[Luna not capture mine move_.zip](https://github.com/ihhub/fheroes2/files/6578402/Luna.not.capture.mine.move_.zip)

**Edit 2021/11/25.**

Another save for this (0.9.9 4628).

Hero Halon of the green AI player does not pick up the Crystal resource pile or capture the Crystal mine.
I don't think he has anything really urgent to do with his army of few Zombies. :D
The next turn, Halon comes to his senses and turns back to capture the mine and pick up the resource pile.

In fheroes2:

![Halon Crystal mine 01](https://user-images.githubusercontent.com/43583994/143434902-585a9a94-3943-4959-b743-f326ec9455eb.png)

End the turn twice.

Here is the save file:
[Before Halon no take resourc.zip](https://github.com/ihhub/fheroes2/files/7602640/Before.Halon.no.take.resourc.zip)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , is it still a valid issue?

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , is it still a valid issue?

Another I'm putting on my "to be tested soon" list. :)
