### ISSUE TITLE
SDL 1 version has white surroundings for video playback

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#3594]
If only `DATA` directory is present in the game's folder SDL 1 renders a frame white surroundings which is incorrect:
![image](https://user-images.githubusercontent.com/19829520/120499934-0ac3b780-c3f3-11eb-84d4-6d4b82e10dda.png)

**Comment by felix642** [comment]
![image](https://user-images.githubusercontent.com/60141446/122776300-f992fb80-d278-11eb-9d76-146f5e22cefd.png)
![image](https://user-images.githubusercontent.com/60141446/122776928-8b026d80-d279-11eb-874f-b055eac7d4a3.png)
Unless I'm wrong this issue also seems to happen with SDL 2 on linux?

**Comment by ihhub** [comment]
The problem is that we use a palette from a video file and the one from `DATA` directory contains a palette with the color on position 0 not being black but almost white which leads to this kind of effect.

**Comment by ihhub** [comment]
Closing this issue as it is a problem of original assets. Such situation happens only if no other video files are present.
