### ISSUE TITLE
AI does not attack monsters and gets stuck

### ISSUE THREAD

**Issue by OVlasiuk** [ihhub/fheroes2#3597]
In this map, one of the AI players decided not to attack the monsters on either side, and got stuck. The game binary was built from 73d3f86.

![Screenshot from 2021-06-02 20-26-15](https://user-images.githubusercontent.com/16726650/120568400-c8de4580-c3e1-11eb-9329-941cdb1a03cc.png)

Here is the save file:
[stuck_bug.sav.zip](https://github.com/ihhub/fheroes2/files/6588098/stuck_bug.sav.zip)

**Comment by ihhub** [comment]
One hero blocks another and the second one has nothing to do. We need to add logic to free path for another heroes.

**Comment by idshibanov** [comment]
Also should avoid hiring more heroes if they have nowhere to go (as a separate improvement). Might check hero count in the same map region and/or their task list.
