### ISSUE TITLE
The battle can not start after Alt+Tab

### ISSUE THREAD

**Issue by Kromster80** [ihhub/fheroes2#3598]
1. Start the battle
2. Alt+Tab out of the game while the battle intro music is playing
4. Alt+Tab back
Bug: Your troops are not selected and you can not click anything. The game still runs (adventure map animations play)

**Comment by Kromster80** [comment]
Okay. Then it can be closed

P.S. I'm using 0.9.3 now :-)

**Comment by oleg-derevenetz** [comment]
@Kromster80 This wasn't fixed in 0.9.3 yet, this fix will be included in 0.9.4. You can always get the latest build (from the latest commit to master branch) here:

https://github.com/ihhub/fheroes2/releases

On the second page with "Pre-release" label.
