### ISSUE TITLE
Campaign is not yet usable?

### ISSUE THREAD

**Issue by xcom169** [ihhub/fheroes2#3615]
Hello All! 
Campaign option is not yet usable?
![image](https://user-images.githubusercontent.com/17802090/120792315-9d6c6f80-c535-11eb-845c-032c36b9ba06.png)

**Comment by Branikolog** [comment]
Hi, @xcom169 !
Both campaigns are supported.
To play campaign you have to own original Heroes of Might and Magic 2 official version.

**Comment by xcom169** [comment]
Hello, @Branikolog !
I have the official GOG version on my machine. My config points to the app/DATA directory. Is it okay? 


# fheroes2 configuration file (saved under version 0.9.3)

# path to directory data
data = ./app/DATA/

# path to directory maps (you can set few map directies)
maps = ./app/MAPS/

# video mode (game resolution)
videomode = 1366x768

**Comment by ihhub** [comment]
Hi @xcom169 , please try not to change configuration file by yourself. Not every feature there is supported (leftovers from previous team). If you're using Linux then you have to copy DATA and MAPS directories to the location of fheroes2 or `XDG_DATA_HOME/fheroes2/maps` if I remember correctly :)
