### ISSUE TITLE
Adventure map, Boat changes orientation after picking up an artifact and then when the hero embarks (0.9.4 3612)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3619]
In fheroes2, the Boat changes orientation after picking up an artifact and then when the hero embarks.

In fheroes2:

![Boat change orientation 001](https://user-images.githubusercontent.com/43583994/120867988-57de8f80-c593-11eb-9e23-96c6e2a9ac24.png)

![Boat change orientation 002](https://user-images.githubusercontent.com/43583994/120868002-5ca34380-c593-11eb-9c11-e4f959a8a6e6.png)

![Boat change orientation 003](https://user-images.githubusercontent.com/43583994/120868014-6036ca80-c593-11eb-88a8-88593ee34181.png)

https://user-images.githubusercontent.com/43583994/120868046-6c228c80-c593-11eb-918c-a698c6e9600a.mp4

Here is the save file:
[Before boat change orientatio.zip](https://github.com/ihhub/fheroes2/files/6601465/Before.boat.change.orientatio.zip)

Similar issues: https://github.com/ihhub/fheroes2/issues/3243, https://github.com/ihhub/fheroes2/issues/2173.

**Comment by tau3** [comment]
This boat has `Direction::UNKNOWN`. Has it been summoned? For some reason it has its direction unset.

**Comment by LeHerosInconnu** [comment]
Hello @tau3,

> This boat has `Direction::UNKNOWN`. Has it been summoned? For some reason it has its direction unset.

If I remember correctly, the hero Dimitry disembarked from this boat after it was built at Bloodreign castle located just northwest of Dimitry's position.
I don't have a previous save file.

**Comment by ihhub** [comment]
Fixed in #5692.
