### ISSUE TITLE
Adventure map, it is not possible to capture a gold mine (0.9.4 3612)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3632]
In fheroes2, it is not possible to capture a gold mine.
This mine is an abandoned mine at the beginning of the scenario.

In fheroes2:

![Gold mine no capture 001](https://user-images.githubusercontent.com/43583994/120903333-ea3f6b80-c645-11eb-8ce4-35208800d965.png)

![Gold mine no capture 002](https://user-images.githubusercontent.com/43583994/120903331-e6abe480-c645-11eb-9436-ed65c8abe6e6.png)

Here is the save file:
[Gold mine no capture 01.zip](https://github.com/ihhub/fheroes2/files/6603134/Gold.mine.no.capture.01.zip)

**Comment by oleg-derevenetz** [comment]
Did this mine belong to some vanquished AI player before?

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> Did this mine belong to some AI player before (then vanquished)?

This is possible because the production of the mine has been restored.
The mine was already like this (without a flag) when one of my heroes revealed the adventure map.

Here are the save files (before Ambrose move to the Observation Tower to reveal the Gold mine, and at scenario turn 4):
[Gold mine bug 01.zip](https://github.com/ihhub/fheroes2/files/6603159/Gold.mine.bug.01.zip)

**Comment by oleg-derevenetz** [comment]
Currently I even don't have any idea how to get an ex-abandoned mine without flag. If former owner was vanquished, then it should have a gray flag. Someone may apply Haunt spell on it, then flag should be removed, but in this case mine should be still haunted.

**Comment by LeHerosInconnu** [comment]
The gold mine is not displayed correctly in the "View World" screen:

![Gold mine bug cercle 01](https://user-images.githubusercontent.com/43583994/120927981-21178f00-c6e3-11eb-8b3a-afe84a0fb873.png)

Strangely, there is a similar bug in the original game: :D
https://heroes2.forumactif.com/t860-heroes-2-bugs-inaccessible-resource-generators

**Comment by oleg-derevenetz** [comment]
It's because there in no mine object on this tile anymore, it's `OBJ_ZERO` now. But I still don't know a way to reproduce this.

**Comment by oleg-derevenetz** [comment]
Here is a save file that reproduces the issue. Just press "End Turn" :)

[Gold mine no capture X.zip](https://github.com/ihhub/fheroes2/files/6623585/Gold.mine.no.capture.X.zip)

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu

> Here are the save files (before Ambrose move to the Observation Tower to reveal the Gold mine, and at scenario turn 4):

Thank you, the latter was really helpful and I was able to reproduce the issue.

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> Here is a save file that reproduces the issue. Just press "End Turn" :)
> 
> [Gold mine no capture X.zip](https://github.com/ihhub/fheroes2/files/6623585/Gold.mine.no.capture.X.zip)

The bug works well, but do you have enough Dragons? :D

**Comment by oleg-derevenetz** [comment]
There will be never enough dragons :)
