### ISSUE TITLE
Combat, AI behavoir, Titan moves to avoid hand-to-hand combat but will position next to another opposing troop (0.9.4 3612)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3634]
In fheroes2, the Titan moves to avoid hand-to-hand combat but will position next to another opposing troop.
This happens frequently with other ranged creatures as well.

In fheroes2:

https://user-images.githubusercontent.com/43583994/120905747-7f496100-c654-11eb-893d-1f12bfd5d0b0.mp4

Attack Lord Kilburn.
Try your best to reproduce the combat.

Here is the save file:
[Before attack Kilburn 01.zip](https://github.com/ihhub/fheroes2/files/6603252/Before.attack.Kilburn.01.zip)

**Comment by idshibanov** [comment]
Existing logic should have been able to handle this situation. Something definitely was miscalculated here, hence tagged the issue as a bug.

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu and @idshibanov !
While watching a stream on youtube I've noticed similar issue.
Titans even couldn't run away from the neighboring enemy:
![Hydra VS Titans 1](https://user-images.githubusercontent.com/55348946/122759346-80a89980-d2a2-11eb-9f8f-ad6948fb43d7.png)
![Hydra VS Titans 2](https://user-images.githubusercontent.com/55348946/122759357-83a38a00-d2a2-11eb-81e9-72047bc7ad97.png)
![Hydra VS Titans 3](https://user-images.githubusercontent.com/55348946/122759363-8605e400-d2a2-11eb-965f-b25a5f2df3a1.png)

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

> Hi, @LeHerosInconnu and @idshibanov !
> While watching a stream on youtube I've noticed similar issue.
> Titans even couldn't run away from the neighboring enemy:

Yes, this often happens, the ranged troop moves into another hexagon located near the troop it is already adjacent to (and even if both troops are one-hex troops).
