### ISSUE TITLE
Since version 0.9.4, all the start screens of the game are displayed each time the program is launched (0.9.4 3612)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3636]
In fheroes2, since version 0.9.4, all the start screens of the game are displayed each time the program is launched.

In fheroes2:

![Launch screens 001](https://user-images.githubusercontent.com/43583994/120908665-c04d6f80-c66c-11eb-951d-f8952c3cebdc.png)

![Launch screens 002](https://user-images.githubusercontent.com/43583994/120908668-c5122380-c66c-11eb-95d1-03a543e82c68.png)

![Launch screens 003](https://user-images.githubusercontent.com/43583994/120908669-c8a5aa80-c66c-11eb-9953-acfacdb09a98.png)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , are you running the game under non-admin account?

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , are you running the game under non-admin account?
> 
> Also please try to set any non default resolution and restart the game. Is the resolution being remembered?

It is the same, if I launch the program using the command "Open in administrator mode".
The resolution is not saved, the game always starts in "640 x 480" resolution.

**Comment by ihhub** [comment]
@LeHerosInconnu , do you have a configuration file under game's directory? Also could you please check the same configuration file under user's directory on your Windows account?

**Comment by LeHerosInconnu** [comment]
@ihhub.

This file is the problem (located in game's directory):
[fheroes2.cfg.zip](https://github.com/ihhub/fheroes2/files/6603501/fheroes2.cfg.zip)

When removing it from the game's directory, the start screens does not appear anymore.
If the file is put back in the game's directory, the start screens appear again.

**Comment by ihhub** [comment]
Hi @qarkai , would you mind to take a look at this?

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , could you please verify your initial issue with these changes (once they're compiled of course)?

**Comment by LeHerosInconnu** [comment]
@ihhub,

> Hi @LeHerosInconnu , could you please verify your initial issue with these changes (once they're compiled of course)?

Everything seems to work correctly.
Starting windows are no longer displayed systematically and the game resolution is properly saved.
