### ISSUE TITLE
Hero animation during battle

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#364]
Frame, when hero closes his eyes, is moved a bit during animation circle.

![Безымянный01](https://user-images.githubusercontent.com/55348946/74530618-228fd780-4f33-11ea-887d-489152d1a604.jpg)
![Безымянный](https://user-images.githubusercontent.com/55348946/74530622-258ac800-4f33-11ea-9c03-13762b31e468.jpg)

**Comment by ihhub** [comment]
It applies only for a hero on the right side of the battle.
