### ISSUE TITLE
travis-ci.org is shutting down at June 15th

### ISSUE THREAD

**Issue by oleg-derevenetz** [ihhub/fheroes2#3643]
As I understand, currently only Linux ARM builds are produced on Travis? Are they in user demand at all?

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , according to download statistics 4% of downloads are Ubuntu ARM. I think we could just cut it off on 15th, it's not worth such troubles.

**Comment by oleg-derevenetz** [comment]
> according to download statistics 4% of downloads are Ubuntu ARM

Interesting, what customer-grade hardware is running this. Some former Android tablets with Ubuntu installed? Mac M1?... Anyway it seems that the people who run this are able to take care of themselves and build game from sources.
