### ISSUE TITLE
View enemy's army

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#366]
You can't see enemy's army info in the city without thieves guild being built in your own city.
![Безымянный11](https://user-images.githubusercontent.com/55348946/74535805-4a853800-4f3f-11ea-8c52-983138944a1f.jpg)

**Comment by ihhub** [comment]
Hi @Branikolog how about the behavior in the original game?

**Comment by werfu** [comment]
Original game would not give you any info unless you have had a theives guilds too. You would get more and more detailed information with more theives guilds.

**Comment by Branikolog** [comment]
In the OG, without thieves guild you will see "unknown" while pointing enemy castle.
If you have 1 thieves guild, you can see troop type with "???" quantity.
If you have 2 or more thieves guilds, you can watch enemy army in city and know approximate quantity of creatures (ex: lots, several, etc.)
