### ISSUE TITLE
Battle screen, walking sound of troops starts each new cell it reaches

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#3661]
Comparing to the OG, in fheroes2 walking sound becomes a mess, especially, while playing on higher speeds.
Seems like sound is starting each time creature reaches new cell. While in the OG walking sound seems to be looped.

https://user-images.githubusercontent.com/55348946/121517490-19fcc380-c9f8-11eb-83c3-1c7df7727553.mp4

In my opinion, original implementation is not optimal too, as there we can notice, that after one creature starts walking making its sound, another same type creature could start its movement before sound of the first creature was finished.

Thanks to @keep[it]movin from discord for finding the issue and creating a videos, showing a problem.

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

Here is a video of the English Gold version of the original game.
It seems that the sounds are handled in a different way in the video of the Russian version presented.

In original game:
Activate the sound of the video.

https://user-images.githubusercontent.com/43583994/121561705-0ada3d80-ca19-11eb-9d85-3b4b621826c2.mp4

Here is the test scenario file:
[0 9959.zip](https://github.com/ihhub/fheroes2/files/6633004/0.9959.zip)

**Comment by oleg-derevenetz** [comment]
Hi all,

> While in the OG walking sound seems to be looped.

This is not good. This gives the impression that creature moves slower than it actually is. In fheroes2 (and in this video from @LeHerosInconnu) the frequency of sounds roughly corresponds to the frequency of steps, what looks more natural.

**Comment by Branikolog** [comment]
Thanks for help, @oleg-derevenetz and @LeHerosInconnu !
I didn't check the behaviour of the OG, because years ago I seem to have the same version with the same sound operation. :)
So the issue is not actual....
The only thing botheres me: each time creature steps new hex walking sound starts. If the speed is too high, multiple sounds start overlapping each other creating echoing sound. How do you think, would it be better to cut walking sounds to prevent overlapping?

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

> Thanks for help, @oleg-derevenetz and @LeHerosInconnu !
> I didn't check the behaviour of the OG, because years ago I seem to have the same version with the same sound operation. :)
> So the issue is not actual....
> The only thing botheres me: each time creature steps new hex walking sound starts. If the speed is too high, multiple sounds start overlapping each other creating echoing sound. How do you think, would it be better to cut walking sounds to prevent overlapping?

As you say, this only happens when the speed is very high.
Personally, I prefer the sound to be played completely rather than truncated, even if it does have the kind of echo effect you are talking about.
It would also be possible to decrease the sound smoothly when the next sound starts to be played, but I think this might become a bit too complicated to handle with the different high speeds.
If it's not complicated to do why not, but if it takes a lot of time to implement it can wait, and also, is it really necessary?

**Comment by Branikolog** [comment]
I'll create a discussion then, if it necessary to to interrupt sounds.
Also, I want to note here, that the same we can hear during hero galloping on a world map. Which also doesn't please my ears.)
