### ISSUE TITLE
Adventure map, visited info of an object doesn't refresh after attacking of guardians

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#3680]
We step on a water wheel, that has some neutral monster nearby and attack them. After battle game initiates visiting of the wheel. But after we step out we can still watch "not visited" state of the wheel.
![image](https://user-images.githubusercontent.com/55348946/121805099-4b70cb80-cc52-11eb-9f62-48f033dce72d.png)
![image](https://user-images.githubusercontent.com/55348946/121805107-54619d00-cc52-11eb-8a18-908264e182dc.png)
![image](https://user-images.githubusercontent.com/55348946/121805115-63e0e600-cc52-11eb-927a-07c59078f8ed.png)
![image](https://user-images.githubusercontent.com/55348946/121805117-6b07f400-cc52-11eb-855d-27c9457b8663.png)
![image](https://user-images.githubusercontent.com/55348946/121805128-73f8c580-cc52-11eb-995a-02f444507f26.png)

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog do you have a savefile before this visit?

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz 
Sorry, forgot to add it! :)
[Water wheel bug.zip](https://github.com/ihhub/fheroes2/files/6643931/Water.wheel.bug.zip)

**Comment by oleg-derevenetz** [comment]
It looks like "not visited" status is not related to guardians, it is still not shown as "visited" after subsequent visits. Even if I liberate the Water Wheel, wait for the next week and visit it again, it is still shown as "not visited".
