### ISSUE TITLE
Adventure map, path shouldn't be created through an object entrance that has some guardians nearby

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#3681]
In the OG:
![image](https://user-images.githubusercontent.com/55348946/121805645-a9061780-cc54-11eb-8793-928cbf04f6bc.png)

In fheroes2:
![image](https://user-images.githubusercontent.com/55348946/121805659-b4f1d980-cc54-11eb-9ec3-e1c05f52e068.png)

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

Oh, I like when a bug improves the game in some way.
Here the hero does not spend 100 points of movement unnecessarily thanks to the bug. :D

This way of making the hero's path over the object's active square could become the norm to decrease the distance to travel, the window of the object's active square would not be triggered if the object is not the final destination.
See the case at the end of this issue: https://github.com/ihhub/fheroes2/issues/1214.

Although this bug needs to be fixed, it is something to remember. :)

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu 
Well, not initiating of an object could be a solution, but in that case player can forgot to visit the object... So, for now we're going to stick to the original behaviour...

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> So, for now we're going to stick to the original behaviour...

Yes, the bug needs to be fixed for a functioning similar to the original game.
As I wrote, it would be for the future.

> Well, not initiating of an object could be a solution, but in that case player can forgot to visit the object...

It is also possible to take into account special cases for objects on the hero's path and not visited by the hero that would trigger the window.

**Comment by oleg-derevenetz** [comment]
I do not know as a result of which commit it was fixed, but it is now fixed:

![Guarded object entrance](https://user-images.githubusercontent.com/32623900/154799389-124428ac-3411-4b4e-8cf9-494b4402730c.jpg)
