### ISSUE TITLE
Quit dialog window

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#369]
There's confirm quit dialog window in the original game. It appears in a case we push the quit button or just press window's close button.

**Comment by ihhub** [comment]
@Branikolog  could you please attach a screenshot showing the dialog?

**Comment by werfu** [comment]
![quit_confirmation](https://user-images.githubusercontent.com/421280/77838052-1a37d880-713e-11ea-88dc-261973448719.jpg)

**Comment by Branikolog** [comment]
Actually, our game has this dialog window, but it appears only if we press esc button.
Should make it appear in a case of pressing quit button in file options menu.

**Comment by shprotru** [comment]
Checked: in the original game you can't initiate quit process by simple pressing ESC button, in fheroes2 you can, and I think it adds little bit comfort to game expirience. But original game asks "are you sure?" on pressing quit button in file menu and we must.
