### ISSUE TITLE
Compilation of project with SDL 2 for Windows

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#37]
We have compilation of the project on _AppVeyor_ for **SDL 1.2**. We would like to have the compilation for **SDL 2** as well.

**Comment by mahasak** [comment]
@ihhub Thanks i will try this one too.

**Comment by andrey-starodubtsev** [comment]
Is it acceptable to double number of configurations here, i.e. instead of

```
Debug|Win32
Release|Win32
Debug|x64
Release|x64
```

have

```
Debug-SDL1|Win32
Release-SDL1|Win32
Debug-SDL1|x64
Release-SDL1|x64
Debug-SDL2|Win32
Release-SDL2|Win32
Debug-SDL2|x64
Release-SDL2|x64
```
?

Also does it make sense to build `Debug` configuration in AppVeyor as well?

Should `msbuild /m` be used to speed up build process?

**Comment by ihhub** [comment]
@andrey-starodubtsev I don't think that we need to build Debug versions on our servers. First, the main goal of any development is to deliver final product which is Release. Secondly, we don't want to double our deployments. Lastly, AppVeyor doesn't support parallel job execution so double number of jobs will double execution time for each commit. I would not recommend to do it.

Speeding up builds is always welcome!
