### ISSUE TITLE
Edge of a world map

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#370]
There's something like a stone frame surrounding world map in the original game. It helps in positioning hero always in the center of the screen.
![Безымянный11](https://user-images.githubusercontent.com/55348946/74585486-d05bbe80-4fe5-11ea-82fd-39bd339bae15.jpg)

**Comment by ihhub** [comment]
Hi @Branikolog could you please attach a screenshot from the original game showing the 'wall'?

**Comment by werfu** [comment]
![image](https://user-images.githubusercontent.com/421280/77838245-202eb900-7140-11ea-9f05-ea71c67235a7.png)
