### ISSUE TITLE
Game, when the game resolution is changed, the value "off" of "show game intro = off" is reset to "on" in the file "fheroes2.cfg" (0.9.4 3699)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3708]
In fheroes2, when the game resolution is changed, the value "off" of "show game intro = off" is reset to "on" in the file "fheroes2.cfg".

**Comment by oleg-derevenetz** [comment]
Cannot reproduce this so far. I found a Windows machine, downloaded and installed the latest build from here:

https://ci.appveyor.com/project/ihhub/fheroes2/builds/39652976/job/t9pehcf6y4d6p4io/artifacts

then manually changed `show game intro` to `off` in `%APPDATA\fheroes2\fheroes2.cfg`, and then tried to change game resolution via resolution menu called by pressing on the door on the left in main game menu. `videomode` is changing in `fheroes2.cfg`, but `show game intro` remains `off`.

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu BTW, you don't happen to be trying to edit fheroes2.cfg while fheroes2 is already running, do you?

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz,

> @LeHerosInconnu BTW, you don't happen to be trying to edit fheroes2.cfg while fheroes2 is already running, do you? Because fheroes2 isn't able to apply manual config changes "on the fly".

I try all possibilities. :D
But in all cases, I have the same result.

The change (made before running the program) is applied correctly when I run the program, but as soon as I change the game resolution (with the door in game), the setting is reset to "on".

**Comment by oleg-derevenetz** [comment]
I can't reproduce this so far. This can only be the case if fheroes2.exe was started first, and, while it is running, fheroes2.cfg was edited. In this case all manual changes in fheroes2.cfg made while fheroes2.exe is running will be overwritten.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog could you please check if you can reproduce this issue?

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz,

I found out what the problem is.
If there is another ".cfg" file in the folder this causes a problem.
I had renamed the old configuration file "old fheroes2.cfg".
When I delete this file everything works fine.
This should be taken into account.

**Comment by oleg-derevenetz** [comment]
> @oleg-derevenetz,
> 
> I found out what the problem is.
> If there is another ".cfg" file in the folder this causes a problem.
> I had renamed the old configuration file "old fheroes2.cfg".
> When I delete this file everything works fine.
> This should be taken into account.

Yes, if I copy existing config file as "old fheroes2.cfg" and set `show game intro` to `on` in it, then game intro is shown, so it seems that this file is read instead of `fheroes2.cfg`. However, if I rename it to `xxx.cfg`, then everything works fine. It seems that any file with name which ENDS with `fheroes2.cfg` is considered as a config file.

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz and @LeHerosInconnu 
It seems that you've resolved the issue without my help.)

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog

> It seems that you've resolved the issue without my help.)

Yes, but thank anyway! :)
