### ISSUE TITLE
Adventure map, "Visions" spell doesn't show actual neighbor monsters

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#3732]
The spell seem to be broken and show info about monsters that are located somewhere else.
![image](https://user-images.githubusercontent.com/55348946/122749339-e5112c00-d295-11eb-9830-3be7cbd56405.png)
![image](https://user-images.githubusercontent.com/55348946/122749363-eb9fa380-d295-11eb-941e-e790c60a3b55.png)
Sometimes it show the same monster info twice.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog could you please attach a savefile? :)

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Sure!
[Visions.zip](https://github.com/ihhub/fheroes2/files/6686146/Visions.zip)
Actually. it doesn't work anywhere in game.)

**Comment by oleg-derevenetz** [comment]
@Branikolog Thanks! I'll try to look into this tonight.
