### ISSUE TITLE
Adventure map, wrong object display priority, top of the Volcano sprite is displayed over the top of the hero sprite

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3746]
In fheroes2, the top of the Volcano sprite is displayed over the top of the hero sprite.

In fheroes2:

![vlcsnap-2021-06-23-15h41m31s776](https://user-images.githubusercontent.com/43583994/123109540-9c937300-d43b-11eb-9c2f-35070ce20136.png)

https://user-images.githubusercontent.com/43583994/123108846-0eb78800-d43b-11eb-86f6-e1e50ca90e65.mp4

Here is the test scenario file:
[0 9958.zip](https://github.com/ihhub/fheroes2/files/6702313/0.9958.zip)

**Comment by ihhub** [comment]
All hero related rendering will be addressed under one pull request later. The way how we render heroes is absolutely incorrect leading to such situations.

**Comment by Branikolog** [comment]
Not sure, if there was a thread for trees.
Just post the screenshot here. ;)
![image](https://user-images.githubusercontent.com/55348946/127515967-cfd285ec-4159-4571-bb54-3dcfe32521e8.png)

**Comment by vasilenkoalexey** [comment]
> Not sure, if there was a thread for trees.
> Just post the screenshot here. ;)
> ![image](https://user-images.githubusercontent.com/55348946/127515967-cfd285ec-4159-4571-bb54-3dcfe32521e8.png)

This related to #1428

**Comment by LeHerosInconnu** [comment]
Another case for this.

In fheroes2, the top of hero sprite is cut.

In fheroes2:

![Top hero sprite cut 1000](https://user-images.githubusercontent.com/43583994/131662389-8ad7e7b0-a807-40e9-a740-8e8a704b71bb.png)

Here is the save file:
[Top hero sprite cut 1000.zip](https://github.com/ihhub/fheroes2/files/7090615/Top.hero.sprite.cut.1000.zip)

Version 0.9.6 4111

**Comment by LeHerosInconnu** [comment]
In fheroes2, the mountain sprite is displayed over the top of the hero sprite.

In fheroes2:

![Top AI hero sprite cut 02](https://user-images.githubusercontent.com/43583994/132981539-c4d56db3-330d-4fa1-b086-198f5a77e70a.png)

Here is the save file (0.9.7 4180):
[Top AI hero sprite cut 1002.zip](https://github.com/ihhub/fheroes2/files/7149300/Top.AI.hero.sprite.cut.1002.zip)
