### ISSUE TITLE
Can't pickup ore 

### ISSUE THREAD

**Issue by felix642** [ihhub/fheroes2#3763]
In fheroes 2 I stumbled upon an unpickable ore.

![Screenshot from 2021-06-27 11-00-09](https://user-images.githubusercontent.com/60141446/123549638-db754180-d737-11eb-8553-7d6c8b824638.png)
![Screenshot from 2021-06-27 11-10-21](https://user-images.githubusercontent.com/60141446/123549744-4b83c780-d738-11eb-97dd-2cc4af4e665f.png)

Here's the save file: 
[unpickable_ore.zip](https://github.com/ihhub/fheroes2/files/6721786/unpickable_ore.zip)

**Comment by ihhub** [comment]
Hi @felix642 , could you please tell which map did you play?

**Comment by ihhub** [comment]
Never mind. I found :)
