### ISSUE TITLE
Campaign savefiles can be seen in a list, while saving a standard game

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#3770]
Autosave and some other campaign savefiles are in the list.
![image](https://user-images.githubusercontent.com/55348946/123644052-b236dd00-d82d-11eb-89dc-fdb289eeefa4.png)

**Comment by oleg-derevenetz** [comment]
Interesting. I cannot see campaign savefiles in file list when saving a single-player game. @Branikolog is it possible to get an archive with the contents of the files/save directory?

**Comment by Branikolog** [comment]
Hello, @oleg-derevenetz !
Here's a "save" folder I have on my machine.
[save.zip](https://github.com/ihhub/fheroes2/files/6731810/save.zip)
It seems, that game shows not all campaign saves (Some of them could be rather old.) But campaign autosave is definitely recently created. Today I checked a fresh release, and couldn't see autosave of campaign game. Even after I created a new campaign and skipped turn. But when I've loaded campaign from a savefile and skipped turn - Autosave became visible while saving in a single scenario game again.
![image](https://user-images.githubusercontent.com/55348946/123764210-4015d500-d8cd-11eb-8741-8f9f64e10a80.png)

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog I just tried different steps, but still not able to reproduce :(

> But when I've loaded campaign from a savefile and skipped turn - Autosave became visible while saving in a single scenario game again.

That's what I tried:

* Started the game;
* Loaded "Campaign save" campaign savefile;
* Skipped a turn;
* Started a new single-player game on the "Alteris" map;
* Pressed the "Save Game" button.

No luck. That's what I also tried:

* Started the game;
* Loaded campaign game from AUTOSAVE;
* Skipped a turn;
* Loaded a single-player game from the "0101" savefile;
* Skipped a turn;
* Pressed the "Save Game" button.

No luck again... Could you describe in more detail the list of actions that leads to such an effect (including details like exact map names, whether you are using hotkeys or not, etc)?

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz 
Try this:
Load any campaign save file. Skip turn (To make sure fresh autosave file was created) Then Press "New Game". In main menu you should cancel new game menu and press load game and load 0101 save file. Then check list in "Save game" window: "autosave.savc" should appear there.
Between, Have you downloaded and unpacked zip archive of all my save files? There're lots of campaign save files in a list. Even without this "magic" tricks with save\load.
![image](https://user-images.githubusercontent.com/55348946/124123046-78f5ab80-da7f-11eb-8d0b-96ee07769898.png)

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog

> Between, Have you downloaded and unpacked zip archive of all my save files?

Yes, but I wasn't able to see the campaign savefiles in the list. I'll try one again tonight.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
That's strange. Regarding autosave - it is not always visible, but I managed to make it appear accidentally (Using secret algorithm from the post above :-) ) 
But a pack of savefiles is always visible with ".savc" in the list....

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog no wonder I wasn't able to reproduce it - it's a Windows-only issue :) Please check if the issue is gone with AppVeyor builds from #3782.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Many thanks for fixing this issue! :)
