### ISSUE TITLE
Sound problem while hero is moving on the adventure map

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#3772]
While hero is running or sailing we cannot hear any theme. After hero stops - music starts from the beginning.

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz.
Could you, please, take a look at this problem? You've recently worked on music, if I'm not mistaken.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog #3771 is intended to fix this :)

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Oh, sorry. Missed your PR in my mailbox.)
