### ISSUE TITLE
Installation guide is missing unpack GOG .exe file on macOS

### ISSUE THREAD

**Issue by Sajjon** [ihhub/fheroes2#3777]
Hello! I'm a huge HoMM fan and I'm a coder, on macOS Big Sur. 

I'm looking into starting the game, `make` runs successfully and when I start the app I see the very much _expected_ error regarding missing data files.

I just bought the [H2 Gold Edition on GOG](https://www.gog.com/game/heroes_of_might_and_magic_2_gold_edition), which offers only `.exe` files to download. In fact it offers two `.exe` files:
_setup_heroes_of_might_and_magic_2_gold_1.01_(2.1)_(33438).exe_
and
_setup_homm2_gold_win_2.0.0.7.exe_
GOG also offers downloading of sound files.

<img width="1210" alt="Screenshot 2021-07-01 at 09 44 26" src="https://user-images.githubusercontent.com/864410/124086145-0f5ea880-da51-11eb-95d3-6742bcbac4fb.png">

[The installation guide](https://github.com/ihhub/fheroes2/blob/master/doc/INSTALL.md#macos) fails to mention how to extract the necessary game files though. How can I do that?

I really do hope there is a way for me to extract the game files from the .exe files..? I also have a Windows and an Ubuntu machine... must I extract the game files from my Windows machine?

**Comment by Sajjon** [comment]
@oleg-derevenetz thx! I realized my Windows machine is packed away in a box... is there any known macOS tool to extract the files from the exe file?

**Comment by oleg-derevenetz** [comment]
Hi @Sajjon You can try to run the installer using WINE, it should be available via MacPorts or Homebrew. You just need to run the installer, there is no need to run original game, I think that WINE should deal with it.

**Comment by Sajjon** [comment]
@oleg-derevenetz right, I saw [Devilution referring to using Wine in their guide](https://github.com/diasurgical/devilution/blob/master/docs/INSTALL_mac.md), I might create a Pull Request if I'm successful. 

Would be nice to have this as part of installation guide, especially since GOG is listed as recommended source for game files. 

If PRs are welcome that is? ;)

**Comment by oleg-derevenetz** [comment]
@Sajjon yes, of course.

**Comment by jdm** [comment]
I used PortingKit to install the GoG version then copied the files from the installed location.

**Comment by Sajjon** [comment]
I can confirm that [wine-crossover](https://github.com/Gcenx/homebrew-wine) worked to extract the game files. Running on Intel mac with Big Sur.

wine32 does no longer work in macOS since Catalina and wine64 didn’t work because…
I don’t know really… but installing the wine-crossover via brew was simple enough, just had to uninstall wine stable (wine64) first.

N.B. the command was `wine` and not `wine64` followed by setup.homm2.exe or whatever the name was 😊

**Comment by Sajjon** [comment]
Might fix PR later, closing this issue now.
