### ISSUE TITLE
Can't win game

### ISSUE THREAD

**Issue by felix642** [ihhub/fheroes2#3787]
While testing a 2 players game, I've encountered a weird bug where I can't win a game. The victory condition is : "Defeat all enemies and castles". But even after defeating everyone the game continues.

Here's the save file: 
[CANT WIN.zip](https://github.com/ihhub/fheroes2/files/6757660/CANT.WIN.zip)
The map was "for honor".

I might simply be missing something but I can't find what.

**Comment by oleg-derevenetz** [comment]
Currently, in a multiplayer games, the game ends only when either all human players are vanquished or there is just one active human player left. No other logic (allies, some special win/loss conditions) are applied.
