### ISSUE TITLE
"Dismiss hero" status message for unhired hero

### ISSUE THREAD

**Issue by vasilenkoalexey** [ihhub/fheroes2#379]
![screenshot](https://user-images.githubusercontent.com/24250224/75285541-df354300-5827-11ea-9aef-26362d4e3880.png)
There are "Dismiss hero" status message for unhired hero when cursor over hidden dismiss button.

**Comment by werfu** [comment]
I cannot reproduce, but dismissing a hero crash in Interface::ListBox::SetCurrentVisible (interface_list.h line 228) caused by a vector iterator seeking out of bound.
