### ISSUE TITLE
Wizard's Isle: Scenario 3 - wrong artifact

### ISSUE THREAD

**Issue by johndc** [ihhub/fheroes2#3801]
Hi all,

goal of the 3rd scenario is to gain the artifact 'Orb of negation'. In actual map player gets 'Ultimate Shied'. As result the scenario is not won and player is stuck in progress.

Save game attached, hero Mandigal stands on location of artifact. 
[Good_1_0038.zip](https://github.com/ihhub/fheroes2/files/6760704/Good_1_0038.zip)

**Comment by PracticalMetal** [comment]
Hi, I would like to work on this issue, can you suggest me ways to get started?

**Comment by ihhub** [comment]
Hi @PracticalMetal , please search all usages of `OBTAIN_ULTIMATE_CROWN` in the code and implement it in the same way. If I'm correct we have to replace Ulitmate Artifact being digged by a certain one.

**Comment by PracticalMetal** [comment]
Can you tell me how I can reproduce this issue?

**Comment by ihhub** [comment]
You have to download the attached save and dig the artifact, check if it's not what excepted by the scenario, restart the scenario with your changes and play it again. You can easily modify any value in the game while debugging it allowing you to complete the game with less efforts.

To verify your changes you can compare it running the original game.
