### ISSUE TITLE
Evil Campaign 10 can't reach last castle

### ISSUE THREAD

**Issue by felix642** [ihhub/fheroes2#3802]
With #3756 I noticed that we can no longer reach the enemy's castle.

https://user-images.githubusercontent.com/60141446/124408782-fa19a080-dd14-11eb-9996-10cbc7276601.mp4

[passability.zip](https://github.com/ihhub/fheroes2/files/6761151/passability.zip)

**Comment by ihhub** [comment]
Hi @felix642 , are you testing on new game (without loading an old save)?
