### ISSUE TITLE
Campaign data doesn't get translated.

### ISSUE THREAD

**Issue by dimag0g** [ihhub/fheroes2#3807]
There is an issue with `campaign_data.cpp`: it defines campaign scenario names and descriptions as translated strings with the file scope. As a result, `gettext` calls translating these strings happen before `main`, and therefore they are always translated from English to English.

I managed to fix this with additional `gettext` calls inside `getXXXCampaignData` methods: these are run when the target locale is already available. Notably, my fix keeps original `gettext` calls intact, otherwise string literals won't be exported to `fheroes2.pot`. I can open a PR with the change I did, but will be happy to implement a better fix if someone has an idea.

https://github.com/dimag0g/fheroes2/commit/ea068afdd2e7ee406139ded883dafcef43b31166

**Comment by dimag0g** [comment]
@undef21 Perhaps you could review/test this? I have seen you worked on Russian locale support before.

**Comment by undef21** [comment]
Hello @dimag0g.  I'll try to fix Buka localization bit later.

**Comment by ihhub** [comment]
Fixed in #3820.
