### ISSUE TITLE
Combat, functioning with only creatures resurrected with the Resurrect spell (not Resurrect True) in the hero's army at the end of a combat

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3812]
If at the end of a combat only creatures resurrected with the Resurrect spell (not Resurrect True) (partially or entirely and all creatures in the troop are considered "temporary") remain in the hero's army, then one creature of the troop should be conserved.
If there are several troops resurrected with the Resurrect spell (not Resurrect True) then one creature of the most powerful troop should be conserved.
(Test with the English Gold version, the strongest creature is conserved at the end of the combat (one Steel Golem, with a troop of Peasants and a troop of Steel Golems).)

Related issue: https://github.com/ihhub/fheroes2/issues/3786.

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu let's check again if I understood everything correctly:

> If at the end of a combat only creatures resurrected with the Resurrect spell (not Resurrect True) (partially or entirely and all creatures in the troop are considered "temporary") remain in the hero's army, then one creature of the troop should be conserved.

This should be done IF (AND ONLY IF) there is at least one creature left from the original army. Suppose we have 2 stacks: 10 Peasants and 10 Archers. If both stacks was completely killed and then partially or entirely resurrected, then it shouldn't be done and hero should lose. However, if only 9 Peasants and 10 Archers were killed and then all of them resurrected, then we should have 1 Peasant and 1 Archer in the army, right? 1 Peasant - because it left from the original army and 1 Archer - because it was restored due to this logic?

> If there are several troops resurrected with the Resurrect spell (not Resurrect True) then one creature of the most powerful troop should be conserved.

By "most powerful troop" do you mean most powerful creature or most powerful stack? Because 1000 Peasants are more powerful than 1 Black Dragon for example...

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

Let's explain with some examples:

The hero's army is composed of a troop of 10 Peasants.
4 Peasants are decimated and resurrected.
At the end of the combat, the hero conserves 6 Peasants.

The hero's army is composed of a troop of 10 Peasants.
The hero summons Elementals.
The 10 Peasants are decimated then resurrected.
The Elementals are decimated (or not).
At the end of the combat, the hero conserves 1 Peasant.

The hero's army is composed of a troop of 10 Peasants and a troop of 10 Steel Golems.
The 10 Peasants are decimated then resurrected.
The 10 Steel Golems are decimated (and not resurrected).
At the end of the combat, the hero conserves 1 Peasant.

The hero's army is composed of a troop of 10 Peasants and a troop of 10 Steel Golems.
The 10 Peasants are decimated and resurrected.
The 10 Steel Golems are decimated then resurrected.
At the end of the combat, the hero conserves 1 Steel Golem (one creature for only one troop and not for each troop).

All creatures resurrected by the Resurrection spell (not Resurrection True) are considered "temporary" and are removed at the end of the combat.

Also, using the Resurrection spell several times on the same troop "adds up" the temporary creatures.
The creatures decimated first during an attack are the ones that are really "alive" (not the ones considered "temporary").

Example:

The hero's army is composed of a troop of 10 Peasants.
4 Peasants are decimated then resurrected.
4 Peasants are decimated then resurrected.
At the end of the combat, the hero conserves 2 Peasants.

> By "most powerful troop" do you mean most powerful creature or most powerful stack? Because 1000 Peasants are more powerful than 1 Black Dragon for example...

It is one of the most powerful creature that is conserved (in relation to the power of each creature individually, not in relation to the power of all the creatures in the different troops).

Zom attacks Vatawna.
Vatawna decimates Titan (total 300 hit points) and Steel Golems (total 350 hit points) with Lightning Bolt.
Zom resurrects Titan and Steel Golems with Resurrect spell (not Resurrect True).
Grand Elves decimate Peasants.
Titan decimate Grand Elves and Zom wins combat.
After combat Titan is conserved in Zom's army.

Here is the save and test scenario files:
[Test multi resurrect 02.zip](https://github.com/ihhub/fheroes2/files/6772297/Test.multi.resurrect.02.zip)

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu

> The hero's army is composed of a troop of 10 Peasants.
> The hero summons Elementals.
> The 10 Peasants are decimated then resurrected.
> The Elementals are decimated (or not).
> At the end of the combat, the hero conserves 1 Peasant.

But we already know that it doesn't work this way. No Peasants are conserved in this case, we will get a "winner" hero with zero troops.

**Comment by vincent-grosbois** [comment]
We can also do what is done in Heroes 3 (I think) where even if you win the fight and you have not true resurected creatures, you simply lose your hero too. I think it at least prevents cheesing (and from the AI too)

Seems like the H3 version is supposed to be the "fixed" version and the H2 version seems more like a bug / incorrect gameplay thing they didn't think about fixing

**Comment by oleg-derevenetz** [comment]
@vincent-grosbois

> We can also do what is done in Heroes 3 (I think) where even if you win the fight and you have not true resurected creatures, you simply lose your hero too.

That's how I did in #3809. All these mechanics with "partial resurrection of temporary troops" looks dubious and confusing.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz and @vincent-grosbois.

> @LeHerosInconnu
> 
> > The hero's army is composed of a troop of 10 Peasants.
> > The hero summons Elementals.
> > The 10 Peasants are decimated then resurrected.
> > The Elementals are decimated (or not).
> > At the end of the combat, the hero conserves 1 Peasant.
> 
> But we already know that it doesn't work this way. No Peasants are conserved in this case, we will get a "winner" hero with zero troops.

I think it's a bug of the original game, because it's not possible otherwise to remove the last creature from the army of a hero.

> We can also do what is done in Heroes 3 (I think) where even if you win the fight and you have not true resurected creatures, you simply lose your hero too. I think it at least prevents cheesing (and from the AI too). Otherwise you can do the old strategy of summoning elementals and spamming spells / armageddon and always win with 1 peasant (or 1 sprite, it's faster unit) left
> 
> Seems like the H3 version is supposed to be the "fixed" version and the H2 version seems more like a bug / incorrect gameplay thing they didn't think about fixing

> @vincent-grosbois
> 
> > We can also do what is done in Heroes 3 (I think) where even if you win the fight and you have not true resurected creatures, you simply lose your hero too.
> 
> That's how I did in #3809. All these mechanics with "partial resurrection of temporary troops" looks dubious and confusing.

Maybe it's also a bug of the original game. :)

I personally agree that this is how it should work (the hero disappears from the adventure map if he doesn't have at least one "real" creature from his starting army).
It changes the way the original game works, so it should be asked for the opinion of other people in the team.

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu

> The hero's army is composed of a troop of 10 Peasants and a troop of 10 Steel Golems.
> The 10 Peasants are decimated and resurrected.
> The 10 Steel Golems are decimated then resurrected.
> At the end of the combat, the hero conserves 1 Steel Golem (one creature for only one troop and not for each troop).

I just tested this variant, and it doesn't work in this way either! I got a hero with 5 Peasants and 5 Steel Golems, spammed the Fire Elemental, killed Peasants and Golems and resurrected them using Resurrect, and got... hero without army once again. No Peasants or Golems are conserved. I starting to think that this "conservation" is a bug itself, because I don't see any logic.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> @LeHerosInconnu
> 
> > The hero's army is composed of a troop of 10 Peasants and a troop of 10 Steel Golems.
> > The 10 Peasants are decimated and resurrected.
> > The 10 Steel Golems are decimated then resurrected.
> > At the end of the combat, the hero conserves 1 Steel Golem (one creature for only one troop and not for each troop).
> 
> I just tested this variant, and it doesn't work in this way either! I got a hero with 5 Peasants and 5 Steel Golems, spammed the Fire Elemental, killed Peasants and Golems and resurrected them using Resurrect, and got... hero without army once again. No Peasants or Golems are conserved. I starting to think that this "conservation" is a bug itself, because I don't see any logic.

In this case, there is no invocation of Elementals. :)
I just checked and that is what happens.

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu

> In this case, there is no invocation of Elementals. :)

So it seems that there is no clear rules and all this behavior with "conservation" of temporary resurrected units is highly dubious.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

As I wrote above I agree with a simpler operation.
Let's wait to see the opinion of the other team members.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub @Branikolog @idshibanov what do you think regarding this?

**Comment by Branikolog** [comment]
Hi all.
One one hand, providing a player at least one creature, after the battle is over is not fair a bit. As this creature could happen to be a strong one, like Titan. And this could be abused in some cases... On the other hand, I don't want to watch a hero on a world map with a completely empty army, which is contrary to the game mechanics.... So, I think, hero should vanish, if he left only not true resurrected creatures in his army... 
Wasn't able to save at least one "alive" creature? Bye-bye then. )

**Comment by oleg-derevenetz** [comment]
> Wasn't able to save at least one "alive" creature? Bye-bye then. )

Agreed. As @vincent-grosbois already said, all this "partial saving of temporary resurrected creatures" looks like a some sort of incorrect gameplay, may be even accidentally introduced (and subsequently fixed in H3). It doesn't work in all cases, it is not completely clear how exactly it works, I even wasn't able to find any sort of "official" description for this mechanics anywhere, only empirical observations.

**Comment by oleg-derevenetz** [comment]
Closing this because this issue due to #3809
