### ISSUE TITLE
Good_2 campaign passability bug

### ISSUE THREAD

**Issue by olegbl** [ihhub/fheroes2#3814]
Upon starting the second scenario of the original good campaign, the hero is stuck in the castle.

It's possible to move to three three tiles outside of the castle shown here, but no further. Reproduces with all 3 possible starting castles.

![image](https://user-images.githubusercontent.com/516977/124685553-55b76b80-de86-11eb-86c0-295d94636d60.png)

Version 0.9.5.

**Comment by ihhub** [comment]
Hi @olegbl , thank you for reporting this. We already have a fix and soon it will be approved.

**Comment by ihhub** [comment]
Hi @olegbl , you can download latest commit build from (here)[https://github.com/ihhub/fheroes2/blob/master/docs/INSTALL.md] and just restart this campaign scenario.

**Comment by olegbl** [comment]
Thanks for the quick fix!
