### ISSUE TITLE
Monsters don't cast spells anymore

### ISSUE THREAD

**Issue by vincent-grosbois** [ihhub/fheroes2#3821]
For instance, Mummies should be able to cast curse randomly.
This doesn't seem to be the case anymore

**Comment by oleg-derevenetz** [comment]
That's because `MonsterAbility`'s `operator<()` compares values using both `type` and `value`, so `std::set::find()` in `Battle::Unit::GetSpellMagic()` is unable to find an ability using just a `type` (e.g. `MonsterAbilityType::SPELL_CASTER` and zero `value`).

**Comment by vincent-grosbois** [comment]
I know, I discovered this by reading the code ;)
I don't know what was the intent with MonsterAbility being stored in a set, and with the comparator being incomplete, and with calling find on another instance . You can't really do all of them at once with this syntax.

IMO the simplest fix would be:
- get rid of storing MonsterAbility in set and put it in vector, because set brings no value ( look-up in set is probably slower than in vector given the layout and the fact we have 6 items max)
- Actually query things using std::find_if instead of std::find. Ideally we assert of throw when the find_if retrieved more than 1 ability (eg monster that has 2 spell caster abilities, not supported yet)
- Ideally, we should rather call instance methods from MonsterAbility instead of querying the public data

All in all it comes from the fact that type-safety for MonsterAbility is not enforced, because it's kind of a variant that is encoded through the enum value + the payload of 2 integers. That's exactly the thing I wanted to avoid with https://github.com/ihhub/fheroes2/issues/3808 ;)

**Comment by oleg-derevenetz** [comment]
@vincent-grosbois

> All in all it comes from the fact that type-safety for MonsterAbility is not enforced, because it's kind of a variant that is encoded through the enum value + the payload of 2 integers, whose meaning depends on the type. That's exactly the thing I wanted to avoid with #3808 ;)

Yes, #3808 looks somewhat more convenient, because it returns different types depending on artifact effect type (the logic in the caller code becomes more transparent, no implementation details stick out), it's like `std::variant` from C++17. BTW `std::variant` always throws an exception when you try to get the wrong type, it's somewhat safer then just an `assert()` which is usually removed in release build.

**Comment by vincent-grosbois** [comment]
We could throw too instead of assert but i dont think it's ever done in the codebase ;)

Envoyé de mon iPhone

**Comment by ihhub** [comment]
@vincent-grosbois  and @oleg-derevenetz , we cannot use C++17 for now and exception handling is not implementated in the code properly. The application will just close on any exception.

**Comment by oleg-derevenetz** [comment]
> The application will just close on any exception.

And it's a good thing. It's much better than UB. Or just call s`std::terminate()` in release builds (in addition to `assert()`).

**Comment by ihhub** [comment]
We should never close the application because of an exception. It's better to have incorrect game logic rather than a crash as users never like them.

**Comment by vincent-grosbois** [comment]
> > The application will just close on any exception.
> 
> And it's a good thing. It's much better than UB. Or just call s`std::terminate()` in release builds (in addition to `assert()`).

My initial point was that maybe we don't need to do these extra checks on release build (for speed mostly, even though it doesn't really matter), but just on debug builds (not sure if non-coders who test the game and report issues here are using debug or release build though).

But it opens up the question of how we want to handle faulty game logic that is triggered by incorrect data in the parts that could be changed by modders (eg changing ability infos)

**Comment by ihhub** [comment]
In the future new monsters might have more than 1 spell caster ability so we can't make such assumption.

I'm okay to use std::vector over std:: set as the last one was for removal of identical abilities. The idea behind MonsterAbility was to keep the structure clean and simple as a storage only while moving the logic of handling the cases outside. In this case the solution is more scalable.

Changing even existing code by bad modders will lead to wrong game behavior :)

**Comment by ihhub** [comment]
Agree. There's no a golden solution to please developers and users :)
