### ISSUE TITLE
Incorrect experience from defeating towns without hero/captains quarters

### ISSUE THREAD

**Issue by saox** [ihhub/fheroes2#3833]
In the original HoMM2/HoMM3 defeating monsters in a town always yields 500 EXP + EXP equal to monster HP. In fheroes2 it gives only the monster HP.

**Comment by qarkai** [comment]
Does only attacking winner get this extra EXP or defending winner too?

**Comment by oleg-derevenetz** [comment]
@qarkai

> Does only attacking winner get this extra EXP or defending winner too?

Logically, defending winner should always get 500XP, because there is always a hero in attacking army. There is no way to attack a town or castle without a hero, so if castle defender wins, he should get additional 500XP because of that.

**Comment by qarkai** [comment]
@saox Does town (no walls) counts as castle?
