### ISSUE TITLE
How can I join the project

### ISSUE THREAD

**Issue by Killbrum** [ihhub/fheroes2#384]
Good time of the day
I'm an experienced C++ developer (mostly Windows dev). I can't tell that I'm able/will be able to contribute too much, but from time to time, I would be glad to look into and add some things. Could you tell me how I can join the project? Thank you

**Comment by ihhub** [comment]
Hi @Killbrum , thanks for expressing an interest to the project!

You can contribute to the project by picking any issues which are taken by anyone else. Fork the project. Make needed changes and create a pull request. The pull request will be reviewed and your changes would be merged into the master branch if they are approved.
