### ISSUE TITLE
AI: cache monster strength once per turn

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#3840]
Currently, AI evaluates reachable monster strength for every AI hero action. We waste CPU resources by recalculating these values. What we need to do is to calculate them only once per turn of an AI player and update it only if a hero fights monsters.

**Comment by vincent-grosbois** [comment]
does it really never change on the same turn though?

**Comment by ihhub** [comment]
No, unless monsters are attacked.

**Comment by ihhub** [comment]
Since this is performance optimization I'm moving this issue to 1.0 release.
