### ISSUE TITLE
Add missing Captain's Quarters part in Barbarian town as a separate image

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#3842]
If Barbarian town does not have built castle but contains Captain's Quarters it's visible that a part of the Quarters is missing. This is the issue in the original game assets. We would like to add missing portion of Quarters but creating an extra image which will be a part of fheroes2 assets. In other words we need to draw an image which will be attached to existing Quarters sprite making it as a completed building rather than truncated in the middle.

This is the task for artists but anyone is welcome to try. Once you're done with image creation either post it here or approach ihhub in [Discord](https://discord.com/invite/xF85vbZ) for assistance in converting image into readable by game format.

![image](https://user-images.githubusercontent.com/19829520/125474656-5b739c1c-0242-4f4e-9aa9-389a1b9e349f.png)

**Comment by cxong** [comment]
![image](https://user-images.githubusercontent.com/1083215/137441696-dcad3d49-cace-416a-a5d6-952bb520719d.png)
This is my interpretation of what the missing part should look like

**Comment by cxong** [comment]
![424C003B-6C2F-43BB-885D-964B62D24059 2](https://user-images.githubusercontent.com/1083215/137492489-3c8109b8-9e24-4c07-94f1-7b2936094c86.png)
![125474656-5b739c1c-0242-4f4e-9aa9-389a1b9e349f](https://user-images.githubusercontent.com/1083215/137492580-8ea0f38c-fa82-4ef6-8ac8-f7c95bfa8ea3.png)

**Comment by cxong** [comment]
[cq.bmp.zip](https://github.com/ihhub/fheroes2/files/7356616/cq.bmp.zip)
as bmp

**Comment by zenseii** [comment]
Hi, @cxong. We're currently doing some cleanup of the licenses of the project and we're going to start using the license [Creative Commons Attribution-ShareAlike 4.0 (CC-BY-SA 4.0) ](https://creativecommons.org/licenses/by-sa/4.0/deed.en) for artwork. We want to add this license to the `barbarian_castle_captain_quarter_left_side` that you contributed, and to do this we need your permission. Currently your artwork is licensed under GPL2.0. If you agree to adding the CC-BY-SA 4.0 license to the aforementioned work, then we would need that you explicitly state that you agree to this.

**Comment by cxong** [comment]
i agree

**Comment by zenseii** [comment]
Thank you, @cxong !
