### ISSUE TITLE
Map bug: Beltway - unpassible place

### ISSUE THREAD

**Issue by saox** [ihhub/fheroes2#3859]
![Uploading beltway.png…]()

**Comment by ihhub** [comment]
Hi @saox , you image wasn't been uploaded.

**Comment by saox** [comment]
![beltway](https://user-images.githubusercontent.com/3976222/126761631-de51aecb-b558-4519-8275-d53d61e3134c.png)

**Comment by gab** [comment]
I confirm that I ran into the same problem in 0.9.7
