### ISSUE TITLE
Remove assertions in Windows release builds

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#3862]
Currently all Windows release builds include assetions which lead to game crash on user's machine. We want to keep assertions only for debug build from now as we're closer to 1.0 release.

**Comment by shprotru** [comment]
Hi, @ihhub!
How to deal with `assert( 0 );`? Should lines [like this](https://github.com/ihhub/fheroes2/blob/05d8fada6ed7cd9f0200c8338275a704f21f503b/src/engine/pal.cpp#L203) be removed from project?
vscode patterns:
- search pattern:
`(\s*)assert(.*\(.*)`
- replace pattern:
```
$1#ifndef _WIN32 or defined DEBUG
$1assert$2
$1#endif
```
is everything correct?

**Comment by oleg-derevenetz** [comment]
Hi @shprotru By "removing assertions" @ihhub means building with `-DNDEBUG` (or the corresponding setting for MSVC). There is no need to remove assertions from the code.

**Comment by vincent-grosbois** [comment]
@shprotru , regular asserts are no-op when NDEBUG symbol is defined. So it's enough to defined NDEBUG for the release windows builds in MSVC

Regarding static asserts, I think the point is to keep them as-is

**Comment by oleg-derevenetz** [comment]
In general, I'd wait with this until the project gets even closer to release - there are still many breaking changes, so users are in fact testers now :)

**Comment by ihhub** [comment]
@oleg-derevenetz , that's true but for builds except Windows we mute assertions. At least we can create a pull request but merge it when the time comes.

**Comment by ihhub** [comment]
> Hi, @oleg-derevenetz and @ihhub. Do we still intend to make this before the release?

I was about to comment it :) Assertions are extremely helpful to detect any issues and users found some in the past. However, only Windows users experience such as far as I remember. To be consistent we should make the logic for all platforms the same.

**Comment by oleg-derevenetz** [comment]
I'd still take my time with this :) We have the majority of users on the Windows platform and, as @ihhub already said, assertions are extremely helpful.

**Comment by ihhub** [comment]
I'm closing this issue as assertions help us to identify a lot of problematic places.
