### ISSUE TITLE
Battle against a hero passing in front of castle happens in the castle

### ISSUE THREAD

**Issue by Emericmeric** [ihhub/fheroes2#3865]
Happens in campaign Good_2, one of my heroes is in my castle, an AI hero is threatening to attack just 1 tile away.
I attack the enemy hero with another hero : the battle appears as if the enemy hero is defending my castle !

See saved game :
[Good_2_0027.zip](https://github.com/ihhub/fheroes2/files/6831015/Good_2_0027.zip)

**Comment by ihhub** [comment]
The problem lies in `, castle( world.GetCastle( Maps::GetPoint( index ) ) )` line in battle_arena.cpp file. `GetCastle()` returns true for all tiles where castle locates, not only for the main entrance which is wrong. We should fix the usage of this method.

**Comment by ihhub** [comment]
As a temporary hack we can check the type of tile object ID and it must be `MP2::OBJ_CASTLE`.
