### ISSUE TITLE
Can you increase the Chinese display?

### ISSUE THREAD

**Issue by yahooboby** [ihhub/fheroes2#3877]
Can you increase the Chinese display? Use fheroes2.pot to translate it into cn.mo and the game will be empty. No fonts are displayed. Thank you. This translation was translated by google. 
![1](https://user-images.githubusercontent.com/72782990/126444927-38ac4e65-6942-47da-8af6-5987ba215594.png)
![2](https://user-images.githubusercontent.com/72782990/126444933-31c41aa2-7698-4fad-8b2f-3c56367e6bd8.png)
cn.mo
[cn.zip](https://github.com/ihhub/fheroes2/files/6853408/cn.zip)

**Comment by yahooboby** [comment]
https://github.com/ciplogic/fheroes2enh

This can display Chinese, but it is not updated, and there are too many BUGs. . 
![3](https://user-images.githubusercontent.com/72782990/126445780-28df0b4b-758a-4654-88a9-9f054019abe6.png)

**Comment by ihhub** [comment]
Hi @yahooboby , another project has nothing to do with us. It support other languages using non-standard fonts. Our engine supports native font from the game to match exactly as it is in the original game.

To add a proper Chinese language support (I assume it's Mandarin) we need to know mapping of images from AGG files to chinese characters. I can build a special version of the game to scan all images and display them certain order. Then once all characters are known with your help we can do mapping to the language encoding.

**Comment by ihhub** [comment]
@yahooboby , also could you please tell where did you purchase such rare version of the game?

**Comment by yahooboby** [comment]
@ihhub 
This is the Chinese version of Heroes2.
I copied the old Chinese official Chinese heroes2.AGG and heroes2x.agg to English to overwrite it. This game is now in Chinese.

If you can understand Chinese, I will give you a Chinese heroes2 download link.
Download link: (all in Chinese)
https://dl.3dmgame.com/pc/16348.html

**Comment by ihhub** [comment]
Hi @yahooboby , we strictly against any piracy content so I removed the link you provided. What I asked is a link to official website where I can purchase the game.

**Comment by yahooboby** [comment]
This old Chinese game no longer has any Chinese official website in China.
The old games of 1996 have not been sold and no one is in charge.
Only GOG sells it, but it is in English, and there is no Chinese.

All are sorted out and published by Chinese game lovers themselves.
No charge, all free download to play.

**Comment by ihhub** [comment]
Hi @yahooboby , only Ubisoft has rights for game publishing. None of people can upload the game, even for me, as it is considered as a piracy which we strigtly prohibit.

Nevertheless, since you have Visual Studio 2019 could you please the size of `auto & imageArray = _icnVsSprite[id];` variable inside **agg_image.cpp** file at line 159? Just set the breakpoint on line 159 which is after the described line and check it.

**Comment by yahooboby** [comment]
![2](https://user-images.githubusercontent.com/72782990/126498820-d8449767-5093-4920-8992-a82bba2b8415.PNG)
![3](https://user-images.githubusercontent.com/72782990/126498842-271265d5-9d34-42f3-813b-d33bab054fe2.PNG)

I have just contacted vs2019, just started to learn, only know some simple copy programming.
I can't use many functions. .
The main reason is that I don't understand the meaning of English functions in Chinese.
Every time you learn a function, you have to go to Google to translate it, and you probably understand the meaning inside.

**Comment by yahooboby** [comment]
Also, we only translate English into Chinese.
Do not modify any procedures, keep the game original flavor.
They don't translate it into Chinese and sell it.

**Comment by ihhub** [comment]
Hi @yahooboby ,

many of our team members are not native English speakers but every (widely-used) programming language is based on English :) Being bilingual is never bad after all.

From the attached by you screenshot I can't see the array size. It should look like this:
![image](https://user-images.githubusercontent.com/19829520/126580861-8c11c2c9-bb57-4b22-8bf8-3fe893696233.png)

but it could be some settings in your Visual Studio. However, not to waste everyone's time could you please replace this code:
```cpp
                auto & imageArray = _icnVsSprite[id];
                if ( id == ICN::FONT ) {
                    // The original images contain an issue: image layer has value 50 which is '2' in UTF-8. We must correct these (only 3) places
                    for ( size_t i = 0; i < imageArray.size(); ++i ) {
                        ReplaceColorIdByTransformId( imageArray[i], 50, 2 );
                    }
                }
```
by this one
```cpp
                auto & imageArray = _icnVsSprite[id];
                const size_t imageCount = imageArray.size();
                if ( id == ICN::FONT ) {
                    // The original images contain an issue: image layer has value 50 which is '2' in UTF-8. We must correct these (only 3) places
                    for ( size_t i = 0; i < imageCount; ++i ) {
                        ReplaceColorIdByTransformId( imageArray[i], 50, 2 );
                    }
                }
```
and see the value of **imageCount**?

**Comment by yahooboby** [comment]
1:
![10](https://user-images.githubusercontent.com/72782990/126593730-27f7ff76-32fd-4990-b066-617da42d537b.PNG)
2:
![11](https://user-images.githubusercontent.com/72782990/126593742-7035f0ba-66ac-4c7e-a92e-85d2b2e0301c.PNG)
3:
![12](https://user-images.githubusercontent.com/72782990/126593748-6e5c5206-1cf5-46f1-8169-227231bffb11.PNG)

In order to do what you want. The result is the same as yours above.
But still no subtitles came out. It's still empty.

**Comment by ihhub** [comment]
From what I see the game itself has images for English alphabet as Mandarin contains around 10000 hieroglyphs. Your version of the game doesn't have a correct set of images for Chinese language, that's why you see nothing.
As of now we support only versions of the game with correct images for alphabets. We will add support for other languages but not right now.

**Comment by yahooboby** [comment]
All right. Thank you for your help.

**Comment by ihhub** [comment]
Closing this issue as it is the same as #2211 .
