### ISSUE TITLE
Status of "transcribe scrolls" and "teaching" skills

### ISSUE THREAD

**Issue by vincent-grosbois** [ihhub/fheroes2#3884]
Hello
in the codebase it seems that there is still "old code" about a few features that are activated through config
like :
- heroes teaching spells to each others
- transcribe scrolls to learn the spell

Can we clarify if these features are intended to be supported, or if we can remove them?
Or, if we can remove them, and re-introduce them properly in another release?

**Comment by oleg-derevenetz** [comment]
Hi @vincent-grosbois I believe that if they are currently not working (I have not tested them), they can be safely removed. However, if they work, it would be better to leave them (unless there are some big issues with the compatibility of these features and the new code).

**Comment by ihhub** [comment]
Closing this issue as experimental options were removed regarding this logic.
