### ISSUE TITLE
Suspicious conversion

### ISSUE THREAD

**Issue by qarkai** [ihhub/fheroes2#3890]
https://github.com/ihhub/fheroes2/blob/cea9150e74594f0dacc48cbe9531500eec33e7dd/src/engine/image.cpp#L816
This `AlphaBlit` overload expects `uint8_t alphaValue` as 9th argument but receives value of `bool flip`. Considering that `bool flip` is 10th parameter, `bool -> uint8_t` conversion looks suspicious. If that was intentional `flip` could be explicitly casted to `uint8_t` at least.

**Comment by qarkai** [comment]
Hi @oleg-derevenetz, this was found by clang-tidy's readability-implicit-bool-conversion check. Maybe it is worth to re-enable it with [ignore options](https://clang.llvm.org/extra/clang-tidy/checks/readability-implicit-bool-conversion.html#options).

**Comment by oleg-derevenetz** [comment]
> Hi this was found by clang-tidy's readability-implicit-bool-conversion check. Maybe it is worth to re-enable it with [ignore options](https://clang.llvm.org/extra/clang-tidy/checks/readability-implicit-bool-conversion.html#options).

I'm not sure really. On the one hand, sometimes it may catch something, on the other hand that's more of the "mixed up arguments" and a random coincidence. If two int arguments were mixed up instead, this check would have revealed nothing.
