### ISSUE TITLE
Remove move point and resource cost from spells

### ISSUE THREAD

**Issue by vincent-grosbois** [ihhub/fheroes2#3903]
Hello
it seems that in spells defintion and code, there is the possibility that each spells also costs either resources or move points.
I think it's unused
Can we remove it?

**Comment by oleg-derevenetz** [comment]
Hi @vincent-grosbois AFAIK only in H3 spells may consume movement points (for example, Dimension Door consumes them), but in H2 it seems to not be the case. However, I'm not an expert here. @Branikolog @LeHerosInconnu do you have any advice?

**Comment by ihhub** [comment]
Isn't Dimension Door eating move points as well as Town Gate? For example, function `bool HeroesTownGate( Heroes & hero, const Castle * castle )` has **hero.ApplyPenaltyMovement( townGatePenalty );**.

**Comment by LeHerosInconnu** [comment]
Hello everyone,

The penalty for using the spells "Dimension Door", "Town Gate" and "Town Portal" is 225 movement points.
The hero can nevertheless cast the spell if he has at least 1 movement point left (not 100 points for a horizontal or vertical movement point on the grass terrain for example, but really 1 point (0001)).

Related closed issue: https://github.com/ihhub/fheroes2/issues/1325.

**Comment by oleg-derevenetz** [comment]
> The hero can nevertheless cast the spell if he has at least 1 movement point left

Ah, that's why I decided that DD doesn't consume movement.

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> The hero can nevertheless cast the spell if he has at least 1 movement point left (not 100 points for a horizontal or vertical movement point on the grass terrain for example, but really 1 point (0001)).

In the original game, I was sure that the hero could teleport even if he couldn't move on the adventure map, but I was wrong about the minimum value of hero's movement points needed for that.
After some tests, it seems that the minimum value of movement points of the hero is as long as there is a yellow portion left in the hero's movement indicator.
The spell can be cast with 75 movement points that's for sure, but I don't know what is the minimum number of points for a yellow portion to be displayed in the hero's movement indicator, with 50 movement points there is no more yellow portion in the movement indicator and the hero can't cast a teleportation spell, between the two values, I don't know.
However, in the original game, if the hero has at least a yellow portion left in the hero's movement indicator and even if he can't move on the adventure map, he can still teleport.

In the example, in the original game, the hero has 175 movement points left.
He can't move on the desert terrain (he should have at least 200 movement points left), but he can teleport with the spells (Dimension Door, etc.).
Note also that the hero's movement bar is not empty, in the original game there is still a part of the movement indicator in yellow (so the player can notice that an action is still possible, here teleporting with a spell).
![Dimension Door spell check 003](https://user-images.githubusercontent.com/43583994/132092537-d910f0ad-b200-46b8-859d-deb338b44675.png)

In the same example, with fheroes2, the hero also has 175 movement points left.
However, the movement bar is empty and the hero cannot use a teleportation spell, although he should be able to do so.
![Dimension Door spell check 004](https://user-images.githubusercontent.com/43583994/132092515-f1223535-49bf-47d6-9e01-90554ce4365d.png)
![Dimension Door spell check 005](https://user-images.githubusercontent.com/43583994/132092521-3963b0dc-77cb-45d7-a030-e371820490cb.png)

Here is the test scenario:
[0 9956c.zip](https://github.com/ihhub/fheroes2/files/7109657/0.9956c.zip)

**Comment by ihhub** [comment]
Hi @vincent-grosbois , you're absolutely right about resource points and move points. Maybe we don't need to remove move points for now.

**Comment by ihhub** [comment]
Closing this issue since move points are needed and we removed resource usage.
