### ISSUE TITLE
Translation of plural forms is not working

### ISSUE THREAD

**Issue by dimag0g** [ihhub/fheroes2#3919]
The actual issue in the title is easily fixed by adding `-k_n:1,2`  to the Makefile (and writing translations for the new PO entries of course). I opened an issue because I'd like to discuss how plural forms should be handled in general. We only have very few "true" plural forms, e.g. `scouting increases the distance by 1/2/3 square(s)`. Those should be handled via `_n( )`. However, most strings fall in one of the two marginal cases:

1. The exact number is known, e.g. `a sawmill delivers two units of wood per day`. I understand it's tempting to encode `two` as `%{count}` so that the description is guaranteed to be consistent with the in-game value, and then `_n( )` with its `count` argument looks appropriate. However, using `_n( )` creates extra work for the translator, who is now prompted to provide several translations, **of which only one will be used**. Most languages will have only two plural forms (one/many), some will have 3 (zero/one/many, one/two/many, one/<5/5+ etc.), some languages will have [even more](https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html). I would therefore suggest we use `_( )` instead of `_n( )` in this case.

2. The exact number is one of two or three fixed plural values, e.g. `pathfinding reduces terrain penalty by 25/50/100%`. Technically, `_n( )` is warranted here, but in practice all three values which are actually used require the same plural form in all languages we have translations for, so `_( )` is sufficient. There might be exceptions I have overlooked, but IMO a better strategy would be to to use a single `_( )` by default, and only use `_n( )` when we actually discover such an exception.

**Comment by a1exsh** [comment]
The English "translations" seem to work properly, so I suppose this issue is only relevant for other languages only.

When I'm trying to change the language I see this message:
![image](https://user-images.githubusercontent.com/489601/135763269-9a69b8e3-7012-4bbd-a842-b079df855d6b.png)

How can I overcome it?  I guess the original resources are not used for translation, except for the Fonts, maybe, so I should be able to switch to, e.g. German?

**Comment by dimag0g** [comment]
@a1exsh You need HoMM2 data files in German in order to switch to German. The version is detected by comparing checksums of you data files with those of known data (GoG and some other versions).

German translation is not currently available at all AFAIK.

**Comment by a1exsh** [comment]
@dimag0g after going through two translations (Russian and German) I agree on both points you are raising here.  The placeholders are probably from an early version of the game that was configurable via external files, but this is not the case anymore (and good so, for the core functionality), so this only adds burden everywhere.

**Comment by dimag0g** [comment]
@a1exsh If you don't mind, I'd like to close this issue. The original problem (supporting translations with plural forms) is already solved, and some of the remaining issues with plural forms are discussed here: https://github.com/ihhub/fheroes2/issues/3929

The dependency of translations on game data (or the lack thereof) is really a separate topic.

**Comment by a1exsh** [comment]
OK, if you think it's better now, let's close this.
