### ISSUE TITLE
Unable to get to the next turn on Alteris

### ISSUE THREAD

**Issue by werfu** [ihhub/fheroes2#392]
Upon completion of the first turn on map Alteris, the engine crash during an AI combat.

At line 524 of file monster.cpp:

`u32 Monster::GetAttack( void ) const
{
    return monsters[id].attack;
}`

For an unknown reason the id is way out of bound and cause an invalid pointer exception.

Happens with both 32bit and 64bit, and both SDL version, VS2017.

**Comment by ihhub** [comment]
Hi @werfu I've created a pull request for this and other crashes. The reason was pretty simple: wrong type of casting.
