### ISSUE TITLE
Unpassable cells in Roland campaign, map 2

### ISSUE THREAD

**Issue by AAS** [ihhub/fheroes2#3926]
Hero can not move on the road to loot resources.

![image](https://user-images.githubusercontent.com/179733/127523474-0ee09533-a72b-4d5c-924c-25f200b66a3b.png)
[bug.zip](https://github.com/ihhub/fheroes2/files/6901828/bug.zip)

**Comment by oleg-derevenetz** [comment]
Looks like a duplicate of #3814. @AAS did you tried to install the latest snapshot?

**Comment by AAS** [comment]
@oleg-derevenetz 
Where can I download it?

**Comment by oleg-derevenetz** [comment]
@AAS https://ihhub.github.io/fheroes2/INSTALL.html#snapshots

**Comment by AAS** [comment]
@oleg-derevenetz Well, snapshot sections links exactly to https://github.com/ihhub/fheroes2/releases/tag/fheroes2-windows-x64-SDL2

Answering your question, yes I tried.

**Comment by oleg-derevenetz** [comment]
@AAS

> Answering your question, yes I tried.

What exactly you tried? You need to restart this mission, because the save file is already broken. I just tried the latest snapshot (0.9.5.9318) and everything seems to work:

![Good_2](https://user-images.githubusercontent.com/32623900/127533471-fce9e81a-99f0-4dc4-a25d-a716651be271.jpg)

**Comment by AAS** [comment]
@oleg-derevenetz Tried to load saved game in snapshot version, and got same result. I didn't knew that saved game info affects cell's passability.

**Comment by oleg-derevenetz** [comment]
@AAS

> Tried to load saved game in snapshot version, and got same result. I didn't knew that saved game info affects cell's passability.

Yes, it does. The save file contains all the passability info and may be played even without the original map itself. Is this issue still observed on the latest snapshot after restart?

**Comment by AAS** [comment]
@oleg-derevenetz The bug is fixed after level restart in a snapshot build.
