### ISSUE TITLE
Monster::GetPluralName is broken

### ISSUE THREAD

**Issue by dimag0g** [ihhub/fheroes2#3929]
There is a problem with `Monster::GetPluralName` for which I don't see a good fix. Right now it uses `_n( )` which is incompatible with `Monster::GetName` and `Monster::GetMultiName` which use `_( )`. It works for most of the monsters where singular and plural forms are next to each other in the `.mo` file, but e.g. for `Goblin/Goblins` there will be `Goblin Hut` in between, so we'll end up with "Goblins" translated as "Goblin Hut" by  `_n( )`. We need to either use `_( )` everywhere and hard-code the plural form logic in `Monster::GetPluralName`, or use `_n( )` everywhere.

However, fixing this issue completely with just `_n( )` will not be possible for languages like Russian, where "monsters" and "5 monsters" have [different](https://translate.google.com/?sl=en&tl=ru&text=monsters%0A5%20monsters&op=translate) forms (the latter is Genitive case). I'm not familiar with Polish, but I expect a similar problem there as well.

One solution would be to use the singular form everywhere except for troop quantities (`5 goblins`/`several goblins`), like the original HoMM2 version does. This avoids the problem in Russian there it simply says "goblin" on e.g. troop info pages, regardless of how many goblins you have:
![homm2_ru](https://user-images.githubusercontent.com/10945319/127575329-adc01284-10d3-4e29-b5eb-f067775e58a4.png)

Another solution is to use the form `goblins (5)` / `goblins (several)` for troop quantities, like the Polish version does, though it doesn't sound very natural:
![homm2_pl](https://user-images.githubusercontent.com/10945319/127576396-8562d3a6-688f-4fed-9855-401899cef028.png)

**Comment by AAS** [comment]
Hello.
Isn't it already handled by gettext and .po with a header like:

```"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n"```

and string should be like:

```
msgid "{:d} Goblin"
msgid_plural "{:d} Goblins"
msgstr[0] "{:d} гоблин"
msgstr[1] "{:d} гоблина"
msgstr[2] "{:d} гоблинов"
```

**Comment by dimag0g** [comment]
@AAS This will only handle cases like `recruit/dismiss 5 Goblins?`. I'm not sure we actually have those.

What we have is:
- `a few Goblins` -> note that `a few` requires a plural form which is different from `1` or `2`, even if `few` actually means 1 or 2. You'll need a `n > 4` plural form here.
- `the Hut produces Goblins`, `attack Goblins`, etc. -> in Russian French and German, these can be translated with a form that corresponds to `n > 4` plural form, not sure about other languages.
- Just `Goblins`, as on the troop info page -> in Russian, **none** of the plural forms would work. The original game simply uses a singular form.

**Comment by dimag0g** [comment]
I'm closing this for now, feel free to comment and reopen if you think you have a better idea on this matter.
