### ISSUE TITLE
Wizards campaign mission 2 - can't move to the left over trees 

### ISSUE THREAD

**Issue by enk37** [ihhub/fheroes2#3948]
See screenshot below, this is the latest build:
<img width="1024" alt="Screenshot 2021-08-02 at 09 22 32" src="https://user-images.githubusercontent.com/28488706/127813491-3246aca9-955c-4251-86d5-7d9b220562b5.png">
[Wizards_2_0001.savc.zip](https://github.com/ihhub/fheroes2/files/6914779/Wizards_2_0001.savc.zip)

**Comment by saox** [comment]
This one has been solved in the latest snapshot: https://github.com/ihhub/fheroes2/blob/master/docs/INSTALL.md

**Comment by enk37** [comment]
Seems latest snapshot for MacOS is outdated, I donloaded it here today: https://github.com/ihhub/fheroes2/releases/latest/download/fheroes2_macos10_15_sdl2.zip
but binary within archive is from 4th July according to ctime.

**Comment by oleg-derevenetz** [comment]
Hi @enk37 That's not the latest snapshot, that's the latest release version. The latest snapshot is here:

https://github.com/ihhub/fheroes2/releases/tag/fheroes2-osx-sdl2_dev

All links to the latest snapshots are available here:

https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds

**Comment by ihhub** [comment]
Closing this issue as this isn't reproducible anymore on the latest build.
