### ISSUE TITLE
Ground Zero - impassable object

### ISSUE THREAD

**Issue by saox** [ihhub/fheroes2#3949]
Original:

![orig_1](https://user-images.githubusercontent.com/3976222/127822054-7c1a80cd-5627-46d7-aade-6f43097f894d.png)

FHeroes2:
![fheroes2](https://user-images.githubusercontent.com/3976222/127822098-94a01b5a-a118-4ee6-8cec-b79944e84a98.png)

The map is "Ground Zero"

**Comment by saox** [comment]
FYI: I am using the latest snapshot. Just fel like reporting this here so we can track in what situations we see this issue.

**Comment by vincent-grosbois** [comment]
@saox what map is it?

**Comment by saox** [comment]
@vincent-grosbois "Ground Zero". Will add to the title.

**Comment by ihhub** [comment]
Looks like trees don't block ther passage for upper objects. We need to check this theory.

**Comment by Branikolog** [comment]
@ihhub 
Seems so.
"Decisions" map, OG:
![image](https://user-images.githubusercontent.com/55348946/128477272-853a2a99-4314-411b-b550-a7a95df5c62a.png)
fheroes2:
![image](https://user-images.githubusercontent.com/55348946/128478851-f68836d6-2a84-4c1a-9a28-9ebcf9d6da89.png)
