### ISSUE TITLE
Adventure map, music, playing while AI turn, plays from the beginning each time new AI starts his turn

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#3974]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

While playing with allies, each time new ally starts his turn, "end turn" theme plays from the beginning.

### Save file

It is obvious, while playing "Fortress Isle" map.
[Music loop.zip](https://github.com/ihhub/fheroes2/files/6938803/Music.loop.zip)

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , could you please take a look at this issue?
