### ISSUE TITLE
Adventure map, boat's shadow changes after hero embarks

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#3978]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Something is wrong with boat's shadow.
![image](https://user-images.githubusercontent.com/55348946/128422424-11758ffe-2a22-458d-aa34-a0840101fb96.png)
![image](https://user-images.githubusercontent.com/55348946/128422481-ac8ff4b5-0d08-4aa6-b06c-213865bb6529.png)

### Save file

[Whirlpool.zip](https://github.com/ihhub/fheroes2/files/6941729/Whirlpool.zip)

**Comment by Branikolog** [comment]
![image](https://user-images.githubusercontent.com/55348946/131500773-abea48eb-c556-48ba-af5e-d7c2a21133f3.png)

**Comment by ihhub** [comment]
Fixed in #5692
