### ISSUE TITLE
Random artifact is same as quest goal.

### ISSUE THREAD

**Issue by undef21** [ihhub/fheroes2#3999]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

Random artifact from grave is same as artifact in victory condition. In that case we get fast victory.

### Save file

[bug2.zip](https://github.com/ihhub/fheroes2/files/6964177/bug2.zip)

Search the grave for fast victory.

**Comment by oleg-derevenetz** [comment]
Haha funny bug :)
