### ISSUE TITLE
Remove sub-revision of application

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#40]
Right now we show that the version of the application is **0.6.000**. While last **000** comes from SVN revision which is no longer the case. We should remove it.

**Comment by hiteshpr** [comment]
Can I work on this?

**Comment by ihhub** [comment]
@hiteshpr , yes, you can!

**Comment by andrey-starodubtsev** [comment]
I removed aforementioned last component of the version, but maybe we should add git hash instead?
