### ISSUE TITLE
Where can I find an updated fheroes2.cfg?

### ISSUE THREAD

**Issue by vanfanel** [ihhub/fheroes2#4005]
### Your question

Hello there!

I know there have been some options you recently added, like the one to skip the animated intro, etc. 
I had them on my fheroes2.cfg file, but I am building and installing in another computer and I can't find a reference to those new options or an example of an updated fheroes2.cfg "template". So where is it?

Thanks!

**Comment by oleg-derevenetz** [comment]
Hi @vanfanel you will need to run fheroes2 once, and it will create default `fheroes2.cfg` which can be used as a template. There is no "default" config file supplied with distribution.

**Comment by vanfanel** [comment]
@oleg-derevenetz Thanks, that clears it up!
BTW, what's the setting name for skipping the intro? I can't see it on the newly created cfg.

**Comment by oleg-derevenetz** [comment]
@vanfanel

```
# show game intro (splash screen and video): on/off
show game intro = on
```

At the very end of the generated config file.

**Comment by vanfanel** [comment]
@oleg-derevenetz Aaahh, ok! Thanks!
