### ISSUE TITLE
Castle Siege, Gates are drawn over a creature sprite

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4010]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

While opening, gates overlap creature standing nearby.
![image](https://user-images.githubusercontent.com/55348946/129446660-e64308bc-a442-4671-b4f8-e39dec81e18b.png)

### Save file

[Gates.zip](https://github.com/ihhub/fheroes2/files/6986480/Gates.zip)

**Comment by oleg-derevenetz** [comment]
Bang!

**Comment by ihhub** [comment]
It's a feature! Stealth mode inherited from the bridge.

**Comment by ihhub** [comment]
The problem is in `void Battle::Interface::RedrawBridgeAnimation( bool down )` method. We draw the bridge not as a part of the whole scene but after everything. The redraw logic of the bridge should be inside `RedrawPartialStart` (in subsequent function calls).
