### ISSUE TITLE
Holy Shout and Holy Word damages Battle Dwarves

### ISSUE THREAD

**Issue by saox** [ihhub/fheroes2#4019]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Both spells damage Battle Dwarves - units that are not considered to be undead.

### Save file

[battlewarf_holyshout.zip](https://github.com/ihhub/fheroes2/files/6988568/battlewarf_holyshout.zip)

**Comment by vincent-grosbois** [comment]
I wonder if it's not a bug with MonsterAbility type again, because normally the checks for which units are immune to holyshout etc is very old

**Comment by vincent-grosbois** [comment]
Ah no :) It's because for dwarves we return here : https://github.com/ihhub/fheroes2/blob/f1a372a902baaf6b0ac45eac3a7a15bb9eba66ee/src/fheroes2/monster/monster_info.cpp#L774 with a value of something like 50% chance resist, instead of the 100% resist
