### ISSUE TITLE
Combat during a siege, if the combat is restarted after the instant combat, the Captain has zero spell points

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4064]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, for a combat during a siege, if the combat is restarted after the instant combat, the Captain has zero spell points

In fheroes2:

![Bug restart siege spell points captain 001](https://user-images.githubusercontent.com/43583994/130361180-963f0805-d90e-4e2f-bc28-850347e89045.png)

![Bug restart siege spell points captain 002](https://user-images.githubusercontent.com/43583994/130361183-50e93b71-ade0-4df2-800d-739d54534d81.png)

End the turn.
Restart the siege combat (third combat).

### Save file

Here is the save file:
[Bug captain zero spell points_.zip](https://github.com/ihhub/fheroes2/files/7027653/Bug.captain.zero.spell.points_.zip)

### Additional info

Version 0.9.6 3976.

**Comment by ihhub** [comment]
And that's why our AI is weak!

**Comment by oleg-derevenetz** [comment]
> And that's why our AI is weak!

This issue related only to captains, heroes will currently get their mana back as it should.
