### ISSUE TITLE
Suggestion: merge commit history from original, SourceForge project

### ISSUE THREAD

**Issue by taeber** [ihhub/fheroes2#407]
I was able to merge the subversion history from the [original, SourceForge project](https://sourceforge.net/projects/fheroes2/). See my branch: https://github.com/taeber/fheroes2/tree/merged.

The benefit of doing so is to see who made what changes and when (and hopefully why, if they left a good commit message).

To do so, I used `git svn`:
```
$ git svn clone https://svn.code.sf.net/p/fheroes2/code/trunk fheroes2
```
This created a new git repository at `fheroes2`. I then used `git mv` to move the code to their new locations (for example, `fh2editor` -> `editor`).

After [committing that](https://github.com/taeber/fheroes2/commit/b488e4aa13ae6c2852ba32ed90184a0f51935732), I added the new GitHub repository as a remote:
```
$ git remote add github https://github.com/ihhub/fheroes2
$ git checkout -b merged ihhub/master
$ git rebase --interactive master
```
There were two or three conflicts related to the `README.md` file, but I was easily able to resolve them and `git rebase --continue`.

Now, I have the entire commit history from both SourceForge and GitHub.

Unfortunately, I'm unable to make a pull request, because technically the histories are "unrelated". I recommend that you (@ihhub) repeat this process and replace your `master` with the merged result as it preserves the histories.

**Comment by ihhub** [comment]
Hi @taeber ,
this is a great idea. I would come back to it at the end of the week since we are planning to make 0.7 version release so I am preparing all needed changes for it right now :)

**Comment by ihhub** [comment]
Hi @taeber ,
uh-oh, `git svn clone` command takes ages, I've started it now it after half an hour I hit only revision 150. I'll try it tomorrow morning :)

**Comment by ihhub** [comment]
Hi @taeber , it's done - https://github.com/ihhub/fheroes2/tree/merged. I'll merge it very soon. Thanks a lot for your suggestion!

**Comment by ihhub** [comment]
Oops. I did something wrong...

**Comment by ihhub** [comment]
Hi @taeber ,
what did you do exactly after rebasing? git push?

**Comment by taeber** [comment]
Hmm... it doesn't look like your rebase worked as it rolled all 180+ changes committed to GitHub into a single commit.

I was able to get the histories merged in my [`master`](https://github.com/taeber/fheroes2/) branch. You see how there are 3649 commits?

Here's what I typed:
```bash
$ git svn clone https://svn.code.sf.net/p/fheroes2/code/trunk fheroes2-sf
$ cd fheroes2-sf
$ git mv fh2editor/ fheroes2/editor
$ rmdir fheroes2/data/ fheroes2/maps/
$ git mv fheroes2/* ./
$ git commit -m "Move files to match github.com/ihhub/fheroes2"
$ git remote add github https://github.com/ihhub/fheroes2
$ git fetch github
$ git checkout -b merged github/master
$ git rebase --interactive master
```
At this point a file opens in your editor so that you can pick which commits to include. I just save and close it. In retrospect, I could have probably run `git rebase master`.

Anyway, the output was:
```bash
CONFLICT (add/add): Merge conflict in LICENSE
Auto-merging LICENSE
error: could not apply 9b91146e... Initial commit
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 9b91146e... Initial commit
$ git status --short
AA LICENSE
A  README.md
```
There was only one conflict to deal with. I resolved it by deleting the original and leaving your GNU text.
```bash
$ edit LICENSE
$ git add LICENSE
$ git rebase --continue
$ git remote add taeber git@github.com:taeber/fheroes2
$ git push -u taeber merged:merged-better
```

Now, I was done with that temporary workspace. I went back to my original fheroes2 checkout.

```bash
$ cd ..
$ git clone git@github.com:taeber/fheroes2 fheroes2
$ cd fheroes2
$ git status --branch 
On branch master
Your branch is up to date with 'origin/master'.
...
$ git pull merged-better --allow-unrelated-histories
$ git push
```
I think you could do something similar—replacing `taeber` with `ihhub`—and it should work.

**Comment by taeber** [comment]
Although, maybe I'm thinking of this backwards. It looks like that doubled every GitHub commit.

Maybe we should rebase the GitHub commits to the original Subversion.

I'll try that approach and let you know.

**Comment by taeber** [comment]
@ihhub, here are the commands I think you should run. First, create a tag for the current `master`, so you can restore to it if the final `push` messes things up. Perhaps `before-svn-merge`. Then:

```bash
$ git svn clone https://svn.code.sf.net/p/fheroes2/code/trunk fheroes2-sf
$ cd fheroes2-sf
$ git mv fh2editor/ fheroes2/editor
$ rmdir fheroes2/data/ fheroes2/maps/
$ git mv fheroes2/* ./
$ git commit -m "Move files to match github.com/ihhub/fheroes2"
$ git remote add github git@github.com:ihhub/fheroes2
$ git fetch github
$ git checkout -b merged github/master
$ git rebase master
CONFLICT (add/add): Merge conflict in LICENSE
Auto-merging LICENSE
error: could not apply 9b91146e... Initial commit
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 9b91146e... Initial commit
$ git status --short
AA LICENSE
A  README.md
$ edit LICENSE  # Take your GPL changes
$ git add LICENSE
$ git rebase --continue
$ git push --force-with-lease github merged:master
```

I really hope it works like [it did for me](https://github.com/taeber/fheroes2/tree/master-copy). Good luck!

**Comment by ihhub** [comment]
Closing this issue as over time we realized that the original code has too many issues so it is not worth to even check the history :(
