### ISSUE TITLE
Escape key not working on options window

### ISSUE THREAD

**Issue by vincent-grosbois** [ihhub/fheroes2#4074]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

When opening all menus in game, you can exit them when pressing escape
All, except the option/config menu

### Save file

none

**Comment by oleg-derevenetz** [comment]
Hi @vincent-grosbois since this window has the "OKAY" button, you need to use Enter key, and not Escape. Enter button works just fine.
