### ISSUE TITLE
Castle: show building hotkey in status bar

### ISSUE THREAD

**Issue by a1exsh** [ihhub/fheroes2#4091]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

There are a number of hotkeys for the castle view, but I didn't know about them before I found `fheroes2.key` file.  It would be nice to show the currently assigned hotkey in the status bar when a building is hovered by the mouse.

### Describe the possible solution

How it can look (mockup):
![image](https://user-images.githubusercontent.com/489601/131081231-2ca7fe9e-ff3d-430a-b96c-12fd2b6aa267.png)

Multiple fonts in one message are not supported, so use of yellow color is optional: could be implemented much later (and probably would require a significant text rendering rework).

**Comment by Branikolog** [comment]
Hi, @a1exsh, @LeHerosInconnu  and @ihhub.
The option is not bad at all, but here I agree with @LeHerosInconnu. That notes in status bar break atmosphere a bit... I'm afraid making all such suggestions optional will completely "WOGify" fheroes2 engine. I believe players will remember that hotkeys in a few minutes of gameplay, so 99% of them will turn the option off later. So why do we need the option, that will be used only few minutes at start? 
In future, I hope, we're going to introduce a tutorial, where we can mention all that hotkeys. So this will be enough to inform new players about keyboard usage.
My 50 cents. :)

**Comment by LeHerosInconnu** [comment]
Hello everyone,

> > I find it breaks the atmosphere of the game by reminding the player that he is in a computer program with keyboard shortcuts.
> 
> We can always make it optional, to be turned on or off in the settings. ;)

> I'm afraid making all such suggestions optional will completely "WOGify" fheroes2 engine.

For me, it's okay if the setting is in the fheroes2.cfg file (so not in "Experimental Game Settings" window). :)

**Comment by ihhub** [comment]
Also please take a note that not every user uses PC abd this option won't make sense for mobile phones.

**Comment by Branpanman** [comment]
Would the ability for the player to remap the hotkeys to their preference be a good alternative to solve this issue?
