### ISSUE TITLE
Make monster parameters to be stored in configuration file

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#41]
We store monster parameters as hardcoded values within the code (`src/monster/monster.cpp`) file. This is bad as we do not give a flexibility for future changes/modification of the game. We need to store such data in a configuration file.

**Comment by enEin100** [comment]
Hello, all. Just now came across the project and I'd like to take this on. I can store the stats in a monster.config file and then write a function that reads the values from there into monstats_t monsters[].

**Comment by enEin100** [comment]
Hey, I'm almost done but wanted to ask if using a vector for monstats_t monsters in monster.cpp is okay. As of now, my work in progress places the stats from my config file into a vector and then copies it into the original monsters array.

Also, I created a couple functions that format the config file text and such. Should I make entries for them in the monsters.h file or keep them in the namespace in the monster.cpp file where the stats were originally created?

**Comment by ihhub** [comment]
Sorry for late reply. We should keep all variables in **cpp** file.

**Comment by ihhub** [comment]
@enEin100 one thing you forgot to make in your previous pull request is to handle a situation when configuration file doesn't exist. In such case we have to have original array of monster stats within application.

**Comment by ihhub** [comment]
Another thing which we don't need to do is to change creature names as these names are predefined. Configuration file could have a format similar to csv for example which is easy to read and write.

**Comment by ihhub** [comment]
@enEin100 is it clear for you now about the scope of work? We need configuration file with csv format where from we read only creatures statistics but we store creature name which we ignore during reading. The format would be something like this:
- header of file
`name,attack,defence,minimum_hit,maximum_hit,hp,speed,initial_growth,shot_count,gold_price,wood_price,ore_price,gems_price,mercury_price,sulfur_price,crystal_price`
Example of line:
`Peasant,1,1,1,1,1,0,12,0,20,0,0,0,0,0,0`

**Comment by enEin100** [comment]
Thanks for the clarification. I'll get on it

**Comment by enEin100** [comment]
I've defined a function in monster.cpp that loads the parameters from the csv file or from the hard coded values if the csv file isn't found. I realized though that I have no idea where I should have that function called.

**Comment by ihhub** [comment]
Hi @enEin100, I'll check which is the most suitable place to call this function.

**Comment by ihhub** [comment]
Hi @enEin100 you might need to have a look into `void Monster::UpdateStats(const std::string & spec)` function. I think it's the same what we need to do. You might need to modify this function if we don't have support of XML.

**Comment by ihhub** [comment]
Closing this issue as we aren't going to focus on this feature in our project.
