### ISSUE TITLE
Add publisher info (if possible) for Windows installer

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#4100]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

On Windows 10 while trying to run the the installer a user will get such error window which by inexperienced users might be considered as a malicious software. We should try to add publisher info for the installer if possible.

### Save file

![image](https://user-images.githubusercontent.com/19829520/131208264-7cab7acc-1106-4850-9e6d-bea2c0760afa.png)

![image](https://user-images.githubusercontent.com/19829520/131208310-c30e3a01-d565-4540-b20c-969cf2344358.png)

**Comment by oleg-derevenetz** [comment]
Hi @ihhub to circumvent Windows SmartScreen, you will need to sign the installer using the EV certificate from some trusted certificate authority. AFAIK there is no any other way.

**Comment by ihhub** [comment]
Hm... let's move it then to 1.0 for now.
