### ISSUE TITLE
fheroes2 0.9.6 crashed on osx 10.13.6

### ISSUE THREAD

**Issue by KlashKontakt** [ihhub/fheroes2#4101]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

macOS

### Describe the bug

the program gives an error immediately upon loading. the problem arose after version 0.9.4 (0.9.4 works quite well)

### Save file

<img width="1110" alt="BUG" src="https://user-images.githubusercontent.com/87890552/131210826-3baf8a8e-8cec-471c-b0ee-fe849172ccd5.png">

### Additional info

Thnx for Your work! =)

**Comment by ihhub** [comment]
Hi @KlashKontakt , the answer is in your attached screenshots: the minimal version for which fheroes2 built is 10.15 while yours is lower. You can build fheroes2 on your machine following our documentation.

**Comment by oleg-derevenetz** [comment]
Hi @KlashKontakt or you can install `fheroes2` using [MacPorts](https://www.macports.org/). The MacPorts version should work well on High Sierra.

**Comment by KlashKontakt** [comment]
> Hi @KlashKontakt , the answer is in your attached screenshots: the minimal version for which fheroes2 built is 10.15 while yours is lower. You can build fheroes2 on your machine following our documentation.

Thanks for the answer. In the end, I just realized that the problem is in the versions of the system. Honestly, I am not so masterful in the magic of the code to compile the version for my computer, but I will try. Thanks again for your great work.

> Hi @KlashKontakt or you can install `fheroes2` using [MacPorts](https://www.macports.org/). The MacPorts version should work well on High Sierra.

I hope I succeed. (Надеюсь у меня что нибудь получится)

Have nice day

**Comment by ihhub** [comment]
Hi @KlashKontakt ,

compilation on OSX is pretty easy, it'll take just few steps. Please read [this documentation](https://github.com/ihhub/fheroes2/blob/master/docs/DEVELOPMENT.md).

**Comment by ihhub** [comment]
Closing this issue for now. @KlashKontakt  please free to reopen if you still face difficulties.
