### ISSUE TITLE
Game settings dialog closes itself after changing resolution

### ISSUE THREAD

**Issue by a1exsh** [ihhub/fheroes2#4103]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

1. Start the game.
2. Click on the door to open "Game settings" dialog.
3. Click on "Resolution".
4. Select a resolution different from the current one and press `ENTER`.
5. The "Select resolution" dialog is closed and the resolution is applied, all good so far.
6. **The bug:** now the "Game settings" is also closed and cannot be opened again.  Clicking on the door shows the dialog for a brief moment, but it closes automatically.
7. It also closes itself when opened from "New game" -> "Config" (by clicking!)
8. The dialog works again if another hotkey is used, e.g. `N` to open "New game" first.

It looks like the `ENTER` hotkey state is not cleared until some other hotkey is used.

### Save file

The issue is reproducible from the main menu.

**Comment by ihhub** [comment]
Hi @a1exsh , I've checked right not on Win 10. It works fine for me.

**Comment by oleg-derevenetz** [comment]
Cannot reproduce this on macOS as well. The "Game Settings" dialog is not closed after pressing "Enter" in the "Select Resolution" dialog and it opens normally afterwards.

**Comment by a1exsh** [comment]
Let's close this: the issue is gone after I've built libSDL2 from source code.  Not sure what's wrong with the packaged version on my system.
