### ISSUE TITLE
Edge of the World Map must not show a popup on right click

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#411]
Here how it looks like right now:
![image](https://user-images.githubusercontent.com/19829520/79677303-554f9800-8222-11ea-898f-82fd1d6a5d76.png)

First of all the cursor changes depending what was the previous column on the map. In the above situation the map has water. That is why we have a popup with `Water` and the cursor in a shape of a boat.

**Comment by shprotru** [comment]
Could you explain how to reproduce this bug? In linux I can't

**Comment by ihhub** [comment]
Open any map --> open some area --> right click on the End of the World Map --> you will get a popup message (not always Water) which must not appear at all.

**Comment by shprotru** [comment]
I tried that, and have no popup message

**Comment by ihhub** [comment]
Which version have you tried: SDL 1 or SDL 2?

**Comment by shprotru** [comment]
SDL2, bult with `env DEBUG=1 WITH_SDL2=1 make`

**Comment by ihhub** [comment]
Could you please try SDL 1 instead? I do not have Linux machine right now to verify it.

**Comment by shprotru** [comment]
Can't reproduce on SDL1 too(moved with `make clean && env DEBUG=1 make`): [https://vimeo.com/412781082](https://vimeo.com/412781082)
At the video I am clicking on the border.

**Comment by ihhub** [comment]
Please click on right or left side of the border, not top ;)

**Comment by Branikolog** [comment]
Ooops, I've made the same issue... The thing is that when you point the right or left edge - it shows the content mirrored from the opposite side of the world edge. You can even left click it and game will create path towards the object near he opposite side of world edge. The up and bottom edge of map have slightly different behavior: it shows a cursor the same as it was while moving from world map to the edge:
![Edge](https://user-images.githubusercontent.com/55348946/80713152-ab162100-8afb-11ea-8a25-345ceb09e7bf.jpg)
![Edge1](https://user-images.githubusercontent.com/55348946/80713158-ad787b00-8afb-11ea-8b61-eb28f334a385.jpg)
![Edge2](https://user-images.githubusercontent.com/55348946/80713167-afdad500-8afb-11ea-9f1d-ce890602c836.jpg)
![Edge3](https://user-images.githubusercontent.com/55348946/80713171-b2d5c580-8afb-11ea-8176-c3d4e798a843.jpg)

**Comment by shprotru** [comment]
Still can't reproduce, video on SDL1(I tryed on SDL2 too): https://vimeo.com/414312537
Need detailed guide to reproduce this bug

**Comment by Branikolog** [comment]
> Still can't reproduce, video on SDL1(I tryed on SDL2 too): https://vimeo.com/414312537
> Need detailed guide to reproduce this bug

As i mentioned before, pointing edge of a world shows mirrored content from the opposite side of map. At your video it shows uncharted territory from the right side of your map, because territory near the right edge is hidden under black clouds. Right click on the edge must not show "uncharted territory" message at all.
You should explore territory near the right edge of map to completely reproduce this bug.
