### ISSUE TITLE
Scenario selection window, the name of each scenario is displayed twice

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4117]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the name of each scenario is displayed twice.

In fheroes2 :

![Twice the same scenario name 01](https://user-images.githubusercontent.com/43583994/131660181-b7015491-4c13-46d9-8f36-8895e4eb0b3d.png)

### Save file

None.

### Additional info

Version 0.9.6 4111

**Comment by Branikolog** [comment]
It seems that you have all these maps stored in both .mx2 and .mp2 formats. So now list shows all maps from the folder.

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

> It seems that you have all these maps stored in both .mx2 and .mp2 formats. So now list shows all maps from the folder.

This is not the case.
Here is a part of the content of the maps folder:
![Twice the same scenario name 02](https://user-images.githubusercontent.com/43583994/131662084-98b061c6-a026-4f7e-9c25-1a4ddaf274fb.png)

**Comment by Branikolog** [comment]
So, here's my another theory then. :) (Actually, not theory, I've successfully checked it already.)
Game reads map lists from both root folder of fheroes2 engine and the fheroes2 folder from users directory.
So, you can have up to 4 maps with the same name. :)
![image](https://user-images.githubusercontent.com/55348946/131665669-0c855c36-5403-433f-a1b7-a8cb8d0381ed.png)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , please check the description of maps are the same and to verify that the game indeed has duplicates just put there 10 maps only and see how many maps is displayed in the game.

**Comment by ihhub** [comment]
Oh, in this case we should do something.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> Game reads map lists from both root folder of fheroes2 engine and the fheroes2 folder from users directory.

My maps folder is empty in the user's folder (C:\Users\Inconnu\AppData\Roaming\fheroes2\maps).

Hello @ihhub,

> Hi @LeHerosInconnu , please check the description of maps are the same and to verify that the game indeed has duplicates just put there 10 maps only and see how many maps is displayed in the game.

Without any files in the Maps folder, I get this:
![Twice same scenario name 001](https://user-images.githubusercontent.com/43583994/131668830-65335336-d50e-42a3-a983-35c179bfd0e8.png)

With only 10 different scenario files in the Maps folder, I get this:
![Twice same scenario name 002](https://user-images.githubusercontent.com/43583994/131668874-612a23ae-0d3d-415d-95f4-904e9a12bc93.png)
![Twice same scenario name 003](https://user-images.githubusercontent.com/43583994/131668893-1586f206-6afa-4810-8d7f-8a4a0a2c1945.png)

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu where is the `fheroes2.exe` itself is located?

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> Hi @LeHerosInconnu where is the `fheroes2.exe` itself located in your case?

Here is the path: "D:\Bureau Disque C\Heroes 2 Bureau\Free Heroes of Might and Magic 2\Version 0.9.6 latest 29 08 2021 4111\fheroes2_windows_x64_SDL2\fheroes2.exe"

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu Hmm, interesting. So there is no `fheroes2.exe` in user's data directory, and there is no `MAPS` directory in the directory with `fheroes2.exe` and maps are still doubled in the map list?

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> @LeHerosInconnu Hmm, interesting. So there is no `fheroes2.exe` in user's data directory, and there is no `MAPS` directory in the directory with `fheroes2.exe` and maps are still doubled in the map list?

Here is the location of the scenarios:

![Maps location 001](https://user-images.githubusercontent.com/43583994/131726842-b8c27d5a-aff9-4d7b-a2de-0c5339580924.png)

![Maps location 002](https://user-images.githubusercontent.com/43583994/131726845-399e9486-235d-4061-8d48-111e8765ed23.png)

![Maps location 003](https://user-images.githubusercontent.com/43583994/131726847-cd218d56-1e73-4e0d-8fe2-4d5548825072.png)

![Maps location 004](https://user-images.githubusercontent.com/43583994/131726855-a06004dc-b9bc-4fc4-9d6d-e142487632c2.png)
