### ISSUE TITLE
Complete hero's movement cell if an user clicks by mouse during hero's movement

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#412]
Recently we [implemented ](https://github.com/ihhub/fheroes2/pull/406) the same feature is an user presses any button on a keyboard. We need to add the same functionality for mouse click as well like it is done in the original game.

**Comment by shprotru** [comment]
very strange bug:
on first turn movement you can't stop your hero by mouse click, but on the second turn you can! Looks like some variable not initialized. Does this issue about that?

**Comment by ihhub** [comment]
On right click you can stop a hero but on left click you cannot if you click on undiscovered area,
