### ISSUE TITLE
Multiple Battle Garbs of Anduran do not stack

### ISSUE THREAD

**Issue by shubalex** [ihhub/fheroes2#4121]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Multiple Battle Garbs of Anduran do not stack, meanwhile, the individual artifact pieces affect the primary stats properly. 

### Save file

![Screenshot-2021-09-01-145828](https://user-images.githubusercontent.com/80069099/131676120-d683ba30-d0ba-4267-864c-6da08f3c3ea1.png)
![Screenshot-2021-09-01-145648](https://user-images.githubusercontent.com/80069099/131676153-d034de5a-857b-45d7-bb5a-b4a2cdfe5498.png)

**Comment by oleg-derevenetz** [comment]
I suppose we need something like #3548 to fix this properly instead of making ad-hoc hacks here and there.
