### ISSUE TITLE
Combat, AI behavior, AI troop doesn't move (0.9.6 4111)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4124]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

The troop of Cavalries doesn't move.

In fheroes2:

![AI troop dont move 01](https://user-images.githubusercontent.com/43583994/131688225-fd5bc211-015a-4b35-a6fd-8a27b2c2b284.png)

https://user-images.githubusercontent.com/43583994/131688276-a6ad04f5-bcd4-4c28-8263-6e92d1d43415.mp4

Wrathmont attacks Cavalries.

Here is the save file:
[AI troop dont move 01.zip](https://github.com/ihhub/fheroes2/files/7091849/AI.troop.dont.move.01.zip)

### Describe the possible solution

Cavalries' troop should at least try. :)
This is what happens if the Green Dragon is positioned at other positions.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , is it still an issue after we fixed pathfinding logic and decision making for the AI?

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , is it still an issue after we fixed pathfinding logic and decision making for the AI?

I'm putting this on my "to be tested soon" list. :)

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hello @ihhub,
> 
> > Hi @LeHerosInconnu , is it still an issue after we fixed pathfinding logic and decision making for the AI?
> 
> I'm putting this on my "to be tested soon" list. :)

The case presented no longer happens.
I close the issue.
