### ISSUE TITLE
Adventure map, hero can create a path through a barrier

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4150]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

![image](https://user-images.githubusercontent.com/55348946/132017210-6e9e0448-f0ab-424b-9bfe-6aa8b203e70b.png)
We can make a path through a barrier to attack skeletons.
Also, while pointing Barrier, cursor changes to a sword. I'm pretty sure, that we shouldn't be able to attack creatures standing behind the barrier.

### Save file

[Barrier.zip](https://github.com/ihhub/fheroes2/files/7106408/Barrier.zip)

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

> Also, while pointing Barrier, cursor changes to a sword. I'm pretty sure, that we shouldn't be able to attack creatures standing behind the barrier.

In the original game, the hero cannot interact with the elements behind a barrier (positioned as in the example).
The barrier should block any interaction.
