### ISSUE TITLE
Adventure map, hero can pass near barrier

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4151]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

![image](https://user-images.githubusercontent.com/55348946/132020883-0dfd8227-b65a-4d23-a5f7-9fe1d2a17dc6.png)
I believe, hero shouldn't be able to pass here.

### Save file

[Barrier2.zip](https://github.com/ihhub/fheroes2/files/7106537/Barrier2.zip)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> I believe, hero shouldn't be able to pass here.

In the original game, the barrier was not designed to be used in this way (blocking a horizontal movement of the hero in relation to the barrier) and depending on the elements positioned on each side of the barrier the hero can pass by, thus making the barrier ineffective and useless.

Either, in fheroes2, it is possible to make sure that when a barrier is used in this way in a scenario the elements positioned on each side have their passability modified to block the hero's movement.
Either, it is left as in the original game.
Either, you have to rework the scenarios and correct the positioning of the barriers to effectively block the hero (I had already modified some scenarios in this sense with a new version of the scenario "1.01").
It is also to be noted that sometimes the scenario creator uses this state of facts voluntarily (the hero can pass by a barrier positioned to block the hero's movement, and an event message is displayed like: "Who needs to visit the tent to pass.").
I remember at least one scenario in this case.

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu !
I didn't compare to the original game the issue above. My fault.
In the OG at this place a hero can definitely pass:
![image](https://user-images.githubusercontent.com/55348946/132094980-eb91c283-3fa5-4d9e-931c-bc86d00131c5.png)
I think, in our future editor we should make this area close to barrier unpassable to expand mapmaker's capabilities.
For now I mark this issue as improvement.

**Comment by ihhub** [comment]
I think we shouldn't fix passabilities and leave them as they are in the original game. At the same time the future Editor must show object passabilities in a very user-friendly way to a creator of the map could flawlessly spot the issue like this.

**Comment by ihhub** [comment]
If @Branikolog  and @LeHerosInconnu  you both agree with my statement above we can close this issue.
