### ISSUE TITLE
Kingdom Overview screen, Heroes Overview and Towns/Castles Overview screens, position of lists in Heroes Overview and Towns/Castles Overview screens are not completely memorized

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4197]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, position of lists in Heroes Overview and Towns/Castles Overview screens are not completely memorized.

In fheroes2:

https://user-images.githubusercontent.com/43583994/132983911-8f80a5bb-a60d-4da9-ab1f-e10b5b294956.mp4

### Save file

Here is the save file (0.9.7 4180):
[Kingdom overview positions 01.zip](https://github.com/ihhub/fheroes2/files/7149411/Kingdom.overview.positions.01.zip)

### Additional info

Related Pull Request merged: Remember UI position in Kingdom Overview dialog #4035

**Comment by Branikolog** [comment]
Here I want to add, that after dismissing a hero list jumps to its upper position.
