### ISSUE TITLE
Adventure map, hero's path through mountains

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4199]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the heroes take paths that give the impression that they are "penetrating" the objects.
This should be avoided.

In original game:

![Path near mountains H2 01](https://user-images.githubusercontent.com/43583994/132984464-0829d8e8-6ae3-4ae3-9554-a17b019a74d9.png)

In fheroes2:

![Path near mountains fh2 01](https://user-images.githubusercontent.com/43583994/132984451-d30f21e3-e76c-4117-b0a3-845cc86e46eb.png)

![vlcsnap-2021-09-12-12h32m19s201](https://user-images.githubusercontent.com/43583994/132984536-859a2718-8917-4376-9ad8-132a1c92018f.png)

https://user-images.githubusercontent.com/43583994/132984442-ff47caab-cb2e-4e30-b987-9285122370b8.mp4

### Save file

Here is the save file (0.9.7 4180):
[Path travers montagne 100.zip](https://github.com/ihhub/fheroes2/files/7149442/Path.travers.montagne.100.zip)

### Additional info

Related closed issues: https://github.com/ihhub/fheroes2/issues/3246, https://github.com/ihhub/fheroes2/issues/3094.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , is this issue still valid after our changes with pathfinding?
