### ISSUE TITLE
Deterministic battles cause different outcome in instant and manual battles

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4206]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

![image](https://user-images.githubusercontent.com/55348946/133069577-ac469721-643e-4274-98e0-5feddb491e34.png)
While attacking the same creature we have different outcome each reload:
![image](https://user-images.githubusercontent.com/55348946/133069658-7a084b01-d38f-4611-a1bf-3458fbe5526a.png)
![image](https://user-images.githubusercontent.com/55348946/133069720-b55ddc4e-83d5-406d-b78c-79459e250ae2.png)
![image](https://user-images.githubusercontent.com/55348946/133069804-b0a1a518-dda1-49dd-8fa6-d15eda75b249.png)

Also, correct me if I'm wrong, deterministic option being turned on should lead to the same battle results: the same damage, morale effects and the same AI behaviour.
Currently the same battle goes completely different on a reload:
![image](https://user-images.githubusercontent.com/55348946/133070451-7a3592f5-dc5f-46b0-8497-ead696eb9914.png)
![image](https://user-images.githubusercontent.com/55348946/133070476-c2e74e54-5df6-4a10-af66-84761e1477a1.png)

Replaying the battle manually and allowing AI make all by himself also leads to different outcome.
![image](https://user-images.githubusercontent.com/55348946/133070739-33e5e751-3970-4771-98e6-29653a1d030b.png)
![image](https://user-images.githubusercontent.com/55348946/133070832-31eb27d4-9556-46e7-9b74-e57b5284c1eb.png)

### Save file

[Non deterministic battle.zip](https://github.com/ihhub/fheroes2/files/7153627/Non.deterministic.battle.zip)

**Comment by vincent-grosbois** [comment]
that's strange... do you know what is the first thing that AI does differently on different reloads ? it could be something that I forgot to make "deterministic" and that is still fully random

**Comment by Branikolog** [comment]
Hi, @vincent-grosbois 
Even damage dealt by hobbits on 5-6 screenshot was different in a same circumstances.

**Comment by vincent-grosbois** [comment]
Does it even work for other battles ? maybe the flag is not even plugged in :D I'll check this later

**Comment by oleg-derevenetz** [comment]
@vincent-grosbois that's because seed calculation in `UpdateRandomSeed()` depends on command's arguments, and they may contain UIDs as troop identifiers (for example, in `MSG_BATTLE_MOVE`, `MSG_BATTLE_ATTACK`, `MSG_BATTLE_CAST` and others), which are different in each battle.

**Comment by vincent-grosbois** [comment]
> @vincent-grosbois that's because seed calculation in `UpdateRandomSeed()` depends on command arguments, and they may contain UIDs as troop identifiers (for example, in `MSG_BATTLE_MOVE`, `MSG_BATTLE_ATTACK`, `MSG_BATTLE_CAST` and others), which are different in each battle.

good catch ! 
I see no simple way to fix this though, what about only hashing the first int of the Command object, which is sure to contain the enum value? Otherwise Command is too generic and it's complex to hash the rest while being sure to never hash the UID of the troop

That, or getting rid of the Troop UID, but it must be quite more complex (I've no idea what is its purpose)

**Comment by oleg-derevenetz** [comment]
@vincent-grosbois yes, it is possible to hash only the `GetType()` part of the command - this will make the seed generation a bit more predictable, but this might be OK(?). I believe we will still need the UIDs for troops in one form or another, because new troops may appear (for example, elementals) and multiple troops may even occupy the same cell (if they are dead and we want to cast Resurrect on them).

**Comment by vincent-grosbois** [comment]
What I'll submit is a patch where there is more "state" in the battle object, so every unit uid counter restarts at 0 at each battle.
I've tested it and it works, ie when you reload and redo the battle, the counter always restarts at 0.

Now I'm checking, and there is also another issue I'm encountering, which is that the Command object starts differently whether you are in manual battle or in "instant" battle. In instant battle it starts with Command (0, 17) and in manual battle it starts with Command (17), so they are hashed differently

**Comment by oleg-derevenetz** [comment]
@vincent-grosbois we can ignore the `MSG_BATTLE_AUTO` command for the purpose of hash computation.

**Comment by vincent-grosbois** [comment]
> 
> 
> @vincent-grosbois we can ignore the `MSG_BATTLE_AUTO` command for the purpose of hash computation.

thanks, I'm still investigating :) I think what happens is that in instant battle, spells are launched, and not in manual battle, "auto" button on. What I have as first command in instant battle is Command(6, 0, 17) which is casting a spell

**Comment by oleg-derevenetz** [comment]
@vincent-grosbois when you press "AUTO" button, `MSG_BATTLE_AUTO` command is sent, which is not happens in instant battle.
