### ISSUE TITLE
Add individual Spell value for AI

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#4227]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Right now all spells for AI are the same value. This is not correct as some spells are much more powerful than others.

### Describe the possible solution

Add a spell value for AI which could be used for evaluation certain actions.

**Comment by idshibanov** [comment]
> Right now all spells for AI are the same value

@ihhub Can you be more specific here? Where/for which calculation?

**Comment by ihhub** [comment]
Hi @idshibanov , we need to make granular differentiation of values for spell. For example, a hero stands between 2 Shrines of the same level. One Shrine offers Curse while another one Slow. In most cases Slow spell is more useful in battles so AI hero must have higher priority for this. However, it is not exactly obvious which spell is more useful. It really depends on a hero and a state of the game.
