### ISSUE TITLE
Lock mouse cursor to window to make game playable in dual-screen

### ISSUE THREAD

**Issue by gab** [ihhub/fheroes2#4230]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

I have a dual-screen setup. I've attempted to play the game in full-screen with this setup and it's not really doable, as you need to use the screen edges to scroll the map, but on the side where my desktop extends to my other screen, the mouse leaves the window instead.

This is a fatal issue since AFAIK, there's no other way to scroll the game map.

### Describe the possible solution

The mouse cursor should be locked to the game screen by default, with an option to keep the current behavior.

In addition, please strongly consider adding an option to scroll the map with arrow keys and/or WASD, as is standard in recent 4X games. I don't know how many people use the arrow keys to move heroes, but I know I never used this functionality and it actually causes me problems when reflexes from other games kick in and I end up moving my hero out of his castle or something with an enemy nearby.

**Comment by ihhub** [comment]
Hi @gab , it was added some time. Please try the latest snapshop of SDL2 build to verify it.

**Comment by gab** [comment]
I just retested with the latest SDL2 Winx64 snapshot, and the cursor still escapes into my left screen.

**Comment by gab** [comment]
Hmm. Weirdly enough, the first time with the latest snapshot failed, just as I described. However, all subsequent tries to reproduce the bug (still with the snapshot) resulted in the mouse being correctly locked. Perhaps something about settings being saved when the program exits, since I didn't clear %appdata%\fheroes2 before testing?
