### ISSUE TITLE
Wild flickering or black screen after changing screen layout

### ISSUE THREAD

**Issue by gab** [ihhub/fheroes2#4231]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

I have a dual screen setup. If I turn off my second screen after the game has been launched (to work around the current issue with the mouse cursor not locking to the game window, preventing map scroll), the game isn't able to recover and goes into either a black screen with cursor (in full screen) or a wild flickering (in windowed mode). No amount of pressing F4 fixes this.

The expected behavior would be to adapt to the new display resolution properly (which in this case, is actually identical for the screen being used since I simply turned off the other screen).

Graphics card is Nvidia GTX 1070.

### Save file

A save file isn't necessary to test this, you can do it from the main menu.

### Additional info

Tested on snapshot 0.9.7-100072

**Comment by ihhub** [comment]
Hi @gab , please try a build from #4709 . It might help to solve your issue.
