### ISSUE TITLE
Adventure map, a part of the combined shadow of the tree and the hero is darker

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4236]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

In fheroes2, in the example, a part of the combined shadow of the tree and the hero is darker.
This also happens with other objects, and is also the case in the original game.

In fheroes2:

![Darker shadow tree hero 01](https://user-images.githubusercontent.com/43583994/134149449-8c18c1a9-56be-436b-aacb-146f824d2240.png)

Here is the save file:
[Darker shadow tree hero 01.zip](https://github.com/ihhub/fheroes2/files/7202149/Darker.shadow.tree.hero.01.zip)

### Describe the possible solution

This could be improved so that the shadow tone is uniform for both shadows combined.

### Additional info

Version 0.9.7 4210

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , could you please not to post anymore issues related to object rendering due to hero/boat presence. All these issues are connected to the same logic so once we fixed the core logic we can restart posting issues if we find any :)
