### ISSUE TITLE
Adventure map, the fountain is displayed over the hero sprite

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4237]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the fountain is displayed over the hero sprite.

In fheroes2:

![vlcsnap-2021-09-21-11h59m46s879](https://user-images.githubusercontent.com/43583994/134152475-efcb5a99-b0c1-44b1-bf69-cd80d1a866b0.png)

https://user-images.githubusercontent.com/43583994/134152516-a60c1e11-f397-4b3a-95ef-eda7892167e3.mp4

### Save file

Here is the save file:
[Fountain over hero 01.zip](https://github.com/ihhub/fheroes2/files/7202274/Fountain.over.hero.01.zip)

### Additional info

Version 0.9.7 4210

**Comment by Branikolog** [comment]
Happens in a cases we have other hero standing diagonally to the right of a fountain.
