### ISSUE TITLE
Passability issue presented even on OG

### ISSUE THREAD

**Issue by lleonis** [ihhub/fheroes2#4250]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

Tile with road in front of the hero is unpassable. This messes up path calculation.
![screenshot](https://user-images.githubusercontent.com/91083784/134571248-4a3ad87c-32e7-4ba4-ae34-7d4daec8e09b.png)

### Save file

[savefile.zip](https://github.com/ihhub/fheroes2/files/7220401/savefile.zip)

### Additional info

0.9.7 is affected, but reproducible with latest snapshot as well.

**Comment by ihhub** [comment]
Hi @lleonis , this is the issue with map itself. Here's a screenshot from the original Homm2 playing the game map:
![image](https://user-images.githubusercontent.com/19829520/135129522-ace856d6-54b0-4514-a26e-8aaaa52e7a73.png)

**Comment by lleonis** [comment]
My bad, I forgot to check with OG. IMHO the game should not fix a buggy map. As far as I'm concerned, this issue can be closed.
