### ISSUE TITLE
Adventure map, wrong passability of mountains near Tree City

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4258]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, there is a wrong passability of mountains near Tree City.

In original game:

![Mountains passability Tree City H2 01](https://user-images.githubusercontent.com/43583994/134777140-17b398f9-9205-4c39-babf-fedf26371401.png)

In fheroes2:

![Mountains passability Tree City fh2 01](https://user-images.githubusercontent.com/43583994/134777152-beacf7c5-6ebc-4b6a-bc40-f2245fb78058.png)

### Save file

Here are the save files:
[Passability 100.zip](https://github.com/ihhub/fheroes2/files/7229977/Passability.100.zip)

**Comment by ihhub** [comment]
It's mines related passability. Eh...😞
