### ISSUE TITLE
Adventure map, AI behavior, AI heroes should visit the Pyramids (0.9.7 4208)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4267]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

In fheroes2, AI heroes don't always visit the Pyramids when they could (powerful enough army and sufficient Wisdom level).

In fheroes2:

![Pyramids not yet visited 01](https://user-images.githubusercontent.com/43583994/134936373-0828c6de-a516-4896-9db0-f90c027efc81.png)

Visit the two Pyramids near Sandro.
The AI heroes have not visited them yet.

Here are a save file and a test scenario:
[Pyramids not yet visited 01.zip](https://github.com/ihhub/fheroes2/files/7237414/Pyramids.not.yet.visited.01.zip)

### Describe the possible solution

Make the AI heroes visit the Pyramids when they could.
The Wisdom level of the AI hero should be taken into account to visit a Pyramid (sufficient Wisdom level).
Maybe also an AI hero could visit a Pyramid even when his Wisdom level is not enough in case an opponent hero nearby could benefit from the spell (powerful enough army). :)

**Comment by vincent-grosbois** [comment]
hi @LeHerosInconnu 

I fear that this is very difficult to fix given a real map after the fact
Is it the case that AI never visits pyramids even when they have nothing else to do ? Otherwise it could be that other stuff were prioritized

**Comment by LeHerosInconnu** [comment]
Hello @vincent-grosbois,

> Is it the case that AI never visits pyramids even when they have nothing else to do ? Otherwise it could be that other stuff were prioritized

In the test scenario provided, it is easy to see that the AI heroes do not visit the Pyramids even if they have a sufficient army and a sufficient level of Wisdom whereas there is nothing else to do.
A level 5 spell should not be neglected when it can be obtained easily enough. :)

**Comment by vincent-grosbois** [comment]
https://github.com/ihhub/fheroes2/blob/3d102c92abdb65621efb3852bdb24ede09587fe5/src/fheroes2/ai/normal/ai_normal_hero.cpp#L351

seems like it's missing anyway
