### ISSUE TITLE
Linux: mouse movement has inertness

### ISSUE THREAD

**Issue by shprotru** [ihhub/fheroes2#427]
On Linux builded with:
`env WITH_SDL2=1 make`
when you moving mouse across the game window you will got artificial deceleration of game mouse cursor.
**Condition**: in higher than default resolution.
Where could be hidden this problem in code?

**Comment by ihhub** [comment]
Hi @shprotru , you can have a look into `int Interface::Basic::HumanTurn( bool isload )` function. There is a root of the problem. We encountered this issue some time ago but I think nobody logged it as a bug. I think move movement cause whole window to be redrawn which of course a very slow operation.

**Comment by shprotru** [comment]
I think problem is deeper, because mouse is laggy even in lobby

**Comment by shprotru** [comment]
@ihhub I've improved mouse cursor for `SDL2` and it start working in 4k resolution like it should be, without any lags. I am sure it will be better in all operating systems, but have problems in code related to `SDL1`. You could check how it working in `SDL2`, check patch, and, if possible, help, please.
[I427.patch.txt](https://github.com/ihhub/fheroes2/files/4624541/I427.patch.txt)
**_help needed_**: I used SDL2-only function `SDL_CreateColorCursor` and everything got better, need make call to `SDL_CreateCursor` with information from `AGG::GetICN` / `Surface` or `SDL_Surface`, the whole thing in `Uint8 *mask`, the second argument to `SDL_CreateCursor` where to get it? We can't leave the old code related to this mouse controlling, it must be done using `SDL1`/`SDL2` cursor API's, both of them have everything we need.

**Comment by ihhub** [comment]
Hi @shprotru , could you please create a pull request with what you have? Making a mask is not the issue. We can even do step by step: first SDL 2 first and then SDL 1.

**Comment by shprotru** [comment]
@ihhub I created PR, help please with mask at first, it would be great. Is any reason why fheroes2 engine did not used `SDL` mouse cursor api instead of writing own routines?

**Comment by ihhub** [comment]
Hi @shprotru , there is no particular reason for this. The initial project was design by a different group of developers so it's a mystery now :)

**Comment by shprotru** [comment]
@ihhub ok, previously I thinked that reasons was on supporting some interesting "historical" devices where `SDL1/2` mouse API doesn't work(that of course strange). I don't know anything about devices, that's why I asked you. So I suggest to replace this code with `SDL` API calls. Check, please, my PR #515 and help to make bit-mask to call `SDL_CreateCursor`.
