### ISSUE TITLE
Descendants Campaign Scenario 7 cannot be solved

### ISSUE THREAD

**Issue by msjasinski** [ihhub/fheroes2#4270]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Descendants Campaign Scenario 7 doesn't work because a few turn into the game NPC Pikemen growth are placed on an only open island hex blocking the only way forward.
![fheroes2_GaVlkaqQKn](https://user-images.githubusercontent.com/4431194/134966435-c1272ea4-64c9-4e90-9740-95d3e7933dec.png)

### Save file

[d7_0093.zip](https://github.com/ihhub/fheroes2/files/7238548/d7_0093.zip)

**Comment by vincent-grosbois** [comment]
lol
I have no idea how this is solved in the OG, if at all
Do they just disable all "week of monsters" weeks ?

**Comment by LeHerosInconnu** [comment]
Hello @msjasinski and @vincent-grosbois,

No one knows exactly how the wandering creature troops are generated during the month of the creature in the original game.
Surely there must be a rule for the case presented in the original game, as this can block the scenario.
Here your only chance is to get the Dimension Door spell, you have three possible cities to achieve this.
Unfortunately for this game this spell is not available in any of the Mage Guilds.
You can also try to load a save file just before the generation of the Month of the Pikeman, as for the moment the positioning of the wandering creature troops is totally random.

**Comment by vincent-grosbois** [comment]
Simpler logic which would lead to less bugs etc would be to not spawn creatures on coasts I guess

**Comment by LeHerosInconnu** [comment]
@vincent-grosbois,

> Simpler logic which would lead to less bugs etc would be to not spawn creatures on coasts I guess

More restrictive but just as effective. :)

**Comment by ihhub** [comment]
I think we shouldn't spawning monsters on coasts if no other neighboring coast cells empty.

**Comment by msjasinski** [comment]
> No one knows exactly how the wandering creature troops are generated during the month of the creature in the original game. Surely there must be a rule for the case presented in the original game, as this can block the scenario. Here your only chance is to get the Dimension Door spell, you have three possible cities to achieve this. Unfortunately for this game this spell is not available in any of the Mage Guilds. You can also try to load a save file just before the generation of the Month of the Pikeman, as for the moment the positioning of the wandering creature troops is totally random.

I had tried all the above - to no avail. Even replayed the scenario and the Pikemen were placed just in the same square.

I assumed the algorithm distributes monsters equally and places them randomly per each "region" of the map.
