### ISSUE TITLE
Question about week of / month of

### ISSUE THREAD

**Issue by vincent-grosbois** [ihhub/fheroes2#4277]
### Your question

I have a question regarding the logic for "week of" / "month of" based on the code : https://github.com/ihhub/fheroes2/blob/a9e7339a65ce9460916323d1a480c13c0e913640/src/fheroes2/kingdom/week.cpp#L89

- In OG, is there a specific difference between "new week" and "new month" ?
- In OG, does "week of [Monster]" appear with proba 33% ?
- In OG, does "week of Plague" appear with proba around 1/30th, and only on new month ?
thanks

**Comment by LeHerosInconnu** [comment]
@vincent-grosbois,

> * In OG, is there a specific difference between "new week" and "new month" ?

Week of the creature:
- +5 creatures in all creature generators (in towns and on adventure map).

Month of the creature:
- population of creature doubles in all creature generators (in towns and on adventure map), wandering creature troops can appears on the adventure map.

> * In OG, does "week of [Monster]" appear with proba 33% ?

I don't know about the percentage of appearance.

> * In OG, does "week of Plague" appear with proba around 1/30th, and only on new month ?

It is only the "month of the Plague" and as the name suggests it is only possible at the beginning of each month if it is triggered.
I don't know what the appearance percentage is, but it is quite low (so as not to annoy the player too much).
But even so, it's already too much for many players (generally they reload to try to remove its appearance). :)

In fheroes2, there was a very useful option to avoid the appearance of the Month of the Plague, but it has been removed.
I have planned to make a request to have this option reintegrated. :)

**Comment by vincent-grosbois** [comment]
> Week of the creature:
> 
> * +5 creatures in all creature generators (in towns and on adventure map).
> 
> Month of the creature:
> 
> * population of creature doubles in all creature generators (in towns and on adventure map), wandering creature troops can appears on the adventure map.

I don't think we handle the difference between these for now

**Comment by LeHerosInconnu** [comment]
Hello @vincent-grosbois,

> > Week of the creature:
> > 
> > * +5 creatures in all creature generators (in towns and on adventure map).
> > 
> > Month of the creature:
> > 
> > * population of creature doubles in all creature generators (in towns and on adventure map), wandering creature troops can appears on the adventure map.
> 
> I don't think we handle the difference between these for now

I haven't checked the results, but the windows are there.

In fheroes2:

![Separation empty line missing 01](https://user-images.githubusercontent.com/43583994/136701434-0d6f275b-8059-4692-9564-f5536ad7de6e.png)

![Separation empty line missing 02](https://user-images.githubusercontent.com/43583994/136701442-afa78c24-9d3b-436d-a1ae-448200bc0f9b.png)

Here are the save files:
[Separation empty line missing 01.zip](https://github.com/ihhub/fheroes2/files/7317657/Separation.empty.line.missing.01.zip)

**Comment by ihhub** [comment]
This issue was fixed in #5958.
