### ISSUE TITLE
View Towns screen, wrong sprites used for towns and castles

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4279]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, wrong sprites are used for towns and castles.

In original game:

![View Town H2 001](https://user-images.githubusercontent.com/43583994/135074452-37bc9744-2f2c-4c23-b938-2e0b0b2855db.png)
![View Town H2 002](https://user-images.githubusercontent.com/43583994/135074463-c7151aa4-3a57-4123-9162-16f1e03157ff.png)
![View Town H2 003](https://user-images.githubusercontent.com/43583994/135074469-ac344e75-37fd-4d1e-9578-230e93e178b2.png)

In fheroes2:

![View Town fh2 01](https://user-images.githubusercontent.com/43583994/135074510-ceb16a27-cab4-4c2b-8c2b-a4f799771f27.png)

### Save file

Here are the save files:
[View towns different 010.zip](https://github.com/ihhub/fheroes2/files/7243302/View.towns.different.010.zip)

### Additional info

Version 0.9.7 4208

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , pardon me but I don't understand what's wrong with graphics in fheroes2. Could you please describe what we need to change?

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , pardon me but I don't understand what's wrong with graphics in fheroes2. Could you please describe what we need to change?

In the original game, in the Fog of War part, the "real" sprites of the towns/castles are used so that the player can see whether it is a town or a castle and he can also see the type of the town/castle, Knight, Necromancer, etc.
In fheroes2, only flags are used.

**Comment by ihhub** [comment]
Thank you, @LeHerosInconnu .

The problem is in the way how we draw the map. Right now there's no level related to towns or mines.
