### ISSUE TITLE
Castle screen, active building area is not updated for the newly created buildings appeared over the existing ones

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4297]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

When we build, for example, a thieves guild in necromancer castle, its sprite appears over a castle. At bottom bar is written "thieves guild", while pointing it. But wen we click on it - a castle construction screens appear as well as castle info window:
![image](https://user-images.githubusercontent.com/55348946/135513068-90ed0f48-ed3e-42ad-a4c6-9050b773c1bc.png)
![image](https://user-images.githubusercontent.com/55348946/135513253-aa4ba51a-b2c8-41c5-9983-9a4a16c37364.png)
Issue happens not only in necromancer castle.

### Save file

Try to create Thieves guild in Necromancer or Knight castles.
[Thieves Guild captured.zip](https://github.com/ihhub/fheroes2/files/7261843/Thieves.Guild.captured.zip)

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

This is related to this issue: https://github.com/ihhub/fheroes2/issues/4257.

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu !
It is not related...
It is completely the same issue.)
Sorry, don't know how did I manage to miss your issue...
I was so shocked when I couldn't enter thieves guild in necromancer castle, that I hadn't made an attempt to search the existing topics. :)
