### ISSUE TITLE
Italian CD version, will be supported?

### ISSUE THREAD

**Issue by Hexaae** [ihhub/fheroes2#4300]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Italian CD version

There's also a rare Italian CD version of this game.
How can I contact or PM the author?

### Describe the possible solution

Support the Italian CD version too, using Italian original localization?

**Comment by ihhub** [comment]
Hi @Hexaae , this is interesting. I haven't known that such version exists😀 To support it we definitely need your help. Are you familiar with programming?

**Comment by ihhub** [comment]
@Hexaae , you can discuss here or message in our Discord server🙂
