### ISSUE TITLE
Adventure map, vertical position of neutrals is off py 2 pixels

### ISSUE THREAD

**Issue by a1exsh** [ihhub/fheroes2#4313]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

In fheroes2, the neutral monsters are rendered 2px down compared to the OG.

OG:
![image](https://user-images.githubusercontent.com/489601/135761923-d55453be-06fd-4a47-bb49-2f16b0a3d0cb.png)

fheroes2:
![image](https://user-images.githubusercontent.com/489601/135761483-b0cd6f7b-2230-46b9-8e91-548b9ec0bbb2.png)

Difference:
![map_monsters_2px_diff1](https://user-images.githubusercontent.com/489601/135761528-01c13931-4d82-4b81-9905-b6e6778e8d06.png)

Shifting by two pixels **up** puts the monsters on the same position as in the OG:
![image](https://user-images.githubusercontent.com/489601/135761870-4ed1bc8a-e2da-4048-a296-5681c6971b92.png)

### Save file

Start any scenario.  Here we see the initial setup from "Arrax the Jerk"

**Comment by Branikolog** [comment]
Hi,  @a1exsh 
I think the issue is similar to this one: #3186
