### ISSUE TITLE
Some human castle buildings are not interactable.

### ISSUE THREAD

**Issue by AAS** [ihhub/fheroes2#4331]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In human castle you cannot click (and open appropriate dialog window) on thieves' guild or marketplace. 
There is a problem with mages guild too, clicking on it opens tavern if it is overlapped with mages guild sprite.
Look like some z-order issue.

### Save file

[AUTOSAVE.zip](https://github.com/ihhub/fheroes2/files/7295474/AUTOSAVE.zip)

**Comment by Branikolog** [comment]
Hi, @AAS !
I believe, the issue you've found is the same to 
https://github.com/ihhub/fheroes2/issues/4257
Correct me, if I'm wrong.

**Comment by Branikolog** [comment]
@AAS 
No problem.
There're so many issues opened, even old members forget if there exists something similar. :) Thanks for your contribution anyway! ;)
