### ISSUE TITLE
Battle screen, Medusa's "Petrification" requires a new icon

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4336]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Currently we have a original icon for this effect. But its design is poor and ugly
![image](https://user-images.githubusercontent.com/55348946/136407568-bb30effc-ee61-454c-bd73-e1ceefafa821.png)
We also need this icon to be shown in spell description window:
![image](https://user-images.githubusercontent.com/55348946/136410122-b964de9e-227f-41cc-b79a-660d63086c27.png)

### Describe the possible solution

A nice starting issue for an artist.
An icon should be created using Heroes 2 palettes. It can look, for example, like some sort of stone object or similar to current implementation figure made of stone. Also, it can be a picture of medusa's face, as the effect is inspired by the medusa's ability to turn creatures into a stone.

**Comment by cxong** [comment]
[Archive.zip](https://github.com/ihhub/fheroes2/files/7633139/Archive.zip)
icons in bmp / zip
![image](https://user-images.githubusercontent.com/1083215/144220829-2b98397e-297a-4c3b-8773-06bfdd901e15.png)

**Comment by ihhub** [comment]
Hi @1GodRage , so-called "stone" effect must be most in contrast with black image. Also you can try to apply such effect from bottom to top like covering legs only (see Slow spell).

**Comment by zenseii** [comment]
Hi @1GodRage , as @ihhub mentioned:
> I would insist not to use the exact blind icon as it might lead to licensing issues but I see no issues to try something new.[...]

we can't make the new icon by editing an original Heroes 2 one and share this with fheroes2, since that would amount to copyright infringement. I hope this doesn't put you off doing this since you're really good, but this is just something we have to be very careful about.

**Comment by Branikolog** [comment]
Hi, @1GodRage !
Really impressive. I like the concept of making icon similar to slow/haste icons. (It's not so far from the original icon). The second attempt (slow-like one) looks good. At the same time the last one has more uniqueness, which is nice - it would be more recognisable for players.
I personally would prefer a bit more brighter gray pixels, as dark ones look close to black. 
The pose of the last picture looks kind of friendly. :) Could you, please, add some attacking/defending mood? Or some anxiety? :D

**Comment by Branikolog** [comment]
Hi, @1GodRage 
Heh, so much nice artwork! :) I love the most the one, where a man is holding his old favourite shirt full of holes. :)
The icon is even better, but I'm still felling it's kind of static... Like a shadowman is holding a sword (he found on a sale) and was stunned accidentally (by the price he saw on it).
Could you please make him showing us more action? Making a step? Attacking someone? Or being hit by someone?
Here's some inspiration images, that came to my mind:
![Figures](https://user-images.githubusercontent.com/55348946/191045001-7f38c6d6-0af5-4265-ae46-fd1b6e69941b.png)

**Comment by ihhub** [comment]
Hi @cxong , could you please try an idea to show stoning effect only for the lower part of the body? Per my opinion it is not obvious that this icon stands for.

But overall a really impressive work so far!

**Comment by ihhub** [comment]
Sorry, I meant @1GodRage :(

**Comment by Branikolog** [comment]
Hi, @1GodRage .

>So, if "stoned" is only cast by medusa, fear attitude or any action-like is fine,

It will happen as you're saying. We're not going to implement such spell available for a hero. Only as a creature special ability.

In a case there were a small splats of stone on a body more brighter looked better. But in current implementation (50% stoned) I think darker gray would be ok.


> ![h3sprite](https://user-images.githubusercontent.com/63362446/191335141-60b8f67a-0a2b-4051-b008-e48252d9d818.png)

Actually, I like this crusader-like shadow. ) Previous shadowman has some issues with body proportions.
I personally would take H3 shadowman, change his helmet for a head (probably looking down) and cover 40% of lower body with stone (up to middle of the rised thigh). But, Probably this concept looks a bit higher quality comparing to the original art. What do you think?

**Comment by zenseii** [comment]
> Hmmmm about head direction, maybe, instead of eyes, adding a nose... 🤔

I think these look great! In my opinion the numbers 27 and 28 look best because the shape of the shield is better and the arm holding it seems more proportioned.

**Comment by ihhub** [comment]
I vote for number 28. If we have no big objections then we can even integrate such icon in the upcoming release.

**Comment by zenseii** [comment]
> 29: I changed a bit the sone effect of the 28

**Comment by ihhub** [comment]
> I will need some indications for the upload of the image.

Hi @1GodRage , you can just pass the original image in PNG or Bitmap format and I will do the rest of the work. We have to convert this image into fheroes2 image format and store it inside resurrection.h2d file which is shipped with the engine.

**Comment by Branikolog** [comment]
Hi, @1GodRage 
Sorry, for the late response. 
This icon look really much better! I love new shield and the pose itself.
I'm only concerning about the wideness of the icon. Doesn't it much wider, than all original icons? @ihhub , what do you think, would there be an issue within game UI with such big icon? If so the sword could be shortened or positioned more vertically.
Anyway, you've made a great job, @1GodRage ! The icon is definitely looking H2-ish. 
I'd also like to see the transition more spread, like in disrupting ray icon (sparse gray pixels could reach a bit higher level), but I'm not sure it'd look better to be honest.

**Comment by ihhub** [comment]
Hi @Branikolog , there is no limit for icon size. For example, FireBlast spell has icon of 52 x 40 pixels size. Mirror Image spell is 66 x 41 pixels so the proposed icon is absolutely fine by size.

**Comment by Branikolog** [comment]
@1GodRage 
Wow, you're fast.)
Gray pixels raised a bit higher, than I've expected, but now I cannot tell which work is better. Maybe something between these both would be ok? )
Something like that...
![Stone](https://user-images.githubusercontent.com/55348946/192993182-587228b2-5cb4-4001-89a6-f50ba6756212.png)
Anyway, I'm OK with both your previous icons, @1GodRage . :)

**Comment by zenseii** [comment]
In my humble opinion 29 looked better since the few single pixels gives it more of a dithered effect, while 30 and the one @Branikolog posted makes me focus on the single gray pixels and this makes it look like there are separate gray spots/stains instead of it being a gradual continuous transformation into stone. It gives somehow an impression that you got hit by many droplets of a gray paint/liquid, like how ketchup could do.

Those are just my thoughts.

**Comment by ihhub** [comment]
![image](https://user-images.githubusercontent.com/19829520/193065214-15a2a3f8-1961-4d69-8bbb-4b2714f0910c.png)

but we need to create a smaller icon for Monster dialog which should be not bigger than 32 x 32 pixels as other icons for this dialog.

**Comment by ihhub** [comment]
@1GodRage , well done with the small icon! I will provide a screenshot how it would look in the game and if no objections from other team members we would go with this solution.

**Comment by Branikolog** [comment]
Hi. @1GodRage , @ihhub .
I personally like 31 more, as it looks closer to the original.  32 and 33 are too tiny and disproportioned a bit.
I think adding 1 pixel to a sword's length will look better.
If we compare original haste icons, they look similar, but the sword is shorter.
