### ISSUE TITLE
Passability bugs on Arrax the Jerk map

### ISSUE THREAD

**Issue by lleonis** [ihhub/fheroes2#4339]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

Two locations on _Arrax the Jerk_ map are not passable. This makes half of the map unreachable and impossible to win without Summon Boat or Dimension Door. Screenshots from OG showing problematic paths:
![arrax1](https://user-images.githubusercontent.com/91083784/136444166-e7d71aed-3ab3-4ff1-9edc-514386b29fa5.png)
![arrax2](https://user-images.githubusercontent.com/91083784/136447642-6de6aaf5-be47-484f-9302-f606d7a19226.png)

### Save file

[savefiles.zip](https://github.com/ihhub/fheroes2/files/7306238/savefiles.zip)

**Comment by ihhub** [comment]
The first passability issue is fixed.
