### ISSUE TITLE
GetMaxMode:  GetMaxMode: no modes available; Init:  data files not found; Load:  Couldn't open sdl_logo.png

### ISSUE THREAD

**Issue by 512yottabytes** [ihhub/fheroes2#4343]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

Hello,
I'm trying to launch fheroes2. I've copied files from CD to `~/.local/share/fheroes2`, but it doesn't work.
```
/usr/games/fheroes2 
19:01:52: [ERROR]	GetMaxMode:  GetMaxMode: no modes available
19:01:52: [DBG_ENGINE]	Init:  data files not found
19:01:52: [ERROR]	Load:  Couldn't open sdl_logo.png
19:01:52: [VERBOSE]	main:  
# fheroes2 config, version: 0.6.0000
data = 
videomode = auto
sound = off
music = off
sound volume = 6
music volume = 6
fullscreen = off
alt resource = off
debug = on
fonts normal = dejavusans.ttf
fonts small = dejavusans.ttf
fonts normal size = 15
fonts small size = 10
unicode = off
```

### Save file

-

**Comment by 512yottabytes** [comment]
I'm using fheroes-pkg installed via `apt install fheroes2`.

**Comment by undef21** [comment]
fheroes2-pkg build game from very very old sources from sourceforge.net.
This project is fork of that project. You should get prebuild binary from this site or build from source

**Comment by undef21** [comment]
Yes this version more recent and support original and addon campaigns. Also this version have a lot  another improvements.)
