### ISSUE TITLE
Please add support for resolutions less than 640x480

### ISSUE THREAD

**Issue by Wolod** [ihhub/fheroes2#4346]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Hello and thanks for your hard work!

I'm trying to play fhereos2 on a Chinese handheld console with a 3:2 screen that works in a 480x320 resolution. This resolution is the only available option when I run fheroes2 on my device. Game works completely fine but different crucial UI elements are hidden behind the screen. For example I can't start a new campaign or do different things inside my castle.

On the other hand I tested original HoMM2 in the dosbox pure emulator on my console and everything scaled properly.

Here's how incorrect UI scaling looks on my device.

![IMG_20211009_143239](https://user-images.githubusercontent.com/5695929/136656482-0c80f959-f67d-4e99-9ad0-7ebe30f83625.jpg)
![IMG_20211009_143305](https://user-images.githubusercontent.com/5695929/136656486-6e826ab9-8948-4ebf-bff1-8bfa262dc623.jpg)
![IMG_20211009_143335](https://user-images.githubusercontent.com/5695929/136656483-a448c222-8973-47b3-af09-2d411bccfa4d.jpg)
![IMG_20211009_143537](https://user-images.githubusercontent.com/5695929/136656484-4d528649-5214-4489-95f5-cf1b3f66c043.jpg)
![IMG_20211009_143458](https://user-images.githubusercontent.com/5695929/136656485-db5c31e3-2988-46ee-8183-0acb9c3f2e7d.jpg)

### Describe the possible solution

I think my issue is related to the fact that minimal resolution that fheroes2 support is 640x480.

### Additional info

My device is called Anbernic RG351P and I use ArkOS firmware that is based on Ubuntu. So basically I'm trying to play Ubuntu version of fheroes2 on my console.

**Comment by ihhub** [comment]
Hi @Wolod , we aren't going to support any resolutions lower than the original 640x480.

**Comment by Wolod** [comment]
Sad to hear that. Anyway thanks for the quick response @ihhub !

**Comment by ihhub** [comment]
Hi @Wolod , please try the latest snapshot in about an hour from now. The compilation should be done.

**Comment by Wolod** [comment]
Hi @ihhub , UI scales properly now but the cursor is invisible. My friend compiled it from the source. He used cmake v.3.13.4, so that's might be the reason because minimum required is v.3.14. He'll try to recompile it on a newer version of cmake.

**Comment by a1exsh** [comment]
@Wolod just for fun, can you post the photos of scaled UI?

**Comment by romadu** [comment]
The fix works on linux handheld game devices. **Please note** that this line means that gamecontroller is **only** initialised on Vita or Switch, so this #ifdef needed to be removed to allow game controllers to work on linux handheld and other devices with game controller support. 
Perhaps game controller support can be made generic, if sdl2 is supported. https://github.com/ihhub/fheroes2/blob/c79c9866f821a92b73622aadf2cff45d2d98e2ae/src/fheroes2/game/fheroes2.cpp#L150
