### ISSUE TITLE
Main menu music issue

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#435]
After entering load menu, world soundtrack continues playing until you press cancel button.
![Menu music](https://user-images.githubusercontent.com/55348946/80708929-258f7280-8af5-11ea-8ad2-02c40ac6bfd4.jpg)
![Menu music1](https://user-images.githubusercontent.com/55348946/80708935-27593600-8af5-11ea-9052-21141ef561d1.jpg)
![Menu music2](https://user-images.githubusercontent.com/55348946/80708941-27f1cc80-8af5-11ea-88b8-5ac3185c79cd.jpg)

**Comment by ihhub** [comment]
Hi @Branikolog , are you saying that a sound track is still playable in main menu which is on your third screenshot?
