### ISSUE TITLE
No more ARM support?

### ISSUE THREAD

**Issue by Grondoval** [ihhub/fheroes2#4353]
### Your question

I have 0.8.4 version that have arm support. 

But in newer versions says ubuntu arm and latest says only ubuntu.

Any differences??

I want to use it on a raspberry pi 4...

**Comment by ihhub** [comment]
Hi @Grondoval , you can compile the game by yourself if you follow [this instruction](https://github.com/ihhub/fheroes2/blob/master/docs/DEVELOPMENT.md). The servers responsible for ARM build are no longer available for we don't provide built packages.

**Comment by ihhub** [comment]
I think it's not worth it at all. We shouldn't spend any efforts right now to add such feature. I'm moving it to post 1.0 launch.

**Comment by ihhub** [comment]
Fixed in #6246.
