### ISSUE TITLE
Castle defenders pop-up position of troops / text

### ISSUE THREAD

**Issue by a1exsh** [ihhub/fheroes2#4367]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

The positioning of troops and text in the castle defenders pop-up window seems to be off, touching the bottom border:
![image](https://user-images.githubusercontent.com/489601/136707168-aa641212-91a1-4c72-b442-f61db00e4d9f.png)

### Save file

[The_Clearing_0055.zip](https://github.com/ihhub/fheroes2/files/7317923/The_Clearing_0055.zip)

**Comment by zenseii** [comment]
I'll have a go at this one.
