### ISSUE TITLE
Archibald 7 scenario missing starter bonus

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4379]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In the OG in this scenario player should have 5th level hero (with 5000 exp. plus random secondary skills) and some army.
For Necromancers:
![image](https://user-images.githubusercontent.com/55348946/136754949-0fdefbc0-10e2-459a-8069-533b2201830b.png)
For Warlocks:
![image](https://user-images.githubusercontent.com/55348946/136757206-53fc4717-19d2-4c76-9063-e2bec1532436.png)
For Barbarians:
![image](https://user-images.githubusercontent.com/55348946/136757292-1043ab7b-c2b3-4009-8313-a22bb1113c83.png)

### Save file

[Evil_6_Complete.zip](https://github.com/ihhub/fheroes2/files/7320773/Evil_6_Complete.zip)

**Comment by a1exsh** [comment]
@Branikolog now I get why it's so hard for me to get past this scenario %)
