### ISSUE TITLE
Obelisk status after digging artifact up

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#438]
After digging ultimate artifact up all obelisk show "Already visited" status. Even those, you haven't visited before.
Actually, i'm not sure how it works in original game...
![Obelisk](https://user-images.githubusercontent.com/55348946/80715223-bb7bcb00-8afe-11ea-84e0-9e62dc525c37.jpg)

**Comment by idshibanov** [comment]
Obelisk status does not change on OG after digging up the artifact. However I think current behavior is an actual improvement over the original logic.

**Comment by LeHerosInconnu** [comment]
For my part, I would prefer that the text displayed really reflects reality as in the original game.

If an obelisk has not yet been visited and the Ultimate Artifact has already been recovered by the player visiting the obelisk (and not when it's another player that has recovered the Ultimate Artifact) this should be indicated:

"Obelisk

(not visited)
(Ultimate Artifact already recovered)"

Also, in the future of the game, a mission or a quest may be envisaged for which the player must visit all obelisks on the adventure map to receive a reward, and it would be difficult in this case to remember which obelisks have already been actually visited.

**Comment by Arthusppp** [comment]
Hello @LeHerosInconnu, @Branikolog, @ihhub and all,

Based on what you have stated above, below is my proposition. In short: I propose to add an "artifact not found"/"artifact found" label and after an artifact is found, the puzzle map presents its content based on how many obelisks were visited by a player. Please let me know what do you think.
[Also the link to my branch.](https://github.com/Arthusppp/fheroes2/commit/84d439b124c0d2626b39eceae7b2d49758fdcd15)

Before a player finds an ultimate artifact:
![01_obelisk visited, artifact not found](https://user-images.githubusercontent.com/85434237/127753455-2310a207-c2f4-4dc4-b472-0dc9223239f6.png)
![02 obelisk not visited, artifact not found](https://user-images.githubusercontent.com/85434237/127753456-3cded36d-04c0-43a1-a931-e832fd179f63.png)

After a player finds an ultimate artifact:
![03_obelisk visited, artifact found](https://user-images.githubusercontent.com/85434237/127753462-dae03f45-c973-4a81-a909-22f2799e2c0a.png)
![04_obelisk not visited, artifact found](https://user-images.githubusercontent.com/85434237/127753463-2cd1360a-5f3e-40af-ae11-c2ad5e53d55c.png)
![05_puzzle after artifact found](https://user-images.githubusercontent.com/85434237/127753464-750f337c-a8fc-46d9-8f02-e15d29a653b6.png)

**Comment by Branikolog** [comment]
Hi, @Arthusppp 
Probably, this could be a solution. I'm not sure about the text itself, though.
I also suggest to show the status of successfully found artifact only. To make this window look less messy (while showing "not found" line), as I really don't like how three lines of text is looking. Especially two of them in parentheses.
P.S. It looks like this issue should be transformed into duscussion. :)
