### ISSUE TITLE
Combat, AI places shooters next to hero's army while maneuvering

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4382]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

![image](https://user-images.githubusercontent.com/55348946/136782628-521ee43b-36a1-4f61-b791-dc50ec3ee143.png)

AI places Grand Elves next to Gargoyles, when there's lots of more proper things to do.

https://user-images.githubusercontent.com/55348946/136783178-49fe7e5a-4cf2-4839-a257-1b5233a2961d.mp4

Related closed issue: #3634

### Save file

[Dumb AI.zip](https://github.com/ihhub/fheroes2/files/7321985/Dumb.AI.zip)

**Comment by ihhub** [comment]
Hi @Branikolog , could you please verify this issue again since we've done many change in pathfinding?

**Comment by Branikolog** [comment]
@ihhub Hi!
I'll try, but you know, it's not so easy to make AI shooters maneuvering. :)

**Comment by Branikolog** [comment]
@ihhub 
I haven't experienced this issue for more than a year. I believe it is completely gone.
