### ISSUE TITLE
Combat screen, sometimes it is difficult to switch back to manual mode when Auto combat mode has been activated

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4387]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, sometimes it is difficult to switch back to manual mode when Auto combat mode has been activated, the click does not always seem to be taken into account.
I also made a suggestion about this: https://github.com/ihhub/fheroes2/discussions/4385.

In fheroes2:

![Auto combat button 02](https://user-images.githubusercontent.com/43583994/136807758-7dbf5b73-1281-48c9-82ee-289abd238c15.png)

![Auto combat button 01](https://user-images.githubusercontent.com/43583994/136801667-5633b6ed-eb18-4c88-b2aa-9b37c19a897d.png)

Try to switch to manual mode towards the end of the combat.

### Save file

Here is the save file:
[Before last combat 01.zip](https://github.com/ihhub/fheroes2/files/7323060/Before.last.combat.01.zip)

### Additional info

Version 0.9.8 4311

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu 
Small precision:
It seems to me that turning off is initiated only by clicking back on "AUTO" button, while in the OG we can click wherever  we like.
Also want to note, that both right and left clicks should work for that.

**Comment by slawomir-witkowski** [comment]
You cannot stop auto-combat when oponnent's units are in control. 
You can toggle auto-combat by pressing A. But when you press ESC, you get a confirmation dialog.
