### ISSUE TITLE
Scenario selection window, description not displayed fully

### ISSUE THREAD

**Issue by a1exsh** [ihhub/fheroes2#4391]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

OG:
![heroes2_001](https://user-images.githubusercontent.com/489601/136814887-cccf059e-7a88-4de2-a825-4c6d591ed0b7.png)

fheroes2:
![Screenshot from 2021-10-11 17-21-00](https://user-images.githubusercontent.com/489601/136815526-595436f4-4f03-45b6-b816-798d47cb6964.png)

### Save file

No save file needed.

**Comment by ihhub** [comment]
The problem is in `void ScenarioListBox::RedrawBackground( const fheroes2::Point & dst )` method where we use
```cpp
TextBox box( info.description, Font::BIG, 290 );
box.Blit( dst.x + 45, dst.y + 320 );
```
code for the map's description. We must use `fheroes2::Text` which must handle this situation correctly.
