### ISSUE TITLE
Show game info hotkey: scenario vs. campaign

### ISSUE THREAD

**Issue by a1exsh** [ihhub/fheroes2#4407]
### Your question

When playing a campaign, the `INFO` button brings the "Campaign info" window both in OG and fheroes2:
![image](https://user-images.githubusercontent.com/489601/137121596-7df178e5-ff3c-4dd8-810d-9e4de08b2043.png)
![image](https://user-images.githubusercontent.com/489601/137121635-43338849-af85-4dc9-a0d0-b95f0ae0e5fb.png)

The **hotkey** for the same button (by default `I`), brings the other scenario info window:
![image](https://user-images.githubusercontent.com/489601/137121809-9c0eb60b-30ce-4142-887f-3f12039305ab.png)

In OG, both the UI button and the hotkey show the "Campaign info" window.

I see the usefulness of the `CONFIG` button in the normal info window, and there is not much space to add this button to the "Campaign info", but it feels odd that there is no consistency.  Not sure what to do here at the moment.

**Comment by ihhub** [comment]
Let's go with consistency first and then add config option later.
