### ISSUE TITLE
Campaign info window, "VIEW INTRO" button doesn't have "pressed" state

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4409]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Button doesn't change when we press, "VIEW INTRO".
![image](https://user-images.githubusercontent.com/55348946/137150659-dc4d9ed4-e31d-4896-8e84-159268ed6280.png)

### Save file

Start any campaign and check scenario info.

**Comment by pflugs30** [comment]
@Branikolog I believe that image failed to upload.

**Comment by pflugs30** [comment]
> Anyway, We cannot hide buttons, as they are a part of the window itself. (Well, we can, but it really not easy task) So disabled button seems natural and easy solution here.

It seems that hiding a button is possible and relatively straight-forward.  In fact, that's how we don't show the **RESTART** button until post-launch: `buttonRestart.hide();`

I appreciate the response, and the logic makes sense.  I will create a PR for the fix to keep this change small and tight.
