### ISSUE TITLE
Attacking cursor issue

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#441]
While standing really close to foes with no movement points left, cursor, pointed foes, doesn't show "2" (days counter) 
![Cursor](https://user-images.githubusercontent.com/55348946/80806574-b3399380-8bc3-11ea-983d-297e2357ce49.jpg)
![Cursor1](https://user-images.githubusercontent.com/55348946/80806577-b5035700-8bc3-11ea-87dd-4e3a0307e32f.jpg)

**Comment by Branikolog** [comment]
Happens while hero stands without movement points in a cell, too close to creature.

**Comment by ihhub** [comment]
Hi @Branikolog , could you please check this issue again after we fixed path calculation code?

**Comment by Branikolog** [comment]
This problem, unfortunately, is still actual.
