### ISSUE TITLE
Combat screen, info windows are missing for buttons in Combat screen and System Options window

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4416]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, info windows are missing for buttons in Combat screen and System Options window.
For the Customize System Options window, the text in the info bar at the bottom of the screen should also change (display the window title) when the player positions the mouse cursor (without clicking) over the different buttons (instead of always indicating "Customize system options").

In original game:

![Combat missing windows 001](https://user-images.githubusercontent.com/43583994/137288808-41239ad1-6e3f-4288-bbe5-8363d58b45d2.png)

![Combat missing windows 002](https://user-images.githubusercontent.com/43583994/137288831-09d5595f-abf0-49d9-a276-d6e289e642c5.png)

![Combat missing windows 003](https://user-images.githubusercontent.com/43583994/137288866-b0c014ef-8c17-4114-99ff-c68573ebaf5e.png)

Don't forget the info window for the "WAIT" button. :)
In fheroes2:

![Combat missing windows 004](https://user-images.githubusercontent.com/43583994/137288922-0071b5f6-820a-4011-8603-fac01735b848.png)

In original game:

![Combat missing windows 005](https://user-images.githubusercontent.com/43583994/137289354-1dabfd05-c22e-4e0d-bce2-806cfbcfbe07.png)

This is not yet present in fheroes2.
![Combat missing windows 006](https://user-images.githubusercontent.com/43583994/137289374-f9229792-b0b4-451a-9747-4828ee6ecfb3.png)

![Combat missing windows 007](https://user-images.githubusercontent.com/43583994/137289388-e7d8aad4-750f-458a-8b51-3ca4fd8d858a.png)

![Combat missing windows 008](https://user-images.githubusercontent.com/43583994/137289408-23d928cd-b079-4e97-b182-a14dbfeb961b.png)

The sentences for the performance of the computer should certainly not be necessary anymore. :D
![Combat missing windows 009](https://user-images.githubusercontent.com/43583994/137289427-2b090cec-c10b-491d-a796-211ceb21262e.png)

Same here, for the sentences for the performance of the computer.
![Combat missing windows 010](https://user-images.githubusercontent.com/43583994/137289446-1179d089-b2ce-4cb3-a26c-20d70eb3c7fa.png)

The title should be "Okay" instead of "OK".
![Combat missing windows 012](https://user-images.githubusercontent.com/43583994/137289478-f9410b2b-689a-4674-8397-271b0f101cf1.png)

I also suggest capitalizing the first letter of the words "Combat" ("Auto Combat" instead of "Auto combat"), "System" and "Options" and deleting the dot "." at the end of the line of text ("Customize System Options" instead of "Customize system options.") in the info bar at the bottom of the screen.

In fheroes2: 

![Majuscule 01](https://user-images.githubusercontent.com/43583994/137295433-702af30a-91ec-4460-8684-04fa40a1a743.png)

![Majuscules 02](https://user-images.githubusercontent.com/43583994/137295448-0ba4ea3d-2f13-457f-a975-3cfb5b41b043.png)

### Save file

Not needed.

**Comment by LeHerosInconnu** [comment]
Hello @pflugs30,

> @ihhub @LeHerosInconnu I'd be willing to take this issue. I believe I understand how to do it, and I think it would be a fun next UI issue. I'm not able to self-assign through this issues page. Is that a permissions restriction, or is there another way?

I'm not familiar with how this works, I think you have to wait for @ihhub or @Branikolog or @oleg-derevenetz to assign you, but nothing prevents you from working on the PR in the meantime. :)

**Comment by ihhub** [comment]
Hi @pflugs30 , sure, you can take it. Only collaborators and admins of this project are able to manage issues like assignment of people or setting labels.

**Comment by pflugs30** [comment]
@LeHerosInconnu I know what you mean about being consistent on our casing.  That being said, I briefly looked through the `battle_interface.cpp` file, and I found that we are mixing several different casing strategies.  For example, we currently have `Skip this unit` and `Hero's Options`.  To make matters more confusing, we also have several messages and phrases that use a trailing period, such as `%{attacker} do %{damage} damage.`

I certainly support having a consistent standard.  For battle logs and message bar text, I'd propose the following:

* Capitalize the first letter of the phrase or sentence.
* Capitalize all proper nouns. (i.e. the names of a Player, Spell or Monster/Troop)
* Do not capitalize other words in the phrase or sentence. (i.e. `Wait this unit` is correctly cased).
* Do not use trailing periods for hover messages. (i.e. `Skip this unit`)
* Do use trailing periods for persistent battle log messages. (i.e. `The %{spell} does %{damage} damage.`)

However, I think the rules regarding headers used for dialog boxes would be different.  For instance, I think it does make sense to capitalize all specific words (such as `Shadow Movement` or ` Monster Info`), but do not capitalize minor words, such as "the", "of", or "this".

Any thoughts?  I'm happy to document these in any location where we keep standards.  While changing these hover tips, I'll review the log messages and dialog headers.

**Comment by LeHerosInconnu** [comment]
Hello @pflugs30,

> @LeHerosInconnu I know what you mean about being consistent on our casing. That being said, I briefly looked through the `battle_interface.cpp` file, and I found that we are mixing several different casing strategies. For example, we currently have `Skip this unit` and `Hero's Options`. To make matters more confusing, we also have several messages and phrases that use a trailing period, such as `%{attacker} do %{damage} damage.`
> 
> I certainly support having a consistent standard. For battle logs and message bar text, I'd propose the following:
> 
> * Capitalize the first letter of the phrase or sentence.
> * Capitalize all proper nouns. (i.e. the names of a Player, Spell or Monster/Troop)
> * Do not capitalize other words in the phrase or sentence. (i.e. `Wait this unit` is correctly cased).
> * Do not use trailing periods for hover messages. (i.e. `Skip this unit`)
> * Do use trailing periods for persistent battle log messages. (i.e. `The %{spell} does %{damage} damage.`)
> 
> However, I think the rules regarding headers used for dialog boxes would be different. For instance, I think it does make sense to capitalize all specific words (such as `Shadow Movement` or ` Monster Info`), but do not capitalize minor words, such as "the", "of", or "this".
> 
> Any thoughts? I'm happy to document these in any location where we keep standards. While changing these hover tips, I'll review the log messages and dialog headers.

All of your proposals are okay for me. :)
Just wait a bit for the other team members to see if it's ok and if there is something else to add.

Regarding "Hero's Options", I think it should be considered as a title and stay with the word "Options" capitalized.
For example, there is also "Hero Screen" for the hero's window opened from the "Hero's Options" window.

In fheroes2:

![Hero's Screen 004](https://user-images.githubusercontent.com/43583994/137581460-3d53b9a1-fee4-4ac7-852b-7ce383da6c6d.png)

![Hero's Screen 001](https://user-images.githubusercontent.com/43583994/137581306-d151757d-bd01-48ae-b3d9-fbd94a9747cd.png)

![Hero's Screen 002](https://user-images.githubusercontent.com/43583994/137581319-ef5db41b-555a-454c-bb19-874251da2799.png)

![Hero's Screen 003](https://user-images.githubusercontent.com/43583994/137581330-6849fc2e-efc3-41fc-b784-415922e71fd2.png)

In the case of "Skip this unit", "Skip" is the "real" title of the window, "this unit" was added for the player's understanding (in the info bar at the bottom of the screen) when the player positions the mouse cursor over the button without performing a right click.
It should be the same for the case of the "Wait" button, the title of the window should be "Wait", the part of the sentence "this unit" is also there only for the understanding of the player in the info bar at the bottom of the screen.

**Comment by pflugs30** [comment]
> Regarding "Hero's Options", I think it should be considered as a title and stay with the first letter of the word "Options" capitalized.

From that perspective, I agree that we would capitalize both words.  However, I had another thought when I woke up this morning.  Several of the popup messages follow a "{Verb} {Noun}" pattern, such as "Skip this unit" or "Customize system options".  In the case of "Hero's Options", that's not consistent with the other buttons.

In general, when making standards, I prefer consistency more than anything.  As such, I propose we change these popup hints to the User to indicate the **action** that will be taking by clicking the button.  Then, I'd recommend we change "Hero's Options" to "View Hero's options".  I'm sure there are a few others to tweak to make consistent.

Thoughts?

**Comment by LeHerosInconnu** [comment]
Hello @pflugs30 and @Branikolog,

> > I did not advocate changing the titles of all dialog screens to the "{Verb} {Noun}" pattern
> 
> I think it was a slight misunderstanding from @LeHerosInconnu here. :)

Yes, I confused your "popup hints" with the info window when it was the info bar at the bottom of the screen. :)

> @Branikolog @LeHerosInconnu please see the draft PR at #4456. I have several more commits to add.
> 
> It's worth noting that I added a few English words, like "view" and "enable". Those changes may require some translations. I also changed the casing and removed trailing periods in some phrases, thus making the messages look different from the OG.
> 
> I mention that here because on [another recent PR](https://github.com/ihhub/fheroes2/pull/4436#pullrequestreview-782266135) I made some similar changes and @ihhub asked me to revert them. If there's any feedback as to when we want to correct any inconsistencies from the OG and when we want to leave them, then I'd love to hear it so I don't cause any rework. :-)

I looked at your draft PR, it's okay for me (for now). :D
