### ISSUE TITLE
AI behaviour, AI shouldn't leave town marked as victory condition empty

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4418]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

There're lots of scenarios where player should capture enemy town. Currently AI can take the whole army out of the town and easily be vanished, if player is tricky to sneak into it.

### Describe the possible solution

AI should consider himself, in which cases he can take the whole army from a city.

**Comment by Pandi-gh** [comment]
Just ran into a similar problem.
Situation: I am with a glass cannon army stand within 6 steps of the crucial castle ai , a direct assault against a hero with an army is doomed to failure as the towers destroy my army in 2 turns. And on the next turn, the hero carelessly leaves the castle, becoming easy prey in the field without the cover of the towers and leaving the garrison in the castle unable to stand even before the towers fire. Moreover, this happened in one move for two castles of two different colors of heroes at once. I checked a similar situation in the original heroes, where the hero sits in a castle for a few turns and accumulates an army until he reaches critical mass and then comes out and kicks my ass.
