### ISSUE TITLE
Invisible monsters preventing hero from passing

### ISSUE THREAD

**Issue by a1exsh** [ihhub/fheroes2#4422]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

The hero cannot pass to the tile immediately East of the cross, because of some monsters spawned nearby (the cursor turns to a sword):
![image](https://user-images.githubusercontent.com/489601/137358233-1ffe17d9-f42f-4473-8baf-7cd0efed0829.png)

The monsters turn out to be liches, spawned not long before.
Similar to this one (because of spawned monsters): #4388 

### Save file

[Good_1_0046.zip](https://github.com/ihhub/fheroes2/files/7347815/Good_1_0046.zip)

**Comment by ihhub** [comment]
Hi @a1exsh , they aren't invisible. They're hidden because they stand behind trees:
![image](https://user-images.githubusercontent.com/19829520/137424455-31f648c8-35b8-41e3-aac3-c3bcc6049fe3.png)

I don't think this is a bug as it's a valid place to put monsters at.

**Comment by a1exsh** [comment]
> Hah, I was looking there but could find them... Normally at least some pixels would be visible when monsters are hiding behind the trees or mountains.

Now looked closer and I can see one pixel showing up and disappearing behind the trees right under the fountain (troop animation). :)
