### ISSUE TITLE
Adventure map, excessive spawn of monster after "week of"

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4427]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

There're too many of monsters spawned after a "week of".
![image](https://user-images.githubusercontent.com/55348946/137457477-506666aa-cd98-405c-b419-7ffecb7ec53e.png)

### Save file

Campaign save file:
[bug_Golem-spawn-Roland.zip](https://github.com/ihhub/fheroes2/files/7352093/bug_Golem-spawn-Roland.zip)

**Comment by idshibanov** [comment]
I believe OG rolls the 1/360 chance for every empty tile. It will be hard to match the spawn 1:1 but I agree that we should adjust it. On a relatively empty L map OG would place ~33 monsters, our version would try to do at least 108.
