### ISSUE TITLE
Russian language related code leads to out of vector access

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#4429]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In this chunk of code:
```cpp
if ( imageArray.size() == 162 && imageArray[121].width() == verifiedFontWidth ) {
    // Engine expects that letter indexes correspond to charcode - 0x20.
    // In case CP1251 font.icn contains sprites for chars 0x20-0x7F, 0xC0-0xDF, 0xA8, 0xE0-0xFF, 0xB8 (in that order).
    // We rearrange sprites array for corresponding sprite indexes to charcode - 0x20.
    imageArray.insert( imageArray.begin() + 0x80 - 0x20, 0xC0 - 0x80, imageArray[0] );
    std::swap( imageArray[0xA8 - 0x20], imageArray[128 + 0xC0 - 0x80] ); // Move sprites for chars 0xA8
    std::swap( imageArray[0xB8 - 0x20], imageArray[161 + 0xC0 - 0x80] ); // and 0xB8 to it's places.
    imageArray.pop_back();
    imageArray.erase( imageArray.begin() + 128 + 0xC0 - 0x80 );
}
```
We check if the size of the vector is equal to 162 but we're accessing elements at position at 192 which obviously leads to an access to out of array.

### Save file

No save file.

**Comment by undef21** [comment]
Sure.

**Comment by undef21** [comment]
Hello @ihhub. I looked at this chunk of code and found no out of array access.
After checking size==162 we add 64 spaces at position 96. Array's size is 226.
Then we remove 2 elements from end and middle. Result array's size is 224.
