### ISSUE TITLE
Campaign info window, number of days spent rendering

### ISSUE THREAD

**Issue by a1exsh** [ihhub/fheroes2#4432]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

Rendering of a bigger number of spent days should be corrected (not touching the border):
![image](https://user-images.githubusercontent.com/489601/137523683-f7a5f78c-5f11-4f44-bbef-8c0c935930c0.png)

Yes, I sometimes spend a lot of time to win ;)

### Save file

[Good_5_Complete.zip](https://github.com/ihhub/fheroes2/files/7354786/Good_5_Complete.zip)

**Comment by a1exsh** [comment]
@seacorn I think there should be a way to calculate the text width in pixels before rendering it — then we can use this value to determine the correct position of the text aligned at the right border.

**Comment by LeHerosInconnu** [comment]
Hello everyone,

> @a1exsh and @seacorn if we need to know the size of the text you can use `w()` method of Text class (old implementation) or `width()` method of fheroes2::Text class (new implementation). The answer for alignment is pretty clear: the same as in the original game.
> 
> @LeHerosInconnu, could you please clarify this issue?

Here are some screens from Roland's campaign.

In original game:

![Roland Campaign 001](https://user-images.githubusercontent.com/43583994/137952312-6a1fea01-296d-40a2-970b-2b242de34221.png)
![Roland Campaign 002](https://user-images.githubusercontent.com/43583994/137952339-eec23855-455f-404f-91ed-dcac7e8deb20.png)
![Roland Campaign 003](https://user-images.githubusercontent.com/43583994/137952355-4752577e-8dd7-4119-b56b-8b26959e2797.png)
![Roland Campaign 004](https://user-images.githubusercontent.com/43583994/137952379-78b8ff4e-a4e8-45fc-a288-684a848ac1e2.png)
![Roland Campaign 005](https://user-images.githubusercontent.com/43583994/137952407-5a498d16-bede-4436-9633-eb9da7e52ea9.png)
![Roland Campaign 006](https://user-images.githubusercontent.com/43583994/137952430-19b2292e-d4d7-45b7-832a-f72ff9d16f0e.png)
![Roland Campaign 007](https://user-images.githubusercontent.com/43583994/137952449-eee382bf-e794-4f95-a5b2-307c1f678f96.png)
![Roland Campaign 008](https://user-images.githubusercontent.com/43583994/137952477-ad24845a-b3cc-4395-8165-bb267d72f77e.png)
![Roland Campaign 009](https://user-images.githubusercontent.com/43583994/137952491-7de823e1-09d2-4a88-abc8-c5456b7c9b98.png)

The horizontal center of the number of days should be positioned at 26 pixels from the inner right yellow frame:
![Roland Campaign rectangle 001](https://user-images.githubusercontent.com/43583994/137952536-83b481a9-de2a-445f-ab64-db2f74e5cccd.png)
![Roland Campaign rectangle 002](https://user-images.githubusercontent.com/43583994/137953009-7b6f13a2-78c0-470e-82f5-e5a27a62e77e.png)

**Comment by seacorn** [comment]
Great! That's all I needed to know :) Thanks @LeHerosInconnu. I would be glad to fix this issue.
