### ISSUE TITLE
Scenario window, title of the "OKAY" button information window should be "Okay" instead of "OK"

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4438]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the title of the "OKAY" button information window should be "Okay" instead of "OK".

In fheroes2:

![Okay scenario 01](https://user-images.githubusercontent.com/43583994/137589701-6f3bef39-9de2-4043-a623-55c8611658fb.png)

### Save file

Not needed.

**Comment by ihhub** [comment]
We have 4 places with OK and only 1 place with Okay. Should we then keep everything the same?

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> We have 4 places with OK and only 1 place with Okay. Should we then keep everything the same?

Yes, all titles should be "Okay" to stay consistent with the other titles like, for example, "Cancel".

In fheroes2:

![Title Cancel 01](https://user-images.githubusercontent.com/43583994/137598050-1d626a91-2f61-4ea3-a14d-aa9fe2167d43.png)
