### ISSUE TITLE
Sailing hero icon

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#444]
There is a small red ship icon near a hero portrait in a case hero entered any boat. In the original demo we don't have any.
![Boat](https://user-images.githubusercontent.com/55348946/80810981-a883fc00-8bcd-11ea-9ac6-4490c08aaabb.jpg)

**Comment by ihhub** [comment]
@Branikolog , shall we remove it then?

**Comment by Branikolog** [comment]
Definitely yes.
