### ISSUE TITLE
Build error .../fheroes2/dialog/dialog_selectfile.cpp:289:43: error: 'unlink' was not declared in this scope

### ISSUE THREAD

**Issue by Zombie-Ryushu** [ihhub/fheroes2#4449]
### Your question

cxx: game_mainmenu.o
../fheroes2/dialog/dialog_selectfile.cpp: In function 'bool SelectFileListSimple(const string&, MapsFileInfoList&, std::__cxx11::string&, bool)':
../fheroes2/dialog/dialog_selectfile.cpp:289:43: error: 'unlink' was not declared in this scope
   unlink(listbox.GetCurrent().file.c_str());
                                           ^
cxx: game_newgame.o
cxx: game_interface.o
cxx: game_startgame.o
cxx: difficulty.o
make[2]: *** [Makefile:67: dialog_selectfile.o] Error 1
make[2]: *** Waiting for unfinished jobs....
../fheroes2/editor/editor_startgame.cpp: In function 'Game::menu_t Game::Editor::StartGame()':
../fheroes2/editor/editor_startgame.cpp:244:8: warning: variable 'selectObject' set but not used [-Wunused-but-set-variable]
     u8 selectObject = 0;
        ^
make[2]: Leaving directory '/builddir/build/BUILD/fheroes-src/src/dist'
make[1]: Leaving directory '/builddir/build/BUILD/fheroes-src/src'
make[1]: *** [Makefile:93: all] Error 2
make: *** [Makefile:23: all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.79192 (%build)
    Bad exit status from /var/tmp/rpm-tmp.79192 (%build)
RPM build errors:

### Additional info

https://file-store.rosalinux.ru/api/v1/file_stores/6b91cd4bf4b081440ded52d0ba24ed4ce25f2069.log?show=true

**Comment by undef21** [comment]
Are you building sources from sourceforge.net? This is ancient unmantained sources.

**Comment by Zombie-Ryushu** [comment]
I built the wrong git branch. I'm sorry. My mistake.
