### ISSUE TITLE
Efficient boat and coast usage by AI

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#4464]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Current AI implementation discourages AI to use boats and come back to coast tiles already visited. Moreover, AI treats boats and coast tiles as action object which at some point makes sense but from another they aren't actions at all.

### Describe the possible solution

 We have pathfinder implementation which depends on pathfinding skill of a hero, his start position and color. We need to remember maximum move points available (`GetMaxMovePoints()`) and the current move points (`GetMovePoints`). During scanning tiles for path we can add 2 cases:
- if a hero is on land and there's an empty boat - reduce as many move point as needed to end the current day
- if a hero is on water and there's a coast tile - reduce as many move point as needed to end the current day

Also remove AI behavior regarding boat and coast, it needs to ignore them as action tiles inside `ai_normal_hero.cpp` file. Such approach will give AI much more freedom to plan its expansion.

This logic must be applied only for AI heroes.

**Comment by ihhub** [comment]
Hi @idshibanov , will you have some time to take a look at this issue?

**Comment by ihhub** [comment]
Marking this as very high priority as we need this logic in order to make AI smart enough to avoid dumb decisions on whirlpools and coast.

@idshibanov , do you have any updates about this?

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , since you're the bravest among us to start digging into hero's pathfinding would you mind to have a look at this issue?

**Comment by oleg-derevenetz** [comment]
Hi @ihhub the pathfinding itself is not an issue, but I'm not very familiar with AI mechanics, so I can't understand yet how exactly these measures should encourage AI to use boats. I'll try to take a look.
