### ISSUE TITLE
No highscore for multiplayer

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4470]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Win multiplayer game by eliminating red player:
![image](https://user-images.githubusercontent.com/55348946/138465215-c507df38-a746-4099-a21c-6ee8ab3ffb09.png)
After that we watch victory animation with dragon and then return to main menu.

### Save file

[Multiplayer score.zip](https://github.com/ihhub/fheroes2/files/7397740/Multiplayer.score.zip)

**Comment by zenseii** [comment]
High scores for multiplayer have been implemented as of this PR I believe:
https://github.com/ihhub/fheroes2/pull/4261

Currently the same high score for single and multiplayer matches is shared, and this is how it works in the OG too.

**Comment by zenseii** [comment]
I'm marking this as improvement since currently fheroes2 works exactly like the original game, and also any extension of this multiplayer high score functionality shouldn't be necessary to prioritized as long as network multiplayer isn't implemented in my opinion.

**Comment by denierlexiese** [comment]
I would also love the scoreboard for multiplayer. I often play hotseat multiplayer over steam's remote gameplay option. There doesn't seem to be any top 10 score listing after the game completes on linux even for 0.9.21.

To play multiplayer on steam, i use a built in steam multiplayer game, like broforce, delete the contents of the steam directory, and add the fheroes2 files, and rename the executable to broforce.  Works like a charm.

**Comment by zenseii** [comment]
Hi @denierlexiese.

Do you have this problem when playing a single player map too? I tested a multiplayer hotseat map not too long ago with 2 players and I was able to end up on the high score because I had enough points. Maybe you're not getting enough points to get to the high score?

Right now we have an issue about not telling the player the score if they don't have enough points to achieve a place in the high scores so this might be confusing: https://github.com/ihhub/fheroes2/issues/2918

I suggest we change the title of this issue to better reflect it.

**Comment by denierlexiese** [comment]
@zenseii just tried hodge-podge single player. Easily got black dragon score on Impossible - entered high score - showed up in high score gui.  Played multiplayer hotseat - expert level 2 player - on ubuntu -  finished in 16 days.  No score - no ranking.  I would imagine it would have at least beat the lowest score of 70.

Either way, both single player and hotseat didn't show the visual score on the dragon breath fmv.  Is there a debug running score showed somewhere else in the game while in game? I thought you guys used to show a running totalunder the 'info' gui in a prior version.

**Comment by denierlexiese** [comment]
_"The easiest way to test is probably to play the official map named Slugfest and set all players to human and remove all the other players troops and heroes"_

@zenseii Just tried that test. Yes on impossible took like 4 days.  No high score screen in hot seat multiplayer in UBUNTU.

**Comment by denierlexiese** [comment]
Just tried with new version 1.0, and still an issue in both windows and ubuntu.  Appreciate all the work you all do.  Multiplayer Hot seat high scores would be great.  Running real time score total in any sub menu would be great too.

**Comment by denierlexiese** [comment]
Small bump. It would mean a lot to my father and I, and only because it was reported to be working before. If it's not a simple fix to restore it, it is what it is and could be de-prioritized for later.
