### ISSUE TITLE
Puzzle map wrong tile rendered

### ISSUE THREAD

**Issue by a1exsh** [ihhub/fheroes2#4476]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

Next to the top-left corner a wrong tile seems to be rendered:
![image](https://user-images.githubusercontent.com/489601/138549564-6d64dc8e-5772-46ab-9304-607117743fd7.png)

### Save file

[Good_8_0026.zip](https://github.com/ihhub/fheroes2/files/7402537/Good_8_0026.zip)

**Comment by ihhub** [comment]
This issue is fixed in #5692 .
