### ISSUE TITLE
Flickering animations in fullscreen mode

### ISSUE THREAD

**Issue by shaman4d** [ihhub/fheroes2#4500]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

I have flickered animations of units, water  (and other thing, they just less noticible) when game in full screen mode. If game in window mode, no matter normal or maximized - all good.

OS: Windows 10 x64 LTSC
GeForce 750M

### Save file

It reproducible in the game independently of  game, map, level or anything else.

**Comment by shaman4d** [comment]
> 
> 
> Hi @shaman4d , which resolutions did you try? Do you notice any slowdowns in the game? What's your machine CPU? Does your GPU have some kind of v-sync technology? If yes did you try to toggle it?
> 
> Please provide more info here as your description is too generic.

Hi I have notebook Dell Inspiron 7737. Here its specs [https://www.wootware.co.za/dell-inspiron-7737-intel-core-i7-4510u-2-0-ghz-17-3-full-hd-led-1920x1080-16gb-memory-8gb-sshd-1tb-5400rpm-hdd-nvidia-geforce-gt750m-2gb-windows-8-1-single-language-64-bit-notebook.html?__cf_chl_captcha_tk__=pmd_7tZWYUmwVXPciGcuqs5x12rgRiNhq0ZwFYAPqHtNOkw-1635772949-0-gqNtZGzNA-WjcnBszQg9#product_tabs_description_tabbed](url)

**Comment by shaman4d** [comment]
> 
> 
> Hi @shaman4d , which resolutions did you try? Do you notice any slowdowns in the game? What's your machine CPU? Does your GPU have some kind of v-sync technology? If yes did you try to toggle it?
> 
> Please provide more info here as your description is too generic.

Yes I've tried to enable v-sync in GPU drivers but it did not affect.

**Comment by shaman4d** [comment]
> 
> 
> @shaman4d, do you have two monitors?

I have one external monitor. And I tried to launch game on notebook monitor and on external one. The issue presented on both.

**Comment by ihhub** [comment]
@shaman4d , can you please try to run the game having just one monitor? Does the issue present?

**Comment by shaman4d** [comment]
> 
> 
> @shaman4d , can you please try to run the game having just one monitor? Does the issue present?

Yes, even I launch game on notebook without any of external monitors issue exists.

**Comment by ihhub** [comment]
Hi @shaman4d , is it possible for you to run a virtual machine and execute fheroes2 from there? The virtual machine should have an emulated GPU. If fheroes2 runs smoothly there then the problem is either with drivers or OS.

**Comment by shaman4d** [comment]
> 
> 
> Hi @shaman4d , is it possible for you to run a virtual machine and execute fheroes2 from there? The virtual machine should have an emulated GPU. If fheroes2 runs smoothly there then the problem is either with drivers or OS.

Excuse me, I dont understand what exactly I have to do? I dont see any link on a virtual machine.

**Comment by shaman4d** [comment]
> 
> 
> Hi @shaman4d , is it possible for you to run a virtual machine and execute fheroes2 from there? The virtual machine should have an emulated GPU. If fheroes2 runs smoothly there then the problem is either with drivers or OS.

By the way, I've checked SDL1 version and there is no such issue with flickering in it!
