### ISSUE TITLE
Adventure map, wrong or missing sounds for some objects

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4506]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Magic Garden has wrong sound. It should have the same to Wagon Camp.
![image](https://user-images.githubusercontent.com/55348946/139050935-0c8117b7-6766-458f-9432-ee398c1d19c8.png)

Observation Tower is missing any sounds: There should be played sound same to Abandoned mine. (FIXED)
![image](https://user-images.githubusercontent.com/55348946/139053718-82fe01b1-434b-4917-9b18-cddec911ee93.png)

Shipwreck survivor is missing sound: while collecting this object we need to play a sound same to Windmill. (FIXED)
![image](https://user-images.githubusercontent.com/55348946/139054562-826408cc-0088-421f-b15a-4cdf3f9ecd7a.png)

Also an artifact being gathered is missing sound: while collecting this object we need to play a sound same to Windmill too. (FIXED)
![image](https://user-images.githubusercontent.com/55348946/139054924-2527986e-cfd6-4ad2-80e6-a038a123b5d6.png)

Watch tower has wrong sound: it should have the sound same to halfling hole.
![image](https://user-images.githubusercontent.com/55348946/139055361-2d8e6cfc-b5fb-423d-9b9a-7b84f2019579.png)

Sound of visiting Hill Fort should be played only if we succeeded in upgrading any troops. If you don't have any proper troops no sound should be played.
![image](https://user-images.githubusercontent.com/55348946/139063818-201ba464-82ec-448e-a2d2-bd8cb493df64.png)

### Save file

[Objects map.zip](https://github.com/ihhub/fheroes2/files/7425675/Objects.map.zip)

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog

> Also an artifact being gathered is missing sound: while collecting this object we need to play a sound same to Windmill too.

Honestly I don't see any difference between OG and fheroes2. OG:

https://user-images.githubusercontent.com/32623900/153765445-c62dff64-3ef7-49fe-9079-9e700f24166d.mp4

fheroes2:

https://user-images.githubusercontent.com/32623900/153765469-6aa99f10-0c49-4f76-a35a-1d8878948788.mp4

So I didn't touch this.

> Shipwreck survivor is missing sound: while collecting this object we need to play a sound same to Windmill.

It seems that this sound is in place as well. fheroes2:

https://user-images.githubusercontent.com/32623900/153765784-f73e2960-d426-49c1-9eb8-56cfe9932baa.mp4

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz 
You're right! Some of issues seem to be fixed since October. Only a few left.
