### ISSUE TITLE
AI behaviour, castle capturing priority

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4507]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Currently AI seems not to be interested much in capturing castles.

### Describe the possible solution

AI should rush capturing castles. We should rise the priority. Especially for the cases, when AI lost all his towns and castles: currently it continues wandering over adventure map, while he should run as fast as he could to capture any close castle without strong guards.

**Comment by idshibanov** [comment]
> Especially for the cases, when AI lost all his towns and castles: currently it continues wandering over adventure map, while he should run as fast as he could to capture any close castle without strong guards.

This case is solved by #5033 .
