### ISSUE TITLE
Adventure map, differences with the way Whirlpools work

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4509]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, there are differences with the way Whirlpools work.
In the original game, the path goes around the Whirlpool to move from a square at the bottom of the Whirlpool to a square at the top of the Whirlpool, while in fheroes2, the path goes directly from the bottom to the top of the Whirlpool.

Also in the original game, if the boat enters the bottom right square of the Whirlpool it ends up in the same bottom right square in another Whirlpool, while in fheroes2, the destination square is random.
This is a problem in some scenarios where the Whirlpool is located close to the land forcing the player to reuse the Whirlpool while it is not the case in the original game.

Also, I think that if this is adjusted to work like in the original game, so when the player uses the space key to reuse the Whirlpool, then this action should cost 2 moves (200 move points (because the hero is on the sea)) to exit and re-enter the Whirlpool at the same square.

And in this case, using the Stone Liths with the space key should also cost movement (as if the hero exits the square of the Stone Liths and re-enters it) the penalty of the terrain where the Stone Liths is located is taken into account as well as the least penalizing terrain penalty for the hero of one of the squares adjacent to the Stone Liths (the hero's Pathfinding skill is also taken into account).

Related discussions: https://github.com/ihhub/fheroes2/discussions/3565, https://github.com/ihhub/fheroes2/discussions/3563 and https://github.com/ihhub/fheroes2/discussions/3562.

In original game:

![Passability test 071](https://user-images.githubusercontent.com/43583994/138717299-1b206cd1-734c-4888-9118-47ceaa5f544d.png)

In fheroes2:

![Passability test 072](https://user-images.githubusercontent.com/43583994/138717310-5335f4be-e4a3-493c-92bc-f520996baa7a.png)

### Save file

Here are the test scenario and the save files (0_9953a2_0002 near Mermaid.sav, Passability near Mermaid.GX1):
[Passability test scenarios and saves.zip](https://github.com/ihhub/fheroes2/files/7411386/Passability.test.scenarios.and.saves.zip)

**Comment by oleg-derevenetz** [comment]
Hi @ihhub I believe it will not close this PR entirely, whirlpool passability issue (the need to make it so that it was necessary to go around the whirlpool to get into another whirlpool tile) still remains.

**Comment by ihhub** [comment]
Yes, I'm still working on it 😞

**Comment by oleg-derevenetz** [comment]
> In the original game, the path goes around the Whirlpool to move from a square at the bottom of the Whirlpool to a square at the top of the Whirlpool, while in fheroes2, the path goes directly from the bottom to the top of the Whirlpool.

BTW it looks like in the OG it is possible to stuck in the whirlpool if it resides too close to the coast.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub @LeHerosInconnu

What's really interesting, when I trying to start the game with the map like this ([WRLTSTX.zip](https://github.com/ihhub/fheroes2/files/7872886/WRLTSTX.zip)):

![Map Editor](https://user-images.githubusercontent.com/32623900/149576895-8c9cb74a-00a3-499b-b1ec-559d1e82dd9c.png)

OG just hangs :) And even if it worked, I believe it would be impossible to get out of the upper tiles of the whirlpool located at the top right. So I believe that current Whirlpool passability rules in the fheroes2 are better than in OG and should be considered as a bugfix.

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz and @ihhub,

> Hi @ihhub @LeHerosInconnu
> 
> What's really interesting, when I trying to start the game with the map like this ([WRLTSTX.zip](https://github.com/ihhub/fheroes2/files/7872886/WRLTSTX.zip)):
> 
> OG just hangs :)

The original program crashes because there is no place to put the Ultimate Artifact (the 9 squares positioning rule from the edges of the map). :)

> And even if it worked, I believe it would be impossible to get out of the upper tiles of the whirlpool located at the top right.

Yes, that's right, the boat could only move east or west.

> So I believe that current Whirlpool passability rules in the fheroes2 are better than in OG and should be considered as a bugfix.

Yes, being able to move to all adjacent Whirlpool squares from each Whirlpool square makes much more sense.
And there are also bugs with the Whirlpool in the original game: https://heroes2.forumactif.com/t171-heroes-2-bugs-stuck-in-whirlpool. :)

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu

> The original program crashes because there is no place to put the Ultimate Artifact (the 9 squares positioning rule from the edges of the map). :)

Ah yes, I added some land at the center of the map and OG doesn't freeze anymore.

**Comment by ihhub** [comment]
@oleg-derevenetz and @LeHerosInconnu , I'm confused. What then are we going to fix for this issue if the OG behavior is incorrect?

**Comment by oleg-derevenetz** [comment]
Hi @ihhub I believe we can just left the whirlpool passability as is.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub and @oleg-derevenetz,

> @oleg-derevenetz and @LeHerosInconnu , I'm confused. What then are we going to fix for this issue if the OG behavior is incorrect?

> Hi @ihhub I believe we can just left the whirlpool passability as is.

For me the main thing to respect is the "teleportation" in the same Whirlpool square (as if each Whirlpool square was an independent teleporter, like a Stone Liths).
After that it makes more sense to move to an adjacent Whirlpool square directly without having to leave the Whirlpool.

**Comment by ihhub** [comment]
Since we have exactly what right now with whirlpools I'm closing this issue and the corresponding pull request.
