### ISSUE TITLE
Adventure map, optimization of the hero's predefined path

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4510]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In the original game, the hero's predefined path favors horizontal and vertical moves first, rather than diagonal moves, which allows the hero to benefit from the bonus given to the last move (if the hero can move horizontally or vertically then he can move diagonally).

In fheroes2, this is not the case, and it penalizes the hero by reducing his movement.

In the original game (the hero's predefined path favors horizontal and vertical moves first):

![Optimize hero path 001](https://user-images.githubusercontent.com/43583994/139136189-5e3a4c32-8b7f-407a-b10a-0bc9928a8f1d.png)

In fheroes2 (the hero's predefined path first makes a diagonal move and the hero cannot reach the last square):

![Optimize hero path 002](https://user-images.githubusercontent.com/43583994/139136275-5e596fec-e3aa-4094-8dca-ea2257d5cd83.png)
![Optimize hero path 003](https://user-images.githubusercontent.com/43583994/139136283-0c8c78ed-7cb0-4224-90e9-9256595ea9cb.png)
![Optimize hero path 004](https://user-images.githubusercontent.com/43583994/139136301-a65e0a4c-a33d-450e-9d23-4e5f9f168047.png)

In fheroes2 (by "manually" moving the hero horizontally as far as possible, the hero can move diagonally into the last square):
![Optimize hero path 005](https://user-images.githubusercontent.com/43583994/139136361-bb9e8fad-5a62-4777-b081-172aad60388e.png)
![Optimize hero path 006](https://user-images.githubusercontent.com/43583994/139136377-4e27f5b2-10be-4d98-bae1-aa180ccc0f79.png)

I noticed a lot of differences between the original game and fheroes2 in the hero's predefined path due to this during my test on passability.
Here are all screenshots for passibility and predefined path differences:
https://drive.google.com/file/d/12eG_uOTrI7wSsnGJBagfvu8AGQ-qxAD0/view?usp=sharing

### Save file

Here is the test scenario file:
[0 9953a4.zip](https://github.com/ihhub/fheroes2/files/7428913/0.9953a4.zip)

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu

> bonus given to the last move (if the hero can move horizontally or vertically then he can move diagonally).

Does the "last move" mean "last move in the path" or "last move hero can make before he runs out of move points"?

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> Hi @LeHerosInconnu
> 
> > bonus given to the last move (if the hero can move horizontally or vertically then he can move diagonally).
> 
> Does the "last move" mean "last move in the path" or "last move hero can make before he runs out of move points"?

It's the "last move hero can make before he runs out of move points".

>  If the latter, then how about paths that take more than one day?

The path should be adapted according to the terrain penalties encountered the next round(s), like this:

In original game:

![Päth optimization 001](https://user-images.githubusercontent.com/43583994/141478235-570d123d-9551-43e0-933a-230b29ec13e9.png)

![Päth optimization 002](https://user-images.githubusercontent.com/43583994/141478256-38868692-b062-4625-9017-440bc4102e82.png)

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu

> The path should be adapted according to the terrain penalties encountered the next round(s)

What I meant is "should this effect be applied to each last-of-the-day move of multi-day paths"? :) In other words, should the each last-of-the-day move in multi-day paths ignore the diagonal penalty too? Because otherwise we will face the same issue - it would be more optimal to move day-by-day instead of paving the multi-day path.

Honestly, all this logic looks weird, like some ancient logic flaw.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> @LeHerosInconnu
> 
> > The path should be adapted according to the terrain penalties encountered the next round(s)
> 
> What I meant is "should this effect be applied to each last-of-the-day move of multi-day paths"? :) In other words, should the each last-of-the-day move in multi-day paths ignore the diagonal penalty too? Because otherwise we will face the same issue - it would be more optimal to move day-by-day instead of paving the multi-day path.

Yes of course, the predefined path over several turns should take into account the movement bonus of the hero's last move for each turn.
 
> Honestly, all this logic looks weird, like some ancient logic flaw.

I think this is a compensation for the fact that a diagonal movement costs 1.5 movement points instead of 1.41 movement points. :D

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu

> Also, it might be a bit "weird" from the player's point of view to be able to take a last step but not in every direction.

I would accept this argument, however it seems that in HoMM3 "last diagonal move" is allowed only on non-penalty terrains - at least that's what said here:

https://heroes.thelazy.net/index.php/Movement#Consumption_of_the_movement_points

So on terrain with penalty player still will not be able to make diagonal move although he will still be able to make a straight one, which is still "weird" :)

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> @LeHerosInconnu
> 
> > Also, it might be a bit "weird" from the player's point of view to be able to take a last step but not in every direction.
> 
> I would accept this argument, however it seems that in HoMM3 "last diagonal move" is allowed only on non-penalty terrains - at least that's what said here:
> 
> https://heroes.thelazy.net/index.php/Movement#Consumption_of_the_movement_points
> 
> So on terrain with penalty player still will not be able to make diagonal move although he will still be able to make a straight one, which is still "weird" :)

Yes, they changed the way it works in Heroes 3 (also with the addition of native terrain for creatures).
You may also notice that the penalty for diagonal movement has also been adjusted to a value closer to "reality", 141 movement points in Heroes 3 instead of the 150 movement points in Heroes 2.

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu

> Yes, they changed the way it works in Heroes 3 (also with the addition of native terrain for creatures).

In fact, I tested this today in HoMM3 and it seems that this wiki is not correct - I still able to do a last diagonal move over the Rough terrain (125% penalty) by a Knight with Knight's native army with 130 MP left (at least in SoD).

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> @LeHerosInconnu
> 
> > Yes, they changed the way it works in Heroes 3 (also with the addition of native terrain for creatures).
> 
> In fact, I tested this today in HoMM3 and it seems that this wiki is not correct - I still able to do a last diagonal move over the Rough terrain (125% penalty) by a Knight with Knight's native army with 130 MP left (at least in SoD).

Oh. :)
I never tested in depth how it works in Heroes 3.
And Heroes 3 is no longer installed on my computer, and I don't intend to reinstall it.
I find Heroes 2 more fun to play and now that fheroes2 is getting closer to Heroes 2... :D
