### ISSUE TITLE
Adventure map, Ultimate Artifact shouldn't be placed at areas behind tall objects, like mountains.

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4512]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Original game doesn't allow to dig artifact out from the areas like that:
![image](https://user-images.githubusercontent.com/55348946/139252922-e0f6cb80-d5c9-414a-aa37-29feef7e2025.png)
In the OG UA is automatically moved to another close free area, while fheroes2 has UA always placed here.
![image](https://user-images.githubusercontent.com/55348946/139255470-a0ec501a-5814-4df9-9fdc-c8ab2942a7a4.png)

### Save file

[UA+Mountain.zip](https://github.com/ihhub/fheroes2/files/7434017/UA%2BMountain.zip)

**Comment by LeHerosInconnu** [comment]
Another save for this.

In fheroes2:

![Ultimate near castle mountain 001](https://user-images.githubusercontent.com/43583994/140295964-fdd9fb06-bcdd-4131-a78d-b5e782a40e39.png)

![Ultimate near castle mountain 002](https://user-images.githubusercontent.com/43583994/140295975-a830015b-484f-4bfb-81a8-cd49ab989e52.png)

![Ultimate near castle mountain 003](https://user-images.githubusercontent.com/43583994/140295982-9fd8ed0c-865d-4419-86be-add452a0dca7.png)

Here is the save file (0.9.8 4530):
[Ultimate near castle mountain.zip](https://github.com/ihhub/fheroes2/files/7473972/Ultimate.near.castle.mountain.zip)

**Comment by LeHerosInconnu** [comment]
Another save for this.

In fheroes2:

![Artifact location 10](https://user-images.githubusercontent.com/43583994/180162745-21ea46b9-b691-4702-8bc6-5e06a20fe669.png)

Here is the save file:
[Artifact location 10.zip](https://github.com/ihhub/fheroes2/files/9157442/Artifact.location.10.zip)

Version 0.9.17 5675

**Comment by ihhub** [comment]
This issue was fixed long time. The game does not place an Ultimate Artifact on tiles which have anything more than shadows.
