### ISSUE TITLE
Adventure map, cannot dig under a road

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4513]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Cannot dig for Ultimate Artifact at any area below a road.
![image](https://user-images.githubusercontent.com/55348946/139256918-863a959c-08ac-43ef-bc29-fdad2735f4bc.png)
![image](https://user-images.githubusercontent.com/55348946/139257108-17dd467e-28e1-4ca4-abc8-92a5e84fd66c.png)

### Save file

[UA+Road.zip](https://github.com/ihhub/fheroes2/files/7434076/UA%2BRoad.zip)

**Comment by ihhub** [comment]
This issue was fixed in #5720
