### ISSUE TITLE
Add a Romanian translation

### ISSUE THREAD

**Issue by pflugs30** [ihhub/fheroes2#4515]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

No Romanian translation exists

### Describe the possible solution

Add a Romanian translation

**Comment by dimag0g** [comment]
@pflugs30 Do you have anyone in mind who is capable of doing the work?

**Comment by pflugs30** [comment]
> @pflugs30 Do you have anyone in mind who is capable of doing the work?

I created this issue to track work done by **BlueRider** from the FreeHeroes2 Discord server.
