### ISSUE TITLE
Medusa stunning effect bug

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#452]
While being stunned from medusa's attack creature's figure is being moved.
There is also no animation of stunning effect.
![Stun](https://user-images.githubusercontent.com/55348946/80861203-a5444b00-8c75-11ea-8947-8c6dfa8850c4.jpg)

**Comment by ihhub** [comment]
The position is fixed. The only part left is animation. We could close this issue and open a new one for this specific case or just the description of the issue.

**Comment by Branikolog** [comment]
OK. 
I'll make new issue about stunning animation as soon, as possible.
