### ISSUE TITLE
Space bar operation

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#453]
Pressing "space" causes opening  heroes' inventory. Only if they don't have path created.
Also "space" works as "M" button, that initiates movement.
Both of this features should be canceled. Space should only initiate object, hero is located at.

**Comment by ihhub** [comment]
Hi @Branikolog , this is an incorrect assumption. The original game allows user to start hero's movement by pressing a space bar.

**Comment by Branikolog** [comment]
> Hi @Branikolog , this is an incorrect assumption. The original game allows user to start hero's movement by pressing a space bar.

No. You can only initiate hero's movement by M button.
