### ISSUE TITLE
Dismiss hero bug

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#454]
If you buy a new hero in a tavern. then exit town, without checking a tavern, and then dismiss hero - it will appear in a tavern in the same slot.

**Comment by Killbrum** [comment]
I see that it doesn't matter when you dismissed your hero. You even can make another turn in the game. Mainly we just do not reset the available heroes list.

**Comment by Branikolog** [comment]
@Killbrum 
True. Only till the moment we check the tavern.
