### ISSUE TITLE
Sphinx riddle bug

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#455]
Cannot read sphinx's riddle.
![Sphinx](https://user-images.githubusercontent.com/55348946/80863488-7635d580-8c85-11ea-8c18-5a9e7242d251.jpg)

**Comment by idshibanov** [comment]
Maybe this depends on a map? The code handling it looks valid and it works on standard maps:
![image](https://user-images.githubusercontent.com/1373638/84859464-3eb79880-b03b-11ea-8810-86874319bf67.png)

**Comment by Branikolog** [comment]
Well, I think problem was due to map being created on a russian version of game... Original game cannot work with cyrilic letters in that way. That's why we can see empty message on a screenshot...
