### ISSUE TITLE
Game, sometimes the sound level of the victory video is lower than the sound of the music, this in windowed mode or in full screen mode

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4565]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, sometimes the sound level of the victory video is lower than the sound of the music, this in windowed mode or in full screen mode.

In fheroes2:

Activate the sound of the videos.

Sound of the video at the same level:

https://user-images.githubusercontent.com/43583994/140623912-6a9bb312-42d8-495e-a817-ad4909ebbe4f.mp4

Sound of the video with lower level:

https://user-images.githubusercontent.com/43583994/140623957-95ed4b4d-49c8-4943-89cc-528a77084ecf.mp4

### Save file

Here is the save file:
[Win video sound low full scree.zip](https://github.com/ihhub/fheroes2/files/7491254/Win.video.sound.low.full.scree.zip)

### Additional info

Game started with version 0.9.8 4544 and continued with version 0.9.9 4551.

**Comment by oleg-derevenetz** [comment]
I believe this issue should already be fixed by #5286. Hi @LeHerosInconnu could you please double check this when you have time and re-open this issue if it is still observed?
