### ISSUE TITLE
Adventure map, AI behavior, AI no longer recruits heroes nor creatures in its castles (0.9.9 4551)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4566]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, AI no longer recruits heroes nor creatures in its castles.

In fheroes2:

Last heroes of the red player (Broken_Alliance_0066.sav):
![Sleeping AI 001](https://user-images.githubusercontent.com/43583994/140624999-388f852f-d45a-4629-8ee1-098b6703068d.png)
![Sleeping AI 002](https://user-images.githubusercontent.com/43583994/140625000-2a3264ca-50f5-4ba6-a098-60323de7d86e.png)

Last hero of the red player (Broken_Alliance_0067.sav):
![Sleeping AI 003](https://user-images.githubusercontent.com/43583994/140625007-7c409696-be51-48a9-8962-294687411dfb.png)

Castle of the purple player discovered (Broken_Alliance_0071.sav):
![Sleeping AI 004](https://user-images.githubusercontent.com/43583994/140625010-bbd7aaa8-e4ee-4a67-a0e6-7df4d0e40ae4.png)

From this point, pass the turns without moving and every turn check with the help of the "View Heroes" spell (all heroes know it) if there are heroes recruited, or creatures recruited in the discovered castle.

Many turns later no heroes recruited and no creatures recruited despite the presence of a hero near the discovered castle:
![Sleeping AI 005](https://user-images.githubusercontent.com/43583994/140625014-13bf13ba-cabe-4323-ad7d-4e75e7a9b157.png)

### Save file

Here are the save files:
[Sleeping AI 01.zip](https://github.com/ihhub/fheroes2/files/7491309/Sleeping.AI.01.zip)

### Additional info

Game started with version 0.9.8 4544 and continued with version 0.9.9 4551.

**Comment by idshibanov** [comment]
Regression since 0.9.5 introduced in #3794, issue with `moreTasksForHeroes` check specifically.
