### ISSUE TITLE
Combat, the result of an instant combat is different from the result of a combat played in automatic mode from the very beginning of the combat, with Auto Spell Casting enabled (0.9.9 4551)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4568]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the result of an instant combat is different from the result of a combat played in automatic mode from the very beginning of the combat, with Auto Spell Casting enabled.

In fheroes2:

![Instant and Auto combat 001](https://user-images.githubusercontent.com/43583994/140627664-eee7ab0a-5476-4e4e-95b1-0616e2ee9ff8.png)

Auto Spell Casting enabled.
![Instant and Auto combat 002](https://user-images.githubusercontent.com/43583994/140627666-d33db185-57fd-44d6-afe1-4517173f3694.png)

![Instant and Auto combat 003](https://user-images.githubusercontent.com/43583994/140627667-a3923b14-1669-4c6a-9767-8beef3f4bbef.png)

Auto Spell Casting enabled.
![Instant and Auto combat 004](https://user-images.githubusercontent.com/43583994/140627669-03d8fba4-13fd-46c8-bcd7-740e53aa69d0.png)

![Instant and Auto combat 005](https://user-images.githubusercontent.com/43583994/140627671-418b4e28-465a-4e18-8cb9-df7f9712d61b.png)

![Instant and Auto combat 006](https://user-images.githubusercontent.com/43583994/140627675-07c5235d-2ea9-4f22-b9f7-c651e0a932a1.png)

Halon attacks Myrini.

### Save file

Here is the save file:
[Before attack disrupting ray_.zip](https://github.com/ihhub/fheroes2/files/7491344/Before.attack.disrupting.ray_.zip)

### Additional info

Game started with version 0.9.8 4544 and continued with version 0.9.9 4551.
Related closed issue: https://github.com/ihhub/fheroes2/issues/4007.

**Comment by vincent-grosbois** [comment]
I'm investigatin but this is quite tricky :D 

The enemy heroes blinds the archers who were resurrected by our hero. In instant battle it seems we can't find the resurected units when applying blind so the "blind" spell fails
