### ISSUE TITLE
[FR] Add an VYSNC option (Easy SDL2 code included)

### ISSUE THREAD

**Issue by vanfanel** [ihhub/fheroes2#4572]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Hi!

Would it be possible to have an VSYNC toggle option on the menu?
It's very simple to implement on the SDL2 side of things: here in this exact line in `src/engine/screen.cpp`:

https://github.com/ihhub/fheroes2/blob/058d675daa31195f552432a30e2c356bd9f967e4/src/engine/screen.cpp#L987

...if the VSYNC option on the game menu is ON, it should return:

`return (SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);
`
instead of:

`return (SDL_RENDERER_ACCELERATED);`

Also, game internal waits for video refresh should be disabled when VSYNC is ON, because **VSYNC should be used as the speed limiter when it's active**.
Yes, I know there are those 144Hz monitors, etc, but these can do without VSYNC as until now.

### Describe the possible solution

It's very simple to implement on the SDL2 side of things: here in this exact line in `src/engine/screen.cpp`:

https://github.com/ihhub/fheroes2/blob/058d675daa31195f552432a30e2c356bd9f967e4/src/engine/screen.cpp#L987

...if the VSYNC option on the game menu is ON, it should return:

`return (SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);
`
instead of:

`return (SDL_RENDERER_ACCELERATED);`

Also, game internal waits for video refresh should be disabled when VSYNC is ON, because **VSYNC should be used as the speed limiter when it's active**.

### Additional info

VSYNC is universally supported in SDL2, every backend has it working unlike in the old SDL1.x days.

I always do my own builds with forced vsync ON, it works perfectly and prevents tearing and flickering like in this issue here:
https://github.com/ihhub/fheroes2/issues/4500

**Comment by ihhub** [comment]
Adding this option in backend is not an issue. UI will be the problem.

**Comment by vanfanel** [comment]
@ihhub Maybe a simple .ini option would be enough?

**Comment by ihhub** [comment]
Yes, it will work too. Let me come up with some solution later.
