### ISSUE TITLE
Boarding off boat not possible in last scenario of Archibald's campaign

### ISSUE THREAD

**Issue by a1exsh** [ihhub/fheroes2#4578]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

It seems that it must be possible to board off the boat at this narrow pass, but the anchor cursor never appears:
![image](https://user-images.githubusercontent.com/489601/140659055-579a7997-d61b-444f-9075-af6f0c4f5798.png)

On the other hand, many places along the coast to the south show the anchor cursor (in the trees), where it doesn't make sense to board off.

### Save file

[Evil_11_0100.zip](https://github.com/ihhub/fheroes2/files/7492945/Evil_11_0100.zip)

### Additional info

Looks like winning the campaign is not possible due to this bug. :(

**Comment by ihhub** [comment]
Hi @a1exsh , it's exactly the same as in the original game. To complete this scenario there's a passage near a sign almost in the middle of the map where you haven't uncovered the fog. Right from your top of the castles.

**Comment by a1exsh** [comment]
> To complete this scenario there's a passage near a sign almost in the middle of the map where you haven't uncovered the fog. Right from your top of the castles.

Hah! How could I miss that?.. Thanks, all is good.
