### ISSUE TITLE
Combat screen, hexagon grid should not be drawn over an obstacle

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4586]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the hexagon grid should not be drawn over an obstacle.

In original game:

![Grid over obstacle flèche 001](https://user-images.githubusercontent.com/43583994/140804544-a7cdd5b7-d37c-4ccc-abb7-df224c468c86.png)

In fheroes2:

![Grid over obstacle flèche 002](https://user-images.githubusercontent.com/43583994/140804591-1af91e2e-61dc-4e84-8de3-db5f92ef70f5.png)

### Save file

Not needed.

**Comment by oleg-derevenetz** [comment]
I believe it's a handy feature for calculating distance.
