### ISSUE TITLE
Building castle in warlock and knight city

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#459]
Castle in a warlock city slowly appears over tent, which has square of textures surrounding it.
![Castle](https://user-images.githubusercontent.com/55348946/80909705-f8300800-8d32-11ea-916e-a74e0dbe88d7.jpg)

**Comment by ihhub** [comment]
It is a problem with this image itself, more precisely is that we incorrectly decode it. Here is a look from the original game:
![image](https://user-images.githubusercontent.com/19829520/82732967-383b4700-9d43-11ea-8005-b8034f5ed6a2.png)

and this is what we have:
![image](https://user-images.githubusercontent.com/19829520/82732974-3ffaeb80-9d43-11ea-9efe-5bd869f96849.png)

Obviously, our tent is grayish which is wrong.

**Comment by Branikolog** [comment]
I've also noticed the same thing in Knight city:
![Castle](https://user-images.githubusercontent.com/55348946/82796827-d7188e00-9e7e-11ea-85ed-9da126683ee9.jpg)

**Comment by ihhub** [comment]
After detailed investigation I can conclude that shadow value is not exactly a shadow but a reference to a specific palette which should be applied for a pixel which is already drawn. The most common case is 128-131 values (of shadow branch during ICN unpacking). These values are refer to a table which I created recently called `darkeningTable`. There are more values as well. For example, for air elemental numbers are 100-103, 104-107, 96-99 and etc. I assume that they refer to different tables (formulas?) as well as looking into air element in the original game we can conclude that.

@idshibanov , could you please try to find such reference in the original source code? I think we just need these table to make things work.

**Comment by ihhub** [comment]
@idshibanov , I think we need to look into attachment in #408 . I think `dimTable` is exactly what we need.

**Comment by ihhub** [comment]
Yes. first part of `dimTable` is almost identical to our `darkeningTable` table :)

**Comment by idshibanov** [comment]
Yes, I think I mentioned on other ticket about this hidden palette in the original code. It is `dimTable` indeed. I tried to figure out it's use before but all graphics calls are very raw and hard to read.

@ihhub Some snippets I know:
Palette 0 is used for general GUI dimming
Palette 2 is used for hex dimming on battlefield
Palette 3 is applied on display for screen fade (such as battle victory screen)

When reading the ICN file for shadows it cuts the value up to 0x3C and multiplies by 64 to get the index. `(value & 0x3C) * 64`

**Comment by ihhub** [comment]
Hi @idshibanov , yeah, I read something in the original decompiled source code. I'll add some small changes to our code to make the same logic.

**Comment by ihhub** [comment]
The fix somehow is very easy: we just don't need to draw tents in all castles at all as castle's background contains tents, we just need to handle areas of these tents :bulb: If someone wants to fix it please go ahead.
