### ISSUE TITLE
Incorrect heuristic for Troop::GetStrength in combat

### ISSUE THREAD

**Issue by vincent-grosbois** [ihhub/fheroes2#4591]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

For combat AI heuristic, we call Troop::GetStrength everywhere to know the power of a unit
 but this heuristic doesn't include both hero stat bonuses (attack etc) and also current unit status (eg stone skin etc) 
is this really intended?

### Save file

-

**Comment by ihhub** [comment]
If it looks logically incorrect then it should be incorrect :) Battle-related code is still the biggest mess and we haven't touched much of it :(
