### ISSUE TITLE
Adventure map, map event should display only one window

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4595]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the map event should display only one window.

Fheroes2 has improved things for the map event, notably the display of all resources.
However, in fheroes2, a map event displays several windows for a single event.

I think that this should be improved so that everything is displayed in one window.
For the text problem, a scrollbar can be used when the text becomes too long to be displayed entirely.

The yellow title of the window should be "Event".
The text of the event displayed below.
And the reward below.

In original game:

https://user-images.githubusercontent.com/43583994/140914024-84dc47c2-cb8d-4953-ac3a-bb1daed761be.mp4

In fheroes2:

https://user-images.githubusercontent.com/43583994/140913561-8b4ae197-7258-4d29-936c-aee7b64110d0.mp4

### Save file

Here are the save files:
[Before events 01.zip](https://github.com/ihhub/fheroes2/files/7504206/Before.events.01.zip)

### Additional info

Related issue: https://github.com/ihhub/fheroes2/issues/1969, https://github.com/ihhub/fheroes2/issues/1338.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , I think this issue is fixed. Could you please verify it?

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , I think this issue is fixed. Could you please verify it?

Yes, it's fixed.
I close the issue.
However, there is still this problem of a cut window with long text in low resolutions (here with the base game resolution at 640 x 480).

In fheroes2:

![Internal Popup 004](https://user-images.githubusercontent.com/43583994/157711320-d0e80a7b-15ac-4692-8997-9c0b0a9a8993.png)

Here is the save file:
[Before events 01.zip](https://github.com/ihhub/fheroes2/files/8225331/Before.events.01.zip)
