### ISSUE TITLE
Adventure map, creature recruitment window should be centered horizontally and vertically on the adventure map

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4596]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the creature recruitment window should be centered horizontally and vertically on the adventure map.
However, it should not be centered in a city (to allow the player to see (a bit) :) the garrisoned creatures).
At least as long as the creature recruitment window is not modified to see garrisoned troops and the hero's army troops more comfortably.

In fheroes2:

![Recruit creatures 001](https://user-images.githubusercontent.com/43583994/140917668-fd34af87-f2b2-4898-be42-99ec7496a7a4.png)

![Recruit creatures 002](https://user-images.githubusercontent.com/43583994/140917679-29a20338-5bc0-487a-9ce7-b5f04f024ccd.png)

### Save file

Here is the save file:
[Before recruit ghosts 01.zip](https://github.com/ihhub/fheroes2/files/7504344/Before.recruit.ghosts.01.zip)

**Comment by Branikolog** [comment]
Hello, @ihhub!
What about well?
![image](https://user-images.githubusercontent.com/55348946/141798515-5cdd6601-c954-4209-bb16-599d29366d5a.png)

**Comment by LeHerosInconnu** [comment]
Hello everyone,

> Hello, @ihhub! What about well?
> ![image](https://user-images.githubusercontent.com/55348946/141798515-5cdd6601-c954-4209-bb16-599d29366d5a.png)

Oh, I forgot about this screen. :D
Yes, the window should also be centered here. :)

**Comment by LeHerosInconnu** [comment]
@ihhub and @Branikolog.

And also in this screen. :)
Is it necessary to open another issue?

In fheroes2:

![Center recruit 10](https://user-images.githubusercontent.com/43583994/141811405-0dc93e9a-3c3c-48b6-975d-095603c5ffa7.png)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , if we don't have such issue please make it.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , if we don't have such issue please make it.

This is no longer necessary, thanks. :)

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

The creature recruitment window has been centered in the "Well" and "Towns/Castles Kingdom Overview" screens.

In fheroes2:

From an aesthetic point of view, I suggest moving the recruitment window down 2 pixels in the "Well" screen to avoid seeing that part of the creature's Dwelling graphic indicated by the red arrow.
![Recruit windon position well flèche 01](https://user-images.githubusercontent.com/43583994/144719401-1b4816e6-abd2-4186-9e82-3aeb589b5a86.png)

And, still from an aesthetic point of view, for the "Towns/Castles Kingdom Overview" screen, I suggest to center vertically the recruitment window in the upper part of the screen, indicated by the red frame, in order to avoid cutting and also hiding the resource generators graphics.
![Recruit window position town overview cadre 02](https://user-images.githubusercontent.com/43583994/144719413-879eb680-1b1d-46ff-bbb1-c002254eb15b.png)
![Recruit window position town overview 01](https://user-images.githubusercontent.com/43583994/144719409-d96931ff-4051-4b5a-88ef-be534f4effe3.png)
