### ISSUE TITLE
Cannot move artifact in heroes inventory

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#460]
Nothing happens when you try to move artifact into different place. 

![Artifact](https://user-images.githubusercontent.com/55348946/80912732-bc536d80-8d47-11ea-9628-8518ef1fa93d.jpg)

**Comment by ihhub** [comment]
We allow to move artifacts. If you select one artifact and an empty place you can move it to that place.

**Comment by ihhub** [comment]
It is a bug, we should allow to move artifacts.
