### ISSUE TITLE
Missing mouse wheel handling in Battle options

### ISSUE THREAD

**Issue by a1exsh** [ihhub/fheroes2#4608]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Overlooked when working on #4553 , battle animation speed should also be possible to change with the mouse wheel:

![image](https://user-images.githubusercontent.com/489601/141256826-2bd46a21-2ed9-4e0c-bac5-a444c9705023.png)

### Describe the possible solution

We should add the same handling as in system options.

**Comment by LeHerosInconnu** [comment]
Hello @a1exsh,

It was on my list. :)
