### ISSUE TITLE
Spacing between letters is not the same as in original game

### ISSUE THREAD

**Issue by seacorn** [ihhub/fheroes2#4611]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

Spacing between letters while using font BIG in original game was 2 px. In fheroes2 it is 1 px.

Compare 
In original game:
![original](https://user-images.githubusercontent.com/91325151/141296339-494aad4a-a54e-42e5-93fc-81261ae1354a.png)

In fheroes2:
![fheroes2](https://user-images.githubusercontent.com/91325151/141296313-4b9a4229-de56-445c-b0d3-6394fa2f6722.png)

### Save file

The save file is not needed. The bug can be seen directly from home screen, e.g. when starting a new campaign.

**Comment by LeHerosInconnu** [comment]
Related issue: https://github.com/ihhub/fheroes2/issues/1234.

**Comment by seacorn** [comment]
Ups. That was embarrassing :) Thanks for pointing out @LeHerosInconnu. I searched only among issues labeled as "bug" and didn't find #1234. In that case, this issue can be closed.

**Comment by LeHerosInconnu** [comment]
Hello @seacorn,

> Ups. That was embarrassing :) Thanks for pointing out @LeHerosInconnu. I searched only among issues labeled as "bug" and didn't find #1234. In that case, this issue can be closed.

No problem, there are so many issues that it is difficult to check them all. and even for those who have reported these issues. :)
