### ISSUE TITLE
Campaign music bug 

### ISSUE THREAD

**Issue by Serd01** [ihhub/fheroes2#4619]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

I found a small bug: when you select the Archibald campaign, when the screen with the details of the scenario is displayed (the one right after the video), you can hear the music, while when you select the Roland campaign or one of the campaigns from POL, then on the above-mentioned the screen has no music. And it should be.

### Save file

[Bug.txt.txt](https://github.com/ihhub/fheroes2/files/7522830/Bug.txt.txt)

**Comment by oleg-derevenetz** [comment]
Honestly, with the latest snapshot build I don't hear any music in either case (and I even don't see a place in the code where it should be played) :) I suppose, it is just not implemented yet.
