### ISSUE TITLE
Voyage Home, scenario 4 has a town with no name leading to an assertion crash during the gameplay

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#4624]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Voyage Home, scenario 4 has one town with no name just left to the start castle. Once a hero enters the village the game crashes during to an assertion in Text class within `getLineWidth` function call.

### Save file

[attack_village_glitch.zip](https://github.com/ihhub/fheroes2/files/7529186/attack_village_glitch.zip)

**Comment by ihhub** [comment]
The main question is are we allowing to have towns with no names or should we fix it and add some fixed or random name? I'm in favor for the second solution as if a map has empty castles it'll be hard to use Town portal.

**Comment by Branikolog** [comment]
Agreed. We should add any standard name to a castle. We also shouldn't forget about versions on other languages.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu and @oleg-derevenetz , would you mind to express your opinion as well?

**Comment by oleg-derevenetz** [comment]
Hi all, we can add a pool of names for such towns or, (or in addition, if pre-defined names will not be enough) we can name them like "Town N" with N starting from 1.

**Comment by LeHerosInconnu** [comment]
Hello everyone,

> Hi @LeHerosInconnu and @oleg-derevenetz , would you mind to express your opinion as well?

There is a bug in the scenario editor:
https://heroes2.forumactif.com/t913-heroes-2-editor-flaws-nameless-town

I also think that if a castle has no name, a standard name should be given to it at start of scenario.
