### ISSUE TITLE
AI is stuck on water

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4625]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Yellow Natasha is standing near coast without any action.
![image](https://user-images.githubusercontent.com/55348946/141523034-d682e839-0ec3-49d3-a113-79f28277ce91.png)
If we hire a hero and embark on a boat Natasha attacks.

### Save file

[Broken_Alliance_100.zip](https://github.com/ihhub/fheroes2/files/7529902/Broken_Alliance_100.zip)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> Natasha is standing near coast without any action.
> If we hire a hero and embark on a boat Natasha attacks.

This is an AI tactic to keep you off the sea. :rofl:
