### ISSUE TITLE
WITH_DEBUG and BUILD_RELEASE should be grouped into one macro

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#4629]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

The code has two macros `WITH_DEBUG` and `BUILD_RELEASE`. These flags are mutually exclusive but somehow we still have them. We must have only one macro for this. Also CMake build has a bug: it sets only `BUILD_RELEASE` macro for release and none for debug build.

### Save file

Nothing to attach.

**Comment by oleg-derevenetz** [comment]
> Also CMake build has a bug: it sets only BUILD_RELEASE macro for release and none for debug build.

In fact it sets `WITH_DEBUG` if `CMAKE_BUILD_TYPE=Debug` is set.
