### ISSUE TITLE
Mage guild: "The above spells have been added to your book" vs. Hero's wisdom

### ISSUE THREAD

**Issue by a1exsh** [ihhub/fheroes2#4633]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

Currently when a hero visits a Mage Guild, the following message is shown in the status line: "The above spells have been added to your book."

This is not strictly correct, as a hero can only learn spells of higher levels if he possesses enough wisdom.

### Save file

No special save file needed.

### Additional info

Not sure what would be appropriate change here.  Maybe we could alter display of the spells that the hero cannot (yet) learn in a way that they are still recognizable, but makes it clear that the wisdom is lacking to learn them (possibly indicating the reason in a message displayed when right-clicking a spell scroll)?

**Comment by oleg-derevenetz** [comment]
This is clearly NOT a bug, it's the original game behavior. OG always shows this message for any guest hero with spell book:

![mg-msg](https://user-images.githubusercontent.com/32623900/141660597-fda9ef4e-451f-4238-bbf9-445d2a382aeb.jpg)

even if this hero have not enough wisdom to learn all these spells:

![mg-hero](https://user-images.githubusercontent.com/32623900/141660607-4ae36c89-86b2-484e-b932-1a059686b019.jpg)

So I reclassify this issue as a suggestion for improvement.

**Comment by a1exsh** [comment]
I know that OG has the same issue. Who said there are no bugs in OG, btw? ;)

**Comment by noomorph** [comment]
@oleg-dereventz, do you have a mechaism for enabling non-OG improtvements or behaviours currently? Or you plan to do this later, after 1.0 ships?

**Comment by oleg-derevenetz** [comment]
Hi @noomorph Yes, we have so-called "Experimental game settings": "NEW GAME" -> "CONFIG" -> "Experimental settings". But now there is a tendency to reduce their number rather than increase :)

**Comment by LeHerosInconnu** [comment]
Hello everyone,

I think just changing the sentence should do the trick.

This:

"The spells you can learn have been added to your book."

Instead of:

"The above spells have been added to your book."

**Comment by Kazhuu** [comment]
I checked this old issue and it seems this string has already been changed right?

**Comment by LeHerosInconnu** [comment]
Hello @everyone,

Yes, taking into account the change for "you" and "your hero", my proposal becomes:

"The spells your hero can learn have been added to his book."

What do you think of it?

**Comment by LeHerosInconnu** [comment]
@zenseii and @Mr-Bajs.

> > Hello @everyone,
> > 
> > Yes, taking into account the change for "you" and "your hero", my proposal becomes:
> > 
> > "The spells your hero can learn have been added to his book."
> > 
> > What do you think of it?
> > 
> > **Edit:** In fact, only one hero at a time learns spells when visiting a town with a mage guild.
> 
> Hi, @LeHerosInconnu. Their can be both plural and singular, and is used in English in cases when the gender is not specified. > There are also female heroes in the game so "his book" would be wrong.
> More details:
> <details>
> 
> https://www.dictionary.com/browse/their
> 
> ![image](https://github.com/ihhub/fheroes2/assets/12501091/9eb7b0f5-b328-49d1-a77e-a7d41b8a6368)
> 
> </details>
 
> _The spells your hero can learn have been added to his book_
> 
> Not all heroes are male though. Should be neutral.

I'm not convinced.
The hero can be either male or female.
We could also say a Heroine (at least in the French language, "Héroïne" in the text) to indicate a female hero.

In the case of the original game, as I understand it, the term "hero" is used whether the hero is male or female, and is therefore used in this way in the game's sentences.
It therefore seems more correct to me to use the terms "hero" and "his", etc. when the sentences concern the hero, whether male or female.
Sentences with the use of "their", although apparently possible, would seem a little odd to me, and also especially so for a player who isn't an expert in the grammar, spelling, etc. of the English language.

Now, it would also be possible to modify all the sentences in the game to indicate the gender of the hero directly in the sentences, using "hero" for a male hero and "heroine" for a female hero.
But is this really necessary and desirable? :)

**Comment by LeHerosInconnu** [comment]
@zenseii.

Thank you for your well-documented reply.
Do what you think is best in this case, even if it will certainly take some extra work to have everything actualized. :)

@Mr-Bajs and @zenseii.

Everyone seems to agree. :)
