### ISSUE TITLE
Betrayal / Turning Point in Archibald's campaign

### ISSUE THREAD

**Issue by a1exsh** [ihhub/fheroes2#4634]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

After winning the 3rd scenario of Archibald's campaign in the OG, the player is offered an option of switching to the good side: ![heroes2_007](https://user-images.githubusercontent.com/489601/141650520-8d887159-5e5c-4f84-b546-e462b0c239ba.png)

This doesn't seem to be the case in fheroes2 (or there is condition of winning the scenario I'm not aware of):
![image](https://user-images.githubusercontent.com/489601/141650623-f893e47e-8c57-4b72-93ac-7f6b5999f94c.png)

### Save file

Save file from OG: [WIN_E_03.zip](https://github.com/ihhub/fheroes2/files/7532339/WIN_E_03.zip)
Save file from fheroes2: [Evil_3_Complete.zip](https://github.com/ihhub/fheroes2/files/7532343/Evil_3_Complete.zip)

### Additional info

This is how the scenario info looks after switching to the good side:
![image](https://user-images.githubusercontent.com/489601/141650737-4b8a7598-cc0f-434a-b0ed-a74082fcaef4.png)

**Comment by Branikolog** [comment]
Hi, @a1exsh !
Isn't it the same issue to #3491 ?

**Comment by a1exsh** [comment]
> Hi, @a1exsh ! Isn't it the same issue to #3491 ?

You're right, but I couldn't find it :(

**Comment by oleg-derevenetz** [comment]
It is better to close duplicates, because the more issues there are, the more difficult it is to find something.
