### ISSUE TITLE
"Town Portal" spell background is generated differently for "Evil" and "Good" interfaces

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4648]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

You can notice a small part of background being shifted:
![ezgif com-gif-maker (7)](https://user-images.githubusercontent.com/55348946/141983750-896fc017-f8cf-44c7-a72e-b4b3a7f8a028.gif)

### Save file

[Town Portal.zip](https://github.com/ihhub/fheroes2/files/7546168/Town.Portal.zip)

**Comment by a1exsh** [comment]
@Branikolog it has taken me around 2 minutes to notice anything, and I'm not sure you mean the same thing (middle of the top border?)

It is very likely that evil resources have slight differences in OG — I've noticed a number of these then working on scaling the adventure border to any resolution.

Otherwise, the dialogs look identical to me, so I wouldn't spend effort on it.

**Comment by Branikolog** [comment]
@a1exsh 
I'm no insisting on fixing it, actually. But non-similar rendering of this windows may reveal some code problems... I hope someone would dive into that place and find out, why do these places are rendered differently..

**Comment by a1exsh** [comment]
Not sure I want to know how you even noticed anything: it's not that you can switch between the two interfaces within the game while having that window open...

**Comment by noomorph** [comment]
I was just passing by, but I don't notice any shifts either. 🤷‍♂️

**Comment by ihhub** [comment]
Middle bottom part between buttons.

**Comment by a1exsh** [comment]
Yeah, maybe...
The big question here, IMO: does it matter?

We have a ton of real issues, and this nobody can notice while playing the game — only when looking closely on both variants of the window.

**Comment by ihhub** [comment]
Nope. It doesn't.
