### ISSUE TITLE
Adventure map, when a hero, positioned on a Magic Well, visits this Magic Well with the space key, the hero's spell points indicator is not updated in the list of heroes

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4653]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, when a hero, positioned on a Magic Well, visits this Magic Well with the space key, the hero's spell points indicator is not updated in the list of heroes.
You have to interact with the list of heroes or the list of towns in order for the hero's spell points indicator to be updated.

In fheroes2:

![Hero spell indicator 01](https://user-images.githubusercontent.com/43583994/142212606-ac3c748c-c0e8-4b80-b47b-a36d836acb81.png)

![Hero spell indicator 02](https://user-images.githubusercontent.com/43583994/142212624-a2d5ce94-8627-4318-904e-0a28d58f53c2.png)

https://user-images.githubusercontent.com/43583994/142212699-a1e2c7a1-b82a-4e22-a7f1-f08717574dc5.mp4

### Save file

Here is the save file:
[Broken_Alliance_0009 a.zip](https://github.com/ihhub/fheroes2/files/7555058/Broken_Alliance_0009.a.zip)

### Additional info

**Edit 2021/11/18.**

Similar issues: https://github.com/ihhub/fheroes2/issues/4659, https://github.com/ihhub/fheroes2/issues/4660, https://github.com/ihhub/fheroes2/issues/4661, https://github.com/ihhub/fheroes2/issues/4662.

**Comment by vincent-grosbois** [comment]
probably the same thing for other similar objects like stable?

**Comment by LeHerosInconnu** [comment]
Hello @vincent-grosbois,

> probably the same thing for other similar objects like stable?

Yes, I will open more issues on this later. :)

**Comment by LeHerosInconnu** [comment]
> Hello @vincent-grosbois,
> 
> > probably the same thing for other similar objects like stable?
> 
> Yes, I will open more issues on this later. :)

First post updated.
Similar issues: https://github.com/ihhub/fheroes2/issues/4659, https://github.com/ihhub/fheroes2/issues/4660, https://github.com/ihhub/fheroes2/issues/4661, https://github.com/ihhub/fheroes2/issues/4662.
