### ISSUE TITLE
Medusa's victim to stone visual glitch

### ISSUE THREAD

**Issue by shprotru** [ihhub/fheroes2#466]
If medusa making victim to stone, the victim could be visually moved to near hexfield: look at titans at screenshot, they are visually on same field as archmages, but medusas attacked correct hex field with titans in that battle.
![Снимок экрана от 2020-05-05 13-53-48](https://user-images.githubusercontent.com/53114202/81060381-ff921580-8eda-11ea-971b-0a0331b1b002.png)

**Comment by ihhub** [comment]
It is a duplication of #452 . Closing this issue.
