### ISSUE TITLE
Adventure map, when a hero visits an Artesian Spring already visited by an opposing hero and therefore does not get the Artesian Spring bonus, this Artesian Spring is not marked as "(already visited)" although it should be

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4666]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, when a hero visits an Artesian Spring already visited by an opposing hero and therefore does not get the Artesian Spring bonus, this Artesian Spring is not marked as "(already visited)" although it should be.

In fheroes2:

https://user-images.githubusercontent.com/43583994/142615335-90ee2dd4-b04c-408b-94d4-91f83547940f.mp4

### Save file

Here is the save file (multiplayer):
[Before artesian spring alread.zip](https://github.com/ihhub/fheroes2/files/7569872/Before.artesian.spring.alread.zip)

**Comment by vincent-grosbois** [comment]
Isn't this intended ? It's the same thing for windmill etc, you can't tell if it was visited by the opponent or not beforehand if you don't actually visit the object
