### ISSUE TITLE
IA computer heroes get stuck on sea vortex/swirl

### ISSUE THREAD

**Issue by Tromthar** [ihhub/fheroes2#4669]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

When i play a standar game, usually AI moves heroes on ships and get stuck on sea vortex, goin on and on in a infinite loop, kinda frustating, because it vanishes the dificulty of the game.

### Save file

[Alteris bug.zip](https://github.com/ihhub/fheroes2/files/7574473/Alteris.bug.zip)

### Additional info

hard dificulty.

**Comment by oleg-derevenetz** [comment]
Hi @Tromthar this should be already fixed by #4649. Did you really tried the latest snapshot (not the latest release, but the latest snapshot) and if yes, is this issue really still observed?

**Comment by Tromthar** [comment]
ohh, maybe my bad, , but how do i donwload latest snapshot and not the realeasE?.

Btw, thanks all for this proyect, this is awesome.

**Comment by oleg-derevenetz** [comment]
@Tromthar Snapshots for all platforms are available here:

https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds

at the very end of the page.

**Comment by ihhub** [comment]
Closing this issue as being fixed. @Tromthar , please reopen it if you face the same issue again with the latest snapshot.
