### ISSUE TITLE
Some objects can be seen over upper world edge.

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#467]
Hero's flag or creature's heads overlap upper world edge when they are too close to it. 
![Upper edge](https://user-images.githubusercontent.com/55348946/81063752-19365b80-8ee1-11ea-9cd7-beadaaaf82ec.jpg)
Same bug i saw even in the original demo.

**Comment by Branikolog** [comment]
The same thing happens to the bottom edge:
![Overlap](https://user-images.githubusercontent.com/55348946/84566458-f3229780-ad79-11ea-96d3-24a4d4cf206a.jpg)

**Comment by ihhub** [comment]
Putting this issue to Beyond 1.0 as the same behavior is being seen in the original game.
