### ISSUE TITLE
Castle screen, Red Tower has one glowing pixel

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4685]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

There's one red glowing pixel at Red Tower.
![Pixel](https://user-images.githubusercontent.com/55348946/142993954-be50345c-ca46-4903-afe1-df85ba036b27.png)

Note: OG has the same flaw.
### Save file

[Uploading Castles.zip…]()

**Comment by a1exsh** [comment]
I guess the dragon just left its nest, so it still glows hot 😂
