### ISSUE TITLE
Adventure map, Ultimate Artifact, in automatic positioning mode, the Ultimate Artifact should not be placed on the shadow of an object

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4690]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, in automatic positioning mode, the Ultimate Artifact should not be placed on the shadow of an object.
Also, it should not be possible to dig on the shadow of objects.

In original game:

![Digging on shadow 001](https://user-images.githubusercontent.com/43583994/143209269-5766ca44-b1f6-475f-b692-59cab5e36e90.png)

![Digging on shadow 002](https://user-images.githubusercontent.com/43583994/143209283-8f3166a2-7f52-47ac-9351-4e13530e288c.png)

![Digging on shadow 003](https://user-images.githubusercontent.com/43583994/143209311-975ea3e3-79da-4081-9aa6-339cc8081497.png)

![Digging on shadow 004](https://user-images.githubusercontent.com/43583994/143209239-20d77844-6aa8-4147-92c2-da127f680adb.png)

In fheroes2:

![Digging on shadow 005](https://user-images.githubusercontent.com/43583994/143209438-60f9d085-225c-4bcc-bda4-808d0caf2005.png)

### Save file

Here are the save files:
[No digging on shadow 01.zip](https://github.com/ihhub/fheroes2/files/7594303/No.digging.on.shadow.01.zip)

**Comment by oleg-derevenetz** [comment]
Honestly, I don't understand how a shadow can prevent you from burying/digging an artifact, so this restriction looks a bit artificial to me.

**Comment by vincent-grosbois** [comment]
> Honestly, I don't understand how a shadow can prevent you from burying/digging an artifact, so this restriction looks a bit artificial to me.

+1

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz and @vincent-grosbois,

> Honestly, I don't understand how a shadow can prevent you from burying/digging an artifact, so this restriction looks a bit artificial to me.

That's true, but that's just the way it works in the original game, and players are used to it (to not even think about trying to dig on a shadow).

**Comment by Branikolog** [comment]
> and players are used to it

I'm almost 99.99% sure, all H2 players never heard of this rule at all. :)
Not everyone knows game mechanics as good, as you do. ;)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> > and players are used to it
> 
> I'm almost 99.99% sure, all H2 players never heard of this rule at all. :) Not everyone knows game mechanics as good, as you do. ;)

It should also be taken into account that not being able to dig on the shadows reduces the number of squares where the hero would have to dig to find the Ultimate Artifact when the area under the puzzle is not fully visible. :)

**Comment by ihhub** [comment]
This is a bug of the original game. Shadows are a part of of objects and to make life simple it's easy to just check if a tile has any object on it, even shadow. If yes then exclude this tile for Ultimate Artifact. This is my assumption based on game's behavior.

**Comment by ihhub** [comment]
I am closing this issue as logically for most of players it makes sense. Also positioning an Ultimate Artifact in more places over the original game makes the game more challenging.
