### ISSUE TITLE
Adventure map, Obelisk window, the word "had" is missing in the last sentence

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4696]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, in the Obelisk window, the word "had" is missing in the last sentence.

It should be:

"...vanishes as abruptly as it had appeared."

Instead of:

"...vanishes as abruptly as it appeared."

In original game:

![Passability test 055](https://user-images.githubusercontent.com/43583994/143458772-8886e87c-01eb-4592-9071-e839e8f2abe0.png)

In fheroes2:

![Passability test 056](https://user-images.githubusercontent.com/43583994/143458711-66632b58-f63d-4111-ad15-f4f562d322e4.png)

### Save file

Not needed.

**Comment by zenseii** [comment]
The original game is gramatically wrong here and the current way it is written in fheroes2 is correct. 

For "had disappeared" to be correct, the whole sentence would have be told as if it happened in the past:
"Quickly you **copied** down the piece and the inscription **vanished** as abruptly as it **had appeared**."

**Comment by LeHerosInconnu** [comment]
Hello @zenseii,

> The original game is gramatically wrong here, and the current way it is written in fheroes2 is correct.
> 
> For "had disappeared" to be correct, the whole sentence would have to be told as if it happened in the past: "Quickly you **copied** down the piece and the inscription **vanished** as abruptly as it **had appeared**."
> 
> To me it seems like the first person to write this string in fheroes2 corrected this, either intentionally or automatically, since the whole passage is told in the present.

I admit that I didn't pay attention to the conjugation. :)
(And in addition I am not a native English speaker.) :D
Just to know, in this sentence the action of appearing is prior to the actions of copying and disappearing, couldn't this also be taken into account in English?

**Comment by zenseii** [comment]
> Hello @zenseii,
> 
> > The original game is gramatically wrong here, and the current way it is written in fheroes2 is correct.
> > For "had disappeared" to be correct, the whole sentence would have to be told as if it happened in the past: "Quickly you **copied** down the piece and the inscription **vanished** as abruptly as it **had appeared**."
> > To me it seems like the first person to write this string in fheroes2 corrected this, either intentionally or automatically, since the whole passage is told in the present.
> 
> I admit that I didn't pay attention to the conjugation. :) (And in addition I am not a native English speaker.) :D Just to know, in this sentence the action of appearing is prior to the actions of copying and disappearing, couldn't this also be taken into account in English?

Don't worry, I had to check up grammar online to make sure my hunch about fheroes2 correct was right.  Yes the inscription appeared before it vanished and this is indeed taken account for by the fact that vanishes is in present tense and appeared is in past. Not sure if this is what you meant.
