### ISSUE TITLE
Adventure map, Sirens, incorrect messages display 

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4698]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, there is incorrect messages display for sirens.

In original game:

![Passability test 078](https://user-images.githubusercontent.com/43583994/143583655-95563f4c-7606-4f62-9a30-ab4f90876b21.png)

![Passability test 080](https://user-images.githubusercontent.com/43583994/143583669-56c11245-22a0-4efb-b446-a1bc85c3c8d1.png)

In fheroes2:

![Passability test 079](https://user-images.githubusercontent.com/43583994/143583727-10b40d15-58f4-4a6c-9945-9c723fe15b37.png)

![Passability test 081](https://user-images.githubusercontent.com/43583994/143583755-eaa5bbe6-c32c-4709-a065-267bcf29a531.png)

**Edit.**

In original game:

This text should be displayed when there is only one creature in the hero's army (**Edit:** for the first visit only.).
![Test one creature](https://user-images.githubusercontent.com/43583994/143607668-5004ff41-bb7a-4314-83d7-388fa1cab1f7.png)

### Save file

Here are the save files:
[Sirens messages 01.zip](https://github.com/ihhub/fheroes2/files/7608821/Sirens.messages.01.zip)

**Comment by zenseii** [comment]
So basically the fheroes2 one should be divided into two dialogs?

**Comment by LeHerosInconnu** [comment]
Hello @zenseii,

> So basically the fheroes2 one should be divided into two dialogs?
> 
> Looking a bit closer it seems that the first part of the fheroes2 dialog should replace the dialog when you have already visited the sirens once.

The two original messages were combined in the first window in fheroes2, and a new message (which does not exist in the original game) was added in the second window to compensate for the mistake committed.

**Comment by zenseii** [comment]
So the fheroes2 unique dialog, the one about "your small, determined army" should be removed? Was it just made specifically for fheroes2 or is there a way to make it appear in the OG?

**Comment by LeHerosInconnu** [comment]
@zenseii.

> So the fheroes2 unique dialog, the one about "your small, determined army", should be removed? Was it made specifically for fheroes2 or is there a way to make it appear in the OG?

This text should be present in the original game actually, but I don't remember seeing it during a game.
Maybe it needs a special condition (e.g. with only one creature) for it to appear.
I'll do a test.

**Comment by LeHerosInconnu** [comment]
@zenseii.

Yes, that's it.
This text is displayed when there is only one creature in the hero's army.

In original game:

![Test one creature](https://user-images.githubusercontent.com/43583994/143607668-5004ff41-bb7a-4314-83d7-388fa1cab1f7.png)

**Comment by zenseii** [comment]
No, thank you! So to be clear this single creature specific text appears when you first visit the sirens or when you've already visited them, or in both cases? And even for 2 or such "small" quantities you will get the other message?

**Comment by LeHerosInconnu** [comment]
@zenseii.

> No, thank you! So to be clear this single creature-specific text appears when you first visit the sirens or when you've already visited them, or in both cases? And for 2 or such "small" quantities you will get the other message?

This message appears only after the first visit with a single creature army. :)
