### ISSUE TITLE
Game, multiplayer, difference in functioning compared to the original game

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4721]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2 currently, for the multiplayer, it doesn't work like in the original game.

After switching the position of the Blue player and the Orange player.
In the original game, the order of play of the player colors has been changed and the Orange player plays first and at the Orange player position on the adventure map.

https://user-images.githubusercontent.com/43583994/143768348-09041b73-18d7-4f97-a930-b7938ba295b3.mp4

Note that the player color graphic is not updated in the original game when the player swaps the Blue and Orange players.
I think it should be in fheroes2.

In fheroes2, this is not the case.

https://user-images.githubusercontent.com/43583994/143768416-1d24e872-d62c-439c-8f5f-d42dbfd5d950.mp4

### Save file

Not needed.

**Comment by oleg-derevenetz** [comment]
Currently the logic in fheroes2 in this regard is like in HoMM3: players bound to colors and the queue of moves is arranged according to the colors (humans first in the order of their colors and then AI - in the order of their colors as well: blue-green-red-...). There is no such thing as "first player", "second player" and so on, all these are just names bound to colors. Honestly, I don't see any gain in the ability to change the order of colors. If a player wants to have the first turn, it should select the color that has the first turn, it is simple and logical.

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu

> This is not possible with fheroes2.

I'm not sure that this is a bad thing. How you can figure out the order of turns by looking on the multiplayer screen in the OG? For example:

![multiplayer](https://user-images.githubusercontent.com/32623900/143925330-0965a89b-5f36-42f1-8f1f-f9c19b126804.jpg)

? Looking on this screen, can you figure out who will have the first turn and who will have the second? What if you have more players? :) Figuring this out is not an issue in HoMM3 (and in fheroes2 currently).

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> Hi @LeHerosInconnu
> 
> > This is not possible with fheroes2.
> 
> I'm not sure that this is a bad thing. How you can figure out the order of turns by looking at the multiplayer screen in the OG? For example:
> 
> ![multiplayer](https://user-images.githubusercontent.com/32623900/143925330-0965a89b-5f36-42f1-8f1f-f9c19b126804.jpg)
> 
> Looking at this screen, can you figure out who will have the first turn and who will have the second? What if you have more players? :) Figuring this out is not an issue in HoMM3 (and in fheroes2 currently).

That's why I specified this in the original post: :)

"Note that the player color graphic is not updated in the original game when the player swaps the Blue and Orange players.
I think it should be in fheroes2."

And the second video just below shows how it worked and allowed to see the order of play of the players' colors in the old version of fheroes2.

@zenseii.

> Interesting and I think that is a cool feature. However, I believe a better implementation than those arrows could be made to change the order of who gets to do their turn when, like a simple number showing the turn order or something above the player icon, because simply swapping the colors doesn't explain the player anything. Having the AI act first gives room for some interesting map introductions, but I digress.

In the original game, the human player always plays first.
If the human player chooses the orange color, the order is, human orange player, AI blue player, AI green player, etc.

In original game:

https://user-images.githubusercontent.com/43583994/143624715-db94b7b1-53a2-4620-a812-66b361bf70e1.mp4

With this feature, it becomes possible to change the order of play of the players.
If the user does not change the order of the players (by clicking on the red two-way arrows), then everything works as in the original game.
If the user changes the order of the players (by clicking on the red two-way arrows), then the players play from the left to the right, starting from the far left.

In old version of fheroes2 (previous team):

https://user-images.githubusercontent.com/43583994/143624684-bf5126b8-1e43-4679-8351-df7998815ddd.mp4

> Basically what you're saying is that the main function of these arrows doesn't work right now anyways? Also their icons do look a lot lower resolution than the rest of this beautiful window, probably because they are upscales of the the cursor for meeting heroes, but that is a bit besides the point.

The graphics are not great, but it was not the "final" version. :)
And there are also bugs in the old version of fheroes2 (previous team).
This no longer works in the latest version of fheroes2. :(

_Originally posted by @LeHerosInconnu in https://github.com/ihhub/fheroes2/discussions/4701#discussioncomment-1707489_
