### ISSUE TITLE
Adventure map, different hero path near Tar Pit compared to the original game

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4731]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the hero steps west and then south from the square northwest of the Tar Pit, while in Heroes 2, the hero steps 
directly obliquely southwest at the same position.

In original game:

![Path near Foundry 01](https://user-images.githubusercontent.com/43583994/144079516-fc414ec1-cfc8-4917-9afa-3a632a610773.png)

In fheroes2:

![Path near Foundry 02](https://user-images.githubusercontent.com/43583994/144079534-bd879170-c692-4407-9449-8a03c1061081.png)

### Save file

Here are the save files (Path near Foundry 01):
[Passability Dimension Door 01.zip](https://github.com/ihhub/fheroes2/files/7626980/Passability.Dimension.Door.01.zip)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , can you please verify this on a fresh new map with the latest build? I think this issue is being fixed some time ago. Passability rules are only applied at the start of a new map.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , can you please verify this on a fresh new map with the latest build? I think this issue is being fixed some time ago. Passability rules are only applied at the start of a new map.

You are right, it works correctly with a new scenario in version 0.9.9 4736. :)
