### ISSUE TITLE
Minimap display of mines and heroes is confusing

### ISSUE THREAD

**Issue by a1exsh** [ihhub/fheroes2#4746]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

After adding heroes on the minimap in #4707 we now have confusing display for the mines (both are displayed as single dots).

OG (sawmill looks bigger on the minimap):
![heroes2_010](https://user-images.githubusercontent.com/489601/143766627-cac3c205-56e9-4449-b004-8767a255ae39.png)

fheroes2 (sawmill looks exactly the same as a hero):
![image](https://user-images.githubusercontent.com/489601/143766654-6271f0e1-06de-4e4c-aa4e-d9e4f03b4670.png)

Mines should be displayed differently from heroes: it doesn't have to be exactly the same way as in OG, but the difference should be easy to tell on the minimap.

### Save file

No save file needed: just try on any map.

**Comment by LeHerosInconnu** [comment]
Hello @a1exsh,

I was just thinking about this yesterday :) and here is my suggestion.
The heroes' colored dots could flash slowly on the minimap, like the colors around the mines in the View Mines spell screen of the original game.
The representation of the resource generators on the minimap, could also be increased in surface (3 pixels by 2 pixels).
And thanks to the flashing hero dot, the hero would always be visible whether he is positioned on the active square, in front of or behind the resource generator, the flashing hero dot being always displayed over the resource generator on the minimap even if the hero is located behind on the adventure map.

In original game:

https://user-images.githubusercontent.com/43583994/116792367-6cc19200-aac0-11eb-962c-8de5fb8e5964.mp4

Related issue: https://github.com/ihhub/fheroes2/issues/3319.
