### ISSUE TITLE
"Town Population Information and Statistics" screen (Well screen) and "Towns/Castles Kingdom Overview" screens, aesthetic improvements

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4749]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Hello @ihhub,

The creature recruitment window has been centered in the "Well" and "Towns/Castles Kingdom Overview" screens.
The aesthetics of these windows could be improved.

### Describe the possible solution

In fheroes2:

From an aesthetic point of view, I suggest moving the recruitment window down 2 pixels in the "Well" screen to avoid seeing that part of the creature's Dwelling graphic indicated by the red arrow.
![Recruit windon position well flèche 01](https://user-images.githubusercontent.com/43583994/144719401-1b4816e6-abd2-4186-9e82-3aeb589b5a86.png)

And, still from an aesthetic point of view, for the "Towns/Castles Kingdom Overview" screen, I suggest to center vertically the recruitment window in the upper part of the screen, indicated by the red frame, in order to avoid cutting and also hiding the resource generators graphics.
![Recruit window position town overview cadre 02](https://user-images.githubusercontent.com/43583994/144719413-879eb680-1b1d-46ff-bbb1-c002254eb15b.png)
![Recruit window position town overview 01](https://user-images.githubusercontent.com/43583994/144719409-d96931ff-4051-4b5a-88ef-be534f4effe3.png)

### Additional info

Related closed issue: https://github.com/ihhub/fheroes2/issues/4596.

**Comment by Kazhuu** [comment]
I'd like to take stab at this.
