### ISSUE TITLE
cannot find the music (error Cyrillic directory path)

### ISSUE THREAD

**Issue by shikulja** [ihhub/fheroes2#4755]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

If the path to the game directory contains Cyrillic, then the game cannot find the music

![image](https://user-images.githubusercontent.com/3386359/144760118-236b7dc2-b1b5-4c5c-8fb9-41563cd2aac5.png)

### Save file

-

**Comment by shikulja** [comment]
In addition, the buka version of the game is still not working, due to the names of the game directories other than gog
Tracks2  (02-AudioTrack 02.ogg) \ Anim2

**Comment by oleg-derevenetz** [comment]
Looks like some incompatibility between encoding of file names returned by `FindFirstFile()`/`FindNextFile()` in fheroes2 and encoding that SDL_Mixer expects in its `Mix_LoadMUS()` call. According to the screenshot, it looks like the former uses xxxA family of these functions (and the file names returned by `FindFirstFileA()`/`FindNextFileA()` is 8-bit Windows-1251), while the latter is built with xxxW family of Windows functions and expects file names in UNICODE.

**Comment by vincent-grosbois** [comment]
> Looks like some incompatibility between encoding of file names returned by `FindFirstFile()`/`FindNextFile()` in fheroes2 and encoding that SDL_Mixer expects in its `Mix_LoadMUS()` call. According to the screenshot, it looks like the former uses xxxA family of these functions (and the file names returned by `FindFirstFileA()`/`FindNextFileA()` is 8-bit Windows-1251), while the latter is built with xxxW family of Windows functions and expects file names in UNICODE.

Mix_LoadMUS() delegates to this : 
https://wiki.libsdl.org/SDL_RWFromFile
apparently this is UTF8. is this the same as UNICODE ?

**Comment by oleg-derevenetz** [comment]
> apparently this is UTF8. is this the same as UNICODE ?

No, Windows uses UTF-16LE with its xxxW family of functions.

**Comment by oleg-derevenetz** [comment]
Hi @shikulja Could you please verify that #4802 solves your issue? You can get binaries by clicking on the "Details" link of the AppVeyor build, selecting the appropriate configuration (SDL2/x64 I suppose) and then clicking on the "Artifacts" link in the upper right corner.

**Comment by shikulja** [comment]
@oleg-derevenetz
Yes, it helped, now the .ogg musiс is played without problems.

**Comment by oleg-derevenetz** [comment]
Hi @shikulja I moved the Buka-related stuff to the separate issue (#4806), so we can handle it later.
