### ISSUE TITLE
Button rendering artifacts after changing resolution

### ISSUE THREAD

**Issue by a1exsh** [ihhub/fheroes2#4762]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

First reported by @ihhub in https://github.com/ihhub/fheroes2/pull/4748#issuecomment-986262150

> if I change resolution of the game OKAY button has incorrect rendering: ![image](https://user-images.githubusercontent.com/19829520/144755225-7f18cbcb-08dd-4f20-af0f-f1ebba79a214.png)

### Save file

No save file needed.

### Additional info

It is not always immediately visible, one might need to change resolution more than once to start seeing it:
![Screenshot from 2021-12-08 07-50-14](https://user-images.githubusercontent.com/489601/145162053-a8c53647-0569-49a0-bffd-aa84268846eb.png)

Also, it seems that all buttons that use the new background-capturing code from #4350 are affected:
![Screenshot from 2021-12-08 07-51-14](https://user-images.githubusercontent.com/489601/145162222-c133a89f-daf7-4838-9aff-282357a8c59a.png)

**Comment by a1exsh** [comment]
@ihhub additionally, when I tried to retreat (in Battle mode), I've seen that fading animation was not right:
![Screenshot from 2021-12-08 07-52-36](https://user-images.githubusercontent.com/489601/145162541-13cd5355-cc82-42f4-b7a5-b0fad4734703.png)

I wonder if this is related to our changes or to changing resolution in general.

**Comment by a1exsh** [comment]
> I wonder if this is related to our changes or to changing resolution in general.

So I've just checked with a clean build on the commit before our changes for the button shadows and I can reproduce the problem the fading:

1. Open the game.
2. Start the default battle, retreat => all looks good.
3. Change resolution.
4. Start the default battle, retreat => observe fading problem.

**Comment by oleg-derevenetz** [comment]
I suppose that's because `Display::_prevRoi` is not updated when `Display::resize()` is called, and therefore `getBoundaryRect(temp, _prevRoi)` in the `Display::render()` calculates incorrect ROI (for example, it can out of bounds when resolution was changed from the bigger one to the smaller one), and therefore there may be out-of-bounds write in the `BaseSDLRenderer::copyImageToSurface()` and may be other places too. Hi @ihhub can you please take a look? I suppose we should reset the `_prevRoi` to the default value `{0, 0, 0, 0}`, but you should know better :)

**Comment by ihhub** [comment]
Sure, I'll take a look.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub there is still an issue with renderer:

```
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = watchpoint
    frame #0: 0x00000001019c5429 fheroes2`(anonymous namespace)::BaseSDLRenderer::copyImageToSurface(this=0x000060f000001310, image=0x0000000102be4cc0, surface=0x00006080000555a0, roi=0x00007ffeefbfc230) at screen.cpp:244:35
    frame #1: 0x0000000101999840 fheroes2`(anonymous namespace)::RenderEngine::render(this=0x000060f000001300, display=0x0000000102be4cc0, roi=0x00007ffeefbfc230) at screen.cpp:851:13
    frame #2: 0x000000010198fe0b fheroes2`fheroes2::Display::_renderFrame(this=0x0000000102be4cc0, roi=0x00007ffeefbfc230) const at screen.cpp:1373:22
  * frame #3: 0x000000010198d5b0 fheroes2`fheroes2::Display::render(this=0x0000000102be4cc0, roi=0x00007ffeefbfc800) at screen.cpp:1345:13
    frame #4: 0x000000010198a819 fheroes2`fheroes2::Display::render(this=0x0000000102be4cc0) at screen.cpp:1311:9
    frame #5: 0x000000010099c619 fheroes2`(anonymous namespace)::showConfigurationWindow() at dialog_game_settings.cpp:144:17
    frame #6: 0x000000010099aacd fheroes2`fheroes2::openGameSettings() at dialog_game_settings.cpp:212:30
    frame #7: 0x0000000100d8ddd7 fheroes2`Game::NewGame() at game_newgame.cpp:434:13
    frame #8: 0x0000000100d62585 fheroes2`Game::mainGameLoop(isFirstGameRun=false) at game_mainmenu.cpp:77:22
    frame #9: 0x0000000100c3c44b fheroes2`main(argc=1, argv=0x00007ffeefbff988) at fheroes2.cpp:230:9
    frame #10: 0x00007fff204eff3d libdyld.dylib`start + 1
    frame #11: 0x00007fff204eff3d libdyld.dylib`start + 1
(lldb) frame select 3
frame #3: 0x000000010198d5b0 fheroes2`fheroes2::Display::render(this=0x0000000102be4cc0, roi=0x00007ffeefbfc800) at screen.cpp:1345:13
   1342	            Copy( backup, 0, 0, *this, backup.x(), backup.y(), backup.width(), backup.height() );
   1343	        }
   1344	        else {
-> 1345	            _renderFrame( getBoundaryRect( temp, _prevRoi ) );
   1346	
   1347	            if ( _postprocessing != nullptr ) {
   1348	                _postprocessing();
(lldb) print temp
(fheroes2::Rect) $13 = (x = 0, y = 0, width = 640, height = 480)
(lldb) print _prevRoi 
(fheroes2::Rect) $14 = (x = 485, y = 533, width = 96, height = 25)
(lldb) print getBoundaryRect( temp, _prevRoi )
(fheroes2::Rect) $15 = (x = 0, y = 0, width = 640, height = 558)
(lldb) frame select 0
frame #0: 0x00000001019c5429 fheroes2`(anonymous namespace)::BaseSDLRenderer::copyImageToSurface(this=0x000060f000001310, image=0x0000000102be4cc0, surface=0x00006080000555a0, roi=0x00007ffeefbfc230) at screen.cpp:244:35
   241 	                        const uint8_t * inX = inY;
   242 	
   243 	                        for ( ; outX != outXEnd; ++outX, ++inX )
-> 244 	                            *outX = *( transform + *inX );
   245 	                    }
   246 	                }
   247 	                else if ( surface->format->BitsPerPixel == 8 ) {
(lldb) print roi 
(const fheroes2::Rect) $16 = (x = 0, y = 0, width = 640, height = 558)
(lldb) print outX
(uint32_t *) $17 = 0x0000000113a4a828
(lldb) print surface->pixels 
(void *) $18 = 0x000000011391e820
```

The difference between `outX` and `surface->pixels` here is already 1228808 bytes, while 640x480 32 bpp image occupies 640x480x4=1228800 bytes, so we have out-of-bounds write here and a memory corruption somewhere. This happens for example after changing screen resolution from 1024x768 to 640x480 because `_prevRoi` is not valid for a new screen resolution anymore.

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , I think Visual Studio doesn't catch out if bounds in this case. You're right about resizing. I'm wondering why I haven't encountered such... I'll fix it as well.
