### ISSUE TITLE
Scenario adjustment window, AI icons have light blue edge

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4772]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Right edge of AI player's name box has light blue line. You can notice that while selecting which color will be played by human or AI.
![ezgif com-gif-maker (32)](https://user-images.githubusercontent.com/55348946/145581347-2912fbfc-9361-48d2-b254-5356196dc909.gif)

### Save file

Enter single/multiplayer scenario window.

**Comment by vincent-grosbois** [comment]
Should we really tag these ones as bug ?

**Comment by Branikolog** [comment]
Hi, @vincent-grosbois.
Isn't it a small bug of UI rendering?

**Comment by vincent-grosbois** [comment]
It really depends on the definition of bugs ;) It seems that all issues tagged in the repo are all *bugs* be it logic error or small UI issues

**Comment by Branikolog** [comment]
@vincent-grosbois 
Well, nevertheless they are all bugs. 😄 No matter it being logic, AI or UI. 
I think, bug/enhancement labels are primary ones (making it clear, is it a bug, or some sort of new feature). So you should force your attention on the second label, which itemizes, what sort of bug it is.

**Comment by ihhub** [comment]
This is original resources bug.
