### ISSUE TITLE
View World window, minimap's selection frame doesn't reach right and bottom edges at some maps.

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4773]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

While moving over view world map, red selection frame comes closer to the left upper edge comparing to right bottom edge:
![image](https://user-images.githubusercontent.com/55348946/145582648-a26bf415-79b6-462d-b27a-893c7204b9eb.png)
![image](https://user-images.githubusercontent.com/55348946/145582665-2f024711-9b0b-46e2-8b85-d3a7a0fadbbc.png)

### Save file

The issue is 100% reproduceable at "Broken Alliance" map.

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

There is already an issue for this: https://github.com/ihhub/fheroes2/issues/4200. :)

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu!
Oh, couldn't find it...
Could you, please, specify the problem in your topic, as it seems for me not obvious, what's the issue there. The position of reticule doesn't seemed to be incorrect for me. It looks like its size doesn't correspond the size of visible screen, that's why in some cases it doesn't fit right and bottom edges of minimap.

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

> Hi, @LeHerosInconnu! Oh, couldn't find it... Could you, please, specify the problem in your topic, as it seems for me not obvious, what's the issue there. The position of reticule doesn't seemed to be incorrect for me. It looks like its size doesn't correspond the size of visible screen, that's why in some cases it doesn't fit right and bottom edges of minimap.

Done. :)

**Comment by Branikolog** [comment]
@LeHerosInconnu 
Thank you! :)
