### ISSUE TITLE
Battle screen, right click info window shouldn't be initiated by clicking on enemy hero or own/enemy captain.

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4775]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

As we cannot check info of enemy hero or our/enemy captain, we should show this info window:
![image](https://user-images.githubusercontent.com/55348946/145584594-8ce05294-0c51-40c1-9871-643d9c83e478.png)

### Save file

Initiate any battle with a hero or castle guarded by captain.

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

What about the "Cast Spell", "Retreat" and "Surrender" buttons?
(Depending on the case, if it is an opposing hero, or a player's or opponent's captain.)
The texts are also addressed to the player, as if it were his own hero.

**Comment by Branikolog** [comment]
Hello, @LeHerosInconnu !

> What about the "Cast Spell", "Retreat" and "Surrender" buttons? (Depending on the case, if it is an opposing hero, or a player's or opponent's captain.) The texts are also addressed to the player, as if it were his own hero.

These buttons have "disabled" state indicating that you cannot use them. But showing an info window, that "opens hero screen to view full information" misleads player, indicating that he can check enemy hero info, which is not possible.

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

> Hello, @LeHerosInconnu !
> 
> > What about the "Cast Spell", "Retreat" and "Surrender" buttons? (Depending on the case, if it is an opposing hero, or a player's or opponent's captain.) The texts are also addressed to the player, as if it were his own hero.
> 
> These buttons have "disabled" state indicating that you cannot use them. But showing an info window, that "opens hero screen to view full information" misleads player, indicating that he can check enemy hero info, which is not possible.

In the original game, in the presented case, only the information window of the "CANCEL" button can be displayed.
I suggest to do the same in fheroes2 as the text of these windows is not adapted to the player, or to modify the text of these windows accordingly.
The first solution suits me perfectly. :)
**Note:** The text in the information bar at the bottom of the screen should also be modified accordingly.
I can open another issue if necessary.

**Comment by Arthusppp** [comment]
I propose the following:
* when the Cast, Retreat, or Surrender button is disabled, a player cannot right-click on it
* when the Cast, Retreat, or Surrender button is disabled, the game does not display any tooltip
* the Hero Screen dialog is not present when a player clicks on the opposing hero

What I did not change:
* when the Cast, Retreat, or Surrender button is enabled, a player can right-click on it and the game displays a tooltip
* I have not touched the current logic that evaluates if 
whether a button is enabled or not

My test map: [4775.zip](https://github.com/ihhub/fheroes2/files/7786636/4775.zip). (Hot Seat/two players)

**Comment by LeHerosInconnu** [comment]
Hello @Arthusppp and @Branikolog,

> I propose the following:
> 
> * when the Cast, Retreat, or Surrender button is disabled, a player cannot right-click on it
> * when the Cast, Retreat, or Surrender button is disabled, the game does not display any tooltip
> * the Hero Screen dialog is not present when a player clicks on the opposing hero
> 
> What I did not change:
> 
> * when the Cast, Retreat, or Surrender button is enabled, a player can right-click on it and the game displays a tooltip
> * I have not touched the current logic that evaluates if
>   whether a button is enabled or not
> 
> My test map: [4775.zip](https://github.com/ihhub/fheroes2/files/7786636/4775.zip). (Hot Seat/two players)

I tested this change, and I think this should only be applied to the opposing hero or captain.
The player should be able to have the information about the buttons of his own hero even when they are grayed out.

For the player-controlled captain, the texts of the button information windows should be adapted to the possibilities (the captain cannot flee, surrender, etc.).

In fheroes2:

Retreat button.
![Captain info buttons 001](https://user-images.githubusercontent.com/43583994/147666878-8cf69da2-bad3-459f-a71c-0d295e843321.png)

"Retreat

The Captain cannot retreat, so he must fight until the end of the combat."
![Captain info buttons 002](https://user-images.githubusercontent.com/43583994/147666896-8c748445-3547-4937-b08d-a6815336491d.png)

Surrender button.
![Captain info buttons 003](https://user-images.githubusercontent.com/43583994/147666919-613ad704-7f0e-493e-81bb-aa3382cc8a96.png)

"Surrender

The captain cannot surrender, so he must fight until the end of the combat."
![Captain info buttons 004](https://user-images.githubusercontent.com/43583994/147666934-5c09fc80-79d0-46a5-912b-7d9f4303ada0.png)

Captain portrait.
![Captain info buttons 005](https://user-images.githubusercontent.com/43583994/147667032-1e449dc6-788e-4e1e-b803-fd85c85e6063.png)

"Captain Screen

It is not yet possible to access the Captain screen."
![Captain info buttons 006](https://user-images.githubusercontent.com/43583994/147667048-6e4de3fd-fc55-4ebd-85fc-eb29fdad5246.png)

I think that the captain could have a screen where it is possible to have information about the creatures (https://github.com/ihhub/fheroes2/issues/3542).

I will open other issues or discussions for this.

**Comment by Arthusppp** [comment]
> I tested this change, and I think this should only be applied to the opposing hero or captain.
> The player should be able to have the information about the buttons of his own hero even when they are grayed out.

Given the above, I propose the following:
1. When viewing the player's hero:
* the Hero Screen is always available
* Cast, Retreat, and Surrender buttons are available as it was before (logic remains unchanged). The tooltip text is displayed, it is possible to right-click on the button (right-click displays an information popup)
2. When viewing the player's captain:
* the Hero Screen is disabled, no tooltip, right-click is unavailable
* the Cast button is always enabled
* Retreat and Surrender buttons are unavailable and no tooltip is displayed 

3. When viewing an opposing hero/captain:
* the Hero Screen is always unavailable, no tooltip is displayed, right-click is disabled
* Cast, Retreat, and Surrender buttons are unavailable, no tooltip is displayed, right-click is disabled
* the Cancel button is present, the tooltip is displayed, right-click displays the information popup

The save for testing is the same as before.

Next step here: I like the idea to customize all captain's texts ("Capitan cannot retreat", etc.). Please start the discussion (or open a dedicated issue), I believe is worth implementing it.

**Comment by Branikolog** [comment]
@LeHerosInconnu 

>For the player-controlled captain, the texts of the button information windows should be adapted to the possibilities (the captain cannot flee, surrender, etc.).

As well as for defending heroes.

**Comment by LeHerosInconnu** [comment]
Hello @Arthusppp and @Branikolog,

> Hello @LeHerosInconnu!
> 
> Next step here: I like the idea to customize all captain's texts ("Capitan cannot retreat", etc.). Please start the discussion (or open a dedicated issue), I believe is worth implementing it.

> @LeHerosInconnu
> 
> > For the player-controlled captain, the texts of the button information windows should be adapted to the possibilities (the captain cannot flee, surrender, etc.).
> 
> As well as for defending heroes.

Discussion here: https://github.com/ihhub/fheroes2/discussions/4867.

**Comment by Arthusppp** [comment]
@ihhub Ready for review.
