### ISSUE TITLE
The game crashes when I try to load scenario

### ISSUE THREAD

**Issue by lua-rocks** [ihhub/fheroes2#4776]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

When I try to load the game from this [save](https://github.com/ihhub/fheroes2/files/7694982/save.zip), it crashes.

### Save file

[save](https://github.com/ihhub/fheroes2/files/7694982/save.zip)

### Additional info

```
fheroes2: ../fheroes2/game/game_campaign.cpp:242: void {anonymous}::setHeroAndArmyBonus(Heroes*, int, uint32_t): Assertion `0' failed.
fish: Job 1, './fheroes2' terminated by signal SIGABRT (Abort)
```

**Comment by a1exsh** [comment]
Isn't it already fixed by https://github.com/ihhub/fheroes2/pull/4768 ?

**Comment by lua-rocks** [comment]
Sorry, I just downloaded latest version and didn't look at the git changes. I'll try to build from source and report back. One moment :)

**Comment by lua-rocks** [comment]
Yes, it is fixed. thank you, @a1exsh!

**Comment by dknight** [comment]
I have same issue on evil campaign level 5, cannot start the level 5 because this error

`/fheroes2/game/game_campaign.cpp:242: void {anonymous}::setHeroAndArmyBonus(Heroes*, int, uint32_t): Assertion `0' failed.`

**Comment by lua-rocks** [comment]
@dknight this bug is fixed in **master** branch. You can build it from source or wait for next release.

**Comment by lua-rocks** [comment]
@dknight here is fixed binary for Linux x64

[fheroes2.zip](https://github.com/ihhub/fheroes2/files/7741296/fheroes2.zip)

**Comment by dknight** [comment]
@lua-rocks Thanks for the build, but I built it myself on my Fedora machine. Very easy to build.
`sudo dnf install SDL2-devel`
`make`

thats all :)
