### ISSUE TITLE
Adventure map, the square information window just below the active castle square displays "Road... penality: 75" when it should display "Dirt... penality: 100" as there is no road portion connected to this square

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4782]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the square information window just below the active castle square displays "Road... penality: 75" when it should display "Dirt... penality: 100" as there is no road portion connected to this square.

In fheroes2:

The hero is in the castle with 1000 movement points:
![Info square south castle entrance 001](https://user-images.githubusercontent.com/43583994/145717031-f945508f-1dee-442e-9b13-19e107dbf14d.png)
![Info square south castle entrance 002](https://user-images.githubusercontent.com/43583994/145717024-508b379f-5702-4411-be25-258fe8561fac.png)

The square information window just below the active castle square displays "Road... penality: 75" when it should display "Dirt... penality: 100" as there is no road portion connected to this square:
![Info square south castle entrance 003](https://user-images.githubusercontent.com/43583994/145717047-f54d7301-0e43-4873-8033-124ed80ea33e.png)
![Info square south castle entrance 004](https://user-images.githubusercontent.com/43583994/145717051-3aeff6f0-10da-4dfa-a0e8-087751837f44.png)

The hero has moved out of the castle, he has spent 75 movement points, it's alright:
![Info square south castle entrance 005](https://user-images.githubusercontent.com/43583994/145717061-855f52f6-efe6-4526-ab67-a63bb8e60e1b.png)
![Info square south castle entrance 006](https://user-images.githubusercontent.com/43583994/145717068-d5d36e77-e682-495f-8025-955382dd56d8.png)

The hero has moved one more step south, he has spent 100 movement points, it's alright:
![Info square south castle entrance 007](https://user-images.githubusercontent.com/43583994/145717076-2a1f4169-d334-4b04-b3d8-9bb84c26b301.png)
![Info square south castle entrance 008](https://user-images.githubusercontent.com/43583994/145717078-4cae3b0a-7f63-49a6-96ec-edd3aab5de44.png)

So, only "Road... penality: 75" in the square information window is erroneous.

Here is the test scenario file:
[0 9941.zip](https://github.com/ihhub/fheroes2/files/7698933/0.9941.zip)

### Save file

Not needed.

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu I cannot reproduce this issue with the latest build. Consider:

<img width="636" alt="Castle entrance terrain" src="https://user-images.githubusercontent.com/32623900/146433026-a76e8b3e-5e59-42f9-844a-8545a3c484a4.png">

Either you used some version without changes from #4756 or you used version with those changes but loaded a savefile made by some previous version instead of starting the map from scratch.

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> Hi @LeHerosInconnu I cannot reproduce this issue with the latest build.
> Either you used some version without changes from #4756 or you used version with those changes but loaded a savefile made by some previous version instead of starting the map from scratch.

You are right, it works correctly with version 0.9.10 4734.
I certainly tried with the version just before #4756.
Sorry for the inconvenience, I close the issue. :)
