### ISSUE TITLE
Adventure map, wrong penalty applied for a horizontal move from a road to the snow terrain

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4783]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, there is a wrong penalty applied for a horizontal move from a road to the snow terrain.

In fheroes2:

The hero is in the castle with 1000 movement points:
![Road to snow 001](https://user-images.githubusercontent.com/43583994/145719047-2819f91c-b4c1-4515-b590-3889d0e177aa.png)
![Road to snow 002](https://user-images.githubusercontent.com/43583994/145719054-14d782ac-88e5-474c-8e11-252e9ab1a267.png)

The hero has moved out of the castle, he has spent 75 movement points, it's alright:
![Road to snow 003](https://user-images.githubusercontent.com/43583994/145719102-aed7451d-ae5c-41e9-8ce4-900543345446.png)
![Road to snow 004](https://user-images.githubusercontent.com/43583994/145719108-e9f095b0-c995-4aa0-83e8-f52dbcfa26ab.png)

The hero has moved one more step south, he has spent 75 movement points, it's alright:
![Road to snow 005](https://user-images.githubusercontent.com/43583994/145719125-1517aac6-c989-4fd0-8621-fe68a6f2c744.png)
![Road to snow 006](https://user-images.githubusercontent.com/43583994/145719134-6a06e7bd-c790-401f-bdd0-cd2899436abd.png)

The hero has moved one step east from the road to the snow terrain, he has spent 150 movement points:
![Road to snow 007](https://user-images.githubusercontent.com/43583994/145719203-9fe51198-e279-4309-8e1b-ef88fae5cc38.png)
![Road to snow 008](https://user-images.githubusercontent.com/43583994/145719206-c22b5fbd-8e89-4107-8c67-8f7d99616a58.png)
![Road to snow 009](https://user-images.githubusercontent.com/43583994/145719213-58b5bf83-bea4-4087-b6f0-7d7237be1abc.png)

This is not correct, the hero should have spent only 75 movement points because it is the penalty of the road where he is located at the start of the movement that should be taken into account.

Here is the test scenario file:
[0 9941.zip](https://github.com/ihhub/fheroes2/files/7698933/0.9941.zip)

### Save file

Not needed.

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu

> This is not correct, the hero should have spent only 75 movement points because it is the penalty of the road where he is located at the start of the movement that should be taken into account.

I disagree. Road bonus should be applied only when moving from one tile WITH A ROAD to the other tile WITH A ROAD, which is specifically mentioned [here](https://handbookhmm.ru/2-logistics):

> Герой получает бонус при передвижении по дороге только в том случае, если делает шаг с дороги на дорогу или, находясь на дороге, взаимодействует с объектом, также расположенным на дороге.

which literally means this:

> The hero gets a bonus when moving along the road only if he takes a step from the road to the road or, while on the road, interacts with an object also located on the road.

When hero performs a horizontal move here, it moves from a tile with the road to a tile without road, so full snow terrain penalty should be applied, and not the road penalty.

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> Hi @LeHerosInconnu
> 
> > This is not correct, the hero should have spent only 75 movement points because it is the penalty of the road where he is located at the start of the movement that should be taken into account.
> 
> I disagree. Road bonus should be applied only when moving from one tile WITH A ROAD to the other tile WITH A ROAD, which is specifically mentioned [here](https://handbookhmm.ru/2-logistics):
> 
> > Герой получает бонус при передвижении по дороге только в том случае, если делает шаг с дороги на дорогу или, находясь на дороге, взаимодействует с объектом, также расположенным на дороге.
> 
> which literally means this:
> 
> > The hero gets a bonus when moving along the road only if he takes a step from the road to the road or, while on the road, interacts with an object also located on the road.
> 
> When hero performs a horizontal move here, it moves from a tile with the road to a tile without road, so full snow terrain penalty should be applied, and not the road penalty.

Ah yes, you're right, there is this special rule for the road. :)
I did a test with all the interactions from a road (attack, meeting, resource capture, etc.), it works fine.
I close the issue.
