### ISSUE TITLE
Adventure map screen, Minimap, wrong castles representation on the minimap

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4785]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, there is a wrong castles representation on the minimap.

In fheroes2:

On the minimap, the three Wizard castles at the bottom of the minimap are represented differently from the three castles at the top of the minimap.
The bottom large rectangle representing the base of the castle (so without the central "tower") of the lower castle has an extra row of pixels at the top of the rectangle compared to the correct representation of the upper castle.
![Castle minimap 01](https://user-images.githubusercontent.com/43583994/145723452-0be5ea74-13df-43eb-ad5c-7f220bddbd48.png)

This can be seen with the hero positioned just on the square north of the road (the hero is not on the road) to the right of the lower castle on the minimap and with the path of the same hero on the adventure map.
![Castle minimap different 01](https://user-images.githubusercontent.com/43583994/145723517-c50325b0-33fa-4015-b28e-f4ea7cb1054c.png)

Also, the brown square (supposed to represent the road penalty of the active castle square) in the castle representation is not at the right position.
This brown square should be positioned just above its current position (the current position is the square just south of the active castle square).
(There is also a square information window  bug reported here: https://github.com/ihhub/fheroes2/issues/4782.)
Brown square position adjusted for the top three castles on the minimap:
![Castle minimap modifié 01](https://user-images.githubusercontent.com/43583994/145723552-bb8c07d0-40eb-44f6-8013-03dcbd857735.png)

Open the two images in different tabs in your browser, enlarge the images and switch between the two tabs alternately.
Fheroes2 with brown square at current position first, fheroes2 with brown square position corrected for the top three castles on the minimap second.
For the fheroes2 corrected position:
Left castle, without a road connected to the square just south of the active castle square.
Middle castle, with a road connected to the square just south of the active castle square, a hero is positioned two squares south and one square east of the active castle square.
Right castle, without a road connected to the square just south of the active castle square, a hero is positioned two squares south of the active castle square.
![Castle minimap coupé 01](https://user-images.githubusercontent.com/43583994/145723558-3cbf4845-35a0-48a8-a06b-7345df2b5253.png) ![Castle minimap modifié coupé 01](https://user-images.githubusercontent.com/43583994/145723559-10f7ea07-6ec9-429d-ad90-900fad447b3f.png)

Here is the test scenario file:
[0 9941.zip](https://github.com/ihhub/fheroes2/files/7698933/0.9941.zip)

### Save file

Not needed.

**Comment by vincent-grosbois** [comment]
This is due to difference in sizes between minimap size and map size. Basically, one square in the real map can map to several minimap pixels or none, depending on where the map square is located.
Not sure how it's possible to fix this

**Comment by ihhub** [comment]
I am closing this issue as we aren't going to fix it due to simple math restrictions :)

**Comment by Branikolog** [comment]
Hi, @ihhub 
I understand, that we have an issue with map and minimap sizes here, but I think, all objects representation should be always the same. For instance, a hero is shown as a dot. We're not showing him as a two dots, right? Making castle representation different depending on place of minimap could confuse players.
So as a solution here I propose to make all objects representation consistent, but stretch the map itself or shift for one cell up\down the castle box.
