### ISSUE TITLE
Home screen, the right side of the door is not included in the clickable area

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4787]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

In fheroes2, the right side of the door is not included in the clickable area.

### Describe the possible solution

I suggest to extend the clickable area to the whole door and even to its frame, indicated by the red rectangle.

In fheroes2:

![Door clickable area cadre 01](https://user-images.githubusercontent.com/43583994/145864265-356d3ad7-6184-4b99-a52c-27c2e28b79b2.png)

**Comment by ihhub** [comment]
I disagree with this suggestion. We should not allow clickable areas to be too close to each other.
