### ISSUE TITLE
Experimental Game Settings window, when the French language is selected, there is a graphic problem at the bottom of the list because two of the texts are written on three lines

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4791]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, when the French language is selected, there is a graphic problem at the bottom of the list because two of the texts are written on three lines.

In fheroes2:

![Options text 3 lines 001](https://user-images.githubusercontent.com/43583994/146017815-2a304671-1a9a-428b-90d3-748426e360c8.png)

![Options text 3 lines 002](https://user-images.githubusercontent.com/43583994/146017835-81616ec2-4c0a-4754-b612-654fdc8bce4e.png)

![Options text 3 lines 003](https://user-images.githubusercontent.com/43583994/146017872-27a0b821-7510-44b0-aa91-1dc4caa5d0fa.png)

### Save file

Not needed.

**Comment by dimag0g** [comment]
One obvious solution is to find shorter translations which fit on two lines:

    château : les guildes de magiciens régénèrent 20% de mana/tour par niveau
    héros : les points de mouvement sont mémorisés après la retraite/reddition

**Comment by Branikolog** [comment]
Hi, @dimag0g.
The same problem occurs in Russian too.

**Comment by ihhub** [comment]
I am closing this issue as we are about to delete this dialog.
