### ISSUE TITLE
Home screen, Language selection window, when the user selects a language, the window title is not changed to that language

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4794]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

In fheroes2, when the user selects a language, the window title is not changed to that language.

In fheroes2:

![Title language window 001](https://user-images.githubusercontent.com/43583994/146238833-a3ad7d4d-a66a-4796-85fd-14a665628b21.png)

![Title language window 002](https://user-images.githubusercontent.com/43583994/146238861-8e288183-ec44-4546-8450-2db5245aa365.png)

![Title language window 003](https://user-images.githubusercontent.com/43583994/146238879-47562f1f-7cdb-48bc-a246-0dabbcc416f8.png)

![Title language window 004](https://user-images.githubusercontent.com/43583994/146238899-c4f611d6-b2db-4e9f-891b-184f132f965b.png)

### Describe the possible solution

When the user selects a language, the window title should be changed to that language.

**Comment by dimag0g** [comment]
If dynamic language change is too difficult to implement, at least the game should tell the user to restart in order to complete the language change.
