### ISSUE TITLE
Game, a save game in French language loaded in the program set in English language and continued to play let appear the text in French in the Tavern's rumor

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4795]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, a save game in French language loaded in the program set in English language and continued to play let appear the text in French in the Tavern's rumor.

In fheroes2:

![Tavern french 01](https://user-images.githubusercontent.com/43583994/146384676-54e849a5-21a4-479e-8582-f5e6890fabbb.png)

### Save file

Here is the save file:
[Tavern french 01.zip](https://github.com/ihhub/fheroes2/files/7727794/Tavern.french.01.zip)

**Comment by ihhub** [comment]
This is due to a fact that don't call translation upon retrieving the message but only at the time of its first creation.

**Comment by zenseii** [comment]
I believe a similar issue is with regards to player names and when they are generated if you start with for example French and open the game info/scenario info window then you will see that the player names are according to player colors like " Vert" (green player), "Rouge" (red player) and "Bleu" (blue player). If you then exit and go and change language to for example English, and reopen the same window from before then the names will still be in French, so Vert, Rouge, Bleu.
