### ISSUE TITLE
Translation, problems encountered with the French language

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4797]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

So, here are the problems I noticed.

The letter "é" in "Résolution" and "Expérimental".
The word "Language" should be "Langage".
The word "Experimental" should be "Expérimentaux".
All words certainly not translated.
![French translation 001](https://user-images.githubusercontent.com/43583994/146010111-ac04a9db-f22f-4a53-aef1-0fee9fd6a9b4.png)

Problem with "Random".
**Edit 2021/12/23:** The word "Random" could be replaced by the word "Hasard".
![French translation 008](https://user-images.githubusercontent.com/43583994/146010224-df286a78-735e-4fc1-bc73-ca3a6557e455.png)

The word "Connaissance" is too long.
The word "Connaissance" could be replaced by "Savoir".
And "Pt de magie" could be replaced by "Mana".
![French translation 009](https://user-images.githubusercontent.com/43583994/146010281-8242037a-289d-4b0e-b4dc-90c9d0b6c3db.png)

The word "Plusieurs" is too long.
The word "Plusieurs" could be replaced by "Quelques" a slightly shorter word.
(It would be better to use the corresponding numbers "5-9".) :D
![French translation 018](https://user-images.githubusercontent.com/43583994/146010466-1bc4d4ee-ba8e-4341-bda6-d48d6335b3c5.png)

Apart from that, there are still texts in English, errors with masculine and feminine forms, articles "le", "la" not accorded with the noun, etc. (https://github.com/ihhub/fheroes2/discussions/4827)

### Save file

Not needed.

**Comment by dimag0g** [comment]
I tried to fix most of the things in https://github.com/ihhub/fheroes2/pull/4851, except for the following:

"Savoir" is nice, but "Connaissance" is used in a lot of places, including artefact names. I'd rather not rename these, googling for "ultime livre du savoir" and finding nothing is not cool.

"Quelques" sounds good, but I would like a second opinion on this one before making the changes, as "Plusieurs" is used in the GoG version.

Regarding (#4827):
- "cost per troop" is not rendered as text, it is part of the background image. You need to get a French version of the game to get it translated.
- "Le Château ... augmente les revenus de 1000 pièces" is wrong. The castle doesn't increase your income by 1000, but only by 500 (from 500 to 1000).

**Comment by LeHerosInconnu** [comment]
Hello @dimag0g,

> Regarding (#4827):
> * "Le Château ... augmente les revenus de 1000 pièces" is wrong. The castle doesn't increase your income by 1000, but only by 500 (from 500 to 1000).

This proposal was made to remain consistent with the text of the Statue.

In fheroes2:
(The word "d'or" is also missing here.) :)
![Statue de 250 pièces 01](https://user-images.githubusercontent.com/43583994/147609655-2fbd49f5-9a05-406d-a605-65625c67b16d.png)

Also your comment would be valid if all castles were first towns that were later improved into castles.
But this is not the case and often castles are directly castles without being towns first.
(For information, a town gives 250 gold, not 500 gold.) :)

Also, the use of "à" may imply that it is the entirety of the Kingdom's income that is being referred to, when in fact it is not and refers only to this castle (whereas with the use of "de" this imprecision disappears).

Therefore, it should be clarified in the sentence:
"...augmente les revenus du château...".

As it is the case for the Statue:
"...augmente les revenus de votre village de 250 pièces...".

In fheroes2:

![French translation 013](https://user-images.githubusercontent.com/43583994/147248926-96d74723-c3dc-4cb0-b990-c3be17e8031e.png)

Another solution would be to replace the word "augmente" by "génère" in the texts of Town, Castle and Statue:

"...génère des revenus de..."

**Comment by dimag0g** [comment]
I'll stick to "...génère des revenus de..." then, this is IMO the most inambiguous sentence which can be applied to all 3 cases (Statue, Donjon, Castle)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , is this issue still relevant?

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

Everything seems to be correct apart from "Connaissance" and "Plusieurs".

In fheroes2:

![Translation french 001](https://user-images.githubusercontent.com/43583994/158174531-2f221a6e-667b-4176-8d2d-5886dbf7bae7.png)

![Translation french 002](https://user-images.githubusercontent.com/43583994/158174545-c611af05-9897-4a48-bfec-286b46d98c4c.png)

Version 0.9.13 5123

**Comment by zenseii** [comment]
Seeing that they're small corrections they can be included in the PR that I have going.

**Comment by zenseii** [comment]
Actually, now that the current French PR got larger than first intended I would add this issue to the next French PR that is planned to be posted, to avoid further growth of this current PR.

Also I would like to ask what the solution to these would be. Abbreviations like "Plus." and "Connaiss." ?

**Comment by LeHerosInconnu** [comment]
Hello @zenseii,

> Actually, now that the current French PR got larger than I had intended, I would add these changes to the next French PR that is planned to be posted, to avoid further growth of this current PR.
> 
> Also I would like to ask what the solution to these would be. Abbreviations like "Plus." and "Connaiss." ?

The abbreviations are not visually appealing and not easily understood by someone who does not know the game.

I had proposed that:

The word "Plusieurs" is too long.
The word "Plusieurs" could be replaced by "Quelques" a slightly shorter word.

The word "Connaissance" is too long.
The word "Connaissance" could be replaced by "Savoir".

"Connaissance" could also be kept by adjusting the horizontal position of the values. :)

**Comment by zenseii** [comment]
@LeHerosInconnu , then I believe the best solution is to adjust the horizontal position of the primary skill values since I don't see how it could be a problem if they are placed further to the right. This is much better than sometimes using Savoir and other times Connaissance, which would indeed be confusing to new players trying to learn the terminology used in the game.

As for Quelques I see no problems with that other than that it might still pixel by pixel be the same length as Plusieurs due to wider letters.

**Comment by LeHerosInconnu** [comment]
Hello @zenseii and @ihhub,

> @LeHerosInconnu , then I believe the best solution is to adjust the horizontal position of the primary skill values since I don't see how it could be a problem if they are placed further to the right. This is much better than sometimes using Savoir and other times Connaissance, which would indeed be confusing to new players trying to learn the terminology used in the game.

@ihhub, so do you think it is appropriate to adjust the horizontal position of all values in this window?

In fheroes2:

![Translation french 001](https://user-images.githubusercontent.com/43583994/158174531-2f221a6e-667b-4176-8d2d-5886dbf7bae7.png)

> As for Quelques I see no problems with that other than that it might still pixel by pixel be the same length as Plusieurs due to wider letters. Still this will only be discovered by trying it.

Let's try it. :)

**Comment by zenseii** [comment]
Here's Quelques:
![image](https://user-images.githubusercontent.com/12501091/158861614-8a9da3ab-c276-44a8-9708-d569cc139390.png)
It's better but not acceptable.

**Comment by LeHerosInconnu** [comment]
@zenseii.

> @LeHerosInconnu Here's Quelques: ![image](https://user-images.githubusercontent.com/12501091/158861614-8a9da3ab-c276-44a8-9708-d569cc139390.png) It's better but not yet perfect/acceptable.
> 
> I suspect you wouldn't be much in favor of the (common) abbreviation `Qlqs.` sweat_smile I would agree if you if you said it's a bit ugly to look at in the game, especially since abbreviations aren't commonly used.

Effectively, it is better, but still too long.
I still think that replacing the terms by the corresponding numbers would only bring advantages: https://github.com/ihhub/fheroes2/issues/1530. :)
Otherwise, I have no other ideas for the moment.

**Comment by zenseii** [comment]
Just noticed the `a` in `affiche` is missing for some weird reason:
![image](https://user-images.githubusercontent.com/12501091/163673897-08b75a89-f492-4a6a-8dfb-a55a7a4b572b.png)

Looking at the .mo in hex it seems some weird encoding snuck in:
![image](https://user-images.githubusercontent.com/12501091/163673914-5d479863-bab0-4bfa-8d2b-abbbdf331cd0.png)


I also recommend in the next PR for French to adopt the "Quelques" as suggested above.

**Comment by zenseii** [comment]
I'll have a French PR up and running shortly.

@LeHerosInconnu I've seen that the original French localization uses the 1 à 4 for Few etc. and I see that you would have prefered this way as well. Other than making a more true to the English translation, is there a reason we should insist on not applying such a system for creature quantities?

**Comment by LeHerosInconnu** [comment]
Hello @zenseii,

> I'll have a French PR up and running shortly.
> 
> @LeHerosInconnu I've seen that the original French localization uses the 1 à 4 for Few etc. and I see that you would have prefered this way as well. Other than making a more true to the English translation, is there a reason we should insist on not applying such a system for creature quantities in the French translation?

There is none to my eyes. :)
For me it would be more convenient and clearer to display the numbers directly wherever the expressions are used, even for the English language.
And besides there would be no problem with translations with long words in some languages, etc.

But some guy wants to keep the expressions...
...but he can still change his mind... :)

"So replace:

Few by 1-4
Several by 5-9
Pack by 10-19
Lots by 20-49
Horde by 50-99
Throng by 100-249
Swarm by 250-499
Zounds by 500-999
Legion by 1000+"

**Comment by zenseii** [comment]
For reference here is the original French localization:
![image](https://user-images.githubusercontent.com/12501091/164731985-87f5b1e4-a58a-4d23-bb1e-b94e87917076.png)![image](https://user-images.githubusercontent.com/12501091/164732081-927989b6-4684-440b-8697-c1147e533b45.png)

That picture to the right shows why using this system wouldn't be the best.
Also the system of names is used too:

![image](https://user-images.githubusercontent.com/12501091/164732299-52958952-080e-4f7c-96ff-2e8a90c81e6b.png)

I'm not really in favor of applying this system to all languages but I think it's important to repect what system players will have gotten used to in their specific translation.

**Comment by LeHerosInconnu** [comment]
@zenseii.

> For reference here is the original French localization: ![image](https://user-images.githubusercontent.com/12501091/164731985-87f5b1e4-a58a-4d23-bb1e-b94e87917076.png)![image](https://user-images.githubusercontent.com/12501091/164732081-927989b6-4684-440b-8697-c1147e533b45.png)
> 
> That picture to the right shows why using this system wouldn't be the best (that bottom line makes me feel dyscalculic). Also the system of adjective descriptions is used too:
> 
> ![image](https://user-images.githubusercontent.com/12501091/164732299-52958952-080e-4f7c-96ff-2e8a90c81e6b.png)

I found that the use of "à" with a space on each side was not very clear in the original French version either (as you illustrated with Ambrose's army).
That's why I changed "500 à 1000" to "500-999" with a hexadecimal editor.

And even for the quick info of the wandering creatures, it is quite clear and precise:
![Creatures equivalent numbers 04](https://user-images.githubusercontent.com/43583994/92218263-22d4cd80-ee99-11ea-9059-ea787a00ed7d.png)

> I'm not really in favor of enforcing the 1-4 etc. system to all languages, ...

Booouuuuuu... :rofl:

**Comment by zenseii** [comment]
> I found that the use of "à" with a space on each side was not very clear in the original French version either (as you illustrated with Ambrose's army). That's why I changed "500 à 1000" to "500-999" with a hexadecimal editor.

Yes, this will look much better and a French person will still read it as 500 à 1000. The small font dash `-` also looks fine compared to the horrible normal font dash. I'm still not convinced this is the best solution to adapt for wandering creatures, though, simply because it changes much of the atmosphere of the game into something more numerical.

> Booouuuuuu... 🤣

Well well let's take one victory at a time 😋 Maybe one day we will see this system applied in other langauges.

**Comment by zenseii** [comment]
Here are some other issues:
This one is probably valid for other langauges too:
![image](https://user-images.githubusercontent.com/12501091/166095372-8122ce84-0ec3-4c26-ad3b-6d080664530a.png)

The "Pas de place dans la garnison" which is in reality two strings "Pas de place" and "dans la garnison" aren't properly placed above the button for accessing the hero screen and go outside the border on the right side.

Another issue is that several item descriptions have the wrong article like "L'Perle noir augemente la puissance...". My proposal for addressing this is to include the article in the name string of the artifact. This would mean that headers of that artifact would have the article in them but I don't think this is a big problem.

**Comment by zenseii** [comment]
Here's another issue I spotted in a vid from current latest public release:
![image](https://user-images.githubusercontent.com/12501091/166967590-288379a5-9d88-40c2-9776-7024847c3adf.png)

**Comment by LeHerosInconnu** [comment]
Hello @zenseii,

> Other issues were reported by Damn3d: `Demi-tour`
> 
> ![image](https://user-images.githubusercontent.com/12501091/171440112-5ce49d85-960d-483c-8b10-bc2e69975ea0.png)
> 
> `Alliance des ogres`
> 
> ![image](https://user-images.githubusercontent.com/12501091/171440300-3e6a5eda-9020-4610-99ab-024041aed343.png)

Some remarks.

I think "Fléau des nains" would be better than "Nain fléau".
Or "Fléau des Nains", if the first letter should be capitalized as for the word "Dragons".

And I suggest "Renforts différés" instead of "Forces reportées".

**Comment by zenseii** [comment]
> Hello @zenseii,
> 
> > Other issues were reported by Damn3d: `Demi-tour`
> > ![image](https://user-images.githubusercontent.com/12501091/171440112-5ce49d85-960d-483c-8b10-bc2e69975ea0.png)
> > `Alliance des ogres`
> > ![image](https://user-images.githubusercontent.com/12501091/171440300-3e6a5eda-9020-4610-99ab-024041aed343.png)
> 
> Some remarks.
> 
> I think "Fléau des nains" would be better than "Nain fléau". Or "Fléau des Nains", if the first letter should be capitalized as for the word "Dragons".
> 
> And I suggest "Renforts différés" instead of "Forces reportées".

Actually, I'm pretty sure Fléau des nains was used, but I think some update just has it "fuzzied" or marked as needing to be checked.

Thanks for your other suggestions!

**Comment by zenseii** [comment]
Hi @LeHerosInconnu !

> And I suggest "Renforts différés" instead of "Forces reportées".

I want to make sure that your suggestion here refers to how these are "Carry-over forces", in other words forces you accumulated in one map that will carry over to a subsequent map later on. "Renforts différés" seems to translate to "Postponed reinforcements" which sounds like they will arrive later than planned?

You'll have to excuse me if the answer is obvious.

**Comment by LeHerosInconnu** [comment]
Hello @zenseii,

> Hi @LeHerosInconnu !
> 
> > And I suggest "Renforts différés" instead of "Forces reportées".
> 
> I want to make sure that your suggestion here refers to how these are "Carry-over forces", in other words forces you accumulated in one map that will carry over to a subsequent map later on. "Renforts différés" seems to translate to "Postponed reinforcements" which sounds like they will arrive later than planned?
> 
> You'll have to excuse me if the answer is obvious.
> 
> When this is cleared up I believe we can close this issue.

The difference is subtle and both could be used, it's all about the reader's interpretation. :)
For me, "reportées" means more that something was planned in advance but there was a problem so it has to be rescheduled, like a rescheduled event.
"différés" would be more consistent with something that does not happen right away but is delayed in time, such as a "live" as opposed to a "replayed" television broadcast.

Also, since it is possible to get information about bonuses with the right mouse click, we could also use these expressions:

"Troupes rassemblées"

Or simply:

"Renforts"

With something like this for the bonus information message:

"Les renforts seront disponibles dans le scénario final."

"Les renforts seront disponibles pour le combat final."

"Les troupes seront disponibles dans le scénario final."

"Les troupes seront disponibles pour le combat final."

**Comment by zenseii** [comment]
Thanks for the thorough explanation, @LeHerosInconnu! 

I'm not qualified to decide which is better. I'm also not sure what the current info window for this reward says, but it should already be present.

If you don't mind I'll share your suggestions on Discord to the other French native speakers.

**Comment by zenseii** [comment]
Here is the current right-click description in English and French. Don't pay too much attention to the fact that the English text has some mistakes. 

I believe a more correct text would be "The army will be carried over to a subsequent scenario", because you get the army in the final battle, which is not the scenario immediately following the one you get that bonus in, if I recall correctly. Sadly my campaign saves no longer work and I don't have the time to speed through the campaign, nor the will to look it up.

Nevertheless, this bonus could be applied for other campaigns in the future so having the text fit more situations would be better, but not very important.

![image](https://user-images.githubusercontent.com/12501091/189117585-4abf2730-5ebd-4afc-8122-c924b707fa66.png)

**Comment by LeHerosInconnu** [comment]
Hello @zenseii,

> Hi @LeHerosInconnu. Here is the current right-click description in English and French. Don't pay too much attention to the fact that the English text has some mistakes.
> 
> I believe a more correct text would be "The army will be carried over to a subsequent scenario", because the carried over army arrives to you in the final battle (I think?), which is not the scenario immediately following the one you get that bonus in, if I recall correctly.
> 
> Sadly my campaign saves no longer work and I don't have the time to speed through the campaign, nor the will to look it up elsewhere.
> 
> Nevertheless, this bonus could be applied for other campaigns in the future so having the text fit more situations would be better, but not very important.
> 
> ![image](https://user-images.githubusercontent.com/12501091/189117585-4abf2730-5ebd-4afc-8122-c924b707fa66.png)

Beware, in Archibald's campaign, the gathered troops are available in the next scenario which is the final scenario, while in Roland's campaign, the gathered troops are not available in the next scenario (which is not the final scenario) but in the very last scenario.

The following sentence might be appropriate for both campaigns:

"L'armée sera disponible dans le scénario final."

**Comment by zenseii** [comment]
Hi @LeHerosInconnu,
> "L'armée sera disponible dans le scénario final."
Thanks!
I've not gotten much response on Discord yet, but in my opinion simply "Renforts" and "Les renforts seront disponibles dans le scénario final." sound the best and make the most sense.

**Comment by zenseii** [comment]
We're deciding between this:
![image](https://user-images.githubusercontent.com/12501091/189483691-b908184b-5a22-481c-96e9-2ca8daa7f6aa.png)

and this:
![image](https://user-images.githubusercontent.com/12501091/189483696-0c312253-bd1d-4ee5-98b7-15917d0f3e01.png)


For reference the troops will be found within Archibald's troops in the beginning of the final evil scenario:
![image](https://user-images.githubusercontent.com/12501091/189483781-053c6d68-3ee2-45d3-b6dd-aec496fa58e7.png)


I'm not sure my french is good enough to understand the exact meaning of "conservées" in the above example, so for me "disponibles" sounds better.

Seeing that we have a visual representation of the troops we could also make a direct reference to them like:

"The following troops will be among your ranks in the final scenario:"

Though that doesn't explain where you got them from, in case you forget how you got that bonus.

We can consider this discussion for how to improve the English text as well later on.

Do you have any thoughts @LeHerosInconnu?

**Comment by LeHerosInconnu** [comment]
Hello @zenseii,

> I'm not sure my french is good enough to understand the exact meaning of "conservées" in the above example, so for me "disponibles" sounds better.
> 
> Seeing that we have a visual representation of the troops we could also make a direct reference to them like:
> 
> "The following troops will be among your ranks in the final scenario:"
> 
> ~ "Les troupes suivantes seront dans vos rangs dans le scénario final :"
> 
> Though that doesn't explain where you got them from, in case you forget how you got that bonus.
> 
> Maybe just simply: "Les troupes suivantes rejoindront vos rangs dans le scénario final :"
> 
> We can consider this discussion for how to improve the English text as well later on.
> 
> Do you have any thoughts @LeHerosInconnu?

For me, "Renforts" and "Les renforts seront disponibles dans le scénario final." fit perfectly. :)

And for the window, what happens when the army includes five different types of creatures?
Is the window adapted to that already?

**Comment by zenseii** [comment]
> This sentence can also be used:

> "Les renforts rejoindront vos rangs dans le scénario final."

Good. I'll change it to your second proposal. I'm so finished with going back and forth on this single sentence so many times now 😂

> And for the window, what happens when the army includes five different types of creatures?
Is the window adapted to that already?

The window adapts automatically, yet I'm not sure this is relevant to this discussion?

Btw you suggestion works even if the "reinforcements" should only end up being a single goblin, in case that is the result after the final battle, whereas "Les troupes" would be logically wrong in that case since it's just one single troop 👍
