### ISSUE TITLE
Marketplace and Trading Post windows, Select Recipients window, wrong elements position

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4804]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, there is a wrong elements position in the Select Recipients window.

The distance between the green and red squares representing the players to be selected is not the same as between the other squares, 21 pixels instead of 22 pixels.
The block of colored squares representing the players to be selected is not centered horizontally in relation to the edges of the window frame.
The two blocks of resource icons for "Your Funds" and "Planned Gift" are not centered horizontally in relation to the edges of the window frame.

In fheroes2:
![Select recipients window 01](https://user-images.githubusercontent.com/43583994/146682193-c1b1590a-a386-467b-96f5-f129a6a02fe8.png)

### Save file

Not needed.

**Comment by srmoll** [comment]
Hi, could I be assigned this issue?

**Comment by ihhub** [comment]
Hi @srmoll , sure!
