### ISSUE TITLE
Marketplace and Trading Post windows, numbers indicating the quantities of resources to be traded are not centered horizontally with respect to their respective resource icon

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4805]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the numbers indicating the quantities of resources to be traded are not centered horizontally with respect to their respective resource icon.

In fheroes2:

In the exemple with "-0 (97)" and "+0 (58)".
![Marketplace quantity to trade 01](https://user-images.githubusercontent.com/43583994/146682619-90f6a6f8-5221-4b96-b0a2-1bb01f4ec827.png)

### Save file

Not needed.

**Comment by felix642** [comment]
Hi @LeHerosInconnu,
I was doing some tests related to this issue on my game and I'm not 100% sure to know what is considered correct..
Can you tell me if you feel like those images are correct ?

![image](https://user-images.githubusercontent.com/60141446/147398001-fdc62c19-ff69-49a6-85ac-5258012f6fa6.png)
![image](https://user-images.githubusercontent.com/60141446/147398004-9011c7c4-0110-4cb8-bc3d-5f7d13153068.png)
![image](https://user-images.githubusercontent.com/60141446/147398006-52d7577c-c16c-432a-a634-4bde0f14584c.png)
![image](https://user-images.githubusercontent.com/60141446/147398008-c2c1f993-0a9b-4c2b-86b3-606588555bdc.png)

**Comment by LeHerosInconnu** [comment]
@felix642.

> Hi @LeHerosInconnu, I was doing some tests related to this issue on my game and I'm not 100% sure to know what is considered correct.. Can you tell me if you feel like those images are correct ?

Not sure about gems, sulfur and ore.
The images are a bit blurry when I download them.
I may see better on screenshots with 640 x 480 game resolution, or I'll have to check once your PR is compiled.
