### ISSUE TITLE
Make use of ë in Russian translation

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#4813]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

During a conversation with several of our Russian fans and contributors, I learnt that the use of ë is completely omitted because it was replaced with "e" in the original translation. This is apparently not optimal and was  most likely done as a cheap compromise. So using ë is better from a quality perspective. 

We would therefore need for our translators to start using ë when it is correct because we do not have the same limitations that they had when they did the original localization back in the 90s.

I assume many words would need this correction.

An example of current fheroes2: "Шатер"
And this should be written: "Шатëр"

### Describe the possible solution

Make the use of "ë" become the standard, instead of using "e" in its place

### Additional info

Was this letter ë added with the new native generation of Russian characters?

**Comment by a1exsh** [comment]
I think this is partially addressed by https://github.com/ihhub/fheroes2/pull/4810 , however there are a lot of other changes in there, mostly around proper capitalization.

**Comment by ihhub** [comment]
Hi @a1exsh and @zenseii , I added generation of this letter in #4813 as I missed it during initial implementation.

**Comment by ihhub** [comment]
Hi @Branikolog , is this issue still valid?

**Comment by Branikolog** [comment]
Hello, @ihhub!
In the recent PR we replaced to "ё" everything, we've found. We could miss some places, but we'd fix them on our way of polishing entire translation.

**Comment by zenseii** [comment]
If the correct letter has now generally replaced the wrong one then I would say this issue can be considered complete. If there are any cases remaining they can be considered typos and will be fixed when noticed. 

The idea of this issue is to have the translation use this letter as a standard, and if this is the impression a player will get when playing then I would say we are good to go closing this.

PS This is not a PR about "Fix all typos" because such a scope could be forever.

@Branikolog could you link the PR which started making general use of this letter, for the sake of clarity?

**Comment by Branikolog** [comment]
Hi, @zenseii !
I believe this one. ;)
