### ISSUE TITLE
Flag animation during combat

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#483]
Animation of flag flutter should be faster and more smooth.

**Comment by ihhub** [comment]
Hi @Branikolog , what do you mean by smooth? We use the original frames. How fast should it be?

**Comment by idshibanov** [comment]
Looks like in OG flag animation scales with battle speed setting. I'll adjust the delay; frames are fine.

**Comment by Branikolog** [comment]
> Looks like in OG flag animation scales with battle speed setting. I'll adjust the delay; frames are fine.

You're certainly right. Different flag animation speed confused me.
