### ISSUE TITLE
"Cost per troop" text is baked into graphic and therefore is untranslatable as-is

### ISSUE THREAD

**Issue by yvesgurcan** [ihhub/fheroes2#4830]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

The "Cost per troop:" text in the creature recruit dialog cannot be translated right now since that text is actually baked into the graphic.

![147248969-bc6e585d-6d71-44c0-a1f7-f53702fd53f4.png](https://user-images.githubusercontent.com/28522282/147265756-7b082b89-f76d-439e-a6a7-3fc07ff519ca.png)

### Describe the possible solution

The graphical editing needed to fix this would consist of a copy-paste of the pattern used next to the baked text to mask it and add actual text above the mask.

Original assets should not be edited directly since that would create copyright issues. The added part should be made as a separate file part of fheroes2 specific resources and applied at runtime. You'll find these files in the resources folder.

### Additional info

Examples of changes like these are to the various Captain's Quarters and the Peasant Farm in Knight's castle.

**Comment by dimag0g** [comment]
If this is deemed important enough, it could be fixed programmatically:

- copy a 1-pixel vertical stripe of the field in a place without text
- fill the entire field with copies of that one-pixel stripe
- render the actual text on top, and make that text translatable

**Comment by ihhub** [comment]
Hi @dimag0g , not exactly like this by you're right.
