### ISSUE TITLE
Adventure map, path changes each time hero moves one cell

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4838]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Path is constantly changes, when hero moves. Right during movement.
![image](https://user-images.githubusercontent.com/55348946/147371596-76a66473-dcb6-4fe1-a78d-1954a1f8c5ce.png)
![image](https://user-images.githubusercontent.com/55348946/147371637-7ce21e58-e3e1-410b-a307-1ff4b2fde14c.png)
![image](https://user-images.githubusercontent.com/55348946/147371666-2426f060-1e64-40a9-8f55-3f80f6ad8c1e.png)

### Save file

[Path.zip](https://github.com/ihhub/fheroes2/files/7775105/Path.zip)

**Comment by oleg-derevenetz** [comment]
This is a regression after #4454 when hero's path ends on a monster. It's merely cosmetic but looks odd. I'll think about how best to fix it tomorrow.
