### ISSUE TITLE
Crash during AI turn

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4840]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Obviously some AI problem.
To reproduce simply end turn at provided savefile.

### Save file

[AUTOSAVE.zip](https://github.com/ihhub/fheroes2/files/7775344/AUTOSAVE.zip)

**Comment by ihhub** [comment]
Fixed in #4841
