### ISSUE TITLE
Adventure map, Summon Boat spell, replace the word "water" by the word "ocean" in the message window that appears when the hero casting the spell is not positioned near the ocean

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4849]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

In fheroes 2, as a square of the sea is designated by the term "Ocean" in the right click information window, I think it would be more appropriate to use this word in the texts referring to it.

In fheroes 2:

![Nearby ocean 01](https://user-images.githubusercontent.com/43583994/147409179-0d57fc5c-2667-40fb-9b74-20455b52eca5.png)

![Nearby ocean 02](https://user-images.githubusercontent.com/43583994/147409186-7c3369fc-1830-46fe-8c50-9a2ad9a48db6.png)

### Describe the possible solution

I suggest to replace the word "water" by the word "ocean" in the message window that appears when the hero casting the spell is not positioned near the ocean.

This text:

"...nearby ocean."

Instead of:

"...nearby water."

**Comment by zenseii** [comment]
Since this could be even for lakes and not just oceans, I would say a better wording is "near a body of water".

**Comment by LeHerosInconnu** [comment]
Hello @zenseii,

> Since this could be even for lakes and not just oceans, I would say a better wording is "near a body of water".

The purpose here is to refer to the type of terrain "Ocean" and not to the area covered by the water. :)
The word "Ocean" is displayed in the information window of the terrain square with the right click.
