### ISSUE TITLE
Game not found on Nintendo Switch

### ISSUE THREAD

**Issue by emersonjr** [ihhub/fheroes2#4869]
### Your question

I've followed the instruction guide for Nintendo Switch setup https://github.com/ihhub/fheroes2/blob/master/docs/README_switch.md
but after finishing the game is not detected on Switch's menu

### Additional info

My Homm2 original copy is from GOG, which doesn't have ANIM folder, so I did run the `extract_homm2_resources.bat` for getting this folder and all the other ones. I think that's the only thing i did that isn't in the guide

FW 13.1.0
HEKATE 5.6.5

**Comment by emersonjr** [comment]
Ok, that might have been a very big noob mistake from my side but i can access the game throught hbmenu, my question now is, is there any way to access the game via default menu? In the current situation, if i press home button, the game closes instead of getting into a suspend status

**Comment by oleg-derevenetz** [comment]
Hi @dimag0g since you are an expert on the Switch, could you take a look, please? :)

**Comment by dimag0g** [comment]
@emersonjr I only ever access homebrew via hbmenu, but I know you can access homebrew apps from the games list by generating an NSP forwarder. Never used that myself though.

If you launch something via hbmenu and it closes when you press the home button, it usually means the hbmenu was started in applet mode. There's a huge red banner in hbmenu when it starts this way:
