### ISSUE TITLE
Hero restores his movement points after retreat

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#488]
You can buy your hero after retreat with full movement points in tavern.
![Tavern](https://user-images.githubusercontent.com/55348946/81476541-17d79c80-921b-11ea-8d96-104d8fbfaa36.png)
![Tavern1](https://user-images.githubusercontent.com/55348946/81476542-19a16000-921b-11ea-8a6a-5e4cffad164b.jpg)
![Tavern2](https://user-images.githubusercontent.com/55348946/81476544-1a39f680-921b-11ea-97bf-c98e03a1c3b8.jpg)
![Tavern3](https://user-images.githubusercontent.com/55348946/81476546-1ad28d00-921b-11ea-9f0b-00a432ceef94.jpg)

**Comment by ihhub** [comment]
Closing this issue as this be can controlled via `heroes: remember move points for retreat/surrender result` option.
