### ISSUE TITLE
Use French quotation marks

### ISSUE THREAD

**Issue by yvesgurcan** [ihhub/fheroes2#4882]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

The French version of the game uses quotation marks `"` as used in English.

### Describe the possible solution

To respect French typography, the game should use quotation marks `« »` wherever the English quotation marks are used in the text.

### Additional info

The quotation mark to open a quotation should be followed by an unbreakable space.

The quotation mark to close a quotation should be preceded by an unbreakable space.

Example: `"Hello!"` should be translated as `« Bonjour ! »`.

We might need special characters to indicate that the space between a quotation mark and the text it quotes should not be breakable, which I don't know if the project supports at the moment. Without unbreakable spaces, we might end up with awkward displays of text such as this:

```
Lorem ipsum bla bla bla : « 
Bonjour ! » Lorem ipsum encore
bla bla bla.
```

The correct way to display this text should be:
```
Lorem ipsum bla bla bla :
« Bonjour ! » Lorem ipsum encore
bla bla bla.
```

**Comment by zenseii** [comment]
To make the unbreakable space actually unbreakable we can simply offset those signs in `ui_font.cpp`.

This would mean that we have to go through the translation and remove every space added before those symbols. This is just a simple search and replace for e.g. " !".

**Comment by zenseii** [comment]
This was not fixed in the above PR and therefore is reopened.
