### ISSUE TITLE
Player refuses to disembark boat and decides to walk on water

### ISSUE THREAD

**Issue by felix642** [ihhub/fheroes2#4887]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

After disembarking the boat, the player decided to stay on the water and walk on it.

![Screenshot from 2022-01-02 21-05-57](https://user-images.githubusercontent.com/60141446/147896121-408b3870-8b2f-4f9e-b853-1bc6d043842b.png)

### Save file

[Pirate_Utopia_0129.zip](https://github.com/ihhub/fheroes2/files/7800169/Pirate_Utopia_0129.zip)

**Comment by felix642** [comment]
I have to admit this is my favorite bug :grin:

**Comment by oleg-derevenetz** [comment]
Yeah, there is some odd place on the map:

<img width="638" alt="Water beach" src="https://user-images.githubusercontent.com/32623900/147900742-4bf19e40-b2cf-443e-bfaf-60d259c9d9b3.png">

the MP2 object here is Beach, so hero is able to disembark here, but the ground here is Ocean, so after disembarking the hero is still on water.
