### ISSUE TITLE
Question / bug on monster growth

### ISSUE THREAD

**Issue by vincent-grosbois** [ihhub/fheroes2#4893]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

cf https://github.com/ihhub/fheroes2/blob/84b4d57dd0aacec2f955cb962bf7506f47979e50/src/fheroes2/maps/maps_tiles_quantity.cpp#L1104

- Monster growth is set at 14% weekly (8/7)
- Due to integer division, the stack will never grow week after week if the initial stack size is < 7

My questions:
- Is this value of 14% weekly accurate ? Do you know what is the behavior in OG ? Is it random ? I know in HOMM3 it also depend on the difficulty level I think
- What should be the correct behavior when stack size is small ? We could instead increase the stack size by one each week randomly (14% of growing by 1 unit if only 1 unit is there, to 85% of chance of growing by 1 unit if 6 units are there)

### Save file

none

**Comment by oleg-derevenetz** [comment]
I believe @LeHerosInconnu is able to answer this question. He knows everything :)

**Comment by LeHerosInconnu** [comment]
Hello @vincent-grosbois and @oleg-derevenetz,

> I believe @LeHerosInconnu is able to answer this question. He knows everything :)

I won't say that I know everything, but there is a link about creature growth in Heroes 2 in this thread: https://github.com/ihhub/fheroes2/discussions/4676. :)

**Comment by vincent-grosbois** [comment]
Unfortunately my dedication to the fheroes2 project doesn't go as far as learning Russian...
Does anyone know what they say ? apparently it's exactly the formula I mentionned in the first message indeed

**Comment by vincent-grosbois** [comment]
In that page, they also mention how the garrison monster should grow when there is a neutral town.
Do we handle this at all in the game ?

**Comment by felix642** [comment]
> Unfortunately my dedication to the fheroes2 project doesn't go as far as learning Russian... Does anyone know what they say ? apparently it's exactly the formula I mentionned in the first message indeed

Hi @vincent-grosbois, from what I can see on the website, we seem to be missing a small part of code to make it work like OG

"N new = N + [N / 7] + Bonus , where
Bonus = 1 with probability P (Bonus = 1) = {N / 7} , and Bonus = 0 otherwise, "

We do not handle the bonus. Every week we should have 1/7 chances to add 1 monster to the pack.

Adding this logic would probably solve the issue.

**Comment by vincent-grosbois** [comment]
thanks, I was able to translate it with google trad
> Every week we should have 1/7 chances to add 1 monster to the pack.
I don't think that's what they write, it's dependant on the fractionary part of N/7. So for n=1 that's 1/7 chance to add 1, but for n=6 that's 6/7 to add 1, which is by chance what I had proposed in my OP :)

**Comment by Branikolog** [comment]
@vincent-grosbois
True.
According to this guide we have a quite low chance of increasing quantity of 1 neutral monster on adventure map.
I've done some tests in the OG. Single Dragon, placed on adventure map received growth only up to the 4-th month.

**Comment by idshibanov** [comment]
> In that page, they also mention how the garrison monster should grow when there is a neutral town. Do we handle this at all in the game ?

Yes: #1872. Although I noticed small differences, like 40/101 chance instead of 40%, etc. I'll double check the logic.
