### ISSUE TITLE
Neutral town garrison growth

### ISSUE THREAD

**Issue by vincent-grosbois** [ihhub/fheroes2#4898]
### Your question

In that page :
https://handbookhmm.ru/2-timing-and-garrison
there seems to be a huge paragraph about how should monster in a neutral town garrison grow over time.

Do we handle neutral town garrison growth at all in fheroes2?

**Comment by oleg-derevenetz** [comment]
Hi @vincent-grosbois this should be handled in the `Castle::ActionNewWeek()`.

**Comment by ihhub** [comment]
Fixed in #5927.
