### ISSUE TITLE
Adventure map, Month of the Creature window, adjust the text

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4901]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

I suggest to adjust the text of the Month of the Creature window.

### Describe the possible solution

The word "the" is missing in the first sentence:

"Astrologers proclaim the Month of the Vampire."

Instead of:

"Astrologers proclaim Month of the Vampire."

In fheroes2:
**Note:** This is a screenshot of a previous version of fheroes2.
The rest of the text is correct and there is a line separating the last two sentences in the most recent version of fheroes2.

![Separation empty line missing 02](https://user-images.githubusercontent.com/43583994/136701442-afa78c24-9d3b-436d-a1ae-448200bc0f9b.png)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , right now it is exactly the same as in the original game.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , right now it is exactly the same as in the original game.

I'll look at that too towards the end of next week. :)

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hello @ihhub,
> 
> > Hi @LeHerosInconnu , right now it is exactly the same as in the original game.
> 
> I'll look at that too towards the end of next week. :)

Yes, it is that way in the original game.
My suggestion was to add the word "the" because I find it missing in the sentence, but I could be wrong.
We would need the opinion of native English speakers on this. :)

**Comment by ihhub** [comment]
I am marking this issue for Beyond 1.0 as it's an improvement over the original game.

**Comment by ihhub** [comment]
Hi @zenseii , what do you think about this?

**Comment by ihhub** [comment]
I am closing this issue as we are literally battling for a single word in English here :)
