### ISSUE TITLE
Adventure map, hero is able to create a path over another hero

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4916]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

A path is being created over another hero standing close to neutral monster.
![image](https://user-images.githubusercontent.com/55348946/148948983-d82c93b4-b919-462b-8c5a-b70c8ce39c5a.png)

### Save file

[!!!.zip](https://github.com/ihhub/fheroes2/files/7846732/default.zip)

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , I think it's related to our new changes in pathfinding. Would you please check it?

**Comment by oleg-derevenetz** [comment]
Hi @ihhub 

> I think it's related to our new changes in pathfinding. Would you please check it?

Nope, it's an older bug, it is observed even on 0.9.11 release version. Nevertheless, it also needs to be fixed :)

**Comment by ihhub** [comment]
I always ask myself do we even have a single portion of the code which doesn't have bugs... :)

**Comment by oleg-derevenetz** [comment]
> I always ask myself do we even have a single portion of the code which doesn't have bugs... :)

The more complex the logic, the more likely it is to make a mistake.
