### ISSUE TITLE
Adventure map, a hero is rendered over neutral troops (Giants)

### ISSUE THREAD

**Issue by a1exsh** [ihhub/fheroes2#4926]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

![image](https://user-images.githubusercontent.com/489601/149563795-df7847ed-e921-4f5c-81b2-f84fd34f9722.png)

Close-up:
![image](https://user-images.githubusercontent.com/489601/149563847-46302cf8-2214-45de-85bb-2128ac606e6f.png)

### Save file

[Teleporters_0042.zip](https://github.com/ihhub/fheroes2/files/7872360/Teleporters_0042.zip)

**Comment by ihhub** [comment]
This issue is fixed in #5692 .
