### ISSUE TITLE
Game crashing when a map folder path contains Russian symbols

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4936]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Based on a feedback from our folower.
The crash occurred when user set game language as english, and checked map info, which contains full system path, with russian characters included.

### Save file

None.

**Comment by ihhub** [comment]
I assume the crash happens due to assertion in UI text related code when an invalid character appears.

**Comment by afrikansviridovic** [comment]
Path to the app folder been the following "D:\Games\герои2\" and all game assets were in respective subfolders in it.
