### ISSUE TITLE
Adventure map, display priority problem with Hero and Jail

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4939]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, there is a display priority problem with Hero and Jail.

In fheroes2:

![Display priority hero jail 01](https://user-images.githubusercontent.com/43583994/150607147-ae3b2d88-9e7f-4c66-9b7e-4b76f22efed2.png)

Here are the test scenario files:
[Heroes portrait jail 01.zip](https://github.com/ihhub/fheroes2/files/7916659/Heroes.portrait.jail.01.zip)

### Save file

Not needed.

**Comment by oleg-derevenetz** [comment]
Funny effect, looks like a hero on a horse stands on the roof of the jail.
