### ISSUE TITLE
AI missed its turn and this was not displayed in a battle journal

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#494]
At the screenshot the last pack of wolves miss their turn. We can watch such behavior in a case there is another unit closes path to the upper part of a screen.
And this action is not written in a journal. 
![Missed turn](https://user-images.githubusercontent.com/55348946/81495352-7010ac00-92b8-11ea-9a8d-ced772aa9096.jpg)
![Missed turn1](https://user-images.githubusercontent.com/55348946/81495595-0db8ab00-92ba-11ea-8a87-61a05683ac13.jpg)

**Comment by idshibanov** [comment]
This will be addressed in Battle AI overhaul to make it closer to the original. Current target priority and pathfinding is unsatisfying.

**Comment by Branikolog** [comment]
OK. 
I'll change the priority of this problem to the second part of this issue. About journal.
