### ISSUE TITLE
Adventure map, mine is not displayed: only the flag is visible

### ISSUE THREAD

**Issue by a1exsh** [ihhub/fheroes2#4945]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

Playing "Voyage Home" scenario 2.

There is a blue flag standing alone in the wastelands:
![image](https://user-images.githubusercontent.com/489601/150638274-676ab824-8ccd-409f-830a-c370387b4f1c.png)

Which turns out to be some mine:
![image](https://user-images.githubusercontent.com/489601/150638299-2a663057-5171-4d8c-9481-c8dd12bc0b36.png)

### Save file

[vh2_0082.zip](https://github.com/ihhub/fheroes2/files/7918292/vh2_0082.zip)

**Comment by ihhub** [comment]
Hi @a1exsh , how does it look in the original game? If it's the same then it's the issue with the map itself, not with fheroes2.

**Comment by LeHerosInconnu** [comment]
Hello @a1exsh,

This is due to a bug that may appear in the scenario editor. :)
Link to original game saves with the bug: https://heroes2.forumactif.com/t178-heroes-2-bugslow-priority-invisible-mercury-mine.

**Comment by a1exsh** [comment]
Good point, checking with the OG.

1. In the editor looks like an empty cell:
![editor2_003](https://user-images.githubusercontent.com/489601/150672338-8db1db4f-f3a1-45c0-b2fb-4c963df12c6a.png)

2. Cannot check how the map looks in OG right now, as expansion campaign do not start in dosbox for some reason.  Don't remember if I ever tried it on this machine.

**Comment by LeHerosInconnu** [comment]
Hello @a1exsh,

> 2. Cannot check how the map looks in OG right now, as expansion campaign do not start in dosbox for some reason.  Don't remember if I ever tried it on this machine.

The bug is also present with this scenario in the original game.

In original game:

![Mercury mine 001](https://user-images.githubusercontent.com/43583994/150684046-e96f987e-cd44-40e6-86c4-4a77ea6d0c16.png)

![Mercury mine 002](https://user-images.githubusercontent.com/43583994/150684049-c155d144-3fd6-4d5c-b98a-794284c94d5b.png)

Here is the save file:
[Mercury mine 1000.zip](https://github.com/ihhub/fheroes2/files/7920686/Mercury.mine.1000.zip)

**Comment by ihhub** [comment]
This is definitely the problem of the original editor. Nothing we need to do here.
