### ISSUE TITLE
Big creature takes wrong position while attacking big enemy

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#495]
As on the screen Phoenix attack right hexagon. but takes the same position if he attack left hexagon of a big enemy troop.
![Attack angle](https://user-images.githubusercontent.com/55348946/81495941-a2240d00-92bc-11ea-8acb-67548383d5b8.jpg)
![Attack angle1](https://user-images.githubusercontent.com/55348946/81495946-b1a35600-92bc-11ea-83b0-6c16383df340.jpg)

**Comment by ihhub** [comment]
Hi @Branikolog , this is logically correct behavior. You are pointing to move Phoenix to that hexagon. You have to think that you're commanding the Phoenix to move it's head to a hexagon near the wolf so its tail will be in hexagon on the left.

I think this is the same behavior as in the original game. Please let me your thoughts and you're agree with me then please close this issue.

**Comment by Branikolog** [comment]
Hi, @ihhub!
Here we have two possible hexes to attack that couple of wolves, right? If we target head or tail the attack will be the same. Logically here we should have an ability to land Phoenixes on two different hexes, while attacking that wolves.
In the original game we can choose the place Phoenixes land: close to that skull or closer to that 16 wolves.
Don't forget, that in the original we have straight bottom attack, while fheroes has not.
Actually, in the original game we can make 4 bottom attacks in battle 2hex creature vs 2hex creature:
![image](https://user-images.githubusercontent.com/55348946/103167457-54084d80-483c-11eb-8e62-ed779769eff3.png)
![image](https://user-images.githubusercontent.com/55348946/103167461-58cd0180-483c-11eb-8b69-6b6f2333b513.png)
![image](https://user-images.githubusercontent.com/55348946/103167464-5c608880-483c-11eb-8c59-ceb562747eda.png)
![image](https://user-images.githubusercontent.com/55348946/103167467-62566980-483c-11eb-959d-226b418163d3.png)
Note, that in the last attack Phoenixes take the position we're discussing in this issue:
![image](https://user-images.githubusercontent.com/55348946/103167486-7d28de00-483c-11eb-902c-f223ff6ad784.png)

**Comment by ihhub** [comment]
Closing this issue as now we have visible indicator which position a creature will take during an attack.
