### ISSUE TITLE
Does fheroes2 support audio from original CD tracks ?

### ISSUE THREAD

**Issue by Saroumane** [ihhub/fheroes2#4953]
### Your question

Hello, 
I understand that Homm2 Gold (DOS) from GOG.com is the most supported version for `fheroes2`.
However is it possible to use `fheroes2` with :

- Win95 version from GOG.com (I understand GOG provides it as a bonus CD image, but I'm not sure that original CUE/BIN audio tracks are included ?)
- a retail CD of Homm2 original edition  / classic edition ? (is it mandatory to rip a CUE/BIN  file to use audio tacks ? or is it possible to use a real CD-ROM drive ?)

(I don't want to use ripped audio tracks from GOG as they have audible glitches)

Thanks for your feedback !

**Comment by oleg-derevenetz** [comment]
Hi @Saroumane, fheroes2 does not support playing music tracks directly from CD (or CD image). You will need to rip them one way or the other (in the OGG format).

> Win95 version from GOG.com (I understand GOG provides it as a bonus CD image, but I'm not sure that original CUE/BIN audio tracks are included ?)

According to the contents of the `homm2.ins` file from the GOG distribution, it seems that the CD image itself does not contain audio tracks, and they are "mounted" using the `*.ogg` files from the `music` folder.

**Comment by Saroumane** [comment]
@oleg-derevenetz Thank you for this answer. Is it planned on the 'feature roadmap' ?

**Comment by oleg-derevenetz** [comment]
@Saroumane

> Thank you for this answer. Is it planned on the 'feature roadmap' ?

Not the top priority at least. Nowadays, apps are no longer distributed on CDs.

**Comment by Saroumane** [comment]
Sure, I perfectly understand that.  CUE/BIN support would be awesome for digital preservation, though.
