### ISSUE TITLE
Cannot use "Dimension door" spell over some areas

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#496]
Cannot use "Dimension door" spell to move hero to the areas behind mountains.
![Mountains](https://user-images.githubusercontent.com/55348946/81500781-0bb41380-92dd-11ea-8358-1f917cda247e.jpg)
![Mountains2](https://user-images.githubusercontent.com/55348946/81500782-0e166d80-92dd-11ea-8945-78509718a3c3.jpg)

**Comment by ihhub** [comment]
The problem lies in `MP2::isClearGroundObject` function.

**Comment by LeHerosInconnu** [comment]
This is a problem with many objects.
I think all objects should be checked in comparison to the original game.

In fheroes2:

![Dimension door unable location 01](https://user-images.githubusercontent.com/43583994/120112819-d1334800-c177-11eb-956f-1bd257cfb810.png)

![Dimension door unable location 02](https://user-images.githubusercontent.com/43583994/120112830-d7292900-c177-11eb-9394-49edabcd75c8.png)
