### ISSUE TITLE
Campaign description window, missing shadows for buttons

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4977]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Shadows for buttons are missing in the window, but appear after releasing of buttons.
![image](https://user-images.githubusercontent.com/55348946/152335452-1ea0e8bb-787f-4d23-baa2-463515245a5f.png)
![image](https://user-images.githubusercontent.com/55348946/152335488-2c85bdef-fe5a-4f8f-9235-b8cb505aadbb.png)
![image](https://user-images.githubusercontent.com/55348946/152335548-4e034862-d78c-4365-9f54-38129a251443.png)
Also, in a pressed state we can watch another button under the pressed one.
![image](https://user-images.githubusercontent.com/55348946/152342416-a56776bb-b61b-4ac3-b259-88d9caf450e8.png)

The bug is present in the OG too.

### Save file

Any PoL campaign window.

**Comment by xcom169** [comment]
Hello All, 
![image](https://user-images.githubusercontent.com/17802090/152866332-d9f2d03a-e0bd-462c-a811-9239c09f21c8.png)
View intro button is working you ?

**Comment by oleg-derevenetz** [comment]
Hi @xcom169

https://user-images.githubusercontent.com/32623900/152892354-14165878-8551-4418-97af-362d6c3003ae.mp4
