### ISSUE TITLE
Battle screen, Cyclops don't perform double attack while

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4978]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

When AI takes the control of Cyclops, he cannot perform 2-hex attack.
![image](https://user-images.githubusercontent.com/55348946/152356796-0fc7d806-df88-461b-a623-194fcc0630f6.png)

### Save file

[Cyclops attack.zip](https://github.com/ihhub/fheroes2/files/7995109/Cyclops.attack.zip)

**Comment by ihhub** [comment]
And somebody claimed that AI is too strong🤔

**Comment by oleg-derevenetz** [comment]
> And somebody claimed that AI is too strong🤔

Perhaps it is - in comparison with the original game.
