### ISSUE TITLE
Wrong animation while angled attack 

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#500]
While angled attacking phoenix's animation is the same as front attack animation.
![Diagonal attack](https://user-images.githubusercontent.com/55348946/81818121-48c71280-9536-11ea-9a4a-c9639387167c.jpg)
![Diagonal attack2](https://user-images.githubusercontent.com/55348946/81818127-4a90d600-9536-11ea-80a5-4016394be241.jpg)
![Diagonal attack3](https://user-images.githubusercontent.com/55348946/81819527-19190a00-9538-11ea-9723-89b37d1a60bb.jpg)

**Comment by ihhub** [comment]
Hi @idshibanov , could you please take a look into it?

**Comment by Branikolog** [comment]
This issue was at previous version too.

**Comment by idshibanov** [comment]
Aware of this. Will be fixed in the upcoming portion of animation changes (attack timings as well).
