### ISSUE TITLE
Freeze during AI turn

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#5008]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Game freezes during AI turn.
Issue was found by one of our players.

### Save file

[error.zip](https://github.com/ihhub/fheroes2/files/8055422/error.zip)

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , could you please take a look at this? It seems that we use `isTileBlocked` function within **buildPath** which leads to a fact that we don't consider a teleport tile as a destination according to `// we shouldn't use teleport at the starting tile` comment.

**Comment by oleg-derevenetz** [comment]
@ihhub the issue is that teleport tile is protected by Griffins, and AI pathfinder has a special rule regarding tile reachability - if hero has not enough army to win the guardians, then the tile is unreachable. I'll propose a fix soon.

**Comment by ihhub** [comment]
Wonderful!
