### ISSUE TITLE
Direct up and down attacks not handled correctly for double-hex units

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#501]
While attacking from a certain angle Phoenix make one wing swing and then attacks. But he stays the same place.
![Flying animation](https://user-images.githubusercontent.com/55348946/81821219-4961a800-953a-11ea-869e-a40c3bb7a858.jpg)
![Flying animation2](https://user-images.githubusercontent.com/55348946/81821223-4b2b6b80-953a-11ea-8800-56d19b7e8dab.jpg)
![Flying animation3](https://user-images.githubusercontent.com/55348946/81821228-4bc40200-953a-11ea-8ad9-12461aa32d9e.jpg)

**Comment by ihhub** [comment]
Hi @idshibanov , would you mind to take a look into this issue? I think it is related to our latest changes.

**Comment by Branikolog** [comment]
> Hi @idshibanov , would you mind to take a look into this issue? I think it is related to our latest changes.

Definitely.

**Comment by idshibanov** [comment]
Yep, I'll take a look

**Comment by idshibanov** [comment]
Turns out in OG game this move is impossible. "Tail" (left) tile is actually the main one and you attack one of the 8 directions rather than attacking the tile.

![heroes2_022](https://user-images.githubusercontent.com/1373638/81896617-fc55f400-9582-11ea-8fb2-4ca828751236.png)

**Comment by idshibanov** [comment]
@ihhub @Branikolog So this case is kind of undefined behavior. What do we want? Disable this kind of attack? Should phoenix turn around and strike those two tiles? If elf wouldn't be blocking to the left - would it try to move to the left first? Trying to illustrate the turnaround.

![81821219-4961a800-953a-11ea-869e-a40c3bb7a858](https://user-images.githubusercontent.com/1373638/81897530-d4679000-9584-11ea-8e38-a8a08349a0fc.jpg)

**Comment by Branikolog** [comment]
> @ihhub @Branikolog So this case is kind of undefined behavior. What do we want? Disable this kind of attack? Should phoenix turn around and strike those two tiles? If elf wouldn't be blocking to the left - would it try to move to the left first? Trying to illustrate the turnaround.
> 
> ![81821219-4961a800-953a-11ea-869e-a40c3bb7a858](https://user-images.githubusercontent.com/1373638/81897530-d4679000-9584-11ea-8e38-a8a08349a0fc.jpg)

From this angle phoenix should attack only vampires. Our version doesn't have straight vertical attack at all. But OG have.
![Vertical attack](https://user-images.githubusercontent.com/55348946/81914940-9b5a0a80-95da-11ea-877f-e89707e2363b.jpg)
I think we firstly should add this type of attack.

>  If elf wouldn't be blocking to the left - would it try to move to the left first? 
> 
I think it should. But only if you choose to attack from this angle
![No elves](https://user-images.githubusercontent.com/55348946/81915561-6e5a2780-95db-11ea-8138-bddbb202ced5.jpg)


Here i should also mention another issue i did a couple days before. 
https://github.com/ihhub/fheroes2/issues/495#issue-615355701

**Comment by ihhub** [comment]
The root of the problem lies in this code:
```
const int dir = cell->GetTriangleDirection( GetMouseCursor() );
const int cursor = GetSwordCursorDirection( dir );
```

The first method should accept an extra parameter for wide creature and then handle the code below `GetSwordCursorDirection`.

**Comment by ihhub** [comment]
Hi @Branikolog , is it still a reason to implement the issue? It's obviously a misleading feature of the original game.

**Comment by Branikolog** [comment]
Hi, @ihhub 
Well, I cannot decide what is better now... On one hand, uneven original attack directions allow to attack creatures, that are not possible to be attacked in fheroes2 implementation. But on the other hand, current non-original implementation is more visually demonstrative.
There were almost 0 complains regarding this difference... But I'm still not sure, if we should not implementing the original behaviour here...
