### ISSUE TITLE
Speed quantity doesn't fit creature's info window

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#503]
I think we should squeeze a little these words.
![Creature info2](https://user-images.githubusercontent.com/55348946/81932120-ea606980-95f3-11ea-805c-3a1e759a42fc.jpg)
![Creature info](https://user-images.githubusercontent.com/55348946/81932125-ec2a2d00-95f3-11ea-9d9f-34c2bbe5f151.jpg)

**Comment by ihhub** [comment]
Hi @Branikolog , how are you proposing to solve this issue?

**Comment by Branikolog** [comment]
> Hi @Branikolog , how are you proposing to solve this issue?

I wrote in a first message. I think we should squeeze this description. Maybe make spaces a little tighter.

**Comment by ihhub** [comment]
No, we cannot do this as our font is fixed.

**Comment by ihhub** [comment]
This is how it looks like in the original demo version:
![image](https://user-images.githubusercontent.com/19829520/82141132-5b0ebc80-9866-11ea-9f0e-ca28a2659df0.png)

**Comment by ihhub** [comment]
What we could do is to remove the number for speed and then shift everything to the right having enough empty space to borders. @Branikolog , what do you think?

**Comment by Branikolog** [comment]
The way it is written in our version i like more.
Are you sure, that we cannot reduce for example this space? It looks like there are two spaces....
![Info](https://user-images.githubusercontent.com/55348946/82141214-fab75500-983c-11ea-98cb-876a0c796640.jpg)

**Comment by Branikolog** [comment]
> What we could do is to remove the number for speed and then shift everything to the right having enough empty space to borders. @Branikolog , what do you think?

What about remove number in hooks and make separate line with the speed quantity?

**Comment by ihhub** [comment]
This is the current state:
![image](https://user-images.githubusercontent.com/19829520/82141434-6c58c880-9868-11ea-8ff5-d4872e6b9d0c.png)
this is when I reduced the gap to be as 1 space:
![image](https://user-images.githubusercontent.com/19829520/82141417-46332880-9868-11ea-857c-29cedf0e6b31.png)
and this is when I shifted everything to be centered:
![image](https://user-images.githubusercontent.com/19829520/82141428-53501780-9868-11ea-8b89-8797700bfc29.png)


@Branikolog , is it better now?

**Comment by Branikolog** [comment]
Second screenshot looks better. I think this solution is what we need.
