### ISSUE TITLE
In-Game Czech characters are broken

### ISSUE THREAD

**Issue by GeorgeK1ng** [ihhub/fheroes2#5041]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

There exist fully translated Czech game from 2002 by CD Projekt. I just tried it and realized Czech support is not added. Then I continued to discord and with @ihhub we found "magic" number to add Czech support. Now I can change language to Czech but there are still issues. On map selection screen is description displayed correctly. I mean all Czech characters are displayed correctly. But when started map and enter Castle, these characters are not correctly displayed. 

This is how it looks 
![image](https://user-images.githubusercontent.com/98261225/154849552-3e485b01-d68f-4df5-9145-7d1abbe4f221.png)

And this is how it should look, screen taken from original game
![image](https://user-images.githubusercontent.com/98261225/154849601-9b6a4a86-c57a-4e87-899f-a6d6511fc6f9.png)

Czech needs to use CP-1250 same as Polish for example.

Of course translation doesn't work correctly. Many things are not translated, even they are completely translated in original game.

### Describe the possible solution

Use CP-1250 for Czech language

**Comment by zenseii** [comment]
Hi, @GeorgeK1ng.

I remembered that you created this issue. Currently we do not have a very complete Czech translation. If you would be interested with helping out with that then you are more than welcome. I can assist you with it, but I do not know any Czech so that is one thing I cannot help with.

**Comment by GeorgeK1ng** [comment]
@zenseii I'm interested in translation, I can also contact "Gremlin" who translated original HOMAM2 and HOMAM3 into Czech. 
I don't know if he will be in. But I'm 100% in, thats why I created PR for files grabbing script and reported Windows XP bug. 

When I'm sure Czech users can download and install original game and load files into fheroes2 without any touch (best would be on XP too), then I hope I can start and make community "ticket", so users can help me to finish this huge translation from scratch soon as possible.

My attempt with this project was delayed due long XP2ESD development
