### ISSUE TITLE
Archibald's campaign is not available

### ISSUE THREAD

**Issue by szymor** [ihhub/fheroes2#5042]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

As the title says, I cannot see any method of selecting Archibald's campaign. I copied all the needed folders (except ANIM) from HoMM 2 Gold from GOG. When I click New Game -> Campaign Game -> Original Campaign, I immediately see Roland's campaign window.

Tested and reproducible on 0.9.11 and the latest snapshot build ( https://github.com/ihhub/fheroes2/releases/tag/fheroes2-linux-sdl2_dev ) on ArchLinux (5.16.9-arch1-1) and on the version provided with EmuELEC v4.3 on Gameforce handheld.

### Save file

The issue is visible before starting the campaign, so no save file provided.

**Comment by ihhub** [comment]
Hi @szymor , the answer for your question lies in your question :) Without video files which are located in `ANIM` directory there is no other way to select Archibald campaign. You must copy ANIM directory.

**Comment by szymor** [comment]
There is no ANIM directory with the version of the game provided by GOG (DOS version run on top of dosbox). I found Windows version of the game with ANIM directory and it works after I copied the mentioned directory.

Thank you for the answer. I will leave closing the ticket to you as compatibility between fheroes2 and the GOG version could be investigated.

**Comment by oleg-derevenetz** [comment]
@szymor please note that you can use the `extract_homm2_resources.sh` script on Linux to extract `ANIM` from GOG distribution (as well as  `extract_homm2_resources.bat` on Windows).

**Comment by szymor** [comment]
Yes, I read the installation guide. The script did not work when a path to the exe installer was given. I have tested it a while ago on the installed DOS version and it extracted ANIM folder properly. That completely solves my issue, big thanks once again :)

I think I can close the ticket now.

**Comment by oleg-derevenetz** [comment]
@szymor Yeah, unfortunately you need to have already installed GOG version somewhere to copy/extract the resource files from it. These scripts are not able to extract resources directly from the EXE installers.

**Comment by viT-1** [comment]
> Hi @szymor , the answer for your question lies in your question :) Without video files which are located in `ANIM` directory there is no other way to select Archibald campaign. You must copy ANIM directory.

Strange, but I already have ANIM directory with files, and have no Campaign Choosing Screen in fheroes2 & HoMM2 (original game).

**Comment by ihhub** [comment]
Hi @szymor , which version of Heroes 2 are you using? Is it from GoG?

**Comment by szymor** [comment]
@ihhub I used HoMM 2 from GoG back then. AFAIR there were two versions (DOS and Windows) available to download. Both of them worked fine, but one of them needed extract_homm2_resources.sh to be used in order to extract all needed files.

If some files seem not to work, try to change lower case letters to upper case (or vice versa).

**Comment by ihhub** [comment]
Sorry, @szymor , I mean another commenter :)

Hi @viT-1 , which version of Heroes 2 are you using? Is it from GoG?

**Comment by viT-1** [comment]
> Sorry, @szymor , I mean another commenter :)
> 
> Hi @viT-1 , which version of Heroes 2 are you using? Is it from GoG?

It's old download. I don't remember from where it was downloaded.
But I think problem is not only ANIM directory, but noCD version, which may be was cracked to not using any video.

**Comment by ihhub** [comment]
@viT-1 , please use an official version of HoMM 2 in this case. We don't support pirated versions.
