### ISSUE TITLE
Restarting the campaign map does not allow you to select a bonus

### ISSUE THREAD

**Issue by AAS** [ihhub/fheroes2#5052]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

For example, if you selected sorceress on map 8 of Roland campaign, restarting dialog forces you to play wizard.

![Screenshot 2022-02-23 084911](https://user-images.githubusercontent.com/179733/155258937-7f63f46a-15f0-4301-971c-a2bf2cdac21c.jpg)

### Save file

[restart_bug.savc.zip](https://github.com/ihhub/fheroes2/files/8121805/restart_bug.savc.zip)

**Comment by a1exsh** [comment]
True.  As a workaround you can load the auto-saved campaign file from winning the latest scenario, but it would be nicer if we allowed the user to choose the bonus or at least keep the choice made initially.
