### ISSUE TITLE
Heroes 2 Compendium version .mp3 music not detected by fheroes2

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#5063]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

A user reported on the project's discord channel that they only get midi sound even after having copied the .mp3 audio from their Heroes 2 Compendium CD to the music folder inside the fheroes2 folder. They've tried to name the audio files the same as the GOG audio files.

### Save file

None

### Additional info
They're on Windows 7 64bit and have tried both the SDL1 and 2 latest builds in the .zip archive/not installer.

**Comment by zenseii** [comment]
The user reporting this issue just posted this:

"Update:
I have managed to make the CD music to work! partying_face 

There are two key steps that must be taken into acount:
1. all the music files must be in *.ogg format! Anything else will not work (eg. mp3)
2. Files must be named "homm2_(track number) - Example: homm2_01.ogg
3. There are 42 audio files from 1-42.
If you are extracting music from CD image file (bin/cue), notice that audio files start from 2 instead of 1, because 1st track is reserved.
Just extract all the audio files and rename them from 1-42 (2nd becomes 1st, 3rd becomes 2nd etc.). If you fail to do so, the tracks will be all messed up yum  (sea theme in dirt, warlock music in necromancer town etc.)

Just a friendly suggestion.
It would be awesome, if the instructions for CD music would be included in the instalation guide or even included in the ZIP file of f_heroes2.

EG. I found an old version of f_heroes2 from 2013 and there was a folder "music" and a readme file with instructions how the audio files must be renamed and in what format to work.

Also in original Heroes the music continues from where it ended when switching heroes, towns or ending turn. While in f_Heroes it always starts from the begining which can be quite frustrating, because it takes time before music kicks in and starts playing. If this could be implemented it would be awesome, because IMHO music is one of the best parts of Heroes 2."

**Comment by ihhub** [comment]
Hi @zenseii , yes it could. According to [this page](https://www.libsdl.org/projects/SDL_mixer/docs/SDL_mixer_55.html) SDL supports MP3 format.

**Comment by zenseii** [comment]
Great! It seems we might also need to take into account that the mp3 files are named differently? I'm not sure if there is some kind of coherence between Heroes 2 versions that come with mp3, which should be all CD based releases (?).

**Comment by ihhub** [comment]
Hi @zenseii , do we know the naming of files for MP3 format? If not let's leave it as it is till we confirm the naming.

**Comment by zenseii** [comment]
I believe I have might still have the compendium version myself somewhere. I'll have a look for it among my stuff when I get home in case we don't receive an answer from maro696 on Discord.
