### ISSUE TITLE
Phoenix's shadow is cropped

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#507]
The shadow under Phoenix is cropped. When Phoenix does its animation the cropped head of the shadow appears for a moment.... 
![Shadow](https://user-images.githubusercontent.com/55348946/81938547-be49e600-95fd-11ea-95fc-f52706aac074.jpg)

**Comment by ihhub** [comment]
We could use a part of 32 frame for frame 1 to fix this issue.

**Comment by Branikolog** [comment]
To fix shadow e should take every pixel from the frame 32 lower than line 0;72px - 74;72px  (up to 0;96px - 74;96px) and paste it to the 001 and 030 frames.
