### ISSUE TITLE
Players can land on boat if they are lucky

### ISSUE THREAD

**Issue by felix642** [ihhub/fheroes2#5070]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

When selecting a path to land, if you finish your turn and an enemy player spawns a boat at the location that you want to go to. Your path will still be valid the next turn and you'll be able (push the boat aside ?) to land at this location.

https://user-images.githubusercontent.com/60141446/156812366-b302f684-1714-41ec-bac0-1788cafe213d.mp4

### Save file

[before_boat_overwrite.zip](https://github.com/ihhub/fheroes2/files/8187674/before_boat_overwrite.zip)

**Comment by oleg-derevenetz** [comment]
Hmm, cannot reproduce this so far. On the latest snapshot:

https://user-images.githubusercontent.com/32623900/156835679-11e60c0a-9e03-419d-9bbe-cbac766be0a6.mp4

**Comment by felix642** [comment]
Oh wow ! You can ignore that. My fork was not synced with the repo at all. I was currently testing on c51b227 which was committed on december 29th. I think we can close this issue. Thank you @oleg-derevenetz
