### ISSUE TITLE
Primary Skill Information windows, value "+1" is not displayed in the primary skill information windows

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#5089]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

In fheroes2, the value "+1" is not displayed in the primary skill information windows.

In fheroes2:

![Internal Popup 005](https://user-images.githubusercontent.com/43583994/157094018-5da21710-56a6-4506-b1b3-2a88f9ae3653.png)

![Internal Popup 006](https://user-images.githubusercontent.com/43583994/157094023-4b96f03e-2fd4-4d30-b627-436155f5bba7.png)

![Internal Popup 010](https://user-images.githubusercontent.com/43583994/157094030-74477d2a-0a1f-4b07-b66c-0527a393b0ed.png)

![Internal Popup 011](https://user-images.githubusercontent.com/43583994/157094039-f32b2e77-833c-4114-b345-ff3c04d0202e.png)

![Internal Popup 012](https://user-images.githubusercontent.com/43583994/157094048-2ceb98a7-5d56-455e-bc53-979cee4c5b0b.png)

![Internal Popup 013](https://user-images.githubusercontent.com/43583994/157094054-d7bfd713-71ff-4ad5-acc6-f506ce528093.png)

![Internal Popup 017](https://user-images.githubusercontent.com/43583994/157094064-ec43785f-c4bb-4d5a-9351-e1501bb40e45.png)

![Internal Popup 018](https://user-images.githubusercontent.com/43583994/157094074-54187253-07db-409e-8f55-b2c70b81f63e.png)

### Describe the possible solution

This seems strange. I think that the value "+1" should also be displayed in the information window.

### Additional info

Version 0.9.12 5071

**Comment by oleg-derevenetz** [comment]
This auxiliary window is just a generic description of the corresponding skill. I personally see no reason why "+1" should be displayed in this window.

**Comment by ihhub** [comment]
I agree with @oleg-derevenetz about this. The auxiliary window contains a general description of the skill so there is no need to display extra value there.

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz and @ihhub,

> This auxiliary window is just a generic description of the corresponding skill. I personally see no reason why "+1" should be displayed in this window.

> I agree with @oleg-derevenetz about this. The auxiliary window contains a general description of the skill so there is no need to display extra value there.

The value is displayed in other information windows.
In the examples, the value of experience points is displayed: "1000", the level of secondary skills is displayed: "Expert".
It seems appropriate and more "natural" to me to do it this way everywhere in the information windows.

In fheroes2:

![Internal Popup 008](https://user-images.githubusercontent.com/43583994/157267561-8ade37e7-7156-48a8-b990-822696816f5c.png)

![Internal Popup 009](https://user-images.githubusercontent.com/43583994/157267571-65fb6565-279f-4504-a6e3-bf1059d5b701.png)

![Internal Popup 049](https://user-images.githubusercontent.com/43583994/157267582-206ed2f6-fc27-47cd-9703-bab2450a996d.png)

![Internal Popup 050](https://user-images.githubusercontent.com/43583994/157267589-39fc628f-c7c6-4aef-8a52-5a7fc6da9c22.png)

**Comment by ihhub** [comment]
I think we shouldn't display values for experience like we do for resources for example. No values should be shown in right click windows. For skills we have to display the skill name and level as the description varies.
