### ISSUE TITLE
Can we run the on lower resolution

### ISSUE THREAD

**Issue by psyhlo** [ihhub/fheroes2#5090]
### Your question

Hi,
i have anbernic rg351p with resolution of the screen - 480×320
It runs smooth but it is smashed and hard to read the text :(.
So is the something we can do to run it on lower resolution?

**Comment by ihhub** [comment]
Hi @psyhlo , no. It is not feasible within the project goals. The original game is designed to run in 640x480 resolution and adapting all in-game assets just for this smaller resolution is out of the scope.
We had similar topics in the past so I am closing this issue as your question was answered fully. Feel free to reopen it if I missed something to explain.

**Comment by psyhlo** [comment]
thanks for the answer
