### ISSUE TITLE
Adventure map, Tree of Knowledge, it is not possible to display the experience information window with a right click

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#5091]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, it is not possible to display the experience information window with a right click.

In fheroes2:

![Internal Popup 028](https://user-images.githubusercontent.com/43583994/157260453-d557b722-2c76-4b80-b8f9-be2d28339844.png)

In original game:

![Internal Popup 028 H2](https://user-images.githubusercontent.com/43583994/157260465-851ba4bd-6be0-44cf-8a45-65eaf66d22af.png)

### Save file

Here are the save files:
[Before knowledge tree 01.zip](https://github.com/ihhub/fheroes2/files/8207069/Before.knowledge.tree.01.zip)

### Additional info

Version 0.9.12 5071

**Comment by ihhub** [comment]
This issue was closed few days ago.
