### ISSUE TITLE
Luck and Morale information windows, use terms that are not reminiscent of the Hero's Luck and Morale level so as not to confuse the player, for example "Negative" and "Positive" Luck and Morale

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#5093]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

~fheroes2, the Luck and Morale value of the information window should correspond to the Luck and Morale value of the hero.~

**Edit 2022/03/09.**
It would be better to use terms that are not reminiscent of the Hero's Luck and Morale level so as not to confuse the player, for example "Negative" and "Positive" Luck and Morale.

In fheroes2:

![Internal Popup 014](https://user-images.githubusercontent.com/43583994/157271381-31d57045-b924-4c5c-889c-99c2a348dcbc.png)
The yellow title and text of the information window should indicate "Great Luck".
![Internal Popup 015](https://user-images.githubusercontent.com/43583994/157271400-cf659af9-b2ce-418e-ac7a-fdfaf490bb16.png)
![Internal Popup 016](https://user-images.githubusercontent.com/43583994/157271410-390ef58b-ada1-443a-bfb1-f9b1c828620b.png)

![Internal Popup 020](https://user-images.githubusercontent.com/43583994/157271416-bd2f69d0-ae59-4084-997a-76074cbe2cb3.png)
The yellow title and text of the information window should indicate "Great Morale".
![Internal Popup 021](https://user-images.githubusercontent.com/43583994/157271427-acd78dbf-3b0f-43b3-ab52-2883761b2895.png)
![Internal Popup 023](https://user-images.githubusercontent.com/43583994/157271445-77a99af5-202e-489b-b040-2ae175c39919.png)

![Internal Popup 025](https://user-images.githubusercontent.com/43583994/157271453-ab0049b0-6cde-459a-a70d-4ed8d6cd7ca8.png)
The yellow title and text of the information window should indicate "Irish Luck".
![Internal Popup 026](https://user-images.githubusercontent.com/43583994/157271463-960ccfc4-d3bc-43ad-bf65-dc077f450b6d.png)
![Internal Popup 027](https://user-images.githubusercontent.com/43583994/157271472-744a5cb5-f818-42ef-8398-01eb1420b3e3.png)

![Internal Popup 031](https://user-images.githubusercontent.com/43583994/157271482-ac9da6a1-3707-4847-848f-76a10f4c6354.png)
The yellow title and text of the information window should indicate "Irish Luck".
![Internal Popup 032](https://user-images.githubusercontent.com/43583994/157271491-a2d6d9bb-4c49-4a15-960a-cd8d88d6a5cb.png)
![Internal Popup 033](https://user-images.githubusercontent.com/43583994/157271499-57fd14aa-0ec6-4030-b82d-1a0cbdc26620.png)

### Describe the possible solution

Display the Luck and Morale value of the hero in the information window.

**Edit:**
Or better (because the Luck and Morale will not necessarily correspond with the value of the hero), replace with a term that is not confusing with the actual value of the hero, such as "Positive Morale" and "Negative Morale", and "Positive Luck" and "Negative Luck".

### Additional info

Version 0.9.12 5071

**Comment by zenseii** [comment]
Right, I forgot about this one. I have one point for discussion though: wouldn't it be better to have the initial window show what your current luck/morale is, and have the right click window remain as a pure informative window about the game mechanics? In the case I'm proposing it might be better to just write "Positive morale gives..." and "Positive luck...". Those are just my two cents.

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu & @zenseii !
I agree with @zenseii , we should go for "Positive Luck/morale" terms in the description windows. No matter what current hero's morale and luck are, there should be written an explanation of luck and morale benefits in the information window.

**Comment by LeHerosInconnu** [comment]
I changed the title for a better understanding.
