### ISSUE TITLE
No titles for spell book tabs

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#51]
In original game we could see names of spell book tabs while in current implementation we display only "Open book" which is incorrect because book is opened.

Look, for example, under the cursor.:
![image](https://user-images.githubusercontent.com/19829520/79065125-7115e400-7ce0-11ea-8602-f8c02995706a.png)

and this how it should be:
![image](https://user-images.githubusercontent.com/19829520/79065178-e4b7f100-7ce0-11ea-9721-1d0b4ad611be.png)

**Comment by ihhub** [comment]
Start point for this issue is `Spell SpellBook::Open(const HeroBase & hero, int filt, bool canselect) const` function.

**Comment by idshibanov** [comment]
This is not as easy as it first seems, needs some kind of dialog system refactoring. Spellbook window doesn't return from the loop until you have selected anything - this means hero dialog won't update or redraw the status bar.

**Comment by vincent-grosbois** [comment]
I can have a look, it seems it's enough to just inject the status bar pointer in the magic book window and tell it to draw the status

**Comment by ihhub** [comment]
Hi @vincent-grosbois , you're right. I think text object has background restore function so it should be easy to implement. I assigned it to you.

**Comment by ihhub** [comment]
Closed in #2674.
