### ISSUE TITLE
Add full support for CD music

### ISSUE THREAD

**Issue by idshibanov** [ihhub/fheroes2#510]
Support for it shouldn't be hidden behind def in the code. We should avoid compiling 'versions' and make it robust.

1. CD music is not supported/implemented for SDL2.
2. SDL1 implementation is old and has to be updated.
3. _Track mapping is wrong (when you get it to work)._
4. _We need an in-game switch between Midi, CD and external music. Editing .cfg file is a no-no._

Edit: points 3 and 4 are done, but we still don't have a CD player

**Comment by ihhub** [comment]
Hi @idshibanov , are we planning to add CD support soon? If not I will move this issue to 1.0 version.

**Comment by idshibanov** [comment]
No problem, updated!
