### ISSUE TITLE
Adventure map, Shipwreck, hero does not fight the guards (Ghosts) while the Shipwreck has not been visited

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#5101]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Adventure map, Shipwreck, hero does not fight the guards (Ghosts) while the Shipwreck has not been visited.

In fheroes2, the hero does not fight the guards (Ghosts) while the Shipwreck has not been visited (there is only one player on the map).

In fheroes2:

![Internal Popup 039](https://user-images.githubusercontent.com/43583994/157417747-022e8779-f6a9-40ae-a77a-fe38e2b8b664.png)

![Internal Popup 042](https://user-images.githubusercontent.com/43583994/157417758-4685d5bb-5b2f-4672-adc2-f3c0e2671d21.png)

### Save file

Here are the save and test scenario files:
[Before Shipwreck 01.zip](https://github.com/ihhub/fheroes2/files/8213576/Before.Shipwreck.01.zip)

### Additional info

Version 0.9.12 5071

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , could you please tell what are possible awards can a hero get from a shipwreck?

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , could you please tell what are possible awards can a hero get from a shipwreck?

I did two tests with ten Shipwrecks.

For the first test, I got:
5 x 5000 gold
1 x 2000 gold and 1 Artifact
1 x 2000 gold
3 x 1000 gold

In original game:

![Shipwreck reward ghosts 001](https://user-images.githubusercontent.com/43583994/157720644-1392e2cf-199e-4f74-94e4-9ed46f877cf4.png)
![Shipwreck reward ghosts 002](https://user-images.githubusercontent.com/43583994/157720664-7e072035-e778-4d7c-880d-197e463e0470.png)
![Shipwreck reward ghosts 004](https://user-images.githubusercontent.com/43583994/157720675-2784aee2-15a6-4d4d-8038-d164b4f84673.png)
![Shipwreck reward ghosts 010](https://user-images.githubusercontent.com/43583994/157720684-2f3dcace-b3d1-415e-afc9-9b132d6f157e.png)

For the second test, I got:
2 x 5000 gold
2 x 2000 gold
6 x 1000 gold 

In original game: (with the number of Ghosts and the distribution of Ghosts groups):

![Shipwreck reward ghosts 011](https://user-images.githubusercontent.com/43583994/157720948-da91db87-aa23-4d67-bcef-9e66dd95c7c2.png)
![Shipwreck reward ghosts 012](https://user-images.githubusercontent.com/43583994/157720964-baeaf079-40a0-4bf2-8d67-914f29ad2567.png)

![Shipwreck reward ghosts 013](https://user-images.githubusercontent.com/43583994/157720977-47cc172f-703a-4445-8af9-82c7872cac72.png)
![Shipwreck reward ghosts 014](https://user-images.githubusercontent.com/43583994/157720991-7b3bb2d8-cb07-4051-a48e-dbe31cf6252a.png)

![Shipwreck reward ghosts 015](https://user-images.githubusercontent.com/43583994/157721003-8458b49a-8baa-4ce0-a163-190147fb8336.png)
![Shipwreck reward ghosts 016](https://user-images.githubusercontent.com/43583994/157721022-9654a5b9-1677-4b08-8b3d-b5f4c40e6dd4.png)

![Shipwreck reward ghosts 017](https://user-images.githubusercontent.com/43583994/157721032-12a5a308-6544-4dbf-8d56-58bbc32a2a4c.png)
![Shipwreck reward ghosts 018](https://user-images.githubusercontent.com/43583994/157721043-60c2d482-8b5a-43eb-aee0-66d2fa370f22.png)

![Shipwreck reward ghosts 019](https://user-images.githubusercontent.com/43583994/157721058-2dbae4d0-09b5-428a-93ec-fb57d63d25b9.png)
![Shipwreck reward ghosts 020](https://user-images.githubusercontent.com/43583994/157721070-26ba9d5e-63b5-48d0-917e-fb05e1e0a1cc.png)

![Shipwreck reward ghosts 021](https://user-images.githubusercontent.com/43583994/157721082-297f2157-192a-486b-9c04-a2fe378e16ab.png)
![Shipwreck reward ghosts 022](https://user-images.githubusercontent.com/43583994/157721092-93134def-d403-49cb-8b39-b13bb95d05de.png)

![Shipwreck reward ghosts 023](https://user-images.githubusercontent.com/43583994/157721105-0acdd32a-774b-4282-ab53-b62a834fa9a3.png)
![Shipwreck reward ghosts 024](https://user-images.githubusercontent.com/43583994/157721116-a33c5bfd-dd6f-471a-b51c-fa33e6ce1a72.png)

![Shipwreck reward ghosts 025](https://user-images.githubusercontent.com/43583994/157721127-4f9b23e0-9d0b-4bab-9e0d-7480e338871d.png)
![Shipwreck reward ghosts 026](https://user-images.githubusercontent.com/43583994/157721138-3088571b-a286-490d-9008-7394e956411f.png)

![Shipwreck reward ghosts 027](https://user-images.githubusercontent.com/43583994/157721152-327d8b66-aaf9-4acd-aee7-a401a3d3f59e.png)
![Shipwreck reward ghosts 028](https://user-images.githubusercontent.com/43583994/157721164-e847ed69-d09a-4898-96e3-d12be5e2aa4c.png)

![Shipwreck reward ghosts 029](https://user-images.githubusercontent.com/43583994/157721186-5cb41488-e89a-4d9d-b3ff-21742d265328.png)
![Shipwreck reward ghosts 030](https://user-images.githubusercontent.com/43583994/157721192-71495545-4846-4d9a-9fe8-ed5ad282f11e.png)

Here is the test scenario file:
[0 9938.zip](https://github.com/ihhub/fheroes2/files/8225680/0.9938.zip)
