### ISSUE TITLE
Upgrade build system to CMake

### ISSUE THREAD

**Issue by alexbruy** [ihhub/fheroes2#512]
This will simplify configuration and building a lot. Now to build it from source I was forced to read all makefiles to figure out what it needed and which options to pass.

**Comment by ihhub** [comment]
Hi @alexbruy , what exact problem do you have with **makefile**? Did you follow Compilation instruction in [README.md](https://github.com/ihhub/fheroes2/blob/master/README.md#compilation) file?

**Comment by alexbruy** [comment]
Instructions in the README.md are not complete. At least on Linux running just `make` does not work. You need to pass additional options. Ideally there should not be a predefined `Makefile` instead either autotools or other build system should be used so user can configure build and only then run `make`.

**Comment by ihhub** [comment]
Hi @alexbruy ,
could you please tell what OS do you use and what errors do you receive by following steps in the instruction?

**Comment by alexbruy** [comment]
I tested on latest Ubuntu 18.04 with all dependencies installed. Running `make` fails early with the following message
```
make[2]: Entering directory '/devel/fheroes2/src/engine'
g++ -c -MD display.cpp  -O3  -Wall -Wextra -Wpedantic -Wconversion -Wsign-conversion -fsigned-char -DWITH_MIXER -DWITH_IMAGE -I/usr/include/libpng16 -DWITH_ZLIB -DWITH_TTF -DWITH_XML -DWITH_ZLIB -DWITH_ICONV
In file included from rect.h:30:0,
                 from surface.h:27,
                 from display.h:27,
                 from display.cpp:26:
types.h:26:10: fatal error: SDL.h: No such file or directory
 #include <SDL.h>
          ^~~~~~~
compilation terminated.
Makefile:13: recipe for target 'display.o' failed
```
As I said, I managed to build it but only after digging into all makefiles and construction quite long command line specifying necessary compilation options and flags.

Using proper build system will make it much-much easier. Of course, if your target is only Win this probably does not matter.

**Comment by ihhub** [comment]
Hi @alexbruy , did you run SDL installation script before the build?

**Comment by alexbruy** [comment]
See my previous comment

> with all dependencies installed

**Comment by ihhub** [comment]
2 days ago I compiled the project on a fresh Ubuntu 18.04. Correct me please about these steps after cloning the project:
```
./script/linux/install_sdl_1.sh
./script/demo/demo_linux.sh
make
```
Did you install SDL 1 or SDL 2?

**Comment by ihhub** [comment]
There is no a solid reason why we need to move the project to **CMake** as cmake introduces more dependencies in the development. Also we still support SDL 1 and SDL 2 so we have to have 2 ways for compilation.

As a conclusion, we can add cmake compilation not as a replacement of makefile but as a additional way of compilation.

**Comment by ihhub** [comment]
Closing this issue as the author is not responding anymore.

**Comment by alexbruy** [comment]
Most of the people have job and should work on their tasks during working hours. And weekends usually are their family time.

Don't know what made you think I'm asking to drop SDL 1.x and switch to SDL 2.x only. Don't know what made you think that CMake adds a dependency and why having quite obscure and non-standard way to configure build better than having easy to use and flexible build system.

Anyway, thanks for closing. Seems I better keep working on the test suite and campaign editor in my repo on Bitbucket than waste time on arguing and trying to make accepted any fixes/improvements here.

**Comment by ihhub** [comment]
Hi @alexbruy ,

before throwing personal tantrums to other people please consider reading the question properly: `Did you install SDL 1 or SDL 2?` It was a general question to find out a root of the problem. If you installed SDL 2 and ran the build without `WITH_SDL2` then most like it was the problem.

There was no mention about dropping some support of SDL 1 at all. I gave a detailed explanation why we keep it such way and why we do not have cmake support as well.
