### ISSUE TITLE
Text suggestions from recent PR

### ISSUE THREAD

**Issue by catadropa** [ihhub/fheroes2#5140]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

On PR #5081, I made some comments which weren't picked up until after the PR was merged. Creating an issue here as advised, to track those suggestions.

1. [First comment, line 794](https://github.com/ihhub/fheroes2/pull/5081/files/1e2ddb5533b51578c8948d3743bb7e74c1134f86#diff-12416991db2e725cff5940191fe9b00e96db71af67ea53e4724d6ed09d2933fd) -- is this true, will the monsters always run away or is it possible that they attack?
2. [Second comment, line 808](https://github.com/ihhub/fheroes2/pull/5081/files/1e2ddb5533b51578c8948d3743bb7e74c1134f86#diff-12416991db2e725cff5940191fe9b00e96db71af67ea53e4724d6ed09d2933fd) -- remove "always"? Or " will join your army if you ask."? But maybe this follows OG.
3. [Third comment, line 511](https://github.com/ihhub/fheroes2/pull/5081/files/1e2ddb5533b51578c8948d3743bb7e74c1134f86#diff-14a58fb744cf2a6f1030e616fb38bd64411b3dab4cbdda3a099e7b7062dd0811) -- swap amount/additional: better as "...will have %{amount} additional %{resource} at..."?
4. [Fourth comment, line 534](https://github.com/ihhub/fheroes2/pull/5081/files/1e2ddb5533b51578c8948d3743bb7e74c1134f86#diff-14a58fb744cf2a6f1030e616fb38bd64411b3dab4cbdda3a099e7b7062dd0811) -- Better as: "...will have +%{count} %{skill} at..."? (note +-sign)

### Describe the possible solution

Please review suggestions, thanks.

**Comment by zenseii** [comment]
I think these corrections sound good. For the second comment I think it would be more correct to say "Will always be willing to join your army.". Not sure where this message appears, might have to do with scouting on neutral armies.

**Comment by zenseii** [comment]
One addtion to this:
Spellbook written in one word in "Close spellbook" - should it also not be magic book?

**Comment by ihhub** [comment]
Most of things are addressed recently. Closing this pull request for now.
