### ISSUE TITLE
Popping sounds when using MP3 tracks

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#5141]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

This issue was first reported in this PR containing a discussion on it:
https://github.com/ihhub/fheroes2/pull/5137
I'm not getting this with neither ogg nor flac audio files.
It sounds like fire crackling.

https://user-images.githubusercontent.com/12501091/159126265-ca274f09-3df6-4f36-bd8d-312b69b451f5.mp4

### Save file

Seems to be more prevalent in castle themes, although you can hear it other places too.

### Additional info

Might need to put the volume a bit higher. As stated before these popping sounds don't appear if the files are played outside of fheroes2.

I'm using the non-expansion tracks.

**Comment by zenseii** [comment]
Actually listening to this with my speakers I don't hear the noise so I'm going to have to check on another PC to rule out that it's not specific to this PC.

**Comment by zenseii** [comment]
Just checked another PC with the same MP3 files and the same sounds can be heard there.

**Comment by ihhub** [comment]
Hi @zenseii , could you please also specify your OS? It is important to know as every OS has its own SDL implementation.

**Comment by zenseii** [comment]
Right sorry I forgot. My second PC has Windows 7. Used SDL2 latest snapshot release build. Still GOG supplied MP3 tracks.

**Comment by ihhub** [comment]
Hi @zenseii , what's the frequency of MP3 tracks?

**Comment by zenseii** [comment]
Hi @ihhub. It's 320 kbps and 48000 Hz.

**Comment by ihhub** [comment]
Hi @zenseii , did it help?

**Comment by zenseii** [comment]
Hi @ihhub. I just tested it and it does help. I can't hear these crackling noises.
Here's a recording with 22050 Hz.
https://user-images.githubusercontent.com/12501091/174477862-6ee7b248-e769-4fa8-80f5-368333894687.mp4

**Comment by ihhub** [comment]
I am closing this issue. The engine uses 22050 Hz frequency, setting it higher than 44100 Hz will result in such issues. Recommended frequency is 22050 Hz. We could state this somewhere in docs or in a wiki page.
