### ISSUE TITLE
Combat, AI behavior, AI Hydras should not move and attack all adjacent troops by staying in the same hexes (0.9.13)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#5144]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, AI Hydras should not move and attack all adjacent troops by staying in the same hexes.

In fheroes2:

![Hydras bad attack position 001](https://user-images.githubusercontent.com/43583994/159173951-8bc91c6b-316d-4b5c-aadc-f6651d4b7d03.png)

![Hydras bad attack position 002](https://user-images.githubusercontent.com/43583994/159173965-5e03bef2-7db8-4ea4-ad04-d58445b9f423.png)

https://youtu.be/F-lkeJvD9v0?t=15790

Related issue: https://github.com/ihhub/fheroes2/issues/4131.

### Save file

Not needed.

### Additional info

Version 0.9.13

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , could you please verify this issue? I believe this should be fixed by now.

**Comment by LeHerosInconnu** [comment]
@ihhub.

> Hi @LeHerosInconnu , could you please verify this issue? I believe this should be fixed by now.

I did some tests, it seems not to be the case anymore.
I'll keep an eye on it though. :)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu ,

Therefore I am closing this issue for now. Please feel free to reopen it if you notice the issue again.
