### ISSUE TITLE
Good/Evil interface bars are removed/covered up after playing the winning dragon animation

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#5145]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

After winning a scenario and after the Dragon breathing fire animation has played, the high score menu will show but in the background you can see that the interface bars have become black. This happens if the Dragon animation is played. Not having this animation in the ANIM folder shows the normal interface.

After Dragon animation:
![Free Heroes of Might and Magic II, version_ 0 9 13 20 03 2022 17 33 24](https://user-images.githubusercontent.com/12501091/159174405-946e6d48-bc67-4413-9cb1-b43df8d45d62.png)

No Dragon animation present in resources:
![Free Heroes of Might and Magic II, version_ 0 9 13 20 03 2022 17 58 51](https://user-images.githubusercontent.com/12501091/159174397-d34a4fe0-d4e0-46d3-ab98-b4fcf1be4ab4.png)

### Save file

I can upload a save from right before winning a scenario if necessary.

### Additional info

You need to use a higher resolution than 640x480 to notice this.

**Comment by ihhub** [comment]
Hi @zenseii , can you please upload a save file as I am unable to reproduce it?

**Comment by zenseii** [comment]
> Hi @zenseii , can you please upload a save file as I am unable to reproduce it?

That's because it has been fixed 👍
