### ISSUE TITLE
Bonus growth of "the week of" doubles only the number of troops, that were available the previous day

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#5153]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

I've noticed, that increased growth bonus haven't applied to one of my castles.
![image](https://user-images.githubusercontent.com/55348946/159474934-691e8fcd-7795-4edd-87ea-f7b59f2d5e33.png)
Previous week there were available 5 druids in one Sorceress castle, and now become:
![image](https://user-images.githubusercontent.com/55348946/159475083-8765f492-dbb3-4f2f-ac45-5432976d194a.png)
Another castle has available only standard growth:
![image](https://user-images.githubusercontent.com/55348946/159475212-68401576-282e-48b9-bc31-a091ee2dcfe9.png)

### Save file

[Fail week of Druids.zip](https://github.com/ihhub/fheroes2/files/8323890/Fail.week.of.Druids.zip)

**Comment by Branikolog** [comment]
Humm... While investigating the original behaviour I came up to conclusion, that in the OG the number of certain creatures is doubled considering all available creatures the previous day plus common weekly growth. 
Example: we had 5 druids the previous week. The next week it will be 20: (5available+5growth)x2
I have another concern regarding current implementation: in the original game only non-upgraded creatures can be doubled within "month/week of...".

**Comment by zenseii** [comment]
>  I have another concern regarding current implementation: in the original game only non-upgraded creatures can be doubled within "month/week of...".

Isn't that how it should be? I believe currently we distinguish between week of Druid and week of Mighty Druid. I don't think Mighty druids should increase if it's the week of Druid.

**Comment by Branikolog** [comment]
Hi, @zenseii !
That's why I'm concerning. :)
Currently in fheroes2 I had increased number of Greater Druids during the month of Druid, which isn't the case in the original game.
But on the other side we are able to hire non-upgraded druids...
