### ISSUE TITLE
Idle animation periodicity

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#516]
I think idle animation should play more frequently.

**Comment by shprotru** [comment]
In addition to this: in `fheroes2` idle animation sees random frame sequence(there are 2-4 for each unit). In OG it seems done without random - strictly defined sequence for frame sequences. What do you think, @Branikolog, am I right?

**Comment by Branikolog** [comment]
> In OG it seems done without random - strictly defined sequence for frame sequences. What do you think, @Branikolog, am I right?

Yes. In OG it seems to be about 8-9 seconds between each animation.
I don't think we should strictly do the same...
But our game has too much random in my opinion. It can be 2 animations in 8 seconds or 0 in 30...

**Comment by idshibanov** [comment]
@Branikolog  Every monster has his own Idle animation timer. For example ghost is 0, so he's always idle. After the recent animation changes we have the right data, it's just a matter of replacing current arbitrary value set in fheroes2 years ago. It is coming, I was just finishing up the music.

@shprotru In OG animation is random too - good example here would be ARCHER, look at his head movements. Main point here is that each animation has probability - so you see one of them more frequently, thus creating an illusion of "defined sequence".
