### ISSUE TITLE
High score does not list two equal high scores like the original game

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#5165]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Unless a high score is unique, it will not be listed (Both versions' player is called Unknown Hero):
Original game:
![Original](https://user-images.githubusercontent.com/12501091/159967351-f950292e-bd88-4c76-93df-0e9cb99b7bbf.png)

fheroes2 where two similar scores should show:
![fheroes2](https://user-images.githubusercontent.com/12501091/159968254-78a0b7d8-8e95-4dd1-8f58-05de4e4920cd.png)

I imagine we would want to list every high score created, even thinking of a case where you play the same map years in between and end up with the exact same score.

Also note that currently fheroes2 does not highlight new scores in yellow like OG. I've looked into solving this separately.

### Save file

I can provide a save file for fheroes2. For original game just press 911 to win immediately (by cheating).

**Comment by LeHerosInconnu** [comment]
Come on, I'm not a cheater. :rofl:
