### ISSUE TITLE
In Necromancer castle we must have an empty area instead of tavern building

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#52]
Necromancer castle has an empty space instead of tavern so it's incorrect to show black tile with "disable building" instead.

**Comment by bjauny** [comment]
I'm not sure about what needs to be done here. Should the tavern be rendered in grey scale or even completely disabled by calling `sprite_deny`?

**Comment by ihhub** [comment]
@bjauny what you could do if you have Windows. Download release (from Gihub releases)/compile this project. Download demo. Run demo with Necromancer race. Open castle and see that castle building has empty area while in this project it is some kind of tavern. I made initial research on this so I can attach my findings.

**Comment by bjauny** [comment]
I don't have a Windows install at hand to see the difference but I'll see what I can do. If you have a screenshot of the expected result it's perfect.

**Comment by ihhub** [comment]
Here is a screenshot of correct behavior:
![image](https://user-images.githubusercontent.com/19829520/66043976-1f331b00-e553-11e9-96db-0c9189f85112.png)

**Comment by bjauny** [comment]
Excellent! I'll work on this one.
