### ISSUE TITLE
Fullscreen in MacOS does not fill up to the top of the screen

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#5203]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

macOS

### Describe the bug

I'm reporting this from a supporter user "Hydd" from the Discord server. This animation they shared shows that the fullscreen does not reach the upper border of the screen, and therefore makes vertical panning upwards with the mouse cursor very inconvenient.
![giphy](https://user-images.githubusercontent.com/12501091/161694509-e26927dc-0b71-4235-93ef-36edeadbaaf0.gif)

I'll report back when the user replies what exact version of MacOS, fheroes2 build and resolution they're using. They first reported this on March 3rd.

### Save file

No save file, just try fullscreen.

**Comment by zenseii** [comment]
@oleg-derevenetz You're the expert on Mac here. Would you have any suggestions? Thank you!

**Comment by zenseii** [comment]
Here's some info:
macOS: 12.3.1
resolution: 960x600
fheroes2: 0.9.13 SDL2

**Comment by oleg-derevenetz** [comment]
Hi @zenseii I do not have exactly the same resolution in the list, but I have another with the same aspect ratio (1.6) - 840x525, and that's what happens on my macOS when toggling the full screen:

https://user-images.githubusercontent.com/32623900/161830677-d5fa228c-55ab-4749-b4a9-eda48a6e90d8.mp4

No issue is observed. I have no idea what's the "real" screen resolution of that user's macOS device is, but there may be black borders if aspect ratio of the "real" screen resolution doesn't match the in-game aspect ratio, like here (in-game resolution is 640x480):

https://user-images.githubusercontent.com/32623900/161831215-3d0835ee-1c27-4507-b9d1-49fbfb6dd398.mp4

So the user needs to choose the in-game aspect ratio to match the the "real" aspect ratio of the screen to avoid this issue.

**Comment by oleg-derevenetz** [comment]
Also if it's a relatively new MacBook with the notch on the top of the screen, this issue may be related to this notch (AFAIK it may be hidden or shown), but I have no device with this notch around to check this.

**Comment by zenseii** [comment]
Thanks for the replies @oleg-derevenetz . I have conveyed them to the user. @ihhub also speculated that a mouse locck could be the solution to go for here. That would be the same solution as the one used in the Windows version right now actually.

**Comment by oleg-derevenetz** [comment]
@zenseii AFAIK Windows just use "real" fullscreen mode (`SDL_WINDOW_FULLSCREEN`) while other OS use "lightweight" fullscreen mode (`SDL_WINDOW_FULLSCREEN_DESKTOP`). The first mode is slower, because resolution of the "real" screen is changed, but in this mode there is no "window" in the usual sense, and all mouse events are captured.

**Comment by zenseii** [comment]
Thanks for the insight @oleg-derevenetz ! The user reported that they do indeed have an M1 Mac with the notch so we will be able to test if this fix is valid for that as well.
