### ISSUE TITLE
Mention PoL original team in credits

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#5223]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

We need to mention all members of The Price of Loyalty original development team in credits.

### Describe the possible solution

Just add few more credits page in PoL add-on files are present.

**Comment by LeHerosInconnu** [comment]
For information, here are the missing screens:

Hello @ihhub,

Currently, the expansion credits are missing.

In Heroes 2 Gold:

Actual credits:

![Expansion credits 003](https://user-images.githubusercontent.com/43583994/142189079-3543e5e7-e891-4dc3-9e57-ec15487d8330.png)

Missing credits:

![Expansion credits 001](https://user-images.githubusercontent.com/43583994/142189122-27187ad2-e8fa-4a13-bfae-f6df45e0390e.png)

![Expansion credits 002](https://user-images.githubusercontent.com/43583994/142189132-a44967b7-8d14-414d-92ad-f498b38fd6c0.png)

_Originally posted by @LeHerosInconnu in https://github.com/ihhub/fheroes2/issues/1021#issuecomment-971476041_
