### ISSUE TITLE
Missing Gift button for other assets than English

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#5237]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

No other language assets have a generated gift button:
![image](https://user-images.githubusercontent.com/12501091/162635273-152f7a63-907a-49d4-ae76-3d7d17d078b6.png)

### Describe the possible solution

Generate a gift button. Same approach as for Battle Only button I'd imagine.

**Comment by zenseii** [comment]
I'll have a look at this one, but I need help to figure out what to call that button in German, French, Polish and Russian.

**Comment by zenseii** [comment]
From our French users on Discord the word "Donner" was proposed for the button.

**Comment by LeHerosInconnu** [comment]
Hello @zenseii,

> From our French users on Discord the word "Donner" was proposed for the button.

Wouldn't "DON" or "CADEAU" be more appropriate?

**Comment by zenseii** [comment]
> Hello @zenseii,
> 
> > From our French users on Discord the word "Donner" was proposed for the button.
> 
> Wouldn't "DON" or "CADEAU" be more appropriate?

Hi @LeHerosInconnu , better late than never to the party for this discussion 😅.

No one has complained since DONNER got implemented in April 😅 But the English word GIFT on the button is something we (or the previous team?) put there and it isn't the best word to use. It would be better to use SEND or DONATE probably.

Note that GIFT refers to the verb and not the noun "a gift". So "to gift someone resources". That's why the verb DONNER was chosen.

**Comment by LeHerosInconnu** [comment]
@zenseii.

> ... But the English word GIFT on the button is something we (or the previous team?) put there and it isn't the best word to use. It would be better to use SEND or DONATE probably.

I would choose "DONATE" or "GIVE". :)
