### ISSUE TITLE
Realign small monster sprites in battle results

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#5240]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Other

### Describe the bug

The sprites for the Defender and Attacker lines of battle casualties in battle results window need to be realigned, mostly further down. Right now the mohawk of the titans overlap with the "Defender" text when there's a single stack of them.

![image](https://user-images.githubusercontent.com/12501091/162636384-b7297430-da2e-4ca5-932c-2f592d1e6d9c.png)

### Save file

Just create a map with an army of lots of titans on a hero.

**Comment by zenseii** [comment]
> 

I had a couple of bugs lying around that I hadn't checked properly if and if they'd been reported, and @ihhub gave me the go to post them (not sure he knew how many they might be). Mostly UI stuff, though while reproducing the bugs I ended up finding some others I posted.

Anyhow. I'm not sure this window would need to be any bigger? What sort of text are you fancing? Most translations are well within the length of the text here.

**Comment by LeHerosInconnu** [comment]
@zenseii.

> I had a couple of bugs lying around that I hadn't checked properly if and if they'd been reported, and @ihhub gave me the go to post them (not sure he knew how many they might be). Mostly UI stuff, though while reproducing the bugs I ended up finding some others I posted.

;)

> Anyhow. I'm not sure this window would need to be any bigger? What sort of text are you fancing? Most translations are well within the length of the text here.

My concern was in the case of a longer hero name, but that seems fine.

In fheroes2:

![Victory window long name 01](https://user-images.githubusercontent.com/43583994/162753778-351a61e8-4302-412a-ac75-ed8c0413819c.png)
