### ISSUE TITLE
Show the 4 primary skill icons +1 for xanadu visit

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#5242]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Currently when visiting the xanadu and you are granted the primary skill bonus you only get a text which is not in line with the style of the rest of the game because there's no visual queue showing what you got.

![image](https://user-images.githubusercontent.com/12501091/162636660-d2f4347d-0c58-40c5-94de-8b9168d82ea2.png)

### Describe the possible solution

Maybe a stacked primary skill icon sort of like mass haste and a +1 next to it?

### Additional info

Visit the Xanadu and have a hero at least level 10 minus level of diplomacy.

**Comment by ihhub** [comment]
@zenseii , like this?
![image](https://user-images.githubusercontent.com/19829520/162691302-5be2af5b-8694-4d27-801e-92f910c058d0.png)

**Comment by zenseii** [comment]
> @zenseii , like this? ![image](https://user-images.githubusercontent.com/19829520/162691302-5be2af5b-8694-4d27-801e-92f910c058d0.png)

This looks good too. I was actually thinking about the smaller icons you see when visiting the arena. I'll show a quick edit in a sec.

**Comment by ihhub** [comment]
The problem is that other dialogs have icons which are shown in my screenshot.

**Comment by zenseii** [comment]
> The problem is that other dialogs have icons which are shown in my screenshot.

Right, then we can separate the 4 icons and have the informative dialog work for each of them, maybe in the same 2x2 alignment that you used..

**Comment by LeHerosInconnu** [comment]
Hello @zenseii and @ihhub,

I made a proposal here https://github.com/ihhub/fheroes2/discussions/4877 for a similar display as for the Arena window.

In my opinion, the four large icons would be a bit overwhelming in this case.

**Comment by zenseii** [comment]
Hi, everyone.

I realized that the small icons are only present with the Price of Loyalty expansion so I think it would be best to go for the larger icons. I've still think I need to see this dialog with the 640x480 game screen to know whether they are too large or not.

**Comment by ihhub** [comment]
We can use icons from Kingdom Summary window.

**Comment by zenseii** [comment]
> We can use icons from Kingdom Summary window.

Yep, they are perfect. This also makes them different enough from the arena icons to avoid the confusing we were talking about.

**Comment by ihhub** [comment]
![image](https://user-images.githubusercontent.com/19829520/192093873-26682128-f1f8-4a27-9209-399a80583fd9.png)

**Comment by zenseii** [comment]
Yes that looks good. I realized they are the same as for the arena but having all 4 icons makes the dialogs distinguishable.
An alternative is to have them in 2x2.
