### ISSUE TITLE
Adjustments to the Well max buy dialog

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#5243]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

The dialog for when you buy several creatures with the max function of the well should:

- [ ] Allow translations to choose where to put the number and how to write this phrase. Like writing `1 Giant` instead of `Giant - 1`
- [ ] Replace `-` with `:` . At first glance it could be misread as minus 1
i.e. `-1` even though that would make no sense.

![image](https://user-images.githubusercontent.com/12501091/162636926-c41e4f1f-b3df-433b-8c8b-7c3cba19552f.png)

### Describe the possible solution

This should just be a simple adjustment of the relevant dialog code.

**Comment by LeHerosInconnu** [comment]
Hello @zenseii,

Here, I suggest to change the yellow title to:

"Recruit Creatures"

Instead of:

"Buy Creatures"

I can open a new issue if necessary.

**Comment by zenseii** [comment]
> Hello @zenseii,
> 
> Here, I suggest to change the yellow title to:
> 
> "Recruit Creatures"
> 
> Instead of:
> 
> "Buy Creatures"
> 
> I can open a new issue if necessary.

I already did so in the PR I just made 😎 I forgot to mention that I thought this header should be changed...

Since it's a Yes/No dialog I changed it to a question : "Recruit these troops?".

![image](https://user-images.githubusercontent.com/12501091/168481561-f9469150-3c96-4ebc-a3c0-3d12a27f4f39.png)

**Comment by LeHerosInconnu** [comment]
@zenseii.

Nice. :)

> > Hello @zenseii,
> > Here, I suggest to change the yellow title to:
> > "Recruit Creatures"
> > Instead of:
> > "Buy Creatures"
> > I can open a new issue if necessary.
> 
> I already did so in the PR I just made sunglasses I forgot to mention that I thought this header should be changed...
> 
> Since it's a Yes/No dialog I changed it to a question : "Recruit these troops?".
> 
> ![image](https://user-images.githubusercontent.com/12501091/168481561-f9469150-3c96-4ebc-a3c0-3d12a27f4f39.png)

Wouldn't it be better to put the same yellow title for all windows:

"Recruit Creatures"

The question can be added below:

"Recruit Creatures"

"Do you want to recruit these creatures?"

From original game:

![Recruit on map 002](https://user-images.githubusercontent.com/43583994/168482328-772d4cac-870d-420a-8b63-b59645eac9c7.png)

**Comment by zenseii** [comment]
> Wouldn't it be better to put the same yellow title for all windows:
> 
> "Recruit Creatures"
> 
> The question can be added below:
> 
> "Recruit Creatures"
> 
> "Do you want to recruit these creatures?"

Yes that would be probably be better. Not sure if we want to add any extra text since this dialog could end up getting very long:

![image](https://user-images.githubusercontent.com/12501091/168482653-542d96a3-049c-41ae-9b1d-7c7fc0127877.png)


I did have some other idea about showing what creatures you could potentially recruit if you have enough room, but I'm not sure this is really necessary.

**Comment by LeHerosInconnu** [comment]
@zenseii.

> > Wouldn't it be better to put the same yellow title for all windows:
> > "Recruit Creatures"
> > The question can be added below:
> > "Recruit Creatures"
> > "Do you want to recruit these creatures?"
> 
> Yes that would be probably be better. Not sure if we want to add any extra text since this dialog could end up getting very long:
> 
> ![image](https://user-images.githubusercontent.com/12501091/168482750-30362c20-c6e8-419d-a89d-8095f27fcace.png)

For me, it's okay with just the yellow title without the question.

> I did have some other idea about showing what creatures you could potentially recruit if you have enough room, but I'm not sure this is really necessary.

I think it's okay for this issue for now, the rest could be proposed later.
I have some suggestions myself. :)

Related issues: https://github.com/ihhub/fheroes2/issues/1798, https://github.com/ihhub/fheroes2/issues/2093.
