### ISSUE TITLE
Windows: Embedding/locking fheroes2 to a side with DPI higher than 100% breaks fullscreen

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#5250]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

When locking the game window to either side by using Windows Key + Left or Right Arrow, and then enter fullscreen breaks the window and it's not able to decide where to go and sometimes the window goes black. I'm on Windows 10. Resolution 1920x1080.

<details>
<summary>Locked to left half:</summary>

![before](https://user-images.githubusercontent.com/12501091/162645974-497ae898-1000-4172-be4f-acada20c628d.png)
</details>

<details>
<summary>After pressing F4:</summary>

![after](https://user-images.githubusercontent.com/12501091/162646270-2b1e308a-19f0-4ad9-8298-a7f2872dc92d.png)

</details>

### Describe the possible solution

This is really low priority since there's not much reason to do this, but it's slightly related to the recent works on fullscreen mode.

### Additional info

Relevant discussion here: https://github.com/ihhub/fheroes2/pull/5209#issuecomment-1093628659

**Comment by oleg-derevenetz** [comment]
Hi @zenseii is this issue still observed on the latest snapshot? I tried to reproduce it on the Windows 10 machine but no luck - everything seems to work properly.

**Comment by zenseii** [comment]
Hi @oleg-derevenetz ! Thanks for checking this. I realized that I have to set another resolution than 1920x1080 (my screen's native resolution) for this to happen. If it set it to 1920x1080 it works fine indeed.

**Comment by oleg-derevenetz** [comment]
@zenseii I tried with 640x480 and was not able to reproduce this. With what resolution exactly is this observed in your case?

**Comment by zenseii** [comment]
@oleg-derevenetz It happens with any resolution lower than native actually. I'm trying to see if there is anything else causing it.

**Comment by zenseii** [comment]
I tested some more resolutions now. 1680x1050 behaves sort of as it should but has some other issues. 1400x1050 behaves as it should, while for example 1600x900 gets the glitching.

**Comment by zenseii** [comment]
Hi @oleg-derevenetz ! Here's a vid I made trying to show the various things. Do not pay attention to the misalignment of the active part of the window in 1680x1050, that is only present in the recording and is due to the recording software (OBS in this case).

https://user-images.githubusercontent.com/12501091/164565679-6d87c325-03d3-415a-9051-042f198b06d7.mp4

Had to be quick to make it fit within the allowed 10MB.

**Comment by oleg-derevenetz** [comment]
Hi @zenseii No luck so far in reproducing this issue :( My native screen resolution is also 1920x1080 and here is the video (recorded by the OBS Studio as well) for in-game resolution 1600x900 (I downscaled it to fit the 10MB GitHub video limit):

https://user-images.githubusercontent.com/32623900/164704354-2e808175-6b4f-4712-8ea0-03481a30e95d.mp4

No glitches so far. I also tested a few other resolutions, no glitches as well. Are you sure you are running the latest snapshot build?

**Comment by zenseii** [comment]
@oleg-derevenetz I'm testing the latest snapshot build downloaded from directly from here, but I'm always grabbing and using latest commits using github desktop, so I would be surprised if this were the issue. I'm more inclined to it being due to my graphics drivers or of that sort. I have an Nvidia gpu along with an integrated intel gpu. I've run fheroes2 with both and get the issue with both.

**Comment by oleg-derevenetz** [comment]
@zenseii I had an impression that this issue may be as well related to the #5209, because before that PR the order of switching off the fullscreen mode and updating the window size was wrong. But maybe it is related to something else - I have no idea what yet, because I can't reproduce this.

**Comment by zenseii** [comment]
I found the source of the issue. It's the DPI settings. I had them at 125% and tried setting them to 100% and fullscreening works from any resolution when embedded to the side.

I realized it from testing my other win 10 PC and got the same problem just with more resolution since I use 150% there (connected to TV).

**Comment by zenseii** [comment]
> > I found the source of the issue. It's the DPI settings. I had them at 125% and tried setting them to 100% and fullscreening works from any resolution when embedded to the side.
> 
> Hmm, then it looks like an SDL issue (or Windows itself). As I understand, this issue is not observed when window is not "docked"?

Exactly, it is only when the Window is docked beforehand. I also believe it is an issue inherent to SDL's fullscreening. At least we know the cause in case a user reports it. Although reducing the DPI is not an option for me, 125% is even the recommended according to Windows for my setup I imagine.

**Comment by zenseii** [comment]
This doesn't seem to be an issue on the current latest snapshot build, as I've tested it on a Win 8 PC with general DPI set to 125% and then docking fheroes2 before fullscreening it.

I don't have a Win 10 PC available but if someone could test that then that'd be great.

Maybe it's related to https://github.com/ihhub/fheroes2/pull/6206 ?

**Comment by oleg-derevenetz** [comment]
> I don't have a Win 10 PC available but if someone could test that then that'd be great.

No, on Windows 10 this still works wrong if DPI is not 100%.

**Comment by zenseii** [comment]
Did any of you test this on Win 10 with the above PR?

**Comment by ihhub** [comment]
I did.
