### ISSUE TITLE
Troop upgrade windows, gold amount and the gold sprite are missing in these windows

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#5260]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the gold amount and the gold sprite are missing in these windows.

In original game:

![Display gold cost 03](https://user-images.githubusercontent.com/43583994/162740638-07b56682-1efd-4402-972f-2da921853018.png)

![Display gold cost 02](https://user-images.githubusercontent.com/43583994/162740624-f7078fd1-90f1-44ad-ae68-156f5dcd6be4.png)

In fheroes2:

![Display gold cost 01](https://user-images.githubusercontent.com/43583994/162740715-0c16234d-73d9-4d53-80af-fc312e618f97.png)

### Save file

Not needed.

### Additional info

Version 0.9.13 5171

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , this issue is not present in 0.9.14 version.
