### ISSUE TITLE
Opening High Scores after exiting from campaign scenario selection opens name entry prompt dialog

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#5269]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

If you exit from the scenario selection window of a campaign (with the awards and bonus etc) to the main menu, and then open up the high scores, you will get the dialog for name entry.

![image](https://user-images.githubusercontent.com/12501091/163059073-9c03248e-1525-4e9a-a0cd-2c8c33129f85.png)

### Save file

Just load up any campaign's complete save file.
[Good_1_Complete.zip](https://github.com/ihhub/fheroes2/files/8476750/Good_1_Complete.zip)

**Comment by ihhub** [comment]
This is not reproducible anymore on the latest version.
