### ISSUE TITLE
Application crash on opening game map

### ISSUE THREAD

**Issue by Killbrum** [ihhub/fheroes2#5274]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Application (game) crashes when you try to start a new game and select "Dead Dragons" map (XL). You are able to pre-select game settings, but while you press "Okay" and load the map -> application crashes. Unfortunately, I have no installed Visual Studio to debug it on my computer.

Reproducibility 10/10
Windows 10

### Save file

No saves. Just start a new game and observe crash

**Comment by zenseii** [comment]
Just tested this on latest snapshot build, along with every other original map from GOG, and none of them crash.

This was probably caused by the same reason Colossal Cavern crashed because of two spell books on a hero. This was fixed by PR got merged https://github.com/ihhub/fheroes2/pull/5254.

@Killbrum did you test the latest fheroes2 snapshot?

**Comment by Killbrum** [comment]
Well, as I see artifacts uploading is disabled for about 3 weeks. I don't see any place where I can get the latest snapshot

**Comment by zenseii** [comment]
Hmm it's a bit harder to find now but if you go via the pr page of the latest commit you can find the workflow artifacts/builds which are the snapshots for various systems: https://github.com/ihhub/fheroes2/actions/runs/2168027354

Just scroll down.

**Comment by ihhub** [comment]
@Killbrum , all latest snapshots are in place: https://github.com/ihhub/fheroes2/releases

**Comment by Killbrum** [comment]
Still, I don't see any available artifacts related to Windows platform placed under any workflow.

@ihhub I assume that you gave a link to releases, not nightly/incremental snapshots

So, as a bottom line. The issue is reproducible on my PC and 0.9.14 build

**Comment by ihhub** [comment]
@Killbrum , please follow the instructions from [here](https://github.com/ihhub/fheroes2/blob/master/docs/INSTALL.md).

**Comment by Killbrum** [comment]
Great. The latest build fixes this issue. Thanks for your patience
