### ISSUE TITLE
Flatpak/Flathub

### ISSUE THREAD

**Issue by Mr-Bajs** [ihhub/fheroes2#5276]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Is there any plans to make fheroes II available as an Flatpak on Flathub?
It would be great if so, that's all.

**Comment by oleg-derevenetz** [comment]
Hi @Mr-Bajs we need maintainers for this. If you regularly use this app store, you can become a maintainer yourself and benefit other users.

**Comment by Mr-Bajs** [comment]
> Hi @Mr-Bajs we need maintainers for this. If you regularly use this app store, you can become a maintainer yourself and benefit other users.

I'm not qualified for that though, can't code a least bit. Trying to figure out all this Github, i'll might contribute with translation to Swedish, i'll need to start learning this Githubing first.

**Comment by Laserlicht** [comment]
Hi,

I tried to create a Flatpak-Package: https://github.com/flathub/flathub/pull/3114

But there are some things that should be fixed in the codebase here:
* Is it possible to add and install the metainfo here? https://github.com/Laserlicht/flathub/blob/75a3546f6daf239d1f910c8694b3e1513de94b3a/io.github.fheroes2.metainfo.xml
* The Desktop-File should be installed https://github.com/flathub/flathub/pull/3114#discussion_r867426107
* The Icon-File should be installed https://github.com/flathub/flathub/pull/3114#discussion_r867426639
* If it possible to fix this workaround: https://github.com/Laserlicht/flathub/blob/75a3546f6daf239d1f910c8694b3e1513de94b3a/io.github.fheroes2.yaml#L16 (more Info here: https://github.com/bvschaik/julius/issues/27 and here: https://github.com/flatpak/freedesktop-sdk-images/issues/83 )

**Comment by Crono141** [comment]
Got my steamdeck coming soon, and would love to have this as a flatpack, vs installing GOG version via lutris.  Its a much smoother experience on desktop.

**Comment by Laserlicht** [comment]
fheroes2 is on flathub now: https://flathub.org/apps/details/io.github.ihhub.Fheroes2

When version 0.9.16 is released, then I only need to reference the appdata.xml in this repo once in the flatpak package.

**Comment by Crono141** [comment]
I just installed on my deck, and moved/simlinked the files from my heroes 2 GOG install (via lutris), but the app refuses to run, saying to copy the files/folder to the ~/.var/app/io.github.ihhub.Fheroes2/data/fheroes2 directory.  There was a folder inside of that called "files".  I tried putting them in that folder as well and still had no joy.  Thoughts?

**Comment by Laserlicht** [comment]
Hi @Crono141

The folders must be look like:
- ~/.var/app/io.github.ihhub.Fheroes2/data/fheroes2/DATA
- ~/.var/app/io.github.ihhub.Fheroes2/data/fheroes2/MAPS
- ...

**Comment by Crono141** [comment]
Thanks.  It seems Fheroes2 doesn't like symlinks.  Copying the data
directly solved the issue.

**Comment by Laserlicht** [comment]
Symlinks probably cause problems because of the flatpak sandbox. Since the target is located at a folder where the application has no rights.

**Comment by novasheikh** [comment]
> Hi @Crono141
> 
> The folders must be look like:
> 
> * ~/.var/app/io.github.ihhub.Fheroes2/data/fheroes2/DATA
> * ~/.var/app/io.github.ihhub.Fheroes2/data/fheroes2/MAPS
> * ...
> 
> I have added some examples to the hint window. So that it is understandable.
> 
> On my deck it's working this way.

My Deck won't let me create the data folder in this subdirectory. Am I missing something?

**Comment by Laserlicht** [comment]
Do you use the "Open folder"?
(see here: https://github.com/ihhub/fheroes2/pull/5434#issuecomment-1146814097 )

In this folder you have to copy the DATA, MAPS, etc. folder.

What's your error?

**Comment by novasheikh** [comment]
> @novasheikh Do you use the "Open folder"? (see here: [#5434 (comment)](https://github.com/ihhub/fheroes2/pull/5434#issuecomment-1146814097) )
> 
> In this folder you have to copy the DATA, MAPS, etc. folder.
> 
> What's your error?
> 
> It works for me without any problems. Installed with "Discover".
> 
> After everything works best to include as a steam foreign game.
> 
>  Peek.2022-06-10.20-28.mp4

THANKS! You were able to help me fix the issues. Great video tutorial

**Comment by Laserlicht** [comment]
Can be closed. It's on Flathub now...

**Comment by Laserlicht** [comment]
For Information: Here are download statistics for Flatpak: https://klausenbusk.github.io/flathub-stats/#ref=io.github.ihhub.Fheroes2
