### ISSUE TITLE
Properly generate MIN button for other assets than English

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#5284]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Currently the MIN button used in places like recruit dialogs is only correctly generated for English and German assets:

Italian:
![image](https://user-images.githubusercontent.com/12501091/163677236-c39dc57f-654e-47c1-be5f-5b091242d089.png)
French:
![image](https://user-images.githubusercontent.com/12501091/163677265-14f09a40-4c36-4c21-95f7-35adb0b65096.png)
Polish:
![image](https://user-images.githubusercontent.com/12501091/163677286-3067b910-ff72-46f8-af75-2a36418b7069.png)

The fact that it's generated correctly for German assets is probably due to the English and German assets having overlap, sort of coincidentally.

### Describe the possible solution

Generate the MIN button properly for the supported assets.

**Comment by Alucard648** [comment]
Russian translation also suffers from this problem.

**Comment by zenseii** [comment]
Hi @ihhub !

I believe this issue should have been closed after this PR https://github.com/ihhub/fheroes2/pull/5815 ? 😊

**Comment by ihhub** [comment]
Yes!
