### ISSUE TITLE
Windows Size

### ISSUE THREAD

**Issue by Valhallle** [ihhub/fheroes2#5293]
### Your question

Hello, 

I've just installed the FHeroes 2 with GOG full game.
But when I want to play the game, the windows is too big:

When I'm on windowed mode, no matter the resolution I choose, the windows heigh it too big, and I can't see the bottom of the windows.
In fullscreen, the game is on 16:9 size, but it's cropped on the side + bottom too. 

I'm on Windows 11, and my monitor is a 32:9 5120*1440p resolution
The resolution I can choose are: 
5120 x1440p (WAY)too big on side + bottom)
1920x1440 (WAY too big on bottom)
1920x1200 (too big on bottom)
1600x1200 (too big on bottom)

There is any way to fix it ? Like manual windows resize ? Or manual resolution ?

**Comment by ihhub** [comment]
Hi @Valhallle , the recommended resolution for the game is 800x600 or 1024x768 or similar one for your wide-screen monitor. Most likely you chose too high resolution. To play in full screen just press F4. You can also manually resize the window if you are using SDL 2 version of the game.
Also please provide the screenshot of resolution window within the game.

**Comment by Valhallle** [comment]
https://i.imgur.com/VlwRC2v.png

Here's the resolution windows.
But I just installed with SL2, didn't saw it at first. It seems to work with the resize !

**Comment by ihhub** [comment]
Looks like something is really wrong with retrieving resolutions.

**Comment by ihhub** [comment]
Hi @Valhallle , please try the latest snapshot to verify that the issue is fixed for you.
