### ISSUE TITLE
Adventure map, hero should be able to cast the Dimension Door, Town Gate and Town Portal spells if he still has movement points

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#5303]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the hero should be able to cast the Dimension Door, Town Gate and Town Portal spells if he still has movement points.

In fheroes2:

![Not enough move points 001](https://user-images.githubusercontent.com/43583994/164056020-5ea4c863-3921-4376-9d2d-3efc54f950e2.png)

![Not enough move points 002](https://user-images.githubusercontent.com/43583994/164056035-d14fa740-cf6c-40be-9177-12c48d462802.png)

![Not enough move points 003](https://user-images.githubusercontent.com/43583994/164056048-009a0ab0-0f72-49fe-b76d-37d0d4ddf3da.png)

![Not enough move points 004](https://user-images.githubusercontent.com/43583994/164056061-dfc2a6e4-8a39-465e-ae6b-c873227eeeab.png)

### Save file

Here are the save files:
[Not enough move town portal 01.zip](https://github.com/ihhub/fheroes2/files/8514923/Not.enough.move.town.portal.01.zip)

### Additional info

Related issue:https://github.com/ihhub/fheroes2/issues/3903.

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu according to my tests, hero should be able to cast spells that consume movement points not when he still have movement points, but when he have enough movement points to move over his current tile. For example, he will not be able to cast those spells on grass with 50MP, but will be able to do this with 100MP.

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> Hi @LeHerosInconnu according to my tests, hero should be able to cast spells that consume movement points not when he still has movement points, but when he has enough movement points to move over his current tile. For example, he will not be able to cast those spells on grass with 50MP, but will be able to do this with 100MP.

In the original game, the hero can use these spells as long as he has movement points left, even if he cannot move on the terrain he is located on.
I don't know if there is a low limit to this number of movement points left in the original game, and on [this site](https://handbookhmm.ru/2-logistics) it says that the hero can use the spells as long as he has at least 0001 movement points left.

In original game:

![No move but dimension door 001](https://user-images.githubusercontent.com/43583994/164451925-bed23262-d6f1-44f1-a563-562dc950cc5c.png)
![No move but dimension door 002](https://user-images.githubusercontent.com/43583994/164451940-6ce4d6a1-041a-46cc-94dd-91df37097be3.png)

![No move but dimension door 003](https://user-images.githubusercontent.com/43583994/164451954-cdcc0a12-3d99-4850-b354-f6ceaaae660a.png)
![No move but dimension door 004](https://user-images.githubusercontent.com/43583994/164451965-5cac397f-0b9b-4e46-8a85-0b8a9df5f268.png)

Here are the save files:
[No move but dimension door 01.zip](https://github.com/ihhub/fheroes2/files/8530663/No.move.but.dimension.door.01.zip)

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu

>In the original game, the hero can use these spells as long as he has movement points left, even if he cannot move on the terrain he is located on.
>I don't know if there is a low limit to this number of movement points left in the original game, and on [this site](https://handbookhmm.ru/2-logistics) it says that the hero can use the spells as long as he has at least 0001 movement points left.

I'm not sure about that. Consider:

![1](https://user-images.githubusercontent.com/32623900/164496519-aa81b213-a32e-457b-b735-4b46a5427f1b.jpg)

Here the hero can make 14 movements on the grass in the straight direction (so he has at least 1400MP, but less than 1500MP), and at the end of his path he is unable to cast DD:

![5](https://user-images.githubusercontent.com/32623900/164497332-2679ed45-c499-489e-ab11-ea8b6d15b409.jpg)

Lest' alter his path a bit:

![2](https://user-images.githubusercontent.com/32623900/164497421-b95661e7-1d2f-45f8-827f-475d3aed24d4.jpg)
![3](https://user-images.githubusercontent.com/32623900/164497441-0ac25a9f-a0c8-484a-a8f5-991b22b6b27d.jpg)

This path takes 150 + 12 * 100 = 1350MP, he should have had at least 50MP left, right? But...

![4](https://user-images.githubusercontent.com/32623900/164498157-423e2d84-ffcb-4a07-b49e-05cb186dec4a.jpg)

He is still unable to use DD after that.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

If you look carefully at my screenshots you will notice that my heroes still have a yellow part (1 pixel and 2 pixels high respectively) in their movement indicator (although they can't move "on horseback" from the terrain where they are located).
While in your screenshots, their movement indicator is completely "empty".

It would be necessary to determine what is the minimum value needed to use these spells in the original game code (what value allows to have still a yellow pixel high in the hero movement indicator).

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu

> If you look carefully at my screenshots you will notice that my heroes still have a yellow part (1 pixel and 2 pixels high respectively) in their movement indicator (although they can't move "on horseback" from the terrain where they are located).
While in your screenshots, their movement indicator is completely "empty".

I remember there were discussions regarding this yellow bar. I don't know how it works exactly in OG, but in fheroes2 it will be shown as empty even if there are some movement points left, but hero can't make a step over the current terrain (you can notice that by using Stone Liths - this yellow bar can hide and appear again depending on the type of terrain on which Stone Liths are located). It looks like at least SOMETIMES this logic works in the OG as well. What I want to demonstrate is that DD (and other similar spells) doesn't work even if the hero still has some movement points, but is not able to make a step from his tile. So he definitely should have more than 1MP (and even 50 MP is not enough) :)

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> @LeHerosInconnu
> 
> > If you look carefully at my screenshots you will notice that my heroes still have a yellow part (1 pixel and 2 pixels high respectively) in their movement indicator (although they can't move "on horseback" from the terrain where they are located).
> > While in your screenshots, their movement indicator is completely "empty".
> 
> I remember there were discussions regarding this yellow bar. I don't know how it works exactly in OG, but in fheroes2 it will be shown as empty even if there are some movement points left, but hero can't make a step over the current terrain (you can notice that by using Stone Liths - this yellow bar can hide and appear again depending on the type of terrain on which Stone Liths are located). It looks like at least SOMETIMES this logic works in the OG as well. What I want to demonstrate is that DD (and other similar spells) doesn't work even if the hero still has some movement points, but is not able to make a step from his tile. So he definitely should have more than 1MP (and even 50 MP is not enough) :)

The problem is that in Heroes 2, the hero can use these spells even if he can't move "on horseback" from the square where he is located and this is not possible in fheroes2, which should be fixed. :)

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu

> The problem is that in Heroes 2, the hero can use these spells even if he can't move "on horseback" from the square where he is located and this is not possible in fheroes2, which should be fixed. :)

Since nobody knows how exactly it should be fixed (because, as you can see, sometimes hero is able to cast these spells and sometimes not, and exact rules of this are not obvious), I propose to postpone this until there is clarity on this issue.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> @LeHerosInconnu
> 
> > The problem is that in Heroes 2, the hero can use these spells even if he can't move "on horseback" from the square where he is located and this is not possible in fheroes2, which should be fixed. :)
> 
> Since nobody knows how exactly it should be fixed (because, as you can see, sometimes hero is able to cast these spells and sometimes not, and exact rules of this are not obvious), I propose to postpone this until there is clarity on this issue. In the current implementation, the rules are simple: no movement - no cast :)

I observed (I have just made a test) the problem of the hero's movement indicator according to the terrain type on which is located the Stone Liths in fheroes2.
This is not a correct way to make the game work in my opinion.

The use of these spells should not be dependent on the type of terrain the hero is located on (if he can move or not), but on a minimum number of movement points allowing their use.
So the solution is to discover to what value of movement points corresponds a pixel high in the hero's movement indicator in Heroes 2. ;)

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu

> I observed (I have just made a test) the problem of the hero's movement indicator according to the terrain type on which is located the Stone Liths in fheroes2.

This is not a problem, this is an intended behavior :) If the hero is not able to move over his current tile in any direction, then the movement indicator should be empty. Otherwise, the player may have questions about why he can't move a hero, despite the hero's movement indicator isn't empty.

> So the solution is to discover to what value of movement points corresponds a pixel high in the hero's movement indicator in Heroes 2. ;)

Maybe :)

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> @LeHerosInconnu
> 
> > I observed (I have just made a test) the problem of the hero's movement indicator according to the terrain type on which is located the Stone Liths in fheroes2.
> 
> This is not a problem, this is an intended behavior :) If a hero is not able to move over his current tile in any direction, then the movement indicator should be empty. Otherwise, the player may have questions about why he can't move a hero, despite the hero's movement indicator isn't empty.
> 
> > So the solution is to discover to what value of movement points corresponds a pixel high in the hero's movement indicator in Heroes 2. ;)
> 
> Maybe :)

So we have to make sure that the yellow bar is only displayed when the hero knows one of these spells and can use it even if he can't move "on horseback" because of the terrain type.
This would be an improvement over the original game (where the hero can't move "on horseback" and part of the hero's movement indicator is still visible).

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu & @oleg-derevenetz 

> So we have to make sure that the yellow bar is only displayed when the hero knows one of these spells and can use it even if he can't move "on horseback" because of the terrain type.

So players could still be confused, why do they have yellow bar but couldn't move...

As far as I know in H3 there's a workaround for such situations, when hero has some movement points, but couldn't make a step due to movement penalty: game shows a little part of yellow bar, but when hero initiates any movement, it disappears, setting movement counter to 0. Like hero makes an attempt to move, but didn't succeed. 
We can use a combination of these two mechanics: in a case hero has teleportation spells show a little bit of yellow movement bar, but reset it, in a case player tries not to cast a spell, but to move somewhere.

But in my personal opinion, I'd prefer to make "Dimension Door" spell unavailable, in a case player has not enough movement points to cast it.

**Comment by zenseii** [comment]
> Hi, @LeHerosInconnu & @oleg-derevenetz
> 
> > So we have to make sure that the yellow bar is only displayed when the hero knows one of these spells and can use it even if he can't move "on horseback" because of the terrain type.
> 
> So players could still be confused, why do they have yellow bar but couldn't move...
> 
> As far as I know in H3 there's a workaround for such situations, when hero has some movement points, but couldn't make a step due to movement penalty: game shows a little part of yellow bar, but when hero initiates any movement, it disappears, setting movement counter to 0. Like hero makes an attempt to move, but didn't succeed. We can use a combination of these two mechanics: in a case hero has teleportation spells show a little bit of yellow movement bar, but reset it, in a case player tries not to cast a spell, but to move somewhere.
> 
> But in my personal opinion, I'd prefer to make "Dimension Door" spell unavailable, in a case player has not enough movement points to cast it.

I agree with these points and that the way it works in the original game is not logical nor intuitive. I believe the "error" message you get when trying to cast it should be the basis for the logic, which currently says something like "not enough movement points". I think that is simple and easy to understand for a player instead of having to take lots of factors into consideration like a movement point threshold based on a magical number between 50-75 and what terrain type they're on etc.

**Comment by oleg-derevenetz** [comment]
> But in my personal opinion, I'd prefer to make "Dimension Door" spell unavailable, in a case player has not enough movement points to cast it.

That's how in fact it currently works - it is grayed out in the spellbook. The question is how many movement points it in fact requires. It is certainly not 1MP like stated in that article, so for simplicity the rule "hero cannot move - hero cannot cast" is currently used. This may change in future when there will be a clarity in this regard.

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz, @Branikolog and @zenseii,

So I checked the heroes' movement points with this savegame editor: [HoMM 2 Save Editor](https://www.celestialheavens.com/forum/7/16791).

With the first save file (7747 no move but dimension door.GM1), Ariel, with 1 yellow pixel high in its movement indicator, has "76" movement points left.
![Save Editor 001](https://user-images.githubusercontent.com/43583994/164726290-3711870e-d7cf-419c-b8d6-27e7ca774750.png)

With the first save file (7748 no move but dimension door.GM1), Gem, with 2 yellow pixels high in its movement indicator, has "163" movement points left.
![Save Editor 002](https://user-images.githubusercontent.com/43583994/164726326-68968409-bd5a-4a00-bc6f-b8d8c786e8e6.png)

I changed Ariel's remaining movement points to "69" (which is a good value) :) and with this value, the yellow bar of the hero's movement indicator is 1 pixel high, and Ariel can still use the Dimension Door spell.
With the value "68", the hero's movement indicator is empty and Ariel cannot use the spell.

I changed Gem's remaining movement points to "137" and with this value, the yellow bar of the hero's movement indicator is 2 pixels high, and Ariel can still use the Dimension Door spell.
With the value "136", the hero's movement indicator is only 1 yellow pixel high, and Ariel can still use the Dimension Door spell.

We can deduce that the value of 1 pixel high in the hero's movement indicator is between "68" and "69" (137 / 2 = 68,5).

This value would correspond to "68.181818..." referring to the indications given on [this site](https://handbookhmm.ru/2-logistics) (in the case of 1500 / 22 = 68.181818...), "22" being the height in pixels of the full yellow bar of the hero's movement indicator.

"4. Visual display of the current power reserve
The amount of MP of the hero is displayed on the main screen in the column to the left of the hero's face in yellow:
Full column: 1500 - 1568 MP
Full column c "+": 1569 - 1840 MP
Full column c "++": 1841 - 2113 MP
Full column c "+++": 2114 MP or more."

What we could do is to set this value of "69" as the minimum value to allow Dimension Door, Town Gate and Town Portal spells.
This could be indicated to the player by a red movement bar when the hero can use one of the spells to "move" without the hero being able to move "on horseback" on the terrain where he is located.
The red color here corresponds to the color of the adventure spell bookmark in the hero's Magic Book.

In this way, the original gameplay is preserved for the enjoyment of experienced players who know the game well and are used to using this feature of the game. :)

Also, this will have to be specified in the future game manual of fheroes2, thanks to @Branikolog. :)

**Comment by Branikolog** [comment]
Nice investigation, @LeHerosInconnu !
Currently, in fheroes2 "Dimension Door" spell consumes 225 movement points. Dose it means, that in a case hero has less than 225, but more than 68 movement points he still would be able to cast the spell? Or fheroes2 simply has wrong value for movement points cost?

**Comment by oleg-derevenetz** [comment]
Hi all,

> What we could do is to set this value of "69" as the minimum value to allow Dimension Door, Town Gate and Town Portal spells.

This part is implemented in #5314.

> This could be indicated to the player by a red movement bar when the hero can use one of the spells to "move" without the hero being able to move "on horseback" on the terrain where he is located.

This part is yet to be implemented in future. I suggest to open a separate issue regarding this improvement. @LeHerosInconnu what do you think?

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz and @Branikolog,

> Nice investigation, @LeHerosInconnu !

Thanks! :)

> Currently, in fheroes2 "Dimension Door" spell consumes 225 movement points. Dose it means, that in a case hero has less than 225, but more than 68 movement points he still would be able to cast the spell? Or fheroes2 simply has wrong value for movement points cost?

Yes, 225 movement points is the correct value for the use of each of these spells and is currently used in fheroes2.
And yes, more than 68 movement points should allow the hero to use these spells.

> Hi all,
> 
> > What we could do is to set this value of "69" as the minimum value to allow Dimension Door, Town Gate and Town Portal spells.
> 
> This part is implemented in #5314.

Nice! :)
 
> > This could be indicated to the player by a red movement bar when the hero can use one of the spells to "move" without the hero being able to move "on horseback" on the terrain where he is located.
> 
> This part is yet to be implemented in future. I suggest to open a separate issue regarding this improvement. @LeHerosInconnu what do you think?

Done here: https://github.com/ihhub/fheroes2/issues/5317. :)
