### ISSUE TITLE
Automate importing of GoG flac music

### ISSUE THREAD

**Issue by michkry** [ihhub/fheroes2#5310]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

At the moment when we want to use flac music downloaded from GoG, we have to download the soundtrack, uncompress it, change the name of each track and then copy all .flac files to music directory. This procedure is carried out manually. This issue is related to the issue #4233 

### Describe the possible solution

The procedure described above could be automatized using powershell script. The script would be stored in the root directory of fheroes2 (like extract_homm2_resources.ps1), and it would use zip file containing the soundtrack in flac format downloaded from GoG. It would allow to specify the location of the zip file and also would detect it, if it was copied to the root directory.

### Additional info

The script we could use to carry out the task could be like this:

```PowerShell
$ErrorActionPreference = "Stop"

try {
    Write-Host "This script will extract and copy music files with flac extension to music directory" -ForegroundColor Yellow
    $flacZipUri = Get-ChildItem -Path ".\*flac*.zip" | Select-Object -ExpandProperty FullName
    $promptMsg = $null
    $flacZipExtractedDir = "extracted_flac"
    $musicDir = "music"
    if ($flacZipUri) {
        Write-Host "The following zip file was found:"
        Write-Host "$flacZipUri" -ForegroundColor Yellow
        $promptMsg = "If it contains the games soundtrack press 'enter', otherwise type in the location of zip file containing the soundtrack"
    } else {
        $promptMsg = "Type in the location of zip file containing the soundtrack"
    }
    $flacZipPrompt = Read-Host $promptMsg
    if (-not $flacZipPrompt) {
        $flacZipPrompt = $flacZipUri
    }
    if ($flacZipPrompt -and (Test-Path -Path "$flacZipPrompt" -PathType Leaf)) {
        if (Test-Path -Path ".\$flacZipExtractedDir" -PathType Container) {
            Remove-Item -Path ".\$flacZipExtractedDir" -Recurse -Force
        }
        Expand-Archive -Path "$flacZipPrompt" -DestinationPath ".\$flacZipExtractedDir" -Force
        if (Test-Path -Path ".\$musicDir" -PathType Container) {
            Remove-Item -Path ".\$musicDir" -Recurse -Force
        }
        New-Item -Path ".\$musicDir" -ItemType Directory -Force | Out-Null
        $extension = "flac"
        Get-ChildItem -Path ".\$flacZipExtractedDir\*.${extension}" -Recurse | 
        ForEach-Object { $orderNumber = (Select-String -InputObject $_.Name -Pattern "[0-9]{2}").Matches.Value;
                         $newName = "Track${orderNumber}.${extension}";
                         #Rename-Item -Path $_.FullName -NewName $newName;
                         Copy-Item -Path $_.FullName -Destination ".\$musicDir\$newName"
                       }
        if (Test-Path -Path ".\$flacZipExtractedDir" -PathType Container) {
            Remove-Item -Path ".\$flacZipExtractedDir" -Recurse -Force
        }
        $flacZipName = Get-ChildItem -Path "$flacZipPrompt" -Name
        if (Test-Path -Path ".\$flacZipName" -PathType Leaf) {
            Remove-Item -Path ".\$flacZipName" -Force
        }
    } else {
        Write-Host -ForegroundColor Red "FATAL ERROR: Unable to find zip file with soundtrack"
        return
    }
} catch {
    Write-Host -ForegroundColor Red (-Join("FATAL ERROR: ", ($_ | Out-String)))
} finally {
    Write-Host "Press any key to exit..."
    [void][System.Console]::ReadKey($true);
}
```

**Comment by zenseii** [comment]
Great @michkry ! Btw I believe the issue you linked is missing a digit or that you intended to link another one than that one?

**Comment by michkry** [comment]
Hi! @zenseii I corrected the error.

**Comment by zenseii** [comment]
Hi @oleg-derevenetz ! Since you're the expert on packaging and scripts, it would be nice if you should at some point have the time to share your opinion on what might be the best approach on this matter. However, this is not at all urgent, so please take whatever time you need.

**Comment by oleg-derevenetz** [comment]
Hi @zenseii I'm still thinking about how best to integrate this. Now we have two scripts - one for downloading and installing the demo version, and another one for unpacking and transferring resources from the original game, both work completely automatically (at least in most cases). I would not like to have 100500 separate scripts, each for solving just one small task like unpacking an archive with music. Therefore, we need to think about it a bit more.

What else I would like to note is that the proposed script in its current form is not quite suitable, because there is a requirement from @ihhub to support at least Windows 7 "out of the box" (i.e. without installing any additional software), and this implies that minimum supported PowerShell version should be 2.0, and this script is not compatible with PowerShell 2.0 because this version of PowerShell doesn't support the `Expand-Archive` cmdlet. But it's relatively easy to fix.
