### ISSUE TITLE
Github Action artifacts are gone?

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#5312]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Other

### Describe the bug

Seems like in recent builds you cannot find the github artifact builds/snapshots?

Here's the latest commit to master.
https://github.com/ihhub/fheroes2/actions/runs/2203545576

### Save file

Github-related.

**Comment by oleg-derevenetz** [comment]
Hi @zenseii Artifacts are generated only for pull requests. For the master branch, the latest snapshot is always available in the Releases section.

**Comment by zenseii** [comment]
I see and they are indeed available for PRs. I can however not find them for the master branch in the releases section. Maybe you need special permission for that?

**Comment by oleg-derevenetz** [comment]
@zenseii No, they are named like "Windows x64 build with SDL2 support (latest commit)" or "Nintendo Switch build with SDL 2.0 support (latest commit)" and so on and marked as pre-releases. Here are the direct links:

https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds

**Comment by zenseii** [comment]
Thank you! From there I can indeed see them.
