### ISSUE TITLE
Adventure map, cursor day counter shows wrong amount of days to reach the target.

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#5320]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Cursor shows that hero will reach destination on the next day. But the next day there's not enough movement points.
![image](https://user-images.githubusercontent.com/55348946/164894212-d3f240fb-dffa-4fcc-872c-d562c3326007.png)
![image](https://user-images.githubusercontent.com/55348946/164894220-b93fd2dc-29c2-46e5-a367-793a75ce6ab3.png)

### Save file

[path_.zip](https://github.com/ihhub/fheroes2/files/8546915/path_.zip)

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Thanks a lot for this instant fix! :)

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog unfortunately, this fix works a bit slower than previous code. The previous code simply subtracted the maximum number of hero movement points from the path length until the length of the remaining path becomes zero, and counted the number of these subtractions, not taking into account the fact that the movement points could not have been completely spent on the previous day. As a result, the error was constantly accumulating. This almost always had a negative effect on long paths, and sometimes even on short ones, like in this case. But it was relatively fast.
