### ISSUE TITLE
Castle siege, coliseum bonus does not apply for troops without defending hero or captain

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#5323]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

No morale bonus for a defending troops without leader.
Castle has coliseum and captain:
![image](https://user-images.githubusercontent.com/55348946/164896657-a7aa40db-53c3-457d-8027-8ca4f4528173.png)
Castle has only coliseum:
![image](https://user-images.githubusercontent.com/55348946/164896699-54979743-77eb-4183-ad37-aa6f2b884524.png)

Inside a castle troops info window shows morale bonus only for a hero army:
![image](https://user-images.githubusercontent.com/55348946/164896858-330b7883-4c19-42da-b93b-ba7695e13b38.png)
![image](https://user-images.githubusercontent.com/55348946/164896863-3156d516-27ad-451a-a0f8-ab713747e508.png)

### Save file

[Coliseum.zip](https://github.com/ihhub/fheroes2/files/8547034/Coliseum.zip)

**Comment by michkry** [comment]
It seems that if we remove the portion of code responsible for calculating morale from heroes_base.cpp:
![image](https://user-images.githubusercontent.com/11597098/164942864-6dd20887-746f-48b4-8eaf-2294490250d6.png)
And we add it to GetMoraleModificator from army.cpp class, the calculation of morale is carried out correctly
![image](https://user-images.githubusercontent.com/11597098/164942886-bdcd438e-edf3-413f-8ebe-2dc70fb9bfdc.png)

**Comment by oleg-derevenetz** [comment]
Hi @michkry you are ALMOST right... except that luck calculation needs to be fixed too, because Rainbow in the Sorceress castle affects the Luck of the defending units.
