### ISSUE TITLE
Castle siege, defending AI doesn't consider castle walls while creating a path to attack enemy inside castle walls

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#5325]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Enemy pack of boars went out of castle trying to reach Rocs. 
Boars also stuck for some turns in a moat because of non optimized path, that caused them drawn in a moat for a while.
Right after that they in panic move in front of castle walls trying to get in...

https://user-images.githubusercontent.com/55348946/164910017-c1bcdea5-1b56-4764-b3f4-659b6369d045.mp4

### Save file

[-8 morale.zip](https://github.com/ihhub/fheroes2/files/8547390/-8.morale.zip)

**Comment by oleg-derevenetz** [comment]
I believe this is fixed by #6479:

https://user-images.githubusercontent.com/32623900/234835223-49e8a920-922f-430c-9dde-5f28b9626e15.mp4

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz !
I've just tested this save file on the latest commit build and boars are simply standing in front of castle gate, while they could attack halflings or magi. The way to reproduce is the same as at video above. 
[-8 morale.zip](https://github.com/ihhub/fheroes2/files/11342530/-8.morale.zip)

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog

> I've just tested this save file on the latest commit build and boars are simply standing in front of castle gate, while they could attack halflings or magi. The way to reproduce is the same as at video above.

I tested this savefile with changes from #7068 (since I'm working on it now) and that's what I see:

https://user-images.githubusercontent.com/32623900/234842393-f81684a8-0222-4515-afe2-a8fdbf9bc3c0.mp4

With fixes from #7068 the overall strength estimation is fine and boars behave more agressively, attacking the halflings. Could you please test this with changes from #7068 on you side?
