### ISSUE TITLE
Spell icon size in creature's info window

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#533]
The OG has much bigger spell icon in creature's info window.
![Spell icon](https://user-images.githubusercontent.com/55348946/82145059-c3eb3a00-9850-11ea-8884-01aa702b52e5.jpg)
Compared to our version:
![Spell icon2](https://user-images.githubusercontent.com/55348946/82145067-d4031980-9850-11ea-9ef6-b18c689ac16d.jpg)

**Comment by ihhub** [comment]
We have even worse situation:
![image](https://user-images.githubusercontent.com/19829520/82662804-18cbed80-9c61-11ea-89a0-e8eda40a2b3a.png)
