### ISSUE TITLE
Creature amount number shouldn't be so close to the bottom edge of a battlefield

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#534]
I think this number shouldn't touch journal window in a bottom of a battlefield. We should make a little space between them.
![Number](https://user-images.githubusercontent.com/55348946/82145132-60154100-9851-11ea-8d83-36d1e9e9e386.jpg)

**Comment by ihhub** [comment]
We need counter offset information to be used to fix this and #261 issues.
