### ISSUE TITLE
Creatures don't have animated or glowing effects

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#535]
Some creatures don't have animated or glowing effects, that they have in original game.
This issue relates to:
#508 
#505 
#536 
#542
#593

**Comment by idshibanov** [comment]
I believe this is done in the original game with the color cycling and swapping palettes around. Not sure which approach should we use for our implementation.

**Comment by Branikolog** [comment]
> I believe this is done in the original game with the color cycling and swapping palettes around. Not sure which approach should we use for our implementation.

I've heard the same opinion from @ihhub regarding creation of animation on a water surface. And I think this approach is quite possible and implementable. But I'm not sure about Genie animation... On a first sight its animation looks more complex...

**Comment by idshibanov** [comment]
> But I'm not sure about Genie animation... On a first sight its animation looks more complex...

Genie and Ghost have idle timer of 0. They are always moving, that's why it looks 'complex'. The bottom part is basically water cycling, same as lava cycling for Phoenix body.

**Comment by idshibanov** [comment]
@ihhub For cycling effects we have to swap palettes (colors #214-#242 specifically). Right now we only apply the palette on initial ICN load and then just hit the cache. We need a way to draw sprite using a new sprite. 

I was thinking along the ways of registering a cycling sprite and then if you encounter one you would pixel-update it before drawing. Or we could go even bigger and swap the colors before `Display.Flip()`. Do you know a better approach?

**Comment by ihhub** [comment]
Hi @idshibanov ,
Regarding your two ideas:
- global scale update based on your idea. **Drawbacks**: some objects require different timings for updates so doing this at global scale might be logically impossible
- special type of Sprite (cycling Sprite). We need an internal mechanism to deal with it.

Let's have a look into Sprite class. This class is derived from Surface which is a foundation for our drawings and which is a holder of an image. Our concern lies on **Blit** function. Moreover, there is already a method called `ChangeColorIndex` which does what we want. Moving forward: we already have an implementation of this idea in `AGG::LoadExtICN` method, lines **692 - 764**.

In such case we could do in 2 ways:
- move pixel rotating mechanism inside Sprite class
- add more code in `AGG::LoadExtICN`

My preference would be to move inside Sprite class with a special method called `void SetInternalAnimation` (the name is subjective). This method should receive:
- uint32_t count <--- number of iterations
- std::map<uint32_t, uint32_t> colorVsColor <--- replacement of colors

The weak point is that the map above is incorrect as we have add actual map for each step/iteration.

What do you think?

**Comment by idshibanov** [comment]
Okay, somehow I missed `ChangeColorIndex` function. Great, this solves half of my problems, but we would have to update it to swap multiple colors at the same time, as this call is very expensive. I would definitely implement all of this in `Sprite` class.

To be honest I'm not too worried about the timing, all colors should cycle at the same time.  In the game there's 3 modes of cycling: one for adventure map, one for battle and the last one for special battle when you fight on Snow, Desert, Wasteland or Beech.

I'm not sure if we need the map at this point but we can decide later on.

**Comment by ihhub** [comment]
Hi @idshibanov , yes it is very computationally expensive. Give me please some time to write a faster implementation of `RenderChangeColor` as well as overloaded version with multiple colors.
