### ISSUE TITLE
Do not translate language name

### ISSUE THREAD

**Issue by kant2002** [ihhub/fheroes2#5361]
### Your question

I do think that language names should always be displayed in their own language, otherwise these names has to be duplicated in all translation files.
For example
- English
- Français
- Українська
- Русский

Unless I'm well educated I do know what my language written in different languages. I may guess, but that's bad UX IMO.

### Additional info

https://github.com/ihhub/fheroes2/blob/d0a73ee5bd346a0a8b2bca7ab29d3b87ecdf4a8d/src/fheroes2/gui/ui_language.cpp#L127-L157

**Comment by ihhub** [comment]
Hi @kant2002 , the application works exactly as you described:
![image](https://user-images.githubusercontent.com/19829520/166420728-c9f74162-0047-4dd5-9910-d4f182ec3d20.png)

Most likely your version does not have *.mo files for specific languages. If a corresponding file is not found a current language is used for translation.

**Comment by kant2002** [comment]
Ahh. Ok. Probably I miss some configuration steps, or screw something up.
