### ISSUE TITLE
Chain Lighting spell sequence problem

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#537]
Chain Lighting spell hits units with improper sequence.
![Chain](https://user-images.githubusercontent.com/55348946/82147205-d10b2780-9856-11ea-915c-c2dab00eb11c.jpg)
![Chain2](https://user-images.githubusercontent.com/55348946/82147206-d36d8180-9856-11ea-8ab9-8867f5ef84de.jpg)
On the screenshot I hit 3rd unit with the spell. Then it goes to 2nd unit. After 4th and then 1st.

**Comment by idshibanov** [comment]
In OG spell jumps to closest target (use `unit.GetRectPosition`). If there's multiple then it's random.

**Comment by Branikolog** [comment]
I don't know exactly how it works in the OG, but in heroes3 and logically Chain Lighting spell should  hit the nearest unit to the unit it stroke before. Now it seems to check closest units to the first target and hit them in order considered their location compared to the first target unit.

**Comment by Branikolog** [comment]
Also "chain lighting" spell hits twice 2-hex unit, if player targets farthest hex of creature.
![Chain](https://user-images.githubusercontent.com/55348946/84634114-03fa1700-aefa-11ea-9cdd-5219072e9612.jpg)
