### ISSUE TITLE
Adventure map, dwellings info empty line missing

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#5393]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

![image](https://user-images.githubusercontent.com/55348946/167302173-dbd63712-57ef-4f7e-9514-28df34bb91cd.png)
All other objects have an empty line before info in parentheses.
![image](https://user-images.githubusercontent.com/55348946/167302221-afd51d77-c23a-4d10-92a0-2b292f12298a.png)
![image](https://user-images.githubusercontent.com/55348946/167302238-5b357631-98ec-410c-9ee1-f925a670afe0.png)

### Save file

[Missing line.zip](https://github.com/ihhub/fheroes2/files/8647199/Missing.line.zip)

**Comment by LeHerosInconnu** [comment]
Related issue: https://github.com/ihhub/fheroes2/issues/2717.
