### ISSUE TITLE
Crash at the end of player's turn

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#5399]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

Based on a feedback from one user.
Not sure this bug is reproduceable, since player used quite an old save file, which was created a couple releases ago.

Crash log:
```
aust@Rizen53600 ~ [SIGABRT]> fheroes2
Free Heroes of Might and Magic II, version: 0.9.15
----------
Main Menu

Press N to choose New Game.
Press L to choose Load previously saved game.
Press H to show High Scores.
Press C to show Credits.
Press T to open Game Settings.
Press ESCAPE to Quit the game.
----------
10:17:35: [ERROR]       Play:  Couldn't open /etc/timidity++/freepats.cfg
10:18:24: [ERROR]       Play:  Couldn't open /etc/timidity++/freepats.cfg
10:18:26: [ERROR]       Play:  Couldn't open /etc/timidity++/freepats.cfg
10:18:28: [ERROR]       Play:  Couldn't open /etc/timidity++/freepats.cfg
10:18:29: [ERROR]       Play:  Couldn't open /etc/timidity++/freepats.cfg
fheroes2: ../fheroes2/kingdom/kingdom.cpp:486: const Recruits& Kingdom::GetRecruits(): Assertion `recruits.GetID1() != recruits.GetID2() && recruits.GetID1() != Heroes::UNKNOWN && recruits.GetID2() != Heroes::UNKNOWN' failed.
fish: Job 1, 'fheroes2' terminated by signal SIGABRT (Abort)
faust@Rizen53600 ~ [SIGABRT]> 
```

### Save file

Unfortunately, no save file was provided by the user.

**Comment by ihhub** [comment]
Closing this issue for now as not feedback was given for a very long time.
