### ISSUE TITLE
Cursor too small

### ISSUE THREAD

**Issue by ondesic** [ihhub/fheroes2#5419]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

I checked for issues related to cursors and didn't find this one.  I am so glad to be playing HOMM2 again.  However, I can barely see the cursor.  It doesn't matter if I fullscreen or minimize the screen, the cursor stays the same small size.  Is there a way to increase the size for more enjoyable play?  Here are two pictures.  It doesn't matter the resolution, the cursor is the same size.  I placed the cursor over a dark part to allow it to show up, but it is lost if anywhere else.  It is on the "High Score" sign.  The first is windowed, the next is maximized.
![20220517_110300](https://user-images.githubusercontent.com/26915986/168870908-bca89640-5799-4ecd-863f-1fa7fa6e3c93.jpg)
![20220517_110309](https://user-images.githubusercontent.com/26915986/168870916-e1cf39f3-fb8b-44a9-b15e-9e502653eca5.jpg)

### Describe the possible solution

I would like to have an option to scale the cursor size.

**Comment by Branikolog** [comment]
Hello, @ondesic !
On both of your screenshots you're running fheroes2 in window mode (you've even stretched it obviously). Currently cursor is scaled only for full-screen application. Try to press F4 and ruin fheroes2 full-screen.

**Comment by ondesic** [comment]
Thanks.  It does help in full screen.  However, it would be helpful to be able to have a larger cursor in windowed so that I can multitask and do work in another window while playing :-)
