### ISSUE TITLE
Wrong description on some terrain objects

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#543]
When you right click over some objects on world map you can notice that their description is wrong. 
![Shrub2](https://user-images.githubusercontent.com/55348946/82199290-2c482300-9906-11ea-8050-c62b46bbcfeb.jpg)
![Shrub3](https://user-images.githubusercontent.com/55348946/82199299-2f431380-9906-11ea-8150-03107ca0d4cb.jpg)
![Skull](https://user-images.githubusercontent.com/55348946/82199303-2fdbaa00-9906-11ea-8d54-289abf159836.jpg)
![Shrub](https://user-images.githubusercontent.com/55348946/82199309-323e0400-9906-11ea-88ea-67f435f3b530.jpg)

**Comment by ihhub** [comment]
I think we interpret object IDs in a wrong way resulting in incorrect descriptions.

**Comment by ihhub** [comment]
Hi @Branikolog , **rock** is correct. The same naming is in the original game.
