### ISSUE TITLE
Scenario window, purple color of the background of the text indication of the opponents' colors does not go to the frame for red, yellow and purple players

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#5433]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, purple color of the background of the text indication of the opponents' colors does not go to the frame for red, yellow and purple players.
One pixel wide is of a different color.

In fheroes2:

![Scenario window flèches 01](https://user-images.githubusercontent.com/43583994/169555992-0976de4a-8a11-4f2b-88e1-3490b928007f.png)

### Save file

Not needed.

**Comment by tarboss** [comment]
- its not a bug - its a feature
- u can only select bule,green or orange for a human player and starting position!
- red,yellow, purple is only for computer (map @Broken Alliance)

**Comment by zenseii** [comment]
> * its not a bug - its a feature
> * u can only select bule,green or orange for a human player and starting position!
> * red,yellow, purple is only for computer (map @broken Alliance)

Hi @tarboss!
This is not what @LeHerosInconnu is suggesting. If you look closer (a lot) on the image posted above you might be able to understand that the issue at hand is about some wrong pixels (not surprising to those of us already familiar with LeHerosInconnu's expert pixel eye):
![image](https://user-images.githubusercontent.com/12501091/169698026-960df56e-3005-4fbd-9e2f-aec8a98ff695.png)

**Comment by LeHerosInconnu** [comment]
Hello @tarboss and @zenseii,

Thanks @zenseii for the explanation with the close-up. :)

After inspection, the visual can be improved. :)
First, by giving the same background color for the text as the player's color (in the example the color blue).
Then by improving the frame by taking the values of the player sprite (human player in the example), that is a yellow frame with a 1 pixel black frame around the background color of the text.

The space between the difficulty texts and the 'Opponents' "title" will have to be reduced to compensate.

![Hero color name frame coupé 02](https://user-images.githubusercontent.com/43583994/169705815-4210ce1d-1a3f-4d0c-84e0-8dc9f1fc33c7.png)

![Hero color name frame coupé zoom 03](https://user-images.githubusercontent.com/43583994/169706233-cb3d2573-4e4c-4827-9885-24426d8fdd74.png)

I'll open an issue for this later. :)

**Comment by zenseii** [comment]
> After inspection, the visual can be improved. :) First, by giving the same background color for the text as the player's color (in the example the color blue). Then by improving the frame by taking the values of the player sprite (human player in the example), that is a yellow frame with a 1 pixel black frame around the background color of the text.


One issue I can see with this is that some text might be less readable? Like White text over yellow background like for Yellow player? We obviously don't have white player color so that isn't a problem. Not sure how necessary this change is and I would want to see a mock up of it first (with all 6 colors). I'm also not convinced this looks "objectively" better or gives any benefit over the original.

**Comment by LeHerosInconnu** [comment]
Hello @zenseii,

> > After inspection, the visual can be improved. :) First, by giving the same background color for the text as the player's color (in the example the color blue). Then by improving the frame by taking the values of the player sprite (human player in the example), that is a yellow frame with a 1 pixel black frame around the background color of the text.
> 
> One issue I can see with this is that some text might be less readable? Like White text over yellow background like for Yellow player? We obviously don't have white player color so that isn't a problem. Not sure how necessary this change is and I would want to see a mock up of it first (with all 6 colors). I'm also not convinced this looks "objectively" better or gives any benefit over the original.

Here is the first try:

![Scenario window change 01](https://user-images.githubusercontent.com/43583994/169708217-4ec6eeef-1ec1-4266-993d-a4c1b1491a37.png)

Here is another version so that the shadow of the "g" in the word "orange" and the "p" in the word "purple" is in the rectangle of the color (and does not overlap the edge of the black frame of one pixel):

![Scenario window change 03](https://user-images.githubusercontent.com/43583994/169708228-3a80e2f9-2b45-4f99-90f1-6330fdc84ea2.png)

**Comment by zenseii** [comment]
@LeHerosInconnu, to me the white on yellow is very hard to make out.

**Comment by LeHerosInconnu** [comment]
@zenseii.

> @LeHerosInconnu, to me the white on yellow is very hard to make out.

Even if the background color is not changed from the original game, the frame around the background color could be improved.

**Comment by LeHerosInconnu** [comment]
Discussion on the frame around the purple color of the background of the text indication of the opponents' colors opened here: https://github.com/ihhub/fheroes2/discussions/5444.
