### ISSUE TITLE
Artefact Text - Spell Scroll Description is confusing

### ISSUE THREAD

**Issue by Eldorias-Piano-Covers** [ihhub/fheroes2#5437]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [ ] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

The description of the "Spell Scroll" type artifacts indicates the following text: "This spell scroll gives your hero the ability to cast the [...] spell".
However, if the hero does not have a magic book but has one of these artefacts, the icon for casting a spell is disabled, and when the "C" key is pressed to cast a spell, a popup warns that there is "no spell to to cast".

Should this artefact gives the possibility to cast a spell even without magic book ? Or does it should add & write a spell "In" the magic book ?

The texts must surely be readjusted to avoid any confusion.

### Save file

[spellscrolltext.zip](https://github.com/ihhub/fheroes2/files/8747414/spellscrolltext.zip)

### Additional info

In savegame : 
Ector Hero does not have any Magic Book
Ector Hero is carrying Spell Scroll for Dimension Door spell.
Ector Hero has 10 mana, and has movement points left.
Description of Spell Scroll : "This spell scroll gives your hero the ability to cast the Dimension Door spell"
Description of Magic Book : "The Magic Book enables you to cast spells".

**Comment by zenseii** [comment]
I believe this is what the original text says so I'm marking it as an improvement. Please correct me if I'm wrong.

**Comment by oleg-derevenetz** [comment]
Hi @Eldorias-Piano-Covers @zenseii this is the original text from the original game:

![Spell Scroll](https://user-images.githubusercontent.com/32623900/169671080-f3382ad1-2786-4a69-961c-30bcb8e3e023.png)

Despite the wording, Spell Scroll does not give the opportunity to cast the spell by itself, your hero still need to have the Spell Book.

**Comment by zenseii** [comment]
So we need to decide whether to:
1. Specify in the text that you need a spell book
or
2. Make it possible to cast spells you have the scrolls for even if you don't have a spell book.


Since the second option is a relatively big change to the game mechanics, I would suggest to change the text for now and then at a later point decide whether to implement the second option.

**Comment by felix642** [comment]
Hi @ihhub, I think we can close this issue. For some reasons I forgot to mention it in my latest pull request ?
