### ISSUE TITLE
Acceleration of city animation while new building appears

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#544]
During the time, new building appears, all animations in city accelerate significantly.

**Comment by ihhub** [comment]
In the original game all other buildings during a construction do not have any animation. Should we do the same?

**Comment by Branikolog** [comment]
> In the original game all other buildings during a construction do not have any animation. Should we do the same?

I think it will be better, than accelerated animation we already have.
But actually, I wish animation be perpetual.
