### ISSUE TITLE
Remove dependency on SDL for tools on Visual Studio

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#5447]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

We removed a lot of dependencies from SDL in the past. Most of tools do not use SDL related code at all so we need to build them without such dependency. This is required for further steps towards simplification of artists work setup.

### Describe the possible solution

Remove SDL dependency on Visual Studio projects for tools.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub If the problem is only to give artists access to tools, then we can just pack them additionally into a ZIP file, because we currently build them anyway.

**Comment by ihhub** [comment]
Closing this issue as we fixed it in a different manner.
