### ISSUE TITLE
Current cell designation

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#545]
Current battle cell is marked in different way, compared to the original game. In the OG it is dimmed, and our version has red contour without dimming.
Our version:
![Cell](https://user-images.githubusercontent.com/55348946/82204329-5cdf8b00-990d-11ea-8bca-5a325eb7a26d.jpg)
OG:
![Cell2](https://user-images.githubusercontent.com/55348946/82204360-6a951080-990d-11ea-9d99-a665df1de4cc.jpg)

**Comment by ihhub** [comment]
Closing this issue as a duplication of #357
