### ISSUE TITLE
Doubled resource description

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#546]
Resources and gold, that can be found on a world map have two same names written one under another.
![Resources](https://user-images.githubusercontent.com/55348946/82207873-345a8f80-9913-11ea-9d13-b094beb1076f.jpg)

**Comment by ihhub** [comment]
Hi @Branikolog , is this bug reproducible on 0.7 version as well? We want to know when we start getting this.

**Comment by Branikolog** [comment]
> Hi @Branikolog , is this bug reproducible on 0.7 version as well? We want to know when we start getting this.

If I'm not mistaken, this started from the 0.7 update. The version I've downloaded 04.29 already had this bug. But the version 0.7 I've installed 04.23 was OK.

**Comment by ihhub** [comment]
**0.7** has the same bug.
