### ISSUE TITLE
Summoned Air Elemental darkening

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#550]
While appearing texture inside Air Elemental darkens.
I also noticed, while summoning the second Elemental They're becoming dark inside together. But not always. I found out, that happens, after I try to summon another type (fire) elemental and receive refusal, due to summon rules. After that summoned Air Elemental appears with darkening and the darkening happens to previously summoned elemental. 
![Air](https://user-images.githubusercontent.com/55348946/82319711-bfeb2380-99da-11ea-8125-0ff9221e4d06.jpg)
![Air2](https://user-images.githubusercontent.com/55348946/82319716-c24d7d80-99da-11ea-9aaf-6286bfab20b4.jpg)

**Comment by ihhub** [comment]
We incorrectly process air elementals ICN files. Here how they should look like:
![image](https://user-images.githubusercontent.com/19829520/82820918-aadc2c00-9ed5-11ea-976a-34c75307c730.png)

and here what we have:
![image](https://user-images.githubusercontent.com/19829520/82820931-b4fe2a80-9ed5-11ea-8d79-79b0a34ec893.png)

**Comment by ihhub** [comment]
Hi @idshibanov , do you have an input how the original game process ICN frames? I suspect that our version of the algorithm has a bug causing this result as well as the problem with tents.

**Comment by ihhub** [comment]
The only place in code wit a tiny fix for this creature is this:
```
    if ( icn == ICN::AELEM && res.first.w() > 3 && res.first.h() > 3 ) {
        res.first.RenderContour( RGBA( 0, 0x84, 0xe0 ) ).Blit( -1, -1, res.first );
    }
```

**Comment by idshibanov** [comment]
@ihhub I believe it's the same issue as #507 and #459. We're handling shadows wrong (specifically 0xC0 ICN block). If you turn off the shadows then tents look good.

Shadow handling is complex in OG and requires more time to figure out. One thing I know is that they use a special dim palette hardcoded in the executable to "cut" the colors and simulate alpha. Our current code in `AGG::RenderICNSprite` simply uses 0x40 alpha mask, which is incorrect.

**Comment by ihhub** [comment]
It happens only for SDL 1.
