### ISSUE TITLE
Spell sorting in a spell book

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#551]
When you enter spell book in inventory, you can see all spells together, until you press battle or adventure shortcuts in a spell book bottom.
![Book](https://user-images.githubusercontent.com/55348946/82322004-78669680-99de-11ea-85e5-a7b08b72f177.jpg)

**Comment by ihhub** [comment]
Hi @Branikolog , could you please explain what behavior you expect?

**Comment by Branikolog** [comment]
> Hi @Branikolog , could you please explain what behavior you expect?

Spells should be separated. When you enter book, you can see world map spells on default. And if you wish to watch combat spells, you should press little sword icon. To switch between these two spell categories. 
Now, on default, we can see ALL spells leafing through.
