### ISSUE TITLE
"k" letter should be the same for all languages

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#5514]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Even at language selection menu we can watch two different styles of  "k". (Compare "Polski" and "Norsk")
![k](https://user-images.githubusercontent.com/55348946/172492174-6ca1ac45-2557-4674-b39d-98bb6864e564.png)

### Describe the possible solution

I think, we should stick to smaller one, since original "k" looks like a capital one.

**Comment by zenseii** [comment]
I agree with this change. I also want to note that whatever approach is used for this, you will need to take into account that some letters might be using k to generate another letter. One example is the cyrillic small k you can see in the screenshot used to write "ukrainian" and "russian".

**Comment by Branikolog** [comment]
Hi, @zenseii !
I suppose, we should leave original asset of small "k" as it is and simply change all "k" in the engine with new one.
Between, cyrillic "k" is completely different, from latin.

**Comment by zenseii** [comment]
> Hi, @zenseii ! I suppose, we should leave original asset of small "k" as it is and simply change all "k" in the engine with new one. Between, cyrillic "k" is completely different, from latin.

Yes, it is different, I'm just saying this from having worked with this part of the code. Basically due to the smaller Cyrillic k being generated by editing the existing lowercase latin k, any change to the lowercase latin k would lead to a change in the cyrillic k, if you don't make sure to make the code avoid this somehow.
