### ISSUE TITLE
Ai defending a castle will just sit in there with his flying units taking ranged hits until they die

### ISSUE THREAD

**Issue by fidde9202** [ihhub/fheroes2#5523]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

I tried fheroes2 out in it's early development, and had this issue back then too, which is main reason i decided to give it a break and come back and try it later on when you've had some time fixing all the ai problems. Basically, when you attack an enemy that is defending his base with flying units, they will just sit in there until you go inside. So i can basically just sit there with my titans killing off the black dragons inside his base since he won't move. 

### Describe the possible solution

I think the ai is acting this way cause it thinks the arrow towers will deal with the enemy and then it just breaks. When i encountered this problem again yesterday he also had range unit which i killed off, and maybe ai doesn't recognize the ranged units being dead and try to defend them?

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , could you please verify this? I think we fixed this issue some time ago.
