### ISSUE TITLE
External audio not always returning to on after turning volume to zero

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#5528]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

See relevant comment https://github.com/ihhub/fheroes2/pull/5526#pullrequestreview-1003469825

Audio doesn't restart for external audio or just plays midi music after having turned off volume, regardless of what audio type you currently have on. Sometimes midi music gets played instead of external, depending on in what audio type you turn the volume off or on.

It is not specific to the PR mentioned above. 

**EDIT: I've checked that it happens in 0.9.15 too.**

https://user-images.githubusercontent.com/12501091/173192395-95cc9752-384b-415e-9923-ed2fa62aa6da.mp4

### Save file

Just open config dialog in any build.

### Additional info

@oleg-derevenetz, it would be great if you have the time and opportunity to take a look at this.
I was asked by @ihhub to ask you if you could since he is unavailable to do so right now.

**Comment by oleg-derevenetz** [comment]
It seems that this is Windows-only issue: it is 100% reproducible on Windows, but I can't reproduce it on macOS (my main development OS). I believe it is related to the SDL_Mixer implementation on Windows itself.

**Comment by oleg-derevenetz** [comment]
What's interesting (this happens only on Windows as well) when we turn off the music on the adventure map, sound effects will remain for a while... until we change the music source to the MIDI. They will come back when we increase the music volume, however if we turn the music off once again and change the music volume to External, neither music nor sound effects are come back... until we turn the music on and change the music source once again:

https://user-images.githubusercontent.com/32623900/173208008-10ce5403-0169-4a71-a959-07d160969ba7.mp4

**Comment by oleg-derevenetz** [comment]
We may try to fix this issue as well as #2009 and possibly #5569 by using on Windows `SDL_Mixer` built with the `FluidSynth` (it has the ability to integrate). In this case built-in Windows MIDI synthesizer will not be used, but we will need to bundle the so-called SoundFont file with the game. I believe there are files available under a suitable license.
