### ISSUE TITLE
Fix all places in code containing FIXME comment

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#56]
We have multiple places with `FIXME` comment. These functions/places we need to fix wit correct logic.

**Comment by bjauny** [comment]
I'll take a look at these. Should I create new issues if need be?

**Comment by ihhub** [comment]
Hi @bjauny , yes, you can look at this. It needs to create other issues for each FIXME comment so it's totally fine to do so. We need to understand what previous developers tended to do with the code.

**Comment by bjauny** [comment]
Great, I'll investigate this.

**Comment by bjauny** [comment]
Created all the relevant issues. The remaining occurences are there for debug purposes.

@ihhub  Feel free to close this one if you're OK with the analysis.
