### ISSUE TITLE
Battle speed problems.

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#560]
The animation speed of flying and walking troops is not the same. Significantly not the same.
I've noticed that difference after #492 commit. Now it became more obvious.
Also I think we need another speed calibration in options: on the values 1-7 troops move way too slow. 
And one more thing:
Attack animation speed of all units seems to be much slower than movement speed.

**Comment by ihhub** [comment]
Hi @Branikolog , we're working on this.

**Comment by Branikolog** [comment]
Great news! I hope you can easily manage this issue.

**Comment by idshibanov** [comment]
Let's convert this issue into **discussion** about animation speed in game in general. There's two more PRs open bringing animations in line, after those it should be consistent. Speed is a very subjective thing, also we might have a different understanding of current settings. Note that every unit animated with own speed: upgraded units will be animated faster.

Right now:
**Speed 5 = Normal** in OG (120ms/frame)
**Speed 7 = Fast** (80ms/frame)
**Speed 9 = Very Fast** (40ms/frame)

@Branikolog What are your expectations here?

Speed 5 is the default in fheroes2. There's no 'Slow' in OG, so all default values in game data were assigned to 5. This brings us two questions: 

1. How granular the speed should be represented in settings? Do you like it being 1 to 10? What about text description such as "fast"?
2. Which speed you want to be new default? Should we stay with OG normal, but make it 3 instead (for example)?

**Comment by Branikolog** [comment]
>
> 1. How granular the speed should be represented in settings? Do you like it being 1 to 10? What about text description such as "fast"?

On one hand I love the granularity we have now. I can adjust the most comfortable speed for me and play with maximum pleasure. Not sure, we need exactly 10 steps... 
But on the other hand "Fast", "Normal", "Slow" etc is more eye-friendly... Looks simple and canonical....

> 2. Which speed you want to be new default? Should we stay with OG normal, but make it 3 instead (for example)?
I think default speed we should make the same or close to the OG. Considering that it rather slow in the OG i don't think we need lots of steps before it... I think the minimum speed shouldn't be less than current speed in a well. Of course, if we'd set lower speed at all.... And maximum speed, I think, should be set up to the moment it looks ridiculous...

**Comment by idshibanov** [comment]
I agree that OG normal speed is rather slow, especially if you play a lot of battles in a row. What the new "normal" should be then? 3 or 4? I want to give an option to go a bit slower.

**Comment by Branikolog** [comment]
> I agree that OG normal speed is rather slow, especially if you play a lot of battles in a row. What the new "normal" should be then? 3 or 4? I want to give an option to go a bit slower.

I think, two steps slower, than OG will be enough. So let's make the 3 similar to the OG normal speed. 
I think in future we would change a bit visual display of speed changing... 
And right now let it be simple adjustment from 1 to 10...

**Comment by idshibanov** [comment]
I just tried setting 3 as default for the battle speed (with smaller jumps), then 5 looked like a sweet spot to me. However most speeds after that looked way too fast, with 8 to 10 already as ridiculous. Two things here: 

1. We need to ditch linear scaling for speed. 40ms to 20ms delay is a huge jump compared to 140ms to 120ms. It should work more like a percentage, I'll come up with something.
2. If the scaling will be smoother then we can make old "Normal" a 4, leaving some room for adjustment since we have a big adjustment range already.

@ihhub what are your thoughts on this issue?

**Comment by Branikolog** [comment]
> 1. We need to ditch linear scaling for speed. 40ms to 20ms delay is a huge jump compared to 140ms to 120ms. It should work more like a percentage.

I think you shouldn't stick to certain numbers. Just find the slowest speed, the highest possible speed and divide this interval to 7 steps.

**Comment by ihhub** [comment]
As a conclusion: we want to have **not** worse than the original game settings keeping in mind that some players want more flexibility in them. As of now we could stick to what we have and review this when we are close to 1.0 release.

@idshibanov  and @Branikolog , is it okay with you, guys?

**Comment by idshibanov** [comment]
Of course I'm happy with the current solution as it provides the identical settings to the original with additional room in between.
