### ISSUE TITLE
Adventure map, enemy hero managed to enter player's castle

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#5606]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

![image](https://user-images.githubusercontent.com/55348946/177994550-f3e88829-5b79-4fdd-9759-4334a8c04af5.png)
Green hero in purple castle. We can even manage his options.
Another bug of "garrison experimental feature"...

### Save file

[Green spy in a castle.zip](https://github.com/ihhub/fheroes2/files/9072121/Green.spy.in.a.castle.zip)

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog was this castle empty when it was occupied by the AI or there was a guest or guardian hero (or may be both)?

**Comment by oleg-derevenetz** [comment]
> Unfortunately the issue was found by one of our players. He don't have save file for previous turn.

Maybe this player can tell the backstory in his own words? Did he notice how the hero arrived in this castle?

> Is it possible for AI to place a hero into castle garrison during his turn?

If you mean setting the hero as a guardian - then no, AI cannot do that. AI heroes can enter castles only as guests. This hero is a castle guest too (occupies the bottom line in the castle).

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz 
Is it possible, that AI could hire new hero, while another is in the castle, so it appears in the garrison row., and then left there, after player captured the castle.

**Comment by oleg-derevenetz** [comment]
@Branikolog as I can see, AI shouldn't use castle to recruit a hero if there is already a guest hero in the castle, this is specifically checked when choosing a castle to hire a hero.

**Comment by Branikolog** [comment]
> @Branikolog as I can see, AI shouldn't use castle to recruit a hero if there is already a guest hero in the castle, this is specifically checked when choosing a castle to hire a hero.

The player, that found an issue, thinks, that the hero was already in garrison, when he captured the castle.

**Comment by oleg-derevenetz** [comment]
@Branikolog Hmm, but AFAIK there is no way to capture the castle without fighting ALL heroes in the castle. So even if AI somehow managed to hire a guardian, this guardian should be defeated first, and only then the castle can be captured.

**Comment by ihhub** [comment]
So this is the problem with `castle: allow guardians` option and specifically with `void AIToCastle()` function where an AI hero kills a defender (guest) and then claims the castle.

This option is not properly implemented in many places like army strength evaluation or AI actions. As of now we are going to remove it.

**Comment by oleg-derevenetz** [comment]
> As of now we are going to remove it.

Sad, it was a funny option.

**Comment by ihhub** [comment]
@oleg-derevenetz . if you would like to fix all cases and the mess with the code then we can keep it :)

**Comment by zenseii** [comment]
Since we want to remove the experimental options dialog, would it make it quicker if we could move these options to only be present in the .cfg file? I'm thinking about other options which are highly contested like getting knowledge skill in Arena, Wait, Spell book from Shrines etc.

It might be an OK compromise for those that want these, @ihhub?

**Comment by ihhub** [comment]
Hi @zenseii , I think we should rewrite at least the system for storing these options. They shouldn't be a part of the fheroes2.cfg file but something else. I am sure many people in the future are going to add more options so we need to have a flexible way to support this.

**Comment by oleg-derevenetz** [comment]
@ihhub Honestly I still don't know how this issue happened. I looked through the code and didn't understand how this could happen, and I was unable to reproduce this.

@zenseii The issue with experimental option is mainly that they are rarely taken into account when developing improvements, because few people use them.

**Comment by ihhub** [comment]
@oleg-derevenetz , to make this option really good we should make both heroes which are in the castle join the battle :)

**Comment by zenseii** [comment]
> @zenseii The issue with experimental option is mainly that they are rarely taken into account when developing improvements, because few people use them.

Yes. I do see streamers like AbsoluteZero use such features like Scouting giving extended info according to level. I honestly don't know how many use these features, and I also want to avoid lengthy discussions about whether or not they should be there by default.

Personally I prefer to keep the core gameplay to be as close to the original as possible.

> They shouldn't be a part of the fheroes2.cfg file but something else.

This works too. I'm just trying to think of the way that will take the least amount of effort because we don't know what the returns will be for working on these options.

**Comment by zenseii** [comment]
> @oleg-derevenetz , to make this option really good we should make both heroes which are in the castle join the battle :)

Maybe we could make garrisoned heroes catapult each other from their castles? :grinning:

**Comment by oleg-derevenetz** [comment]
@ihhub

> to make this option really good we should make both heroes which are in the castle join the battle :)

But they do. Guest hero participates in battle first, outside the castle, and then there is a separate battle with guardian near the castle walls.

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz !

> > As of now we are going to remove it.
> 
> Sad, it was a funny option.

Since Heroes2 has a captain for defending castles, placing heroes inside garrison makes this original mechanic needless, unlike in H3, where garrison heroes came from. Defending castles shouldn't be the same to H3, since these are different games after all.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog

> Since Heroes2 has a captain for defending castles, placing heroes inside garrison makes this original mechanic needless, unlike in H3, where garrison heroes came from. Defending castles shouldn't be the same to H3, since these are different games after all.

Captain works differently: if there is already a guest hero in the castle, captain doesn't participate in battle at all, while guardian hero always participates in battle if guest hero lost his battle before that. Also, unlike HoMM3, guardian heroes are counted in the total limit of kingdom heroes, which somewhat weakens this feature and does not replace the captains as a whole. But, of course, guardian heroes are not included in the original HoMM2 mechanics.
