### ISSUE TITLE
No animation while upgrading Dragon Tower

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#561]
There is no smooth animation in a Warlock city when you upgrade the Green Tower to the Red one. 
The Red Tower just appears at once, after building sound had finished.
Similar thing happens while upgrading to the Black Tower. The only difference is that we do have animation but new color of the tower appears instantly, after process of building had finished.

**Comment by ihhub** [comment]
The problem is in `CastleDialog::RedrawAnimationBuilding` function.
