### ISSUE TITLE
Crash during AI turn

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#5613]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Something has happened during AI turn.

### Save file

[Wizard_s_Land_3_0001.zip](https://github.com/ihhub/fheroes2/files/9079099/Wizard_s_Land_3_0001.zip)

**Comment by Branikolog** [comment]
One more save file. Probably the same issue:
[Wizard_s_Land_2_0001.zip](https://github.com/ihhub/fheroes2/files/9079130/Wizard_s_Land_2_0001.zip)

**Comment by ihhub** [comment]
The crash in AI related code in `setHeroRoles` function.
