### ISSUE TITLE
Main menu, fast switch external music causes it play too quiet.

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#5622]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

The same actions described in #5581 cause now low music level. I believe there's some problem with fade.
![image](https://user-images.githubusercontent.com/55348946/178253027-5486c45d-a82e-47b4-b53f-8d37a8fa30dd.png)
We still need to press "Music type" button slow to avoid problems with music.

### Save file

None.

**Comment by oleg-derevenetz** [comment]
We can't resolve this issue in a different way than getting rid of Windows MIDI in favor of another software MIDI synthesizer. In the meantime, do not click quickly :)

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Okay. :)
I'll wait for the MIDI solution then.)
