### ISSUE TITLE
Battle screen, external music don't start on the beginning of the battle

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#5643]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Couldn't reproduce it, but the issue definitely occurred.
https://youtu.be/lH6csPoL8Zo?t=14400

### Save file

None.

**Comment by ihhub** [comment]
I think #6206 fixed this issue. I am closing it for now.
