### ISSUE TITLE
Combat, Abandoned Mine, wrong number of ghosts, ghost groups and their positioning 

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#5651]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the Ghosts guarding an Abandoned Mine should always be divided into five groups, as in the original game.
Otherwise it's too easy to slow down the single group with an easily accessible Slow spell, compared to the Mass Slow spell.

In original game:

![Abandoned mine 001](https://user-images.githubusercontent.com/43583994/179030042-4805b9a9-674b-45e4-afcb-172cf224fa6f.png)

![Abandoned mine 002](https://user-images.githubusercontent.com/43583994/179030055-b6eaace8-48b9-42ca-92f8-d3de79298d87.png)

![Abandoned mine 003](https://user-images.githubusercontent.com/43583994/179030068-6299fddd-840c-4eb7-a261-c1161f0f9754.png)

![Abandoned mine 004](https://user-images.githubusercontent.com/43583994/179030079-9453925a-1a9a-4884-8e79-c506c02d63de.png)

![Abandoned mine 005](https://user-images.githubusercontent.com/43583994/179030093-203fa07f-f6ae-4033-8120-04f6fea234d7.png)

![Abandoned mine 006](https://user-images.githubusercontent.com/43583994/179030025-a09d01f6-b24d-46d7-ac03-63f1ad69e212.png)

In fheroes2:

![Abandoned mine 007](https://user-images.githubusercontent.com/43583994/179030199-2adcc1d8-48d2-4663-984d-388fca9845f9.png)

https://user-images.githubusercontent.com/43583994/179030233-f22e7f9e-933f-4a6b-882c-091cd585deb3.mp4

**Edit 2022/07/16.**

In fheroes2:

**Abandoned Mine:**
- The number of ghosts can evolve over the combats, unlike the original game.
- There is a different number of ghosts than in the original game.
- There is a different number of ghost groups and the positioning of these ghost groups than in the original game.

In original game:

**Abandoned Mine:**

The ghosts can be divided into three configurations:
- 5 groups
- 4 groups
- 3 groups

In original game:

![Abandoned Mine H2 001](https://user-images.githubusercontent.com/43583994/179294197-cca1f9f5-6920-49c3-98ea-db4185de5d5f.png)

![Abandoned Mine H2 009](https://user-images.githubusercontent.com/43583994/179294227-0cb251b1-c926-40b3-8bb2-8c4b1cc62ed0.png)

![Abandoned Mine H2 003](https://user-images.githubusercontent.com/43583994/179294211-f60483d1-601c-4b52-8b54-72491bb996be.png)

The number of ghosts does not increase or decrease if the combat is not won and another combat is started on the same abandoned mine.
If there are 30 ghosts at the beginning of the combat and the hero reduces this number to 15 ghosts before fleeing, there will still be 30 ghosts at the next combat.
If there are 30 ghosts at the beginning of the combat and the number of ghosts is increased to 45 ghosts before the hero flees, there will still be 30 ghosts in the next combat.

The number of ghost groups and their positioning in the battlefield hexes is related to the position of the abandoned mine on the adventure map.
Repeating the combat in the same abandoned mine always gives the same number of groups and the same positioning of the ghosts, even if the scenario is completely restarted.
The number of ghosts is different when the scenario is completely restarted, but is always the same during the same scenario session.
This is certainly determined at the start of the scenario for all abandoned mines.

> @undef21 @LeHerosInconnu
> 
> It is mentioned here that the number of ghosts can be in the range of 30-60:
> 
> https://handbookhmm.ru/2-objects

This is consistent with what I have observed.

In original game:

30 ghosts:
![Abandoned Mine H2 003](https://user-images.githubusercontent.com/43583994/179294211-f60483d1-601c-4b52-8b54-72491bb996be.png)

60 ghosts:
![Abandoned Mine H2 001](https://user-images.githubusercontent.com/43583994/179294197-cca1f9f5-6920-49c3-98ea-db4185de5d5f.png)

_Originally posted by @LeHerosInconnu in https://github.com/ihhub/fheroes2/issues/5651#issuecomment-1185846862_

### Save file

Here are the save files:
[Abandoned mine 01.zip](https://github.com/ihhub/fheroes2/files/9113536/Abandoned.mine.01.zip)

### Additional info

Related issues: https://github.com/ihhub/fheroes2/issues/5662, https://github.com/ihhub/fheroes2/issues/5663.
Related discussion: https://github.com/ihhub/fheroes2/discussions/5664.

**Comment by LeHerosInconnu** [comment]
Hello @undef21,

> @LeHerosInconnu how ghosts should be placed in case total count < 5

Four groups of one creature (4 ghosts), or three groups of one creature (3 ghosts), or two groups of one creature (2 ghosts), or one group of 1 creature (1 ghost), always from the hexagon at the top of the screen. :)

**Comment by undef21** [comment]
Hm, according fheroes2 code the total ghosts count is 39-45. Does OG have same count?

**Comment by oleg-derevenetz** [comment]
> Hm, according fheroes2 code the total ghosts count is 39-45. Does OG have same count?

Please remember that ghosts may arrive also under the following circumstances:

1. Using the Haunt adventure spell (IIRC numbers are dependent on hero's Spell Power, but I'm not sure about this). Anyway I'm totally sure that their numbers may be less than 39 in this case;
2. When they defeat the hero's army, their  numbers may increase during the battle up to literally any numbers (depending on the size of the defeated army). All these additional ghosts then remain on the tile.

**Comment by undef21** [comment]
@oleg-derevenetz it's all true.
Look at src/fheroes2/maps/maps_tiles_quantity.cpp:815. The possible counts of ghosts are 39, 42, 45. And look at @LeHerosInconnu's screenshots. He attacked the mine twice or OG placed ghost with another way.

**Comment by LeHerosInconnu** [comment]
Hello @undef21 and @oleg-derevenetz,

I will do a more complete test on the subject. :)

**Comment by oleg-derevenetz** [comment]
@undef21 @LeHerosInconnu

It is mentioned here that the number of ghosts can be in the range of 30-60:

https://handbookhmm.ru/2-objects

**Comment by LeHerosInconnu** [comment]
Hello @undef21 and @oleg-derevenetz,

> Hello @undef21 and @oleg-derevenetz,
> 
> I will do a more complete test on the subject. :)

Here is what I have observed in Heroes 2:

**Abandoned Mine:**

The ghosts can be divided into three configurations:
- 5 groups
- 4 groups
- 3 groups

In original game:

![Abandoned Mine H2 001](https://user-images.githubusercontent.com/43583994/179294197-cca1f9f5-6920-49c3-98ea-db4185de5d5f.png)

![Abandoned Mine H2 009](https://user-images.githubusercontent.com/43583994/179294227-0cb251b1-c926-40b3-8bb2-8c4b1cc62ed0.png)

![Abandoned Mine H2 003](https://user-images.githubusercontent.com/43583994/179294211-f60483d1-601c-4b52-8b54-72491bb996be.png)

The number of ghosts does not increase or decrease if the combat is not won and another combat is started on the same abandoned mine.
If there are 30 ghosts at the beginning of the combat and the hero reduces this number to 15 ghosts before fleeing, there will still be 30 ghosts at the next combat.
If there are 30 ghosts at the beginning of the combat and the number of ghosts is increased to 45 ghosts before the hero flees, there will still be 30 ghosts in the next combat.

The number of ghost groups and their positioning in the battlefield hexes is related to the position of the abandoned mine on the adventure map.
Repeating the combat in the same abandoned mine always gives the same number of groups and the same positioning of the ghosts, even if the scenario is completely restarted.
The number of ghosts is different when the scenario is completely restarted, but is always the same during the same scenario session.
This is certainly determined at the start of the scenario for all abandoned mines.

> @undef21 @LeHerosInconnu
> 
> It is mentioned here that the number of ghosts can be in the range of 30-60:
> 
> https://handbookhmm.ru/2-objects

This is consistent with what I have observed.

In original game:

30 ghosts:
![Abandoned Mine H2 003](https://user-images.githubusercontent.com/43583994/179294211-f60483d1-601c-4b52-8b54-72491bb996be.png)

60 ghosts:
![Abandoned Mine H2 001](https://user-images.githubusercontent.com/43583994/179294197-cca1f9f5-6920-49c3-98ea-db4185de5d5f.png)

While I was at it, I also did a test on ghosts in the other places concerning them.

**Shipwreck:**

It works the same way as for the abandoned mine:
- The number of ghosts does not increase or decrease if the combat is not won and another combat is started on the same shipwreck.
- The number of ghost groups and their positioning in the battlefield hexes is related to the position of the shipwreck on the adventure map.
...
This is certainly determined at the start of the scenario for all shipwrecks.

In original game:

![Shipwreck H2 007](https://user-images.githubusercontent.com/43583994/179295331-0d32ef34-c5a3-45c1-804c-1295ee982de8.png)

![Shipwreck H2 003](https://user-images.githubusercontent.com/43583994/179295325-08152ea4-2257-4aba-8337-68541f80fff0.png)

![Shipwreck H2 001](https://user-images.githubusercontent.com/43583994/179295318-f3152421-47c5-4c00-b3a8-a7a07c0172f0.png)

The reward works this way:
- win the combat against 10 ghosts gives 1000 gold (30%).
- win the combat against 15 ghosts gives 2000 gold (30%).
- win the combat against 25 ghosts gives 5000 gold (30%).
- win the combat against 50 ghosts gives 2000 gold and 1 random artifact (10%).

Note: I have used the percentage given on this page: https://handbookhmm.ru/2-objects.

In original game:

10 ghosts:
![Shipwreck H2 004](https://user-images.githubusercontent.com/43583994/179295673-f365e04a-255a-43d2-add6-36a1d87408b5.png)

15 ghosts:
![Shipwreck H2 002](https://user-images.githubusercontent.com/43583994/179295664-82cfacd2-b0a3-45e0-9cb0-1a2b28ad0aff.png)

25 ghosts:
![Shipwreck H2 008](https://user-images.githubusercontent.com/43583994/179295678-11f75cef-6749-4a87-a244-89729ac59056.png)

50 ghosts:
![Shipwreck H2 022](https://user-images.githubusercontent.com/43583994/179295686-90672dab-e10d-4c7f-85b0-ddba3660475d.png)

**Haunt spell:**

Here again, it works in the same way as for the abandoned mine regarding the number of ghost groups and their positioning in the hexes of the battlefield, which is therefore related to the position of the mine on the adventure map.

The total number of ghosts generated corresponds to 4 ghosts multiplied by the hero's Spell Power value.

In the case of the Haunt spell, the number of ghosts is conserved over the course of the combats if the first combat is not won, and it can therefore increase or decrease if another combat is started on the same haunted mine.

In original game:

Kastore generates 12 ghosts (4 x 3 Spell Power) before attacking them:
![Haunt H2 001](https://user-images.githubusercontent.com/43583994/179295926-80360e5b-5545-4bfe-8884-0c90ae26989b.png)

Kastore reduced the number of ghosts to 6 before running away and attacking them again:
![Haunt H2 002](https://user-images.githubusercontent.com/43583994/179295939-69c3b91d-5ae1-4771-b265-f1ff09295d93.png)

Innocent peasants are sent to feed the ghosts for the purpose of the demonstration: :)
![Haunt H2 003](https://user-images.githubusercontent.com/43583994/179295949-91f46d03-d89b-4b8e-a2e0-98a314df70a5.png)

Kastore attacks again the ghosts whose number has been increased by the martyr imposed on these brave peasants, peace to their souls:
![Haunt H2 004](https://user-images.githubusercontent.com/43583994/179295964-91a67447-a63d-4452-a852-5dfc60662712.png)

I will do a test, certainly tomorrow, with fheroes2 to compare how it goes.
I will change the title and the original post of this issue after my test with fheroes2.

Here is the test scenario file:
[0 9930.zip](https://github.com/ihhub/fheroes2/files/9123469/0.9930.zip)

**Comment by LeHerosInconnu** [comment]
Hello @undef21 and @oleg-derevenetz,

> I will do a test, certainly tomorrow, with fheroes2 to compare how it goes.
> I will change the title and the original post of this issue after my test with fheroes2.

So I did my test with fheroes2 and here are my observations:

**Abandoned Mine:**
- The number of ghosts can evolve over the combats, unlike the original game.
- There is a different number of ghosts than in the original game.
- There is a different number of ghost groups and the positioning of these ghost groups than in the original game.

**Shipwreck:**
- The number of ghosts cannot evolve over the combats, as in the original game.
- There is a different number of ghosts than in the original game.
- There is a different number of ghost groups and the positioning of these ghost groups than in the original game.

**Haunt spell:**
- The number of ghosts can evolve over the combats, as in the original game.
- There is a number of ghosts similar to the original game.
- There is a different number of ghost groups and the positioning of these ghost groups than in the original game.

I will change the title and the original post of this issue and open new issues for the other places concerning ghosts.

I'm not against the idea that the number of ghosts evolves over the course of the combats and I'll open a discussion about it.
This could also be applied to other places on the adventure map, like the Graveyard, Dragon city, etc.

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , did we fix this issue?

**Comment by oleg-derevenetz** [comment]
Hi @ihhub not quite. Currently the Haunted mine and Abandoned mine in fheroes2 are the same, and number of ghosts is conserved between battles for both types of mines, while in the OG it is not conserved in case of Abandoned mine. The current behavior looks more natural to me (since the number of Ghosts is conserved in Shipwrecks too, so I have no idea why it is not conserved in Abandoned mines), but still it's the difference, so I didn't close this issue.

**Comment by Branikolog** [comment]
I think, the number of ghosts should be conserved for all similar objects.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog @ihhub The current logic of conservation of guardians is as described by @LeHerosInconnu here:

https://github.com/ihhub/fheroes2/issues/5651#issuecomment-1186160173

So it seems that eventually we will need to make Haunted mine and Abandoned mine different objects (now they are effectively the same) and apply a different logic regarding conservation of guardians between battles.
