### ISSUE TITLE
Ability to buy all army with hotkey or single button press

### ISSUE THREAD

**Issue by denierlexiese** [ihhub/fheroes2#5657]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

While in town it would be nice to have an auto buy all creatures / armies button.  Slightly tedious to click on each building to buy the army 1 by 1.

Thank you for implementing the auto max button though - that's a lot of time savings.

### Describe the possible solution

Thank you. Thank you.

### Additional info

Thank you for all your hard wor.

**Comment by ihhub** [comment]
Hi @denierlexiese , please open a **well** for this purpose.

**Comment by denierlexiese** [comment]
yes - i just read through the logs.  That's really nice the 'MAX' button in the well.  Thank you!
