### ISSUE TITLE
Cheat codes missing

### ISSUE THREAD

**Issue by athompso** [ihhub/fheroes2#5677]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Cheat codes from original HOMM2 appear to be missing entirely.  (Not sure if this should be a feature request... is the intent to produce an exact clone?  If so, then it's a bug report.)

### Save file

n/a

**Comment by ihhub** [comment]
Clone of #5265

**Comment by athompso** [comment]
Ah, sorry, I missed that.  Those.  Apparently search doesn't work on issues now????  Anyway, I'll see if I have enough skill to contribute to the codebase...
