### ISSUE TITLE
When resuming MIDI music after changing its volume, during the first milliseconds it is played at the volume at which it was paused instead of the new volume

### ISSUE THREAD

**Issue by oleg-derevenetz** [ihhub/fheroes2#5688]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

This bug was originally [reported](https://github.com/ihhub/fheroes2/pull/5628#issuecomment-1191308080) by @Branikolog.

> When we turn music off, we can hear the last sound of composition at the moment it stopped.
> 
> https://user-images.githubusercontent.com/55348946/180190739-bda32930-6561-4817-b565-361768198c89.mp4

### Save file

No save file needed.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub I just did a little investigation on this, and an interesting thing turned out. `Mix_Music` cached by our `MusicTrackManager` [stores the internal context](https://github.com/libsdl-org/SDL_mixer/blob/8c6c095c0800055a8eb88d43d8201a197dafabf0/src/music.c#L61-L71) of the music decoder backend. In the case of FluidSynth backend, it stores the current position in the music track. This means that when we call `Mix_FadeInMusic()`, the music playback continues from where we left off, so even if the `isMusicResumeSupported()` check fails (and it in fact fails) the music is always continues from the place when it was stopped 🙃To start the music from scratch we need to remake the `Mix_Music` structure from scratch. So the question is: is it worth doing this? Or maybe this issue (or maybe even "feature" in our case) can be considered as an upstream `SDL_mixer` issue and we should just report it to the upstream and left everything in our code as is?

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , I believe that it's easier and faster to make a fix ourselves. If we clear the full cache then all tracks will start from the beginning but if we clear only tracks we will still have their positions. So what we need is to clear cache upon changing music volume.

**Comment by oleg-derevenetz** [comment]
@ihhub The problem here is not only with the volume, but with the fact that currently MIDI music handled by FluidSynth is ALWAYS continued from the place it was stopped, even if we don't want it to happen :)

**Comment by ihhub** [comment]
@oleg-derevenetz , then no choice but to clean the cache 😒 It's not a big deal for performance to clean it as music volume is barely changed over time.

**Comment by oleg-derevenetz** [comment]
@ihhub I propose to use the same approach as with `Mix_Chunk`s - just don't cache them at all and always call `Mix_FreeMusic()` once the music playback is finished.

**Comment by ihhub** [comment]
It also would solve (with some modifications) the issue while switching music types the song starts from the beginning while in OG it continues.

**Comment by ihhub** [comment]
> @ihhub I propose to use the same approach as with `Mix_Chunk`s - just don't cache them at all and always call `Mix_FreeMusic()` once the music playback is finished.

Audio chunks are much smaller than music tracks by size so caching might be reasonable. However, we had no caching in the past and nobody complained about it so you are right. If we want some caching in the future we can cache original files (OGG files) if needed.

**Comment by oleg-derevenetz** [comment]
@ihhub

> It also would solve (with some modifications) the issue while switching music types the song starts from the beginning while in OG it continues.

? Currently the song of the same type continues just fine: for example when we switch from External to MIDI and then back to External, the External track continues. Or did you mean something else?

**Comment by ihhub** [comment]
@oleg-derevenetz , I meant we played 10 seconds MIDI, then switch to external and we should continue from that 10 seconds position. This is how it is implemented in OG.

**Comment by oleg-derevenetz** [comment]
@ihhub

> I meant we played 10 seconds MIDI, then switch to external and we should continue from that 10 seconds position. This is how it is implemented in OG.

Ah, yes. Didn't know that in OG it works this way. Anyway, I suppose we will be not able to use the `Mix_FadeInPos()` with MIDI :) The fact that MIDI music resumes now is pure coincidence, because it is resumed just because `Mix_Music` stores the decoder's internal state. We will not be able to control this process.

**Comment by ihhub** [comment]
I thought the most problematic part would be rendering...

**Comment by oleg-derevenetz** [comment]
@ihhub

> I meant we played 10 seconds MIDI, then switch to external and we should continue from that 10 seconds position. This is how it is implemented in OG.

Honestly I don't know why it is implemented in OG this way, because MIDI music tracks and External music tracks for the same location can be completely different :) I believe that linking a position to a specific track, as we have done, is a more correct solution.

**Comment by ihhub** [comment]
In this case let's keep the logic as it is in relation to different types of music.
