### ISSUE TITLE
Optimise Monster Monster::Rand(level_t level) function

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#57]
This function locates in `src/fheroes2/monster/monster.cpp` file. Here we allocate an array every time which is resource waste. Additionally, `GetLevel` function of the same class must be static so then we don't need to create an object of this class just to call this function. Furthermore, this function could contain just a map, then the call of this function would be even faster.

**Comment by bjauny** [comment]
I'll start working on this if it's OK.
