### ISSUE TITLE
Combat screen, incorrect positioning of the groups of wandering creatures

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#5700]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, there is an incorrect positioning of the groups of wandering creatures during combat.

In the original game, the walking and flying creatures can be divided into 3 groups, 4 groups or 5 groups.
Ranged creatures are always divided into 5 groups.
The creatures are distributed evenly in the groups, always starting with the group located at the top of the screen.

In fheroes2, this is not the case.
The creatures are not distributed uniformly in the groups.
The central group has sometimes a greater number of creatures than the other groups.
The ranged creatures are also sometimes combined into one group, which makes them easier to fight because, for example, a single flying troop can block them, or a Blind spell can control them more easily.

The position of the square on the adventure map is used to determine the number of groups and their position on the battlefield.
This is certainly determined at the start of the scenario for all squares.
The exception is that if a square contains ranged creatures, the creatures will be divided into 5 groups.

In original game:

![Knight 001](https://user-images.githubusercontent.com/43583994/180988546-a096eb6f-f621-4de0-aaf9-bc360b3ac1e1.png)
![Knight 002](https://user-images.githubusercontent.com/43583994/180988568-51394ada-0494-472f-8cce-f7f5e6eb8f05.png)
![Knight 003](https://user-images.githubusercontent.com/43583994/180988590-5a8a0f10-90ea-4dfd-b808-c8c618814efa.png)

![Warlock 014](https://user-images.githubusercontent.com/43583994/180988674-89afffe4-8f35-4ce6-b4b7-9361e1b5c85e.png)
![Warlock 011](https://user-images.githubusercontent.com/43583994/180988668-3710f677-025d-4418-9e6b-c9b15ec5612a.png)
![Warlock 016](https://user-images.githubusercontent.com/43583994/180988687-f7c11213-914c-43a5-8658-33191fd26ffd.png)

![Warlock 001](https://user-images.githubusercontent.com/43583994/180988653-5d6ac490-a408-4173-8d80-bf33714870cf.png)
![Ranged H2 001](https://user-images.githubusercontent.com/43583994/180988607-eab29152-f770-42ff-a887-8f2a3537871e.png)
![Ranged H2 005](https://user-images.githubusercontent.com/43583994/180988624-7ba7ff24-d2ad-42b6-80e8-934e790d17df.png)
![Ranged H2 007](https://user-images.githubusercontent.com/43583994/180988641-1fb962de-4697-415c-b0ce-9bf197ab5738.png)

In fheroes2:

![Knight fh2 002](https://user-images.githubusercontent.com/43583994/180989053-17aba26e-b048-473e-904f-c39418c136c0.png)
![Knight fh2 032](https://user-images.githubusercontent.com/43583994/180988976-5ccb4748-38a4-4a5b-90cc-1a7a4d9ba041.png)
![Warlock fh2 011](https://user-images.githubusercontent.com/43583994/180989039-dc5354d3-cbb0-409b-af00-c5a6e0f76bc6.png)

![Knight fh2 003](https://user-images.githubusercontent.com/43583994/180989068-d9e6755a-5541-4394-818b-37754b5c8569.png)

![Knight fh2 011](https://user-images.githubusercontent.com/43583994/180989075-04aedc29-6022-49fc-8c1b-4f0cc4a49529.png)
![Knight fh2 014](https://user-images.githubusercontent.com/43583994/180988958-42ba0154-2735-4383-b447-5fd86f99cd4d.png)
![Warlock fh2 002](https://user-images.githubusercontent.com/43583994/180989022-2fc129bd-301e-44a5-867b-85059888970d.png)
![Warlock fh2 001](https://user-images.githubusercontent.com/43583994/180989011-6958acaa-61e3-449a-ba55-f3ee40bf66ab.png)
![Ranged fh2 001](https://user-images.githubusercontent.com/43583994/180988994-19fa23bf-b910-425e-8ef4-495ebaa14bd8.png)
![Ranged fh2 005](https://user-images.githubusercontent.com/43583994/180989002-07edd092-c578-4347-82b8-65ce6ceba7bc.png)

### Save file

Here is the test scenario file:
[0 9928.zip](https://github.com/ihhub/fheroes2/files/9189078/0.9928.zip)

### Additional info

Version 0.9.17 5674

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu do you know the exact conditions for the appearance of an upgraded stack? Currently the upgraded stack always appears if the number of wandering monsters exceeds 20 and they can be upgraded.

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu , @oleg-derevenetz 
In #4478 I described some cases, I hope, it will be useful.

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz and @Branikolog

> Hi @LeHerosInconnu do you know the exact conditions for the appearance of an upgraded stack? Currently the upgraded stack always appears if the number of wandering monsters exceeds 20 and they can be upgraded.

I think it's about 50% of the time that upgraded creatures are present in the ranks of non-upgraded wandering creatures.
I had 4, 5, 6 and 7 cases out of 10.
It's independent of the number of wandering creatures.
And I think it is also depending on the position of the square on the adventure map (if the scenario is replayed completely from the beginning, the groups of upgraded creatures are present on the same squares).
The group of upgraded creatures is always located in the central hex, the third from the top (or bottom). :)

> Hi, @LeHerosInconnu , @oleg-derevenetz In #4478 I described some cases, I hope, it will be useful.

Your screenshots show cases of 3, 4 and 5 group arrangements with too few creatures to fill all the groups.
For example, if it's a 5 groups layout with only 3 creatures to distribute, there will be 3 groups of 1 creature from the top of the screen, the other groups cannot be "filled".

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , @Branikolog and @oleg-derevenetz , while making the conditions of monster distribution exactly the same as in the OG don't we make AI more predictable and less challenging? There are some "stupid" places to put monsters but making archers always in 5 groups is 100% predictable. Also applies for uniform distribution of numbers.

I do not want to create a long discussion topic for this as the corresponding pull request contains some useful fixes but from my perspective it is a bit of downgrade for AI difficulty.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub

> There are some "stupid" places to put monsters but making archers always in 5 groups is 100% predictable.

Dividing the shooters into the maximum number of stacks is really worth it, because it will be difficult for the opponent to block them all at once, unlike the situation when there are only 3 archer stacks, for example. So it looks more challenging.

> Also applies for uniform distribution of numbers.

The previous distribution logic was predictable as well, just with that logic the central stack always got all the "extra" units (the remainder). Now the remainder is uniformly distributed among the upper stacks.
