### ISSUE TITLE
Use extended fonts at least for English

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#5712]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

If users select English as game's language then all maps which are made for other languages will have question marks instead of real symbols which reduces user's experience.

### Describe the possible solution

If the primary language of the game is selected as English we could use some extended font like from Polish, French, Russian and etc. This is not an ideal solution but it could cover at least a part of maps being displayed properly.

**Comment by oleg-derevenetz** [comment]
How should it help that the player will see unreadable sequences of "real" symbols on the screen instead of question marks (if some extended font that doesn't match the map's locale will be used)?

**Comment by ihhub** [comment]
This is a valid question. I don't have proper solution to cover all cases. Seeing some weird characters is better than question marks.

Anyway, you're right. I will close it for now till we find an acceptable solution.
