### ISSUE TITLE
Implement visual clue for Dimension Door

### ISSUE THREAD

**Issue by bmorel** [ihhub/fheroes2#5714]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

For a start, I'm sorry but I half-lied when checking "￼ I've checked that there aren't other open issues on the same topic. ", I have not checked all the issues, only searched for "Dimension door" in tracker, and no issue there seems related to this.

Now, on topic.

In HoMM2, Dimension Door spell was limited to visible map. Fheroes2 support higher resolutions by showing more of the adventure map instead of scaling.
This is nice, but this also removes the implicit visual clue for it's range.

### Describe the possible solution

What I would suggest is to "shade" the part of displayed map which is not reachable from this spell when selecting a place.

**Comment by ihhub** [comment]
Hi @bmorel , which version of fheroes2 are you using? Unreachable area was implemented like 2 years ago.

**Comment by Branikolog** [comment]
Hi!
It currently works like this:
![image](https://user-images.githubusercontent.com/55348946/183091143-8db23a7f-eaec-4f84-9ed2-796e48e3a3b2.png)

**Comment by bmorel** [comment]
> fheroes2 engine, version: 0.9.17

Did I missed this feature then? Is there is a way to "cheat" and have it? Maybe I simply didn't noticed it for some reason, if so, sorry for the noise.

**Comment by Branikolog** [comment]
@bmorel 
It's simply to check: just run the engine and initiate the spell. If something isn't working - paste screenshot here for further investigation. ;)

**Comment by bmorel** [comment]
> It's simply to check: just run the engine and initiate the spell

I'd be glad to, but how? I do not have savegames with that spell right now

**Comment by LeHerosInconnu** [comment]
Hello @bmorel,

> > It's simply to check: just run the engine and initiate the spell
> 
> I'd be glad to, but how? I do not have savegames with that spell right now

Here is a test scenario: [0 9988.zip](https://github.com/ihhub/fheroes2/files/9271198/0.9988.zip).
Visit the castles with the hero to learn the desired spells. :)

**Comment by Branikolog** [comment]
@bmorel 
So, you've half lied, when you missed visual clue for "Dimension Door". :) Because it is implemented in game long ago. )

**Comment by ihhub** [comment]
Closing this issue as false alarm.
