### ISSUE TITLE
More portable generation of locale files?

### ISSUE THREAD

**Issue by txgk** [ihhub/fheroes2#5735]
### Your question

Hi, I'm maintainer of fheroes2 package in Alpine Linux and so far I have a trouble with processing of some files in `files/lang`.

To be more precise:

* `hu.po`, `lt.po`, `nl.po`, `tr.po` files are processed with `//TRANSLIT` encoding suffix. This feature is not supported by musl version of iconv;
* `ro.po` file is using "ISO-8859-16" charset. It fails to build just because "ISO-8859-16" name is not portable (that's what iconv on my system says);
* `fr.po` file when processed yields lots of "invalid multibyte sequence" messages and quits make with exit code 1;

My current solution to all these issues is just removing problematic `.po` files, namely `hu.po`, `lt.po`, `nl.po`, `tr.po`, `ro.po` and `fr.po` and then doing `make -C files/lang`. This is not very elegant solution, you see :)

So my question is: can you consider doing some of the localization with other implementations of iconv in mind? I think it can be very useful for musl-based Linux distributions overall.

Thanks for fheroes2 to everyone who is involved!

**Comment by oleg-derevenetz** [comment]
Hi @txgk have you tried to use portable iconv (based on GNU libiconv) instead of libc-based iconv? It is designed specifically for systems with oversimplified/incomplete iconv implementations in libc.

**Comment by undef21** [comment]
Hi @txgk 

>ro.po file is using "ISO-8859-16" charset. It fails to build just because "ISO-8859-16" name is not portable

Does it fail or just put warning?

>fr.po file when processed yields lots of "invalid multibyte sequence" messages and quits make with exit code 1

Looks like the locale sets to LC_ALL=C in your build environment. Could you try to run `LC_ALL=UTF-8 make -C files/lang`?

>My current solution to all these issues is just removing problematic .po files, namely hu.po, lt.po, nl.po, tr.po, ro.po and fr.po and then doing make -C files/lang. 

Also you can set only needed translations, eg : `make -C files/lang be.mo bg.mo`

**Comment by txgk** [comment]
> Hi @txgk have you tried to use portable iconv (based on GNU libiconv) instead of libc-based iconv? It is designed specifically for systems with oversimplified/incomplete iconv implementations in libc.

I just tried gnu-libiconv package but I needed to replace all `iconv` strings in `files/lang/Makefile` with `gnu-iconv`. Can you please add a variable like ICONV_PROGRAM to this Makefile so that instead of me doing:
```
sed -i s/iconv/gnu-iconv/g files/lang/Makefile
make -C files/lang
```
I could just:
```
make -C files/lang ICONV_PROGRAM=gnu-iconv
```
It is a solution, it works now. Thanks. But I hope someday it will be doable without this TRANSLIT stuff. After all, how do other locales cope without it?

**Comment by txgk** [comment]
> Does it fail or just put warning?

It does put warning and produces bad `ro.mo` with the following contents: [ro.txt](https://github.com/ihhub/fheroes2/files/9307879/ro.txt) (it has `.txt` extension because stupid GitHub won't allow me to upload files with `.mo` extension).

> Looks like the locale sets to LC_ALL=C in your build environment. Could you try to run LC_ALL=C.UTF-8 make -C files/lang?

I found out what was the problem: busybox sed can't process some unicode characters so it yields these warnings. Using GNU sed fixed generation of French locale.

**Comment by undef21** [comment]
Msgfmt has the hardcoded list of portable encodings, so it puts warning
about 8859-16

Does ro.mo built correctly with gnu iconv?

чт, 11 авг. 2022 г., 13:20 Grigory Kirillov ***@***.***>:

**Comment by txgk** [comment]
No, when I use `gnu-iconv` it still produces invalid `ro.mo`.

**Comment by undef21** [comment]
Does `gnu-iconv -l` output contain iso-8859-16?

чт, 11 авг. 2022 г., 14:33 Grigory Kirillov ***@***.***>:

**Comment by txgk** [comment]
Yes

**Comment by undef21** [comment]
> Or it is supposed to be like that?

Oh. This is expected. Some translation is placeholders because noone translate strings yet.

**Comment by oleg-derevenetz** [comment]
@txgk

> But I hope someday it will be doable without this TRANSLIT stuff. After all, how do other locales cope without it?

Other languages have their own fonts (which is either taken from the localized data files of the original game or auto-generated by our engine) with the necessary additional characters. But if there is no font for some language, then it needs to be at least transliterated to use it with the original English font (which is always present in original game resources in any localization).

**Comment by txgk** [comment]
Okay, thanks everyone. Now all locales are generated properly despite warning about "ISO-8859-16".
