### ISSUE TITLE
Ignore zero-length .smk files

### ISSUE THREAD

**Issue by DmitrySokolov** [ihhub/fheroes2#5741]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Ignore zero-length .smk files as the original heroes2.exe does.

Now the app crashes when it tries to read any zero-length .smk file.

### Save file

N/A

**Comment by oleg-derevenetz** [comment]
Hi @DmitrySokolov  First of all, where do these zero-size SMK files come from? They are hardly zero size in any version of the original game assets.

**Comment by DmitrySokolov** [comment]
Hi,

The archive came from 1990's. I see some .smk files have the size of 0, and the game works ok. But launching fheroes2.exe with the same game data causes a crash.

**Comment by DmitrySokolov** [comment]
I've deleted all 0-size files, and fheroes2.exe is working now.
