### ISSUE TITLE
CRASH in ui_dialog.cpp when showing Message (Windows)

### ISSUE THREAD

**Issue by XcodeWarrior** [ihhub/fheroes2#5742]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

ui_dialog.cpp   -  method showMessage()  
-----------------------------------------
Line ~123
rowId.emplace_back( rowId.back() ) - has Buggy behaviour (at least in Visual Studio)

Your intention is obvious - Duplicate the Back value
BUT during insertion vector will be REALLOCATED that makes rowId.back() REFERENCE invalid

Before this statement:
rowId = { 0 }; // 1 element

After this statement:
rowId = { 0, 0xdddddddd }; // 2 elements

Later in this method CRASH because of Access Violation

### Save file

ui_dialog.cpp   -  method showMessage()  
Line ~123: rowId.emplace_back( rowId.back() ) // has Buggy behaviour (at least in Visual Studio)

**Comment by ihhub** [comment]
Hi @XcodeWarrior , when exactly does it crash? Which call of this function?

**Comment by oleg-derevenetz** [comment]
Hi @ihhub this should be some dialog with many elements (>2). `std::vector` implementation may preallocate some capacity, but if it is forced to reallocate on `emplace_back()` call, then the described scenario may happen.

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , I understand that this is a bug. I am just curious why nobody has encountered it before.

**Comment by oleg-derevenetz** [comment]
@ihhub Sphinx may in theory give more than 2 types of rewards (if they are resources).

**Comment by XcodeWarrior** [comment]
In my particular case I found the issue in 2 cases:
- after picking the Campfire with 2 resources
- and when visiting a building that increases the morale (show 2 flying birds)

> ... why nobody has encountered it before ?

Because actual behaviour is greatly depends on the STL-implementation and C++ Runtime you are using

1) Looks like my std::vector<> did not reserve many elements after adding the first element
2) After Releasing the initial memory block the Debug version C++ runtime in MSVC zapping released block with 0xdddddddd
( all newly heap allocated blocks are zapped with 0xcdcdcdcd )

In your environment, either std::vector() reserved enough capacity to store some additional elements
or after re-allocating the memory, the released block was not immediately overwritten, that created illusion of proper using the already deallocated element

By the way, please note that in your code there are 3 places like following:
  monsters.emplace_back( monsters.back().GetUpgrade() );
This works properly because  .GetUpgrade() call creates a completely new instance of the unit

**Comment by ihhub** [comment]
Hi @XcodeWarrior , would you like to create a pull request for this?

**Comment by XcodeWarrior** [comment]
No, thank you for proposal
It's up to you to provide a suitable fix here
