### ISSUE TITLE
Disable console window on Windows when fheroes2.exe starts

### ISSUE THREAD

**Issue by DmitrySokolov** [ihhub/fheroes2#5744]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

It seems that `add_executable` is called without `WIN32` option (https://cmake.org/cmake/help/latest/command/add_executable.html), so a console window is opened when fheroes2.exe starts.

### Describe the possible solution

Is it possible to disable it, and redirect output to a log file instead?

**Comment by ihhub** [comment]
The answer lies in your question. Logs must be saved in a separate file. Plus we use SDL, it is not a normal WIN32 app. It creates a separate window which is the main app. However, it might be possible to run without the console.

**Comment by ihhub** [comment]
We can start logging into a separate file for Windows and hide the console window. However, it's good to do this only for release build as for debugging such logs are extremely useful.

**Comment by 44zb** [comment]
Hi, console window can be hidden with [ShowWindow function](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-showwindow). 
For logging can used same way as on Nintendo Switch.

this is my solution #5890
