### ISSUE TITLE
Battle screen, triggered low morale should make other creature with the same speed to act

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#5745]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

If a creature with triggered low morale skips its turn and hero has one more creature with the same speed, then turn should be transferred to the creature of the same player. If next creature also skips its turn due to low morale, the next one with the same speed should be able to make its action. Until one creature of the same speed don't have low morale triggered.
![image](https://user-images.githubusercontent.com/55348946/184346487-296b905b-a8c1-487a-ae01-407ba89f894c.png)
![image](https://user-images.githubusercontent.com/55348946/184349551-c4e6d44b-7907-4ecd-a794-6dc01e5e90e1.png)

Currently fheroes2 works like Heroes 3: if creature has low morale triggered then next creature is going to act according to battle que.

If a creature skips its turn due to low morale and its speed is higher, than speeds of the rest, then opponent creature should make its action (in a case opponent's creatures have higher or the same speed comparing the rest of the current player).
![image](https://user-images.githubusercontent.com/55348946/184353170-843ed6b1-be2c-4d93-8068-868f5d32040d.png)
(Second wolves skipped their turn due to low morale, so Pikemen are able to act now.)

Also, I want to mention that in a case the last creature has low morale triggered, then turn is passed to opponent creature in the beginning of the next turn. (In a case both sides have same speed first-acting creatures.)

### Save file

[Low morale.zip](https://github.com/ihhub/fheroes2/files/9315976/Low.morale.zip)

**Comment by oleg-derevenetz** [comment]
OMG, another "not like all" illogical HoMM2-specific trickery.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
If we forget about the later games of Homm series, it doesn't look so unnatural. Just different. :)
I can say here, that within H3 3DO changed the rules. :)

**Comment by oleg-derevenetz** [comment]
> I can say here, that within H3 3DO changed the rules. :)

And maybe it was just a bug that was fixed in subsequent versions :)

**Comment by Branikolog** [comment]
> And maybe it was just a bug that was fixed in subsequent versions :)

Bug? Heroes2 has no bugs. It has features. ;)

**Comment by oleg-derevenetz** [comment]
> If a creature skips its turn due to low morale and its speed is higher, than speeds of the rest, then opponent creature should make its action (in a case opponent's creatures have higher or the same speed comparing the rest of the current player).

This is not quite true:

https://user-images.githubusercontent.com/32623900/184560584-cf9c0b4b-6c4b-4e3e-a290-9055745897fe.mp4

> Also, I want to mention that in a case the last creature has low morale triggered, then turn is passed to opponent creature in the beginning of the next turn. (In a case both sides have same speed first-acting creatures.)

This is not quite true as well:

https://user-images.githubusercontent.com/32623900/184560619-4d22a38f-44bb-4410-91d2-4a07aad20012.mp4

I believe that the ACTUAL logic is as follows: a unit that skipped a turn due to bad morale is considered as not getting a turn at all, so the "fastest unit of the opposing side goes first" logic just skips it: if the LAST unit that performed a fully-fledged action belongs to the attacker, then the next unit after the panicked one will be from the defender (all other conditions being equal), and vice versa.

**Comment by Branikolog** [comment]
> > If a creature skips its turn due to low morale and its speed is higher, than speeds of the rest, then opponent creature should make its action (in a case opponent's creatures have higher or the same speed comparing the rest of the current player).
> 
> This is not quite true:

Sorry, you're right. `or the same` is wrong here. If the left side had orcs instead of peasants, that they'd get a turn. While both peasants with te same speed are left on the both sides, so the right side is going to act. 

>I believe that the ACTUAL logic is as follows: a unit that skipped a turn due to bad morale is considered as not getting a turn at all,
👍 

> > Also, I want to mention that in a case the last creature has low morale triggered, then turn is passed to opponent creature in the beginning of the next turn. (In a case both sides have same speed first-acting creatures.)
> 
> This is not quite true as well:

Hmmm.
It seems to be some difference according to how many creatures are left: in a case the last side has two creatures that are going to make actions, and the last creature has low morale triggered, then turn is passed to the opposite side. On your example, peasant skipped his turn, but the previous creature, who made action, belongs to opposite side. That's why after low morale of peasants bone dragons from the same side received turn.

https://user-images.githubusercontent.com/55348946/184831197-e9c573f5-a59c-4ebb-a496-69f42bac40d2.mp4

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog and @oleg-derevenetz,

> This is not quite true as well:
> 
> https://user-images.githubusercontent.com/32623900/184560619-4d22a38f-44bb-4410-91d2-4a07aad20012.mp4
> 
> I believe that the ACTUAL logic is as follows: a unit that skipped a turn due to bad morale is considered as not getting a turn at all, so the "fastest unit of the opposing side goes first" logic just skips it: if the LAST unit that performed a fully-fledged action belongs to the attacker, then the next unit after the panicked one will be from the defender (all other conditions being equal), and vice versa.

In this case, the fifth troop on the left, the ten peasants had a bad morale and this troop is therefore ignored.
The last troop to have played is the fifth troop on the right, the ten peasants, so the bone dragons troop on the left get the hand the next turn.

> Hmmm.
> It seems to be some difference according to how many creatures are left: in a case the last side has two creatures that are going to make actions, and the last creature has low morale triggered, then turn is passed to the opposite side. On your example, peasant skipped his turn, but the previous creature, who made action, belongs to opposite side. That's why after low morale triggered for peasants allowed bone dragons from the same side to receive a turn.
> 
> https://user-images.githubusercontent.com/55348946/184831197-e9c573f5-a59c-4ebb-a496-69f42bac40d2.mp4

In this case, the fifth troop on the right, the hundred goblins, had a bad morale and this troop is therefore ignored.
The last troop to have played is the fourth troop on the right, the hundred goblins, so the pikemen troop on the left gets the hand the next turn.
