### ISSUE TITLE
Battle screen, snow object has glowing pixels

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#5746]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

There're a few glowing pixels near rock on a snow battlefield.
![Gloww](https://user-images.githubusercontent.com/55348946/184360409-29d897d5-0964-4efb-b575-e95d8b18c898.png)

### Save file

[Low morale.zip](https://github.com/ihhub/fheroes2/files/9316486/Low.morale.zip)

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

This problem comes from the "0000.bmp" file in the "COVR0010.ICN" file.

There are many other graphic problems listed in [this thread](https://heroes2.forumactif.com/t303-changes-to-the-game-s-graphics). :)

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu !
It would be nice if someone, who knows all the tricks of fheroes2 engine, like @ihhub , could fix all those graphics. :D

**Comment by ihhub** [comment]
No comments.
