### ISSUE TITLE
NaN in fheroes2::GetEuclideanLine()

### ISSUE THREAD

**Issue by oleg-derevenetz** [ihhub/fheroes2#5755]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

macOS

### Describe the bug

Sometimes during the siege, when the tower tries to shoot at a unit located close to it, UB sanitizer may report the following attempt to convert NaN to int:

```
14:12:41: [DBG_BATTLE]	ApplyActionTower:  tower: 1, attack to Unit: [ 7 Paladins, Blue, pos: 7, -1 ]
tools.cpp:267:50: runtime error: nan is outside the range of representable values of type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior tools.cpp:267:50 in 
tools.cpp:267:89: runtime error: nan is outside the range of representable values of type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior tools.cpp:267:89 in 
../fheroes2/battle/battle_interface.cpp:2954:124: runtime error: signed integer overflow: -2147483648 - 18 cannot be represented in type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../fheroes2/battle/battle_interface.cpp:2954:124 in 
image.cpp:264:37: runtime error: negation of -2147483648 cannot be represented in type 'int32_t' (aka 'int'); cast to an unsigned type to negate this value to itself
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior image.cpp:264:37 in 
image.cpp:270:19: runtime error: signed integer overflow: 18 - -2147483648 cannot be represented in type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior image.cpp:270:19 in 
14:12:41: [DBG_BATTLE]	ApplyDamage:  14 to Unit: [ 7 Paladins, Blue, pos: 7, -1 ] and killed: 0
```

It seems that sometimes both `length` and `dx`/`dy` may become zero, and in this case here:

https://github.com/ihhub/fheroes2/blob/c1002c71e0c8a897c07e7f4da0781a0aa75c9d08/src/engine/tools.cpp#L260-L261

either `moveX` or `moveY` (or both) may become NaN. But I'm not sure how to better fix it in this particular case. Hi @ihhub what do you think?

### Save file

None available.

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , this is interesting. This function was made before us. I will take a look.
