### ISSUE TITLE
Battle screen, battle log doesn't show the info regarding Vampires special ability

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#5758]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

![image](https://user-images.githubusercontent.com/55348946/184878811-28bdb36d-7cf8-4289-9df8-ed55be2eca97.png)
There's no info in battle journal whether vampires resurrected or not after attack.

### Describe the possible solution

In a case some vampires resurrected there should be a message in battle log like:
"X vampires revived."

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

Yes, something like [this](https://github.com/ihhub/fheroes2/discussions/3482). :)

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu !
Once again I forgot to check discussions. :)
Thanks for pointing on more precise info.
