### ISSUE TITLE
View Puzzle screen, wandering creatures and campfires should not be displayed

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#5780]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, wandering creatures and campfires should not be displayed in the View Puzzle screen.

In original game:

![View puzzle creatures 001](https://user-images.githubusercontent.com/43583994/186418589-97f606b3-dc26-4b4a-9d92-46f383f34abb.png)

In fheroes2:

![View puzzle creatures 002](https://user-images.githubusercontent.com/43583994/186418628-21c472f7-8141-4277-9820-84491778418a.png)

### Save file

Here is the test scenario file:
[0 9991b.zip](https://github.com/ihhub/fheroes2/files/9416019/0.9991b.zip)

**Comment by Branikolog** [comment]
Hello, @LeHerosInconnu !
I've noticed, that both original game and fheroes2 show gatherable objects on the sea, like chests etc. 
I'm concerning whether they should be shown on a puzzle map, since they could disappear.

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

> Hello, @LeHerosInconnu ! I've noticed, that both original game and fheroes2 show gatherable objects on the sea, like chests etc. I'm concerning whether they should be shown on a puzzle map, since they could disappear.

I think they left them visible because the sea is completely similar and that these objects can therefore give a clue when the puzzle is only revealed in part and that part is only sea.
I personally agree with this. :)

**Comment by Branikolog** [comment]
@LeHerosInconnu 
Okay. But these objects could disappear. Do original and fheroes2 puzzle maps update if someone collect all sea items on your screenshot?
I think, it's a bit weird, that campfires, resources and land chests shouldn't be drawn on the map, but sea objects are.
To my personal point, a large water part of the puzzle map makes it easier to dig, once player spot the area, since water is the place, where no one manages to dig. ;) Also, sea on a puzzle map shows, that you should seek for UA somewhere near beach, not in the middle of the continent.
So there're some pros and cons for both our theories. :)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> @LeHerosInconnu Okay. But these objects could disappear. Do original and fheroes2 puzzle maps update if someone collect all sea items on your screenshot?

Sea objects are no longer displayed in the puzzle when they have been captured.
This is also a way to get clues. :)

> I think, it's a bit weird, that campfires, resources and land chests shouldn't be drawn on the map, but sea objects are. To my personal point, a large water part of the puzzle map makes it easier to dig, once player spot the area, since water is the place, where no one manages to dig. ;) Also, sea on a puzzle map shows, that you should seek for UA somewhere near beach, not in the middle of the continent. So there're some pros and cons for both our theories. :)

The ultimate artifact can be on a small island surrounded by sea. :)
Or the map has land in its upper part and its lower part is sea.
The utimate artifact is therefore near the coast, but the coast is the whole width of the map.
