### ISSUE TITLE
Ghost Planet 1.1 has invalid victory conditions

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#5792]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Ghost Planet 1.1 which comes with PoL addon has invalid scenario conditions which we completely ignore. Somehow we have alliance with other players but at the same time Victory conditions is to defeat everyone. I think if the victory condition to defeat everyone alliances should be ignored as it is done in the original game for this map.

### Save file

No need.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub

> Somehow we have alliance with other players but at the same time Victory conditions is to defeat everyone.

Are you sure about that? Unions are used only when victory condition is `VICTORY_DEFEAT_OTHER_SIDE`:

https://github.com/ihhub/fheroes2/blob/ac68abe2d9ea9009dffc582cc9cdb8ea5739fa31/src/fheroes2/maps/maps_fileinfo.cpp#L367-L392

This issue looks like a purely cosmetic due to #5793.

**Comment by ihhub** [comment]
Closing this issue as invalid.
