### ISSUE TITLE
Better translation

### ISSUE THREAD

**Issue by shprotru** [ihhub/fheroes2#5806]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Currently there is no translation of messages from campaigns. We can play translated campaign only one way - use relevant resources. But what to do with custom maps or lack of such resources?

### Describe the possible solution

We need to make small change, always ask a game engine to translate passed text.

![translation](https://user-images.githubusercontent.com/53114202/188270420-b38efdc0-c253-4b7f-88ef-3d7efa29890a.png)

Players can see untranslated text and update translation files.

**Comment by ihhub** [comment]
Hi @shprotru , please give more explanatory title for the issue. The current title is not clear.

There is no way that we would be able to translate campaigns because they are a part of game resources and we have no rights to distribute them.
