### ISSUE TITLE
Artifact disappears after digging if the hero artifact slots are full

### ISSUE THREAD

**Issue by Districh-ru** [ihhub/fheroes2#5819]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

When the hero is full with artifacts and you try to dig an artifact the game first says that is ni space for an artifact, than the game undigs it and the artifact flushes. So that some maps become uncompletable.

### Save file

[Good_8_gid_bug.zip](https://github.com/ihhub/fheroes2/files/9541891/Good_8_gid_bug.zip)

### Additional info

My example - map Good_8 (main campaign):
1. My hero is full with artifacts
![hero full](https://user-images.githubusercontent.com/113276641/189515235-72670f13-2961-4fde-b7d5-1c2a78ab13e3.png)

2. I try to dig the artifact: 
![cannot pick](https://user-images.githubusercontent.com/113276641/189515270-3aaf8ee1-4e11-448d-9f88-07a7d95b1efa.png)

3. Than the game undigs it and says the false congratulations!
![false congratulations](https://user-images.githubusercontent.com/113276641/189515354-e80d3e3e-3215-4d72-9175-a591a1a0c7bf.png)

4. But the artifact is not picked by the hero and it disappears. If I make a free space for artifacts (give some to another hero) and try again to dig, the game says that there is no more artifatcs under ground.
![nothing there](https://user-images.githubusercontent.com/113276641/189515343-88fa1e93-ac4a-41ea-83a4-ba710b079bfa.png)

After that I cannot complete this map and I have to reload before the first digging.

**Comment by ihhub** [comment]
Hi @Districh-ru , does it work the same as in the original game? If yes then we no need to change anything in fheroes2 logic.

**Comment by Alucard648** [comment]
I think, digging should require a free slot for artifact, otherwise uoy get message, like "You can`t fit a new artifact, should you dug up one".

**Comment by ihhub** [comment]
This makes sense.

**Comment by Districh-ru** [comment]
> Hi @Districh-ru , does it work the same as in the original game? If yes then we no need to change anything in fheroes2 logic.

I've tried the same in original game:
When you try to dig the artifact and you have no place for it the game displays:

![orig game](https://user-images.githubusercontent.com/113276641/189519892-512a951d-0e5b-4923-ac33-8eaef9aa5608.png)

And the artifact remains laying under ground (digging is canceled).
