### ISSUE TITLE
Crash on Windows 7

### ISSUE THREAD

**Issue by msjasinski** [ihhub/fheroes2#5824]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Crash on Windows 7 64 bit, when fheroes2 is opened. New version and yesterday's nightly built - so it must be something relatively new.

Terminal reading:
![fheroes crash](https://user-images.githubusercontent.com/4431194/189542406-0b252353-67a9-4642-b5d8-2cf395fed732.png)

On my computer, there is no and never was a pathname D:\a\fheroes2\...

### Save file

N/A

**Comment by oleg-derevenetz** [comment]
Hi @msjasinski it looks like some of your SMK files (in `ANIM` or `DATA` folders) are corrupted (maybe zero size).

**Comment by msjasinski** [comment]
Yes, that was it. Thanks! I deleted empty files and the problem (crash) was gone.

Closing the report.

Keep up the good work!
