### ISSUE TITLE
Dimension Door spell cancelling button.

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#584]
In the original game we have separate button to cancel the spell in right upper corner.
Now we have to press right mouse button to cancel the spell.
![Door](https://user-images.githubusercontent.com/55348946/82725693-507d7880-9ce7-11ea-8baa-509a76f752eb.jpg)
![Door2](https://user-images.githubusercontent.com/55348946/82725695-51aea580-9ce7-11ea-9664-98d5bd30ee4a.jpg)

**Comment by ihhub** [comment]
We need to use `viewddor` resource file within **Interface::Radar** class.
