### ISSUE TITLE
Scroll bar size doesn't update for the map list until refresh

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#5841]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Scroll bar appears as small, as it should be for the whole map list until we refresh map filter.

https://user-images.githubusercontent.com/55348946/190853573-39c50928-532d-46e7-8a6e-64e6d07fd071.mp4

### Save file

None.

**Comment by Districh-ru** [comment]
Hi @Branikolog, is this issue still exist in current master build?
I cannot reproduce it: when I press SELECT the ALL button is always selected and scroll bar size is OK.

https://user-images.githubusercontent.com/113276641/215266077-a4aed545-df59-45ff-8c44-646583705826.mp4

**Comment by Branikolog** [comment]
Hi, @Districh-ru !
The issue is gone.
I think, map filter should be maintained, but this is not related to this issue. :)
