### ISSUE TITLE
Under certain circumstances, extra terrain sounds are heard

### ISSUE THREAD

**Issue by oleg-derevenetz** [ihhub/fheroes2#5847]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Watch the video with sound turned on. When Maximus is near the mine and focus is switched from Maximus to Debug Hero, extra mine sound is heard. When Maximus is moved away from the mine and focus is switched from Maximus to Debug Hero, no extra mine sound is heard. This is with 3D Audio feature enabled, when it is disabled, no extra mine sounds are heard.

https://user-images.githubusercontent.com/32623900/190902089-ef723616-c979-4ecc-8df6-e021841170c0.mp4

### Save file

[!!!.zip](https://github.com/ihhub/fheroes2/files/9593973/default.zip)

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz !
Isn't it the sound of crystal mine near debug hero? We can hear two separate sounds, as there're two mines nearby.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog the thing is, when I move Maximus away from his mine and select the Debug Hero, the extra mine sound is not heard anymore, even though Debug Hero himself stands in place. That extra mine sound somehow depends on the position of another hero, and this should not be.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
After you move Maximus I think I can hear second mine on a debug hero. But the sound is almost simultaneous with the first one. Sounds like echoed. Or am I wrong?

**Comment by oleg-derevenetz** [comment]
@Branikolog I hear two mines on Debug Hero before I move Maximus away from his mine and just one mine after Maximus movement.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Ok. Probably, my notebook's speakerphones make an impression of the echoed mine.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub how many mines you hear in this video while Debug Hero is selected - before and after Maximus movement?

**Comment by ihhub** [comment]
I clearly hear 2 sounds of Mine played in parallel.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub

> I clearly hear 2 sounds of Mine played in parallel.

Do you hear them on Debug Hero after Maximus was moved away from the mine? I hear 2 mines before that and just 1 mine after that.

**Comment by ihhub** [comment]
First focusing - obviously 2 sounds with a delay in time
Second focusing - 2 sounds with like 50-100 ms delay in between
Third focusing - 2 sounds with 20 (?) ms delay in between (like echoing)

I believe the problem is in a fact that multiple sounds a played with probably broken 3D audio feature off.

**Comment by ihhub** [comment]
@oleg-derevenetz , I tested SDL 1 and SDL 2 and have no issues with sounds. Are you sure that 3D audio is off?

**Comment by Branikolog** [comment]
Hi, @ihhub !

>This is with 3D Audio feature enabled, when it is disabled, no extra mine sounds are heard.

**Comment by Branikolog** [comment]
@ihhub 

I think the problem is that sometimes similar sounds play with a tiny delay. Could we set a fixed delay for the same sounds?

**Comment by ihhub** [comment]
I believe to do this we need to know an exact algorithm based on positioning: delay in sounds in comparison with distance to it.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub @Branikolog if there are always two mine sounds are played, just with different delay between them, then there is no issue. I thought that there was just one mine sound sometimes, maybe I was unable to distinguish that small delay. For me, it was heard like just one mine sound.

**Comment by ihhub** [comment]
Marking this as an improvement.

**Comment by oleg-derevenetz** [comment]
Closing this issue because there is no real issue.
