### ISSUE TITLE
Implement checks for image()[]

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#5848]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Other

### Describe the bug

Currently we are using `image()[]` to generate new or edited images on the fly in `agg_image.cpp`. However, we need checks for this since it could lead to crashes if it tries to access an array element out of bounds.

Initial discussion here with example of such a case here:
https://github.com/ihhub/fheroes2/pull/5836#discussion_r973714517

### Save file

Not needed.

**Comment by bjauny** [comment]
Looking at the code, a pair of get/set functions to get/set values in the array could be easily arranged.

Should the assert macro be used to check the value of position or do you want to escalate an exception?

**Comment by ihhub** [comment]
Hi @bjauny , the solution is simple as it looks: create a function which will accept a const reference to an image and a pixel position. If the position is out of image size then return 0. No assertion or exception is needed as this function works with assets which is theoretically out of our control.

**Comment by bjauny** [comment]
> Hi @bjauny , the solution is simple as it looks: create a function which will accept a const reference to an image and a pixel position. If the position is out of image size then return 0. No assertion or exception is needed as this function works with assets which is theoretically out of our control.

OK, but most of the calls to image()[] are actually used to modify the value of an image (from what I get when I search for "image()[" in the project. This means that we should return a reference to the actual uint8_t of the image at the requested position, right?
