### ISSUE TITLE
tools icn2img CreateDirectoryA

### ISSUE THREAD

**Issue by tarboss** [ihhub/fheroes2#5857]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

**system.cpp:**

#if defined( __MINGW32__ ) || defined( _MSC_VER )
// clang-format off
// shellapi.h must be included after windows.h
#include <windows.h>
#include <shellapi.h>
#include <direct.h>   // added
// clang-format on
#else
#include <dirent.h>
#endif

int System::MakeDirectory( const std::string & path )
{
#if defined( __WIN32__ ) && defined( _MSC_VER )
    //If the function succeeds, the return value is nonzero.
    //bool ret = CreateDirectoryA( path.c_str(), nullptr );
    //GetLastError();
    // _mkdir zero if dir created (opposite CreateDirA)
    return _mkdir( path.c_str());

i changed it to _mkdir() on my install (add #include <direct.h> ), because CreateDirectoryA() returns zero if fail!!!
----------------------------------------------------------------------
**icn2img.cpp**
    if ( System::MakeDirectory( prefix ) != 0) {
        std::cout << "Error mkdir: " << prefix << std::endl;
        std::cerr << "Error: " << strerror( errno ) << std::endl;
        std::cerr << "(hint: u can only create one directory under windows!)\n";
        return EXIT_FAILURE;
    }

### Save file

not avail

**Comment by zenseii** [comment]
Hi, @tarboss.
Thanks for this suggestion! Would you be able to post this as a PR so it would be easier to understand the code changes you are proposing.

Also could you write more clearly and more structured in the issue what exactly it is that the problem is? I can understand it from the commented code, but it's not a very intuitive way to present it.

**Comment by tarboss** [comment]
hmm, later, yet another sidenote:
if i run the tool to convert icn file to png format:

**icn2img-vs2019.exe **phoenix.icn** depack s:\tmp\homm2\kb.pal**.

The offsets of the sprites are negative/0xfffx (not sure) or is it another bug? 
(http://thaddeus002.github.io/fheroes2-WoT/infos/informations.html - signed offsets, not unsigned )

_output from tool (changed to signed 16bit offset):_
Image 1 has offset of [0, 0]
dstfile: depack\phoenix\000.png
5515
Image 2 has offset of [-14, -95]
dstfile: depack\phoenix\001.png
4290
Image 3 has offset of [-18, -102]
dstfile: depack\phoenix\002.png

the agg_file.h should look like this or?
struct ICNHeader
    {
        ICNHeader()
            : offsetX( 0 )
            , offsetY( 0 )
            , width( 0 )
            , height( 0 )
            , animationFrames( 0 )
            , offsetData( 0 )
        {}

        int16_t offsetX;  //not uint16_t 
        int16_t offsetY;  //not uint16_t 
        uint16_t width;
        uint16_t height;
        uint8_t animationFrames; // used for adventure map animations, this can replace ICN::AnimationFrame
        uint32_t offsetData;
    };
