### ISSUE TITLE
automatic evil/good interface type

### ISSUE THREAD

**Issue by bmorel** [ihhub/fheroes2#5869]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Original game had a way to have automatic selection of evil or good interface, depending on the starting castle.

### Describe the possible solution

Currently, it's is possible to either select "evil" or "good" but no "automatic". Automatic should be evil for barbarians, necromancers and warlocks, and good for knights, sorceress, and wizards.

**Comment by zenseii** [comment]
Hi @bmorel,
This issue is already described here:
https://github.com/ihhub/fheroes2/issues/1329
So I suggest closing this duplicate issue.
