### ISSUE TITLE
Where's "CHOOSE.SMK"?

### ISSUE THREAD

**Issue by vanfanel** [ihhub/fheroes2#5872]
### Your question

Hi there,

I just built the latest version of FHeroes2 on Debian 11 GNU/Linux, and when starting a new campaign I get "Required video files for campaign selection window are missing", etc on a pop-up window.

Looking at the code, it seems that the game is looking for `CHOOSE.SMK`, which is a file I don't have on my Heroes 2 Gold (GOG) installation.

Where does that file come from, please?

**Comment by zenseii** [comment]
Hi @vanfanel.

This file comes from the ANIM folder of the Heroes 2 gog installation. fheroes2 comes with a script that should find all these files in your installation called `extract_homm2_resources.sh`.

This folder can also be found manually by either mounting the heroes2.gog file as a disc image, potentially just rename to heroes2.bin, or if you have grab the heroes 2 gold windows edition from GOGs website where you downloaded it from then the ANIM folder will be unpacked in the installation directory.

Don't hesitate to ask should you encounter any problems.

**Comment by vanfanel** [comment]
Found it, thank you @zenseii !

My GOG install didn't have it for some reason...
