### ISSUE TITLE
AI does not take into consideration that artifact bag is full while trying to move through an artifact

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#5880]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

If an AI hero has a full bag of artifacts and it tries to move to another place over an artifact he spends all move points by trying to get the artifact over and over again. This was observed while testing auto AI control feature.

The hero tries to reach Gold pile sitting behind an artifact:
![image](https://user-images.githubusercontent.com/19829520/192139230-bda1178a-c3e2-49ac-b42c-4b85891b9149.png)

https://user-images.githubusercontent.com/19829520/192139170-f6320ea0-f9fa-4d9a-87e3-2293d6846a40.mp4

### Save file

Enable auto AI control feature and observe the behavior.

[AI_does_not_move.zip](https://github.com/ihhub/fheroes2/files/9640537/AI_does_not_move.zip)

**Comment by ihhub** [comment]
Hi @idshibanov , would you mind to take a look at it?

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

It would also be necessary to consider ocean objects that contain artifacts, such as Shipwreck Survivor (always), or Sea Chest (sometimes).
There are also locations that give artifacts like Graveyard (always), etc.

**Comment by ihhub** [comment]
This is a valid point also. Thank you, @LeHerosInconnu !
