### ISSUE TITLE
AI constantly using Dimension door to jump between 2 neighboring spots

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#5883]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

AI hero constantly jumps between 2 neighboring cells for no reason while under AI auto control:

https://user-images.githubusercontent.com/19829520/192141628-68caa754-fbd9-43ed-a366-a65d165c754f.mp4

### Save file

[constant_dimesion_door.zip](https://github.com/ihhub/fheroes2/files/9640650/constant_dimesion_door.zip)

**Comment by ihhub** [comment]
This is even more bizarre situation:

https://user-images.githubusercontent.com/19829520/192141987-958e2508-b64d-4820-a187-75f1dd3425b9.mp4


Here is a save for it:
[infinite_teleport.zip](https://github.com/ihhub/fheroes2/files/9640674/infinite_teleport.zip)

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

AI loves to taunt wandering troops. :rofl:

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , once AI auto control feature is merged you can test all sorts of AI behavior ;)

**Comment by LeHerosInconnu** [comment]
@ihhub.

> Hi @LeHerosInconnu , once AI auto control feature is merged you can test all sorts of AI behavior ;)

The unknown fun of being an AI. :)

**Comment by ihhub** [comment]
This is another very strange behavior by Dimension Door:

https://user-images.githubusercontent.com/19829520/192274626-cbcca2fb-8539-49b9-ba4d-be39396ffd0d.mp4

[dimension_door.zip](https://github.com/ihhub/fheroes2/files/9646105/dimension_door.zip)
