### ISSUE TITLE
“Your name” shouldn’t be asked every time you win a game

### ISSUE THREAD

**Issue by kazenoyouni** [ihhub/fheroes2#5892]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

“Your name” will be requested even if the score cannot get into the top 10 high scores when you win a game.

### Describe the possible solution

“You name” should not be asked when the score is not high enough, and directly return to the start screen.

**Comment by zenseii** [comment]
I'm marking this as a bug since the Original Game behaves the way described above.
