### ISSUE TITLE
Save file, selected hero or castle should be stored in the save file

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#5898]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In the original game, the selected hero or castle is stored in the save file, so that when a save is loaded, the hero or castle is selected automatically.

In fheroes2, it worked this way when the option "game: remember last focus" was activated.
This option has since been removed.
It is to be noted that it should have worked as in the original game whether the option "game: remember last focus" was activated or not.

### Save file

Here are the save files:
[Selected hero castle stored in save file 01.zip](https://github.com/ihhub/fheroes2/files/9674131/Selected.hero.castle.stored.in.save.file.01.zip)

**Comment by felix642** [comment]
I will be working on this issue.
