### ISSUE TITLE
Battle, double attacking shooters proceed one attack without arrows

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#5931]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In a case a shooter has odd number of arrows left he can come up to an attack, when he has only one arrow left.
![image](https://user-images.githubusercontent.com/55348946/194547798-76f29e11-da25-4727-a14f-b0222fb6ead6.png)
In the OG he's allowed to proceed the second shot, even if he has only one arrow. I think it's a debatable logic. To my mind if shooter has only one arrow, he could make only one shot.
But currently in fheroes2 shooter is able to make a second hit with his knife. It looks like some sort of telekinetic swing. :D
![image](https://user-images.githubusercontent.com/55348946/194548416-b74f9eda-274a-4bf5-9277-2c5ea609fc77.png)

### Save file

[Really distant swing.zip](https://github.com/ihhub/fheroes2/files/9733784/Really.distant.swing.zip)

**Comment by ihhub** [comment]
A magical knife! I approve it!

**Comment by Branikolog** [comment]
@ihhub 
Poor boars. They were hurt with an arrow first and then were stabbed with an invisible knife. Combo-fatality by elves. ;)
