### ISSUE TITLE
Debug mode movement pointer range

### ISSUE THREAD

**Issue by a1exsh** [ihhub/fheroes2#5945]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

In debug mode I can see the whole map, but the mouse pointer only turns to movement (the horse) within the short range, supposedly in the area what should be seen by the hero w/o debugging.  There are no obstacles that could prevent movement.

Within the range:
![image](https://user-images.githubusercontent.com/489601/194746298-a9e32529-1d3f-4c8d-8887-40626bbd1ca7.png)

Outside of the range:
![image](https://user-images.githubusercontent.com/489601/194746319-42356026-da4f-43be-b34f-77379ddbfe4c.png)

### Save file

[Good_1_0001.zip](https://github.com/ihhub/fheroes2/files/9741084/Good_1_0001.zip)

### Additional info

`debug = 65535`

**Comment by oleg-derevenetz** [comment]
I wouldn't consider it as a bug. Although you can see the whole map in the debug mode, it's just sort of unfair "x-ray vision", but technically the fog of war is still there, and it still limits you in terms of movement.

**Comment by Branikolog** [comment]
True. I've also thought it was a bug the first time I used debug mode. :)

**Comment by a1exsh** [comment]
Well, it would make sense if in this debug mode the fog was indicated somehow.  I find it very confusing otherwise.

**Comment by oleg-derevenetz** [comment]
> Well, it would make sense if in this debug mode the fog was indicated somehow.  I find it very confusing otherwise.

Well, it is indicated... sort of - you can't pave a path through it :) In general, the debug mode is intended not for a general user audience, but for developers who are expected to be aware of internal game mechanics. It's not a part of the game, but some sort of shortcuts.

**Comment by ihhub** [comment]
I am not considering this as a bug. It's maximum an improvement as debug mode is not designed to be perfectly executed as it is only for developers.

**Comment by a1exsh** [comment]
Framing it as an improvement is fine. :)

**Comment by ihhub** [comment]
We can dim tiles with fog for debug mode to show that they are under fog but still visible.
