### ISSUE TITLE
Minimap, player Green shade of owned objects

### ISSUE THREAD

**Issue by a1exsh** [ihhub/fheroes2#5946]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

The shade of the green color used to display the objects on the minimap that belong to the Green player are quite hard to tell from the forest on the minimap:
![image](https://user-images.githubusercontent.com/489601/194746900-7d6e7ee5-2d6d-45e9-8aed-8db842b3d6af.png)

My suggestion is to use the same shade as for the Blue player (`#52b440`):
![image](https://user-images.githubusercontent.com/489601/194747112-a57ec090-2ead-499c-8874-3c8224f4b50d.png)

### Save file

[AUTOSAVE.zip](https://github.com/ihhub/fheroes2/files/9741122/AUTOSAVE.zip)

**Comment by Branikolog** [comment]
Hi, @a1exsh !
Colors are the same in the original game and in fheroes2.
OG:
![image](https://user-images.githubusercontent.com/55348946/194749864-ff57ac89-b7b2-448e-9e51-f13b07ad3e18.png)
Green color on a grass terrain would anyway be not so perceptible within a minimap. Looking on your screenshot I cannot tell it's much better. But anyway, I'm not against, if the majority of the team would accept this enhancement.

**Comment by Branikolog** [comment]
@a1exsh 
Oh, actually no. My bad eyes...
In the original game green color corresponding trees and mountains is a bit brighter, that's why in fheroes2 it's harder to distinguish green mines.

**Comment by a1exsh** [comment]
This way or the other, it would be nice to have a little more contrast here ;)  Let's use the OG colors then?
