### ISSUE TITLE
Music is not working on ubuntu

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#5986]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

The issue is created based on a feedback from a user.

No music during application run. Please note that sound effects are OK.
This has started since: 0.9.18

OS: Ubuntu 20.04.3 LTS
fheroes2 engine, version: 0.9.18 - 0.9.20

$ ./fheroes2
fheroes2 engine, version: 0.9.20
15.10.2022 09:41:06: [ERROR] createMusic:  Failed to create a music track from memory. The error: No SoundFonts have been requested
15.10.2022 09:41:18: [ERROR] createMusic:  Failed to create a music track from memory. The error: No SoundFonts have been requested
15.10.2022 09:41:19: [ERROR] createMusic:  Failed to create a music track from memory. The error: No SoundFonts have been requested

The issue is actual for both MIDI and External music setting.

Version 0.9.17 is the last one where I dont get this problem.
No music at all but in game SFX work OK.

### Save file

None.

**Comment by oleg-derevenetz** [comment]
It looks like this user does not have the external music files (ogg/flac/mp3) and it always tries to play built-in MIDI files, but fails to play them because there are no soundfonts available. It's hard to tell what exactly should be done in this case, because it depends on the build settings of `SDL_mixer` on his Ubuntu - is it built with timidity or fluidsynth. I have no live Ubuntu around.

**Comment by Branikolog** [comment]
Hello, @oleg-derevenetz .
The user says, on 0.9.17 everything worked fine (I suppose both midi and external). Do you remember, what we've changed from 9.17 to 9.18?

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog the thing is, soundfonts are not needed to play audio formats other than MIDI, so it seems that external music didn't work even with earlier builds for that user (I mean, user may hear a music, but it always was MIDI music). Currently the game tries to load soundfonts from the `data/soundfonts` subdirectory (to properly support MIDI music playback on Windows), and, if there are no soundfonts, it will set the soundfonts path inside the `SDL_mixer` to an empty string, but IIRC `SDL_mixer` has fallbacks for such a case (at least on Windows it starts to use the system MIDI backend in this case), and maybe its MIDI backend (timidity or fluidsynth) has their own fallbacks too to use some system-wide soundfonts in this case. Anyway, putting the external music files to the right place and setting the music type to External should resolve this issue.

**Comment by oleg-derevenetz** [comment]
Yeah, there is the fallback heuristics at least in the SDL_mixer:

```c
const char* Mix_GetSoundFonts(void)
{
    const char *env_paths = SDL_getenv("SDL_SOUNDFONTS");
    SDL_bool force_env_paths = SDL_GetHintBoolean("SDL_FORCE_SOUNDFONTS", SDL_FALSE);
    if (force_env_paths && (!env_paths || !*env_paths)) {
        force_env_paths = SDL_FALSE;
    }
    if (soundfont_paths && *soundfont_paths && !force_env_paths) {
        return soundfont_paths;
    }
    if (env_paths) {
        return env_paths;
    }


    /* We don't have any sound fonts set programmatically or in the environment
       Time to start guessing where they might be...
     */
    {
        static char *s_soundfont_paths[] = {
            "/usr/share/sounds/sf2/FluidR3_GM.sf2"  /* Remember to add ',' here */
        };
        unsigned i;


        for (i = 0; i < SDL_arraysize(s_soundfont_paths); ++i) {
            SDL_RWops *rwops = SDL_RWFromFile(s_soundfont_paths[i], "rb");
            if (rwops) {
                SDL_RWclose(rwops);
                return s_soundfont_paths[i];
            }
        }
    }
    return NULL;
}
```

So it tries the paths set by `Mix_SetSoundFonts()` first, if they are empty, it tries the paths from the environment variable, and, if both are empty, it tries some hardcoded system path.
