### ISSUE TITLE
Minimap color differences

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#5994]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In the original game some of colors for minimap are different from current. Right now, within #5980 colors of obstacles on grass are fixed, but there some other differences left:
![Mmap mini](https://user-images.githubusercontent.com/55348946/196669811-39d4ddb8-1f0a-44f9-8436-a3e7914a3216.png)
The grass terrain color is different.
Wasteland terrain and obstacles have wrong colors.

### Save file

[Terrains.zip](https://github.com/ihhub/fheroes2/files/9819744/Terrains.zip)

**Comment by a1exsh** [comment]
@Branikolog good catch!  Both colors are off by one position in the palette, please see the linked PR.

**Comment by Branikolog** [comment]
Hi, @a1exsh 
As I mentioned https://github.com/ihhub/fheroes2/pull/5980#issuecomment-1283809881, after your previous PR all colours for obstacles became brighter.
![mmap mini last](https://user-images.githubusercontent.com/55348946/196928247-d72b1a01-24c7-419b-844b-80bdff6da1b3.png)
Could you, please, look, what went wrong?

**Comment by Branikolog** [comment]
@a1exsh 
Original issue was created for obstacles on grass terrain, which had wrong color.
![ezgif com-gif-maker (87)](https://user-images.githubusercontent.com/55348946/196952826-a9430f78-27cc-4a44-b7fd-e1347564a46f.gif)

After the latest PR grass obstacles were fixed, but all other changed their colors.
![ezgif com-gif-maker (86)](https://user-images.githubusercontent.com/55348946/196952975-c7e956e8-4fe2-4f69-9f04-4a11f174bdd1.gif)

**Comment by Branikolog** [comment]
Wasteland has not correct colours in all cases, since we haven't touched it yet and that's why I originally created current issue. But obstacles colours became brighter for snow, swamp, lava, sand, dirt and beach, while they were OK before the previous PR touched minimap.

**Comment by a1exsh** [comment]
> Wasteland has not correct colours in all cases, since we haven't touched it yet and that's why I originally created current issue.

Yes, wasteland and grass colors were off by one, compared to the OG.

> But obstacles colours became brighter for snow, swamp, lava, sand, dirt and beach, while they were OK before the previous PR touched minimap.

That's right, they became brighter by one index, but at the same time they are now correct (same as in OG).  Or do you see an issue with that?

**Comment by Branikolog** [comment]
Hi, @a1exsh 

> That's right, they became brighter by one index, but at the same time they are now correct (same as in OG). Or do you see an issue with that?

They are NOT the same to the OG.


> ![ezgif com-gif-maker (86)](https://user-images.githubusercontent.com/55348946/196952975-c7e956e8-4fe2-4f69-9f04-4a11f174bdd1.gif)

Can't you see the difference between these both screenshots?
The one with short scrollbars is the original one, and the second is fheroe2 obviously.
Look at minimap, which contains all 8 terrains. Upper part of each terrain is filled with obstacles and is intended to be darker. Comparing these both screenshots terrain part has color differences.

**Comment by a1exsh** [comment]
@Branikolog OK, I need to double-check, it may happen that I got confused at some point.

**Comment by a1exsh** [comment]
@Branikolog btw, can you attach the `Terrains.map` file that I can run in OG as well?  You've only attached a save file for fheroes2...

**Comment by Branikolog** [comment]
@a1exsh 
Sure!
[Map_0014.zip](https://github.com/ihhub/fheroes2/files/9838197/Map_0014.zip)

**Comment by a1exsh** [comment]
@Branikolog you are absolutely correct — the problem was with the _base_ shade of grass, and not with the way the obstacle shade is calculated.  I've reverted that change in PR #5998, and now every base shade and obstacle shade should match the OG exactly.
