### ISSUE TITLE
Incorrect display of MIN button in 'move troops' dialog window

### ISSUE THREAD

**Issue by Districh-ru** [ihhub/fheroes2#6006]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Hi,
'MIN' button has incorrect drawing in the 'move troops' dialog window.
In recruit dialog this button generates correctly.
I am using russian resources and this incorrect drawing is noticeable.

![изображение](https://user-images.githubusercontent.com/113276641/196908307-2f86b2ae-ca48-4422-a4fe-14630925925a.png)  ![изображение](https://user-images.githubusercontent.com/113276641/196908653-36050b8e-c9f9-4c94-b5e5-7042504b9c69.png)

### Save file

No save file is needed, just start a new game and try to split the troops in hero's army.

### Additional info

There is a function ('generateLanguageSpecificImages'), that generates 'MIN' button for recruit dialog (NOT_UNIFORM_GOOD_MIN_BUTTON).
For 'move troops' dialog it is generated from parts of other buttons (UNIFORM_GOOD_MIN_BUTTON).
Maybe it should be generated like in recruit dialog.

**Comment by zenseii** [comment]
Hi, @Districh-ru.

I can have a look at this very easily but I need to ask you how this looks in the recruit creature dialog now? I don't have the Russian resources so I will just need some clarification from you.

**Comment by Districh-ru** [comment]
Hi, @zenseii 
The recruit creature dialig In Russian is on the left picture, and in English with Rusiian resouces - on the right side one.
![изображение](https://user-images.githubusercontent.com/113276641/196937557-2b3bd257-80be-44c7-9d62-eb25e28c64dc.png) ![изображение](https://user-images.githubusercontent.com/113276641/196938244-1ef708fb-93b3-43d4-b0a6-17abbd4f2280.png)

**Comment by zenseii** [comment]
> Hi, @zenseii The recruit creature dialig In Russian is on the left picture, and in English with Rusiian resouces - on the right side one.

Great then that looks quite good. We will do the same for the other MIN button. I believe there might be three of them afaik.

**Comment by Districh-ru** [comment]
The third is in the Evil Interface :)
![изображение](https://user-images.githubusercontent.com/113276641/196941460-fcf5201a-3590-48d7-a456-8c7503334e16.png)
