### ISSUE TITLE
"Month/week of..." event increases the amount of both basic and upgraded creatures

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#6038]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Only basic creatures should be increased inside castles during "Month/week of..." event.
Currently, after such event both creatures are increased in neutral castle.
The month of Troll happened:
![image](https://user-images.githubusercontent.com/55348946/197534453-14ac7d85-691b-4864-95f3-4d705cb93165.png)
You can see, that War trolls have much higher quantity, that they've supposed to have after month of trolls. 
![image](https://user-images.githubusercontent.com/55348946/197534942-c62496fc-9d25-4bd3-ba67-7ac514124f25.png)
Nearby castle with the same amount of trolls.

### Save file

None.

**Comment by oleg-derevenetz** [comment]
I suppose that this is a side effect of the fact that player can choose between upgraded and non-upgraded creatures when hiring.

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz !
We've fixed similar issue for human player a year or so ago. (#5153)
I believe, it's completely the same, but everyone forgot to add the correct rule for castles, that are not belong to a player. :)

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Yes, I know, that fheroes2 allows to hire both creatures, after an upgrade was established in a city. But the rule for doubling non-upgraded creatures available for hiring should be applied only for the cases when player built only basic creature dwelling. 
Otherwise it changes gameplay, allowing to have doubled growth of creatures, that in the original game was impossible.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
I've mistaken a bit. Currently the rule of doubling available creatures in the beginning of month is applied for human player too.
So in fheroes2 the amount of creatures could become 2x for all cases, while in the OG only those castles, where player couldn't afford upgrade, receive the bonus. Thus the bonus becomes much more rare event, than in fheroes2. I think this prevents players from overwhelming their castles with excessive number of creatures.
Also, I've noticed, that during "Week of +5..." both creatures (basic and upgraded) receive bonus in fheroes2, which is not the case in the OG game and should be fixed as well.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog

> I've mistaken a bit. Currently the rule of doubling available creatures in the beginning of month is applied for human player too.

Yes, just like I said, it doesn't depend on the controlling player's type - it happens due to the special logic, apparently because its designer believed that, since in fheroes2 both types of creatures are available for hire simultaneously, upgraded creatures should be doubled as well (because there is the same count both of upgraded and non-upgraded creatures).

**Comment by Branikolog** [comment]
@oleg-derevenetz 
So, The logic for this event should look like:
In a case the event is dedicated to a basic creatures - it should be applied only for castles, without upgraded creatures available for hiring.
Am I right?

**Comment by oleg-derevenetz** [comment]
@Branikolog yes, it looks like it should happen this way.
