### ISSUE TITLE
Missing highscore after winning a campaign

### ISSUE THREAD

**Issue by flydrt** [ihhub/fheroes2#6041]
### Preliminary checks

- [x] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [x] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Engine version: 0.9.20
Issue: After winning a campaign, there's no dialog to enter my name for the score and it exits to the main menu immediately. No new high score is recorded.

### Save file

I didn't find any save file. I searched for the file name (the same name shown in game) under heroes2 folder but found nothing.

**Comment by oleg-derevenetz** [comment]
Should be already fixed by #6026. Please try the latest snapshot (not the latest release).

**Comment by flydrt** [comment]
Hey sorry, you are right.

**Comment by flydrt** [comment]
Close
