### ISSUE TITLE
Roland/Archibald last scenario AI alliance is missing

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#6046]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Currently in fheroes2 AI players fight each other, which cause the last scenario in original campaign way too easy.
As we've discussed in #4576, all AI players should be in alliance.

### Save file

[Campaign save.zip](https://github.com/ihhub/fheroes2/files/9869795/Campaign.save.zip)

**Comment by zenseii** [comment]
Hi, @Branikolog!

From that discussion that is linked to, I assume this to be hardcoded in the original game and not specified in the campaign map file, or else it wouldn't be an issue in fheroes2. It would in fact change this map significantly.

There's also the possibility that there is some parameter we don't read from the original campaign map file yet.

**Comment by Branikolog** [comment]
Hi, @zenseii !
I've tested original campaign, and noticed that AI never fights each other or captures castles. Nevertheless, it sometimes captures mines, but that's really a rare case. The most of time AI is running near each other and near allied mines without any offensive behaviour.

**Comment by a1exsh** [comment]
Related: #4576

**Comment by zenseii** [comment]
> Hi, @zenseii ! I've tested the original campaign, and noticed that AI never fights each other or captures castles. Nevertheless, it sometimes captures mines, but that's really a rare case. The most of time AI is running near each other and near allied mines without any offensive behaviour.

This could be due to the AI calculating their route over a mine and disregards whether it's theirs or someone else's.

What I would do first is to open this map in the editor to see if any alliance flags are turned on. If there are then there is something wrong with the fheroes2 code. Original campaign map files can be opened in the editor by simply renaming them to use the respective standard game file extension, .mp2 for succession wars.

**Comment by Branikolog** [comment]
Hi, @zenseii !
In the original map editor there's no alliance initiated. So, I suppose, alliance is hardcoded for this mission.

**Comment by zenseii** [comment]
> Hi, @zenseii ! In the original map editor there's no alliance initiated. So, I suppose, alliance is hardcoded for this mission.

I see. Thanks for checking. I suggest we apply the normal AI alliance to this. In other words not make it possible for AI players to capture allied mines - this seems more like a bug to me.
