### ISSUE TITLE
Can't get in fullscreen by F4 pressing on SDL2 build

### ISSUE THREAD

**Issue by shprotru** [ihhub/fheroes2#605]
[This](https://github.com/ihhub/fheroes2/blob/master/src/engine/display.cpp#L206) is mistake on flags working, flags could be only 3 types: `SDL_WINDOW_FULLSCREEN`, `SDL_WINDOW_FULLSCREEN_DESKTOP` or `0` by [documentation](https://wiki.libsdl.org/SDL_SetWindowFullscreen) on this function. That's why impossible to get into fullscreen mode on `SDL2` build by pressing `F4` button. I think it's need to be correct view in fullscreen mode, but I think this should be another issue.

**Comment by idshibanov** [comment]
Thanks for creating this one, I was about to point it out too.

**Comment by Branikolog** [comment]
SDL1 the same.

**Comment by shprotru** [comment]
@Branikolog as for me, `F4` on build with `SDL1` working good in `Linux Ubuntu`, I will inspect code related to `SDL1` build on this problem. On which platform did you test?

**Comment by Branikolog** [comment]
Win x64
