### ISSUE TITLE
Main menu, language list is too big for native resolution

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#6059]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Game supports too many languages now to fit the the screen at 640x480.
![image](https://user-images.githubusercontent.com/55348946/198820903-85fc4572-1b0f-475e-aa6d-0ee34e1950af.png)

### Describe the possible solution

The list could be divided into to columns or completely reworked to have scroll bar.

**Comment by ihhub** [comment]
This issue must be fixed for the upcoming release.
