### ISSUE TITLE
Looped idle animation in battle

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#606]
One random unit's idle animation is looped. Unit is moving infinitely.

**Comment by ihhub** [comment]
Ah, yes. In this set first top medusa from left side is always looping:
![image](https://user-images.githubusercontent.com/19829520/82751165-04662d00-9de8-11ea-9ac2-673444a258f3.png)

**Comment by idshibanov** [comment]
> Unit is moving infinitely.
This is a good thing. Units like Medusa, Ghost and Genie are **always idling**. Check the original game.

The bug here is that only one force/unit is animated at the time due to silly optimizations I made.

**Comment by Branikolog** [comment]
> > Unit is moving infinitely.
> 
> This is a good thing. Units like Medusa, Ghost and Genie are **always idling**. Check the original game.
> 
> The bug here is that only one force/unit is animated at the time due to silly optimizations I made.

Agreed. But!
Now idling of medusa has a small pause between animations.
Also, I've noticed, that Bone Dragons idle too often.
