### ISSUE TITLE
Castle siege, catapult projectile misses spinning animation

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#6075]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

![image](https://user-images.githubusercontent.com/55348946/199229979-9de85362-0d2d-438e-9f9c-cfd2ea9643ae.png)
![image](https://user-images.githubusercontent.com/55348946/199232934-2e598c2d-322a-47b5-b49b-7cdad4c44475.png)

Currently rock sprite moves over the battlefield being static.
In the original game projectile spins during the whole flight.

### Save file

Could be reproduced at any castle siege.

**Comment by LeHerosInconnu** [comment]
Related issue: https://github.com/ihhub/fheroes2/issues/6079.
