### ISSUE TITLE
Castle siege, army arrangement containing several stacks of the same type is not retained 

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#6076]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In a case defending hero has several stacks of the same type creature and a few other creatures in castle garrison, those same type creatures are combined into one stack and creatures from castle garrison are merged into hero army.
![image](https://user-images.githubusercontent.com/55348946/199250682-28f9cfb4-840a-4fd6-9842-9a8c4f6fd5b2.png)
![image](https://user-images.githubusercontent.com/55348946/199250833-9e2d791a-6140-48d6-9934-f3cbefb3ed56.png)

This is very annoying, when you want some of your creatures to avoid siege, but they are nevertheless join battle.
So, I propose to transfer strongest creatures from garrison to hero army only in cases, when hero has some spare slots in army. In a case hero has all 5 slots occupied with creatures (even if it would be 5 stacks of 1 goblin) nothing should be merged from garrison to hero army, unless there're goblins left in garrison.

### Save file

[No_Name_3_0001.zip](https://github.com/ihhub/fheroes2/files/9910670/No_Name_3_0001.zip)

**Comment by oleg-derevenetz** [comment]
I propose to consider this as an improvement(?), because such things are always arguable. Anyone else may whine "why my Black Dragons from the castle garrison didn't want to join the battle despite the fact that there is a place for them if these two stack of archers will be merged, stupid computer, I lost my castle because of it".

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog and @oleg-derevenetz,

> I propose to consider this as an improvement(?), because such things are always arguable. Anyone else may whine "why my Black Dragons from the castle garrison didn't want to join the battle despite the fact that there is a place for them if these two stack of archers will be merged, stupid computer, I lost my castle because of it".

I think that garrisoned troops should join the hero's army only if there is a troop of the same type and/or only if there is a free slot in the hero's army.

In the example, if the troop of 12 peasants had been a troop of grand elves, this troop would have joined the first troop of grand elves in the hero's army.
And if the troop of 3 champions had been a troop of elves, this troop would have joined the first troop of elves in the hero's army.
We can see here that the goal of the player was to organize his troops to have a maximum of shooters with a flexibility of the possibilities of shooting (five possibilities of shooting with the five groups of shooters).
This tactic is ruined with the incorporation of peasants and champions in the hero's army, which moreover, are not sufficient in number to turn the tide of combat.

**Comment by Branikolog** [comment]
Hello, @oleg-derevenetz !
That's a valid point. :) There're always be situations, where people would whine. :)
But in your example people can reload and fix the problem by moving needed troops into hero army, while in the case I mentioned above, there's no solution to the problem. Lets say, you visited a castle, where some garrison was already hired... For instance, necromant troops. And there's **no way** to prevent them from joining your army and spoiling morale without dismissing them now. Usually, people tend to arrange troops in their castles right before the siege, so they would definitely consider having Black Dragon on their warm spot at hero army. :)
The issue is not about overall forbidding of troop merging from garrison to hero. Army still should be transferred, in a case hero has only 1 slot occupied and all other troops placed in garrison for speeding hero next day. I want within the issue to leave player a possibility to exclude some troops from upcoming siege (by placing some 1-stacks or dividing some stacks 50/50 obviously), since there's no way in this game to select, which troops should protect castle right before the battle starts.

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu !
This goes without saying, that the current behaviour is not obvious, and you couldn't expect which troops would be united and what slot would be taken by troop moved from garrison. :)
