### ISSUE TITLE
Combat, Catapult shot, trajectory of the catapult projectile is not very realistic

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#6079]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In Heroes 2, the trajectory of the catapult projectile is very regular and takes the characteristic trajectory of a "bell shot".

In fheroes2, it looks as if the projectile reaches its peak and undergoes a new force which modifies its trajectory.

In original game:

https://user-images.githubusercontent.com/43583994/199306196-9a1978ee-b9bd-4ade-a6ea-100f8d4ed8e2.mp4

![Catapult projectile trajectory H2 02](https://user-images.githubusercontent.com/43583994/199306262-e3cb0fc4-cea2-43b6-82eb-5d90a1039afa.png)

In fheroes2:

https://user-images.githubusercontent.com/43583994/199306349-0dcdf29e-b480-46ce-bcc8-c917854daf77.mp4

![Catapult projectile trajectory fh2 02](https://user-images.githubusercontent.com/43583994/199306412-9110dfea-58b9-4af8-85a0-a1f022ce0a8c.png)

### Save file

Here is the test scenario file:
[0 9962a.zip](https://github.com/ihhub/fheroes2/files/9912888/0.9962a.zip)

**Comment by Districh-ru** [comment]
Hi @LeHerosInconnu.
I would like to try to fix this bug.
I changed the equations for calculating the trajectory of the stone flight to the prabolic trajectory calculation:

https://user-images.githubusercontent.com/113276641/201520807-16da583e-ed83-47d6-afc4-f27d3803d451.mp4

If it is good, I'll do some tests and open a PR.

**Comment by LeHerosInconnu** [comment]
Hello @Districh-ru,

> Hi @LeHerosInconnu. I would like to try to fix this bug. I changed the equations for calculating the trajectory of the stone flight to the prabolic trajectory calculation:
> 
>  fheroes2.2022-11-13.15-01-15-241.mp4 
> If it is good, I'll do some tests and open a PR.

Yes, it looks much better.
Feel free to make a PR.
If something goes wrong, there will always be someone to help you.
