### ISSUE TITLE
Adventure map, wrong arrows for the hero's path

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#6085]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, there are wrong arrows for the hero's path.

The arrow used should be representative of the terrain penalty (for the targeted square) taking into account the hero's Pathfinding secondary skill, without taking into account the hero's oblique movement penalty.

In fact, the arrow should correspond to the penalty value displayed in the right-click information window for each square of the adventure map (example: "penalty: 150").

In original game:

It seems that the second arrow from the hero is not correct in the original game:
![Arrow path 001](https://user-images.githubusercontent.com/43583994/199949656-e854e7da-3eaa-4d9a-9e52-55d210bf7742.png)

In fheroes2:

The third and sixth arrows from the hero are not correct:
![Arrow path 002](https://user-images.githubusercontent.com/43583994/199949821-5a47f52e-065c-45cc-801a-daabfb770d2c.png)

In original game:

![Arrow path 003](https://user-images.githubusercontent.com/43583994/199949913-8eeb4b11-bafa-49fb-a367-e7d8f5677a60.png)

In fheroes2:

The fourth arrow from the hero is not correct:
![Arrow path 004](https://user-images.githubusercontent.com/43583994/199949959-37201f73-bd82-442e-b714-41aaeb184731.png)

Note: I noticed other problems with the arrows of the hero's path especially on the sea, I will complete this later.

### Save file

Here are the save files:
[Arrow path 50.zip](https://github.com/ihhub/fheroes2/files/9937243/Arrow.path.50.zip)

**Comment by LeHerosInconnu** [comment]
Other saves for this:
[Arrow longeur path 30.zip](https://github.com/ihhub/fheroes2/files/9937828/Arrow.longeur.path.30.zip)

In fheroes2:

The eighth arrow from the hero is too long (on dirt, 100%):
![Arrow path 30 001](https://user-images.githubusercontent.com/43583994/199963902-65233a78-9acc-4258-8c80-93ccefbe7082.png)

The first arrow from the hero is too long (on road, 75%):
![Arrow path 30 002](https://user-images.githubusercontent.com/43583994/199963910-ba123421-5803-4a9d-9812-e0da0afb81cc.png)

The first arrow from the hero is too long (on dirt, 100%):
![Arrow path 30 003](https://user-images.githubusercontent.com/43583994/199963920-082fab60-41cd-4230-9fb6-dcc7021f611b.png)

The arrow near mouse cursor is too long (on road, 75%):
![Arrow path 30 004](https://user-images.githubusercontent.com/43583994/199963931-91856a9a-44b3-4464-aed4-90ec314a0c10.png)

**Comment by oleg-derevenetz** [comment]
> The third and sixth arrows from the hero are not correct:

In fact, the third arrow here IS correct, because the road penalty is not applied on this tile (despite what the information window shows regarding penalty). But let's pretend that it's OK.
