### ISSUE TITLE
Adventure map, AI behavior, AI doesn't seem to manage correctly artifacts with condition (0.9.20 5949)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#6088]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

In fheroes2, the AI doesn't seem to manage correctly artifacts with condition (here being recognized as a "True Leader").
In the example, it is already month 2 and an artifact has still not been captured by the AI.

In fheroes2:

https://user-images.githubusercontent.com/43583994/199969513-355af929-5380-4543-a21d-33dd8514cc6c.mp4

Here is the save file:
[Artifact not captured 40.zip](https://github.com/ihhub/fheroes2/files/9938070/Artifact.not.captured.40.zip)

### Describe the possible solution

Ensure that AI effectively manages artifacts with condition, especially when it is a high-value artifact.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , can you please explain why this is a bug? Are you certain that AI heroes from Barbarian castle had the needed skill? To verify this please place an AI hero with this skill on any map together with an artifact.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , can you please explain why this is a bug? Are you certain that AI heroes from Barbarian castle had the needed skill? To verify this please place an AI hero with this skill on any map together with an artifact.

This is not strictly speaking a bug, that's why I put it as an improvement.

My point is that when there are artifacts with a condition like being a "True Leader" (having the secondary skill Leadership), being a "Wise Person" (having the secondary skill Wisdom), and even when it comes to paying gold and resources to acquire the artifact, the AI should take it into consideration and send a hero (or even recruit one who meets the condition) to get the artifact especially when it is an artifact that gives +3 in Attack, or +4 in Spell Power, or a gain in resources or a move bonus, etc.
These are artifacts that should not be neglected.
Is there already a part of the code that handles this currently?

**Comment by LeHerosInconnu** [comment]
Another save for this (version 1.0.1 6629):
[AI no capture resource artif2.zip](https://github.com/ihhub/fheroes2/files/10899608/AI.no.capture.resource.artif2.zip)

**Comment by LeHerosInconnu** [comment]
Version 1.0.8 7767.
The save files only show that the AI did not capture the artifacts.
The AI's behavior cannot therefore be observed.
I close the issue and will open a new one if necessary.
