### ISSUE TITLE
Assertion on campaign scenario loading

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#6091]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

![image](https://user-images.githubusercontent.com/55348946/200119920-d7027741-ddd6-4d41-8f1a-ff4587fbd3ff.png)
After pressing "ignore" button briefing page appears, but campaign couldn't be started.
![image](https://user-images.githubusercontent.com/55348946/200119909-d20e8cb8-6639-4341-a2ac-a18ba29db246.png)

### Save file

[Good_9_Complete.zip](https://github.com/ihhub/fheroes2/files/9943789/Good_9_Complete.zip)

**Comment by ihhub** [comment]
Hi @Branikolog , I cannot reproduce this issue. Do you see intro video for this scenario?
