### ISSUE TITLE
AI behavior, already Month 2 Week 3, a hero enhanced by AI does not have a magic book (0.9.20 5949)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#6096]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

In fheroes2, it's already Month 2 Week 3, and a hero enhanced by AI (Knight) is available in the tavern and it does not have a magic book.

In fheroes2:

https://user-images.githubusercontent.com/43583994/200127381-3ef5bec0-9b35-4451-bf9c-9f448e1ced16.mp4

Here is the save file:
[Ambrose tavern no book 01.zip](https://github.com/ihhub/fheroes2/files/9944133/Ambrose.tavern.no.book.01.zip)

### Describe the possible solution

Make the AI buy a magic book for its heroes, at least when they are of a high enough level.

### Additional info

Similar remark in this closed issue: https://github.com/ihhub/fheroes2/issues/2158.

**Comment by ihhub** [comment]
I am closing this issue as in the past we fixed very critical bugs such as trying to upgrade non-upgradable creatures which led to lack of gold for the AI.
