### ISSUE TITLE
Adventure map, AI behavior, AI castle defenseless despite a threat (0.9.20 5949)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#6108]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

In fheroes2, there is AI castle defenseless despite a threat.

In fheroes2:

https://user-images.githubusercontent.com/43583994/200174726-3bbc1905-39f6-4ebe-a90b-bf15dc263826.mp4

Here is the save file:
[No troop defense 01.zip](https://github.com/ihhub/fheroes2/files/9945973/No.troop.defense.01.zip)

### Describe the possible solution

Make the AI defend its castles if it is possible and worthwhile.
In the example, the available creatures could have caused the castle to be preserved or at least inflicted significant losses on the attacker.

**Comment by zenseii** [comment]
The behavior I've currently observed is that the AI will defend it's castle for one day exactly and then the next day it will move out. It seems we need to have it defend for as long as the threat is in the nearby area.

**Comment by LeHerosInconnu** [comment]
Other saves for this (1.0.2 6820):
[Castle no defense 0100.zip](https://github.com/ihhub/fheroes2/files/10970537/Castle.no.defense.0100.zip)

In fheroes2:

![Castle no defense 001](https://user-images.githubusercontent.com/43583994/225054292-06ed8c65-211c-40c9-92fb-597ffa50a4f7.png)

![Castle no defense 002](https://user-images.githubusercontent.com/43583994/225054312-c710e426-d0e0-4938-9590-5e20eb18db4f.png)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , is it still valid for the current build?

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , is it still valid for the current build?

I'm going to take a look at it in my current game (started with version 1.0.5 7308).

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hello @ihhub,
> 
> > Hi @LeHerosInconnu , is it still valid for the current build?
> 
> I'm going to take a look at it in my current game (started with version 1.0.5 7308).

So, I tested this in my latest game (started with version 1.0.5 7308 and continued with version 1.0.5 7339) and AI is better at protecting its threatened castles.

**Comment by ihhub** [comment]
Closing this issue as we improved castle defense logic since 1.0.5 release which was good enough for the topic creator.
