### ISSUE TITLE
AI hero on sleep mode

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#6113]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

I don't know if this is of any help or if it can be a problem, but I met an AI hero in sleep mode.

In fheroes2:

https://user-images.githubusercontent.com/43583994/200301441-3d0aeda8-5001-4791-b619-86fc681fa25f.mp4

Here is the save file:
[AI hero on sleep 01.zip](https://github.com/ihhub/fheroes2/files/9951049/AI.hero.on.sleep.01.zip)

### Describe the possible solution

It depends. :)

**Comment by oleg-derevenetz** [comment]
This is an ordinary situation, a hero, who has the priority task of defending the castle, goes to the sleeper mode.

**Comment by zenseii** [comment]
You'll have to take it up with his superiors that he was sleeping on the job.

**Comment by ihhub** [comment]
Unfair! Humans can sleep but AI can't? AI demands the equal rights!🤣

**Comment by oleg-derevenetz** [comment]
I believe we can close this issue? There is really no issue, heroes that have a task to defend a castle intentionally put into sleeper mode by AI.

**Comment by zenseii** [comment]
> I believe we can close this issue? There is really no issue, heroes that have a task to defend a castle are intentionally put into sleeper mode by AI.

I agree. This issue should be closed as this is completely intentional and no wrong behavior is observed due to it.

**Comment by ihhub** [comment]
This is maximum a UI minor issue for showing some weird dot on hero's portrait.

**Comment by Branikolog** [comment]
Hi, all!
I don't think it's an issue either.
But I'm afraid that small dot could confuse players, since they don't know, what does it mean. I think it simply needs to be removed. :)
