### ISSUE TITLE
Stunning effect icon is always the last in a row

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#612]
Stunning effect icon is always placed to the right from other.
![Icon](https://user-images.githubusercontent.com/55348946/82757249-dda7f680-9de7-11ea-81e6-f260ddff6956.jpg)
![Icon2](https://user-images.githubusercontent.com/55348946/82757252-e00a5080-9de7-11ea-911e-c78aa2e42046.jpg)

**Comment by ihhub** [comment]
Hi @Branikolog what kind of behavior do you expect for this situation?

**Comment by Branikolog** [comment]
All new icons appear from the right side. So I think there should be no exceptions.
