### ISSUE TITLE
Adventure map, AI behavior, not optimized path depends on difficulty level

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#6123]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

https://user-images.githubusercontent.com/55348946/200573935-f295e7bb-5f36-4a50-9e3b-568a44a5b204.mp4

AI always behaves the same while replaying on these two difficulties.

### Save file

The map is called "Carmine".

**Comment by ihhub** [comment]
I am closing this issue as the current AI behavior implementation does not depend on difficulty but on the amount of resources each gold pile had. This problem has been fixed recently.
