### ISSUE TITLE
No "Blood Lust" animation over stunned unit

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#613]
While casting "Blood Lust" spell we cannot see red animation over stunned by Medusa unit.

**Comment by idshibanov** [comment]
What a catch. I would never even think of testing something like that :)

**Comment by Branikolog** [comment]
I've just remembered my old days, when i cast mass spells over whole army with some stunned troops.) Because Blood Lust animation looks a bit different over stunned unit, due non standard colors.
