### ISSUE TITLE
Castle captain has no mana

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#6132]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

![image](https://user-images.githubusercontent.com/55348946/200826290-e9fa81f3-0581-404b-9cec-5bf8a0e9f195.png)
No mana is shown in captain info window.

### Save file

None.

**Comment by Districh-ru** [comment]
Hi @Branikolog,
As the captain always has maximum spell points between battles in quick info could be shown only one number. What do you think?
![изображение](https://user-images.githubusercontent.com/113276641/200903035-c5f32a88-8aec-4909-bfb0-923f40b70ff0.png)

**Comment by oleg-derevenetz** [comment]
@Districh-ru We can also call

```cpp
SetSpellPoints( GetMaxSpellPoints() );
```

in the `Captain`'s constructor and remove the appropriate call from the `Captain::ActionPreBattle()`. In this case Captain will have full mana even if it never participated in a battle.

**Comment by oleg-derevenetz** [comment]
@Districh-ru this might not work for you if you load an old savefile, because contents of this old savefile overwrites changes made by the constructor. Try to start a new game.

**Comment by oleg-derevenetz** [comment]
@Districh-ru yes, it seems that captain's `knowledge` is set properly only for castles with predefined races. If castle is random, its captain is additionally "fixed" in the `Castle::PostLoad()`. So yes, it seems that we need to set spell points in the `LoadDefaults()`.

**Comment by Districh-ru** [comment]
@oleg-derevenetz I'm sorry that I did not mention that in my test map were only 4 random castles :(
I'll check how setting spell points works from `LoadDefaults()` for all types of castles an open a PR.
Thank you for assistance!
