### ISSUE TITLE
Russian text is out of borders of MAX button

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#6155]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

![image](https://user-images.githubusercontent.com/55348946/201471270-75e7260b-f539-4dad-96f2-075788c1cd21.png)
Until we optimize the Russian font I suggest to return back to MAX  instead of МАКС, which doesn't fit the button

### Save file

None.

**Comment by zenseii** [comment]
Note that this is a problem for many languages right now. As discussed earlier this can either be solved by adjusting the font or by enlarging the buttons, like @ihhub suggested.
