### ISSUE TITLE
Increased default speed settings.

### ISSUE THREAD

**Issue by Mr-Bajs** [ihhub/fheroes2#6178]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

The game on installation has the Hero speed and Enemy Speed set very low. I might be wrong but I don't think anyone ever plays on this low speed setting. I assume that the first thing everyone changes when starting a game for the first time is to increase the Enemy speed, Hero Speed and Combat Animation Speed.

The original probably has a low default speed setting, but I don't find it to be any conflict at all with the goal of fheroes2 1.0 to recreate Homm2.

### Describe the possible solution

Increase the default Hero Speed, Enemy Speed and Combat Animation Speed to some more reasonable speed setting of maybe 6,7 or 8?

**Comment by zenseii** [comment]
I've seen players prefer the more relaxed slower speeds like this player who prefers to use what looks like 5:
https://www.youtube.com/watch?v=yioCb7t_Xr0

**Comment by Branikolog** [comment]
Hi, @Mr-Bajs , @zenseii .
I really enjoy smooth walking animation in fheroes2. :)
I think on the first start it's even a positive moment, when people would see that smootheness. :)

**Comment by zenseii** [comment]
> Hi, @Mr-Bajs , @zenseii . I really enjoy smooth walking animation in fheroes2. :) I think on the first start it's even a positive moment, when people would see that smootheness. :)

Not to mention that it forces the lazy veteran players to open the options and in that way discover all the new features of fheroes2.

**Comment by ihhub** [comment]
This is a subjective improvement and depends on many factors. There are many players who really like to play slowly. The default value is the middle value so nothing to do right now. Hence, I am closing this issue.
