### ISSUE TITLE
Android, Adventure Map, Two finger touch support for the Adventure map.

### ISSUE THREAD

**Issue by Mr-Bajs** [ihhub/fheroes2#6182]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Tried the Android version on a 10 inch tablet, it was a much better and seamless experience then I expected. 

One apparent issue was you can't look around in the adventure map by touching the screen. You can look around by touching the minimap, but that's unintuitive for a touchbased interface. I guess this is known but I put it out there so there is atleast an issue about it.

### Describe the possible solution

To look around the map the player should use a two finger input as most touch based applications.

**Comment by zenseii** [comment]
Hi @Mr-Bajs.

@Laserlicht is already one step ahead of you and is working on implementing this in a PR https://github.com/ihhub/fheroes2/actions/runs/3451396692. You can try it out with by grabbing a the fheroes2-android.zip from this link
https://github.com/ihhub/fheroes2/actions/runs/3451396692

We also have work being made to make right click possible here:
https://github.com/ihhub/fheroes2/pull/6092

I suggest we close this PR, @Mr-Bajs.
