### ISSUE TITLE
"View Mines" spell is not working for our version

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#621]
"View Mines" spell is not working for our version.
![Mines](https://user-images.githubusercontent.com/55348946/82758427-316a0e00-9def-11ea-89fc-b2b79be0fe6b.jpg)

**Comment by ihhub** [comment]
Hi @Branikolog , all **View** spells are not implemented in the game. I am moving the implementation of them to **1.0** release so for 0.8 version we concentrate our efforts for fixing and polishing exiting UI without adding new one.
