### ISSUE TITLE
Everhot Lava Rock doesn't affect Armageddon spell

### ISSUE THREAD

**Issue by RicaNeaga** [ihhub/fheroes2#6211]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

See the title - Everhot Lava Rock artifact is supposed to help "Fire spells do 50% more damage". Armageddon is a fire spell, right?

Please check for yourself and try to fix it. Thanks :)

### Save file

Do you also want a screenshot of this?

### Additional info

Thanks :)

**Comment by oleg-derevenetz** [comment]
AFAIK in HoMM2 Armageddon does the same kind of damage as the Elemental Storm, so it's not in fact fire spell. Hi @LeHerosinconnu, am I right?

**Comment by Branikolog** [comment]
Hello!
Armageddon is considered to deal some sort of magic damage. It's not elemental, since Phoenixes are not immune to Armageddon. Also, such artifacts as cloaks don't reduce damage taken from Armageddon. The only special PoL artifact (Broach of Shielding) reduces Armageddon spell damage during combat.
Btw, Golems reduce that magic damage for 50% as intended, since it's the magic damage.

**Comment by oleg-derevenetz** [comment]
@Branikolog So this is not in fact a fire spell, it's a spell with some "special" damage?

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Yes. Fire Elementals and Phoenixes don't resist it while having fire spells immunity.

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> AFAIK in HoMM2 Armageddon does the same kind of damage as the Elemental Storm, so it's not in fact a fire spell. Hi @LeHerosInconnu, am I right?

Yes, the two fire spells in the game are Fireball and Fireblast and they are the only ones affected by the Everhot Lava Rock and Fire Cloak artifacts.

**Comment by RicaNeaga** [comment]
Ok, thank for the info, then the thread is closed :)
