### ISSUE TITLE
Bug or intended? Ultimate artifacts are really lost

### ISSUE THREAD

**Issue by RicaNeaga** [ihhub/fheroes2#6212]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

After a hero I defeat has an ultimate artifact, it really gets lost - when I try to recruit them (even the same day), they do not have ANY artifacts on them.

Is this the desired functionality? Maybe I am wrong, but in the original game I remember that when recruiting that hero it had the ultimate artifact in the bagpack.

Maybe it is the other way around, and the current state of the game is the desired one, so please close this bug thread if so. Thanks :)

### Save file

Do you also want a screenshot of this?

**Comment by oleg-derevenetz** [comment]
Hi @RicaNeaga

> After a hero I defeat has an ultimate artifact, it really gets lost - when I try to recruit them (even the same day), they do not have ANY artifacts on them.

Yes, you cannot capture the Ultimate Artifact in the battle, you can only dig it out - as well as in the original game. When you defeated a hero that has an Ultimate Artifact, the winning hero gets all the artifacts... except the Ultimate, and the following message appears (screenshot from the original game):

![ultimate](https://user-images.githubusercontent.com/32623900/202796473-84b00e8e-7d35-477c-837f-a4be8a30f2c5.jpg)

So this is not a bug.

> Do you also want a screenshot of this?

No, usually we want the savefile that demonstrates the issue. Next time just put the savefile to the ZIP archive, drag it to the appropriate input element and drop it here.

**Comment by RicaNeaga** [comment]
Ok, thanks, then please close this thread. :)

**Comment by zenseii** [comment]
The question I have about this is more a general one: if a hero with the ultimate artifact retreats and that player is later on defeated but the game continues, will it be possible to recruit this hero and will that hero have the ultimate artifact? Do you know @LeHerosInconnu or @Branikolog ?

**Comment by oleg-derevenetz** [comment]
@zenseii if a hero retreats or surrenders, it retains all his artifacts, including the Ultimate, so it could be re-hired later and still have this artifact.

**Comment by zenseii** [comment]
Thanks for the explanation, @oleg-derevenetz. I don't see why we should keep this issue open when the inteded behavior is present in fheroes2.

**Comment by LeHerosInconnu** [comment]
Hello @zenseii and @oleg-derevenetz,

> The question I have about this is more a general one: if a hero with the ultimate artifact retreats and that player is later on defeated from the game but the game continues, will it be possible to recruit this hero and will that hero have the ultimate artifact? Do you know @LeHerosInconnu or @Branikolog ?

> @zenseii if a hero retreats or surrenders, it retains all his artifacts, including the Ultimate, so it could be re-hired later and still have this artifact.

Yes, the Ultimate Artifact cannot be captured after a combat, but a hero with one or more Ultimate Artifacts can be recruited with these artifacts and keep them.

Also, an AI hero with an Ultimate Artifact should make sure to be more cautious and run away more wisely during a combat if he risks being defeated.
I will open a discussion about this.
