### ISSUE TITLE
Adventure map, V-sync enabled makes hero movement drastically slow

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#6252]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Hero starts moving really slowly while we make any movements with cursor.

https://user-images.githubusercontent.com/55348946/203976868-77d23540-c76b-4176-b9d0-db8548d5df5e.mp4

### Save file

None.

**Comment by Branikolog** [comment]
Forgot to mention, that the issue happens with enabled software cursor rendering.

**Comment by ihhub** [comment]
Hi @Branikolog , can you please explain why this is a regression and when was it introduced? Such slowdowns were since the started this project for every OS if software cursor was enabled.

**Comment by Branikolog** [comment]
Hi, @ihhub !
Well, a sort of... I consider this as regression in terms of performance. )

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , making rendering in batches is my next step to improve rendering in general. I am delaying this in favor of 1.0.
