### ISSUE TITLE
Castle screen, barbarian captain's quarters has shifted column

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#6263]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

![image](https://user-images.githubusercontent.com/55348946/204151728-66bfe8b7-12a3-40c1-ae4f-8ec35906e93d.png)
Recently added column ran away.

### Save file

None.

**Comment by undef21** [comment]
@Branikolog, could you provide a save with this castle?

**Comment by Branikolog** [comment]
Hi, @undef21 !
Sure.
[Barbarian Captain.zip](https://github.com/ihhub/fheroes2/files/10113617/Barbarian.Captain.zip)

I want to note, that issue appeared on 0.9.15 version. Somewhere between 10 and 20 of May on the way to 0.9.16.
