### ISSUE TITLE
Add proper support for Anbernic devices

### ISSUE THREAD

**Issue by Shatur** [ihhub/fheroes2#6272]
### Your question

Is it possible to emulate mouse with keyboard?
In old version of the game I had the following:
```
emulate mouse left = 276
emulate mouse right = 275
emulate mouse up = 273
emulate mouse down = 274
emulate press left = 306
emulate press right = 308
```
Is this feature still supported?

**Comment by ihhub** [comment]
Hi @Shatur , could you please explain the real use case for this? Usually every machine which has keyboard contains mouse. Using just keyboard is extremely inconvenient. An alternative for your case if you use Windows is to enable mouse emulation on the OS level.

**Comment by Shatur** [comment]
@ihhub I run it on my handheld Anbernic RG280V.
So the feature was removed? I compiled the latest master.

**Comment by ihhub** [comment]
@Shatur , the proper way is to add support for button for your device like it is done for PS Vita or Switch.

**Comment by ihhub** [comment]
I suggest to rename this topic into something like "Add proper support for Anbernic RG280V" where we highlight the need of buttons usage of the device. You can contribute as well 🙂

**Comment by Shatur** [comment]
@ihhub Okay! Could you point me to some source files I should try to edit?

**Comment by ihhub** [comment]
localevent.h|cpp is where you need to start your changes.

**Comment by Shatur** [comment]
@ihhub How main menu is navigated on such devices?

**Comment by Shatur** [comment]
Oh, with touch, right? Anbernic devices don't have a touch screen :(

**Comment by ihhub** [comment]
Joystick support.

**Comment by Shatur** [comment]
> Joystick support.

No joystick either, only a D-Pad :(

**Comment by Shatur** [comment]
@ihhub Sure, but I also need to move a cursor somehow? I need to provide some kind of cursor emulation for this device?

**Comment by Shatur** [comment]
Discovered that devices with OpenDingux have <kbd>Power</kbd> + <kbd>B</kbd> hotkey to enable mouse emulation.
So the feature actually not needed, the game runs fine. Sorry for the mess!

**Comment by Branikolog** [comment]
@Shatur , hello!
I'm just curious, how fast fheroes2 is running on your device? It would be nice, if you check FPS while hero running on the adventure map.

**Comment by Shatur** [comment]
@Branikolog I have ~100 FPS in adventure map when I move my mouse and ~30 FPS when here is moving. I also noticed that I also have ~100 FPS if I move my cursor while the hero is running (but the hero moves slower!).

I would say that the game is definitely playable.

**Comment by ihhub** [comment]
@Shatur , please the latest commit from master branch, it contains fixes for mouse movement slowdowns.

**Comment by Shatur** [comment]
@ihhub Thank you, the problem is gone. Also, the cursor movements themselves have become more accurate (it was a little laggy before).
