### ISSUE TITLE
Remove VCRUNTIME140.dll dependency

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#6276]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Based on the report from user this dependency was introduced recently (needs verification). We need to make sure that these files either not needed or shipped with the archive.

### Save file

None.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub how is this a regression? This DLL was always needed, it's a part of the Visual C++ Redistributable Package.

**Comment by ihhub** [comment]
Then it's a false alarm :)

**Comment by oleg-derevenetz** [comment]
@ihhub some apps offer the installation of MSVC redistributable package in their installers.

**Comment by ihhub** [comment]
@oleg-derevenetz , if it is easy to do then why not? If it takes days to implement let's scrap the idea for now.
