### ISSUE TITLE
Right click feature stopped working on some Android devices

### ISSUE THREAD

**Issue by michkry** [ihhub/fheroes2#6290]
I can't get to work right click feature on my Android devices using the latest version of apk (Downloaded: 02/12/2022). When I touch the screen and hold the finger and with another finger point to any element on the screen, it does not trigger right click event. Another issue related to it is that even though the "left clicking" works well, there is no visible cursor on the screen. 

When I install the apk downloaded on 22 November on the same devices, the right click feature works correctly and there is a visible cursor on the screen.

Devices used for testing:

1) Tablet HUAWEI T5 Mediapad - Andorid version 8.0.0
2) Pocophone F1 - Android version 10 QKQ1.196828.002

The following screenshot shows that nothing happens when I touch the screen with one finger and point elements with other. It also shows that there is no cursor on the screen (apk downloaded 02/12/2022):

![not_working_right_click_no_cursor_new_apk](https://user-images.githubusercontent.com/11597098/205438017-e131ce44-6c86-4fb8-9dc0-7d33929de5b2.jpg)

Here we can see that the cursor is visible using the apk from 22 November:

![visible_cursor_old_apk](https://user-images.githubusercontent.com/11597098/205438021-19f05e5b-323c-4f37-8017-83c82bfa39bc.jpg)

Also using the apk from 22 November, the right click feature works correctly:

![working_right_click_old_apk](https://user-images.githubusercontent.com/11597098/205438026-57e9ece7-d63b-4f79-a6e3-d1be51620af0.jpg)

I'm also attaching the apk from 22 November:

[old_apk.zip](https://github.com/ihhub/fheroes2/files/10146220/old_apk.zip)

**Comment by oleg-derevenetz** [comment]
Hi @michkry

> using the latest version of apk

Where exactly did you download it from? I just tried the latest snapshot from the bottom of the Installation Guide page, and it works just fine. Please don't confuse the latest release, which is about a month old, and the latest snapshot from [here](https://github.com/ihhub/fheroes2/releases/tag/fheroes2-android).

**Comment by oleg-derevenetz** [comment]
@zenseii IIRC because the latest **release**__ didn't have this functionality yet :)

**Comment by michkry** [comment]
> Hi @michkry
> 
> > using the latest version of apk
> 
> Where exactly did you download it from? I just tried the latest snapshot from the Snapshots section at the bottom of the Installation Guide page, and it works just fine. Please don't confuse the latest release, which is about a month old, and the latest snapshot from [here](https://github.com/ihhub/fheroes2/releases/tag/fheroes2-android).

I'm pretty sure I downloaded it directly from "Installation" section. But now I see there is no specific entry for Android. Anyway, I've just installed the latest snapshot and it seems the right click works fine. The problem seems to be related to the apk I was using. Would you like me to attach the apk I was using for tesing? 
Sorry for my misleading description of the apk

**Comment by oleg-derevenetz** [comment]
@michkry I suspect that you downloaded your APK from this section:

https://ihhub.github.io/fheroes2/INSTALL.html#android

instead of this section:

https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds

The "latest release" of Android package was released about a month ago and was half-baked, without the proper right-click and software cursor support. If there is in fact no issue with the latest snapshot, then it looks like there is no issue, right? :)

**Comment by michkry** [comment]
You're right. Sorry for wasting your time :(
I'm closing the issue. Thank you for the help!
