### ISSUE TITLE
Battle screen, minotaur uses not direct path to reach the target 

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#6291]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

https://user-images.githubusercontent.com/55348946/205440585-e84bbca3-2420-4fa3-9ba1-964ebbfe803f.mp4

This is not a critical issue, but in a case we have such weird path, there could be some issues with pathfinding. There's no obstacle that made minotaur choose such path.

### Save file

[Minotaur pat.zip](https://github.com/ihhub/fheroes2/files/10146343/Minotaur.pat.zip)

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog the algorithm that is currently used (recursive with limited depth, cells nearest to target are considered first) do not guarantee that chosen path will be "globally optimal", it only guarantees that if there is a path, it will be found. So there may be situations when it may choose suboptimal paths - for example, like in this case: the cell was considered first because formally it's nearest to the target (or at least the distance to the target is not worse in comparison to others), there is really a path via this cell to the target, but in general it's not the best path available. This is not generally a problem, but this may be considered as a cosmetic issue. I propose to consider this as a request for an improvement.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Sure! I was afraid, we have some problems with pathfinding. I'm aware, that current implementation sometimes chooses not optimal path, but the issue I've met was extremely weird looking, as there was absolutely (from human point) obvious path in that situation. :)

**Comment by oleg-derevenetz** [comment]
@Branikolog your may consider the current logic as if that Minotaur has the compass with the direction to target, but may look only one step further. He is moving right to the target using the compass (at least he thinks so) first, but then it sees the obstacle - another Minotaur! Now he would go around him. There is still enough movement points remaining for this, so he just goes around and that's all.

**Comment by Branikolog** [comment]
@oleg-derevenetz Oh, I see. Thanks for clarification! :)

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog and @oleg-derevenetz,

This poses a problem, because the maximum distance that can be covered is reduced (by one hexagon in the example) because of the "zig-zag" of the path.
The path should also take into account the "obstacles" that are positioned on the "supposedly most direct" path.

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu

> This poses a problem, because the maximum distance that can be covered is reduced (by one hexagon in the example) because of the "zig-zag" of the path.

Don't worry, this "zig-zag" may be performed only if there is still enough movement points for this. If not, then algorithm will "rollback" for a few cells more and search again.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> @LeHerosInconnu
> 
> > This poses a problem, because the maximum distance that can be covered is reduced (by one hexagon in the example) because of the "zig-zag" of the path.
> 
> Don't worry, this "zig-zag" can be performed only if there is still enough movement points for this. If not, then algorithm will "rollback" for a few cells more and search again. My explanation was just somewhat simplified for the sake of clarity.

Okay, I see, but let's consider some possibilities.
With a more appropriate path, the troop of minotaurs can move one hex further (to the left of the screen) and still attack the troop of boars.
Let's imagine that the next turn the hero casts the Slow spell on this troop of minotaurs.
The troop of minotaurs could attack the troop of rocs with the more appropriate path (or if the halflings were replaced by centaurs, these centaurs could be attacked) whereas in the example the troop of minotaurs could not do it.

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu

> With a more appropriate path, the troop of minotaurs can move one hex further (to the left of the screen) and still attack the troop of boars.

These are unrelated things. Path to some specific cell is not related to the fact how far can the unit move. Destination cell is selected first by the player (or AI) and only then the pathfinder paves the path to that cell. The path may be not 100% optimal in certain cases, but it's just a cosmetic issue.

**Comment by Branikolog** [comment]
@oleg-derevenetz 

>The path may be not 100% optimal in certain cases, but it's just a cosmetic issue.

This could be an issue, if Heroes2 had some similar spell to "Land Mine" from H3. :)

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> @LeHerosInconnu
> 
> > With a more appropriate path, the troop of minotaurs can move one hex further (to the left of the screen) and still attack the troop of boars.
> 
> These are unrelated things. Path to some specific cell is not related to the fact how far can the unit move. Destination cell is selected first by the player (or AI) and only then the pathfinder paves the path to that cell. The path may be not 100% optimal in certain cases, but it's just a cosmetic issue.

Okay, I see.
So it's the AI that should be improved in this case and it should plan the positioning for the attack of its troops according to the next turn too. :)

**Comment by oleg-derevenetz** [comment]
@Branikolog

> This could be an issue, if Heroes2 had some similar spell to "Land Mine" from H3. :)

But it's not :)

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu

> So it's the AI that should be improved in this case and it should plan the positioning for the attack of its troops according to the next turn too. :)

AFAIK currently it chooses the target unit and then selects the target cell (from which an attack will be performed) by random from the set of nearby reachable cells. That's why AI units like to move even if they attack the same unit.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> @LeHerosInconnu
> 
> > So it's the AI that should be improved in this case and it should plan the positioning for the attack of its troops according to the next turn too. :)
> 
> AFAIK currently it chooses the target unit and then selects the target cell (from which an attack will be performed) by random from the set of nearby reachable cells. That's why AI units like to move even if they attack the same unit they attacked on the previous turn.

So that's why the creatures are dancing frantically around the troops during their consecutive attacks, :) it's because it's random, all of this is not really very tactical.
Are there already plans to improve this or is it better to open an issue for this?

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu

> it's because it's random, all of this is not really very tactical.

Well, it's not quite ALWAYS random. When attacking by units like dragons or hydras AI tries to choose the best cell for this. BUT if there are multiple cells with the same attack value (an ordinary case when attacking with an ordinary unit without any special abilities) a specific cell is selected by random from the set of these "equal value" cells.

> Are there already plans to improve this or is it better to open an issue for this?

There are always plans, but plans are one thing, implementation is another :)

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> @LeHerosInconnu
> 
> > it's because it's random, all of this is not really very tactical.
> 
> Well, it's not quite ALWAYS random. When attacking by units like dragons or hydras AI tries to choose the best cell for this. BUT if there are multiple cells with the same attack value (an ordinary case when attacking with an ordinary unit without any special abilities) a specific cell is selected by random from the set of these "equal value" cells.
> 
> > Are there already plans to improve this or is it better to open an issue for this?
> 
> There are always plans, but plans are one thing, implementation is another :)

So, I plan to open an issue about this. :rofl:

**Comment by viT-1** [comment]
#6148

**Comment by LeHerosInconnu** [comment]
I will keep an eye on this. :)
