### ISSUE TITLE
Inconsistencies With Original Game (Movement Points, Empty Armies)

### ISSUE THREAD

**Issue by JoLiKMC** [ihhub/fheroes2#6310]
### Preliminary checks

- [x] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

I've been messing around with the original _Heroes of Might and Magic II: Editor_, and I've found some interesting quirks and statistics.  And that, of course, led me to testing these same quirks here in _fheroes2_!
–

**Hotkey Issues**
There's a lot of hotkeys in the original _Heroes II_ that do various things.  For example, hitting "F" will open the "File Menu" where one can load or save their game, quit, or start a new game.  In any case, it seems like _most_ of the hotkeys work as expected.  However, there are two small problems I've noticed:

1. If the player opens the File sub-menu and tries to use any of the expected hotkeys (N, Q, L, S) from within, they won't work.
2. There is no "Quit Game" hotkey.  At all. (Default "Q" in _Heroes II_.)
2b. However, in _fheroes2_, hitting Escape while on the Adventure Map _does_ open the Quit Game prompt.  This doesn't work in _Heroes II_.
3. In the original version of the game, both H and Tab would select the next Hero with usable movement points.  By default, _fheroes2_ only uses "H" for this.

Nothing earth-shattering.  Just some observations.
–

**Keyboard Movement Isn't Instant**
In the original _Heroes II_, players could use the keyboard or Number Pad to move around instantly with a single press of a button.  In _fheroes2_, pressing a direction will, instead, **place a movement marker** on the map one tile away without actually moving the hero.  Pressing the same movement key will then initiate movement.
–

**Inconsistent Number Pad Functions**
Tying in to the last point, in _fheroes2_, the Number Pad arrows (8, 4, 6, 2) move the **map viewport** around, rather than moving the _hero_.  However, the diagonal buttons (Home, Page Up, Page Down, and End) still point the hero in diagonal directions.  Kind of confusing…
–

**Heroes With No Armies**
This is another simple one – and it was probably done on purpose.  In the original _Heroes II_, it was possible to create a Hero without any army at all – ie, setting all five "Troops" slots to -empty- in the editor.  Doing so didn't seem to have any _negative_ effects on the game.  Heroes with no armies suffer absolutely no movement penalty, but they will _immediately lose_ any battle when it's their turn.  Making _two_ heroes fight when neither has a single unit will result in _both_ heroes being defeated.
Now, this is currently **impossible** in _fheroes2_.  For whatever reason, the game seems to be coded to **give heroes their class' standard units** if they lack an army.  It seems about the same as setting them to have "Standard" Troops in the editor.

I don't know if this was a bug in the original or something, but I figured it was worth mentioning the difference.
–

**Movement Points on First Turn** (_This one_ is the main reason I've filed this report.)
In doing some testing, I've noticed that in the original game, heroes will **always start with a set amount of Movement Points** – specifically, the Warlock hero **starts with 12(00) movement points** and the Wizard hero **starts with 11** while every _other_ hero **starts with 10**.  It doesn't matter if a hero starts with only Ultra Fast units (Champion, Phoenix), has any-or-all movement-enhancing Artifacts equipped (Nomad Boots, Traveler's Boots, True Compass), or has _any_ level of Logistics, they will **always** start with a set amount of Movement Points on their first turn.  This is **absolutely not** the case with _fheroes2_. wherein Heroes seem to start with the "correct" amount of Movement Points on Day 1, based on their starting inventory / skills / army.

Again, I'm not sure if this is a bug in the original or something, but I guess _someone_ noticed it… and "fixed" it.
–

**Dwarf Death Animation Glitch**
The Dwarf and Battle Dwarf units have glitched death animations.  I'll quote from _[The Cutting Room Floor](https://tcrf.net/Heroes_of_Might_and_Magic_II#Non-glitched_Dwarf_Death)_:
> Due to a bugged frame count, dwarf death animations contain two frames from idle animation and lacks two final frames. Because of this dwarves animations end earlier, leaving their dead bodies with upraised hand and two final frames left unused.

The current behavior in _fheroes2_ is _technical_ correct since this was how things worked in the original game, but still…  It probably wouldn't hurt to fix this obvious oversight, right~?
–

Attached is a custom map file (M2X format) which can be used to test the things I've mentioned.  Try loading it in the original game client, then _fheroes2_, and spot the differences!

Cheers,
J

### Save file

[HoMM2 Map - Hero Movement Test.zip](https://github.com/ihhub/fheroes2/files/10167201/HoMM2.Map.-.Hero.Movement.Test.zip)

**Comment by oleg-derevenetz** [comment]
> In the original Heroes II, it was possible to create a Hero without any army at all – ie, setting all five "Troops" slots to -empty- in the editor.

Regarding this one - there was a discussion at the time and this considered as a bug in the original game - because there is absolutely no way to entirely remove an army from a hero using the game UI. If this was a regular feature, then the developers of the original game would certainly have made some way for this. But neither in this nor in other main games of the series (HoMM3, HOMMV) there is no such functionality.

**Comment by oleg-derevenetz** [comment]
@zenseii AFAIK this map is community-made.

**Comment by JoLiKMC** [comment]
@JoLiKMC
> I have no idea if these 32 bonus maps are community-made or not […]
Actually, yes I do have an idea.  It's right there in the manual (which is included in the _GoG_ release):
> Aleksei Andrievski: Clouds of Xeen, Great War II, Wizard's Land 1, Wizard's Land 2, Wizard's Land 3

The More You Know~

**Comment by oleg-derevenetz** [comment]
> I have no idea if these 32 bonus maps are community-made or not, but Gold is an official release by 3DO.

I suppose that they went this way "oh, such a funny map with the appropriate license, let's add this to the pack". the fact that this game uses behavior that was hardly intended by the developers (otherwise, as I already said, this behavior had to be integrated into the game UI) was most likely just ignored. It works - and okay.

**Comment by JoLiKMC** [comment]
So, hey.  I got curious about this unintended behavior thing and tried to make "no-army heroes" in _Heroes of Might and Magic: A Strategic Quest_.  It might surprise you to learn that it is, indeed, possible – the game acts the same way it does in _Heroes II_.  But then, I tried it with the _Heroes of Might and Magic III_ editor and…

… it greyed out the "OK" button.  I couldn't confirm my changes.  (,:

So, between the fact that you can't manually remove all of your troops in the game _and_ the fact that it's **impossible** to make "empty" heroes in _Heroes III_… I'm inclined to agree that, yeah, it was completely unintentional.  It just took 'em a while to realize what was going on.
_Darn you, Aleksei Andrievski, for bringing it to New World's attention~_

**Comment by JoLiKMC** [comment]
I'm gonna split this into separate issues so it's easier to track each of them.  I don't know why I piled these together in the first place…  That's against the spirit of _GitHub_ Issues archives.

Please, excuse the spam.
