### ISSUE TITLE
[Controls] Hotkey Inconsistency Issues

### ISSUE THREAD

**Issue by JoLiKMC** [ihhub/fheroes2#6313]
* _Split from #6310_

### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

There's a lot of hotkeys in the original _Heroes II_ that do various things.  For example, hitting "F" will open the "File Menu" where one can load or save their game, quit, or start a new game.  In any case, it seems like _most_ of the hotkeys work as expected.  However, there are two small problems I've noticed:

1. If the player opens the File sub-menu and tries to use any of the expected hotkeys (N, Q, L, S) from within, they won't work.
2. There is no "Quit Game" hotkey.  At all. (Default "Q" in _Heroes II_.)
2b. However, in _fheroes2_, hitting Escape while on the Adventure Map _does_ open the Quit Game prompt.  This doesn't work in _Heroes II_.
3. In the original version of the game, both H and Tab would select the next Hero with usable movement points.  By default, _fheroes2_ only uses "H" for this.

Nothing earth-shattering.  Just some observations.

**Comment by oleg-derevenetz** [comment]
> If the player opens the File sub-menu and tries to use any of the expected hotkeys (N, Q, L, S) from within, they won't work.

What is the "File sub-menu"?

> In the original version of the game, both H and Tab would select the next Hero with usable movement points. By default, fheroes2 only uses "H" for this.

This is configurable. Just set the `next hero` in the `fheroes2.key` to `TAB`. However, multiple hotkeys for the same action are not supported, you need to choose just one hotkey which you are more used to.

**Comment by JoLiKMC** [comment]
> What is the "File sub-menu"?

![File Sub-Menu](https://user-images.githubusercontent.com/102710555/206164721-6e8f2f7c-0625-44c9-be54-f0575e6eede1.png)
This thing.  Hitting `Q` from here does nothing whereas in the original game, it does _something_.

> > In the original version of the game, both H and Tab would select the next Hero with usable movement points. By default, fheroes2 only uses "H" for this.
> 
> This is configurable. Just set the `next hero` in the `fheroes2.key` to `TAB`. However, multiple hotkeys for the same action are not supported, you need to choose just one hotkey which you are more used to.

Also, to be fair, `TAB` opens the **chat prompt** in _Heroes III_ rather than change heroes.  And I'm guessing you're trying to emulate _Heroes III_ for "consistency", or to "update the game to modern standards".  If either of those are the case, then I guess it's fine as it is.

**Comment by oleg-derevenetz** [comment]
> And I'm guessing you're trying to emulate Heroes III for "consistency", or to "update the game to modern standards".

Not quite - this is because the current implementation of hotkeys is made so that you cannot have more than one hotkey for one specific action. But, unlike the original HoMM2, you can choose the hotkey that you like best.

**Comment by JoLiKMC** [comment]
I feel obligated to point out: `Q` doesn't quit the game in _Heroes III_, either, but `Escape` does.  So.

Once again… it's your project.
