### ISSUE TITLE
[Controls] Inconsistent Number Pad Functions

### ISSUE THREAD

**Issue by JoLiKMC** [ihhub/fheroes2#6315]
* Split from #6310

### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In _fheroes2_, the Number Pad arrows (8, 4, 6, 2) move the **map viewport** around, rather than moving the _hero_.  However, the diagonal buttons (Home, Page Up, Page Down, and End) still point the hero in diagonal directions.  Kind of confusing…

### Save file

_Save not necessary – this is a control issue._

### Related issues

* #6314

**Comment by oleg-derevenetz** [comment]
This behavior is configurable via `fheroes2.key`. You can choose whatever keys you want. For example, you can scroll the map using regular arrows and move a hero using the keypad arrows.

**Comment by JoLiKMC** [comment]
There is no `fheroes2.key` file.  And my point was more than this functionality is inconsistent with how things work in the original _Heroes II_.  Yes, these keys can be reconfigured in the game, itself, but again, not my point.

**Comment by oleg-derevenetz** [comment]
> There is no `fheroes2.key` file. 

Where is "there"? :) This file resides in the same directory as `fheroes2.cfg` - on Windows it's `%APPDATA%\fheroes2`.

> Yes, these keys can be reconfigured in the game, itself, but again, not my point.

Do you mean that _default_ keys are different from the original game?

**Comment by JoLiKMC** [comment]
> > There is no `fheroes2.key` file.
> 
> Where is "there"? :) This file resides in the same directory as `fheroes2.cfg` - on Windows it's `%APPDATA%\fheroes2`.

Nn.  So it is.  Sorry, then.

> > Yes, these keys can be reconfigured in the game, itself, but again, not my point.
> 
> Do you mean that _default_ keys are different from the original game?

Yes.  Yes, I do.

In the original game, the Number Pad moves the hero in eight directions.  In this version, **by default**, only the corner keys move the hero while the NumPad Arrows move the _map viewport_.

At the end of the day, It's your project.  You can make whatever keys do whatever you want, by default.  I'm just being meticulous about things.

**Comment by oleg-derevenetz** [comment]
We can make the following defaults then for the sake of consistency: regular arrows to scroll the map around and numpad arrows to move the hero. But this is a sort of breaking change, because previous defaults were different, and people may already get used to it. @ihhub @LeHerosInconnu @Branikolog @zenseii what's your opinion regarding this?

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Absolutely agree with @zenseii . Changing some defaults would even force people exploring our hotkeys list even more.

**Comment by LeHerosInconnu** [comment]
Hello everyone,

> We can make the following defaults then for the sake of consistency: regular arrows to scroll the map around and numpad arrows to move the hero. But this is a sort of breaking change, because previous defaults were different, and people may already get used to it. @ihhub @LeHerosInconnu @Branikolog @zenseii what's your opinion regarding this?

As you should know by now, I prefer using the mouse over the keyboard. :)
The proposed default operation (regular arrows to scroll the map around and numpad arrows to move the hero) is fine by me (or the other way round), and the user can switch the use of the regular arrows and the numpad arrows to his convenience anyway.
Also, the "home", "end", "page up" and "page down" keys could be used for diagonal scroll of the adventure map.

**Comment by JoLiKMC** [comment]
Honestly, this particular non-issue is probably going to upset some people while others – like myself – are going to enjoy having the "classic" controls become the default.  Either way, the Number Pad works for moving one space at a time, now.

**Comment by ihhub** [comment]
All hotkeys are configurable. This is not a big blocker.
