### ISSUE TITLE
Attacking animation issue

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#634]
The last few updates i noticed, that attacking animation, especially melee is played much slower, than moving or flying animation of the same unit.

Also, while attacking, unit makes a little pause in the middle of animation.
It is very noticeable while attacking by unicorns Phoenixes and Liches. Lich is standing with its hands rised for too long period of time... 
 
I've tested Phoenixes, Unicorns, Arch mages... Attacking animation of these units seems to be too slow....
But animation of grand elves and druids seems to be ok.

**Comment by ihhub** [comment]
Closing this issue as it's fixed in #858
