### ISSUE TITLE
Battle speed adjustment

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#635]
I think 9 and 10 adjustments of combat speed are too fast. Can we set maximal (10) like current speed of 8th step? So can we stretch all adjustments between current 1 and 8 over new 2-9?

**Comment by ihhub** [comment]
I think we can move this to late stage of development as of now higher speeds help testing.

**Comment by Branikolog** [comment]
Agreed. At least now we have  more or less adequate speed adjustments.

**Comment by ihhub** [comment]
@Branikolog , is it still valid? Are we happy with what we have?

**Comment by Branikolog** [comment]
@ihhub 
It feels like currently we can adjust speed for any taste.
