### ISSUE TITLE
Long phrases in the battle log

### ISSUE THREAD

**Issue by Districh-ru** [ihhub/fheroes2#6357]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Some phrases do not fit in the width of the combat log. (especially in translations)
![long_phrase](https://user-images.githubusercontent.com/113276641/205974672-926d4bc9-c578-4bf5-99fc-9b37141f2a3e.png)

It could be reproduced in "Battle only" mode: Attack many master swordsmen with other many master swordsmen.
![изображение](https://user-images.githubusercontent.com/113276641/207129173-dc19b7a9-93a8-4e91-959a-91dff501e242.png)

### Describe the possible solution

_Originally posted by @zenseii in https://github.com/ihhub/fheroes2/issues/6165#issuecomment-1339686868_ :
>This happens in many other languages and I honestly think we should just make it so that these strings wrap to the next line, or make them cut with a [...] part at the end like we do for campaign awards and bonuses.

**Comment by Stisen1** [comment]
Sometimes the lines dublicates and centers it down in the battlelog. This makes the long lines expand even beyond the battle-screen border. It only happens when the battle ends, and the battle results pops up. It doesn't always happen. I will look more into it.

**Comment by LeHerosInconnu** [comment]
Hello everyone,

The three little dots (...) at the end of too long sentences, it's ~????????~ a heartbreaker (Hello @zenseii).

All sentences should be displayed in their entirety.
If several lines are needed, let's display several lines.

Laziness is good.
It really is. :)
The three little dots (...) at the end of too long sentences is not good laziness.

**Comment by ihhub** [comment]
@LeHerosInconnu , we will show several lines later. As of now it is better to show ... then rendering over other UI elements.
