### ISSUE TITLE
No wait for luck rainbow animation end

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#636]
Unit starts its attack before ending lucky rainbow animation.

Before recent changes we had a small pause after full rainbow appearance before unit starts its attack.

**Comment by idshibanov** [comment]
![ezgif-5-6970b4c04eae](https://user-images.githubusercontent.com/1373638/83377265-137a4b80-a3a3-11ea-9a3e-7bd9a852c46e.gif)

There shouldn't be any delay?

**Comment by Branikolog** [comment]
I think, there should be a short delay... After the whole rainbow is being completely animated.
Also, iv'e noticed, that at high speeds we cannot even see animation of rainbow. And attack sound overlaps luck sound. In my opinion, at higher speeds animation should be delayed till the moment the sound of lucky attack finishes.
But all these my thoughts are related to the current lucky animation style.

**Comment by shprotru** [comment]
@idshibanov I noticed that in OG the endpoint of the rainbow is on top left of unit's rectangle area, sometimes it's right upper, sometimes it's at center point position, anyway rainbow always goes to the top. The most strange behaviour of rainbow is from picture taked from the google:
![Alt text](https://onyxgame.com/img/game/heroes-of-might-and-magic-2-the-price-of-loyalty/screenshots/heroes-of-might-and-magic-2-the-price-of-loyalty-image-screenshot-6.jpg)
Is it possible to understand behaviour of rainbow in OG?

**Comment by shprotru** [comment]
Hi, @idshibanov! Is luck animation still work? I checked SDL1 and SDL2 builds and everywhere it still as before, I think I was saw it worked the way you did. Am I confused?

**Comment by idshibanov** [comment]
> Hi, @idshibanov! Is luck animation still work? I checked SDL1 and SDL2 builds and everywhere it still as before, I think I was saw it worked the way you did. Am I confused?

@shprotru I think you're a bit confused here. We're still using Heroes1 leftover animation from EXPMRL icn file. Implementing rainbow drawing function is tricky, so it should go as a separate ticket.

> The most strange behaviour of rainbow in OG taked on picture from google, here, as you can see rainbow goes from the right side

Starting position of rainbow in OG is not hard to determine, we have the formula. It depends on direction unit is facing (right or left) and current position. For the screenshot you gave it's something like this: `rainbowX = unitY / 2 + unitX + 150`. Again, problem here is not a position but draw call.

**Comment by shprotru** [comment]
@idshibanov thank you very much for explanations!
