### ISSUE TITLE
Implement Global Hot Key to enable Text Support mode

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#6370]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Right now to turn on text support mode you have to be able to visually navigate to the settings after turning on the game in order to turn on text mode. This defeats the purpose of this feature because many people with visual impairment wouldn't be able to do this. A global hotkey for enabling and disabling it could be one solution.

It has to be possible to turn on this feature when first running the game and the welcome dialog appears.

### Describe the possible solution

Add a Hot Key for text mode.

### Additional info

Any other solutions are welcome. For example enabling during installation.

**Comment by ihhub** [comment]
Hi @zenseii , which key do you suggest to be used?
