### ISSUE TITLE
Troll's throwing animation lasting

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#638]
After a throw trolls or war trolls stand too long with their hands being in front.
In the OG trolls don't pause animation at this moment and start creating new stone at once.
![Troll](https://user-images.githubusercontent.com/55348946/82813560-f70b7a00-9e9d-11ea-8f33-5b5b46d327b7.jpg)

**Comment by idshibanov** [comment]
Aware of this, it's next on the pipeline. Current loop draws one animation at the time so we have to refactor the code in `battle_interface.cpp` to handle multiple at the same time.

**Comment by Branikolog** [comment]
Good to hear you're one step ahead of this issue.)
