### ISSUE TITLE
Assertion on resource collecting

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#6393]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

![image](https://user-images.githubusercontent.com/55348946/208296692-a37dd3eb-85ea-4b56-bc43-503c8ec691c7.png)
![image](https://user-images.githubusercontent.com/55348946/208296737-bb566338-b9db-47f9-900a-b4c6183ee73d.png)

Original campaign, 4 Roland scenario has incorrectly placed resource, which causes assertion on collecting.

### Save file

[X_CRASH_ON_TAKE_RES.zip](https://github.com/ihhub/fheroes2/files/10253728/X_CRASH_ON_TAKE_RES.zip)

**Comment by oleg-derevenetz** [comment]
Yeah, it's some strange place. In OG we can even make the hero stand on this tile:

![fail](https://user-images.githubusercontent.com/32623900/208298003-a52a61ea-18b5-4110-8523-93d3a3f5862c.jpg)

but not on exactly the same tile in another place:

![ok](https://user-images.githubusercontent.com/32623900/208298038-188bba59-5027-4e80-9098-b5dd53b42c9b.jpg)

Probably we should somehow filter out such invalid tiles on map load. Maybe @ihhub will be able to take a look, he is our greatest specialist regarding adventure map structure and passability.

**Comment by Branikolog** [comment]
@oleg-derevenetz 

>Maybe @ihhub will be able to take a look, he is our greatest specialist regarding adventure map structure and passability. Not sure that this will be fixed before 1.0 though, the adventure map is a complex thing. Even if we will have a proper fix, we should test it for possible regressions first.

I hope, he will make a miracle. 🙏 

The issue came out of our community. That's just before the 1.0 release. I'm not sure, what to expect after the release, when thousands of players will play fheroes2. :)
