### ISSUE TITLE
1.0.0 seems to require GLIBC 2.35, is that intentional?

### ISSUE THREAD

**Issue by RobertZenz** [ihhub/fheroes2#6403]
### Your question

The 1.0.0 release (fheroes2_ubuntu_x86-64_SDL2.zip) seems to require GLIBC 2.35 or newer, was that change intentional or is my system broken?

0.9.21 was working fine with GLIBC 2.31.

**Comment by ihhub** [comment]
Hi @RobertZenz , we compile Ubuntu builds based on GitHub Actions build runners. This runners use Docker images of Ubuntu OS and most likely GitHub updated them and this library. We did not do anything intentional about this.

**Comment by RobertZenz** [comment]
Okay, any chance you could downgrade that? GLIBC 2.35 means Ubuntu 22.04 or newer, as far as I know, which is a quite limiting requirement, I guess.

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , what do you think to downgrade GitHub Actions runners to Ubuntu 18.04?

**Comment by oleg-derevenetz** [comment]
Hi @ihhub we can use 18.04 in our `Make` workflow, but I have an impression that this Ubuntu version will become deprecated in the foreseeable future :) 0.9.21 was built with 20.04, because `ubuntu-latest` was 20.04 at the time. Now `ubuntu-latest` is [22.04](https://github.com/actions/runner-images#available-images).

**Comment by ihhub** [comment]
Then let's stick to Ubuntu 20 which has support till 2025 while support for Ubuntu 18 ends in April 2023.

**Comment by undef21** [comment]
Hello @ihhub. ARM64 version building requires 22.04. For 20.04 we should rework the ARM64 build script.

**Comment by oleg-derevenetz** [comment]
@undef21 we can leave the `ubuntu-latest` in the build matrix for ARM64 builds and use an older image for x86-64.

**Comment by ihhub** [comment]
Hi @RobertZenz , please use the latest snapshot for Ubuntu.

**Comment by RobertZenz** [comment]
I can confirm that it's working again, thank you very much.
