### ISSUE TITLE
.MP2 maps for Android

### ISSUE THREAD

**Issue by Mr-Bajs** [ihhub/fheroes2#6404]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Other

### Describe the bug

Tried the new 1.0 version for android.

Been using assets from Homm2 GOLD from GOG and have been putting the maps from the GOG version in 
Android/data/org.fheroes2/files/maps

Been using the same assets for the Flathub version on linux and for Android

Somehow on Android only .mx2 files is shown on the map selection, .mp2 maps isn't.

I was going to play the classic map Broken Alliance. It's in the flathub version but not on the Android version. I assume it's the BROKENA.MP2 that the Broken Alliance map. Though editing the filename to BROKEN.MX2 doesn't seem to work. 

Is Fheroes2 and or Homm2 using several different files for its maps?

### Save file

.

**Comment by oleg-derevenetz** [comment]
There was similar issue somewhere when the program that was used to copy map files to the Android device considered MP2 files as multimedia files because of their expansion and did some wrong actions with them.

**Comment by Mr-Bajs** [comment]
Okey, thanks. 

I solved the problem by renaming the .MP2 files to .MX2 files prior to copying the files and that seams to work. If anyone reads this and have a similar problem.

**Comment by oleg-derevenetz** [comment]
There might be a better solution - pack the files of the original game to the ZIP archive, upload this archive to Android device and then unpack this archive to the appropriate place using, for example, Total Commander for Android or some other similar Android app.

**Comment by JoLiKMC** [comment]
> Is Fheroes2 and or Homm2 using several different files for its maps?
Yes, actually.

- `MP2` files are maps created with / for _The Succession Wars_.  They use only the base game content and can be played with any version of the game.
- `MX2` files are maps created with / for _The Price of Loyalty_.  They use extra content introduced within the expansion, such as extra heroes, artifacts, and map objects, and can only be played with the _Price of Loyalty_ expansion or _Heroes of Might and Magic II Gold_.

I'm a little confused that no one at New World Computing realized that the file extension of `MP2` was already in use by the MPEG-1 Audio Layer II file format, which had been in commercial use [for years](https://en.m.wikipedia.org/wiki/MPEG-1_Audio_Layer_II) before this game was made.  Not very forward-thinking of them, eh?  (:

It's not just Android, though, which sees the files as something they aren't.  Even Windows 10 "recognizes" `MP2` files as MPEG audio, and _no one_ uses 'MP2`, anymore!  Difference being, Windows 10 doesn't _prevent_ programs in the OS from reading the files whereas, seemingly, some Android operating systems do.  Very confusing.

**Comment by ihhub** [comment]
Hi @JoLiKMC , we can't undo what is done before us. We have to deal with it. The new map format won't have mp2 file extension :)

**Comment by viT-1** [comment]
>     * `MP2` files are maps created with / for _The Succession Wars_.
>       They use only the base game content and can be played with any version of the game.
> 
>     * `MX2` files are maps created with / for _The Price of Loyalty_.
>       They use extra content introduced within the expansion, such as extra heroes, artifacts, and map objects, and can only be played with the _Price of Loyalty_ expansion or _Heroes of Might and Magic II Gold_.

Also MP2 maps are saved in "PoL editor" if map hasn't any "new PoL object" .
