### ISSUE TITLE
Random maps generator

### ISSUE THREAD

**Issue by arkeyaallods** [ihhub/fheroes2#6406]
Do you have any plans to make in-game homm3-like RMG with templates, zones, roads and all this stuff?
All homm2 maps and campaigns was cleared many years ago in DOS version countless times, it's not than fun to play them again and again but RMG will add some new and exciting experience.
I know that homm2 has maps generator but it sucks because it generates not completed playable maps but shit. And to play even that "maps" you need to generate it on PC and transfer them to android instead of simply tap 10 times and enjoy right ot the go. Even VCMI can create random maps.

**Comment by ihhub** [comment]
Hi @arkeyaallods , this is in our roadmap. We will eventually add it.

**Comment by ihhub** [comment]
Closing this issue as this is a part of #6845 .
