### ISSUE TITLE
Buttons no longer work in version 1.0.0

### ISSUE THREAD

**Issue by kazenoyouni** [ihhub/fheroes2#6410]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

PlayStation Vita

### Describe the bug

After updating to version 1.0.0, the buttons and analog sticks other than the touchscreen no longer work (The binding of the keys is invalid.). Scrolling the map on the main screen is now easier (In previous version, needed to move the cursor to the edge of the screen to scroll.), but it's very difficult to accurately select a destination on the map or target enemies during combat (When you want to attack from a specified direction, it is more accurate to use the joystick to control the cursor.). Also, the hotkey settings are for the pc, so you can't change the controls.

### Save file

*

**Comment by ihhub** [comment]
Hi @kazenoyouni , which version was working fine for you till it got broken?

**Comment by kazenoyouni** [comment]
Hi @ihhub ,till version 0.9.21, it was working fine. And when I updated to 1.0.0, it got broken.

**Comment by ihhub** [comment]
I think #6342 broke this compatibility with buttons.

**Comment by ihhub** [comment]
@kazenoyouni , can you please explain in details what works and what doesn't work? From the code I see that you can still use the pad buttons to move a hero on Adventure Map.

**Comment by kazenoyouni** [comment]
@ihhub , thank you for checking.
All the buttons (except ps button) and both analog sticks don’t work. I can’t skip the intros, also when I push any button, nothing happens in game. Only the touchscreen and rear touch panel work. I can only use these two to play the game. This phenomenon confirmed on both psv 1000 and 2000.

**Comment by ihhub** [comment]
Hi @kazenoyouni , if we make a special build would you be able to test it and then provide logs?

**Comment by kazenoyouni** [comment]
Hi @ihhub , if you tell me how to do that, I’m glad to test it.

**Comment by ihhub** [comment]
Hi @kazenoyouni , please try [this version](https://github.com/ihhub/fheroes2/suites/10037572278/artifacts/488158660). Just run the game, try to move sticks and press few buttons. The **fheroes2.log** file should appear at the same place where your application is.

**Comment by kazenoyouni** [comment]
Hi @ihhub , I have tried the attached version. Now everything goes OK. But the mentioned fheroes2.log file cannot be found, neither in data/fheroes2/ nor app/FHOMM0002/.
And I have noticed that now if I move the right stick, the hero will move directly on the adventure map (But I can only go straight up and down, or left and right. Can't move diagonally). In 0.9.21, right stick was to scroll the adventure map.
Thank you very much!

**Comment by ihhub** [comment]
Hi @kazenoyouni , your mentioned issue with a hero can be fixed. Let me update the code and you test it again.

**Comment by kazenoyouni** [comment]
Hi @ihhub , OK, I will test it.
Thank you for the prompt action!

**Comment by ihhub** [comment]
@kazenoyouni , please try https://github.com/ihhub/fheroes2/suites/10038117742/artifacts/488196094

**Comment by kazenoyouni** [comment]
@ihhub, now it works perfectly. Many thanks!

**Comment by ihhub** [comment]
@kazenoyouni , thank you very much for testing!

**Comment by kazenoyouni** [comment]
@ihhub , noticed one more thing. While in the hero window, if I move the right stick left or right, it will switch between the heroes quickly. 
While in the castle window, if I move right stick left or right, it will switch between the castles. Also, if I move right stick up or down, it will move the troops into the castle or to the hero side. If this is the expected logic, then it is OK.

**Comment by ihhub** [comment]
Hi @kazenoyouni , we remapped hot keys so now the right stick has additional functionality which is not a bad thing as you usually want to have shortcuts.

**Comment by kazenoyouni** [comment]
Hi @ihhub , duly noted. Thank you for the explanation.

**Comment by ihhub** [comment]
Hi @kazenoyouni , can you please help to test some changes on Vita if I create a separate pull request? I found a way how to speed up rendering but I don't have Vita to test it.

**Comment by kazenoyouni** [comment]
Hi @ihhub No problem. Glad to test it.

**Comment by ihhub** [comment]
@kazenoyouni , please compare [master branch build](https://github.com/ihhub/fheroes2/releases/tag/fheroes2-psv-sdl2_dev) and [optimized build](https://github.com/ihhub/fheroes2/suites/10053567061/artifacts/489252438). You need to enable System Info in Configuration --> Graphics. Then on Adventure Map set hero speed to 9 and walk a hero from point A to point B. Do the same walking for another build and check what FPS value is for both builds. It fluctuates a bit but if the improvement is reasonable you would see the difference.

**Comment by kazenoyouni** [comment]
@ihhub , I have tested, however, no big difference found between these 2 versions. If you give me a place to upload the videos, I can do it.

**Comment by ihhub** [comment]
Hi @kazenoyouni , you can upload them even here. Is there no difference at all or slight difference?

**Comment by kazenoyouni** [comment]
https://user-images.githubusercontent.com/111102725/209549578-1cf7943f-bf44-49a9-b8be-4763a918279c.mp4


https://user-images.githubusercontent.com/111102725/209549588-f8229209-7018-4c07-be30-039d52af7366.mp4

@ihhub , for me hardly see the differece even shot the video in slow motion.

**Comment by kazenoyouni** [comment]
@ihhub , some more videos here.

https://user-images.githubusercontent.com/111102725/209550463-e2f9a670-168c-4588-8046-e3310384bc08.mp4


https://user-images.githubusercontent.com/111102725/209550468-aa82af3f-7f70-493d-be8f-82e6cd7f9e85.mp4


https://user-images.githubusercontent.com/111102725/209550469-a8e87cc2-2b8f-48ec-a2dd-2c770e22619d.mp4


https://user-images.githubusercontent.com/111102725/209550471-ef750f29-23d2-41aa-bc74-be930a6029fd.mp4

**Comment by ihhub** [comment]
Hi @kazenoyouni , it's almost the same, at least not worse. I'm not entirely sure why as I removed a whole frame copying command.

**Comment by kazenoyouni** [comment]
Hi @ihhub , OK. If you need further tests, please let me know.

**Comment by ihhub** [comment]
Hi @kazenoyouni , can you please the same tests for 640x480 resolution?

**Comment by kazenoyouni** [comment]
Hi @ihhub , same result as 960x544 resolution.
