### ISSUE TITLE
Screen flickering on tablet outside viewable area

### ISSUE THREAD

**Issue by drevoborod** [ihhub/fheroes2#6422]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Other

### Describe the bug

There is annoying screen flickering on Android tablet when the game is in 4:3 screen mode (any resolution). 
OS: Android 8.1.0
Device: Lenovo TB-X304L
Native screen resolution: 1280x800
Steps to reproduce:
1. Set game resolution to 640x480 or 800x600. 
2. Tap anywhere on the screen.
Result: everytime when the screen is being tapped there is flickering outside image borders (in the space where normally should be blank screen because image is 4:3 and the screen itself is 16:10).

### Save file

Not necessary - it can be reproduced even in main menu.

### Additional info

https://user-images.githubusercontent.com/10282847/209815240-abc9c24a-740f-40f8-9293-aa9af78422a9.mp4

https://user-images.githubusercontent.com/10282847/209815017-487b8536-12ef-4476-af97-839619668f16.mp4

**Comment by oleg-derevenetz** [comment]
Interesting issue. I was unable to reproduce it so far on my old Lenovo tablet with Android 6.0 as well as on my Sony Xperia with Android 10. This is video from the Lenovo tablet with 640x480 and black bars on both sides of the screen:

https://user-images.githubusercontent.com/32623900/209819117-5044b6ba-1903-406a-9b79-c2ddaf900d48.mp4

**Comment by drevoborod** [comment]
Maybe I can provide some additional information?

**Comment by oleg-derevenetz** [comment]
@drevoborod, @ihhub seems to have an idea why this may happen.

**Comment by drevoborod** [comment]
Ok, please feel free to ask me if any additional information required. Also I could install patched version of apk before a fix will be merged to the release brach :)

**Comment by ihhub** [comment]
Hi @drevoborod , can you please try [this build](https://github.com/ihhub/fheroes2/suites/10085667364/artifacts/491438949) ?

**Comment by drevoborod** [comment]
@ihhub Sorry, no luck - a problem still persists. Tried both resolutions, with and without vsync and both in menu and during a game.

**Comment by oleg-derevenetz** [comment]
@drevoborod Looking at your two videos, I thought - does the appearance of this effect depend on the force of pressure on the screen? In your second video, for example, flickering is clearly visible only at the moment of pressing the screen.

**Comment by drevoborod** [comment]
Flickering definitelly appears when I place my finger on the screen and move it. Sometimes when I just tap on the screen it does not flicker. Looks like it happens on "tap+drag" gesture, not just "tap".

**Comment by oleg-derevenetz** [comment]
@drevoborod

> Flickering definitelly appears when I place my finger on the screen and move it.

What I meant is that on your second video flickering appears at the moment when you put your finger on the screen and not when you move it after that. What if you just put your finger on the screen and don't move it, will that parasitic image appear at the edges of the screen? Does the appearance of a parasitic image depend on the finger's pressure force (what if you press your finger harder or weaker)? I want to exclude the option of a banal mechanical or electrical malfunction.

**Comment by drevoborod** [comment]
No, of course it's not a malfunction because there is no such effect in any other app and even in fheroes if it's aspect ratio fits the aspect ratio of the display (16:10). So it does not depent on the pressure force. And I'm not sure that it's easy to just put your finger and not to move it at all. Sometimes I can do it but it's hard to reproduce because the system detects any micro move including ones that aren't noticiable for myself. Afaic, in most software there is even an artificial ignorance of such micro moves implemented to separate the gesture "tap" from "tap and move".

**Comment by ihhub** [comment]
Hi @drevoborod , do you use the original Android version or some flavor of it?

**Comment by drevoborod** [comment]
Here is a demonstration of map dragging without flickering:

https://user-images.githubusercontent.com/10282847/209894489-9a870a6f-399a-450e-b561-691765d73a21.mp4

**Comment by drevoborod** [comment]
@ihhub It's an original Android version provided by the manufacturer. So it's not "pure" Android of course, it's with some changes by Lenovo.

**Comment by ihhub** [comment]
@drevoborod , we are building another Android build with hypothetical fix. Let's see if it would help.

**Comment by ihhub** [comment]
@drevoborod , can you please try to use [this build](https://github.com/ihhub/fheroes2/suites/10093268783/artifacts/491938501)?

**Comment by drevoborod** [comment]
Yes, it helped! No flickering anymore in every screen resolution and vsync mode! Checked both in main menu and in game.

**Comment by drevoborod** [comment]
I guess that the issue has been fixed by this addition:
`int returnCode = SDL_RenderClear( _renderer );`
Isn't it? :)

**Comment by ihhub** [comment]
> I guess that the issue has been fixed by this addition:
> `int returnCode = SDL_RenderClear( _renderer );`
> Isn't it? :)

Yes for non-full frame rendering cases.
