### ISSUE TITLE
Do not use macOS-latest label on GitHub Actions

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#6426]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Based on the information from GitHub Action artifacts the GitHub team is going to upgrade default macOS to 12. See [this](https://github.com/actions/runner-images/issues/6384).

### Describe the possible solution

Use macos-11 (?) label for the existing jobs to avoid unnecessary bump in requirements.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub we already use, `macos-11` in jobs that produce artifacts (`Make` workflow). But we also have jobs that doesn't produce them (for example in `CMake` workflow), I don't see a reason not to use `macos-latest` in these jobs.

**Comment by ihhub** [comment]
Ah, yes. I saw them only in cmake, while make has macos-11. You're absolutely right.
