### ISSUE TITLE
Cannot change Human to AI in single mode after starting Hot Seat mode

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#643]
If you start playing Hot seat mode and choose opponent as human, and then start play the same map in single mode - opponent is still human and you cannot change it to AI.

**Comment by Branikolog** [comment]
Also, if you start new game in a single mode, and then return to main menu, choose hot seat mode, you won't be able to add human player, until you change a selected scenario

**Comment by ihhub** [comment]
Closing this issue as it was fixed some time ago.
