### ISSUE TITLE
External music does not work anymore begins from 1.0.0 but works on 0.9.21

### ISSUE THREAD

**Issue by asm64** [ihhub/fheroes2#6434]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

Good day, bad news.

External music does not work anymore begins from 1.0.0. I have Ubuntu 20.04.5 LTS (Focal Fossa). Build from source:

FOPT="-march=amdfam10 -O2"
cmake -B build -DUSE_SDL_VERSION=SDL2 -DENABLE_IMAGE=ON -DCMAKE_CXX_FLAGS="$FOPT"
cmake --build build

but in latest snapshot the same.

If I roll back git to 0.9.21 and build then external music works fine. Music in ./music/homm2_XX.ogg.
In 1.0.0 always play midi even if set external music.

In output I have:
[ERROR]	playSound:  Failed to create an audio chunk from memory. The error: Unsupported block alignment
but this error occurs in both 1.0.0 and 0.9.21. Only in 1.0.0 no external music.

Thanks.

### Save file

Save file not needed

**Comment by oleg-derevenetz** [comment]
```
[ERROR] playSound: Failed to create an audio chunk from memory. The error: Unsupported block alignment
```

This error is returned by SDL when it tries to play the a-law or u-law compressed audio, and this audio has the wrong format or it is corrupted. This error is strange in itself (where did this corrupted x-law soundtrack come from?)

**Comment by asm64** [comment]
> ```
> [ERROR] playSound: Failed to create an audio chunk from memory. The error: Unsupported block alignment
> ```
> 
> This error is returned by SDL when it tries to play the a-law or u-law compressed audio, and this audio has the wrong format or it is corrupted. This error is strange in itself (where did this corrupted x-law soundtrack come from?)

$ file homm2_01.ogg
homm2_01.ogg: Ogg data, Vorbis audio, stereo, 44100 Hz, ~192000 bps

In 0.9.21 the same error, but external audio plays well

**Comment by asm64** [comment]
> Hi, @asm64. Are these the music files supplied with Heroes 2 from GOG/Ubisoft or did you rip them yourself from your own CD/get them elsewhere?

I don't remember exactly, it was a long time ago. Unfortunately, my friends didn't return my collectible gold disc to me, they lost it and I can't make my own rip anymore. Here I checked for sure that everything still works in version 0.9.21, and there is a regression in 1.0.0.

**Comment by oleg-derevenetz** [comment]
> Here I checked for sure that everything still works in version 0.9.21, and there is a regression in 1.0.0.

Since you are building from sources, could you please perform the `git bisect` process and find the exact commit after which you started experiencing this issue? I can't reproduce this issue.

**Comment by oleg-derevenetz** [comment]
Also could you please tell, where your `fheroes2` binary is located, where are your music files are located and how exactly you run your `fheroes2` binary?

**Comment by asm64** [comment]
> Also could you please tell, where your `fheroes2` binary is located (full path), where are your music files are located (full path) and how exactly you run your `fheroes2` binary?

2b21450568fb6c2d2e987f533a46d80d604a547a is the first bad commit
commit 2b21450568fb6c2d2e987f533a46d80d604a547a
Author: Oleg Derevenetz <oleg-derevenetz@yandex.ru>
Date:   Wed Nov 23 04:12:57 2022 +0300

    Fix multiple issues with auxiliary functions from the engine (#6235)

 src/engine/dir.cpp                        |   6 +-
 src/engine/logging.cpp                    |  22 ++-
 src/engine/logging.h                      |   4 +-
 src/engine/rand.cpp                       |   4 +-
 src/engine/system.cpp                     | 308 ++++++++++++++----------------
 src/engine/system.h                       |  20 +-
 src/fheroes2/audio/audio_manager.cpp      |   4 +-
 src/fheroes2/dialog/dialog_selectfile.cpp |   4 +-
 src/fheroes2/game/fheroes2.cpp            |  45 +----
 src/fheroes2/game/game_highscores.cpp     |   2 +-
 src/fheroes2/game/game_hotkeys.cpp        |   2 +-
 src/fheroes2/game/game_io.cpp             |   6 +-
 src/fheroes2/game/game_video.cpp          |   4 +-
 src/fheroes2/h2d/h2d.cpp                  |   2 +-
 src/fheroes2/system/save_format_version.h |   5 +-
 src/fheroes2/system/settings.cpp          | 148 +++++++-------
 src/fheroes2/system/settings.h            |  12 +-
 src/fheroes2/world/world.cpp              |   4 +-
 src/tools/extractor.cpp                   |   2 +-
 src/tools/icn2img.cpp                     |   4 +-
 src/tools/til2img.cpp                     |   4 +-
 21 files changed, 276 insertions(+), 336 deletions(-)

**Comment by oleg-derevenetz** [comment]
> Also could you please tell, where your `fheroes2` binary is located (full path), where are your music files are located (full path) and how exactly you run your `fheroes2` binary?

?

**Comment by asm64** [comment]
> Also could you please tell, where your `fheroes2` binary is located (full path), where are your music files are located (full path) and how exactly you run your `fheroes2` binary?

binary path: ~/Games/build/fheroes2/fheroes2
music path: ~/Games/build/fheroes2/music

**Comment by oleg-derevenetz** [comment]
> how exactly you run your fheroes2 binary?

? By using the following scheme:

```
$ cd ~/Games/build/fheroes2
$ ./fheroes2
```

or something else?

**Comment by asm64** [comment]
> > how exactly you run your fheroes2 binary?
> 
> ? By using the following scheme:
> 
> ```
> $ cd ~/Games/build/fheroes2
> $ ./fheroes2
> ```
> 
> or something else?

Yep. Exactly.

**Comment by oleg-derevenetz** [comment]
Hi @asm64 please test the changes from #6435, does this PR solve your problem? Also please test these changes with all combinations of launch conditions, such as:

```bash
$ cd ~/Games/build/fheroes2
$ mv music mUsIc
$ ./fheroes2
$ PATH="." fheroes2
$ cd ..
$ fheroes2/fheroes2
$ ./fheroes2/fheroes2
$ cd /
$ ~/Games/build/fheroes2/fheroes2
```

**Comment by asm64** [comment]
> Hi @asm64 please test the changes from #6435, does this PR solve your problem? Also please test these changes with all combinations of launch conditions, such as:
> 
Wait, in process now

**Comment by asm64** [comment]
> ```shell
> ~/Games/build/fheroes2/fheroes2
> ```

Everything works fine! All variants. Confirm, you can merge fix.

**Comment by oleg-derevenetz** [comment]
@asm64 thank you!

**Comment by asm64** [comment]
> @asm64 thank you!

Thank you too and happy New Year!
