### ISSUE TITLE
High CPU usage in Select Language dialog

### ISSUE THREAD

**Issue by a1exsh** [ihhub/fheroes2#6445]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

When the "Select Language" dialog is open, a single CPU core is used to ~90%, which is not the case for normal game operations or other dialogs.

### Save file

No save file needed to reproduce.

**Comment by ihhub** [comment]
This is due to this chunk of code:
```cpp
            if ( items.isSelected() ) {
                chosenLanguage = items.GetCurrent();
                Settings::Get().setGameLanguage( fheroes2::getLanguageAbbreviation( chosenLanguage ) );
            }
```
