### ISSUE TITLE
See the spellbook after casting a spell

### ISSUE THREAD

**Issue by VanHexing** [ihhub/fheroes2#6463]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Sometimes I want to look through the spellbook after a spell is casted.  In the current version, it is impossible till the end of the turn.

### Describe the possible solution

Make the darkened spellbook icon clickable, and the spells in the book right-clickable (though not left-clickable).

**Comment by LeHerosInconnu** [comment]
Hello @VanHexing,

You can access the magic book (and much more) by clicking on the hero's portrait at any time.

In fheroes2:

![Hero spells 001](https://user-images.githubusercontent.com/43583994/210874340-8d9cfad1-6f59-4089-b0ac-f70620790377.png)

![Hero spells 002](https://user-images.githubusercontent.com/43583994/210874348-0be32389-7aac-4539-bb18-ef4c129f1225.png)

**Comment by ihhub** [comment]
I am closing this issue as the author of this topic was given the solution for the problem.
