### ISSUE TITLE
Pathing issue?

### ISSUE THREAD

**Issue by Arthusppp** [ihhub/fheroes2#6470]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

When I click unicorns, I suppose, my hero should go straight up and fight them. However, my hero chooses to go around. 

![image](https://user-images.githubusercontent.com/85434237/211171542-570749ea-4fa9-430f-a28e-7d982b7705b1.png)

![image](https://user-images.githubusercontent.com/85434237/211171549-806a0190-c3d0-46a3-bb35-b04ddb50e362.png)

### Save file

[Broken_Alliance_0059.zip](https://github.com/ihhub/fheroes2/files/10367250/Broken_Alliance_0059.zip)

**Comment by Branikolog** [comment]
Hi, @Arthusppp .
I suppose, this is duplicate of existing issue: https://github.com/ihhub/fheroes2/issues/4274.

**Comment by oleg-derevenetz** [comment]
> I suppose, this is duplicate of existing issue: https://github.com/ihhub/fheroes2/issues/4274.

Yes, it is the same issue. Hero can't move diagonally from the cell to the bottom right from the Unicorns and attack them directly because of tile passability issue.

**Comment by Arthusppp** [comment]
If you find this as the same root cause, then I am closing this issue. Thanks for checking!
