### ISSUE TITLE
Only MIDI music is used in 1.0.0

### ISSUE THREAD

**Issue by gamvrosi** [ihhub/fheroes2#6477]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [ ] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

macOS

### Describe the bug

I have installed the latest macOS ZIP package (version 1.0.0). Regardless of what option I pick (MIDI, MIDI Expansion, or Extended), only the MIDI music plays. I am using the latest GOG version and have transferred the MUSIC/ directory along with all the .ogg files (e.g., `MUSIC/homm2_41.ogg`), which I have checked are playable via a music player (e.g., VLC).

I cannot find any documentation on this, is this expected behavior? Please advise!

### Save file

N/A

**Comment by oleg-derevenetz** [comment]
Hi @gamvrosi looks like a duplicate of #6434. Please download the latest snapshot from [here](https://github.com/ihhub/fheroes2/releases/tag/fheroes2-osx-sdl2_dev) and try to run it.

**Comment by gamvrosi** [comment]
This is indeed a duplicate, my apologies for not noticing that. Will try latest snapshot!

Thank you for all your hard work on this porject!

**Comment by oleg-derevenetz** [comment]
Hi @gamvrosi Please let us know if this issue is still being observed with the latest snapshot.

**Comment by gamvrosi** [comment]
It is not. Just downloaded the latest commit and confirmed it. Thanks!
