### ISSUE TITLE
Infinite loop when redrawing the wince animation after a lich shot

### ISSUE THREAD

**Issue by oleg-derevenetz** [ihhub/fheroes2#6482]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

* Load the attached savefile;
* Attack Roxana by Myra;
* Arrange the units as shown on the following screenshot:

![lich](https://user-images.githubusercontent.com/32623900/212440286-84256261-1731-44e3-8ebd-f3951f03c627.jpg)

* Make the Lich shoot at the Golems;
* Observe an infinite loop in the `Battle::Interface::RedrawActionWincesKills()`.

### Save file

[Lich_Test.zip](https://github.com/ihhub/fheroes2/files/10416162/Lich_Test.zip)

### Additional info

Looks like a regression after #6414. On commit b4383ecb there is no infinite loop while on commit b200ee96 it is observed.

**Comment by oleg-derevenetz** [comment]
Hi @Districh-ru could you please take a look at this issue?

**Comment by Districh-ru** [comment]
Hi @oleg-derevenetz, thanks for finding this issue!
