### ISSUE TITLE
Visiting first obelisk doesn't reveal puzzle part

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#6485]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

When we have many obelisks on a map, visiting the first one doesn't reveal any part of puzzle map

https://user-images.githubusercontent.com/55348946/212466865-87cc2cf4-e040-49e2-8e01-be1dc96540c7.mp4

### Save file

[1st puzzle.zip](https://github.com/ihhub/fheroes2/files/10417110/1st.puzzle.zip)

**Comment by oleg-derevenetz** [comment]
I just checked the OG behavior in this case.

* OG map editor will warn you if there are more than 48 Obelisks on the map (because puzzle map has 48 fragments);
* OG won't reveal the first puzzle fragment either when visiting the first Obelisk if there are more than 48 Obelisks on the map.

So this is not a bug, this is an exact reproduction of the OG behavior.

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz !
Indeed.
Correct me if I'm wrong, the current algorithm skips revealing of some puzzle parts within that sequence of 48+ visited obelisks depending on the exceeded number. I mean, if there're 50 obelisks, it skips revealing on first and ~24 obelisk visiting.
It's quite an elegant solution, but the only thing bothering me is exactly the first puzzle part not being revealed with the first obelisk. I mean, for new players (and even me) it looks, like something is broken when hero visits and nothing happens. I agree with you, that this is the original behaviour, but what if we reclassify this issue as enhancement and change algorithm a bit to reveal at least the first puzzle part in such cases (48+ obelisks), so players would understand, what's happenning after they visited the first obelisk.
It would be OK for me, if even the second obelisk wouldn't reveal puzzle part (probably, better would be to distribute these "non working obelisks" somewhere in the middle of sequence). But the first one revealed would show to a player, what are they really for. 
I believe this inconsistency with the original game wouldn't break the complexity of searching for UA in cases, when the map has so many obelisks.

**Comment by oleg-derevenetz** [comment]
@Branikolog how many real maps have more than 48 Obelisks (especially given that OG editor deliberately warns about the number of Obelisks on the map)?

**Comment by Branikolog** [comment]
@oleg-derevenetz 
I haven't met any. :-D
But in future they could appear, since we're going to add new map format.
As a hardcore player I'm not against current logic. I even would accept, if we skip, for instance, 10 puzzle parts reveals with first 10 obelisks and continue revealing 48 remaining one by one (in a case therere 58 obelisks on a map).
But skipping the first puzzle revealing looks really not accurately regarding game design.

**Comment by oleg-derevenetz** [comment]
@Branikolog This works this way (both in OG and in fheroes2): for each new obelisk the total number of fragments that should be revealed is calculated using the formula `visitedObelisks * 48 / totalObelisks`. So if `totalObelisks` is more than 48 and `visitedObelisks` is too small (say, 1) the result is zero, so no fragments will be shown. As `visitedObelisks` increase, the result will become 1 eventually (if `totalObelisks` is more than 48, but less than 97, it will happen on the second obelisk), then 2, etc, etc.

**Comment by Branikolog** [comment]
> @Branikolog This works this way (both in OG and in fheroes2): for each new obelisk the total number of fragments that should be revealed is calculated using the formula `visitedObelisks * 48 / totalObelisks`. So if `totalObelisks` is more than 48 and `visitedObelisks` is too small (say, 1) the result is zero, so no fragments will be shown. As `visitedObelisks` increase, the result will become 1 eventually (if `totalObelisks` is more than 48, but less than 97, it will happen on the second obelisk), then 2, etc, etc.

I see. I'm only proposing to show that "zero" fragment in the middle of attended obelisks sequence. Let's say we have 49 obelisks. Can we show that "zero" puzzle part on visiting 25th obelisk? Not the first one, which makes an impression, that obelisks doesn't work at all. Especially, if you're playing the game for the first time.
In a case map has 50 obelisks, "zero" parts would be revealed on 17th and 34th obelisks. 51 obelisks -> 13th, 26th, 39th attendance and etc...

**Comment by oleg-derevenetz** [comment]
> In a case map has 50 obelisks, "zero" parts would be revealed on 17th and 34th obelisks. 51 obelisks -> 13th, 26th, 39th attendance and etc...

Then let's reconsider this as a request for improvement. However I still have no idea why map should have more than 48 obelisks given that some of them will be definitely useless :) The developers of the original game apparently did not understand this either.

**Comment by Branikolog** [comment]
@oleg-derevenetz 

> Then let's reconsider this as a request for improvement. However I still have no idea why map should have more than 48 obelisks given that some of them will be definitely useless :) The developers of the original game apparently did not understand this either.

I think, to force player to visit not 48 obelisks, but 60, for instance, to reveal the whole puzzle map. )

I've converted thread into "improvement", 👍
