### ISSUE TITLE
Combat screen, AI fails to cast Resurrect spell

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#6492]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

It was really hard to catch and reproduce the bug.
Here's a guide to reproduce the bug. I recommend to repeat all steps, since depending on hero stats and creatures  the result may vary.

https://user-images.githubusercontent.com/55348946/212499987-bdf1c635-1159-4e37-9346-ad0a3b47caee.mp4

https://user-images.githubusercontent.com/55348946/212499994-9cf9715f-a918-4fdc-8d05-268d66ce3ce3.mp4

It was really hard to catch and reproduce the bug. Sorry for such long video.

AI it strying to use Resurrect spell but nothing happens.

### Save file

None.

**Comment by oleg-derevenetz** [comment]
It looks like the AI is trying to cast a resurrection on one of the dead stacks on which the dragons are standing. This cast was ignored by the engine, so game logic seems fine, but AI shouldn't perform this cast of course.

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz 
The thing is that it not always behaves like that. If I kill his both stacks and place my troops over them he simply skips casting. The issue occurred even if there were no enemy corpses covered by my troops. I think, here could be a problem with AI trying to resurrect recently defeated clone of some creature.

**Comment by oleg-derevenetz** [comment]
@Branikolog Yes, it looks like it. Mirror images are added to the army, but not to the graveyard, and AI doesn't look whether the unit it tries to resurrect is in the graveyard when it tries to resurrect it, and this attempt fails because the game logic code checks the graveyard then.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
I hope, this could be fixed without global code rewriting. :pray: 
Btw, the issue occurs for both Resurrect and Resurrect true spells.
