### ISSUE TITLE
Castle graphic error 

### ISSUE THREAD

**Issue by alexanderlindstrom** [ihhub/fheroes2#6497]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

I noticed this graphical bug in the map "Arrax the Jerk". When I captured the town Weddington and looked at the castle screen, this is what it looked like:
![fheroes](https://user-images.githubusercontent.com/1754686/212834796-5e90991d-0557-4c59-839a-1f610e378061.png)

Playing with 1280x960, windowed mode, v-sync off

### Save file

[Arrax_the_Jerk_0029.sav.zip](https://github.com/ihhub/fheroes2/files/10432374/Arrax_the_Jerk_0029.sav.zip)

**Comment by ihhub** [comment]
Hi @alexanderlindstrom , isn't it the same in the original game?

**Comment by alexanderlindstrom** [comment]
I do not have the original name, but you are probably right. But could this because there are some buildings (moat, tower, etc.) already built before the castle is built?

I just figured it looked so strange that it was an graphical glitch.

**Comment by alexanderlindstrom** [comment]
I can now confirm that this is beacuse the towers, moat and captains quarter is already, that is why it looks like that. I will close this issue.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

I think the new scenario editor of fheroes2 should take this into account and not allow turrets and moat if the castle is not built.

Also, maybe when loading a scenario created with the scenario editor of the original game, fheroes2 should not display the turrets and the moat if the castle is not built, a kind of "automatic correction".
What do you think about it ?

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , we shouldn't change the logic for existing maps but we will add checks in the future editor.
