### ISSUE TITLE
The speed of creatures in the information window

### ISSUE THREAD

**Issue by DM-VLK** [ihhub/fheroes2#6526]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

The speed of creatures in the information window is indicated only by words (Average, Fast, etc.)

### Describe the possible solution

I propose to indicate the speed of creatures in the window of information with a number in brackets from 1 to 6

**Comment by ihhub** [comment]
Hi @DM-VLK , which version of fheroes2 do you use?

This is what the current version has:
![image](https://user-images.githubusercontent.com/19829520/214887517-cd0bafb3-9a62-4c52-88ea-6d3f41f69d5d.png)

It clearly stated the speed in numbers.

**Comment by ihhub** [comment]
That's a good point. I suggest to rename the title and update the description stating where exactly the missing numbers are.
