### ISSUE TITLE
Pathfinding issue

### ISSUE THREAD

**Issue by Arthusppp** [ihhub/fheroes2#6528]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

I suppose, my hero in the first step should go down, not down-left.

![image](https://user-images.githubusercontent.com/85434237/214955355-35ce9ccd-d602-4bad-be9e-533409f70270.png)

### Save file

Play Hot Seat, 2 players:
[Dobro_kontra_Z!o_0001.zip](https://github.com/ihhub/fheroes2/files/10513541/Dobro_kontra_Z.o_0001.zip)

**Comment by oleg-derevenetz** [comment]
This is not a bug, the original HoMM2 has the same path here:

![path](https://user-images.githubusercontent.com/32623900/214970649-edc7707b-89bf-4a25-a92a-bf575ff99f78.jpg)

In fact, there is a shrub on the tile below the hero:

![shrub](https://user-images.githubusercontent.com/32623900/214970839-6a0efe49-d721-4d11-8ff5-5897899f6607.jpg)

and this tile cannot be traversed in the vertical direction, only in the horizontal one.
