### ISSUE TITLE
Battle animation: Creature's contour problem

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#653]
In our version creature's black contour is drawn a bit blurred, so yellow highlighting is drawn with gap in ~1 pixel.
![Genie](https://user-images.githubusercontent.com/55348946/83022588-6a46f480-a034-11ea-954b-674831e53fe3.jpg)
And this is how it looks in the OG:
![Genie2](https://user-images.githubusercontent.com/55348946/83022613-7763e380-a034-11ea-81c4-85ee8727f67b.jpg)

**Comment by ihhub** [comment]
This is something to do with our decoding and in particular shadow interpretation.
