### ISSUE TITLE
the interface is too small

### ISSUE THREAD

**Issue by kkooka1** [ihhub/fheroes2#6546]
### Your question

Even when the screen is reduced, the interface is too small. i use windows 10 and [fheroes2_windows_x64_SDL2.zip]

I can't find any shortcuts or how to adjust the resolution either in the files or in the game. F4 is for windowed and fullmode only.

please help me 

![11](https://user-images.githubusercontent.com/124224465/216216248-28315a65-8cc0-4f61-b95a-15f36ba64b13.PNG)

**Comment by ihhub** [comment]
Hi @kkooka1 , can you please set smaller resolution and hit F4 keyboard button?

**Comment by ihhub** [comment]
Since you mentioned F4 you can just resize window as you want🙂 We are working on adding scaled resolutions, #6516 pull request is in review stage right now.

**Comment by kkooka1** [comment]
> 안녕@kkooka1, 더 작은 해상도를 설정하고 F4 키보드 버튼을 눌러 주시겠습니까?

impossble
