### ISSUE TITLE
Add a new icon for Graphics Settings

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#6550]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

We utilize many existing icons and this is bad. Every option should have its own unique icon. This is how the graphics settings icon look like and the same icon is used for mixed Interface type in the original game:
![image](https://user-images.githubusercontent.com/19829520/216775896-6fd2e405-eda2-4c85-8d8c-e94f78e636e6.png)

### Describe the possible solution

Add a brand new icon which is suitable for this option.

**Comment by Laserlicht** [comment]
Maybe this one?
![icon_fheroes2_graphics](https://user-images.githubusercontent.com/13953785/219797063-9eed41aa-0d18-47d6-af1e-cdc73b28e856.png)

Based on https://www.svgrepo.com/svg/20418/video-card (CC0)

**Comment by ihhub** [comment]
I assigned this issue for myself but in reality it is handled by @golden-lining

**Comment by ihhub** [comment]
Hi @Laserlicht , we are going to add slightly different new icon without using open source assets. However, we might use your ideas for an option to choose rendering API which is essentially a bridge between GPU and monitor.

**Comment by Shadic93nh** [comment]
I would also personally add an option to have a possibility to do a button that will allow on android and other mobile ports to have stretch to screen or keep aspect ration so we can enjoy it in full beauty as on higher resoultion most of text becomes unreadable
