### ISSUE TITLE
Make pixel artist work more efficient

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#6553]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Based on the latest feedback from people who want to contribute into the project's pixel art there are multiple obstacles for them to get started with work. We have to improve and simplify the onboarding stage for any potential artists.

### Describe the possible solution

This is the list of things we need to do in order to simplify artists' work
- [x]  add a separate compilation stage to compile tools such as **icn2img** and **extractor**. We don't need to cover every single OS. Windows and (optional for now) macOS are enough. Most of artists use only these OSes. Only SDL 2.
- [x] add extra bash and bat scripts to automate the work of tools or modify them. For instance, **icn2img** accepts only a single image.
- [x] add documentation as we did for developers and translators which tools to download, how to extract images and which issues to look in GitHub as a start point.
- [x] add a tool to load an image from a disk, convert it internally and save it on disk as well. This will allow artists to see how the final image would look like in the game and to verify that they use correct palette.
- [x] add a tool to generate an image of colors present in KB.PAL file. 16x16 tiles of 16 pixels each.
- [ ] add a list of color indexes used for cycling into the documentation.
- [x] add support of loading of 8-bit BMP images

**Comment by oleg-derevenetz** [comment]
> add a separate compilation stage to compile tools such as icn2img and extractor. We don't need to cover every single OS. Windows and (optional for now) macOS are enough. Most of artists use only these OSes. Only SDL 2.

Tools are already being built for Windows, macOS and Linux, they are just not packed into the ZIP file.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub Could you please tell me, which tools are still worth to build and put into the ZIP file? As far as I can see, not all tools even have a project file for MSVC. Are there any superfluous/outdated ones among them? Maybe some need to be modernized, like `icn2img`? I am very little familiar with the artists' needs.

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , `extractor` and `icn2img`. The rest of tools are no in use by anyone.

An artist should download these 2 tools, ideally run a script which will unpack files and create all necessary images. We can also add extra generated files which will contain image offsets present in some ICN images.

**Comment by ihhub** [comment]
Hi @zenseii , could I please ask you to draft a documentation file for artists? We added an extra package into pre-releases for Windows and macOS builds. These tools help to extract files including image conversion. A simple guide would be sufficient. We also need to include this guide / README file into the archive which we can do later.

**Comment by oleg-derevenetz** [comment]
> I tested the extraction script and it seems it doesn't work with the HEROES2X.agg file. It reports Cannot open file *.agg.
The Succession Wars HEROES2.agg worked fine.

It will report this if there is no `*.agg` files :) My home-grown implementation of wildcards is case-sensitive, so this script runs the following command: `extractor *.AGG *.agg`. If there are `HEROES2.AGG` and `HEROES2X.AGG`, it will extract both, but will report about missing `*.agg` files, which is not an error.

**Comment by oleg-derevenetz** [comment]
@zenseii

> Actually, what happens with the ICNs that have the same names in both `HEROES2.agg` and `HEROES2X.agg`

The former will be overwritten by the latter. Yes, it would be good then to modify this script so these AGG files will be extracted to separate directories. I'll do this later today.

**Comment by oleg-derevenetz** [comment]
@zenseii

> Are we planning to add the generation of the palette image into the script too or do we leave it as a command line tool? I just need to know what to write in the guide.

Well, why not, if @ihhub deems it appropriate.

**Comment by ihhub** [comment]
Hi @zenseii and @oleg-derevenetz , yes, we should add this into the scripts.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub the only item left in this issue is "add a list of color indexes used for cycling into the documentation". Is this item still relevant? How to obtain these color indexes?
