### ISSUE TITLE
Kingdom Income is not displayed over the area of Gold Income in Kingdom Overview window

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#6557]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Open Kingdom Overview window and right-click on any mine / sawmill to see Kingdom Income. However, this is not the case when you click on Gold Per Day area:
![image](https://user-images.githubusercontent.com/19829520/216778018-7e8bf427-23a9-40ff-a7b2-a47ec6f9f28c.png)

### Save file

Start any game and go to Kingdom Overview dialog.

**Comment by Kazhuu** [comment]
I'll take a look at this.

**Comment by ihhub** [comment]
Sure.
