### ISSUE TITLE
City of the dead sprite enhancement

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#6574]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

City of the damned was created to fit desert terrain.
![City of the dead](https://user-images.githubusercontent.com/55348946/216816356-41dbc75a-3fe3-4340-99da-d9f1215e3269.png)

### Describe the possible solution

It would be nice to enhance the sprite to be able place it on other terrains.
- I think the most suitable is snow terrain, which would require minimum changes of the sprite itself and mostly switch to white colour.
- Sprite should have more smooth and esthetically pleasing edges, so it can be placed on any terrain. (Except of snowy, as it should have some snow over the buildings anyway)

**Comment by ihhub** [comment]
I'm closing this issue as adding new terrain variants of existing objects is on the plate for the Editor.
