### ISSUE TITLE
Translation progress

### ISSUE THREAD

**Issue by Laserlicht** [ihhub/fheroes2#6588]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Currently there is no overview where how many untranslated strings are in which language.

### Describe the possible solution

Maybe after updating the translations a json with status could be generated, which could then be displayed with shields in percent for each language.

`https://img.shields.io/badge/dynamic/json?url=<CURL>&label=<LABEL>&query=<$.DATA.SUBDATA>&color=<COLOR>&prefix=<PREFIX>&suffix=<SUFFIX>`

**Comment by ihhub** [comment]
Since we use po files for translation we can try [this approach](https://stackoverflow.com/questions/10218026/get-words-count-in-po-file).
