### ISSUE TITLE
Only touchscreen work on Switch release

### ISSUE THREAD

**Issue by ld892012** [ihhub/fheroes2#6589]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Nintendo Switch

### Describe the bug

Hello,
Maybe i did something wrong but controls not work for me, only the touchscreen work.

### Save file

I just play a fresh install.

### Additional info

I play in handled mode with retail french Heroes 2 version.

**Comment by oleg-derevenetz** [comment]
Hi @ld892012 did you tried the latest snapshot from [here](https://github.com/ihhub/fheroes2/releases/tag/fheroes2-switch-sdl2_dev)?

**Comment by ld892012** [comment]
Now it's done, sorry i realize i download the switch version from "Nintendo Switch" part instead of "Snapshots (latest builds)", controls works in the snapshot build, sorry for my mistake.
