### ISSUE TITLE
Inability to cast any spell when hero has 0 movepoints

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#659]
Hero cannot cast any spell while he has no movepoints.
![tired](https://user-images.githubusercontent.com/55348946/83132632-5958ba80-a0ea-11ea-878b-b64c0a1aea3a.jpg)

**Comment by Branikolog** [comment]
Such spells as "Visions", "View Resources" etc can be cast if hero has no movepoints.
"Tired" hero shouldn't be able to cast all teleport spells.

**Comment by ihhub** [comment]
Is it valid for the original game?

**Comment by Branikolog** [comment]
Yes. 
Why can't you cast these spells with no movepoints?
