### ISSUE TITLE
Игра не работает на Маке

### ISSUE THREAD

**Issue by Murlakotamus** [ihhub/fheroes2#6597]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

macOS

### Describe the bug

Как не запускалось на Маке, так и не запускается.

### Save file

Не запускается.

### Additional info

Вывод консоли при запуске:

> xxx@MacBook-Pro-xxx fheroes2_macos10_15_sdl2_x86-64 % ./fheroes2 
> dyld: Library not loaded: /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib
>  Referenced from: /Users/xxx/Downloads/fheroes2_macos10_15_sdl2_x86-64/./fheroes2
>  Reason: image not found
> zsh: abort      ./fheroes2

Содержимое каталога:

> -rw-r--r--@  1 staff    18092  8 фев 15:38 LICENSE
> -rw-r--r--@  1 staff     2317  8 фев 15:44 README.txt
> -rw-r--r--@  1 staff   105655  8 фев 15:38 changelog.txt
> drwxr-xr-x   6 staff      192  6 ноя  2021 data
> drwxr-xr-x  14 staff      448  8 фев 23:35 demo
> -rw-r--r--@  1 staff     3628  8 фев 15:44 download_demo_version.sh
> -rw-r--r--@  1 staff     5568  8 фев 15:44 extract_homm2_resources.sh
> -rwxr-xr-x@  1 staff  4224912  8 фев 15:44 fheroes2
> drwxr-xr-x@  4 staff      128  8 фев 23:30 files
> drwxr-xr-x   3 staff       96  6 ноя  2021 maps
> drwxr-xr-x@  3 staff       96  8 фев 23:30 script

**Comment by oleg-derevenetz** [comment]
Игра требует установки определенных библиотек, об этом написано в [инструкции по установке](https://ihhub.github.io/fheroes2/INSTALL.html#macos-zip-archive):

> After downloading the ZIP archive, extract it to a suitable directory of your choice and then run the script `install_sdl_2.sh` from the `script/macos` subdirectory. This will install the SDL libraries required to run the game.

Этот скрипт использует [Homebrew](https://brew.sh/) для установки библиотек. Если у вас установлен Homebrew, то можно просто [установить fheroes2 из него](https://ihhub.github.io/fheroes2/INSTALL.html#homebrew-mac).

**Comment by oleg-derevenetz** [comment]
Closing this due to lack of feedback.
