### ISSUE TITLE
View World screen, zoom level of the View World screen is not memorized

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#6619]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the zoom level of the View World screen is not memorized unlike in the original game.

In original game:

https://user-images.githubusercontent.com/43583994/218465811-9786658d-c718-4aeb-bc77-52d8d5e16c9a.mp4

In fheroes2:

https://user-images.githubusercontent.com/43583994/218465897-797af0e5-c3e4-458a-8f69-0052cff95b7c.mp4

### Save file

Not needed.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , should it be memorized on the level of the game or per scenario?

**Comment by Districh-ru** [comment]
Hi @ihhub, as I checked in the original game it is memorized until you restart the game engine.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub and @Districh-ru,

> Hi @LeHerosInconnu , should it be memorized on the level of the game or per scenario?

> Hi @ihhub, as I checked in the original game it is memorized until you restart the game engine.

The way it works in the original game seems to me to be a good way to operate, if it is not a more complicated solution to implement. :)

**Comment by Districh-ru** [comment]
Hello @LeHerosInconnu, it is not complicated to implement and is implemented in #6640 :)
