### ISSUE TITLE
"Dimension Door" spell causes enemy hero disappear when using it too close

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#662]
While appearing after "Dimension Door" spell used, enemy hero disappears for a while. Only if the spell teleports hero close to enemy hero:
![door](https://user-images.githubusercontent.com/55348946/83145093-f58bbd00-a0fc-11ea-8cff-e9f82ae823f9.jpg)
![door2](https://user-images.githubusercontent.com/55348946/83145100-f7558080-a0fc-11ea-9c7e-9fa6d7ea6c3d.jpg)
![door23](https://user-images.githubusercontent.com/55348946/83145106-f9b7da80-a0fc-11ea-8f77-915a105ea7b9.jpg)
I believe that this issue is related to #220.

**Comment by ihhub** [comment]
Must be fixed in #667
