### ISSUE TITLE
Main menu, hot keys image lack shadow

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#6630]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

A shadow could be added under the buttons image to make the design of the icon more consistent with other GUI elements.
![keys](https://user-images.githubusercontent.com/55348946/218678977-7988a30b-a624-4b71-b1d6-efdcae526b3e.png)

### Save file

None.

**Comment by ihhub** [comment]
I assigned this issue for myself but in reality it is handled by @golden-lining
