### ISSUE TITLE
Adventure map, Lighthouse which was already flagged by current player lacks any message on visiting

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#6635]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

There's only one message you can read and it is shown only the time you flag a lighthouse.
![Light](https://user-images.githubusercontent.com/55348946/218777265-a1393550-e2a8-4759-8c85-650f9611702c.png)
By the time you step on the same lighthouse one more time nothing happens.

### Describe the possible solution

I propose to show a window with some text to be consistent to all other objects on adventure map.
I think, a short message could help player realizing, that visiting of such objects doesn't bring anything new. Something like that: "You're entering the lighthouse again. After a quick inspection you realize that everything works well and the lighthouse still allows your ships move further each day."

**Comment by oleg-derevenetz** [comment]
Lighthouse is no different in this regard from mines, sawmills and alchemist's labs: there is no any notification if you step on these tiles and object is already flagged by you.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Could be. Probably, I was confused by a recently fixed sound issue, when on revisiting captured Lighthouse there was a music interruption. (which I interpreted as missing dialog window)
The only difference I can mention here is that mines provide player with certain resources which is written in info window. While player can simply forget about the purpose of lighthouse and there's no way to check again, what is this object for. Mines are more intuitive in this point. :)

**Comment by Branikolog** [comment]
Hi, @zenseii !

>Now that this PR https://github.com/ihhub/fheroes2/pull/6590 is merged, a player can simply right click the lighthouse icon in the kingdom overview. This should be enough, no?

I believe not many players notice that small icon and even less right click on it. :)

>The benefit of not having any dialog pop up from mines and lighthouses (more rare), is that when you plan a route over them, you won't be interrupted by a dialog you have to exit. It's a small convenience, especially since a mine and a lighthouse that already belongs to you won't give you any changes, unlike for example the faerie ring which will also grant you more luck.

Making a route over map objects could happen on any map object, no matter capturable it is or not. All other objects perform dialogs on unlimited number of visits.

Anyway, my proposal is debatable and I cannot say that is a mandatory one. Just to make the game more pleasant and friendly to new users. You know, we've added a new info window for magellan's map object, while in the original game you could spend all your money in the same object. :) The story here is not about abusing kingdom treasury, though, but to remind a player, what is this rare object for. Especially, if he accidentally skipped first message. :)

**Comment by oleg-derevenetz** [comment]
@Branikolog

> Probably, I was confused by a recently fixed sound issue, when on revisiting captured Lighthouse there was a music interruption. (which I interpreted as missing dialog window)

Almost so :) Lighthouse musical effect started to play regardless of whether the lighthouse was already captured or not. If it was already captured, then no dialog window was shown, so that musical effect practically did not even have time to start playing before replacing it with the usual background music, but nevertheless it caused a noticeable break in playback due to fade-in at the beginning of a new soundtrack.

**Comment by ihhub** [comment]
Closing this issue as the proposed change is debatable.
