### ISSUE TITLE
Support for .ogg CD audio tracks.

### ISSUE THREAD

**Issue by Barr-find** [ihhub/fheroes2#6648]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

In "Ubisofts Heroes I-IV Complete" ubisoft is using .ogg files to emulate CD Audio for their version of "Heroes 2 Gold". Those files just reside in "CD" Directory after game instalation. It would be nice to use those audio tracks in FHeroes2. I'm not the fan of MIDI music.
![Heroes2_OGG_Files](https://user-images.githubusercontent.com/10328382/219018371-526de9e2-8ce2-4730-84d2-7a6c0a9590f2.png)

### Describe the possible solution

Investigate tracks layout (imo it's same like on Heroes2 Gold CD) and add option to playback those .ogg files instead of standard .mid files.

### Additional info

On same DVD release there is Heroes 2 Gold .iso file with all of the CD Audio tracks but FHeroes2 can't read them. Even if I mount this .iso into virtual drive FHeroes still play only .mid music. BTW Media Player is able to play those audio tracks without problem so??? Will You add CD Audio support to FHeroes2? Please!

**Comment by undef21** [comment]
Hello @Barr-find. fheroes2 already supports ogg, flac and mp3 music. If you rename tracks to "Track02.ogg" and put them into "music" folder, you'll get CD music.

**Comment by Barr-find** [comment]
Ohh so less work for them. Their scripts just should detect .ogg files from "Ubisofts Heroes I-IV Complete" DVD edition and rename them / paste them in proppre folder.

**Comment by oleg-derevenetz** [comment]
@Barr-find since you (apparently) have all these assets, you are welcome to implement this and offer a PR.

**Comment by undef21** [comment]
@Barr-find
Is your "Heroes 2 Gold.iso" image of DOS version? That version used multitrack CD.  In that case user needs to install additional software: a good CD emulator and a CDAudio ripper. Modern releases  of HoMM 2 usually have ripped tracks.

**Comment by ihhub** [comment]
I'm closing this issue as the author of the topic vanished and doesn't respond.

**Comment by Barr-find** [comment]
BTW, read with understanding. In the 1st post I've written that it's "Heroes I-IV Complete" Ubisoft's DVD version. On that DVD there is "Heroes 2 Gold" data track in ".iso" format and Audio tracks in ".ogg".
As suggested by undef21 I've used My brain and put those tracks in the right place and it works.

**Comment by Barr-find** [comment]
> undef21

This suggestion solved the issue! TY one more.

**Comment by Barr-find** [comment]
> Hello @Barr-find. fheroes2 already supports ogg, flac and mp3 music. If you rename tracks to "Track02.ogg" and put them into "music" folder, you'll get CD music.

This suggestion solved the issue! TY once more.
