### ISSUE TITLE
Adventure map, no music should be played while attending an empty object or an object bringing no effect

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#6649]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Currently, the same sound is playing while interacting following objects no matter do they bring some effect or no.

### Describe the possible solution

To operate consistently I believe the engine shouldn't play sound while attending empty dwellings or structures, that don't bring any effect due to some circumstances. 
Here's the list of objects, that shouldn't play sound when visiting:
Dragon City (being empty)
City of the Dead (being empty)
Attending Xanadu with a level being lower, than required by game logic or attending it for the second time.
Attending Magic Well with full mana.
Troll bridge (being empty)
Artesian spring (visiting after someone has already been there)
Wagon camp (being empty)
Tree of knowledge (visiting for the second time)
Fort (visiting for the second time)
Gazebo (visiting for the second time)
Mercenary camp (visiting for the second time)
Standing stones (visiting for the second time)
Witch Doctor's hut (visiting for the second time)
Tree City (being empty)
Tree house (being empty)
Desert Tent (being empty)
Magellan's map (visiting for the second time, since in fheroes2 you cannot buy map more than 1 time per gameplay)

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

Why not play a "sad sound" when this is the case?

Related discussions: https://github.com/ihhub/fheroes2/discussions/4642, https://github.com/ihhub/fheroes2/discussions/4641.

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu 

> Why not play a "sad sound" when this is the case?
> 
> Related discussions: #4642, #4641.

Since, we don't have any, for now I suggest to implement OG behaviour. No music in such circumstances is much more noticeable, than other, "sad" compositions, that player should distinguish.
