### ISSUE TITLE
Adventure map, wrong ambient sound for lava objects

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#6650]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Currently two lava objects have wrong sounds.
![Volcano 2](https://user-images.githubusercontent.com/55348946/219032792-0fe9aeea-59e2-4bb6-9767-45ed25b5fb3e.png)
![Volcano 1](https://user-images.githubusercontent.com/55348946/219032796-3d34e727-b57b-46d3-adb9-4550bc3e16f6.png)
05. wav composition should be played while hero standing near these two objects.

### Save file

[Lava.zip](https://github.com/ihhub/fheroes2/files/10743138/Lava.zip)

**Comment by oleg-derevenetz** [comment]
This issue will NOT be addressed by #6641, because there are some uncertainties with different sounds for different volcano objects.
