### ISSUE TITLE
Puzzle map window is not centered on the screen

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#6657]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Puzzle map is not vertically and horizontally centered
![image](https://user-images.githubusercontent.com/55348946/219302064-a8ab79c3-09f5-41ba-bc31-6d94c71d50bd.png)

### Save file

None.

**Comment by Branikolog** [comment]
Hi, @ihhub !
How could this issue happen in the OG game, since it doesn't support high resolutions?
![Puzzle2](https://user-images.githubusercontent.com/55348946/219323348-256b6ebf-42c3-4caf-8bc5-5a245144c8e1.png)

**Comment by ihhub** [comment]
Ah, I thought you refer to the puzzle image itself.
