### ISSUE TITLE
AI stays put with very strong champion hero in castle instead of attacking

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#6659]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

The AI knows how to buy boats but for some reason it chooses to stay put instead of buying a boat in a nearby town. In addition it turns out the AI always could use dimension door across to a nearby island and could easily take the castles there.

The problem is seen in this stream in which the player steals all of red player's boats with summon boat. The fact that the a player can steal the opponents' boats is a bug that we have tracked https://github.com/ihhub/fheroes2/issues/4109.
However the south-eastern town on that island comes prebuilt with a shipyard so the AI should still have built a new boat, but for some reason it doesn't. EDIT: As pointed out in the discussion below this might be due to resources.

https://www.youtube.com/live/8kcMqaz2C6E?feature=share&t=1467

### Save file

We would have to ask the streamer for a save file.

**Comment by oleg-derevenetz** [comment]
AI will buy a boat only if it has extra resources (boat price x2 - x4 depending on situation), and if it has enough resources to develop a castle, then it will develop it instead.
