### ISSUE TITLE
Adventure map, pathfinding routing through forest

### ISSUE THREAD

**Issue by kfishster** [ihhub/fheroes2#6667]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

macOS

### Describe the bug

When pointing hero to walk to castle, which should require the hero to go around a forest, the path shows that he can go straight though it, which looks like a bug.

![image](https://user-images.githubusercontent.com/4021245/219849257-26f69af5-72b3-4be2-a517-a55bfcc08c61.png)

Hero "Heylon" is facing this issue in the save file.

I'm running the latest version from master. Happy to provide more logs if needed!

### Save file

[Good_9_0014.savc.zip](https://github.com/ihhub/fheroes2/files/10773674/Good_9_0014.savc.zip)

**Comment by kfishster** [comment]
Seems like AI is utilizing this path as well: 

![image](https://user-images.githubusercontent.com/4021245/219849950-aa459838-b1c2-4a9b-9d1a-0892fed082d8.png)

**Comment by oleg-derevenetz** [comment]
This is not a bug:

![path](https://user-images.githubusercontent.com/32623900/219850333-3af0f74d-8340-4ac3-9daa-b3202a9df78a.jpg)

**Comment by kfishster** [comment]
Fascinating. Thanks for checking, seems like a shortcut that shouldn't exist!
