### ISSUE TITLE
Rework button shadow generation code

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#6670]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

We now generate buttons and these can be longer or shorter than the original ones. The problem is that shadows for buttons are often embedded in the background and not generated according to the size of the button.

The prime example is this below. Look at the shadow on the lower right part of the button that is missing:
![image](https://user-images.githubusercontent.com/12501091/219873030-26357b43-bc5d-45be-b9a2-80c1420f5198.png)

We have code for generating buttons with shadows, but iirc this code assumes that there isn't already a shadow present, which in many cases throughout the assets is the case:
https://github.com/ihhub/fheroes2/blob/aeb57f0b546caffa171423475cd408b88c51d522/src/fheroes2/gui/ui_button.cpp#L454-L479

### Describe the possible solution

We need to solve two things:
1. How to add a shadow when there is already a partial shadow present. Clean the background or use a standard background for all dialogs?
2. Where to put the code for the buttons that need shadows.
3. Optional: Should we generate shadows for buttons that are on uniform backgrounds like this?:
![image](https://user-images.githubusercontent.com/12501091/219873276-22856cd0-8208-4843-8694-52c7d30649bd.png)

### Additional info

This issue is necessary to solve before we can continue with adding new buttons as pointed out by @Branikolog here https://github.com/ihhub/fheroes2/issues/6391#issuecomment-1367933390

**Comment by Districh-ru** [comment]
Hi, @zenseii.
I'll try to fix this issue soon, but first we need to answer the first question (about `StandardWindow`).
   If yes then we only have to prepare the proper code for shadows.
   If no then if we generate buttons bigger than original (like `MIN` in Recruit dialog) we can simply add shadow only for enlarged part. This also can be a temporary solution if we plan to use  `StandardWindow` in future and should be done in dialog code as it is unique for this dialog.
If we want to clear the existing shadow then this should be also done in dialog code as it will be unique for each dialog IMHO.

And if we look closer to the generated button:
![изображение](https://user-images.githubusercontent.com/113276641/219881701-a1a46f3e-62e5-42b7-b891-adc262bb3d3a.png)
1. We have extra darkened pixels to the right of the button (more visible when button is pressed).
2. This button is very close to yellow arrows - the shadow from this button will overlap these arrows?.. If not - how to draw it properly under the arrows taking into account that arrows and their shadows are the part of original dialog.
3. Should the button automatically change its width to correspond the width of the word?

Assuming this - we have to think about migrating to `StandardWindow`. :)

**Comment by Districh-ru** [comment]
Hi, @zenseii!
Sorry for long delay with this issue.
Lets set what we will do:

1. Make a function that only generates a shadow for the button (something rectangular). It will be something like the last part of StandardWindow code. :)

2. Or remake a function to generate custom button with/without shadow. This function will make a button using DrawLine, DrawRect and have a code for shadow. So we will be able to make a button with random size without using the game resources. And we will need to use something like Restorer to restore background when replacing the pressed button with unpressed one.

**Comment by Districh-ru** [comment]
> Anyways the shadow generation code will probably be the same no matter what structure we go for in the end. Unless @ihhub has any objections I think we can just start and publish a PR when ready.

OK, I'll try to make such function. I think it will be called from the dialog rendering function, not from button generation function.
The only I can't decide is where to put it. :)))
"agg_image.cpp" is for AGG images, not for self made.
"ui_button.cpp" is only for the ButtonBase class.
Maybe "image.cpp"...??

**Comment by Districh-ru** [comment]
Adding shadow to the button sprite will not work as the shadow (application of transform channel) will be done on every button press making the shadow darker every time. We have to add shadow to the background once and to make a special shadow generation function for buttons.
Also making a shadow using existing `fheroes2::makeShadow" makes a rectangular shadow and it don't take into account that button corners are rounded...
I believe I'll have time to deal with this task in near future :)

**Comment by ihhub** [comment]
Hi @Districh-ru , I tentatively assigned you for this issue as you worked with similar issues in the past.

**Comment by Districh-ru** [comment]
Hi @ihhub, sure. :)
I'll try to deal with it at the weekend.

**Comment by Districh-ru** [comment]
Sorry for the long delay, the work is in process (the shadows for the buttons and arrows are generated by the engine):
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/f57c6b09-a579-4dfe-b298-ff8709c8abe3)
I'm polishing the shadow generation code. After that I plan to make a PR with recreation of recruit dialog using this code.
