### ISSUE TITLE
Combat screen, animation of the projectiles compared to the original game

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#6687]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, there is a difference in the animation of the projectiles compared to the original game.

In the original game, the projectile animation stops before the hexagon where the target is located.
In fheroes2, the animation of the projectile is displayed in the hexagon where the target is located.
This looks strange in fheroes2 because it is possible to see the projectile entirely over the sprite of the targeted creature.

In original game:

![Shotcut_00_00_31_600](https://user-images.githubusercontent.com/43583994/220382755-55f2d81f-1d62-40ee-822b-a5e5f6aa6195.png)

https://user-images.githubusercontent.com/43583994/220382964-60e7a42e-64a0-4b07-bff7-1c65bc8fda99.mp4

In fheroes2:

![Shotcut_00_00_04_080](https://user-images.githubusercontent.com/43583994/220382720-453afb7b-468b-415e-8167-82b17121c8e3.png)

https://user-images.githubusercontent.com/43583994/220383337-de663fa1-b1bd-4faa-87f9-503f43d57384.mp4

### Save file

Here is the save file:
[0_9926a_0001.zip](https://github.com/ihhub/fheroes2/files/10794904/0_9926a_0001.zip)

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu !
I think current implementation looks better, than the original one. But not ideal, though.
On your examples I cannot see the projectile entirely over the sprite of the targeted creature, but can admit, that it could disappear a few pixels before its last rendered position.

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

> Hi, @LeHerosInconnu ! I think current implementation looks better, than the original one. But not ideal, though. On your examples I cannot see the projectile entirely over the sprite of the targeted creature, but can admit, that it could disappear a few pixels before its last rendered position.

I think that if the projectile could enter only a quarter (no more than half at most) inside the last hexagon it would be much better.

**Comment by ihhub** [comment]
I'm tentatively assigning this issue to @Districh-ru as he is the most knowledgeable person in this area at the moment.
