### ISSUE TITLE
Iron & Steel Golem animation issues

### ISSUE THREAD

**Issue by oleg-derevenetz** [ihhub/fheroes2#6689]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

https://user-images.githubusercontent.com/32623900/220469527-f52c9d2b-1339-4b14-9963-5b01abf1aed8.mp4

Looks like they missing some frames. This is reproducible with the following settings:

![settings](https://user-images.githubusercontent.com/32623900/220470090-40f2d3ad-b680-4ca0-b159-64e81b205574.jpg)

### Save file

No save file needed.

**Comment by oleg-derevenetz** [comment]
The same issue in slow-mo (battle speed 1):

https://user-images.githubusercontent.com/32623900/220472623-118a8346-a2e4-47bb-8861-ac4a1d800f32.mp4

**Comment by Districh-ru** [comment]
Hi @oleg-derevenetz , does this issue take place only on Linux OS and what game data did you use?
This lost frames should be made from original golem ICN. The engine checks the size of ICN and if it is not equal to 40 (size of original ICN) then the generation of these frames is skipped.

**Comment by oleg-derevenetz** [comment]
Hi @Districh-ru This is reproducible on my Ubuntu with demo version assets, I was unable to reproduce this on Windows so far.

> The engine checks the size of ICN and if it is not equal to 40 (size of original ICN) then the generation of these frames is skipped.

I checked this and size of ICN is 40, so these frames should be generated.

**Comment by Districh-ru** [comment]
I installed Ubuntu on Oracle VM and got the same effect on demo and full version assets.
And it seems that `_icnVsSprite[id].insert( _icnVsSprite[id].end(), firstFrameToCopy, firstFrameToCopy + copyFramesNum );` does not copy the original frames, but makes default (empty) `fheroes2::Sprite`.

```
districh@districh-VirtualBox:~/Рабочий стол/git$ ./fheroes2
fheroes2 engine, version: 1.0.1
22.02.2023 22:28:14: [VERBOSE]	LoadModifiedICN:  orig ICN size: 40
22.02.2023 22:28:14: [VERBOSE]	LoadModifiedICN:  orig frame #0, width: 37, height: 84
22.02.2023 22:28:14: [VERBOSE]	LoadModifiedICN:  modded frame #0, width: 0, height: 0
22.02.2023 22:28:14: [VERBOSE]	LoadModifiedICN:  orig frame #1, width: 40, height: 83
22.02.2023 22:28:14: [VERBOSE]	LoadModifiedICN:  modded frame #1, width: 0, height: 0
22.02.2023 22:28:14: [VERBOSE]	LoadModifiedICN:  orig frame #2, width: 37, height: 83
22.02.2023 22:28:14: [VERBOSE]	LoadModifiedICN:  modded frame #2, width: 0, height: 0
22.02.2023 22:28:14: [VERBOSE]	LoadModifiedICN:  orig frame #3, width: 35, height: 84
22.02.2023 22:28:14: [VERBOSE]	LoadModifiedICN:  modded frame #3, width: 0, height: 0
22.02.2023 22:28:14: [VERBOSE]	LoadModifiedICN:  orig frame #4, width: 41, height: 83
22.02.2023 22:28:14: [VERBOSE]	LoadModifiedICN:  modded frame #4, width: 0, height: 0
22.02.2023 22:28:14: [VERBOSE]	LoadModifiedICN:  orig frame #5, width: 35, height: 83
22.02.2023 22:28:14: [VERBOSE]	LoadModifiedICN:  modded frame #5, width: 0, height: 0
22.02.2023 22:28:14: [VERBOSE]	LoadModifiedICN:  new ICN size: 46
```

I'll open a PR soon.

**Comment by oleg-derevenetz** [comment]
> And it seems that `_icnVsSprite[id].insert( _icnVsSprite[id].end(), firstFrameToCopy, firstFrameToCopy + copyFramesNum );` does not copy the original frames, but makes default (empty) `fheroes2::Sprite`.

That's because you can't use iterators to the vector as arguments to `insert()` while inserting new elements to the same vector, because these iterators could be invalidated due to reallocation if there is not enough space for new elements in earlier allocated memory chunk. You should either call `reserve()` beforehand to not cause reallocation, or use another temporary vector.

**Comment by Districh-ru** [comment]
> That's because you can't use iterators to the vector as arguments to `insert()` while inserting new elements to the same vector, because these iterators could be invalidated due to reallocation if there is not enough space for new elements in earlier allocated memory chunk. You should either call `reserve()` beforehand to ensure that you do not cause a reallocation during insertion, or use another temporary vector. Dereferencing an invalid iterator is undefined behavior.

Thanks for the explanation, I didn't took into account this behavior.
I'll do a `reserve()` before declaring the iterators.

**Comment by oleg-derevenetz** [comment]
> I'll do a `reserve()` before declaring the iterators.

It would be good to check other parts of the corresponding PR for similar potential issues.

**Comment by Districh-ru** [comment]
> > I'll do a `reserve()` before declaring the iterators.
> 
> It would be good to check other parts of the corresponding PR for similar potential issues.

In the other part of that PR (in `bin_info.cpp`) `insert()` is used two times:
```cpp
            animationFrames[MOVE_TILE_START].resize( animationFrames[MOVE_TILE_START].size() + animationFrames[MOVE_MAIN].size() - 1 );
            animationFrames[MOVE_START].insert( animationFrames[MOVE_START].end(), animationFrames[MOVE_MAIN].begin(), animationFrames[MOVE_MAIN].end() - 1 );
            animationFrames[MOVE_MAIN].erase( animationFrames[MOVE_MAIN].begin(), animationFrames[MOVE_MAIN].end() - 1 );
            // Do the same for 'x' offset vector and make a copy to 'MOVE_TILE_START'.
            frameXOffset[MOVE_START].insert( frameXOffset[MOVE_START].end(), frameXOffset[MOVE_MAIN].begin(), frameXOffset[MOVE_MAIN].end() - 1 );
            frameXOffset[MOVE_TILE_START] = frameXOffset[MOVE_MAIN];
            frameXOffset[MOVE_TILE_START].pop_back();
            frameXOffset[MOVE_MAIN].erase( frameXOffset[MOVE_MAIN].begin(), frameXOffset[MOVE_MAIN].end() - 1 );
```

And it uses iterators from other vector for insertion.

**Comment by oleg-derevenetz** [comment]
> And it uses iterators from other vector for insertion.

Yes, these ones doesn't look suspicious.
