### ISSUE TITLE
Add month.week.day to windows title

### ISSUE THREAD

**Issue by wincmd64** [ihhub/fheroes2#6697]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Pls, add month.week.day to windows title

### Describe the possible solution

Add month.week.day to windows title

**Comment by Branikolog** [comment]
Hi, @wincmd64 
Could you, please, be more detailed in your proposals, attaching screenshots and the logic you expect for this improvements too?
It's completely unclear, what you're talking about.

**Comment by wincmd64** [comment]
![2023-02-23 15_04_24-fheroes2 engine, version_ 1 0 1](https://user-images.githubusercontent.com/104612222/220914616-305b3d43-531d-4ec3-a459-c7ebbb8c74dd.png)

**Comment by ihhub** [comment]
We won't do this as this information exists within the game.

**Comment by ihhub** [comment]
I am closing this issue as the author disappeared and this definitely out of the scope of the project.
