### ISSUE TITLE
Add scroll map with mouse wheel pressed

### ISSUE THREAD

**Issue by wincmd64** [ihhub/fheroes2#6698]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

add scroll map with mouse wheel pressed

### Describe the possible solution

Pls, add scroll map with mouse wheel pressed

**Comment by Branikolog** [comment]
Hi, @wincmd64 !
Currently map scrolling is available with dragging using left mouse button being pressed.
The left button was chosen, as it's more comfortable and intuitive. Mouse wheel may be missing for some mouse models. Some devices with touch control don't even intend to have scroll wheel (like mobile phones).

**Comment by wincmd64** [comment]
Okay, but not to use the button at all is not right. For example, you can add View World or else.

**Comment by ihhub** [comment]
I am closing this issue as the functionality to move the Adventure Map is present and we should avoid adding logic just for the sake of using extra buttons where it is not needed.
