### ISSUE TITLE
Adventure map buttons are partially visible through kingdom summary window

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#6699]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

![image](https://user-images.githubusercontent.com/55348946/220908369-dedb945e-f793-4fd8-b0d1-1c4e87fc6a84.png)
There's a small gap between "heroes" and "towns" buttons which allows to see adventure map buttons.
The issue appeared somewhere after 17.02.2023

### Save file

None.

**Comment by Districh-ru** [comment]
Hello @Branikolog!
This is a regression after #6605, as now we do not render the background for current window. We can revert this, but the more optimal solution will be to render a background only in that small gap.

**Comment by Branikolog** [comment]
Hello, @Districh-ru !

> Hello @Branikolog! This is a regression after #6605, as now we do not render the background for current window. We can revert this, but the more optimal solution will be to render a background only in that small gap.

I believe, you have a plan how to fix it properly. :)
