### ISSUE TITLE
portable mode

### ISSUE THREAD

**Issue by wincmd64** [ihhub/fheroes2#6708]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

use cfg and saves in game folder, not %appdata%

### Describe the possible solution

use cfg and saves in game folder, not %appdata%

**Comment by oleg-derevenetz** [comment]
You can implement "portable mode" yourself using the BAT file like this:

```
@echo off
set APPDATA=%~dp0
"%APPDATA%\fheroes2.exe"
```

**Comment by ihhub** [comment]
Hi @wincmd64 , does the proposed by @oleg-derevenetz approach solves your problem?

**Comment by wincmd64** [comment]
yes
