### ISSUE TITLE
Can't quit/close game during battle

### ISSUE THREAD

**Issue by mataski** [ihhub/fheroes2#6712]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

If battle window is open there is no way to quit the game, there is no ESC to open any menu, ALT+F4 does not work, alt-tabbing and trying to close from taskbar with right click + close window does nothing.

### Save file

n/a

### Additional info

Only solution is to kill process via Task Manager

**Comment by Branikolog** [comment]
Hi, @mataski !
We already have such issue https://github.com/ihhub/fheroes2/issues/3042
Between, you can finish any battle instantly (default Q). ;)
