### ISSUE TITLE
Cold ring hurts the central creature too

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#6730]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Casting Cold Ring damages the creature in the middle too, which it shouldn't.

I'm pretty sure this used to work as it should before so I'm not sure when the bug was introduced.

### Save file

Just start a battle mode fight and give the hero the cold ring spell.

### Additional info

This was spotted during a stream from today using 1.0.1 public release: https://www.youtube.com/live/uoNoRWF6Ock?feature=share&t=4764
I also tested this building the latest commit.

**Comment by oleg-derevenetz** [comment]
When I wrote a more optimal implementation of `Battle::Board::GetDistanceIndexes()`, I did not reproduce the original behavior exactly - originally the central cell was not included in the results, while in my implementation it is included.
