### ISSUE TITLE
Adventure map, guarded creature dwellings, activation sound for the battle dialog window

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#6735]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Currently, activation sound for Dragon city, City of the dead and Troll bridge plays only when hiring dialog window appears.
![image](https://user-images.githubusercontent.com/55348946/221873543-e44d8833-7402-479d-8dd7-ce33b450d307.png)

When we visit these objects for the first time (or when these objects were previously captured by other players) no sounds are played.
![image](https://user-images.githubusercontent.com/55348946/221873685-c96429ff-85f9-4815-8023-82f504da976f.png)

### Describe the possible solution

I suggest in a case these objects belong to other players or you visit them for the first time, play the current activation sound only on battle dialog window. This behaviour is consistent with other objects, where player should fight to guardians.
![image](https://user-images.githubusercontent.com/55348946/221873712-d53705c8-1812-404c-80de-c4dcc113c27f.png)
After winning the battle there could be no activation sound, since you're in object currently.

**Comment by oleg-derevenetz** [comment]
How about using the different sounds for pre-battle and pre-hire dialogs (and if yes, which ones exactly)?

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz !

> How about using the different sounds for pre-battle and pre-hire dialogs (and if yes, which ones exactly)?

These high level creature dwellings have a special sound in the original game to point, that it's not ordinary object, I believe.  The original sound for these objects is definitely the best one to play before the fight: it's harsh and frightening. For hiring dialog I expect some unique sound too. But we still don't have a sound designer to create that.
So, I believe, the common dwelling sound could also fit for hiring dialog (the one from halfling hole, for instance).
