### ISSUE TITLE
THUNK is stuck in its starting location

### ISSUE THREAD

**Issue by Stiivi** [ihhub/fheroes2#6747]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

macOS

### Describe the bug

In the map THUNK, the THUNK hero gets stuck in its starting location - he does not pass though the Sphere of Negation artefact. 

Might be not necessarily a bug, but it seems likes there is some AI logic is in the play. The current AI logic, that is causing this behaviour, is making the main hero character of the map irrelevant.

<img width="315" alt="image" src="https://user-images.githubusercontent.com/71105/222714311-2e4598b1-52fb-4955-8d3e-ee28b93d0e1f.png">

### Save file

[THUNK_0039.sav.zip](https://github.com/ihhub/fheroes2/files/10881604/THUNK_0039.sav.zip)

**Comment by oleg-derevenetz** [comment]
This artifact has the special requirement for the secondary skill that the THUNK hero lacks (namely Wisdom). It seems that in OG AI just ignores these requirements, while in fheroes2, the AI obeys them.

**Comment by oleg-derevenetz** [comment]
Has no direct relation to this particular issue, but just an example of the AI behavior in the original game:

https://www.youtube.com/watch?v=IY9CRBt6OOY

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> This artifact has the special requirement for the secondary skill that the THUNK hero lacks (namely Wisdom). It seems that in OG AI just ignores these requirements, while in fheroes2, the AI obeys them. The game logic is in fact fine here, so I removing the "logic" badge.

I'm not sure about this behavior in Heroes 2.
I remember cases where in order to capture an artifact one of the conditions "to have Wisdom" or "to have Leadership" was necessary and the AI didn't capture it although it was in its territory and in a game already well advanced in time.

In fheroes2, the AI respects the conditions properly, but does nothing to meet the conditions and capture the artifact afterwards: https://github.com/ihhub/fheroes2/issues/6088.

**Comment by oleg-derevenetz** [comment]
> I'm not sure about this behavior in Heroes 2.

At least, the author of this map definitely counted on the fact that THUNK will always be able to take this artifact, while according to the game logic it is not necessary the case.

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> > I'm not sure about this behavior in Heroes 2.
> 
> At least, the author of this map definitely counted on the fact that THUNK will always be able to take this artifact, while according to the game logic it is not necessary the case.

To remedy this, I think that in the scenario editor of fheroes2, the creator of the scenario could have access to the artifact settings on this subject.
To wit:
Have Leadersship.
Have Wisdom.
Pay resources.
Fight creatures.

It could also be foreseen that an artifact that blocks the movement in an open passage (as in the exposed case) is automatically forbidden to have one of these conditions, in the case of a randomly generated map.

**Comment by oleg-derevenetz** [comment]
JFYI: a similar situation can be observed in the original game under similar circumstances:

https://user-images.githubusercontent.com/32623900/222984108-456487cf-2757-4259-96cd-3f6715f45356.mp4

I edited this map a bit to check the artifact and have a vision on that tile, and if this artifact requires Wisdom, THUNK just stuck on nearby tile.

Thus, this is in no sense a bug, but simply a miscalculation of the map's author. Reclassifying this as a request for improvement.

**Comment by ihhub** [comment]
I am closing this issue as this is the original game behavior but we are going to fix in the our Editor.
