### ISSUE TITLE
Avoid extra frame rendering on dialog events leading to its closure

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#6759]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

For many dialogs where we handle events for buttons we actually render one extra frame before closing the dialog. This is not much of a problem but just useless to do and we waste resources. For example,
```cpp
SelectedWindow showConfigurationWindow()
{
...
        while ( le.HandleEvents() ) {
            // <---- here we update the state of the button
            if ( le.MousePressLeft( okayButton.area() ) ) {
                okayButton.drawOnPress();
            }
            else {
                okayButton.drawOnRelease();
            }

            // <---- here we exit the window
            if ( le.MouseClickLeft( okayButton.area() ) || Game::HotKeyCloseWindow() ) {
                break;
            }
...
```
we actually update the state of the button first and rendering extra frame and only then close the window. If you do this on a very slow machine you would notice that the button "jumps" form pressed to released state just before closing the window.

### Save file

No need.

### Additional info

The solution is to check events before rendering UI elements.

**Comment by oleg-derevenetz** [comment]
> If you do this on a very slow machine you would notice that the button "jumps" form pressed to released state just before closing the window.

Why is this a bug? :) Clicked button should be released first and then the action should be performed, i.e. the window should be closed.

**Comment by ihhub** [comment]
Haha, I actually realized this as well. Closing it then.
