### ISSUE TITLE
Application crash (the latest snapshot from 08.03.2023)

### ISSUE THREAD

**Issue by Killbrum** [ihhub/fheroes2#6781]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

The application crashed with an assert popup when a computer (yellow) AI made a turn. The snapshot was taken on 08.03.2023 (morning). 
The snapshot corresponds to the commit 80880f5185238e89e3ea7467eb15fb3e39496565 (Update translation files)
![Screenshot_21](https://user-images.githubusercontent.com/7841390/223699446-f87e0243-4aeb-46cf-8650-c21fe93dded7.png)

### Save file

[AUTOSAVE.zip](https://github.com/ihhub/fheroes2/files/10920042/AUTOSAVE.zip)

**Comment by oleg-derevenetz** [comment]
Looks like a regression after #6745.

**Comment by ihhub** [comment]
Hi @idshibanov , can you please check this issue ASAP?

**Comment by idshibanov** [comment]
> Hi @idshibanov , can you please check this issue ASAP?

Assert assumption was wrong, the defend task could be cleared by another hero. Will push a fix shortly.

**Comment by ihhub** [comment]
> > Hi @idshibanov , can you please check this issue ASAP?
> 
> Assert assumption was wrong, the defend task could be cleared by another hero. Will push a fix shortly.

Thank you very much!

**Comment by Killbrum** [comment]
I wish to have another PC where I will be able to install MSVS and support you guys. Thank you so much for your outstanding work
