### ISSUE TITLE
Adventure map, the number of resources subtracted in the event messages should be adjusted

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#6795]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In the original game, when an amount of resources is taken away from the player in an event, global or local, the amount of resources taken away from the player is adjusted to the player's actual treasury in the message displayed.
This is not the case in fheroes2.
In fheroes2, it is always the quantity indicated in the scenario editor which is displayed, without taking into account the treasury of the player.
This should be corrected.

In original game:

![Gold event true value 001](https://user-images.githubusercontent.com/43583994/224051770-ac0a8714-0fd6-4811-a085-974db87592fe.png)

![Gold event true value 003](https://user-images.githubusercontent.com/43583994/224051777-1cfc8115-3181-40a6-8fac-c18ad128ed72.png)
![Gold event true value 004](https://user-images.githubusercontent.com/43583994/224051794-052a35be-00ff-449e-a9f6-a32578aa847a.png)

![Gold event true value 006](https://user-images.githubusercontent.com/43583994/224051811-4cbc6662-43ae-4a56-95da-05afc1bb5df9.png)
![Gold event true value 007](https://user-images.githubusercontent.com/43583994/224051825-10dd1d38-85c9-4c1a-b60c-0244fd3fe949.png)

![Gold event true value 008](https://user-images.githubusercontent.com/43583994/224051836-41b3f5d2-18ca-41dd-82ed-4b4969c11d58.png)
![Gold event true value 009](https://user-images.githubusercontent.com/43583994/224051850-f5e15f86-4612-444f-a16b-076457519a19.png)

In fheroes2:

![Gold event true value 002](https://user-images.githubusercontent.com/43583994/224052070-1469a8f2-e671-4b47-b33c-fa29ea013b98.png)

In original game:

![Event true value 001](https://user-images.githubusercontent.com/43583994/224052315-b4cdc02c-a758-4949-ad2e-1bede4f61d0a.png)

![Event true value 002](https://user-images.githubusercontent.com/43583994/224052327-38bea483-847e-4af3-b848-40ab53ed4351.png)

In fheroes2:

![Event true value 003](https://user-images.githubusercontent.com/43583994/224052341-9d0a5b7d-8bf2-484f-9196-d761566b0c78.png)

### Save file

Here is the test scenario file (for map event):
[0 9925f.zip](https://github.com/ihhub/fheroes2/files/10932461/0.9925f.zip)

**Comment by undef21** [comment]
@LeHerosInconnu, what is OG behavior if a player has 0 resources? For example, the player has 0 wood and 0 gold for your last screenshot.

**Comment by LeHerosInconnu** [comment]
Hello @undef21,

> @LeHerosInconnu, what is OG behavior if a player has 0 resources? For example, the player has 0 wood and 0 gold for your last screenshot.

Since the player has nothing, no withdrawal is displayed.

In original game:

![Event no resources 001](https://user-images.githubusercontent.com/43583994/224170834-1b5e6a5f-4c40-4bbd-8011-7e65ac6a0408.png)

![Event no resources 002](https://user-images.githubusercontent.com/43583994/224170846-618ae6da-d7d3-45f1-96ac-a38871243f34.png)

![Event no resources 003](https://user-images.githubusercontent.com/43583994/224170852-62433914-2ca7-4671-b7b2-826b1f0ec837.png)
