### ISSUE TITLE
Combat, Army Order bar should display a different sprite (brighter sprite) for the mirror troop

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#6798]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

In fheroes2, the Army Order bar should display a different sprite (brighter sprite) for the mirror troop.

In fheroes2:

![Mirror troop Mirror Image spell 01](https://user-images.githubusercontent.com/43583994/224078946-0329b047-aa11-4c98-b8e8-58d33a3bb4c4.png)

### Describe the possible solution

In fheroes2, the Army Order bar should display a different sprite (brighter sprite) for the mirror troop.

### Additional info

Related issue: https://github.com/ihhub/fheroes2/issues/6796.

**Comment by ihhub** [comment]
We should use the same palette applied on mini-monster icons, which is used for mirrored monsters during the battle.
