### ISSUE TITLE
Combat, Necromancy Report window, number of skeletons raised after using the mirror image spell

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#6803]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In the original game, the decimated mirror troops are taken into account for the calculation of the number of skeletons raised by the Necromancy skill, regardless of whether the mirror troops were decimated by attacking them directly or by decimating the original troop targeted by the mirror image spell.
In fheroes2, mirror image troops are only taken into account when they have been decimated by attacking them directly.
The decimated mirror troops should always be taken into account for the number of skeletons raised as in the original game.

After the mirror image spell was cast on all the defender's troops, the initial troops of the hero's army were decimated and the mirror troops disappeared without being attacked:

In original game:
![H2 troop first 01](https://user-images.githubusercontent.com/43583994/224132698-76e97fef-14d3-4337-9848-b0e71f459aa5.png)
![H2 troop first 02](https://user-images.githubusercontent.com/43583994/224132712-f817707a-77bd-4d26-a5a9-136d0ab052ec.png)
Note: Not all troops are displayed in the original game, this is a GUI "bug".
![H2 troop first 03](https://user-images.githubusercontent.com/43583994/224139504-45ac02f2-2604-4075-ac49-d79c6996eda7.png)

In fheroes2:
![Fheroes2 troop first 01](https://user-images.githubusercontent.com/43583994/224132970-b86ff5f2-8d4a-430f-970c-1778fa2036c2.png)
![Fheroes2 troop first 02](https://user-images.githubusercontent.com/43583994/224132985-f2064a11-c2c2-40e2-bc85-8acb131f0de0.png)
![Fheroes2 troop first 03](https://user-images.githubusercontent.com/43583994/224139683-7a28a065-6549-4ee5-9c7b-5bf2b7da4b19.png)

After the mirror image spell has been cast on all the defender's troops, the mirror image troops were decimated first and then the initial troops of the hero's army:

In original game:
![H2 mirror first 01](https://user-images.githubusercontent.com/43583994/224133092-6b179047-acac-47eb-ab4a-3f71f2850209.png)
Note: Not all troops are displayed in the original game, this is a GUI "bug".
![H2 mirror first 02](https://user-images.githubusercontent.com/43583994/224139766-a63ac72e-a804-4fc5-bea6-7d857e52c3fe.png)

In fheroes2:
![Fheroes2 mirror first 01](https://user-images.githubusercontent.com/43583994/224133155-eec54ec0-f3d9-4f71-97ce-fe442cd7790d.png)
![Fheroes2 mirror first 02](https://user-images.githubusercontent.com/43583994/224139868-0908616b-26a9-4c96-99c8-f475e284f78f.png)

### Save file

Here are the save files:
[Test mirror image 01.zip](https://github.com/ihhub/fheroes2/files/10935304/Test.mirror.image.01.zip)

### Additional info

Related issue: https://github.com/ihhub/fheroes2/issues/6801.

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu !
For me it's not logically clear, why do necromancer could rise skeletons out of fragile magic essences, whos corpses disappear after demolishing. :)
I personally wouldn't give such advantages for overpowered necromancy.

**Comment by Branikolog** [comment]
Hello, @zenseii 
Indeed... Vampires' and ghosts' abilities work on these mirrored creatures as well... As if they killed the whole normal stack in a single hit.
It would be a reckless thing to mirror legion of troops in a battle against ghosts. 😅 
I have to admit this behaviour of the spell then. :)

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog and @zenseii,

> Hi, @LeHerosInconnu ! For me it's not logically clear, why do necromancer could rise skeletons out of fragile magic essences, whos corpses disappear after demolishing. :)

And how can these same fragile magic essences do so much damage? :D
And as @zenseii explained, it is also important to be consistent with the functioning of the other creatures in the game.

> I personally wouldn't give such advantages for overpowered necromancy.

There are other ways to handle Necromancy than introducing, in my opinion, unclear functioning for the player.
An example here (alternative calculation for Necromancy): https://github.com/ihhub/fheroes2/discussions/3235.
