### ISSUE TITLE
Combat, Mirror Image spell, A glorious victory window, taking into account the experience points related to the decimated mirror troops

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#6804]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

In the original game, the hit points of decimated mirror troops are not taken into account, regardless of whether the mirror troops were decimated by attacking them directly or by decimating the original troop targeted by the mirror image spell.
In fheroes2, the hit points of decimated mirror troops are only taken into account when they have been decimated by attacking them directly.

In this case, I suggest that the hit points of decimated mirror troops should always be taken into account, a kind of trade-off to the use of the spell for the one using it. :)
As opposed to what happens in the original game.
In original game, decimated mirror troops are taken into account for the skill Necromancy to raise skeletons, why not also for experience points.

After the mirror image spell was cast on all the defender's troops, the initial troops of the hero's army were decimated and the mirror troops disappeared without being attacked:

In original game:
![H2 troop first 01](https://user-images.githubusercontent.com/43583994/224132698-76e97fef-14d3-4337-9848-b0e71f459aa5.png)
![H2 troop first 02](https://user-images.githubusercontent.com/43583994/224132712-f817707a-77bd-4d26-a5a9-136d0ab052ec.png)
Note: Not all troops are displayed in the original game, this is a GUI "bug".

In fheroes2:
![Fheroes2 troop first 01](https://user-images.githubusercontent.com/43583994/224132970-b86ff5f2-8d4a-430f-970c-1778fa2036c2.png)
![Fheroes2 troop first 02](https://user-images.githubusercontent.com/43583994/224132985-f2064a11-c2c2-40e2-bc85-8acb131f0de0.png)

After the mirror image spell has been cast on all the defender's troops, the mirror image troops were decimated first and then the initial troops of the hero's army:

In original game:
![H2 mirror first 01](https://user-images.githubusercontent.com/43583994/224133092-6b179047-acac-47eb-ab4a-3f71f2850209.png)
Note: Not all troops are displayed in the original game, this is a GUI "bug".

In fheroes2:
![Fheroes2 mirror first 01](https://user-images.githubusercontent.com/43583994/224133155-eec54ec0-f3d9-4f71-97ce-fe442cd7790d.png)

### Describe the possible solution

In this case, I suggest that the hit points of decimated mirror troops should always be taken into account, a kind of trade-off to the use of the spell for the one using it. :)
As opposed to what happens in the original game.
In original game, decimated mirror troops are taken into account for the skill Necromancy to raise skeletons, why not also for experience points.

### Additional info

Related issue: https://github.com/ihhub/fheroes2/issues/6801.

**Comment by oleg-derevenetz** [comment]
Should be fixed by #6805.
