### ISSUE TITLE
Adventure map, Haunt spell, update of the minimap (version 1.0.1 6774)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#6808]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the update of the minimap is not done correctly.

In fheroes2:

![vlcsnap-2023-03-10-20h28m59s906](https://user-images.githubusercontent.com/43583994/224412008-f007a2d7-10ac-480a-9227-88884c6dd33b.png)

https://user-images.githubusercontent.com/43583994/224412032-a07106e7-b483-4832-925e-a26ac6cfca48.mp4

Also, I think that the minimap should be updated as soon as the Haunt spell has been cast and not when the hero makes a move.
For example, the hero may not move from the mine and the minimap is then erroneous.

### Save file

Here is the test scenario file:
[0 9930.zip](https://github.com/ihhub/fheroes2/files/10945393/0.9930.zip)

**Comment by Districh-ru** [comment]
Hi @LeHerosInconnu!
This bug is fixed in https://github.com/ihhub/fheroes2/pull/6780. The abandoned and the Haunted mines will not be displayed on mini-map.
If you want and have time, you are welcome to test that PR. :)

**Comment by Districh-ru** [comment]
But currently the "Haunted" mine is not shown on mini-map.
The engine assigns the same object type to Abandoned and Haunted mines.
I'll try to fix this.

**Comment by LeHerosInconnu** [comment]
Hello @Districh-ru,

> Hi @LeHerosInconnu! This bug is fixed in #6780. The abandoned and the Haunted mines will not be displayed on mini-map. If you want and have time, you are welcome to test that PR. :)

> But currently the "Haunted" mine is not shown on mini-map. The engine assigns the same object type to Abandoned and Haunted mines. I'll try to fix this.

I did a quick test, seems to work for the part of the minimap update.

**Comment by Districh-ru** [comment]
Many thanks for testing, @LeHerosInconnu!
The fix for display of Haunted mines on mini-map is done in #6811. The mine color in that PR is black, but after merging both #6780 and #6811 it will be OK :)
