### ISSUE TITLE
Adventure screen, list of castles should not be adjusted when a hero moves

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#6837]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the list of castles should not be adjusted when a hero moves.

In fheroes2:

https://user-images.githubusercontent.com/43583994/225036557-73a1173b-65de-43ed-bd4e-80333bc290bf.mp4

**Edit 2023/03/24.**

There is the same problem with the list of heroes.

In fheroes2:

https://user-images.githubusercontent.com/43583994/227537275-750af327-17fe-4e8d-8407-0de6b22cace3.mp4

I can open another issue for this if necessary.

### Save file

Not needed.
Here is the save file (list of heroes):
[Hero list 01.zip](https://github.com/ihhub/fheroes2/files/11062696/Hero.list.01.zip)

**Comment by autoexecbatman** [comment]
https://github.com/ihhub/fheroes2/blob/master/src/fheroes2/gui/interface_list.h

It seems this issue is happening in the template class ListBox
Line 263 is affecting the hero list scrollbar.
Could not yet find a solution. Maybe someone will find this useful

**Comment by ihhub** [comment]
Hi @autoexecbatman , I think shouldn't even refresh the castle's list in first place so no scrollbars would be updated.

**Comment by autoexecbatman** [comment]
Inside the kingdom overview window .

**Comment by LeHerosInconnu** [comment]
Hello @Kazhuu,

> I could take a stab at this. I tested on original game and the scrollbars doesn't update at all. I guess the point to update the heroes scrollbar is to bring the currently moving hero to the view. The game seems to scroll the currently moving hero to the bottom of the scrollbar view.
> 
> And yes the castle scrollbar shouldn't be updated when hero moves, but what about the hero scrollbar? I think it's nice feature that it automatically scrolls to the hero that is moving. Now it seems to always scroll the hero to the bottom of the view. I guess one improvement would be not to auto scroll if the moving hero is already in the view?

It is better to let the user set the position of the heroes list at his convenience, for whatever reason, and not to "automatically" change the position of the heroes list.
Let's say the user has positioned the hero list to select another hero when the selected one has moved.
The fact that the hero list is "automatically" changed interferes with the user's setting, who has to search for the other hero again.

**Comment by Kazhuu** [comment]
I made a fix for this. Here is also save file to test this out.

[scrollbartes.savh.zip](https://github.com/ihhub/fheroes2/files/11303853/scrollbartes.savh.zip)

**Comment by LeHerosInconnu** [comment]
Hello @Kazhuu,

I did a test for this and here is what I observed.
The hero is no longer selected in the heroes list when using the "Next Hero" button.

In fheroes2:

https://user-images.githubusercontent.com/43583994/235179328-fa71cc9e-63fd-48f5-861a-efdfbe526b04.mp4

**Comment by Kazhuu** [comment]
Hello @LeHerosInconnu I did some changes. Can you try again now?
