### ISSUE TITLE
Magic Book, cost in spell points is not correct in the spell information window when the hero has the artifact that reduces the cost of elemental spells

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#6838]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the cost in spell points is not correct in the spell information window when the hero has the artifact that reduces the cost of elemental spells.
The cost should be adjusted to "15".

In fheroes2:

![Cost summon spell 001](https://user-images.githubusercontent.com/43583994/225057887-6bed0e2f-3399-4da9-8f05-fa1eeef0eec3.png)

![Cost summon spell 002](https://user-images.githubusercontent.com/43583994/225057909-b523ef8f-1fe5-4932-bc5d-a3f97840e5e1.png)

![Cost summon spell 003](https://user-images.githubusercontent.com/43583994/225057925-615baefb-b897-4067-8058-af67d1f60d2f.png)

### Save file

Here is the save file:
[Cost summon elemental 01.zip](https://github.com/ihhub/fheroes2/files/10970672/Cost.summon.elemental.01.zip)

**Comment by autoexecbatman** [comment]
This is due to the value being passed as a raw integer. 
Is anybody working on this already? How can I know if somebody is working on it  ?

**Comment by autoexecbatman** [comment]
![image](https://user-images.githubusercontent.com/91700559/225309025-edc9f587-ee23-4f31-bb67-2b219887d7f5.png)
So I sort of found the source of it 
Now the question is :
this change should be done ? 
The whole spell book can get some finishing touches. 
Also you can click the icon inside and you get a window in a window not sure for what
Also you can right click on tabs to get the description but can't right click the Exit tab .
It is very minor but the quality of the spell book feels unfinished and might impact user impression on this release as a whole

**Comment by autoexecbatman** [comment]
thanks 
How would I submit the change in a good way ?

**Comment by autoexecbatman** [comment]
I am sorry about some beginner question. 
Should I commit my change and the ask a pull to this repository ?

**Comment by thestahan** [comment]
Maybe a helpful tip from me, cause I also started looking at this.

I'm not sure you are looking at the right piece of code - it seems fine to me. That function is responsible for "adjusting" the spell cost for the hero, so if no hero is passed, the default value is returned.

I think the issue might be somewhere here, but I don't know how to access the hero context here.
![image](https://user-images.githubusercontent.com/46906385/225317519-28038580-3a17-43e8-a645-16e0134b4023.png)

**Comment by autoexecbatman** [comment]
![image](https://user-images.githubusercontent.com/91700559/225322325-62db706b-4396-4237-af85-2d7a39377e89.png)
@thestahan you are correct
