### ISSUE TITLE
Enemy hero can flee on sea battle

### ISSUE THREAD

**Issue by AAS** [ihhub/fheroes2#6847]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

When you start sea battle enemy hero has an option to flee.
I think it's a bug.

### Save file

[AUTOSAVE.zip](https://github.com/ihhub/fheroes2/files/10987120/AUTOSAVE.zip)

**Comment by ihhub** [comment]
Hi @AAS , how does it work in the original game?

**Comment by AAS** [comment]
I can't remember it. But fleeing into the water definitely strange mechanic.

**Comment by Mr-Bajs** [comment]
I checked in the original game. I had 1000 Black dragons vs s few peasants and some archers. The computer never flees. So I  assumes that this is a bug.

**Comment by ihhub** [comment]
Hi @Mr-Bajs , never flees doesn't mean can't do this. AI the the OG has a lot of issues. Please check a human player vs human player.

**Comment by Mr-Bajs** [comment]
Of course, that's true.
I checked, the human player can flee during boat combats in the original game

**Comment by ihhub** [comment]
Then it is not a bug. What a human can do AI does as well.
