### ISSUE TITLE
Hero info window frame is missing when checking through hero meeting window

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#6860]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

![image](https://user-images.githubusercontent.com/55348946/226108633-36dbb4c2-6fa2-4959-bcdd-be74ccccc298.png)
Hero info window is missing when we click on a hero portrait in hero meeting window.

### Save file

None.

**Comment by ihhub** [comment]
The proposed fix was introduced in #5923.
