### ISSUE TITLE
Combat, Necromancy, number of skeletons raised is not rounded up correctly

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#6871]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the number of skeletons raised is not rounded up correctly.

In fheroes2:

In the example, for 10% of 21 decimated peasants (2.1), 2 skeletons are raised instead of 3 (standard and instant combat):
![Necromancy standard combat 003](https://user-images.githubusercontent.com/43583994/226373493-2e8ff253-c8d0-4d5a-bdaa-6b612fac10a3.png)
![Necromancy standard combat 004](https://user-images.githubusercontent.com/43583994/226373510-3b4a5445-1b85-44d1-9a8e-1dff10ba09d7.png)
![Necromancy instant combat 001](https://user-images.githubusercontent.com/43583994/226373466-ee139352-0371-41d1-ad45-5051f02bf6db.png)
![Necromancy instant combat 002](https://user-images.githubusercontent.com/43583994/226373479-ea63036d-76de-40f1-859a-b05b86099934.png)

In the example, for 10% of 22 decimated peasants (2.2), 2 skeletons are raised instead of 3 (standard and instant combat):
![Necromancy standard combat 005](https://user-images.githubusercontent.com/43583994/226373804-3da1656d-5a4f-4201-ae79-274f40163dd5.png)
![Necromancy standard combat 006](https://user-images.githubusercontent.com/43583994/226373752-67f6d18b-5ae6-45f2-bffc-155193888fd1.png)
![Necromancy instant combat 003](https://user-images.githubusercontent.com/43583994/226373770-485f38f4-500c-4fde-b539-be8e7fde9479.png)
![Necromancy instant combat 004](https://user-images.githubusercontent.com/43583994/226373786-b3cb6cf1-1578-4d71-829d-bcc1872dc3a4.png)

In the example, for 10% of 23 decimated peasants (2.3) and then up to 30 decimated peasants, 3 skeletons are raised (standard and instant combat), so from there to 30, it is correct:
![Necromancy standard combat 007](https://user-images.githubusercontent.com/43583994/226373969-e8fa8020-3de0-482e-b8af-34355ee29246.png)
![Necromancy standard combat 008](https://user-images.githubusercontent.com/43583994/226373983-bc3494a5-3eef-45eb-a0f6-964e930dc455.png)
![Necromancy instant combat 005](https://user-images.githubusercontent.com/43583994/226373999-8750e47e-a00e-4ceb-89fa-964176a39ae0.png)
![Necromancy instant combat 006](https://user-images.githubusercontent.com/43583994/226373951-5c4fc36e-112f-41e2-96a7-6621219ef811.png)

### Save file

Here is the test scenario file:
[0 9924d.zip](https://github.com/ihhub/fheroes2/files/11019394/0.9924d.zip)

**Comment by Mr-Bajs** [comment]
It it a bug though? I tried the basic necromancy in the original game, and it seams to always to round down, never up. 
21 peasants gave 2 skeletons, 29 gave 2 skeletons, 30 gave 3.

**Comment by oleg-derevenetz** [comment]
@Mr-Bajs yeah, I also remember that number of skeletons is rounded down. This should be additionally checked.

**Comment by LeHerosInconnu** [comment]
Hello @Mr-Bajs and @oleg-derevenetz,

> It it a bug though? I tried the basic necromancy in the original game, and it seams to always to round down, never up. 21 peasants gave 2 skeletons, 29 gave 2 skeletons, 30 gave 3.

> @Mr-Bajs yeah, I also remember that number of skeletons is rounded down. This should be additionally checked.

This is rounded down in the original game.
It was made rounded up in fheroes2, because in the original game the necromancy always gives at least 1 skeleton (10% of 1 peasant (0.1) raises 1 skeleton) while in fheroes2 it was given 0 skeleton (10% of 1 peasant (0.1) raises 0 skeleton).

Related closed issue: https://github.com/ihhub/fheroes2/issues/1496.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> @LeHerosInconnu
> 
> > This is rounded down in the original game.
> > It was made rounded up in fheroes2, because in the original game the necromancy always gives at least 1 skeleton (10% of 1 peasant (0.1) raises 1 skeleton) while in fheroes2 it was given 0 skeleton (10% of 1 peasant (0.1) raises 0 skeleton).
> 
> But that's not the case. In fheroes2 there also will be 1 skeleton even from 1 peasant. Just checked this in the Battle Only mode.

Yes, the problem has been solved and the issue closed. :)

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu

> Yes, the problem has been solved and the issue closed. :)

So currently this logic behave (mostly) just like in the OG, right? The only exception is 3 skeletons from 23 peasants, which is incorrect.

**Comment by oleg-derevenetz** [comment]
@undef21

> in this case raising of 3 skeletons from 23 units is incorrect, right?

Yes, this case seems incorrect.

**Comment by Mr-Bajs** [comment]
> > @Mr-Bajs yeah, I also remember that number of skeletons is rounded down.
> 
> @oleg-derevenetz, in this case raising of 3 skeletons from 23 units is incorrect, right?

Yes incorrect.

OG: 23 peasants gives 2 skeletons
Fheroes2 1.0.2: 23 peasants gives 3 skeletons, which is incorrect. It should give 2 skeletons not 3. So something is wrong.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> @LeHerosInconnu
> 
> > Yes, the problem has been solved and the issue closed. :)
> 
> So currently this logic behave (mostly) just like in the OG, right? The only exception is 3 skeletons from 23 peasants, which is incorrect.

I assumed that it was simpler to round up as this would take all cases into account, without needing a special case to have at least one skeleton raised, but this does not seem to be the case.

It is the same from 23 to 29.
Everything must be 3 skeletons from 21 to 29 creatures decimated (rounded up), or everything must be 2 skeletons from 21 to 29 creatures decimated (rounded down).

**Comment by oleg-derevenetz** [comment]
@undef21

> Is a correct formula just `raiseCount = enemyTroopsKilled * necromancyPercent / 100`?

I'm not sure about the correct formula. Need to make some inquiries.

**Comment by oleg-derevenetz** [comment]
> Is a correct formula just `raiseCount = enemyTroopsKilled * necromancyPercent / 100`?

Yes, it seems so. In HoMM3 the efficiency of Necromancy depends on the health of dead stacks, while in HoMM2 it seems to depend only on the number of killed units (although I haven't found the exact formula anywhere).
