### ISSUE TITLE
Screen doesn't dim under mouse

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#688]
After victory dimming a small piece of battlefield stays bright:
![Dimmed](https://user-images.githubusercontent.com/55348946/83353220-a1314900-a359-11ea-8854-e8ff790dc18f.jpg)
![Dimmed2](https://user-images.githubusercontent.com/55348946/83353221-a393a300-a359-11ea-9b53-f9d2ad8d5eaf.jpg)

**Comment by shprotru** [comment]
This happens because we don't redraw background, only front. That, I think, is incorrect, because we can move mouse cursor on the top of background. Second possible reason could be in mouse cursor drawing, it's now same for `SDL1` and `SDL2` builds, but I hope I will done it different for `SDL2`.

**Comment by ihhub** [comment]
It is because we do not hide the cursor while dimming the area.

**Comment by ihhub** [comment]
The problem lies in `void Battle::Interface::FadeArena( void )` function.
