### ISSUE TITLE
Map selection menu, memorizing map size filter

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#6888]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In the original game once player selected map size, it will be applied the next time he opens map list, even after loading and restarting the game.
fheroes2:

https://user-images.githubusercontent.com/55348946/227226159-3ecfc213-32aa-4248-b325-93d64d3682f8.mp4

The selection is preserved until player restarts the application.

### Save file

None.

**Comment by ihhub** [comment]
Hi @Branikolog , could you please expand the description of this issue? I believe that we shouldn't do this for all cases. For instance if a player chooses a standard map and then a campaign the selection wouldn't be preserved. At least state all possible cases and when the selection should be memorized. Also it is good to note that this is a runtime feature and we shouldn't remember it in the configuration file.

I'm assigning this issue for your update. Once you're done unassign yourself.

**Comment by Branikolog** [comment]
Hi, @ihhub .
Actually, in the original game the state of map filtering is always saved, until you restart the application. No matter you start campaign or multiplayer game, win a scenario or select expansion/original maps, map size filtering is always preserved.
