### ISSUE TITLE
Czech characters are incorrectly displayed in buttons

### ISSUE THREAD

**Issue by GeorgeK1ng** [ihhub/fheroes2#6906]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

I just download and builded project from sources based on original Czech game (original is fully localized, including voice in campaign cutscenes). And I found issue with buttons and Czech characters.

For example CANCEL is correctly translated as ZRUŠIT but ZRU**S**IT is displayed instead.
![image](https://user-images.githubusercontent.com/98261225/228021754-de8c5396-e94b-4551-9fce-cd8a52413335.png)

Same issue on this screen, instead on PRYČ is displayed PRY**C**
![image](https://user-images.githubusercontent.com/98261225/228022000-2661e30c-4dfa-4056-ad3a-56be5a28c4a4.png)

### Save file

No savefile

**Comment by GeorgeK1ng** [comment]
@zenseii Great, patiently awaiting for fix in 1.0.3 :)

**Comment by ihhub** [comment]
Based on the amount of work needed to fix this issue as well as tight schedule for the upcoming release this issue was set for 1.1.0 release.
