### ISSUE TITLE
Colossal Cavern - Unable to pass through a corner

### ISSUE THREAD

**Issue by Stiivi** [ihhub/fheroes2#6917]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

macOS

### Describe the bug

In the map Colossal Cavern (top-left part) it is impossible to pass the following corner:

<img width="810" alt="image" src="https://user-images.githubusercontent.com/71105/228865931-6b2e6925-8bf6-450d-bf12-0d1522b6c987.png">

Clearly it should be possible to pass. Problem seems to be just the corner, since it is possible to move further down the passage:

<img width="175" alt="image" src="https://user-images.githubusercontent.com/71105/228867361-c0539cf1-afaf-4b0c-86ad-bcf1610ca097.png">

This is how the portion of the map looks like after passing through using Dimension Door:

<img width="654" alt="image" src="https://user-images.githubusercontent.com/71105/228866925-93be1d8e-fcba-47ac-8e62-0c22e2c125fb.png">

### Save file

[Colossal_Cavern_BLOCK.sav.zip](https://github.com/ihhub/fheroes2/files/11112562/Colossal_Cavern_BLOCK.sav.zip)

**Comment by Mr-Bajs** [comment]
@ihhub 
The first impassable part of the upper corner is a design flaw of the original game. Hence I assume it won't be fixed due to licensing of the original map editor.

But will these issues be solved when the new editor is done? Or does the licencing issues also affect the maps them selfs?

**Comment by oleg-derevenetz** [comment]
> The bottom pyramid is not accessible.

Just like in the original game:

https://user-images.githubusercontent.com/32623900/228943029-3c35adb4-0ba5-4335-bf25-be46b18bc492.mp4

I believe that this issue can be closed, because there is no issue.
