### ISSUE TITLE
Allow to lower difficulty of campaign during gameplay

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#6922]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Some players faced a situation when a chosen difficulty level for a campaign is too high for them. Right now it is not possible to change campaign's difficulty unless you restart the campaign.

### Describe the possible solution

We should give an ability to lower campaign difficulty through the gameplay. Lowering it down reduces the final score and also gives an  opportunity to finish the campaign without restarting it, especially if you are on the last stages of a campaign.

**Comment by Branikolog** [comment]
Hello, @ihhub !
The root of the problem currently is that AI is playing same on any difficulty selected (even easy). I think the majority of complains from players appeared on "easy" campaign on walkthrough, so allowing to reduce difficulty wouldn't help.
I think, up to the time we make AI behaviour adaptive according to map difficulty selected (when he could act not so smart, not so aggressive and play using more defensive strategy on maps with "easy" or "normal" difficulty), there'd no need to allow difficulty changing, There would be a challenge only when map difficulty is "expert" or "impossible", which could happen mostly in the cases when player selected "normal" or "hard" campaign difficulty. (Impossible difficulty is never going to happen at all on "easy" campaign walkthrough.)
I believe, that AI should perform his best only on "expert"/"impossible" difficulty, while now he plays the same even on "easy" mode.

**Comment by ihhub** [comment]
Hi @Branikolog , it is not true. A difficulty level affects start resources of a human player as well as perks for AI so the behavior of AI differs depending on amount of perks it has.

**Comment by Branikolog** [comment]
@ihhub 

> Hi @Branikolog , it is not true. A difficulty level affects start resources of a human player as well as perks for AI so the behavior of AI differs depending on amount of perks it has.

I agree, but I believe, these perks don't effect really much the rate AI invades the territories. I also want to note that the majority of the original maps were made in such way, where AI enemies have rich territories, so resources shortage is not a common problem for AI.
Despite of this AI is still is considered too aggressive for "easy...hard" difficulties in my opinion.

**Comment by ihhub** [comment]
Hi @Branikolog , so based on this conversation lowering down the difficulty level does not make things worse :)

**Comment by Branikolog** [comment]
@ihhub 

> Hi @Branikolog , so based on this conversation lowering down the difficulty level does not make things worse :)

Only in a way we'd debate for a long time deciding what penalty would be applied for a player on difficulty changing, ;)
And again, in my opinion, it wouldn't help much. :)

**Comment by ihhub** [comment]
As discussed in Discord we can allow only to reduce difficulty in a campaign and the final score would be based on the lowest difficulty being chosen.
