### ISSUE TITLE
Creature amount number is in a wrong place while too close to another unit

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#694]
While two units are in front of each other their amount numbers should be placed closer to the creature it belongs. 
Also the number of the left creature is overlapped by the opposite creature.
![Over2](https://user-images.githubusercontent.com/55348946/83400335-4fe19200-a40b-11ea-966f-425d86dde079.jpg)
In the OG it looks like:
![Over](https://user-images.githubusercontent.com/55348946/83400385-67b91600-a40b-11ea-9cfe-b7a64ae254a2.jpg)

**Comment by Branikolog** [comment]
Here I should add, that on the screen we have 22 Magi and 9 ogres.

**Comment by ihhub** [comment]
I could say that the current solution would be to draw monster amount first and then monsters themselves.

**Comment by ihhub** [comment]
Closing this issue as it was fixed in #1019
