### ISSUE TITLE
Adventure map, adjustment for Summon Boat spell

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#6952]
Hello @Kazhuu,

I did some tests with the summon boat spell.
It turns out that if there are no more neutral boats (not belonging to any player) or player-built boats available and there is at least one free square adjacent to the hero, the spell is not grayed out, as it should be, and if the hero casts the summon boat spell the message "Summon Boat failed!!!" is displayed.
This is what we want to remove with these improvements.

- Save file: Before boats 02.savh (multiplyer game)(video below).
There are two neutral boats (not belonging to any player) at the beginning of the scenario.
Troyan casts the summon boat spell twice, the two neutral boats are summoned near Troyan.
After that, the summon boat spell is not grayed out in Troyan's magic book, although it should be because there is no other boat to summon.
There is one free square adjacent to Natasha, but there is no additional boat available.
If Troyan casts the non-greyed spell, the message "Summon Boat failed!!!" is displayed. This is what we want to remove with these improvements.

https://user-images.githubusercontent.com/43583994/230159377-38156be6-52ef-4447-becd-e4026053ea6c.mp4

- Save file: Before boats 01.savh (multiplyer game)(video below).
There are four boats available, two neutral boats from the beginning of the scenario and two boats built at the Weed Patch shipyard.
Natasha casts the summon boat spell four times, the four boats are summoned near Natasha.
After that, the summon boat spell is grayed out in Natasha's magic book.
There is no free square adjacent to Natasha (and furthermore, there is no additional boat available).
In this case, everything works as intended.

https://user-images.githubusercontent.com/43583994/230160100-e0c07105-cdc0-4b7b-bfac-7f8352a0c9f4.mp4

- Save file: Before boats 02.savh (multiplyer game)(video below).
There are two neutral boats (not belonging to any player) at the beginning of the scenario.
Troyan casts the summon boat spell twice, the two neutral boats are summoned near Troyan.
After that, the summon boat spell is not grayed out in Troyan's magic book, although it should be because there is no other boat to summon.
There is one free square adjacent to Natasha, but there is no additional boat available.
If Troyan casts the non-greyed spell, the message "Summon Boat failed!!!" is displayed.
A boat is built at the Weed Patch shipyard.
Troyan casts the summon boat spell, the just built boat is summoned near Troyan.
After that, the summon boat spell is grayed out in Troyan's magic book.

https://user-images.githubusercontent.com/43583994/230160243-bf68e704-7641-47fc-ac65-f42bbb8adfad.mp4

- Save file: Before boats 03.savh (multiplyer game)(video below).
There are two neutral boats (not belonging to any player) at the beginning of the scenario.
A boat is built at the Bloodreign shipyard.
Troyan casts the summon boat spell twice, the two neutral boats are summoned near Troyan.
After that, the summon boat spell is not grayed out in Troyan's magic book, although it should be because there is no other boat to summon.
There is one free square adjacent to Troyan, but there is no additional boat available.
If Troyan casts the non-greyed spell, the message "Summon Boat failed!!!" is displayed.

https://user-images.githubusercontent.com/43583994/230160448-89c3153c-aee5-4896-af32-50b6afecd3c0.mp4

- Save file: Before boats 04.savh (multiplyer game)(video below).
There are two neutral boats (not belonging to any player) at the beginning of the scenario.
Troyan casts the summon boat spell twice, the two neutral boats are summoned near Troyan.
After that, the summon boat spell is not grayed out in Troyan's magic book, although it should be because there is no other boat to summon.
There is at least one free square adjacent to Natasha, but there is no additional boat available.
If Troyan casts the non-greyed spell, the message "Summon Boat failed!!!" is displayed.
A boat is built at the Bloodreign shipyard.
Troyan casts the summon boat spell, the just built boat is summoned near Troyan.
Then Troyan casts the summon boat spell and boats are built at the Bloodreign shipyard until all free squares adjacent to Troyan are occupied by boats.
After that, the summon boat spell is grayed out in Troyan's magic book.

https://user-images.githubusercontent.com/43583994/230160582-fa3030b1-8401-4b9e-9914-9f5bac8a97c4.mp4

Here are the save files (multiplyer game):
[Before boats 01 04.zip](https://github.com/ihhub/fheroes2/files/11161581/Before.boats.01.04.zip)

If the hero tries to cast the spell while it is grayed out, a message is displayed depending on the case.
Something like this:
Yellow title for all message windows:
"Summon Boat"

Window Texts;
If there is no boat available:
"There is no boat available to cast this spell."

If there is no free square near the hero:
"There is no free location at sea near the hero to cast this spell."

If there is no boat available and no free square near the hero:
"There is no boat available and no free location at sea near the hero to cast this spell."

_Originally posted by @LeHerosInconnu in https://github.com/ihhub/fheroes2/issues/6729#issuecomment-1497909576_

**Comment by Kazhuu** [comment]
I assume you want to still keep the text "This spell can be casted only nearby water." when the hero is not near water, right?

**Comment by Kazhuu** [comment]
Okay @LeHerosInconnu I made a PR to fix these. Can you test it out?

**Comment by LeHerosInconnu** [comment]
Hello @Kazhuu,

> Okay @LeHerosInconnu I made a PR to fix these. Can you test it out?

So I tested the Summon Boat spell and everything works as expected.
Again, good work. :)

While we're in these windows, there's also this related issue: https://github.com/ihhub/fheroes2/issues/4849 to replace the word "water" by the word "ocean".

In correspondence with the above related issue, maybe we should also use the word "ocean" instead of "at sea" in the texts of the windows concerning the Summon Boat spell, to stay consistent:
If there is no free square near the hero:
"There is no free ocean location near the hero to cast this spell."

Instead of:
"There is no free location at sea near the hero to cast this spell."

And:
If there is no boat available and no free square near the hero:
"There is no boat available and no free ocean location near the hero to cast this spell."

Instead of:
"There is no boat available and no free location at sea near the hero to cast this spell."

**Comment by Kazhuu** [comment]
Okay @LeHerosInconnu I did the changes and also changed the text "This spell can be casted only nearby ocean." as well. So this PR will solve issue https://github.com/ihhub/fheroes2/issues/4849 as well.
