### ISSUE TITLE
1.0.3 all copied files prompt "same name as source message"

### ISSUE THREAD

**Issue by PatrykIBM** [ihhub/fheroes2#6989]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Clean install. 1.0.2 uninstalled and folder removed. fheroes2_windows_x64_SDL2_installer while performing installation when chosen directory with windows GOG copy of the game starts copying files in stage 3 while prompting on each and every file that source name is the same as destination filename. I held "enter" key to keep canceling all prompts and game came out working eventually after instalation but this bug is annoying.

Maybe I am doing something wrong, should I try x86 instead? Ps. uninstaller leaves game files in program folder so it has to be removed manually is it a feature or a bug? 1.0.2 and 1.0.3 had the same uninstalling behavior.

### Save file

No save available.
![obraz](https://user-images.githubusercontent.com/103884024/231238780-1a8b75ee-fbfb-48c5-955a-b6177c7cebc0.png)
![obraz](https://user-images.githubusercontent.com/103884024/231239096-77b13f96-0490-4e05-8634-bf70fe06428d.png)
![obraz](https://user-images.githubusercontent.com/103884024/231239280-35742cd8-3b42-48a2-804c-0a74aaf6300a.png)
![obraz](https://user-images.githubusercontent.com/103884024/231239384-84a9ce40-cb2c-431e-8e6b-9ffc73a4eb1f.png)

### Additional info

Last time I installed version 1.0.2 everything was working fine back then. Tested on GOG (win) version of heroes 2

**Comment by PatrykIBM** [comment]
Up: same with x86 installer. Script is probably overwriting already copied files for no reason.

**Comment by oleg-derevenetz** [comment]
The installation script somehow detects the HoMM2 CD drive, which is `.` in your case, i.e. the current directory, so it attempts to copy files from it, which is actually copying files into themselves, and Windows Explorer complains about that. It looks like some of the following registry paths on your machine:

`HKEY_LOCAL_MACHINE\SOFTWARE\New World Computing\Heroes of Might and Magic 2`
`HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\New World Computing\Heroes of Might and Magic 2`

contains the `CDDrive` key which value is `.`.

> Ps. uninstaller leaves game files in program folder so it has to be removed manually is it a feature or a bug? 1.0.2 and 1.0.3 had the same uninstalling behavior.

Uninstaller will never touch user-supplied files (including data files of the original game), this is intended behavour.

**Comment by PatrykIBM** [comment]
Thank you for quick reply Oleg. Indeed HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\New World Computing\Heroes of Might and Magic 2\1.0 contain value of . under CDDrive key. The other key which I assume is for 32 bit OS does not exist in mine.

I have no knowledge why that value is just "." I have not changed anything in this game files. I just have GOG gold edition installed for Windows I do not own original release on CD. Probably its just GOG thing to bypass CD check or something?

So, any advices to mitigate this? Modify value to actual optical drive path or remove the key completely? Or maybe I can hope that in future releases script will auto check this? Can I still consider this as BUG to be expected focusing in further releases or should I change something in my setup and close this case?

**Comment by oleg-derevenetz** [comment]
> So, any advices to mitigate this?

I'll try to properly mitigate this in the installation script later today and then I'll probably ask you to test these changes by running an installer made by our CI for the corresponding pull request.

**Comment by oleg-derevenetz** [comment]
Hi @PatrykIBM please test the installer from #6992 build artifacts in your environment. Does it solve the issue?

**Comment by PatrykIBM** [comment]
Hi Oleg, thanks for preparing this. Unfortunately can't test it now. I need some time since I am out till Monday. I will let you know as soon as I can if it works for me.

**Comment by oleg-derevenetz** [comment]
@PatrykIBM OK, thanks! There is no hurry with this.

**Comment by PatrykIBM** [comment]
@oleg-derevenetz Hey, it works. I swapped original script with one modified by you, and went with bat file. All went smooth no overrting. Thanks Oleg!

**Comment by oleg-derevenetz** [comment]
Let's close it when the corresponding pull request will be merged.
