### ISSUE TITLE
Keep game data and saves upon update

### ISSUE THREAD

**Issue by louisamand** [ihhub/fheroes2#6994]
### Your question

Is there a way to update fheroes2 (`brew` does it automatically every time I use it) without losing both save data and game data (`DATA`, `MAPS`, `MUSIC`) ?

**Comment by oleg-derevenetz** [comment]
I do not use Homebrew (I'm a MacPorts fan), but I have no idea how can you ever lose your save and data files because they should be in `~/.fheroes2` directory and `brew` should never ever touch them.

**Comment by louisamand** [comment]
Perfect, the game data is now in the right folder, thanks !
But I still see save data in the folder that I can't see in-game, weird...

**Comment by oleg-derevenetz** [comment]
> But I still see save data in the folder that I can't see in-game, weird...

Which folder?

**Comment by oleg-derevenetz** [comment]
> Could it be so simple that the files are saves from older versions of the game thats not supported anymore that just lingers on?

Maybe it is, but I'm still wondering how the game data (DATA/MAPS/MUSIC) was lost :)

**Comment by louisamand** [comment]
> Maybe it is, but I'm still wondering how the game data (DATA/MAPS/MUSIC) was lost :)
At first I did not put it in `~/.fheroes2` but rather in `.../homebrew/.../fheroes2`. Probably rushed the installation for I was too impatient to play it 🙃

> Which folder?
`~/.fheroes2/files/save`. Files have `.sav` (x3 with none visible in-game) and `.savh` (x4 with 3 visible in-game) extensions. I guess the latter refers to **h**ot-seats.
