### ISSUE TITLE
Game crashes if some heroes were dismissed in a row

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#700]
If player start dismissing his heroes game crashes. Not all maps and not all heroes...

**Comment by idshibanov** [comment]
Game currently keeps a lot of Hero pointers around, so I'm sure it's one of those nulls.

@Branikolog can you try to find a scenario to reproduce this, so we could see where exactly it fails? When it crashes, AI turn? Which screen?

**Comment by ihhub** [comment]
I know the reason: try to delete any hero in Debug version. It is related to lists class. I will remove iterator's usage, we have to use normal counters instead.
