### ISSUE TITLE
Installation guide should include hint for M1 configuration

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#7031]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Some users wonder how to install fheroes2 on devices based on M1.

### Describe the possible solution

Include some discription for devices on M1 into installation guide list.

**Comment by oleg-derevenetz** [comment]
`Homebrew` and `MacPorts` packages installed and work absolutely the same way on M1 and x86-based devices, and they are already mentioned in the Installation guide. What exactly causes difficulties?

**Comment by Branikolog** [comment]
Hello, @oleg-derevenetz !
I suppose users expect phrase containing "M1" term in installation guide. I've recently had several questions, whether M1 would be supported.
