### ISSUE TITLE
Death ripple and Death wave spells do not have animation

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#704]
In the original game we have an animation showing a moving wave through the battle field:
![image](https://user-images.githubusercontent.com/19829520/83512359-ada4d580-a502-11ea-8420-cebffe1029f0.png)

Our version simply does not have any animation.

**Comment by idshibanov** [comment]
What can we use to apply it for the whole battle display? Any ideas on this one?

**Comment by ihhub** [comment]
Hi @idshibanov ,

We need to use `SpriteBack`  object in order to remember the screen before applying any effects. Then we can copy this image and apply our effects and Blit it on display.
