### ISSUE TITLE
Main menu, buttons are shifting on hovering

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#7045]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Main menu buttons start shifting while hovering cursor over them. Issue occurs with widescreen resolution selected.

https://user-images.githubusercontent.com/55348946/233648769-f524db22-7f12-4cf7-9c43-6d6041791928.mp4

### Save file

None.

**Comment by ihhub** [comment]
This will be fixed in #7014
