### ISSUE TITLE
Castle's click area

### ISSUE THREAD

**Issue by shprotru** [ihhub/fheroes2#705]
![Снимок экрана от 2020-06-02 15-41-21](https://user-images.githubusercontent.com/53114202/83521507-01ee8c00-a4e8-11ea-8ecb-ad9f7779af67.png)
Here I am clicked on a castle, think must be chooses Barbarian castle instead of Warlock's castle

**Comment by undef21** [comment]
@shprotru , did you check this issue with latest builds? This issue is SDL2-related, probably.

**Comment by shprotru** [comment]
@undef21 just checked, this issue still present on latest build
