### ISSUE TITLE
Add a new UI element during battle to avoid touchscreen misclicks

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#7070]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Playing a battle of a mobile phone with a small screen (even 5") there is always a chance to misclick which leads to frustration and disappointment from the gameplay. We should account for cases when it's not possible to click precisely by a finger.

### Describe the possible solution

When attaching a monster we might display a wheel of directions (actually a hexagon) which show all possible directions the player can attack the opponent. In this case it is not needed to do precise movement on a screen to make an attack from a specified angle.

**Comment by dood-apo** [comment]
How about a different approach - let's allow performing swipes (drags) from a hex where attacking creature will be standing upon completing its movement to a hex where defending creature stands. This could result in drawing the "attack direction sword" only. Subsequent tap onto the defending creature would confirm the choice.

This would not require any new visual aids, which as I understand we are trying to avoid if possible.

**Comment by oleg-derevenetz** [comment]
> How about a different approach - let's allow performing swipes (drags) from a hex where attacking creature will be standing upon completing its movement to a hex where defending creature stands. This could result in drawing the "attack direction sword" only. Subsequent tap onto the defending creature would confirm the choice.

This proposal deserves attention, but I should say that this mechanics is very different from the OG/desktop mechanics and player should have a certain degree of imagination to figure out that it is possible to do this at all. If a player has only experience playing the desktop version, then I'm afraid he will never guess, even if this will be mentioned in the manual, because almost no one reads the manual.

**Comment by oleg-derevenetz** [comment]
> How about a different approach - let's allow performing swipes (drags) from a hex where attacking creature will be standing upon completing its movement to a hex where defending creature stands.

BTW this is quite (well, almost) working now - you can swipe/drag the finger from a hex where attacking creature will be standing upon completing its movement to a hex where defending creature stands and then confirm this by a separate touch. Why almost - because if you drag your finger a little further, then the attack vector may change :) But as a finger technique, it's still quite convenient compared to trying to immediately click on the right part of the hex of the defending creature (especially if that hex is small due to the device screen size).

**Comment by dood-apo** [comment]
> This proposal deserves attention, but I should say that this mechanics is very different from the OG/desktop mechanics and player should have a certain degree of imagination to figure out that it is possible to do this at all.

That might be right. But to be honest, when I was starting playing fheroes2 on my phone, the first instinct was to draw the attack angle with my finger. I actually had to use my imagination to discover that I should be tapping the correct part of the destination hex, like I would be doing it using the mouse.

> BTW this is quite (well, almost) working now

Well, but the whole point of my proposal is to always use a whole hex as an input source and to avoid having specialized parts of the hex. On small screens (phones), one hex is just about big enough to comfortably hit with the finger. So while I agree that you can drag right now, you still need to be very precise and actually be very precise twice.

**Comment by oleg-derevenetz** [comment]
> But to be honest, when I was starting playing fheroes2 on my phone, the first instinct was to draw the attack angle with my finger.

Well, it seems to me that someone who has already played Heroes on PC won't even try it, because on PC this works differently :) However, as an **additional** mechanic to the existing one, it might be suitable.

**Comment by dood-apo** [comment]
> Well, it seems to me that someone who has already played Heroes on PC won't even try it, because on PC this works differently :)

But on the other hand if that same person has played a lot of various games on touch screen devices, they might try or even expect it. Please note that on PC you have a hovering cursor which changes appearance, which is not the case on touch screen devices. Not sure if comparing expectations is fair taking this into account.

> However, as an additional mechanic to the existing one, it might be suitable

Yes, it can be done without affecting the current mechanic. Another option is to affect the current mechanic just a little bit - the confirmation tap being more relaxed (meaning anywhere on the destination hex) could also apply to the current input method.

> But I still think that most likely most of the players who had OG experience will not guess this mechanics :)

Probably. But there is a lot of improvements in fheroes2 that I would not guess without reading the manual or watching streamers. And most of those improvements are great :).
