### ISSUE TITLE
MIDI musics, there is no more MIDI music if the user does not wish to use the fonts of the fheroes2 folder "soundfonts" (version 1.0.3 7065)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#7073]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Windows 7 SP1 - 64 bits.

In fheroes2, MIDI music is no longer played if you don't want to use the MIDI fonts in the "soundfonts" folder (by renaming the folder "nosoundfonts" for example) to have the same rendering as the original game.
The MIDI musics generated from the MIDI fonts of the folder "soundfonts" installed by fheroes2 are far from being similar and give a different rendering.
It still worked with version 1.0.3 7035.
If there are no MIDI fonts available, the program should use the default MIDI fonts of the operating system.

In original game (Windows):
Activate the sound of the video.

https://user-images.githubusercontent.com/43583994/234962636-d6604750-0633-4e2c-ae6f-ecce22a2b79f.mp4

In fheroes2:
Activate the sound of the video.

https://user-images.githubusercontent.com/43583994/234962847-a29d5ded-1ed5-4116-9123-e9cb2455f482.mp4

### Save file

Not needed.

**Comment by oleg-derevenetz** [comment]
One of vcpkg `sdl2-mixer` package maintainers unjustifiably [removed](https://github.com/microsoft/vcpkg/blob/master/ports/sdl2-mixer/vcpkg.json) the support of native MIDI from this package, so now we need to patch the package somehow to get the native MIDI to work on Windows. I believe this is not urgent and can be addressed during the next update cycle (after the upcoming release).
