### ISSUE TITLE
Set Unknown Artifact ID to 0 or 255

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#7099]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

The current ID for Unknown Artifact is 103. This isn't bad as it is the last value in an enumeration. However, this carries a lot of problems when we start adding new artifacts essentially increasing this number and making a mess when users load old saves.

### Describe the possible solution

Either we set the artifact ID to 0 or to some high value like 255. Since we don't want to handle extra cases from map loading let's just increase the value.

**Comment by Alucard648** [comment]
Better increase max artifact ID to 65536 or larger.

**Comment by ihhub** [comment]
We will set to 0.
