### ISSUE TITLE
Mouse double click delay over status window

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#711]
If a player does fast clicks over any place of status window and immediately moves mouse over world map (This issue can be caught, when you change heroes, that are on different terrain, and at the same time try to open inventory, by double click over any hero), the moment mouse returns to any place of status window, delayed click occurs.

**Comment by Branikolog** [comment]
Happens with midi music only. As now we experience a short lag, while starting new melody (when hero switches)

**Comment by ihhub** [comment]
Hi @Branikolog , could you please verify this issue as we fixed lagging with midi? If it's not valid anymore please close the issue.

**Comment by Branikolog** [comment]
The problem is gone!
