### ISSUE TITLE
Mage Guild, Summon Elemental and Town Portal spells too frequent in Mage Guild compared to the original game (1.0.3 7084)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#7117]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Playing the game and watching let's play fheroes2 videos, it seems to me that the Summon Elemental and Town Portal spells appear way too often compared to the original game.

Here an old closed issue on the subject: https://github.com/ihhub/fheroes2/issues/1531.

Here possible information about the subject: https://handbookhmm.ru/kakim-obrazom-zaklinaniya-popadayut-v-magicheskuyu-gildiyu.html.

For those who play a lot of fheroes2, how do you feel about this subject compared to the original game?

### Save file

Here is a savegame from the last fheroes2 game played:
[Broken_Alliance_0071.zip](https://github.com/ihhub/fheroes2/files/11410442/Broken_Alliance_0071.zip)
The Town Portal spell is present in both Mage Guilds fully built and a Summon Elemental spell is present in one of the two Mage Guilds fully built.

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu !
I've made a dozens of tests and I don't see any flaws in generation in fheroes2. Elementals may seem to appear too frequently, but don't be confused by their quantity: there're 4 similar but still different spells. While doing my tests I could hardly achieve the situation, when I got two **same** elemental spells in 8 castles. I even experienced (both in OG and fheroes2) a rare case, when I had both summoning spells in Wizard castle. :) So I don't see it appears more often than other spells.

I can only tell, that TP appears a bit more often... Like 2 times for 8 castles each ~2 restarts. But how many 5th level spells do we have to make them appear for 8 castles without duplicates? If I'm not mistaken TP is supposed to be more rare spell, since it's rather gamebreaking. But still I got some generation without TP at all. So It looks like TP appears random... Possibly ~ +5% more than others. I could say I catch Resurrection or Hypnotize less often, but it is all about random...

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

> Hi, @LeHerosInconnu ! I've made a dozens of tests and I don't see any flaws in generation in fheroes2. Elementals may seem to appear too frequently, but don't be confused by their quantity: there're 4 similar but still different spells. While doing my tests I could hardly achieve the situation, when I got two **same** elemental spells in 8 castles. I even experienced (both in OG and fheroes2) a rare case, when I had both summoning spells in Wizard castle. :) So I don't see it appears more often than other spells.

You say that these spells do not appear more often than the other spells in fheroes2, but in the original game these spells do not have the same chance to appear as the other spells.

> I can only tell, that TP appears a bit more often... Like 2 times for 8 castles each ~2 restarts. But how many 5th level spells do we have to make them appear for 8 castles without duplicates? If I'm not mistaken TP is supposed to be more rare spell, since it's rather gamebreaking. But still I got some generation without TP at all. So It looks like TP appears random... Possibly ~ +5% more than others. I could say I catch Resurrection or Hypnotize less often, but it is all about random...

I made a single test with a test scenario in Heroes 2 Gold 2.1 English version and fheroes2 1.0.3 7084.
Here is what I observed:

In Heroes2:
With 12 castles for the human player and 12 towns for the AI player.
Here is what I got:

Human player's Mage Guilds at the beginning of the scenario:
- No Summon Elemental spell
- No Town Portal spell

Mage Guilds of the AI player captured by the human player:
- 2 Summon Fire Elemental spells
- No Town Portal spell

This is typically what I see when I play Heroes 2.

In fheroes2:
With 12 castles for the human player and 12 towns for the AI player.
Here is what I got:

Human player's Mage Guilds at the beginning of the scenario:
- 3 Summon Earth Elemental spells
- 1 Summon Air Elemental spell
- 1 Summon Fire Elemental spell
- 2 Town Portal spells

Mage Guilds of the AI player captured by the human player:
- 2 Summon Air Elemental spells
- 1 Summon Earth Elemental spell
- 1 Summon Water Elemental spell
- 2 Town Portal spells

We can easily notice that it is not really similar to what happens in the original game.

Here are some details about the fact that some spells are considered rare in the original game (Town Portal, Visions, Haunt, and all 8 elemental summoning spells):
"2. There are "rare" and "inappropriate for the type of castle" spells in the game. Holy word and Holy shout spells are considered unsuitable for the Necropolis, and Death ripple and Death wave are considered unsuitable for all other castles. Rare spells are Town Portal, Visions, Haunt, and all 8 elemental summoning spells. If the spell is rare or inappropriate, there is a 10/11 chance it will be rejected and the game will return to step 1."
https://handbookhmm-ru.translate.goog/forum/viewtopic.php?f=11&t=31&p=12690&_x_tr_sl=ru&_x_tr_tl=en&_x_tr_hl=en#p12690

Here are the test scenario and save files:
[0 9988h and saves.zip](https://github.com/ihhub/fheroes2/files/11412919/0.9988h.and.saves.zip)

**Comment by oleg-derevenetz** [comment]
To be honest, I like the spell distribution in fheroes2, including the more frequent occurrence of powerful spells. I lack the resolve to fix this :) It's quite sad to observe approximately the same weak spells in all castles.

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> To be honest, I like the spell distribution in fheroes2, including the more frequent occurrence of powerful spells.

The Town Portal spell is a particular spell.
Once it is present in a mage guild, it is not really necessary to have it in another mage guild because it allows to visit all the mage guilds easily if you want.
If it is present in several mage guild it becomes then a little redundant.
Also, it is much more fun to get it when this spell is more rare in the mage guilds. :)

It's a bit the same for summon elemental spells.
Once you have one type of these spells, the other types are kind of the same.
Same thing, it's also a good surprise when you get one of them in a mage guild.

Their rarity is also an incentive for the player to build other mage guilds to try to get them.
By becoming too easily attainable in a mage guild, the player no longer has that need, nor that hope of joy in obtaining them.

Also, the fact that these spells are rarer in the mage guilds makes the pyramids particularly attractive, because in the pyramids there is no such rarity, as all spells have the same chance to appear.
So even in an advanced game, pyramids are still interesting locations to visit.

Currently, fheroes2 removes all this mechanics.
And then you get too many Town Portal and Summon Elemental spells when you're hoping for True Resurrection spell for example.

> I lack the resolve to fix this :)

You can also make a proposal in "Discussions" so that it is possible to have this operating mode in option in fheroes2. :)

> It would be quite sad to observe approximately the same weak spells in all castles, like it happens in OG.

For me, all the other level five spells are interesting.
Armageddon, Dimension Door, Mirror Image, True Resurrection, all have their uses, and allow you to develop different strategies.
Only the Hypnotize spell, in its current state, is not really interesting and is a bit of a "pollution" for the mage guilds.

**Comment by Branikolog** [comment]
> Only the Hypnotize spell, in its current state, is not really interesting and is a bit of a "pollution" for the mage guilds.

Hypnotize spell is the "Eagle Eye" of the mage guild. :D
