### ISSUE TITLE
Mouse lags while pulling a scroll bar of "Town Portal" spell town list

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#713]
If you grab with a mouse scroll bar and start moving it up and down you can notice, that cursor is lagging.

**Comment by Branikolog** [comment]
This issue happens now only for SDL1 whit the game running at high resolutions. Seems to be optimization problem.

**Comment by ihhub** [comment]
Hi @Branikolog could you please verify this issue?

**Comment by Branikolog** [comment]
Hi, @ihhub !
The problem is gone! -1 issue. :)
