### ISSUE TITLE
Android version is impossible to update from Google Play Store

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#7167]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Android

### Describe the bug

After uploading 1.0.4 it is impossible to update from Google Play Store. Maybe due to changes done in the toolset.

### Save file

none

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , do you want any ideas why it could happen?

**Comment by oleg-derevenetz** [comment]
What do you mean by "impossible"?

**Comment by oleg-derevenetz** [comment]
You cannot install updates from Google Play over APK from Github (does not matter whether it's debug or release build), because they are signed by different signatures. You can only update a previous installation from Google Play itself.

**Comment by oleg-derevenetz** [comment]
@zenseii unless some special measures was performed, the "release" key from GitHub becomes so-called "upload key" for AAB, but keys to sign resulting APKs (that are installed on end-user devices) are generated by Google and stored in their so-called "play app signing" infrastructure.

**Comment by ihhub** [comment]
@oleg-derevenetz , thank you so much for this explanation!
