### ISSUE TITLE
Game freeze on next turn

### ISSUE THREAD

**Issue by vovansrnd** [ihhub/fheroes2#7168]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

v 1.0.4 - cannot continue the game. Its freeze on the next turn.

### Save file

[AUTOSAVE.zip](https://github.com/ihhub/fheroes2/files/11469924/AUTOSAVE.zip)

**Comment by ihhub** [comment]
It is the problem with an AI hero using Dimension Door.

**Comment by ihhub** [comment]
@vovansrnd , a fix is already in review. Thank you for spotting it!

**Comment by vovansrnd** [comment]
> @vovansrnd , a fix is already in review. Thank you for spotting it!

Thanks, it works!
