### ISSUE TITLE
Hero shouldn't be automatically attacked by creatures placed near Stone Liths 

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#717]
Currently If a hero enters Stone Liths, which exit is located near creature, battle automatically occurs. 
Hero should have an ability to run away using "Space" if creatures are too strong near the Stone Liths exit.
![Teleport](https://user-images.githubusercontent.com/55348946/83638143-632e6200-a5b1-11ea-83f3-98aef9d4d148.jpg)
![Teleport2](https://user-images.githubusercontent.com/55348946/83638152-66c1e900-a5b1-11ea-9908-3e0e016ce343.jpg)
Note, that battle still should occur, when hero used "Dimension Door" spell too close to creature.

**Comment by ZsoltMolnarrr** [comment]
"Note, that battle still should occur, when hero used "Dimension Door" spell too close to creature."
I believe this is not true. In GOG version of the OG when you dimension door next to a creature, it doesn't attack you automatically. You can even pick up loot without getting attacked, attack will only occour on physical movement next to creatures.

**Comment by Branikolog** [comment]
@ZsoltMolnarrr, hello! 
That's true, the original game allows it. But everyone in heroes community knows, that "Dimension Door" spell allows to cheat legally. 
In future we are going to nerf it even more... 
For now, we believe, that it will be fair, if neutrals attack hero, being teleported too close.
At the same time, it is not the original behavior, and can ruin gameplay of some maps... 
So I think we should add both this options (Dimension door and Stone Liths) to CONFIG menu, so player can decide on his own...

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

I don't consider the fact of teleporting next to the creatures and recovering artifacts and resources without triggering a combat as cheating, but rather as a reward for building a level 5 Mage guild, and certainly several to get the Dimension Door spell, especially at the highest level of difficulty.

So yes, the original gameplay must be preserved, and offer the changes as an option.
