### ISSUE TITLE
Please extract the videos from the homm2.gog  disc image file

### ISSUE THREAD

**Issue by xcom169** [ihhub/fheroes2#7172]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Extract HOMM2 resources  script doesn't extract the videos from the GOG version of the game. 

### Describe the possible solution

Please add commands to the script to extract the videos from the homm2.gog  fle. 

### Additional info

![image](https://github.com/ihhub/fheroes2/assets/17802090/89fe1746-5698-475d-9190-cf6e07b505c2)

**Comment by oleg-derevenetz** [comment]
If you are talking about animations (`ANIM` directory) then it extracts them.

**Comment by xcom169** [comment]
Maybe I'm doing it wrong, but I used innoextract to extract the setup_homm_2_gold.exe archieve, and after I don't have the ANIM folder but I have a homm2.gog  CD-image which I can't use with the extract_homm2_resources.bat file.  Is it possible to use this script to mount this file, and cut out the ANIM folder from it? 

Thanks

**Comment by oleg-derevenetz** [comment]
> but I used innoextract to extract the setup_homm_2_gold.exe archieve

That's what I'm talking about. You should have the GOG HoMM2 **installation**, not just an unpacked InnoSetup bundle. Unpacked bundle is missing some files needed by the script to unpack the `homm2.gog` image.

**Comment by xcom169** [comment]
Yes, but the setup needs admin rights, and I don't have it on this machine.

**Comment by oleg-derevenetz** [comment]
Basically, this script uses the `DOSBOX` to mount the GOG CD image and extract the animations. See the contents of the `extract_homm2_resources.ps1` script, towards the end.
