### ISSUE TITLE
Implement full CP1250 font support

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#7180]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

We only have partial support for CP1250 font for Polish, Slovak and Czech. The button font has been implemented in https://github.com/ihhub/fheroes2/pull/7173 but for normal text we are missing some letters.

### Describe the possible solution

Add the remaining letters for CP1250 for our supported languages.

**Comment by Roxterat** [comment]
Ready to fill in some characters.

**Comment by Roxterat** [comment]
So, as mentioned before, I would take (at least) Normal and Small font of Slovak characters and after PR#7173
(https://github.com/ihhub/fheroes2/pull/7173)
is closed/merged, I will take a look at "generateCP1250GoodButtonFont" function in ui_font.cpp and see that the characters are included there as well.
More characters possibly included further as well.

**Comment by Roxterat** [comment]
Characters nearly added, just want to figure "lowercase L with caron" (not in Codepage) and could be a PR.

**Comment by Roxterat** [comment]
Resolved, PR open for review.

**Comment by Districh-ru** [comment]
Just a note:
There are still some CP1250 letters to add to Normal and Small fonts: [Ş](https://www.ascii-code.com/character/%C5%9E) [µ](https://www.ascii-code.com/character/%C2%B5) [Ă](https://www.ascii-code.com/character/%C4%82) [Ç](https://www.ascii-code.com/character/%C3%87) [Ë](https://www.ascii-code.com/character/%C3%8B) [Î](https://www.ascii-code.com/character/%C3%8E) [Đ](https://www.ascii-code.com/character/%C4%90) [Ţ](https://www.ascii-code.com/character/%C5%A2) [ß](https://www.ascii-code.com/character/%C3%9F) [ă](https://www.ascii-code.com/character/%C4%83) [ç](https://www.ascii-code.com/character/%C3%A7) [ë](https://www.ascii-code.com/character/%C3%AB) [î](https://www.ascii-code.com/character/%C3%AE) [đ](https://www.ascii-code.com/character/%C4%91) [ţ](https://www.ascii-code.com/character/%C5%A3)

**Comment by Roxterat** [comment]
So RP https://github.com/ihhub/fheroes2/pull/7184 is merged, I'll check if "generateCP1250GoodButtonFont" function in ui_font.cpp got all it needs (probably do), take a breather and will see if I can manage other letters too. Those are not Czech for certain (I know) and as far as I google they don't look Polish either..

**Comment by Roxterat** [comment]
> If we have covered Czech, Polish and Slovak in all the fonts then this PR can be closed.

Czech and Slovak characters are done, I am uncertain about Polish characters though.
