### ISSUE TITLE
System Info, Audio Settings, the audio setting "Music Type" should be set to "MIDI" by default (and not to "External") when there is no "MUSIC" folder present

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#7182]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

In fheroes2, the audio setting "Music Type" should be set to "MIDI" by default (and not to "External") when there is no "MUSIC" folder present.

In fheroes2:

![MIDI default no MUSIC folder](https://github.com/ihhub/fheroes2/assets/43583994/be370fd1-dc25-47d4-a5f3-0863a355ef91)

**Edit.**

Also, if the user tries to change the "Music Type" setting, a message should inform the user that there must first be a "MUSIC" folder with the necessary files before the music type setting can be changed.

In original game:
The message of the original game when only MIDI music can be used:
Note: The message of the original game cannot be used in fheroes2, because it is not the same operation for the type of music.

![MIDI only message 001](https://github.com/ihhub/fheroes2/assets/43583994/920481a4-16af-458a-8ef8-9bcf58ca9eb3)

![MIDI only message 002](https://github.com/ihhub/fheroes2/assets/43583994/f281205d-fd9f-47c5-a195-011fc08480b9)

### Describe the possible solution

In fheroes2, the audio setting "Music Type" should be set to "MIDI" by default (and not to "External") when there is no "MUSIC" folder present.

**Comment by oleg-derevenetz** [comment]
To be honest, this proposal looks like an increase in the amount of manual work for the end user. I doubt that many players will ever select the MIDI music deliberately. I suspect that the usual sequence of actions looks like this: player downloads the demo version, plays a little, then it upgrades assets to the full version from GOG/UbiSoft/whatever. In the current situation, he will not need to do anything extra - in the demo version there will be MIDI, in the full version OGG/MP3/FLAC will be automatically used. According to this proposal, the user will need to switch to the external music manually after an upgrade. It doesn't look too "user-friendly".

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> To be honest, this proposal looks like an increase in the amount of manual work for the end user. I doubt that many players will ever select the MIDI music deliberately. I suspect that the usual sequence of actions looks like this: player downloads the demo version, plays a little, then it upgrades assets to the full version from GOG/UbiSoft/whatever. In the current situation, the user will not need to do anything extra - in the demo version there will be MIDI (as a fallback), in the full version OGG/MP3/FLAC will be automatically used. According to this proposal, the user will need to switch to the external music manually after an upgrade. It doesn't look too "user-friendly".

Is the "MUSIC" folder automatically created and filled with the necessary files when the user uses fheroes2 with the Gold 2.1 English version or the 1.3 English version (basic version plus patch)?

**Comment by oleg-derevenetz** [comment]
> Is the "MUSIC" folder automatically created and filled with the necessary files when the user uses fheroes2 with the Gold 2.1 English version or the 1.3 English version (basic version plus patch)?

If the user runs the asset extraction script, then yes, all files, including music files, should be extracted and copied to the appropriate places.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> > Is the "MUSIC" folder automatically created and filled with the necessary files when the user uses fheroes2 with the Gold 2.1 English version or the 1.3 English version (basic version plus patch)?
> 
> If the user runs the asset extraction script, then yes, all files, including music files, should be extracted and copied to the appropriate places.

If I understood correctly, it means that from, for example, the Gold 2.1 installation of the original game (not the GOG version), the tracks of the Audio CD will be retrieved from the original game CD and inserted in a compatible format in the "MUSIC" folder created, and if the original game CD is not present, the user will be asked to insert the original game CD so that the tracks of the Audio CD are retrieved.
Is this how it works?

**Comment by oleg-derevenetz** [comment]
> the tracks of the Audio CD will be retrieved from the original game CD and inserted in a compatible format in the "MUSIC" folder created, and if the original game CD is not present, the user will be asked to insert the original game CD so that the tracks of the Audio CD are retrieved.

No, if the music is available in the form of CD tracks on a physical CD, it will not be copied and converted to some compatible audio format. This is not currently supported.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> > the tracks of the Audio CD will be retrieved from the original game CD and inserted in a compatible format in the "MUSIC" folder created, and if the original game CD is not present, the user will be asked to insert the original game CD so that the tracks of the Audio CD are retrieved.
> 
> No, if the music is available in the form of CD tracks on a physical CD, it will not be copied and converted to some compatible audio format. This is not currently supported.

So yes, this issue is just about that.

**Comment by oleg-derevenetz** [comment]
> So yes, this issue is just about that.

Well, how many owners of original CDs are there now compared to those who install the game over the Internet from GOG or UbiSoft? What is convenient for the former will be inconvenient for the latter.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> > So yes, this issue is just about that.
> 
> Well, how many owners of original CDs are there now compared to those who install the game over the Internet from GOG or UbiSoft?

I don't know.
Do you have any information on the subject?

« Et s’il n’en reste qu’un, je serai celui-là ! »
Victor HUGO (1802-1885), Les Châtiments (1853)

> > What is convenient for the former will be inconvenient for the latter.

If the "MUSIC" folder is present, it won't bother the seconds at all.

**Comment by oleg-derevenetz** [comment]
> Do you have any information on the subject?

I suppose that there are much fewer of them than at the time when these CDs were being sold. None of my laptops have a CD drive. No modern handheld devices (phones, tablets, game consoles) have a CD drive. It's a fossil.

> If the "MUSIC" folder is present, it won't bother the seconds at all.

But, if a user tried the demo version _from the Internet_ first (which, as we all know, doesn't include external music), and then he liked it and upgraded it to the modern HoMM2 installation _from the Internet_, then he will need to perform additional actions to switch the music source from MIDI to External. There will undoubtedly be questions like "I bought the full version, but I still can't hear normal music." Is all this worth the convenience for the few owners of fossil physical CD? :)

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> > Do you have any information on the subject?
> 
> I suppose that there are much fewer of them than at the time when these CDs were being sold. None of my laptops have a CD drive. No modern handheld devices (phones, tablets, game consoles) have a CD drive. It's a fossil.

Those who still use these fossils will appreciate it. :D

> > If the "MUSIC" folder is present, it won't bother the seconds at all.
> 
> But, if a user tried the demo version _from the Internet_ first (which, as we all know, doesn't include external music), and then he liked it and upgraded it to the modern HoMM2 installation _from the Internet_, then he will need to perform additional actions to switch the music source from MIDI to External. There will undoubtedly be questions like "I bought the full version, but I still can't hear normal music."

If the modern installation goes smoothly, then the "MUSIC" folder will be present and it will not have to do anything more.
("MIDI" is by default only when there is no "MUSIC" folder present.)

> Is all this worth the convenience for the few owners of fossil physical CD? :)

So, we will break the heart (Hello @zenseii) of these players. :)

**Comment by oleg-derevenetz** [comment]
> If the modern installation goes smoothly, then the "MUSIC" folder will be present

Yes, if the user installs the full version of the game from the very beginning. But the demo version doesn't have external music. Currently it's not a problem, but you propose to set the music source to MIDI if there is no MUSIC folder present, so users with demo version will get the music source setting set to MIDI. And if they install the full version later, it still will be set to MIDI.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> > If the modern installation goes smoothly, then the "MUSIC" folder will be present
> 
> Yes, if the user installs the full version of the game from the very beginning. But the demo version doesn't have external music. Currently it's not a problem, but you propose to set the music source to MIDI if there is no MUSIC folder present, so users with demo version will get the music source setting set to MIDI. And if they install the full version later, it still will be set to MIDI.

It means that currently, fheroes2 does not check which version of the original game is used before launching?
Isn't this a potential source of problems?

Perhaps the user should be informed that a full version has to be installed (so other than the demo version) in order to have a complete functioning.

**Comment by oleg-derevenetz** [comment]
> Isn't this a potential source of problems?

So far it's working quite well.

> Perhaps the user should be informed that a full version has to be installed (so other than the demo version) in order to have a complete functioning.

The user is usually aware that he is using the demo version, because it is he who runs the corresponding script or selects the appropriate "download the demo version" item in the installer. And as far as I understand, the policy of the project is not to advertise specific sources of original HoMM2 packages. Informing the user about where, how and at what price the assets of the original game can be found is completely beyond the scope of this project.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> The user is usually aware that he is using the demo version, because it is he who runs the corresponding script or selects the appropriate "download the demo version" item in the installer.

The user should then know what he is doing, and if he first used the demo version and then switched to a full version, he will have to make the adjustment to get the desired type of music.
I don't see a problem with that.

**Comment by oleg-derevenetz** [comment]
> The user should then know what he is doing

Yes, the soft of... User is aware that he is running a demo version. And he is aware that he will get new maps, campaigns, etc when he will install the full version. He installs the full version and automatically gets campaigns, new maps, no additional steps are required. Currently he gets the new music as well - automatically, no additional actions are currently required on his side. Your proposal involves additional actions on the user's side to get the same result, and the benefits of them are not entirely clear.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

There is a problem with this.
Some sounds are available in MIDI and are no longer available when the "MUSIC" folder is not present and the music type is set to "External".

In fheroes2:
Activate the sound of the videos.
Music Type set to "MIDI":

https://github.com/ihhub/fheroes2/assets/43583994/5c4f7dd8-26b5-429a-9eb8-9b7fd9c48442

Music Type set to "External" without "MUSIC" folder:

https://github.com/ihhub/fheroes2/assets/43583994/e59cb780-1ee6-46ce-ad4b-b1f7be9e88bf

**Comment by oleg-derevenetz** [comment]
> There is a problem with this.
Some sounds are available in MIDI and are no longer available when the "MUSIC" folder is not present and the music type is set to "External".

This issue should be fixed by #7183:

https://github.com/ihhub/fheroes2/assets/32623900/3d592051-d01d-48d8-b3da-1355891ffe97

Also, the presence of MUSIC folder doesn't guarantee the presence of music files themselves - this folder may be present, but empty. Currently this situation is handled just fine (if there is no external music file for a track, then we play the corresponding MIDI track if there is one). I'm not sure how this situation should be handled according to your proposal.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> > There is a problem with this.
> >  sounds are available in MIDI and are no longer available when the "MUSIC" folder is not present and the music type is set to "External".
> 
> This issue should be fixed by #7183:
> 
> https://github.com/ihhub/fheroes2/assets/32623900/3d592051-d01d-48d8-b3da-1355891ffe97

I will pay attention to this in my next test game.

> Also, the presence of MUSIC folder doesn't guarantee the presence of music files themselves - this folder may be present, but empty (or have an incomplete set of music files). Currently this situation is handled just fine (if there is no external music file for a track, then we play the corresponding MIDI track if there is one). I'm not sure how this situation should be handled according to your proposal.

Yes, when I write the "MUSIC" folder it also implies the necessary files inside the folder. :)

**Comment by oleg-derevenetz** [comment]
> Yes, when I write the "MUSIC" folder it also implies the necessary files inside the folder. :)

"Necessary files" a bit of an ephemeral concept :) Music files may present only partially, for example. How many files should be missing in order to switch to MIDI? With current implementation, such questions do not even arise.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> > There was no sound played, for example, for the magic garden.
> 
> With objects the logic was more straight: if there is MIDI sound set in the game settings, then play melody X, otherwise play melody Y. There was no transparent switching in their case, and the problem was precisely in its absence, and not that is was not needed at all. Thus, we should add it in this case, and not abandon it altogether.

Fine, then. :)
Thanks for all the explanations.
