### ISSUE TITLE
i was unable to update the apk. had to uninstall first. 

### ISSUE THREAD

**Issue by gruianovac** [ihhub/fheroes2#7189]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

cant remember what v 1 had probably 1.01. 1.04 threw exception. 

why are you forcing a save file attachment?!

### Save file

h
[README.txt](https://github.com/ihhub/fheroes2/files/11483928/README.txt)

irrelevant

**Comment by oleg-derevenetz** [comment]
> Platform: Windows

What? Which version of Android do you have?

> cant remember what v 1 had probably 1.01

Then it's probably was signed by a different certificate.

> why are you forcing a save file attachment?!

It is not forced:

> If you do not want to provide a save file (for example, because it is not required to reproduce the issue or is not available), please indicate here the reason why the save file cannot be attached to this bug report.

But it is needed in most cases, and because of this that input field is mandatory.

**Comment by ihhub** [comment]
Hi @gruianovac , could you please reply to the message above as the provided by you information is not enough? In order to fix the issue we have to know all conditions.

**Comment by gruianovac** [comment]
android 12

**Comment by ihhub** [comment]
@gruianovac , how did you install the previous version? From the APK file? How did you install 1.0.4: from the APK file or from Google Play Store?

**Comment by oleg-derevenetz** [comment]
@ihhub 1.0.1 could only be installed from APK, there was no Google Play publication at the time.

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , I asked just in case :)

**Comment by ihhub** [comment]
As highlighted by @oleg-derevenetz installation from APK and from Google Play Store means different certificates. I am closing this issue due to lack of support and provided information.

**Comment by gruianovac** [comment]
i do not remember, I think the first one was from store while this new one was from apk
