### ISSUE TITLE
Adventure map, AI behavior, AI does not protect its castles enough (1.0.4 7171)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#7193]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

In fheroes2, AI does not protect its castles enough.

I don't know if it's because of a lack of gold and/or resources, but the castle's garrison is not very numerous, while there are a significant number of creatures available for recruitment.

Also, in the example, the halflings should be spread across all the slots rather than just one to maximize the damage possible with the ballista and turrets before all the halflings groups are decimated.

Also, the main hero goes away from the castle to visit the resource generators, while this could be done by a secondary hero.

My heroes may seem far away, but at least one of them, Sandro, can easily reach the AI player's castle in one turn with the Dimension Door spell.

In fheroes2:

![AI castle poor defense 001](https://github.com/ihhub/fheroes2/assets/43583994/664c9ebb-6f76-4b5b-b2fc-03e1c204646e)

![AI castle poor defense 002](https://github.com/ihhub/fheroes2/assets/43583994/72f4e732-59f1-46fc-9b21-3b033a7e54c3)

![AI castle poor defense 003](https://github.com/ihhub/fheroes2/assets/43583994/1db368ae-dc7d-4d83-8854-d281395817cd)

![AI castle poor defense 004](https://github.com/ihhub/fheroes2/assets/43583994/b3098e28-921b-45a2-8865-71b6eb78afab)

### Describe the possible solution

In this case, the powerful hero of the AI should be positioned in defense of the castle with the maximum number of recruited creatures, as he does not have many other possibilities of action from a strategic point of view on the adventure map being stuck on his island.
A secondary hero should take care of collecting resources from the resource generators.
Also, in this case, there is no point in saving gold, the castle is fully built.
AI might as well spend the gold on buying creatures waiting for the enemy to attack or on building up a large army while waiting for other possible strategic actions, such as capturing the boat of a weak enemy hero who ventures onto the island, or recruiting a hero who has the Dimension Door spell.
AI should also take into account the possible use of "long distance" movement spells (notably dimension door) by its opponents to organize the defense of its castles and not wait for an opposing hero to be a threat near the castle.

### Additional info

Here are the save files (end of previous turn, beginning of turn, and in front of the AI player's castle):
[AI castle poor defense 01.zip](https://github.com/ihhub/fheroes2/files/11497460/AI.castle.poor.defense.01.zip)

**Comment by LeHerosInconnu** [comment]
Other saves for related behavior.

In fheroes2:

The hero AI Zam, with a substantial army, leaves a castle, thus leaving it without any real defense.
He is caught the next turn.
He would have done more damage if he had stayed in the castle and fought in it.
![AI move away castle 01](https://github.com/ihhub/fheroes2/assets/43583994/a29bb5e1-9e74-4be1-9ee7-57ec40858e0e)
![AI move away castle 02](https://github.com/ihhub/fheroes2/assets/43583994/5d0038dc-5512-448e-a797-d39577fd87c3)
![AI move away castle 03](https://github.com/ihhub/fheroes2/assets/43583994/4f1c79be-6d1f-40e0-8dec-64ecfbaa2d0e)

The two AI heroes move away from the castle.
They seem to be attracted by the boat like magnets.
However, only one of them will be able to board.
One of the two heroes could have defended the castle, with potentially more damage against the attacker.
![AI move away castle 04](https://github.com/ihhub/fheroes2/assets/43583994/c06375d7-a25e-4635-acfe-3cda475c04ae)
![AI move away castle 05](https://github.com/ihhub/fheroes2/assets/43583994/b01f2b0d-622c-4aa8-b44f-a1d88e494483)

Here are the save files (1.0.4 7171):
[AI move away castle 01.zip](https://github.com/ihhub/fheroes2/files/11507143/AI.move.away.castle.01.zip)

**Comment by drevoborod** [comment]
Maybe something changed, but it does not affect one of saved files: "AI move away castle 02". There is no difference between AI moves in 1.0.4 and 1.0.5. Is it how it supposed to be? @ihhub

**Comment by ihhub** [comment]
Hi @drevoborod , this is an issue which I am trying to fix right now. The problem is that all threats are calculated only at the start of a turn and also all threats are based on reachability of enemy heroes for castles. In this save an AI hero is "blocking" a way to player's hero so pathfinding fails to reach the castle through the AI heroes because he is too powerful.
