### ISSUE TITLE
The strongest allied hero attacks a neutral monster guarding nothing and loses its entire army

### ISSUE THREAD

**Issue by kitovyj** [ihhub/fheroes2#7194]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

The strong green hero(Trayan) attacks earth elementals and loses. The neutral guards nothing and there is no visible reward for this battle except experience. There are still many enemy castles and strong heroes on the map, so why take a risk? Also, enemy army evaluation function probably should be made more pessimistic - Zounds can be a lot!

### Save file

[New_Enemies_0178.zip](https://github.com/ihhub/fheroes2/files/11501659/New_Enemies_0178.zip)

**Comment by oleg-derevenetz** [comment]
> The neutral guards nothing and there is no visible reward for this battle except experience.

AI still can attack neutral monsters (even if they guard nothing) to clear the shortest path to some object or for the fog discovery.

**Comment by oleg-derevenetz** [comment]
In this case AI deliberately decided to go for the Elementals because of experience. But it overestimated its strength somewhat :)
