### ISSUE TITLE
Combat screen, interruption (freezing) of the vampire lord's animation during the attack in a pyramid

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#7197]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, there is an interruption (freezing) of the vampire lord's animation during the attack in a pyramid.

In fheroes2:
Speed: 8
Attacking the bone dragons.

https://github.com/ihhub/fheroes2/assets/43583994/609718ed-985f-4775-9ffd-50017614d64e

Speed: 1
At the beginning of the flight.

https://github.com/ihhub/fheroes2/assets/43583994/c750cf99-7965-40d1-8e61-3e039ce7153e

### Save file

Here is the save file:
[Before pyramid 01.zip](https://github.com/ihhub/fheroes2/files/11506635/Before.pyramid.01.zip)

### Additional info

Version 1.0.4 7171

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , is it still the case?

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , is it still the case?

I'm brokenly overloaded at the moment.
I'll test this after mid-December, ...or next year. :D

**Comment by ihhub** [comment]
I'm closing this issue as nobody can reproduce it and Pyramid has nothing special about battlefield animation. Feel free to open it back if you can reproduce it, @LeHerosInconnu .
