### ISSUE TITLE
Do not play the same sound at the same time during battle

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#7203]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

If during battle a hero casts a mass spell damaging multiple units with the same wince or death sounds we still play them but since we play these sounds simultaneously there is not difference (in reality it is like few microseconds) while hearing them. For example, I attacked Centaurs and casted Death Ripple spell:
```
20.05.2023 22:19:06: [DBG_GAME] `anonymous-namespace'::PlaySoundImp:  Try to play sound CNTRWNCE.82M
20.05.2023 22:19:06: [DBG_GAME] `anonymous-namespace'::LoadWAV:  CNTRWNCE.82M
20.05.2023 22:19:06: [DBG_GAME] `anonymous-namespace'::PlaySoundImp:  Try to play sound CNTRWNCE.82M
20.05.2023 22:19:06: [DBG_GAME] `anonymous-namespace'::PlaySoundImp:  Try to play sound CNTRWNCE.82M
20.05.2023 22:19:06: [DBG_GAME] `anonymous-namespace'::PlaySoundImp:  Try to play sound CNTRWNCE.82M
20.05.2023 22:19:06: [DBG_GAME] `anonymous-namespace'::PlaySoundImp:  Try to play sound CNTRWNCE.82M
```
But I can hear only one sound so the rest 4 are useless.

### Describe the possible solution

You can use Battle Only mode to simulate it.

**Comment by Districh-ru** [comment]
What about creature move sound?
At high battle speeds we have many simultaneous playbacks (with delays) of the same sound for each cell move.
Should we play only one sound, limit the number of simultaneous sounds or interrupt the previous sound when a new cell is reached and start playing it from the beginning for move to the next cell?

**Comment by ihhub** [comment]
Hi @Districh-ru for walking we do play the same sound but with different time offsets so we can hear many sounds at the same time. I don't have a strong opinion about this but limiting the number to say 3 sounds at one time would be a good approach.

**Comment by Branikolog** [comment]
@ihhub 

> Hi @Districh-ru for walking we do play the same sound but with different time offsets so we can hear many sounds at the same time. I don't have a strong opinion about this but limiting the number to say 3 sounds at one time would be a good approach.

Can we try to fade the earlier sound, after game starts playing 2nd/3rd simultaneous sound?

**Comment by Districh-ru** [comment]
> @ihhub
> 
> > Hi @Districh-ru for walking we do play the same sound but with different time offsets so we can hear many sounds at the same time. I don't have a strong opinion about this but limiting the number to say 3 sounds at one time would be a good approach.
> 
> Can we try to fade the earlier sound, after game starts playing 2nd/3rd simultaneous sound?

SDL mixer has such function: `setVolume( const int channelId, const int volumePercentage )`. So we are able to change the volume of previously started sound, but not smoothly: while unit is moving from one cell to other we are playing the move animation and it would be not good co complicate this logic with the sound fade... but we can try.

**Comment by ihhub** [comment]
Hi @Branikolog and @Districh-ru , let's address the situation with walking sounds separately as we have no proper solution at the moment for it. Fixing the initial problem described in this thread should be straightforward and agreeable for everyone :)

**Comment by Districh-ru** [comment]
I'll address the issue later. And there are some questions:
- if we strike 1 Centaur the the sound volume is normal, and if we strike more than 1 and play only one sound should it be louder (as many Centaurs are wincing)?
- if we strike many (different) creatures should we reduce the volume of each wince to avoid sound overload?
