### ISSUE TITLE
Tooltips on adventure map, like in larger editions of HOMM

### ISSUE THREAD

**Issue by KOLANICH** [ihhub/fheroes2#7211]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Later versions of HOMM have small tooltips that are shown via just hovering an object on an adventure map with a mouse pointer. It'd be nice to have it here too.

**Comment by oleg-derevenetz** [comment]
I really don't think that we need to clutter the UI by these tooltips that OG doesn't have and which users of the original game are not used to. Also these tooltips are absolutely incompatible with touch screen devices (unlike the original behavior with the right mouse button).

**Comment by KOLANICH** [comment]
>Also these tooltips are absolutely incompatible with touch screen devices (unlike the original behavior with the right mouse button).

Could be disableable. Anyway, I guess alt-clicking is a faster way than to wait for a tooltip.
