### ISSUE TITLE
Game settings should be saved to file

### ISSUE THREAD

**Issue by idshibanov** [ihhub/fheroes2#723]
Ideally we should save the settings as soon as they are updated and/or settings dialog is closed. fheroes2.cfg update on game exit might work too. It is annoying to go into .cfg file and change it manually when we have a beautiful GUI to do it.

**Comment by ihhub** [comment]
Fixed long time ago.

**Comment by AlexFolland** [comment]
How long ago?  This doesn't seem to be the case today.

**Comment by ihhub** [comment]
fheroes2.cfg always saves when user makes changes. The same applies to experimental settings window in the main menu.

**Comment by AlexFolland** [comment]
I tested this just now by opening the game, changing my resolution, closing the game, and reopening it.  The resolution was back to the original resolution.  So, it doesn't seem to be saving the cfg file still, at least with resolution changes.

**Comment by ihhub** [comment]
@AlexFolland what version of **fheroes2** are you using? **0.8.2**?

**Comment by AlexFolland** [comment]
Yes, 0.8.2.

**Comment by ihhub** [comment]
What OS are you using?

**Comment by AlexFolland** [comment]
I'm running Manjaro 20.1.1 with the Linux 5.8.11-1 kernel.  To install, I extracted the 0.8.2 release from github because I had the issue that BujuArena posted in the fheroes2-git AUR package on the package page comments: https://aur.archlinux.org/packages/fheroes2-git

**Comment by ihhub** [comment]
I haven't used such OS but I assume that this configuration file (fheroes2.cfg) is not being stored within the folder of the application. Your OS **might** save new files in totally different location leading to a fact that for the second run the application can't find the file.

**Comment by ihhub** [comment]
To prove my theory please search this file at the whole hard drive and see where the file is being saved.

**Comment by AlexFolland** [comment]
There's a config file at ```/home/alex/.fheroes2/fheroes2.cfg``` which is where I set the resolution and fheroes2 used the resolution I set there, so fheroes2 is reading that.  If it's reading that, why wouldn't it write to the same file?  That behavior doesn't seem sane.

**Comment by ihhub** [comment]
@AlexFolland , could you try these steps:
- rename `.fheroes2` into `fheroes2` without a dot
- run the application in admin mode (sudo)
- remove both files and run the application to see where exactly a new file is created
- if you run through a command line please `cd` to fheroes2 directory first and execute the application withing the directory like:
```
cd /home/alex/.fheroes2
./fheroes2
```
