### ISSUE TITLE
Missing big objects on battlefield

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#7236]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

I noticed that there are cases when no objects are present on the battlefield and it is not possible to move your troops there:
![image](https://github.com/ihhub/fheroes2/assets/19829520/08e797a3-5130-4dca-a8ce-533fa6eaad45)

In the attached save attack the Lord Corlagon and observe the battlefield.

I believe this is a regression from #6911

### Save file

[Good_9_0005.zip](https://github.com/ihhub/fheroes2/files/11581615/Good_9_0005.zip)

**Comment by Districh-ru** [comment]
It might be a regression from #7208. I'll check it.
