### ISSUE TITLE
Missing glowing effects of units in UI

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#724]
Gorgeous glowing effects of some units, recently being added by our hardworking team, can be seen not only on a battlefield, comparing to the OG. But in army view, recruit window, status window and world map. And even spells in spellbook and mage guild.

**Comment by idshibanov** [comment]
This should be handled with global animation logic after rendering engine update coming in 0.9. No point in fixing each part of the UI individually.
