### ISSUE TITLE
Игра падает

### ISSUE THREAD

**Issue by toperx** [ihhub/fheroes2#7245]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

/home/toper/Games/HOMM2/fheroes2                                                                                                                                                                             ──(Вс,мая28)─┘
fheroes2 engine, version: 1.0.4
28.05.2023 17:35:52: [ERROR]    _createRenderer:  Failed to set a linear scale hint for rendering.
----------
Main Menu

Press N to choose New Game.
Press L to choose Load previously saved game.
Press H to show High Scores.
Press C to show Credits.
Press T to open Game Settings.
Press Q or ESCAPE to Quit the game.
----------
----------
Load Game

Press S to choose Standard Game.
Press C to choose Campaign Game.
Press M to show Multi-Player Game.
Press ESCAPE to go back to Main Menu.
----------
----------
�������� ���

��������� ���� ����� ��� ����� ������.
�� ������������� ������ ��������� ���?
Press RETURN to choose YES.
Press ESCAPE to choose NO.
----------
fheroes2: ../fheroes2/maps/maps_tiles_helper.cpp:834: void Maps::updateDwellingPopulationOnTile(Maps::Tiles&, bool): Assertion `count > 0' failed.
[1]    11188 IOT instruction (core dumped)  /home/toper/Games/HOMM2/fheroes2

### Save file

[AUTOSAVE.zip](https://github.com/ihhub/fheroes2/files/11583896/AUTOSAVE.zip)
[SURFTURF.MX2.zip](https://github.com/ihhub/fheroes2/files/11583902/SURFTURF.MX2.zip)

### Additional info

Приложил сейв и карту.

**Comment by KOLANICH** [comment]
@toperx, GitHub is an international website, please don't write in Russian here.
