### ISSUE TITLE
Neutral creatures always attack hero

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#726]
Neutral creatures always attack hero. Except those, who appeared after special week or those, who want join hero's army.

**Comment by idshibanov** [comment]
Last time I checked join logic was on point, so you have to elaborate a little bit more. Monsters flee if hero is 5 times as strong, and you have a small random chance for a free join if your army is 2 times stronger.

What behavior are you expecting? What's missing?

**Comment by Branikolog** [comment]
At the map I've created I have 3k of titans and when I attack 50 of the same unit in a world - they don't run. 
The same scenario in the OG they run.
