### ISSUE TITLE
Wrong direction of turret's arrow

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#728]
While being launched, upper turret's arrow animated in a strange manner.
![Arrow](https://user-images.githubusercontent.com/55348946/83809420-133dc100-a6bf-11ea-97c7-756f370488d0.jpg)

**Comment by idshibanov** [comment]
Interesting, was it shooting at the skeleton? I'll take a look..

**Comment by Branikolog** [comment]
Yes. Only the upper turret and only shooting  at the skeleton.
