### ISSUE TITLE
Opening dialogs from battle options dialog causes short flicker

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#7281]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

I believe there is some unnecessary redrawing happening when opening either the audio options or hot keys dialog from the battle options as there is a short moment where you can view the background changing before the new dialog is opened.

I haven't had time to investigate exactly what happens but it was only recently I noticed it. I believe it is even more noticeable on slower devices.

Play the video slowly to hopefully see it. It's somewhat more noticable when opening the audio settings. Also the video is reduced to 30 fps or lost some frames so I see that it isn't as easy to spot on it.

https://github.com/ihhub/fheroes2/assets/12501091/e567da77-acea-47d3-a507-6b97ad9f0641

### Save file

Just open the battle only mode.

**Comment by ihhub** [comment]
This actually could happen because of color cycling. I suspected this issue for a very long time. The idea here is to switch off the color cycling for this operation. This is applicable for many other places.

**Comment by Districh-ru** [comment]
Hi @zenseii and @ihhub.
I saw such things in other places and it happens (on my hardware) only if I set `cursor soft rendering = on`.
As all our dialogs use **fheroes2::ImageRestorer** at every dialog close it restores the screen image before the dialog open. And if we use software cursor the display is updated by mouse cursor move and if the engine did not finish render of the new frame (with the new dialog) we can see a restored frame (or part of it) without opened dialog:
The previous ROI was button, the new if mouse cursor, the restorer has restored the screen and the display was updated in the (previousRoi^cursorRoi) before the new dialog was rendered.

![изображение](https://github.com/ihhub/fheroes2/assets/113276641/bebc2627-06e8-4d7d-9a56-9736a4862d45) ![изображение](https://github.com/ihhub/fheroes2/assets/113276641/d0ef7f00-9616-4b87-b4ab-8b151289d282) ![изображение](https://github.com/ihhub/fheroes2/assets/113276641/b94565db-1603-4897-ac68-dac4124f17be)

This bug happens in many places where the `ImageRestorer` when the software cursor rendering is turned on.
The best way is to somehow hold the screen redraw for software cursor in the interval  between restoring an image and rendering a new frame by the engine...
