### ISSUE TITLE
Stop a moving AI hero if a new action object has been revealed during movement

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#7290]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

At the moment we update object cache while unveiling fog during AI hero movement. However, there is a chance that the newly uncovered object could be much more useful that the current set of available objects to visit.

### Describe the possible solution

We need to modify functions to unveil fog to indicate that the moving hero has to stop to re-evaluate the priority upon discovering a new object. This should improve the efficiency of map exploration and also we should be able to update priorities for castles and heroes in case of finding a new enemy hero or castle.

**Comment by LeHerosInconnu** [comment]
Yes, this could possibly also be applied to heroes led by a human player. :)
I take this opportunity to gather a list of related issues and discussions.

Related issues:

The movement of the human player's heroes along a path should also be stopped when a point of interest is revealed under the fog of war:
https://github.com/ihhub/fheroes2/issues/1219

The hero's predefined path should be updated when the fog of war is removed:
https://github.com/ihhub/fheroes2/issues/6109

The path taken by the heroes should be improved to remove as much of the fog of war as possible (also a great benefit for the AI):
https://github.com/ihhub/fheroes2/issues/1217
In the ocean, the AI zig-zags:
https://github.com/ihhub/fheroes2/issues/7320

The hero's path should be improved when the fog of war can be removed, thus avoiding a longer detour:
https://github.com/ihhub/fheroes2/issues/1215

The squares of interactive locations are taken into account and used for the hero's path to reduce the path and therefore the movement points used:
https://github.com/ihhub/fheroes2/issues/1214

Related discussions:

Adventure map, when a hero moves by revealing the adventure map, the hero's path should be adjusted to take into account the revealed terrain:
https://github.com/ihhub/fheroes2/discussions/4654

Adventure map, optimization of the hero's predefined path:
https://github.com/ihhub/fheroes2/discussions/6106

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , at the current stage the AI is very dumb while a player can interrupt hero's movement any time. So adding such a change at least makes the AI on the same level as a human player.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , at the current stage the AI is very dumb while a player can interrupt hero's movement any time. So adding such a change at least makes the AI on the same level as a human player.

Yes, I understand.
In the case of the human player, it would be a comfort to play.
Instead of the player being tense on his mouse, trying to see what appears in the hero's field of view, and clicking too late when it does. :)
He could activate the option and enjoy the game without stress.
