### ISSUE TITLE
Make credits non-stretchable

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#7303]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Credits are now stretched according to a chosen resolution and it doesn't look good at all for widescreen resolutions:
![image](https://github.com/ihhub/fheroes2/assets/19829520/184f2422-d78a-4952-9ba2-6f89fd82f0b7)

### Describe the possible solution

Render the same background as we do for the Main Menu where we might probably add some action items in the future.

**Comment by Districh-ru** [comment]
Also we are doing `fheroes2::Resize()` before every render in the loop. We should use Resize only once for each credits page.
