### ISSUE TITLE
Exit button in well window not well positioned Bulgarian text

### ISSUE THREAD

**Issue by Effektus** [ihhub/fheroes2#7312]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Exit button in well window not well positioned Bulgarian text

### Save file

![image](https://github.com/ihhub/fheroes2/assets/12934196/b1043373-8c7d-4c83-94b3-1f852df28bb4)

**Comment by ihhub** [comment]
Hi @Effektus , as I see the text is longer than the acceptable text length on the button. Unless we regenerate a new button as an alternative solution is to name the button as OK.

**Comment by Effektus** [comment]
Great Thanks
