### ISSUE TITLE
Adventure map, Stables, right-click information window for stables related to the hero is not displayed on the left side of the stables

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#7318]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the right-click information window for stables related to the hero is not displayed on the left side of the stables.

In fheroes2:

https://github.com/ihhub/fheroes2/assets/43583994/afcb189b-c807-4340-9320-1451e2131879

### Save file

Here is the save file (1.0.5 7020):
[Stables info 01.zip](https://github.com/ihhub/fheroes2/files/11768442/Stables.info.01.zip)

**Comment by oleg-derevenetz** [comment]
There is no valid information in the `DOMINION.MX2` file regarding the object on this tile. The same issue happens in the original game for the same tile:

https://github.com/ihhub/fheroes2/assets/32623900/26ad309d-de40-4ef8-9588-68b660b352f6

But in this case everything works properly both in OG and fheroes2:

https://github.com/ihhub/fheroes2/assets/32623900/abce010a-1ed8-4350-928f-25147cd3bd6b

I believe it's the map editor issue and not the engine issue.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> There is no valid information in the `DOMINION.MX2` file regarding the object on this tile. The same issue happens in the original game for the same tile:
> 
> https://github.com/ihhub/fheroes2/assets/32623900/26ad309d-de40-4ef8-9588-68b660b352f6
> 
> But in this case everything works properly both in OG and fheroes2:
> 
> https://github.com/ihhub/fheroes2/assets/32623900/abce010a-1ed8-4350-928f-25147cd3bd6b
> 
> I believe it's the OG map editor issue and not the engine issue.

Could this type of error be corrected with the future fheroes2 scenario editor?
By loading a scenario from the original game and saving it from the fheroes2 scenario editor.

**Comment by oleg-derevenetz** [comment]
> Could this type of error be corrected with the future fheroes2 scenario editor?
By loading a scenario from the original game and saving it from the fheroes2 scenario editor.

I believe that there will be need to replace the object, i.e. to remove the original Stables object and place a new Stables object instead, but that's just a guess for now.

**Comment by ihhub** [comment]
I am closing this issue as this is a problem of the original Editor or most likely some hacky hex editing of the map.

The upcoming Editor will not allow to do such tricks.
