### ISSUE TITLE
Castle walls don't create shooting penalty for raged attacks

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#732]
While attacking over castle walls troops should have penalty (arrow broken).
![Penaly](https://user-images.githubusercontent.com/55348946/83815352-ab8c7380-a6c8-11ea-8199-0c0d9add8675.jpg)

**Comment by idshibanov** [comment]
@Branikolog Does your hero has Archery skill? Maybe Golden bow artifact?

**Comment by Branikolog** [comment]
> @Branikolog Does your hero has Archery skill? Maybe Golden bow artifact?

Oops. Didn't knew Archery has such effect. Thank you for your correction!
