### ISSUE TITLE
Virtual keyboard shows false symbols after blinking cursor

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#7325]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

![Screenshot_2023-06-17-15-07-24-80_591ba0aa0c25b75f4ad8b373a1ebed7f](https://github.com/ihhub/fheroes2/assets/55348946/8eb59d5d-3922-4bac-9f27-4da5efe20ee0)

There're a few random symbols each time keyboard was initiated on Android device.

### Save file

None.

**Comment by oleg-derevenetz** [comment]
Hi @Districh-ru

https://github.com/ihhub/fheroes2/blob/31742e29b6f80756f268d1431b94deef16889721/src/fheroes2/gui/ui_keyboard.cpp#L233

This place looks suspicious. `_cursor` is `char`, it's not a null-terminated string, and you cannot just take an address of this `char` and treat it like a null-terminated string.

**Comment by Districh-ru** [comment]
> Hi @Districh-ru
> 
> https://github.com/ihhub/fheroes2/blob/31742e29b6f80756f268d1431b94deef16889721/src/fheroes2/gui/ui_keyboard.cpp#L233
> 
> This place looks suspicious. `_cursor` is just a single `char`, it's not a null-terminated string, and you cannot just take an address of this `char` and treat it like a pointer to a null-terminated string.

Hi @oleg-derevenetz, thanks for pointing to the root of the problem.
