### ISSUE TITLE
Border interface for View World is missing when using multiplier-based scaled resolutions

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#7328]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

When using any resolution that is multiplied by a factor - 1.5x, 2.0x, the interface of the right side panel and the bottom part are missing:
![image](https://github.com/ihhub/fheroes2/assets/12501091/4064abff-b73c-4c56-bcfe-aa130ac12f75)

This is noticed on Android too where it has 1.5x by default.

### Save file

No save file needed.

**Comment by oleg-derevenetz** [comment]
Regression after introduction of the fade effect.
