### ISSUE TITLE
Kingdom overview window, castle theme continues after visiting any town

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#7329]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

After visiting castle through kingdom overview window castle music continues playing.

https://github.com/ihhub/fheroes2/assets/55348946/3be0132b-c9bd-4b46-87b1-f7c18e6683e2

### Save file

None.

**Comment by oleg-derevenetz** [comment]
It's a regression, everything works correctly with 1.0.4. I will try to find out later what exactly it is related with.

**Comment by oleg-derevenetz** [comment]
Regression after #7256
