### ISSUE TITLE
Short flicker of the screen after closing last dialog of first time run of the engine

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#7338]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

After closing the dialog with "Please Remember" there is a short black flicker of the screen.

Around the 3 second mark:

https://github.com/ihhub/fheroes2/assets/12501091/e603a89c-7e55-4683-b075-e5101ba7b4bf

I've experienced this on Android too.

### Save file

Just make sure you set the engine to start for the first time in fheroes2.cfg.

**Comment by Districh-ru** [comment]
This is a regression after #7062
