### ISSUE TITLE
FHeroes2 Crash when Discord/OBS try to stream that specific window

### ISSUE THREAD

**Issue by Yslohr** [ihhub/fheroes2#7357]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

When trying to stream FHeroes 2 whether on windowed or fullscreen mode the game crashes immidiately.
To reproduce this, simply install GOG HOMM2 Gold, download the 1.0.5 "fheroes2_windows_x64_SDL2_installer.exe" file and run it and extract resources from the original game, open up obs game capture and try to capture a specific window, the game will crash.
Link to the video where I demonstrate the same issue with discord:
https://youtu.be/LV_Z_hnUT4A
Please reply to this with any needed additional information.

### Save file

Save file isn't needed this works without even entering a campaign or scenario.

### Additional info

Useless log file.
[fheroes2.log](https://github.com/ihhub/fheroes2/files/11860622/fheroes2.log)
My config file: https://gist.github.com/Yslohr/980167270f04fe940f0ba9a33bd53bd9

**Comment by ihhub** [comment]
Hi @Yslohr , I tested this scenario on my machine (Win 10) and I did not observe the same behavior.
