### ISSUE TITLE
Some "Stone Liths" don't work on last git version

### ISSUE THREAD

**Issue by vovansrnd** [ihhub/fheroes2#7387]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

Some "Stone Liths" don't work on last git version

### Save file

 [saves](url https://disk.yandex.ru/d/kVVtFvq2vKaDQw)

**Comment by oleg-derevenetz** [comment]
Hi @vovansrnd I haven't taken a look at your save file yet, but please note that Stone Liths will not work if another exit is occupied by a hero. Weak AI-controlled heroes sometimes cannot exit the Stone Liths after teleportation because of strong guard nearby.

**Comment by vovansrnd** [comment]
> Hi @vovansrnd I haven't taken a look at your save file yet, but please note that Stone Liths will not work if another exit[s] is/are occupied by a hero. Weak AI-controlled heroes sometimes cannot exit the Stone Liths after teleportation because of strong guard nearby.

No, this is not the case. Just part of the Stone Liths is inactive to enter

**Comment by ihhub** [comment]
I assume it might be related to AI changes where heroes are temporary removed from the map during pathfinding but this is just a guess.

**Comment by ihhub** [comment]
Object type is set to NONE (0) for these tiles.

**Comment by ihhub** [comment]
Most likely the problem lies in `void Maps::Tiles::SetHeroes( Heroes * hero )` function and specifically in line 569 **setAsEmpty();** which shouldn't be called at all but somehow it does.

**Comment by ihhub** [comment]
It happens because of
```cpp
void Heroes::Move2Dest( const int32_t dstIndex )
{
    const int32_t currentIndex = GetIndex();

    if ( dstIndex != currentIndex ) {
        world.GetTiles( currentIndex ).SetHeroes( nullptr );
        SetIndex( dstIndex );
        Scout( dstIndex );
        world.GetTiles( dstIndex ).SetHeroes( this );
    }
}
```
code where we don't set a hero at any tile.
