### ISSUE TITLE
Random town and castle are drawn incorrectly on World Map

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#742]
When a map has multiple castles very close to each other you could such a strange effect (check Sorceress castle):
![image](https://user-images.githubusercontent.com/19829520/83938352-0e375980-a806-11ea-9644-7d8c6c576703.png)

**Comment by idshibanov** [comment]
Can't reproduce anymore. Do you still have save/map?

**Comment by ihhub** [comment]
Hi @idshibanov , please try this map.
[Map_0003.zip](https://github.com/ihhub/fheroes2/files/4910209/Map_0003.zip)

**Comment by idshibanov** [comment]
It seems to be an issue with Random castle initialization when map is loading. Wrong tile index set on TileAddon level 2.

**Comment by idshibanov** [comment]
If you know how to trigger it and overlap random castles in can lead to very bizarre results. Shadows are wrong too.
![image](https://user-images.githubusercontent.com/1373638/87362425-9fec6200-c53c-11ea-9219-b8a0b386d97d.png)
