### ISSUE TITLE
AI in debug (automated) mode can't close "player vanquished" dialogue

### ISSUE THREAD

**Issue by drevoborod** [ihhub/fheroes2#7428]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

**Steps**
1. Load provided savegame in development build.
2. Give control to the AI (by pressing F8).
3. Wait until orange player is eliminated.

**Expected result**
Corresponding dialogue window is closed automatically.

**Actual result**
The dialogue remains open until a human presses OK.
![изображение](https://github.com/ihhub/fheroes2/assets/10282847/cd5b41c9-0b80-4310-8040-f1d99afc5491)

### Save file

[AUTOSAVE_182.zip](https://github.com/ihhub/fheroes2/files/12088029/AUTOSAVE_182.zip)

**Comment by oleg-derevenetz** [comment]
> The dialogue remains open until a human presses OK.

And this is a good thing because I'm (as a developer) want to be noticed when some of players has been eliminated.

**Comment by ihhub** [comment]
Closing this issue as this is only for debug mode and for some developers it might be useful.
