### ISSUE TITLE
Dying unit is being drawn under neighboring

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#743]
When any unit dies standing in front of another unit, its animation is drawn under another unit.
![Dying](https://user-images.githubusercontent.com/55348946/83939456-e506d100-a7e5-11ea-9554-23055d656d76.jpg)

**Comment by idshibanov** [comment]
I believe this should be fixed by #1047. Dying unit was placed in the graveyard too early and drawn as a part of terrain. Will have to test it though
