### ISSUE TITLE
Castle screen, EXIT button has wrong background in a pressed state

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#7461]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

When pressing EXIT button we can see brown background line above it.

![image](https://github.com/ihhub/fheroes2/assets/55348946/59cad71a-9436-49c8-9b54-a0b6e29bab2f)

### Save file

None.

**Comment by Districh-ru** [comment]
And also a bug in Heroes meeting:
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/c9d1ed4d-492b-4f4a-b75a-e60e0285c66f)

We need to separate these buttons: not for the STONEBAK background and other - for black background

**Comment by Districh-ru** [comment]
Hi, @zenseii.
Could you please try fix this issue when you have time as you have good experience with GUI buttons.

**Comment by Districh-ru** [comment]
> Hi, @Districh-ru. I'm busy the next 6-7 days and most of the time won't have a PC available, but I can look at it after that unless someone else wants to do it.
> 
> As for the solution I'm I'll try to think of the best approach.

Thanks!
Take your time. :)
