### ISSUE TITLE
Battle screen, low morale triggered prevents the next slower creature from acting in combat

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#7484]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

https://github.com/ihhub/fheroes2/assets/55348946/b718d363-de1d-4cda-8702-42814f6849d6

Grand Elves have highest speed and have the first attack each turn.
After low morale triggered ballista shoots and the turn is passed to pikemen, who has average speed. But there are also troops with average speed in the left army, who should act instead of elves.

OG:

https://github.com/ihhub/fheroes2/assets/55348946/df660bd6-9425-4d29-ac29-59d323984d76

### Save file

[No_Name_86_0001.zip](https://github.com/ihhub/fheroes2/files/12195266/No_Name_86_0001.zip)

**Comment by Branikolog** [comment]
@oleg-derevenetz 

Let me explain as I understand it.

In this particular case the last creature of previous turn doesn't matter. We check for the fastest creature on the new round. It is Grand elf. But Elf missed the turn due to low morale, so the next creature with the same speed of red army should act. But if there's no "very fast" creatures, then "fast" creatures should take its turn. If no "fast" creatures - then "average".
This particular example is valid only for the case, when blue player has no "very fast" and "fast" creatures.
If both players have "very fast" creatures, then on a new round first turn belongs to the side, opposite from the one, who made the last action on the previous turn. 
In a case, first creature of the side missed turn due to low morale, then another creature of "very fast" speed should act. If the side has no more "very fast" creatures - then the turn is passed to opposite player, who has "very fast" creature.
If opposite player has no "very fast" creatures, then the turn should be left for "fast" creatures of the red player.

And here's more complex case I've experienced in the OG:

https://github.com/ihhub/fheroes2/assets/55348946/2a2d1ab6-e517-4138-9120-d9b298bd95b7

New round starts:
Grand elves missed because of low morale. Red player has no more "very fast" and even no "fast" creatures - so the turn is passed to blue player, who has "fast" pikemen. If the Red had "fast" creature, then this creature would get an ability to act.
But blue Veteran Pikemen also lost their turn because of low morale. Then the "average" speed troops are going to act.

I think the main idea here is that once one side received an ability to act, it has a privilege in a case low morale triggers.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog

> In this particular case the last creature of previous turn doesn't matter. We check for the only fastest creature on the new round.

That's not how it works in the original game. Consider:

https://github.com/ihhub/fheroes2/assets/32623900/be2b1e3c-e966-410a-9614-21e45a34a8d8

In this video the last unit on the first turn was the blue Zombie, so the green Zombie has the turn when the Elves panic on the next turn, not the blue Zombie - as-if Elves completely absent from the battlefield (like I described in my previous comment).

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Hmm... I need to do more deep tests then.
Sorry for my mistakes.

**Comment by oleg-derevenetz** [comment]
> Hmm... I need to do more deep tests then.

The color of the unit that was the last on the previous turn always matters on a new turn. A panicked unit is just ignored as-if there is no such a unit at all (at least on this turn).

**Comment by Branikolog** [comment]
@oleg-derevenetz 
You're completely right.
Sorry for bothering you with this issue. The logic here was not really apparent for me.
Thanks for explanation!
