### ISSUE TITLE
AI hero sits in a castle forever despite having the stongest army

### ISSUE THREAD

**Issue by kitovyj** [ihhub/fheroes2#7488]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

The green hero sits in the castle for many turns. I noticed that sometimes heros with strong armies enter "defend castle" mode and that makes them absolutely passive. That is something that didn't exist in the previous versions. I think 'defend castle' regime is not well balanced. In this case the paralyzed green hero can wipe out (I bet) all the enemies in 2 weeks, instead of sitting in the castle.

### Save file

[Uploading vh1_0016.savc…]()
[save.zip](https://github.com/ihhub/fheroes2/files/12202589/save.zip)

**Comment by oleg-derevenetz** [comment]
> I think 'defend castle' regime is not well balanced.

Maybe. The problem is that if, for example, there are two castles not far from each other, each of them has a hero, and neither hero feels enough superiority to defeat the other with a sufficiently high probability, then they will sit in their castles until the balance of their forces somehow changes, because each of them fears to lose his castle, but believes that most likely he will not be able to defeat the other if he just attacks him.

**Comment by kitovyj** [comment]
> > I think 'defend castle' regime is not well balanced.
> 
> Maybe. The problem is that if, for example, there are two castles not far from each other, each of them has a hero, and neither hero feels enough superiority to defeat the other with a sufficiently high probability, then they will sit in their castles until the balance of their forces somehow changes, because each of them fears to lose his castle, but he believes that, most likely, he will not be able to defeat another hero if he just attacks him.

Yes, I see the point. In that particular case the green hero being equpped with 11 titans can easily (I think) wipeout the hero in the neighbouring town. Despite that both are sitting still for 15+ turns. Maybe, hero strength evaluation function here underestimates the strength of titans or overestimates the significance of hero level. 

One more point: green hero here is outnumbered in terms of the the number of the castles he and the opposing party has. In such case passive strategy is almost always a bad choice. Maybe such "having less castles" condition should affect the decision based on danger evaluation. The green guy here should risk and he has a chance.

**Comment by kitovyj** [comment]
[New_Enemies_0087stillsitting.zip](https://github.com/ihhub/fheroes2/files/12233422/New_Enemies_0087stillsitting.zip)
[New_Enemies_0107sits.zip](https://github.com/ihhub/fheroes2/files/12233430/New_Enemies_0107sits.zip)
[New_Enemies_0113nomoves.zip](https://github.com/ihhub/fheroes2/files/12233435/New_Enemies_0113nomoves.zip)

Here is the continuation of the situation in the same game. "still sitting" - the green still sits in the same castle(lower right corner), despite the situation for him is even better now. Now two red heroes in the neigbouring castles are paralyzed by the green guy, and the green is paralized by them. Lets consider that green can easily beat them both, and the red hero in the town has,in principle, nothing to defend there.

"sits" - After some of my help, the green(Ruby) started moving and took the castle in the lower left corner. Shortly after that she got in a stalemate with the red hero hero in the neighbouring castle again. They paralyze each other and will be sitting there(two strongest armies!) till the end of the game.

"no moves" - The climax! all AI heroes paralyzed each other - AI makes no moves at least for several rounds.

**Comment by LeHerosInconnu** [comment]
Here's a save file showing the same case (end the tour several times).
I did not test with PR #7500.

In fheroes2:

![AI heroes stay in castle cercles rouges 01](https://github.com/ihhub/fheroes2/assets/43583994/18b169ff-2ccc-4fae-a8e4-2885a278fdf7)

Here is the save file (1.0.6 7494):
[AI heroes stay in castle 01.zip](https://github.com/ihhub/fheroes2/files/12269767/AI.heroes.stay.in.castle.01.zip)

**Comment by kitovyj** [comment]
It seems that in the first attached game of #7488 the green hero demonstrates another wierd behaviour now. Instead of sitting in the castle still, he starts moving towards the enemy sitting in the castle nearby (the threat that forced him sitting still before). But in the next turn the green returns back instead of attacking the enemy, repeating that evolution many times.
