### ISSUE TITLE
Hero screen, Necromancy icon name alignment

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#7491]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

![ezgif com-resize (1)](https://github.com/ihhub/fheroes2/assets/55348946/156e80ec-57c1-4a0c-a6d3-916158bd07b0)

The skill name should be shifted for 1 px to the left.

### Save file

None.

**Comment by ihhub** [comment]
Nothing we can do about it as the rendering of skill names is the same. English is not the only language which requires special handling for some skill names. Moreover, the font has shadow which is exactly 1 pixel on the left. If we shift the name then the shadow will appear on the golden frame.

Therefore, I am closing this issue as we aren't going to fix it.

**Comment by Branikolog** [comment]
Hi, @ihhub !

In the original game the skill name is positioned the same way I was mentioned in the issue. 

![image](https://github.com/ihhub/fheroes2/assets/55348946/bd071cda-264e-4f5c-958e-0b79792e807c)

I think cutting shadow for such cases is a nice visual improvement of the game UI.
Even without fixing shadow of the first letter it looks better than the current implementation of fheroes2.

**Comment by ihhub** [comment]
Fixed in #8058 .

**Comment by a1exsh** [comment]
Hm, seems to be missing the handling in the pop-up dialog when checking the skill:
![Screenshot from 2024-01-04 15-11-22](https://github.com/ihhub/fheroes2/assets/489601/c79e243a-cd0c-4d56-8560-1336e89cea61)

The hero details itself is fixed:
![Screenshot from 2024-01-04 15-15-08](https://github.com/ihhub/fheroes2/assets/489601/2f419754-72b9-4343-9d2c-8eac09cae7d1)

**Comment by JasonQorbin** [comment]
Hi. That's correct. We said that the pop-up would be fixed in a separate PR. Will try to have a look at this over the weekend.
