### ISSUE TITLE
City screen button label misalignment in german language version

### ISSUE THREAD

**Issue by kitovyj** [ihhub/fheroes2#7496]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

City screen "Beend" button label misalignment in german language version. 4K screen, zoomed window.
![beend](https://github.com/ihhub/fheroes2/assets/15792725/d1ff7a1e-7a95-4157-ac53-ae86d72c80eb)

### Save file

no need

**Comment by Laserlicht** [comment]
Maybe `VERL.` as abbreviation for `VERLASSEN` (`leave`)?

**Comment by kitovyj** [comment]
@zenseii I think Laserlicht can be the expert here - I'm not a native speaker, just studying german, that's I'm using german version. However, if the original game really displays exactly "BEEND." then somehow they solved the issue, maybe by applying some manual tweaks in the rendering code.

**Comment by Laserlicht** [comment]
My mistake... I just checked again. In german resources it is called `ENDE`.

Will change... in #7495

**Comment by Laserlicht** [comment]
> Is it ENDE for all EXIT buttons or just the ones in the castle, @Laserlicht ?

Just the one.

Main menu is in original translation:
![grafik](https://github.com/ihhub/fheroes2/assets/13953785/7485462b-a495-4baa-83ca-e2ae843334a2)
