### ISSUE TITLE
Dragons decided not to act : a bug or a feature? (definitely not optimal)

### ISSUE THREAD

**Issue by kitovyj** [ihhub/fheroes2#7498]
### Your question

Please see the video and use the saved game to reproduce - most of times the situation reproduces if the same moves are performed.

https://youtu.be/YjkZwahUF8g

### Additional info

[New_Enemies_0064dragonstay.zip](https://github.com/ihhub/fheroes2/files/12233955/New_Enemies_0064dragonstay.zip)

**Comment by oleg-derevenetz** [comment]
@zenseii Black Dragons decided to skip the turn (according to the battle log), but why exactly - is a separate interesting question.

**Comment by oleg-derevenetz** [comment]
That's because "defensive tactic" for that turn was chosen, and this tactic involves attacking enemy units only inside the castle walls (there is none) or covering "friendly" shooters (there is none as well). The existing logic does not provide for any other actions for this tactic.

**Comment by kitovyj** [comment]
> That's because "defensive tactic" for that turn was chosen, and this tactic involves attacking enemy units only inside the castle walls (there is none) or covering "friendly" shooters (there is none as well). The existing logic does not provide for any other actions for this tactic.

[New_Enemies_0036_PHOENDA.zip](https://github.com/ihhub/fheroes2/files/12236648/New_Enemies_0036_PHOENDA.zip)

https://github.com/ihhub/fheroes2/assets/15792725/51e250b4-eea6-41cf-9f8c-51d756005053

Here is another example, different game but similar situation, this time with phoenixes. If there is no "block enemy shooters" logic in the battle AI then it looks more like a bug related to caste defense and maybe large creatures.
