### ISSUE TITLE
Implement report issue and attach save file from Android Helper tool

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#7501]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Right now a user that experiences a problem while playing on Android and wants to attach the save file has to connect the phone to a PC and transfer the save there, and then make the issue from their PC.

I realize this might be problematic because a user would have to have a Github account to actually upload and create an issue.

In addition the privacy policy would have to be updated to reflect how the app would allow users to share save data.

EDIT: We made it possible to extract saves from the Android save folder using the fh2 helper app. There is still no way to attach save files from just the phone so it will have to be transfered to a PC for uploading to github.

### Describe the possible solution

Make save sharing from Android more convenient.

**Comment by ihhub** [comment]
Hi @zenseii , it is doable but I believe we need to have more information how we could implement this. I suggest to focus only on **fh2Toolset** as this is the application which was written for Android devices only. Adding a functionality such as sharing selected save files could be what users want.

**Comment by oleg-derevenetz** [comment]
> I realize this might be problematic because a user would have to have a Github account to actually upload and create an issue.

The user will still need a GitHub account to create an issue here, whether it will happen automatically or manually.

**Comment by oleg-derevenetz** [comment]
> There is still no way to attach save files from just the phone

There is a way - in the GitHub web UI (in its mobile form) you should click on the text edit field and then press the "attach file" button in the button row at the top of the text edit field (with the icon representing some sort of a scenery with a mountain and the sun) and then choose the File app to select the ZIP archive to upload and attach.

**Comment by oleg-derevenetz** [comment]
![fheroes2_save_files.zip](https://github.com/ihhub/fheroes2/files/12389325/fheroes2_save_files.zip)

I just attached this ZIP file via GitHub mobile app :) Sony Xperia with Android 13.
