### ISSUE TITLE
The AI creates path through pyramid, attacks it and dies.

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#7503]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

The AI green player avoids the blue player by creating path through the pyramid and attacks it, but it is obviously too weak and dies.

It has a decent enough army:
![image](https://github.com/ihhub/fheroes2/assets/12501091/3563b624-659f-48d4-88a1-2ca4c38c278a)

https://github.com/ihhub/fheroes2/assets/12501091/c141cf27-1eca-430c-80aa-3ac373c2087a

There are several issues here, but the core one is that the AI's evaluation of the pyramid needs improvement.

### Save file

[ai suicide pyramid.zip](https://github.com/ihhub/fheroes2/files/12240464/ai.suicide.pyramid.zip)

**Comment by ihhub** [comment]
Ah, yes. I have this in my TODO list. Sometimes AI heroes indeed move on objects which they shouldn't. We need to connect **HeroesValidObject()** function from ai_normal_hero.cpp to ai_normal.cpp file.

**Comment by idshibanov** [comment]
I don't see an issue for AI to pass through objects like Pyramids, especially here when it was trying to avoid another hero blocking the way. Better fix is to add a check during the visit for AI to decline the battle.
