### ISSUE TITLE
Increase width and height of the Campaign Difficulty selection dialog

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#7511]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

The campaign difficulty selection dialog has very limited space and should perhaps adjust its height dynamically to allow for languages that have longer texts. Additionally there should be more horizontal space since a couple of the supported languages have a bit longer difficulty level names than English:

![image](https://github.com/ihhub/fheroes2/assets/12501091/5622ec0e-3eb0-43aa-bdce-f5e08d65947f)
![image](https://github.com/ihhub/fheroes2/assets/12501091/c31a597f-5b3c-4182-b7c5-81424f1838ce)

### Describe the possible solution

Make the dialog wider and taller, preferrably adjusting its vertical height as needed.

**Comment by ihhub** [comment]
This should be done in **setCampaignDifficulty()** function within `game_campaign.cpp` file.
