### ISSUE TITLE
The Hero info button in level up dialog has black background

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#7514]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Seen here:
![image](https://github.com/ihhub/fheroes2/assets/12501091/ace28523-d766-4079-8f88-3ec0e3b470c8)

It is the same background as it has in the adventure map buttons
![image](https://github.com/ihhub/fheroes2/assets/12501091/c047da7c-41a8-4dca-8b07-021ff985fb81)

### Save file

No need.

**Comment by LeHerosInconnu** [comment]
I confirm this in my current game with version 1.0.6 7494.

In fheroes2:

![Hero button 01](https://github.com/ihhub/fheroes2/assets/43583994/4a111f1c-67ae-4ccf-8253-09d668a58ee5)

Here is the save file:
[Hero button 01.zip](https://github.com/ihhub/fheroes2/files/12267534/Hero.button.01.zip)
