### ISSUE TITLE
Combat, AI behavior, red dragons skip their extra morale attack when they could attack a second time (1.0.6 7494)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#7517]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

In fheroes2, the red dragons skip their extra morale attack when they could attack a second time.

Red dragons attack greater druids.
High morale enables the red dragons to attack again.
Red dragons skip their turn.

In this case, the red dragons could attack the greater druids again and decimate them entirely.

In fheroes2:

![Red dragon skip morale 01](https://github.com/ihhub/fheroes2/assets/43583994/c1d699d4-236c-4227-8400-8aab2fda43fc)

https://github.com/ihhub/fheroes2/assets/43583994/c3cf947e-0d8f-484b-8026-684d9f6ea7b9

Here is the save file:
[Red dragon skip morale 01.zip](https://github.com/ihhub/fheroes2/files/12269831/Red.dragon.skip.morale.01.zip)

### Describe the possible solution

In this case, the red dragons could attack the greater druids again and decimate them entirely.

**Comment by kitovyj** [comment]
It could be the same bug as #7498
