### ISSUE TITLE
Battle only mode and maybe future editor; possibility to select same skill more than once

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#7534]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In the battle only mode it is possible to select the same skill, at the same level or different levels, more than once in the skill selection dialog. The future editor uses these dialogs so this issue will need to be solved for that too.

![image](https://github.com/ihhub/fheroes2/assets/12501091/7cd741ca-6857-4b53-b256-fc0161670fd8)

### Save file

Prohibit a skill from being applied more than once.

**Comment by ihhub** [comment]
Yes, this is a problem with an existing original Editor which allows to select the same skills. It shouldn't be the case at all.
