### ISSUE TITLE
AI teleports next to neutral monsters via Dimension Door and the monsters don't attack.

### ISSUE THREAD

**Issue by kitovyj** [ihhub/fheroes2#7543]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

AI teleports next to neutral monsters via Dimension Door and the monsters don't attack.

### Save file

[teleport_ignores_titans.zip](https://github.com/ihhub/fheroes2/files/12327143/teleport_ignores_titans.zip)

**Comment by Branikolog** [comment]
Hi, @kitovyj !
Your archived file seems to be broken.
But it doesn't matter much, since the original game logic allows you to teleport close to monsters and even steal items near them. :)

**Comment by kitovyj** [comment]
> Hi, @kitovyj ! Your archived file seems to be broken. But it doesn't matter much, since the original game logic allows you to teleport close to monsters and even steal items near them. :)

Ahh! I didn't know that it's allowed) I updated the file just in case.

**Comment by oleg-derevenetz** [comment]
This is not a bug. This behavior was specially implemented at the time in #6966.

**Comment by kitovyj** [comment]
> This is not a bug. This behavior was specially implemented at the time in #6966.

Thanks for the clarification.
