### ISSUE TITLE
AI hero jumps during movement

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#7546]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

AI heroes jump while walking. It should be the case. Hit F8 for AI mode and see what happens to the hero.

### Save file

[Chests.zip](https://github.com/ihhub/fheroes2/files/12327191/Chests.zip)

**Comment by ihhub** [comment]
This is something to do with no remembering the last tile a hero stepped in. I believe it is related to our recent changes.

**Comment by oleg-derevenetz** [comment]
I don't see any jumping:

https://github.com/ihhub/fheroes2/assets/32623900/2d022c9b-0173-4e39-9bab-3578cf39a679

This is on animation speed 3. Maybe this is observed on some other speed?

**Comment by Districh-ru** [comment]
> I don't see any jumping:

I also could not reproduce the bug. :(

https://github.com/ihhub/fheroes2/assets/113276641/6170c0b8-9110-47d7-8ede-44aaee19bca8

**Comment by ihhub** [comment]
Hmm... I will be back home in few hours and record the behavior.

**Comment by oleg-derevenetz** [comment]
I observed some "jumps" occasionally in the past during the AI turn too, but couldn't reliably reproduce them. In general, I thought that these "jumps" (or rather, frame skips during rendering) happen because the hero is acting on the edge of the fog of war.

**Comment by ihhub** [comment]
Please use [reduce_ai_object_knowledge](https://github.com/ihhub/fheroes2/tree/reduce_ai_object_knowledge) branch or build from #7542

https://github.com/ihhub/fheroes2/assets/19829520/4cb3be85-44cb-4b9f-8542-b5d20257d8f9

**Comment by oleg-derevenetz** [comment]
> Please use [reduce_ai_object_knowledge](https://github.com/ihhub/fheroes2/tree/reduce_ai_object_knowledge) branch or build from https://github.com/ihhub/fheroes2/pull/7542

Yes, on that branch it is reproducible.

**Comment by oleg-derevenetz** [comment]
If I comment out the hero's stop logic in the `Normal::revealFog()`, then everything works like it should.

**Comment by ihhub** [comment]
@oleg-derevenetz , I think the problem is in this code:
```cpp
            if ( hero->isMoveEnabled() ) {
                hero->GetPath().Reset();
                hero->SetMove( false ); <--- this is the problem
                break;
            }
```

**Comment by oleg-derevenetz** [comment]
It seems that scouting for a tile begins earlier than hero is actually moved at that tile, and that's really what causes hero to "jump back". Even if we remove the `SetMove()` call here, hero still will jump back a bit (he does his initial movement animation and then jumps back).

**Comment by Districh-ru** [comment]
Currently as I can see it works:
1 - AI hero starts a move (without moving hero's position to the next step in the path),
2 - hero reveals the fog and checks was a new object found (if yes - AI resets path and recalculates it from the start of this, already started, move),
3 - the engine animates hero movement to the next step using the path that was before the start of the movement,
4 - hero gets to a new position if move was not cancelled or visually "jumps" to the current move start position,
5 - AI starts the next hero move.

IMHO AI should continue and finish this step (as the territory could be revealed only after starting a move, so jumping back is a cheat/bug), at the 4th point if hero's path was reset he should be moved to the new position, according to the previous path and only then recalculate the new path and start the move from this new position.

**Comment by oleg-derevenetz** [comment]
@ihhub you can try to truncate carefully the hero's path to just one step (the current one) instead of resetting it and do not stop the hero. You can add a special method to the `Route::Path` for this. This should resolve this issue. Or if you wish I can take a look later today.

**Comment by ihhub** [comment]
@oleg-derevenetz , can you please take a look at it as for me it's night time? Yes, we just need to cut all other steps in the path except the current.
