### ISSUE TITLE
Army/artifact trading dialog: text artifact on the picture of the right hero (german translation).

### ISSUE THREAD

**Issue by kitovyj** [ihhub/fheroes2#7551]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Please see the screenschot, "en?" seems to be a remnant of some question text.
![trading art](https://github.com/ihhub/fheroes2/assets/15792725/33d8cf64-b117-4a0a-b07a-786d268fdee5)

### Save file

not needed

**Comment by ihhub** [comment]
Hi @kitovyj , I cannot reproduce the issue:
![image](https://github.com/ihhub/fheroes2/assets/19829520/f087e9d7-7055-4556-973e-7b31a3802349)

Please describe exact steps how you get this, possibly attaching a save file if needed.

**Comment by ihhub** [comment]
We must rework monster separation dialog (relates to #2388).

**Comment by kitovyj** [comment]
> This is due to the text from the fast separation dialog: ![image](https://user-images.githubusercontent.com/12501091/262064224-5ba9004d-7894-42fc-b677-890bff2757f7.png)
> 
> I suggest making the text wrap to the next line.
> 
> Curiously the text over the left hero's portrait does not remain.

Yes, thank you for researching the cause. If I remember correctly somehow this 'en?' even can appear immediately after opening the dialog, probably if army exchange was initiated before at least once.
