### ISSUE TITLE
Battle should start instantly if sounds are off

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#756]
If you play without sounds, a battle shouldn't wait a few seconds, while battle intro sound is supposely playing, which is switched off. Now we have to wait 3-4 seconds in silence.
Also battle music should be played from the start.
![battle](https://user-images.githubusercontent.com/55348946/83963443-de905c00-a8ae-11ea-8045-3e4690fe100c.jpg)

**Comment by idshibanov** [comment]
I think good approach here is to update `Mixer::isPlaying` to return false if volume is 0.
