### ISSUE TITLE
"Summon boat" spell does not work if there are no boats built by the player

### ISSUE THREAD

**Issue by drevoborod** [ihhub/fheroes2#7562]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

Seems like boat summoning spell stopped working as expected for human players in 1.0.7.. Here is save game, where my first hero does have the spell and there are a lot of boats on the map, but none of them were anytime possesed by player's heroes. So, it's not possible to summon them. 
And after I built my own boat, I was able to summon it.

### Save file

[Dominion_0132.zip](https://github.com/ihhub/fheroes2/files/12366555/Dominion_0132.zip)

**Comment by drevoborod** [comment]
> You cannot summon a boat belonging to another player.

And the same behaviour was in the original game, right? Now I understand why I couldn't summon them that days I was playing the original! It always frustrated me..
Ok, so it's not a bug, but it looks weird for me.. Why on Earth do they remain belonging when noone uses them?? There are even neutral flags on them! So I suggest to remove this strange mechanics of belonging empty boats to anyone. Actually, in Heroes 3 it was removed - all boats can be summoned there.
Maybe the issue should be converted to a feature request?

**Comment by oleg-derevenetz** [comment]
> Actually, in Heroes 3 it was removed - all boats can be summoned there.

That's not really the case. You still cannot summon boats belonging to other players in HoMM3.

> Maybe the issue should be converted to a feature request?

What would be the point of this feature request? To allow any free boat to be summoned? I believe this would severely break the game mechanics.

**Comment by drevoborod** [comment]
> What would be the point of this feature request? To allow any free boat to be summoned? 

Exactly. It looks logical for me. Or at least mark such "belonging" boats with corresponding flag colour.

> I believe this would severely break the game mechanics

Actually, I think that some strange mechanics should be broken :) But ok, it's up to you.

**Comment by drevoborod** [comment]
> That's not really the case. You still cannot summon boats belonging to other players in HoMM3.

I definitelly can, but maybe it was added in HotA - actually I haven't played vanilla for a very long time.

**Comment by oleg-derevenetz** [comment]
> Actually, I think that some strange mechanics should be broken :) But ok, it's up to you.

In fact, I'm thinking about the changes in the opposite direction - to not allow AI players to summon neutral boats at all. But for now it's just a thought.

**Comment by drevoborod** [comment]
I'm sure that if we have such concept as "possesion" of a boat, we definitelly need to mark them visually. At the time it's not clear why these boats cannot be summoned. We need to provide explanation to the player. The simpliest way seems to leave boat flags painted with player's colour. But it can confuse in separate way - at the time coloured flag means that there is a hero onboard. So it requires further discussion.
And what definitely should be done - explanation should be added to spell description. Something like "Only unowned boats can be summoned (and how to distinguish which are owned, we won't tell you, muhaha!)" :)

**Comment by drevoborod** [comment]
Ok, so this issue can be closed.
