### ISSUE TITLE
Font color should be changed if there is not enough mana points

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#759]
While hero has not enough mana points in the OG font of spells have different color:
![color](https://user-images.githubusercontent.com/55348946/84009228-a276fd00-a97b-11ea-8f0b-d3ed80e4f091.jpg)
While our version has the same:
![color2](https://user-images.githubusercontent.com/55348946/84009262-af93ec00-a97b-11ea-9ade-16efd054da20.jpg)

**Comment by ihhub** [comment]
We need to introduce another font for such case like it's done for yellow font.
