### ISSUE TITLE
Spell book should be fixed in inventory

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#761]
In the OG we cannot move spell book over hero's inventory. It even can't be selected: single click over it opens book. 
While trading between heroes a message "This item can't be traded" should pop up when clicking over a book,
![book](https://user-images.githubusercontent.com/55348946/84024162-09071580-a992-11ea-9fb0-4364572d27de.jpg)

**Comment by 0UserName** [comment]
The problem of moving can be solved by editing in the `ArtifactsBar::ActionBarLeftMouseSingleClick` method. The [Artifact](https://github.com/ihhub/fheroes2/blob/master/src/fheroes2/resource/artifact.h#L36) class does not have any attributes to help determine if an element is selectable. That is, we can either add this attribute and check it, or go the other way and write something like this: 

```
bool ArtifactsBar::ActionBarLeftMouseSingleClick( Artifact & art )
{
    if ( isSelected() ) {
        if ( !read_only ) {
            if ( art.GetID() != Artifact::MAGIC_BOOK && GetSelectedItem()->GetID() != Artifact::MAGIC_BOOK ) {
                std::swap( art, *GetSelectedItem() );
            }
        }
        return false;
    }
    else if ( art.isValid() ) {
        if ( !read_only ) {
            Cursor::Get().Hide();
            spcursor.hide();
        }
    }
    else {
        if ( can_change )
            art = Dialog::SelectArtifact();

        return false;
    }

    return true;
}
```
