### ISSUE TITLE
Вылетает игра

### ISSUE THREAD

**Issue by cafedemidov** [ihhub/fheroes2#7648]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Файл с сохранением игры прикрепил.
Нужно загрузить игру и сделать конец хода.
![Безымянный](https://github.com/ihhub/fheroes2/assets/31575246/0d2b9da2-6ddf-4017-a838-3ddd20bb9bc7)

### Save file

[save.zip](https://github.com/ihhub/fheroes2/files/12448380/save.zip)

**Comment by oleg-derevenetz** [comment]
Hi @cafedemidov, I can't reproduce this problem yet. It may have already been fixed. Please try to install the latest snapshot build from here:

https://github.com/ihhub/fheroes2/releases/tag/fheroes2-windows-x64-SDL2

and check if the problem continues to appear.

**Comment by cafedemidov** [comment]
[oleg-derevenetz](https://github.com/oleg-derevenetz)
Прежде чем запостить этот баг, я скачал этот самый свежий билд и попробовал с ним.
С ним у меня всё так же, вылетает.

**Comment by oleg-derevenetz** [comment]
> Прежде чем запостить этот баг, я скачал этот самый свежий билд и попробовал с ним.
С ним у меня всё так же, вылетает.

Interesting. Still cannot reproduce:

https://github.com/ihhub/fheroes2/assets/32623900/18dbd4c0-deef-45da-9474-4cd53a929247

Hi @Districh-ru @Branikolog @ihhub can anyone reproduce it?

**Comment by cafedemidov** [comment]
Вот запись видео экрана )
https://disk.yandex.ru/i/UFHkz-qAtnv5lg

**Comment by oleg-derevenetz** [comment]
> Вот запись видео экрана )

I readily believe that it crashes :) The question is why and how to reproduce this. BTW two questions:

1. Do you use 32-bit or 64-bit version?
2. Is everything all right with the original game resources? There are some pirated distributions where they were tampered with.

**Comment by cafedemidov** [comment]
Использую 64-битную версию.
Насчёт все ли в порядке с ресурсами игры, не знаю.
Скачивал с рутрекера, извините....
Если интересно, выложу в облако ресурсы игры или файл карты

**Comment by oleg-derevenetz** [comment]
> Насчёт все ли в порядке с ресурсами игры, не знаю.

Try the data files from the official GOG distribution.

**Comment by oleg-derevenetz** [comment]
I was able to reproduce this with the demo version assets. Purple hero attacks another hero on water and then assertion fails.

**Comment by Alucard648** [comment]
He can`t get Heroes 2 from GoG - that game is banned in Russia from that store.

**Comment by oleg-derevenetz** [comment]
Hi @cafedemidov could you please take the Windows binary from #7649 and verify whether it fixes your issue with non-GOG HoMM2 assets? Here is an instruction on how to do it:

https://github.com/ihhub/fheroes2/wiki/Download-Windows-latest-compiled-packages-of-a-pull-request

**Comment by cafedemidov** [comment]
Нашел  и скачал релиз от GOG, с ним вылетать перестало.
Что за сборка героев2 стояла до этого, что-то уже не найти, чтобы проверить билд ((

**Comment by oleg-derevenetz** [comment]
> Что за сборка героев2 стояла до этого, что-то уже не найти, чтобы проверить билд ((

This issue has been observed with any HoMM2 "Succession Wars"-only assets (i.e. without The Price of Loyalty addon). For example, this has been observed with assets from HoMM2 demo version, that are freely available.
