### ISSUE TITLE
Castle construction screen, cliff nest has glowing pixel

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#7666]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

![nest](https://github.com/ihhub/fheroes2/assets/55348946/ef8fa934-d15c-44d3-aee9-6ad48eb87f5e)

A small dot is shining in the Cliff Nest icon.

### Save file

None.

**Comment by ihhub** [comment]
It's a fire detector. Nothing wrong with it.
