### ISSUE TITLE
Adventure map, Witch's Hut, right-click information window, a line with brackets and no text is displayed below the secondary skill line when the selected hero does not have the secondary skill of the witch's hut

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#7670]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, a line with brackets and no text is displayed below the secondary skill line when the selected hero does not have the secondary skill of the witch's hut.

In fheroes2:

![Archery hut bug 01](https://github.com/ihhub/fheroes2/assets/43583994/913116d4-5b90-4e49-82b4-0e7089156898)

### Save file

Here is the save file:
[Archery hut bug 01.zip](https://github.com/ihhub/fheroes2/files/12476937/Archery.hut.bug.01.zip)

### Additional info

Version 1.0.7 7640

**Comment by lwollnikowski** [comment]
Does not happen on official release 1.0.7, so one of the 62 commits broke this.

Probably here: https://github.com/ihhub/fheroes2/commit/59da44d2342a993ec485d75c0a3cebb670a9f67e#diff-581d4a087734b63941ac6d2357595f4992147d281e136c79b4bb1cf454eb84c3R279
Line 279.

I will fix it.
