### ISSUE TITLE
Message while casting spells should be centered in a window

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#771]
![window](https://user-images.githubusercontent.com/55348946/84150489-9ae25180-aa6a-11ea-88d5-92c9401ee83a.jpg)
I think message should be placed a little higher in this window.

**Comment by Branikolog** [comment]
The same should be done for all such pop up windows, such as quit dialog window, or load game window.

**Comment by ihhub** [comment]
Fixed some time ago.
