### ISSUE TITLE
Shadow problems near hero on a world map

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#772]
Shadows from mountains become patchy close to hero. Also while moving some parts of object's shadow become darker.
![Shadow](https://user-images.githubusercontent.com/55348946/84376398-c2abf380-abe9-11ea-855b-aa44edc6f787.jpg)
![Shadow2](https://user-images.githubusercontent.com/55348946/84376400-c475b700-abe9-11ea-9186-cc6d0c31bde4.jpg)

**Comment by ihhub** [comment]
The issue lies in `Heroes::Redraw` method where we redraw dependency tiles. So there we draw shadow twice leading to a darker version of it to be shown on the World Map.
