### ISSUE TITLE
VSync ON causes flickering fade out when exiting certain screens back to the adventure map

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#7730]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

When exiting back to the adventure map I sometimes observe a fade out that flickers a lot, but only with Vsync ON.

It happens in all the cases below when going from hero screen, castle screen, hero meeting screen. But, it does not happen when you leave the kingdom overview screen or apparently the hero screen if you enter it by pressing the mini hero portrait on the side bar, same with the castle screen if you enter it from the side bar.

https://github.com/ihhub/fheroes2/assets/12501091/d6ded272-94db-41a7-a95d-d4bbf0f1d3fc

### Save file

No save file needed

### Additional info

Software cursor ON
VSync ON
Nearest filtering

**Comment by Districh-ru** [comment]
The core of te issue is the same as for https://github.com/ihhub/fheroes2/issues/7281and, possibly, https://github.com/ihhub/fheroes2/issues/7272.
The restorer in dialog destructor restores the image after the fade-out and then the fade-in starts. Sometimes it produces fully bright frame in the middle of fade animation and sometimes this:
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/69a7cbd7-c9a8-4954-b2d6-d0a506b9de84)

The software cursor causes the screen redraw call before the engine prepares a new frame after the restoration of the screen image.
Perhaps we should redo the software cursor not to force the screen image update when it is not needed, but update only cursor position, in example using another restorer for the cursor ... and the will be a race of restorers ... :(

**Comment by Districh-ru** [comment]
> You can close this issue if you wish since you're the expert on this.

Let's keep it because it is observed in the different place (fade effect, not the battle options).
We will close these issues if we can beat the core issue. :)

**Comment by Districh-ru** [comment]
The engine forces the screen render with unprepared image after the cursor Restorer (this issue and https://github.com/ihhub/fheroes2/issues/7272):
https://github.com/ihhub/fheroes2/blob/b38abb6402aa84060b5e5e2c5bbf6ed38ae8734e/src/fheroes2/gui/cursor.cpp#L264-L268
And after the cursor move (this issue and https://github.com/ihhub/fheroes2/issues/7281):
https://github.com/ihhub/fheroes2/blob/b38abb6402aa84060b5e5e2c5bbf6ed38ae8734e/src/engine/localevent.cpp#L941-L946

A partial fix is to avoid using cursor restorers where it is not needed, e.g. Hero or Castle dialogs - after closing these dialogs the restored cursor updates.

We can try to implement cursor rendering without force updating the screen image: use a separate render for the software cursor (with its own restorer of the under cursor image), but if the render is called for the screen image - update the cursor at the same time without calling its renderer.

**Comment by Districh-ru** [comment]
Hi, @ihhub.
Do we really need to immediately render the restored cursor in destructor `~CursorRestorer()`?
`CursorRestorer()` is used for new dialogs or screens, and after restoring the cursor on dialog/screen exit, the restored (after appropriate processing) screen will be rendered with the restored cursor.

Removing the `render()` call from `~CursorRestorer()` will allow us to fix the issues mentioned here without overcomplicating the rendering code, and, as far as I can see, will not bring new bugs or delays in cursor update.
What do you think?

**Comment by ihhub** [comment]
Hi @Districh-ru  , yes this is a valid idea. Moreover, what we are missing is to disable cycling animation in between dialogs but this is a separate issue.

**Comment by Districh-ru** [comment]
> Hi @Districh-ru , yes this is a valid idea. Moreover, what we are missing is to disable cycling animation in between dialogs but this is a separate issue.

For color cycling disabling we need to keep FPS/TIME render (with 1 FPS). A little later I'll try to implement this.
