### ISSUE TITLE
Teach AI to scout the map more effectively

### ISSUE THREAD

**Issue by fheroes2bugs** [ihhub/fheroes2#7775]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

The map is XL for 6 players, "The Soul Maze". I was checking when will computer will defeat me. But for 44 months I could see no one near me and also none on computers were defeated.
![2023-09-19_040744](https://github.com/ihhub/fheroes2/assets/145407420/36a2bbdb-97e8-4c55-b0b8-32487a7445f5)
![2023-09-19_040757](https://github.com/ihhub/fheroes2/assets/145407420/b438477d-1536-48ba-9665-8e8b7cde3716)
[ai does not scout.zip](https://github.com/ihhub/fheroes2/files/12654616/ai.does.not.scout.zip)

### Describe the possible solution

Can't actually tell how to solve, because cheat for map is not working in fheroes2, don't know what problem AI actually have, but in XL maps game ends in 6-8 months, and I can see everyone in alive in 44 moths.

**Comment by ihhub** [comment]
Hi @fheroes2bugs , are you sure that AI has an ability to pass through gates?

**Comment by ihhub** [comment]
@fheroes2bugs , the AI is very smart in uncovering the fog of war. I believe that map is made in a way that AI has no access to other parts of the map. You can build a debug version and see how the AI behaves.

**Comment by ihhub** [comment]
I am closing this issue as this is map specific thing. @fheroes2bugs , please pay attention to Tents and Barriers on the map and also some heroes are made not to move.
