### ISSUE TITLE
GOG EXE Linux Extract failed

### ISSUE THREAD

**Issue by AShynkevich** [ihhub/fheroes2#7777]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

Once I try to select the EXE file installation from GOG the system shows the error message window: 

"innoextract was not found in your system. Unable to extract the installer package. Installation aborted."

The file is located correctly.

### Save file

I'm not allowed to send the GOG installer, but available now here
https://www.gog.com/en/game/heroes_of_might_and_magic_2_gold_edition

### Additional info

Linux Mint 21.2 Cinnamon

**Comment by oleg-derevenetz** [comment]
> "innoextract was not found in your system. Unable to extract the installer package. Installation aborted."

Well, you need to install the `innoextract` tool using your system's package manager, so that it is present in `PATH`.

**Comment by AShynkevich** [comment]
Yep, I've installed it additionally and got:

me/user/homm2 or /tmp/installer.exe): /home/alex/Downloads/h2inst.exe 
Verifying the installer package, please wait...
Not a supported Inno Setup installer!
Done with 1 error.

**Comment by oleg-derevenetz** [comment]
Probably the innoextract version offered by your package manager is a bit old. Latest version of innoextract is 1.9:

https://github.com/dscharrer/innoextract

You can also try to contact the innoextract developer directly. Our scripts use innoextract, but we are not developing it.

**Comment by undef21** [comment]
@AShynkevich The minimal version of innoextract for unpacking homm's GOG installer is 1.9.

**Comment by oleg-derevenetz** [comment]
I suppose we can close this.

**Comment by groundnuty** [comment]
I'm facing the same issue, same errors, bought the same version from gog, while having innoextract 1.9

```bash
>innoextract -v
innoextract 1.9
Extracts installers created by Inno Setup 1.2.10 to 6.0.5
```

please help.

**Comment by groundnuty** [comment]
Solved it and commented for others to find.

Apparently, I downloaded the wrong file form GoG:
- wong file is a gog installer: `GOG_Galaxy_Heroes_of_Might_and_Magic_2_Gold.exe`
- a good file is so-called off line backup install: `setup_heroes_of_might_and_magic_2_gold_1.01_(2.1)_(33438).exe`
