### ISSUE TITLE
AI just moves back and forward, instead of killing me

### ISSUE THREAD

**Issue by fheroes2bugs** [ihhub/fheroes2#7780]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Yellow AI moves back and forward, instead of killing me. Looks like he wanted to go to the teleport, but I block the path.
If I am correct, then it is also strange why teleport has better priority then killing me.
His army is much more stronger then I have...

[yellow AI ignores.zip](https://github.com/ihhub/fheroes2/files/12668498/yellow.AI.ignores.zip)

https://github.com/ihhub/fheroes2/assets/145407420/f9645ff7-8170-44c2-9b1b-390ae3feed04

Seems like dublicate of #7557 but not the exact same one.

### Describe the possible solution

Before moving back and forward, check first if path can be cleared by killing an enemy.

**Comment by ihhub** [comment]
@fheroes2bugs , what happen if you go to the teleport? Will you fight monsters?

**Comment by fheroes2bugs** [comment]
> @fheroes2bugs , what happen if you go to the teleport? Will you fight monsters?

There is just a chest and an artifact. Also, after I pick them and move forward, AI continues his strange behavior and don't want to go to the teleport


![2023-09-20_082638](https://github.com/ihhub/fheroes2/assets/145407420/4094ca20-5cd0-4b73-9809-8605754ceb2f)


https://github.com/ihhub/fheroes2/assets/145407420/9f9563fb-e13e-46ba-8695-e090cb06719d

**Comment by ihhub** [comment]
This is not an issue. The AI hero is on a patrol mode.

**Comment by fheroes2bugs** [comment]
He is on a patrol mode, but if a stay in a different place (than you can see in a video), he kills me...
Also this patrol mode looks weird: sometimes we can see AI "patrols" (moves bad and foreward for no reason) and sometimes he just stay at one place and does not move. There is no logic is he moving or staying at one place, looks like random.
