### ISSUE TITLE
Combat screen, Griffins retaliate after being paralyzed by Cyclops

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#7784]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

https://github.com/ihhub/fheroes2/assets/55348946/72152e61-9bc1-47ff-b442-c318e9e016ac

Griffins shouldn't retaliate once they are paralyzed. But once paralyze spell was cancelled, retaliation should be possible for all next attacks.

### Save file

[Paralyse.zip](https://github.com/ihhub/fheroes2/files/12684302/Paralyse.zip)

**Comment by oleg-derevenetz** [comment]
> Griffins shouldn't retaliate once they are paralyzed.

No, they should:

https://handbookhmm.ru/2-monsters

Griffins are always retaliate, even when paralyzed (or petrified). This is not a bug, works as intended.

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz 

I've checked the original game. Griffins don't retaliate in the same situation as on my video. Maybe author of the guide from the link was talking about the case, that Griffins should retaliate when they are already paralyzed and someone is attacking them? I'll check it today evening once again.

**Comment by oleg-derevenetz** [comment]
@Branikolog

> Maybe author of the guide from the link was talking about the case, that Griffins should retaliate when they are already paralyzed and someone is attacking them?

I remember I checked the original game with Paralyze spell and Griffins retaliated even being paralyzed. I don't think that built-in spell should work differently from the "regular" spell, and if it does work differently in OG, then it's a bug in OG.

**Comment by Branikolog** [comment]
@oleg-derevenetz 

That's how it works in the original:

https://github.com/ihhub/fheroes2/assets/55348946/c97ea961-10e4-4bfb-9c98-d2b626c63686

For me it's obvious, that after the spell applied target shouldn't retaliate, as it was just paralyzed/blinded, so it cannot react properly.

Indeed, if Cyclops attacks paralyzed Griffins they still retaliate. While I suppose common (without unlimited retaliations) and paralyzed creature shouldn't retaliate at all.

https://github.com/ihhub/fheroes2/assets/55348946/1a39f0dd-15a8-4337-bfa5-be7c5dd7b5f4

**Comment by oleg-derevenetz** [comment]
> Indeed, if Cyclops attacks paralyzed Griffins they still retaliate.

That is, it turns out that in one case the griffins retaliate while being paralyzed, and in the other they do not. In both cases, at the moment of the griffins (potential or real) retaliation, they are paralyzed. Is it right that in one case they retaliate, and in the other they don't? Please note that if you just cast the Paralyze spell on the griffins using a Spell Book, they will always retaliate too, even if they are paralyzed.

**Comment by Branikolog** [comment]
@oleg-derevenetz 

Here's one essential difference:
In the first case from my video we attack first -> griffins are going to retaliate but... --> whoa! they suddenly paralyzed and freezed without any chance to move!

In the second case griffins are **already** paralyzed. Cyclops sneacked out from behind and attacked poor paralyzed griffins -> the blood of griffins boils from rage and pain, the spell breaks down and griffins gladly revenge with all their might and fury.

**Comment by oleg-derevenetz** [comment]
> similar to how any other creature retaliates if it is struck while being blinded or paralyzed.

The problem that other creatures do not retaliate if they were paralyzed at the moment of the attack :)

**Comment by Branikolog** [comment]
I consider the ability of griffins to retaliate after they were attacked being paralyzed as a special feature of their "unlimited retaliations" characteristic. All other creatures cannot retaliate in the same situation.

**Comment by oleg-derevenetz** [comment]
> As we can see "Always" is quite ambiguous.

In fact "always" is closer to the truth, because Griffins are really capable of striking back, even being under the influence of paralyzing spells (other units are not able to retaliate in this case). BUT if these spells are applied to them during the CURRENT attack, they are not retaliate. The question is how much this difference from other cases (i.e. when Griffins are attacked being already paralyzed) is legal.

**Comment by Branikolog** [comment]
For me personally the inability of griffins to retaliate **after** they were paralyzed is an absolutely naturaly looking thing.
All creatures in the game can't act while being paralyzed or blinded. They can't move or retaliate.
Griffins are unique in their ability to retaliate right after the spell was cancelled.
After all this is the original behaviour that players (and me among them) got used to it.

**Comment by LeHerosInconnu** [comment]
Hello everyone,

This is how it should work for me:

With the Paralyze spell:
- The creature still under the effect of the spell (from magic book spell, or from cyclops ability), or, which has been under the effect of the spell and has been attacked from a distance (ranged creature, or ballista or turret during a siege), or in close combat, or by a damage spell (armageddon, magic arrow, etc.), does not retaliate when attacked for the entire current turn.
- Whether the creature has a single retaliation, several retaliation, or an unlimited number of retaliation, it does not retaliate.
- The creature also loses the ability to play for the current turn if it is attacked in any way while under the effect of the spell.
- If the Paralyze spell has been removed (with a dispell spell, or with a cure spell) before the creature is attacked in any way, the creature acts normally, as if unaffected by the spell.

With the Blind spell:
- The creature still under the effect of the spell (from magic book spell, or from unicorn ability), or, which has been under the effect of the spell and has been attacked from a distance (ranged creature, or ballista or turret during a siege), or in close combat, or by a damage spell (armageddon, magic arrow, etc.), retaliates and inflicts only half the damage when attacked for the entire current turn.
- The creature retaliates as many times as it is able to, once (for creatures in general), several times (if a creature had this ability), an unlimited number of times (like the griffin, for example), but always inflicting only half the damage.
- The creature also loses the ability to play for the current turn if it is attacked in any way while under the effect of the spell.
- If the Blind spell has been removed (with a dispell spell, or with a cure spell) before the creature is attacked in any way, the creature acts normally, as if unaffected by the spell.

**Comment by oleg-derevenetz** [comment]
> Whether the creature has a single retaliation, several retaliation, or an unlimited number of retaliation, it does not retaliate.

But that's not how it work in the original game. Units with the ability to "always retaliate" really retaliate ALWAYS, even being under effect of Paralyze or Petrification:

https://github.com/ihhub/fheroes2/assets/32623900/b3dcddb0-2977-462c-a516-183fe04f1f66

This is the ONLY exception:

https://github.com/ihhub/fheroes2/assets/32623900/916c4163-8ef1-4f65-bebe-d1d2cde2ccea

i.e. such a unit does not retaliate ONLY if the attack it is supposed to retaliate to has just paralyzed/petrified this unit.

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> > Whether the creature has a single retaliation, several retaliation, or an unlimited number of retaliation, it does not retaliate.
> 
> But that's not how it works in the original game. Units with the ability to "always retaliate" really retaliate ALWAYS, even being under effect of Paralyze or Petrification:
> 
> https://github.com/ihhub/fheroes2/assets/32623900/b3dcddb0-2977-462c-a516-183fe04f1f66
> 
> This is the ONLY exception:
> 
> https://github.com/ihhub/fheroes2/assets/32623900/916c4163-8ef1-4f65-bebe-d1d2cde2ccea
> 
> i.e. such a unit does not retaliate ONLY if the attack it is supposed to retaliate to has just paralyzed/petrified this unit (I suppose by the same logic as noone retaliates when stack of Unicorns blinds them).
            
This is clearly a Paralyze spell bug in Heroes 2 for me.
The Paralyze spell should have priority as it acts before the retaliation and is intended to block it.
Otherwise, what's the point of casting the paralyze spell on griffins?
And why is it then possible to cast it on griffins since it has no effect on them?

Once the spell is active on griffins following the cyclops' ability, it's still bugged since griffins retaliate even under the spell's effect.

In original game:

https://github.com/ihhub/fheroes2/assets/43583994/8b57dcd8-3dcf-4b25-952f-978ad53f6db5

Here are the test scenario and the save files:
[Paralyze 01.zip](https://github.com/ihhub/fheroes2/files/12694041/Paralyze.01.zip)

The behavior of griffins in relation to medusa petrification is also a bug for me in Heroes 2.
Same raison, the medusa petrification should have priority as it acts before the retaliation and is intended to block it.

**Comment by oleg-derevenetz** [comment]
I'm not so sure that this Griffins' ability to always retaliate is a bug.

> Otherwise, what's the point of casting the paralyze spell on griffins?

There is no point, just don't do that. Just like there is no point to cast Curse or Bless on Peasants.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> I'm not so sure that this Griffins' ability to always retaliate is a bug.
> 
> > Otherwise, what's the point of casting the paralyze spell on griffins?
> 
> There is no point, just don't do that. Just like there is no point to cast Curse or Bless on Peasants.

The griffin has unlimited retaliation.
The paralyze spell prevents any retaliation.
So the griffin should not retaliate, not once, not several times, but not at all.
As far as I know, there's no mention of the griffin being immune to the paralyze spell, either fully or partially.
This is a bug in the original game.
Same for the petrification of medusa on griffin.

**Comment by oleg-derevenetz** [comment]
> As far as I know, there's no mention of the griffin being immune to the paralyze spell, either fully or partially.

But Griffins are not "immune" to this spell. They still cannot have their turn while this spell is in effect. The only thing they "immune" to in this spell is the anti-retaliation effect.

> This is a bug in the original game.

I don't think so. This is just the Griffin's feature - you cannot "turn off" its retaliation (except just one case demonstrated above).

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> > As far as I know, there's no mention of the griffin being immune to the paralyze spell, either fully or partially.
> 
> But Griffins are not really "immune" to this spell. They still cannot have their turn while this spell is in effect. The only thing they "immune" to in this spell is the anti-retaliation effect.

What's the point of making the spell work halfway?

> ...(except just one case demonstrated above).

Why?

**Comment by oleg-derevenetz** [comment]
> What's the point of making the spell work halfway?

To give an unique useful ability to Griffins.

> Why?

As I already mentioned above - possibly for the same reason that blinded units do not retaliate to unicorns (although Blind spell by itself doesn't prohibit the retaliation at all). Another "bug"?

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> > What's the point of making the spell work halfway?
> 
> To give an unique useful ability to Griffins.

The griffin has a unique useful ability without the spell.
So why make it half-sensitive to the spell?

> > Why?
> 
> As I already mentioned above - possibly for the same reason that blinded units never retaliate to Unicorns after their blinding strike (although Blind spell by itself doesn't prohibit the retaliation at all). Another "bug"?

The blind spell works as it should with the griffin, and all other creatures.
Only the paralyze spell doesn't work as the spell description indicates with griffin.
So it's definitely a bug.
Heroes 2 is a game with simple, straightforward mechanics.
Why make a spell behave differently from other spells, and confuse the player about how the game works?

**Comment by oleg-derevenetz** [comment]
> So why make it half-sensitive to the spell?

Why not?

> The blind spell works as it should with the griffin, and all other creatures.

Huh? Blind spell casted by Unicorns prevents their target to retaliate, although Blind doesn't prohibit retaliation by itself. Why?

**Comment by oleg-derevenetz** [comment]
> So why make it half-sensitive to the spell?

Why not?

> The blind spell works as it should with the griffin, and all other creatures.

Huh? Blind spell casted by Unicorns prevents their target to retaliate, although Blind doesn't prohibit retaliation by itself. Why?

> Why make a spell behave differently from other spells, and confuse the player about how the game works?

That's how it works in the original game, so players should already have used to it.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> > So why make it half-sensitive to the spell?
> 
> Why not?

The other spells are simple and straightforward to use.
Paralyze spell is bugged.

> > The blind spell works as it should with the griffin, and all other creatures.
> 
> Huh? Blind spell casted by Unicorns prevents their target to retaliate, although Blind doesn't prohibit retaliation by itself. Why?

The blind spell works as described, clearly and simply.

> > Why make a spell behave differently from other spells, and confuse the player about how the game works?
> 
> That's how it works in the original game, so players should already have used to it.

Just because old players are used to the bug doesn't mean that new players have to suffer from it too.

**Comment by oleg-derevenetz** [comment]
> The blind spell works as described, clearly and simply.

There is nothing in Blind spell description that prevents blinded units from retaliation. It's the personal feature of Unicorns. Unicorns prevent blinded units from retaliation strike against Unicorns who blinded them. Unicorns have this feature, and Griffins have a different feature. You are claiming Griffin's feature as a "bug", but Unicorn's feature is fine, why is that?

> Just because old players are used to the bug doesn't mean that new players have to suffer from it too.

Then they probably should try some other game with different set of rules.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> > The blind spell works as described, clearly and simply.
> 
> There is nothing in Blind spell description that prevents blinded units from retaliation. It's the personal feature of Unicorns. Unicorns prevent blinded units from retaliation strike against Unicorns who blinded them. Unicorns have this feature, and Griffins have a different feature.

When the blind spell is cast by the hero, there is no retaliation.
Once under the effect of the spell, if the troop is attacked in close combat, it retaliates with half the damage.
When the blind spell is cast by the unicorn's ability, there is no retaliation.
Once under the effect of the spell, if the troop is attacked in close combat, it retaliates with half the damage.

When the paralyze spell is cast by the hero, there is no retaliation.
Once under the effect of the spell, if the troop is attacked in close combat, it does not retaliate.
When the paralyze spell is cast by the cyclops' ability, there is no retaliation.
Once under the effect of the spell, if the troop is attacked in close combat, it does not retaliate.

It's simple, clear and precise.

> You are claiming Griffin's feature as a "bug", but Unicorn's feature is fine, why is that?

I never wrote nor claimed that the griffin's ability is a bug.
The griffin's ability is not a bug.
It's the paralyze spell that's bugged.

> > Just because old players are used to the bug doesn't mean that new players have to suffer from it too.
> 
> Then they probably should try some other game with different set of rules.

That's probably what some of them will do.
Personally, when a game is bugged, all I see are the bugs, and the game appeals to me less and less.

**Comment by oleg-derevenetz** [comment]
> When the blind spell is cast by the hero, there is no retaliation.

Because there is no attack to retaliate against.

> When the blind spell is cast by the unicorn's ability, there is no retaliation.

But in this case there IS an attack to retaliate against. But there is no retaliation anyway (even with half a damage). Why?

> It's simple, clear and precise.

Huh? :) All the same quirky rules in both cases. Unicorns prevent retaliation just because. And Griffins ignore the "prevents retaliation" part of the Paralyze and Petrification spells just because. Just because the authors of the original game decided to do this way. I don't think that we should change anything here.

**Comment by oleg-derevenetz** [comment]
Hi @zenseii

> To me I do not see any difference in the behavior of the paralyze spell and blind and petrification?

In the original game, in cases when Blind/Paralyze/Petrification is performed as a result of a unit's "special" attack, no units (including Griffins) ever retaliate. I decided to replicate this behavior in my linked PR.

BUT when attacked unit already has been Paralyzed/Petrified at the time of the attack, there IS a difference between Griffins and other units: Griffins perform the retaliation in this case, while other units don't. That's what @LeHerosInconnu treats as a "bug" (and I don't think so and not going to "fix" this in any way).

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> > When the blind spell is cast by the hero, there is no retaliation.
> 
> Because there is no attack to retaliate against.
> 
> > When the blind spell is cast by the unicorn's ability, there is no retaliation.
> 
> But in this case there IS an attack to retaliate against. But there is no retaliation anyway (even with half a damage). Why?

Following the unicorn's attack, the blind spell is cast.
The affected troop is then under the effect of the spell.
The troop does not retaliate before the unicorn casts the spell, and the unicorn has not cast the spell after the targeted troop has retaliated.
It's the same principle as the hero casting the spell.
Easy to understand.

> > It's simple, clear and precise.
> 
> Huh? :) All the same quirky rules in both cases. Unicorns prevent retaliation just because. And Griffins ignore the "prevents retaliation" part of the Paralyze and Petrification spells just because.

For both spells, the targeted troop doesn't retaliate because the spell has just been cast by the creature's ability, as if it were cast by the hero.
Once the spell has been cast, it is activated as soon as a close combat attack is made.

> Just because the authors of the original game decided to do this way. I don't think that we should change or "fix" anything here.

The original game is bugged, so we're going to reproduce the bug in the original game, just besause.

**Comment by oleg-derevenetz** [comment]
> The troop does not retaliate before the unicorn casts the spell, and the unicorn has not cast the spell after the targeted troop has retaliated.

Who prevents the blinded unit to retaliate against Unicorn's attack with 50% damage? Isn't this also a "bug"?

> It's the same principle as the hero casting the spell.

You are claiming that principle is "the same", but there is nothing in common, because hero doesn't attack the unit being blinded and never gets the retaliation, whether he casts Blind or any other spell.

> The original game is bugged

It's just your personal opinion. I have a different opinion in this regard.

**Comment by LeHerosInconnu** [comment]
Hello @zenseii,

> Hi, @LeHerosInconnu and @oleg-derevenetz. To me I do not see any difference in the behavior of the paralyze spell and blind and petrification?

Consider this.
When the creature attacks in close combat, it performs its physical attack and as soon as the attack is over, its ability comes into play, casting the blind spell for the unicorn, the paralyze spell for the cyclops and the petrify spell for the medusa.
The targeted troop then has no time to retaliate, as the spell is cast immediately after the physical attack.
From then on, the operation of the spell is activated as soon as a close combat attack is made.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> > The troop does not retaliate before the unicorn casts the spell, and the unicorn has not cast the spell after the targeted troop has retaliated.
> 
> Who prevents the blinded unit to retaliate against Unicorn's attack with 50% damage? Isn't this also a "bug"?

The blinded troop doesn't retaliate because it's just been blinded.
No, it's not a bug.

> > It's the same principle as the hero casting the spell.
> 
> You are claiming that principle is "the same", but there is nothing in common, because hero doesn't attack the unit being blinded and never gets the retaliation, whether he casts Blind or any other spell. For example, Mummies still receive the retaliation from the target, despite the imposition of a Curse. Hero doesn't get retaliation after casting the Curse spell, so Mummies shouldn't get the retaliation either, isn't it? But this doesn't work this way, because your logic is flawed. You're just taking a "profitable" example, ignoring the "unprofitable" ones.

The mummy's ability doesn't blind the targeted troop, but casts the curse spell, which in no way prevents retaliation.

> > The original game is bugged
> 
> It's just your personal opinion. I have a different opinion in this regard.

Your opinion is yours, my opinion is mine.
It's all right.

**Comment by oleg-derevenetz** [comment]
> The blinded troop doesn't retaliate because it's just been blinded.

But Blind spell doesn't prevent the retaliation. And still the unit refuses to retaliate.

> No, it's not a bug.

You just personally like this behavior and don't like the behavior with Paralyze and Griffins. But in fact the rules are quite arbitrary in both cases.

> The mummy's ability doesn't blind the targeted troop, but casts the curse spell, which in no way prevents retaliation.

Blind doesn't prevent the retaliation. It just halves the retaliation damage. You see, there is no any logic :) "Just because".

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> > The blinded troop doesn't retaliate because it's just been blinded.
> 
> But Blind spell doesn't prevent the retaliation. And still the unit refuses to retaliate.

There was no attack after the spell was cast; the attack took place before the spell was cast.

> > No, it's not a bug.
> 
> You just personally like this behavior and don't like the behavior with Paralyze and Griffins. But in fact the rules are quite arbitrary in both cases.

All spells must be simple and intuitive to use.
When a creature retaliates under the effect of a spell that prevents retaliation, there's a bug.

> > The mummy's ability doesn't blind the targeted troop, but casts the curse spell, which in no way prevents retaliation.
> 
> Blind doesn't prevent the retaliation too :) It just decreases the retaliation damage (just like Curse BTW). You see, there is no any logic :) "Just because".

The blind spell prevents any action until the targeted creature is attacked.
After the spell has been cast, the targeted creature has not been attacked; the attack took place before the spell was cast by the creature's ability.

**Comment by oleg-derevenetz** [comment]
> There was no attack after the spell was cast; the attack took place before the spell was cast.

But there was an attack before the spell was cast, it should be retaliated and Blind doesn't prohibit the retaliation :)

> When a creature retaliates under the effect of a spell that prevents retaliation, there's a bug.

But when a creature doesn't retaliate because of a spell that doesn't prohibit the retaliation, this is not a bug :) Don't mix it up, yes? :) These are nothing more than attempts to adjust the game logic to certain personal preferences about what is "right" and what is "wrong".

**Comment by oleg-derevenetz** [comment]
@zenseii

> this might just be by design to not reduce the effect of this unique ability of the griffins

Yes, exactly. This is just a part of their unique ability, just like the non-retaliated Blind is a part of Unicorn's unique ability. No need to shuffle the "right" and "wrong" here and come up with far-fetched and one-sided "simple logical explanations".

**Comment by LeHerosInconnu** [comment]
@zenseii.

The Paladins/Crusaders and Wolves special attack is considered by the game as one attack with two strikes, per example, the Griffins replicate to the first strike and not to the second strike.

If Paladins/Crusaders or Wolves are paralyzed by Cyclops retaliation after their first strike, they don't perform their second strike.
If Paladins/Crusaders or Wolves are petrified by Medusa retaliation after their first strike, they don't perform their second strike.
If Paladins/Crusaders or Wolves are blinded by Unicorn retaliation after their first strike, they don't perform their second strike.
Everything works clearly, and it's easy to understand.
Spells take priority over the creature's ability, and as soon as a spell is cast, blind for the Unicorn, paralyze for the Cyclops, or petrify for the Medusa, the creature's ability is countered.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> > There was no attack after the spell was cast; the attack took place before the spell was cast.
> 
> But there was an attack before the spell was cast, it should be retaliated and Blind doesn't prohibit the retaliation :)

As I wrote above, the blind spell prevents any action until the targeted creature is attacked.
After the spell has been cast, the targeted creature has not been attacked; the attack took place before the spell was cast by the creature's ability.

> > When a creature retaliates under the effect of a spell that prevents retaliation, there's a bug.
> 
> But when a creature doesn't retaliate because of a spell that doesn't prohibit the retaliation, this is not a bug :) "Don't mix it up", right? :) These are nothing more than attempts to adjust the game logic to certain personal preferences about what is "right" and what is "wrong".

As I wrote already above, the blind spell prevents any action until the targeted creature is attacked.
After the spell has been cast, the targeted creature has not been attacked; the attack took place before the spell was cast by the creature's ability.
