### ISSUE TITLE
Combat screen, AI should consider and block the nearest ranged troops while attacking the target

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#7786]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

AI often ignores and doesn't block ranged troop nearby the target.

https://github.com/ihhub/fheroes2/assets/55348946/aabab954-6c64-4ce6-9840-59fbb4c5e408

Dragons could definitely land between titans and trolls to cover them both, but prefer calming down in a water (which reduces the defense).

### Describe the possible solution

If there is any ranged troop near target AI should place his attacking troop in such manner to prevent them from making ranged attacks.

**Comment by idshibanov** [comment]
I would even call this a bug, something is off with `PostionQuality`. It is supposed to be working..
