### ISSUE TITLE
Improve AI to find the fastest way

### ISSUE THREAD

**Issue by fheroes2bugs** [ihhub/fheroes2#7791]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Trajectory is not the fastest. Computer tries to find fasters trajectory, but he is not considering what would be, if he would visit object.

This is computer tries to find path:
![computer don't want to visit object to cut path](https://github.com/ihhub/fheroes2/assets/145407420/347f6422-e1d6-4e5d-bcd8-dc7e5946192a)

This is me, first visiting the object, then I continue my journey:

![I first visit the object and then coninue journey](https://github.com/ihhub/fheroes2/assets/145407420/0d78ca4c-3243-4036-97cb-9d580724e0ca)

[why not to visit object.zip](https://github.com/ihhub/fheroes2/files/12694338/why.not.to.visit.object.zip)

### Describe the possible solution

Computer should visit object, if it will help him to find the fastest way.

**Comment by oleg-derevenetz** [comment]
AI is able to do such a tricks for a very long time. But human player should perform such a cutting of corners on his own, because that's how it works in the original game (and in other well-known games of the HoMM series BTW). There is no need to turn this game into another modern single-button casual.

**Comment by ihhub** [comment]
@fheroes2bugs , the AI does visit objects "on the way" as mentioned by @oleg-derevenetz . We aren't going to introduce such "improvements" for human player. Therefore, I am closing this issue.
