### ISSUE TITLE
Improve AI for situations on using "Armageddon" spell

### ISSUE THREAD

**Issue by fheroes2bugs** [ihhub/fheroes2#7793]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

It would be very useful to defeat enemy if we have only immune monsters (i.e. dragons).
In this situation, AI is not using Armageddon, so enemy has fled. If AI would use it, we would win.

Here is AI not using "Armageddon" and enemy has fled, but when I use it - I win:

https://github.com/ihhub/fheroes2/assets/145407420/fd7bd95f-bff1-4f90-8563-69b8299d8efa

[teach armageddon.zip](https://github.com/ihhub/fheroes2/files/12694521/teach.armageddon.zip)

### Describe the possible solution

Teach AI to use "Armageddon" spell if we have only immune monsters (i.e. dragons).

**Comment by ihhub** [comment]
@fheroes2bugs , please play with Battle Only mode for any battle AI logic to verify your assumptions. The AI knows this spell.

**Comment by fheroes2bugs** [comment]
> @fheroes2bugs , please play with Battle Only mode for any battle AI logic to verify your assumptions. The AI knows this spell.

So, if AI knows this spell, may be it is bug? I tried it battle (magic using is ON), but he does not use magic in this battle at all.




https://github.com/ihhub/fheroes2/assets/145407420/d8b79a96-2eb6-4546-af29-00482bb3e561

**Comment by fheroes2bugs** [comment]
> Hi, @fheroes2bugs.
> 
> > So, if AI knows this spell, may be it is bug? I tried it battle (magic using is ON), but he does not use magic in this battle at all.
> 
> I wouldn't be so quick to call it a bug (:something implemented is not working as intended). The AI knows how to use armageddon and it will use it if it considers it useful. However, there are a couple of considerations in your battle above.
> 
> 1. The AI will try to avoid wasting unnecessary spell points if it knows it can win a battle. Casting armageddon would not change the win/loss outcome, and it costs a lot of mana.
> 2. The AI does not make its moves in order to hinder an opposing hero from retreating/surrendering - it makes its decisions as if the opposing hero won't retreat or surrender.
> 
> If there is a bug here then I don't see it. On the other hand, I see room for improvement in several areas. For example, 1. the AI should improve its tactics when it comes to stopping a hero from retreating.
> 
> 2. The AI should improve its use of the armageddon spell in the cases when it has only creatures immune to this spell, but this might already be in place. Maybe the AI would have used it if it felt threathened enough? I haven't worked with this part of the code enough to know this.
> 
> These are two separate improvements that would maybe lead to the AI behavior you want here. However, implementing them isn't very easy either.
> 
> The first thing I suggest is to rename the title of this issue, because the AI does already know how to use the spell, just not optimially in every situation. The title does not reflect what you are suggestion to improve.

Thank you for the answer. I can not comment, because have not seen AI ever used "Armageddon".
I don't argue if AI knows how to use it or not, on 0.8 I can see "Implementation of missing spell effects such as Lightning, Armageddon, Death Wave as well as fixing many others" - but personally, never have seen it.

Also, another battle, AI loses 9 dragons and don't use "Armageddon" - he uses "Berserk".

https://github.com/ihhub/fheroes2/assets/145407420/22b2ac2f-00c5-4792-8c7f-2e78f7643a3e



But if I use armageddon 2 times, have 0 dead dragons and enemy fled:


https://github.com/ihhub/fheroes2/assets/145407420/d0ef16bf-91d1-45b7-adc5-f969296696c3




Also, I edited the title of the issue. 

[AI uses berserk instead of armageddon.zip](https://github.com/ihhub/fheroes2/files/12696195/AI.uses.berserk.instead.of.armageddon.zip)
