### ISSUE TITLE
Teach AI to use marketplace

### ISSUE THREAD

**Issue by fheroes2bugs** [ihhub/fheroes2#7801]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Haven't found an issue, about marketplace.
AI can't use marketplace.

At map marooned AI (green) has a lot of strong neutral monsters surrounding him, and have town+marketplace. When I found him at 6 month, he had starting army and 2 heroes. He could trade gold for ore and build something, then buy units.

### Describe the possible solution

Teach AI to use marketplace

### Additional info

No save/video at this time.

**Comment by ihhub** [comment]
I'm closing this issue as @oleg-derevenetz imemented basic logic for the AI to use marketplaces to build castles.
