### ISSUE TITLE
Sorting saves in "load game" window

### ISSUE THREAD

**Issue by fheroes2bugs** [ihhub/fheroes2#7802]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

If I save game for number, 1, 2, 3 etc, I got after 1 - 11 and after 2 - 20.

![image](https://github.com/ihhub/fheroes2/assets/145407420/75cb3f3d-e968-4369-8be9-6d3f64bf91e2)

### Save file

In windows sorting works correct, that is the way it should be:
![image](https://github.com/ihhub/fheroes2/assets/145407420/a103ec7e-3c01-44e2-be05-bb2d221a4fc2)

**Comment by ihhub** [comment]
I am closing this issue as the sorting is done [lexicographically](https://en.wikipedia.org/wiki/Lexicographic_order). We aren't going to fix it.
