### ISSUE TITLE
Improve AI in battle (AI wants to protect range unit, but this is losing strategy)

### ISSUE THREAD

**Issue by fheroes2bugs** [ihhub/fheroes2#7803]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

AI wants to protect range unit, but this is losing strategy.

This is AI losing the battle:

https://github.com/ihhub/fheroes2/assets/145407420/0348b886-c440-4eb2-9c75-4757f19c10bc

This is me, winning the battle (i don't even use spells):

https://github.com/ihhub/fheroes2/assets/145407420/74079e41-02da-4419-9555-2399b0ec6865

### Describe the possible solution

Improve AI in battle, 1 unit can't protect range unit. If a range unit is far away, no need to bring them back, to "protect".

### Additional info

[AI loses and I am not.zip](https://github.com/ihhub/fheroes2/files/12705411/AI.loses.and.I.am.not.zip)

**Comment by Branikolog** [comment]
Hi, @fheroes2bugs 

It's not loosing strategy. Running away from the castle, while my ranged troops shoot the defenders is not a bad strategy and I use it commonly to save my flying troops. It is especially effective if defending troop is quite slow.

In such edge cases even a single lucky hit could bring the victory. I've made lots of battling tests recently and find out, that, for instance, the damage of the first strike could completely change the battle outcome. I've tested a huge stack of ghosts (~150) against 10 titans, and when I've changed starting conditions a little bit and my attacking stack, did minimal damage - I lost the battle. But when my stack of ghosts did considerable damage I managed to win even with 50+ ghosts left. So in the example from the video the difference of a few strikes could bring the different outcome. Therefore, to say that this tactic is wrong, you need to run dozens of tests or test on creatures with minimal damage spread.

**Comment by fheroes2bugs** [comment]
> Hi, @fheroes2bugs
> 
> It's not loosing strategy. Running away from the castle, while my ranged troops shoot the defenders is not a bad strategy and I use it commonly to save my flying troops. It is especially effective if defending troop is quite slow.
> 
> In such edge cases even a single lucky hit could bring the victory. I've made lots of battling tests recently and find out, that, for instance, the damage of the first strike could completely change the battle outcome. I've tested a huge stack of ghosts (~150) against 10 titans, and when I've changed starting conditions a little bit and my attacking stack, did minimal damage - I lost the battle. But when my stack of ghosts did considerable damage I managed to win even with 50+ ghosts left. So in the example from the video the difference of a few strikes could bring the different outcome. Therefore, to say that this tactic is wrong, you need to run dozens of tests or test on creatures with minimal damage spread.

>It's not loosing strategy.
Well, that is why I did this videos and attached the replay.
So, if the enemy unit is slow, our flying units can go protect range units, but if enemy have 5-6 speed unit, it will lead to bigger loss, as we can see in the videos. Sure, not all the cases, but in my situation it is a question of will I win the whole game or lose it.

**Comment by ihhub** [comment]
Closing this issue as fixed.
