### ISSUE TITLE
Articaft/resource is not visible because of the rocks

### ISSUE THREAD

**Issue by fheroes2bugs** [ihhub/fheroes2#7805]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Can't actually tell if it is bug or creators of the game did it intentionally, but sometimes artifact is behind the rock, I click on it - see "artifact", but don't know what is the name of the artifact...

![image](https://github.com/ihhub/fheroes2/assets/145407420/504aaae0-9d9f-4813-91a6-ea55666a1f00)

### Save file

I suggest to add name of the artifact to the window (when pressing the right key of the mouse).
![image](https://github.com/ihhub/fheroes2/assets/145407420/2ebf1aed-6f01-4a85-8928-a882069e453b)

**Comment by ihhub** [comment]
This is not a bug, this is the correct behavior of rendering items. The artifact is **behind** the mountain so you shouldn't see it easily.
