### ISSUE TITLE
Hero info window, morale modifiers pop-up window is too large

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#7818]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

With the latest versions morale info window became too big:
![image](https://github.com/ihhub/fheroes2/assets/55348946/7cc7cdfd-4ce5-4c0d-b8b9-88c371880f0e)
![image](https://github.com/ihhub/fheroes2/assets/55348946/23f7efa1-13b0-4e91-8f03-da45e1dd0e62)

A version a few weeks ago doesn't have such issue:
![image](https://github.com/ihhub/fheroes2/assets/55348946/bda6f8ca-190b-447b-bbac-4569347b8dcc)

### Save file

None.

**Comment by Branikolog** [comment]
@ihhub 
It happened somewhere between 11 and ~18 of September. Cannot tell more exact, as there was a week, when I didn't installed fheroes2 from master branch. But it definitely happened after 1.0.8 release.

**Comment by oleg-derevenetz** [comment]
It seems that it happened after #7753.

**Comment by ihhub** [comment]
Hi @Districh-ru , could you please take a look at this issue when you have time?

**Comment by Districh-ru** [comment]
Hi @ihhub, sure. I'll try to fix it today.
