### ISSUE TITLE
Game crashes when starting mission 3 from "The Good" original campaign

### ISSUE THREAD

**Issue by PhilippKilian** [ihhub/fheroes2#7821]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

# steps to reproduce

- start game version 1.0.8 used with Heroes II Gold v1.01
- Load "Good 2 complete"
![Bildschirmfoto vom 2023-09-25 21-52-48](https://github.com/ihhub/fheroes2/assets/43444352/0c469a04-b886-420d-bee6-40184e50a37c)
- choose Mission 3, hard mode
![Bildschirmfoto vom 2023-09-25 21-50-26](https://github.com/ihhub/fheroes2/assets/43444352/eb98b0a4-4d53-41b0-ac7e-e0db748f13ec)
![Bildschirmfoto vom 2023-09-25 21-50-43](https://github.com/ihhub/fheroes2/assets/43444352/753be533-d002-43a5-9402-001f596c62b8)
- when starting the mission, the games crashes

### Save file

Don't know how to provide this file (couldn't figure out the location of this file). Would provide it when given a hint, where I can find it...

```
~/Games/fheroes2 » ls
anim/
data/
extract_homm2_resources.sh
files/
maps/
README.txt
changelog.txt
download_demo_version.sh
fheroes2
LICENSE
music/
script/
```

### Additional info

when using the release file 1.0.8:

```
~/Games/fheroes2 » ./fheroes2        
fheroes2 engine, version: 1.0.8
fheroes2: ../fheroes2/maps/maps_tiles.cpp:515: void Maps::Tiles::Init(int32_t, const MP2::mp2tile_t&): Assertion `( ( ( mp2.quantity2 << 8 ) + mp2.quantity1 ) >> 3 ) == 0' failed.
[1]    12445 IOT instruction (core dumped)  ./fheroes2
```

when using the last develop file (still version 1.0.8):
```
~/Games/fheroes2 » ./fheroes2                                134 ↵
fheroes2 engine, version: 1.0.8
fheroes2: ../fheroes2/maps/maps_tiles.cpp:491: void Maps::Tiles::Init(int32_t, const MP2::mp2tile_t&): Assertion `_metadata[0] == 0' failed.
[1]    12652 IOT instruction (core dumped)  ./fheroes2
```

**Comment by ihhub** [comment]
Possible regression from #7796 .

**Comment by ihhub** [comment]
Hi @PhilippKilian , it seems that this map is corrupted or has invalid map format. The assertion was made exactly to catch this issue and we tested literally several hundreds official maps for this check.

Could you please tell us where did you get this version of the game?

**Comment by PhilippKilian** [comment]
@ihhub It's the Version from [gog.com](https://www.gog.com/de/game/heroes_of_might_and_magic_2_gold_edition)

To check if a map was corrupted or invalid, i backup my maps folder and replaced the files with the ones from the original download. Now the Mission starts normally:

![grafik](https://github.com/ihhub/fheroes2/assets/43444352/ffa91ee9-073c-4472-9cf4-8c9afda6fdc8)

**Comment by ihhub** [comment]
@PhilippKilian , was it a German version you were using before?

**Comment by PhilippKilian** [comment]
> @PhilippKilian , was it a German version you were using before?

@ihhub It's still the German version. But some mission text boxes are in english. Don't know why.

**Comment by ihhub** [comment]
This is definitely the problem with map format:
```
******* Tile info *******
Tile index      : 1837, point: (37, 25)
UID             : 0
MP2 object type : 20 (Dragon City)
ICN object type : 0 (UNKNOWN)
image index     : 255
layer type      : 0 - Object layer
region          : 10
ground          : Snow (isRoad: 0)
ground img index: 136, image flags: 0
shadow          : false
passable from   : center, top, top-right, right, bottom-right, bottom, bottom-left, left, top-left
metadata value 1: 0
metadata value 2: 0
metadata value 3: 0
--------- Level 2 --------
UID             : 1820
ICN object type : 41 (OBJNMUL2.ICN)
image index     : 34
layer type      : 0 - Object layer
is shadow       : yes
--- Extra information ---
*************************
```

There is no object at this tile. The same structure for the 'fixed' map.
