### ISSUE TITLE
hotkey menu is too narrow

### ISSUE THREAD

**Issue by fheroes2bugs** [ihhub/fheroes2#7829]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Hotkey menu is too narrow.
![2023-09-28_003707](https://github.com/ihhub/fheroes2/assets/145407420/19845888-e17d-4b10-b8b5-d7f3d65e406d)

### Describe the possible solution

Make it wide, so everything could be seen.
PS I know than if you click on the line, appears a new window, where you can see full line.

**Comment by ihhub** [comment]
Hi @Districh-ru , how difficult would it be to implement this?

**Comment by Districh-ru** [comment]
Hi @ihhub, it should not be difficult - the changes are mostly the same as we done for the save/load dialog.

**Comment by fheroes2bugs** [comment]
Still not everything visible:
![image](https://github.com/ihhub/fheroes2/assets/145407420/b67a3f4c-e125-4e76-b1a4-0be82688648c)

Now it looks wide enought, but the text is still too long for it.
**May be just create a transfer to second line?**

Anyways, thanks for the upgrade, it looks better now.

**Comment by ihhub** [comment]
@fheroes2bugs , there always will be situations when a certain text is longer than a window length. We can't cover all possible situations. You can right click on it to see the full text.

**Comment by Branikolog** [comment]
I agree with @ihhub 
1 string for 1 hotkey looks better and takes less space, than dividing the name of the function into several lines. The list will look intermittently then.
