### ISSUE TITLE
Fix german translation of the dungeon

### ISSUE THREAD

**Issue by erazortt** [ihhub/fheroes2#7848]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Currently the dungeon is translated by the word "Verlies".
https://github.com/ihhub/fheroes2/blob/f71ce3d60dae82e1c64f67ef63a67c42f4d255d2/files/lang/de.po#L2282

The current info screen shown for the dungeon does not translate the word "Dungeon" at all:
https://github.com/ihhub/fheroes2/blob/f71ce3d60dae82e1c64f67ef63a67c42f4d255d2/files/lang/de.po#L2413

### Describe the possible solution

While "Verlies" is pretty much ok as a translation, the original game used the somehow less generic term:
Burgverlies

Independently of whether using "Verlies" or "Burgverlies", the infotext about this should be using that same transaltion:
Das Burgverlies erhöht...
If you prefer using the shorter variant "Verlies" then the text would be:
Das Verlies erhöht...

### Additional info

I am comparing with my orignal german DOS game which I have running in DOSBox.

**Comment by ihhub** [comment]
Hi @erazortt , would you like to help with the translation?

**Comment by erazortt** [comment]
Hey, as I have found more instances of necessarz translation fixes I have decided to go through the whole german translation file, comparing it to the strings of the original game. I think I have gone through about half of the file right now.
I will create a new issue including an upload of my edited file once when I'm done.

**Comment by ihhub** [comment]
I am closing this issue as we have a bunch of PRs to cover the whole German translation.
