### ISSUE TITLE
Re-running Battle Only should give you the same setup

### ISSUE THREAD

**Issue by bleakley** [ihhub/fheroes2#7876]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

A common use case for Battle Only is testing the same setup with minor variations or changes in tactics. Most of the time a player selects that option they will want to try the same thing again.

### Describe the possible solution

The default behavior should be to reload the last battle. Next to the "Okay" button could be "Reset" button to clear out all changes and revert to the default loadout.

**Comment by LeHerosInconnu** [comment]
There's so much to do for the "BATTLE ONLY" mode. :0 :D
