### ISSUE TITLE
"Manage creatures" button's shadow

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#788]
Shadow surrounding button looks weird. I suppose this button should look similar to the "No" button on the same window: without black contour.
![Manage](https://user-images.githubusercontent.com/55348946/84564878-c8324680-ad6d-11ea-93fc-4fa4d4ebcb12.jpg)

**Comment by Branikolog** [comment]
Also, i think we should add right click pop up window over it, so user could find out, what happens, after it being pressed.

**Comment by ihhub** [comment]
We need to create a new button just for this case as the original one has black background.
