### ISSUE TITLE
Combat screen, spell information window, remove spell cost shown in square brackets "[1]" for petrification spell (medusa ability)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#7880]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

I suggest to remove the spell cost shown in square brackets "[1]" for petrification spell (medusa ability).

This spell has no cost as such, since it cannot be cast by a hero.
The cost of 1 spell point displayed in square brackets "[1]" may lead the player to believe that the spell costs the hero one spell point when the medusa triggers its petrification ability.

In fheroes2:

![Petrification sprite 01](https://github.com/ihhub/fheroes2/assets/43583994/92acb1f1-1756-4f16-b90b-f36ad80c57bb)

Here is the save file:
[Alamar Troyan medusa 01.zip](https://github.com/ihhub/fheroes2/files/12829381/Alamar.Troyan.medusa.01.zip)

### Describe the possible solution

Remove the spell cost shown in square brackets "[1]" for petrification spell (medusa ability).

### Additional info

Version 1.0.8 7767

**Comment by roman-yagodin** [comment]
Seems like fixed by https://github.com/ihhub/fheroes2/commit/40f405d267d8c8512a2ec0dd3446b306b27a1c3d. If it isn't a hero spell, use unmodified spell points value (which is 0 for Petrification):

```C++
if ( hero == nullptr ) {
        return spells[id].spellPoints;
    }
```

![petrify](https://github.com/ihhub/fheroes2/assets/5691178/8edef687-ace4-4337-b2cd-65b678a4523d)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , can you please test it on the latest version?

**Comment by ihhub** [comment]
Closing this issue as completed:
![image](https://github.com/ihhub/fheroes2/assets/19829520/680e9f57-9eee-4973-8509-abe1f8590d85)
