### ISSUE TITLE
Cannot cast "Anti-Magic" spell over unit being cloned

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#789]
If you cast "Mirror Image" spell over any unit, you cannot cast "Anti-Magic" spell, over it, until clone dies.
![Anti](https://user-images.githubusercontent.com/55348946/84565202-3972f900-ad70-11ea-91ce-51555a18e4fd.jpg)

**Comment by idshibanov** [comment]
Not sure how it works in OG, but this actually makes some sense from logic perspective. Anti-magic blocks both good and bad spells.

**Comment by Branikolog** [comment]
In the OG anti magic spell can be cast on a unit, which already has mirror image. And after that you cannot cast any other spell over it. 
In our version we cannot cast anti magic over unit, that has mirror image. 
There is also other point of logic: mirror image spell creates separate magic creature. Fragile creature. But it is not associated with the main creature anymore. If it would, it would have all spells and effects applied to the primal creature.

**Comment by LeHerosInconnu** [comment]
Hello @idshibanov and @Branikolog,

This is how the Mirror Image spell works in the original game:
- The mirror troop is destroyed if it takes physical damage or magic damage.
- If the original troop is decimated, the mirror troop is destroyed as well.
- If positive or negative spells were already active on the original troop before the mirror spell was cast, they are not carried over to the mirror troop (the mirror troop has no active spells).
- Positive or negative spells can be cast on the mirror troop.
- The Anti-Magic spell cannot be cast on the mirror troop.
- All positive or negative spells can be cast on the original troop after the Mirror Image spell is cast.
- The Anti-Magic spell can also be cast on the original troop after the Mirror Image spell is cast.
- The Mirror Image spell cannot be cast on the mirror troop.
- The Mirror Image spell cannot be cast again on the original troop while the mirror troop is still present.

I made a proposal for an option on the possibility of casting the Anti-Magic spell on a mirror troop: https://github.com/ihhub/fheroes2/discussions/2638.
