### ISSUE TITLE
File Options, File to Save, Mouse-operated keyboard window, there is a graphic default on the up arrow of the "Shift" button

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#7895]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

In fheroes2, there is a graphic default on the up arrow of the "Shift" button.

In fheroes2:

![Mouse keyboard 01](https://github.com/ihhub/fheroes2/assets/43583994/cb7c3d2b-a012-4928-873a-1271ce491be9)

Default at the bottom of the graphic, at the vertical part of the upward-pointing arrow:
![Mouse keyboard  Maj key default 01](https://github.com/ihhub/fheroes2/assets/43583994/55e50472-7309-4182-816f-3e9ed823dbaf)

### Describe the possible solution

Correct the default.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , what exactly is wrong with the button? Please point precisely the place which has an issue.

**Comment by oleg-derevenetz** [comment]
This is a sort of a "Caps Lock" icon, and not the regular arrow:

![caps-lock-icon-29](https://github.com/ihhub/fheroes2/assets/32623900/9f5521af-e9cb-47a4-9506-767622e0426d)

And it is perfectly justified, because this button is "sticky".

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , what exactly is wrong with the button? Please point precisely the place which has an issue.

The arrow seems to be "cut" at the bottom, in a way that adds nothing visually, except that it is perceived as a display fault.

Even if the current representation could be valid, the sprite definition in fheroes2 doesn't allow the display to emerge clearly or correctly.
In that case, we might as well use a standard, well-known representation, which doesn't pose any problems for the display due to the sprite definition in fheroes2.

Here's an example of the standard representation:

![](https://www.komando.com/wp-content/uploads/2023/01/dreamstime_l_23226525.jpg)

Other examples shown in a famous search engine:

https://www.google.com/search?q=shift+key&tbm=isch&ved=2ahUKEwiByubzoeSBAxWhtycCHWIODXYQ2-cCegQIABAA&oq=shift+key&gs_lcp=CgNpbWcQARgAMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIECAAQHjIECAAQHjIECAAQHjoHCAAQigUQQzoICAAQsQMQgwE6CAgAEIAEELEDOgsIABCABBCxAxCDAToKCAAQigUQsQMQQ1DSDVjPOmCrTGgAcAB4AIABVogB1gWSAQIxMJgBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=9XohZcH7MqHvnsEP4py0sAc&bih=1028&biw=1920

**Comment by ihhub** [comment]
I am closing this issue as per @oleg-derevenetz explanation why we chose this icon for the button.
