### ISSUE TITLE
Remove src/tools/palette_h2.h file

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#79]
We have the same file in `src/tools/palette_h2.h` and `src/fheroes/agg/palette_h2.h` files. We want to remove code duplication so we remove file in `tools` and use another file in `src/tools/icn2img.cpp` file.

**Comment by Rhuancpq** [comment]
Can I try this?

**Comment by ihhub** [comment]
@Rhuancpq sure!
