### ISSUE TITLE
Adventure map, town portal spell window extension

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#7906]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

![image](https://github.com/ihhub/fheroes2/assets/55348946/f40fc8a7-d4ef-48ff-8285-629b9df6502f)
The castle list is too small for such screen size.

### Describe the possible solution

Town portal window could be adjusted according resolution selected.
I suggest adding a few more lines into the Town Portal spell UI. The same as was implemented for save file list.
On the screen game is running on ...x600. The castle list could be extended for 2-3 lines here (but not making it too long).

**Comment by ihhub** [comment]
We can use the same UI code which we utilize for the Editor and for Battle Only mode.
