### ISSUE TITLE
Castle Construction screen, transition to Castle screen, there's a sort of black frame effect around the Castle screen when a building is constructed

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#7913]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, there's a sort of black frame effect around the Castle screen when a building is constructed and the game switches from the Castle Construction screen to the Castle screen.

This is not systematic.
And it's hard to spot by recording a video of the game (it didn't happen with a recent version).
I've also noticed it when watching let's play fheroes2 videos on the Internet.
I'll add a link to an online video when I find one where the phenomen is easily visible.

In fheroes2:
From this screen:
![Black frame effect 001](https://github.com/ihhub/fheroes2/assets/43583994/3a2fc8e4-aa9f-45dd-9e3c-9ee753ee4a8b)

To this screen:
![Black frame effect 002](https://github.com/ihhub/fheroes2/assets/43583994/7543312b-f4cb-4bd5-8468-1bd7d464935d)

Approximate era of the effect:
![Black frame effect area red 002](https://github.com/ihhub/fheroes2/assets/43583994/496fc98d-cfb7-4a29-a083-f406e5294745)

### Save file

Not needed.

### Additional info

Version 1.0.8 7846

**Edit 2023/10/10.**

It's easy to see the flaw in the transition effect [here](https://youtu.be/7K0GQsdu5xg?t=6080).

![Screen transition default coupé 01](https://github.com/ihhub/fheroes2/assets/43583994/f4ce3545-ad94-4a2e-a551-57d32dda2ca2)

**Comment by Districh-ru** [comment]
Trying to reproduce this issue i found that sometimes only a part of castle screen is rendered for one frame after the build dialog is closed:
![изображение](https://github.com/ihhub/fheroes2/assets/113276641/d073e5bb-85fd-492c-be95-80f9e8c88240)

**Comment by ihhub** [comment]
I believe this is due to cycling animation.

**Comment by Districh-ru** [comment]
> I believe this is due to cycling animation.

This is because of `StatusBar::ShowMessage()` - it updates display in a `ROI` (it includes previous ROI - the building dialog and the new ROI - the status bar) and only then the castle dialog updates the whole display while doing the build animation.
I'll try to fix this.
