### ISSUE TITLE
Adventure map, castle and hero right click info windows, creature sprites overlap

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#7927]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, creature sprites overlap in castle and hero right click info windows.

In fheroes2:

![Creatures overlap 001](https://github.com/ihhub/fheroes2/assets/43583994/bdd5d9f4-07c0-484e-b605-e6daa5b5d398)

![Creatures overlap 002](https://github.com/ihhub/fheroes2/assets/43583994/fa2ef253-b2dd-4842-963e-70491a1f55d3)

### Save file

Here is the save file:
[Info right clic buzz 01.zip](https://github.com/ihhub/fheroes2/files/12870605/Info.right.clic.buzz.01.zip)

### Additional info

Version 1.0.9 7923

**Comment by ihhub** [comment]
This is a regression from #7859.

**Comment by ihhub** [comment]
Hi @Districh-ru , could you please take a look at this issue?

**Comment by Districh-ru** [comment]
Hi @ihhub, sure)
