### ISSUE TITLE
Campaigns scenario difficulty selector

### ISSUE THREAD

**Issue by idshibanov** [ihhub/fheroes2#793]
We should add a difficulty selector (similar to Heroes 3) to every campaign scenario. Final score for the highscore table shouldn't be only in days then: sum up regular scoring for every scenario (that takes into account both difficulty and days).

I believe most campaign scenarios assume Normal-Hard difficulties. This will allow for a more challenging playthrough if one desires. Then we don't have to worry about AI changes breaking campaign balance.

**Comment by ihhub** [comment]
Making it as a part of beyond 1.0 scope.

**Comment by ihhub** [comment]
Closing this issue as it was implemented completely in the past.
