### ISSUE TITLE
Combat, Hero screen, right click hero info window, wrong window displayed

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#7930]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the wrong window is displayed in the Hero screen with a right click on the hero portrait during combat.
The human hero was attacked during the AI's turn.

In fheroes2:

![Hero info combat 001](https://github.com/ihhub/fheroes2/assets/43583994/52b1516a-b360-477b-b135-9618b3f0ac5b)

Access the hero's screen by left-clicking on his portrait.
![Hero info combat 002](https://github.com/ihhub/fheroes2/assets/43583994/05665eba-8f6a-4a92-8cb2-2f473c1c3b84)

![Hero info combat 003](https://github.com/ihhub/fheroes2/assets/43583994/14916c58-60eb-41db-860e-ec456a54f7f7)

This is the window which should be displayed:
![Hero info combat 004](https://github.com/ihhub/fheroes2/assets/43583994/5187007f-cbd1-46f9-a133-1fe844c41986)

### Save file

Here is the save file (end the turn):
[Before hero info window 01.zip](https://github.com/ihhub/fheroes2/files/12882772/Before.hero.info.window.01.zip)

### Additional info

Version 1.0.8 7846

**Comment by oleg-derevenetz** [comment]
> It also seems weird that it reports creatures as few and not as numbers as it should when you're viewing your own troops.

This is because the corresponding "quick info" window logic compares the hero's color with the color of the kingdom, whose turn is it now, and since now it is AI turn, it shows approximate numbers instead of exact numbers.

**Comment by LeHerosInconnu** [comment]
Hello @zenseii,

> Hi, @LeHerosInconnu. I have a vague memory that you've reported this before. I also personally find it useful to refer to the inbattle hero window to know what the starting troops were.

> The description is also not entirely clear to me. Is the problem that the info should be for the hero Kastore and not Agar? It also seems weird that it reports creatures as few and not as numbers as it should when you're viewing your own troops.

It's during the AI tour that the correct window is not displayed.
I've edited the original post to precise this and added a save file (while you were posting your messages). :)

The last image is just a reference to the hero's standard right-click information window.
The starting troops of the hero's army are visible in the hero's screen, as it is not updated with combat losses at the moment.
