### ISSUE TITLE
Add Flathub verification

### ISSUE THREAD

**Issue by Mr-Bajs** [ihhub/fheroes2#7938]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

The flathub version is unverified by the developers. I don't know who does the flatpak version on flathub, but if it's an developer from here then adding a verification that confirms it's a developer or a trusted party by the developer thats behind the version on flathub would be nice.

https://flathub.org/apps/io.github.ihhub.Fheroes2
https://docs.flathub.org/docs/for-app-authors/verification

### Describe the possible solution

Adding verification to the flathub version.

**Comment by oleg-derevenetz** [comment]
AFAIK @Laserlicht is the maintainer of the Flathub fheroes2 distribution. But I could be wrong.

**Comment by Laserlicht** [comment]
Yes. There are two possibilities:
- Create the page  https://ihhub.github.io/.well-known/org.flathub.VerifiedApps.txt with token. Is that possible?
- @ihhub can try to login here with Github and approve (should be possible!?): https://flathub.org/apps/manage/io.github.ihhub.Fheroes2

**Comment by ihhub** [comment]
@Laserlicht and @Mr-Bajs , done.
