### ISSUE TITLE
Battle: add a window with a retreat question

### ISSUE THREAD

**Issue by fheroes2bugs** [ihhub/fheroes2#7944]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

As far as I remember, in original heroes 2, if it autobattle enabled, if you are going to lose, appears a window with a question: will you retreat or die?

In fheroes2 I just lose the battle and lose the hero:

https://github.com/ihhub/fheroes2/assets/145407420/c9b15ff8-e02a-444a-94bb-b4aeed0ed133

### Describe the possible solution

Add this window

### Additional info

version 1.09

save: 
[window retreat.zip](https://github.com/ihhub/fheroes2/files/12907818/window.retreat.zip)

**Comment by ihhub** [comment]
The window exists in the game. The AI needs changes in logic which are going to be addressed in #7344 .

I'm closing this issue as duplicate.

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , do we intend to implement this? I think such "improvement" makes the game more casual, where players just play the game with the AI doing everything.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub I think definitely not in the near future. Maybe someday later, when there will be clear justifications for the necessity of this feature. The losing player in most cases will not retreat, but load the last save and try to replay the battle manually hoping for better result or surrender for money.
