### ISSUE TITLE
Battle: position a high of number of creatures

### ISSUE THREAD

**Issue by fheroes2bugs** [ihhub/fheroes2#7953]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Attack side always have number of creatures postioned very low:
![image](https://github.com/ihhub/fheroes2/assets/145407420/2c3d147e-86f3-4ff7-813c-eba253a6c6b3)

That is the reason, when sometimes number is not visible:
![image](https://github.com/ihhub/fheroes2/assets/145407420/d7df0c23-f90c-454c-96a6-5e1118171666)

### Describe the possible solution

Make the number in the center of the cell.
I can see no logic for low position for attacking side.

### Additional info

version 1.09

**Comment by oleg-derevenetz** [comment]
> Make the number in the center of the cell.
I can see no logic for low position for attacking side.

The logic is obvious - consider the situation when attacking and defending units are standing on adjacent cells face to face:

![numbers](https://github.com/ihhub/fheroes2/assets/32623900/87432dc2-b885-453a-b7bb-0577e7d36d62)

If both numbers were in the center of the cell, they would overlap.

**Comment by fheroes2bugs** [comment]
what about moving the number to the top of the cell?

**Comment by oleg-derevenetz** [comment]
> what about moving the number to the top of the cell?

If you look at my screenshot more closely and try to mentally move the dragons' unit count indicator to the top of the cell, you will see that it will partially overlap the sprite of the elves (and many other sprites as well), which looks ugly. This is also very obvious.

**Comment by ihhub** [comment]
I am closing this topic as nothing we need to do: this is the same as in the original game.
