### ISSUE TITLE
Screen jumps in a certain cells while hero moving

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#797]
While hero moves on a world map, at some places screen starts jumping between two cells, until hero passes that place.

**Comment by idshibanov** [comment]
Can confirm, it happens quite often, especially during diagonal move.

**Comment by ihhub** [comment]
I'm working on this. The problem is in calculation of visible area for the World Map.

**Comment by Branikolog** [comment]
I've noticed this bug occurs on certain lines through the whole map. If hero moves by one cell you can notice, that focus is shifting (up) for about one cell on this line. The next step focus returns to hte hero.
