### ISSUE TITLE
Cannot build a boat in a specific castle

### ISSUE THREAD

**Issue by amty** [ihhub/fheroes2#7970]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

In the castle Erliquin (the last of three castles owned by a player, a wizard's one) it is impossible to build a boat. If you try game takes your resources for a boat, game plays a sound of a boat materializing but it turns out it is a fraud, no boat created.

### Save file

[bug.zip](https://github.com/ihhub/fheroes2/files/13059558/bug.zip)

**Comment by oleg-derevenetz** [comment]
With the latest snapshot, game doesn't take the resources for a boat (although the sound of buying a boat is playing). The problem here is that there is the `OBJ_TREES` object in the only water tile nearby. Hi @ihhub since you are an expert regarding map processing, is this legitimate?
