### ISSUE TITLE
Castle screen, action not possible in hero's army after hero recruitment

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#7977]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, there is no action possible in hero's army after hero recruitment.

Recruit Charity at Olympus.
It is not possible to perform actions in Charity's army, or from Charity's army to the garrison, or from the garrison to Charity's army.

In fheroes2:

https://github.com/ihhub/fheroes2/assets/43583994/0e2ee493-1116-4b2c-bb9b-f6d1040343d7

### Save file

Here is the save file:
[Broken_Alliance_0023.zip](https://github.com/ihhub/fheroes2/files/13061297/Broken_Alliance_0023.zip)

### Additional info

Version 1.0.9 7974

**Comment by Districh-ru** [comment]
This is a regression after https://github.com/ihhub/fheroes2/pull/7960 :(
