### ISSUE TITLE
Wrong behavior of the "Continue Movement" button

### ISSUE THREAD

**Issue by oleg-derevenetz** [ihhub/fheroes2#7987]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

The first problem that is 100% reproducible for me:

https://github.com/ihhub/fheroes2/assets/32623900/e44bea7a-cbc0-44ad-b75c-d3f22375d062

The second problem that is 100% reproducible for me as well:

https://github.com/ihhub/fheroes2/assets/32623900/a4d4532d-ac12-4e9b-85fd-a96215ff33c8

Both save files are attached to this issue.

### Save file

[save.zip](https://github.com/ihhub/fheroes2/files/13127806/save.zip)

**Comment by oleg-derevenetz** [comment]
Hi @Districh-ru could you please take a look when you have the opportunity?

**Comment by Districh-ru** [comment]
Hi, @oleg-derevenetz. I'll take a look today evening.

**Comment by Districh-ru** [comment]
@oleg-derevenetz, it seems that "hero action" button image is not generated.
This generation is skipped if ICN::ADVBTNS has other than 16 images and image width and height are not equal to 32.
What game assets do you use?

**Comment by oleg-derevenetz** [comment]
Hi @Districh-ru I use official GOG assets from DOS version. Please note that in my video this button is in fact generated, but later it disappear.
