### ISSUE TITLE
Adventure map, hero list bug after dismissing a hero

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#7989]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

https://github.com/ihhub/fheroes2/assets/55348946/96478c3d-a7b3-4f9e-a688-3b1cd5de4c43

Hero list has multiple issues when a hero is dismissed through kingdom overview window.

Current hero selection disappears. 
Hero list is not updated properly.

### Save file

[Hero list.zip](https://github.com/ihhub/fheroes2/files/13166232/Hero.list.zip)

**Comment by ihhub** [comment]
Hi @Branikolog , is it reproducible on 1.0.9?

**Comment by Branikolog** [comment]
@ihhub 
Yes.
