### ISSUE TITLE
Combat, ranged troop behaviour in a case of forthcoming blocking

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#7992]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

If Centaurs cannot kill the stack, which is about to block them - they prefer to run.

https://github.com/ihhub/fheroes2/assets/55348946/1cd47cd7-464d-4a9f-97b8-0fd03a1687c8

In a case they can kill the stack, which is about to block them, they made a shot.

https://github.com/ihhub/fheroes2/assets/55348946/9449731c-4228-45ec-8132-eb3c47267007

But it is not always necessary shot:

https://github.com/ihhub/fheroes2/assets/55348946/ce1e8429-9950-432a-8b87-e466c35865bb

### Describe the possible solution

I suggest opposing Centaur to attack anyway, even if he cannot kill the entire stack. There's no point running away from a few troops left, which cannot do a significant damage to the defending stack. The worse scenario here is when player would simply block ranged defending troop, in that case defending troop loses nothing while killing it on the next turn.

I cannot suggest the exact values, but defending ranged troop could continue shooting at about-to-block attacker (not running from it) if it is possible to kill him in 1 hit in melee fight (the next turn or by retaliation). It could be even more strong attacker, since there could be an assistance from other allied troops, but the attacking troop should be weak enough not to make significant damage to the defending ranged troop).

I also suggest defending ranged troop focusing the most dangerous attacking stack anyway, rather than running from or killing a weak stack which is about to block the defending ranger troop. In my example above Centaurs could attack Rangers and prevent losses, but they decided to attack weak walking centaur and allowed Rangers to shoot once.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog this behavior should be changed by #7986.

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz 
Oh, sorry, missed this items in the PR!
Should I close it now?

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog that PR fixes the excessive desire to retreat from archers or too slow units, but archers will still shoot at possibly blocking stacks.

> I also suggest defending ranged troop focusing the most dangerous attacking stack anyway, rather than running from or killing a weak stack which is about to block the defending ranger troop. In my example above Centaurs could attack Rangers and prevent losses, but they decided to attack weak walking centaur and allowed Rangers to shoot once.

This is a rather vague wish. If we follow this literally, then the stack never need to retreat at all, because the default behavior is to just attack the most dangerous attacking stack.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Indeed.
But in some cases this logic allows to demolish the significant amount of troops, just because ranged troop made the first, especially effective shot.
You know, I'm doing quite a lot of tests and in some cases, when comparable armies are met, the only non-optimal decision can cause an absolutely different outcome. I've recently pushed two large stacks of troops against each other and the battle could be finished either with victory or loss just because of the early first attack dispersion. And the number of troops left was even far from minimal. So the success of the first attack had a drastic influence on the outcome.

So I suggest to make a few checks in the case some troops are going to block the ranged defending one.
The first check should consider the potential losses, when the attacking melee troop reached defending one. If the damage is not really high, and the ranged troop could kill attacker with retaliation or with 1-2 melee attacks then lower the attacking priority for attacker in favor of dealing the damage to other threatening troops.
And the second check should consider whether any troop of attacking side can do a high damage right in the current turn (after the defending ranged troop).
Currently, AI behaves properly in this regard, when opposing two stacks, that can both reach him:

https://github.com/ihhub/fheroes2/assets/55348946/2ec31905-e400-4482-9612-e3d5db9cee09

But in the case of ranged attacking stack, AI ignores him focusing the potential blocking one instead:

https://github.com/ihhub/fheroes2/assets/55348946/75b07440-1c45-43ee-a55f-44030ca32a42

**Comment by oleg-derevenetz** [comment]
> So I suggest to make a few checks in the case some troops are going to block the ranged defending one.
The first check should consider the potential losses, when the attacking melee troop reached defending one. If the damage is not really high, and the ranged troop could kill attacker with retaliation or with 1-2 melee attacks then lower the attacking priority for attacker in favor of dealing the damage to other threatening troops.
And the second check should consider whether any troop of attacking side can do a high damage right in the current turn (after the defending ranged troop).

After some thought, I decided to remove the corner-case heuristics of this kind completely within the scope of #7986. This PR in any case tightens the requirements for when a shooting unit should retreat.

**Comment by oleg-derevenetz** [comment]
I suppose that we can close this because #7986 addressed all the described misbehaviors:

https://github.com/ihhub/fheroes2/assets/32623900/7cd88cff-937d-46f3-8fc1-bd4a6eb307c7

https://github.com/ihhub/fheroes2/assets/32623900/6660cb49-1302-4daf-8308-a940a9bd0f25

**Comment by ihhub** [comment]
@Branikolog , please check and close this issue is needed.

**Comment by Branikolog** [comment]
The problem of inadequate maneuvering of archers on the battlefield is no longer relevant.
Target selection is better now too.
Thanks, @oleg-derevenetz , for improving the battle AI! I'm pretty sure, a huge part of players are not even aware of using such tricks during battles. Auto battles will soon make manual battles redundant with such an efficacious logic. :)
