### ISSUE TITLE
Cursor image doesn't match its actual position 

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#802]
I've noticed, that cursor changes its type over different objects on a world map not over the object, but a little shifted to right...
On a screenshots helmet's area is shifted to right. (Both helmets are screened at left and right edges)
![cursor](https://user-images.githubusercontent.com/55348946/84593063-9941d080-ae52-11ea-8ff2-33df96985673.jpg)
![cursor2](https://user-images.githubusercontent.com/55348946/84593064-9ba42a80-ae52-11ea-9c6d-f104034cec7f.jpg)
 I suppose this issue is connected with #365

**Comment by idshibanov** [comment]
I think `Cursor::SetOffset` is the issue here, it has a bunch of arbitrary numbers there, so every cursor image has to be checked separately.
