### ISSUE TITLE
Fog edges are drawn incorrectly for some cases

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#803]
Some fog edges are drawn in incorrect way. For example:
![image](https://user-images.githubusercontent.com/19829520/84594770-18e99280-ae87-11ea-85d3-fc5a97b3c55b.png)
![image](https://user-images.githubusercontent.com/19829520/84594794-37e82480-ae87-11ea-9e70-a7d58fd40f8f.png)
![image](https://user-images.githubusercontent.com/19829520/84594835-54845c80-ae87-11ea-8a4c-c12c659bdc74.png)

**Comment by ihhub** [comment]
The problem lies in incorrect index of tile which is calculated in `void Maps::Tiles::RedrawFogs( Surface & dst, int color ) const` function.

**Comment by Branikolog** [comment]
Not sure such things are normal.)
![fog](https://user-images.githubusercontent.com/55348946/85201902-75c3cd80-b30b-11ea-9d12-0e45d1a59ad1.jpg)
