### ISSUE TITLE
Combat, AI skips turns of several troops in a row

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#8031]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

I don't know why AI preferred to stay, while he could focus my Centaurs or come closer to fliers.

https://github.com/ihhub/fheroes2/assets/55348946/c4e61900-1321-41de-9c3c-292889167e4b

### Describe the possible solution

AI should proceed attacks.

[Skip attack.zip](https://github.com/ihhub/fheroes2/files/13308702/Skip.attack.zip)

**Comment by oleg-derevenetz** [comment]
When AI chooses the defensive tactics (and in this case it does, because it has more powerful shooters than you), it prefers not to move to the opposing side of the battlefield, and it cannot use other units to eliminate your Gargoyles because of the obstacle on tiles 7 and 8, so only Boars are able to attack your Gargoyles.

**Comment by Branikolog** [comment]
@oleg-derevenetz , so AI just wants to attack Gargoyles with all his troops, right?

So we need to improve somehow the defensive logic. There're really lots of things to do with his rest troops, instead of skipping (in the case above).

In this particular case his enemy (me) has shooters, which are not guarded by any adjacent troops (Minotaurs are blinded). So AI could easily attack (and cover) Centaurs with his flying Rocs, which are not able to reach Gargoyles and skip turn currently.

In a case of defensive pattern was chosen I expect AI moving all his melee troops closer towards the defending shooters (Magi) - this helps in guarding, if boars fail in defending and were eliminated. With current logic, golems just standing and doing nothing. Once boars are dead, golems would start moving, but will reach Magi in a couple of turns, which allows me to attack Magi a few turns more without being attacked by anyone.

Golems, mummies etc coming closer to Magi would make it possible to focus griffins, which are attacking boars. Right now griffins are eating poor boars, but golems are just standing and watching - what a soulless machines!

Speaking about griffins... Since fliers cover all the battlefield, it's rather hard to attack them with melee troops. My ideal AI opponent should not be afraid attacking flying troops, like griffins: especially with ranged troops or even flying troops.
In the case from the topic Rocs are standing without any action, while they could fly 1 cell and attack potentially threatening griffins. I think, if attacking Griffins won't place Rocs in a situation, when Rocs could be attacked by some other strong troops, Rocs should definitely proceed (in a case of reasonable outcome for sure).
Unsafe position:
![Unsafe attack](https://github.com/ihhub/fheroes2/assets/55348946/cfdb0e33-8eb2-4634-b206-c6a8b61625fb)

Safe position:
![Safe attack](https://github.com/ihhub/fheroes2/assets/55348946/3a16ede2-df36-4c7e-b57f-44582dc91de1)

Such choice above could be done, when there're some other things to do or while choosing between two similar targets.

To conclude, I expect AI skipping only in really edge cases: while standing and defending shooters behind the troop. While sitting in castle relying on towers damage. Or even when the opponent has no shooters, magic and the AI has speed advantage.
But not in a cases described above, when there're enough targets to attack and AI still could get some losses from ranged troops or be attacked (or allow attacking other allied troops) by opponent's troops.
