### ISSUE TITLE
Save files from 1.0.10 not visible in 1.0.9

### ISSUE THREAD

**Issue by fheroes2bugs** [ihhub/fheroes2#8049]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Save files from 1.0.10 not visible in 1.0.9

### Save file

If it is done intentionally, then I suggest add it to changelog, because it is sensitive change.

**Comment by ihhub** [comment]
This is not a bug and done intentionally. It will be reflected in social media.
