### ISSUE TITLE
Combat, enemy advancement issue

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#8070]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Enemy is not using the whole movement range if I place my troops at the distance (move speed+2) in front of his troops.

https://github.com/ihhub/fheroes2/assets/55348946/afc90dd1-d9ef-4f9c-93bc-b64f192fab08

This could be highly abused by cheating humans allowing archers to shoot a few more turns.
I think there's no need to use such tactics if AI troops are slower than my.

Even if AI is going towards slower troops I can abuse this logic and slow down swordsmen for a few turns:

https://github.com/ihhub/fheroes2/assets/55348946/0499596d-5a72-4c35-9be2-6e58314ae5cd

I suggest swordsmen rush without slowing down in a case enemy army has strong shooters and/or weak troop standing in front of swordsmen.

### Save file

None.

**Comment by roman-yagodin** [comment]
Such a nice bug! 👍
I'd vote to leave it as is, somehow - e.g. by introducing some kind of AI preferences.

**Comment by oleg-derevenetz** [comment]
In fact it's the same as #7973.
