### ISSUE TITLE
In higher resultions resources data in the background is not synchronized with the city screen data.

### ISSUE THREAD

**Issue by kitovyj** [ihhub/fheroes2#8113]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In higher resultions resources data in the background is not synchronized with the city screen data. This sometimes makes the picture confusing.

### Save file

not needed, please see the screenshot
![is not updated](https://github.com/ihhub/fheroes2/assets/15792725/4bb0a2e9-1577-42ea-9811-df223f39d1f1)

**Comment by oleg-derevenetz** [comment]
Duplicate of #5976.

**Comment by kitovyj** [comment]
> Duplicate of #5976.

ops, sorry!
