### ISSUE TITLE
Assertion failure when opening a jail located next to another jail

### ISSUE THREAD

**Issue by oleg-derevenetz** [ihhub/fheroes2#8179]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

https://github.com/ihhub/fheroes2/assets/32623900/b30f56f3-81ac-4422-9411-37cd367e68cf

In this case assertion failure happens due to the fact that the object type at tile 37 (the top left jail in a row) becomes `OBJ_NONE` after calling the `Maps::removeObjectSprite()` for the tile with the jail opened by the AI-controlled hero.

### Save file

[!HIRETST.zip](https://github.com/ihhub/fheroes2/files/13766175/HIRETST.zip)

**Comment by ihhub** [comment]
I will take a look.
