### ISSUE TITLE
Sort headers in alphabetic order in few files

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#82]
It's good to have a standardised code style. A good practice is have sorted list of header inclusion for easier navigation between files. Here is a list of files which need such change:
```
src\fheroes2\army\army_bar.cpp
src\fheroes2\army\army_bar.h
src\fheroes2\army\army_troop.cpp
src\fheroes2\army\army_troop.h
src\fheroes2\army\army.cpp
src\fheroes2\army\army.h
```

Sorting header must be done in this way:
C++ headers like `<iostream>`
project headers like `"army.h"`

**Comment by RisingGeek** [comment]
I am taking up this issue @ihhub

**Comment by ihhub** [comment]
@CruxBox created a pull request for this issue.
