### ISSUE TITLE
Castle construction screen, statue description is not translated on all non-English languages

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#8219]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Description is in English, while choosing Russian localization.

![image](https://github.com/ihhub/fheroes2/assets/55348946/994d5b69-0811-4227-8816-612e54827254)

### Save file

Not needed.

**Comment by ihhub** [comment]
I am closing this issue as this is a general problem of any translation. The Russian translation does not cover 100% of texts. Therefore, this untranslated text exists.

**Comment by Branikolog** [comment]
Hi, @ihhub !
As stated in the name of the issue, this is the problem of **any** translation in the game. 
I want to note also, this issue is valid on the latest versions of the game. While my 1.0.10 works fine:
![Screenshot_2024-01-02-17-18-25-65_591ba0aa0c25b75f4ad8b373a1ebed7f](https://github.com/ihhub/fheroes2/assets/55348946/77756fce-c4a5-45be-9dfc-babf40817d9a)
