### ISSUE TITLE
Add description of how much gold was paid to surrender in battle result dialog

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#8221]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Neither the original game nor fheroes2 tells you how much gold you got from your opponent surrendering. I suggest to add this in the battle result dialog. It is quite possible that the height of this dialog will need to be extended in this case. This can be achieved with the `StandardWindow` object.

Something like:

`%{heroName} accepts the %{goldAmount} gold and allows %{surrenderingHeroName} and their army to surrender.`

Initial description about teaching AI to surrender, which now has been implemented:

<details>

When defending a castle, the only way to escape with a hero is by surrendering, because retreat is disabled.

It is very often worth it to surrender if you only have a few troops left and it would only cost you a few tens or hundreds of gold. This would avoid granting a winning attacker 500 extra EXP for taking out a hero, giving them any artifacts, and you losing a good hero.

The logic shouldn't be very different from how the current retreat logic works, except it would need to take into account whether the gold payment is worth it. I suppose if the AI has an overabundance of gold compared to the cost of surrendering, then surrendering is fine.

Unless it doesn't require complex logic, I suggest not teaching the AI to use the fheroes2 specific feature of using the market place to get enough gold to surrender. I'm also not sure this feature is very good, especially since you get to use it when attacked outside of your own turn, but that is a discussion for another issue or discussion thread, hence why I suggest not looking much into letting the AI do this right now.

Note that I specifically restricted this to sieges, because for normal battles outside castles, the logic behind choosing to surrender compared to retreating is much more complex.

Secondly, note that the way surrendering in the original Heroes 2, and naturally the way it works in fheroes2 right now, is that the non-surrendering party does not have anything to say whether the opponent gets to surrender or not - it is essentially a retreat paid by gold (plus you get to keep the surviving creatures).

**I strongly suggest** that any discussions about the way surrendering works be done in a separate discussion, as this issue is only about giving the AI the ability to do what the human player does right now - the AI does not get to refuse your surrender so neither should you be allowed to refuse them.

 

### Describe the possible solution

Teach the AI surrender when defending in a castle siege like it would have retreated in a regular battle.

### Additional info

An interesting point will be scenarios and campaigns like the final battles against Roland and Archibald, in which they potentially could surrender. I think this would just be much more fun and a reason for someone to improve their tactics and retry a battle so that they can avoid that the opponent hero manages to surrender.

Some might see it differently and consider this behavior weird because the subsequent video cutscenes usually imply that Roland or Archibald did not get to surrender and escape...? Still, surrendering doesn't technically mean that someone got to escape, if we're talking about the real world.

</details>

**Comment by oleg-derevenetz** [comment]
Hi @zenseii I suppose we can move your comment into the issue description and mark it as an UI improvement suggestion (maybe also change the issue subject), because only the UI-related part is not yet addressed.

**Comment by Alucard648** [comment]
I think, AI should prefer to surrender, if cost (including modifiers) is <10% of his gold treasury, similar to behaviour in H7.

**Comment by oleg-derevenetz** [comment]
> I think, AI should prefer to surrender, if cost (including modifiers) is <10% of his gold treasury, similar to behaviour in H7.

It's not just about gold in treasury, but also about the situation on the battlefield. Currently, when AI tends to retreat or surrender, it has an army that is usually just not worth buying out.

**Comment by oleg-derevenetz** [comment]
> Let's say that they AI starts with a huge gold amount or scripts that continuously give gold, which is often the case for many maps, then <10% might be insignificant for the AI, but it can be a huge amount for you.

I should note that currently AI will think that it's time to retreat or surrender if enemy's army is 10x or more powerful than the AI army, so either the AI army is powerful, but yours is 10x more powerful (and in this case you, more likely, just swimming in gold), or AI army is weak and you are unlikely to get very rich with AI's cents.
