### ISSUE TITLE
Changing game resolution in the Editor gives unexpected with the side panel and map area

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#8232]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Open the editor and change the resolution via the settings. Different unexpected behavior happens depending on how you are changing the resolution, whether you're going up or down in resolution.

For example, here is what happens when going from 940x540 (2.0x) to 640x480:
<img width="337" alt="image" src="https://github.com/ihhub/fheroes2/assets/12501091/84ae3b36-e3f0-4b05-9a60-a418b1456bc4">

See that the panel on the side is absent.

### Save file

Test within the editor

**Comment by Branikolog** [comment]
Hi, @zenseii 

That's why the editor is still not really ready for the public release. :)
Actually most of the game settings doesn't work properly yet.

**Comment by Branikolog** [comment]
@zenseii 
@ihhub suggested to track all such issues inside one thread: https://github.com/ihhub/fheroes2/issues/8026#issuecomment-1797430404 .
