### ISSUE TITLE
Hexagon on some terrain has wrong color

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#824]
In the OG hexagons seems to have lighter green color.
OG:
![hex2](https://user-images.githubusercontent.com/55348946/84898469-f7b7ba80-b0af-11ea-8d7a-555fe1a290d4.jpg)
In our version:
![hex](https://user-images.githubusercontent.com/55348946/84898429-e9699e80-b0af-11ea-9ee9-c40981ded209.jpg)

**Comment by ihhub** [comment]
I'm putting this issue to 1.0 as it's a minor enhancement over existing implementation. @Branikolog could you please check the color of grid at all terrains?

**Comment by Branikolog** [comment]
Indeed. Same issue can be seen on a Dirt, Sand and Beach.
On a grass and swamp it seems to be ok.

**Comment by LeHerosInconnu** [comment]
In the original game, the color of the grid is always the same regardless of the type of terrain.

HTML #688C04
RGB (104, 140, 4)
C++ 0x048C68

In fheores2, it is not the same color as in the original game and the color is not the same depending on the type of terrain.

For grass, lava, dirt and swamp:

HTML #789C04
RGB (120, 156, 4)
C++ 0x049C78

For beach, snow, desert and wasteland:

HTML #344804
RGB (52, 72, 4)
C++ 0x044834

For my part, I prefer the color of the original game.
For example for snow type terrain, the grid color is too much dark in fheroes2.
