### ISSUE TITLE
Allied AI perks should be reduced on higher difficulties

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#8254]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Currently, AI players that are allied to human player have all same perks, the opponent AI has. Playing on higher difficulty means that not only a human has to overcome difficulties, but his allies too.

On the screenshots below we can see that allied AI has extended scouting on impossible difficulty:
![image](https://github.com/ihhub/fheroes2/assets/55348946/74186242-100c-49c4-bda2-67b92759de29)

![image](https://github.com/ihhub/fheroes2/assets/55348946/fd02af81-52c9-49d7-b747-999c72692329)

### Describe the possible solution

All allied AI's should have perks based on reversed difficulty level selected by human.
On easy difficulty allies should have maximal perks and on "Impossible" - minimal.

**Comment by kitovyj** [comment]
I would prefer allied AI not have any disabilities in comparison to human player. Not having handicaps is ok, but please don't make it dumb. I like to play with allies on imposible and if allied AI is dumb it's not that funny anymore.

**Comment by ihhub** [comment]
Hi @kitovyj , this issue is not related to perks, not behavior.

**Comment by ihhub** [comment]
I suggest to gather the opinion of other members.

@oleg-derevenetz , @zenseii , @idshibanov and @Districh-ru , what do you think about this change? Is it going to be game breaking? Or is it fair to make such a change?

**Comment by oleg-derevenetz** [comment]
Well, I don't know really, but I suspect that in this case on higher difficulties allies can become a burden instead of being helpers, so enemy allies will defeat your allies first and then they will have an overwhelming advantage in terms of castles (i.e. army) and economy.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
It's a reasonable point. 

But on the other hand human player get benefits with the extended scouting of allied AI players (watching more revealed territories).
After all, expert and impossible modes are not expected to be easy so players shouldn't count on their AI allies. :)

**Comment by Districh-ru** [comment]
Then we can modify only the scouting range for allied AI to correspond the player scouting range. So there will be no benefit for the player, but allied AI will have all other skills like enemy AI.
Also after #8256 AI will rarely attack other AI so allied AI will have less battles with enemy AIs leaving them to the player, if I'm not wrong. :)

**Comment by oleg-derevenetz** [comment]
We can also try to remove this AI scouting bonus completely, because, IIRC, this is the bonus from OG, and it was introduced for OG AI, which  behave differently from our AI. In addition, this will not lead to a skew between the capabilities of the allied AI and the enemy AI.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Doesn't the original AI had the whole map revealed?

@zenseii 

>I've played too many games where having a bad AI on your team ruins the experience. The perks that the AI currently has are to compensate for shortcomings, and those shortcomings are present both for enemy and allied AIs.

In the original game players were always abusing allies by killing them, so weaker allies will make higher difficulites more challenging, as enemies will make the work original game players are used to do. ;)

**Comment by oleg-derevenetz** [comment]
> Doesn't the original AI had the whole map revealed?

I'm not 100% sure about that. Anyway, this bonus was added to fheroes2 longer ago, maybe even by previous team.
