### ISSUE TITLE
The AI should not know what flotsam contains before picking it up

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#8263]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

It is very obvious for players that the AI knows what flotsam is worth picking up and not and this is simply cheating.

Before they start:

<img width="273" alt="image" src="https://github.com/ihhub/fheroes2/assets/12501091/2dacbfab-3588-481f-9c6f-418e6608e01c">

After they're done picking up stuff, these are left and they are all empty:

<img width="260" alt="image" src="https://github.com/ihhub/fheroes2/assets/12501091/fa30a479-61bd-436e-8864-ec9913c163d1">

Savegame for testing:

[FlotsamTest.zip](https://github.com/ihhub/fheroes2/files/13915401/FlotsamTest.zip)

### Describe the possible solution

Similar to what has been done for chests, the AI should not know what the flotsam contains.

**Comment by ihhub** [comment]
We say a no to cheaters!
