### ISSUE TITLE
AI shouldn't surrender in the final fight

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#8292]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Currently AI can surrender while defending his last castle:
![image](https://github.com/ihhub/fheroes2/assets/55348946/8fe5136e-b01e-4f9b-8000-cdbb29945680)

![image](https://github.com/ihhub/fheroes2/assets/55348946/5ba72676-6dcf-4be8-83ec-4bf400b1a972)

There's no need to surrender from the last battle for the AI player.
If I'm not mistaken, the engine has such rule for running away from the battle. 

Maybe that's why I sometimes find some AI heroes in tavern with a considerable army, that surrendered but the player has been vanished.

### Save file

[surrender.zip](https://github.com/ihhub/fheroes2/files/13956781/surrender.zip)

**Comment by Branikolog** [comment]
@zenseii 

Isn't fighting till the last breath and inflicting maximum damage would help your teammates? :)
Also, surrendered hero could be hired by opposite side, so surrendering into nowhere could be controvertial step.

**Comment by oleg-derevenetz** [comment]
> @Branikolog does have a point in that it seems inconsistent/weird that the AI will try to make a last stand in cases for retreat, but not for surrender in castles

We can let it retreat in similar cases, why not.
