### ISSUE TITLE
Application closes while checking info of Necromancer/Sorceress guild bonus in campaign briefing window

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#8293]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

To reproduce just right click on Sorceress or Necromancer guild bonus.
![image](https://github.com/ihhub/fheroes2/assets/55348946/556a527c-1712-46b1-85a3-281e30c6f824)

### Save file

[Campaign saves with Guild bonus.zip](https://github.com/ihhub/fheroes2/files/13956874/Campaign.saves.with.Guild.bonus.zip)

**Comment by ihhub** [comment]
This is a regression from #8227.

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , can you please take a look at this issue?

**Comment by oleg-derevenetz** [comment]
Hmm, interesting, how this campaign scenario window issue could be related to that purely battle related PR. Sure, I'll take a look tomorrow.

**Comment by ihhub** [comment]
@oleg-derevenetz , you changed Army related code in that pull request and added an assertion that is now being hit.
