### ISSUE TITLE
Path behind oasis not passable

### ISSUE THREAD

**Issue by Stiivi** [ihhub/fheroes2#8298]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

macOS

### Describe the bug

Path behind an oasis is not passable. Situation:

<img width="960" alt="Screenshot 2024-01-18 at 08 13 29" src="https://github.com/ihhub/fheroes2/assets/71105/760f7f6d-23df-453b-805c-7b424cbf886f">

The gems (random resource) are not reachable, can not proceed further east.

The original game:

<img width="1024" alt="Screenshot 2024-01-18 at 08 13 34" src="https://github.com/ihhub/fheroes2/assets/71105/c97d76a3-5f94-40c5-b323-1546061ba115">

... resources taken, can proceed east.

### Save file

[a_War_to_end_all_BUG.sav.zip](https://github.com/ihhub/fheroes2/files/13973280/a_War_to_end_all_BUG.sav.zip)
[War.MX2.zip](https://github.com/ihhub/fheroes2/files/13973283/War.MX2.zip)

**Comment by Branikolog** [comment]
It is definitely a passability issue.
OG:
![image](https://github.com/ihhub/fheroes2/assets/55348946/1cdf8a0d-4ba4-4277-a510-684985dd0ea0)

fheroes2:
![image](https://github.com/ihhub/fheroes2/assets/55348946/3b630dd1-8c48-4d2d-9879-0b3298ea485b)
