### ISSUE TITLE
Add sound of magic resistance

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#830]
Try to play against Dwarves and notice that at the time of magic resistance we don't play any sound which is wrong.

![image](https://user-images.githubusercontent.com/19829520/85147617-b545d780-b281-11ea-9e31-581d01478e8f.png)

**Comment by idshibanov** [comment]
We have the logic for resist sound playing in `Interface::RedrawActionWincesKills`, need to check if it is working correctly and then do the same thing in `RedrawActionResistSpell`.
