### ISSUE TITLE
Music becomes quieter for a while during changing a terrain

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#831]
Move hero at the end of terrain types and you would notice that overall sounds are quieter which is abnormal and feels incorrect. It's obvious especially when you attack a monster which stands on a different terrain type.

**Comment by idshibanov** [comment]
@ihhub this is fade in/fade out effect, it exists in OG too, but shorter (3000ms vs 900ms). Do you want it removed at all?

Specifically sound levels are buggy on SDL2. Music mixer volume affects sound channels too, as noted in #237 .

**Comment by ihhub** [comment]
We shouldn't remove it at all but the current implementation is a bit wacky,
