### ISSUE TITLE
Boat changes its position after a hero boards it

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#833]
Move a hero close to a boat:
![image](https://user-images.githubusercontent.com/19829520/85188655-fdddaf00-b2da-11ea-92e0-3e0dc76702ff.png)
then board the boat:
![image](https://user-images.githubusercontent.com/19829520/85188660-07671700-b2db-11ea-8fdc-941fddc3f5fc.png)
Notice that the boat is shifted by few pixels to the top.

**Comment by shprotru** [comment]
Here you could notice additional insanely evil: a tile of ship in our game with water from stern of the ship. OG:
![Снимок экрана от 2020-06-20 09-56-36](https://user-images.githubusercontent.com/53114202/85195604-a6404300-b2dc-11ea-9b42-32b0e739b200.png)
![Снимок экрана от 2020-06-20 09-56-45](https://user-images.githubusercontent.com/53114202/85195608-ab9d8d80-b2dc-11ea-9978-292351cd65b6.png)
