### ISSUE TITLE
Mountain sprites are drawn in a wrong way

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#834]
Please take a look at this screenshot:
![image](https://user-images.githubusercontent.com/19829520/85189181-e0124900-b2de-11ea-9948-702595559861.png)
you can notice that the mountain just above Ogres has straight edge which is wrong.

Most likely we read or drawn this element incorrectly.

**Comment by ihhub** [comment]
Hi @Branikolog , could you please check how this map looks like in the original game? Does it have the same problem?

**Comment by Branikolog** [comment]
The map was created in that way: overlaying of objects in H2 editor is not always look good.
