### ISSUE TITLE
Derelict Ship is drawn incorrectly

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#835]
Find a map with a Derelict Ship. You can see that the area which is attached to the beach is not smooth:
![image](https://user-images.githubusercontent.com/19829520/85189218-67f85300-b2df-11ea-8296-56aeb91f33a2.png)

We have to fix it.

**Comment by Branikolog** [comment]
Derelict Ship has it's own part of coast in map editor. 
So, to make it smooth mapmaker should apply a certain amount of  skill...
![Ship](https://user-images.githubusercontent.com/55348946/87535318-f4f4b900-c69f-11ea-90ae-a2d9c8f404ab.jpg)

**Comment by ihhub** [comment]
Closing this issue as there is no work to be done here.
