### ISSUE TITLE
The Price of Loyalty objects have missing descriptions

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#836]
We have multiple objects from the Price of Loyalty add-on which have an incorrect description. Here are few of them:
![image](https://user-images.githubusercontent.com/19829520/85189304-64b19700-b2e0-11ea-81a8-1b5924ce7d53.png)
![image](https://user-images.githubusercontent.com/19829520/85189325-afcbaa00-b2e0-11ea-9432-a6b16aca0a9b.png)
![image](https://user-images.githubusercontent.com/19829520/85189329-b6f2b800-b2e0-11ea-9da4-db96b53a05c7.png)
![image](https://user-images.githubusercontent.com/19829520/85189332-c114b680-b2e0-11ea-9276-20eb48990fb1.png)

**Comment by idshibanov** [comment]
@ihhub Not able to reproduce on master with the maps copied from the expansion cd. Tried every object. IDs might be incorrect. Was it an old save or a map created with our editor? If you still can reproduce send me either.
![image](https://user-images.githubusercontent.com/1373638/86137298-2031b280-babb-11ea-8a10-8662c45d7598.png)

**Comment by ihhub** [comment]
Hi @idshibanov , the save was given to me by @Branikolog . I'll try a fresh map.
