### ISSUE TITLE
Hero cannot interact with the Price of Loyalty map's objects

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#837]
Start a map which was made for the Price of Loyalty add-on and notice that all objects which are from the add-on behave as terrain objects and you cannot interact with them:
![image](https://user-images.githubusercontent.com/19829520/85189366-1781f500-b2e1-11ea-9e3c-739fd8aba23d.png)

**Comment by idshibanov** [comment]
Same comment as in #836 . This looks like map/editor issue assigning wrong IDs.

![image](https://user-images.githubusercontent.com/1373638/86138550-9f73b600-babc-11ea-8bbb-435761915b4e.png)

On the side note this dialog needs adjustment
