### ISSUE TITLE
Double cursor while playing on MacBook

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#8389]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

macOS

### Describe the bug

OS cursor is rendered over the game cursor when playing on MacBook and moving cursor along the edge of the screen to scroll the map. After switching to window and then back to fullscreen the issue is gone, but after a few tries to scroll the map (or even touch the edge in the main menu) - second cursor appears again.

![IMG20240210180911](https://github.com/ihhub/fheroes2/assets/55348946/0198a17c-3bea-4fd7-9ac8-483a761055d6)

Don't know if it helps, a user was playing in software cursor rendering mode.

### Save file

None.

**Comment by oleg-derevenetz** [comment]
While I was unable to reproduce this issue on my MacBook with latest SDL 2.30.0 and software cursor, this issue looks identical to this:

https://github.com/libsdl-org/SDL/issues/8190

I suggest this person to update SDL to the latest available one (currently it is 2.30.0).

**Comment by ihhub** [comment]
The problem was the user installed sdl1.2-compat package instead of sdl2. The problem was solved installing sdl2.
