### ISSUE TITLE
Battle screen, auto combat disabling dialog refers to "battle", not "combat

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#8397]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

![Auto battle dialog](https://github.com/ihhub/fheroes2/assets/55348946/6a332fbf-4ab1-414c-af35-131b2a633d5a)

### Describe the possible solution

In all other places the feature is called "auto combat", except this interruption dialog.

**Comment by noah-white-8** [comment]
Hello, I'm new here.  I've installed the demo version, and I'm wondering how I could go about working on this issue?

**Comment by noah-white-8** [comment]
Thanks! Do I need Visual Studio in order to develop, because I have VS Code but not the regular Visual Studio IDE, and it just seemed like I might the IDE instead from the guide.

**Comment by noah-white-8** [comment]
So, I have visual studio and I opened the .vcxproj file, and the build succeeded.  But when I attempt to run it, the game window appears and has the message "Error! Data files not found! Please see README file. Press any key to continue..."

And when I close the game window, the debug console has the error message "SDL_main:  Exception 'No AGG data files found.' occurred during application runtime."  I am just hoping someone could maybe help me out.  Thanks!

**Comment by ihhub** [comment]
Hi @noah-white-8 , please read [this guide](https://github.com/ihhub/fheroes2/blob/master/docs/DEVELOPMENT.md).

**Comment by eduardojp26** [comment]
I can fix this, you want it to say auto combat instead of auto battle
