### ISSUE TITLE
Remove all inline word usage

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#84]
Nowadays compiler are smart enough to decide which function should be inlined. Keyword `inline` makes no sense with this. We would like to remove it everywhere in code (it's in 17 lines of code).

**Comment by SBhargav15** [comment]
I am taking this issue up @ihhub

**Comment by RisingGeek** [comment]
@SBhargav15 I have made a pull request that will close this issue. #87

**Comment by ihhub** [comment]
@RisingGeek unfortunately , @SBhargav15 took the task first :( I created a new #88 task for you. Would you mind to have a look to be fair for everyone?
