### ISSUE TITLE
"Chain lighting" spell operation while casting over dwarves

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#840]
"Chain lighting" spell behaves incorrectly, while dwarves' resistance occurs. 
Sometimes the spell hits only one pack of dwarves. Like single Lighting bolt.

**Comment by Branikolog** [comment]
Also if the spell was resisted by first stack of dwarves it still continues hitting other neighboring creatures.

**Comment by Branikolog** [comment]
@LeHerosInconnu, could you help me please with this issue?
I've tried many times to check, how "Chain Lightning" spell works over dwarves... 
And I couldn't find out the exact algorithm. 
Here's some screenshots from the original game with dwarves, where I hit the first (the highest) stack of dwarves with the "Chain Lightning" spell which deals 80dmg.
![3-3-3-2-2](https://user-images.githubusercontent.com/55348946/93014102-d3884e80-f5b6-11ea-8bd0-62f246844f9f.png)
Here we had 5 stacks: 3-3-3-2-2. The middle stack after the spell lost 10 hp... But, as I'm not mistaken, the damage should be 20, as it's the third unit the spell have hit....

![3-3-2-2-2](https://user-images.githubusercontent.com/55348946/93014191-ac7e4c80-f5b7-11ea-85f3-2cfdc3c3fdcd.png)
At this screenshot we had 5 stacks: 3-3-2-2-2. The Lightning accidentally jumped from the first stack to the lowest one. But managed to kill the middle stack with its last strike...

Can you explain me if the dwarve's resistance can lower damage? Or can the spell return back to the unit it missed before?

**Comment by LeHerosInconnu** [comment]
@Branikolog.

I will look at this later. :)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

I did some tests.
I have failed to reproduce your results.

Anyway, the Chain Lightning spell always hits 4 troops.
If a Battle Dwarves troop resists the spell another Battle Dwarves troop is chosen.
Battle Dwarves troops take full damage, there is no damage reduction.
With a 2 Spell Power hero, the spell still does 80, 40, 20, and 10 damage, even on Battle Dwarves.
Battle Dwarves have the ability to resist the spell (the spell is not applied), but if the spell hits them, there is no damage reduction.

Test 01:

Target first slot.
![Chain Lightning test 01 01](https://user-images.githubusercontent.com/43583994/93026061-8383a900-f603-11ea-8fb6-5ccb802432e8.png)

Target second slot.
![Chain Lightning test 01 02](https://user-images.githubusercontent.com/43583994/93026063-85e60300-f603-11ea-9b86-c5f448320a93.png)

Target third slot.
![Chain Lightning test 01 03](https://user-images.githubusercontent.com/43583994/93026065-88485d00-f603-11ea-891d-69874c68fee7.png)

Target fourth slot.
![Chain Lightning test 01 04](https://user-images.githubusercontent.com/43583994/93026067-8aaab700-f603-11ea-8b64-0de9ec816b79.png)

Target fifth slot.
![Chain Lightning test 01 05](https://user-images.githubusercontent.com/43583994/93026068-8d0d1100-f603-11ea-9270-30d418c798bd.png)

Test 02:

Target first slot.
![Chain Lightning test 02 01](https://user-images.githubusercontent.com/43583994/93026079-97c7a600-f603-11ea-94b7-bc9f1e9208b9.png)

Target second slot.
![Chain Lightning test 02 02](https://user-images.githubusercontent.com/43583994/93026081-9a2a0000-f603-11ea-91d9-aa8a5a06d157.png)

Target third slot.
![Chain Lightning test 02 03](https://user-images.githubusercontent.com/43583994/93026082-9c8c5a00-f603-11ea-91cd-aa129058671d.png)

Target fourth slot.
![Chain Lightning test 02 04](https://user-images.githubusercontent.com/43583994/93026084-9e561d80-f603-11ea-8996-e7f818d939d4.png)

Target fifth slot.
![Chain Lightning test 02 05](https://user-images.githubusercontent.com/43583994/93026074-94ccb580-f603-11ea-932f-a8de16ae8a53.png)

**Comment by Branikolog** [comment]
Thanks for your help, @LeHerosInconnu!
You see, don't know how, but I managed to experience that strange bahaviour on a version I compared to... )

One more question...
> If a Battle Dwarves troop resists the spell another Battle Dwarves troop is chosen.

Does the spell chooses the next target close to the last, that receive damage, or to the resisted troop?

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> Thanks for your help, @LeHerosInconnu!
> You see, don't know how, but I managed to experience that strange bahaviour on a version I compared to... )

Maybe you found a bug in the original game. ;)
If you still have the save file, do some more testing. :)

> One more question...
> 
> > If a Battle Dwarves troop resists the spell another Battle Dwarves troop is chosen.
> 
> Does the spell chooses the next target close to the last, that receive damage, or to the resisted troop?

From my observations, it is always the closest troop to the last hit troop that is hit.
Everything happens as if the troop which resists the spell did not exist.
