### ISSUE TITLE
Tavern doesn't show artifact quantity if hero has 0

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#841]
In the OG we have "0 artifacts". Our version shows message if hero has only >=1 artifacts.
![Artifacts](https://user-images.githubusercontent.com/55348946/85201165-c9331d00-b305-11ea-81a0-0ba3645727d2.jpg)
![Artifacts2](https://user-images.githubusercontent.com/55348946/85201166-cafce080-b305-11ea-9128-421b14b8ec11.jpg)

**Comment by idshibanov** [comment]
I actually prefer how it is right now, this "0 artifacts" text might be confusing at times. Is it 0? Is it 8? They all look similar in this font.

**Comment by Branikolog** [comment]
Let's write then, that heto has "no artifacts", or note that hero is "without any".
In my opinion, info should always show the same content: name of a hero, his level, and artifact amount.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> Let's write then, that hero has "no artifacts", or note that hero is "without any".
> In my opinion, info should always show the same content: name of a hero, his level, and artifact amount.
> Or let's take away the number at all. I like clear window more. Players always look through hero's info and obviously will notice artifacts there.

This information on the number of artifacts owned by the hero must be displayed in this window even if the hero has no artifact.
A sentence with "no artifact" would work very well:
"Gem is a level 1 Sorceress with no artifact."

**Comment by Branikolog** [comment]
Hi,  @LeHerosInconnu 

> "Gem is a level 1 Sorceress with no artifact."

Or "no artifacts"...? What would be correct?

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

> Hi, @LeHerosInconnu
> 
> > "Gem is a level 1 Sorceress with no artifact."
> 
> Or "no artifacts"...? What would be correct?

I think that with the word "without" it would be better:
"Gem is a level 1 Sorceress without artifact."

There must not be an "s" because there are not multiple artifacts. :)

**Comment by idshibanov** [comment]
"Gem is a level 1 Sorceress without artifacts."
"Gem is a level 1 Sorceress with 1 artifact."
"Gem is a level 1 Sorceress with 3 artifacts."

**Comment by LeHerosInconnu** [comment]
@idshibanov.

> "Gem is a level 1 Sorceress without artifacts."
> "Gem is a level 1 Sorceress with 1 artifact."
> "Gem is a level 1 Sorceress with 3 artifacts."

"Gem is a level 1 Sorceress without artifact."
The "s" is not necessary because there is no artifact.

**Comment by idshibanov** [comment]
I disagree again. It can be either "without an artifact." or "without artifacts." (similar to phrase "World without cars") but not what you suggest.

**Comment by LeHerosInconnu** [comment]
@idshibanov.

> I disagree again. It can be either "without an artifact." or "without artifacts." (similar to phrase "World without cars") but not what you suggest.

You are right, with the word "without" both spellings can be used depending on whether it means one or more things ("not a single artifact" or "not several artifacts").
Choose the spelling that you think is the most appropriate. :)
