### ISSUE TITLE
Crash when selecting Roland hero in final Roland campaign map and he has empty carry over army

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#8418]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug
EDIT: Please see the post right below this. 

Loading up the final map in Roland's campaign in the attached save and saw that he has an empty movement point bar. Selecting him triggers this assertion in `heroes.cpp`:
<img width="534" alt="image" src="https://github.com/ihhub/fheroes2/assets/12501091/2437a9bc-cc84-40ed-b9f7-99c1da10c71f">

<img width="238" alt="image" src="https://github.com/ihhub/fheroes2/assets/12501091/ba899bc8-3304-4af1-8f15-992832510797">

### Save file

[Good_9_Complete.zip](https://github.com/ihhub/fheroes2/files/14317040/Good_9_Complete.zip)

**Comment by oleg-derevenetz** [comment]
> if you win the carry over scenario with just elementals or other temporary troops left?

Heroes with empty armies are not supported in fheroes2. If you "win" the battle but you have no army as a result (only summoned or non-true-resurrected units at the end of the battle), then your hero will lose and get a basic starting army (in fact, both sides will lose the battle). In theory you should get the basic starting army as a carry-over army in this case (and you should never get an empty army).

**Comment by oleg-derevenetz** [comment]
According to my observations, the "carry-over forces" award is used only in scenarios with single hero (which is logical, because if it were possible to hire a lot of heroes, it is not known which hero's troops would need to be carried over). In all cases, the task is to capture the castle. If both heroes are defeated in the process of capturing the castle, then the castle does not change its affiliation (the attacking hero could not enter it), therefore, under normal circumstances, the scenario when no forces are carried out is not possible.

However, I have made some minor changes, mostly cosmetic (e.g. early assertion) in #8419.

**Comment by oleg-derevenetz** [comment]
> The final town you get to can be upgraded and you can hire more than one hero.

IIRC you win the scenario immediately once you capture that town. You have no time to build the castle and hire a hero. Even if you capture the empty town by moving a hero to that town, you still need to move that hero out to recruit a new hero, but once you leave the town screen to move the hero out, the scenario ends.

**Comment by oleg-derevenetz** [comment]
Interesting, if there will be multiple heroes in OG, army of which one will be carried over? Always starting hero, hero who won the last battle, or some other option? In fheroes2 currently it will be the army of hero who won the last battle (literally). So if one hero attacks some wandering stack, won the battle, and then  another hero attacks the target castle and there is a draw, then it will be the army of the first hero that will be carried over. Moreover, if there will be no battles at all except the last one, there will be a draw and then the target castle will be captured by some newly hired hero, then no forces will be carried over at all. But this scenario seems almost unbelievable.
