### ISSUE TITLE
Click over selected castle causes immediate teleportation in "Town Portal" spell list

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#843]
If player makes simple click over "yellow" castle spell activates.
![TP](https://user-images.githubusercontent.com/55348946/85202679-c5f15e80-b310-11ea-9a2e-572e56a31ab4.jpg)

**Comment by ihhub** [comment]
It's an existing behavior for all lists: even for saves or maps.

**Comment by ihhub** [comment]
I think the correct way would be to do not highlight first town in a list at the beginning of the spell.

**Comment by Branikolog** [comment]
In my opinion it is not comfortable behavior. If player misclicks wrong castle - spellpoints would be spent in vain.
In the OG, between, a double click is required to activate a spell.

**Comment by Arthusppp** [comment]
@Branikolog, @ihhub Do we have a conclusion here? Do we want to change it now? Or "Beyond 1.0"?

**Comment by Branikolog** [comment]
I've checked the OG recently: There we cannot activate the spell by double click. We should always press "OK" button to confirm teleportation.
Current fheroes2 implementation can cause a wrong teleportation, but works faster, comparing to the OG, because we can initiate the spell by a single click on a selected town
I personally prefer initiating teleportation on common double-clicking (fast one, that we use while browsing our OSes). So I consider this thread as "improvement" of the original mechanics. Not sure both original and current implementations are much better, comparing to each other, but they both are quite workable, so this improvement is definitely not in priority for now.
