### ISSUE TITLE
Avoid saving configuration file for Audio, Graphics and Interface dialogs

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#8489]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

These dialogs save configuration file if any of these settings are being changed. However, these dialogs are never being called directly. This means that the dialogs are being called from other setting dialogs that handle configuration file settings.

### Describe the possible solution

Pass an additional boolean flag which should be set to true if any of the settings was changed. Then the parent dialog will do one time configuration file save upon its closure. This is of course a very minor improvement. Therefore, it is ideal for newcomers for the project.

**Comment by glitchhopcore** [comment]
Hi, I am new to this project and would like to help with this issue. Can you share some more information regarding where the boolean flags are being called from and other relevant things which I should look for?

**Comment by glitchhopcore** [comment]
Hi @ihhub 
I am new to this project and would like to help contribute to this, can you elaborate about which boolean flags are you referring to and of any other things that I should be aware about while implementing the possible solution?
Thanks

**Comment by ihhub** [comment]
Hi @glitchhopcore , the start point to solve this issue is to look into `openGraphicsSettingsDialog()` function which is responsible for rendering Graphics option dialog. Once you understand the function code and where it is called from it is straightforward how to fix the issue.
