### ISSUE TITLE
Marketplace window is drawn incorrectly

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#851]
Take a look into a screenshot of a marketplace from the original game:
![image](https://user-images.githubusercontent.com/19829520/85206943-1b9d2980-b358-11ea-820a-46836eba0368.png)
Now compare it with out version:
![image](https://user-images.githubusercontent.com/19829520/85206947-2657be80-b358-11ea-97e7-5fb7f23d67d0.png)

Obviously, EXIT button is on incorrect place as well as Marketplace should be written with yellow color.

**Comment by idshibanov** [comment]
We should make it wider too, we have space. We should also check line width for the top message.
