### ISSUE TITLE
Application closes during AI turn

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#8521]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

I cannot tell exactly, what build among the recent PRs was used to create this game, but the application simply closes, when I skip the turn on the latest changes version.

### Save file

[Lost_Relic_0012.zip](https://github.com/ihhub/fheroes2/files/14736129/Lost_Relic_0012.zip)

**Comment by oleg-derevenetz** [comment]
Regression after #8516.
