### ISSUE TITLE
[Vita] Resolution 847x480 (x1.1) with diagonal distortion

### ISSUE THREAD

**Issue by j4w0r** [ihhub/fheroes2#8529]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

PlayStation Vita

### Describe the bug

Choosing a resolution 847x480 (x1.1) results in a diagonaly distorted image.
Example with distortion (resolution 847x480 (x1.1)) : 
![2024-03-30-192049](https://github.com/ihhub/fheroes2/assets/25296584/5cc8701c-fcd5-4263-aa80-0bcf2619d5dd)

Example with normal image (resolution 848x480) : 
![2024-03-30-191856](https://github.com/ihhub/fheroes2/assets/25296584/8fccd521-c4dc-4b46-a70a-f63315f56a73)

Steps to reproduce:
In main menu / in game, select:
1. Settings
2. Graphics settings
3. Resolution
4. 847x480 (x1.1)
5. Confirm changes

### Save file

Save file is not required to reproduce the issue, just change the resolution in the settings.

### Additional info

Reproducible on the 1.0.13 and the latest snapshot build.

**Comment by oleg-derevenetz** [comment]
I have an impression that this is an issue with SDL itself (on PSV). It may even have already been resolved in newer SDL versions, but vitasdk has SDL 2.28.5 in its package repo while the latest SDL version is currently 2.30.1.

**Comment by ihhub** [comment]
Simple way to fix it is to disable all resolutions with width not divisible by 4. This is a common logic for all monitors. We don't use SDL for rendering on Vita. We shouldn't populate any resolutions except existing 2 for Vita.
