### ISSUE TITLE
Enable the Editor save button

### ISSUE THREAD

**Issue by Cheerfulbull** [ihhub/fheroes2#8543]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

At the moment, using the save button in the experimental editor gives the message
"The Map Editor is still in development. Save function is not implemented yet."
This is actually not quite correct: using the save hotkey (default: S) you can save the map, but at the moment the button is not connected to that.

### Describe the possible solution

I think this would be relatively simple to rectify, simply by putting the save code under the button click event as well as the hotkey press event. However, I understand the team may be busy. If necessary, I could attempt to implement this myself in a pull request.

**Comment by ihhub** [comment]
Closing it as a part of #6845 task.

@Cheerfulbull , please refer to the list of open tasks in the corresponding ticket.
