### ISSUE TITLE
Cursor freezes while collecting resources after pressing some status window buttons

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#856]
When player collects resources on a world map and then tries to enter spellbook, or press end turn, adventure options, file options and system options buttons, game seems to be freeze (as cursor stays on a same place), but when player presses esc button game continues. Also player can interact with pop up window with mouse, but cursor is always stays the same place.
I believe this issue is connected with #234. But i'm not sure that previous issue could be cancelled with esc button...
![freeze](https://user-images.githubusercontent.com/55348946/85221516-f7bfff00-b3bc-11ea-9c76-df83320f95fb.jpg)
![freeze2](https://user-images.githubusercontent.com/55348946/85221519-fabaef80-b3bc-11ea-8df6-e2df613d8b46.jpg)

**Comment by ihhub** [comment]
Hi @Branikolog , please retest this issue. I don't see such behavior.

**Comment by Branikolog** [comment]
> Hi @Branikolog , please retest this issue. I don't see such behavior.

Problem is actual for SDL1.
