### ISSUE TITLE
Map list scroll bar is not rendered fully

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#8644]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

![image](https://github.com/ihhub/fheroes2/assets/55348946/9283f24b-6234-482b-ad5e-6a404b7ca77c)
Just ~half of bar is rendered.

### Save file

None

**Comment by oleg-derevenetz** [comment]
Looks like a regression after #8634.
