### ISSUE TITLE
AI heroes will try to pickup Magic Books on the adventure map even though they have one

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#8696]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

The AI will try to pick up the Magic Book placed on the adventure map even though it already has one. An easy way to test it is to place an AI hero in the middle of Magic Books.
![Screenshot_20240520_101548_fheroes2](https://github.com/ihhub/fheroes2/assets/12501091/dfcd30ab-89d6-418d-ac2c-1a14ce58e5ab)

Although the above picture shows a case in which it doesn't matter for the AI, there could be other cases where it would be better for the AI to prioritize some other move.

### Describe the possible solution

Make the AI avoid trying to pick up Magic Books when it already has one.

**Comment by ihhub** [comment]
Oh, this is bad. We need to fix it ASAP.

**Comment by ihhub** [comment]
On the other hand, picking up a Magic Book is the same as picking up bottle in sea. We need to just reduce value of Magic Book.

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , would you like to take a look at this issue?

**Comment by ihhub** [comment]
Yes, we need to reduce the value only for heroes with Magic Books.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub @zenseii Is my understanding correct that currently both AI-controlled and human-controlled heroes can pick up a spell book, even if they already have one (and in this case it just disappears)? Is this correct behavior?

**Comment by oleg-derevenetz** [comment]
> The current behavior of the magic book when you already have one is the same as for an artifact if you don't have room: the artifact remains on the adventure map for someone else to pick up.

Then it's not the same as a bottle in a sea, and lowering the priority is not enough. OK, I'll try to look into this.
