### ISSUE TITLE
One frame of cavalry dying animation has horse in blue colours

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#871]
When cavalry dies you can notice, that horse's harness becomes blue in one frame.
![cavalry](https://user-images.githubusercontent.com/55348946/85408061-b53d2480-b56c-11ea-8d35-a98e1976fee5.jpg)

**Comment by idshibanov** [comment]
Note for the future: here we'll have to redraw art in `cavalryr.icn` or replace it with new custom image. Known historical issue with the game.

**Comment by ihhub** [comment]
We can replace colors at the time of reading ICN as a fast solution for this problem.
