### ISSUE TITLE
A crash while entering text in the Editor

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#8716]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

From Discord:
I got a crash in editor when I tried to type something in map description

`22.05.2024 22:50:47: [ERROR]    main:  Exception 'basic_string::insert: __pos (which is 1) > this->size() (which is 0)' occurred during application runtime.`

### Save file

No need.

**Comment by ihhub** [comment]
Hi @Districh-ru , could you please take a look at this?

**Comment by DarthGandalf** [comment]
Hi

Platform is Linux here. Version 1.1.0

**Comment by Districh-ru** [comment]
Hi, @ihhub, sure!
