### ISSUE TITLE
Disable mouse popup for empty space in map selection window

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#8738]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

This is how it looks when not enough maps exist in the list:

https://github.com/ihhub/fheroes2/assets/19829520/9ba03ac6-fbf1-4fc3-aa87-5e4168d74e54

### Describe the possible solution

Do not show this popup dialog if a user is clicking on an empty space.

**Comment by oleg-derevenetz** [comment]
Closed by #9001.
