### ISSUE TITLE
Adventure map, center the spell scroll sprite horizontally in the square of the adventure map

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#8757]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

It has been bugging me for a long time, even in the original game, that the spell scroll sprite isn't centered horizontally in the square of the adventure map.
I corrected this in the original game by modifying the original sprite.
It would be nice to do this as standard in fheroes2. :)

In original game:

![Spell scroll heroes 2 01](https://github.com/ihhub/fheroes2/assets/43583994/3e1d46cf-754d-4668-88f8-ae35bccc7f6b)

In original game with the corrected graphic:

![Spell scroll heroes 2 modified 01](https://github.com/ihhub/fheroes2/assets/43583994/96640dee-f1f5-4489-abef-9614243b06b6)

In fheroes2:

![Center spell scroll 01](https://github.com/ihhub/fheroes2/assets/43583994/1cc871f0-22da-4509-b359-f2eb80b4df39)

### Describe the possible solution

Center the spell scroll sprite horizontally in the square of the adventure map.

### Additional info

Related issue: https://github.com/ihhub/fheroes2/issues/8756.

**Comment by ihhub** [comment]
This is a huge task for a very little outcome. We need to change the original images. Each artifact consists of 2 images.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , please take a look at #9381.
