### ISSUE TITLE
Editor: Object placement restrictions

### ISSUE THREAD

**Issue by admmlk** [ihhub/fheroes2#8762]
### Your question

I've noticed the current editor is even more restrictive when it comes to object placement, than the original editor.

For example, in the original one, some landscape objects (like reed) or monsters could be placed on water.

However, in the new editor, it is no longer possible.
Even if you manage to place some grass/reed on the shore, it gets deleted as soon as the terrain layer is updated (when painting terrain tiles).

Do we plan to change that in the future and allow more free object placement? 
I believe, that allowing unrestricted object placement could be benefical in terms of map variety - what do you think?

### Additional info

v1.1.0 on Android 5.1.1

**Comment by ihhub** [comment]
@admmlk , please attach a video showing that you can place an object on water **without** any tricks with terrains in the original Editor.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub IIRC this was possible (to some extent) in the SW editor and was "fixed" in the PoL editor (to some extent as well, some tricks are still possible even there).

**Comment by admmlk** [comment]
Hi, yeah it's just a question about your future plans.
I thought such stuff could be possible now, since the editor uses custom map format.
Basically I was just curious what do you think about it, as for example this could allow creating more interesting landscapes.

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , I know that it was a bug and this is why I asked to prove that `original one, some landscape objects (like reed) or monsters could be placed on water.` which is simply not true and it is a bug.

**Comment by ihhub** [comment]
> Hi, yeah it's just a question about your future plans. I thought such stuff could be possible now, since the editor uses custom map format. Basically I was just curious what do you think about it, as for example this could allow creating more interesting landscapes.

As of now we aren't planning to allow this as it might break the gameplay. We are focusing on more important features for the editor at the moment.

**Comment by admmlk** [comment]
Thanks for your answer, I get your point and it makes sense 👍
Since this has been explained, I think we can close the ticket!
