### ISSUE TITLE
Capitulation logic

### ISSUE THREAD

**Issue by fheroes2bugs** [ihhub/fheroes2#8772]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Computer is capitulating while defending the castle, but not asking me do I agree with the price.

https://github.com/ihhub/fheroes2/assets/145407420/ff033d1e-c19f-4172-a015-0351212d14a2

If we want to make AI to behave like human, if the battle is not defending town/castle - just hero1 (strong) vs hero2 (weak) and hero2 that wants to capitulate, he needs to make offer to hero1 "win you let me out for 275 gold?" and hero1 may accept it or not. At the moment there is no offer, hero2 just capitulates.

### Describe the possible solution

Save the logic from original game.

### Additional info

version 1.1.0
[capitulation.zip](https://github.com/ihhub/fheroes2/files/15502150/capitulation.zip)

**Comment by ihhub** [comment]
Closing this based on @zenseii explanation.
