### ISSUE TITLE
Castle info field is too large and shifted 

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#8779]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Information about the selected castle appears when clicking too far from the sprite itself.

https://github.com/ihhub/fheroes2/assets/55348946/36c062ac-9f27-4e65-97ae-00372fefe67c

### Save file

None.

**Comment by ihhub** [comment]
Hi @Branikolog , how is it affecting the gameplay? I see no problem for this. Moreover, in the past there were issues asking to expand area for object interaction and now we are going the opposite way.
