### ISSUE TITLE
Show creature info for the editor dialog

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#8780]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

![image](https://github.com/ihhub/fheroes2/assets/55348946/7a441b35-64a1-4b4d-a668-c961f06be79b)

Some players could forget the precise creature stats when creating a map.

### Describe the possible solution

It would be nice to show the selected creature properties on right click for this dialog.

**Comment by ihhub** [comment]
This can be done by introducing a new UI element and using the structure based on `DialogElement` class.
