### ISSUE TITLE
[Scenario Editor] Graveyard is in the wrong category

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#8784]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the graveyard is in the wrong category.
The graveyard is in the "Dwelling" list when it should be in the "Adventure Object" list.

In fheroes2:

![Graveyard wrong list 001](https://github.com/ihhub/fheroes2/assets/43583994/1ac25924-fa94-4911-8917-e45b1408e78d)

![Graveyard wrong list 002](https://github.com/ihhub/fheroes2/assets/43583994/027fc158-0838-44f3-8a05-ebb9e08ce540)

### Save file

Not needed.

**Comment by oleg-derevenetz** [comment]
In fheroes2 Editor, there are also some `OBJ_GRAVEYARD` objects which I couldn't find in the original HoMM2 editor:

![graveyard](https://github.com/ihhub/fheroes2/assets/32623900/459bb469-3e7c-49b4-9ee2-b443d1f18d6d)

**Comment by LeHerosInconnu** [comment]
Yes, please stop this.
**My eyes are bleeding.** :D
See here: https://github.com/ihhub/fheroes2/discussions/8785.
