### ISSUE TITLE
Sort headers in alphabetic order in files

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#88]
It's good to have a standardised code style. A good practice is have sorted list of header inclusion for easier navigation between files. We would like to sort header inclusions for all files within `src/fheroes2/objects` and `src/fheroes2/dialog` directories.

Sorting header must be done in this way:
- C++ headers like `<iostream>`
- project headers like `"army.h"`

**Comment by ihhub** [comment]
@RisingGeek would you mind to work on this issue?

**Comment by RisingGeek** [comment]
Yes, sure

> @RisingGeek would you mind to work on this issue?

Yes, sure

**Comment by ihhub** [comment]
Great! Then everyone is happy :)

**Comment by ihhub** [comment]
uh-oh, someone already created a pull request...
@RisingGeek have you started the work on it? If no you could do the same for `src/fheroes2/dialog` directory.

**Comment by ihhub** [comment]
I could modify the issue to represent both cases/directories.

**Comment by RisingGeek** [comment]
Okay, I will work for `src/fheroes2/dialog`

**Comment by ihhub** [comment]
hi @RisingGeek , are you still working on this issue?

**Comment by RisingGeek** [comment]
No
