### ISSUE TITLE
Wrong path calculation over roads

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#880]
In the OG path is created over roads, while in our version hero want to cross fields, than walk on roads.
![path](https://user-images.githubusercontent.com/55348946/85550650-d9ab0680-b629-11ea-8374-9216aa9ac4f2.jpg)
![path2](https://user-images.githubusercontent.com/55348946/85550664-db74ca00-b629-11ea-8d1c-df11ea888594.jpg)

**Comment by idshibanov** [comment]
Hmm first path should cost 675, second one is 700. I suspect that's why roads had that magical 59 value; might be a bug that was covered up previously. `Route::Path::Find` to check.

**Comment by Branikolog** [comment]
Hero still prefers walking not on roads in some cases:
![path roads](https://user-images.githubusercontent.com/55348946/87549800-ec5bad00-c6b6-11ea-8d05-50dcd6f6200f.jpg)
![path roads2](https://user-images.githubusercontent.com/55348946/87549803-eebe0700-c6b6-11ea-9458-e653372deb7d.jpg)
