### ISSUE TITLE
Hero's path shouldn't include 2 cells guarded by creature

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#881]
![Move](https://user-images.githubusercontent.com/55348946/85551119-59d16c00-b62a-11ea-9488-215ad5aa6706.jpg)
Battle occurs at the place hero finish its movement (on a screenshot). There shouldn't be "red arrow" next to that place: hero should make diagonal move to the cross placed over a creature.

**Comment by idshibanov** [comment]
Fix diagonal move cost in `Maps::Ground::GetPenalty`.

**Comment by idshibanov** [comment]
Fixed with new pathfinder class.
