### ISSUE TITLE
Troop loss bug when attacking the hero in the castle

### ISSUE THREAD

**Issue by Otakufanatic** [ihhub/fheroes2#8836]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In this case it occurs in the last scenario of the Archibald campaign:

When you are attacked having a hero in the castle if the hero has troops and the castle also in the same square when the enemy attacks you the castle troops are lost and only the hero's troops are left for combat, unless the castle troops you change them to another of the 4 remaining squares so that it is not the same square where the hero has the troops.

![1](https://github.com/ihhub/fheroes2/assets/61146840/aba2e4c7-e596-4f94-897a-b34723c33485)
![2](https://github.com/ihhub/fheroes2/assets/61146840/9fcaff5e-0031-43f8-a567-1168cf164cdf)
![3](https://github.com/ihhub/fheroes2/assets/61146840/9ba5b101-b500-489a-9ba3-9865fbf7b4a7)
![4](https://github.com/ihhub/fheroes2/assets/61146840/30dc0ee6-7e5f-448d-bee6-a55dafae1ea6)

### Save file

[Bug_save.zip](https://github.com/user-attachments/files/15848411/Bug_save.zip)

### Additional info

version 1.1.0 (22 May 2024)

**Comment by oleg-derevenetz** [comment]
> When you are attacked having a hero in the castle if the hero has troops and the castle also in the same square when the enemy attacks you the castle troops are lost and only the hero's troops are left for combat, unless the castle troops you change them to another of the 4 remaining squares so that it is not the same square where the hero has the troops.

This is not a bug, works as intended. Please see a long discussion in #6740 regarding this.

**Comment by Otakufanatic** [comment]
But in the original game if the square matches but the rest are free you do not lose the troops, the game implements it in the next square, that is, in this case that I have exposed, the trolls should appear in combat in square 2 (which is free) and the goblins in square 1 during combat and do not lose the troll troops because it matches in square 1 with the goblins for the hero and the castle. The troops were only lost in the original game if all the squares were already occupied (for example if the hero has 5 squares with troops and in the castle there are DIFFERENT troops in other squares, then the castle troops were lost for combat and left the hero's, unless they were some of the same type and then grouped to the corresponding square of the hero.

**Comment by oleg-derevenetz** [comment]
> But in the original game if the square matches but the rest are free you do not lose the troops

This is not the case in fheroes2, and that's by design. Please read the discussion provided at the link above. There are justifications for why it was done this way and not otherwise.

**Comment by Otakufanatic** [comment]
Ok, thanks for the clarification.

**Comment by Otakufanatic** [comment]
Ok, thanks for the clarification.

**Comment by Otakufanatic** [comment]
Ok, thanks for the clarification.
