### ISSUE TITLE
The map does not match that of the original game.

### ISSUE THREAD

**Issue by Otakufanatic** [ihhub/fheroes2#8837]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In the "Campain Expansion - Descendand - Scenario 4 (Cracy Uncle Ivan)" of the original game you could go through here and reach a clearing where there was an artifact, currently in this version of the game you can not.

![Camp - Descendand - Esc - 4- Cracy Uncle Ivan](https://github.com/ihhub/fheroes2/assets/61146840/9e6394f4-a392-41ef-8e4b-db8723c72e65)

### Save file

No save file.

### Additional info

version 1.1.0 (22 May 2024)

**Comment by oleg-derevenetz** [comment]
Apparently this is related to #4495 and #8390.

**Comment by ihhub** [comment]
I need to crack my head how to solve these passability issues :(

**Comment by Districh-ru** [comment]
I couldn't go this path in the original game...

https://github.com/user-attachments/assets/7588861d-8631-4a6c-a1d9-dfb461a48fd1

**Comment by Otakufanatic** [comment]
The original game is MS-DOS although they released some versions for windows that gave quite a few problems. If you play the ISO with DosBox of Heroes II Gold that integrated the base game and the expansion and with the last official patch (2.1) you will see that you can go through that area. In fact the video you send you will see that there is a clearing with an artifact and several treasure chests. Well, you can only access through this little secret. I send you a video of the original MS-DOS game so you can see it. Maybe what happens to you is that in the windows version the bug was not patched and that's why you can't pass, but as I said it gave you a lot of problems with the audio. Best regards.


https://github.com/user-attachments/assets/f81bcccb-67aa-40cd-bb0c-3879500695e6

**Comment by oleg-derevenetz** [comment]
> If you play the ISO with DosBox of Heroes II Gold that integrated the base game and the expansion and with the last official patch (2.1) you will see that you can go through that area.

In the following video I'm playing the 2.1 DOSBOX version from GoG:

https://github.com/user-attachments/assets/72f92bf8-7820-4086-9b74-8e3631e99e91

and I'm still not able to move to this area.

**Comment by Otakufanatic** [comment]
It's strange, it seems to be a map bug introduced in v2.1 that changed some game maps with errors (like mines that could not be captured among other things). I've tried it in MS-DOS and Windows English version and I get like you, inaccessible the way to get to the clearing with the artifact and treasure chests. On the other hand with the 2.0 version in Spanish if it is possible to access.

**Comment by ihhub** [comment]
I am closing this issue as it is not a problem of fheroes2 engine but different maps being used.
