### ISSUE TITLE
Combat screen, Captured Artifact window, artifact is displayed only once when opposing hero has two copies of the same artifact

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#8844]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, in the example, the opposing hero has two copies of the same artifact, but the artifact is displayed only once in Captured Artifact window.

In fheroes2:

![Artifact two only one](https://github.com/ihhub/fheroes2/assets/43583994/daaaf9c7-91e3-481d-ae0a-fbdf74613057)

https://github.com/ihhub/fheroes2/assets/43583994/c9a07798-3ab3-4060-8deb-6097d3ba3018

### Save file

Not needed.

**Comment by oleg-derevenetz** [comment]
This is a regression introduced in #8244.

**Comment by oleg-derevenetz** [comment]
Hi @zenseii

> I remember when making that PR I was suprised that it worked that way, but iirc I checked the OG and that's how it worked, or that was how it was before the PR.

I understood that your idea was not to redraw the same artifacts running _in a row_, which is correct in general (and now the redraw is not being done either), you just shouldn't skip the event loop :)
