### ISSUE TITLE
Game window was shifted after hero finished its movement

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#886]
Hero stopped and some elements of interface shifted as well as upper edge of a world map. The problem stayed until i restarted the game...
![screen](https://user-images.githubusercontent.com/55348946/85792575-680fad00-b73c-11ea-98ae-e311715ed6b0.jpg)
I think hero stopped on a special line, where screen loses its focus over hero...(https://github.com/ihhub/fheroes2/issues/797#issuecomment-649797335)

**Comment by ihhub** [comment]
Fixed in #898
