### ISSUE TITLE
Add HD-mod to roadmap

### ISSUE THREAD

**Issue by fheroes2bugs** [ihhub/fheroes2#8863]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

I have found, that all the sprites of HOMM2 are in public: https://www.spriters-resource.com/pc_computer/heroesofmightandmagic2
As I see the development of old 90's games, a lot of games got a "HD-mod". I am sure, HOMM2 will have it too (ubisoft won't do it for sure, but regular users - will).

### Describe the possible solution

The things can be done:
1. Add more pixels (upscale):
2. Add more frames.

Don't know how it can be done most properly. May be there already are scripts, that do it great, may be some AI can help, or may be there is no solution at the moment (only draw the missing pixels and frams by users in photoshop etc).

Add a HD-mod to roadmap.

### Additional info

Make a HD-mod, that can be turned on-off by 1 click on the keyboard. Or create addinional .exe named "fheroes2-HD mod".

**Comment by ihhub** [comment]
There is no such thing as all graphics of HoMM2 are in public domain. HoMM2 is a property of Ubisoft and only this company allows to do with game's resources what they want. fheroes2 team will **not** violate copyright laws. I suggest to get familiar how copyright laws work.

**Comment by fheroes2bugs** [comment]
just want to mention, that HOTA has HD-mod, they are in the same situation as fheroes2

**Comment by ihhub** [comment]
@fheroes2bugs , HoTA is a mod which modifies the original executable file and this is considered copyright infringement. HD-mod comes from an **official** version of HoMM3 released by Ubisoft. It has nothing to do with publicly accessed resources.
