### ISSUE TITLE
Ctrl to see enemy creature range

### ISSUE THREAD

**Issue by denierlexiese** [ihhub/fheroes2#8888]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Ability to hit control during fights and see the enemies walking distance.

### Describe the possible solution

Ability to hit control during fights and see the enemies walking distance.

**Comment by ihhub** [comment]
Duplicate of #6527
