### ISSUE TITLE
Android mouse map movement move mouse to edges should scroll

### ISSUE THREAD

**Issue by denierlexiese** [ihhub/fheroes2#8899]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

It would be nice on android if I could use a usb mouse, and scroll the map like in windows/linux to look around.

### Describe the possible solution

It would be nice on android if I could use a usb mouse, and scroll the map like in windows/linux to look around.

**Comment by oleg-derevenetz** [comment]
There is nothing stopping you from scrolling with the mouse on Android. Just open the Settings on the Adventure Map screen, then go to the Interface Settings and select the Scroll Speed you want (it's Off by default on Android).

**Comment by ihhub** [comment]
I am closing this issue as @denierlexiese is not responding to the proposed solutions.
