### ISSUE TITLE
Attacked creature freezes, while trolls materialize stone in their hands

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#890]
After trolls made shot, target creature freezes until trolls stop materializing new stone.
![Troll](https://user-images.githubusercontent.com/55348946/85859952-a81b7200-b7c6-11ea-892d-c835fc9a7dae.jpg)

**Comment by idshibanov** [comment]
Monster is not redrawn with `STATIC` state.

**Comment by ihhub** [comment]
It happens because the animation of Elves is shorted than animation of Trolls leading to this problem.
