### ISSUE TITLE
Holes in a battle journal scrollbar 

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#891]
On a screenshot we can watch battlefield (snow) through the scrollbar. This happens only the first time you open journal (there should be enough notes to be able to scroll it) and start fast scrolling using scrollwheel or simply drag bar .
![scroll](https://user-images.githubusercontent.com/55348946/85860863-16acff80-b7c8-11ea-99a0-2d44a6388a41.jpg)

**Comment by ihhub** [comment]
Hi @Branikolog , do you still observe such behavior?

**Comment by Branikolog** [comment]
Cannot reproduce the bug anymore.
It should have been fixed by our glorious team already!
