### ISSUE TITLE
Surface Duo - keyboard input is laggy

### ISSUE THREAD

**Issue by denierlexiese** [ihhub/fheroes2#8910]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Android

### Describe the bug

On surface duo, keyboard input is slow / laggy.  I have to push 'h' or 't' , 5 or 6 times before a single click is registered.

### Save file

None

### Additional info

I suspect this is a niche issue considering it the application seems fast on my galaxy phone. I've tried multiple keyboards. It's slow with different keyboards.  And the keyboard input is fast in other applications on the surface duo.

Surface Duo is a great way to play the game portably otherwise.

**Comment by oleg-derevenetz** [comment]
Hi @denierlexiese could you please try to install the Android artifact from #8912 on your Surface Duo device and see how it goes? 

There are instructions [here](https://github.com/ihhub/fheroes2/wiki/Download-Windows-latest-compiled-packages-of-a-pull-request) on how to do this for Windows builds, they are also suitable for Android, except that you should download the `fheroes2_android.zip` artifact.

Please note that the APK file inside this artifact is a debug build and is signed by a different signature, so you will not be able to just install it "on top" of the Google Play version. You will need to uninstall the Google Play version first, and then you will be able to install this debug APK. You will have to install the resources of the original game once again.
