### ISSUE TITLE
'Allow castle' is broken?

### ISSUE THREAD

**Issue by kitovyj** [ihhub/fheroes2#8914]
### Your question

I noticed that I can't upgrade a town to a castle compiling the current master branch.

It seems that old logic

    const bool allowToBuildCastle = ( dataStream.get() != 0 );
    if ( allowToBuildCastle ) {
        ResetModes( ALLOWCASTLE );
    }
    else {
        SetModes( ALLOWCASTLE );
    }

interprets the "allowance" byte the opposite way to the present logic:

    _disabledBuildings = 0;

    const bool allowToBuildCastle = ( dataStream.get() != 0 );
    if ( !allowToBuildCastle ) {
        _disabledBuildings |= BUILD_CASTLE;
    }

?

**Comment by oleg-derevenetz** [comment]
It seems to me that `allowToBuildCastle` wasn't a very good name. It would be better to name it `castleNotAllowed`.
