### ISSUE TITLE
Adventure map, mouse cursor position after the action of selecting a hero with a left click held on the hero sprite

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#8921]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

When action is taken to select a hero by a left click held on the hero sprite on the adventure map, the hero becomes the selected hero and the area of the adventure map is centered on the hero.
However, the mouse cursor remains at its previous position.
I suggest that, at the end of the action, the mouse cursor be positioned on the hero sprite, so in the center of the adventure map area.

In fheroes2:

https://github.com/ihhub/fheroes2/assets/43583994/e17eaa39-bf51-497c-8300-f64190954002

### Describe the possible solution

At the end of the action to select a hero by a left click held on the hero sprite on the adventure map, make the mouse cursor to be positioned on the hero sprite, so in the center of the adventure map area.

**Comment by LeHerosInconnu** [comment]
Hello @zenseii,

> How does this work for quickly selecting castles in the OG, @LeHerosInconnu ?

There's the same problem with the mouse cursor and castle in the original game.
It should be improved for the mouse cursor and castle too.
I haven't posted an issue for the mouse cursor and castle yet, I'll do it later.

> I should also note that we do not have auto placement of the mouse cursor as other games and apps tend to have, in which the cursor will jump to either the OK button or similar by as soon as a dialog pops up.

It's not so much a matter of an auto placement of the mouse cursor on a clickable button, but of leaving the mouse cursor where the user positions it, in relation to the elements of the adventure map.
When the user left clicks, on the castle for example, to select it, the next action will be, in the vast majority of cases, to left click on the castle a second time to access the castle screen.
However, as the mouse cursor is no longer positioned over the castle sprite where the user has clicked, the user must move the 
mouse cursor back to the castle sprite.

> I considered this way of operation when implementing it. However, this hero selection can be compared to the quick swap to a castle when the current focus is on a hero, and neither in this case does the mouse cursor get centered on the castle you just clicked on. Therefore I was reluctant to implement a potential unexpected way of working for the UI.

It would be a real plus, in my opinion, if the user didn't have to readjust the position of the mouse cursor when performing this type of action.
Namely, for hero selection as in this thread.
The user positions the mouse cursor over the hero sprite to perform the action.
His next action, in most cases, will be to left click again on the hero sprite to access the hero screen.
The user expects the mouse cursor to still be positioned over the hero sprite, where he clicked when the action was triggered.
But the mouse cursor is no longer positioned over the hero sprite at the end of the completion of the action.
The user must then readjust the position of the mouse cursor.

Similar case for the action of casting the dimension door spell (in the example, I position the mouse cursor over the windmill during spell casting to visit it after the spell animation) in this issue: https://github.com/ihhub/fheroes2/issues/8922.

Another case is for the mouse cursor and castle, from which I'll open an issue later.

**Comment by ihhub** [comment]
As explained in #9006 , we are not going to implement this as the current behavior is more understandable by players than jumping mouse cursor which might be actually very annoying for some users. Also, playing in a windowed mode having such a feature worsens usability of mouse as users don't expect the mouse to jump in relation to the overall screen if many apps are open.

Therefore, I am closing this issue as well.
