### ISSUE TITLE
Adventure map, mouse cursor position after the action of casting the dimension door spell

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#8922]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

When the hero casts the dimension door spell, the positioning of the mouse cursor performed by the user is not retained at the end of the spell casting (the mouse cursor remains at its previous position).
I suggest that the positioning of the mouse cursor performed by the user in relation to the elements of the adventure map not to be modified.
In the example, I position the mouse cursor over the windmill during spell casting and at the end of the hero's displacement the mouse cursor position is changed.

In fheroes2:

https://github.com/ihhub/fheroes2/assets/43583994/31cd6220-9022-4434-a17e-11e409c2fc54

### Describe the possible solution

Do not change the positioning performed by the user at the end of the hero's displacement following the casting of the dimension door spell.

### Additional info

Similar issue: https://github.com/ihhub/fheroes2/issues/8921.

**Comment by ihhub** [comment]
The same explanation as for #8921 and #9006 . While for some players it might be convenient for many it is going to cause issues.
