### ISSUE TITLE
Dimension door view area

### ISSUE THREAD

**Issue by shprotru** [ihhub/fheroes2#893]
View area of Dimension door spell have shifted on high resolutions, see attach on 3840 × 2160 (be careful it is 9.1 Mb!!!)
[link](https://imgur.com/a/PVbzlwd)
If need, you can download image, button at right "Download post".
Area of displacement of spell is ok, problem only with visual effect.

**Comment by ihhub** [comment]
The issue is related to common topic of setting hero's focus in the center of the screen.
