### ISSUE TITLE
Web port

### ISSUE THREAD

**Issue by midzer** [ihhub/fheroes2#8935]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Hi,

I've ported the demo of the game in the browser: https://midzer.de/wasm/heroes2/

Have a nice weekend
midzer

### Describe the possible solution

Relevant changes at https://github.com/midzer/fheroes2/tree/emscripten

Probably gonna update it because there are over 800 new commits since the first build.

**Comment by oleg-derevenetz** [comment]
Eh, as far as I can see, emscripten is still a bit raw. However, AFAIK, it now has (experimental) support for pthreads (and, therefore, native C++ threads), but I do not know how well it _actually_ works.

**Comment by ihhub** [comment]
Unless I am missing something this is purely self-advertising post. I have no idea why it is even an issue. 

Closing this topic.
