### ISSUE TITLE
Update Android API

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#8954]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

This is a requirement from Google Play Store:

![image](https://github.com/user-attachments/assets/7580200d-8541-4ee9-b556-10f833e627d7)

### Describe the possible solution

We should update Android API level.

**Comment by oleg-derevenetz** [comment]
fheroes2 is already targeting Android 14 (API level 34):

![Screenshot_20240713-154752.png](https://github.com/user-attachments/assets/d9813a54-b34b-4ff0-81e5-a0c5fd8a693d)

**Comment by ihhub** [comment]
@oleg-derevenetz , thank you for clarifying this! I'm closing this issue then.

**Comment by oleg-derevenetz** [comment]
I suspect that Google somehow mixed up Android 14 with upcoming Android 15 (not the first time BTW).
