### ISSUE TITLE
The description of AntiMagic is correct?

### ISSUE THREAD

**Issue by kitovyj** [ihhub/fheroes2#8968]
### Your question

Please see the screenshot. Is the description of AntiMagic correct? It prevents the application of all spells, not only harmful.

### Additional info

![am](https://github.com/user-attachments/assets/9573aebc-481e-4e05-9710-51145775af4c)

**Comment by oleg-derevenetz** [comment]
Yes, in fact it prevents all the spells, but its description was taken from the original game:

![amd](https://github.com/user-attachments/assets/5a7e4749-9337-4b8d-a746-3142b8e9d571)

**Comment by oleg-derevenetz** [comment]
Reclassifying this as a request for improvement.

**Comment by AlexSnowLeo** [comment]
@oleg-derevenetz can I try to fix this?

**Comment by oleg-derevenetz** [comment]
Hi @AlexSnowLeo

> can I try to fix this?

Yes, sure.

**Comment by AlexSnowLeo** [comment]
@oleg-derevenetz 
I'm a little confused. Do I need to update all the translation ".po" files in this issue? Or it will be enough to update only the spell description in the code:
https://github.com/ihhub/fheroes2/blob/master/src/fheroes2/spell/spell.cpp#L82

**Comment by oleg-derevenetz** [comment]
> Do I need to update all the translation ".po" files in this issue?

No, you don't have to do this. You may, however, update the translation for your native language - if it is not English and if there is a corresponding PO file.

> Or it will be enough to update only the spell description in the code

Yes.

**Comment by AlexSnowLeo** [comment]
https://github.com/ihhub/fheroes2/pull/8974
