### ISSUE TITLE
Polish translation of ALL for map selection is out of button area

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#8972]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

This is how it looks if you select Polish language and go to map selection:
![image](https://github.com/user-attachments/assets/3cf2280f-c357-4200-89ee-24d331626833)

### Save file

No save file needed.

**Comment by Arthusppp** [comment]
I do not see a good abbreviation for the "Całość" word. In fact, the word "Całość" is a cheat here. The proper word here is "Wszystkie". 
If we need something shorter, then I propose "ALL" (yes, English word) or the "*" (asterisk).

Can we solve this differently? For example, the Original Game uses a slightly different font style: spacing between letters is much smaller here:
![image](https://github.com/user-attachments/assets/813640e3-6c0c-4a6d-8560-080cb9ef7fd1)

**Comment by Arthusppp** [comment]
> I don't know any polish but is a simple "M-BD" an solution?

Good idea! :)
