### ISSUE TITLE
Can't save map in the editor with the Flathub version

### ISSUE THREAD

**Issue by Mr-Bajs** [ihhub/fheroes2#8980]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

Using the editor with the flatpak version on flathub (v. 1.1.1). I'm not able to save any map in the editor. It just show the failed to same map pop-up warning.

What are the default directory for the new maps in the editor for the flathub version? I assumed tha it was so simple that here was no r/w access for the flatpak version. Maybe it its, but I couldn't save any map after trying giving fheroes2 more access with flatseal.

**Comment by oleg-derevenetz** [comment]
IIRC @Laserlicht may know about the details. On non-Flatpak Linux distributions maps should be saved to the `${XDG_DATA_HOME}/fheroes2/maps` (or `${HOME}/.local/share/fheroes2/maps` if `XDG_DATA_HOME` is not defined).

**Comment by Laserlicht** [comment]
> IIRC @Laserlicht may know about the details. On non-Flatpak Linux distributions maps should be saved to the `${XDG_DATA_HOME}/fheroes2/maps` (or `${HOME}/.local/share/fheroes2/maps` if `XDG_DATA_HOME` is not defined).

Not sure, what's the problem here...

Saving games works: `/home/laserlicht/.var/app/io.github.ihhub.Fheroes2/data/fheroes2/files/save` and seems to respect `XDG_DATA_HOME`.
Not sure, whats the difference to saving maps...

**Comment by oleg-derevenetz** [comment]
Hi @Mr-Bajs is your maps directory named by chance "MAPS" (in uppercase)?

**Comment by oleg-derevenetz** [comment]
> However the datafolders from the GOG are capitalised I would asume that this would be a recurring issue for users. Most users just copy the the folders.

Yeah, I already prepared a fix for that, so users won't need to rename it.
