### ISSUE TITLE
SDL2 build UI scrolling

### ISSUE THREAD

**Issue by shprotru** [ihhub/fheroes2#900]
Can't scroll world map with 1920x1080 resolution in full screen mode(native display resolution is bigger than game resolution). Have space to scroll and can't. Sometimes in all directions, simetime only with right direction. Notice, if this triggers - you can't click on castles, heroes, move your hero or set new path, just nothing happens, till you back to windowed mode.
Real action area in fullscreen mode is decrease to 1920x1080, while screen resolution is 3840x2160, it should be stretched like in SDL1 build. Previously it working fine.

**Comment by ihhub** [comment]
Hi @shprotru , is it still reproducible with latest changes for resolutions?

**Comment by shprotru** [comment]
Hi @ihhub! Yes it's still reproducible, no scrolling on `SDL2` build.

**Comment by ihhub** [comment]
Hi @shprotru , could you please investigate the problem why exactly we can't interact with objects? Maybe there is a flag which prevents scrolling

**Comment by ihhub** [comment]
Hi @shprotru , is it still present with the new engine?

**Comment by shprotru** [comment]
Hi @ihhub the problem still present on current engine
