### ISSUE TITLE
Mouse cursor too high inertion

### ISSUE THREAD

**Issue by shprotru** [ihhub/fheroes2#9004]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

Impossible to control mouse pointer with enough powerful hardware, i7-7700k, nvidia gtx 1060 and 32gb ddr4 ram memory, in screen resolution 1280x720 while host resolution is 3840x2160, it's slow and getting inertion effect.
Possible root of a problem: https://github.com/ihhub/fheroes2/pull/8912

https://github.com/user-attachments/assets/2f3dc2f5-fc24-4c3e-85e1-6e0f1f78d9a8

**Comment by oleg-derevenetz** [comment]
> Possible root of a problem: https://github.com/ihhub/fheroes2/pull/8912

What if you bring the `while ( SDL_PollEvent( &event ) )` loop back? Does it help?

**Comment by shprotru** [comment]
> > Possible root of a problem: #8912
> 
> What if you bring the `while ( SDL_PollEvent( &event ) )` loop back? Does it help?

yes! I returned the code of while handleEvents function to previous, when it uses while loop, and this helps!
