### ISSUE TITLE
SDL2 build mouse cursor after computer turn in fullscreen.

### ISSUE THREAD

**Issue by shprotru** [ihhub/fheroes2#901]
In fullscreen mode you could notice that mouse cursor does not resets from sundial pointer type to horse, after computer finished his turn.

**Comment by shprotru** [comment]
Hi @ihhub found [strange place](https://github.com/ihhub/fheroes2/blob/master/src/fheroes2/game/game_startgame.cpp#L551), related to cursor. There is `cursor.Hide` call without `cursor.Show` next, is this place correct?

Thinking on inserting this code:
```
cursor.Hide();
LocalEvent & le = LocalEvent::Get();
const int32_t cursorIndex = gameArea.GetValidTileIdFromPoint( le.GetMouseCursor() );
Cursor::Get().SetThemes( GetCursorTileIndex( cursorIndex ) );
Interface::Basic::Get().buttonsArea.Redraw();
Redraw();
cursor.Show();
display.Flip();
```
before [this](https://github.com/ihhub/fheroes2/blob/master/src/fheroes2/game/game_startgame.cpp#L550) line, but checked again both builds `SDL1` and `SDL2` without any code modifications, and can't see this bug. Can you check this please, could it be closed if can't reproduce?
Steps I do to get this on `SDL2` build:
1. open game in windowed mode, and start playing
2. end turn
3. while AI makes his turn press `F4`, you will go into fullscreen
4. notice that after end of turn your mouse cursor have sundial icon.

**Comment by ihhub** [comment]
Hi @shprotru , I tested this issue and for me it's not valid. Is it still valid for your side?

**Comment by shprotru** [comment]
Hi @ihhub, checked on fresh master: bug is gone, ticket could be closed
