### ISSUE TITLE
AI is ignoring patrol limit

### ISSUE THREAD

**Issue by Stiivi** [ihhub/fheroes2#9015]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

macOS

### Describe the bug

In some cases AI ignores patrol limit. The original map location and patrol information:

<img width="1024" alt="Screenshot 2024-07-30 at 00 22 53" src="https://github.com/user-attachments/assets/98ab06ac-45cf-4c0d-92a8-c3b9efef24d1">

<img width="1024" alt="Screenshot 2024-07-30 at 00 23 00" src="https://github.com/user-attachments/assets/e633fc47-fbdd-4ad6-8ebe-a279ad522baf">

The hero was found lose way too far away from intended patrol area:

<img width="1280" alt="Screenshot 2024-07-30 at 00 29 17" src="https://github.com/user-attachments/assets/53598655-7464-46bb-a29e-f0a3421c7da0">

### Save file

[Slayer_Legacy_0073.sav.zip](https://github.com/user-attachments/files/16419760/Slayer_Legacy_0073.sav.zip)

### Additional info

Revision: 81ddac960b83712b665be2efbd7c2dc5dc7e04ba

**Comment by oleg-derevenetz** [comment]
I have an impression that heroes on patrol still can perform the fog discovery outside of their patrol zone, at least I don't see any limitations for this in the code with a cursory glance. Perhaps this is the reason.
