### ISSUE TITLE
Sounds are gone!

### ISSUE THREAD

**Issue by shprotru** [ihhub/fheroes2#902]
Disappears all sounds for both builds, SDL1 and SDL2, except music, see attached log file [fh2_sdl1_sounds_gone.log](https://github.com/ihhub/fheroes2/files/4841816/fh2_sdl1_sounds_gone.log)

**Comment by ihhub** [comment]
Hi @shprotru , could you please provide a description of conditions when this is happening? Which OS?

**Comment by shprotru** [comment]
Ubuntu Linux, default build, don't know what heppened, what information could I provide to understand this problem?

**Comment by ihhub** [comment]
It might be something wrong with settings. Try to run a fresh build without any extra files like `files/save/fheroes2.bin` as well as restart PC :)

**Comment by shprotru** [comment]
Can't understand, may be while I switching between branches my config file gone. Checked again, now sounds work fine.
