### ISSUE TITLE
Castle Construction screen, quantity of resources is not updated when construction takes place after changing castle with the right left arrows at the bottom of the screen

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#9020]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the quantity of resources is not updated when construction takes place after changing castle with the right left arrows at the bottom of the screen.

In fheroes2:

https://github.com/user-attachments/assets/e7312535-b1fa-4bf9-b3b1-26eff648f8fd

### Save file

Here is the save file:
[Before market no update 01.zip](https://github.com/user-attachments/files/16487516/Before.market.no.update.01.zip)

**Comment by oleg-derevenetz** [comment]
Regression after #8358.
