### ISSUE TITLE
The screen doesn't move smoothly during AI hero turn

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#903]
Notice that during AI hero move the screen doesn't smoothly move like it is done for human's hero turn.

**Comment by ihhub** [comment]
Hi @shprotru , could you please take a look into this issue? I think you know the place of code where it's needed to be fixed as you changed there some time ago. Basically, we need to make the same logic as it's done for human-controller hero.

**Comment by shprotru** [comment]
Hi @ihhub! Understand, will make attempt to look this at the end of a day.

**Comment by ihhub** [comment]
@shprotru thanks a lot! As usual if you need any help please reach me ;)

**Comment by shprotru** [comment]
Trying to understand code, see `GetVisibleTileROI` how do I understand `ROI` abbreviation? Going deeper `_windowROI`, see comment `visible to draw area of World Map in pixels`, but how this could turn into a `ROI`?
Am I correctly done it? Can't be sure, may be before `I.Redraw( REDRAW_GAMEAREA );` possible missed call for `Interface::Basic::Get().RedrawFocus();`

**Comment by ihhub** [comment]
Hi @shprotru , ROI stands for region of interest in image processing/computer vision/computer graphics.
