### ISSUE TITLE
Main menu, resolution selection window is missing pop up info

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#9034]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

![image](https://github.com/user-attachments/assets/5599e2a6-72f6-42de-bf01-29d14aa563b2)

### Describe the possible solution

It would be great to add info window for multiplied resolutions (x2.0, x1.8. x3.0 etc) so players could understand the purpose of proposed options.

**Comment by ihhub** [comment]
Hi @zenseii , would you mind to propose the most appropriate dialog's message for this issue?
