### ISSUE TITLE
Castle screen, additional mage guild level construction issue

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#9039]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Second level guild appears out of empty space.

https://github.com/user-attachments/assets/75172798-f44b-4eac-8315-b1989a9dfbfc

Initially, the second floor should appear over the existing 1st level guild image.

### Save file

None.

**Comment by oleg-derevenetz** [comment]
Most likely a regression after #9026. I'll take a look later today.
