### ISSUE TITLE
AI doesn't protect a castle despite having troops there

### ISSUE THREAD

**Issue by kitovyj** [ihhub/fheroes2#9044]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

The yellow doesn't protect 'Big Oak' from Roxana despite having troops to buy there (campaign map). 

### Save file

[doesnt protect.zip](https://github.com/user-attachments/files/16591890/doesnt.protect.zip)

### Additional info

In "updateIndividualPriorityForCastle" _pathfinder.getDistance returns 0 for Roxana for some reason.

**Comment by oleg-derevenetz** [comment]
> In "updateIndividualPriorityForCastle" _pathfinder.getDistance returns 0 for Roxana for some reason.

The reason here is obvious: Big Oak's entry is invisible for red player (it's hidden in the fog), that's why pathfinder is not able to pave a path here from Roxana to this castle's entry.

**Comment by kitovyj** [comment]
> > In "updateIndividualPriorityForCastle" _pathfinder.getDistance returns 0 for Roxana for some reason.
> 
> The reason here is obvious: Big Oak's entry is invisible for red player (it's hidden in the fog), that's why pathfinder is not able to pave a path here from Roxana to this castle's entry.

Ahh, so that is partially the side effect of the fact that partially invisible objects are completely invisible. However even if a castle was completely invisible to the red player such logic is a bit unsafe. If a hero is standing just a few tiles away from a castle then the castle is definitely is in danger despite being not yet visible to the hero.

**Comment by kitovyj** [comment]
Recently I noticed that it is quite easy to take enemy castle while doing fog discovery. The have no protection - AI doesn't care about the hero approaching because I don't see the castle yet.

**Comment by oleg-derevenetz** [comment]
> Ahh, so that is partially a side effect of the fact that partially invisible objects are completely invisible.

Let's say that these are different, albeit partially interdependent problems. A partially visible castle is not a reason for the AI to be able to plot a route to its (invisible) entrance (because a human player wouldn't be able to do that either). This can only be a reason to conduct additional fog discovery in this direction.

> However even if a castle was completely invisible to the red player such logic is a bit unsafe.

Yes, therefore it is better to plot such a route from the castle owner's point of view, who sees both the castle and the enemy army at the same time.
