### ISSUE TITLE
Adventure map, shifting of the adventure map when casting the dimension door spell

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#9084]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Sometimes I have this problem of the adventure map shifting when casting the dimension door spell, and I've also seen it in let's play videos, but I haven't been able to reproduce it in a consistent way.
I'm opening this issue to point out the problem and to serve as a reminder on the subject.

You can observe the problem here:
https://youtu.be/Ca5bbwKArOQ?t=191

### Save file

See the video above, the bug is not easily reproducible.

**Comment by HubKing** [comment]
I have the same problem. Very annoying.

**Comment by oleg-derevenetz** [comment]
If someone is able to more or less reliably reproduce this behavior, then write how exactly. I haven't been able to do it yet (i.e. at all, I don't remember seeng it even occasionally). I tried both using only the mouse and using the hotkey to open the Spell Book, in different screen resolutions (both when DD area covers the entire screen and the part of the screen), no luck so far.

**Comment by HubKing** [comment]
It starts to happen randomly, but once it happens, it keeps happens until I restart the game. If I play a "standard game" and it gets long (100+ turns), it always happens. I don't know the exact condition, so maybe you need to see the code for any potential bug.

**Comment by HubKing** [comment]
> > It starts to happen randomly, but once it happens, it keeps happens until I restart the game. If I play a "standard game" and it gets long (100+ turns), it always happens. I don't know the exact condition, so maybe you need to see the code for any potential bug.
> 
> Could you please describe your setup? Presumably Windows. Which version? Do you have software cursor on? What are your display settings for the app? What gpu do you have?

Software cursor (otherwise, it's too small), 960 * 540, vsync on, 1080p monitor at 120% scaling, flatpak.

Operating System: EndeavourOS 
KDE Plasma Version: 6.1.4
KDE Frameworks Version: 6.5.0
Qt Version: 6.7.2
Kernel Version: 6.10.7-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i3-7100U CPU @ 2.40GHz
Memory: 7.7 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 620

**Comment by oleg-derevenetz** [comment]
> The issue looks like a duplicate of my old issue:
https://github.com/ihhub/fheroes2/issues/6347
To reproduce the screen jump you simply need to make several left mouse clicks.

It is not surprising that I couldn't reproduce this. I would never have guessed to hold down the left mouse button during the teleportation :) I'm 99% sure that this action is regarded as an attempt to scroll the game area via dragging.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
> It is not surprising that I couldn't reproduce this. I would never have guessed to hold down the left mouse button during the teleportation :) I'm 99% sure that this action is regarded as an attempt to scroll the game area via dragging.

It happens quite often on my side. I suffer from this screen jump in a case I'm just clicking on the adventure map right before teleportation animation is finished. So nice that you've fixed this issue!

**Comment by oleg-derevenetz** [comment]
> I suffer from this screen jump in a case I'm just clicking on the adventure map right before teleportation animation is finished.

- Doctor, when I do this, it hurts here.
- Don't do this.

**Comment by Branikolog** [comment]
@oleg-derevenetz 

😄 

> > I suffer from this screen jump in a case I'm just clicking on the adventure map right before teleportation animation is finished.
> 
> * Doctor, when I do this, it hurts here.
> * Don't do this.

It's just a matter of playstyle. Teleportation animation is not instant and I just click too early being impatient. :)
