### ISSUE TITLE
Hourglass is refilling few times during AI move

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#909]
Just make AI makes its move and notice that Hourglass which represents the progress of AI movement jumps multiple times.

**Comment by idshibanov** [comment]
Basically hourglass is re-running for each hero separately. I believe OG has the same bug.

I have this fixed in the new AI code already, but it's too early to push in.

**Comment by idshibanov** [comment]
Fixed as of 0.8.2.
