### ISSUE TITLE
Remove unused functions

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#91]
In `src/fheroes2/heroes/heroes.h` and `src/fheroes2/heroes/heroes.cpp` files we have these functions:
```cpp
    int			GetAttack(void) const;
    int			GetDefense(void) const;
    int			GetPower(void) const;
    int			GetKnowledge(void) const;
```
which inside call these functions:
```cpp
    int			GetAttack(std::string*) const;
    int			GetDefense(std::string*) const;
    int			GetPower(std::string*) const;
    int			GetKnowledge(std::string*) const;
```
we see no point to have first bunch of functions as we can simply set default value for second bunch of functions as `NULL`.

**Comment by ihhub** [comment]
@CruxBox sure! Please go ahead.

**Comment by CruxBox** [comment]
Also, have you made any tests?

**Comment by ihhub** [comment]
No. Currently this project doesn't have any tests but it should have.

**Comment by ihhub** [comment]
Closing this issue as it is invalid (I missed class inheritance).
