### ISSUE TITLE
Increase the size of hero and castle lists for high resolutions

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#910]
Run the game in high resolution, for example, in 1920 x 1080 pixels:
![image](https://user-images.githubusercontent.com/19829520/85946634-4569d800-b978-11ea-936b-4d8c54bb1b54.png)

Please notice that the size of hero and castle lists are fixed but there is enough space to make them bigger avoiding useless scrolling.

**Comment by idshibanov** [comment]
@ihhub I think we should definitely do it. There's couple things to consider here:

1. Keep in mind possible support for global scaling. On modern, high resolutions (such as this screenshot) UI can feel very small and tiring for the eyes to look at. Adding plain scaling option (x1.5 or x2) is crucial for old games. All of this means is that when determining UI layout we should account for both scale and target window resolution.
2. I would also like to increase the size of status window (that can go in a separate ticket). It will help to unclutter unit and resource list. Then we have to decide how much of the free space goes to status window and how much is dedicated to hero/castle list.

**Comment by ihhub** [comment]
I think we can close it. After all the game icons are too small on high resolutions. We should increase the size of icons than adding more.
