### ISSUE TITLE
Crash during AI turn due to unknown object

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#9123]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Reported on discord. Using public 1.1.2 version 

Load the save file and end the turn. An assertion will trigger.

![Schermafbeelding_2024-09-21_225841](https://github.com/user-attachments/assets/3bc0c252-9404-408a-8a93-12e3247794d1)

### Save file

[584f9408-1634-4945-94dd-c1c26d959b70.zip](https://github.com/user-attachments/files/17088790/584f9408-1634-4945-94dd-c1c26d959b70.zip)

**Comment by Districh-ru** [comment]
This save has a bug: two near standing boats have the same UID == 3, so they both are removed by the Summon Boat spell:
```
22.09.2024 12:53:24: [DBG_DEVEL]        Interface::AdventureMap::mouseCursorAreaPressRight:
******* Tile info *******
Tile index      : 20246, point: (86, 140)
MP2 object type : 171 (Boat)
UID             : 3
ICN object type : 6 (BOAT32.ICN)
image index     : 27
layer type      : 0 - Object layer
is shadow       : no
region          : 46
ground          : Ocean (isRoad: 0)
ground img index: 8, image flags: 4
passable from   : center, top, top-right, right, bottom-right, bottom, bottom-left, left, top-left
metadata value 1: 0
metadata value 2: 0
metadata value 3: 0
boat owner color: Green
--- Extra information ---
*************************

22.09.2024 12:53:25: [DBG_DEVEL]        Interface::AdventureMap::mouseCursorAreaPressRight:
******* Tile info *******
Tile index      : 20390, point: (86, 141)
MP2 object type : 171 (Boat)
UID             : 3
ICN object type : 6 (BOAT32.ICN)
image index     : 27
layer type      : 0 - Object layer
is shadow       : no
region          : 46
ground          : Ocean (isRoad: 0)
ground img index: 9, image flags: 4
passable from   : center, top, top-right, right, bottom-right, bottom, bottom-left, left, top-left
metadata value 1: 0
metadata value 2: 0
metadata value 3: 0
boat owner color: Yellow
--- Extra information ---
*************************
```

But the upper boat (which is now removed by UID while removing the lower one) is still in the `_mapActionObjects` vector.

Interesting, how it could happen...

**Comment by Districh-ru** [comment]
I found the cause of the issue: the `objectCounter` for the UID is set to 0 by default when the engine is started.
When we load a game it is not restored to its state when the game was saved. So then you can get ID that is already present on some tile.
Unluckily in the attached game it happened for the nearby boats.
