### ISSUE TITLE
Cannot load .fh2 map

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#9172]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

The engine is failed to load the map.
It's from a discord map-sharing section.

### Save file

[Crowns of Eldoria.zip](https://github.com/user-attachments/files/17267531/Crowns.of.Eldoria.zip)

**Comment by Districh-ru** [comment]
Hi, @Branikolog, this bug appears in v1.1.2 release and it is already fixed in `master` branch probably by this PR: https://github.com/ihhub/fheroes2/pull/9134.
