### ISSUE TITLE
When picking up a floating chest from land, the game crashes

### ISSUE THREAD

**Issue by zminin** [ihhub/fheroes2#9184]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In more than one game, when pickup up a floating xp/gold chest, the game crashes.

### Save file

[save file](https://drive.google.com/file/d/11C11pEADActNIZJqodtgi7an61UYkpi2/view?usp=sharing)
![Captură de ecran 2024-10-12 120156](https://github.com/user-attachments/assets/68a95d45-a4c5-4ca5-847f-889e62831c6d)

![Screen 2024-10-12 120044](https://github.com/user-attachments/assets/3dcc934f-ce0e-47e8-ba90-cd113a2dfb2e)

**Comment by ihhub** [comment]
This map is hacked by a map maker. This is not a Treasure Chest but a Sea Chest and the engine expected this. This object cannot have such a name.

@zminin , where did you get this map from?

**Comment by oleg-derevenetz** [comment]
AFAIK you cannot place Sea Chest on land using standard SW/PoL editor in a regular way (except for using some hacks maybe). This map looks invalid.

**Comment by ihhub** [comment]
@oleg-derevenetz , even then the object should be named as Sea Chest, not Treasure Chest. A type of object doesn't change the mentioned by you hack.
