### ISSUE TITLE
Source code is not compileable - WC_ERR_INVALID_CHARS is not defined

### ISSUE THREAD

**Issue by GeorgeK1ng** [ihhub/fheroes2#9187]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

I just downloaded source as zip, downloaded prereqs and opened in VS2019. It fails on WC_ERR_INVALID_CHARS in system.cpp.
Can be solved by adding #define WC_ERR_INVALID_CHARS      0x00000080  // error for invalid chars, after #define WIN32_LEAN_AND_MEAN

Or #define _WIN32_WINNT 0x0600. I quess better is just to stick with define WC_ERR_INVALID_CHARS only.

Not sure why this happends on mine side. Adding one more define fixed it.

### Save file

No save file

**Comment by oleg-derevenetz** [comment]
`WC_ERR_INVALID_CHARS` is available since Windows Vista only. If you are trying to build on/for WinXP, it will be missing, but fheroes2 is not targeted for WinXP anyway.

**Comment by GeorgeK1ng** [comment]
I just downloaded source, opened vcproj and tried to build it. Nothing more. Realized that issue and added needed define. And then I could build it. I'm on Windows 10 x64 19041.

**Comment by oleg-derevenetz** [comment]
> I just downloaded source, opened vcproj and tried to build it. Nothing more.

That's what I do on a daily basis, and so does the GitHub CI. If this define is not present, then there is some issue with your SDK. As I already said, this define should be there if target platform is Windows Vista+. It is present in SDK headers and shouldn't be defined by hand.

**Comment by GeorgeK1ng** [comment]
What SDK do you have installed? And how looks when you open project property?

Also much more cleaner fix should be 
**#if !defined WC_ERR_INVALID_CHARS 
#define WC_ERR_INVALID_CHARS 0x00000080 // error for invalid chars
#endif**

And of course I grabbed that define from winnls.h to solve it. No idea why it happeds here in my Visual Studio 2019 v16.11.38

![image](https://github.com/user-attachments/assets/cd868c5b-fda1-4c5f-9224-99be4f055a1a)

![image](https://github.com/user-attachments/assets/0aa30139-93f7-4239-a631-ec06798ccc59)

**Comment by oleg-derevenetz** [comment]
> Also much more cleaner fix should be
#if !defined WC_ERR_INVALID_CHARS
#define WC_ERR_INVALID_CHARS 0x00000080 // error for invalid chars
#endif

No. Please don't suggest to define/redefine the macro symbols that should be defined by Windows headers. This is not a proper way to go.

Availability of this symbol depends on `WINVER` value (file `WinNls.h` from Windows SDK):

```cpp
#if (WINVER >= 0x0600)
#define WC_ERR_INVALID_CHARS      0x00000080  // error for invalid chars
#endif
```

On my installation `WINVER` is defined in the `sdkddkver.h` header file (Windows SDK 10.0.19041.0):

```cpp
#ifndef WINVER
#ifdef _WIN32_WINNT
// set WINVER based on _WIN32_WINNT
#define WINVER          _WIN32_WINNT
#else
#define WINVER          0x0A00
#endif
#endif
```

So Windows 10 SDK sets it to `0x0A00` (Windows 10) by default, which is definitely more than `0x0600` (Windows Vista), but if it is already defined, then it will not be redefined. It looks like you defined the `WINVER` or `_WIN32_WINNT` somewhere, but I have no idea where. As I understand it, you are a big fan of Windows XP (#6002, #6007), perhaps this has something to do with it.

**Comment by GeorgeK1ng** [comment]
Damn, thats true, and you found that issue, I see I have modded sdkddkver.h to 0x0501.. 

Closing issue, caused by me.
