### ISSUE TITLE
Game crashes during AI turn

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#9214]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

The app closes during the AI turn. No assertion is triggered.

https://github.com/user-attachments/assets/758146fa-4d8c-42cf-8183-3e12044355be

### Save file

[Lattice_work_34.zip](https://github.com/user-attachments/files/17441486/Lattice_work_34.zip)

**Comment by oleg-derevenetz** [comment]
> I suppose this could be the known case about invalid boats/tiles? https://github.com/ihhub/fheroes2/issues/9141

Yes, sort of. Crash is happens here:

https://github.com/ihhub/fheroes2/blob/fcd24e9ce6bce35e3bd07e359182b27cf6ec0c2f/src/fheroes2/world/world.cpp#L825-L842

When boat is removed from this tile after the Summon Boat spell, the object type on this tile becomes `OBJ_WHIRLPOOL`, so the check at line 827 succeeds. But the `_imageIndex` on the tile is now wrong (255, while whirlpool tiles have images with indexes 202, 206, 210, 214, 218 and 222), so `_allWhirlpools` doesn't have it, and `at()` at line 832 throws an exception. We need to somehow "restore" whirlpools properly in such cases.

> However the hero who's planning their move is here:

It doesn't matter. AI pathfinder works globally, so it evaluates any tile that is available to a certain hero in principle by any means, even if this hero should perform some complex chain of actions to get there (e.g. move to some distant tile (even if it will take a few days), then summon a boat, then board it, then move to a Whirlpool on a next day or later, etc, etc).
