### ISSUE TITLE
Demo version is no more available 

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#9220]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

The script cannot download demo currently:
![image](https://github.com/user-attachments/assets/72f34165-3bd5-4edf-9772-6d768b3d832c)

### Describe the possible solution

Need to find another link for the demo.

**Comment by ihhub** [comment]
This is a huge problem for many. Therefore, marking it as high priority.

internet archive website was hacked recently.

**Comment by oleg-derevenetz** [comment]
According to the error message text, this is a temporary issue.

**Comment by oleg-derevenetz** [comment]
Technically, we can place this archive on our own fheroes2 website (on the GitHub hosting) - in our `docs` folder.

**Comment by oleg-derevenetz** [comment]
Here is the full `license.txt` text from the demo ZIP archive:

```
HEROES OF MIGHT AND MAGIC(tm) II 

(1) 10 business day hold on all personal checks.  
Please allow 4-6 weeks for delivery.  Special offers 
such as this are subject to cancellation without warning.

(2) Feel free to give copies of this demonstration version 
of "Heroes of Might and Magic II" (the "3DO Software Program")
to your friends, as long as you don't sell it.

(3) The 3DO Software Program recorded on the compact disc is 
PROVIDED on an "as is" basis, without any warranty or condition
of any kind, and 3DO shall not be liable for any losses or damages 
of any kind or nature resulting from the use of or inability to 
use such program.

(4) 3DO neither assumes nor authorizes any other person or 
entity to assume for 3DO (or any related or affiliated entity) 
any other liability in connection with this 3DO Software Program.  
IN NO EVENT WILL 3DO BE LIABLE FOR ANY INCIDENTAL, 
CONSEQUENTIAL (INCLUDING LOSS OF PROFITS), OR 
SPECIAL DAMAGES OR ANY LOSS OF DATA, TO YOU OR 
TO ANY THIRD PARTY, RESULTING FROM THE POSSESSION, 
USE OF OR INABILITY TO USE THIS 3DO SOFTWARE PRODUCT, 
EVEN IF 3DO HAS BEEN ADVISED OF THE POSSIBILITY OF 
SUCH DAMAGES OR LOSS.
```

**Comment by oleg-derevenetz** [comment]
However, this license is not compatible with GPL, so we need some separate repo for it, we cannot place it into fheroes2 repo.

**Comment by ihhub** [comment]
Briefly from the license we can distribute it. I can see a solution to this overall problem as the following:
1. Create a separate repo under fheroes2 organization within GitHub.
2. Put there an archive, possible sh256 sum and this license file to emphasise the license.
3. Add extra logic to the scripts as GitHub uses URL redirection.
4. Add extra logic for the scrips and fh2toolset in case if the link is unreachable to display more meaningful message to users.

@oleg-derevenetz , what are your thoughts about it?

**Comment by ihhub** [comment]
I also suggest to wait 1-2 days since we still need to retest everything after merging #9217.

**Comment by oleg-derevenetz** [comment]
> 1. Create a separate repo under fheroes2 organization within GitHub.

Yes.

> 2. Put there an archive, possible sh256 sum and this license file to emphasise the license.

We can put this archive and LICENSE, but there is no need to put sha256 sum here. This checksum should be verified by our scripts, and it is already "baked in" these scripts and it shouldn't change after the URL change.

> 3. Add extra logic to the scripts as GitHub uses URL redirection.

It may not be necessary, but it will only be enough to change the URL. We'll have to look at it.

> 4. Add extra logic for the scrips and fh2toolset in case if the link is unreachable to display more meaningful message to users.

I believe that "more meaningful message" is only makes sense if users are able to somehow fix this by themselves. In this case, they cannot :) On the other hand, HTTP error message, which is currently reported, is much more meaningful for us than some "user-friendly", but "generic" message intended for users. All that users can do is to take the screenshot and report that error to us, and in this case exact HTTP error message is more useful.

**Comment by ihhub** [comment]
1.1.3 release is set on 23rd October. We can monitor the situation for maximum 2 days and then decide what to do next.

**Comment by oleg-derevenetz** [comment]
It looks like archive.org is back and HoMM2 demo archive is available again.

**Comment by ihhub** [comment]
Yay!

**Comment by oleg-derevenetz** [comment]
> I'm not sure it's available.

At the moment it is not. Apparently, the archive.org recovery is still WIP, but it worked recently. Anyway, this is a temporary issue, and not so that this archive will never be available on the archive.org website.
