### ISSUE TITLE
Game doesn't stretch over whole screen on some resolutions

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#923]
If I run game (ex:1024x576, or 800x576) fullscreen it doesn't fit the screen.
![P00629-154258(1)](https://user-images.githubusercontent.com/55348946/86009575-0e043580-ba23-11ea-970c-8620d7069c0d.jpg)
Also, after switching (Alt+Tab) game return to fullscreen in next state:
(also surrounded by black frames from right and left (prtscrn does not catch this aspect unfortunately))
![state](https://user-images.githubusercontent.com/55348946/86010190-ba461c00-ba23-11ea-8a14-338096bcbe31.jpg)

**Comment by ihhub** [comment]
Closing this issue as we made needed changes for fullscreen resolutions recently.
