### ISSUE TITLE
User-reported crash with save file

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#9254]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [ ] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

A user from the Discord of KhelbensCoinTV provided this save file and said that the latest public release build crashes when ending the turn. 

The game was started on an older unspecified build, although recent enough that the save file was still compatible with latest public.

I haven't had time to check it and I won't have time to look into it further myself these next days so I'm sharing the file here in case someone else does.

### Save file

[PureLand Crash.zip](https://github.com/user-attachments/files/17624690/PureLand.Crash.zip)

**Comment by ihhub** [comment]
This happens during the battle. In method `int32_t Battle::Unit::evaluateThreatForUnit( const Unit & defender ) const` caused by `assert( distance > 0 );`.

https://github.com/user-attachments/assets/685bca5d-f6ad-4488-a283-cb75b906c816

**Comment by ihhub** [comment]
The change is related to Hypnotize spell in #8341.

Hi @oleg-derevenetz , would you mind please to take a look at this issue?

**Comment by oleg-derevenetz** [comment]
> The change is related to Hypnotize spell in https://github.com/ihhub/fheroes2/pull/8341.

Not quite. It happens because `optimalAttackValue()` didn't take into account the case when the attacking unit with the `ALL_ADJACENT_CELL_MELEE_ATTACK` ability changed sides. It's just that before #8341, AI was relatively dumb in relation to Hypnotize spell usage.
