### ISSUE TITLE
Sound Font Used in Midi Music.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [ihhub/fheroes2#9304]
### Your question

How do I control what Sound Fonts are used in the Midi Music?

**Comment by oleg-derevenetz** [comment]
It depends on MIDI backend used by SDL_mixer on your OS and how exactly this backend has been built. It may even be impossible at all.

**Comment by Zombie-Ryushu** [comment]
Can you offer a configuration option to use Timidity++ or FluidSynth?

**Comment by ihhub** [comment]
I am closing this issue as this is beyond our project's scope.
