### ISSUE TITLE
AI lands from ship to a wrong place that causes hero's sprites glitching and disappearing

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#931]
AI lands to the place at the beach he cannot reach. No hero appears after landing.
![Boat1](https://user-images.githubusercontent.com/55348946/86133982-bb457f00-baf1-11ea-8041-be0fd4ca3244.jpg)
![Boat12](https://user-images.githubusercontent.com/55348946/86133988-be406f80-baf1-11ea-847d-5e2d27c40436.jpg)
My hero can even enter that boat:
![Boat123](https://user-images.githubusercontent.com/55348946/86134592-7ff78000-baf2-11ea-8fd3-71eefc500ffb.jpg)
But next AI turn boat disappears and enemy hero runs away:
![Boat1234](https://user-images.githubusercontent.com/55348946/86134678-98679a80-baf2-11ea-8cc7-0019d553a7ec.jpg)
My hero stands the same place invisible and without an ability to move anywhere.

**Comment by idshibanov** [comment]
Not surprised it happened, I already noticed that there's no validation when AI moves, so they actually can move on top of each other if there's issues with pathfinding. This issue will require two bugfixes: hero move validation and possibly AI boat unboarding logic update.

**Comment by ihhub** [comment]
This issue came along with recent changes for hero smooth movement.
