### ISSUE TITLE
Assertion on loading the map after saved another one

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#9353]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

I'm not sure, if this the problem with map versioning, but after I **save** changes in one particular map I cannot load some other maps.
If I just save map with no changes - no assertion.
If I just save changes and reload the same map - no assertion.
Some maps could be loaded with no assertion, but some fail.
Sometimes I make terrain changes and loading is fine. But in some other cases - assertion occurs.
Here's the way it could be reproduced in the most cases.

https://github.com/user-attachments/assets/4b960e3e-151a-4b63-a0d1-51683d41af2f

Edit: the assertion seem to occur more frequently, when I use only keyboard for navigating in the UI.

### Save file

[Assertoin maps.zip](https://github.com/user-attachments/files/18196948/Assertoin.maps.zip)

**Comment by ihhub** [comment]
Hi @Branikolog , these maps don't trigger any assertions to me. Are you sure that you are using the latest version of the engine?

**Comment by Branikolog** [comment]
Hi, @ihhub !

> Hi @Branikolog , these maps don't trigger any assertions to me. Are you sure that you are using the latest version of the engine?

Sure. How could I edit shrines then? :) I've installed it several hours ago.
Try repeating all actions from my video, including using keyboard instead of mouse. Try also several times in a row...

**Comment by Branikolog** [comment]
After several tests I think the problem is in the "Map 01". After editing some values and saving it an attempt to load any other map can fail.
