### ISSUE TITLE
Disappearing monster on the map is shifted before animation

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#936]
A monster after being attacked and defeated has a different location on the map. Here is a screenshot of the monster before being attacked:
![image](https://user-images.githubusercontent.com/19829520/86203816-84767400-bb98-11ea-8b28-119982de5316.png)

and this is its position during fading animation:
![image](https://user-images.githubusercontent.com/19829520/86203842-92c49000-bb98-11ea-8cac-b3a8c0ee99e1.png)

There is obviously a shift for a monster which we need to fix.

**Comment by idshibanov** [comment]
Probably we need to apply monster offset in `GameArea::Redraw` RemoveAnimation part.

**Comment by idshibanov** [comment]
That's because monsters on the map are drawn using ICN::MINIMON instead of ICN::MONS32 used in the UI. Offsets and sprite sizes are different so they would never match.
