### ISSUE TITLE
Magic Book, Spell information windows, cost in spell points is not correct when the hero has artifact that reduces the cost of spells

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#9365]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the cost in spell points is not correct in the Spell information windows (the reduction is not applied) when the hero has artifact that reduces the cost of spells.
This concerns:
- Evil Eye with curse spells (Curse and Mass Curse).
- Skullcap with mind influencing spells (Blind, Paralyze, Berserker and Hypnotize).
- Snake-Ring with Bless spells (Bless and Mass Bless).
- Elemental Ring with summon elemental spells (Summon Earth Elemental, Summon Air Elemental, Summon Fire Elemental and Summon Water Elemental).

In fheroes2:
![Info cost spell 001](https://github.com/user-attachments/assets/d33a4561-945c-47d8-b203-0f987ccaed21)

![Info cost spell 002](https://github.com/user-attachments/assets/5a98dbb5-8742-4856-962f-96130ba66671)

![Info cost spell 003](https://github.com/user-attachments/assets/89289a8e-c187-4795-abb1-fa52e9ae9a14)

![Info cost spell 004](https://github.com/user-attachments/assets/358e4258-8928-4b36-948f-747febf6ae45)

![Info cost spell 005](https://github.com/user-attachments/assets/91e88065-e8bd-4bc6-b7aa-16e14727c2f5)

### Save file

Here is the test scenario file:
[0 9894.zip](https://github.com/user-attachments/files/18222418/0.9894.zip)

### Additional info

Version 1.1.4 9347
Related closed issue: https://github.com/ihhub/fheroes2/issues/6838.

**Comment by oleg-derevenetz** [comment]
Regression after #7969.

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu  and @oleg-derevenetz 

If I'm not mistaken, such behavour was made on purpose so that the player can see the actual cost of the spell in his book and at the same time know how much mana the spell normally costs. This can be useful when the player wants to transfer (or get rid of an artifact that reduces the cost of the spell). You know, the Bless spell costs 3 mana without an artifact, but it is not so obvious to the player that with an artifact the spell only costs 1 mana. So I think it's a reminder of the default cost of the spell. 
The player, noticing the difference, is aware of the effect of the artifact.
There was a discussion about this somewhere in PR or issue a long time ago... Are you sure this needs to be fixed?

**Comment by oleg-derevenetz** [comment]
> There was a discussion about this somewhere in PR or issue a long time ago... Are you sure this needs to be fixed?

The current behavior was introduced in the very first commit of #7969 and I don't see any discussion or justification of this change in that PR.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Indeed, the current behaviour appeared within the PR you've mentioned. I bet I've discussed this behavior with someone before. I apologise for referring to the missing discussion. 
I've been used to this for a while now. There's no suprise for me, that values are different in the book and spell info window. 
From my point of view it is nice to give a player the reminder of the actual spell points requrement. 
If you think the current behaviour is misleading and looking like a bug - then proceed with fixing it. Maybe in future we can find a more proper way to warn the player about the changed spell requirements.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog let's wait for opinions of other team members on this matter. I proposed the PR that should change this behavior, but maybe it is not needed.

**Comment by ihhub** [comment]
Hi @oleg-derevenetz and @Branikolog , this is a regression and must be fixed.

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog and @oleg-derevenetz,

> Maybe in future we can find a more proper way to warn the player about the changed spell requirements.

Personally, I'd prefer a text that clearly indicates, for example:
"The Evil Eye artifact reduces the cost of casting this spell by half."
