### ISSUE TITLE
Boat always changes its direction to a certain state no matter how hero was landing.

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#939]
Boat always stays at this direction after hero landed.
![landing](https://user-images.githubusercontent.com/55348946/86238062-927ec180-bba5-11ea-8d2f-163fab913da2.jpg)

**Comment by idshibanov** [comment]
There's practically no ability to store boat direction right now, have to update map structures described in #1026 first to do this properly.

`AIToCoast` is the call to start.
