### ISSUE TITLE
Add monsters in High Score board

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#954]
Here is a look of our score board:
![image](https://user-images.githubusercontent.com/19829520/86526343-9f612500-bec5-11ea-9f52-dd327a6f19aa.png)

And this is how it should look:
![image](https://user-images.githubusercontent.com/19829520/86526346-af790480-bec5-11ea-8e9c-2f1c0919df08.png)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , do you know the formula for displaying creatures in this window?

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , do you know the formula for displaying creatures in this window?

**dahbk** did it!

It's not really a "formula", but the list of creature correspondence according to the number of days.

https://www.gog.com/forum/heroes_of_might_and_magic_series/homm2_rating_corresponding_creatures

I didn't check for all the scores, but it matches the scores I did.
I think that should be correct. :)

**Scenario.**

Days Monster:
0 Peasant
1 Peasant
2 Peasant
3 Peasant
4 Goblin
5 Goblin
6 Goblin
7 Goblin
8 Sprite
9 Sprite
10 Sprite
11 Sprite
12 Halfling
13 Halfling
14 Halfling
15 Halfling
16 Centaur
17 Centaur
18 Centaur
19 Centaur
20 Rogue
21 Rogue
22 Rogue
23 Rogue
24 Skeleton
25 Skeleton
26 Skeleton
27 Skeleton
28 Orc
29 Orc
30 Orc
31 Orc
32 Zombie
33 Zombie
34 Zombie
35 Zombie
36 Archer
37 Archer
38 Archer
39 Archer
40 Ranger
41 Ranger
42 Ranger
43 Ranger
44 Boar
45 Boar
46 Boar
47 Boar
48 Dwarf
49 Dwarf
50 Dwarf
51 Dwarf
52 Mutant zombie
53 Mutant zombie
54 Mutant zombie
55 Mutant zombie
56 Orc Chieftain
57 Orc Chieftain
58 Orc Chieftain
59 Orc Chieftain
60 Elf
61 Elf
62 Elf
63 Elf
64 Gargoyle
65 Gargoyle
66 Gargoyle
67 Gargoyle
68 Pikeman
69 Pikeman
70 Pikeman
71 Pikeman
72 Grand Elf
73 Grand Elf
74 Grand Elf
75 Grand Elf
76 Battle Dwarf
77 Battle Dwarf
78 Battle Dwarf
79 Battle Dwarf
80 Nomad
81 Nomad
82 Nomad
83 Nomad
84 Veteran Pikeman
85 Veteran Pikeman
86 Veteran Pikeman
87 Veteran Pikeman
88 Wolf
89 Wolf
90 Wolf
91 Wolf
92 Mummy
93 Mummy
94 Mummy
95 Mummy
96 Iron Golem
97 Iron Golem
98 Iron Golem
99 Iron Golem
100 Royal Mummy
101 Royal Mummy
102 Royal Mummy
103 Royal Mummy
104 Ogre
105 Ogre
106 Ogre
107 Ogre
108 Griffin
109 Griffin
110 Griffin
111 Griffin
112 Swordsman
113 Swordsman
114 Swordsman
115 Swordsman
116 Druid
117 Druid
118 Druid
119 Druid
120 Steel Golem
121 Steel Golem
122 Steel Golem
123 Steel Golem
124 Master Swordsman
125 Master Swordsman
126 Master Swordsman
127 Master Swordsman
128 Air Elemental
129 Air Elemental
130 Air Elemental
131 Air Elemental
132 Greater Druid
133 Greater Druid
134 Greater Druid
135 Fire Elemental
136 Fire Elemental
137 Fire Elemental
138 Ghost
139 Ghost
140 Ghost
141 Vampire
142 Vampire
143 Vampire
144 Water Elemental
145 Water Elemental
146 Water Elemental
147 Earth Elemental
148 Earth Elemental
149 Earth Elemental
150 Roc
151 Roc
152 Roc
153 Minotaur
154 Minotaur
155 Minotaur
156 Cavalry
157 Cavalry
158 Cavalry
159 Troll
160 Troll
161 Troll
162 Mage
163 Mage
164 Mage
165 Medusa
166 Medusa
167 Medusa
168 Lich
169 Lich
170 Lich
171 Ogre Lord
172 Ogre Lord
173 Ogre Lord
174 Minotaur King
175 Minotaur King
176 Minotaur King
177 Champion
178 Champion
179 Champion
180 War Troll
181 War Troll
182 War Troll
183 Vampire Lord
184 Vampire Lord
185 Vampire Lord
186 Archmage
187 Archmage
188 Archmage
189 Power Lich
190 Power Lich
191 Power Lich
192 Unicorn
193 Unicorn
194 Unicorn
195 Hydra
196 Hydra
197 Hydra
198 Paladin
199 Paladin
200 Paladin
201 Genie
202 Genie
203 Genie
204 Crusader
205 Crusader
206 Crusader
207 Cyclops
208 Cyclops
209 Cyclops
210 Giant
211 Giant
212 Giant
213 Phoenix
214 Phoenix
215 Phoenix
216 Bone Dragon
217 Bone Dragon
218 Bone Dragon
219 Green Dragon
220 Green Dragon
221 Green Dragon
222 Red Dragon
223 Red Dragon
224 Red Dragon
225 Titan
226 Titan
227 Titan
228 Black Dragon 

**Campaign.**

Days Monster:
0-300 Black Dragon
301-320 Titan
321-340 Red Dragon
341-360 Green Dragon
361-380 Bone Dragon
381-400 Phoenix
401-420 Giant
421-440 Cyclopse
441-460 Crusader
461-480 Genie
481-500 Paladin
501-520 Hydra
521-540 Unicorn
541-560 Power Lich
561-580 Archmage
581-600 Vampire Lord
601-620 War Troll
621-640 Champion
641-660 Minotaur King
661-680 Ogre Lord
681-700 Lich
701-720 Medusa
721-740 Mage
741-760 Troll
761-780 Cavalry
781-800 Minotaur
801-820 Roc
821-840 Earth Elemental
841-860 Water elemental
861-880 Vampire
881-900 Ghost
901-920 Fire Elemental
921-940 Greater druid
941-960 Air Elemental
961-980 Master Swordsman
981-1000 Steel Golem
1001-1100 Druid
1101-1200 Swordsman
1201-1300 Griffin
1301-1400 Ogre
1401-1500 Royal Mummy
1501-1600 Iron Golem
1601-1700 Mummy
1701-1800 Wolf
1801-1900 Veteran Pikeman
1901-2000 Nomad
2001-2200 Battle Dwarf
2201-2400 Grand Elf
2401-2600 Pikeman
2601-2800 Gargoyle
2801-3000 Elf
3001-3200 Orc Chieftain
3201-3400 Mutant Zombie
3401-3600 Dwarf
3601-3800 Boar
3801-4000 Ranger
4001-4200 Archer
4201-4400 Zombie
4401-4600 Orc
4601-4800 Skeleton
4801-5000 Rogue
5001-5200 Centaur
5201-5400 Halfling
5401-5600 Sprite
5601-5800 Goblin
5801-∞ Peasant

**Comment by LeHerosInconnu** [comment]
@ihhub.

Be careful that in the original game, the creature animations are not synchronized when there are several times the same creature in the high scores list. :)

In original game:

![2020-12-10 01-53-39_0-145](https://user-images.githubusercontent.com/43583994/101708291-3d68a500-3a8d-11eb-9e35-abece499d36f.gif)

**Comment by Arthusppp** [comment]
@LeHerosInconnu, what do you think above this? I have done few element position adjustments.

![image](https://user-images.githubusercontent.com/85434237/130371566-3be47c55-5ec0-438b-8b94-bfeaaa6e765b.png)

@ihhub @LeHerosInconnu about row no 8: the player name in the OG has 15 chars length, fheroes2 has 25 (at least the UI accepts 25 chars). How do you want to handle this? (make the player name 15 chars? truncate display, if longer than 15 chars? someting else?)

**Comment by LeHerosInconnu** [comment]
Hello @Arthusppp,

> @LeHerosInconnu, what do you think above this? I have done few element position adjustments.

Here are the spacings from the original game:

![Position scores 01](https://user-images.githubusercontent.com/43583994/130645870-99bc46f9-499c-4062-add6-6af1e7adfa34.png)

![Position scores 02](https://user-images.githubusercontent.com/43583994/130645856-8c5acb2f-0289-47f3-bdd0-b3806c354c3c.png)

Also the position of the creature sprite should be moved 1 pixel down and 6 pixels to the right.

> @ihhub @LeHerosInconnu about row no 8: the player name in the OG has 15 chars length, fheroes2 has 25 (at least the UI accepts 25 chars). How do you want to handle this? (make the player name 15 chars? truncate display, if longer than 15 chars? someting else?)

For my part, I think that the number of characters the player can enter for the player name should be limited so that the name can never be displayed too close to the scenario name or the campaign name.
