### ISSUE TITLE
Build with clang on Linux

### ISSUE THREAD

**Issue by shprotru** [ihhub/fheroes2#959]
Impossible to build with clang on Linux, possible reason is in guards usage

**Comment by ihhub** [comment]
Hi @shprotru, could you please explain the advantage to use cmake over make?

**Comment by shprotru** [comment]
Hi @ihhub I report not on cmake, but clang, a different compiler than default gcc, it helps to catch errors

**Comment by ihhub** [comment]
Ah, my apologies. We could embed a clang compilation into GitHub Actions

**Comment by shprotru** [comment]
This is mainly good feature for developers on their machines
