### ISSUE TITLE
Morale and luck animation should be shifted lower

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#975]
Currently morale and luck animation for units standing in the upper part of battlefield goes out of visible part of battlefield.
![Morale 1](https://user-images.githubusercontent.com/55348946/86594185-3f3eb180-bf9f-11ea-809a-6cf2eac9a311.jpg)

In the OG we can see whole animation:
![Morale](https://user-images.githubusercontent.com/55348946/86593285-9774b400-bf9d-11ea-817f-19ebfeff0789.jpg)

**Comment by Branikolog** [comment]
But what about luck animation?

**Comment by idshibanov** [comment]
> 
> But what about luck animation?

Will do. Forgot it had it's own function.
