### ISSUE TITLE
Some of the interface buttons should have "inactive" state

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#981]
While entering adventure options menu with a city being chosen in a list, we can see "Dig for the artifact" button being pressed, but not disabled.
![Dig](https://user-images.githubusercontent.com/55348946/86768754-b3885c00-c056-11ea-9bd8-6d20a1d63dd5.jpg)

**Comment by shprotru** [comment]
Hi @ihhub! inside [dialog_adventure.cpp](https://github.com/ihhub/fheroes2/blob/master/src/fheroes2/dialog/dialog_adventure.cpp#L60) I could see conditional call for `SetDisable`:
```
if ( !enabledig )
        buttonDig.SetDisable( true );
```
inside `SetDisable` I see [this](https://github.com/ihhub/fheroes2/blob/master/src/fheroes2/gui/button.cpp#L129) code:
```
if ( f )
        flags |= ( BTN_DISABLE | BTN_PRESSED );
    else
        flags &= ~( BTN_DISABLE | BTN_PRESSED );
```
I remember that you done `GetDisabledButtonSurface`, and have question: in OG it looks like a different image:
![Снимок экрана от 2020-07-10 00-27-01](https://user-images.githubusercontent.com/53114202/87092631-75e92600-c244-11ea-89cd-49136e0bd3c1.png)
See this things? Don't know how to call them, but seems they are gone in our version, @Branikolog do you mean this things?

**Comment by Branikolog** [comment]
Hello, @shprotru. Sorry, didn't see your question.
Yes. I've meant  these "flares".
The same we've already done in #806.

**Comment by Branikolog** [comment]
Can I add here boat purchase button?
![boat button](https://user-images.githubusercontent.com/55348946/87158707-d326bb00-c2c8-11ea-86c9-1babf0b90004.jpg)

**Comment by ihhub** [comment]
Hi @Branikolog and @shprotru , we just need to add this button to a list of ICN which are supported for disabled buttons. That's it. However, we must be sure that we don't bring side effects. I observed that for some buttons like OKAY we have black edge after for disabled buttons.

**Comment by Branikolog** [comment]
![Castle](https://user-images.githubusercontent.com/55348946/87160343-7ed10a80-c2cb-11ea-98b9-9e2de3656d81.jpg)

**Comment by ihhub** [comment]
We could rename this topic for all disabled buttons. As of now this issue is marked for 1.0 so we aren't going to fix it in the near future.

**Comment by Branikolog** [comment]
![hero](https://user-images.githubusercontent.com/55348946/87930473-d1ab7e80-ca90-11ea-8e53-3a43677f0126.jpg)

**Comment by ihhub** [comment]
Closing this issue as it's fixed in the new engine.
