### ISSUE TITLE
Retaliation delay is missing

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#983]
There is a small delay before attacked creature retaliates enemy in the OG.

**Comment by ihhub** [comment]
Hi @Branikolog , could you please describe the issue in greater details? I don't full understand it.

**Comment by Branikolog** [comment]
Hello, @ihhub.
Retaliation animation starts at the moment, attacking animation had finished. There is a small (~0.3sec) pause between these animations in the OG.

**Comment by ihhub** [comment]
Hi @Branikolog , could you please verify this issue? We had a missing static frame after wince animation not being displayed but not we show.

**Comment by Branikolog** [comment]
Hi, @ihhub.
It has become better, but I still feel, than in the OG pause takes a little bit more time before creature retaliates...
