### ISSUE TITLE
Diplomacy skill rate

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#987]
All creatures want to join hero with a diplomacy skill and strong enough army.
We should definitely reduce chance of joining.

**Comment by vincent-grosbois** [comment]
Are you sure the issue is still there?
In fheroes2 the quantity of monster to join is dependent on the skill level, AFAIK this is correct
The fact that a stack joins is not randomized: it depends on relative strength of army vs stack and some flags set for the stack itself. I'm not sure if it is different than the original game (I couldn't find any info on this)

**Comment by Branikolog** [comment]
Hi, @vincent-grosbois 
I've just checked. Issue is still on. While hero having Diplomacy skill (I've tested with expert one) Every creature offered me to join army. 95% with gold and 5% of creatures for free. I've attacked ~30 stacks.

**Comment by Branikolog** [comment]
@vincent-grosbois, my apologies for incorrect description. 
I've edited the first post.

**Comment by vincent-grosbois** [comment]
In that case, shouldn't we also edit the tags / milestone for this ? :) I mean, if we can confirm that the OG is working like this

**Comment by Branikolog** [comment]
@vincent-grosbois 
The problem is that in the original game if hero has no free space in his army, no-one would like join his army! But fheroes2 has a nice enhancement, where hero can re-arrange army during joining dialog. So this causes  joining dialog to appear constantly. And persistent battles after a refusal too.
I think we need either to allow creatures to run away after refusal (with a certain rate) or make not 100% of neutral creatures on a world map to join hero.
Or even (which I like more) two this together. As diplomacy was always overpowered in HoMM series.

**Comment by LeHerosInconnu** [comment]
@Branikolog and @vincent-grosbois.

> As diplomacy was always overpowered in HoMM series.

I don't think Diplomacy is too powerful in Heroes 2, it's just another way to recruit creatures.
The player must pay the cost of recruiting creatures, it is not free.
Diplomacy allows to recruit creatures "on the way", this is its advantage.
Also, I find that in Heroes 2, Diplomacy is restrictive to use, I plan to add an option that will allow easier use from the Basic level.

> In fheroes2 the quantity of monster to join is dependent on the skill level, AFAIK this is correct
> The fact that a stack joins is not randomized: it depends on relative strength of army vs stack and some flags set for the stack itself. I'm not sure if it is different than the original game (I couldn't find any info on this)

In the original game, certain troops of wandering creatures will always join the hero who attacks them, and this without special condition.

For other troops of wandering creatures, the hero's army power must be between two times and five times the power of the wandering troop for the wandering troop to join the hero if he has Diplomacy.

- If the hero refuses the proposal of the wandering troop to join his army, the wandering troop attacks.
- If the wandering troop could join the hero, but the player does not have the necessary amount of gold, the wandering troop attacks.
- If the wandering troop could join the hero, but the hero does not have a free slot in his army, the wandering troop attacks.
- If the hero's army power is less than twice the power of the wandering troop, the wandering troop attacks.
- If the hero's army power is more than five times the power of the wandering troop, the wandering troop flees.

> The problem is that in the original game if hero has no free space in his army, no-one would like join his army!

In the original game, in this case, the wandering troop attacks.

> But fheroes2 has a nice enhancement, where hero can re-arrange army during joining dialog. So this causes joining dialog to appear constantly. And persistent battles after a refusal too.

I really like this enhancement.
Here, with this enhancement, Diplomacy allows the wandering troop to be recruited even if there is no place in the hero's army.
If the hero does not make room, the wandering troop attacks.
This is what the wandering troop would have done anyway if the enhancement was not available.

> I think we need either to allow creatures to run away after refusal (with a certain rate)...

There may be an option whereby when a wandering troop offers to join the hero's army and the hero refuses (or does not make room in his army) the wandering troop disappears without a combat.

> ...or make not 100% of neutral creatures on a world map to join hero.

I think it would be better to keep the way the original game works, and not introduce a luck-related operation for Diplomacy or whatever into the game.
The game should be based on strategy and not on luck. :)

**Comment by Branikolog** [comment]
> In the original game, in this case, the wandering troop attacks.

> If the hero does not make room, the wandering troop attacks.
> This is what the wandering troop would have done anyway if the enhancement was not available.

In the OG, if player has no free space in army - none of the wandering creature would like to join.
In fheroes2 joining dialog is constantly appearing, which leads to infinite battles. While in the OG all neutral creatures run away.

We should find a solution no to fight each time with all joining creatures...

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

> > In the original game, in this case, the wandering troop attacks.
> 
> > If the hero does not make room, the wandering troop attacks.
> > This is what the wandering troop would have done anyway if the enhancement was not available.
> 
> In the OG, if player has no free space in army - none of the wandering creature would like to join.
> In fheroes2 joining dialog is constantly appearing, which leads to infinite battles. While in the OG all neutral creatures run away.
> 
> We should find a solution no to fight each time with all joining creatures...

In the original game, the wandering creatures join the hero with Diplomacy if the power of the hero's army is more than twice the power of the wandering creatures.
And the wandering creatures flee if the power of the hero's army is more than five times the power of the wandering creatures.

In the original game:
In the example, the group of 15 Trolls joins as soon as the power of the hero's army is greater than twice the power of the wandering creatures and there is a free slot.
![Army diplomacy attack fh2 001](https://user-images.githubusercontent.com/43583994/117547970-abac9600-b032-11eb-8d10-dc4c09fa4fd9.png)
![Army diplomacy attack fh2 002](https://user-images.githubusercontent.com/43583994/117547974-aea78680-b032-11eb-9b2b-9f50d09dd667.png)

In the example, with the same army, the group of 15 Trolls attacks the hero if there is no free slot.
![Army diplomacy attack fh2 003](https://user-images.githubusercontent.com/43583994/117547983-b6672b00-b032-11eb-9af4-18b6c47a4540.png)
![Army diplomacy attack fh2 004](https://user-images.githubusercontent.com/43583994/117547986-b9621b80-b032-11eb-85c5-4cb1b3698bcd.png)

In fheroes2, there is also a problem with the high value of the rallying range.
I have updated the corresponding issue: https://github.com/ihhub/fheroes2/issues/3336.

I think it's better to fix first this problem in fheroes2 before going further.

**Comment by Branikolog** [comment]
> In the original game, the wandering creatures join the hero with Diplomacy if the power of the hero's army is more than twice the power of the wandering creatures.
> And the wandering creatures flee if the power of the hero's army is more than five times the power of the wandering creatures.

![image](https://user-images.githubusercontent.com/55348946/123113769-7c69b100-d447-11eb-908f-1c4705a0b6a1.png)
At the original screenshot all wandering creatures (Dwarves and peasants) are willing to join hero army (In a case there's free slot), while hero's army is way much stronger.
And peasants are still attacking on refusal.
In a case there's no free space in hero's army - everyone flees. (Of course! 500 ghosts is a horrifying army!)
That's the behaviour I experienced in the original game.

Anyway, We're talking about fheroes2 now. Currently, wandering creatures are always willing to join hero's army (with certain army strength), like in original game they do in a case hero has free slots. Even in the original game hero can always dismiss some army and be quite sure, wandering creatures will join due to diplomacy rules. In the original game, in a case hero has no free slots - wandering creatures flee.
I think we should make as close to original, as we can. Hero should always be able to accept joining creatures (If strength conditions are satisfied), but in a case he refuses, engine should make another check of army's strength: If creatures a comparable to hero's army - they attack. If they are extremely weak - engine should initiate standard pursuing dialog window.

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

There is a bug in the original game, the rule "And the wandering creatures flee if the strength of the hero's army is more than five times the strength of the wandering creatures." does not always work correctly.
Look at the end of the original post in this thread: https://github.com/ihhub/fheroes2/issues/3336, there is also a save file to make tests.

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu.
Actually, I've tried so many times this skill at my test maps, but never noticed the behaviour you've described in the post above. Are you sure it is a bug? Could it be one more hidden condition applied that we don't know about?

**Comment by LeHerosInconnu** [comment]
@Branikolog.

If we stick to the rule "more than twice the power of the wandering creatures, more than five times the power of the wandering creatures", there is a bug in the original game.
Now maybe there is a hidden rule, but what is it? And why?

**Comment by LeHerosInconnu** [comment]
Hello @@Branikolog,

> @Branikolog.
> 
> If we stick to the rule "more than twice the power of the wandering creatures, more than five times the power of the wandering creatures", there is a bug in the original game. Now maybe there is a hidden rule, but what is it? And why?

In fact the restriction "if the strength of the army is more than five times the strength of the wandering creatures" is not required for Diplomacy in the original game.
If the player has the necessary gold and the hero has the Diplomacy skill, the wandering troops will always want to join the hero. :)
