### ISSUE TITLE
AI hero's sprite jumps a few pixels forward while moving more that one cell to the single direction

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#990]
I've noticed, that AI hero makes small jumps after horse had made one step, while moving to a single direction.

**Comment by ihhub** [comment]
Hi @Branikolog , could you please attach a save file for easier debugging of this problem?

**Comment by Branikolog** [comment]
Hi, @ihhub.
Here you are.
[AI moving.zip](https://github.com/ihhub/fheroes2/files/4894760/AI.moving.zip)
