### ISSUE TITLE
Ship Wreck bug

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#995]
While exploring ship wreck hero fights at empty battle field. A moment later we can see animation of hero being defeated. And the hero disappears.
![shipwreck1](https://user-images.githubusercontent.com/55348946/87043408-aa85bf00-c1fd-11ea-860f-44715a3661c5.jpg)
![shipwreck2](https://user-images.githubusercontent.com/55348946/87043417-ac4f8280-c1fd-11ea-814a-a219e4f3a25f.jpg)
![shipwreck3](https://user-images.githubusercontent.com/55348946/87043428-ae194600-c1fd-11ea-9550-8b30bf25ef4a.jpg)

**Comment by ihhub** [comment]
It's not a bug, it's a feature :)

@Branikolog, could you please attach a save file for this?

**Comment by Branikolog** [comment]
"Instant defeat" feature? )
[O_O.zip](https://github.com/ihhub/fheroes2/files/4897271/O_O.zip)
